### ISSUE TITLE
Compiling for/of to a plain index loop

### ISSUE THREAD

**Issue by marijnh** [swc-project/swc#1019]
**Describe the feature**

Bublé has a [`dangerousForOf`](https://buble.surge.sh/guide/#dangerous-transforms) switch that you can use when you know all `for`/`of` loops in a codebase are iterating over arrays. It'll compile such loops to a regular `for` that runs an index over the array, when possible. This can, for code where it is valid, obviously help generate a lot better output.

Would such an option potentially be in scope for this project, or does it sound too dodgy?

**Comment by Austaras** [comment]
This is already implemented in `loose` mode, which is, as the OP said, dangerous. Maybe we could move it to an assumption soon.

**Comment by Austaras** [comment]
This issue could be closed now
