### ISSUE TITLE
Some corner case

### ISSUE THREAD

**Issue by muzea** [swc-project/swc#102]
When I tried to compile lodash with swc, I found some problems.

```shell
ERROR in ./vendor/escape.js 2:8
Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
| var htmlEscapes = {
>         &: '&amp',
|         <: '&lt',
|         >: '&gt',
 @ ./src/lodash.js 43:0-38 294:16-22
 @ ./src/test.js
 @ multi ./src/test.js

ERROR in ./vendor/unescape.js 2:8
Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
| var htmlUnescapes = {
>         &amp;: '&',
|         &lt;: '<',
|         &gt;: '>',
 @ ./src/lodash.js 225:0-42 476:18-26
 @ ./src/test.js
 @ multi ./src/test.js

ERROR in ./vendor/.internal/Stack.js 46:32
Module parse failed: Unexpected token (46:32)
You may need an appropriate loader to handle this file type.
|         }, {
|                 key: 'delete',
>                 value: function delete(key) {
|                     var data = this.__data__;
|                     var result = data['delete'](key);
 @ ./vendor/.internal/baseClone.js 4:0-31 139:26-31
 @ ./vendor/clone.js
 @ ./src/lodash.js
 @ ./src/test.js
 @ multi ./src/test.js

ERROR in ./vendor/.internal/MapCache.js 58:32
Module parse failed: Unexpected token (58:32)
You may need an appropriate loader to handle this file type.
|         }, {
|                 key: 'delete',
>                 value: function delete(key) {
|                     var result = getMapData(this, key)['delete'](key);
|                     this.size -= result ? 1 : 0;
 @ ./vendor/.internal/SetCache.js 22:0-37 29:28-36
 @ ./vendor/.internal/baseDifference.js
 @ ./vendor/difference.js
 @ ./src/lodash.js
 @ ./src/test.js
 @ multi ./src/test.js
```

About reserved words, babel will add an underscore to the front, like

```js
{
    key: 'delete',
    value: function _delete(key) {
      var result = getMapData(this, key)['delete'](key);
      this.size -= result ? 1 : 0;
      return result;
}
```

This project is very cool and I am looking forward to the plugin system.

**Comment by kdy1** [comment]
Thank you very much for trying swc.
The `es3::reserved_word` pass is not implemented yet, so I guess it's expected result.
I'll fix it soon.

**Comment by muzea** [comment]
If just test, it doesn't seem to have much code to write a webpack loader.

```js
const { transform } = require('swc')

module.exports = function(source) {
  const callback = this.async();
  new Promise(function() {
    callback(null, transform(source).code);
  })
};
```

work fine for me.

**Comment by useafterfree** [comment]
@muzea How did you compile lodash with swc? Can you post an example?

**Comment by muzea** [comment]
@useafterfree Just a simple demo
https://github.com/muzea-demo/swc-loader
use yarn link or npm link
https://github.com/muzea-demo/swc-loader-demo
Then install swc-loader in this project, run make.js to generate the lodash entry file.

**Comment by muzea** [comment]
@kdy1 Now I can run through the demo, very exciting work.
But the results here are very strange, only the meaningless assignments are included in the packaged results, and there are a lot of blank lines inside. It’s convenient to see why it is?

**Comment by kdy1** [comment]
I guess `./src/test.js` resulted in error because es module transform is not implemented yet.

**Comment by kdy1** [comment]
@muzea You are correct. I'll implement it soon.

**Comment by kdy1** [comment]
I could compile whole lodash with swc-cli. Is it okay to close the issue?

I used `npx swc -d out *.js`

**Comment by muzea** [comment]
@kdy1 Transform a single file is no error, but I want to use it with webpack.

**Comment by muzea** [comment]
@kdy1 swc-cli seems to be a bit problematic(0.0.3), the lib directory after the bundle is not in the npm package.

**Comment by kdy1** [comment]
Fixed in version 0.1.0

**Comment by muzea** [comment]
@kdy1 nice, cli now work fine. Is there a configuration description of the transform?

**Comment by muzea** [comment]
@kdy1 I see this example. If I want to transform to cjs or es3, how do I configure it?

**Comment by kdy1** [comment]
Currently it's not possible. I will implement module passes soon

**Comment by kdy1** [comment]
@muzea I implemented commonjs / umd module bundler.
You can use like

```json
{
  "module: {
    "type": "commonjs"
  }
}
```

See: https://swc-project.github.io/docs/configuring-swc#module

**Comment by muzea** [comment]
@kdy1 Awesome.
Will swc add some real-world tests like v8?

**Comment by kdy1** [comment]
@muzea Definitely yes.
Currently swc passes almost all tests copied from babel
