### ISSUE TITLE
regenerator scoping issue

### ISSUE THREAD

**Issue by sod** [swc-project/swc#1036]
**Input code**

```javascript
const x = async function() {
    console.log(
        await Promise.all([[1], [2], [3]].map(
            async ([a]) => Promise.resolve().then(() => a * 2))
        )
    );
}
```

Transpiled with swc to es2015, this yields `[6, 6, 6]`, but I'd expect `[2, 4, 6]`. The `[a]` is handled in a way, that all calls of `() => a * 2` only see the last value.

The generated code looks like this:

```javascript
console.log(await Promise.all([
    [
        1
    ],
    [
        2
    ],
    [
        3
    ]
].map(_asyncToGenerator(regeneratorRuntime.mark(function _callee(param) {
    var _param, a;
    return regeneratorRuntime.wrap(function _callee$(_ctx) {
        while(1)switch(_ctx.prev = _ctx.next){
            case 0:
                _param = _slicedToArray(param, 1), a = _param[0];
                return _ctx.abrupt("return", Promise.resolve().then.call(Promise.resolve(), function() {
                    return a * 2;
                }));
            case 2:
            case "end":
                return _ctx.stop();
        }
    }, _callee);
})))));
```

**Config**
```json
{
  "jsc": {
    "target": "es2015"
  }
}
```

**Expected behavior**

Expected output `[2, 4, 6]`, just like if you paste that in chrome:

![image](https://user-images.githubusercontent.com/905328/92325385-78041100-f04a-11ea-8156-a3e162db9b55.png)

**Version**
The version of @swc/core: 1.2.22

**Comment by sod** [comment]
As a sidenote. Do you even need to downlevel destructoring in `"target": "es2015"`? As far as I can tell this feature was introduced in es2015 - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by kdy1** [comment]
@sod I'm not sure about it. I did it because babel's 2015 preset does it.
