### ISSUE TITLE
Something like @babel/preset-env

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#104]
caniuse-db for rust: https://github.com/kdy1/rust-caniuse

# Required transformations
 - [ ] regenerator

**Comment by fabiosantoscode** [comment]
I propose SWC enables every feature by default, and accepts an optional browserlist parameter that will control what browsers are the targets. Things like `IE > 6` or `> 1%`. That can be done in JS easily.

**Comment by kdy1** [comment]
I thought this is almost done, but determining `.swcrc` api is quite hard. I want to follow it of babel, but there is a problem.

Invoking browserslist from rust code is not easy. It means that allowing browserslist query to be specified on .swcrc is not a trivial task.



There are some options.

 - Invoke browserlist via node executable

It would make swc slow, but the query result can be cached.


 - Inject browserslist function while creating a instance of Compiler.

This is hard at the moment. https://github.com/neon-bindings/neon/pull/375 is required.


 - Handle browsersquery from node

This option requires removing target from .swcrc



I'll go with first option.
