### ISSUE TITLE
TypeScript allowSyntheticDefaultImports: false + esModuleInterop:false compatible

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#1043]
## Library bar

```js
module.exports = {
  foo: 1
}
```
## TS allowSyntheticDefaultImports: false

```ts
import * as bar from 'bar'
console.log(bar.foo) //1


import bar from 'bar'

console.log(bar) // undefined
```

## TS allowSyntheticDefaultImports: true

Behavior is the same with babel/swc

```ts
import * as bar from 'bar'
console.log(bar.foo) // undefined


import bar from 'bar'

console.log(bar.foo) // 1
```

Many existed projects haven't set the `allowSyntheticDefaultImports: true`.

So codes like: https://github.com/nestjs/nest/blob/01dfe29458a2851e42efe8d5b4d614caf9935742/packages/common/services/logger.service.ts#L1 running will throw error while running with swc.

**Comment by Brooooooklyn** [comment]
I'm trying to replace `ts-node` to `@swc-node/register` in `nest` project, but meet many `import * as xx from 'yyy'` issues.

**Comment by kdy1** [comment]
I thought about the api, but I couldn't think of one. Any suggestion will be appreciated.


According to the doc, it should not affect the emitted code. But is it not the case?

https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options

**Comment by Brooooooklyn** [comment]
I think this option is used with `esModuleInterop: true`, `esModuleInterop` allow typescript `import` npm module in `babel` style, and `allowSyntheticDefaultImports` option make it type compatible.

**Comment by kdy1** [comment]
I tested it locally and I found that `"noInterop": true` makes

```
import * as clc from 'cli-color';

console.log(clc.toString());
```

work exactly same as tsc with `"esModuleInterop": false`


See: https://swc-project.github.io/docs/configuring-swc.html#common-js

**Comment by Brooooooklyn** [comment]
> work exactly same as tsc with "esModuleInterop": false

let me have a try

**Comment by Brooooooklyn** [comment]
It works, but I found another problem: there are some **circular require ** codes in `nestjs`, its work fine with `TypeScript` but break with `swc`. I think it might because the `export order is not strictly defined as code source` in swc:

With swc, the codes:

```ts
export * from './http';
export { Scope } from './interfaces'
```
transform to:

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "Scope", {
    enumerable: true,
    get: function() {
        return _interfaces.Abstract;
    }
});

var _interfaces = require("./interfaces");
var _http = require("./http");

Object.keys(_http).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function() {
            return _http[key];
        }
    });
});
```

The `Scope` was exported after `http` in source code but exported before `http` in transpiled code.

**Comment by kdy1** [comment]
Will this work?

```js

"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
var _interfaces = require("./interfaces");
var _http = require("./http");
Object.defineProperty(exports, "Scope", {
    enumerable: true,
    get: function() {
        return _interfaces.Scope;
    }
});
Object.keys(_http).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function() {
            return _http[key];
        }
    });
});


```

**Comment by Brooooooklyn** [comment]
> Will this work?

Yes its behavior the same with Babel and ts.

**Comment by kdy1** [comment]
Fixed it :)

**Comment by Brooooooklyn** [comment]
I tested this patch in nest, found it's still errors appear in some situation because of the `require` order problem:

This file https://github.com/nestjs/nest/blob/master/packages/common/index.ts
```ts
import 'reflect-metadata';

export * from './cache';
export * from './decorators';
export * from './enums';
export * from './exceptions';
export * from './http';
export {
  ...
} from './interfaces';
export * from './pipes';
export * from './serializer';
export * from './services';
export * from './utils';
```

transformed to

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
require("reflect-metadata");
var _interfaces = require("./interfaces");
var _cache = require("./cache");
var _decorators = require("./decorators");
var _enums = require("./enums");
var _exceptions = require("./exceptions");
var _http = require("./http");
var _pipes = require("./pipes");
var _serializer = require("./serializer");
var _services = require("./services");
var _utils = require("./utils");
// ....
```

The `var _interfaces = require("./interfaces");` should be after the `var _http = require("./http");`

**Comment by kdy1** [comment]
I'll fix it soon.

**Comment by kdy1** [comment]
Fixed!
