### ISSUE TITLE
Fix publish issue

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#1045]
I have published a new version of `napi-rs`: https://github.com/napi-rs/napi-rs/commit/51f71fbd92b1578a5a4f555d2925c9fdf91b1b98

Please rerun this job: https://github.com/swc-project/swc/actions/runs/243051722 to verify I have fixed publish issue.

**Comment by kdy1** [comment]
Did it, thanks a lot!

**Comment by Brooooooklyn** [comment]
My bad, I have not tested all corner cases with `nap-rs` cli usage... I will write some tests and documents for it in next week.

**Comment by kdy1** [comment]
It's ok, I re-runned it.

**Comment by Brooooooklyn** [comment]
Please rerun again...

**Comment by kdy1** [comment]
It worked!
