### ISSUE TITLE
angular support

### ISSUE THREAD

**Issue by joebnb** [swc-project/swc#1055]
![image](https://user-images.githubusercontent.com/1646883/92723076-1c63bb80-f39b-11ea-953f-a7bc56eea611.png)

line is :
![image](https://user-images.githubusercontent.com/1646883/92723271-706ea000-f39b-11ea-82c2-fef3bc6d83e7.png)

run with angular project need more configruation,could implement it？

this is angular ts config has alternative angularCompilerOptions
```json
{
  "DO_NOT_EDIT_THIS_FILE": "",
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "target": "es2015",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by kdy1** [comment]
You can enable decorator support. See https://swc-project.github.io/docs/configuring-swc.html#jscparser and https://swc-project.github.io/docs/configuring-swc.html#jsctransformdecoratormetadata

**Comment by joebnb** [comment]
i tried it before submit issue ,its not working

**Comment by kdy1** [comment]
Can you share the error message?

**Comment by kdy1** [comment]
Closing in favor of #1061
