### ISSUE TITLE
strictmodel:false  error

### ISSUE THREAD

**Issue by joebnb** [swc-project/swc#1063]
```js
{
                loader: "swc-loader",
                options: {
                    "jsc": {
                        "parser": {
                            "syntax": "typescript",
                            "decorators": true,
                            "dynamicImport": true
                        },
                        "transform": {
                            "legacyDecorator": true,
                            "decoratorMetadata": true
                        },
                        "module": {
                            "strictMode": false   // set false 
                        }
                    }
                }
            }
```
console out put this error,:
```shell
ERROR in /Users/never/Documents/workSpace/reborn/src/pages/index/app.module.ts
Module build failed (from ../sfe/sfe-builder-angular/node_modules/happypack/loader.js):
Error: failed to process js file

Caused by:
    failed to parse module

ERROR in /Users/never/Documents/workSpace/reborn/src/pages/page_demo/app.module.ts
Module build failed (from ../sfe/sfe-builder-angular/node_modules/happypack/loader.js):
Error: failed to process js file

Caused by:
    failed to parse module
```

if set strictMode true it will throw

![image](https://user-images.githubusercontent.com/1646883/92887338-fdbafe80-f446-11ea-9643-0804cf11bd7c.png)

if add declare for variables ,project will work

**Comment by kdy1** [comment]
Error messages seem too unhelpful. Is this related to toast editor on npm?

**Comment by joebnb** [comment]
> Error messages seem too unhelpful. Is this related to toast editor on npm?

yes ,[toast editor](https://github.com/nhn/tui.editor/tree/master/apps/editor) 

i see not defined error and add `strictmodel:false ` but it output `failed to process js file`.

btw,did swc tested on windows?the same project run on windows it will throw alternative errors

**Comment by kdy1** [comment]
> The same project run on windows it will throw alternative errors

Only very lightly. Which error do you mean? I'd expect parser tests to fail on windows, due to crlf issue.

**Comment by joebnb** [comment]
> Only very lightly. Which error do you mean? I'd expect parser tests to fail on windows, due to crlf issue.

<img width="883" alt="Untitled1" src="https://user-images.githubusercontent.com/1646883/92893840-9f911a00-f44c-11ea-97a0-c0fc6976c6b4.png">

on windows10 x64

**Comment by kdy1** [comment]
What is your nodejs version?

**Comment by joebnb** [comment]
> What is your nodejs version?

all latest node12

**Comment by kdy1** [comment]
Can you try `npm ls @swc/core-win32`?

**Comment by joebnb** [comment]
> Can you try `npm ls @swc/core-win32`?


![image](https://user-images.githubusercontent.com/1646883/92896885-568e9500-f44f-11ea-9782-1b6b0435682a.png)

**Comment by kdy1** [comment]
Hmm... Binding is downloaded, but not found?

@Brooooooklyn Can you take a look?

**Comment by Brooooooklyn** [comment]
oh, wired, I will fix it soon

**Comment by kdy1** [comment]
@Brooooooklyn Thanks!

**Comment by joebnb** [comment]
> oh, wired, I will fix it soon

你好~

this project and builder was in different volume, may should take some params to switch volume

![image](https://user-images.githubusercontent.com/1646883/92898984-03b5dd00-f451-11ea-96f9-23dba5853736.png)
this partten maybe helpful

**Comment by Brooooooklyn** [comment]
> this project and builder was in different volume

@joebnb which volume did `@swc/core` was installed ?

**Comment by joebnb** [comment]
>  this project and builder was in different volume
> 
> @joebnb which volume did `@swc/core` was installed ?

@swc/cored & swc-loader   on  c:/,  project on d:/.

this  issue contain  2 problem. hope you  noticed

**Comment by Brooooooklyn** [comment]
From [screenshot in this comment](https://github.com/swc-project/swc/issues/1063#issuecomment-690957513), node try to resolve `@swc/core-win32` from `c:\users\...\plugins_next\node_modules\@swc\core-win32\swc.win32.node` and I noticed that `@swc/core` was in the same level folder: `c:\users\...\plugins_next\node_modules\@swc\core`. So it's weird that `Node` could not find `c:\users\...\plugins_next\node_modules\@swc\core-win32\swc.win32.node` if `@swc/core-win32` was installed properly.

So could you find where `@swc/core-win32` was installed, and is `swc.win32.node` existed in it ?

**Comment by joebnb** [comment]
> From [screenshot in this comment](https://github.com/swc-project/swc/issues/1063#issuecomment-690957513), node tried to resolve `@swc/core-win32` from `c:\users\...\plugins_next\node_modules\@swc\core-win32\swc.win32.node` and I noticed that `@swc/core` was in the same level folder: `c:\users\...\plugins_next\node_modules\@swc\core`. So it's weird that `Node` could not find `c:\users\...\plugins_next\node_modules\@swc\core-win32\swc.win32.node` if `@swc/core-win32` was installed properly.
> 
> So could you find where `@swc/core-win32` was installed, and is `swc.win32.node` existed in it ?

package install path decide by npm,lt will put shared package in higher level folder,if project require npm will search like:

`/builder/node_modules/@swc/core/node_modules/@swc/core-win32` at begining
 
when trying search 
`/builder/node_modules/@swc/core-win32`

till root
`/node_modules/@swc/core-win32`
 
> here is a explain about dependencies graph  https://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html

----

could fix strictmodel set false,will out throw error first? it throw on darwin,and i found many custom options also cause this error 🤣

**Comment by Brooooooklyn** [comment]
> package install path decide by npm,lt will put shared package in higher level folder,if project require npm will search like

I know this behavior, so it's weird in your case: `@swc/core-win32` was installed but could not resolve in `require`. 

So have you check `@swc/core-win32` location in your project ?

**Comment by joebnb** [comment]
> So have you check @swc/core-win32 location in your project ?
no,just installed swc loader and core and configuration followed swc web guding
