### ISSUE TITLE
Support parsing E4X code as an extension.

### ISSUE THREAD

**Issue by crlf0710** [swc-project/swc#1067]
Currently modern javascript engines seldomly have e4x support. it would be nice if `swc` can support parsing e4x-using javascript code and "babel“ them to something implementable before feeding the code to v8 engine.

**Comment by kdy1** [comment]
Is it kind of standard?

**Comment by crlf0710** [comment]
It's an extension to ecmascript, and defined in ISO/IEC 22537 or ECMA-357. Web browsers have dropped its usage. But some application usages still persists. (example: PDF 2.0 standard ISO 32000-2 mentions that the script that PDF processors shall execute may include E4X).
