### ISSUE TITLE
JSX pragma

### ISSUE THREAD

**Issue by CodeWitchBella** [swc-project/swc#107]
One of the recent commits added support for jsx but as far as I see it did so without support for @jsx pragma documented here: https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#custom-1)

This is critical for people using https://emotion.sh/ in their projects.

So this issue here is to request this feature 🙂

**Comment by fabiosantoscode** [comment]
I want to work on this one, will send PR :)
