### ISSUE TITLE
Spack seem to be unable to resolve imports

### ISSUE THREAD

**Issue by anshulrgoyal** [swc-project/swc#1076]
**Describe the bug**
I tried to import React but it throws error.
![image](https://user-images.githubusercontent.com/32068075/93130383-13068600-f6f0-11ea-84fc-8f7a1167878c.png)

**Comment by anshulrgoyal** [comment]
test also seems to fail
![image](https://user-images.githubusercontent.com/32068075/93130578-5c56d580-f6f0-11ea-8d4e-ce98075896ba.png)

**Comment by kdy1** [comment]
Thanks for the report!
I'll fix it with next version.

**Comment by anshulrgoyal** [comment]
It is still not fixed If I try to import a component, it doesn't work.

**Comment by MarcoPNS** [comment]
My problem is that spack can resolve imports but not the imports from the imports
