### ISSUE TITLE
importsNotUsedAsValues is wrong

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#1094]
@kdy1 This is not the behaviour of `tsc` under `"importsNotUsedAsValues": "preserve"`. The correct behaviour is to _never_ preserve completely unused import identifiers. The above branch should always be used.

I think `ImportNotUsedAsValues` should be removed since it's a misunderstanding of the equivalent `tsc` option.

_Originally posted by @nayeemrmn in https://github.com/swc-project/swc/pull/1060#discussion_r491990064_

It's a breaking change.

**Comment by nayeemrmn** [comment]
@kdy1 What if I don't remove the option, but disassociate it with any behaviour for now? The behaviour it's currently associated with should unconditionally be "remove".

**Comment by kdy1** [comment]
I think it's not correct. I think it should at least panic if an option which causes wrong behavior.
Actaully decorator pass does it, because decorator metadata for current proposal is not implemented yet.

**Comment by nayeemrmn** [comment]
@kdy1 Nevermind, I can fix it to cause the correct behaviour.

**Comment by kdy1** [comment]
@nayeemrmn Sounds great!
