### ISSUE TITLE
getCustomTransformers option - Set of option

### ISSUE THREAD

**Issue by matheus1lva** [swc-project/swc#1099]
**Question**

Hello! First, i want to congratulate for such amazing and promising project! 

On ts-loader there is [`getCustomTransformers`](https://github.com/TypeStrong/ts-loader#getcustomtransformers) option, which can have custom transformers. Is there something similar here?

Thank you!

**Comment by farfromrefug** [comment]
We use transformer in uour project. Any chance of seeing it available in swc ?

**Comment by zyf0330** [comment]
Maybe need to see https://swc.rs/docs/usage/plugins, to write new plugin instead of original transformers which is developed for `tsc`.
