### ISSUE TITLE
How to build with cargo?

### ISSUE THREAD

**Issue by swedebugia** [swc-project/swc#110]
Hi
After checkout:
I get this error trying to build swc:
 cargo build --release --all-features
error: failed to parse manifest at `/tmp/guix-build-swc-0.0-1.2e22397f4.drv-7/source/ecmascript/ast/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature

**Comment by kdy1** [comment]
You need nightly toolchains to build swc. I think you are using stable version of rustc.
