### ISSUE TITLE
New jsx transform

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#1103]
See: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by kitsonk** [comment]
Any update on this.  Looking to get it into Deno 1.8 on March 2nd.

**Comment by kdy1** [comment]
@kitsonk Then I'll work on this after fixing the bundler.

**Comment by kdy1** [comment]
@kitsonk https://github.com/swc-project/swc/pull/1408 is now merged :)
