### ISSUE TITLE
Why target: ES2015 transform es2015 syntax

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#1108]
And  `ES2016` `ES2017` `ES2018` `ES2020`

**Comment by kdy1** [comment]
Initially it was named after babel's preset-es2015 (and name is changed to `target`), but I could not fix it because it's a breaking change.

Maybe adding version field to swcrc may be solution. How do you think about this?

**Comment by Brooooooklyn** [comment]
> Maybe adding version field to swcrc may be solution.

Seems like not a elegant solution.

How about fix it in next major release.

**Comment by kdy1** [comment]
I'll do so.

**Comment by kdy1** [comment]
I decided to fix this as a "bugfix".

**Comment by kdy1** [comment]
Edit: I'll postpone this to v2.
Sorry for spamming

**Comment by kdy1** [comment]
I decided to fix this in v1
