### ISSUE TITLE
Proper Documentation for Migrating from Babel to SWC

### ISSUE THREAD

**Issue by vikashpisces** [swc-project/swc#111]
Is there any documentation or help on getting Babel replaced with SWC. I wanted to try out SWC to check its performance against Babel.

I could only got till npm installation of SWC and RustUP for windows. But the doc at https://swc-project.github.io/4_migrating_from_babel.html is blank.

**Comment by LegNeato** [comment]
Would it perhaps make sense to mirror the Babel js API? The benefits would be three-fold: be a drop in replacement (that is, no migration docs needed), Babel's own test suite could be used to validate swc behavior, and encourage adoption of sec in existing projects.

**Comment by useafterfree** [comment]
I too am interested in this! 

I am currently attempting to run the benchmark in https://github.com/swc-project/node-swc but ran into: #112

**Comment by kdy1** [comment]
I wrote migration guide from babel-cli to swc-cli.
See https://swc-project.github.io/docs/migrating-from-babel-cli

**Comment by thgh** [comment]
Currently, `npx swc` is not working:

```
$ npx swc input.js
command not found: swc
$ npx swc-cli input.js
npx: installed 28 in 1.969s
Cannot find module 'swc'
$ node -v
v11.2.0
```

**Comment by kdy1** [comment]
@thgh You should run npm i -D swc swc-cli first
