### ISSUE TITLE
Endless loop with try { await ... } finally {}

### ISSUE THREAD

**Issue by jingyu9575** [swc-project/swc#1125]
**Describe the bug**

I'm not sure what's happening here, but a simple async function with `try { await ... } finally {}` is transformed into an endless loop.

**Input code**

```js
async function test() {
	try {
		await 1
	} finally {
		console.log(2)
	}
}
test()
```

**Config**
```json
{
	"env": {
		"targets": "last 2 versions, Firefox ESR, ie >= 9",
		"mode": "entry",
		"coreJs": 3
	},
	"jsc": {
		"parser": {
			"syntax": "ecmascript",
			"dynamicImport": true
		}
	}
}
```

**Expected behavior**
Shows `2` in console.

Actual behavior: browser freezes with endless outputs of `2`.

**Version**
1.2.34

**Additional context**

This doesn't happen in babel. Adding a `return` in either the try block or the finally block can fix the problem.

**Comment by kdy1** [comment]
I tried fixing this, but it was much more complex than I initially thought.

This seems like an issue of `async_to_generator` pass.


```js
function* test() {
        try {
            yield 1;
        } finally{
            console.log(2);
        }
    }
    test()
```

The code above, which is produced by `async_to_generator pass`, works
