### ISSUE TITLE
await with optional chaining is broken

### ISSUE THREAD

**Issue by avaly** [swc-project/swc#1133]
**Describe the bug**

A side-effect of the fix for #1130 when using `await` with optional chaining.

**Input code**

```js
const item = await data?.foo();
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

**Actual behavior**

`swc`:

```js
const item = await data === null || data === void 0 ? void 0 : data.foo();
```

`babel`:

```js
const item = await (data === null || data === void 0 ? void 0 : data.foo());
```

**Expected behavior**

`await` with optional chaining should work correctly.

**Version**
The version of @swc/core: 

@swc/cli: 0.1.27
@swc/core: 1.2.35

**Comment by ryanatkn** [comment]
Similarly, parens are not preserved in these cases:

`await (a || b);` -> `await a || b;`
`await (a ? b : c);` -> `await a ? b : c;`

Same versions and es2019 target.
