### ISSUE TITLE
Is it possible to preserve unused imports that aren't types?

### ISSUE THREAD

**Issue by ryanatkn** [swc-project/swc#1134]
**Question**

In upgrading from 1.2.28 to 1.2.35 I'm running into a problem for my use case which requires unused imports to be preserved. This seems to have changed with the import stripping functionality in PRs #1060 and #1101. I looked through the docs, issues/PRs, and briefly the code (I know only a little Rust), and couldn't find an answer - sorry if it's obvious. :)

Is `import_not_used_as_values`/`strip::ImportNotUsedAsValues` exposed as an option? I was unable to figure out how to test with different values.

My use case is using swc to preprocess the TypeScript in [Svelte](https://github.com/sveltejs/svelte) files. Svelte combines JS/TS with an HTML-like templating language in the same file, so imports are often not referenced in the code given to swc. The behavior in 1.2.28 has worked for what I need, except sometimes I've had to use `import type`.

Thank you! I really love this project.

**Comment by intrnl** [comment]
+1 for this, but some additional notes.

`importsNotUsedAsValues` will not do the option you think it is, it'll still strip the named imports, leaving only `import "abc"` for the side effect. I've tested this with tsc and esbuild.

Personally, I think that it'd be better to enforce the use of `import type` for importing types, as we can just strip that off immediately. We could take something like `onlyRemoveTypeImports` from Babel TypeScript plugin as the option name.

**Comment by kdy1** [comment]
This is fixed by https://github.com/swc-project/swc/pull/1318

**Comment by btakita** [comment]
Thank you for the project. Is there any documentation on how to activate this feature? Is there a `onlyRemoveTypeImports` or similar config option somewhere?

**Comment by kdy1** [comment]
@btakita No, currently this is only for rust users.

**Comment by btakita** [comment]
@ryanatkn, I'm also attempting to compile ts from svelte. Did you solve this problem using swc?
