### ISSUE TITLE
export * as ns is part of ES2020 and should not be a proposal pass

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#1137]
**Describe the bug**

Currently swc requires the `swc_ecmascript::transforms::proposals::export` to support _export * as ns_.  This should not be required as the proposal was ratified and is [part of ES2020](https://tc39.es/ecma262/2020/#table-42).

**Expected behavior**

That `swc_ecmascript::transforms::proposals::export` is not required to properly handle code such as:

```js
export * as a from "./a.js";
```

**Version**
The version of @swc/core: 1.2.35

**Comment by Brooooooklyn** [comment]
Maybe related https://github.com/swc-project/swc/issues/1108

**Comment by kdy1** [comment]
As this is a breaking change, I'll fix this in a separate pr.
