### ISSUE TITLE
swc_bundler: Import and export from same module

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#1150]
**Describe the bug**

swc_bundler goes a bit crazy under certain conditions.  I tried to reduce this use case down further, but the reproduction is difficult, and the emit is all a bit strange.

**Input code**

*example12.ts*

```ts
import { a as defaultA, O } from "./m.ts";
export { O } from "./m.ts";

interface AOptions {
  a?(): void;
  c?: O;
}

class A {
  #a: () => void;
  #c?: O;
  constructor(o: AOptions = {}) {
    const {
      a = defaultA,
      c,
    } = o;
    this.#a = a;
    this.#c = c;
  }

  a() {
    this.#a();
  }

  c() {
    console.log(this.#c);
  }
}

let a = new A();
a.a();
a.c();
```

*m.ts*

```ts
export { a } from "./n.ts";
export { O } from "./o.ts";
```

*n.ts*

```ts
export function a() {
  console.log("a");
}
```

*o.ts*

```ts
export enum O {
  A,
  B,
  C,
}
```

**Expected behavior**

An emit something like that outputs the following when run:

```
a
undefined
```

Current bundling outputs:

```js
var O;
(function(O1) {
    O1[O1["A"] = 0] = "A";
    O1[O1["B"] = 1] = "B";
    O1[O1["C"] = 2] = "C";
})((void 0) || (O = {
}));
const O1 = void 0;
export { O1 as O };
class A {
    #a;
    #c;
    constructor(o = {
    }){
        const { a =defaultA , c ,  } = o;
        this.#a = a;
        this.#c = c;
    }
    a() {
        this.#a();
    }
    c() {
        console.log(this.#c);
    }
}
let a1 = new A();
a1.a();
a1.c();
```

Which outputs the following when run:

```
error: Uncaught ReferenceError: defaultA is not defined
        const { a =defaultA , c ,  } = o;
                   ^
    at new A (file:///example12.bundle.js:15:20)
    at file:///Users/example12.bundle.js:26:10
```

Outside of the `a` imported function being totally dropped, the enum is totally not working.  It is worth noting that the enum is re-exported from the `example12.ts` but it is never used in a code position in the module.

**Version**

Version: master (75a6211e2d17ab39355b743b9cb33374be7a5cd4)

**Additional context**

Working to integrate swc_bundler into Deno.

**Comment by kdy1** [comment]
@kitsonk I fixed it.
