### ISSUE TITLE
Automatically detect if file is script or module when parsing

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#1164]
**Describe the feature**
Add ability to `swc_ecmascript`'s `Parser` to automatically detect if parsed source file 
is an ES module or plain old script. 

Currently it's up to implementor to decide if file is a script of a module and based on that
decision should call either `Parser::parse_script` or `Parser::parse_module`.

It makes writing libraries working on both scripts and modules a bit more cumbersome,
because of need to handle both `swc_ecma_ast::Script` and `swc_ecma_ast::Module`.

Proposed API: `Parser::parse_program() -> PResult<Program>`

**Additional context**
Came up in discussion regarding https://github.com/denoland/deno_lint/issues/366

**Comment by RDambrosio016** [comment]
- Its not exactly doable without a lot of state handling, modules impose more restrictions as they are in strict mode, so youd have to mark every strict mode possible error and go back over them and either clear them or reconsider whether an error should be thrown. Moreover, guessing what the user meant is a pretty bad idea for a linter (talking about deno lint specifically) which is meant to consistently enforce good practices, say you accidentally copy and pasted some wrong code, well, now you may have a lot of errors about strict mode and you have no idea why. Generally try to avoid implicit behavior for a tool used to enforce consistency. I would prefer making an enum called program then simply assuming scripts for js and modules for mjs. Thats my take from experience with js parsers and linters 👍
