### ISSUE TITLE
Question: can swc be used as a native library?

### ISSUE THREAD

**Issue by xmo-odoo** [swc-project/swc#1169]
swc is mostly being billed as a fast JS/TS compiler which incidentally happens to be implemented in Rust. But it's unclear how much of the behaviour / feature is implemented in Rust versus JS, and whether swc could usefully be leveraged from an other language without having to go through node.

Is Rust only the core transformation engine with all the transforms being implemented in javascript (requiring node) or are some / most / all transforms part of the Rust core, with the CLI using node simply because that's the ecosystem it lives in?

A quick browse makes it look a lot like the former (all the "business" stuff is in feature and node is absolutely not optional), but I wanted to check just in case.

Asking here because the website's help page only has a link to the doc, the "community" and "whatsnew" sections of the page are completely empty.

**Comment by kdy1** [comment]
All transforms are written in rust. Deno uses swc to transpile typescript into ecmascript, and some clients use swc by compiling into wasm with their own transforms.

**Comment by kdy1** [comment]
Yes, but there are some binding helper libraries so knowing the exact language you want may help.

**Comment by xmo-odoo** [comment]
@kdy1 python in this case.

**Comment by kdy1** [comment]
@xmo-odoo Then https://github.com/PyO3/pyo3 will help greatly.

**Comment by xmo-odoo** [comment]
@kdy1 there's certainly no worries about you having other things to do than writing bindings, I just asked the initial question because I hadn't seen any doc about swc being supported / usable as a library so it wasn't obvious whether that was an official use-case or just an implementation detail of the tool.

**Comment by kdy1** [comment]
@xmo-odoo The library itself is not documented well as there are too many codes,  but I guess https://swc.rs/rustdoc/swc/  will help you.

Docs about compiling rules lives at https://swc.rs/rustdoc/swc_ecma_transforms/
