### ISSUE TITLE
Possibility of compiling on stable Rust?

### ISSUE THREAD

**Issue by alexcrichton** [swc-project/swc#117]
Hello! Over in the [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen) project we've [got a new proposal](https://github.com/rustwasm/rfcs/pull/6) which partly entails eventually having a JS parser built into our tooling. The JS parser would need to basically compile ES module syntax to either CommonJS or "linked manually with no modules" style syntax. The swc project seems like it perfectly fits the bill in terms of use cases here!

One hesitation that we'd currently have from using swc is that it looks like it currently requires nightly Rust and also isn't published much on crates.io. I'm curious if y'all have an idea about whether it's feasible in the near-term to compile on stable (and as a bit of a stretch goal publish on crates.io too). That'd make swc a strong possibility for us to use in `wasm-bindgen` as a dependency!

We're mostly just evaluating our options right now, so "not any time soon" is a totally valid answer too!

**Comment by kdy1** [comment]
I removed some unused features and checked which crate depends on which feature.


swc_common:
 - never_type
 - specialization

swc_ecma_parser:
 - box_syntax
 - box_patterns
 - specialization
 - never_type

-----


 - Removing uses of never_type will be easy
 - Removing box_syntax will be easy
 - Removing box_pattern may be tricky, but possible
 - Specialization can be replaced with hand-written folder / visitor.
But lots of work is required


So I think it's possible and I'd like to do it, but I'm not sure how much time it would take.

**Comment by kdy1** [comment]
I'm currently working on this using cargo feature.

**Comment by kdy1** [comment]
cc @alexcrichton 
Currently swc depends on rustc-ap-* crates, but I think those crates will never be stabilized, is this correct? Then we should copy some code into swc..

Only hygiene and error reporting is used by swc, so it would not be too hard.

**Comment by alexcrichton** [comment]
Oh wow thanks for the speedy responses, this looks great!

I was trying to give this a spin locally with a few `path` dependencies, but it looks like dependencies like `scoped-tls` still have the `nightly` feature enabled. Do I need to disabled some features of swc or something like that though?

**Comment by kdy1** [comment]
@alexcrichton I've published it.

**Comment by kdy1** [comment]
Oh, my mistake..
I fixed and verified that stable rustc can build swc_ecma_parser

I guess you should run `cargo update`.

See https://github.com/kdy1/swc-stable-rust

**Comment by alexcrichton** [comment]
Ok great, thanks! Our use case will also need to write out the JS file after transforming it, does that mean that we would need the `swc_ecma_codegen` flag as well?

**Comment by kdy1** [comment]
@alexcrichton Yes. I published swc_ecma_codgen v0.5.1 which can be built with stable rustc.

**Comment by alexcrichton** [comment]
Awesome, thanks again so much for your help!
