### ISSUE TITLE
Jest with SWC doesn't seem much faster than Jest with babel :(

### ISSUE THREAD

**Issue by benwainwright** [swc-project/swc#1172]
So I've spent today experimenting with swapping out `tsc` for `swc` in our small typescript project (ejected create-react-app typescript/react), and if I'm honest I've been... a bit disappointed. 

The project is moderately small so test times are not a huge deal *yet*, but anticipating it getting bigger, I was looking for an improvement on testing times, but after benchmarking (using `yarn add jest-benchmark`) test runs with `swc-jest` and the default babel config that comes with create react app, the speed seemed to be about the same. 

Here is the results of the benchmarking our jest tests with `swc`:

![image](https://user-images.githubusercontent.com/3321885/96283132-a70b8c00-0fd3-11eb-862d-c9072944be51.png)

And here is the same thing using our normal jest config:

![image](https://user-images.githubusercontent.com/3321885/96283501-344ee080-0fd4-11eb-9096-b8509825fd83.png)

As you can see; the improvement in the whole test run is about 0.25 seconds per run - nothing to write home about and certainly not worth swapping out a tried and tested part of our toolchain for. Now I appreciate that `babel` is likely not the only bottleneck in a `jest` run, but given all the impressive claims I've seen in various places about swc, is this really what I'd expect to see? Or have I configured something wrong. Swapping `babel-loader` out for `swc-loader` doesn't seem like a massive improvement in terms of build times either, though I've not yet found an easy way of benchmarking that. Below are the configs that I used to get `swc` working:

## `jestConfig` `transform` block in `package.json`
![image](https://user-images.githubusercontent.com/3321885/96282710-f7ceb500-0fd2-11eb-864d-fd426f6d16c9.png)

## `.swcrc`
![image](https://user-images.githubusercontent.com/3321885/96282830-22207280-0fd3-11eb-8275-58d190c350c2.png)

**Comment by kdy1** [comment]
swc cannot optimize the time used for running test. It just reduces time of transpiling.

**Comment by benwainwright** [comment]
@kdy1 That's a complete non answer to my question (if you actually read what I wrote, you'll see that I more or less accept that), so I'll restate it in the hope that someone will actually answer me:

> Now I appreciate that babel is likely not the only bottleneck in a jest run, but given all the impressive claims I've seen in various places about swc, is this really what I'd expect to see? Or have I configured something wrong.

**Comment by kitsonk** [comment]
For testing, especially benchmarks, transpiling code is likely less than 1% of the time spent on the test, so optimising 1% of a process will lead to the results you are seeing. I don't know the internals of jest, but I suspect it doesn't even transpile on every run, so you are only get a one off improvement in startup.
