### ISSUE TITLE
Are external source maps working?

### ISSUE THREAD

**Issue by AlexisPuga** [swc-project/swc#1177]
Hi, @kdy1.

**Question** When source maps are generated by other tools, are these files taken into consideration when generating new ones?

If I run the following:
```cli
esbuild \
	--bundle static/js/index.js \
	--outfile=temp/js/main.min.js \
	--minify \
	--sourcemap
```

And then use swc:
```cli
swc temp/js -d public/js -s
```

Source maps doesn't seem to be working (even if I use "inline" for one or both options).

However, running babel will generate valid source maps (after 3 years, of course :wink:):
```bash
babel temp/js -d public/js -s
```

**Question 1.1** Is this a bug or there's something I'm missing here?

Thank you in advance (and sorry for the inconveniences).
Also, congrats for your work!

Below are my .swcrc and my .babelrc files (just in case):
<details>
<summary>My .babelrc file</summary>

<pre>
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "entry",
                "corejs": 3
            }
        ]
    ]
}
</pre>
</details>
<details>
<summary>My .swcrc file</summary>
<pre>
{
    "minify": true,
    "jsc": {
        "target": "es5"
    },
    "env": {
        "coreJs": 3
    }
}
</pre>
</details>

Also, these are the versions I'm using for swc:
@swc/cli: 0.1.27
@swc/core: 1.2.32

... and for testing on babel:
@babel/cli: 7.12.1
@babel/core: 7.12.3
@babel/preset-env: 7.12.1

Have a nice day!

**Comment by kdy1** [comment]
External source maps are fixed, if I remember correctly.
