### ISSUE TITLE
new.target syntax is not transformed

### ISSUE THREAD

**Issue by wessberg** [swc-project/swc#1179]
**Describe the bug**

[`new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) is not being transformed to ES5-compatible syntax when `es5` is the target.

**Input code**
[Please see this repro](https://repl.it/@wessberg/swc-newtarget#index.js).

In it, you'll find that `output.js` is the result of running `swc index.js -o output.js` with `es5` as the target.

**Config**
You'll find it in the repro, but here it is:
```json
{
  "jsc": {
    "target": "es5"
  }
}
```

**Expected behavior**
`new.target` syntax should be transpiled into syntax that legacy environments can understand.

Here's how babel would have rewritten new.target in the example from the repro:

```js
if ((this instanceof Foo ? this.constructor : void 0) === undefined) {
    throw new TypeError("Constructor ".concat(Foo.name, " requires 'new'"));
}
```

**Version**
The version of @swc/core: 1.2.36

**Comment by wessberg** [comment]
This still doesn't work if the class is declared within a nested lexical environment, such as within a self-invoking function.
[Please see this repro](https://replit.com/@wessberg/swc-newtarget-2#output.js) where I've copied the exact same code from my original repro but placed it inside a self-invoking function.

`swc` produces the following output:

```js
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
var _newtarget = new.target;
(function() {
    var Foo = function Foo(callback) {
        "use strict";
        _classCallCheck(this, Foo);
        if (_newtarget === undefined) {
            throw new TypeError("Constructor ".concat(Foo.name, " requires 'new'"));
        }
    };
})();
```
Which leads to syntax errors in browsers that doesn't support `new.target` syntax.
Please reopen this issue, and thanks for your time.

**Comment by kdy1** [comment]
@wessberg Can you file a new issue?

**Comment by wessberg** [comment]
Alright, here it is: https://github.com/swc-project/swc/issues/2308
