### ISSUE TITLE
swc_bundler: support outputting an IIFE

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#1184]
**Describe the feature**

Currently, swc_bundler can output an ES module, but it does support output as an IIFE.

For outputting the bundle, instead of `export`ing entries from the entry module in the bundle, `swc_bundler` would output an IIFE where the return value of the IIFE is the value of the exported module.  For example if the entry module was:

_a.js_

```js
export const a = "a";
```

The output of the bundle would be something like:

_a.bundle.js_

```js
(function () {
  "use strict";
  var __exports = {};
  Object.defineProperty(__exports, "__esModule", {
    value: true
  });
  __exports.a = "a";
  return __exports;
})();
```

**Babel plugin or link to the feature description**

There are [Babel plugins](https://github.com/MindTouch/babel-plugin-transform-modules-iife) that in theory can do this, but IIFE output is one of the builtin output formats of Rollup (and other bundlers).

**Additional context**

In particular with Deno, we would like to have an option for `Deno.bundle()` to be able to output a single file ES module or an IIFE.

**Comment by kitsonk** [comment]
A couple of other considerations:

- For emitting dynamic imports, assume that there is some sort of of `import()` global?
- Support TLA by emitting an async IIFE, meaning the consumer would need to figure out how to wait for the promise resolution.  For example, given the input of:

  _b.js_

  ```js
  export const b = await Promise.resolve("b");
  ```

  The output would be something like:

  _b.bundle.js_

  ```js
  (async function () {
    "use strict";
    var __exports = {};
    Object.defineProperty(__exports, "__esModule", {
      value: true
    });
    __exports.b = await Promise.resolve("b");
    return __exports;
  })();
  ```

**Comment by ClarisL** [comment]
Hello,

I'm really interested in using the IIFE output from swc_bundler.
Happy to see this is now available !
Still I did not find any documentation regarding the setup part.

Do you have any piece of advice regarding how this can be setup ?
Thanks,
