### ISSUE TITLE
Not all Unicode Escape Sequences are escaped correctly, leading to "Unterminated string constant" errors

### ISSUE THREAD

**Issue by wessberg** [swc-project/swc#1187]
Please see [this repro](https://repl.it/@wessberg/swc-unicode-bug#index.js).
In it, you'll see an input file such as this:

`export const unicodeWhitespaceCharacters = '\u0009\u000A\u000B\u000C\u000D\u0020\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028\u2029\uFEFF';`

`swc` transforms Unicode Escape Sequences into UTF-8 characters, and this is the compiled output (`output.js` in the repro) with default settings:

<img width="656" alt="Screen Shot 2020-10-26 at 11 23 18 AM" src="https://user-images.githubusercontent.com/20454213/97161136-a9ad7480-177d-11eb-87f6-12ea9c300225.png">

Notice the "?" in the end of that string. That's where `\u2028`, `\u2029`, and `\uFEFF` used to be.

Here's the output I would have expected, which is also what tools like `terser` produces, and `esbuild` given the `--charset=utf8` produces:

```js
export var '\t\n\v\f\r                　\u2028\u2029\ufeff';
```

The current behavior of `swc` leads to `Unterminated string constant` exceptions in browser such as IE 11 - even with `<meta charset="utf-8">` in the HTML document. On that note, it is not always possible for the website author to instruct IE to use UTF-8. [There's a bunch of ways IE can choose to ignore that](https://docs.microsoft.com/en-us/troubleshoot/browsers/wrong-character-set-for-html-page).

I ran into this problem specifically while bundling core-js (the declaration from the example is located within `core-js/internals/whitespaces.js` with swc and testing it across browsers.

On a related note, I've also created https://github.com/swc-project/swc/issues/1188

**Comment by QGB** [comment]
python regex whitespace \s not match "\uFEFF"
