### ISSUE TITLE
Output: Import statement must be with `.js` not `.ts`

### ISSUE THREAD

**Issue by Maxvien** [swc-project/swc#1208]
**Describe the bug**

**Input code**
```ts
// sum.ts
export function sum(a: number, b: number) {
  return a + b;
}
```
```ts
// main.ts
import { sum } from './sum.ts';

console.log(sum(1, 2));
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  }
}

```
**Result**
```js
// main.js
import { sum } from './sum.ts';

console.log(sum(1, 2));
```

**Expected result**
```js
// main.js
import { sum } from './sum.js';

console.log(sum(1, 2));
```

The import statement must be with `.js`. Not `.ts`

**Version**
The version of @swc/core: 1.2.37

**Comment by kwonoj** [comment]
I believe this is related with https://github.com/swc-project/swc/issues/3043 also it's correct behavior as-is currently. 

Linked issue's comment explains it 

```
See @RyanCavanaugh's comment here: microsoft/TypeScript#41887 (comment)

TypeScript doesn't modify JavaScript code you write, the import path you write should be the one you want to appear in the output .js file
```

Actually, if you try latest tsc (https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEZwGZQiOAcgDoB6VfAU2JlUIG4g) you'll get error instead: 

> An import path cannot end with a '.ts' extension. Consider importing './some.js' instead.

If swc's bundler or other tool's resolver cannot resolve module with full extension (I believe for some cases it's failing) that's something to fix, but I believe swc should not try to modify import specifier by its own. 

/cc @kdy1 , in my opinion I'd like to suggest to close this - and if we need, we can implement error out as same as tsc does.

**Comment by kdy1** [comment]
Yeah, I think you are right.
Thanks!
