### ISSUE TITLE
JSON arrays have a semicolon attached at the end if they are parsed from files

### ISSUE THREAD

**Issue by vijaybritto** [swc-project/swc#1210]
**Describe the bug**
SWC seems to attach a ; at the end of json files which have json arrays
**Input code**
```js
import jsonArray from '../file.json'
```
#file.json
```json
["a" ,"b"]
```
Error: Unexpected token ; at position 10
**Expected behavior**
It should parse the json array which is valid json

**Version**
The version of @swc/core: 

**Additional context**

**Comment by kdy1** [comment]
Why is `.json` file processed at first time?
