### ISSUE TITLE
Swc permits ts class names with disallowed names

### ISSUE THREAD

**Issue by RDambrosio016** [swc-project/swc#1218]
**Describe the bug**
Swc's `invalid_class_name` check should check the same identifiers as `typescript::parse_ts_interface` instead of only `any`. Here: 
https://github.com/swc-project/swc/blob/master/ecmascript/parser/src/parser/class_and_fn.rs#L1077-L1097

Edit: it appears that tsc doesnt enforce this for `class intrinsic {}`, so that should be omitted.

**Input code**
```ts
class number {}
```

**Config**
None

**Expected behavior**
`Class name cannot be 'number'`

**Version**
The version of @swc/core: `1.2.37`

**Additional context**
None, explained in the first section

**Comment by kakoc** [comment]
As I see ecmascript specification doesn't tell that you can't create `class number {}`, seems that it's totally fine.  
But at the same time typescript mentions that point.  
So probably even any should be removed from `invalid_class_name` as an invalid name.

**Comment by RDambrosio016** [comment]
Its fine for ECMAScript code, its not fine for TypeScript code, TypeScript can include as many restrictions as it wants since its a superset. Even if technically this means your ecmascript code using `class any {}` wont work. Its best that a TS parser stays consistent with TSC instead of not enforcing this.
