### ISSUE TITLE
Unicode Code Point Escape syntax is not transpiled

### ISSUE THREAD

**Issue by wessberg** [swc-project/swc#1227]
**Describe the bug**

[Unicode Code Point Escape syntax](https://exploringjs.com/es6/ch_unicode.html) is not being transformed to ES5-compatible syntax when `es5` is the target.

It would seem that swc is always assuming traditional unicode escape sequences of on the form `\u` followed by four digits and simply doesn't parse code point escape syntax.

**Input code**
[Please see this repro](https://repl.it/@wessberg/swcunicodecodepointescapebug#index.js).

In it, you'll find that `output.js` is the result of running `swc index.js -o output.js` with `es5` as the target for the following input:

```js
const foo = "\u{a0}";
```

The output is:

```js
var foo = "\u";
```

Which is incorrect.

**Config**
You'll find it in the repro, but here it is:
```json
{
  "jsc": {
    "target": "es5"
  }
}
```

**Expected behavior**
Unicode Code Point Escape syntax should be transpiled into syntax that legacy environments can understand.

Here's how babel would have rewritten the example from the repro:

```js
var foo = "\xA0";
```

**Version**
The version of @swc/core: 1.2.39

**Comment by wessberg** [comment]
This issue has been marked as closed, but the issue haven't been resolved. Please reopen this issue and see the updated repro.

It is correct that the example from the my original repro now produce the correct output, but the following code snippet will still produce invalid code:

For the following input:
```typescript
const foo = [
        "\u{660}",
        "\u{661}",
        "\u{662}",
        "\u{663}",
        "\u{664}",
        "\u{665}",
        "\u{666}",
        "\u{667}",
        "\u{668}",
        "\u{669}"
    ];
```

swc will now produce the following output:
```typescript
var foo = [
    "\u{660}",
    "\u{661}",
    "\u{662}",
    "\u{663}",
    "\u{664}",
    "\u{665}",
    "\u{666}",
    "\u{667}",
    "\u{668}",
    "\u{669}"
];
```

**Comment by wessberg** [comment]
Can this issue please be reopened? See my comment above.

**Comment by vertic4l** [comment]
Ran into this issue as well while testing webpack 5 + swc-loader (which gives create build performance) and was checking the output within IE11.

Encountered syntax errors due to the above mentioned problem.

**Comment by kdy1** [comment]
Closing as it's fixed and there's test for it.
https://github.com/swc-project/swc/tree/a564ced26a814cf1f696b04ab121638ffb3e77b1/crates/swc/tests/fixture/issue-1227

**Comment by wessberg** [comment]
@kdy1, please reopen this issue again. As I mentioned in [this comment](https://github.com/swc-project/swc/issues/1227#issuecomment-794027378), the problem isn't actually fixed. You can verify this by opening up the repro and running it. It is a problem in the current build of swc too, version 1.2.164. You did reopen this issue, but it would seem that you closed it again without actually addressing the problem.

Did you check out the repro?

You made a partial fix and wrote a test for it, but there are cases it doesn't cover, such as an array of strings, like in the example in the repro.

**Comment by kdy1** [comment]
It now works, see
https://play.swc.rs/?version=1.2.164&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVYjmUoACpZjSajMzg1olHTQhQ0whI0whY0whE0whU0whM0whc0whC0why1olsEisNRcAMnFmZtIAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

2022년 4월 7일 (목) 오후 8:46, Frederik Wessberg ***@***.***>님이 작성:

**Comment by wessberg** [comment]
You're right, I deleted my comment after running the repro example again. Thanks!
