### ISSUE TITLE
Multiline attributes in JSX result in invalid javascript

### ISSUE THREAD

**Issue by jsedlacek** [swc-project/swc#1233]
**Describe the bug**

When JSX contains multi-line attributes, the resulting javascript code is invalid:

```js
function Component() {
    return React.createElement("div", {
        name: "A
    BB"
    });
}
```

**Input code**

```jsx
function Component() {
  return (
    <div
      name="A
    B"
    />
  );
}
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    }
  }
}
```

**Expected behavior**

The resulting javascript is valid:

```js
function Component() {
    return (React.createElement("div", { name: "A\n    B" }));
}
```

**Version**
The version of @swc/core: 1.2.39

**Additional context**

Typescript and Babel handle this use case correctly.

**Comment by snaumov** [comment]
bumped into it today as well, made a small [repr](https://repl.it/@amigozz/multiline-bug)

a working example in [babel](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4BZATwGFdIakb4BeOABQBKOLwB8g8nDgAeACbAAbmKnTZAZVxJ24Wtxiq1cGEgAeMXgCIAKgAskcEClOgArnhruARkihwImHB0wADmNCgwrkR0cCgANnEQAO5IcsYQcD5w6gCSAOIAcgCiACL-NMa2wDGYwEhxcgB0hkZwAFq-GQIADCIgqPQENBlxoMAw-I1wAII0zDBVNCFwAEIAqtZw3Y4DMfijIOOVDp4gPn4BQaHhkURw40ggdM2tamt0DgvVcKfncEn2CpyJAmKCHGjAJbHRzONx4ADE_kCwTCESiSDokxaRgA6oDoQcjt8iOh7HIADTQujMBiPf7ABJwIggCCKBwoOZwMDcBRQ1z0a6pK6o24OB5PSwtFSvAAKcXQSFsEAavhaMgA9Jp-jpOPppbJ1QplOQhBRyGZILA4MDMChXHEmGwOHoeKQgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.9&externalPlugins=)
