### ISSUE TITLE
SWC inputSourceFile does not respect sourceMappingURL

### ISSUE THREAD

**Issue by pyrocat101** [swc-project/swc#1236]
**Describe the bug**

The documentation of SWC config says the following for [`inputSourceMap`](https://github.com/swc-project/swc/blob/4490e2551dc806d39b20b4520f7101cab06e4a21/node-swc/src/types.ts#L152-L161) option:

```js
  /**
   * `true` will attempt to load an input sourcemap from the file itself, if it
   * contains a //# sourceMappingURL=... comment. If no map is found, or the
   * map fails to load and parse, it will be silently discarded.
   *
   *  If an object is provided, it will be treated as the source map object itself.
   *
   * Defaults to `true`.
   */
  inputSourceMap?: boolean | string;
```

But the actual logic is that if the file is named X.js, then SWC assumes its source map file is located at X.js.map.

**Input code**

```js
// Assuming input file is X.js, but it contains a comment of sourceMappingURL=Y.js.map
const {code, map} = swc.transformFileSync(inputFilePath, {
    inputSourceMap: true,
    sourceMaps: true,
    swcrc: false,
    env: {
        targets: {
            ie: '11',
        },
        dynamicImport: true,
    },
});
```

**Config**
N/A

**Expected behavior**
Read sourceMappingURL comment from the input file and use that to resolve the source map file name.

**Version**
The version of @swc/core: 1.2.38

**Additional context**
N/A

**Comment by pyrocat101** [comment]
Thanks!

**Comment by kdy1** [comment]
I think this isn't fixed yet.
(The pr mentions this because it's postponed)
