### ISSUE TITLE
Provide binary for android

### ISSUE THREAD

**Issue by FabianSellmann** [swc-project/swc#1238]
**Describe the feature**
Basically to run swc on android (e.g. by using termux) one would need a binary for android / arm64.

Currently getting this error on yarn install:
```
error @swc/core@1.2.36: The platform "android" is incompatible with this module.
error @swc/core@1.2.36: The CPU architecture "arm64" is incompatible with this module.
```

**Comment by Brooooooklyn** [comment]
I will do it in https://github.com/swc-project/swc/pull/1244

**Comment by FabianSellmann** [comment]
Awesome! Thanks a lot!
