### ISSUE TITLE
how to walk swc ast

### ISSUE THREAD

**Issue by JiangWeixian** [swc-project/swc#1239]
**Question**

```js
const { parseFileSync } = require('@swc/core')
const path = require('path')

const result = parseFileSync(path.resolve(__dirname, './sample-js.js'))
```

how to walk result? like acron-walk

**Comment by kdy1** [comment]
There's a visitor, but the ast node types are bit outdated.

I'll fix the inconsistency with https://github.com/swc-project/swc/pull/1229

**Comment by JiangWeixian** [comment]
@kdy1 thanks reply

may i just traverse ast, but no transform

**Comment by JiangWeixian** [comment]
forget it, it's really easy to write a traverse.. 😀
