### ISSUE TITLE
TypeScript 

### ISSUE THREAD

**Issue by marcus-sa** [swc-project/swc#124]
Will this transpiler be up to date with the newest changes to TS when they occur?

Awesome project btw!

**Comment by kdy1** [comment]
Yes. I'll implement more typescript-related features as neccessary

**Comment by marcus-sa** [comment]
What's the roadmap for missing features in TS?

**Comment by kdy1** [comment]
Currently all features are implemented I guess.

Unfortunately, currently there's no roadmap for tracking it
