### ISSUE TITLE
[RFC] Snowpack Usage: what would you want to see in a Snowpack Plugin?

### ISSUE THREAD

**Issue by jhechtf** [swc-project/swc#1249]
**Question**

I've recently come across SWC and honestly I _love_ it. I've been complaining about there needing to be a faster compiler for TS since the moment I've worked on a large enough code base. 

As an aside, I've also started preferring to use Snowpack whenever possible, and have created an (as yet unreleased) plugin to use SWC to compile TS files. 

Are there any particular things you would look for in an SWC plugin for Snowpack? As of right now it takes no options and literally only loads and compiles TS files. 

Thanks!

**Comment by kdy1** [comment]
What comes to my mind right now is an option to use external helpers.
It would greatly reduce bundle size.

**Comment by jhechtf** [comment]
@kdy1 could you give me an example of how you would expect to use that? As it is I am unsure what that would look like (meaning I wouldn't be able to add in the functionality)

**Comment by kdy1** [comment]
@jhechtf Do you use it from javascript? If then, https://swc.rs/docs/configuring-swc.html#jscexternalhelpers will help.
All options in `.swcrc` files are also supported from `@swc/core`, so you can specify option in similar way.

I think reading description of https://github.com/microsoft/tslib will help understanding results. (I'm not english native and have limitations in explaining)

**Comment by kdy1** [comment]
Closing as not suitable for issue. I enabled github discussion for swc, so please use it instead.
