### ISSUE TITLE
Usage without node.js

### ISSUE THREAD

**Issue by jeromegn** [swc-project/swc#125]
Is it possible to use swc from rust directly?

We're building https://github.com/superfly/fly.rs and would like to bundle code (typescript and javascript) via swc.

As far as I can tell, the node implementation is a wrapper around swc, but it should work from rust too, right?

**Comment by jeromegn** [comment]
Nevermind, I figured it out from node-swc's native folder.

**Comment by kdy1** [comment]
Also note that node-swc uses Cargo.lock file to manage version of the swc.

I don't want to publish swc on crates.io because managing it would be too complex.
