### ISSUE TITLE
How to use jsx factories with typescript?

### ISSUE THREAD

**Issue by brielov** [swc-project/swc#1250]
I'm trying to upgrade my react template app to use swc instead of babel. This template is currently configured to use jsx factories (it doesn't need React in scope). Is this feature supported? Babel has a `runtime: "automatic"` option.

**Comment by kdy1** [comment]
I'm working on it at https://github.com/swc-project/swc/pull/1223

**Comment by brielov** [comment]
@kdy1 Thanks! One more thing, my template also has configured react's `fast refresh` through `react-refresh/babel`. Is this something you are looking to implement in the future?

**Comment by kdy1** [comment]
Of course. But I'm busy these days.

**Comment by brielov** [comment]
@kdy1 awesome, thanks for responding so quickly 🍻

**Comment by brielov** [comment]
@kdy1 Any news on this?

**Comment by kdy1** [comment]
It's implemented. I forgot documenting it, though.

**Comment by brielov** [comment]
@kdy1 Can you share how to use it here until it gets documented? I have a react template that depends on factories and fast-refresh.

**Comment by kdy1** [comment]
@brielov I added some docs at https://swc.rs/docs/configuring-swc/#jsctransformreact
But fast refresh isn't released yet. I'll release a new version within a week.
