### ISSUE TITLE
syntax errors and incorrect exports produced by spack when encountering reserved name

### ISSUE THREAD

**Issue by jeremyBanks** [swc-project/swc#1254]
**Describe the bug**

In some cases, spack can generate invalid syntax such as

```ts
const instanceof = mod.instanceof;
```

This is invalid because `instanceof` is a context-dependent keyword that is not allowed to be used as a variable name, though it is allowed to be used as a property name and export name.

In some cases, spack instead appears to omit exports with such names, which also causes the program to fail:

```js
const mod = function() {
    var a = "hello world";
    return {
    };
}();
```

I encountered this trying to use [Deno](http://deno.land/) with [Zod](https://github.com/colinhacks/zod/), but have a reduced example:

**Input code**

#### `main.ts`
```ts
import {instanceof as x} from "./dep.ts";
// Second import is required, otherwise the value is inlined instead of
// being put in an invalid local variable.
import * as y from "./dep.ts";

console.log(x);
```

#### `dep.ts`
```ts
const a = "hello world";
export { a as instanceof };
```

**Config**
#### `spack.config.js`
```js
const { config } = require('@swc/core/spack')

module.exports = config({
    entry: {
        web: __dirname + '/main.ts',
    },
    output: {
        path: __dirname + '/lib'
    },
    module: {},
});
```

**Actual output**

Observe the invalid variable name and missing export noted above.

```js
const mod = function() {
    var a = "hello world";
    return {
    };
}();
const instanceof = mod.instanceof;
console.log(instanceof);
```

**Expected behavior**
Something like this:

```js
const mod = function() {
    var a = "hello world";
    return {
        instanceof: a
    };
}();
const instanceof_ = mod.instanceof;
console.log(instanceof_);
```

**Version**
```
 % npx spack --version  
@swc/cli: 0.1.27
@swc/core: 1.2.40
```

**Additional context**
Encountered while working on https://github.com/colinhacks/zod/pull/209.

**Comment by jeremyBanks** [comment]
Not specific to TypeScript. Reproduces the same in 0.1.26.

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/swc-project/swc/pull/1296
