### ISSUE TITLE
Fails to load in yarn 2 PnP

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#1265]
**Describe the bug**

@swc/core does not load under yarn 2 PnP.

The root cause is in `@node-rs/helpers`, but once it's fixed, it will require a tiny code change in `@swc/core`

Here is a description of the root cause of the failure.
https://github.com/napi-rs/node-rs/issues/263

Once the root cause is fixed, `@swc/core` will need to adjust it's `loadBinding` call like this:
https://github.com/swc-project/swc/blob/master/node-swc/src/index.ts#L14

```
const bindings = loadBinding(__dirname, "swc", "@swc/core", require)
```

**Input code**

N/A

**Config**

N/A

**Expected behavior**

`require('@swc/core')` succeeds when installed via yarn PnP.

**Version**
The version of @swc/core: 1.2.40

**Additional context**

**Comment by Brooooooklyn** [comment]
I will fix it in https://github.com/swc-project/swc/pull/1244
