### ISSUE TITLE
Use @swc/core with wasm, when native modules cannot / should not be used

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#1275]
**Describe the feature**

On some projects, native code cannot / should not be used for various reasons.  For example, yarn2 would like to compile with swc but their project is configured so that they can't rely on native modules.

It would be nice if @swc/core automatically uses the WASM build when the native modules are not available.

Alternative, is there a way to configure @swc/core to use the WASM build today?

Related discussion on yarn2 pull request to use swc compilation: https://github.com/yarnpkg/berry/pull/2228#discussion_r541941283

**Comment by kdy1** [comment]
Closing as

 - API of the wasm cannot match those of `@swc/core` because of restrictions of wasm. (File api does not exists)
 - It requires downloading wasm version of swc even if not required , or build-script based detection of runtime.
