### ISSUE TITLE
Unable to transform private fields with decorators

### ISSUE THREAD

**Issue by snewcomer** [swc-project/swc#1304]
**Problem**

When transpiling private class [fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) with decorators, I get an error - `not implemented: ClassMember::PrivateProp(PrivateProp...`

Run from command line `npx swc index.js`

**Input code**

```
// index.js
function cache(target, key, value) {
  return {
    get() {
      return value;
    }
  }
}

class Life {
  #friends = true;

  @cache // remove this and see private class field transpile without errors
  get happy() {
    return this.#friends;
  }
}
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "decorators": true,
      "dynamicImport": true,
      "classPrivateProperty": true
    }
  },
  "env": {
    "targets": {
      // not important
      "chrome": "80"
    }
  }
}
```

**Expected behavior**

I expect private class fields to also transpile with decorators.  Note - the above code compiles fine without decorators.

**Version**

The version of @swc/core: latest

**Comment by kdy1** [comment]
Closing as fixed.
https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAz2OUQqDMBBE%2F3OKgf4oSD2AFHqAXiLETROaxrBZLVK8ezVaPxaG3bczY8doxA8RRhtHlWh%2BkjR40dxg0mGkGl8FMMnIsUhgJar60OepwF3ZLWqbRSkTdM54eEuFvlj2FPuMG4Q3eN3dSy7advV5DxNBnM%2FQsUcmQmI%2FaSHsRtZT6NdXHXPygfDx4oZRQMwDZ1WKwemU5rPeUW4zvf7ju73eDxBLL9n6AAAA&config=H4sIAAAAAAAAA0WOQQ7DIAwE%2F%2BJzru2BP%2FQRFnEiqoCR7UhFiL8XUNrcrPXs2BXe6sFVyChKMiYtyfADDqxkUi8hGyxg2qMND6UFVvIsaCwKzuSk1tcoO1kvkT46fTAr%2FfkYUtjKcHuOWUj1XmHajx%2FZuijyeo6gzvNT%2BIR2O65e0NcFzge%2BGhPNuMcAAAA%3D
