### ISSUE TITLE
Plugin system rewrite for swc and spack

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#1321]
# swc

We should 

  - [ ] Allow specifying plugin in `.swcrc` file.
 
This requires calling js function from rust. See https://docs.rs/napi/1.1.1/napi/struct.JsFunction.html for apis for it.
We should create a `sync::channel` and call the stored js function javascript thread because the javascript function is not `Send` nor `Sync`.

 - [ ] Support calling babel plugins

It can done by converting the ast of `swc` into the one of babel. As ast node of babel does not have methods, so converting to json using newtype structs will work.

# spack

 - [ ] Allow writing plugin with javascript

Requirement is same as above.

 - [ ] Allow using webpack plugins.

I'm not sure how hard this will be.

**Comment by mfeckie** [comment]
What format would the plugins take in `.swcrc`?

```
{
  "plugins" [] //
}
```

**Comment by kdy1** [comment]
@mfeckie 

It should be string for now. In future, we may add support for javascript functions within `.swcrc.js`, just like babel.

**Comment by mfeckie** [comment]
```json
{
  "plugins" ["my-plugin"]
}
```
The user would have this item in their `package.json`

```json
  "my-plugin": "x.x.x"
```

And `my-plugin` would be built and published via `napi-rs` or would it be plain JS and `napi-rs` would only be used withing `swc` to make it callable?

**Comment by kdy1** [comment]
I think plugins should be written in plain javascript.

The ast definition changes over time, and it means native binaries should be rebuilt frequently. It's bad for plugin users.

**Comment by dwoznicki** [comment]
> Allow using webpack plugins.

I'm quite interested in spack as a replacement for webpack. I can look into this unless someone else is.

**Comment by kdy1** [comment]
Are you guys working on this?
I'm asking this because I'm going to work on this if nobody is working on it.

**Comment by mfeckie** [comment]
I have not got far. I was only still reading about napi-rs.

Would be faster if you do it!

**Comment by dwoznicki** [comment]
Yeah, I haven't gotten far either. I've managed to get `bundle()` to accept an array of plugin functions and execute them in Rust, but I'm still trying to figure out the internals of webpack's plugin system. [Here's the small amount I've done so far](https://github.com/dwoznicki/swc/blob/3d6a7c6772c9979e1bb35bb12cebb7ca519ca7ac/native/src/bundle.rs#L159-L174), it's any help.

**Comment by mischnic** [comment]
Are there plans to support plugins written in Rust?

**Comment by kdy1** [comment]
@mischnic No. Managing two plugin APIs is too much for now.
