### ISSUE TITLE
typescript conversion

### ISSUE THREAD

**Issue by Japroz-Saini** [swc-project/swc#1323]
**Question**
Hi, can anyone please send me a code snippet on how to convert a typescript file to javascript using this library.

**Comment by kdy1** [comment]
What is the language are you using?
swc is rust library and js library at same time.

**Comment by Japroz-Saini** [comment]
I am using it in a rust project

**Comment by kdy1** [comment]
@Japroz-Saini
Then `module.fold_with(&mut swc_ecma_transforms::typescript::strip())` would be enough.
Note that you should enable a cargo feature named 'typescript'.

**Comment by Japroz-Saini** [comment]
I didn't understand. For example ,i read a file and stored in a variable called code. How would I convert that typescript file to javascript and how can I enable the typescript feature in the cargo.toml file

**Comment by kdy1** [comment]
See ecmascript/parser/examples/typescript for parsing code, and you can just do `module.fold_with(&mut swc_ecma_transforms::typescript::strip())` to convert it to javascript ast.
Finally use swc_ecma_codegen to convert it into the javascript code.
