### ISSUE TITLE
Support Typescript 4.2

### ISSUE THREAD

**Issue by soilSpoon** [swc-project/swc#1327]
**Describe the feature**
`Typescript 4.2 beta` has been released.
Please prepare support for `Typescript 4.2` version.

**Additional context**
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2-beta/

**Comment by kitsonk** [comment]
I've run several changes in the release note through master...  The only thing that swc seems to have a problem with is [Abstract Construct Signatures](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2-beta/#abstract-construct-signatures).  The following appears to get mis-lexed:

```ts
abstract class Shape {
  abstract getArea(): number;
}

let Ctor: abstract new () => HasArea = Shape;
