### ISSUE TITLE
Issue with accessing private properties

### ISSUE THREAD

**Issue by MeLike2D** [swc-project/swc#1333]
**Describe the bug**

Files using the private syntax don't get transformed to use the `_classPrivateFieldGet` helper. Or in some cases, only a few get transformed.

Example:
```js
get connected() {
        return _classPrivateFieldGet(this, _ws2) && this.#ws.readyState === _ws1.default.OPEN;
}
```

**Input code**

<https://github.com/neo-cord/neocord/tree/dev/src>

**Config**
```json
[
  {
    "test": [
      ".*.js"
    ],
    "jsc": {
      "target": "es2019",
      "parser": {
        "dynamicImport": true,
        "syntax": "ecmascript"
      }
    },
    "module": {
      "type": "commonjs"
    }
  },
  {
    "test": [
      ".*.ts"
    ],
    "jsc": {
      "target": "es2019",
      "parser": {
        "syntax": "typescript"
      }
    },
    "module": {
      "type": "commonjs"
    }
  }
]
```

**Expected behavior**
Everything to be transformed.

**Version**
The version of @swc/core: 1.2.45

**Comment by kdy1** [comment]
@MeLike2D Can you point the file which causes the error?

**Comment by MeLike2D** [comment]
> @MeLike2D Can you point the file which causes the error?

sure, https://www.github.com/neo-cord/neocord/tree/dev/src/client/gateway/Shard.js
and https://www.github.com/neo-cord/neocord/tree/dev/src/client/rest/RequestHandler.js

_note: these are the only ones I looked at_
