### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by teymour-aldridge** [swc-project/swc#1336]
**Describe the feature**
I'm finding that documentation is quite sparse which is really slowing things down when trying to use some of the crates that have been written.
I think it would be useful to have documentation for:
 - [ ] JavaScript users (documentation for this aspect looks to better, but I'm not using swc for a project written in Javascript so I'm not sure)
 - [ ] Rust users (people consuming the libraries)
I also think that there are some things which will be helpful to have in order to gain greater adoption:
 - [ ] Tutorials (for people consuming it, a more in-depth guide to writing plugins both on the JS and the Rust side)
 - [ ] More documentation about the general architecture
**Babel plugin or link to the feature description**

**Additional context**
I'd like to write (and am happy to review) this – I appreciate that you're already doing a lot with relatively few people!

**Comment by shadowtime2000** [comment]
+1 to more docs for Rust users
