### ISSUE TITLE
Webpack to spack plugin integration

### ISSUE THREAD

**Issue by dwoznicki** [swc-project/swc#1339]
## Webpack plugin API
A webpack plugin is a class (or prototype function) that implements an `apply` function. The `apply` function takes the webpack compiler instance as an argument, which provides an API for adding hooks to the compilation process. Hooks are expected to modify some aspect of the data, and allow the compilation to continue.

#### Example plugin
```javascript
class HelloWorldPlugin {
    apply(compiler) {
        compiler // <-- top-level static object, responsible for kicking off compilation, bundling, etc. 
            .hooks // <-- where plugins can register
            .initialize // <-- executed during initialization step
            .tap(compilation => { // <-- "tap" call means this hook is synchronous
                console.log("Hello cruel world!");
            });
    }
}
```

See webpack [Writing a Plugin document](https://webpack.js.org/contribute/writing-a-plugin/) for more info.

## About hooks
Hooks are provided by the [tapable library](https://github.com/webpack/tapable). There are multiple types of hooks available, each with small variations. [Here's a link to the documentation.](https://github.com/webpack/tapable#hook-types) Some to note:
- SyncHook: Executes functions synchronously.
- SyncBailHook: Executes functions synchronously, with expected return value.
- AsyncSeriesHook: Executes functions asynchronously, one after another.
- AsyncParallelHook: Executes functions asynchronously and at the same time.

## Available hooks
Different objects in the webpack system implement the tapable interface.

The following are a list of webpack hooks, listed in order of execution, on each object which provides them.

### Compiler hooks
- environment (SyncHook(), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/webpack.js#L74)): Called after compiler has been created.
- afterEnvironment (SyncHook(), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/webpack.js#L75)): Called right after environment hook.. not sure why this one exists.
- entryOption (SyncBailHook(context, entry), [link](https://github.com/webpack/webpack/blob/c80c8fe5c2dd0f2ec27ffa145b61a7e4163eddb0/lib/WebpackOptionsApply.js#L248)): Called after `entry` has been parsed from config.
- afterPlugins (SyncHook(compiler), [link](https://github.com/webpack/webpack/blob/c80c8fe5c2dd0f2ec27ffa145b61a7e4163eddb0/lib/WebpackOptionsApply.js#L547)): Called after plugins have been initialized.
- afterResolvers (SyncHook(compiler), [link](https://github.com/webpack/webpack/blob/c80c8fe5c2dd0f2ec27ffa145b61a7e4163eddb0/lib/WebpackOptionsApply.js#L573)): Called after resolvers have been setup.
- initialize (SyncHook(), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/webpack.js#L77)): Called after compiler object has been setup.
- beforeRun (AsyncSeriesHook(compiler), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L462)): Called before compilation is started.
- run (AsyncSeriesHook(compiler), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L465)): Also called before compilation is started.
- watchRun (AsyncSeriesHook(compiler), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/Watching.js#L66)): In watch mode, called before run.
- normalModuleFactory (SyncHook(normalModuleFactory), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L1004)): Called after `NormalModuleFactory` is created.
- contextModuleFactory (SyncHook(contextModuleFactory), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L1010)): Called after `ContextModuleFactory` is created.
- beforeCompile (AsyncSeriesHook(compilationParams), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L1028)): Called after compilation parameters have been created. [Can be used to modify compilation parameters.](https://webpack.js.org/api/compiler-hooks/#beforecompile)
- compile (SyncHook(compilationParams), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L1031)): Called before compilation starts.
- make (AsyncParallelHook(compilation), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L1038)): Called after compilation has started, but before it's finished.
- afterCompile (AsyncSeriesHook(compilation), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L1059)): Called after compilation is finished and sealed.
- shouldEmit (SyncBailHook(compilation), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L399)): Called before output is written to filesystem. If function returns false, will not emit compiled assets.
- emit (AsyncSeriesHook(compilation), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L811)): Called before writing output.
- afterEmit (AsyncSeriesHook(compilation), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L802)): Called after writing output.
- assetEmitted (AsyncSeriesHook(file, info), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L667)): Called for each file after it has been written to file system.
- done (AsyncSeriesHook(stats), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L403)): Called after compilation is completed.
- additionalPass (AsyncSeriesHook(), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L428)): Called after finishing, allowing you to do any additional work.
- failed (SyncHook(error), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L386)): Called when compilation fails for whatever reason.
- invalid (SyncHook(fileName, changeTime), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/Watching.js#L252), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/Watching.js#L271)): In watch mode, called when compilation has been invalidated (due to file change, etc.).
- watchClose (SyncHook(), [link](https://github.com/webpack/webpack/blob/fd056e27f477e364c16d1b09b39905fce28c13ca/lib/Watching.js#L323)): In watch mode, called when stopped.
- infrastructureLog (SyncBailHook(name, type, args), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L289)): Called when something tries to log infrastructure info.
- log (SyncBailHook(origin, logEntry), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1042)): Called when something tries to log.

Reference: https://webpack.js.org/api/compiler-hooks/
Source: https://github.com/webpack/webpack/blob/c0573a7e9c1edf5ed8e65c141303eebbb27f59b7/lib/Compiler.js

### Compilation hooks
- buildModule (SyncHook(module), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1236)): Called before a module has been built. [Can be used to modify the module.](https://webpack.js.org/api/compilation-hooks/#buildmodule)
- rebuildModule (SyncHook(module), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1856)): Called before rebuilding a module.
- failedModule (SyncHook(module, error), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1248), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1259)): Called when module fails to build.
- succeedModule (SyncHook(module), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1262)): Called when module builds successfully.
- finishModules (AsyncSeriesHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1896)): Called when all modules are built successfully.
- finishRebuildingModule (SyncHook(module), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1863), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1880)): Called when module has finished rebuilding, with success or error.
- seal (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1954)): Called when compilation stops accepting new modules.
- unseal (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1930)): Called when compilation begins accepting new modules.
- optimizeDependencies (SyncBailHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1957)): Called to optimize dependencies.
- afterOptimizeDependencies (SyncHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L1960)): Called after dependencies have been optimized.
- optimize (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2094)): Called before general optimization begins.
- optimizeModules (SyncBailHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2096)): Called to optimize modules.
- afterOptimizeModules (SyncHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2099)): Called after modules have been optimized.
- optimizeChunks (SyncBailHook(chunks), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2101)): Called to optimize chunks.
- afterOptimizeChunks (SyncHook(chunks), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2104)): Called after chunks have been optimized.
- optimizeTree (AsyncSeriesHook(chunks, modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2106)): Called to optimize dependency tree.
- afterOptimizeTree (SyncHook(chunks, modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2113)): Called after dependency tree has been optimized.
- optimizeChunkModules (AsyncBailHook(chunks, modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2115)): Called to optimize chunk modules.
- afterOptimizeChunkModules (SyncHook(chunks, modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2125)): Called after chunk modules have been optimized.
- shouldRecord (SyncBailHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2127)): Called to determine if modules, chunks, etc. should be recorded.
- reviveModules (SyncHook(modules, records), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2129)): Called to restore module info from records.
- beforeModuleIds (SyncHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2130)): Called before modules are assigned an ID.
- moduleIds (SyncHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2131)): Called to assign an ID to each module.
- optimizeModuleIds (SyncHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2132)): Called to optimize module IDs.
- afterOptimizeModuleIds (SyncHook(modules), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2133)): Called after module IDs have been optimized.
- reviveChunks (SyncHook(chunks, records), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2135)): Called to restore chunk information from records.
- beforeChunkIds (SyncHook(chunks), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2136)): Called before chunks are assigned an ID.
- chunkIds (SyncHook(chunks), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2137)): Called to assign an ID to each chunk.
- optimizeChunkIds (SyncHook(chunks), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2138)): Called to optimize chunk IDs.
- afterOptimizeChunkIds (SyncHook(chunks), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2139)): Called after chunk IDs have been optimized.
- recordModules (SyncHook(modules, records), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2146)): Called to store modules in records.
- recordChunks (SyncHook(chunks, records), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2147)): Called to store chunks in records.
- beforeHash (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2175)): Called before compilation hash is created.
- afterHash (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2177)): Called after compilzation hash is created.
- recordHash (SyncHook(records), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2182)): Called to store compilatoin hash in records.
- beforeModuleAssets (SyncHooks(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2189)): Called before module assets are created.
- shouldGenerateChunkAssets (SyncBailHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2234)): Called to determine if chunk assets should be created. If function returns false, will not create.
- beforeChunkAssets (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2235)): Called before chunk assets are created.
- processAssets (AsyncSeriesHooks(assets), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2195)): Called to add/modify file assets. This one is... pretty involved. And the API appears to be in flux. Search for "processAssets" on [this page](https://webpack.js.org/api/compilation-hooks/) for details.
- afterProcessAssets (SyncHook(assets), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2201)): Called after assets have been processed.
- record (SyncHook(compilation, records), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2214)): Called to record compilation in records.
- needAdditionalSeal (SyncBailHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2217)): Called to determine if compilations needs to be unsealed to add additional assets.
- afterSeal (AsyncSeriesHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2221)): Called if needAdditionalSeal was true.
- shouldGenerateChunkAssets (SyncBailHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2234)): Called to determine if chunk assets should be created. If function returns false, assets will not be created.
- beforeChunkAssets (SyncHook(), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L2235)): Called before chunk assets are created.
- assetPath (SyncWaterfallHook(path, options), [link](https://github.com/webpack/webpack/blob/fa5cc4500d9717c7e06cf970035351cbb8b915f8/lib/Compilation.js#L3493)): Called to determine the path of an asset.
- needAdditionalPass (SyncBailHook(), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L417)): Called to determine if additional pass is necessary.
- childCompiler (SyncHook(childCompiler, compilerName, compilerIndex), [link](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compiler.js#L965)): Called after a child compiler has been created.

Reference: https://webpack.js.org/api/compilation-hooks/
Source: https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Compilation.js

### Parser hooks
I'm not completely sure what this is, and there [appear to be quite a few of them](https://github.com/webpack/webpack/search?q=extends+Parser) within the webpack project. These include a whole other set of hooks, which I'm not going to document now because I'm getting lazy.

Reference: https://webpack.js.org/api/parser/
Source: https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Parser.js

**NOTE**: There are several more undocumented hooks in the actual code. It's not clear if these are experimental, deprecated, or internal only.

## Analysis
Making spack compatible with webpack plugins would probably require us to implement a considerable amount of the webpack infrastructure. Webpack plugins rely on webpack internals, such as the [NormalModuleFactory](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/NormalModuleFactory.js) and [chunks](https://github.com/webpack/webpack/blob/3ef285bda957c81f562d967d6b182fdbf8e717ed/lib/Chunk.js) to work properly. I'm not sure how much would need to change about the current version of swc/spack (I haven't fully grokked the project), but my guess is quite a bit.

Thoughts, @kdy1 ?

Related: #1321

**Comment by kdy1** [comment]
It would require lots of work, but I'm sure that it worths the effort.

**Comment by dwoznicki** [comment]
Cool, just wanted to check that you were still okay with this before continuing onward. I think that making spack compatible with webpack plugins is the best option as well.

Are you okay with me working on this, or would you prefer to do it yourself? I'm happy to do it, but it will probably take me a lot longer.

**Comment by kdy1** [comment]
@dwoznicki I'd really love it if you can work on this. I'll help as much as I can. Just ping me on github, slack or discord when you need any help.

**Comment by dwoznicki** [comment]
@kdy1 How do you feel about this feature now? I know before you wanted to support Babel/Webpack plugins, but it sounds like you're thinking of having the AST plugin system in Rust land (which I assume means swc won't support Babel plugins). How do you feel about doing the same for the bundler (formerly known as spack)?

**Comment by kdy1** [comment]
@dwoznicki I'm considering something similar for the bundler, too. Node js api does not provide a good way to get results of js function from native side.

**Comment by dwoznicki** [comment]
Cool. For what it's worth, I think a Rust plugin system for the bundler is a better way to go for a number of reasons beyond speed. I'm going to close this issue for now then.
