### ISSUE TITLE
Rollup Plugin

### ISSUE THREAD

**Issue by shadowtime2000** [swc-project/swc#1344]
**Describe the feature**
It would be nice to have a Rollup plugin for SWC.

**Babel plugin or link to the feature description**
N/A

**Comment by kdy1** [comment]
I think there's already one out there, but it's not official and I don't have a link to it.

**Comment by shadowtime2000** [comment]
Yeah I think there is a `rollup-plugin-swc` but an official one would be pretty cool

**Comment by kwonoj** [comment]
Closing, looks like there's an userland fulfills ecosystem.
