### ISSUE TITLE
Exclude files through wildcard patterns

### ISSUE THREAD

**Issue by josteph** [swc-project/swc#1350]
**Describe the feature**
More aggressive exclude/ignore files pattern matching.

**Babel plugin or link to the feature description**
Related to https://github.com/swc-project/swc/issues/466 but it should cover this kind of pattern instead:

.swcrc
```
{
  exclude: ["**/__tests__/**"]
}
```

Folder structure path
```
src/auth/__tests__
```

The expected output: `__tests__` folder will not be transformed and exported into the out dir folder.

**Comment by kdy1** [comment]
It's already supported by swc. See: https://swc.rs/docs/configuring-swc/#exclude

**Comment by josteph** [comment]
@kdy1 it only supports through specifying extensions afaik, does it also support excluding folder through glob patterns?

**Comment by kdy1** [comment]
Yes. As it's a regular expression, you can exclude a folder using it.

**Comment by josteph** [comment]
One more question, how do you make `--copy-files` respect `exclude` option?

**Comment by kdy1** [comment]
<del>It's currently not possible.</del>

I patched `@swc/cli` to respect `.swcrc`. Updating cli to `v0.1.34` will do the trick.

Note that it may take some time for the new version to be installable.

**Comment by Gervwyk** [comment]
> One more question, how do you make `--copy-files` respect `exclude` option?

Did you manage to find a setting to exclude files while using `--copy-files`?  It unfortunately copies snapshot files.

**Comment by josteph** [comment]
I created my own `copyFiles` function:

```
const cpy = require('cpy');
const relativeOutDir = path.relative(srcPath, outDir);

await cpy(['**', `!**/*.{snap,ts,js,tsx,jsx}`], relativeOutDir, {
   cwd: srcPath,
   parents: true,
});
```
