### ISSUE TITLE
single quote transform error

### ISSUE THREAD

**Issue by joebnb** [swc-project/swc#1358]
swc will transform single quotes ' to \\'  in double quotes.

<a href="abc'def'">
to
<a href="abc\\'def\\'">

![image](https://user-images.githubusercontent.com/1646883/105669908-1ff77980-5f1b-11eb-80e0-5abfb3ea60d7.png)

**Comment by kdy1** [comment]
Please post some input and .swcrc

**Comment by joebnb** [comment]
> Please post some input and .swcrc

```json
            {
                loader: 'swc-loader',
                options: {
                    jsc: {
                        parser: {
                            syntax: 'typescript',
                            decorators: true,
                            dynamicImport: true,
                        },
                        transform: {
                            legacyDecorator: true,
                            decoratorMetadata: true,
                        },
                    },
                },
            },
```

**Comment by kdy1** [comment]
Cannot reproduce it.

Do you use windows?

**Comment by joebnb** [comment]
no , it's happen on  a mac,and thise lines in   html  template attribute
```
<div style='font-family:\'font name\'''></div>
```
i  have off work, error detail need tomorrow to post

**Comment by kdy1** [comment]
@joebnb Then I'll fix this tomorrow :)

**Comment by joebnb** [comment]
source:
```html
<span style="font-size:10px;font-family:&#39;Arial&#39;,&#39;sans-serif&#39;;color:gray">
texts
</span>
```
and i tried use ' to replace numeric reference character,the error still.

output and stack:

![image](https://user-images.githubusercontent.com/1646883/106343216-42084780-62df-11eb-8226-d142bffb3476.png)

![image](https://user-images.githubusercontent.com/1646883/106343771-0327c100-62e2-11eb-8cd8-f07686bf092e.png)

**Comment by joebnb** [comment]
this error seem not cause by this line ,bacuese use ts and ts-loader the output are same of this line 
```html
<span style="font-size:10px;font-family:&#39;Arial&#39;,&#39;sans-serif&#39;;color:gray">
texts
</span>
```
and remove this tyle,other lines will throw error
![image](https://user-images.githubusercontent.com/1646883/106346570-142cfe00-62f3-11eb-8462-543191ed7808.png)
this line hard to location

**Comment by joebnb** [comment]
i'm trying to init a empty angular project to reproduce it,but swc works well with same config.and i'm trying to use ngcc(@angular/compiler-cli) to compile node_modules(output es2015 moudues) and the error stack change to zone.js,the code also in VM and stack like above out put(in runtime compiler.js) ,it's hard to debug by design.

i still think swc have some different behavior with typescript compiler(typescript transpiled works),but debug in angular too hard.

i also use dichotomy to debug this project,but i didn't finish today,i will continue i some spare time.this issue seems no valuable infomation about this problem, i think should close now.


--------------
here is the stack error after ngcc for reference
![image](https://user-images.githubusercontent.com/1646883/106351539-e8703f00-6317-11eb-99fe-0d75ca7a885a.png)

![image](https://user-images.githubusercontent.com/1646883/106351530-d1315180-6317-11eb-9459-1e420d9e32a6.png)
