### ISSUE TITLE
Bug: swc incorrectly un-strings object keys with periods in them

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#137]
Try running swc on the following js:

```js
const x = {
  'foo.bar': true
}
```

It will output

```js
'use strict';
var x = {
        foo.bar: true
};
```

The `foo.bar` is not correct syntax. swc needs to keep string object keys that contain js special characters as strings. It's probably easier to just keep all string object keys as strings.

**Comment by kdy1** [comment]
Thank you for the reporting an issue.
I fixed this with swc@1.0.1
