### ISSUE TITLE
Minification could be improved?

### ISSUE THREAD

**Issue by kaushalyap** [swc-project/swc#1371]
As seen in https://github.com/privatenumber/minification-benchmarks SWC minfication ability is comparatively low. Can this be improved?

**Comment by kdy1** [comment]
I'm already working on it.
See: https://github.com/swc-project/swc/pull/1302
I'm basically porting terser, with some additional rules from closure compiler.

**Comment by kdy1** [comment]
I made an issue about it at https://github.com/privatenumber/minification-benchmarks/issues/6

**Comment by IllusionPerdu** [comment]
I see the code for the benchmark for the esbuild is 

```js
import esbuild from 'esbuild';
import measure from './measure.js';

const service = await esbuild.startService();

await measure(async ({ code }) => {
	const minified = (await service.transform(code, {
		minify: true,
		sourcemap: false,
	}));
	return minified.code;
});

service.stop();
```
I think it would be nice to do the equivalent of the "esbuild.startService" function to initialize the wasm of swc.
This would allow the performance of swc to be measured without loading the wasm.
