### ISSUE TITLE
Exponentiation operator does not get transpiled for targets IE 11

### ISSUE THREAD

**Issue by lephuongbg** [swc-project/swc#1377]
**Describe the bug**

The exponentiation operator does not get transpiled when targeting IE 11 or even when using `forceAllTransforms`.

**Input code**

```
export const value = 2**2
```

**Config**
```json
{
    "env": {
        "targets": {"ie": "11"},
        "forceAllTransforms": true
    }
}
```

**Expected behavior**

The exponentiation operator should be transformed into `Math.pow` call.

**Version**
The version of @swc/core: 1.2.47

**Comment by shadowtime2000** [comment]
I think I can try to take a go at this

**Comment by kdy1** [comment]
This is because ie 11 is not supported anymore.
This is same as babel.

See: https://github.com/babel/babel/blob/b12a4de45703156246fddf562a751b72005501d4/packages/babel-compat-data/data/plugins.json#L159-L169
