### ISSUE TITLE
Bug: swc does not import the `_interopRequireDefault` function when it is referenced

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#138]
If you try compiling the following with swc:

```
import Foo from 'bar';
```

You get this:

```
'use strict';
var _bar = _interopRequireDefault(require('bar'));
```

The function `_interopRequireDefault` is referenced, though never defined, leading to `ReferenceError`s.

There are other functions that have the same behavior: 

- `_interopRequireWildcard`

Expected: If swc inserts references to functions, it will define or import those functions.

Actual: swc references numerous functions that it does not define/import.

**Comment by kdy1** [comment]
Thank you for the reporting an issue.
I fixed this with swc@1.0.1
