### ISSUE TITLE
How to add custom syntax/operators/keywords to JavaScript with swc?

### ISSUE THREAD

**Issue by faramozzayw** [swc-project/swc#1380]
I would like to add some custom operators, keywords, and syntax to Javascript (e.g. [range expression](https://doc.rust-lang.org/reference/expressions/range-expr.html) from Rustlang).

Is this possible with `swc`?

**Comment by kdy1** [comment]
It's not possible

**Comment by faramozzayw** [comment]
okay :( thanks for the quick reply!
