### ISSUE TITLE
How do I specify environment target?

### ISSUE THREAD

**Issue by miqdadfwz** [swc-project/swc#1385]
**Question**
Hi first of all thank you for the project, I really appreciate your time to build this breaking through library. However I have two questions regarding of spack:

1. How do I define option to instruct spack to bundle in node/browser environment?
2. Also, is there any option to exclude `node_modules` which should not to be part of compilation process?

Thanks.

**Comment by kdy1** [comment]
For 1, spack does not support it currently.

For 2, if you mean something like an external module of other bundler, it's not supported at the moment.

**Comment by miqdadfwz** [comment]
For no 2, yes I mean excluding certain import (commonly from `node_modules`) from bundle, like `externals` API from webpack.

**Comment by wycats** [comment]
@kdy1 it seems like `external_modules` was added to the Rust API in https://github.com/swc-project/swc/pull/1349. Is it just a matter of adding support to the JavaScript wrapper, or is it more involved that that?

**Comment by kdy1** [comment]
@wycats I missed the email. It's easy stuff, as bundler already supports it. I'll fix it with next release.
