### ISSUE TITLE
cwd, source_root, and source_file_name options do not have any effect

### ISSUE THREAD

**Issue by kherock** [swc-project/swc#1388]
**Describe the bug**
I was trying to figure out why certain options in the CLI weren't working but it looks like the transform functions simply don't do anything with the options listed in the PR title.

**Input code**
```console
> swc = require('@swc/core');
> swc.transformSync('var foo = 1;\nexport { foo };\n', { sourceMaps: true, sourceRoot: '..', sourceFileName: 'foo'  })
{
  code: 'var foo = 1;\nexport { foo };\n',
  map: '{"version":3,"sources":["<anon>"],"sourcesContent":["var foo = 1;\\nexport { foo };\\n"],"names":[],"mappings":"IAAA,GAAA,GAAA,CAAA;SACA,GAAA"}'
}

> swc.transformFileSync('fixtures/amd.js', { sourceMaps: true, cwd: 'out', sourceRoot: '..' })
{
  code: 'var foo = 1;\nexport { foo };\n',
  map: '{"version":3,"sources":["fixtures/amd.js"],"sourcesContent":["\\nconst foo = 1;\\nexport { foo };"],"names":[],"mappings":"IACA,GAAA,GAAA,CAAA;SACA,GAAA"}'
}
> swc.transformFileSync('../fixtures/amd.js', { sourceMaps: true, cwd: 'out' })
thread '<unnamed>' panicked at 'failed to load file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', native/src/transform.rs:158:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Config**
```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript"
        }
    },
    "module": {
        "type": "commonjs"
    }
}
```

**Expected behavior**
Here, I'd expect `"sources"` to not have an anonymous filename, and `"sourceRoot"` should be set to `".."`. When a `cwd` is passed to `transformFileSync`, the source file in the sibling directory should resolve with a path relative to `cwd`.

**Version**
The version of @swc/core: 1.2.47

**Additional context**
I'm currently fighting this when trying to use `@swc/cli` as a drop-in replacement for `tsc`, TypeScript generates its maps using paths relative to the output directory, but currently the only way to achieve the same effect with swc is by starting the process from the output directory itself.

**Comment by realtimetodie** [comment]
I am working on this

Related
- https://github.com/swc-project/swc/pull/6817
- https://github.com/aspect-build/rules_swc/issues/146

**Comment by realtimetodie** [comment]
@kdy1 This can be marked as resolved.

**Comment by kdy1** [comment]
Thank you!
