### ISSUE TITLE
Bus Error When Using bundle API from @swc/core

### ISSUE THREAD

**Issue by miqdadfwz** [swc-project/swc#1389]
**Describe the bug**
I was working to build internal build tools using `bundle` API taken from `@swc/core`, but in certain modules it will throw error complaining bus error.

<img width="640" alt="Screen Shot 2021-02-10 at 09 03 31" src="https://user-images.githubusercontent.com/43945767/107454790-3f7bdc80-6b80-11eb-9732-078b923bc138.png">

**Input code**
```js
const { bundle } = require('@swc/core');
const { pcwd } = require('../../utils/path');

const build = async config => {
  const timerStart = Date.now();
  const cwdPaths = pcwd.split('/');
  const packageName = `${cwdPaths[cwdPaths.length - 2]}/${cwdPaths[cwdPaths.length - 1]}`;

  const handler = async () => {
    try {
      await bundle(config);
    } catch (error) {
      console.error(`❌  An error happened while trying to run Babel build for "${packageName}"`);
      console.error(error);
    } finally {
      const timerEnd = Date.now();
      console.log(`✅ Spack bundle for "${packageName}" finished in ${timerEnd - timerStart}ms`);
    }
  };

  await handler();
};

module.exports = build;
```
**Config**
```json
{
    // Please copy and paste your .swcrc file here
    "jsc": {
        "parser": {
        "syntax": "ecmascript",
        "jsx": false,
        "dynamicImport": false,
        "privateMethod": false,
        "functionBind": false,
        "exportDefaultFrom": false,
        "exportNamespaceFrom": false,
        "decorators": false,
        "decoratorsBeforeExport": false,
        "topLevelAwait": true,
        "importMeta": false
    }
}
```

**Expected behavior**
The target module is successfully compiled and bundled.

**Version**
The version of @swc/core: 1.2.46
Running on MacOS 13-inch, 2017
Node version 12.13.1

**Additional context**
I was also trying execute spack bin using `execSync` but it will throw `SIGBUS` error which I assume it is the same error.

**Comment by kdy1** [comment]
cc @Brooooooklyn 
Do you have any thoughts?

**Comment by Brooooooklyn** [comment]
No idea.. @miqdadfwz  could you please upgrade your nodejs to latest 12.x and try again? Non lts version have many bugs and unexpect behavior in N-API side.

**Comment by kdy1** [comment]
Does this happen with recent vesion of swc?
I disabled avx instructions, so it may work.
