### ISSUE TITLE
No syntax error reported for forgetting equals sign before object literal expression initializer in variable declaration

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#1391]
**Describe the bug**

If someone forgets to have an equals sign in a variable declaration with an object literal expression initializer then there won't be a syntax error.

**Input code**

```ts
const Methods {
  f: (x, y) => x + y,
};
```

**Expected behavior**

I expected swc to return a syntax error or at least some diagnostic in the emitter, but nothing happens.

**Version**

swc_ecmascript: 0.20.0

**Comment by 00ff0000red** [comment]
Oh hey, it's not just missing assignment operators and object initializers, it's declaration related, here's another broken snippet if it helps:
or just 
```js
let a = 0,
let b = 1;
```
emits:
```
let a = 0,
  let;
```

Seems to be treating `let` as a indentifier, instead of a keyword?

**Comment by kdy1** [comment]
I tested it, but it resulted in an error.
You should use `Parser.take_errors()`

**Comment by dsherret** [comment]
@kdy1 interesting and thanks for investigating! I didn't even know about this method (I just assumed the handler would emit these, but now I see it's not even passed to the handler).

Was this one of the diagnostics that was moved from a `PResult` error into one of these diagnostics? Is there any way to tell these diagnostics appart from other ones? I think I will start collecting a list of error codes.

I think this issue can be closed.

**Comment by kdy1** [comment]
@dsherret I didn't finish error recovery and it is treated as a recoverable error from start I guess.
Also, if you get an error via `Parser.take_errors`, it's a recoverable error.
