### ISSUE TITLE
`.swcrc` should allow using typescript and javascript together

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#141]
Currently you can't use esnext features if you use typescript.

**Comment by DanielRamosAcosta** [comment]
I were about create a new issue but I think it goes in the same line as this. I would like to use swc to remove  TypeScript typings on the code and transform ES2016 modules into CommonJS ones. Is this possible (or will be) with swc?

**Comment by kdy1** [comment]
@DanielRamosAcosta Sorry for late response. It will be possible to do it.
