### ISSUE TITLE
No bindings for CentOS 7

### ISSUE THREAD

**Issue by ri0ter** [swc-project/swc#1410]
**Describe the bug**
On CentOS 7 it throws following error:
`Can not find node binding files from @swc/core-linux-x64-gnu, @swc/core-linux-x64-gnux32, @swc/core-linux-x64-musl and /opt/app-root/src/swc-test/node_modules/@swc/core/swc.linux-x64-gnu.node, /opt/app-root/src/swc-test/node_modules/@swc/core/swc.linux-x64-gnux32.node, /opt/app-root/src/swc-test/node_modules/@swc/core/swc.linux-x64-musl.node`

Can be reproduced with docker image: `centos/nodejs-10-centos7`

**Version**
The version of @swc/core: 1.2.47

PS I'm not sure if this should be opened as a bug or feature request.

**Comment by IllusionPerdu** [comment]
It's strange in the release they are "swc.linux-x64-musl.node". I think you can check if file exist in your system because it's probably a bad permition...
(sorry for my bad english ^^)

**Comment by ri0ter** [comment]
So I tried to manually call require on the bindings that were installed and this is what I got:
```
> require('./node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node')
Thrown:
Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/app-root/src/test/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
> require('./node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node')
Thrown:
Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by Brooooooklyn** [comment]
The version of Glibc is too low on CentOS, we need to build Linux binary on Ubuntu 16 if we want to support the CentOS /cc @kdy1

**Comment by kdy1** [comment]
I don't think it worth supporting.

**Comment by Brooooooklyn** [comment]
I've checked the version of `glibc` on `centos/nodejs-10-centos7` is `2.17`, which release in **2012**, and the `glibc` version of `ubuntu:16.04` is `2.23`, which means compile `swc` on `ubuntu:16.04` could not resolve this issue.
And I think it's impossible to build `swc` with `glibc@2.17`, the Rust toolchains is not existed in that age.

**Comment by kdy1** [comment]
Can you try manually installing `@swc/core-linux-x64-musl` via npm install?

**Comment by joebeachjoebeach** [comment]
I ran into this issue as well, then recently noticed that it was fixed in https://github.com/swc-project/swc/pull/3314 — just a note for others.
