### ISSUE TITLE
tests not passing on windows

### ISSUE THREAD

**Issue by JakubKoralewski** [swc-project/swc#1417]
I didn't see anything mentioned about Windows development in the [contritbuting.md](https://github.com/swc-project/swc/blob/master/CONTRIBUTING.md) file so I assumed it was ok to try

First of all the fixture macro is broken on Windows:
https://github.com/swc-project/swc/blob/eecdca4e866f470781806ed287fd8480aefa8dce/testing/macros/src/fixture.rs#L136

so I added a check for `\\`, but then I still get errors while running just ecmascript/parser: https://gist.github.com/JakubKoralewski/5c66c60998e630663641e2d03446a3c8

`cargo test --all --all-features`: 

1. First run
   https://gist.github.com/JakubKoralewski/8a2c2158a69d3c392348379cd231c4ab
2. Second run
   https://gist.github.com/JakubKoralewski/ad0794768000e010d909789343955cc0
I think they're the same but I was hoping the allocation error would be accidental.

So I just checked on WSL and I'm getting same sort of output too but like 100x slower IO I think

**Comment by kdy1** [comment]
You have to checkout with correct crlf setting.
