### ISSUE TITLE
The "use strict" directive is being included twice in transpiled files.

### ISSUE THREAD

**Issue by djalbat** [swc-project/swc#1423]
I am transpiling this code:

```
"use strict";

import { arrayUtilities } from "necessary";

const { second } = arrayUtilities;

const elements = [ 1, 2, 3 ],
      secondElement = second(elements);

console.log(secondElement)
```
The result is this code:

```
"use strict";
var _necessary = require("necessary");
"use strict";
var second = _necessary.arrayUtilities.second;
var elements = [
    1,
    2,
    3
], secondElement = second(elements);
console.log(secondElement);
```
You can see that the "use strict" directive is being included twice.

The `.swcrc` file is the following:

```
{
    "module": {
        "type": "commonjs"
    }
}
```
The version is `"@swc/core": "^1.2.47"`.

I am calling SWC programmatically rather than from the command line.

Many thanks in advance!

**Comment by grosto** [comment]
I found the source of the issue.

`ExportNamespaceFrom` pass moves all the imports statement in the beginning of file. So you get this after this pass
```js
import { arrayUtilities } from "necessary";
"use strict";
```

Then common js pass checks if "use strict" is the first module item and if it's not it adds the "use strict". 

I am thinking about solution(should not be hard), but I am quite new to the codebase so have to see what's the best way to go around it. The first instinct is to make a special case for "use strict" in ExportNamespaceFrom pass, but have to how that interacts with everything else.

**Comment by kdy1** [comment]
@grosto Thanks! I can now fix it without hard debugging :)

**Comment by djalbat** [comment]
Awesome! Thank you both. I'm really excited about using SWC going forward.

One thing I should mention. You get this error for another module kind, not just CommonJS. I can't remember the other off hand but it should be easy to check. Please let me know if you need more on this.
