### ISSUE TITLE
swc 0.7.0 requires rust nightly because of cargo "strip" feature

### ISSUE THREAD

**Issue by fasterthanlime** [swc-project/swc#1432]
swc 0.6.0 worked with the latest Rust stable, swc 0.7.0 no longer does:

```
error: failed to download `swc v0.7.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/vscode/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.7.0/Cargo.toml`

Caused by:
  the cargo feature `strip` requires a nightly version of Cargo, but this is the `stable` channel
  See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
```

**Expected behavior**

If that's the only thing that requires Rust nightly, could stripping debug symbols be moved to a post-build step instead of relying on an unstable Cargo feature?

**Version**

the `swc` crate, v0.7.0

**Comment by kdy1** [comment]
Hmm...
The swc crate is not designed for use from the rust side. (swc_ecma_preset_env expects node to be on the path)
What is your usecase?

**Comment by fasterthanlime** [comment]
I've been using `swc::Compiler` for its `parse_js` and `print` methods, but maybe the same could be achieved by using some of the underlying crates instead? Like `swc_ecma_parser::Lexer` and `swc_ecma_codegen::text_writer::JsWriter` - and then `swc_ecma_transforms` for, well, transforms.

I haven't been able to find a lot of docs on the whole family of swc Rust crates, maybe I've been missing some?

If using the individual crates seems like the way for to go for usage from Rust, feel free to confirm and close this.

(My use case is parsing a TypeScript codebase, transforming it to ES2020 and bundling it so it can be loaded easily in `deno_core`).

**Comment by kdy1** [comment]
Yes, you can do it using subcrates.

See typescript parser example at https://github.com/swc-project/swc/blob/master/ecmascript/parser/examples/typescript.rs

You can then apply `swc_ecma_transforms::typescript::strip`. See https://docs.rs/swc_ecma_transforms_typescript/0.7.0/swc_ecma_transforms_typescript/strip/fn.strip.html
You need to enabled the `typescript` feature of `swc_emca_transforms` to import it from `swc_ecma_transforms`.

Then you can use `swc_ecma_codegen` to convert the AST into a code.


Also, `swc_ecmascript` is a collection of such crates. It provides a compatible version of crates.

**Comment by fasterthanlime** [comment]
Thanks! I managed to get everything working with the subcrates 🎉

**Comment by newtack** [comment]
Deno also uses Rust API for transpilation, see here

https://github.com/denoland/deno/blob/4f80587d26891f783b1a7a46b0f3273def49cd6e/cli/ast.rs

**Comment by kdy1** [comment]
> Deno also uses Rust API for transpilation, see here
> 
> https://github.com/denoland/deno/blob/4f80587d26891f783b1a7a46b0f3273def49cd6e/cli/ast.rs

I know.
