### ISSUE TITLE
Cannot transform nested object destructuring with default value

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#1449]
**Describe the bug**

Panics parsing the following destructuring assignment with default value within an async function.

When compiling the code example using the following swc CLI invocation, I get this error:

```
❯ ./node_modules/.bin/swc -d ./swc-out ./foo.js
thread '<unnamed>' panicked at 'not implemented: assignment pattern AssignPat { span: Span { lo: BytePos(48), hi: BytePos(55), ctxt: #0 }, left: Object(ObjectPat { span: Span { lo: BytePos(48), hi: BytePos(50), ctxt: #0 }, props: [], optional: false, type_ann: None }), right: Object(ObjectLit { span: Span { lo: BytePos(53), hi: BytePos(55), ctxt: #0 }, props: [] }), type_ann: None }', ecmascript/transforms/compat/src/es2015/destructuring.rs:810:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    13076 abort      ./node_modules/.bin/swc -d ./swc-out ./foo.js
```

**Input code**

This is the most minimal reproduction I could create.  It appears to only happen within an async function, when the destructuring is nested, *and* when the nested destructured object is given a default value.

```
async function foo() {
    const {
        bar: {} = {}
    } = baz;
}
```

**Config**

Do not have an `.swcrc`

**Expected behavior**

The above code should compile correctly.

**Version**
The version of @swc/core: 1.2.49

**Additional context**

**Comment by kdy1** [comment]
Postponing as it a not a parsing issue.
