### ISSUE TITLE
How to keep the order of `import`?

### ISSUE THREAD

**Issue by wxs77577** [swc-project/swc#1457]
I need to import a `setGlobalOptions` function and run it, and import `./schemas` after that.

But it changes the order of code.
```ts
import {
  setGlobalOptions,
  plugin,
  buildSchema,
  addModelToTypegoose,
  deleteModel,
} from '@typegoose/typegoose';
import * as typegoose from '@typegoose/typegoose';
// typegoose.mongoose.set('debug', true);
setGlobalOptions({
  options: {
    allowMixed: typegoose.Severity.ALLOW,
  },  
  schemaOptions: {
    timestamps: {
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
});
import { schemas } from './schemas';
```
becomes
```js
var _common = __webpack_require__(7);
var _nestjsTypegoose = __webpack_require__(11);
var typegoose = __webpack_require__(12);
var _schemas = __webpack_require__(13);
var _class;
// typegoose.mongoose.set('debug', true);
typegoose.setGlobalOptions({
    options: {
        allowMixed: typegoose.Severity.ALLOW
    },
    schemaOptions: {
        timestamps: {
            createdAt: 'created_at',
            updatedAt: 'updated_at'
        }
    }
});
const models = _schemas.schemas.map((cl)=>({
        provide: _nestjsTypegoose.getModelToken(`Base${cl.name}`),
        inject: [
            _nestjsTypegoose.getConnectionToken()
        ],
        useFactory (conn) {
            //@ts-ignore
            return conn.model(`${cl.name}`, typegoose.buildSchema(cl));
        }
    })
);
```

**Comment by FelixStridsberg** [comment]
Did some debugging on this to get to know the code base, the issue is in this function:
https://github.com/swc-project/swc/blob/97269a37b964f362d4d8cade37ce30010a4a6199/ecmascript/transforms/compat/src/es2020/export_namespace_from.rs#L16

It groups the imports aside from the rest of the items, then at the bottom it merges them with the imports first.
The problem goes away if you set target to es2020.

**Comment by devongovett** [comment]
I think this is incorrect. Import statements are hoisted according to the spec. If you ran your code in a browser or in node with ESM support the `import` of `'./schemas'` would happen before the call to `setGlobalOptions`. The previous behavior was correct. I suggest reverting this change.

**Comment by kdy1** [comment]
@devongovett Oh, I see.
I will revert it.

**Comment by petkaantonov** [comment]
If target is commonjs or any target that uses functions rather than "import" statement, it should *not* rearrange the imports as they are require function calls which should be in order. This is incompatible with tsc and others.
