### ISSUE TITLE
String literal as property name not handled correctly

### ISSUE THREAD

**Issue by akeating** [swc-project/swc#146]
Hi, I've encountered a problem using `swc` in one of my code-bases. Feel free to close if this is known or symptomatic of an planned but unjmplemented feature.

Given this source javascript:
```
const o = {
    foo: 1,
    'bar@': 2,
    '@': 3
};
```

Expected output:
```
var o = {
    foo: 1,
    'bar@': 2,
    '@': 3
};
```

Actual output:
```
var o = {
    foo: 1,
    bar@: 2,
    @: 3
};
```

Which results in an `SyntaxError: Invalid or unexpected token` for `@`.

I am using:
```
$ npx swc --version
0.1.7
```

Which incidentally appears to be another problem since `package.json` is pinned to `0.1.8`:
```
"dependencies": {
    "swc": "^1.0.3",
    "swc-cli": "^0.1.8"
  }
```

**Comment by kdy1** [comment]
Fixed with swc@1.0.5
