### ISSUE TITLE
Feature request: regenerator-runtime should be inlined when externalHelpers is false (or offer the functionality to do so)

### ISSUE THREAD

**Issue by wessberg** [swc-project/swc#1461]
**Describe the feature**

`swc` comes with a set of helper functions, all of which are inlined by default. However, it leverages `regenerator-runtime` for transforming async- and generator functions. However, even when `externalHelpers` are false (the default option), `regenerator-runtime` is included via a `require("regenerator-runtime")` call.

To my knowledge, there is no way to configure swc to inline regenerator-runtime.

The only way to work around it is by transforming the output of swc to manually remove the `require()` call and inline it, which is cumbersome and slow.

**Proposed solution**

Ideally, `externalHelpers` should be respected, since `regenerator-runtime` is being used by swc as a helper function.

Alternatively, at the very least, it should be customizable whether or not `regenerator-runtime` is inlined.

Any suggestions for workarounds are more than welcome.

**Comment by nino-vrijman** [comment]
Note that I didn't test this thoroughly in anyway but by code would run successfully after installing `regenerator-runtime` as a dependency manually.

**Comment by wessberg** [comment]
Yes,
- If the code is executed in an environment that the developer has control over (they may not)
- if the executing runtime supports CommonJS modules (e.g. node)

For example, for my usecase, swc is embedded in a webservice that performs JIT-transpilation per API call of a bundle of polyfills, so I must ensure that the output generated by swc is in fact free of external dependencies.

Currently, swc is using `regenerator-runtime` as a helper, but is always treating it as external, which defeats the purpose of being able to customize this as an option.

**Comment by jsilveira** [comment]
I also second this! I'm only using `swc` for the es6 -> es5 conversion for an existing bundle and it would be very useful to have a "browser usable" output from `swc`

**Comment by wessberg** [comment]
I juts want to reiterate how important this issue is to me - there's no other workaround than to apply a transformation on the generated code which is slow, cumbersome, and error prone.

Even though I strongly suggest that `regenerator-runtime` should respect the `externalHelpers` rule, I would also just appreciate a way to get around this with some config property.

**Comment by jsilveira** [comment]
Is this closed because it is fixed? Is something out of scope of the library? I'm asking because I still need this (actually last week had an ugly bug due to the workaround required because of it). Thanks

**Comment by kdy1** [comment]
Closed because it belongs to the bundler
swc has a bundler, and you can achieve this if you use it.

**Comment by wessberg** [comment]
Can you elaborate? Is there some new config option? Did you change the default behavior? Is there any documentation? What changed, basically.

**Comment by kdy1** [comment]
It's swc simply having a bundler.
See https://swc.rs/docs/spack-basic

**Comment by jsilveira** [comment]
In my use case I already have a bundler (esbuild). I'm just using swc to transpile its output to es5

**Comment by wessberg** [comment]
This issue is related to `regenerator-runtime` being included even when externalHelpers` is `false`. Has this behavior changed? How does the bundler relate to this issue? It's not very obvious to me how this issue has been resolved, and I would appreciate a bit more explanation or a link to some release notes or documentation if that's possible 🙂

**Comment by kdy1** [comment]
Does esbuild allow running swc before esbuild handles it?
I think it's the right way to go.

**Comment by jsilveira** [comment]
If it did I would lose all of the usability and performance benefits of using esbuild (bundling hundreds of files in milliseconds, very rich feature set for transformations, etc).

**Comment by kdy1** [comment]
Why? swc can process hunred files in milliseconds, too. Also, what do you mean by rich feature set?
swc also has lots of transforms. Is anything missing?

**Comment by wessberg** [comment]
@kdy,1, just to keep things separate, this issue isn't related to how the swc bundler works or how it integrates with esbuild, but rather the behavior of the `externalHelpers` option and how it relates to `regenerator-runtime`. For existing code bases that use `swc` for applying syntax transformations for lowering to es5 as a faster alternative to babel, this is a relevant use case.

**Comment by kdy1** [comment]
No, it's about the order of passes in compilation.
Opening again because this can be fixed when swc migrates to `tslib`, but not now.

**Comment by wessberg** [comment]
When and if you eventually align with `tslib`, the result will be exactly what I'm proposing. As I've mentioned before, because there's no way for the configure this currently, I have to apply a transformation on the output of swc _every time_, and transform the source maps accordingly. This is done many thousands of times daily in a web service and comes at an unnecessary performance cost. I hope you will either prioritize the switch to tslib or offer this as a configuration option or just change the default (which I really think is the right solution here), but as an open source maintainer myself, I understand that you have limited time available.

**Comment by jsilveira** [comment]
> Why? swc can process hunred files in milliseconds, too. Also, what do you mean by rich feature set?
> swc also has lots of transforms. Is anything missing?

Maybe this has changed in the last months, but last time I checked spack was 10 times slower than esbuild bundling and didn't offer the same functionality (there's  even an issue on esbuild on why it wasn't added to the benchmarks).

Anyway, I think comparing them is missing the point. I find swc very valuable to handle es5 transpiling, is there any reason why this wouldn't be a good idea? Is there a better tool for this? I love swc's speed. Thanks

**Comment by kdy1** [comment]
@jsilveira For perf, please refer to https://swc.rs/docs/benchmark-transform
I'm sure you were benchmarking different operations.
My benchmark aligns task and it's open sourced.

**Comment by kdy1** [comment]
I found non-breaking solution. I'll try fixing this soon.

**Comment by wessberg** [comment]
Very good news, thanks! ♥️

**Comment by Khachatour** [comment]
hey @kdy1 do we have any updates on this? Do you plan on finishing this in `1.2.86`? Thanks in advance!

**Comment by kdy1** [comment]
@Khachatour No to both. I have lots of tasks with higher priorities.

**Comment by Khachatour** [comment]
@kdy1 got you, maybe it would be better to put some freeze or similar label to this?

**Comment by kdy1** [comment]
I don't think so. I don't use such labels for good reasons.

**Comment by wessberg** [comment]
@kdy1, you mentioned you had found a non-breaking solution recently?

**Comment by kdy1** [comment]
Yes, I found one.

**Comment by yisar** [comment]
@kdy1 Any progress here? I have to use esbuild to do secondary packaging, This is not a good way.

**Comment by kdy1** [comment]
@yisar No. I have lots of tasks with higher priority.
I got paid, and issues related to the company have higher priority.

**Comment by kdy1** [comment]
I'll fix this with the next version.

**Comment by kdy1** [comment]
Seems like a huge change including the reimplementation of `regenerator` pass.
Also, I found that `regenerator-runtime` is quite big while `__generator ` of `tslib` is quite small.

I think this requires more investigation about drawbacks of `tslib.__generator`.

**Comment by wessberg** [comment]
Yes, `regenerator-runtime` is doing a lot of things. The size of it, however, doesn't change depending on whether or not it is referenced via an import declaration. This is not a "one or the other" type of situation, this can be divided into two things. One, you want to replace `regenerator-runtime` with something more compact. And the other is this one. Once again swc is using `regenerator-runtime` as a helper library, but it doesn't follow the same rules as other helpers for the `externalHelpers` flag, and in fact, there's no way users can request that it is inlined just like all other helpers. Adding import declarations after syntax transformation is completely fine if the user wants it, but it tends to be an opt-in thing, because there are scenarios in which no bundler sits after swc, for example if swc is used as a drop-in replacement for Babel as the final step in a build pipeline. In any case, I'm fine you with switching the default to marking helpers as external by default, all I want is the ability to control this, and for it to be consistent.

**Comment by kdy1** [comment]
Inlining `regenerator-runtime` is not an option. There are various reasons, and babel also does not inline `regenerator-runtime`, too.

The solution I mentioned above is about using `__generator ` of `tslib`.
Postponing as this would take really lots of time.

**Comment by kdy1** [comment]
To be exact, reimplementing generator pass is fine, but I think I need to investigate a lot about generator helpers.
I think `regenerator-runtime` is huge because of good reasons, and I'm not aware of such reasons.

**Comment by wessberg** [comment]
To be precise, Babel only adds require calls/import statements for things like `@babel/runtime/regenerator` when you use the `runtime` transformer. Without it, it expects `regeneratorRuntime` to be available in global scope, which too is less than ideal. Of course, the concern is that a very large helper will be inlined across many files, which pollutes them quite a lot. However, I also think there should be a way for Babel to inline regenerator runtime which is a much better solution that expecting an identifier to be present in the global scope with a certain name (which could have been deconflicted/mangled by a build step before it), but I digress.

If you decide not to do anything about this, if _I could just have_ a way to make swc inline regenerator runtime via a config option somehow, I would be happy and very appreciative.

In any case, I respect if you decide to postpone this. I just hope I have been successful in explaining why this is such an important use case for me: Many, many thousands of times a day, I run a bundled file through swc to lower syntax to ES5 if the clients of a web service request it, and there I'm using sec but have to be parse the output and see if there's an important for regenerator runtime and if so, manually inline it, generate new source maps, etc, before returning it.

**Comment by matzetronic** [comment]
Hi 👋🏻
is there a chance that this will get fixed anytime soon? Our team would also like to move from babel to swc but this bug is blocking us. We can not ship external helpers in our software, so a fix for this would be a big deal for us. 😃
Thanks!
