### ISSUE TITLE
Expose JS API for parse/generate

### ISSUE THREAD

**Issue by Djaler** [swc-project/swc#1466]
**Describe the feature**
This can be used in many cases as a replacement for @babel/parser and @babel/generator and improve performance of frontend tooling

**Comment by kdy1** [comment]
There are apis for it.

**Comment by Djaler** [comment]
Can you link me for it, please? I didn't found it in the docs.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/06cb4b89cba109e8bae8739a8509c5be569d1da1/node-swc/src/index.ts#L45


There's no doc on the website currently.

**Comment by Djaler** [comment]
Thanks!
