### ISSUE TITLE
strip: Define class fields in constructor by default

### ISSUE THREAD

**Issue by nayeemrmn** [swc-project/swc#1472]
Example input:
```ts
class A extends Object {
  a = 1;
  constructor(public b = 2) {
    super();
  }
}
```
TSC actually only preserves class fields under specific conditions:
1) `"target": "ESNext", "useDefineForClassFields": true` - Preserve class fields. Current default behaviour (roughly) of swc.

  ```js
  class A extends Object {
      b;
      a = 1;
      constructor(b = 2) {
          super();
          this.b = b;
      }
  }
  ```
2) `"target": "ESNext", "useDefineForClassFields": false` - Define class fields in constructor. Current behaviour of swc with `typescript_class_properties()` pass. Proposed default.

  ```js
  class A extends Object {
      constructor(b = 2) {
          super();
          this.b = b;
          this.a = 1;
      }
  }
  ```
3) `"target": "ES6-ES2020", "useDefineForClassFields": true` - Define class fields in constructor using `Object.defineProperty()`.

  ```js
  class A extends Object {
      constructor(b = 2) {
          super();
          Object.defineProperty(this, "b", {
              enumerable: true,
              configurable: true,
              writable: true,
              value: b
          });
          Object.defineProperty(this, "a", {
              enumerable: true,
              configurable: true,
              writable: true,
              value: 1
          });
      }
  }
  ```
4) `"target": "ES6-ES2020", "useDefineForClassFields": false` - Same as (2).

So swc should have a similar API. I propose adding `strip::Config::use_define_for_class_fields: bool`, defaulting to `false`. If set to `true`, class fields preserved. Otherwise they are put into the constructor. The `typescript_class_properties()` pass should instead transform class fields to be constructor-defined using `Object.defineProperty()` -- we suggest using it when targeting ES2020 and earlier with `"useDefineForClassFields": true`.

Ref #949.

**Comment by kdy1** [comment]
Seems reasonable about the api but I have a question. 
Is changing default behavior correct?

**Comment by nayeemrmn** [comment]
> Is changing default behavior correct?

Yes, the example is copy-pasted from tsc output. Additionally it's strictly more compatible and non-breaking.

**Comment by kdy1** [comment]
@nayeemrmn Thanks for the clarification! I will implement it soon.
