### ISSUE TITLE
`"target": "es201n"` actually targets the version before that

### ISSUE THREAD

**Issue by Hoishin** [swc-project/swc#1484]
**Describe the bug**

`const` and `let` are converted to `var` with es2015 target. Arrow functions are converted to function expression with es2015 target. Both are added in ES2015. They are not converted with es2016 target.

Exponential operator is converted to `Math.pow` with es2016 target. It's added in ES2016. It's not converted with es2017 target.

**Input code**

```ts
const foo = 'foo';

const aaa = () => {
	console.log(foo, 2 ** 4)
}
```

**Config**

```json5
{
  "jsc": {
    "parser": {"syntax": "typescript"},
  },
  "target": "es2015" // or "es2016", "es2017", and so on
}
```

**Expected behavior**
It should target the correct ECMAScript version

**Version**
The version of @swc/core: 1.2.50

**Additional context**
TypeScript `tsc` does target correct ECMAScript version. It keeps `const`/`let`/arrow functions with es2015 target, and exponential operators with es2016 target.

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/swc/issues/1108

**Comment by Hoishin** [comment]
Couldn't find that issue by searching, my bad
