### ISSUE TITLE
dynamicImport error should be a warning

### ISSUE THREAD

**Issue by mikob** [swc-project/swc#1504]
error: import(...) expressions requires `jsc.parser.dynamicImport` to be true

But I would like to ignore the dynamicImport (let it happen at runtime). Perhaps this would make more sense as a warning, about the dynamic import being unresolved because dynamicImport is false?

**Comment by kdy1** [comment]
It's option for the parser, though.

**Comment by mikob** [comment]
@kdy1 sorry, I'm new to this. I thought that turning that option on would make it resolve and bundle the dynamic import. But I now see I was wrong!
