### ISSUE TITLE
Incorrect parsing of nested <> generics in fat arrow functions in tsx mode

### ISSUE THREAD

**Issue by alxu-sentry** [swc-project/swc#1505]
**Describe the bug**
I tried running swc on https://github.com/getsentry/sentry, and while ~3800 files successfully compiled, about a dozen failed. One issue is on our end: https://github.com/getsentry/sentry/pull/24773. The main issue however is the following edge case in tsx parsing:

**Input code**

```typescript
class MyClass<T> {};
type MyType = {};
export const fn = <T>() => class extends MyClass<MyClass<T>> { static x = 5; };
```

```typescript
class MyClass<T> {};
type MyType = {};
export const fn = <T>() => class extends MyClass<Omit<MyType, 'x'> & T> {};
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

**Expected behavior**
JavaScript is output.

**Actual behavior**

```
error: Expression expected
 --> test.ts:3:68
  |
3 | export const fn = <T>() => class extends MyClass<Omit<MyType, 'x'> & T> {};
  |                                                                    ^

failed to process js file

Caused by:
    failed to parse module: error was recoverable, but proceeding would result in wrong codegen
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/Users/alex/PycharmProjects/sentry/node_modules/@swc/cli/lib/swc/util.js:152:15)
    at files (/Users/alex/PycharmProjects/sentry/node_modules/@swc/cli/lib/swc/file.js:176:18)
```

```
error: 'implements', 'interface', 'let', 'package', 'private', 'protected',  'public', 'static', or 'yield' cannot be used as an identifier in strict mode
 --> test.ts:3:64
  |
3 | export const fn = <T>() => class extends MyClass<MyClass<T>> { static x = 5; };
  |                                                                ^^^^^^

failed to process js file

Caused by:
    failed to parse module: error was recoverable, but proceeding would result in wrong codegen
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/Users/alex/PycharmProjects/sentry/node_modules/@swc/cli/lib/swc/util.js:152:15)
    at files (/Users/alex/PycharmProjects/sentry/node_modules/@swc/cli/lib/swc/file.js:176:18)
```

**Version**
The version of @swc/core: 1.2.50

**Additional context**
Both issues can be worked around by changing to an explicit return statement, so not super high priority but would be nice to have fixed. I think this is quite an edge case, but hopefully not too hard to fix.

Although I work for @getsentry, we don't currently use swc officially. I think we currently rely fairly heavily on emotion component selectors which require either babel-plugin-emotion or babel-plugin-macros so we can't migrate to swc.

**Comment by kdy1** [comment]
I tried to fix this, and I found that it works if you set `.swcrc` as

```json
[
  {
    "test": ".*.ts$",
    "jsc": {
      "parser": {
        "syntax": "typescript"
      }
    }
  },
  {
    "test": ".*.tsx$",
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "tsx": true
      }
    }
  }
]

```

See: https://swc.rs/docs/configuring-swc/#multiple-entries

I'll change default value of `tsx` to determined by extension, though.

**Comment by alxu-sentry** [comment]
Hi, are you saying this is invalid in TSX? I think this should be parsed as a generic, not as a tag. I'm not sure how tsc handles this but it is allowed in both TS and TSX mode.

**Comment by kdy1** [comment]
Yes. It's invalid in tsx.

https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeBhcUA8AVAfNA3gXwG4AoAF3gAcBTOedC6gXl0KMoA9yB7AJxOmE4A7CHwBmg6EwyYAFAEpJ2UJBjsSlQQBMYCZCtS6UEadhzQRYEgEtg0NpOgBWAtBZA


https://www.typescriptlang.org/play?#code/FAYwNghgzlAECyBPAwpGAeAKgPlgbwF8BuYAF0QAcBTBRTSmgXn2OCoA8KB7AJ1NhBcAdlH4AzIbGZZsACgCUU3OGhwOpKkIAmcJKlXoA8gFsAlqXRJ61ADSwA5O3u4AZLBwsiQA

In both examples, there are parsing errors. (`Unexpected token `)

**Comment by alxu-sentry** [comment]
Sorry, I didn't check that my reduced example works in TSC. This example is working in TSC but not SWC:

Full code: https://github.com/getsentry/sentry/blob/37ca88539ecfd98ccc61513c179704f31689afe1/src/sentry/static/sentry/app/utils/withTeamsForUser.tsx#L27

Reduced example:

```typescript
type InjectedTeamsProps = {};
const withTeamsForUser = <P extends InjectedTeamsProps>(
  _WrappedComponent: React.ComponentType<P>
) =>
  class extends React.Component<
    Omit<P, keyof InjectedTeamsProps> & Partial<InjectedTeamsProps>,
    InjectedTeamsProps
  > {
    static displayName = `x`;
  };
```

TSC OK: https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdgKwgY2BAJgFQgQwLYDOACgE4D2YBUAvFAN4C+A3AFDIA2OBVAwmXmDJwIcYAB4A+pgA0UCQFUAfPQZtO3KHwFCRwTOAiTMyxmyEFgUAO4BLYAAts+AgDEyJeQQgkaUMUSgIAA80OHQqeCRUDCdCUgoCRQAKFig5AHUSHDBIdC1BYVEALk1+At19SH9FFgBKGhq0ji4qYNDw0u1C8VS0qAB5PDt-WQBrCBAyADNYRBQ0LFw48kplADIoIhwSYBscdjFI+Zil4hXE6V60o+jF53jKXpMrqAscXeQodBsCME4QABy+GgtAABkFQaw0swWEA

SWC error:

```
error: Expression expected
 --> test.tsx:8:39
  |
8 |     Omit<P, keyof InjectedTeamsProps> & Partial<InjectedTeamsProps>,
  |                                       ^

failed to process js file
```

Sorry for the wrong example before, hope this helps. Thank you for the quick responses.
