### ISSUE TITLE
`assert` identifier in call expression with type arguments fails to parse

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#1512]
**Describe the bug**

Code fails to parse.

**Input code**

```ts
import assert from './index'

assert<123>(123)
assert<123>(123, 123)
assert<123>(123, 123, 123)
```

```
Line 3, column 11: Expected a semicolon

  assert<123>(123)
            ~
```

**Expected behavior**

It would parse.

**Version**

swc_ecmascript 0.27.0 (I'm assuming this hasn't been fixed in 0.28... my bad if so)

**Comment by kdy1** [comment]
I'll fix this with https://github.com/swc-project/swc/pull/1506. (I need to fix parser anyway)
