### ISSUE TITLE
Combining import and default import transpiles wrong output

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#1525]
**Describe the bug**

When using this syntax in TypeScript code:
```
import { Component, default as React } from "react";

...

class X extends Component {
}

```

My output looks like this:

```
var _react = _interopRequireDefault(require("react"));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}

class X extends _react.Component {
}
```

and that results with error: ```Class extends value undefined is not a constructor or null``` because `_react.Component` doesn't exist (it needs to be rather `_react.default.Component`).

**Config**

```json
{
  "env": {
    "targets": {
      "node": "15.10"
    }
  },
  "jsc": {
    "target": "es2019",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Version**
1.2.51

**Comment by kdy1** [comment]
Is this really bug?
I'm not sure, but using `_react.default` where _react is default-exported seems wrong to me.

**Comment by pbadenski** [comment]
I do believe this is a bug. Let me try to explain a bit better.

`import { Component, default as React } from "react";` is a valid syntax in ES Module and it's also supported by Babel.

If I create 2 files test.mjs and test.js with identical content:
```
import { Component, default as React } from "react";

console.log(Component);
console.log(React.Component);
```

> node test.mjs

Output:
```
[Function: Component]
[Function: Component]
```

> swc-node test.js

Output:
```
undefined
[Function: Component]
```

I would expect `swc-node` to return the same output as node's ES module example.

**Comment by kdy1** [comment]
Ah, sorry. I misread it. I only considered `_react.default.Component` this part.

**Comment by Austaras** [comment]
For reference, [this](https://babeljs.io/repl#?browsers=chrome%2088&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgYQuCA7AphmAaOAEywDMBDAVwBt4yBnOAJSzIGN4BfOEqNOAIigt2_ANwAoSayr0GADThYAHjByEGqdNlyJxHcUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-1%2Cstage-2&prettier=false&targets=&version=7.13.15&externalPlugins=) is what babel do. Basically clone the original object and assign it to `.default` too
