### ISSUE TITLE
Comment map key positions are incorrect in some cases in swc_ecmascript 0.29.0

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#1530]
**Describe the bug**

Had a lot of tests fail. Probably related to this statement: https://github.com/swc-project/swc/pull/1527/files#diff-ff99e374b96f1bc47fba4a477800d8f6e78d43ddb8d4899afb6b7d9073e7139cR281

Given the following code:

```ts
while (1) {
/* test */}
```

swc now has the following leading and trailing comment maps:

```
Leading: {BytePos(23): [Comment { kind: Block, span: Span { lo: BytePos(12), hi: BytePos(22), ctxt: #0 }, text: " test " }]}
Trailing: {}
```

Byte position 23 is after the close brace token and not before it.

**Expected behavior**

```
Leading: {BytePos(22): [Comment { kind: Block, span: Span { lo: BytePos(12), hi: BytePos(22), ctxt: #0 }, text: " test " }]}
Trailing: {}
```

**Another Scenario**

Actually, I think this has the same cause.

```ts
switch (1) {
    case 2:
        3;
    // 4
}
```

Now (incorrect):

```ts
Leading: {BytePos(46): [Comment { kind: Line, span: Span { lo: BytePos(40), hi: BytePos(44), ctxt: #0 }, text: " 4" }]}
Trailing: {}
```

Previously (correct):

```ts
Leading: {BytePos(45): [Comment { kind: Line, span: Span { lo: BytePos(40), hi: BytePos(44), ctxt: #0 }, text: " 4" }]}
Trailing: {}
```

**Version**

swc_ecmascript 0.29.0

**Comment by kdy1** [comment]
I'll implement a test system for comments.

**Comment by kdy1** [comment]
Fixed and published a new version :)

**Comment by dsherret** [comment]
Thanks @kdy1! It is working perfectly now 😊
