### ISSUE TITLE
Error message for invalid config is misleading

### ISSUE THREAD

**Issue by grimly** [swc-project/swc#1532]
**Describe the bug**

I am using swc with rollup, therefore I am using the API, not the CLI.

I tracked down my issue to the use of the `transform` function from `@swc/core`.
I've removed all the code I could to narrow down the source of my problem.

Here is the code to run with `node` directly :

```typescript
const { transform } = require('@swc/core');

const filename = 'index.ts';

const code = `
export async function getDependency(): Promise<any> {
  return import('./dep').then(({dependency}) => dependency);
}
`

const options = {
  jsc: {
    parser: {
      syntax: 'typescript',
      dynamicImport: true
    },
    externalHelpers: true,
    target: 'esnext'
  },
  sourceMaps: true,
  filename
}

transform(code, options)
  .then(console.info, console.error)
```

The following error prints immediately:

```
error: import(...) expressions requires `jsc.parser.dynamicImport` to be true
 --> index.ts:3:10
  |
3 |   return import('./dep').then(({dependency}) => dependency);
  |          ^^^^^^
```

The returned promises emits an error which prints as the following:

```
[Error: failed to process js file

Caused by:
    failed to parse module] {
  code: 'GenericFailure'
}
```

**Expected behavior**
The code should compile

**Version**
The version of @swc/core: **1.2.51**

**Comment by kdy1** [comment]
`target: 'esnext'` is wrong. You should use `target: 'es2020'` instead.
Error message seems misleading, though.

**Comment by grimly** [comment]
Indeed this fixed my problem. Thank you very much.

Should I leave this issue open until the error message is clearer or not ?

**Comment by kdy1** [comment]
Please leave it. I'll change the title.
