### ISSUE TITLE
add support for "named amd" module targets:

### ISSUE THREAD

**Issue by stefanpenner** [swc-project/swc#154]
First of all, cool project I have been dreaming of having the time to do something similar, but I am happier to see folks with more rust experience than myself take this on. Awesome.

Anyways, re: named amd module targets

## Rationale

Currently, babel and rollup allow for named AMD transpilation outputs. Currently the ember ecosystem via ember-cli-babel + broccoli-babel-transpiler make use of this.

I would love to experiment, and offer SWC as a likely much faster alternative. Although other blockers exist, this would help move us closer.

## Example:

```js
const { code } swc.transformSync(`export default  from 'fruit';`, {
  module: {
    type: 'named-amd',
    moduleId: 'apple'
  }
});

code === `
define("apple", ['fruit', 'exports'], function(fruit, exports) {
  exports['default'] = fruit;
}); 
`
```

* `getModuleId` in babel: https://babeljs.io/docs/en/options#getmoduleid
* `--amd.id <id>` in rollup

**Comment by kdy1** [comment]
Fixed with swc@1.0.6
