### ISSUE TITLE
Problems with Crypto

### ISSUE THREAD

**Issue by matiosfree** [swc-project/swc#1545]
**Describe the bug**

I'm getting an error in the project that uses crypto-browserify:
```
87% sealing module hashingTypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at BulkUpdateDecorator.update (\node_modules\webpack\lib\util\createHash.js:51:14)
```

if I'm going into createHash.js and changing (just for the test)
`this.hash.update(data, inputEncoding);`
to 
`this.hash.update(data + '', inputEncoding);`
The error disappears.

**Input code**

```
import {createHash, createHmac} from 'crypto';

let hash = createHash(algorithm);
let hmac = createHmac(fn, key);
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

**Expected behavior**
No error happen

**Version**
The version of @swc/core: v1.2.52

**Comment by kdy1** [comment]
Are you using swc-loader?
And are you transpiling `webpack\lib\util\createHash` with swc?

**Comment by matiosfree** [comment]
> Are you using swc-loader?

yes, I do



> And are you transpiling webpack\lib\util\createHash with swc?

no, I'm transpiling **createHash**  and **createHmac**  from  `crypto-browserify\index.js`

**Comment by kdy1** [comment]
Can you provide more input?
I tried a test using 

```js
import { createHash, createHmac } from 'crypto-browserify';

let hash = createHash(algorithm);
let hmac = createHmac(fn, key);
```

but output was identical.

**Comment by kdy1** [comment]
Closing as no information provided
