### ISSUE TITLE
ReferenceError: _interopRequireDefault is not defined

### ISSUE THREAD

**Issue by RIP21** [swc-project/swc#1554]
This is what I get for a typical CRA v4 app where I have overridden babel transform with the current one.
```
ReferenceError: _interopRequireDefault is not defined
```
Override looks like
```
    const key = Object.keys(config.transform)[0]
    config.transform[key] = [require.resolve('@swc/jest')]
    return config
```
which results in transform like

```
'^.+\\.(js|jsx|mjs|cjs|ts|tsx)$': [require.resolve('@swc/jest')]
```
Which is absolutely valid but doesn't work.

CRA v4 uses Jest 26.

It's all against TypeScript codebase.

BTW, 15 tests even passed. But not other 240 or so :)

**Comment by lexanth** [comment]
For me, the code that was triggering this was along these lines
```ts
export { default as X, Y } from './Z';
```

Conversely this works:
```
import X, { Y } from './Z';
export { X, Y };
```

Hopefully this helps you track down the issue @kdy1 !

**Comment by atsikov** [comment]
I've found another case which triggers the same error. It looks like swc doesn't like when both import and export are used for the same module

This fails with `ReferenceError: _interopRequireDefault is not defined`
``` js
import X from './module'

export { X }
export { Y, Z } from './module'
```

While this works fine
``` js
import X, { Y, Z } from './module'

export { X }
export { Y, Z }
```

**Comment by badescuga** [comment]
maybe try using `externalHelpers`: https://swc.rs/docs/configuring-swc#jscexternalhelpers
