### ISSUE TITLE
Transform esmodule without break `this`

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#1556]
**Describe the bug**
As we have discussed in #1524, when swc transform esmodule to `commonjs|amd|umd` it will generate code like
```js
const a = require('./a')
a.foo()
```
However, that will make `this` in `foo` points to module `a` instead of `globalThis`. Although few people still use commjs target today and even fewer people use `this` to refer global, this still should be fixed. swc should instead generate code like
```js
const a = require('./a')
(0, a).foo()
```
**Version**
latest

**Additional context**

**Comment by Austaras** [comment]
Seems like this bug runs down to [this line](https://github.com/swc-project/swc/blob/2211a9908a9a1c2e01d5f483ad91ac396336dc08/ecmascript/transforms/base/src/fixer.rs#L667). What is the purpose of this line @kdy1? There are many cases where I believe it would cause bug, e.g.
```js
const a = {
   foo() {
    console.log(this.name)
   }
};

(0, a.foo)()
```
or 
```js
window.__defineGetter__('a', () => {
  console.log(1);
  return 2;
})

let b = (a, 123)
```

**Comment by kdy1** [comment]
It's a known issue and it should be changed to preserve one useless value.

**Comment by Austaras** [comment]
So should I remove `ignore_return_value` completely?

**Comment by kdy1** [comment]
@Austaras No, I think it should preserve only one useless value.

**Comment by Austaras** [comment]
Fine. But consider the up mentioned example 2, `Ident` should be considered as useless value.
