### ISSUE TITLE
Should support `async override` in addition to `override async`

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#1558]
**Describe the bug**

Right now doing `async override` will throw an error.

**Input code**

It seems TypeScript supports both ways, but right now swc errors.

```ts
class Base {
    method1() {}
    method2() {}
}

class Test extends Base {
    public override async method1() {
        return Promise.resolve(1);
    }

    public async override method2() {
        return Promise.resolve(1);
    }
}
```

https://www.typescriptlang.org/play?ts=4.3.0-beta#code/MYGwhgzhAEBCkFNoG8CwAoaXoFsEBcALAewBMBGACgEoUBfDbXAk0gJhvowfQ1EhgAVBBHzQEAD3wIAdqRjwISNJmwAHAK4AjEAEtg0YgDcEAJ1O7SSSAE8ZBvETJVaKpk1MENpmdAAKpsQ4ukoAdJ4QxCAmlOTUANyM2DxJWJo6+tC29oYm5pZIjqwcrqnunvjevgFBIQjhIlExcYmqWDw8QA

**Expected behavior**

No diagnostic.

**Version**

swc_ecmascript 0.31.0

**Comment by Skalman** [comment]
The TypeScript compiler often requires a specific modifier order. I've filed an issue with them to see if this behavior is on purpose or not: https://github.com/microsoft/TypeScript/issues/43606.

**Comment by dsherret** [comment]
@Skalman thanks for getting clarification on that! I had just assumed it was by design since there are some other scenarios where the compiler supports any modifier order and c# supports either `async override` or `override async`. I looked into it and `override async` is more popular in c# than `async override`.

Regardless, I think it would be best if swc supported parsing whatever modifier order without a hard diagnostic (#1178), then doing a soft diagnostic for when the modifier order is incorrect. This would allow to continue analyzing code regardless of modifier order.

**Comment by Skalman** [comment]
@dsherret, yeah I agree with you. I just bumped in to the same issue with other modifiers the other day: https://github.com/swc-project/swc/pull/1541#issuecomment-813350386
I just think it'd be nice if TS were consistent :smile:
