### ISSUE TITLE
Evaluate export default beforehand

### ISSUE THREAD

**Issue by josteph** [swc-project/swc#1568]
**Describe the bug**
Currently export should be evaluated beforehand to avoid undefined if bundled using webpack. Refer to this issue https://github.com/webpack/webpack/issues/7767.

**Input code**
```
export default function get(key: string) {
  console.log(key);
}
```

**Config**

```
{
  jsc: {
    parser: {
      syntax: "typescript",
      tsx: false,
      decorators: false,
      dynamicImport: true
    },
    target: "es5",
    loose: true,
    externalHelpers: false
  },
  sourceMaps: true,
  minify: false,
  env: {
    mode: "entry",
    coreJs: 3
  },
  module: {
     type: "commonjs"
  }
}
```

**Expected behavior**
Babel sample output:
```
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true,
});

exports.default = get;

function get(key) {
  // code here
}
```

**Version**
The version of **@swc/core: 1.2.51**

**Additional context**
If we change the export this way, it would work normally as expected.

```
function get(key: string) {
  // code
}

export default get;
```

SWC output (changed the export as described above) **(works)**:
```
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true,
});
exports.default = void 0;

function get(key) {
  // code here
}

var _default = get;
exports.default = _default;
```

Current SWC output **(doesn't work)**:
```
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true,
});

function get(key) {
  // code here
}

exports.default = get;
```

**Comment by kdy1** [comment]
How did you get the output of swc?
Your `.swcrc` does not contains module config, so I failed to reproduce it.

**Comment by kdy1** [comment]
I think I can fix it without reproduction.

**Comment by josteph** [comment]
Ah right, I forgot to put the module type. It should be "commonjs".
