### ISSUE TITLE
Reduce binary size

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#157]
# Analysis
According to very unscientific benchmark (calculated by commenting out and looking at size of index.node),

 - swc_common & dependencies: **5.2MB** (5198800 bytes)

 - swc_ecma_ast: **450KB** (5660136 bytes - `swc_common`)

 - swc_ecma_codegen: **302KB** (5969320 bytes - `swc_ecma_ast`)

 - swc_ecma_parser
   - (with verify feature): **1567KB** (7264728 bytes - `swc_ecma_ast`)
   - (without verify feature): **1552KB** (7249072 bytes - `swc_ecma_ast`)

(verify feature: **15KB**)

 - swc_ecma_transform: **15655KB** = **15.2MB** (23279456 bytes - `swc_ecma_parser`)
   - Base (helpers + macros + util): **2835KB** (10152072 bytes - `swc_ecma_parser`)
   - compat: **9053KB** = **8.8MB** (19422696 bytes - `base`)
     - es3: **1505KB** = **1.5MB** (11694008 bytes - `base`)
     - es2015: **6869KB** = **6.7MB** (17185920 bytes - `base`)
     - es2016: **1066KB** = **1MB** (11243528 bytes - `base`)
     - es2017: **1418KB** = **1.4MB** (11604440 bytes - `base`)
     - es2018: **1477KB** = **1.4MB** (11664656 bytes - `base`)
   - fixer: **286KB** (10444528 bytes - `base`)
   - hygiene: **520KB** (10684040 bytes - `base`)
   - react: **1565KB** = **1.5MB** (11754928 bytes - `base`)
   - proposals: **2220KB** = **2.2MB**
   - typescript: **1055KB** = **1.0MB** (11232016 bytes - `base`)
   - Optimizers (simplify + inline_globals): **808KB**

It seems like type based folder / visitor is problematic.

I'll dig further.

**Comment by LuoZijun** [comment]
https://github.com/johnthagen/min-sized-rust

**Comment by LuoZijun** [comment]
CodeLines: https://github.com/swc-project/swc/blob/master/ecmascript/parser/src/lexer/jsx.rs#L73-L78

this codes looks like try to read a `LiteralNumber`, but this file https://github.com/swc-project/swc/blob/master/ecmascript/parser/src/lexer/number.rs looks can handle that with out regex ?

**Comment by kdy1** [comment]
LTO helped a lot.
