### ISSUE TITLE
Trailing comma incorrectly kept when stripping types for ...rest param

### ISSUE THREAD

**Issue by danopia** [swc-project/swc#1573]
**Describe the bug**

When accepting an options argument in a function, often times I want certain options to be kept separate. I achieve this by setting up an object splat, or whatever they're called, and putting a rest param afterwards to catch the rest.

The issue that I see is that swc is lifting out the trailing comma, if any, from within the TypeScript type clause for the overall parameter, and dropping it into the splat which creates a syntax error.

**Input code**
```typescript
function myFunc({...data}: {
  field: string,
}) {
}
```

**Output code**
```javascript
// Uncaught SyntaxError: Rest element must be last element
function myFunc({ ...data,  }) {
}
```

Note that removing the type's inner trailing comma removes it from the output as well, producing valid code:

**Input code**
```typescript
function myFunc({...data}: {
  field: string
}) {
}
```

**Output code**
```javascript
// All good!
function myFunc({ ...data  }) {
}
```

**Config**

I'm nominally using Deno, so to recreate this bug I wrote a very basic `.swcrc`:

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020"
  }
}
```

**Expected behavior**
The inner comma probably shouldn't get lifted out of the type signatures in general. I don't see when that would be useful

**Version**
```
repro@1.0.0
├── @swc/cli@0.1.36
└── @swc/core@1.2.52
```

**Additional context**
It seems that using semicolons instead of commas inside the type is a valid workaround.

**Comment by Liamolucko** [comment]
It seems like this is the cause:
https://github.com/swc-project/swc/blob/df2a926e9d4908456256e701b1399d3af7d153d0/ecmascript/codegen/src/lib.rs#L1629-L1645

It tries to emit a trailing comma if the input has a trailing comma, but this picks up the trailing comma of the type annotation. Should this functionality just be removed?

**Comment by danopia** [comment]
It looks like a fix for this is rolled into this PR: https://github.com/swc-project/swc/pull/1572/commits/e3b64a051f3c3bff1b0c765836fc3a7df1b6728d

**Comment by kdy1** [comment]
@danopia You are correct, thanks! I'll update the pr.
