### ISSUE TITLE
Source maps not working with swc

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#1581]
.swcrc:

```
{
  "sourceMaps": "inline"
}
```

foo.ts:
```
export const foo = () => {
  return 2;
};
```

When I run: ` node_modules/.bin/swc foo.ts` output is:
```
export var foo = function() {
    return 2;
};


//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzdGRvdXQifQ==⏎  
```

Decoded source map outputs shows:
```
{"version":3,"sources":[],"names":[],"mappings":"","file":"stdout"}
```

P. S. I have this issue with a more complicated scenario, I tried to isolate it. If this example is too simplistic I can expand. Originally I have a problem not being able to debug my code when using `swc` which is quite a big blocker for me in terms of adoption.

**Comment by kdy1** [comment]
Which version are you using? I tried reproducing it, but it worked as expected.

**Comment by kdy1** [comment]
Ah, I found the cause of the bug.

https://github.com/swc-project/cli/blob/92df674e497222f90f6750eb316e485e26c7536f/src/swc/file.ts#L76-L79

This is problematic code.
