### ISSUE TITLE
[Tracker] TypeScript: Multi-file mode

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#1584]
This issue is a tracker for the decorator metadata and const enum support.

Initially, the decorator metadata was requested with #1160 and I implemented a very simple dependency analyzer with #1500.
But it has lots of issues. This issue tracks it.
This issue also tracks const enum, because multi-file mode also allows const enums.

# Decorator metadata

 - [ ] Decl + named export.
 - [ ] `export`s from other module.
 - [ ] Circular dependency.

# Const enum

 - [ ] Basic implementation

But I'm postponing these tasks because I'm not sure what's the correct way to implement them.
I'm not sure about the way to avoid degrading performance while reusing codes of bundler.
(It would be dead simple to implement both of them if we could use the system of the bundler)

**Comment by matthew-dean** [comment]
Will this also fix the issue like "[name] is not exported by [module]" when the export is a type?

**Comment by kdy1** [comment]
Closing as we are not going to implement `project mode` of `tsc`
