### ISSUE TITLE
css support

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#16]
# TODOs
 - [ ] Parser
 - [ ] Transforms (See [postcss][])
   - [ ] minifier (P-high)
   - [ ] cssnext (P-high)
This includes features which does not have compatability hazard.
   - [ ] AutoPrefixer (P-high)
 - [ ] scss support
It might use [libsass][].

[postcss]:https://github.com/postcss/postcss
[libsass]:https://github.com/sass/libsass

**Comment by pickfire** [comment]
We could use https://lib.rs/crates/sass-rs or wait for https://github.com/kaj/rsass or https://github.com/connorskees/grass.
