### ISSUE TITLE
No support for `export default from "foo"`

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#160]
Babel provides the module `@babel/plugin-proposal-export-default-from` that supports the syntax `export default from "foo"`. Swc currently does not support this syntax.

```
error: Expected Semi, got Some(Str { value: Atom('foo' type=inline), has_escape: false })
 --> test.js:1:21
  |
1 | export default from "foo";
  |                     ^^^^^
```

**Comment by kdy1** [comment]
Fixed with swc@1.0.6

**Comment by joaomilho** [comment]
Latest it 1.0.45, any timeline for a release?

**Comment by kdy1** [comment]
@joaomilho 
It is already released. You have to specify `parser: { syntax: "ecmascript", exportDefaultFrom: true }` to use it.

**Comment by joaomilho** [comment]
k, will try
