### ISSUE TITLE
TypeScript: Exponential slowdown with complex method chaining

### ISSUE THREAD

**Issue by ihm-tswow** [swc-project/swc#1612]
**Describe the bug**
When doing complex method chaining, the compilation seems to slow down exponentially. As this doesn't seem to happen for something like `a.b().b().b().b().b()...`, ~it seems related to introducing a large amount of identifiers to the same method chain.~ (this was wrong, see my comment)

**Input code**
I've been able to reduce this to the following code. If I remove the `InterruptFlags` lines the compilation is pretty much instant, and restoring them one by one shows something is clearly exploding at that point.

```ts
export class Profession {
    AddGatheringSpell(
      mod: string
    , id: string
    , lockType: number
    , speed: number = 0
    , maxRange: number = 5
    , totem: number = 0) {
        std.Spells.create(mod,id)
            .Attributes.isHiddenInSpellbook.mark()
            .Attributes.isHiddenFromLog.mark()
            .Attributes.unk41.mark()
            .Range.set(0,maxRange,0,maxRange)
            .SkillLines.add(this.ID).end
            .CastTime.set(speed,0,speed)
            .RequiredTotems.setIndex(0,totem)
            .Effects.add()
                .EffectType.setOpenLock()
                .TargetA.setGameobjectTarget()
                .LockType.set(lockType)
                .effect 
                .BasePoints.set(-1)
                .PointsPerLevel.set(5)
                .Radius.set(2,0,2)
                .ChainAmplitude.set(1)
            .end
            .end
            .SchoolMask.mark(0)
            .InterruptFlags.OnMovement.mark()
            .InterruptFlags.OnPushback.mark()
            .InterruptFlags.OnInterruptCast.mark()
            .InterruptFlags.mark(3)
            .InterruptFlags.mark(4)
            .Visual.makeUnique().end
            
        this.ApprenticeLearnSpell.Effects.addLearnSpells(spl.ID)
        return new GatheringSpell(spl);
    }
}
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false
    }
  }
}
```

**Expected behavior**
Fast compilation

**Version**
The version of @swc/core:
```
@swc/cli: 0.1.39
@swc/core: 1.2.54
```

**Comment by ihm-tswow** [comment]
Some more findings: 

- This does not happen if `target` is set to `es2020`
- This seems to **only** happen in class functions (both static, non-static and constructors), regardless of whether the class is exported or not. I cannot cause this to happen anywhere else. 
- I was wrong to assume this had anything to do with the amount of identifiers, I can now cause this with a chain of `a(...).a(...).a(...)....` as shown in the next point ->
- This only seems to happen in calls where the functions receive **arguments**. It does not happen for `a().a().a().a()...`, but it does happen for `a(1).a(1).a(1).a(1)...`. 

A more minimal example:

```ts
class Test {
	test() {
			 a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
			.a(1)
	}
}
```

**Comment by kdy1** [comment]
I tried reproducing this, but I failed because it took too short time.
`perf` didn't give me any useful information.

Can you share the way you used for invoking swc?

**Comment by ihm-tswow** [comment]
After upgrading to 1.2.60, I cannot reproduce this either so I'll close the issue. You can re-open it if you want to track the change, last broken version i tested it on was `1.2.54`
