### ISSUE TITLE
Missing plugin utilities

### ISSUE THREAD

**Issue by arendjr** [swc-project/swc#1615]
**Describe the feature**

I'm trying to write a plugin for SWC in TypeScript, but I'm struggling as I find there are no utilities besides the basic visitor. If I compare this to Babel, there are utilities for traversing back to parent nodes, helpers for figuring out the types of nodes, utilities for retrieving adjacent comments. Some of what I need I could create my own utilities for, but without having `parent` reference from nodes, any traversal seems barely feasible. Am I overlooking it, or is there no such tooling for SWC?

**Babel plugin or link to the feature description**

See these helpers for Babel, for instance: https://babeljs.io/docs/en/babel-types

**Comment by kdy1** [comment]
There are no tools for it.
And I'm not extending the plugin interface because I think allowing users to use babel plugins as-is is the right way to go.

**Comment by arendjr** [comment]
Fair enough :) Babel plugin support is WIP, right?

**Comment by kdy1** [comment]
@arendjr Yes.
Currently, ast translation is WIP. PR: https://github.com/swc-project/swc/pull/1465

**Comment by kdy1** [comment]
Closing as not relevant anymore
