### ISSUE TITLE
expr simplification produces invalid JS

### ISSUE THREAD

**Issue by wbinnssmith** [swc-project/swc#1619]
The expression simplify transform produces invalid JavaScript using non-strict-mode compatible octal characters, at least as far as Terser considers it. Terser outputs the following: `Legacy octal escape sequences are not allowed in strict mode`. Browsers are okay with the transformed code.

**Input code**
```
"use strict";
	
console.log("\x00" + "\x31");
```

**Output code**
```
"use strict";
console.log("\01");
```

**Config**

Using the simplify transform, I reproduced this by writing a test case in `ecmascript/transforms/optimization/src/simplify/expr/tests.rs`. 

**Expected behavior**
Octal escape sequences are not used. For comparison, Babel's generator accounts for this: https://astexplorer.net/#/gist/f0e75b9c555de86c79ca4c3b0f737f5d/7a03bd48372c6477142e6b77804f6b36e86e3284 (thanks @devongovett for putting that together)

**Version**
The version of @swc/core: `a24266d986b25c8412945b29501ffa4eb568a211`

**Additional context**
Found while trying to transform https://www.npmjs.com/package/pdfjs-dist with the simplify transformer.

**Comment by devongovett** [comment]
Seems like maybe this line should check if the next character is a digit and fallback to the `'\x01'..='\x0f'` case below? https://github.com/swc-project/swc/blob/246bdd5088ce48838def373585fe6ef7a45a2a9c/ecmascript/codegen/src/lib.rs#L2472

**Comment by kdy1** [comment]
I just modified it to emit `\x00` because babel does so.
