### ISSUE TITLE
Unexpected named exports, related to spread operator

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#162]
It appears function parameters are jumping into the list of module exports.
swc version 0.1.7

### Input
```js
export const good = {
  a(bad1) {
    (...bad2) => { };
  }
};
```

### Output
```js
var _ref = {
    a: function(bad1) {
        (function() {
            for(var _len = arguments.length, bad2 = new Array(_len), _key = 0; _key < _len; _key++){
                bad2['_key'] = arguments['_key'];
            }
        });
    }
}, good = _ref;
export { good, bad1, bad2 }
```

Note the unexpected `bad1`, and `bad2` exports.

**Comment by kdy1** [comment]
Fixed with swc@1.0.6

**Comment by duncanbeevers** [comment]
@kdy1 Did this issue regress? I'm seeing similar incorrect behavior.

### Input
```js
export const good = {
  a(bad1) {
    (...bad2) => { };
  }
};
```

### Output
```js
var good = {
    a: function(bad1) {
        (function() {
            for(var _len = arguments.length, bad2 = new Array(_len), _key = 0; _key < _len; _key++){
                bad2['_key'] = arguments['_key'];
            }
        });
    }
};
export { good, bad1, bad2 }
```

**Comment by kdy1** [comment]
@duncanbeevers There is a test for it, and it passes.

https://github.com/swc-project/swc/blob/c1a3cc53c1b6d818e8a5e133f2b1c1d6dcbd8127/ecmascript/transforms/src/modules/common_js/tests.rs#L56-L82


What is your config? (I mean `.swcrc`)

**Comment by duncanbeevers** [comment]
I did a rebuild with a linked c1a3cc53c1b6d818e8a5e133f2b1c1d6dcbd8127
In my project I did an `npm link swc`

`swc --version` displays `0.1.7`.

I get the same results running with `--no-swcrc`.

My project `.swcrc`, such as it is, is very simple
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "numericSeparator": false,
      "classPrivateProperty": false,
      "privateMethod": false,
      "classProperty": true,
      "functionBind": false,
      "decorators": false,
      "decoratorsBeforeExport": false
    }
  }
}
```
