### ISSUE TITLE
emitDecoratorMetadata has a bug

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#1620]
See: https://github.com/Brooooooklyn/swc-node/issues/401

> When emitDecoratorMetadata is enabled, property decorators is being called with property descriptors but tsc dont do this only return property descriptor when is set or is a function

**Comment by zyf0330** [comment]
I meet this problem.

**Comment by Youmoo** [comment]
Hi. When will this issue get resolved and release a new version?

My project uses swc , but the compiled property descriptors conflict with class-transformer libray.

Thank you for your amazing work .

**Comment by kdy1** [comment]
I'm sorry, but I don't have an estimate at the moment.
The only maintainer is me and I have lots of tasks to do.

**Comment by maclockard** [comment]
@kdy1 what PR was this fixed in?

**Comment by kdy1** [comment]
Not sure

**Comment by kdy1** [comment]
@maclockard I just decided to not waste time for issues without enough inforamation
