### ISSUE TITLE
visitCallExpression misses calls embedded in array

### ISSUE THREAD

**Issue by mikob** [swc-project/swc#1623]
**Describe the bug**
visitCallExpression of a Visitor class does not get called if I embed a function within an array.

**Input code**
```
class FnReplacer extends Visitor {
  visitCallExpression(c: CallExpression) {
    console.log(c);
    return c;
  }
}

const bad = `
  function fn() { }
  export default {
    commands: [
      {
        abc: fn(),
      }
    ]
  };
    `;
const ast = await parse(bad, {
  syntax: "ecmascript",
  dynamicImport: true,
});

const fnReplacer = new FnReplacer();
fnReplacer.visitProgram(ast);

// (does not print the fn)
```

**Expected behavior**
Expected the call expression to be visited.

**Version**
1.2.54

**Comment by mikob** [comment]
Still happening on 1.2.58

In `visitArrayExpression`

e.elements = [{
  expression: {type: "ObjectExpression", span: {…}, properties: ...},
  spread: null
}]

then `visitArrayElement` gets called, then `visitOptionalExpression` with the one element:

```
{
  expression: {type: "ObjectExpression", span: {…}, properties: ...}
  spread: null,
}
```
which `visitExpression` gets called with - returning undefined - because there's no type here.

**Comment by kwonoj** [comment]
Closing as legacy plugin visitor is not actively maintained by core team for now. We will accept PRs however.
