### ISSUE TITLE
Expose `RefreshOptions`

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1634]
Either I'm too bad at Rust, or the `RefreshOptions` struct really is not accessible.

It's not listed here: https://rustdoc.swc.rs/swc_ecma_transforms_react/index.html (but used in https://rustdoc.swc.rs/swc_ecma_transforms_react/struct.Options.html)

And code like this
```rust
                  react::refresh(
                    true,
                    Some(react::refresh::RefreshOptions {
                      refresh_reg: "$RefreshReg$".to_string(),
                      refresh_sig: "$RefreshSig$".to_string(),
                      emit_full_signatures: false
                    }),
                    source_map.clone(),
                    Some(&comments),
                  ),
```
 doesn't compile because 
```
error[E0603]: module `refresh` is private
   --> packages/transformers/js/src/lib.rs:225:33
    |
225 |                     Some(react::refresh::RefreshOptions {
    |                                 ^^^^^^^ private module
    |
```

**Comment by mischnic** [comment]
I think the same problem also applies to `Runtime`?

https://github.com/swc-project/swc/blob/b6ff4d6f717dfb4bd41c62c7085e15ace868f296/ecmascript/transforms/react/src/jsx/mod.rs#L41

**Comment by kdy1** [comment]
Thanks! I'll update the pr.

**Comment by kdy1** [comment]
I published a new version.

**Comment by mischnic** [comment]
Thanks!
