### ISSUE TITLE
no rules expected this token in macro call

### ISSUE THREAD

**Issue by newtack** [swc-project/swc#1650]
I use the swc_ecmascript crate and it compiles with 0.29 but stopped compiling I believe with 0.30 and still does not compile with 0.32.

The error message I get is:

error: no rules expected the token `"override"`
   --> /home/ralf/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.4/src/parser/class_and_fn.rs:467:58
    |
467 | ...                   SyntaxError::TS1030(js_word!("override")),
    |                                                    ^^^^^^^^^^ no rules expected this token in macro call

error: no rules expected the token `"override"`
   --> /home/ralf/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.4/src/parser/class_and_fn.rs:472:58
    |
472 | ...                   SyntaxError::TS1029(js_word!("override"), js_word!("readonly")),
    |                                                    ^^^^^^^^^^ no rules expected this token in macro call

error: no rules expected the token `"override"`
   --> /home/ralf/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.4/src/parser/class_and_fn.rs:477:58
    |
477 | ...                   SyntaxError::TS1243(js_word!("override"), js_word!("declare")),
    |                                                    ^^^^^^^^^^ no rules expected this token in macro call

error: no rules expected the token `"override"`
   --> /home/ralf/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.4/src/parser/class_and_fn.rs:500:66
    |
500 |                 SyntaxError::TS1243(js_word!("static"), js_word!("override")),
    |                                                                  ^^^^^^^^^^ no rules expected this token in macro call

error: no rules expected the token `"override"`
   --> /home/ralf/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.4/src/parser/class_and_fn.rs:582:54
    |
582 |                         SyntaxError::TS1089(js_word!("override")),
    |                                                      ^^^^^^^^^^ no rules expected this token in macro call

error: aborting due to 5 previous errors

error: could not compile `swc_ecma_parser`

My Cargo.toml references

swc_common = { version = "0.10", features = ["sourcemap"] }

swc_ecmascript = { version = "0.32", features = [
    "codegen",
    "dep_graph",
    "parser",
    "proposal",
    "transforms",
    "typescript",
    "visit",
] }

The error message looks similar to an earlier resolved issue 745 (https://github.com/swc-project/swc/issues/745)

**Comment by kdy1** [comment]
cargo update will fix it
