### ISSUE TITLE
JS runtime error occurs when nested namespaces of the same name conflict with each other.

### ISSUE THREAD

**Issue by kittygorey** [swc-project/swc#1653]
# JS runtime error occurs when nested namespaces of the same name conflict with each other.

If there are two namespaces with an inner exported namespace sharing the same name, a run time error would occur where Javascript throws the message `Uncaught ReferenceError: <inner_namespace_name> is not defined`. No compilation errors are printed when compiled.

## Example
```ts
namespace X
{
    export namespace Z
    {
        export const foo = 0
    }
}

namespace Y
{
    export namespace Z
    {
        export const bar = 1
    }
}

// Compilation is successful!
// Oh, but running the compiled Javascript file results in the error message: 'Uncaught ReferenceError: Z is not defined'...
```

## Expected Behavior
As far as I know, Typescript should be okay with nested namespaces like above. I expected the compiled Javascript file to not report any errors and have the nested namespaces defined.

## Setup

I'm using ***v1.2.54*** of `@swc/core`. The following `.swcrc` config file is used:
```json
{
	"jsc":
	{
		"parser":
		{
			"syntax" : "typescript"
		},
		"transform": null,
		"target": "es2015",
		"loose": true,
		"keepClassNames" : false
	},
	"minify": true
}
```

I mainly hacked together the config for `swc`, so there might be something bad about the above config file I'm unaware of.

---

Here's a picture of my cat as appreciation for this *purrfect* project.

<img src="https://user-images.githubusercontent.com/77856521/117514723-91a38280-af62-11eb-8dc6-654fbdd72fd7.jpg" alt="drawing" width="200"/>

**Comment by waterlink** [comment]
This is also affecting the default `typescript-fetch` generator of `swagger-codegen` when there are generic models with enums inside of them. Relevant template: https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/handlebars/typescript-fetch/modelGeneric.mustache
