### ISSUE TITLE
Keep original class name when decorator is applied

### ISSUE THREAD

**Issue by egoist** [swc-project/swc#1656]
**Describe the bug**

class name is changed when decorator is also used, e.g. `class Foo` becomes `class Foo1`.

**Input code**

```ts
@ObjectType()
class Foo {}
```

**Output code**

```ts
var _class;
var _dec = ObjectType();
let Foo = _class = _dec((_class = class Foo1 {
}) || _class) || _class;
```

**Config**

```js
{
      jsc: {
          parser: {
          syntax: 'typescript',
          decorators: true,
          dynamicImport: true,
          },
      transform: {
          legacyDecorator: true,
          decoratorMetadata: true,
      },
        target: 'es2019',
    },
}
```

**Expected behavior**

class names should not be changed

**Version**
The version of @swc/core: 1.2.55

**Additional context**

libraries like https://typegraphql.com/ relies on the original class name to determine output graphql type name.

**Comment by kdy1** [comment]
You can use `jsc.keepClassNames`. See: https://swc.rs/docs/configuring-swc/#jsckeepclassnames
