### ISSUE TITLE
panic: Panicked while running parallel benchmarks (es2019)

### ISSUE THREAD

**Issue by zero734kr** [swc-project/swc#1662]
1. Source code

https://github.com/kdy1/benchmark-done-right/blob/main/compat-transform/common.ts#L119...L137

2. `.swcrc` file

https://github.com/kdy1/benchmark-done-right/blob/main/compat-transform/common.ts#L122...L127

3. Error message gained from `swc --sync <input.js>`
   (--sync is required to get panic message)

It's only panicking in parallel mode

4. Backtrace

(You can get it by invoking swc by setting an environment varaible`SWC_DEBUG` to `1`, invoke swc like `SWC_DEBUG=1 npx swc foo.js` on linux / darwin)

```rs
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: worker
             at /home/iojs/build/ws/out/../deps/uv/src/threadpool.c:122:5
  11: start_thread
  12: clone

fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

![image](https://user-images.githubusercontent.com/51540538/117553256-d264cf80-b026-11eb-94d3-9559197e7532.png)
(* The command run above is ``yarn install && SWC_DEBUG=1 yarn bench``)

A strange point is that I tested it in the Docker environment, but it is working perfectly without panic.

If you prefer, I will open issue in https://github.com/kdy1/benchmark-done-right

* OS: Linux Mint 20.1
* CPU: AMD Ryzen 5600X

**Comment by kdy1** [comment]
Can you still reproduce this?

**Comment by zero734kr** [comment]
I upgraded swc from 1.2.57 to 1.2.159 and it seems fixed.
