### ISSUE TITLE
Consider emitting `export {};` to make sure that TS files remain ES modules

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1698]
**Describe the bug**

When transpiling an ESM file with TSC, it always inserts `export {}` in the output (if the output format is set to esnext) to make sure that the output file is also an ES module:

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiEJwLxwHYCuAtgEbBQDcAUEA

**Input code**

```ts
export type Foo = number;
```

**Current behavior (swc, Babel)**

(empty)

**Proposed behaviour (= TSC)**

Just like TSC:
```ts
export {};
```

**Additional context**

There are also some comments in https://github.com/babel/babel/issues/12568

**Comment by bartlomieju** [comment]
CC @kitsonk this has been a problem in Deno for some time as well
