### ISSUE TITLE
Function cannot spread a string into another function's parameter.

### ISSUE THREAD

**Issue by kittygorey** [swc-project/swc#1701]
**Describe the bug**

If there's a function that spreads a string using the spread operator into another function, an error would occur at runtime saying `second argument to Function.prototype.apply must be an array`.

**Input code**

```typescript
const f = (...characters : Array <string>) : number =>
	characters.length

const g = (str : string) : number =>
	f (...str)

g ("meow")
// Compiles fine
// At runtime: "Uncaught TypeError: second argument to Function.prototype.apply must be an array"
```

**Config**

```json
{
	"jsc" :
	{
		"parser" :
		{
			"syntax" : "typescript"
		},
		"transform"       : null,
		"target"          : "es2015",
		"loose"           : true,
		"keepClassNames"  : false
	},
	"minify" : true
}

```

**Expected behavior**
In the above code snippet, function `g` should be able spread the string `str` into function `f` just fine and return a number.

**Version**
The version of @swc/core: 1.2.57

**Comment by Austaras** [comment]
Could you retest it with latest build? I seems to be unable to reproduce this in my machine

**Comment by kittygorey** [comment]
Sorry for the delayed reply. I've recompiled with **1.2.61** with the same config as before and the issue still persists. The runtime error says

```
Uncaught TypeError: second argument to Function.prototype.apply must be an array
    g file:///C:/blah/blah/index.js:1
    <anonymous> file:///C:/blah/blah/index.js:1
```

The outputted code is:

```js
var f=function(){for(var _len=arguments.length,characters=new Array(_len),_key=0;_key<_len;_key++){characters[_key]=arguments[_key];}return characters.length;};var g=function(str){return f.apply(void 0,str);};g("meow");
```

If needed, I can create a fresh environment and test it there instead of doing it in my repository which might be the reason.

**Comment by Austaras** [comment]
It might be caused by your other build tool. In my machine I got
```js
function _arrayWithoutHoles(arr){if(Array.isArray(arr)){for(var i=0,arr2=new Array(arr.length);i<arr.length;i++){arr2[i]=arr[i];}return arr2;}}function _iterableToArray(iter){if(Symbol.iterator in Object(iter)||Object.prototype.toString.call(iter)==="[object Arguments]")return Array.from(iter);}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance");}function _toConsumableArray(arr){return _arrayWithoutHoles(arr)||_iterableToArray(arr)||_nonIterableSpread();}var f=function(){for(var _len=arguments.length,characters=new Array(_len),_key=0;_key<_len;_key++){characters[_key]=arguments[_key];}return characters.length;};var g=function(str){return f.apply(void 0,_toConsumableArray(str));};g("meow");
```

**Comment by kittygorey** [comment]
I've narrowed it down to the `.swcrc` file causing it. I've made a completely fresh environment with only SWC. Compiling using the CLI outputs correct code:

```js
function _arrayWithoutHoles(arr) {
    if (Array.isArray(arr)) {
        for(var i = 0, arr2 = new Array(arr.length); i < arr.length; i++){
            arr2[i] = arr[i];
        }
        return arr2;
    }
}
function _iterableToArray(iter) {
    if (Symbol.iterator in Object(iter) || Object.prototype.toString.call(iter) === "[object Arguments]") return Array.from(iter);
}
function _nonIterableSpread() {
    throw new TypeError("Invalid attempt to spread non-iterable instance");
}
function _toConsumableArray(arr) {
    return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread();
}
var f = function() {
    for(var _len = arguments.length, characters = new Array(_len), _key = 0; _key < _len; _key++){
        characters[_key] = arguments[_key];
    }
    return characters.length;
};
var g = function(str) {
    return f.apply(void 0, _toConsumableArray(str));
};
g("meow");
```

-- but when I add the `.swcrc`, it breaks. Any idea why?

**Comment by kdy1** [comment]
Thanks for narrowing the test case!

**Comment by Austaras** [comment]
So what's your `.swcrc` looks like?

**Comment by kittygorey** [comment]
If I recall correctly, the `.swcrc` should be the same as I gave in the original issue:

```json
{
	"jsc" :
	{
		"parser" :
		{
			"syntax" : "typescript"
		},
		"transform"       : null,
		"target"          : "es2015",
		"loose"           : true,
		"keepClassNames"  : false
	},
	"minify" : true
}
```

Introducing this config and then compiling using the CLI breaks the output. Likely one of the settings is causing it.

**Comment by kdy1** [comment]
This issue was wrong.
You can't spread string if you enable `loose`.

**Comment by desaiuditd** [comment]
> You can't spread string if you enable `loose`.
@kdy1 do you have any documentation or reference link to support this fact?

**Comment by kdy1** [comment]
No, maybe babel have documentation for it I guess?

**Comment by desaiuditd** [comment]
I could find this one - https://github.com/babel/babel/issues/8298

But that would be Babel's behaviour. So is it true that swc is just simply behaving how babel would behave?
Or swc has its own way of interpreting loose mode? Is there any doc I could read on what would happen in swc if loose mode is enabled?

**Comment by kdy1** [comment]
No, but it's related to helper used in loose mode, which is almost identical to one of babel.
