### ISSUE TITLE
TypeScript: Don't emit `export {};` if there are no import/exports declarations in the input

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1706]
**Describe the bug**

`export {};` should only be inserted if the input file actually contained import/export declarations.

TSC only inserts it if there was a import or export in the input file. With swc's current behaviour, the file below is not using strict mode in the input but the output is parsed in strict mode.

(As an optimization, TSC furthermore only emits `export {};` if the output contains no ESM imports/exports. This doesn't actually make a different though since `export {};` is a noop and there are already other delcarations that force strict mode.)

(So one possible rule here would be to only add it if the input contains `import type {}` or [there were `import {}` declarations that actually only imported types](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnAZhqERwEQB0A9AB54DcAUJQMYQB2AzhADYoEsQDmAFD-QEMAbsC4CY0OAMYYAlLPJA) and were therefore also removed)

Related to https://github.com/swc-project/swc/issues/1698

**Input code**

https://github.com/swc-project/swc/blob/8a36435ee1897d40591b9fab77eae188d54a12dc/tests/fixture/pr-1524/comment-2/input/index.tsx#L1-L7

(= non-strict mode)

**Current output**

https://github.com/swc-project/swc/blob/8a36435ee1897d40591b9fab77eae188d54a12dc/tests/fixture/pr-1524/comment-2/output/index.tsx#L1-L8

(= strict mode)

**Expected output**
In that example, no `export {};` is added.

**Comment by kdy1** [comment]
You can pass `Script` instead of `Module` if you want such behavior.
The parser has an api to parse as a module or as a script, based on the content.


But I think some compatibility transforms require some patch to work with `Script`s.

**Comment by kdy1** [comment]
If it's insufficient, please feel free to tell me.

**Comment by mischnic** [comment]
Thanks, so we should be using `parse_program` instead of `parse_module`. That does make sense

I did run into `panicked at 'not implemented: automatic polyfill for scripts'`. In our case, it's fine for a script to become a module.

**Comment by kdy1** [comment]
Seems like changing typescript pass is much easier.
(All passes are written for modules, so I have to test lots of passes to support using `Script`s)

As I have to check if it's a module (import/export exists) anyway, I'll modify the typescript pass.

**Comment by mischnic** [comment]
Thanks!
