### ISSUE TITLE
Export * should allow named export overrides

### ISSUE THREAD

**Issue by lexanth** [swc-project/swc#1714]
**Describe the bug**
When you do `export * from 'x'` and override something in `*` with a named export, according to the spec the named export should override the version from `*`. This pattern is recommended in e.g. https://testing-library.com/docs/react-testing-library/setup

**Input code**
```ts
import { customRender } from './customRender';

// re-export everything
export * from '@testing-library/react';

// override render method
export { customRender as render };
```

**Config**

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "refresh": true
      },
      "hidden": {
        "jest": true
      }
    }
  },
  "module": {
    "type": "commonjs"
  },
  "env": {
    "coreJs": 3,
    "mode": "usage"
  }
}
```

**Expected behavior**
The transpilation should respect the behaviour that the named exports can override the wildcard exports.
e.g. [Babel REPL](https://babeljs.io/repl#?browsers=node%2014&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgYwK4GcYRAJQKYB2AJnlHAL5wBmU2cA5AHQD0am2-xp9A3AFB9mzOFDwBaPAA9IsOHgBupAJ4wAFsAIBzPlJnwAVNVogGAARh5MGzWIA2wAEZQAhlCXNRz5DF4ChcCEUoKGASEUISMhA8NQgiHWloeCQ2LFwI0jhndHCuMnJ-IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env,react&prettier=false&targets=Node-14&version=7.14.1&externalPlugins=) generates the `_exportNames` and then excludes those when defining the wildcard export.

Other refs:
* https://github.com/babel/babel/issues/3986
* https://262.ecma-international.org/6.0/#sec-getexportednames
* https://stackoverflow.com/questions/34745110/es2015-re-export-module-and-override-single-export-function-of-the-re-exported-m

**Version**
The version of @swc/core: 1.2.55

**Additional context**
Workaround is to not depend on this behaviour
```js
import * as rtl from '@testing-library/react';
import { customRender } from './customRender';

module.exports = {
  ...rtl,
  userEvent,
  render: customRender,
};
```

**Comment by atsikov** [comment]
Another case is that star exports should not override named exports
Such module should not export `render` from testing-library
``` js
export { customRender as render } from './customRender';

// re-export everything, but keep named 'render' exported above
export * from '@testing-library/react';
```

**Comment by lexanth** [comment]
@kdy1 This isn't quite fixed.

The code as currently output still gives a runtime error if the re-export is different from the initial export (which is the case in the example above - the aim is to override `render` with our custom version).

In your test (https://github.com/swc-project/swc/pull/1909/files#diff-b558773d8ee3e958908d1bdf859f470eabcd8ff82aee06841982ddcdcb6b11a2) it only checks if there is an existing export of that name with the same thing being exported (`if (key in exports && exports[key] === _react[key]) return;`).

In the babel output ([REPL](https://babeljs.io/repl#?browsers=node%2014&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgYwK4GcYRAJQKYB2AJnlHAL5wBmU2cA5AHQD0am2-xp9A3AFB9mzOFDwBaPAA9IsOHgBupAJ4wAFsAIBzPlJnwAVNVogGAARh5MGzWIA2wAEZQAhlCXNRz5DF4ChcCEUoKGASEUISMhA8NQgiHWloeCQ2LFwI0jhndHCuMnJ-IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env,react&prettier=false&targets=Node-14&version=7.14.1&externalPlugins=)), it also tracks the list of named exports to not override
```js
var _exportNames = {
  render: true
};

Object.keys(_react).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return; // <-- This check is missing in the swc output
  if (key in exports && exports[key] === _react[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function () {
      return _react[key];
    }
  });
});
```
Without this check, at runtime you get an error from not being able to redefine the property (`TypeError: Cannot redefine property: render`)

**Comment by lexanth** [comment]
@kdy1 Can you reopen this, or would you like a new issue?

**Comment by kdy1** [comment]
I prefer a new issue, would you open one?

**Comment by lexanth** [comment]
Raised https://github.com/swc-project/swc/issues/2101 for this
