### ISSUE TITLE
Code can overwrite generated helper functions

### ISSUE THREAD

**Issue by PullJosh** [swc-project/swc#172]
When compiling the following (contrived example of) ecmascript:
```js
// This will overwrite one of the helper functions:
function _createClass(a) {
  return a
}

// This will cause the _createClass helper function to be generated:
class MyClass {
  myMethod() { return 'Hello, world!' }
}

// The instance will no longer be created correctly:
const inst = new MyClass()
console.log(inst.myMethod())
```

The compiler gives no warnings or errors, but the output code fails to run.

This is because in the output (generated code), the auto-generated `_createClass` helper function is overwritten by the user-created function:
```js
function _createClass(Constructor, protoProps, staticProps) {
    if (protoProps) _defineProperties(Constructor.prototype, protoProps);
    if (staticProps) _defineProperties(Constructor, staticProps);
    return Constructor;
}
var _createClass = function _createClass(a) {
    return a;
};
```

This could be solved by automatically renaming the helper functions to something that is unused (ideal), or by giving a compilation error when such a collision occurs (probably easier?).

(For reference, I'm using swc version `0.1.7`)

**Comment by kdy1** [comment]
I'm aware of this issue. This can be fixed by make helper to hold a marker. I'll fix it soon.
