### ISSUE TITLE
Issue running on Oracle Linux

### ISSUE THREAD

**Issue by SomethingSexy** [swc-project/swc#1723]
**Describe the bug**
Running @swc-node/jest on Jenkins that is using Oracle Linux. When running I am receiving 

`TypeError: Can not find node binding files from @swc/core-linux-x64-gnu, @swc/core-linux-x64-gnux32, @swc/core-linux-x64-musl and /mnt/jenkins_workspace/ianow_Panda_panda-ssr_master/node_modules/@swc/core/swc.linux-x64-gnu.node, /mnt/jenkins_workspace/ianow_Panda_panda-ssr_master/node_modules/@swc/core/swc.linux-x64-gnux32.node, /mnt/jenkins_workspace/ianow_Panda_panda-ssr_master/node_modules/@swc/core/swc.linux-x64-musl.node`

I see the modules being installed under node_modules/@swc/ but it appears it is looking for it under node_modules/@swc/core/?

**Input code**

**Config**

```javascript
export default {
  resolver: 'jest-ts-webcompat-resolver',
  testMatch: ['**/test/**/*.+(ts)'],
  testPathIgnorePatterns: ['test/MockStore.ts'],
  transform: {
    [`(${esModules}).+\\.js$`]: ['@swc-node/jest'],
    '^.+\\.(ts|tsx)$': ['@swc-node/jest'],
  },
  transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
};
```

```json
{
  "jsc": {
    "parser": {
      "decorators": true,
      "dynamicImport": true,
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2020"
  }
}
```

**Expected behavior**
Tests to run by finding the correct node bindings.

**Version**
"@swc-node/jest": "^1.2.1",
"@swc/cli": "^0.1.40",
"@swc/core": "^1.2.57",

**Additional context**
Here is the output of the os that the build is running on

NAME="Oracle Linux Server"
VERSION="7.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Oracle Linux Server 7.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.7

**Comment by kdy1** [comment]
Can you see the directory names under `node_modules/@swc`?

**Comment by SomethingSexy** [comment]
@kdy1 This is the list of directories under node_modules/@swc

- cli
- core
- core-android-arm64
- core-darwin-arm64
- core-darwin-x64
- core-linux-arm64-gnu
- core-linux-arm-gnueabihf
- core-linux-x64-gnu
- core-linux-x64-musl
- core-win32-ia32-msvc
- core-win32-x64-msvc

**Comment by kdy1** [comment]
cc @Brooooooklyn 
Do you have any idea?

**Comment by Brooooooklyn** [comment]
Seems like to be `Glibc` compatible problem again,I will add more useful information in `@node-rs/helper` later.

**Comment by Brooooooklyn** [comment]
@SomethingSexy Could you run `ldd --version` on your server, and paste the output?

**Comment by SomethingSexy** [comment]
@Brooooooklyn 

```ldd (GNU libc) 2.17```

**Comment by SomethingSexy** [comment]
I am reading the Rust documentation right, we might need to upgrade our version of glibc? Not sure 2.17 is supported?

**Comment by Brooooooklyn** [comment]
`Glibc` is distributed with the operation system, I found a disussion about how to upgrade `Glibc` version on `Oracle linux`: https://access.redhat.com/discussions/3244811

**Comment by SomethingSexy** [comment]
@Brooooooklyn thanks! I will see about getting it upgraded and see if that helps.

**Comment by SomethingSexy** [comment]
@Brooooooklyn  do you know what the minimum version is we should strive to support?

**Comment by Brooooooklyn** [comment]
swc will always support the `node:lts` docker image, and the `Glibc` version in it is `2.24` for now

**Comment by SomethingSexy** [comment]
@Brooooooklyn  thank you!
