### ISSUE TITLE
Default import replaces named import for the same path

### ISSUE THREAD

**Issue by atsikov** [swc-project/swc#1734]
**Describe the bug**

**Input code**

Given such module
`./A.ts`
``` js
export const foo = 'foo'
export default const baz = 'baz'
```

This doesn't work as expected ❌
`./B.ts`
``` js
import { foo } from './A'
import baz from './A'

console.log(baz, foo) // <-- baz undefined
```

This works fine ✔️
`./C.ts`
``` js
import baz, { foo } from './A'

console.log(baz, foo) // <-- baz foo
```

This works fine as well ✔️
`./D.ts`
``` js
import baz from './A'
import { foo } from './A'

console.log(baz, foo) // <-- baz foo
```

**Expected behavior**
Both `foo` and `baz` in `./B.ts` are correctly resolved

**Version**
The version of @swc/core: 1.2.58

**Comment by kdy1** [comment]
Are you using spack?

**Comment by atsikov** [comment]
@kdy1 I was using `swc-loader`

**Comment by kdy1** [comment]
What is your `.swcrc`?
