### ISSUE TITLE
Return missing on implicit class return value

### ISSUE THREAD

**Issue by timreichen** [swc-project/swc#1738]
`swc_bundler` specific used in Deno.

**Describe the bug**
implicit return is transformed into explicit return without `return` keyword if return value is a class.
**Input code**
Input:
```ts
const fn = () => class Bug {}
console.log(fn())
```
Output:
```ts
const fn = ()=>{
    /* missing return */ class Bug {
    }
};
console.log(fn());
```

**Expected behavior**
No transformation to explicit return OR with transformation to explicit return with `return` keyword.

Either
```ts
const fn = () => class Bug {}
console.log(fn())
``` 
or
```ts
const fn = ()=>{
    return class Bug {
    }
};
console.log(fn());
``` 
**Version**
swc_bundler = "0.34.0"

**Additional context**
Appeared when using `Deno.emit`.
https://github.com/denoland/deno/blob/6044b037fb3efd638e599f39da2b28f53c915319/cli/ast.rs#L146-L183

**Comment by kdy1** [comment]
I think it's already fixed with recent version of swc_ecma_transform_typescript.
Maybe I forgot releasing it, but it's fixed on master.
