### ISSUE TITLE
Non-ascii characters are always replaced with unicode point escapes

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1744]
**Describe the bug**

Unicode point escapes aren't supported in older browsers: https://caniuse.com/mdn-javascript_grammar_unicode_point_escapes

**Input code**
```js
console.log("🤭 ü");
```

**Current behaviour**

```js
console.log("\u{1f92d} \xfc");
```

**Config**

`yarn swc input.js -o output.js`

**Expected behavior**
Make sure that the output still works in older browsers

**Version**
The version of @swc/core: 1.2.58

**Comment by danieltroger** [comment]
Yo @kdy1 it still escapes when using a pound sign (`£`), please see https://github.com/parcel-bundler/parcel/issues/6356#issuecomment-860545276 and maybe add more extensive tests?
