### ISSUE TITLE
Unterminated string literal error when parsing \u2028 and \u2029 in JSON string literal

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#1754]
**Describe the bug**

When parsing JSON using the EcmaScript `Lexer` the Unicode characters `\u2028` and `\u2029` are treated as line breaks and cause parsing to fail with:

```
(node:13991) UnhandledPromiseRejectionWarning: Error: load_transformed failed

Caused by:
    0: Bundler.load() failed
    1: Bundler.loader.load(/home/muji/git/consensys/metamask-extension/node_modules/unicode-confusables/data/confusables.json) failed
    2: failed to load json file at /home/muji/git/consensys/metamask-extension/node_modules/unicode-confusables/data/confusables.json
    3: failed parse json as javascript object: Error {
           error: (
               Span {
                   lo: BytePos(
                       6920931,
                   ),
                   hi: BytePos(
                       6920932,
                   ),
                   ctxt: #0,
               },
               UnterminatedStrLit,
           ),
       }
```

Note also that the `BytePos` is way beyond the size of the file (95779 bytes), not sure if that is a separate issue or not.

When I set up an MVP we can get a diagnostic which was very useful:

```
error: Unterminated string constant
   --> examples/confusables.json:160:2
    |
160 |  " ": " ",
    |  ^

thread 'main' panicked at 'Failed to parse expression.: ()', ecmascript/parser/examples/json.rs:42:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Input code**

This is the file being parsed: https://npmfs.com/package/unicode-confusables/0.1.1/data/confusables.json

An MVP that reproduces the problem is here:

https://github.com/tmpfs/swc-unterminated-string-literal

**Config**

N/A

**Expected behavior**

I expect the JSON file to be parsed correctly to an AST.

**Version**

HEAD / @swc/core - v1.2.59

**Additional context**

I think the issue is calling `is_line_break()` in the context of `Lexer::read_str_lit()` both EcmaScript and JSON should not treat `\u2028` and `\u2029` as line breaks in the context of string literals. See:

* https://tc39.github.io/ecma262/#sec-literals-string-literals
* https://tc39.github.io/ecma262/#sec-line-terminators
* https://www.json.org/json-en.html

I think the existing function should be renamed to a more explicit `is_line_terminator()` (which is the correct intended usage) and we add another function that just tests for carriage return and line feed and call that in `read_str_lit()`.

I will put together a PR for this, thanks :+1:

**Comment by tmpfs** [comment]
Ok, so I have looked into this some more and have a PR that fixes the JSON parse problem but my original hypothesis is wrong so I cannot submit the PR.

Line terminators (`\n`, `\r`, `\u2028` and `\u2029`) should not be allowed in EcmaScript string literals according to the specification but `\u2028` and `\u2029` should be allowed when parsing JSON.

This means that to fix this correctly we would need to know the type of data (`JSON` or `Javascript`) that is being parsed.

@kdy1 , please advise how you want to proceed. I would really like to fix this but I think I would need some guidance to ensure a fix can be merged.

**Comment by tmpfs** [comment]
Also furthermore it looks like both V8 and JavaScript Core appear to allow `\u2028` and `\u2029` contrary to the spec.

Also see: https://github.com/tc39/test262-parser-tests/issues/26 which I believe it a mis-interpretation like my original theory.

**Comment by tmpfs** [comment]
Looks like there is a PR to move those tests to the pass directory: https://github.com/tc39/test262-parser-tests/pull/30

**Comment by eelco** [comment]
Please note that `\u2028` and `\u2029` are valid characters in JS too since ES2019: https://github.com/tc39/proposal-json-superset

This is currently causing issues in our usage of SWC, where we compile code with user input that might have these characters.
