### ISSUE TITLE
Infinite hang running spack

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#1756]
**Describe the bug**

The `spack` program gets stuck in an infinite loop whilst doing the topological sort in the chunking phase.

**Input code**

MVP: https://github.com/tmpfs/metamask-extension/tree/swc 

I use `yarn link` to run against my local versions of `@swc/core` and `@swc/cli`.

First run `yarn setup` then try to compile everything in `ui` with `npx spack`.

You will need to be building using all the PRs I submitted over the past couple of days to get past earlier errors and reproduce this, if you want this branch has them all: https://github.com/tmpfs/swc/tree/develop.

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es2016",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false
  }
}
```

```js
const path = require('path');
const { config } = require('@swc/core/spack')

module.exports = config({
  entry: {
    'main': __dirname + '/ui/index.js',
  },
  output: {
    path: path.join(__dirname, "builds", "ui"),
  },
  module: {},
});
```

**Expected behavior**

I expect the program to complete and generate a bundle.

**Version**

HEAD (with recent bug fixes)

**Additional context**

I stepped through and am certain the problem lies in `toposort_real_module_ids()` but I don't have a clear enough mental model of the code to be able to fix this. In particular, these are the lines that create the infinite loop: https://github.com/swc-project/swc/blob/master/bundler/src/modules/sort/chunk.rs#L217-L226.

If you comment out those lines then the program proceeds to the `finalize()` phase and completes.

**Comment by tmpfs** [comment]
Note that the earlier code here: https://github.com/swc-project/swc/blob/master/bundler/src/modules/sort/chunk.rs#L194-L203 is also potentially problematic although it is not the culprit in this case. 

I think it would be preferable to refactor this function to avoid `VecDequeue` and the current `pop` / `push` logic but don't understand the code well enough to know what a solution might look like.

**Comment by tmpfs** [comment]
We have been looking into this a bit more and determines that this file as an entry point will cause the issue: https://github.com/tmpfs/metamask-extension/blob/develop/ui/pages/swaps/exchange-rate-display/exchange-rate-display.stories.js

Hopefully this may help you narrow down the problem.

**Comment by kdy1** [comment]
Seems like infinite hang is fixed by https://github.com/swc-project/swc/pull/1739 and the patch is already published.

But I got a different error.

```
(node:97887) UnhandledPromiseRejectionWarning: Error: load_transformed failed

Caused by:
    0: Bundler.load() failed
    1: Bundler.loader.load(/Users/kdy1/projects/metamask-extension/node_modules/unicode-confusables/data/confusables.json) failed
    2: failed to load json file at /Users/kdy1/projects/metamask-extension/node_modules/unicode-confusables/data/confusables.json
    3: failed parse json as javascript object: Error {
           error: (
               Span {
                   lo: BytePos(
                       6921159,
                   ),
                   hi: BytePos(
                       6921160,
                   ),
                   ctxt: #0,
               },
               UnterminatedStrLit,
           ),
       }
```


I opened the corresponding file with vscode, and it shows a warning.

Closing as line ending issue is already reported at https://github.com/swc-project/swc/issues/1754

**Comment by kdy1** [comment]
@tmpfs Reducing the test case would really help

**Comment by tmpfs** [comment]
Hi @kdy1, I have reduced it as far as possible here:

https://github.com/tmpfs/spack-infinite-loop-mvp

There is a little bit more information in the README. The interesting thing is that commenting out *any of the imports* will make the build succeed so this looks like an edge case quite specific to this sort of module graph. Hopefully something about the module graph will point you to the bug!

Anything else I can do to help move this along please let me know :pray:

**Comment by kdy1** [comment]
Thanks!

Cycle detection is always an issue.
I'll fix this soon.

**Comment by tmpfs** [comment]
@kdy1, this is awesome, thanks so much. You are amazing :raised_hands:
