### ISSUE TITLE
The conversion of React props value, unicode character is unnecessary

### ISSUE THREAD

**Issue by fiture** [swc-project/swc#1782]
Here is the swcrc config:
```
{
	"jsc": {
		"parser": {
			"syntax": "typescript",
			"tsx": true
		}
	}
}
```

This is the source file:
```js
import React from 'react';

export const HelloWorld = () => {
  return (<div title="您好SWC"></div>)
}

```

Result：

```js
import React from 'react';
export var HelloWorld = function() {
    return(/*#__PURE__*/ React.createElement("div", {
        title: "\\u60a8\\u597dSWC"
    }));
};

```

As we can see all the chinese character was converted to unicode. but that is not what we want.

**Comment by haydnhkim** [comment]
Other non-English strings have the same problem. #1792

**Comment by haydnhkim** [comment]
@kdy1 It looks like it could have been caused by a #1732.

**Comment by Austaras** [comment]
@kdy1 hi this is a severe bug which seems to be caused by unicode in jsx props are being transformed twice in jsx transform and codegen. The prior is introduced in #1732 but why is unicode transform in codegen needed?

**Comment by kdy1** [comment]
Because some Unicode characters do not fit into the `String` of rust.

**Comment by kdy1** [comment]
I made some wrong design decisisions, and the it's a complement

**Comment by Austaras** [comment]
But wasn't data in `node.value` already a rust string?

**Comment by kdy1** [comment]
Oh I found a way to fix it. Currently, swc is depending on UB being not optimized by the compiler

**Comment by vovacodes** [comment]
Just run in to this problem just to find out that it's already being fixed 😄 God's work @kdy1 . Please look at my PR that adds a test for it: https://github.com/swc-project/swc/pull/1817
