### ISSUE TITLE
REPL mode

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#1785]
I often use REPL for ad hoc experimentations. When you run `babel-node` without any arguments it enters a REPL mode. 

It would be great if running `swc-node` entered REPL mode too.

**Comment by adrienjoly** [comment]
I'm also interested in solutions.

https://github.com/Brooooooklyn/swc-node was suggested as one, in https://github.com/swc-project/swc/discussions/3835.

**Comment by kwonoj** [comment]
Closing as original request itself is fulfilled.
