### ISSUE TITLE
strip type-only imports from TypeScript files

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#179]
TypeScript allows importing modules solely for their types.  This is used, for example, to use types in an annotation without triggering the module to eagerly load at runtime.  Perhaps the module does not exist at runtime.

```
import {Types} from 'other';
const a: Types.foo = {/* yadda yadda */};
```
In this case the emitted code should omit the `import` statement.

Will swc ever support this?

**Comment by kdy1** [comment]
@cspotcode I'm not sure if it's safe to remove import because multiple things can be exported with same name.

**Comment by kdy1** [comment]
swc will support this. It seems very important mainly because typescript interface does not exists at runtime.

**Comment by kdy1** [comment]
Fixed with @swc/core@1.0.13.
Note that `swc` is renamed to `@swc/core` and `swc-cli` is renamed to `@swc/cli`.

**Comment by Kronuz** [comment]
How can I use it?
I'm getting errors like this:

```
error: Expected Comma, got Some(LBrace)
  --> modules/store.js:10:13
   |
10 | import type { StateHelpers, StateInstance, StateObject } from '../config/types';
   |

error: Expected Comma, got Some(Colon)
  --> modules/dom.js:15:38
   |
15 | export function getClientRect(element: HTMLElement): Object {
   |                                      ^

error: Expected LBrace, got Some(Colon)
 --> modules/helpers.js:9:27
  |
9 | export function isMobile(): boolean {
  |                           ^

error: Expected Comma, got Some(LBrace)
  --> modules/step.js:11:13
   |
11 | import type { StepProps, JoyrideProps } from '../config/types';
   |             ^
```

**Comment by kdy1** [comment]
@Kronuz It's enabled if you specify `syntax: typescript`. It's swc's bug that does not strip type imports correctly.

**Comment by Kronuz** [comment]
But if I specify typescript, what esnext stuff will be lost? The things I enable in `.swcrc`, like `jsx` or the `exportDefaultFrom`? Because I do need some of those flags on.

**Comment by kdy1** [comment]
@Kronuz You can't, at least currently, because `export default from 'foo'` is not a valid typescript syntax.

**Comment by Kronuz** [comment]
Yes, imports/exports in typescript do change... maybe we could just add typing (or ignore it) to esnext. That way we could feed typescript-like esnext or flow code and it would just strip typings.

**Comment by cspotcode** [comment]
What would be the purpose of that?  If someone's writing typescript, they
presumably intend it to be compatible with TypeScript's language service.
Otherwise there's no point.

So if someone's writing Typescript, they're writing according to the rules
and conventions established by TS.  So swc merely needs to understand and
implement those conventions so that the runtime code behaves according to
the developer's expectations.

**Comment by ricardobeat** [comment]
@kdy1 could you point to the commit were this was fixed in @swc/core@1.0.13?

I think this was not fully resolved - still getting errors when using `import { SomeType } from `../types/foo` where foo is `foo.d.ts`

**Comment by kdy1** [comment]
@ricardobeat https://github.com/swc-project/swc/pull/217/commits/cc32edaeda620b19a67e852ee0efd36815b6b3f0

**Comment by cspotcode** [comment]
According to the test case added in cc32eda, swc is still preserving type-only imports.

```
import {Type} from './types';
```
...becomes
```
import './types';
```

In order for TypeScript to behave the same way, we need to set `"importsNotUsedAsValues": "error"` in `tsconfig.json`.

However, TypeScript's default & legacy behavior is to remove that import statement entirely.
