### ISSUE TITLE
Doesn't export the default value when `interopRequireDefault` is applied

### ISSUE THREAD

**Issue by merceyz** [swc-project/swc#1790]
**Describe the bug**

swc exports the incorrect value when the `interopRequireDefault` helper is applied to a separate import from the same library

**Input code**

Reproducible using the API

```js
const swc = require(`@swc/wasm`);
console.log(swc.transformSync(`
import semver from 'semver';

export {SemVer} from 'semver';

export function foo() {
  return new semver.SemVer('');
}
`, {
  module: {type: `commonjs`},
  jsc: {
    externalHelpers: true,
  },
}).code);
```

The output exports `_semver.SemVer` instead of `_semver.default.SemVer`

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.foo = foo;
var swcHelpers = require("@swc/helpers");
var _semver = swcHelpers.interopRequireDefault(require("semver"));
Object.defineProperty(exports, "SemVer", {
    enumerable: true,
    get: function() {
        return _semver.SemVer;
    }
});
function foo() {
    return new _semver.default.SemVer('');
}
```

**Config**
n/a

**Expected behavior**

```patch
diff --git a/out.js b/out.js
index 3b5596341..8b5e63f09 100644
--- a/out.js
+++ b/out.js
@@ -8,7 +8,7 @@ var _semver = swcHelpers.interopRequireDefault(require("semver"));
 Object.defineProperty(exports, "SemVer", {
     enumerable: true,
     get: function() {
-        return _semver.SemVer;
+        return _semver.default.SemVer;
     }
 });
 function foo() {

```

**Version**
The version of @swc/wasm: 1.2.58

**Additional context**
https://github.com/yarnpkg/berry/pull/2228

**Comment by cspotcode** [comment]
I think we may need to revise the description of this issue.  The exported value should actually be `require('semver').SemVer`, at least according to TypeScript's behavior:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAZwKYgG5KnAZlCI4DkyaGBA3ALABQ1SAHpLHAN4DKKAahgL7a75EU6KOWq0G0eFgCuAOwDGMYBFnYIEABQBKFtThwoSGNKirZSAO6IhGAHTsQXKBoIEtlKtyA

I believe this issue may be fixed by #1829
