### ISSUE TITLE
@swc/wasm has invalid SPDX license: `Apache-2.0/MIT`

### ISSUE THREAD

**Issue by connorjs** [swc-project/swc#1798]
_Cutting a bug, but feel free to re-label if licensing does not warrant the bug label._

**Describe the bug**

`@swc/wasm` (https://www.npmjs.com/package/@swc/wasm) has license `Apache-2.0/MIT`, which is not a valid SPDX license.

**Input code** - N/A

**Config** - N/A

**Expected behavior**

Instead, I think it should have license `(Apache-2.0 AND MIT)` (`AND` instead of `/`), which is a valid SPDX license.

**Version**

Latest/all?

**Additional context**

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license provides commentary on licensing syntax, including SPDX references.

Also see the spec/grammar https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/

**Comment by signal-intrusion** [comment]
For more context: this can cause issues with license scanning software and raise alarms that block using the library in some organizations.
