### ISSUE TITLE
Compared to Sucrase?

### ISSUE THREAD

**Issue by arv** [swc-project/swc#180]
Sucrase, which is written in JS is already 20x faster than Babel*. How does swc compare to Sucrase?

[*] https://github.com/alangpierce/sucrase

**Comment by kdy1** [comment]
@arv Surcrase compiles to ecmascript to ecmascript 6 while swc compiles ecmascript to ecmascript 3. Currently swc does not provide option to ecmascript 2015 / 2016 / 2017 but it will provide an option soon.
