### ISSUE TITLE
“error: 'delete' cannot be called on an identifier in strict mode” in non-strict mode

### ISSUE THREAD

**Issue by andersk** [swc-project/swc#1810]
**Describe the bug**

swc incorrectly tells me “error: 'delete' cannot be called on an identifier in strict mode”, even though I’m not in strict mode.

```console
$ npx swc in.js
error: 'delete' cannot be called on an identifier in strict mode
 --> in.js:1:8
  |
1 | delete a;
  |        ^

failed to process js file

Caused by:
    failed to parse module: error was recoverable, but proceeding would result in wrong codegen
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/tmp/test/node_modules/@swc/cli/lib/swc/util.js:109:15)
    at files (/tmp/test/node_modules/@swc/cli/lib/swc/file.js:178:18)
    at async _default (/tmp/test/node_modules/@swc/cli/lib/swc/file.js:197:9)
```

**Input code**

```js
delete a;
```

**Config**

```json
{
  "module": {
    "type": "commonjs",
    "strictMode": false
  }
}
```

**Expected behavior**
I’m not in strict mode, so this should parse without an error.

**Version**
The version of @swc/core: 1.6.20

**Comment by kdy1** [comment]
Your config is wrong.
Module code is always in strict mode and if you want non-strict context, you should parse it as a script.

**Comment by kdy1** [comment]
```
    "strictMode": false
```

Is about emitting `'use strict'`.

**Comment by andersk** [comment]
Thanks. I haven’t found a way to parse as a script from the `swc` command line or `.swcrc`, but I found that the `@swc/core` functions accept `{isModule: false}`, which seems to do the right thing here. (It leads to another problem, though, which I filed as #1814.)
