### ISSUE TITLE
Firefox 72-78 doesn't support nullish assignment

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1812]
**Describe the bug**

swc doesn't transpile nullish assignment for `firefox 72` up until `firefox 78` (the last version not to support it): https://caniuse.com/mdn-javascript_operators_logical_nullish_assignment

It should also be transpiled wit `firefox esr` (which I think is equivalent to firefox 78 currently)

**Input code**

```js
let x = 1;
x ??= 2;
console.log(x);
```

**Config**

```json
{
  "dependencies": ...,
  "browserslist": "Firefox 72"
}
```

```json
{
	"env": {
		"shippedProposals": true
	}
}
```

**Expected behavior**
`??=` should not be used in the output

**Version**
```
    "@swc/cli": "^0.1.46",
    "@swc/core": "^1.2.60"
```

**Additional context**

https://github.com/parcel-bundler/parcel/issues/6440

**Comment by kdy1** [comment]
Seems like babel compat data is wrong?

https://github.com/babel/babel/blob/6c8b2336f6216479215114585c3e0777f8113a6c/packages/babel-compat-data/data/plugins.json#L55

**Comment by mischnic** [comment]
Babel transpiles it 
- [for firefox 71 into "old" syntax](https://babeljs.io/repl#?browsers=firefox%2071&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAHhC8EEYDcAoGB-d8BMqDGA9gHYDOBoAdMAQOYAUUAlEkA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.14.5&externalPlugins=%40babel%2Fplugin-syntax-import-assertions%407.12.1)
- [for firefox 72 `x ??= 2;` is turned into `x ?? (x = 2);`](https://babeljs.io/repl#?browsers=firefox%2072&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAHhC8EEYDcAoGB-d8BMqDGA9gHYDOBoAdMAQOYAUUAlEkA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.14.5&externalPlugins=%40babel%2Fplugin-syntax-import-assertions%407.12.1)

**Comment by mischnic** [comment]
I think this is the correct key in the data: https://github.com/babel/babel/blob/6c8b2336f6216479215114585c3e0777f8113a6c/packages/babel-compat-data/data/plugins.json#L41

Nullish coalesing is just`??`, not the assignment part

**Comment by kdy1** [comment]
Ah, I see. I missed `x ?? (x = 2);`
