### ISSUE TITLE
With isModule: false, emits references to non-emitted helpers

### ISSUE THREAD

**Issue by andersk** [swc-project/swc#1814]
**Describe the bug**

When transforming a module, swc emits definitions for the helpers it references (such as `_typeof`); however, when transforming a script, it references helpers without emitting their definitions. This leads to a `ReferenceError` when the result is run.

**Input code**

```js
> swc.transformSync("typeof Math")  // works
{
  code: 'var _typeof = function(obj) {\n' +
    '    return obj && typeof Symbol !== "undefined" && obj.constructor === Symbol ? "symbol" : typeof obj;\n' +
    '};\n' +
    'typeof Math === "undefined" ? "undefined" : _typeof(Math);\n'
}
> swc.transformSync("typeof Math", {isModule: false})  // fails
{
  code: 'typeof Math === "undefined" ? "undefined" : _typeof(Math);\n'
}
```

**Config**
none

**Expected behavior**
If I’m understanding correctly, swc should emit the same `var _typeof = …` in script mode that it emits in module mode. (Perhaps an IIFE is needed to scope the extra definitions in a script, although swc doesn’t do that for `let` at a script’s top level so I’m not sure.)

**Version**
The version of @swc/core: 1.2.60

**Comment by sventschui** [comment]
When using `externalHelpers: true` with `isModule: false` I'd also expect `require()` statements to be added for the external helpers, which currently doesn't work neither.

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/swc-project/swc/pull/4025
