### ISSUE TITLE
Jest hangs forever when importing component from locally linked npm package.

### ISSUE THREAD

**Issue by sznowicki** [swc-project/swc#1816]
**Describe the bug**

I've noticed when upgrading to recent @swc/core (after 1.2.54) my builds hang forever. Applies to libraries and a website that uses them (Webpack + sac-loader).

The main project is a monorepo (React package, CSS lib, JS lib).

On the other project, which is a simple react app that uses the other libraries, I noticed during optimisations that jest also hangs. After some investigation I'm sure it's happening when I have linked packages.

So it seems like swc/code hangs forever when:
- package is linked with `yarn link package-name`
- or when it's a monorepo setup (with yarn workspaces).

I guess it might be some platform quirk (yarn link and yarn workspaces use symlinks).

I can provide a repro repo but not today, sorry for that.

**Input code**
When I removed import like this jest stopped hanging itself. Then I unlink the package and jest also worked. Only hangs when package is linked:

```javascript
import { Container } from '@namespace/package-name';
```

**Config**

The website within a monorepo:
```json
{
  "module": {
    "type": "commonjs"
  },
  "exclude": ["/__tests__/"],
  "env": {
    "coreJS": 3,
    "mode": "usage"
  },
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "numericSeparator": false,
      "classPrivateProperty": false,
      "privateMethod": false,
      "classProperty": false,
      "functionBind": false,
      "decorators": false,
      "decoratorsBeforeExport": false
    },
    "transform": {
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "throwIfNamespace": true,
        "development": false,
        "useBuiltins": false
      },
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    }
  }
}

```

The website where I noticed jest hanging:

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "privateMethod": true
    },
    "externalHelpers": false
  },
  "env": {
    "coreJs": 3
  }
}

```

That website uses SWC via Parcel, deps are:
```JSON
{
"devDependencies": {
    "@parcel/transformer-sass": "2.0.0-nightly.713+003cce7b",
    "@swc/jest": "^0.1.2",
    "browserslist": "^4.16.6",
    "jest": "^27.0.4",
    "parcel": "^2.0.0-beta.3.1"
  },
  "dependencies": {
    "@namespace/package-name": "^3.1.1",
    "intl-format-cache": "^4.3.1",
    "intl-messageformat": "^9.6.18",
    "intl-messageformat-parser": "^6.4.4",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

Jest config:
```javascript
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest'],
  },
  testEnvironment: 'jsdom',
  collectCoverageFrom: [
    'src/**/*.js',
    'src/**/*.jsx',
  ],
  moduleNameMapper: {
    '\\.(scss|css)$': '<rootDir>/__mocks__/styleMock.js',
    '^.+\\.svg$': '<rootDir>/__mocks__/svgMockedTransform.js',
  },
};

```

**Expected behavior**
Transpilation should not hang

**Version**
The version of @swc/core: everything above 1.2.54

**Additional context**
Like I mentioned before, excuse me for not providing a repro repo, I'll try make one over the weekend.

**Comment by jantimon** [comment]
we saw the very same bug in our mono repository - jest runs a lot of tests but suddenly it hangs forever without any message..

`next: "12.1.7-canary.24`

![Code Change](https://user-images.githubusercontent.com/4113649/171875643-75f2eef2-5e2a-4838-abe1-b23370214cee.jpg)

it worked with babel but hangs with swc

we don't use symlinks and I can't see any dedicated pattern to reproduce the bug 😕

another run did not freeze but instead crashed:

![Pipelines_-_Run_merge_20220603_16_41_logs](https://user-images.githubusercontent.com/4113649/171882398-7314bf0f-0beb-4680-91ed-5c6f35e3c629.jpg)

**Comment by sznowicki** [comment]
@kdy1 is it fixed?

**Comment by kdy1** [comment]
No. Read comments

2023년 2월 21일 (화) 오후 3:41, Szymon Nowicki ***@***.***>님이 작성:
