### ISSUE TITLE
Cannot parse yield and await as identifiers

### ISSUE THREAD

**Issue by uhyo** [swc-project/swc#1822]
**Describe the bug**

swc cannot parse `yield` and `await` used as identifiers.

**Input code**

`yield` repro:

```js
function foo() {
  const yield = 3;
  return yield;
}
```

`await` repro:

```js
function foo() {
  const await = 3;
  return await;
}
```

We get these errors when compiling these code with swc:

```
error: 'implements', 'interface', 'let', 'package', 'private', 'protected',  'public', 'static', or 'yield' cannot be used as an identifier in strict mode
 --> repro2.js:2:9
  |
2 |   const yield = 3;
  |         ^^^^^

error: Unexpected token `yield`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier
 --> repro2.js:3:10
  |
3 |   return yield;
  |          ^^^^^

failed to process js file
```

```
error: Expected ident
 --> repro.js:2:9
  |
2 |   const await = 3;
  |         ^^^^^

failed to process js file
```

**Config**

```json
{}
```

**Expected behavior**

Both repros are valid ECMAScript code, so transpiled output should be emitted.

**Version**
The version of @swc/core: `1.2.60`

**Additional context**

I was actually using the `swc_ecma_parser` crate (`0.57.1`) directly from my Rust code and found the above problem.

**Comment by kdy1** [comment]
If you use parse_module, `yield` and `await` is not a valid identifier.
