### ISSUE TITLE
Invalid ES5 emitted if class has reserved word as method name

### ISSUE THREAD

**Issue by Qix-** [swc-project/swc#1838]
**Describe the bug**

SWC emits a `function let() {}` which causes an error in strict mode stating `'let' is a reserved word` (and thus cannot be used as a function name) if a class has a method called `let`. I would imagine this is also the case with other reserved words.

**Input code**

```javascript
class Foo {
    let() {}
}
```

outputs:

```javascript
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
function _defineProperties(target, props) {
    for(var i = 0; i < props.length; i++){
        var descriptor = props[i];
        descriptor.enumerable = descriptor.enumerable || false;
        descriptor.configurable = true;
        if ("value" in descriptor) descriptor.writable = true;
        Object.defineProperty(target, descriptor.key, descriptor);
    }
}
function _createClass(Constructor, protoProps, staticProps) {
    if (protoProps) _defineProperties(Constructor.prototype, protoProps);
    if (staticProps) _defineProperties(Constructor, staticProps);
    return Constructor;
}
var Foo = /*#__PURE__*/ function() {
    "use strict";
    function Foo() {
        _classCallCheck(this, Foo);
    }
    _createClass(Foo, [
        {
            key: "let",
            value: function let() {        // <--- INVALID JAVASCRIPT
            }
        }
    ]);
    return Foo;
}();
;
```

In firefox 89.0.1, this error is thrown:

```
Uncaught SyntaxError: let is a reserved identifier
```

**Config**

N/A - no config, just running straight swc:

```console
$ swc test.js -o test.es5.js
```

**Expected behavior**
Either `function let_` or something of the sort, or simply don't name those functions anything.

**Version**
The version of @swc/core: `1.2.61`

**Additional context**
None.

**Comment by Austaras** [comment]
This is a little bit complicated as `let` is only reserved in strict mode per [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#future_reserved_keywords), @kdy1 what's your opinion? Maybe add an option for strict mode and one for module(which indicates the former)?

**Comment by kdy1** [comment]
I don't think `let` being transpiled to `_let` is a big problem.
So... simply renaming with reserved-keywords pass would be enough.

**Comment by Qix-** [comment]
Awesome! What's the release schedule like? :)

**Comment by kdy1** [comment]
I started publishing of new version.
Github action will publish it soon.

**Comment by Qix-** [comment]
Thanks so much!
