### ISSUE TITLE
typescript paths alias

### ISSUE THREAD

**Issue by pincman** [swc-project/swc#1858]
how to configure `.swcrc` to support paths alias from tsconfig.json
`tsconfig.json` file
```
"paths": {
            "@/*": ["src/*"]
 }
```
my `bin.js` like follow
```
#!/usr/bin/env node
const { execSync } = require('child_process');

const path = require('path');

const register = require.resolve('@swc/register');

const argv = process.argv
    .slice(2)
    .map((i) => `"${i}"`)
    .join(' ');
const runner = path.resolve(__dirname, 'runner.ts');

execSync(`node -r ${register} ${runner} ${argv}`, {
    stdio: 'inherit',
});

```
and I found #1834 pr has been merged,so how to config it?

**Comment by kdy1** [comment]
It's not published yet.

**Comment by pincman** [comment]
@kdy1 thx for your reply  and when will it be released?

**Comment by kdy1** [comment]
I'm not sure, but I want to publish a new version today or tomorrow.

**Comment by pincman** [comment]
@kdy1 hope the new version will support paths alias,it will be a great work😀

**Comment by sinbargit** [comment]
@kdy1  does 1.2.62 support the path alias?

**Comment by kdy1** [comment]
Yes, https://swc.rs/docs/configuring-swc/#jscpaths
(I found a typo there... but it does not affect usage)

**Comment by sinbargit** [comment]
@kdy1  please take a look at my configure. That still not work. The version of swc/core is 1.2.62
```
{
    sourceMaps: false,
    module: {
      type: 'commonjs',
      strict: true,
    },
    jsc: {
      paths: {
        "@/*": ["src/*"],
        "@test/*": ["test/*"]
      },
      target: 'es2017',
      parser: {
        syntax: 'typescript',
        decorators: true,
      },
      transform: {
        legacyDecorator: true,
        decoratorMetadata: true,
      },
    },
  }
```

**Comment by pincman** [comment]
@kdy1 still not work

**Comment by hexelon** [comment]
@kdy1 paths seems to be missing in typing and still doesn't seem to work :/

**Comment by kdy1** [comment]
@hexelon I will fix it with a new version.

**Comment by kfirba** [comment]
@kdy1 Would be amazing! I'm also having issues with this new feature - it doesn't work. I tried both the `.swcrc` and JS function call methods, and neither one worked.

Thanks for your hard work! 🙂

**Comment by kfirba** [comment]
@kdy1 This isn't in 1.2.64 right? I just updated and it still does not work. Is it due to 1.2.65?

**Comment by kdy1** [comment]
Yes

**Comment by kfirba** [comment]
@kdy1 Thanks! 
Any estimation of when 1.2.65 will be out?

**Comment by kdy1** [comment]
I'm not sure, but maybe next week.

**Comment by kdy1** [comment]
I'll publish a new version.

**Comment by kfirba** [comment]
@kdy1 Thanks for the version!

I noticed that each path transformed is now being added with a `.ts` suffix. Why is that? I would expect to have no suffix added (there is no suffix in the original code) or at least a `.js` file since we transpiled a `.ts` file

**Comment by kdy1** [comment]
Oh, my bad. I forgot excluding extensions.
I filed an issue for it. https://github.com/swc-project/swc/issues/1934

**Comment by JanJakes** [comment]
Does this support targeting ESM modules? If I omit the `module` directive in `.swcrc` or use `"module": { "type": "es6" }`, it doesn't seem to work. (With `"module": { "type": "commonjs" }` paths are replaced.)

**Comment by ibraelillo** [comment]
This is still not working on es6, nor when omitting "module"

**Comment by JanJakes** [comment]
@ibraelillo So do you mean https://github.com/swc-project/swc/issues/1943 is not working?

**Comment by Stuyk** [comment]
Would love to see this feature in SWC sooner rather than later.

**Comment by kdy1** [comment]
It's already implemented
