### ISSUE TITLE
typescript auto export a default module

### ISSUE THREAD

**Issue by pincman** [swc-project/swc#1859]
**Describe the bug**
compiler will auto export a default module

**Input code**
`app.config.ts`

```typescript
export const app: ConfigRegister<AppConfig> = () => ({...})
```

`database.config.ts`

```typescript
export const database: ConfigRegister<DatabaseConfig> = () => {})
```

`index.ts`

```
export * from './app.config';
export * from './database.config';
```

```typescript
import * as config from './config';
console.log(config)
```

output will be
```json
{
  app: [Getter],
  database: [Getter],
  default: { app: [Getter], database: [Getter] }
}
```
if `"noInterop": true`
other default like `import merge from 'deepmerge';`(deepmerge in node_modules) not work
error 
```
 this.config = (0, _deepmerge).default({
TypeError: (0 , _deepmerge).default is not a function
```

**Config**

```json
{
    "sourceMaps": false,
    "jsc": {
        "loose": true,
        "parser": {
            "syntax": "typescript",
            "decorators": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "target": "es2020",
        "externalHelpers": false
    },
    "module": {
        "type": "commonjs",
        "strict": true
    }
}
```

**Expected behavior**
Like tsc and ts-node,it will get
```json
{
  app: [Getter],
  database: [Getter]
}
```
and 
`import xxx from 'xxx'` work fine

**Version**

 "@swc/core": "^1.2.61",
 "@swc/register": "^0.1.7",

**Additional context**

**Comment by kdy1** [comment]
I failed to understand what you said. I tested with your code and it works as intended.

**Comment by pincman** [comment]
@kdy1 kdy1can't work,it has an error
`npm i deepmerge`and `import merge from 'deepmerge';` and `merge(xxx,yyy)`
has an error `(0, _deepmerge).default({`
other package is also like that
`_findUp.default.sync([ TypeError: Cannot read property 'sync' of undefined`

**Comment by kdy1** [comment]
What's the value of your `esModuleInterop`?

**Comment by kdy1** [comment]
See https://github.com/swc-project/swc/pull/1861/files#diff-34d4a92de229dfc7281690f95739fa06654ca251be80bea556f327815c899336R33

If your config is valid, `default` exports will be filtered by this line.

**Comment by pincman** [comment]
@kdy1 
my tsconfig.json
```json
{
    "compilerOptions": {
        "strict": true,
        "target": "ES2017",
        "module": "commonjs",
        "moduleResolution": "node",
        "declaration": true,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "alwaysStrict": true,
        "preserveSymlinks": true,
        "sourceMap": true,
        "incremental": true,
        "forceConsistentCasingInFileNames": true,
        "isolatedModules": true,
        "esModuleInterop": true,
        "noUnusedLocals": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "allowSyntheticDefaultImports": true,
        "pretty": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "noImplicitAny": true,
        "allowJs": true,
        "importsNotUsedAsValues": "remove",
        "lib": ["ESNext", "ScriptHost", "WebWorker"],
        "outDir": "./dist",
        "baseUrl": "./",
        "paths": {
            "@/*": ["src/*"]
        }
    },
    "include": [
        "src/**/*.ts",
        "test/**/*.ts",
        "typings/**/*.d.ts",
        "scripts",
        "examples",
        "**.js"
    ]
}
```
so ,`esModuleInterop` is `true`
and `.swcrc`
```json
{
    "sourceMaps": false,
    "jsc": {
        "loose": true,
        "parser": {
            "syntax": "typescript",
            "decorators": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "target": "es2020",
        "externalHelpers": false
    },
    "module": {
        "type": "commonjs",
        "strict": true,
        "noInterop": true
    }
}
```
so `noInterop` is `true`

and `scripts/bin.js`
```javascript
#!/usr/bin/env node
// eslint-disable-next-line import/no-extraneous-dependencies
const { execSync } = require('child_process');

const path = require('path');

const runner = path.resolve(__dirname, 'runner.ts');

execSync(`node -r '@swc/register' -r 'module-alias/register' ${runner}`, {
    stdio: 'inherit',
});
```
`runner.ts`
```typescript
import merge from 'deepmerge';

console.log(merge({ x: 1 }, { y: 2 }));
```
when I run `node ./scripts/bin.js`
have an error
```
console.log((0, _deepmerge).default({
                                   ^

TypeError: (0 , _deepmerge).default is not a function
```

**Comment by kdy1** [comment]
Ah, I see. Then the `.swcrc` you posted was wrong.
I'm not sure what does babel do.
I worked on a similar issue, but I don't remember it.

But if I remember correctly, the config was simply wrong.
In this case,  you use `esModuleInterop: true` for `tsc` and `noInterop: true` for swc.
You should use `false` for it

**Comment by pincman** [comment]
@kdy1
even if `noInterop` is set to `false`, the problem still exists
```
console.log((0, _deepmerge).default({
                                   ^

TypeError: (0 , _deepmerge).default is not a function
```

but `ts-node`and `tsc` work fine,I can't find the reason for it

**Comment by pincman** [comment]
but for when `"esModuleInterop": false` and `"noInterop": false`,back to the question at the beginning,
when 
``` typescript
import * as config from './config';
console.log(config)
```
will get
```
{
  app: [Getter],
  database: [Getter],
  default: { app: [Getter], database: [Getter] }
}
```
I don't want to auto generate `default` export ,I think it should just like `tsc` or `ts-node` when `esModuleInterop: true` in `tsconfig.json`,that will
if `import merge from 'deepmerge'`,work fine and `import * as config from './config';` not has `default export`

**Comment by kdy1** [comment]
This is how the module transpiled when `noInterop: true`.


https://github.com/swc-project/swc/blob/33f2ab2d795ee8fbe935f535cf5568a252af1fcc/ecmascript/transforms/module/tests/common_js.rs#L1155-L1179

First, swc does not generate `default` for namespaced imports.

https://github.com/swc-project/swc/blob/33f2ab2d795ee8fbe935f535cf5568a252af1fcc/ecmascript/transforms/module/tests/common_js.rs#L3973-L3998

Second, swc **excludes** default export from `export *` correctly.

If you think this is wrong, please post expected code. Installing tools and creating an env just to reproduce a bug consumes too much time.

**Comment by pincman** [comment]
A simple answer is filter default ^v^
```typescript
const customConfigs = Object.fromEntries(
            Object.entries(_config)
                .filter(([name]) => name !== 'default')
                .map(([name, value]) => {
                    return [name, value()];
                }),
        );
```

**Comment by ShivamJoker** [comment]
@kdy1 any updates on this ?
I am still facing the issue in index.ts file where 
```js
[nodemon] starting `node dist/index.js`
user routes [ { method: 'POST', url: '/signup', handler: [Function: handler] } ]
{
  default: [ { method: 'POST', url: '/signup', handler: [Function: handler] } ]
}
/Users/shivam/Documents/web/onlineworks/Portal-API/dist/index.js:11
_routes.default.forEach((route)=>server.route(route)
                ^

TypeError: _routes.default.forEach is not a function
    at Object.<anonymous> (/Users/shivam/Documents/web/onlineworks/Portal-API/dist/index.js:11:17)
```
