### ISSUE TITLE
How can I deal with `visitTsType not implemented`

### ISSUE THREAD

**Issue by SoloJiang** [swc-project/swc#1863]
![image](https://user-images.githubusercontent.com/14757289/123538587-4b032500-d768-11eb-84ed-16322f1a2e26.png)

**Comment by SoloJiang** [comment]
However, which situations we will use `visitTsTypeElmements`

**Comment by kdy1** [comment]
Currently, plugin API is very limited and I want to remove it in v2.

Maybe using `transofrm` to stripe typescript types can be a workaround for now, but I'm not sure about it.

**Comment by SoloJiang** [comment]
I see v2 plan in another issue, when it ready to deploy?

During I migrate our project from babel to swc, I really find the plugin API is very limited and not as good as the Babel. Such as:
- Presets
- some options, like `stat` which includes `filename`, or `params` pass to plugins
- @babel/types for swc
- `nodePath` etc..

Above most all of this, I write [a new loader for webpack](https://github.com/alibaba/ice/blob/007237fcf84394224df7a41e7880764567f69193/packages/swc-loader/src/index.ts) to handle, but I think it should be handled by swc self.

Where I can see the more detail plan for plugin API in v2? I am so interested about it~

**Comment by SoloJiang** [comment]
I look wrong your reply....Will you remove plugin API in v2 ? 

emmmm.... For FE developers plugin is very important and the most important reason we choose swc not esbuild is the plugin system..

**Comment by kdy1** [comment]
With v2, swc will support using babel plugins without modification.
I'm still working on it.

**Comment by SoloJiang** [comment]
Okay~

**Comment by SoloJiang** [comment]
Now, I transform ts file by swc in first step, and then add plugins to swc options to transform the result again.
