### ISSUE TITLE
Generate appropriate Typescript typings for Options

### ISSUE THREAD

**Issue by 9oelM** [swc-project/swc#1870]
**Describe the feature**
Right now `@swc/wasm-web` is published, but some of the typescript definitions have `any`. Most notably:

```ts
/**
* @param {string} s
* @param {any} opts
* @returns {any}
*/
export function parseSync(s: string, opts: any): any;
/**
* @param {any} s
* @param {any} opts
* @returns {any}
*/
export function printSync(s: any, opts: any): any;
/**
* @param {string} s
* @param {any} opts
* @returns {any}
*/
export function transformSync(s: string, opts: any): any;
```

`parseSync`, `printSync`, and `transformSync` have `opts` as `any`, so it significantly degrades developer experience.

Therefore the type definitions should be ported; For example, the type definition of `opts` in `transform_sync` could be properly ported from 

https://github.com/swc-project/swc/blob/4cd43375a5367cd4cff87f391b183bfc0f1c7528/src/config.rs#L62

**Comment by 9oelM** [comment]
@kdy1 do you think porting existing types from 

https://github.com/swc-project/swc/blob/33a43f85b18191ed2a68d04a1c2e39aa623e6b66/node-swc/src/types.ts#L6-L179

into `wasm/src/lib.rs` using https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/typescript_type.html would be the the best way to do it?

**Comment by kdy1** [comment]
Oh, I didn't know about the option of `wasm-bindgen`.
I think creating another package like `@swc/types` or `@swc/shared` would be better.

As I'm planning publising more crates under `@swc` namespace, I prefer `@swc/shared`.

e.g. Minifier will be published as `@swc/minifier`

**Comment by 9oelM** [comment]
Okay. Publishing a `@swc/types` package would mean that we will need to import the types from there into `@swc/wasm-web`'s typings, right? If that's the case, another thing to worry about is that `wasm-bindgen` does not support importing external typescript definitions for build as per https://github.com/rustwasm/wasm-bindgen/issues/1341. There is one commercial software called https://github.com/taggartsoftware/ts2rs (mentioned in the same issue) but I don't think it's usable.

Because of this reason, I think there are two plausible ways: 
1. to have generate all types inside `@swc/wasm-web` by using  https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/typescript_type.html
2. to manually create `wasm.d.ts` completely separately and only using wasm-bindgen to produce `.js` and `.wasm` files

Do you have any other opinions?

**Comment by kdy1** [comment]
> Okay. Publishing a @swc/types package would mean that we will need to import the types from there into @swc/wasm-web's typings, right? 

Yes. I didn't aware of such bug.


How about using a build script which reads typescript files and exports them with a format specified in `#[wasm_bindgen(typescript_custom_section)]`?

**Comment by 9oelM** [comment]
Yeah i think that makes sense. Let's do it that way

**Comment by DreamTexX** [comment]
How's status on the typings? It's really annoying, or is there any workaround currently?

**Comment by kdy1** [comment]
It can be implemented, but it's too much work.

**Comment by kwonoj** [comment]
I believe I completed this via https://github.com/swc-project/swc/blob/main/bindings/binding_core_wasm/src/types.rs.
