### ISSUE TITLE
cargo run failed

### ISSUE THREAD

**Issue by maedaKaori** [swc-project/swc#188]
after `cargo build`, cargo run failed

error: a bin target must be available for `cargo run`

**Comment by kdy1** [comment]
This repository only contains libswc, and you should run `npm i swc swc-cli` to get command line access.

**Comment by maedaKaori** [comment]
@kdy1 I want to Debug swc

**Comment by kdy1** [comment]
@maedaKaori Then you can run `cargo test --all` instead.

FYI,
`swc_ecma_ast`: ecmascript / typescript ast
`swc_ecma_codegen`: ecmascript code generator
`swc_ecma_parser`: javascript / jsx / typescript parser
`swc_ecma_transforms`: Transcompiler
