### ISSUE TITLE
Chained optional chaining transpilation leaves partial chain

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#1882]
**Describe the bug**
When there is chain of optional chain, some of chain left as-is without transpilation.

**Input code**

```
const button = renderedView.find(LoadingButton);
button?.prop('onClick')?.({} as any);
```

output

```
var ref;
const button = renderedView.find(LoadingButton);
var _obj = button?.prop('onClick');
(ref = _obj) === null || ref === void 0 ? void 0 : ref.call(_obj, {
});
```

raises runtime exception

```
var _obj = button?.prop('onClick');
                              ^

    SyntaxError: Unexpected token '.'

```

**Config**

```json
{
  "jsc": {
    "target": "es2018",
    "parser": {
      "syntax": "typescript",
      "decorators": false,
      "dynamicImport": true
    }
  }
}
```

**Expected behavior**

**Version**
The version of @swc/core:  @swc/core@1.2.62

**Additional context**

**Comment by kwonoj** [comment]
@kdy1 I'm curious if I can attempt to contribute and if so if you could share some pointers to work on. So far I understand this seems happening around this area https://github.com/swc-project/swc/blob/04d43844821bfea4de40f14e58a10e6f7a42f147/ecmascript/transforms/compat/src/es2020/opt_chaining.rs#L421 but I couldn't think of possibly feasible approach to solve this one since I'm not very much familiar with existing codebase.

**Comment by kdy1** [comment]
This issue seems to be caused by children nodes not visited.
If it's the case, proper `expr.fold_children_with(self)` may fix the issue.
