### ISSUE TITLE
Destructuring Declaration error

### ISSUE THREAD

**Issue by EedoCelsius** [swc-project/swc#1887]
**Input code**

```diff
const obj = {}
const [obj.a, obj.b, obj.c] = [1, 2, 3]
```

**Describe the bug**

Spits out this 'failed to parse module' error.
```diff
Unexpected token `.`. Expected yield, an identifier, [ or {
```

**Version**
The version of @swc/core: 1.2.62

**Comment by Austaras** [comment]
This is not valid js, and babel will throw parser error too, it should be written as
```js
const obj = {};
[obj.a, obj.b, obj.c] = [1, 2, 3]
```
