### ISSUE TITLE
visitArrayElement/visitOptionalExpression Error

### ISSUE THREAD

**Issue by EedoCelsius** [swc-project/swc#1888]
**Comment 확인부탁드립니다!**

Current Visitor.js is:

    visitArrayElement(e) {
        if (e && e.type === "SpreadElement") {
            return this.visitSpreadElement(e);
        }
        return this.visitOptionalExpression(e);
    }

When it should be:

    visitArrayElement(e) {
        if (e && e.type === "SpreadElement") {
            return this.visitSpreadElement(e);
        }
        if (e.expression) {
            e.expression = this.visitOptionalExpression(e.expression);
        }
        return e
    }

**OR**

Current Visitor.js is:

    visitOptionalExpression(e) {
        if (e) {
            return this.visitExpression(e);
        }
    }

When it should be:

    visitOptionalExpression(e) {
        if (e.expression) {
            e.expression = this.visitExpression(e.expression);
        }
        return e
    }

Because:

Current Visitor class returns:
```diff
a = [
    ,
    ,
];
```
When it should be:
```diff
a = [
    a,
    b,
    c
];
```

**Version**
The version of @swc/core: 1.2.62

**Comment by EedoCelsius** [comment]
메인 개발자분이 한국분인것 같아 한국어로 댓글답니다! 
visitArrayElement 또는 visitOptionalExpression 에 오류가 있어 맨 아래의 예제와 같이 array가 빈 상태로 반환됩니다.

어제 제가 이슈한 'props => properties' 버그도 그렇고 Visitor 클래스에 문제가 조금 많은것 같은데,
개발자님이 보셨을 때 SWC로 커스텀 플러그인을 만들기에는 아직 시기상조의 단계인지 궁금합니다.

사용자로부터 받은 스크립트에서 보안적 이슈들을 제거하고 서버에서 실행시켜주는 서비스에 느린 바벨 대신 사용하려는데,
아직은 불안정한 단계인가 싶어 조금 걱정이 되어 문의드립니다. 특히 보안이랑 관련된 사항이다보니 ㅜㅜ

답답한 바벨을 대체할 수 있는 빠른 트랜스 스크립터 개발에 힘써주시는 강동윤님께 정말 감사의 말씀드립니다!!

**Comment by kdy1** [comment]
Core transforms are stabilized but the plugin system is not powerful enough.
Also, it's not well-tested, and I don't think improving my own plugin system worths it because I'm working on support for babel plugins. (It's almost done.)

With v2, swc will drop support of current plugin APIs and the only plugin API will be one of babel.

**Comment by EedoCelsius** [comment]
> Core transforms are stabilized but the plugin system is not powerful enough.
> Also, it's not well-tested, and I don't think improving my own plugin system worths it because I'm working on support for babel plugins. (It's almost done.)
> 
> With v2, swc will drop support of current plugin APIs and the only plugin API will be one of babel.

**Comment by EedoCelsius** [comment]
Oh my, that really is a great news.
So I am guessing the speed of transcriptors are mostly determined by parsing AST and restructuring part?

I'll be waiting for v2 then :), is it possible for you to give me an idea of when the v2 will be released?

**Comment by kdy1** [comment]
> So I am guessing the speed of transcriptors are mostly determined by parsing AST and restructuring part?

I expect babel plugins to be a bottleneck. Even if I call them from the background thread, all javascript code run within a thread. Although parsing is one of the slow parts, the task would be offloaded to a background thread.


> is it possible for you to give me an idea of when the v2 will be released?

I'm sorry but I'm not sure about this at the moment. Estimating time is too hard.

**Comment by SoloJiang** [comment]
However, I think this bug should be solved in v1. @EedoCelsius  will you contribute a PR for it?

**Comment by kdy1** [comment]
I found that babel plugin compatibility would be much harder than I expected.
I'm also considering rust plugin api.

https://github.com/swc-project/swc/issues/1392#issuecomment-873521336

**Comment by kdy1** [comment]
I'll fix the plugin api for now, as babel plugin compat requires more investigation.

**Comment by mikob** [comment]
Seems related: https://github.com/swc-project/swc/issues/1623
