### ISSUE TITLE
SWC has a tick too much in transpiled `for await` resulting in different output after transpiling

### ISSUE THREAD

**Issue by danieltroger** [swc-project/swc#1918]
**Describe the bug**

This exact bug: https://github.com/babel/babel/issues/13490 but for SWC.

See this, output after transpiling and before transpiling should be the same:

```
daniel@Daniels-MacBook-Pro swc-for-await % node dist/ie11.js 
0
daniel@Daniels-MacBook-Pro swc-for-await % node src/main.ts 
0
1
```

**Input code**

```
let resolve;
let promise = new Promise((r) => (resolve = r));
let iterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        return promise;
      },
    };
  },
};

(async () => {
  for await (let value of iterable) {
    console.log(value);
  }
})();

(async function () {
  resolve({ value: 0, done: false });
  promise = new Promise((r) => (resolve = r));

  await null;
  resolve({ value: 1, done: false });
  promise = new Promise((r) => (resolve = r));

  resolve({ value: undefined, done: true });
})();
```

**Config**

```json
{
  "env": {
    "shippedProposals": true
  }
}

```

**Expected behavior**
Expected behavior is for the code above to output

```
0
1
```
like it does untranspiled.

**Version**
```
@swc/cli: 0.1.46
@swc/core: 1.2.63
```

**Additional context**
I use SWC with parcel

Simple reproduction repository with SWC (kudos to @mischnic):
[swc-for-await-repro.zip](https://github.com/swc-project/swc/files/6815730/swc-for-await-repro.zip)

Reproduction with parcel using SWC:
[swc-for-await.zip](https://github.com/swc-project/swc/files/6815733/swc-for-await.zip)

**Comment by kdy1** [comment]
I was aware of such bug as you mentioned in the babel issue, but I prefer waiting for the babel team because I want to align the helper scripts.

**Comment by danieltroger** [comment]
@kdy1 could you please review this pull request then for them? https://github.com/babel/babel/pull/13491 they're just waiting for a review so they can merge

**Comment by kdy1** [comment]
I'm not a babel expert, so I expect my review to be helpless.
(I barely looked at the babel source code while building swc)

**Comment by danieltroger** [comment]
You know how async transpilation works and I therefore think you're one of the few people that even understand what the changes are. I think they're not merging because there's like one more person on the planet that knows what it's about and they're on vacation.

**Comment by kdy1** [comment]
But I don't want to do it.
It does not seem to be an interesting task.

**Comment by danieltroger** [comment]
I see, that's fair

**Comment by sachinraja** [comment]
Update: that PR has now been merged
