### ISSUE TITLE
use generator in code does not inject _interopRequireDefault implement into output

### ISSUE THREAD

**Issue by IronLu233** [swc-project/swc#1924]
**Describe the bug**
compile code using generator without any other import will  generate a broken code without `_interopRequireDefault`
**Input code**

export default function * foo() {}
**Config**

```json
{
  "module": {
    "type": "commonjs"
  },
  "jsc": {
  }
}
```

**Expected behavior**
generated code should include _interopRequireDefault implements.

**Version**
The version of @swc/core: 1.2.64

**Additional context**
generated code
``` js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = foo;
var _regeneratorRuntime = _interopRequireDefault(require("regenerator-runtime"));
function foo() {
    return _regeneratorRuntime.default.wrap(function foo$(_ctx) {
        while(1)switch(_ctx.prev = _ctx.next){
            case 0:
            case "end":
                return _ctx.stop();
        }
    }, foo);
}

```

**Comment by chyzwar** [comment]
can this fix be released ?, it hard to force resolution of previous version.

**Comment by kdy1** [comment]
I'll publish a new version.
