### ISSUE TITLE
`paths` in swcrc should not add file extensions to the import

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#1934]

**Comment by kfirba** [comment]
This also happens without the `swcrc` file, but with manually invoking the `transformFile` method

**Comment by JanJakes** [comment]
Is there any estimate or a priority set for the path-alias related issues? I wanted to give it a try but https://github.com/swc-project/swc/issues/1934 and https://github.com/swc-project/swc/issues/1943 seem to prevent the feature from working for us. (Not sure if https://github.com/swc-project/swc/issues/1935 is as important as well.)

**Comment by kdy1** [comment]
I'll fix it with next release.
I think about this and as fix is dead simple, I decided to just fix this.

**Comment by JanJakes** [comment]
Oh, wow, that was quick! 👏 Thanks a lot!
