### ISSUE TITLE
typescript paths alias

### ISSUE THREAD

**Issue by YannBCF** [swc-project/swc#1935]
**Describe the bug**

I try to get the typescript path aliases to work since it should be working right now on the ``1.2.65`` swc core version, am i doing something wrong ?
```
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@api" is not a valid package name imported from C:\Users\x\test\hello.js
    at packageResolve (internal/modules/esm/resolve.js:601:11)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

**Input code**

api.ts
```typescript
export const api = 0;
```

hello.ts
```typescript
import { api } from '@api';
console.log('api', api);
```

**Tsconfig**
```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@api": ["src/api"]
        }
    }
}
```

**Config**

```json
{
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "dynamicImport": true
      },
      "target": "es2016",
      "paths": {
        "@api": ["src/api"]
      }
    },
    "minify": false
}
```

**Expected behavior**
It should replace the alias with a relative path

**Version**
1.2.65

**Comment by kwonoj** [comment]
tsc, or babel (unless separate plugin specified) both doesn't transpile alias to runtime resolvable path and each tool like webpack / jest specifies way to resolve, may swc would leave as-is as well? for some cases, I expect `jsc.paths` being used as resolve time only - it's not unusal runtime points to different based on tooling such as jest test points to stub mock instead of real module for path aliases.

**Comment by wi-ski** [comment]
Please please please - how do we fix this <3

**Comment by EarthlingDavey** [comment]
I found that I had to use a .swcrc file with no paths during the build. BTW the --config-file flag didn't work for me.
Then, something like this in package.json

```
...
"type": "module",
...
"build": "swc src  -d dist",
"start": "node --experimental-specifier-resolution=node dist/index.js",
...
"imports": {
    "#lib/*": "./dist/lib/*"
}
```
