### ISSUE TITLE
panic: `with` statement can't be compiled

### ISSUE THREAD

**Issue by troy351** [swc-project/swc#1944]
```js
function withStatement(){
   const a = { b: 1 }
   with (a) {
      console.log(b)
   }
}
```
Screenshot from repl
![image](https://user-images.githubusercontent.com/8372385/126436628-18465368-2fa4-47c6-9490-4d700279d80a.png)

**Comment by kdy1** [comment]
It's not a bug. Module code runs in strict mode.

**Comment by troy351** [comment]
Is there a way to disable module?
babel can do this by `sourceType: 'script'`

**Comment by troy351** [comment]
Found it `isModule: false`.
It's in issues and changlog, not in docs
