### ISSUE TITLE
Support shims for built in modules

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#1955]
**Describe the bug**

Compiling built in modules when the target is the browser and `paths` are configured does not use the packages from `paths` but compiles down to `import` statements. Possibly a duplicate of #1943.

**Input code**

An MVP reproducing and describing the issue is here:

https://github.com/tmpfs/swc-builtin-shim 

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "paths": {
      "assert": ["node_modules/assert"],
      "events": ["node_modules/events"]
    },
    "transform": null,
    "target": "es2016",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false
  }
}
```

**Expected behavior**

We expect the packages configured in `paths` to be used instead of the default behavior for handling builtin modules.

**Version**
The version of @swc/core: 1.2.66

**Additional context**

N/A

**Comment by kumavis** [comment]
specifically we're looking for a way for spack to map "node core modules" (`events`, `assert`) to shims published on npm
