### ISSUE TITLE
Support browser field of package.json

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#1956]
**Describe the feature**

Support the `browser` field of `package.json` ([docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#browser)) to determine an entry point that overrides `main` when the target is a browser environment. This field is supported by Webpack and other bundlers and would be helpful for users migrating to spack/swc.

It would enable support for isomorphic packages such as [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/package.json#L5).

**Additional context**

This should be enabled by default (the assumption is that the browser is the most common target) but an option needs to be provided to disable use of  the `browser` field for other targets such as server-side code. This could be achieved with a new configuration parameter in `.swcrc` which could be set on the command line when invoking `spack` to override the configuration.

Note I have assumed this is not yet supported as the `PackageJson` struct in `NodeResolver` does not declare the field.

**Reference**

* [Webpack aliasFields](https://webpack.js.org/configuration/resolve/#resolvealiasfields)
* [Browser field spec](https://github.com/defunctzombie/package-browser-field-spec)

**Comment by kdy1** [comment]
Is this a bug about the bundler?

**Comment by tmpfs** [comment]
I don't think it's a bug so I created a feature request as I figured you just haven't had time to implement this yet. Happy to help out to get this landed of course :+1: 

It is worth being aware that handling package entry points correctly from `package.json` configuration is a bit of a can of worms. So in addition to `browser` there is also the `module` field when the `type` is set to `module` and then there is the more recent `exports` ([docs](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_package_entry_points)) which is specific to nodejs and supports different entry points for ESM (`import`) and CommonJS (`require`) - implementing this may involve passing a context to `NodeResolver` indicating whether to prefer ESM or CommonJS entry points.

Neither of these are part of the official `package.json` specification (unlike `browser`) but many bundlers support them and I think the goal for spack/swc should be compatibility so migrating from other bundlers is easy.

**Comment by kdy1** [comment]
I mean is this feature request about the bundler of the resolver.

**Comment by tmpfs** [comment]
It is related to the bundler as it is about resolving package entry points but I think the main part of the implementation would go in `NodeResolver` as that is where `package.json` is read and the main entry point is determined: https://github.com/swc-project/swc/blob/master/ecmascript/loader/src/resolvers/node.rs#L150.

But because reading the `browser` entry point is only specific to a particular target environment the implementation is also concerned with configuration (`.swcrc`) and command line options IMO.

**Comment by tmpfs** [comment]
Closing as fixed by #2045 .
