### ISSUE TITLE
common js imports are wrong when strict option is given

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#198]
ECMAScript® 2018 Language Specification

[ecma-262/#sec-imports](https://www.ecma-international.org/ecma-262/#sec-imports)
[ecma-262/#sec-exports](https://www.ecma-international.org/ecma-262/#sec-exports)

Example Code:

```javascript
// foo.js
const NUM = 1;
export default NUM;

// bar.js
import Foo from './foo.js';
// `Foo` should be eq `1`. not an object ( `{ 'default': 1}` )
console.log(Foo);
```

**Comment by kdy1** [comment]
If you use module transform (any of common js / amd / umd), it works correctly.
Emitted code:


`foo.js`:
```js
'use strict';
Object.defineProperty(exports, '__esModule', {
    value: true
});
exports.default = void 0;
var NUM = 1;
var _default = NUM;
exports.default = _default;

//# sourceMappingURL=foo.js.map
``` 


`bar.js`:
```js
'use strict';
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
var _fooJs = _interopRequireDefault(require('./foo.js'));
console.log(_fooJs.default);

//# sourceMappingURL=bar.js.map
```

https://github.com/kdy1/swc-example/tree/a1ca6c8c2e32d4e57c3e5866c7760c59ae4e6d7c/inputs/issue-198


If you think such interop based on `__esModule` is incorrect, please tell me how it should work.

**Comment by LuoZijun** [comment]
`src/foo.js`:

```javascript
function Foo(){
    return "function Foo";
}
export default Foo;
```

`src/bar.js`:

```javascript
function Bar(){
    return "function Bar";
}
export { Bar, };
```

`src/index.js`:

```javascript
import Foo from './foo.js'
import {Bar, } from './bar.js'
import Bar2 from './bar.js'

console.log(Foo);
console.log(Bar);
console.log(Bar2);
```

Build:
```bash
swc src/index.js -d build
swc src/foo.js -d build
swc src/bar.js -d build
```

Run:

```bash
node build/index.js
```

Output:

```
{ default: [Function: Foo] }
undefined
{ Bar: [Function: Bar] }
```

But, i belive the output should be:

```
[Function: Foo]
[Function: Bar]
{ Bar: [Function: Bar] }
```

**Comment by LuoZijun** [comment]
@kdy1

**Comment by kdy1** [comment]
@LuoZijun I'll look at it.

**Comment by kdy1** [comment]
You need a `.swcrc` file like

```json
{
    "module": {
        "type": "commonjs"
    }
}
```

I got
```
[Function: Foo]
[Function: Bar]
undefined
```

with such `.swcrc`

It's undefined because `import Bar2 from './bar.js';` is not a namespace import.

If you want third one to be `{ Bar: [Function: Bar] }`, you can import like `import * as Bar2 from './bar.js';`

**Comment by LuoZijun** [comment]
@kdy1 

My `.swcrc` file is like this:

```
{
    "module": {
        "type": "commonjs",
        "strict": true,
        "strictMode": true,
        "lazy": false,
        "noInterop": false
    }
}

```

If change to this, the output look is right.
```
{
    "module": {
        "type": "commonjs",
        "strict": false,        // Key config
        "strictMode": true,
        "lazy": false,
        "noInterop": false
    }
}
```

The last, you are right, the `import Bar2 from './bar.js'` is not right, it should be `import * as Bar2 from './bar.js'`.

**Comment by kdy1** [comment]
Note that this behavior is equivalent to babel.


https://github.com/kdy1/swc-example/tree/82468a2ef07ac8877f5b5081466bb4c0e3a0f4c5/inputs/issue-198

```sh
$ npx swc inputs/**/*.js -d out && node ./out/index.js && npx babel inputs/**/*.js -d out-babel && node ./out-babel/index.js 
Successfully compiled 12 files with swc.
{ default: [Function: Foo] }
[Function: Bar]
{ Bar: [Function: Bar], default: { Bar: [Function: Bar] } }
Successfully compiled 12 files with Babel.
{ default: [Function: Foo] }
[Function: Bar]
{ Bar: [Function: Bar], default: { Bar: [Function: Bar] } }

```

**Comment by LuoZijun** [comment]
@kdy1 

I want to know what is`strict` option ? is this option is just one babel option ? or defined on Language Specification ?

i think we should follow and respect the ECMAScript spec, not babel. 

as i know, babel can handle many syntax ( ECMAScript not defined them), like:

*   currying function
*   proposal-class-properties ( plugin )
*   ...

Example Code:
```javascript
// currying function
const sum = a => b => a + b;
// Eq
function sum(a, b) {
    return a + b;
}

// proposal-class-properties ( plugin )
class A {
    state = {}
}
// Eq
class A {
    constructor(){
        this.state = {};
    }
}
```

**Comment by kdy1** [comment]
It's just a babel's option. It removes `__esModule`.
I agree with you that we should follow ecmascript spec. (That's why I reopened this issue)

**Comment by kdy1** [comment]
@LuoZijun You can specify `noInterop: true` like 

```json
{
    "module": {
        "type": "commonjs",
        "strict": true,
        "noInterop": true
    }
}
```

to make default import correct. Is this problematic?

**Comment by LuoZijun** [comment]
@kdy1 

It work with my case.

But panic with `React`.

```javascript
import React from 'react'
import ReactDOM from 'react-dom'


class HomePage extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            data: []
        }
    }
    render() {
        return (
            React.createElement("h1", null, "Hi, 世界！")
        )
    }
}

```

Output:

```
}(_react.default.Component);
                 ^

TypeError: Cannot read property 'Component' of undefined
```

**Comment by kdy1** [comment]
Oh.. Current behavior is definitely wrong.. Although I'm not sure how can I fix it.

**Comment by kdy1** [comment]
React does not export anything as default, so I think you should import like `import * as React from 'react';`

**Comment by LuoZijun** [comment]
@kdy1 

Yeah, i have check that, and i have do the test. i will close this issue. thank you.

-_-

**Comment by Noramire** [comment]
Surprisingly this bug still exists in newer versions. When you set "strict" as true, independently of "noInterop" value, it will cause an error. For example, Express DOES have a default export.

`(0 , _express).default is not a function`
