### ISSUE TITLE
Clearer information regarding what is supported input/output

### ISSUE THREAD

**Issue by jpike88** [swc-project/swc#1981]
Looking at this project there two things still aren't clear to me:

- Up to what version of TypeScript code is accepted
- what versions of JS can be output

Can these be on the readme.md? The biggest decision adopters need to make is compatibility and change management, this will help.

**Comment by kdy1** [comment]
All version of typecript code is supported. Typically swc is patched when the typescript team writes a post about the release candidate.
Output is also every es version, starting from es3.
