### ISSUE TITLE
panic: thread 'main' panicked at 'position 31 does not resolve to a source location'

### ISSUE THREAD

**Issue by yisar** [swc-project/swc#1994]
```rs
    pub fn print(module: Module) -> String {
        let sm: Lrc<SourceMap> = Lrc::new(SourceMap::default());
        let mut buf = vec![];
        let mut sm_buf = vec![];
        {
            let writer = Box::new(JsWriter::new(sm.clone(), "\n", &mut buf, Some(&mut sm_buf)));
            let config = Config { minify: false };
            let mut emitter = Emitter {
                cfg: config,
                comments: None,
                cm: sm.clone(),
                wr: writer,
            };

            emitter.emit_module(&module).unwrap();
        }
        return String::from_utf8(buf).unwrap();
    }
```
I don't know what I did wrong. I'm going to cry...Can I disable sourcemap?

**Comment by kdy1** [comment]
You can pass `None`.

**Comment by yisar** [comment]
> You can pass `None`.

The type does not allow me to pass None, can you write a sample code?

Thank you.

**Comment by kdy1** [comment]
Do you mean `swc_common::SourceMap`? No you can't.

**Comment by yisar** [comment]
> Do you mean `swc_common::SourceMap`? No you can't.

What should I do?   I don’t know why this error is triggered, tomorrow I can provide a demo with minimal recurrence.

**Comment by kdy1** [comment]
I think you are trying to generate code from ast, correct?
Currently, the code generator does not care about AST nodes created manually, without using `swc_common`.

**Comment by yisar** [comment]
> I think you are trying to generate code from ast, correct?
> Currently, the code generator does not care about AST nodes created manually, without using `swc_common`.

If I generate code from ast, do I need to implement the generator myself? I don’t want this.

**Comment by kdy1** [comment]
Where does `position 31 ` come from?

Modifying AST should be ok if the AST is parsed using `swc_ecma_parser`, as it requires `swc_common::SourceMap`.

Alternatively, you can drop span of all nodes to prevent it from panicking. (See https://docs.rs/swc_ecma_utils/0.41.0/swc_ecma_utils/fn.drop_span.html)

**Comment by yisar** [comment]
> Where does `position 31 ` come from?
> 
> Modifying AST should be ok if the AST is parsed using `swc_ecma_parser`, as it requires `swc_common::SourceMap`.
> 
> Alternatively, you can drop span of all nodes to prevent it from panicking. (See https://docs.rs/swc_ecma_utils/0.41.0/swc_ecma_utils/fn.drop_span.html)

Yes, yes, this is how I did it, and I will give you a minimally reproducible use case tomorrow.  I use it to parse jsx, simple grammar can pass, complex grammar will report errors.

**Comment by kdy1** [comment]
Oh.. Okay, I think it's not debuggable without code.

**Comment by yisar** [comment]
@kdy1 Hi, I am coming back.
https://github.com/yisar/swc_sourcemap_bug

I wrote a demo of the  minimal recurrence, please check it.
I think maybe there is something wrong with my code. If so, you can directly PR modify my code. I will be very grateful.

**Comment by kdy1** [comment]
You should use same `swc_common::SourceMap` for parsing and printing and it will work.
