### ISSUE TITLE
minifier: odd auto-definition in 1.2.74

### ISSUE THREAD

**Issue by kapouer** [swc-project/swc#2011]
This one is harder to isolate for now.

The result i get is:

```
var Ua
S.exports = (_defineProperty(Ua = (_createClass(Ua, [{
				key: "init",
```
> Uncaught TypeError: Cannot read property 'prototype' of undefined
>    at _createClass (site.min.js:2)

I attach the source (bundled by another tool). It's messy...
Likely comes from that part:
```
module.exports = class BlockView {
```
however i tried to isolate it and couldn't reproduce.

[bundle.js.gz](https://github.com/swc-project/swc/files/6931274/bundle.js.gz)

**Comment by kdy1** [comment]
Did you use `transform`? What was your `.swcrc`?
`_createClass ` is injected by swc or babel, so I couldn't reproduce it.

**Comment by kapouer** [comment]
```
{
	"sourceMaps": false,
	"jsc": {
		"loose": true,
		"parser": {
			"syntax": "ecmascript",
			"classPrivateProperty": true
		},
		"target": "es3",
		"minify": {
			"compress": true,
			"mangle": true
		}
	},
	"minify": true
}
```
i'll check with 1.2.76 if this happens again, and close or report further info accordingly.

**Comment by kapouer** [comment]
Nailed it !
Using swc 1.2.76

```
class ClassA {}

module.exports = class ClassB {
	static MyA = ClassA;

  it() {
    this.bb = new ClassB.MyA();
  }
}
```

and .swcrc as the one above.

**Comment by kdy1** [comment]
Thank you a lot! Reducing a test case is the most hard part :)
