### ISSUE TITLE
minify: problem with returnasync

### ISSUE THREAD

**Issue by haydnhkim** [swc-project/swc#2020]
**Describe the bug**
Due to incorrect minify, return and async are appended to the output. (`returnasync`)
For the issue to be reproduced, all of the following complex conditions must be met:

- It must be a currying function
- returning function must be async
- returning function must have two or more arguments.
- Use optional chaining inside the returning function

**Input code**
```js
const createRegisterItems = registerType => async (a, b) => {
  const a = root?.test;
};
```

**Output code**
```js
"use strict";const createRegisterItems=registerType=>{returnasync(a,b,c)=>{console.log(1);const a=root===null||root===void 0?void 0:root.test}}
```

**Config**

```json
{
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es2018"
  },
  "minify": true
}
```

**Expected behavior**
There must have a space between return and async.

**Version**
The version of @swc/core: 1.2.74

**Comment by acdibble** [comment]
The issue is much simpler to reproduce:

```javascript
// input:
const test = () => {
  return async () => {};
};

// output:
const test=()=>{returnasync()=>{}}
```

Work around:
```javascript
// input:
const test = () => {
  const cb = async () => {};
  return cb;
};

// output:
const test=()=>{const cb=async()=>{};return cb}
```

config:
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es2018"
  },
  "minify": false
}
```
