### ISSUE TITLE
Allow to disable "import/export" conversion

### ISSUE THREAD

**Issue by onigoetz** [swc-project/swc#2030]
**Describe the feature**

When transpiling es6+ code using swc, everything is transpiled, including import/export.
This is cool and what we would expect when we transpile code.

However webpack loaders and rollup plugin expect the transpiled code to still have import/export.

That's why for example babel has both options : `targets` and `modules`, setting modules to false keeps import/export.

**Babel plugin or link to the feature description**

https://babeljs.io/docs/en/babel-preset-env#modules

**Additional context**

This works fine today in webpack as it's able to parse commonjs, but treeshaking is disabled (at least in webpack 4, not sure 100% about webpack 5)
It's possible to make it work in rollup, but needs duplicating rollup-plugin-commonjs

**Comment by kdy1** [comment]
You can disable it by specifing no `module`

**Comment by onigoetz** [comment]
I have no module configuration : 
```
{
    jsc: {
      parser: {
        jsx: true
        syntax: "ecmascript"
      },
      target: "es5"
    },
    env: {
      targets: "> 0.25%, Edge >= 17, Safari >= 11, iOS >= 11, Chrome >= 66, Firefox >= 60, IE >= 11, not op_mini all",
      mode: "entry",
      coreJs: 3
    },
    sourceMaps: true
    filename: ...
}
```

And I don't have a .swcrc, by the way, is the module configuration possible without an `.swcrc` ?

**Comment by kdy1** [comment]
Yes, you can pass module option via programmatic api

**Comment by kdy1** [comment]
Please post your input and some more info. Otherwise I can't debug this.

**Comment by onigoetz** [comment]
So I was able to find the problem and the solution to it. (for the next one with the same question)

The file I am converting is `@swc/helpers/src/index.js` and contrary to what I thought, there IS a `.swcrc` that contains

```json
{
  "jsc": {
    "target": "es2015"
  },
  "module": {
    "type": "commonjs"
  }
}
```

This simple repro case shows it : 

```js
const fs = require("fs/promises");
const { transform } = require("@swc/core");

const TO_CONVERT = require.resolve("@swc/helpers/src/index.js");

async function run() {
  const options = {
    jsc: {
      target: "es5"
    },
    //module: { type: "es6" },
    filename: TO_CONVERT
  };

  const code = await fs.readFile(TO_CONVERT, "utf-8");
  const output = await transform(code, options);

  console.log({code, output: output.code});
}

run().then(
  () => console.log("Done"),
  (e) => console.error("Failed", e)
);
```

This outputs commonjs exports.

but uncommenting `module: { type: "es6" }` forces all exports to be ES6.

thanks a lot for our work and this tool :)

**Comment by kdy1** [comment]
I read again this and it's because helpers were published as a common js module.
This is not a bug
