### ISSUE TITLE
node bindings: `.message` instead of stderr for parse failures?

### ISSUE THREAD

**Issue by bakkot** [swc-project/swc#2035]
When using the node bindings, parse failures are written to stderr directly instead of, as would be more customary, being reported as the `message` property of the thrown error (which is instead always just "failed to parse module"). Can that be changed?

Context: I was going to try fuzzing this project, but for that to be practical I have to be able to skip errors I've seen before. It's a lot more annoying (and significantly slower) to try to determine the cause of a failure by capturing and reading stderr instead of just looking at the thrown error.

**Comment by kdy1** [comment]
Yes, I'll do so.
Actually, I was going to do it in v2, but it's an exception anyway, so it's fine to fix it in v1.
