### ISSUE TITLE
JSX parsing panics when using the spread operator

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#2037]
**Describe the bug**

Using the spread operator in a JSX block causes a panic (at least in Deno).

**Input code**

```jsx
const A = () => {
  return <div>{...[]}</div>;
};
```

**Expected behavior**

The code to be emitted without a panic and something like:

```js
"use strict";
const A = () => {
    return React.createElement("div", null, []);
};
```

**Actual behaviour**

```
❯ RUST_BACKTRACE=1 deno bundle --no-check spread.tsx
Bundle file:///Users/kitsonk/github/deploy_dg/spread.tsx
thread 'main' panicked at 'cannot access a scoped thread local variable without calling `set` first', /Users/kitsonk/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:168:9
stack backtrace:
   0: std::panicking::begin_panic
   1: swc_ecma_transforms_react::jsx::Jsx<C>::jsx_elem_child_to_expr
   2: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
   3: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::next
   4: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   5: swc_ecma_transforms_react::jsx::Jsx<C>::jsx_elem_to_expr
   6: <swc_ecma_transforms_react::jsx::Jsx<C> as swc_ecma_visit::VisitMut>::visit_mut_expr
   7: swc_ecma_visit::visit_mut_stmts
   8: <swc_ecma_transforms_react::jsx::Jsx<C> as swc_ecma_visit::VisitMut>::visit_mut_expr
   9: swc_ecma_visit::visit_mut_var_declarators
  10: <swc_visit::Optional<V> as swc_ecma_visit::Fold>::fold_module
  11: swc_bundler::bundler::load::<impl swc_bundler::bundler::Bundler<L,R>>::load_transformed
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  13: deno::module_graph::Graph::emit_bundle
  14: deno::bundle_module_graph
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: deno::main
```

**Version**

swc_common = "0.11.4"
swc_ecmascript = "0.46.0"

**Additional context**

**Comment by kdy1** [comment]
Seems like [swc_ecma_utils::HANDLER](https://docs.rs/swc_ecma_utils/0.41.0/swc_ecma_utils/static.HANDLER.html) is not configured?

**Comment by kdy1** [comment]
Btw, it does not look like an erroneous input.

**Comment by kitsonk** [comment]
@NamPNQ [TypeScript transpiles it without error](https://www.typescriptlang.org/play?jsx=4#code/MYewdgzgLgBAgjAvDAFASiQPhgbwFAwwBOAplAK5FgwA8AJgJYBumOAdBwNoC6AvjQHpGLANx5eYoA).  Also there is a big difference between an error and a panic.

**Comment by kdy1** [comment]
@kitsonk 
It panics because [swc_ecma_utils::HANDLER](https://docs.rs/swc_ecma_utils/0.41.0/swc_ecma_utils/static.HANDLER.html) is not configured

**Comment by kitsonk** [comment]
Ok, I will look into that. It seems we don't have that set across several projects.

The input isn't an error though, as I mentioned, TypeScript transforms it without error.

**Comment by kdy1** [comment]
swc also transpiles it without an error.
I'm not sure if it's related to `HANDLER`.

**Comment by kdy1** [comment]
Can you try configuring [swc_ecma_utils::HANDLER](https://docs.rs/swc_ecma_utils/0.41.0/swc_ecma_utils/static.HANDLER.html)?

**Comment by kitsonk** [comment]
I am trying to, but we have never used `HANDLER.set()` anywhere in Deno before.  I think I have figured out what I need to do to create a handler, but I am not exactly sure where it needs to be scoped in our code.

Specifically when we bundle, we first create a `swc_bundler::Bundler` and then take the `.bundle()` and run it through a `swc_ecmascript::codegen::Emitter`.  Where does the scoping of the `HANDLER.set()` need to occur?

**Comment by kdy1** [comment]
I think scope should be the invokation of`jsx` transform.
I'm not sure if it will fix the issue. I asked trying it because I can't guess a cause of panic.

**Comment by dsherret** [comment]
It was because `swc_ecma_utils::HANDLER` wasn't set. This API seems very hidden and I'm not sure ideal... I implemented it in Deno in https://github.com/denoland/deno/pull/12773 by collecting the diagnostics and then returning an error after transforming if a diagnostic with a certain level appeared. Works ok, I think, now that we know about it.

The error we get now is: `Spread children are not supported in React.`. I see Babel gives that error, but as Kitson pointed out TypeScript seems to handle this transform. I don't think there's any harm in implementing it.

**Comment by kdy1** [comment]
I'll do so, as I prefer behavior of tsc of it of babel.

**Comment by kdy1** [comment]
It's not hard, but not sure how much it will be for others

**Comment by Hotell** [comment]
Wondering if there are plans to fix this in near future ? We ran into this as well (not panic rather error which is preventing us to use swc) https://github.com/microsoft/fluentui/issues/25767. ty!

**Comment by Hotell** [comment]
that was fast ! thanks a ton @kdy1 🙌
