### ISSUE TITLE
Do not return an error from `parse_program()` when the text contains `import.meta`

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#2041]
**Describe the feature**

When the text contains `import.meta` it would be nice to still be able to get an AST via `parse_program()`. Going along with the theme of #1178, I think it would be better for it to still return an AST, but put this in the errors diagnostic collection instead.

It would also be nice if the same thing happened for import and export declarations (IIRC it does this for them too).

**Comment by bartlomieju** [comment]
To add to that - shouldn't `import.meta` (or import/export statement) put parser into "module" mode instead of erroring?

**Comment by kdy1** [comment]
@bartlomieju Yeah, I think you are correct.

**Comment by bartlomieju** [comment]
> @bartlomieju Yeah, I think you are correct.

Thanks @kdy1, there's no huge rush from our side, I think we can safely upgrade to 0.51.0 in the meanwhile.
