### ISSUE TITLE
Support stage-4 ergonomic brand checks for private fields

### ISSUE THREAD

**Issue by sosukesuzuki** [swc-project/swc#2064]
**Describe the feature**

Support [ergonomic brand checks](https://github.com/tc39/proposal-private-fields-in-in) proposal that is now Stage-4.

**Babel plugin or link to the feature description**

Now [Babel 7.15](https://babeljs.io/blog/2021/07/26/7.15.0#ecmascript-features-enabled-by-default) supports it in default.

**Additional context**

Nothing

**Comment by kdy1** [comment]
Thanks for the info!

**Comment by HiZhaoxiaoyang** [comment]
开始还以为shock wave component又卷土重来了。

**Comment by sosukesuzuki** [comment]
Note; Ergonomic brand checks will be landed in TypeScript 4.5 :smile:
(Sorry if you know about this.)

- ref: https://github.com/microsoft/TypeScript/pull/44648

**Comment by kdy1** [comment]
I didn't finish it because of time. It's stage-4, so support of `tsc` does not matter.
