### ISSUE TITLE
Provide a statically linked binary

### ISSUE THREAD

**Issue by idan-at** [swc-project/swc#2085]
Hi, I'm trying to replace `babel` with `swc`. I use a docker image which disallows dynamic linking of `.so` files.

I might be wrong with my assumption (that a statically linked binary will work), and will appreciate your help.

When I try to `require("@swc/core")`, I get:
```bash
Error: Can not load bindings, file: /app/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node existed but error occurred while require it: /app/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node: cannot open shared object file: No such file or directory
file: /app/node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node existed but error occurred while require it: /app/node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node: cannot open shared object file: No such file or directory
Installed packages: [core-linux-x64-gnu, core-linux-x64-musl]
    at Object.loadBinding (/app/node_modules/@node-rs/helper/lib/loader.js:50:11)
    at Object.<anonymous> (/app/node_modules/@swc/core/index.js:37:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  _internalJustPassThrough: true
}
```

Any idea?

Thanks in advanced.

**Comment by kdy1** [comment]
You can install [`@swc/core-linux-x64-musl`](https://www.npmjs.com/package/@swc/core-linux-x64-musl)

**Comment by Brooooooklyn** [comment]
What base image are you using

**Comment by kdy1** [comment]
Oh, I missed the error message.

**Comment by idan-at** [comment]
I've tried requiring `core-linux-x64-musl` too, and I get the same error:

```
Error: /app/node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node: cannot open shared object file: No such file or directory
```

I'm using a custom docker image only contains node (no `bash` or anything)

**Comment by Brooooooklyn** [comment]
But you must have a base image, does it node:lts-alpine?

**Comment by idan-at** [comment]
It’s from scratch 

basically we copy the node executable and thats it

**Comment by mischnic** [comment]
Not sure if libgcc and libc are meant to be statically linked (or if that causes other problems):
```
readelf -d node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node

Dynamic section at offset 0x1797960 contains 23 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.musl-x86_64.so.1]
```

**Comment by Brooooooklyn** [comment]
Node.js addon is actually a `dynamic link file`, see https://napi.rs/introduction/native-module

So I think it's not possible using it without `libc libraries`. For `Node.js` program, if you want a Docker image with smallest size, I recommend using the `node:lts-alpine` image, `swc` should be compatible with this ***Official*** Docker image.

**Comment by idan-at** [comment]
I found out that we have `libgcc_s.so.1`, but missing `libc.musl-x86_x64.so.1`. 

I know it's not official and you might change things in the future and it's fine.

Thanks for your help, I will try adding `libc.musl` manually
