### ISSUE TITLE
Support environment variables that map to globals (spack)

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#2087]
Support passing environment variables using a command line option that are transformed into global variables when building with **spack**.

This is typically used to switch backend API but has many uses beyond that. I suggest adding the `--env` option to spack which would take:

```
spack --env API_URL=http://localhost:3000
```

When compiling spack would define a `const` declaration for each environment variable at the top-level scope of the bundle:

```javascript
const API_URL = 'http://localhost:3000'
```

If a variable name contains a period it should be expanded to an object literal:

```
spack --env process.env.FOO=bar
```

Should yield:

```javascript
const process = {
  env: {FOO: 'bar'}
};
```

@kdy1, if you are happy with this feature request I can have a go at the implementation, thanks! :+1:

**Comment by kdy1** [comment]
Yes, I think this is super useful, especially if someone can configure this from javascript.

**Comment by tmpfs** [comment]
It is possible to do this using `jsc.transform.optimizer.globals.envs`, see #2093 and #2121.
