### ISSUE TITLE
optimizer: inline code error when not using Object Literal Shorthand 

### ISSUE THREAD

**Issue by troy351** [swc-project/swc#2108]
**Describe the bug**

**Input code**
```js
function foo() {
  let arr = []
  arr = [1, 2, 3]

  // NOTE: `return { arr }` works fine
  return { arr: arr }
}

foo()
```

**Config**

```js
{
    jsc: {
      parser: {
        syntax: 'ecmascript',
      },
      transform:{
            optimizer: {
              globals: {
                vars: {
                },
              },
            },
          },
      loose: true,
      target: 'es2021',
      externalHelpers: true,
    },
    module: {
      type: 'commonjs',
    },
  }
```

**Expected behavior**
output error
```js
function foo() {
    let arr;
    arr = [
        1,
        2,
        3
    ];
    return {
        // wrong here
        arr: []
    };
}
foo();
```
**Version**
The version of @swc/wasm: 1.2.78

**Additional context**

**Comment by kdy1** [comment]
You can use minify option instead.

**Comment by troy351** [comment]
You mean optimizer option was deprecated? But I do want to use `globals.vars`

**Comment by kdy1** [comment]
`optimizer` is not deprecated, but the `optimizer` option has nothing to do with shorthand syntax.
Also, minify option supports replacing global variables.
https://swc.rs/docs/config-js-minify#global_defs

**Comment by troy351** [comment]
Yeah, I mean I can use minify instead, but it still a bug didn't it?

**Comment by kdy1** [comment]
No, it's not a bug. Again, `optimizer` option is not related to shorthand syntax.

**Comment by troy351** [comment]
Sorry, maybe it's not related to shorthand syntax, but the output code does change the behavior of the original code

**Comment by kdy1** [comment]
Oh, I misread because of the title. This is definitely a bug.

**Comment by troy351** [comment]
Sorry for the misleading
