### ISSUE TITLE
Problem with Arrays

### ISSUE THREAD

**Issue by willytobler** [swc-project/swc#211]
There seems to be a severe bug with arrays - or i didnt understand something with config

**input**:
    idx=$this.attr('data-idx');
    **_query[idx]**=$this.attr('data-ref');
    if($this.hasClass('tag-is-active')){
      _query[idx]='';
    }else {
      if(activeTags[idx])activeTags[idx].removeClass('tag-is-active');
      activeTags[idx]=$this;
    }
**output**:
       idx = $this.attr('data-idx');
        **_query.idx** = $this.attr('data-ref');
        if ($this.hasClass('tag-is-active')) {
            **_query.idx** = '';
        } else {
            if (**activeTags.idx**) activeTags.idx.removeClass('tag-is-active');
            **activeTags.idx** = $this;
        }

To compile _query[idx] to _query.idx is never correct for an array!

**Comment by kdy1** [comment]
Seems like #206. Are you using lastest version of swc? (1.0.10)
