### ISSUE TITLE
Node span incorrect when iterating over source containing characters over ASCII range (0-127)

### ISSUE THREAD

**Issue by jdalton** [swc-project/swc#2128]
```js
const a = '¤';
export { a };
```
Will produce a node of:
```
    {
      type: 'ExportNamedDeclaration',
      span: { start: 16, end: 29, ctxt: 0 },
      specifiers: [
        {
          type: 'ExportSpecifier',
          span: [Object],
          orig: [Object],
          exported: null
        }
      ],
      source: null,
      typeOnly: false,
      asserts: null
    } 
   ```
   The substring of the coordinates 16 29 is `xport { a };` and not `export { a };`.
   If I swap the `'¤'` for `'a'` then the correct coordinates are populated.
   
   ~~In this case `'¤'` is 1 character totaling 2 bytes.~~

**Comment by jdalton** [comment]
Hmm the char code for `'¤'` is only 164.  I'm at a loss as to why the parser is messing up there.

**Comment by jdalton** [comment]
The character of `""` which is a char code of 128 also causes a problem if present in the source.

**Comment by jdalton** [comment]
Looks like it's only accepting code with an ASCII range of 0-127 without causing the coordinates to get off.

**Comment by kdy1** [comment]
I tried this and I found that span api is working as intended.

![image](https://user-images.githubusercontent.com/29931815/130590922-db7016c9-500b-455e-abfd-a2b5c7c90848.png)


Note: `¤` takes two bytes in utf8. See https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=89ba841bd13990fe1598856a43bd7068

**Comment by jdalton** [comment]
Hi @kdy1. Thanks for checking it out!

I can still repro this however. Try using the `parseSync` API and checking the results of the span as is pointed out in the repro.

**Comment by jdalton** [comment]
`'¤'.length` is `1` in JS.

**Comment by kdy1** [comment]
I mean it's the correct output because the span is byte-based.
I know the length of `'¤'` is 1 in js, but it's two bytes width.

**Comment by jdalton** [comment]
Right but your coordinates need to be correct for the language consuming it. What good are coordinates that produce invalid results?

**Comment by jdalton** [comment]
There's no way beyond inspecting the source to know there could be an issue and then no way to fix it and account for the offset unless the entire string is found/replaced and then parsed. It makes working around the issue perf consuming.
