### ISSUE TITLE
References to process.env are overwritten with an empty string

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#215]
expressions containing `process.env.foo` are overwritten as an empty string

I tried this: 

```
const x = process.env.x;
```

I expected to see this happen: 

```
'use strict';
var x = process.env.x;
```

Instead, this happened: 

```
'use strict';
var x = '';
```

I'm using 0.1.9

**Comment by kdy1** [comment]
Fixed with @swc/core@1.0.13.
Note that `swc` is renamed to `@swc/core` and `swc-cli` is renamed to `@swc/cli`.
