### ISSUE TITLE
SWC REPL panics

### ISSUE THREAD

**Issue by danieltroger** [swc-project/swc#2151]
**Describe the bug**

Steps to reproduce:
1. Go to https://swc.rs/repl/#%7B%22rawCode%22%3A%22main()%3B%5Cn%5Cnasync%20function%20main()%20%7B%5Cn%20%20let%20promise%3B%5Cn%5Cn%20%20const%20awaited_promise%20%3D%20await%20(promise%20%7C%7C%3D%20Promise.resolve(%5C%22this%20is%20a%20string%5C%22))%3B%5Cn%20%20console.log(awaited_promise.toString())%3B%5Cn%7D%22%2C%22rawConfig%22%3A%22%7B%5Cn%20%20%5C%22env%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22shippedProposals%5C%22%3A%20true%5Cn%20%20%7D%5Cn%7D%22%7D
2. Wait
3. Page will turn white

**Expected behavior**
Page does not turn white

**Additional context**
Wanted to try if SWC is to blame for an issue I'm having with parcel

**Comment by danieltroger** [comment]
Hello, thank you for the fix. The REPL link now no longer leads to a white page. However, it now says `RuntimeError: unreachable executed`. Could you solve that too?

**Comment by IWANABETHATGUY** [comment]
> Hello, thank you for the fix. The REPL link now no longer leads to a white page. However, it now says `RuntimeError: unreachable executed`. Could you solve that too?

I guess this is because env option rely on `browserslist` npm module , https://swc.rs/docs/preset-env,  which wasm doesn't have, this cause runtime error   


```bash
 panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Other, message: "operation not supported on this platform" }', ecmascript/preset-env/src/lib.rs:479:29
```

**Comment by RiESAEX** [comment]
seems our new playground don't have this problem

**Comment by kdy1** [comment]
@g-plane Thank you so much!
