### ISSUE TITLE
Await as a part of compound expression results in syntax error

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#216]
<short summary of the problem>

I tried this: 

```
async function foo(bar) {
  bar && await bar();
}
```

I expected to see this happen: 

```
if (bar) {
  yield bar();
}
```

Instead, this happened: 

```
...lots of lines
bar && yield bar();
```

According to the MDN docs, yield has a specific statement syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield#Syntax. It looks like it can only be used as a rvalue, not as a part of a compound expression.

I'm using 0.1.9

**Comment by kdy1** [comment]
Fixed with @swc/core@1.0.13.
Note that `swc` is renamed to `@swc/core` and `swc-cli` is renamed to `@swc/cli`.
