### ISSUE TITLE
Sourcemap shifting with multiline template strings in jest

### ISSUE THREAD

**Issue by hjkcai** [swc-project/swc#2185]
**Describe the bug**
The sourcemap has shifting when testing in jest with multiline template strings. This problem will disappear after removing `target` option in swcrc.

See the screenshot below:

![image](https://user-images.githubusercontent.com/731326/131369457-9df5db65-7a54-407b-942d-63a81d80163b.png)

However, I cannot reproduce if I use swc cli directly. Everything seems be fine when I upload the source and the sourcemap to [source-map-visualization](https://sokra.github.io/source-map-visualization). I have no idea whether this issue is related to jest or swc.

![image](https://user-images.githubusercontent.com/731326/131370336-07906035-d7c2-4493-9874-1069f5f8d163.png)

**Input code**

https://github.com/hjkcai/jest-swc-source-map-shifting

```js
describe("foo", () => {
  it("test1", () => {
    expect(false).toBe(true);
  });

  it("test2", () => {
    const str = `
      bar
    `;

    expect(false).toBe(true);
  });

  it("test3", () => {
    expect(false).toBe(true);
  });
});
```

**Config**

```json
{
  "sourceMaps": true,
  "jsc": {
    "target": "es2015"
  }
}
```

**Expected behavior**
The sourcemap correctly maps back to the source.

**Version**
The version of @swc/core: latest (1.2.83)

**Comment by ihm-tswow** [comment]
Looks like this is indeed an issue with swc, it also messes up sourcemaps for [source-map-support](https://www.npmjs.com/package/source-map-support) with TypeScript.

The same thing also happens with multi-line comments:

```ts
/**
 * This is a
 * long
 * license
 * header
 */
console.log(new Error().stack)
```

Some findings:
- Single-line template strings (``` `string` ```) or multiline comments (`/** comment */`) are unaffected and work fine 
- The issue more precisely seems to be that multiline comment / template string lines counts as two lines, for every new line i add to them, two are added to the output sourcemap.

```
@swc/cli: 0.1.52
@swc/core: 1.2.112
```

```json
{
    "module": {
        "type":"commonjs"
    },
    "exclude":[".*.js$",".*\\.d.ts$"],
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
            "decorators": true,
            "dynamicImport": true
        },
        "target":"es2016",
    },
    "sourceMaps": true
}
```
