### ISSUE TITLE
Expose internal parse APIs

### ISSUE THREAD

**Issue by 71** [swc-project/swc#2187]
Hey, and thanks for your work on swc!

I'm trying to build a parser for a superset of JavaScript. Basically, it would allow `import` and `export` statements in a function context which can `yield` (and other features).

For now, this isn't possible. `Context` fields are not exposed, and thus a parser cannot be in an `is_generator` / `module` state simultaneously. Also, for more advanced changes (for instance, adding new top-level declarations), nothing is possible.

It would be great if the internal parsing APIs were exposed (e.g., `parse_import`, `handle_import_export`, ...) to allow extended syntax. Custom parsers could work on the existing `Parser` structure, and return existing AST nodes (possibly transformed or `Mark`ed for later processing in a visitor). Alternatively, a trait like `ParseWith` implement for all expressions would work.

**Comment by 71** [comment]
`Parse<T>` sounds great, yep!

As for `Context`, it makes sense that it wouldn't be completely exposed as it probably needs to uphold some internal invariants. I also like the idea of having methods that return new `Context`s, since those methods could validate invariants internally and possibly return `Result<Context, E>`.

In any case, if you want I can try submitting a PR adding these features.

**Comment by kdy1** [comment]
Can you make a PR?
I don't know the exact feature set you need, and exposing all would take lots of time.

**Comment by kdy1** [comment]
Closing as it's a feature request but author did not respond
