### ISSUE TITLE
Consider making `MapWithMut` a public API

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#2189]
I am using the `MapWithMut` trait for `take()` in `Fold`. I realize it is designed for `VisitMut` but I have a use case where it makes sense to use `take()` to prevent an additional `clone()`. The comments in  the file indicate it is not for public use yet there is documentation that it can be used when implementing `VisitMut` as an optimization in preference to `Fold`.

I have some *fallible functions* that I use to build `Stmt` (and other node types). Because `Fold`, `VisitMut` etc are all infallible I want to build these nodes outside of the `Fold` implementation and then pass them in. The general pattern looks like this:

```rust
fn build_stmt() -> Result<Stmt> {
  // Generate the statement
}

fn fallible_builder(self) -> Result<Self> {
  let stmt = build_stmt()?;
  let mut stmt_fold = StmtFold {stmt};
  self.script.fold_with(&mut stmt_fold);
  Ok(self)
}

struct StmtFold {
  stmt: Stmt,
};
impl Fold for StmtFold {
  fn fold_script(&mut self, mut n:Script) -> Script {
    let stmt = self.stmt.take();
    // Do something with `stmt`
    n
  }
}
```

Would you consider making `MapWithMut` and therefore `take()` a public API?

**Comment by kdy1** [comment]
Yeah, I felt that I should expose it while working on a transform for `next.js`.
But I should polish it before exposing.
