### ISSUE TITLE
export Foo from 'bar' is not supported

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#219]
I tried this: 

```js
export Foo from 'bar';
```

I expected to see this happen: 

(roughly)
```js
module.exports = {
  Foo: require('bar'),
};
```

Instead, this happened: 

```
error: Expected LBrace, got Some(Word(Foo))
 --> test.js:1:8
  |
1 | export Foo from 'bar';
  |        ^^^

fatal runtime error: failed to initiate panic, error 5
[1]    39889 abort      npx swc test.js
```

I'm using CLI 0.1.12, @swc/core 1.0.13.

**Comment by natemara** [comment]
It also looks like `export default foo from 'bar'` is not working anymore either, as described in #160

**Comment by kdy1** [comment]
You need `.swcrc` like 
```json
{
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "exportDefaultFrom": true
        }
    }
}
```

**Comment by natemara** [comment]
I have this `.swcrc`, but I'm still not able to get `export default from ...` to work

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "dynamicImport": true,
      "classProperty": true,
      "exportDefaultFrom": true,
      "jsx": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Comment by kdy1** [comment]
I verify that @swc/core@1.0.13 can compile export default from using your config.

See: https://github.com/kdy1/swc-example/tree/0732c0f04461162fb64cc4c653860bb04c343e9c/inputs/issue-219

**Comment by natemara** [comment]
That source has `export Foo from 'bar';`, not `export default from 'bar';`

**Comment by kdy1** [comment]
Nice catch. I'll start working on it.

**Comment by cyjake** [comment]
This one seems not have been fixed yet. `export Foo from 'bar'` still breaks

**Comment by cyjake** [comment]
@kdy1 nice. It compiles without error now, though it seems to be some interop issue. I'll post another issue if bug confirmed. btw, great work!
