### ISSUE TITLE
{ 	"sourceMaps": true } not working

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#2194]
**Describe the bug**

It doesn't create a sourcemap file.

**Input code**

anything

**Config**

```json
{
	"sourceMaps": true
}
```

**Expected behavior**
After running `swc index.js -d dist`, there should be a `dist/index.js` and `dist/index.js.map` file.

**Current behaviour**
No sourcemap is emitted.
`"sourceMaps": "inline"` works correctly though.

**Version**
The version of @swc/core: 1.2.83

**Comment by UsamaHameed** [comment]
For me, this works

```
// .swcrc
{
    "sourceMaps": true,
    "inlineSourcesContent": true,
}
```
