### ISSUE TITLE
Panic on parsing TypeScript syntax

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#2198]
**Describe the bug**

The following code will cause a panic when being parsed.  It isn't valid, but it should parse and allow diagnostics to be returned.

```
thread 'main' panicked at 'internal error: entered unreachable code: parse_lit should not be called', /Users/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.66.2/src/parser/expr.rs:1574:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Input code**

```ts
function imp<T extends string>(x: T): typeof import(T) {
    return x;
}

console.log("123");
```

**Expected behavior**

No panic.

**Version**

swc_parser 0.66

**Additional context**

Ref: denoland/deno#11898

**Comment by kdy1** [comment]
@kitsonk Is this valid syntax? If so, the AST definition of `TsImportType` is wrong.
