### ISSUE TITLE
core-js definitions are not fully injected with useBuiltIns: usage

### ISSUE THREAD

**Issue by pan93412** [swc-project/swc#2209]
**Describe the bug**

When using `env: mode: "entry"` with TypeScript and `Promise.any`, the output file should include not only `promise.any` module but also `esnext.agregate-error` module. 

For reference: https://github.com/zloirock/core-js/issues/737 https://github.com/babel/babel/issues/10910

**Input code**

```ts
Promise.any([]);
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "dynamicImport": false,
      "decorators": false
    },
    "target": "es2015"
  },
  "env": {
    "target": {
      "node": "10"
    },
    "mode": "usage",
    "coreJs": "3.17",
    "shippedProposals": true
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

**Expected behavior**

Considering the output file:

```js
"use strict";
require("core-js/modules/es.promise");
require("core-js/modules/es.object.to-string");
require("core-js/modules/esnext.promise.any");
require("core-js/modules/es.string.iterator");
require("core-js/modules/es.array.iterator");
require("core-js/modules/web.dom-collections.iterator");
Promise.any([]);
```

It should also include `require("esnext.agregate-error")` according to https://github.com/zloirock/core-js/issues/737.

**Version**

```bash
$ yarn swc --version
yarn run v1.22.11
$ /Users/pan93412/Projects/check_env/node_modules/.bin/swc --version

@swc/cli: 0.1.49
@swc/core: 1.2.84

✨  Done in 0.24s.
```

**Additional context**

Thanks a lot! :)

**Comment by zloirock** [comment]
Built-ins definition should be aligned with https://github.com/babel/babel-polyfills/pull/99

**Comment by pan93412** [comment]
> Built-ins definition should be aligned with [babel/babel-polyfills#99](https://github.com/babel/babel-polyfills/pull/99)

So, should we wait until it got merged?

**Comment by zloirock** [comment]
Not necessary. In this PR also should be:
- Removed `*.typed-array.*` methods from instance dependencies (they are in constructors dependencies)
- Removed `es.reflect.to-string-tag` from `Symbol.toStringTag` dependencies (it's mover to global `Reflect`)
- Added `IteratorDependencies` to instance `every`, `filter`, `find `, `flatMap`, `forEach`, `map`, `reduce`, `some`.

**Comment by zloirock** [comment]
https://github.com/babel/babel-polyfills/pull/99 is merged.
