### ISSUE TITLE
name conflict between imports and underscore prefixed function-scoped properties

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#2211]
**Describe the bug**

This is a regression - works fine for me in 1.2.74

During transpilation imports are renamed to file name prefixed with underscore. If you define a class property with the same name, it will instead overshadow the import.

This works fine if you define simple variable with the same name - transpiler resolves the conflict by using number as a suffix.

**Input code**

bar.ts
```
export const bar = () => console.log("foo");
```

foo.ts
```
import { bar } from "./bar";

const makeX = () => {
  const _bar = () => bar();
  return { _bar };
}

makeX()._bar();
```

Throws:
```
        this._bar = ()=>(0, _bar).bar()
                                  ^

TypeError: (0 , _bar).bar is not a function
```

**Config**

```json
{
  "env": {
    "targets": {
      "node": "16.8"
    }
  },
  "jsc": {
    "target": "es2019",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": "inline"
}
```

**Expected behavior**
Generated import names should not conflict with class properties after transpilation.

**Version**
The version of @swc/core: 1.2.84

**Comment by kdy1** [comment]
Where does `this._bar = ()=>(0, _bar).bar()` come from?
It's not reproducible with the input you provided.

**Comment by pbadenski** [comment]
Sorry - this error gets throw when I run `node_modules/.bin/swc-node foo.ts`:

```
> node_modules/.bin/swc-node foo.ts
/private/tmp/swc-test/foo.ts:4
    const _bar = ()=>(0, _bar).bar()
                               ^

TypeError: (0 , _bar).bar is not a function
    at Object._bar (/private/tmp/swc-test/foo.ts:4:32)
    at Object.<anonymous> (/private/tmp/swc-test/foo.ts:10:9)
```

**Comment by pbadenski** [comment]
Still a problem if a function is defined within scope, but no exported. It will generate name conflict if `foo.ts` is changed to below:

```
import { bar } from "./bar";

const makeX = () => {
  const _bar = () => bar();

  const alfa = () => _bar();

  return { alfa };
}
```

Should I submit as a separate issue?
