### ISSUE TITLE
Error recursion limit exceeded

### ISSUE THREAD

**Issue by tido64** [swc-project/swc#2223]
**Describe the bug**

While evaluating whether we can use swc, I got "recursion limit exceeded" in our somewhat large codebase:

```
thread '<unnamed>' panicked at 'failed to deserialize Program: Error("recursion limit exceeded", line: 1, column: 35827)', node/binding/src/transform.rs:42:50
stack backtrace:
   0:        0x
10e2c19c3 - _rust_eh_personality
   1:        0x10e21a1cc - _napi_register_module_v1
   2:        0x10e2c044a - _rust_eh_personality
   3:        0x10e2c0c1f - _rust_eh_personality
   4:        0x10e2c0181 - _rust_eh_personality
   5:        0x10e2df2ba - _rust_eh_personality
   6:        0x10e2df239 - _rust_eh_personality
   7:        0x10e2df1f5 - _rust_eh_personality
   8:        0x10f4b80af - _rust_eh_personality
   9:        0x10f4b8395 - _rust_eh_personality
  10:
 0x10e0e0d0c - <unknown>
  11:        0x1009f24fa - _worker
  12:     0x7fff204978fc - __pthread_start
fatal runtime error: failed to initiate panic, error 5
```

**Input code**

Unfortunately, this is proprietary code I cannot publish here.

**Config**

```js
{
  filename,
  swcrc: false,
  jsc: {
    parser:
      filename.endsWith(".ts") || filename.endsWith(".tsx")
        ? {
            syntax: "typescript",
            tsx: filename.endsWith(".tsx"),
          }
        : {
            syntax: "ecmascript",
            jsx: true,
          },
    target: "es2015",
  },
  minify: options.minify,
  sourceMaps: true,
  isModule: true,
}
```

**Expected behavior**
No recursion limit is hit.

**Version**
The version of @swc/core: 1.2.85

**Additional context**
I realize this may be hard to reproduce without the actual code. Please let me know if there are other ways I can provide more information.

**Comment by kdy1** [comment]
I can't debug it without code.

**Comment by kdy1** [comment]
If you can't reduce it, can you send the input via email?
My email is kdy1997.dev@gmail.com

**Comment by kdy1** [comment]
Reopening as it can be fixed without input code. (It's serde error, and I can increase limit)

**Comment by tido64** [comment]
Thanks for the quick fix. I wasn't able to create a minimal repro but I'm glad you figured it out.
