### ISSUE TITLE
Decorated class .name is broken in class properties

### ISSUE THREAD

**Issue by petrzjunior** [swc-project/swc#2224]
Follow-up to #1279 
**Describe the bug**
When decorating class, property initalizers get wrong class name.
**Input code**
```ts
@Injectable()
export class TestClass {
	private readonly property = TestClass.name;
	private unitializedProperty;

	constructor() {
		const constructorVariable = TestClass.name;
		this.unitializedProperty = TestClass.name;
	}
}
```
**Output**
```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.TestClass = void 0;
var _class1;
var _dec = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:paramtypes", []), _dec1 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", Function), _dec2 = Injectable();
let TestClass2 = _class1 = _dec2(_class1 = _dec1(_class1 = _dec((_class1 = class TestClass {
    constructor(){
        this.property = _class.name;
        const constructorVariable = TestClass.name;
        this.unitializedProperty = TestClass.name;
    }
}) || _class1) || _class1) || _class1) || _class1;
exports.TestClass = TestClass2;

```
**Config**

```json
{
	"jsc": {
		"parser": {
			"syntax": "typescript",
			"decorators": true
		},
		"transform": {
			"decoratorMetadata": true,
			"legacyDecorator": false
		},
		"target": "es2020",
		"keepClassNames": true,
	},
	"module": {
		"type": "commonjs",
		"strict": false,
		"strictMode": true,
		"lazy": false,
		"noInterop": false
	}
}
```

**Expected behavior**
I expect `TestClass.name` to stay as `TestClass.name`. Instead, in case of initialized class property, I get `_class.name`, which throws error at runtime. Initializing property in constructor works as expected. Note that this is happening only if the class is decorated.

**Version**
The version of @swc/core: 1.2.85

**Comment by petrzjunior** [comment]
Adding playground link to replicate: https://play.swc.rs/?version=1.2.138&code=H4sIAAAAAAAAA22OQQrCMBBF180pZtlueoFSEVy5cyHux3TASEzCZFqsJXc3arGC3Q1%2FHu9%2F7V0U2LsracGzJWihrKDdwJQapbbLo6wU3YNnAW0xRjhSlN37mlQR2AwoBEzYeWdHCOwDsYxZ9wVrhzdqFrh3Rgxa86DuMOO5stCvRdxr8ZyXZPkngZ%2F8hGzmsX%2F2Qi4m1ivuNTip9ARhTK4pAQEAAA%3D%3D&config=H4sIAAAAAAAAA0XOQQ7DIAwEwL%2F4zAu4Jtf2Dxa4VVPAyHakoIi%2FNyhNe9vD7mh3WDSA36GiKMlI2orhBh6sVdIgr2rgIFJgQWNR8CYrOTDdztgdvInqlFD1jpn%2BDcGiD5Y82ERPDG2%2BmKvzc29kGNHwax5o5rgmGtvx5DgUOGcui0LvH6Z1WjO4AAAA

**Comment by gmalette** [comment]
As far as I can tell this is a faulty integation between [`Strip`](https://github.com/swc-project/swc/blob/8a651bc449e077ad0e9c9d87379775d734d11421/crates/swc_ecma_transforms_typescript/src/strip.rs) and [`decorators::Lazy`](https://github.com/swc-project/swc/blob/8a651bc449e077ad0e9c9d87379775d734d11421/crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs). 

Without decorators, `Strip` will be going through `visit_mut_stmt_like` which preserves the original class name. 

https://github.com/swc-project/swc/blob/8a651bc449e077ad0e9c9d87379775d734d11421/crates/swc_ecma_transforms_typescript/src/strip.rs#L620-L623

With decorators, it goes through `handle_expr` which creates a new `_class` identifier to name the class.

https://github.com/swc-project/swc/blob/8a651bc449e077ad0e9c9d87379775d734d11421/crates/swc_ecma_transforms_typescript/src/strip.rs#L695-L697

Once inside `fold_class_as_decl`, it will rename `ClassProp` right-side identifiers matching the class name.

https://github.com/swc-project/swc/blob/8a651bc449e077ad0e9c9d87379775d734d11421/crates/swc_ecma_transforms_typescript/src/strip.rs#L413-L415

Therefore it will be replaced with `_class`. I'm not sure why it does that yet.
