### ISSUE TITLE
"Unexpected token `div`. Expected jsx identifier" in .tsx file

### ISSUE THREAD

**Issue by srmagura** [swc-project/swc#2237]
**Describe the bug**
swc fails to compile a React component that defines a function with a return type inside a JSX expression.

```
error: Unexpected token `div`. Expected jsx identifier
 --> broken.tsx:5:10
  |
5 |         <div>
  |          ^^^



Caused by:
    0: failed to process js file
    1: failed to parse module
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (C:\Projects\CareServices\TracRx\Source\node_modules\@swc\cli\lib\swc\util.js:115:15)
    at files (C:\Projects\CareServices\TracRx\Source\node_modules\@swc\cli\lib\swc\file.js:179:18)
    at async _default (C:\Projects\CareServices\TracRx\Source\node_modules\@swc\cli\lib\swc\file.js:198:9)
```

**Input code**
```ts
import React from 'react'

export function Results() {
    return (
        <div>
            {[].map(() => {
                function onClick(): void {}

                return null
            })}
        </div>
    )
}
```

**Config**
Doesn't seem to matter much. Same error whether I use no config file or
```json
{
   "jsc":{
      "parser":{
         "syntax":"typescript",
         "tsx":true,
         "decorators":false,
         "dynamicImport":true
      },
      "target":"es5"
   },
   "module":{
      "type":"commonjs"
   }
}
```

**Expected behavior**
The code should compile without error. The TypeScript compiler can compile this code.

**Version**
The version of @swc/core: 1.2.85

**Additional context**
The error goes away if you remove the `void` return type annotation from `onClick`.

**Comment by matteoturini** [comment]
This shouldn't be closed bugs still happening.

**Comment by kdy1** [comment]
@matteoturini Please share more input code.

**Comment by kdy1** [comment]
@faustAbc 

> I faced the same problem recently. The issue was I used component that wasn't defined.

Did you use swc? At the moment of parsing, whether a component is defined does not matter at all.

**Comment by kdy1** [comment]
Also, please file another issue with input
