### ISSUE TITLE
HTML parsing/minification as well?

### ISSUE THREAD

**Issue by clarfonthey** [swc-project/swc#2242]
Right now, the program supports parsing both ECMAScript and CSS -- it seems like a logical step would be to support HTML as well? I'm not sure if this is on the roadmap or not, but I figured I'd mention it here since I didn't see anything anywhere mentioning it.

Given a full HTML DOM, it would be pretty easy to create a rudimentary version of `uncss` as well, which could potentially save space for large frameworks.

**Comment by kdy1** [comment]
Will it be useful?
I'm mot sure.
Can you suggest some usecases?

**Comment by clarfonthey** [comment]
I mean, I already gave one. Being able to minify DOM is the other use case but I don't think that is as useful as being able to check what's used in it like in the case I mentioned.

**Comment by kdy1** [comment]
I'm not going to work on this near future, because there's no user actually requires this.

**Comment by alexander-akait** [comment]
Mostly finished https://github.com/swc-project/swc/tree/main/crates/swc_html. To finish:
1. Resolve todo (simple)
2. Add tests from html5_tests
3. Implement some addiontal rules for minifier (simple)

**Comment by alexander-akait** [comment]
@kdy1 I think we can close now, we support HTML parsing and minification (and more) and have binding, will be great to have docs about it, but the originally issue solved

**Comment by kdy1** [comment]
You are right
