### ISSUE TITLE
swc generates incorrect code when it encounters a function and a namespace with the same name (similar issue as #1515)

### ISSUE THREAD

**Issue by mawart** [swc-project/swc#2243]
Hi guys, thank you for the great work so far!

**Describe the bug**

On some files our Typescript codebase that use declarative merging on functions and namespaces, swc generates code that crashes with SyntaxError: Identifier has already been declared. These files have a TS function and namespace with the same name, which is allowed in TypeScript.

**Input code**
```typescript
export function Colors(member: Colors.KeyType): Colors {
    return Colors.ValueFor(member);
}

export module Colors {
    export type KeyType = keyof typeof ValueMap;

    export const ValueMap = {
        Red: { value: 0.0, label: 'Red' },
        Blue: { value: 1.0, label: 'Blue' },
        Green: { value: 2.0, label: 'Green' },
    } as const;

    export const Values: Colors[] = [0.0, 1.0, 2.0];

    export function ValueFor(member: KeyType): Colors {
        return ValueMap[member]?.value;
    }

    export function LabelFor(
        member: KeyType
    ): Promise<string | undefined> {
        return ValueMap[member]?.label;
    }
}
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,   
    },
    "target": "es2018"
  },
  "module": {
    "type": "es6"
  }
}
```

**Expected behavior**
I expected swc to generate correct code without syntax errors. However, it generates a class and a variable with the same name – which throws the SyntaxError.

**Version**
The version of @swc/core: 1.2.85

**Comment by kdy1** [comment]
Please provide more input.

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwMIQA20AzgBQC2wFARsFAFz5GkB0A0sAJ4AqXYwAJRMCxKCTgBvAFBw5cKMBhIouUWwBqAQ0JJgAMWiVqdKIIDc0gL7TpoSLDgUIAEySFgzMRJny496HgYfk9OXhC4AF44AGtuCAQ4YIEEuG1dYABZLTBLWXkAxzQcEnh0vWywKKl8vzkAJWAXJkk4ADcdPSYABlZugBo4Qi06QiYAckaXcbgrftq6gCEMlvbO4CYARj7B4dGJ5b0ZuYW-AHFFYBRVjpW4ACYdoZHgMbhxi+Ar4-m-KzgtBJiihSnk-IV4MDSml1iQRCxxABtAC61URvQGcG2mMe3WRYIK4ECiFQGGwuHKBiMVFo9CYYT4AmEXlINTq8kUylUMIylURNNMyIA-KxbnpLH9bOCiY5kOgsDg4AAZF6EQxQMineQCulwBkhBbMgAKUAgFEwJGAAB5SlBMCgAOZwAA+cFQLmACHtTQAfGz2QolCoKes+TqoMLWHtXhL5DYrEA

`tsc` produces no output for your code.

**Comment by mawart** [comment]
Hi,

I am sorry, I manually changed the code snippet as it was part of a large fragment, but did not check its correctness. The correct code should be:

```typescript
export type Colors = 0.0 | 1.0 | 2.0;

export function Colors(member: Colors.KeyType): Colors {
    return Colors.ValueFor(member);
}

export module Colors {
    export type KeyType = keyof typeof ValueMap;

    export const ValueMap = {
        Red: { value: 0.0, label: 'Red' },
        Blue: { value: 1.0, label: 'Blue' },
        Green: { value: 2.0, label: 'Green' },
    } as const;

    export const Values: Colors[] = [0.0, 1.0, 2.0];

    export function ValueFor(member: KeyType): Colors {
        return ValueMap[member]?.value;
    }

    export async function LabelFor(
        member: KeyType
    ): Promise<string | undefined> {
        return ValueMap[member]?.label;
    }
}
```
