### ISSUE TITLE
Unexpected behavior when there's try-catch block in async function

### ISSUE THREAD

**Issue by joonseokhu** [swc-project/swc#2248]
**Input code**

```ts
export const foo = async () => {
  try {
    console.log(1)
  } catch (err) {
    console.log(err.message)
  }
}
```

**Expected behavior**
- Should compile successfully but makes TS Error `TS2571: Object is of type 'unknown'.`

**result**
- `Error: Can't resolve 'regenerator-runtime'` if I haven't installed `regenerator-runtime`
- Doesn't make any error if I've installed that.

**Version**
The version of @swc/core: 1.2.85

**Comment by kdy1** [comment]
You have to install `regeneraor-runtime` if you target es5.
Maybe related to https://github.com/swc-project/swc/issues/1461

**Comment by joonseokhu** [comment]
1. I configured target dialect as ES2018 in `tsconfig.json`, and didn't configure `.swcrc` at all. So, any plan to respect `tsconfig.json` by default?
2. It seems that it builds well when I configured target to dialect higher than ES5, however in this case, It should emit a type error nevertheless the build was successful.

**Comment by kdy1** [comment]
1. There's a plan.
2. swc does not check types.
