### ISSUE TITLE
minify throw error since 1.2.85

### ISSUE THREAD

**Issue by SoloJiang** [swc-project/swc#2257]
![image](https://user-images.githubusercontent.com/14757289/133569741-56a4825e-6fa4-4b8e-a0ff-68ee6e9eb389.png)

**Comment by kdy1** [comment]
Please post some input code.

**Comment by SoloJiang** [comment]
You can see it https://github.com/SoloJiang/minify-error

```npm run build``` and start a http-server in the build dir.

**Comment by SoloJiang** [comment]
A simple example: https://github.com/SoloJiang/minify-error
