### ISSUE TITLE
Missing refresh signature for hook calls outside of assignments

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#2261]
**Describe the bug**

If a React hook call isn't assigned but instead used in an expression, then the refresh transformer doesn't seem to recognize it and create a hash.

(This is a valid hook call, and the React Hooks eslint rule doesn't complain)

**Input code**

```js
import { useState } from "react";

export function App() {
	console.log(useState())

	return null;
}
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "transform": {
      "react": {
        "refresh": true,
        "development": true
      }
    }
  }
}

```

**Current behaviour** 

```js
import { useState } from "react";
export function App() {
    console.log(useState());
    return null;
}
_c = App;
var _c;
$RefreshReg$(_c, "App");
```

**Expected behavior**
With the offical `react-refresh/babel` plugin:

```js
var _s = $RefreshSig$();

import { useState } from "react";
export function App() {
  _s();

  console.log(useState());
  return null;
}

_s(App, "VhlnxxH3xh7Qs17KADUJ8wvRSZs=");

_c = App;

var _c;

$RefreshReg$(_c, "App");
```

**Version**
20ce326909670d0e40c9f1bbd804387c2958eae6

**Comment by Austaras** [comment]
The fix is fairly straightforward, but has this ever appeared in real code?

**Comment by mischnic** [comment]
I opened this issue because I wrote exactly such code and it broke HMR. And I think the Webpack plugin (or rather the official React transformer) also handles this correctly.

**Comment by Austaras** [comment]
Well the misalignment of behaviour with official babel plugin is because at that time I'm not quite sure how `Visit` works. I will land a fix soon.
