### ISSUE TITLE
Pass newOptions to plugin invocation

### ISSUE THREAD

**Issue by aaaristo** [swc-project/swc#2267]
**Describe the feature**

In order to implement something like [babel-plugin-codegen](https://github.com/kentcdodds/babel-plugin-codegen) it would be useful to have newOptions passed down to the plugin so that it can have the filename to resolve other modules via require.

**Babel plugin or link to the feature description**
https://github.com/kentcdodds/babel-plugin-codegen
https://github.com/swc-project/swc/blob/4ca85ec79cc24ed11191668501c21626777c0b2a/node-swc/src/index.ts#L126

https://github.com/kentcdodds/babel-plugin-codegen/blob/4ed043c88e7bd54f48bbc06a68664012d52965cc/src/helpers.ts#L43

**Comment by kwonoj** [comment]
Closing as we won't revisit legacy plugin interface. I believe new wasm plugin have proper metadatacontext can be used for these kind of purpose.
