### ISSUE TITLE
Segmentation fault on require("@swc/core") in a Node.js worker thread

### ISSUE THREAD

**Issue by andersk** [swc-project/swc#2276]
Running `require("@swc/core")` inside a Node.js [worker thread](https://nodejs.org/api/worker_threads.html) causes a segfault. (This causes problems with terser-webpack-plugin’s new [`swcMinify`](https://github.com/webpack-contrib/terser-webpack-plugin#swc) function.)

```js
// test.js
const { Worker } = require("worker_threads");
new Worker('require("@swc/core")', { eval: true });
```

```console
$ node test.js
Segmentation fault (core dumped)
```

I’m running Node 14.17.6 on Linux x86-64 (NixOS 21.11). In case this is system-dependent, here’s a Dockerfile that should reproduce reliably:

```dockerfile
# Dockerfile
FROM node:14.17.6
WORKDIR /tmp
RUN npm i @swc/core@1.2.88
RUN node -e 'new worker_threads.Worker(`require("@swc/core")`, { eval: true })'
```

```console
$ docker build .
Sending build context to Docker daemon  57.85MB
Step 1/4 : FROM node:14.17.6
 ---> 9dc0768a6295
Step 2/4 : WORKDIR /tmp
 ---> Using cache
 ---> ade3fef59802
Step 3/4 : RUN npm i @swc/core@1.2.88
 ---> Using cache
 ---> e1b2d22eae67
Step 4/4 : RUN node -e 'new worker_threads.Worker(`require("@swc/core")`, { eval: true })'
 ---> Running in 25299ad85030
Segmentation fault (core dumped)
The command '/bin/sh -c node -e 'new worker_threads.Worker(`require("@swc/core")`, { eval: true })'' returned a non-zero code: 139
```

**Comment by kdy1** [comment]
Native node bindings are expected to

 - Call async operations from js thread

or 

 - Call synchronous function from worker thread

It's the limitation of node js itself.

cc @Brooooooklyn 
Am I right?

**Comment by andersk** [comment]
I don’t know of any such limitation. Perhaps you’re confusing [worker threads](https://nodejs.org/api/worker_threads.html) (JS threads created using the `worker_threads` API) with threads in the [worker pool](https://nodejs.org/api/n-api.html#n_api_napi_create_async_work) (native threads created from addons to perform synchronous operations that are exposed to JS via a custom asynchronous JS API)?

In worker threads, Node.js addons should be able to perform synchronous and asynchronous operations, provided they follow certain rules about [thread safety](https://nodejs.github.io/node-addon-examples/special-topics/thread-safe-functions) and [context awareness](https://nodejs.github.io/node-addon-examples/special-topics/context-awareness/).

**Comment by Brooooooklyn** [comment]
> In worker threads, Node.js addons should be able to perform synchronous and asynchronous operations, provided they follow certain rules about thread safety and context awareness.

Yes. I will dig into this issue today.

**Comment by Brooooooklyn** [comment]
This issue only occurs on Linux GNU platform with `napi-rs`. I've tried Linux musl / macOS / Windows, all these platform is fine.
And I've also tried this example https://github.com/nodejs/node-addon-examples/tree/main/async_pi_estimate/node-addon-api  on Linux GNU, also works fine.

I need more time to dig into it.

**Comment by kdy1** [comment]
Does it happen only on centos?
Maybe it's a bug of glibc in centos 7

**Comment by andersk** [comment]
@kdy1 I originally found this on NixOS; the `node:14.17.6` Docker image is based on Debian 9, and it also reproduces with `node:16.13.1` which is based on Debian 10. Since you asked, I was also able to reproduce on CentOS. As far as I can tell, all glibc platforms are impacted. (Did you find a glibc platform that isn’t?)

**Comment by Brooooooklyn** [comment]
Maybe a valid workaround https://github.com/rust-lang/rust/issues/91979#issuecomment-995986043

**Comment by Jackson-p** [comment]
+1,i meet this problem too,it also caused by terser-webpack-plugin’s new swcMinify function.

**Comment by Brooooooklyn** [comment]
@Jackson-p What are your system and `Glibc` versions

**Comment by Jackson-p** [comment]
> 

CentOS Linux release 7.4.1708(Core)

ldd(GNU libc) 2.17

**Comment by Jackson-p** [comment]
> CentOS Linux release 7.4.1708(Core)
> 
> ldd(GNU libc) 2.17

CentOS Linux release 7.4.1708(Core)

ldd(GNU libc) 2.17

> @Jackson-p What are your system and `Glibc` versions

CentOS Linux release 7.4.1708(Core)

ldd(GNU libc) 2.17

**Comment by Jackson-p** [comment]
> @Jackson-p What are your system and `Glibc` versions

CentOS Linux release 7.4.1708(Core)

ldd(GNU libc) 2.17

@Brooooooklyn

**Comment by Brooooooklyn** [comment]
I've confirmed, this issue should have been fixed in https://github.com/swc-project/swc/pull/3314

```
docker run -w /root --rm -it node:14.17.6 sh -c "npm i @swc/core && node -e 'new worker_threads.Worker(\`console.log(require(\"@swc/core\"))\`, { eval: true })'"
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-win32-ia32-msvc@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-win32-ia32-msvc@1.2.133: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-win32-x64-msvc@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-win32-x64-msvc@1.2.133: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-arm-gnueabihf@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-arm-gnueabihf@1.2.133: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-arm64-musl@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-arm64-musl@1.2.133: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-android-arm64@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-android-arm64@1.2.133: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-darwin-arm64@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-darwin-arm64@1.2.133: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-arm64-gnu@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-arm64-gnu@1.2.133: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-win32-arm64-msvc@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-win32-arm64-msvc@1.2.133: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-darwin-x64@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-darwin-x64@1.2.133: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-android-arm-eabi@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-android-arm-eabi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-android-arm-eabi@1.2.133: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-freebsd-x64@1.2.133 (node_modules/@swc/core/node_modules/@swc/core-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-freebsd-x64@1.2.133: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ @swc/core@1.2.133
added 3 packages from 1 contributor and audited 14 packages in 68.157s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

{
  version: '1.2.133',
  plugins: [Function: plugins],
  Compiler: [class Compiler],
  parse: [Function: parse],
  parseSync: [Function: parseSync],
  parseFile: [Function: parseFile],
  parseFileSync: [Function: parseFileSync],
  print: [Function: print],
  printSync: [Function: printSync],
  transform: [Function: transform],
  transformSync: [Function: transformSync],
  transformFile: [Function: transformFile],
  transformFileSync: [Function: transformFileSync],
  bundle: [Function: bundle],
  minify: [Function: minify],
  minifySync: [Function: minifySync],
  DEFAULT_EXTENSIONS: [
    '.js',  '.jsx',
    '.es6', '.es',
    '.mjs', '.ts',
    '.tsx'
  ]
}
```

**Comment by kdy1** [comment]
@Brooooooklyn Do you mean this issue can be closed?

**Comment by Brooooooklyn** [comment]
> Do you mean this issue can be closed?

Yes

**Comment by kdy1** [comment]
Thank you!

**Comment by devongovett** [comment]
@Brooooooklyn could you explain how this works and how it fixes the Rust issue? Does this mean it doesn't depend on glibc somehow?

**Comment by Brooooooklyn** [comment]
@devongovett It is a little complex, I'll write an article to talk about this.

In a nutshell, `__cxa_thread_atexit_impl` is introduced in [std/src/sys/unix/thread_local_dtor.rs#L7-L13](https://github.com/rust-lang/rust/blob/86b1581ea0e0e47196e1ea70b2d980b3eee72623/library/std/src/sys/unix/thread_local_dtor.rs#L7-L13)

But it's weakly linked since `Rust std` has a fallback implementation: [std/src/sys/unix/thread_local_dtor.rs#L27](https://github.com/rust-lang/rust/blob/86b1581ea0e0e47196e1ea70b2d980b3eee72623/library/std/src/sys/unix/thread_local_dtor.rs#L27)

If a library is built with target < `GLIBC_2.18`, the `__cxa_thread_atexit_impl` symbol will not be linked.

**Comment by devongovett** [comment]
@Brooooooklyn ah interesting. So if I understand correctly, another solution would be to build on a system (or docker image) with an older glibc version? What kind of magic is zig doing here?

> I'll write an article to talk about this.

That would be great!

**Comment by Brooooooklyn** [comment]
> So if I understand correctly, another solution would be to build on a system (or docker image) with an older glibc version?

Yes, we can only compile our codes on an older glibc version system without `zig`.

If we are using `zig` as the program linker, we can target our binary to whatever glibc versions, like `x86_64-linux-gnu.2.12`.

https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html
https://github.com/napi-rs/napi-rs/blob/main/cli/src/build.ts#L279
