### ISSUE TITLE
line and file directives/macros

### ISSUE THREAD

**Issue by rrichardson** [swc-project/swc#2289]
**Describe the feature**

Special keywords for supplying the filename and line number that are replaced by the appropriate value during the compilation step.  
Similar to the `line` and `file` macros in Rust. 

e.g.
``` 
__file :  Would be replaced by the filename in which this directive exists. 
__line : Would be replaced by the line number on which this directive exists. 
```

**Additional context**

The lack of line/file annotations has long been a thorn in the side of JS devs. Since SWC is a compiler, it should be fairly trivial to add these keywords and make them work.  This would eliminate the need for an additional preprocessor that many shops employ, simply to get appropriate metadata into their logs and traces.

**Comment by kdy1** [comment]
It's not in scope of swc.
First of all, it's not a standard.
