### ISSUE TITLE
ES private field check

### ISSUE THREAD

**Issue by Danue1** [swc-project/swc#2311]
**Describe the bug**
ES private field check failed.

**Input code**
```
class Foo {
  static foo(foo) {
    return #foo in foo;
  }

  #foo = 'foo';
}
```

**Config**
default

**Expected behavior**
When lhs of "in" operator is a private identifier.

If there is a corresponding private field in the class definition, there is no error and it should be transpiled as it is.
If the corresponding private field does not exist in the class definition, an error should be raised that the corresponding private field in the class definition must exist.

**Version**
The version of @swc/core: 1.2.91

**Comment by Danue1** [comment]
I know the maintainers are busy.
If I get a guide on how to approach it, I'll try PR. Is it possible?
Although I am making a small financial support to swc, I also wanted to make a technical contribution.

**Comment by kdy1** [comment]
This is already implemented by https://github.com/swc-project/swc/pull/2079, but not published yet.

**Comment by Danue1** [comment]
good.
It's already been done...
I respect that speed.

**Comment by Danue1** [comment]
It's almost resolved, so I'll close the issue now.
