### ISSUE TITLE
`drop_console ` option is invalid

### ISSUE THREAD

**Issue by xyyjk** [swc-project/swc#2321]
**Describe the bug**
The last one was not discarded

**Input code**
```js
console.log('discarded');
console.log('Not discarded');
```

**Config**

```json
{
  "jsc": {
    "minify": {
      "compress": {
        "drop_console": true
      }
    }
  }
}
```

**Version**
The version of @swc/core: 1.2.92

![image](https://user-images.githubusercontent.com/2508421/135389412-b7c9aaa1-3395-49ff-b14e-88a27a7d6700.png)

https://swc.rs/repl#%7B%22rawCode%22%3A%22console.log('discarded')%3B%5Cnconsole.log('Not%20discarded')%3B%5Cn%22%2C%22rawConfig%22%3A%22%7B%5Cn%20%20%5C%22jsc%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22minify%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%5C%22compress%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%5C%22drop_console%5C%22%3A%20true%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D

**Comment by schacker** [comment]
I am going to try to solve this bug.

**Comment by schacker** [comment]
hi @kdy1 :
I encountered a strange problem. I copied a copy of `terser/compress/drop-console/drop_console_2` and executed cargo test -p swc_ecma_minifier --test compress again, but it failed.
```
failures:

---- fixture_tests__terser__compress__drop_console__issue_2321__input_js stdout ----
---- Config -----
{
    "drop_console": true
}

---- Input -----
console.log("foo");
console.log.apply(console, arguments);

---- Ourput -----
"foo";
console.log.apply(console, arguments);

---- Expected -----
void 0;
void 0;
```
----------------------------------------
So the question is: how did terser/compress/drop-console/drop_console_2 succeed?
Do I need to do other actions? 😅 Thanks~

**Comment by kdy1** [comment]
I'm not sure.
You can run it with `RUST_LOG=debug cargo test --all-features` to see what's going on.

**Comment by schacker** [comment]
## Structure as shown below:
![image](https://user-images.githubusercontent.com/5550163/141923322-2504b1a7-2c4b-494c-a502-3ffdcdf904ac.png)

The two folders are exactly the same, but no matter how I modify the contents of `drop_console_2`, it will succeed. 😂
So I can't see its failure message. But if I modify issue_2321, the corresponding failure message will appear.

But after I execute `RUST_LOG=debug cargo test -p swc_ecma_minifier --test compress`, I only get the following information
```js
failures:

---- fixture_tests__terser__compress__drop_console__issue_2321__input_js stdout ----
---- Config -----
{
    "drop_console": true
}

---- Input -----
console.log("foo");
console.log.apply(console, arguments);

   INFO global_defs took 1.199µs
    at crates/swc_ecma_minifier/src/lib.rs:76

   INFO precompress took 10.946µs
    at crates/swc_ecma_minifier/src/lib.rs:83

   INFO Running minifier in the normal mode
    at crates/swc_ecma_minifier/src/metadata/mod.rs:182

  DEBUG Scope analysis took 48.497µs
    at crates/swc_ecma_minifier/src/analyzer/mod.rs:53

  DEBUG Scope analysis took 39.913µs
    at crates/swc_ecma_minifier/src/analyzer/mod.rs:53

   INFO compress: Running expression simplifier (pass = 0)
    at crates/swc_ecma_minifier/src/compress/mod.rs:273

   INFO compress: expr_simplifier took 18.426µs (pass = 0)
    at crates/swc_ecma_minifier/src/compress/mod.rs:297

   INFO compress/pure: Running pure optimizer (pass = 0)
    at crates/swc_ecma_minifier/src/compress/mod.rs:318

   INFO compress/pure: Pure optimizer took 259.558µs (pass = 0)
    at crates/swc_ecma_minifier/src/compress/mod.rs:332

   INFO compress: Running optimizer (pass = 0)
    at crates/swc_ecma_minifier/src/compress/mod.rs:348

   INFO compress: Optimizer took 64.837µs (pass = 0)
    at crates/swc_ecma_minifier/src/compress/mod.rs:371

   INFO compressor took 676.448µs
    at crates/swc_ecma_minifier/src/lib.rs:122

   INFO postcompressor took 4.315µs
    at crates/swc_ecma_minifier/src/lib.rs:129

   INFO optimize(/Users/huangwei/opensource/swc/crates/swc_ecma_minifier/tests/terser/compress/drop-console/issue_2321/input.js) took 854.099µs
    at crates/swc_ecma_minifier/tests/compress.rs:205

   INFO process(/Users/huangwei/opensource/swc/crates/swc_ecma_minifier/tests/terser/compress/drop-console/issue_2321/input.js) took 1.296521ms
    at crates/swc_ecma_minifier/tests/compress.rs:220

---- Ourput -----
"foo";
console.log.apply(console, arguments);

---- Expected -----
void 0;
void 0;

/Users/huangwei/opensource/swc/crates/swc_ecma_minifier/tests/terser/compress/drop-console/issue_2321/input.js
thread 'fixture_tests__terser__compress__drop_console__issue_2321__input_js' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<"foo";
<console.log.apply(console, arguments);
>void 0;
>void 0;
```

**Comment by schacker** [comment]
I modified part of the code to solve the invalid situation of drop_console, but the result is not `void 0;`, but delete the console expression.

input:
```js
console.log('discarded');
console.log('Not discarded');
```
output:
```js
```
Is this correct? Thanks.

**Comment by kdy1** [comment]
It depends on the option. If `unused` is true, the empty output is correct.
Otherwise, I think it's better to follow the behavior of terser.

**Comment by schacker** [comment]
Thanks for the answer! I re-verified the effect of `terser` and `SWC` for the `drop_console` option. All the `console.*` in `terser` are removed, and there is no `void 0`. So I understand that the `tests` of `drop_console` in `SWC` is invalid or ignored? I am confused, but I see that the logs of `drop_console_1` and `drop_console_2` in the test show as `ok`, so I don't understand why?

BTW, currently in `SWC`, for example, `console.log.apply(console, arguments)` is reserved, but is removed in `terser`, so the current single test about drop_console, I guess it is invalid Or ignored

Regarding the single test of `drop_console`, it needs to be verified

**Comment by kdy1** [comment]
> So I understand that the tests of drop_console in SWC is invalid or ignored?

No, actually there's `output.terser.js`, which is the output from terser.

I think you are confused because `defaults` is true for terser, but it's false for tests.

**Comment by schacker** [comment]
> > So I understand that the tests of drop_console in SWC is invalid or ignored?
> 
> No, actually there's `output.terser.js`, which is the output from terser.
> 
> I think you are confused because `defaults` is true for terser, but it's false for tests. (I mean tests ported from terser)
./src/index.ts:
```ts
console.log('discarded');
console.log('Not discarded');
console.log.apply(console, ["something"]);
```
I use `terser ./src/index.ts -c drop_console -o ./terser.out.js` command to parse the file, there is no `void 0` in `terser.out.js`, so why is it in `SWC` There is `void 0` in `output.terser.js`?

**Comment by kdy1** [comment]
Actually, terser have a flag named `defaults`. It's true for terser CLI / javascript api but it's false by default for tests.

**Comment by schacker** [comment]
> Actually, terser have a flag named `defaults`. It's true for terser CLI / javascript api but it's false by default for tests.

get it! thanks.

**Comment by schacker** [comment]
> Actually, terser have a flag named `defaults`. It's true for terser CLI / javascript api but it's false by default for tests.

I just verified that the option `defaults` is in `SWC`. True or false has the same effect. Is it still not supported?

**Comment by schacker** [comment]
> I am confused, but I see that the logs of `drop_console_1` and `drop_console_2` in the test show as `ok`

🤣  I'm really sorry, I found that `drop_console/drop_console_2/input.js` was ignored in `tests/ignore.txt`

**Comment by kdy1** [comment]
Oh, I forgot it too.

**Comment by schacker** [comment]
hi @kdy1 
My plan is as follows:

1. Now in the judgement that it is `console.*` call expression, only `log` and `info` are filtered. The effect of `terser` is that `console.*` will be removed. Of course, similar methods need to be implemented in the future. `Terser`'s `pure_funcs` option to filter the specified functions, not yet completed
2. The parameters in the call expression are also collected in the logic, but I don't understand why? If deleted, there should be no need to collect or return `void 0`
3. The configuration for `drop_console_2` in the single test should be `defaults: true`, even though `drop_console_2` is currently ignored
---------
Please help to see if there are any questions and suggestions ?😊

**Comment by kdy1** [comment]
> The parameters in the call expression are also collected in the logic, but I don't understand why? If 

Because arguments can have side effects.


>  configuration for drop_console_2 in the single test should be defaults: false

This is always handled by the test suit of swc minifier. `defaults` flag is also false by default for minifier tests of swc.

**Comment by schacker** [comment]
Hi @kdy1 
Where are the side effects collected in the `drop_console` stage handled? I did not find a corresponding place.

Do you have any ideas you can provide? 😊

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/4075ff8029b4d0a71819145dd53de061c47d9b74/crates/swc_ecma_minifier/src/compress/pure/misc.rs#L140 

and

https://github.com/swc-project/swc/blob/4075ff8029b4d0a71819145dd53de061c47d9b74/crates/swc_ecma_minifier/src/compress/optimize/mod.rs#L680

All operations will be moved to `pure` in future, though.

**Comment by kdy1** [comment]
@schacker  Oh, sorry. I misread your comment. 
Arguments are preserved by https://github.com/swc-project/swc/blob/e19fe7d33b2a18c1b068c2f808f3ea72f1ccff15/crates/swc_ecma_minifier/src/compress/drop_console.rs#L76-L79
