### ISSUE TITLE
Abort found

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#233]
The syntax here is a bit wonky, but it is valid. 

I tried this: 

```js
const foo = () => ({ x, ...y }) => y
```

I expected to see this happen: 

This is what babel outputs (I left out the helpers that it generated)

```js
var foo = function foo() {
  return function (_ref) {
    var x = _ref.x,
        y = _objectWithoutProperties(_ref, ["x"]);

    return y;
  };
};
```

Instead, this happened:

```
fatal runtime error: failed to initiate panic, error 5
[1]    34942 abort      npx swc test.js
```

I'm using CLI 0.1.12, @swc/core "1.0.19"

**Comment by kdy1** [comment]
Fixed with `@swc/core` `1.0.20`
