### ISSUE TITLE
"Module parse failed: Duplicate export 'ref" when exporting multiple destructured assignments 

### ISSUE THREAD

**Issue by tannera** [swc-project/swc#2336]
**Describe the bug**

`Module parse failed: Duplicate export 'ref'` when exporting multiple destructured assignments. 

**Input code**
```ts
export const [useQuery, { query }] = createQuery();
export const [useMutation, { mutate }] = createMutation();
```

**Output code**
```ts
// ... helpers
var ref = _slicedToArray(createQuery(), 2);
var useQuery = ref[0], ref1 = ref[1], query = ref1.query;
export { ref1 as ref }; // <- FIRST REF
var ref2 = _slicedToArray(createMutation(), 2);
var useMutation = ref2[0], ref3 = ref2[1], mutate = ref3.mutate;
export { ref3 as ref }; // <- SECOND REF
```

**Config**

```json
{
  "test": ".tsx?$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": true
    },
    "target": "es5"
  }
}
```

**Expected behavior**
The compiler shouldn't output duplicate ref exports

**Version**
swc/core@1.2.92 with swc-loader@0.1.15 and webpack@4.46.0

Repl link to reproduce: https://swc.rs/repl/#%7B%22rawCode%22%3A%22export%20const%20%5BuseQuery%2C%20%7B%20query%20%7D%5D%20%3D%20createQuery()%3B%5Cnexport%20const%20%5BuseMutation%2C%20%7B%20mutate%20%7D%5D%20%3D%20createMutation()%3B%22%2C%22rawConfig%22%3A%22%7B%5Cn%20%20%5C%22test%5C%22%3A%20%5C%22.tsx%3F%24%5C%22%2C%5Cn%20%20%5C%22jsc%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22parser%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%5C%22syntax%5C%22%3A%20%5C%22typescript%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22tsx%5C%22%3A%20true%2C%5Cn%20%20%20%20%20%20%5C%22decorators%5C%22%3A%20false%2C%5Cn%20%20%20%20%20%20%5C%22dynamicImport%5C%22%3A%20true%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%5C%22target%5C%22%3A%20%5C%22es5%5C%22%5Cn%20%20%7D%5Cn%7D%22%7D

**Comment by kwonoj** [comment]
This seems to be fixed with latest version: 

https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlGILi1ODSxNLarUUahWKAQxFGpjFWwVkotSE0sgMhqa1rxcqeiafEtLEksy8%2FNA%2BnJB7FRkjTBZoF4A94yh4m8AAAA%3D&config=H4sIAAAAAAAAAyWLwQmAMBAEe9m3Xz%2FpwSKO5JRIMOH2AorYuxF%2Fs7PMjZ0R4UYTo9pHvA6XEwF%2BNWW03BwTnEO5dZ2QNFYTr0aEVQr1GbfYpj4i5YyxM5eaetG%2FeV7Bn%2F9nZwAAAA%3D%3D

@tannera would you try latest version to confirm?
