### ISSUE TITLE
Enhancement: SWC_DEBUG environment variable

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#234]
Currently, if the Rust swc library aborts in a release build, there is no information given to the user about what caused it. I would like to propose that an environment variable `SWC_DEBUG` set to `1`, or some other sentinel string, would cause swc to print out the name of the file that it is about to try to transform. Currently, when you want to track down the source of an abort, you need to modify the source to include this extra logging. It would be very convenient if this information was presented to the user without too much extra effort.

**Comment by natemara** [comment]
Or the `env_logger` crate could be used to control this behavior as well

**Comment by kdy1** [comment]
I updated node-swc to emit the file name when `SWC_DEBUG` is 1 or true.
