### ISSUE TITLE
Source maps aren't loaded correctly in Chrome Node DevTools

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#2362]
I ran `node --inspect-brk -r @swc/register some_script.ts` and then opened `chrome://inspect` - DevTools for Node. Source maps weren't loaded properly (was showing a transpiled JS content under a TS filename). I checked with babel and it works fine. There seems to be a difference between babel and swc that makes it break -  I used debugger to dynamically modify swc source maps and managed to see it working.

It looks like embedding full filename path in sources doesn't work in Chrome DevTools for Node. What babel does, and seems to make it work - is encodes directory path in sourceRoot and just filename in sources.

This works (babel):
```
{
  "version": 3,
  "sourceRoot": "/Users/pbadenski/workspace/project/",
  "sources": [
    "test.ts"
  ],
  ...
}
```

This doesn't (swc):
```
{
  "version": 3,
  "sources": [
    "/Users/pbadenski/workspace/project/test.ts"
  ],
  ...
}
```

**Comment by kdy1** [comment]
Can you try https://swc.rs/docs/configuring-swc/#inlinesourcescontent ?

**Comment by pbadenski** [comment]
I tried, doesn't help unfortunately.

**Comment by kwonoj** [comment]
Do we know only chrome devtools affected by this or other tools are also broken? I recall in few tools (like jest?) saw correctly mapped source locations so curious if this is tool specifics.

Per spec,

> If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap

I _guess_ having each sources having full path without sourceroot would behave same. Maybe lacks of `sourceRoot` property relates with this.

**Comment by pbadenski** [comment]
It seems to a bit of hit and miss. WebStorm works for some cases, but not for all - I haven't looked at it closely yet.

**Comment by kwonoj** [comment]
Curiousity q: if you manually add `sourceRoot: ""` in existing sourcemap, does it makes any diff?

**Comment by egilsster** [comment]
I have a similar report where source maps were working when running unit tests with VSCode but _not_ WebStorm. I haven't had time to investigate that issue in particular but we pinned `swc/core` to `1.2.100` because the source maps are broken in WebStorm in `1.2.101`.

The swc deps it works with:
```
"@swc-node/jest": "1.4.1",
"@swc/core": "1.2.100",
"swc-loader": "0.1.15",
```

**Comment by kdy1** [comment]
@egilsster Can you try `inlineSourcesContent: false`?

Judging from https://github.com/swc-project/swc/milestone/202?closed=1, and there's https://github.com/swc-project/swc/pull/2471 which changes the default behavior.

**Comment by kwonoj** [comment]
It looks like there are multiple different root (from `@swc/register` to something else). Anyone experiencing this issue mind share exact repro steps for each? It's hard to do guesswork with currently known information.

**Comment by pbadenski** [comment]
Just FYI looks, I'm extremely happy. I haven't had any problems since recently - I will keep this thread updated. Thank you!! :star:

**Comment by kdy1** [comment]
Can you try the latest version of `@swc/core`? (`v1.2.155`)

Patches in https://github.com/swc-project/swc/pull/4007 are very likely to fix this issue.

**Comment by kdy1** [comment]
Can anyone make an executable repro case?
node.js seems to consume sourcemap of swc without any problem.

**Comment by kdy1** [comment]
Can you try the latest version? (`v1.2.156`)
There was a bug fix for a module that only contains `export * from './foo'` and such module is super common, so I think it can be the cause of this.

**Comment by daviduzumeri** [comment]
If it helps, I'm still having the same issue and was able to create a quick repo to reproduce it: https://github.com/daviduzumeri/swctest

Any help would be appreciated, as we're pretty much back to `console.log` debugging over here.

**Comment by kdy1** [comment]
I found that `sourcemap` crate does not support `sourceRoot`.
https://docs.rs/sourcemap/6.1.0/sourcemap/struct.SourceMapBuilder.html

**Comment by kdy1** [comment]
Ref: https://github.com/getsentry/rust-sourcemap/issues/50
