### ISSUE TITLE
Why is the testsuite in `swc-example` not part of this repository?

### ISSUE THREAD

**Issue by thomaseizinger** [swc-project/swc#238]
I've been following your repository for a while because I find it is super interesting work!

I noticed that https://github.com/kdy1/swc-example contains a many tests cases that mostly come from issues that were reported by users. I was wondering why those are not part of this repository? It shouldn't be too hard to run them as part of the CI process on travis.

It seems like they are very valuable in terms of preventing regressions.

**Comment by kdy1** [comment]
Those tests are added inlined to this repository. `rg issue_` from `ecmascript/transforms` shows them.
Those stuffs cannot live at this repository because `.swcrc` is currently handled by node-swc.

Even though, I'll consider moving tests from swc-example to node-swc

**Comment by thomaseizinger** [comment]
> Those stuffs cannot live at this repository because `.swcrc` is currently handled by node-swc.

Ah I see, makes total sense!

Does this mean the tests would need to be translated so that whatever the config in `.swcrc` is would need to be passed as a config to `swc`?

This would add the assumption that no bug is introduced when the config is translated from `.swcrc` to the rust config. However, there might still be value in having all the tests next to the actual code that does all the processing (i.e. this repo)

**Comment by kdy1** [comment]
All of tests in swc-examples live in this repository in an inlined form like 

https://github.com/swc-project/swc/blob/4fddea0bbd750fdc6658d3e092366b3fecf3c899/ecmascript/transforms/src/compat/es2015/parameters/tests.rs#L13-L28
https://github.com/swc-project/swc/blob/4fddea0bbd750fdc6658d3e092366b3fecf3c899/ecmascript/transforms/src/compat/es2015/parameters/tests.rs#L30-L50

**Comment by thomaseizinger** [comment]
Ah cool! Thanks for the hint :)
