### ISSUE TITLE
Possibility to include some node_modules

### ISSUE THREAD

**Issue by billouboq** [swc-project/swc#2387]
Hi, 

I would like to know if it was possible to include "some" node_modules with swc ?

I'm working on a monorepo with different packages and compiling each of them is time consuming and has a lot of drawbacks. I would like to consume them directly from source in my api and compile them on the fly. Is this possible ?

Something like exclude all node_modules except this one and this one

**Comment by kdy1** [comment]
Of course, you can use `@swc/regsiter` with options. I don't remember rhe exact option, but I copied the option handling code from `@babel/cli`, so API would be similar.

Relevant code is at
https://github.com/swc-project/register/blob/377bad1f81cc590b95cb207c0524e95718b4e065/src/node.ts#L122-L142

**Comment by billouboq** [comment]
Thank you very much ! Will test it 🎉

**Comment by billouboq** [comment]
I don't know if it's possible to do it in Swc, in babel there is some upward config to allow workspace to work :

https://github.com/babel/babel/issues/8309#issuecomment-464110015

Right now I have to use babel with this register options :

```ts
// const register = require('@swc/register');
const register = require('@babel/register');
const path = require('path');

register({
	rootMode: 'upward',
	extensions: ['.js', '.ts', '.jsx', '.tsx'],
	// Array of ignore conditions, either a regex or a function. (Optional)
	// File paths that match any condition are not compiled.
	ignore: [
		// The file's path is also passed to any ignore functions. It will
		// **not** be compiled if `true` is returned.
		(filepath) => {
			return (
				filepath.includes('node_modules/') && !filepath.includes('@beedeez/')
			);
		},
	],
});
```

With this .babelrc at the package level :

```json
{
	"extends": "../../babel.config.js"
}
```

And this babel.config.js at workspace root :

```js
module.exports = (api) => {
	api.cache(true);

	return {
		presets: [
			[
				'@babel/preset-env',
				{
					targets: {
						node: 12,
					},
				},
			],
			'@babel/preset-react',
			'@babel/preset-typescript',
		],
		plugins: [],
	};
};

```

**Comment by xiaoyu-tamu** [comment]
Hi, @billouboq. Did you found a solution?
