### ISSUE TITLE
Rest spread in constructor causes abort

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#239]
I tried this: 

```
class Foo {
  constructor ({ ...bar }) {}
}
```

I expected to see this happen: 

The constructor would be compiled like a normal function with rest params

Instead, this happened:

```
fatal runtime error: failed to initiate panic, error 5
[1]    69697 abort      npx swc test.js
```

I'm using 1.0.20

**Comment by kdy1** [comment]
Fixed with `@swc/core@1.0.21`
