### ISSUE TITLE
exportDefaultFrom not supported for typescript parser

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#240]
I tried this: 

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "exportDefaultFrom": true
    }
  },
  "module": { "type": "commonjs" }
}
```

I expected to see this happen: 

`export default from 'foo'` should parse correctly.

Instead, this happened: 

```
Error: failed to parse config file: unknown field `exportDefaultFrom`, expected one of `tsx`, `decorators`, `dynamicImport` at line 7 column 3
```

I'm using 1.0.20

**Comment by kdy1** [comment]
@natemara Does typescript spec supports this syntax?

**Comment by natemara** [comment]
Looks like it actually does not by default. Babel must support it behind some experimental flags, because it was definitely being used somewhere in our codebase. Up to you if you want to add support for it here, I can also change our code.

**Comment by kdy1** [comment]
@natemara Sorry. I want to keep typescript parser follow typescript spec. I'll not support this feature. Closing as wontfix.
