### ISSUE TITLE
Babel-plugin-import support 

### ISSUE THREAD

**Issue by hannadrehman** [swc-project/swc#2404]
**Describe the feature**

we are using [Antd](https://ant.design/docs/react/introduce) in our major projects and one of the requirement for us is to use `babel-plugin-import` which helps in tree shaking this huge library.   this is the only reason why we cant migrate to swc right now. i checked [comparison with babel ](https://swc.rs/docs/comparison-babel) page to find all the plugins that we use and didnt find any support for the same

**Babel plugin or link to the feature description**
link to [babel-plugin-import](https://github.com/ant-design/babel-plugin-import#readme)

**Comment by tunesmith** [comment]
It appears this is also mentioned in the recommended config for minimizing bundle size when using MUI: 
https://mui.com/guides/minimizing-bundle-size/#option-2

**Comment by kwonoj** [comment]
Actually duplicated discussion here https://github.com/swc-project/swc/discussions/3042

I expect we'll have (experimental) plugin support soon, which'll allow to write plugins like these without patching core support.

**Comment by kwonoj** [comment]
It looks like I didn't realize 3042 is dupe when it's filed and then all discussion occured in there. For the purpose of consolidating discussion, let me close this issue and feel free to discuss over #3042 as needed. But I expect this need to be resolved via plugins.
