### ISSUE TITLE
TypeScript pass strips import used for JSX

### ISSUE THREAD

**Issue by devongovett** [swc-project/swc#2418]
**Describe the bug**

When compiling TypeScript, SWC strips unused (presumably type-only) imports. However, it has a [hard-coded exception](https://github.com/swc-project/swc/blob/master/ecmascript/transforms/typescript/src/strip.rs#L1455-L1457) for "react". However, this doesn't work when the JSX `pragma` or `import_source` is set to a different value, e.g. for Preact. In this case, it gets stripped.

**Input code**

```jsx
import {h} from "preact";

module.exports = <div></div>;
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "pragma": "h"
      }
    }
  }
}
```

**Expected behavior**

The import of `h` should be preserved. It seems this broke when the order of passes was changed. Perhaps the TypeScript transform should be passed the pragma rather than using a hard coded check for "react"? We tried changing the pass order in Parcel so React runs first and then TypeScript, but that breaks TS enums... See https://github.com/parcel-bundler/parcel/pull/7057

**Version**
The version of @swc/core: ^1.2.95

**Comment by kdy1** [comment]
Yeah, I think I made a mistake, and `typescript::strip` is expected to invoked before `react` pass, but we now need a way to detect import statements that will be injected.

Passing `pragma` will work, but only if ~`typescript::strip` has logic for parsing `@jsxPragma`~.


I'll fix this by making `typescript::strip` used after `react`. It will make binary little bit larger, but it seems like a right way to go.

**Comment by kdy1** [comment]
Oh, I checked it, but it's not possible.
Your idea seems like the right fix.

I'll expose parsing logic for `@jsxPragma` and make typescript pass accept it.
