### ISSUE TITLE
Variable declaration collision with function declaration name in bundler output

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#2434]
**Describe the bug**

The bundler is not taking into account `var` variable declarations and function declarations with the same name in different modules.

**Input code**

```ts
// mod.ts
import * as test from "./mod2";

for (var i = 0; i < 10; i++) {
  var property = "test";
  console.log(property);
}

console.log(test.property(1, 2));
```

```ts
// mod2.ts
export function property(a, b) {
  return a + b;
}
```

**Config**

spack.config.js

```js
module.exports = {
  entry: {
    web: __dirname + "/mod.ts",
  },
  output: {
    path: __dirname + "/lib",
  },
};
```

**Expected behavior**

Maybe something like (I'm guessing):

```js
function property(a, b) {
    return a + b;
}
for(var i = 0; i < 10; i++){
    var property1 = "test";
    console.log(property1);
}
console.log(property(1, 2))
```

**Actual behaviour**

```js
function property(a, b) {
    return a + b;
}
for(var i = 0; i < 10; i++){
    var property = "test";
    console.log(property);
}
console.log(property(1, 2));
```

**Version**

The version of @swc/core: 1.2.95

**Comment by dgreensp** [comment]
While the repro above is now fixed, this bug (as I encountered it) is actually still present as of Deno release 1.16.2 five days ago, and I managed to create a small, self-contained repro.  Could this be added as a test case?  https://github.com/denoland/deno/issues/12436#issuecomment-963523398

**Comment by kdy1** [comment]
@dgreensp Can you file an another issue?

**Comment by dgreensp** [comment]
Will do

**Comment by dgreensp** [comment]
@kdy1 I finally got around to downloading SWC to try to repro it directly rather than via Deno, and it seems to be fixed in SWC.  Awesome.
