### ISSUE TITLE
Parse error when "async" used as a function parameter name

### ISSUE THREAD

**Issue by wbinnssmith** [swc-project/swc#2436]
**Describe the bug**
swc fails to parse code that uses `async` as the name of a parameter, when followed by another parameter of any name. This failure appears unique to a named arrow function expression, and doesn't apply to other named function expressions with the parameter, function declarations with the parameter, or variable declarations with the "async" name. This parses correctly in Node.js as `async` is not a reserved identifier (https://stackoverflow.com/a/45337231).

**Input code**
https://swc.rs/repl#%7B%22rawCode%22%3A%22const%20foo%20%3D%20(async%2C%20bar)%20%3D%3E%20%7B%5Cn%20%20%2F%2F%5Cn%7D%3B%5Cn%22%2C%22rawConfig%22%3A%22%7B%7D%22%7D

``` 
const foo = (async, bar) => {
  //
};
```

Results in the error: `error: Expected ), got ,`. Renaming `async` to e.g. `_async` or other names results in it parsing.

**Expected behavior**
The code parses as valid code.

**Version**
The version of @swc/core: repl, and in Parcel https://github.com/parcel-bundler/parcel/blob/674539e13167275be17620f638ea2ceb98aa0c54/packages/transformers/js/core/Cargo.toml#L11-L14

cc @devongovett @gorakong @AGawrys @mischnic

**Comment by g-plane** [comment]
This has been fixed several versions ago, so this issue can be closed.

**Comment by kdy1** [comment]
Thanks!
