### ISSUE TITLE
Incorrect transform for static private property

### ISSUE THREAD

**Issue by sosukesuzuki** [swc-project/swc#2476]
**Describe the bug**

**Input code**

```js
class  Foo {
  static #_ = (() => { this.bar  ="3"; })();
}

```

**Config**

```json
{"jsc": {"target": "es2015"}}
```

**Actual behavior**

```js
class Foo {
}
var __ = {
    writable: true,
    value: (()=>{
        this.bar = "3";
    })()
};
```

**Expected behavior**

[Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAE0GIHsHQN4ChYQC5iwS2GgGIB9aAXmgAoqBKCgPlWiwAs8IA6AIzACdY5AEQBmIQG5oAX1p1xaKWiA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.15.8&externalPlugins=%40babel%2Fplugin-proposal-class-static-block%407.15.4%2C%40babel%2Fplugin-proposal-class-properties%407.14.5&assumptions=%7B%7D)

```js
class Foo {}

var _ = {
  writable: true,
  value: (() => {
    Foo.bar = "3";
  })()
};
```

**Version**
The version of @swc/core:

**Additional context**

[REPL](https://swc.rs/repl#%7B%22rawCode%22%3A%22class%20%20Foo%20%7B%5Cn%20%20static%20%23_%20%3D%20(()%20%3D%3E%20%7B%20this.bar%20%20%3D%5C%223%5C%22%3B%20%7D)()%3B%5Cn%7D%5Cn%22%2C%22rawConfig%22%3A%22%7B%5C%22jsc%5C%22%3A%20%7B%5C%22target%5C%22%3A%20%5C%22es2015%5C%22%7D%7D%22%7D)

I found  this via working on #2474. Because of this bug, transform in saitc blocks does not work well.

**Comment by kdy1** [comment]
I'll fix it soon
