### ISSUE TITLE
Incorrect transform for static private scope

### ISSUE THREAD

**Issue by sosukesuzuki** [swc-project/swc#2481]
**Describe the bug**

Incorrect transform for static private scope.

**Input code**

```js
class Foo {
    static #prop1 = 42;
    static #prop2 = (() => {
         console.log(this.#prop1);
    })();
}

```

**Config**

```json
{"jsc": {"target": "es2015"}}
```

**Actual behavior**

[REPL](https://swc.rs/repl#%7B%22rawCode%22%3A%22class%20Foo%20%7B%5Cn%20%20%20%20static%20%23prop1%20%3D%2042%3B%5Cn%20%20%20%20static%20%23prop2%20%3D%20(()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20console.log(this.%23prop1)%3B%5Cn%20%20%20%20%7D)()%3B%5Cn%7D%5Cn%22%2C%22rawConfig%22%3A%22%7B%5C%22jsc%5C%22%3A%20%7B%5C%22target%5C%22%3A%20%5C%22es2015%5C%22%7D%7D%22%7D)

```js
class Foo {
}
var _prop1 = {
    writable: true,
    value: 42
};
var _prop2 = {
    writable: true,
    value: (()=>{
        console.log(this.#prop1);
    })()
};

```

**Expected behavior**

(Babel's output)

[Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ0PQgFzNglsNAMQAOATvKQIzQC80ALAEwDc6mOehJFVz9aAAohASnoA-FB0yzg8AHYR4IAKYA6EPADmQ7AAt8EdWUo1R7WQF9RY9ldRA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.15.8&externalPlugins=%40babel%2Fplugin-proposal-class-static-block%407.15.4%2C%40babel%2Fplugin-proposal-class-properties%407.14.5&assumptions=%7B%7D)

```js
function _classStaticPrivateFieldSpecGet(
  receiver,
  classConstructor,
  descriptor
) {
  _classCheckPrivateStaticAccess(receiver, classConstructor);
  _classCheckPrivateStaticFieldDescriptor(descriptor, "get");
  return _classApplyDescriptorGet(receiver, descriptor);
}

function _classCheckPrivateStaticFieldDescriptor(descriptor, action) {
  if (descriptor === undefined) {
    throw new TypeError(
      "attempted to " + action + " private static field before its declaration"
    );
  }
}

function _classCheckPrivateStaticAccess(receiver, classConstructor) {
  if (receiver !== classConstructor) {
    throw new TypeError("Private static access of wrong provenance");
  }
}

function _classApplyDescriptorGet(receiver, descriptor) {
  if (descriptor.get) {
    return descriptor.get.call(receiver);
  }
  return descriptor.value;
}

class Foo {}

var _prop = {
  writable: true,
  value: 42,
};
var _prop2 = {
  writable: true,
  value: (() => {
    console.log(_classStaticPrivateFieldSpecGet(Foo, Foo, _prop));
  })(),
};

```

**Version**
The version of @swc/core:

**Additional context**

I found this via working on #2474

**Comment by kdy1** [comment]
Of course. Thanks!
