### ISSUE TITLE
`let` / `const` binding in different scopes introduces collision when transforming

### ISSUE THREAD

**Issue by g-plane** [swc-project/swc#2493]
**Describe the bug**
Two variables (using `let` or `const` binding) with same name but from different block scopes are transformed with same name, which introduces collision.

**Input code**

```js
let a;
{
  let a;
}
```

**Config**

```json
{
  "jsc": {
    "target": "es5"
  }
}
```

**Expected behavior**

Variables from different block scopes should be named differently.

```js
var a;
{
  var a1;
}
```

**Version**
The version of @swc/core: Used in REPL.

**Additional context**
[REPL](https://swc.rs/repl/#%7B%22rawCode%22%3A%22let%20a%3B%5Cn%7B%5Cn%20%20let%20a%3B%5Cn%7D%22%2C%22rawConfig%22%3A%22%7B%5Cn%20%20%5C%22jsc%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22target%5C%22%3A%20%5C%22es5%5C%22%5Cn%20%20%7D%5Cn%7D%22%7D)

**Comment by kdy1** [comment]
It seems like a regression..
I'm reimplementing the hygiene pass.
