### ISSUE TITLE
Dropped parens break bool casting

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#252]
### swc version
```
$ grep swc package.json
    "@swc/cli": "0.1.12",
    "@swc/core": "1.0.23",
    "swc-loader": "0.1.4",
```

### Input
```js
!!(a && b);
```

### Output
```js
!!a && b;
```

### Problem
If `a` is truthy, the final value of the expression will be `b`, rather than b-cast-to-boolean.

**Comment by Kronuz** [comment]
Could this be related to #255, where it removes the needed parenthesis from the ternary body, when using comma operators?
