### ISSUE TITLE
Broken jsx compilation for vue 2's functional component

### ISSUE THREAD

**Issue by lephuongbg** [swc-project/swc#2536]
**Describe the bug**

In vue functional component, the `h` argument of `render()` got renamed to `h1`, causing the jsx output to be broken, since `h` is now undefined.

**Input code**

```js
    export default {
        functional: true,
        render(h, {data, children}) {
            const noPadding = data.attrs?.['no-padding'] || data.attrs?.['no-padding'] === ''

            return (
                <div class={['f-sheet', noPadding ? 'f-sheet--no-padding' : '', data.class, data.staticClass]}>
                    {children}
                </div>
            )
        },
    }
```

**Config**

```js
{
    jsc: {
        parser: {
            syntax: 'typescript',
            tsx: true,
            dynamicImport: true,
        },
        transform: {react: {pragma: 'h'}},
    },
}
```

**Expected behavior**

The `h` argument should not be renamed.

**Current (broken) output**

```js
{
    functional: true,
    render (h1, { data  }) {  // <-- h becomes h1
        var ref, ref1;
        const fullSolid = ((ref = data.attrs) === null || ref === void 0 ? void 0 : ref['full-solid']) || ((ref1 = data.attrs) === null || ref1 === void 0 ? void 0 : ref1['full-solid']) === '';
        return(/*#__PURE__*/ h("div", { // <-- h here is now undefined
            class: [
                'f-sheet',
                noPadding ? 'f-sheet--no-padding' : '',
                data.class,
                data.staticClass
            ]
        }, children));
    }
}
```

**Version**
The version of @swc/core: 1.2.103

**Additional context**

**Comment by lephuongbg** [comment]
@kdy1 Is there any workaround for this while we're waiting for this to be fixed?

**Comment by Austaras** [comment]
This seems to be fixed in [latest](https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA31QywrCMBC8C%2F7D3FIh1bsYPfgD3sVDSFIbKIkkWxFq%2F93GVq0PnNPuDLMzLACYy8kHgjaFrCtCM51gQFE7RdY7WS1BoTb8JQXjtAlZydFoSZJDlbbSHdvOxhcSlHeR4PxOam3dEQLJMZdEIW7me%2BZ8fuoldsD1%2Bk8VQoCx6eQ9IBiqg0P2ziastD1DVTJG0exZkcfSGGJ8VGaDB53noygsuxzeV7n7hzmSJKu2iTm06%2B%2FAhOb5ih%2BFFl2jD9%2FstbbDh9sbiIvsdpgBAAA%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE7zJrb9uF79BDCFcJLv4hOVBjfPfaISU7MfPmoY6POtiOQqIs69KWKn1hwS6SOvGlwkxsRlUOHgaVZOe6CH3MKuSsDLtRUDaIPvmtLZHLsQir3hWlPfzJMUUxv48VdNRW%2BBQ%2BMW7HtfP6usDzgR%2Fs3ILttAAAAA%3D%3D)?

**Comment by Austaras** [comment]
Also, you are not suppoesd to use swc to transform vue jsx -- swc currently only supports react jsx, and they're incompatible

**Comment by kdy1** [comment]
@Austaras 

> This seems to be fixed in latest?

Seems like a bug of order version I guess? It's v1.2.106

**Comment by Austaras** [comment]
This should be closed anyway

**Comment by kdy1** [comment]
Yeah, I think you are right.
This should be implemented as a plugin instead.

**Comment by lephuongbg** [comment]
> Also, you are not suppoesd to use swc to transform vue jsx -- swc currently only supports react jsx, and they're incompatible

@Austaras Simply setting `transform: {react: {pragma: 'h'}}` should make it compatible. This is also how babel does it. The issue is that swc automatically changes the render function's argument names to not match the pragma, effectively makes the pragma setting useless.

**Comment by kdy1** [comment]
The old behavior of swc is simply a bug and I don't think pragma from config, which is **global** should interfere with local variable (parameter)

**Comment by Austaras** [comment]
> > Also, you are not suppoesd to use swc to transform vue jsx -- swc currently only supports react jsx, and they're incompatible
> 
> @Austaras Simply setting `transform: {react: {pragma: 'h'}}` should make it compatible. This is also how babel does it, and swc before 1.2.103 works well with the config. The issue is that swc since 1.2.103 automatically changes the render function's argument names to not match the pragma, effectively makes the pragma setting useless.

For babel you should use `@vue/babel-plugin-transform-vue-jsx` for vue 2 which would transform
```jsx
<div id="foo">{this.text}</div>
```
to
```js
h(
  'div',
  {
    attrs: {
      id: 'foo',
    },
  },
  [this.text],
)
```
see related package docs for more details
