### ISSUE TITLE
Function hoisting ignored in async function

### ISSUE THREAD

**Issue by PaulBlanche** [swc-project/swc#2556]
For deeply nested async function, hoisting is ignored, and function declared after the return statement are droped.

With this code : 
```js
function requester() {
	return pureRequester
  
    async function pureRequester() {
      	await refreshThenRequest()
        return true;
        
        async function refreshThenRequest() {
        
        }
    }
}
```

and this config : 
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "runtime": "classic",
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment"
       }
    }
  }
}
```
We get this : 
```js
import regeneratorRuntime from "regenerator-runtime";
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _asyncToGenerator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}
function requester() {
    var pureRequester = function pureRequester() {
        return _pureRequester.apply(this, arguments);
    };
    return pureRequester;
    function _pureRequester() {
        _pureRequester = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
            return regeneratorRuntime.wrap(function _callee$(_ctx) {
                while(1)switch(_ctx.prev = _ctx.next){
                    case 0:
                        _ctx.next = 2;
                        return refreshThenRequest();
                    case 2:
                        return _ctx.abrupt("return", true);
                    case 5:
                    case "end":
                        return _ctx.stop();
                }
            }, _callee);
        }));
        return _pureRequester.apply(this, arguments);
    }
}
```
[REPL link](https://swc.rs/repl#%7B%22rawCode%22%3A%22%20%20%5Cn%20%20%20%20async%20function%20pureRequester()%20%7B%5Cn%20%20%20%20%20%20%5Ctawait%20refreshThenRequest()%5Cn%20%20%20%20%20%20%20%20return%20'bar'%3B%5Cn%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20async%20function%20refreshThenRequest()%20%7B%5Cn%20%20%20%20%20%20%20%20%5Ctreturn%20'foo'%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%22%2C%22rawConfig%22%3A%22%7B%5Cn%20%20%5C%22jsc%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22parser%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%5C%22syntax%5C%22%3A%20%5C%22typescript%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22tsx%5C%22%3A%20true%2C%5Cn%20%20%20%20%20%20%5C%22dynamicImport%5C%22%3A%20true%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%5C%22transform%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%5C%22react%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%5C%22runtime%5C%22%3A%20%5C%22classic%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22pragma%5C%22%3A%20%5C%22React.createElement%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22pragmaFrag%5C%22%3A%20%5C%22React.Fragment%5C%22%5Cn%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D)

You can see that the function `refreshThenRequest` is called in `_pureRequester`, but the definition of this function has been droped.

This seems to only happen in the context of async function. If we change to sync functions, the declaration of `refreshThenRequest` is preserved.

**Comment by dlindenkreuz** [comment]
Workaround: if possible, use a compilation target like `es2017` that does not transpile async functions.

**Comment by kwonoj** [comment]
Digging bit, this is due to we mark completion as soon as hit returnstmt (https://github.com/swc-project/swc/blob/9b36abbe759f01e42cc14ad9c22c5faef01d7faa/crates/swc_ecma_transforms_compat/src/es2015/regenerator/case.rs#L878) so remaning stmts are omitted from transform.

@kdy1 any ideas on how to fix? I tried couple of approaches but it doesn't create correct transform, puts fns into incorrect scope of case switches.

**Comment by kdy1** [comment]
We can change it to

```rust
if !already_end && !matches!(&*stmt, Stmt::Decl(Decl::Fn(..))) {

}
```

This will actually ignore `already_end` flag for function declarations.

**Comment by kwonoj** [comment]
Shouldn't we preserve any stmts after return stmt? Like `var` for example?

**Comment by kdy1** [comment]
I think patterns of `var` and function declaration is enough.
`regenerator` is actually ported from `regenerator-transform` so there should be a reason for the `already_end` check.

**Comment by kwonoj** [comment]
Thanks, I'll try  to peek bit more.

**Comment by kwonoj** [comment]
I gave those attempt bit and that wasn't suffecient, it skews switch / case ordering as well as omitting some key paths. I'll try to dig bit more.
