### ISSUE TITLE
Strip flow types

### ISSUE THREAD

**Issue by Kronuz** [swc-project/swc#256]
Babel has this module: `@babel/plugin-transform-flow-strip-types`, which simply ignores flow types. There are quite a few modules out there that use babel to compile, yet have flow typing.

Please add support for stripping types, no need for full _Flow support_ (issue #174), just ignore/strip them.

**Comment by goodmind** [comment]
#174

**Comment by kdy1** [comment]
Closing as flow decided to focus on internal usages.

**Comment by FezVrasta** [comment]
That doesn't mean external projects can't use it. There are a lot of projects that still use Flow.

**Comment by kdy1** [comment]
@FezVrasta If you send a PR, I'll happily accept it and maintain it.

**Comment by kdy1** [comment]
@FezVrasta Maybe it's unrelated question, can you show me some projects using flow?
I've been working on swc for few years and I didn't have time to look at the source code of other js/ts projects.

**Comment by FezVrasta** [comment]
I maintain Popper, which is used by approximately a couple million websites around the world, and it's entirely wrote with Flow.

https://popper.js.org

**Comment by FezVrasta** [comment]
> @FezVrasta If you send a PR, I'll happily accept it and maintain it.

The best way to implement it would be to use [`flow-remove-types`](https://flow.org/en/docs/tools/flow-remove-types/) since it's a standalone binary (no Babel involved) and it's maintained by the Flow core team.

I'd be happy to send a PR, I just need to understand if integrating flow-remove-types would be an acceptable approach, and some guidance on where to start.

**Comment by kdy1** [comment]
Hmm... I don't think using js module is acceptable.
I'll just try implementing it in rust when I have some free time. (Hopefully tomorrow, as it's holiday)

**Comment by FezVrasta** [comment]
Thanks that'd be awesome! The whole Flow community will be grateful for this 🤗

**Comment by kdy1** [comment]
I found that I have a task with higher priority, so I'm postponing this.

**Comment by kdy1** [comment]
I looked at the source code of `flow-remove-types`, and it depends on `flow-parser`, which means lots of job.

**Comment by FezVrasta** [comment]
Yes it depends on the JS-compiled OCaml compiler. Considering how fast the OCamls compiler it is I wonder if swc could directly interface with it?

TBH a simple plugin-like approach where each file is feeded through the Flow parser would be all it's needed to address this.

**Comment by kdy1** [comment]
Is there a way to see the size of the compiled flow stripper?
I don't want to bloat the binary size.

**Comment by FezVrasta** [comment]
It's between 30-40 MB depending by the target platform, but I'd suggest to keep this as an external dependency so that only who needs Flow support needs to download it, especially because if it gets embedded in SWC you would need to cut a new release anytime the Flow compiler is updated.

![CleanShot 2021-10-04 at 13 27 18@2x](https://user-images.githubusercontent.com/5382443/135843850-45f8381a-7e04-4ce3-aa57-5d2bbb6ce7c1.jpg)

From my understanding, the Babel plugin to strip Flow types doesn't depend on the Flow compiler though, so maybe you could use their source code as reference for a Rust implementation?

https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-flow-strip-types/src/index.js

**Comment by kdy1** [comment]
> From my understanding, the Babel plugin to strip Flow types doesn't depend on the Flow compiler though, so maybe you could use their source code as reference for a Rust implementation?

Yes. But it means lots of work. It's really enormous amount of work.

**Comment by FezVrasta** [comment]
> > From my understanding, the Babel plugin to strip Flow types doesn't depend on the Flow compiler though, so maybe you could use their source code as reference for a Rust implementation?
> 
> Yes. But it means lots of work. It's really enormous amount of work.

What about the approach I described above?

> TBH a simple plugin-like approach where each file is feeded through the Flow parser would be all it's needed to address this.

**Comment by kdy1** [comment]
I'm fine with it.
But currently, there's no plugin api for parser, so we need to make some decisions about the api.

**Comment by FezVrasta** [comment]
Ok that sounds great, this way the Flow support will be implementable at plugin level and the core is not tied to it.

Is there anything else I can do to help to move this effort forward? Do you have an RFC or other kind of documentation where the API is being designed?

**Comment by kdy1** [comment]
Can you join discord server at https://discord.gg/GnHbXTdZz6 ?

I'm not sure about the RFC, but I think people in discord server may provide some ideas about the api.

**Comment by FezVrasta** [comment]
For anyone interested, I started a conversation here https://discord.com/channels/889779439272075314/889780921002246154/894551464410763314

**Comment by noppa** [comment]
Facebook's Hermes project also [has parsers for both TypeScript and Flow](https://github.com/facebook/hermes/tree/main/lib/Parser), written in C++, if that's any help.

**Comment by FezVrasta** [comment]
> Facebook's Hermes project also [has parsers for both TypeScript and Flow](https://github.com/facebook/hermes/tree/main/lib/Parser), written in C++, if that's any help.

That's great! It also seems to expose a Rust API?

**Comment by mikeduminy** [comment]
react-native also uses flow which need to be stripped away in production builds

**Comment by langri-sha** [comment]
Shooting from the hip: there's only a few differences between the TS and Flow type syntaxes, so perhaps it's possible to reuse a goodly portion of the TS transformer and take it from there?

**Comment by kwonoj** [comment]
I'm going to suggest to close this. /cc @kdy1 before actually closing it.

Given the scope of the SWC's feature and codebase, I don't think we have enough bandwidth to support this continuously. Probably the best way forward is someone making a userland parser based on the existing implementation of SWC.

**Comment by kdy1** [comment]
It's now implemented!
I need to document it, though
