### ISSUE TITLE
minification swallows `ReferenceError`

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#2603]
### Describe the bug

At least for Terser, the behaviour before and after minification shouldn't change. This included that code causing a `ReferenceError: xyz is not defined` before minification should still throw one afterwards.

### Input code

```typescript
// var xyz = 1;
var unused = xyz;
console.log(1);
```

### Config

```js
{
	compress: true,
	mangle: true,
	toplevel: true,
	module: true,
}
```

### Expected behavior

Terser's output is
```js
xyz;console.log(1);
```

swc's output is
```js
console.log(1);
```

(When adding a `xyz` local variable as shown in the comment, Terser behaves like swc)

### Version

1.2.106

### Additional context

cc @fabiosantoscode might have insight how important this is

**Comment by fabiosantoscode** [comment]
It's pretty important to not make output code crash less than input code.

**Comment by kdy1** [comment]
@fabiosantoscode I agree.
I'll fix this soon. I looked at it, but as we can't add a property to expressions in rust, I'm not sure about the way to check if an expression contains an unresolved reference efficiently.

In other places I just used visitor, but it caused problems because it has exponential time complexity.

**Comment by fabiosantoscode** [comment]
Was dead code elimination ported from Terser, or is it in swc's tree shaking code?

**Comment by kdy1** [comment]
@fabiosantoscode It's not ported, and it lives in https://github.com/swc-project/swc/blob/fbbdeeae5677b065182e5853e011832a6fedf68c/ecmascript/minifier/src/compress/optimize/unused.rs
