### ISSUE TITLE
does not allow reassign ref to exported fn for typescript

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#2606]
### Describe the bug

This is followup edge case for https://github.com/swc-project/swc/issues/2549.

When assignment is a typescript expression like

```
export function warn() {
  throw new Error("this should not be called");
}

export const test = {};

Object.defineProperty(test, "warn", {
  get: () => warn,
  set: (v) => {
    (warn as any) = v;
  },
});
```

`(warn as any) = v;` won't reassign exports.

First glimpse this looks like issue around AST:

``` 
//(warn as any) = v;

TsAs(
        TsAsExpr {
            span: Span {
                lo: BytePos(
                    733,
                ),
                hi: BytePos(
                    744,
                ),
                ctxt: #0,
            },
            expr: Ident(
                Ident {
                    span: Span {
                        lo: BytePos(
                            733,
                        ),
                        hi: BytePos(
                            737,
                        ),
                        ctxt: #0,
                    },
                    sym: Atom('warn' type=inline),
                    optional: false,
                },
            ),
....
```

```
// warn = v;

Ident(
          BindingIdent {
              id: Ident {
                  span: Span {
                      lo: BytePos(
                          838,
                      ),
                      hi: BytePos(
                          842,
                      ),
                      ctxt: #0,
                  },
                  sym: Atom('warn' type=inline),
                  optional: false,
              },
              type_ann: None,
          }
```

in case tsc it doesn't create bindingident.

### Expected behavior

ts expression also should reassign exports

### Version

master

**Comment by kwonoj** [comment]
Am I understanding correct this need to be updated other than transform, or it's still something to be fixed with transforms?

**Comment by kwonoj** [comment]
I may wrong still though, peeking issue it looks like assignment is not evaluated when there's paren (https://github.com/swc-project/swc/blob/3280b4cd7a147cf72f517afa7a11cc5c39ccec06/ecmascript/parser/src/parser/pat.rs#L537) . Bit sure `how to fix` part, returning pat from inner expr breaks ast.

**Comment by kwonoj** [comment]
@kdy1 would you mind share some thoughts, first if above seems correct triage & secondly some high level thoughts how to fix issue? :pray: I'll spin some time myself to dig further meanwhile.

**Comment by kdy1** [comment]
@kwonoj You can add `visit_mut_pat_or_expr` to visitor in https://github.com/swc-project/swc/blob/f8c7d36ac9cb6d46de690e90a0399a1b01ca823b/ecmascript/transforms/typescript/src/strip.rs

and you can 

  1. visit children with `visit_mut_chilren_with(self)`.
  2. Check if it's `PatOrExpr::Expr(Expr::Ident)` and normalize it to `PatOrExpr::Pat(Pat::Ident))`.

I guess this is enough. If not, just ping me again.

**Comment by kwonoj** [comment]
Thanks for the pointer, I'll give it a go! :runner:
