### ISSUE TITLE
Unicode parse error

### ISSUE THREAD

**Issue by stefanpenner** [swc-project/swc#261]
```js
error: Not an utf-8 character: 55356
  --> <anon>:11:15
   |
11 |     unicode: '\ud83c\udf83',
   |               ^^^^^^

error: Not an utf-8 character: 55357
  --> <anon>:11:15
   |
11 |     unicode: '\ud83d\udc35',
   |               ^^^^^^

error: Not an utf-8 character: 55356
  --> <anon>:11:15
   |
11 |     unicode: '\ud83c\udfc1',
   |               ^^^^^^
```

**Comment by stefanpenner** [comment]
I'm trying SWC out on a very large codebase, my goal is to help surface issues by using it to essentially fuzz swc.

**Comment by kdy1** [comment]
@stefanpenner I'm happy with bug reports. I want swc be more mature.
By the way, is non-utf8 unicode sequence is valid is javascript?

**Comment by stefanpenner** [comment]
> @stefanpenner I'm happy with bug reports. I want swc be more mature.

Good stuff!

> By the way, is non-utf8 unicode sequence is valid is javascript?

I believe so https://www.ecma-international.org/ecma-262/5.1/#sec-7.1
