### ISSUE TITLE
Failed to globally replace import.meta - "cannot be used outside of module code"

### ISSUE THREAD

**Issue by ghost** [swc-project/swc#2615]
### Describe the bug

When trying to replace an `import.meta` value, swc fails to replace it, and produces an error. I don't really have a choice when it comes to using this construct, given [it's how vite handles env variables](https://vitejs.dev/guide/env-and-mode.html).

```
error: 'import.meta' cannot be used outside of module code.
    
  |
1 | import.meta.env.PUBLIC_APP_API_URL
  | ^^^^^^
```

### Input code

```typescript
export const apiUrl = import.meta.env.PUBLIC_APP_API_URL;
```

### Config

```json
{
  "env": {
    "targets": "current node"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "import.meta.env.PUBLIC_APP_API_URL": "'http://api.example.com'"
          }
        }
      }
    }
  }
}
```

### Playground link

https://swc-play.vercel.app/?version=1.2.106&code=H4sIAAAAAAAAA0vOzysuUUgsyAwtylGwVcjMLcgvKtHLTS1J1EvNK9MLCHXy8XSOdwwIAGLP%2BNAgH2sAlJonxTIAAAA%3D&config=H4sIAAAAAAAAAyWNMQuDQAyF%2F0sWF3Hs4NZ2EhyOgrNcbVqu3HlHEqVW%2FO9NaCDkIy8vb4c3T9DuUDwxkhFvs%2FgPtCBbQZ4oFIEahHUltOChTH7mZ6Zk57lISOH7975ivvvIhqs%2BtBlSySRNQvENzmvjhkvfXcezc9rdONx6jaoqOKxqSPmxRDSjxauEfFLtB6mFvUKoAAAA

### Expected behavior

The value should have been replaced as requested in the config.

### Version

1.2.106

### Additional context

Error while using `@swc/jest`.

**Comment by choyongjoon** [comment]
For temporal solution, I used a custom transformer like this.


importMetaEnvTransformer.cjs
```js
module.exports = {
  process(sourceText, sourcePath, options) {
    return {
      code: sourceText.replaceAll('import.meta.env', '{}'),
    }
  },
}
```

jest.config.cjs
```js
const cwd = global.process.cwd()

...

  transform: {
    '^.+\\.(t|j)sx?$': [
      'jest-chain-transform',
      {
        transformers: [
          `${cwd}/importMetaEnvTransformer.cjs`,
          '@swc/jest',
        ],
      },
    ],
    '^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      'jest-transform-stub',
  },
```

I used `jest-chain-transform` to apply my custom transformer first. I also used `cwd` because it doesn't support `<rootDir>`.

**Comment by nrjshka** [comment]
Having the same issue. It would be great if somebody could take a look on it, please

**Comment by kdy1** [comment]
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2017"
  },
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  // This line is important
  "isModule": true
}
```

will work
