### ISSUE TITLE
_interopRequireWildcard not defined when import is repeated

### ISSUE THREAD

**Issue by edu-bound** [swc-project/swc#2619]
### Describe the bug

Seems that when an import is accidentally used twice, once with the default export and once with a named export, swc will not declare the `_interopRequireWildcard` function.

### Input code

```typescript
import { keyframes } from 'styled-components';
import styled from 'styled-components';

const QuiteItem = styled.div``;

const foo = keyframes``;

const MyCompTallClassNameRename: FC<
  ComponentProps<typeof MyComp> & { className?: string }
> = (props) => {
  const { className, ...rest } = props;
  return <MyComp {...rest} classNameFieldsContainer={className} />;
};
const MyCompTall = styled(MyCompTallClassNameRename)``;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://swc-play.vercel.app/?version=1.2.106&code=H4sIAAAAAAAAA32Qy2rDMBBF9%2FqKWTUJtM4%2BfnQhCHSR0IZ%2BQIw9DqKyxoyUgDH690xqxw2UdqOF7rlzmDFtRxxggC%2FsGy5b9BChYWph4UNvsX6pSBCHLvhFqsyIj9E%2FnKrI%2BQAfZxPwLWAL%2BdRJanM5HmegIZJodj8ku17LwM%2FSWm1L7%2FcSH9DJu4GtzhSAvvvemTqfhb5DaqZaAU%2ByUnUvvm7EzsadIKpCfMvuVllBXsAgk0bhA%2F8MSZIwymcU%2BhtOhWMMZ3aQjQ4YJij%2BFLcGbe01uVAah5wPcxJhXaQqpr%2B2my%2Bz%2FHPj1e0sV494h%2BqpAQAA&config=H4sIAAAAAAAAAyWNUQrEMAhE7%2BJ3T9Ab7DHEWkipMaiBDSV3r9n9G948Zh64nGB%2FoKE520o%2BauAXdojR2MlKC9ggPFFY5w2OUVEKfaSpxR%2FOFAyrn2qyNoyR4hd6jSKca9hDBaMQzJm66NFvXsq6yZ5UROvlWb8jid2%2FlQAAAA%3D%3D

### Expected behavior

To have the `_interopRequireWildcard` helper defined.

### Version

1.2.106

**Comment by zephraph** [comment]
I've been bumping into this same error when trying to add `@swc/jest` to one of my work projects.

The first instance was this:

```
import { cloneElement } from 'react'
import React from 'react'
```

Easy enough to fix. The next one points to whitespace under this group:

```
import React from 'react'
import type { TableInstance } from 'react-table'
import cn from 'classnames'
import './menu-button.css'
```

There's no duplicate import there. Perhaps the `menu-button.css` import? The only reason I drop it here is that I suspect they're related. It seems like if there's something weird with the imports then the helpers aren't included correctly. 

My config:
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "externalHelpers": false,
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "target": "es2019"
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Comment by kwonoj** [comment]
I believe this is fixed via https://github.com/swc-project/swc/pull/2868. Please give it a try with latest version.

**Comment by kdy1** [comment]
Why did you close this?

**Comment by kwonoj** [comment]
I _guess_ reporter confirmed this? https://github.com/swc-project/swc/issues/2619#issuecomment-990647429
