### ISSUE TITLE
disable _interopRequireDefault

### ISSUE THREAD

**Issue by stefanpenner** [swc-project/swc#262]
Is there a way to disable `_interopRequireDefault`? In babel, we currently disable this as for some users with large code-bases this can add up to non-trivial bite size and parse/eval overhead, especially if they are authoring without the need for this interop.

**Comment by kdy1** [comment]
If you are using commonjs module, it's possible. If you are not, it's not possible.

**Comment by stefanpenner** [comment]
@kdy1 using amd + moduleId

**Comment by stefanpenner** [comment]
Also producing 

```
  Object.defineProperty(_exports, '__esModule', {
        value: true
    });
```

With no need for interopt is wasteful

**Comment by stefanpenner** [comment]
It may be worth considering:

```js
module.interopt = true | false
```
