### ISSUE TITLE
Getters and setters applied through a decorator don't get called when decorated property is also initialized.

### ISSUE THREAD

**Issue by astegmaier** [swc-project/swc#2655]
### Describe the bug

If you create a decorator that applies a getter and setter to the decorated property, and then also initialize (e.g. assign a value to the decorated property in the class definition), the resulting class, transpiled by `swc`, will never call the getters and setters for that property. The same code transpiled by `tsc` will work as expected.

### Input code

```typescript
const testDecorator = <T extends {}>(target: T, key: keyof T) => {
    const privateField = Symbol();
    // We define getters and setters for the property on the prototype of the class
    // A real application might use this to intercept changes to the decorated property.
    // This is a simplified version of a pattern used by the @microsoft/fast-elements library.
    Reflect.defineProperty(target, key, {
        get: function () {
            console.log(`called getter for property ${key}.`)
            return (target as any)[privateField]
        },
        set: function (newValue) {
            console.log(`called setter for property ${key} with newValue ${newValue}.`)
            return (target as any)[privateField] = newValue
        }
    })
    console.log("called testDecorator!");
  };

class TestClass {
    @testDecorator
    testProp = "hello"
}

const instance = new TestClass();
// SWC console output:
//    "called testDecorator!"
// TSC console output:
//    "called testDecorator!"
//    "called setter for property testProp with newValue hello"

instance.testProp = "goodbye";
// SWC console output:
//    <nothing>
// TSC console output:
//    "called setter for property testProp with newValue goodbye."

console.log("testProp is now", instance.testProp);
// SWC console output:
//    "testProps is now goodbye"
// TSC console output:
//    "called getter for property testProp."
//    "testProps is now goodbye"
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "target": "es2016"
  }
}
```

### Playground link

[see here for current swc output of the above example](https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA51SwU7DMAy99ytMxWGVpu6%2BMQQCcUZQwQEhLaRuG5ElVeIyqqn%2Fjpu2Y0NCQuRQOXb83vOrpTWegNDTLUrrBFkHa7jIAD8JTe5h313OSLgSaQnZHN6xXfYfW0CWwPoS9hHwkQGmdupDEN4p1DmjPLbbN6tnySo8WSzgGSHHQhkEhiN0HoTJwY9xwdRUIaPYGh21YM10J0ttjcCkfUJq4f2EeQ0OhQZR11pJQYqbtqqsCBqP%2FFp5IAvKMIPEmkBWwpQYkj1UPgyN%2BYE1TQPyAxYaJaWD3vuxODoRbJiPo%2FcnuFM0Rgb%2BWXJUmtyxGlNty9lGCq2Zb3AgDH0Y%2BHzPuF26SU66HVLjGHXgBtG71iYvx2a%2FHhq6%2BSH0p6IM7p6EbvAv4vyv4mCnqIIJi5NT%2BC%2FZvCRT%2F%2FcEIeqS6Ke4eBR3sqxncVivbhVFYS0g4%2BpNiIYxr06eh1Sf6f8os8cVam3jqPsCdXSR1AgDAAA%3D&config=H4sIAAAAAAAAA0WOQQ7DIAwE%2F%2BJzDm0POfCHPgIRJyICjGxHaoT4ewGlzc3a3Rm5wC4OTIFsWZD7JWdS%2BwEDemYUxz4rTKDSotUGwQkWdMRWiQWM8oG11ZY31AahvB7PuQGBSPCPRJ%2F8ena9o5gZRe7Kpi38lrW5Ii1HD8r4YDhnqLfj4ry8r%2BH44QtyiB%2BMygAAAA%3D%3D).

### Expected behavior

I'd expect the getters and setters defined by the decorator to be called, just like they are in the code transpiled by `tsc`.

### Version

1.2.106

### Additional context

You can see [`tsc` output of the above example here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7xsdARYSoCGM0cAvHADwAqcomyAJqnAN4C+AfABQwFQDmwGAC44VADRwA1sACeombIgAzMQEoyHVgCg4exCnRwwUAJYA3IsABip4ABsGZOAGVZAWwBGEe1zUBuXX0AemC4AHVgOAZgZVNkKMEYTChmAkY4VCEU5mUSGAALKJMIMGBYWTgUOELiqAhiGFkyqtVaxHsCVFQgvVC4AEE4KGACezgCMDB7UwQiU2r3U34C+ABXLJqC02ZiOHiUhGAweAQC9MFdiC2omPwrJxKyioA6F964ACVY+zwYF5icQSAAV6s8mjw+ElJIpJCwPvo4ElRMo1sgEDAFsg4H4dIj8fokGgfMAXvYIPwuAADOb2X5OJIpOB5KDGMHlJpwAAkLEUbBeVLUCIJwyEayg2MhAiEEzSyFkagA2iYLFZbA4GABdYV6NjiHWZIQotEYrE4hIAdwAamM1sANPCRfiiagSWSKdTafTDclysySE8OZUeXy4BbTIU4JabfY7dyWNHbcB+YKDYiRjBxZLeNL4F0JvKlSrLJh1Y5Nc5E7HgAa2B82ELES63eTKQAiL3AJyYHB4aBEaAAQjbASCbEC2gQnW6YiwMAAwtPmI79AABHswXD3YhQD4b0GlZxtop0iBt7RsIA).

I also have [a reproduction in this repo](https://github.com/astegmaier/swc-decorators-test).

The root cause appears to be the fact that typescript will transpile the property initializer into a simple assignment in the constructor - which invokes the getters and setters defined on the prototype - like this:

```
class TestClass {
    constructor() {
        this.testProp = "hello";
    }
}
```
...while SWC will ultimately do the initialization through a call to `Object.defineProperty([instance], "testProp", [descriptor])`, which bypasses the prototype (see swc playground link above for details).

This bug is the root cause of an issue that blocks the use of `swc` with the `@microsoft/fast-elements` library. The `@observer` ([docs](https://www.fast.design/docs/fast-element/defining-elements)) and `@attr` ([docs](https://www.fast.design/docs/fast-element/observables-and-state)) decorators in this library follow a pattern similar to this example. You can see a reproduction of those more-complicated real-life examples in [the repo I linked to above](https://github.com/astegmaier/swc-decorators-test).

**Comment by astegmaier** [comment]
I did a bit more digging about what is going on here, and I discovered two things:

1. Babel has the same behavior as `swc` - using `defineProperty` to initialize class fields instead of simple assignment. I added a repro of this to [my test repo](https://github.com/astegmaier/swc-decorators-test).
2. `tsc` has an option called [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) that is `false` by default, unless your target is `ES2022` or `ESNext`. When it is `true`, `tsc` will output the same thing as `babel` and `swc`, and you'll see the bug above. [The release notes for Typescript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier) have a detailed explanation about this flag and why it was introduced. In short, the original typescript behavior didn't align with the way that the ECMA standard ended up evolving to, they want to eventually move to the standard, but they expect some code bases and libraries to break. It looks like `@microsoft/fast-elements` is one such library.

In light of this discovery, I think this is actually a feature request, not a bug - it would be great if there was some option in `swc` to opt into `tsc`'s legacy behavior, so it would be possible to adopt `swc`, and still use libraries that were built around that old assumption.

It might be called something like `useLegacyClassInitialization` and be `false` by default. When it was `false`, we'd keep current behavior. When it was `true`, the following code...
```ts
class MyClass {
    myProp = "something";
}
```
...would be transpiled to...
```ts
class MyClass {
    constructor() {
        this.myProp = "something";
    }
}
```
In terms of the impact this might have on users, I can say personally that the lack of this feature blocks me from using `swc` along with `@microsoft/fast-elements` decorators. There are probably a fair number of other libraries and code bases built with `tsc` that will have a similar problem - otherwise the typescript team wouldn't have been so cautious in rolling this out. Ultimately, it's a problem that will probably get less important with time, although it could take years.

**Comment by Austaras** [comment]
There should be -- and swc already has one -- option to opt out define semantic, and that is `loose`, but loose mode for class hasn't been implemented yet.

**Comment by e111077** [comment]
Hello, typically to get around this in TSC, you have to set `useDefineForClassFields: false`, but when doing that. This issue means that to use a tool that depends on SWC like parceljs, when that tsconfig setting is set, it uses `@swc/helpers/_initializer_define_property.js` which still uses `Object.defineProperty`.

In order to use tools like parcel for TS in projects like `@microsoft/fast-elements` or `lit` you have to opt out of the SWC compiler  from transforming TS.

Is there any way we can get support for this?

**Comment by kdy1** [comment]
@e111077 Is `useDefineForClassFields` not enough for this case?

**Comment by e111077** [comment]
Heya, setting it to false doesn't seem to be respected by SWC specifically when used with a decorator. In all other cases `useDefineForClassFields: false` works as intended

**Comment by kdy1** [comment]
I think it's a separate issue, but I'll fix this anyway.
