### ISSUE TITLE
Default namespace export is not exported

### ISSUE THREAD

**Issue by matunnkazumi** [swc-project/swc#2669]
Default export is not exported in below case.

**Input Code**
```typescript
export namespace TEST {
  export const VALUE = "value";
}

export default TEST;
```

.swcrc
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    },
    "target": "es5"
  }
}
```

version
```
    "@swc/cli": "^0.1.51",
    "@swc/core": "^1.2.107",
```

**Result**
```javascript
var TEST1;
export { TEST1 as TEST };
(function(TEST) {
    TEST.VALUE = "value";
})(TEST1 || (TEST1 = {
}));
```

```TEST``` is not default exported.

**Expected behaviror**
```TEST``` is default exported. like tsc. ([TSC playground](https://www.typescriptlang.org/play?target=1&module=1#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDgFQFEBlfOAbwCg45RJY5sIF14A1AQQBkBVQuALxwARADckAGwCuwYQG5KAX0qU60eABNgAMyRSJ8IqQVA) )

**Comment by DarkRoku12** [comment]
This bug is stopping me from using SWC sadly.
