### ISSUE TITLE
Module parse failed: Assigning to rvalue 

### ISSUE THREAD

**Issue by apenshar** [swc-project/swc#269]
hope swc-loader can parse the code below correctly 🍰 

```js
;(function() {
  // do something
})(window, window.lib || (window.lib = {}))
```

**Comment by kdy1** [comment]
It seems like you are using old version of swc. Package `swc` is renamed to `@swc/core` and you should run `npm i --save-dev @swc/core`.

I also updated documentation on swc-loader.
