### ISSUE TITLE
Comments above an object method declaration cause an early return to be added to the function body

### ISSUE THREAD

**Issue by hexmodr** [swc-project/swc#2701]
### Describe the bug

The output generated by SWC adds in an early return to async function when defined using the short-hand method syntax. This leads to no code in the method body being executed

### Input code

```typescript
const x = {
  // i am some comment
  async hello(arg) {
    console.log("Hello")
  }
}
```

### Config

```json
{
    "jsc": {
        "externalHelpers": false,
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": true
        }
    },
    "module": {
        "type": "commonjs"
    }
}
```

### Playground link

https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA0vOzysuUahQsFWo5lJQ0NdXyFRIzFUozs9NVUjOz81NzSsBCicWV%2BYlK2Sk5uTkayQWpWuC1SoAFeQV5%2Bek6uXkp2soeYBklTSBErVctVwAp5%2F48lcAAAA%3D&config=H4sIAAAAAAAAAy2NQQrDMAwE%2F7Jnv8Av6KWPEI4KCbZlJAUSgv9eq%2FQ6O8M%2BOKwgP%2BDLWTvVF9fBasgfqsYJg9RYw7C7O13I8HuwFd2HI8FtIddzqRsXUXKJOsicCU22s3LkUa24SGvSD8Mad3v%2F59%2FZ%2FALw%2FWoujQAAAA%3D%3D

### Expected behavior

It to not generate an invalid early return in the function

### Version

1.2.106

**Comment by UMASHIBA1** [comment]
Can I pick this?

**Comment by kdy1** [comment]
@UMASHIBA1 Of course, thank you!
