### ISSUE TITLE
Async to regenerator explicitly binds this context when created

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#2716]
### Describe the bug

I'm hitting some series of https://github.com/swc-project/swc/issues/2305, with various edge cases. We've fixed by not binding to context for some known cases. While, comparing emitted output between swc / babel, both do the similar like

```
function tt() {
  return _tt.apply(this, arguments);
}

function _tt() {
  _tt = _asyncToGenerator(function* () {
    ...
  }); // if swc, do the explicit .bind(this) here
  return _tt.apply(this, arguments);
}
```

which returns wrapped fn calls .apply(this) to bind this context when fn is being called

### Expected behavior

this context would be preserved for each fn per call time.

### Version

master

### Additional context

discord discussion thread: https://discord.com/channels/889779439272075314/889785438938726441/908256585313312819

**Comment by kwonoj** [comment]
Will attempt to not-to-bind by default. Given babel emits similar, and swc already does it for some known paths I expect this won't be huge breaking changes.

**Comment by Austaras** [comment]
Have you started working on this?

**Comment by kwonoj** [comment]
Yes. Trying to resolve a few challenges takes some time.

**Comment by kwonoj** [comment]
For the note: main challenages in here is some cases `this` context still need to be preserved, such as inside of class, etcs. I presume that was the reason to introduce `bind`. It could be resolved by capturing context (`var _this = this;`) and main work comes from there to properly determine if it's needed & insert it.

**Comment by Austaras** [comment]
I believe 'bind' is introduced solely because there's no generator arrow function in js but there is async arrow functions.

**Comment by kwonoj** [comment]
I do not have a full history of where / how bind is introduced, but for the async arrow it could also be treated without bind as long as context is properly captured. For example. babel does this:

```
const x = async (x) => x + this.val

// output

const x = function () {
  var _ref2 = _asyncToGenerator(function* (_x3) {
    return _x3 + _this2.val;
  });

  return function x(_x2) {
    return _ref2.apply(this, arguments);
  };
}();
```

it's different matter if swc should do same or not though.

**Comment by Austaras** [comment]
'swc' could and should treat async arrow this way. The current implementation is flawed, and 'arguments' is untended.

For a bit of context, 'swc' used to translate normal arrow functions to 'bind' until #2212 is fixed.

**Comment by kwonoj** [comment]
> 'swc' could and should treat async arrow this way.

I generally agree, esp current impl does this

```
const x1 = _asyncToGenerator((function*(x) {
    return x + this.val;
}).bind(this)).bind(this);

```

having double `bind` is something unexpected as far as I believe.

In anyway, these are the issue I'm seeing & trying to solve. I just couldn't solve all correctly yet.

**Comment by Austaras** [comment]
It might be possible to extract logic from `es2015_arrow` and reuse it here, especially consider #2543

**Comment by kwonoj** [comment]
Looks like this is closed as I refrenced in other pr. Let me reopen it.

**Comment by kdy1** [comment]
Now there's only one code path that may generate a `.bind` call.
It's https://github.com/swc-project/swc/blob/d03824b13d8d744f2b16698dbed182e3afe88374/crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs#L128-L135 and we should change the third argument to `true`.
