### ISSUE TITLE
createSuper was not found in '@swc/helpers' is breaking builds

### ISSUE THREAD

**Issue by midudev** [swc-project/swc#2721]
### Describe the bug

Suddenly, when compiling a project, we're getting the next error:

```
"export 'createSuper' (imported as 'swcHelpers') was not found in '@swc/helpers'\n`
```

Checking `@swc/helpers` package, it seems that the module is missing but the compiled code is trying to use the `createSuper` method.

We haven't done any change from our side (no upgrading dependencies).

### Input code

```typescript
import {Entity} from '@s-ui/domain'

export default class SavedSearch extends Entity {}
```

### Output code

```js
import*as swcHelpers from"@swc/helpers";import{Entity as Entity1}from'@s-ui/domain';var SavedSearch=function(Entity){"use strict";swcHelpers.inherits(SavedSearch,Entity);var _super=swcHelpers.createSuper(SavedSearch);function SavedSearch(){swcHelpers.classCallCheck(this,SavedSearch);return _super.apply(this,arguments)}return SavedSearch}(Entity1);export{SavedSearch as default}
```

### Config

```js
module.exports = {
  minify: true,
  jsc: {
    parser: {
      syntax: 'ecmascript',
      jsx: true,
      dynamicImport: true,
      privateMethod: true,
      functionBind: true,
      exportDefaultFrom: true,
      exportNamespaceFrom: true,
      decorators: true,
      decoratorsBeforeExport: true,
      topLevelAwait: true,
      importMeta: true
    },
    transform: {
      legacyDecorator: true,
      react: {
        useBuiltins: true,
        runtime: 'automatic'
      }
    },
    target: 'es5',
    loose: true,
    externalHelpers: true
  },
  env: {
    targets: {
      ie: '11'
    },
    dynamicImport: true,
    loose: true,
    mode: 'entry',
    coreJs: 3
  }
}
```

### Playground link

Playground link is not representable as it doesn't compile the same way.
https://play.swc.rs/?version=1.2.107&code=H4sIAAAAAAAAA8vMLcgvKlGods0rySyprFVIK8rPVVB3KNYtzdRPyc9NzMxT5%2BJKrQArSklNSyzNKVFIzkksLlYITixLTQlOTSxKzlBIrShJzUspVoCYolDNVcsFAGd6ir9ZAAAA&config=H4sIAAAAAAAAA2WQwU4DMQxE%2FyXnXrnsjaogkIB%2FsLKzxSiJI8cpu6r239m0SiniZr3xWOM5u8iJp8UNphU791W8G84ukxZom8qSjGY3OPhIxStnczs3Loki%2B9eYRa17s%2FKJDO%2BwTxk7nGryxpL2nG4Mc7MdMFEN9qwS%2FwofFFEyedxLI7womWj5T%2FaYRPE034cxyW84ITx%2BE98gX%2FJuAelK1m1PKZXNHtuzAUfyy6Ef7jYFeWu61mQcsbVB1SSSsXdrO0J6hLWSysPWThAp%2BP3JoInCC0JGT7%2BuP%2FNS8hZ5AQAA

### Expected behavior

The module `createSuper` is available in `@swc/helpers` and builds work as expected.

### Version

@swc/core@1.2.107 & @swc/helpers@0.2.13

### Additional context

I'm using `swc` programatically and not with the cli.

**Comment by kdy1** [comment]
You can update `@swc/helpers` to fix the issue.

**Comment by midudev** [comment]
Thanks @kdy1, I guess the moment I compiled, the new package of @swc/helpers wasn't updated yet as I tried to update it! I see now is available.  👍

**Comment by kdy1** [comment]
I forgot adding helpers to `@swc/helpers`. That's one of the reasons I flattened the project.
I'll merge other core javascript packages into the main repository so I can update them along with changes.

**Comment by midudev** [comment]
Awesome! Thanks @kdy1!
