### ISSUE TITLE
spack: Minifier corrupts code that uses direct `eval`

### ISSUE THREAD

**Issue by evanw** [swc-project/swc#2728]
### Describe the bug

Code that uses direct `eval` can access variables in any enclosing scope. This constraint isn't correctly handled by spack. There are two separate bugs:

* Names of variables in enclosing scopes are incorrectly minified when they should not be
* Variables in enclosing scopes are incorrectly removed when they could still be accessed

I'm using the following `spack.config.js` file:

```js
module.exports = {
  mode: 'production',
  options: {
    jsc: {
      minify: {
        compress: true,
        mangle: {
          topLevel: true,
        },
      },
    },
  },
  entry: {
    web: 'input.js',
  },
  output: {
    path: '.',
    name: 'output.js',
  },
}
```

### Input code

```typescript
function fn(bar) {
  const foo = 64206..toString(16)
  return eval(bar)
}
console.log(fn('foo + bar'))
```

### Expected behavior

That code should print the following:

```
facefoo + bar
```

However, when bundled with spack that code crashes instead:

```
$ node output.js
undefined:1
foo + bar
^

ReferenceError: foo is not defined
```

That's because spack generates the following code:

```js
function a1(a) {
    64206..toString(16);
    return eval(a);
}
console.log(a1("foo + bar"));
```

### Version

@swc/cli: 0.1.51, @swc/core: 1.2.108

**Comment by leerob** [comment]
Thank you so much for opening these! Very helpful.
