### ISSUE TITLE
enum member value type assertion should be removed

### ISSUE THREAD

**Issue by funn1est** [swc-project/swc#2730]
### Describe the bug

According to [TypeScript Handbook Enums Reverse mappings](https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings)

> Keep in mind that string enum members do not get a reverse mapping generated at all.

But we can use enum member value type assertion to enable `Reverse mappings`, but in the generated code `type assertion` is not removed.

### Input code

```typescript
enum Enum {
  A = 'A',
}

enum EnumWithReverseMappings {
  A = 'A' as any,
  B = <any>'B',
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2015"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.107&code=H4sIAAAAAAAAA0vNK81VcAUR1VwKCo4Ktgrqjuo6XLVcXKkwmfDMkoyg1LLUouJU38SCgsy89GJkxQqJxQqJeZU6QBEnoIgNkG2n7gQ2AwAvFFI5XQAAAA%3D%3D&config=H4sIAAAAAAAAA6tWyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpR0lEqKgUJpiTnFqbVATmJRemoJUElqsZGBoalSbS0AwrWlU0gAAAA%3D

#### SWC Result

```js
var Enum1;
(function(Enum) {
    Enum["A"] = "A";
})(Enum1 || (Enum1 = {
}));
var EnumWithReverseMappings1;
(function(EnumWithReverseMappings) {
    EnumWithReverseMappings[EnumWithReverseMappings["A"] = 'A' as any] = "A";
    EnumWithReverseMappings[EnumWithReverseMappings["B"] = <any>'B'] = "B";
})(EnumWithReverseMappings1 || (EnumWithReverseMappings1 = {
}));
```

#### TypeScript Result

The generated code should be like [TS playground](https://www.typescriptlang.org/play?jsx=0#code/KYOwrgtgBAou0G8BQUoEEoF4oHI04BokBfJJUSWeAdQEsAXACwCVgA3YAJwGdgBZAIYAHIbRABzblGSoM2PDigCpAkAE8iqAEJYoAHlVqAfDi2ESSIA)

```js
"use strict";
var Enum;
(function (Enum) {
    Enum["A"] = "A";
})(Enum || (Enum = {}));
var EnumWithReverseMappings;
(function (EnumWithReverseMappings) {
    EnumWithReverseMappings[EnumWithReverseMappings["A"] = 'A'] = "A";
    EnumWithReverseMappings[EnumWithReverseMappings["B"] = 'B'] = "B";
})(EnumWithReverseMappings || (EnumWithReverseMappings = {}));
```

### Version

1.2.107

**Comment by kwonoj** [comment]
This seems to be fixed with the latest version. 

https://play.swc.rs/?version=1.2.121&code=H4sIAAAAAAAAA0vNK81VcAUR1VwKCo4Ktgrqjuo6XLVcXKkwmfDMkoyg1LLUouJU38SCgsy89GJkxQqJxQqJeZU6QBEnoIgNkG2n7gQ2AwAvFFI5XQAAAA%3D%3D&config=H4sIAAAAAAAAA6tWyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpR0lEqKgUJpiTnFqbVATmJRemoJUElqsZGBoalSbS0AwrWlU0gAAAA%3D

@funn1est would you confirm if you can repro still?

**Comment by funn1est** [comment]
@kwonoj this issue has been fixed and I will close the issue
