### ISSUE TITLE
`jsc.paths` should handle index

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#2753]
Hey everybody, I saw a PR that was dealing with this was merged, so I went ahead and tried the latest `1.2.108` SWC version.

Unfortunately, I have to report that, at least on my end, the paths are still not being transformed the way they should be.

The steps I did were the following...

1. Created a brand new project and installed SWC.
2. Created the following files:

```
src
├── index.ts
└── utils
    └── index.ts
```

The `src/index.ts` looks like the following:

```ts
import test from "~/utils";

test();
```

3. I created the same `.swcrc` config I used above:

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "paths": {
      "~/*": ["./src/*"]
    },
    "baseUrl": "."
  }
}
```

4. Ran `swc src -d dist --source-maps --copy-files --extensions '.ts'`

Results?

Well, ultimately, the results were the same as reported initially. 😔

The compiled code was:

```js
import test from "~/utils";
test();

//# sourceMappingURL=index.js.map
```

So, "~" wasn't replaced.

And, as stated above, once I switched to `commonjs` via ...

```json 
"module": {
    "type": "commonjs"
}
```

... the path transformation was successful:

```js
"use strict";
var _utils = _interopRequireDefault(require("./utils"));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
(0, _utils).default();

//# sourceMappingURL=index.js.map
```

Hope I'm not missing something. If so, I'm sorry in advance for the trouble. 🙂

_Originally posted by @doitadrian in https://github.com/swc-project/swc/issues/2523#issuecomment-968595223_

**Comment by doitadrian** [comment]
Thanks @kdy1 for reopening.

**Comment by peterp** [comment]
I'm in the same boat, it appears that it's just replacing the imports, but it's not resolving them. As an example:

```js
{
  jsc: {
     target: 'es2020',
     baseUrl: '.',
     paths: {
       '@src/*': ['./src/*]
     }
  }
}
```

Input, files path is `./src/command/restore.ts`
```js
import { module } from `@src/config`
```

output is:

```js
var _module = require("./src/config");
```

It should be:

```js
var _module = require("../config");
```
