### ISSUE TITLE
spack: Bug of the minifier

### ISSUE THREAD

**Issue by neutralboy** [swc-project/swc#2775]
### Describe the bug

I created a react starter project to try out swc + spack and started playing around with react context.
> Here's my example repo for my code: [github.com/swc-hooks-test](https://github.com/neutralboy/swc-hooks-test)

I could get the basic setup working but as soon as I tried out the `reactContext` I hit an error with react 
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    resolveDispatcher http://127.0.0.1:8000/lib/index.js:1094
    useContext http://127.0.0.1:8000/lib/index.js:1098
    App http://127.0.0.1:8000/lib/index.js:21789
    renderWithHooks http://127.0.0.1:8000/lib/index.js:14153
    mountIndeterminateComponent http://127.0.0.1:8000/lib/index.js:16320
    beginWork http://127.0.0.1:8000/lib/index.js:17152
    callCallback http://127.0.0.1:8000/lib/index.js:6394
    invokeGuardedCallbackDev http://127.0.0.1:8000/lib/index.js:6429
    invokeGuardedCallback http://127.0.0.1:8000/lib/index.js:6474
    beginWork$1 http://127.0.0.1:8000/lib/index.js:20274
    performUnitOfWork http://127.0.0.1:8000/lib/index.js:19530
    workLoopSync http://127.0.0.1:8000/lib/index.js:19487
    renderRootSync http://127.0.0.1:8000/lib/index.js:19471
    performSyncWorkOnRoot http://127.0.0.1:8000/lib/index.js:19194
    scheduleUpdateOnFiber http://127.0.0.1:8000/lib/index.js:18930
    updateContainer http://127.0.0.1:8000/lib/index.js:21265
    legacyRenderSubtreeIntoContainer http://127.0.0.1:8000/lib/index.js:21623
    unbatchedUpdates http://127.0.0.1:8000/lib/index.js:19300
    legacyRenderSubtreeIntoContainer http://127.0.0.1:8000/lib/index.js:21622
    render1 http://127.0.0.1:8000/lib/index.js:21659
    <anonymous> http://127.0.0.1:8000/lib/index.js:21824
```
Link to the index.js in the above error: [index.js](https://raw.githubusercontent.com/neutralboy/swc-hooks-test/master/lib/index.js)

Initially considered it to be a problem with how its been coded and created a repo with `create-react-app` typescript template. 
> Here's the link to that: [github.com/react-swc-comparison](https://github.com/neutralboy/react-swc-comparison)\
The same 100% identical code on CRA seems to work.

Im not entirely sure what the issue is. Hopefully what I have provided helps!

Thanks in advance!

### Config

```json
{
  "minify": true,
  "jsc": {
    "minify": {
      "compress": { "unused": true },
      "mangle": true
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "throwIfNamespace": true,
        "development": true,
        "useBuiltins": false
      },
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    },
    "target": "es5",
    "loose": false
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

I expect the code to compile successfully just like the create-react-app. Which isnt happening as of now.
Here's the JS console error I get:
![Screenshot from 2021-11-17 11-12-14](https://user-images.githubusercontent.com/21339738/142141714-626324e1-49fc-4780-a6cd-08414afee801.png)
 

### Version

0.1.51

**Comment by kdy1** [comment]
`jsc.minify` is not an option for `spack`.
It's accidentally allowed because spack uses same code as `.transform()`.

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/swc/issues/2780
