### ISSUE TITLE
[Refactor] (es/transforms/compat): consolidate replacer visitor for arrow / fns

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#2786]
### Describe the feature

Context: https://github.com/swc-project/swc/pull/2776#discussion_r751427342

With effort for the #2716, there seems some overlapping between few visitors to handle replacing context specific (`this`, etcs). It maybe possible we could reuse instead of repeating same steps.

Probably reusing `ThisReplacer`, and moreover potentially make a single visitor instead fo `This` + `Arguments`. But it requires proper audit to do so.

**Comment by kwonoj** [comment]
@Austaras I think you have better context than me for this, maybe you're up for PR for this?

**Comment by Austaras** [comment]
Definitely will! But it's late in GMT+8, I'll try to spin up one next morning

**Comment by kwonoj** [comment]
Oh sure no worries, I didn't mean `let's do it now` 😅 .

**Comment by egilsster** [comment]
@kwonoj @Austaras might be related but I found one issue (I can report a new issue as well) where the `arguments` object is not getting the correct reference. Here's a snippet that reproduces it:
```
export class Quirk {
  async doStuff() {
    const args = arguments;
    console.log(args);
    return { foo: null, ...args[0] };
  }
}
```

I have a reproduction here https://github.com/egilsster/swc-jest-issue/blob/main/src/args.test.ts

**Comment by Austaras** [comment]
Yes, this is indeed a bug in my refact, please open a new issue

**Comment by egilsster** [comment]
Tracked in https://github.com/swc-project/swc/issues/2895
