### ISSUE TITLE
Unexpected transformation of function declaration

### ISSUE THREAD

**Issue by midudev** [swc-project/swc#2793]
### Describe the bug

A function declaration inside another function (expression or declaration) is being transformed to a expression causing problems with the hoisting.

### Input code

```typescript
function hiThere () {
    function a() {
        return 'hola'
    }
}

function b () {}
```

### Config

```json
{
  "minify": false,
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "topLevelAwait": true,
      "importMeta": true
    },
    "transform": {
      "legacyDecorator": true,
      "react": {
        "runtime": "automatic"
      }
    },
    "target": "es5",
    "loose": false,
    "externalHelpers": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA0srzUsuyczPU8jIDMlILUpV0NBUqOZSAII0mEwiXAgEilJLSovyFNQz8nMS1cGitVy1XFxw1UkIE7hqATjp6TJeAAAA&config=H4sIAAAAAAAAA2WQwU7EMAxE%2F8XnvXLpjdWCQAL%2BwUqnJSiJI8ddWlX9dxJQyyJu0UxmNH4rRZ%2F8sFA3cCg40Udx1K2UWQu0vcqSjGfqCC5yceqz0Yn6JXH07jlmUaPOdKrZrP7KhlfYu%2FS7OEzJmZd09unQMLfYBQNPwR5V4l%2FjjSNKZodbq4cTZRMt%2F5UzBlE8zLdjTPILrgj3n%2BwP0X%2FvrQP5R9nqP%2BVUajy2YwNGdstlL95jCnbWfJ2S%2BYhKgyeTyOYdba2EdYQ1SOWu0gkiBQdSzAZNHJ4QMn7n7%2BBXchKzopQjETmNYS%2FYtu0L0hFFsqYBAAA%3D

### Expected behavior

Inner function `a` preserves the function declaration.

```js
function hiThere() {
  function a() {
    return 'hola';
  }
}

function b() {}
```

[Example in Babel Playground](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=entry&corejs=3.6&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABACxgFWQUwE6cQCgEpEBvAKEUsVElgUQEMjSKq3coRskByZOADYMerSgF8yEsjWjwkAIwLESYoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D)

### Version

1.2.110

**Comment by ruiconti** [comment]
This is happening because of the compile target. If you change the target to any version after `es5`, you should be able to get the expected result —which is legal ES5 code. I, however, lack the context to judge if that's an actually bug or an intentional behavior from `swc` team.

@kdy1, would you mind clarifying it? I'm planning to binge on this one.

**Comment by RiESAEX** [comment]
i guess is a problem in ecma_transform_compat::es2015::function_name

**Comment by kdy1** [comment]
I think this is a bug.
Also, I think the `block_scoping` pass is the problem.

https://play.swc.rs/?version=1.2.127&code=H4sIAAAAAAAAA6vmUgCCtNK85JLM%2FDyFRA1NhWqwEAgUpZaUFuUpqGfk5ySqg0VruWq5ALAFoiMzAAAA&config=H4sIAAAAAAAAA2WQwU7EMAxE%2F8XnvXLpjdWCQAL%2BwUqnJSiJI8ddWlX9dxJQyyJu0UxmNH4rRZ%2F8sFA3cCg40Udx1K2UWQu0vcqSjGfqCC5yceqz0Yn6JXH07jlmUaPOdKrZrP7KhlfYu%2FS7OEzJmZd09unQMLfYBQNPwR5V4l%2FjjSNKZodbq4cTZRMt%2F5UzBlE8zLdjTPILrgj3n%2BwP0X%2FvrQP5R9nqP%2BVUajy2YwNGdstlL95jCnbWfJ2S%2BYhKgyeTyOYdba2EdYQ1SOWu0gkiBQdSzAZNHJ4QMn7n7%2BBXchKzopQjETmNYS%2FYtu0L0hFFsqYBAAA%3D
