### ISSUE TITLE
double identifier not throwing 

### ISSUE THREAD

**Issue by idan-at** [swc-project/swc#2795]
### Describe the bug

Hey,

I see a difference between how babel and swc handles the attached code.
While `babel` throws `[SyntaxError: unknown: Identifier 'ok' has already been declared. (2:8)`, `swc` succeeds.

I see that in general (regardless of `import` statements, `swc` doesn't catch duplicated identifiers. a similar example is just:
```js
const x = 1;
const x = 2;
```

### Input code

```typescript
import { hi } from 'foo';
import { hi } from 'foo';
```

### Config

```json
{}
```

### Expected behavior

I'd expect SWC to throw a similar error as Babel.

### Version

1.2.110

**Comment by idan-at** [comment]
@kdy1 I'd be glad to contribute if you can guide me

**Comment by kdy1** [comment]
For first, you can create a trait representing `Rule`s like https://docs.rs/deno_lint/0.19.0/deno_lint/rules/index.html

IMO, `swc_ecma_lints` in https://github.com/swc-project/swc/pull/2763 is the right crate to store the trait and implementations.

After declaring `Rule`, you can look for variable declarations with the same symbol and same span hygiene. You can refer to https://docs.rs/swc_ecma_ast/0.59.0/swc_ecma_ast/struct.Ident.html to know what does `span hygiene` means.

Thanks to the [`resolver`](https://docs.rs/swc_ecma_transforms_base/0.48.0/swc_ecma_transforms_base/resolver/fn.resolver_with_mark.html), you can just check if two variable declarations exist.

**Comment by idan-at** [comment]
Thanks. I'm a bit confused TBH, so let me make sure I understand.

1. wait for #2763 to be merged.
2. Extend the `Rule` trait (add a `lint` method that takes a program and runs on it?)
3. Create a `DuplicateIdentifier` rule that has the logic to check the scenarios (named imports and variable declarations)
4. Use the resolver on the spans I find duplications (can you explain further how?)

Also, can you refer me to the tests so I can add a similar one?
