### ISSUE TITLE
Attempted import errors in external libraries

### ISSUE THREAD

**Issue by dsuresh-ap** [swc-project/swc#2797]
### Describe the bug

Some external libraries causing compilation failures.
Ex.
* Attempted import error: 'CalendarContainer' is not exported from 'react-datepicker'.

* ./node_modules/draft-js-utils/esm/getEntityRanges.js
    Attempted import error: 'OrderedSet' is not exported from 'immutable'.

(just few examples)

It is most likely I have set swc-loader incorrectly for the node_modules folder.

### Config

```json
//Using Craco to modified CRA and remove babel

// add swc-loader for non app code
    addAfterLoader(webpackConfig, loaderByName('babel-loader'), {
      test: /\.(js|mjs)$/,
      exclude: paths.appSrc,
      loader: require.resolve('swc-loader'),
      options:{
              jsc: {
                externalHelpers: true,
                target: 'es5',
                parser: {
                      syntax: 'ecmascript',
                      jsx: true,
                      dynamicImport: true,
                      exportDefaultFrom: true
                    }
              },
            },
    });
// Add swc-loader for app code
    addAfterLoader(webpackConfig, loaderByName('babel-loader'), {
      test: /\.(js|mjs|jsx|ts|tsx)$/,
      include: paths.appSrc,
      loader: require.resolve('swc-loader'),
      options:{
              jsc: {
                externalHelpers: true,
                target: 'es5',
                parser: {
                      syntax: 'typescript',
                      tsx: true,
                      dynamicImport: true,
                    }
              },
            },
    });

    // remove the babel loaders
    removeLoaders(webpackConfig, loaderByName('babel-loader'));
```

### Expected behavior

Compilation is successful.

### Version

1.2.66

**Comment by dsuresh-ap** [comment]
It looks like to fix this issue I had to install the `@types` version of certain packages. Is there some config I can modify to not have to replace every package that has this issue?

Ex. for `react-scroll-sync` I had to install `@types/react-scroll-sync`.

**Comment by Frikki** [comment]
Is there any verification that this is a bug? Or can we close the issue?

**Comment by kdy1** [comment]
Thanks!
