### ISSUE TITLE
No info about sourceMaps in the docs

### ISSUE THREAD

**Issue by dy** [swc-project/swc#285]
Hi @kdy1!
I'm developing [swcify](https://github.com/dy/swcify) transform for browserify, had trouble making sourceMaps available from `swc.transform` output, turns out they're enabled via undocumented options:
```ts
sourceFileName: string
sourceMaps: boolean
```
https://github.com/swc-project/cli/blob/master/src/file.ts#L176-L187

Would be nice to have it in docs.

While at it - I just wonder, would you accept that project as donation to swc-project?

**Comment by kdy1** [comment]
I documented it and I would be happy to accept it
