### ISSUE TITLE
jsc.paths: invalid path added to `require` in some cases

### ISSUE THREAD

**Issue by Strate** [swc-project/swc#2862]
### Describe the bug

I've tried to enable `jsc.paths` in my project, but with no luck, because swc generate wrong paths in some cases. I've extracted reproducible project to https://github.com/Strate/swc-paths-test

### Input code

```typescript
Test project with reproducible bug located here: https://github.com/Strate/swc-paths-test

Steps:

git clone git@github.com:Strate/swc-paths-test.git
cd swc-paths-test
npm install
npm test
Expected output:

SUCCESS
Actual output:

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './core/utilFile'
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2019",
    "baseUrl": "./src",
    "paths": {
      "core/*": ["core/*"],
      "utils/*": ["utils/*"],
      "core": ["core"],
      "utils": ["utils"]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://github.com/Strate/swc-paths-test

### Expected behavior

swc expected to generate valid path to required file, using `jsc.paths` mappings

### Version

1.2.112

**Comment by kdy1** [comment]
I think this is fixed by https://github.com/swc-project/swc/pull/3142

**Comment by kdy1** [comment]
I'll re-close this after adding test

**Comment by Strate** [comment]
@kdy1 FYI - i've checked my repo with `@swc/cli@latest @swc/core@latest` with no luck. Maybe your fix is not published yet.

**Comment by kdy1** [comment]
Yeah it's not published.
