### ISSUE TITLE
Why generate `exports.AAA = void 0` when esm to commonjs?

### ISSUE THREAD

**Issue by anchengjian** [swc-project/swc#2877]
### Describe the bug

Why does `export { AAA }` generate `exports.AAA = void 0, exports.AAA = a` instead of `exports.AAA = a` ???

### Input code

```typescript
function AAA() {
  console.log("this is AAA");
}

export function BBB() {
  console.log("this is BBB");
}

export {
  AAA
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": {
        "arguments": true,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": true,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": false,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": false,
        "typeofs": true,
        "unsafe": true,
        "unsafe_arrows": true,
        "unsafe_comps": true,
        "unsafe_Function": true,
        "unsafe_math": true,
        "unsafe_symbols": true,
        "unsafe_methods": true,
        "unsafe_proto": true,
        "unsafe_regexp": true,
        "unsafe_undefined": true,
        "unused": true
      },
      "mangle": {
        "toplevel": true,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "strictMode": false,
    "lazy": true,
    "noInterop": true,
    "ignoreDynamic": true
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.112&code=H4sIAAAAAAAAA0srzUsuyczPU3B0dNTQVKjmUlBIzs8rzs9J1cvJT9dQKsnILFYAIqC0kqY1Vy0XV2pFQX5RiUIaTKOTkxM%2BjUBpVI0glUDTuGqtAZUwf3Z8AAAA&config=H4sIAAAAAAAAA42UvY7bMAzH38VzhnYoUGQuCnS4ZxAUiXaYWqIhUr64wb17KceWY%2FeGbuZPpPTnlx%2FNjV1zfjSDTQypfPEUxd6bcwMuWHYJB2lO6qaotT3Dx6kRmzqQ4sLf9KwnYmjOkjKcmoAR26lc5CgMCZjLtwbkAFF4dbMp0Xu1LkQ92PiPbSwbjAIdpHrmqO%2FtwGBG%2BwqDZoBMcYeygDdDouGFRo%2BCFDWVlXmw3jjyNQePCZzgCLzkrEgvUZ%2FIKmwPPVxy15XaPYNhtH22Ui%2BD%2B1wFfbLGXQlZTJsjH9BO6hM9s1y8sDUJJKe4%2BtwI464QvwFUZ2%2BZow0v%2BmfeahuO6BM3jK02UaZKtcGbrAidZmcQ25pikQ1JEKpTAp8dlBTddvkCdxkxejDQtlrvGszvKO76okqmAait51o3uz3%2BtMx%2BoBZYZuDIfqommbuxw8HK9YB4Chfqj%2FEB5Er%2BSLUEQgeWdG7vwwHm6EHLC37jmVdLdyvY2JURezRCQw8j9P%2FX2k%2FYkHAsrVqmap0h%2BL5V3%2BpI4Ncv62p%2FFAHk8yJAy65LrkUMFG%2Bsm86S0Ent02y9zYuzTor9M9VBoV%2B6uvr2CrCLlODHpFLRbQkvP4xVHr8tAubzv5UbkK%2BhBAAA

### Expected behavior

function a() {
    console.log("this is AAA");
}
function b() {
    console.log("this is BBB");
}
exports.BBB = b, exports.AAA = a;

### Version

1.2.112

**Comment by kdy1** [comment]
It's to follow spec in cases of exceptions.
