### ISSUE TITLE
`Unterminated string constant` with TSX and children

### ISSUE THREAD

**Issue by Ayc0** [swc-project/swc#2896]
### Describe the bug

When some JSX is used in the same line as some string that looks like JSX, it crashes with `Unterminated string constant`

### Input code

```tsx
<div>children</div>; '<>hello</>';
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

### Playground link

The "copy" link doesn't seem to work due to permissions issues 😕

### Expected behavior

It should compiled to
```js
/*#__PURE__*/ React.createElement("div", null, "children");
'<>hello</>';
```

### Version

Only the 1.2.113 (it worked in the 1.2.112)

### Additional context

Adding a line break works:

![image](https://user-images.githubusercontent.com/22725671/143688568-1f793a74-c5da-4f5d-b840-d865f4b9deae.png)

It also works if the string isn't JSX like:

![image](https://user-images.githubusercontent.com/22725671/143688593-c0d425c4-f39d-40ed-adf5-7a54e34feaf1.png)

**Comment by rianmcguire** [comment]
Also get the same error if there are quote characters within the JSX.

[Playground link](https://play.swc.rs/?version=1.2.118&code=H4sIAAAAAAAAA7NJySyz888vKNZT8CxRL1ZIzFNILSrKL7LRB0lYcwEAxGVexyAAAAA%3D&config=H4sIAAAAAAAAA0WOSw7DIAxE7%2BJ1tu2CO%2FQQiDoRFT95HKkIcfcCSpXdaGb8PI0%2BcGQaFStgmQo1qf2SIa2F4cQXpY0Uw1I5uQ9t5WAdDcZjRCFnMJndBvBG0Se%2F1wlyORZh4I5sOsK%2F2Qco5vc5jbZ%2BLeCT%2Bs247jxeV3EN%2BAFJDkBftAAAAA%3D%3D)

![image](https://user-images.githubusercontent.com/1201065/145337623-3a15205f-aca8-442e-8335-0426ef7ef4ea.png)
