### ISSUE TITLE
Incorrect sourcemap generated for code with indented multiline template literals

### ISSUE THREAD

**Issue by airhorns** [swc-project/swc#2900]
### Describe the bug

In the process of trying to debug why jest is not able to update inline sourcemaps for my project, I think I have found an swc bug where some given input code gets an incorrectly generated source map. See below!

### Input code

```typescript
export {};

describe("whatever", () => {
  test("it can find inline snapshots", () => {
    expect([1, 2]).toMatchInlineSnapshot(`
      Array [
        1,
        2,
      ]
    `);
  });

  test("it can find two inline snapshots", () => {
    expect([3, 4]).toMatchInlineSnapshot();
  });
});
```

### Config

```json
{ "sourceMaps": "inline", "jsc": { "target": "es2020", "externalHelpers": true } }
```

### Playground link

https://play.swc.rs/?version=1.2.113&code=H4sIAAAAAAAAA42OQQuCQBCF7%2F6Kh6cVlkDrJgUdO3TqKILbOuFC7MrukIb43xMxISjoMPPewHvMR33rPGMY8yiqKWhvriTirlFMD%2FKxhEiwP2CIAKbAIjYMrSxuxtYw9m4sIVjVhsZx%2BIgD1LekWRSpRFYmG3Znxbo5zaXL0hHVHAWO3qsniuUCUrna7G3LWaskn3Sc9lco7ty%2FYFuJ3U%2Bw9cs0L6waQO0mAQAA&config=H4sIAAAAAAAAA0WNSQ6DMAxF7%2BI1i5Yld%2BAQUWpQUCb5J1IjlLvXoFTs%2FKfnkw5YWk7KRsByXWixmC8tVFpmWHG50EQFam3Gg7sKIzsXrTDm1%2FzW2KcEHoWJgotuaxfMppCFgScycff%2FZldWSJ96Gef9T5k6CSkeoP6AxthhHe0iVTVSFcuryconF72LTP0HIni%2FHNMAAAA%3D

### Expected behavior

The sourcemap matches the input content, and doesn't have ranges in the output content with no source mapping at all. I find this is easiest to see with https://evanw.github.io/source-map-visualization/, here's a screenshot of the output file:

![CleanShot 2021-11-27 at 21 45 23@2x](https://user-images.githubusercontent.com/158950/143726861-d2aa543f-750c-4694-a92a-d9ecc38fa5ee.png)

That shows how many of the lines in the output are mapped incorrectly unless I am missing something!

### Version

1.2.112

**Comment by ihm-tswow** [comment]
https://github.com/swc-project/swc/issues/2185

**Comment by alexander-akait** [comment]
@kdy1 I think it will be closed in favor https://github.com/swc-project/swc/issues/2185
