### ISSUE TITLE
[mangle] exporting from along with importing the same variable name doesn't work

### ISSUE THREAD

**Issue by neuronetio** [swc-project/swc#2924]
### Describe the bug

just run the code

### Input code

```typescript
import { y } from 'z';
export { y } from 'z';
```
### Output

```javascript
import { y as a } from 'z';
export { a as y } from 'z'; // <- a is not defined in z
```

### Playground link

[Playground](https://play.swc.rs/?version=1.2.111&code=H4sIAAAAAAAAA8vMLcgvKlGoVqhUqFVIK8rPVVCvUrfmSq3AJgwAW0YioS0AAAA%3D&config=H4sIAAAAAAAAA22PSwrDMAxE76J1FkkWpeQOPUMRrhLc%2BiMsJTQE371OyYdCVxqNHmJmgacY6BZgTEJpVTIHxTd0oDOTmGRZoQKVYvXohHJZMA2kBSFp67YpZxej0AZU4G2w%2Fbw%2B8xgGR6vSyI4mcgf0IuK7cSgS0JP8%2Bv0fj5OdUKnMyOfJ0vXQgj0m29RnUhM9J5Idz8Xy8TFukUrBb4kL5DP0%2FlduG6hppPwBXE3XBSkBAAA%3D)

### Expected behavior

exported value should keep proper name

### Version

1.2.114

**Comment by dsherret** [comment]
This also sometimes occurs when transforming and not mangling. It's a problem in the resolver code.
