### ISSUE TITLE
error with Unicode escape

### ISSUE THREAD

**Issue by RiESAEX** [swc-project/swc#2948]
### Describe the bug

`"\u{Dc00}" // Invalid unicode code point`

### Expected behavior

compile to `"\u{Dc00}"`

### Version

1.2.117

### Additional context

I found this in 
/crates/swc_ecma_parser/test/typescript/tsc/es6/unicodeExtendedEscaptes/unicodeExtendedEsacpesInString11

**Comment by jimberlage** [comment]
I tried fixing this in this commit:

https://github.com/jimberlage/swc/commit/6c6ef84621fd8624f373518ff53d9dab224a063f

It adds a test and uses the u32 value directly.  It looks like fixing this specific test might require something like Simon Sapin's [WTF-8](https://simonsapin.github.io/wtf-8/), which feels like something that's better left for a maintainer to decide.  But feel free to use the test and the code I have!

**Comment by kdy1** [comment]
@jimberlage I thought about this, but I failed to find a clear answer. I'll postpone this a bit. (Because API change is too big)
