### ISSUE TITLE
`sourceMaps: false` strill generates source maps

### ISSUE THREAD

**Issue by dy** [swc-project/swc#296]
```js
config.sourceMaps=false
swc.transformSync('code', config) // {code, map}
```
Is that planned behavior?

(Completely off-topic. Do you mind registering swc-project.github.io in [brave rewards](https://publishers.basicattentiontoken.org/) - I've sent you a tip there. That would facilitate donations - significantly. @kdy1 )

**Comment by kdy1** [comment]
I think you are using old version of swc.
`swc` packaged is renamed to `@swc/core`.
Currently there's a test for it. (https://github.com/swc-project/node-swc/blob/9047e3c08714097eef1a8400587e0867e8ee17e3/__tests__/module_test.js)

**Comment by dy** [comment]
Hm, there's not test with `sourceMap: false` flag like that from what I see:
```js
 const out = swc.transformSync('import foo from "foo"', {
        module: {
            type: "commonjs"
        },
        sourceMap: false
    });
```
I use the latest 1.0.30

**Comment by kdy1** [comment]
I fixed it and added a test for `sourceMaps: false`.

**Comment by kdy1** [comment]
Also I tried to set braverewards up, but it only says I need to verify my identity fully on uphold.com

**Comment by dy** [comment]
@kdy1 yes, you have to create uphold.com cryptowallet for donations - they use that as default financial backpoint. That's just a free wallet service - you can transfer coins then anywhere you want.
