### ISSUE TITLE
[Mangle] Doesnt change the names like expected (typescript)

### ISSUE THREAD

**Issue by ruessej** [swc-project/swc#2988]
### Describe the bug

Mangle doesnt make var a, b, c, ... and instead only let a

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "transform": {
      "optimizer": {
        "jsonify": {
          "minCost": 0
        }
      }
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.118&code=H4sIAAAAAAAAA8tLzE0tLkhMTlUISS0uUajm5VJQSK0oyC8qUUjNK81VKAGKuoIYYBkFiCpbBSVDJR2EgBFIxAhZxBgkYgwRqeXlwmWqEWXG1gIAydeBxL4AAAA%3D&config=H4sIAAAAAAAAA21QS24CMQy9i9csBhYIzZZ1z1BZg4NCk9iyDWKKcvcmdGBUqas8v5%2FsPOBiE4wPEFQj7cjm4niHEXwWskmjOGzArVEBk1Ftg2KxwJq7n8Vjjt%2B%2F4YtxiWHuMMdyZHMYh1p7BvVMbQKy3bDbtsrEbLSUbrp9CU6cRclslbCcE3XJWRLdKL2lLyL5nBKaFcxkf%2FnwDycab%2BjUXpZVinR4Y8OAGrfD69y%2BfObTddmgfcrziD3UdelXjX0sRtcr1R8cWxKAXQEAAA%3D%3D

### Expected behavior

The result should be like in 1.2.117:

```js
var Test;
(function(a) {
    var b;
    (function(a) {
        a["Test"] = "1";
        a["Test2"] = "2";
        a["Test3"] = "3";
    })(b || (b = JSON.parse("{}")));
    var c;
    (function(a) {
        a["Test"] = "1";
        a["Test2"] = "2";
        a["Test3"] = "3";
    })(c || (c = JSON.parse("{}")));
    a.testEnum = b, a.testEnum2 = c;
})(Test || (Test = JSON.parse("{}")));
```

### Version

1.2.118

**Comment by kdy1** [comment]
![image](https://user-images.githubusercontent.com/29931815/145026467-ade3d56b-e890-4782-82e6-d3804fd7b098.png)


Can you share your output?

**Comment by kdy1** [comment]
Oh, I see. Thanks!
