### ISSUE TITLE
Typescript compilation - Assignment Assertions

### ISSUE THREAD

**Issue by K-Jean** [swc-project/swc#2990]
### Describe the bug

When I tried to compile my application with assignment assertions swc crash. 

```
Error: error: Unexpected token `!`. Expected identifier, string literal, numeric literal or [ for the computed key
29 |     private!: boolean;
```

### Input code

```typescript
class Game {
    private!: boolean;
}
```

### Playground link

https://play.swc.rs/?version=1.2.118&code=H4sIAAAAAAAAA0vOSSwuVnBPzE1VqOZSAIKCosyyxJJURSuF4JKizLx0rloA3sXoGiMAAAA%3D&config=H4sIAAAAAAAAA0WNSQrDMAxF76J1Fk0WXfgOPYRxlODiCUmBGuO7Vw4u3Ul%2FeL%2FBmx2YBsUSI42LaxL7AQNSC7IjXwQWEFbpsIGx62PpRNEI8vbYVrVDzoxghC5cIPrkjzpYLsdCyDyratl0BvyRFBXzfg2h3XM38gn9z5g9z68ZHBP9Cwznsdi3AAAA

### Expected behavior

That I can use Assignment Assertions in typescript class

### Version

1.2.118

**Comment by dsherret** [comment]
It gets tripped up by the name `private`, which is a bug. A workaround is to use a different name. Same thing seems to happen for `public` and `protected`.

**Comment by Austaras** [comment]
Similar to #1219?
