### ISSUE TITLE
Non-leading `@jsxImportSource` pragma is emitted as import

### ISSUE THREAD

**Issue by nayeemrmn** [swc-project/swc#2992]
Using Deno with `--no-check`.

### Input code

```typescript
console.log(1);
/** @jsxImportSource foo */
console.log(<div></div>);
```

### Expected

In tsc, the pragma comment is ignored because there is code before it, and it must be a leading comment.
```ts
console.log(1);
console.log(/*#__PURE__*/ React.createElement("div", null));
```

### Actual

```ts
import { jsx as _jsx } from "https://esm.sh/preact/jsx-runtime";
console.log(1);
console.log(/*#__PURE__*/ _jsx("div", {}));
```

### Version

swc_ecma_transforms_react 0.53.0

**Comment by kdy1** [comment]
This is intended, as mdx-loader emits non-leading `/** @jsxImportSource foo */`

**Comment by nayeemrmn** [comment]
> This is intended, as mdx-loader emits non-leading `/** @jsxImportSource foo */`

I think this should be an extended compatibility option, since it doesn't comply with tsc. Or it's just an mdx-loader bug. In Deno this case can lead to something like a panic because these aren't picked up at the static "prepare module load" step but the import is emitted.

**Comment by kdy1** [comment]
But babel supports this by default.

**Comment by nayeemrmn** [comment]
@kdy1 It doesn't look like it: https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUBGAlAbgFAHoAqQgAgAEArCADwEkBbABxACcAXAZRAFcXhYSAMxAgShfLlCQYCJGgA8AEwCWANwB88-Co04gA whereas [when the pragma is on top](https://www.typescriptlang.org/play?#code/PQKhAIAECsGcA8CSBbADgewE4BcDK6BXTAYwFNwAzddcEYAKGPQDtZ0AbUgOnfQHMAFAEYAlAG5GLNpx78BAHgAmASwBuAPnnAVG8UA), `React.createElement()` is replaced with `_jsx()` showing the pragma is respected only when leading.

One thing I couldn't figure out is that swc _does_ seem to be scanning leading comments only: https://github.com/swc-project/swc/blob/017392aa5b681e4a8240259e7e26709b7160d623/crates/swc_ecma_transforms_react/src/jsx/mod.rs#L929-L934 so I don't know how this is the current behaviour.

**Comment by kdy1** [comment]
Why are you linking to the typescript playground?

**Comment by kdy1** [comment]
FYI, https://github.com/swc-project/swc/blob/017392aa5b681e4a8240259e7e26709b7160d623/crates/swc_ecma_transforms_react/src/jsx/mod.rs#L1038-L1045
This is the reason.

**Comment by nayeemrmn** [comment]
> Why are you linking to the typescript playground?

Oops :P I searched "babel TS playground" and used the first link without looking. Babel does indeed match current swc behaviour. I guess we'll keep the current work around...

**Comment by kdy1** [comment]
I think patch will be quite simple.
