### ISSUE TITLE
Export declaration with specifier has export specifiers identifiers tied to local declarations

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#2996]
### Describe the bug

An export declaration (swc: named export) with module specifier's export specifiers are getting resolved as identifier references. ~~I have a fix incoming.~~

### Input code

```typescript
import { Ident } from "./ident";

export { Ident } from "./ident";
```

### Output Code When Mangled

```typescript
import { Ident as a } from "./ident";
export { a as Ident } from "./ident";
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "transform": {
      "optimizer": {
        "jsonify": {
          "minCost": 0
        }
      }
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.118&code=H4sIAAAAAAAAA8vMLcgvKlGoVvBMSc0rUahVSCvKz1VQ0tPPBPGVrHm5eLmS8%2FOK83NS9XLy0zXAyjTBwqkVhLQCAG1DNttdAAAA&config=H4sIAAAAAAAAA21QS24CMQy9i9csBhYIzZZ1z1BZg4NCk9iyDWKKcvcmdGBUqas8v5%2FsPOBiE4wPEFQj7cjm4niHEXwWskmjOGzArVEBk1Ftg2KxwJq7n8Vjjt%2B%2F4YtxiWHuMMdyZHMYh1p7BvVMbQKy3bDbtsrEbLSUbrp9CU6cRclslbCcE3XJWRLdKL2lLyL5nBKaFcxkf%2FnwDycab%2BjUXpZVinR4Y8OAGrfD69y%2BfObTddmgfcrziD3UdelXjX0sRtcr1R8cWxKAXQEAAA%3D%3D

### Expected behavior

Should remain as `export { Ident } from "./ident";`

### Version

1.2.118

**Comment by kwonoj** [comment]
this repro looks same as https://github.com/swc-project/swc/issues/2924 ?

**Comment by dsherret** [comment]
Yup, my search had "export declaration" and that filtered that one out.

Duplicates #2924.
