### ISSUE TITLE
Comments in the wrong row

### ISSUE THREAD

**Issue by ruessej** [swc-project/swc#2999]
### Describe the bug

Look at the playground

### Playground link

https://play.swc.rs/?version=1.2.118&code=H4sIAAAAAAAAA9PXD0ktLuHlSs0rzVUAMRWqebkUICxbBSUQraTDy1ULADcmvf0oAAAA&config=H4sIAAAAAAAAA0WOsY6DQAxE%2F8U1RS4l7aVJkY%2BwFoMWsfbKNtJtIv49JpxI53kzGs8LZkvQv8AV2UbRsgupnkt%2Bku5iNuE8tv0smX%2FFHPrLtm0dVFQ7MtbY8Q968FbJkubq0IFboBEXow4GSqLoovZFjbHkdC9V1P9ptDrqRKGB7Hq5%2FkCgIsO60Gdm9IeVpBTh2eKJuebkZ%2BkhHzJEzHUNsuCznTbLnZ1U6knyxKJ0O7Z8V5ismuiB1Y6e7Q09Jo1nKgEAAA%3D%3D

### Expected behavior

"use strict";
//Test
var Test;
(function(Test) {
    Test["Test"] = "Test";
})(Test || (Test = JSON.parse("{}")));

### Version

1.2.118

**Comment by ruessej** [comment]
I have a website with a code editor ```TS``` and the user can see the generated ```JS``` code

**Comment by Austaras** [comment]
If we merge multiple enum declaration in the future, what would be the expected result?

**Comment by ruessej** [comment]
From my side no longer necessary
