### ISSUE TITLE
EcmaScript lexer is inefficient

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#3]
- [ ] It currently pushes one char at a time. It should chunk to amortize allocations.

Current code is similar to
```rust
let mut buf = String::new();
loop {
   // xxx
   buf.push(c);
}
```
Obviously, this almost always allocate and reallocates quite frequently. 

-----

 - [x] It allocate needlessly while tokenizing numeric literals.

Noticeable parts are

```rust

let s = format!("{}", val);
// if it contains '8' or '9', it's decimal.
if s.contains('8') || s.contains('9') {}

```

```rust
// It's Legacy octal, and we should reinterpret value.
let val = u64::from_str_radix(&format!("{}", val), 8)
    .expect("Does this can really happen?");
let val = format!("{}", val)
    .parse()
     .expect("failed to parse numeric value as f64");

```

```rust
val = format!("{}.{}", val, minority).parse();
```

**Comment by nicoburns** [comment]
Would it makes sense for lexing to generate `&str`s which point into the original buffer and avoid allocating altogether (except once per file)?

**Comment by kdy1** [comment]
Now we can utilize `uncons_while()`

https://github.com/swc-project/swc/blob/eb2a2a7f156dab5c87ab7f828d98a8dc9efd78c5/ecmascript/parser/src/lexer/input.rs#L103-L140

`SourceFileInput` stores source code as `String` so we can slice and copy it instead of extending String byte by byte.


I expect this task to be easy.
