### ISSUE TITLE
[Parser] jsx fragment shouldn't be a fragment's child

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#300]
Spec: https://facebook.github.io/jsx/

Grammar:
```
JSXFragment :
    < > JSXChildren < / >

JSXChildren :
    JSXChild JSXChildren

JSXChild :
    JSXText
    JSXElement
    { JSXChildExpression }

```

That's means is say this is not correct ?

```jsx
<> 
    <App2></App2>
    <> </>
</>
```

**Comment by kdy1** [comment]
I postponed this issue because babel currently supports 
```jsx
<> 
    <App2></App2>
    <> </>
</>
```

**Comment by koba04** [comment]
The syntax has been allowed in https://github.com/facebook/jsx/pull/97, but it hasn't been synced to the website yet. https://github.com/facebook/jsx/issues/128
I think it's fine `swc` allows the syntax, so this issue can be closed.

**Comment by kdy1** [comment]
Thanks!
