### ISSUE TITLE
add write option to swcpack

### ISSUE THREAD

**Issue by souporserious** [swc-project/swc#3012]
### Describe the feature

Hello, not sure if this is too preemptive since the bundler is still being worked on, but as a feature request I'm wondering if there can be a `write` option like [esbuild](https://esbuild.github.io/api/#write).

I could see this being similar where it doesn't write any files to disk and instead returns the bundled code. I'm currently achieving this in esbuild by doing the following:

```
  const result = await esbuild.build({
    entryPoints: [componentReadmePath],
    target: 'esnext',
    format: 'esm',
    bundle: true,
    write: false,
    plugins: [xdm()],
    external: ['react', 'react-dom'],
  })
  const [bundled] = result.outputFiles
  const decoder = new StringDecoder('utf-8')
```

I'm not sure how the MDX mechanism would work, but would love to stay in SWC entirely in the future if possible 😊

**Comment by kwonoj** [comment]
Have you tried `@swc/core`'s `bundle`? https://github.com/swc-project/swc/blob/main/node-swc/src/index.ts#L197

Essentially cli wraps those to write into file. (https://github.com/swc-project/cli/blob/master/src/spack/index.ts#L57)

**Comment by souporserious** [comment]
Amazing 🎉 I'll play with this tomorrow, thanks for pointing that out! I'll close this for now then since this sounds achievable.

**Comment by souporserious** [comment]
So from what I can tell, I can't do exactly the same as esbuild since they have a plugin system. I'm wondering if it is plausible to have a similar API to resolve imports and be able to transform contents for things like MDX.

**Comment by kwonoj** [comment]
There's wip plugin, you can see gh discussions for details. It is not same as esbuild does but in either cases I think that's separate to this issue.
