### ISSUE TITLE
Source maps break with multiline comments

### ISSUE THREAD

**Issue by ihm-tswow** [swc-project/swc#3013]
### Describe the bug

a3bd6aea54f8ad6eacbcb1cb67cb19c6c1cd2be8 fixes sourcemaps for string templates, but the issue remains for multiline comments.

### Input code

```typescript
describe("multiline comments", () => {
    it("test1", () => {
        expect(false).toBe(true);
    });

    it("test2", () => {
        /**/
        expect(false).toBe(true);
    });

    it("test3", () => {
        /*
         *
         */
        expect(false).toBe(true);
    });

    it("test4", () => {
        expect(false).toBe(true);
    });
});
```

### Config

```json
{
    "module": {
        "type":"commonjs"
    },
    "exclude":[".*.js$",".*\\.d.ts$"],
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
        },
        "target":"es2016",
    },
    "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.118&code=H4sIAAAAAAAAA0tJLU4uykxK1VDKLc0pyczJzEtVSM7PzU3NKylW0lHQ0FSwtVOo5lIAgswSDaWS1OISQzRxEEitKEhNLtFIS8wpTtXUK8l3StUoKSpN1bQGq6gF0ihGGGExQl9LS59c84yxmgdnKiAzybbEhCx%2FAzEAlsytqGQBAAA%3D&config=H4sIAAAAAAAAA0WNSQrDMAxF76J1Fm0XXeQOOYRxleDgCX0baoLvXiW4ZKc%2FPR20w9J8UDYClvNCi8V8aabSMsOKy4UmKlBrNR7cVRjZuGiF8Xo83xr7lMCjMFFw0a3thNkUsjBwRyZu%2Ft%2FsygrpU0%2FjuP4pUychxR3Ub9AYOyyjXaSqRqpieTFZ%2BeSid5Gp%2FwC0naCm0wAAAA%3D%3D

### Expected behavior

Multi-line comments should not break sourcemaps

### Version

1.2.119

### Additional context

Issue was also present in 1.2.112 (I should've probably made a separate issue for that, my mistake): 
https://github.com/swc-project/swc/issues/2185#issuecomment-978209846

Checking both 1.2.112 and 1.2.119 on the playground verifies nothing changes for multiline comments, so it's at least not a new issue.

**Comment by kdy1** [comment]
Yeah, I should apply same patch for comments, but I forgot it.
I'll fix this in a near future

**Comment by ihm-tswow** [comment]
It appears that this bug is still in effect for 1.2.120 and 1.2.121. You can verify the output sourcemap on the playground link above stays the same for versions 1.2.118/1.2.120/1.2.121

**Comment by kdy1** [comment]
Test I added:

<img width="1367" alt="스크린샷 2021-12-20 오후 5 35 16" src="https://user-images.githubusercontent.com/29931815/146737285-2ca0d9a0-94e4-434c-8866-585262a816d8.png">

Playground version:

<img width="1564" alt="스크린샷 2021-12-20 오후 5 36 32" src="https://user-images.githubusercontent.com/29931815/146737296-40a563e5-9e33-4d6a-85d0-377a42e07bde.png">


![image](https://user-images.githubusercontent.com/29931815/146738001-711616b6-1244-46a0-a11c-f3275fdb8efc.png)

**Comment by kdy1** [comment]
For playground version, I copied the output file and feed it to source map visualizer.
