### ISSUE TITLE
[Lexer/Parser/Transform] jsx element name

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#302]
Spec: https://facebook.github.io/jsx/

Grammar:
```
JSXElementName :
    JSXIdentifier
    JSXNamespacedName
    JSXMemberExpression

JSXIdentifier :
    IdentifierStart
    JSXIdentifier IdentifierPart
    JSXIdentifier NO WHITESPACE OR COMMENT -
```

The JSX spec is not defined what is a `IdentifierStart`, but [react recommend naming components with a capital letter](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized), since them use the first letter of element name to decide create built-in component or user-defined component.

When we talk about `JSX`, actually we talking is about `react` (as far as I know, just `react` used `JSX`).

So, maybe we should restriction the jsx element name on the lexer parse stage ?

I just suggestion use [crates/unicode-xid](https://crates.io/crates/unicode-xid) to do that check, make sure element name is a [Unicode Identifier](http://www.unicode.org/reports/tr31/), and first character should be can `.to_lowercase()` or `.to_uppercase()` ( [SpecialCasing.txt](http://ftp.unicode.org/Public/UNIDATA/SpecialCasing.txt) ), or just allow ASCII letters `A-Z` and `a-z` be first element name's character.

Example Code:

```rust
fn parse_elem_name(&mut self) {
    let ch = self.read_char();
    let mut name: Vec<char> = Vec::new();
    if UnicodeXID::is_xid_start(ch) {
        name.push(ch);
        loop {
            self.bump();
            let ch = self.read_char();
            if !UnicodeXID::is_xid_continue(ch) {
                break;
            }
            name.push(ch);
        }
    }
    if name.len() > 0 {
        let first_char = name[0];
        if first_char.is_ascii_alphabetic() {
            // Good
        } else {
            // Bad
        }
    }
}
```

Currently JSXElementName transform like this:
```jsx
// React.createElement('app', null);
<app />
// React.createElement(App, null);
<App/>;
// React.createElement($App, null);
<$App/>;
// React.createElement(_App, null);
<_App/>;
```

Ref:

*   HTML static element names: [servo/servo/components/atoms/static_atoms.txt](https://github.com/servo/servo/blob/master/components/atoms/static_atoms.txt)
*   JSX In Depth: [User-Defined Components Must Be Capitalized](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)
*   Determine if a char is a valid identifier for a parser and/or lexer use [docs.rs/unicode-xid](https://docs.rs/unicode-xid/0.1.0/unicode_xid/trait.UnicodeXID.html#tymethod.is_xid_start) follow [Unicode Standard Annex #31](http://www.unicode.org/reports/tr31/)
*   [SpecialCasing.txt](http://ftp.unicode.org/Public/UNIDATA/SpecialCasing.txt)

**Comment by kdy1** [comment]
You mean there should be a lint for component names like `app` but not for `div` nor `App`.
Is this correct?

**Comment by LuoZijun** [comment]
@kdy1 

I mean is:

>    make sure element name is a Unicode Identifier, and first character should be can .to_lowercase() or .to_uppercase() ( SpecialCasing.txt ), or just allow ASCII letters A-Z and a-z be first element name's character.

**Comment by kdy1** [comment]
Is this correct?
There is a test copied from babel which uses non-ascii character as start of tag name.

https://github.com/swc-project/swc/blob/a2144bbbf59c93ff5fe71d16d562197aefc073b4/ecmascript/parser/tests/jsx/basic/6/input.js#L1
