### ISSUE TITLE
Change definition of ClassProp

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#3026]
### Discussed in https://github.com/swc-project/swc/discussions/3025

<div type='discussions-op-text'>

<sup>Originally posted by **Austaras** December 12, 2021</sup>
Change `key` field to `PropName` and remove `computed`. There's two reasons:
1. ClassProp key and ClassMethod key are both `ClassElementName` in spec, it's better to unify them
![图片](https://user-images.githubusercontent.com/15013925/145755879-8732dcce-d492-43e7-893c-e6fe1c96c926.png)
![图片](https://user-images.githubusercontent.com/15013925/145755905-c663151d-37ca-419d-b031-f0cdf89c4840.png)
2. Current definition may generate invalid state. When `computed` is false, `key` could only be `Number` `String` `BigInt`

Do we need to wait for a new major release to fix this?</div>

**Comment by kwonoj** [comment]
I feel this is breaking change?

**Comment by Austaras** [comment]
It surely will be a break change for rust side, but it may be fine for js side?

**Comment by kwonoj** [comment]
If JS plugin's visitor is not affected yes.
