### ISSUE TITLE
Referencing a compiler-made-up yet undeclared variable in compiled output.

### ISSUE THREAD

**Issue by majg0** [swc-project/swc#3029]
### Describe the bug

Using latest swc.

Accessing `.name` (possibly other fields too) from the static class does not work when using a constructor.

See the compiled output in additional context below.

Specifically, this output:

```ts
        this.name = _class.name;
```

does not work, because `_class` is never even declared, much less defined.

### Input code

```typescript
function boom() {
  return function(a, b, c) {};
}
export class Foo {
  private name = Foo.name;

  constructor(
    @boom()
    private foo,
  ) {}
}
```

### Config

```json
{
  "test": ".*.ts$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020",
    "keepClassNames": true
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Expected behavior

Either

```ts
        this.name = Foo.name;
```

or

```ts
        this.name = _class1.name;
```

### Version

1.2.119

### Additional context

```ts
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.Foo = void 0;
var _class1;
function boom() {
    return function(a, b, c) {
    };
}
var _dec = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:paramtypes", [
    void 0
]), _dec1 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", Function), _dec2 = function(target, key) {
    return boom()(target, undefined, 0);
};
let Foo = _class1 = _dec2(_class1 = _dec1(_class1 = _dec((_class1 = class Foo {
    constructor(foo){
        this.foo = foo;
        this.name = _class.name;
    }
}) || _class1) || _class1) || _class1) || _class1;
exports.Foo = Foo;
```

**Comment by majg0** [comment]
Funny, I also had this problem using Nest.js and a ping logger, I just narrowed it down as much as possible so it's easier to repro :D

**Comment by kwonoj** [comment]
This seems fixed in latest : 
https://play.swc.rs/?version=1.2.148&code=H4sIAAAAAAAAAzWNQQoDIRAE74J%2F6KMByQdCIKf8wxWFhezMMo4hEPbvcXBz6%2B6i6Nop68qEhXkLF3y9A6RoF0I9WUgRS0Qe9Lh5d3hXPjuLIr9Sa3gyT22X9Z20gNJWcLf9anEoRjNTU%2BlZWYJ14DE%2FZ%2FnLlTnaYmfj6wfIZfjQoAAAAA%3D%3D&config=H4sIAAAAAAAAA02OOw6DQAxE7%2BKaAlFum7TJHaxlQCH7k22kIMTd2VUUkc6y5%2FnNTot6cjsVFoW0Sbdk%2FCFHthWol1cx6si0riYOio5G%2BCxsWZScyYqjnoWTTlli%2BxAws9%2Fuv9Q39Ic9YDyy8UWzzLCqhA790FfdGyi3wKpPjrg0MY9rQHO0chXwOcacFqXjOAFR%2BLzzywAAAA%3D%3D
