### ISSUE TITLE
Empty output for latest swc/cli@0.1.54

### ISSUE THREAD

**Issue by aelbore** [swc-project/swc#3033]
### Describe the bug

Empty output for latest swc/cli@0.1.54

### Input code

src/index.ts
```typescript
export function log() {
  return 'Hello World'
}
```

package.json script
```json
  "scripts": {
    "build": "swc ./src/index.ts -o ./dist/index.js"
  },
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true
    },
    "target": "es2020"
  }
}
```

### Expected behavior

it should have build output

### Version

@swc/cli@^0.1.54 and @swc/core@^1.2.120

### Additional context

This works when cli is at version 0.1.52

**Comment by kwonoj** [comment]
@aelbore looks like this is regression from https://github.com/swc-project/cli/commit/47135083bcc89a3dd3a2611cad5c87647c567610#diff-dc05644f5a7f98a1a756a19dca85e9f46988f1271bef6e01f1c26886a511f08aR38, probably better to file an issue there?

**Comment by aelbore** [comment]
@kwonoj noted thanks

**Comment by aelbore** [comment]
Close this file issue in swc/cli
https://github.com/swc-project/cli/issues/97
