### ISSUE TITLE
_class is not defined when using with default Nest.js Logger

### ISSUE THREAD

**Issue by RIP21** [swc-project/swc#3035]
### Describe the bug

Somehow when you use `nestjs-pino` or just a regular `Logger` implementation of Nest js and pass down there a class like `UserService.name` it fails with weird `_class is not defined` error.

### Input code

```typescript
-
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2018"
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Playground link

https://gist.github.com/RIP21/e9d1ac60fab076ec6c2b01dd17d8a855

### Expected behavior

It shouldn't error out. The comparison between TSC output and SWC is pretty big and some weird `_class || _class || _class` noted there in `swc` output that may be the root cause of this issue. 

### Version

1.2.120

### Additional context

Above is mentioned the `gist` with all the code that you can download and just run `npm install` `npm run start` to get the error.

**Comment by carlosasin** [comment]
Hello @RIP21 

Can you try to replace AppController.name to this.constructor.name?

**Comment by arkraft** [comment]
I had the same problem. After using `this.constructor.name`, like suggested by @carlosasin the problem was fixed
