### ISSUE TITLE
Wrong import from regenerator-runtime when using noInterop: true

### ISSUE THREAD

**Issue by meshulam** [swc-project/swc#3036]
### Describe the bug

I'm trying to run swc with `__esModule` interop disabled. When I use async functions the transformed code always references `require('regenerator-runtime').default`, even though `regenerator-runtime` is published as a commonjs module with non-default exports for its various functions: https://github.com/facebook/regenerator/blob/main/packages/runtime/runtime.js

This results in a `TypeError: Cannot read property 'mark' of undefined` error when running the emitted output code.

### Input code

```typescript
export async function foo() {
  console.log('hi');
}

foo();
```

### Config

```json
{
  "module": {
    "type": "commonjs",
    "strict": true,
    "noInterop": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA0utKMgvKlFILK7MS1ZIK81LLsnMz1NIy8%2FX0FSo5lIAgqLUktKiPIXE8sTMEoWAovzc%2FMziVL2i1OL8nLJUDfWMTHVNa65aAJqUnr1IAAAA&config=H4sIAAAAAAAAA0WOwQ6DMAiG34VzT0t28Qm2JXuIpkNT09IGcLExvvtadXqCwMf3s8AoDroFsmVBbp0UUjtDB%2BiiFcc%2BK5iK1ZHyhKsBtTygNkLudRVSEoSut0HQQPTk%2B9JELsXMKHKtLA3hT1YPzopMNjwwZGQ5%2FTF9psYtoCXX2kwx0Sg1TJS90x01QOlJ1ZHyeYv03bMZX9V422zNgaRcYL0ePJ7y8j7iNsMP%2BSpiJBEBAAA%3D

### Expected behavior

The generated code should reference `regenerator-runtime` in a manner compatible with the module settings.

### Version

@swc/core 1.2.120

### Additional context

There was a similar recent issue specific to `spack`: https://github.com/swc-project/swc/issues/2789 

Thanks for taking a look!

**Comment by kdy1** [comment]
You need interop if you want to use it.
