### ISSUE TITLE
use plugins with @swc/wasm-web

### ISSUE THREAD

**Issue by souporserious** [swc-project/swc#3049]
### Describe the feature

From what I can tell, JS plugins can't be created and used with `@swc/wasm-web`. This would help to showcase JS plugins in the playground as well as run custom plugins when SWC is used at runtime.

### Additional context

I'm building a code and element highlighter similar to SwiftUI and want to use a runtime SWC plugin to add source information (line/column) to JSX elements.

**Comment by kdy1** [comment]
You can use `parse` and `print` instead.

**Comment by souporserious** [comment]
Appreciate the quick response! Are there docs for those anywhere by chance? Would I pass those as options to `transformSync`?

**Comment by kdy1** [comment]
I meant you have to use `swc.parse()` to get AST and `swc.print` to converty AST into code. Currently there's no doc for it as js plugins are not recommended.

**Comment by souporserious** [comment]
Ah, that makes sense now! That should work great for my use case 👍  thank you!

**Comment by souporserious** [comment]
Hey, @kdy1 I tried using `parse/print` without much luck since I need to read the JSX tags before they are compiled. Since Rust is the preferred method for plugins would I just need to create a custom plugin that provides those metrics and publish a WASM version? And would I bundle SWC into that WASM version or can I pass a Rust plugin to the web version? Appreciate any help 🙏 just want to make sure I'm heading in the right direction 😅

**Comment by kdy1** [comment]
I think building a custom wasm binary is preferable.
