### ISSUE TITLE
Output mjs file extension

### ISSUE THREAD

**Issue by stefee** [swc-project/swc#3067]
### Describe the feature

A configuration option to output mjs files instead of js files (when using module type es6). 

### Babel plugin or link to the feature description

https://babeljs.io/docs/en/babel-cli#set-file-extensions

### Additional context

https://github.com/swc-project/swc/discussions/2953

https://github.com/babel/babel/pull/9144

**Comment by snowyu** [comment]
Why has this merged feature not been released for two years?

**Comment by kdy1** [comment]
It's not merged

**Comment by Tjerk-Haaye-Henricus** [comment]
Will this ever be solved :D I would really need this feature.

**Comment by wintercounter** [comment]
When I transpile to modules, my dynamic imports will stop working in Node, because it either requires an extension to be defined, or the file must have `.mjs` extension. A simple `import('./myModule')` will fail without having an extension defined.

**Comment by himself65** [comment]
Landed in https://github.com/swc-project/cli/pull/286

Should close this issue

**Comment by himself65** [comment]
No, after I tried, even the output file is mjs, but the code is still like `import './xxx.js'`

**Comment by shimarulin** [comment]
In https://github.com/swc-project/swc/issues/8742#issuecomment-2040392007 I describe possible workaround. You also need to use the `.mts` extension of the sources to import them as `.mjs`.

 `tsconfig.json'

⬇⬇⬇

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext"
    "...": "..."
  }
}

```

```ts
// ======
// SOURCE
// Import from './pkgs.mts'  to './ctx.mts'
// ======
import { ProjectPackages, getProjectPackages } from "~/pkgs.mjs";

export interface Ctx {
  packages: ProjectPackages | null
}

//...
```

⬇ swc --out-file-extension mjs ... ⬇

```js
import { getProjectPackages } from "./pkgs.mjs";
//...
```

**Comment by josh-i386g** [comment]
@shimarulin thanks that works

```json

  "scripts": {
    "swc-watcher": "npx swc src --out-dir dist --strip-leading-paths --watch --out-file-extension mjs",
    "swc-runner": "node --watch-path=./dist/ ./dist/index.mjs"
  }
```

**Comment by sirzeta** [comment]
I have a problem with ESM (mjs) modules, when i use something like this:

```typescript
// src/bootstrap.mjs
import 'reflect-metadata'
import {RegisterRoutes}      from './routes.mjs'
import {errorRequestHandler} from './my_module/middleware/index.mjs'
import {getContainer}        from './inversify.config.mjs'
```

and build it with

```shell
swc src --out-file-extension mjs --strip-leading-paths -D -d dist
```

I get the following:

```typescript
// dist/bootstrap.mjs
import "reflect-metadata";
import { RegisterRoutes } from "./routes.mjs";
// This should be ".mts" extension, no ".js"
import { errorRequestHandler } from "./my_module/middleware/index.js"; 
import { getContainer } from "./inversify.config.mjs";
```

if I run this, I get the following error

```text
Error: Directory import '/dist/my_module/middleware' is not supported resolving ES modules imported from /dist/bootstrap.mjs
```

my configuration is

```json
{
  "$schema": "https://swc.rs/schema.json",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true,
      "resolveFully": true
    },
    "transform": {
      "decoratorMetadata": true
    },
    "target": "es2022",
    "baseUrl": "."
  },
  "module": {
    "type": "es6",
    "noInterop": true,
    "resolveFully": true
  },
  "sourceMaps": true
}

```

*My workaround* is transform the import, but theres a catch, check for `{{matches.[1]}}.mjs`.

```json
{
  "$schema": "https://swc.rs/schema.json",
  "jsc": {
    "experimental": {
      "plugins": [
        [
          "@swc/plugin-transform-imports",
          {
            "^(.*?)\\.mjs(x)?$": {
              "skipDefaultConversion": true,
              "transform": "{{matches.[1]}}.mjs "
            }
          }
        ]
```

There's a space at the end of .mjs. This does the job (it's still a valid import), as it ensures it doesn’t end up returning `"./my_module/middleware/index.js"`. This makes my app happy to run but with annoying spaces.

```javascript
// dist/bootstrap.mjs
import "reflect-metadata";
import { RegisterRoutes } from "./routes.mjs ";
import { errorRequestHandler } from "./my_module/middleware/index.mjs ";
import { getContainer } from "./inversify.config.mjs ";
```

There's a better way to doing this?.

Thanks.

**Comment by hanseltime** [comment]
I wanted to echo what @sirzeta reported.  We do have the `out-file-extension` command, but it when used with `resolveFully` the resolve fully seems unaware of the extension to use and creates the broken links.  It would be nice to have this supported in swc/core

**Comment by kdy1** [comment]
I'll work take on this when I have some time for it.

**Comment by hanseltime** [comment]
@kdy1 - I ended up cobbling together a solution locally to this problem since the above hack wasn't working for me and I figured  that I may as well spend time debugging a fix instead of a hack.  If you already have something you're working on or if you have a different fix in mind because my PR did the fix in the wrong spot or isn't up to par for rust in this project, etc, just let me know and I can bow out or make requested changes (whatever works best for you).

https://github.com/swc-project/swc/pull/9784

Thanks!

**Comment by hanseltime** [comment]
@kdy1 - one thing that I didn't do was add any documentation to the site for this option.  Should that be added as well?

**Comment by kdy1** [comment]
Yeah, I guess so. Can you send a PR to https://github.com/swc-project/website ?

**Comment by hanseltime** [comment]
Aweomse.  I added an attempt at the documentation here:  https://github.com/swc-project/website/pull/278
