### ISSUE TITLE
`.swcrc` cannot be read correctly

### ISSUE THREAD

**Issue by Arikatou123** [swc-project/swc#307]
I'm sure that I configured webpack correctly. When I compile, the .swcrc file cannot be read. So what went wrong?

**Comment by kdy1** [comment]
`.swcrc` file cannot contain comments

**Comment by Arikatou123** [comment]
The file contains no comments.
It just like this: `{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "numericSeparator": false,
      "classPrivateProperty": false,
      "privateMethod": false,
      "classProperty": false,
      "functionBind": false,
      "decorators": false,
      "decoratorsBeforeExport": false
    }
  }
}`
however, I got this option in function transformFile, class Compiler:  `{ sourceFileName: '../test/output.js',
  jsc: { parser: undefined, transform: {} },
  filename: undefined,
  sourceMaps: undefined,
  configFile: undefined }`
I really can't find the problem.😨😨

**Comment by kdy1** [comment]
`.swcrc` is handled by rust code. Can you show your webpack configuration related to swc-loader to me?

**Comment by Arikatou123** [comment]
Please, am I right? : `{
          test: /\.rs$/,
          use: [{
            loader: 'wasm-loader'
          }, {
            loader: 'rust-native-wasm-loader',
            options: {
              release: true
            }
          }]
        },
        {
          test: /\.m?js$/,
          exclude: /(node_modules|bower_components)/,
          use: {
            loader: 'swc-loader'
          }
        }`

**Comment by kdy1** [comment]
I want to know your exact error message and how did you got the message

**Comment by Arikatou123** [comment]
I got that option in @swc/core/lib/index.js, Compiler.transformFile, when I use swc-cli.
I just reinstalled npm packages and run start, it works!
It's my fault, I shoud have checked more. And thank you for your patience.
