### ISSUE TITLE
`.browserlistsrc` should be considered even if `.swcrc` exists

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#3085]
Currently, we don't check for `.browserlistsrc`, but it can be confusing.

**Comment by g-plane** [comment]
Which config file should be preferred?

**Comment by kdy1** [comment]
Oh... Maybe we should emit a warning if there's both `jsc.target`/`env` with `.browserslisttc`

**Comment by g-plane** [comment]
Looking for `.browserslistrc` file can be complicated, how do we check it?

**Comment by kdy1** [comment]
@g-plane 

Yeah, I also think it's a complicated task.
Does `browserslist-rs` supports checking `.browserlistsrc` or entry in the `packge.json`?


Maybe a command like `swc doctor` would be better.

**Comment by g-plane** [comment]
Yes, but it didn't expose APIs about reading configuration files.

**Comment by kdy1** [comment]
Is there a way to distinguish between a default value and configured value?
I think it will be enough.

**Comment by g-plane** [comment]
What does "default value" and "configured value" mean?

**Comment by kdy1** [comment]
If user specified anything related to `browserslist`, it's configured.

**Comment by g-plane** [comment]
Maybe it can't.

There's a kind of query: `defaults`. If users don't specifying anything, it will use `defaults` as "default value". However, users can also configure it using `defaults` in config file manually.

**Comment by kdy1** [comment]
Oh, I see. Then we can check if `env` and `jsc.target` are specified at the same time.

**Comment by g-plane** [comment]
https://github.com/babel/babel/blob/cb3ebde8ceed47f4b6783c16137cc9ddc78998b7/packages/babel-helper-compilation-targets/src/index.ts#L194

I think we may need to expose an API about loading config.

**Comment by zalishchuk** [comment]
@kdy1 @g-plane Hey! Are you sure `browserslist` config loading works fine now? The issue I have is that `swc-loader` doesn't load the config from `package.json`, so I have to do it manually, `.browserslistrc` doesn't seem to work either.

```js
// webpack swc-loader options
{
  env: {
    // FIXME: swc-loader doesn't load browserslist config from package.json for some reason
    targets: require('browserslist').loadConfig({
      path: paths.appPath,
      env: nodeEnv,
    }),
    mode: 'entry',
    coreJs: '3.22',
  },
  jsc: {
    target: 'es5',
    parser: {
      syntax: 'typescript',
      dynamicImport: true,
      tsx: true,
    },
    experimental: {
      cacheRoot: paths.appSwcCache,
    },
    transform: {
      react: {
        runtime: 'automatic',
        refresh: isEnvDevelopment,
        development: isEnvDevelopment,
      },
    },
  },
  minify: false,
},
```
