### ISSUE TITLE
does not properly parse import clauses with assertions

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#3103]
### Describe the bug

swc indicates this is invalid syntax.  According to the [specification](https://tc39.es/proposal-import-assertions/#prod-ImportDeclaration) this is valid syntax:

> **import** _ModuleSpecifier_ [no _LineTerminator_ here] _AssertClause_ ;

### Input code

```typescript
import "./test.json" assert { type: "json" };
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA8vMLcgvKlFQ0tMvSS0u0csqzs9TUkgsLk4FClYrlFQWpFopKEFEa625AO%2BrxKUuAAAA&config=H4sIAAAAAAAAA0WOSw7DIAxE7%2BJ1Fm0WXXCHHgIRJyIigGxHKkLcvYamym40n6epsLMDUyFbYqSuuESxHzAgJSM78llgAmG1hE6cYEGXyEoi%2FjlNU0sbim6Q58f81H5IiRHMagPr5PDRr6XTXToyIfMd2biFf7Mp60jL2Y06DgzmC9rNuHae31dxfPgCqp7SockAAAA%3D

### Expected behavior

This parses without issue.

### Actual behavior

It indicates the assert clause is unexpected.

### Version

1.2.115

**Comment by andreubotella** [comment]
Also, although import assertions with import bindings work in the Typescript parser, they are not supported in the Javascript parser.

https://play.swc.rs/?version=1.2.122&code=H4sIAAAAAAAAA8vMLcgvKlFISSxJVEgrys9VUNLTL0ktLtHLKs7PU1JILC5OBUpXK5RUFqRaKShBRGutAbj67Vw3AAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F8WLLnKHHkK4SnDxD0mBGuO71w4u2Q0zb16DjzjYGhRkIZ5JalL8wgbkIopjXxTMwEa1YxDqBhT5IJ2I2Ie1Yw45Cy3AQPTJ73XKXI6FSeSeMB3hT%2Fbhivl9zqKB1kKX8wn9dqyfl9cClU%2FqPxrFaXe4AAAA

**Comment by andreubotella** [comment]
> Also, although import assertions with import bindings work in the Typescript parser, they are not supported in the Javascript parser.
> 
> https://play.swc.rs/?version=1.2.122&code=H4sIAAAAAAAAA8vMLcgvKlFISSxJVEgrys9VUNLTL0ktLtHLKs7PU1JILC5OBUpXK5RUFqRaKShBRGutAbj67Vw3AAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F8WLLnKHHkK4SnDxD0mBGuO71w4u2Q0zb16DjzjYGhRkIZ5JalL8wgbkIopjXxTMwEa1YxDqBhT5IJ2I2Ie1Yw45Cy3AQPTJ73XKXI6FSeSeMB3hT%2Fbhivl9zqKB1kKX8wn9dqyfl9cClU%2FqPxrFaXe4AAAA

My bad, I didn't realize that `import_assertions` was an option in `EsConfig`.
