### ISSUE TITLE
`import type {foo} from 'foo'` should not remove `foo` from `export {foo} from 'foo'`

### ISSUE THREAD

**Issue by binjospookie** [swc-project/swc#3114]
### Describe the bug

Hi! First of all thank u for the swc.

Looks like it has a bug with `type` keyword.

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA8vMLcgvKlEoqSxIVahOy8%2BvVUgrys9VUAcy1bm4UisQsm75%2BQq2YGZ%2BmgJQ2houja4PAGYvU81UAAAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1FsWLLnyHHsK4SnDxD0mBGuO7VzYp2Q0zo6fp8GEPtkN1xEhTccvivmBBWkX2FKrABsJqCZ04VDs6ULSBbB7GaBpLYQS7u8i4QQo57G2yfEmVkPmOXD7ivzmUlcr7nEZf7xbzCeNmXHeBX1dxbfgBaADhoLcAAAA%3D

### Expected behavior

Like in [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3gMwhAvnTKCEOAcmwlICgqUAPSWBZNAMRzgF5nUJMCcAbhr1G8LDnyFiZCqSA)

```js
export { foo } from 'foo';
```

### Actual behavior

```js
export { };
```

### Version

1.2.122

**Comment by kdy1** [comment]
Is `typeof foo` valid in this context? `foo` is a type and I think it should be

```ts
export type Foo = foo;
```

(I changed the title as the previous one did not contain any useful information.)

**Comment by binjospookie** [comment]
`foo` is a function ([for example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MAUAPAXGArgWwCMBTAJwBoBPHAk0gShQD4YMYBqGSmAKCkoAOxGADFEKGPyEg48REA)).

**Comment by kdy1** [comment]
Oh... So a function can be imported with a type keyword?
Or is there a type named `foo` along with the function?

```ts
import type {foo} from 'foo'
```

**Comment by binjospookie** [comment]
There is a practice that if imported value used only as a type it must be imported with `type` keyword. It's normal for me. There is also a [rule](https://github.com/typescript-eslint/typescript-eslint/blob/v5.8.0/packages/eslint-plugin/docs/rules/consistent-type-imports.md) of eslint.

In other cases the `type` keyword would be unnecessary:

```ts
import { foo } from 'foo';

export type Bar = typeof foo;

export const bar = foo;
```

```ts
import { foo } from 'foo';

export const bar = foo;
```

**Comment by kwonoj** [comment]
fyi `import type` is introduced in ts@3.8 (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) to support babel which runs in a isolated mode cannot infer if imported one is type or actual runtime.

As discussed already in here, we may need to strip import type syntaxes but preserve references to runtime import (or export).

**Comment by binjospookie** [comment]
Thank you!
