### ISSUE TITLE
SWC doesn't transform dynamic imports into require imports

### ISSUE THREAD

**Issue by Minecodes** [swc-project/swc#3131]
### Describe the bug

SWC built the Typescript file, but didn't transformed the imports from "import { Command } from 'commander'" into "const { Command } = require('commander')" and "import { version } from '../package.json'" into "const { version } = require('../package.json')".

### Input code

```typescript
import { Command } from "commander"
import { version } from "../package.json"
const program = new Command("ytdlm")
program.version(version)
program.usage("ytdlm <url> [options]")

program
    .option("-a, --audio", "Download audio only")

program.parse(process.argv)

console.log(program.args)
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "dynamicImport": false
        },
        "target": "es5"
    },
    "minify": false
}
```

### Expected behavior

The imports should be transformed into require imports.

### Actual behavior

The imports doesn't changed

### Version

1.2.123

### Additional context

The cli is on version 0.1.55 and the core is on version 1.2.123. My dev dependencies are "@types/node" version 17.0.5 and "typescript" version 4.5.4. And the only normal dependencie is "commander" version 8.3.0.

**Comment by kdy1** [comment]
You should configure module

**Comment by Minecodes** [comment]
And what is wrong in the config? I'm a new user and don't understand why it doesn't work.
