### ISSUE TITLE
New crate `swc_ecma_template`

### ISSUE THREAD

**Issue by sosukesuzuki** [swc-project/swc#3146]
### Describe the feature

new crate `swc_ecma_template` that has a same feature as [`@babel/template`](https://babeljs.io/docs/en/babel-template).

```rs
let ast = template!("const %%name%% = 3", "foo");
```

equals to

```rs
let ast = Decl::Var(VarDecl {
    span: DUMMY_SP,
    kind: VarDeclKind::Const,
    declare: false,
    decls: vec![VarDeclarator {
        span: DUMMY_SP,
        name: Pat::Ident(BindingIdent {
            id: Ident {
                span: DUMMY_SP,
                sym: "foo".into(),
                optional: false,
            },
            type_ann: None,
        }),
        init: Some(Box::new(Expr::Lit(Lit::Num(Number {
            span: DUMMY_SP,
            value: 3.0,
        })))),
        definite: false,
    }],
  });
}
```

### Babel plugin or link to the feature description

https://babeljs.io/docs/en/babel-template

### Additional context

I'm not familiar with Rust, so I'm not sure that such macros are possible. However if it is possible, it will help plugin and transformer developers.

**Comment by kdy1** [comment]
I love the idea but I'm not sure how much is possible. As input is invalid javascript, it's very limited and will be slow.

If we use approach like pmutil, we can expand it further I guess. Needs investigation anyway.

**Comment by kdy1** [comment]
I'll work on it.

**Comment by kdy1** [comment]
I implemented one, but not sure about how should we handle variables.

 - Should we automatically add `clone` as required?
 
 - Current design only allow variables in identifier position. Is this too restrictive?
 

cc @kwonoj 

What do you think?

This may need ADR

**Comment by kwonoj** [comment]
> Should we automatically add clone as required

I.. think so? is there way without clone even?

Probably need adr, but also we may need some docs for main target users.

**Comment by kdy1** [comment]
Thanks!
Clone is necessary, but I wasn't sure about `implicit` clone, as I expect many users to come from js world, where gc exists.

**Comment by kwonoj** [comment]
Yes it sounds like can be a footgun later. Let's start from explicit clone where it's needed?

**Comment by sosukesuzuki** [comment]
Oh thank you for implementing this! This would makes plugin development easer.

**Comment by kwonoj** [comment]
@kdy1 @sosukesuzuki do we need to guide with some docs / or plugin template to let plugin authors aware of thise?

**Comment by kdy1** [comment]
I think so

**Comment by sosukesuzuki** [comment]
I think yes. One of the hard point of implementing SWC transformer was we need to write strucs and enums that represent AST to me.
