### ISSUE TITLE
Globals Vars Issue

### ISSUE THREAD

**Issue by LeonardSSH** [swc-project/swc#3149]
### Describe the bug

Globals vars should replace the variable properly.

### Input code

```typescript
console.log(__SOMETHING__);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "__SOMETHING__": "SOMETHING"
          }
        }
      }
    },
    "target": "es2020"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP14iPD%2Fb3dQ3x8PRzj4%2FXtAYA9Ek0thsAAAA%3D&config=H4sIAAAAAAAAA6tWyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpRqdZRKihLzitPyi3JBavILSjJzM6sgGtJz8pMSc4pBzDKgKSA6Pj7Y39c1xMPTzz0%2BHmgUnKdUCwRAwxKL0lNLgBKpxUYGRgZAUQAOeN0yiQAAAA%3D%3D

### Expected behavior

```js
console.log("SOMETHING");
```

### Actual behavior

```js
console.log(SOMETHING);
```

### Version

1.2.124

**Comment by kdy1** [comment]
You should quote it

**Comment by andrevinsky** [comment]
Is there a way to make SWC keep the `__SOMETHING__` as is throughout the transpiled code?

**Comment by kdy1** [comment]
@andrevinsky  swc does not touch it by default
