### ISSUE TITLE
Incorrect async function.length when function is passed as argument

### ISSUE THREAD

**Issue by joseBasso** [swc-project/swc#3182]
### Describe the bug

Hi 👋 

Some days ago I reported an issue - #3135 - that was fixed very quickly (thank you very much @magic-akari and @kdy1).

Even thought it is fixed, I noticed that when the function is passed as an argument to another function, the value seems to still be 0.

Thank you!

### Input code

```typescript
const myWrapper = (myFunc) => {
  console.log("arity", myFunc.length);
};

myWrapper(async (one, two, three) => {
  return "irrelevant";
});
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.126&code=H4sIAAAAAAAAAz3MMQqEMBBG4T6n%2BEkVQbyAuOVeYesQBhXijIzjShDvbkCwedXjS8KbYSk%2FjetKigFhKd%2BdU4Phg9MBqR6SqcsyBh91tuJbPE%2BXiUebmt5dvXMvEuJWOCEIUws7pGZSoldUsl0ZflalTP%2FI5qtQlRs7lss7jQAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8aBWqM714bUrKSmPdmOp3wtHWqrBBdH1o2%2FtJG4hPDa6hGbmoz2jlChiNjPcSWgtdksRTITR2lkMPe1pIvqaoAD%2BJ8xL855lAqn2sFnazVeVcllXyCxjN0lwPet216yfgBCKaI9boAAAA%3D

### Expected behavior

Prints "arity 3"

### Actual behavior

Prints "arity 0"

### Version

1.2.126

**Comment by magic-akari** [comment]
Thanks for report this issue.
Maybe it's better to refactor this part of code.
It may take some time.
