### ISSUE TITLE
[Transform] async is removed from method property without converting async to yield

### ISSUE THREAD

**Issue by Knium** [swc-project/swc#319]
### Input
```js
export default obj({
    async f() {
        await g();
    }
});
```

### Output
```
ERROR in ./src/index.js
Module parse failed: The keyword 'await' is reserved (3:8)
You may need an appropriate loader to handle this file type.
```

#### Version
```
"@swc/core": "^1.0.33",
"swc-loader": "^0.1.4",
```
If this is not so hard issue, I want to tackle this too!

**Comment by LuoZijun** [comment]
@Knium @kdy1 

Actually, i belive this should be a syntax error.

Because `obj(...)` is an expr, but `async f() { ... }` is a stmt, if u realy want do that, u should use function expr not function stmt. like this `async f() => { }`.

**Comment by Knium** [comment]
@LuoZijun 
Hi, thanks for your mention! I read your explanation and some syntax in spec. Your opinion sounds correct but it is legal input in [Babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28ICMBWAFAN4BQcFcqAzgJ4B2AxnMoQJRxmXdUDuqAS3gBzdgG5ylAL6kpbCUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.3.4)... I should confirm why Babel accepts my input.

**Comment by kdy1** [comment]
I think 

```js

async f() {
      await g();
}
```

is a method property and if then, it is a bug of parser

**Comment by LuoZijun** [comment]
@dy 

`BindingPropertyList` need key, if have a key, that's fine.

**Comment by LuoZijun** [comment]
@Knium 

BTW: the `babel` support a lot of syntax , but them not belong ecmascript spec.

**Comment by kdy1** [comment]
This error comes from swc's transform, not parser.

swc emits

```js
export default obj({
    f () {
        await g();
    }
});
```
