### ISSUE TITLE
"Duplicate Binding" error for redeclared functions

### ISSUE THREAD

**Issue by gotdibbs** [swc-project/swc#3193]
### Describe the bug

When attempting to run `swc @ >=1.2.122` against a file that has redeclared a function, we receive the message "error: Duplicate Binding".

This is currently causing our jest tests to fail due to a 3rd party library that is written this way.

Functionality works fine in `v1.2.121` and lower.

Thanks!

### Input code

```typescript
function test() {}
function test(a, b) {
    console.log(a, b);
}
```

### Config

```json
{}
```

### Playground link

https://play.swc.rs/?version=1.2.126&code=H4sIAAAAAAAAA0srzUsuyczPUyhJLS7R0FSoruVKQxFK1FFIAgpzKQBBcn5ecX5Oql5OfjpE3JqrFgAkfkZoQQAAAA%3D%3D&config=H4sIAAAAAAAAAy2NTQoCMQxG75J1ERV0MXdw6QFizQyV%2FpFkwFLm7pOO7sL7Hi8dPuJh6lCRhXhc0rLiFyYgn1A8h6rgTDOkvNLm4IVCT46mnGxR5IV0%2BHI9X25GYilCP9tBCjnMbYQT5iUanzEKbdZJ5b0O0EFbpaNwB%2BNBHv%2FleLgDVeaBr6QAAAA%3D

### Expected behavior

The output from v1.2.221 or lower should work fine, simply pass through both of the function declarations as is.

### Actual behavior

error: Duplicate binding
 --> input.jsx:2:10
  |
2 | function test(a, b) {
  |          ^^^^
  |
note: test was declared at here
 --> input.jsx:1:10
  |
1 | function test() {}
  |          ^^^^

### Version

1.2.122+

**Comment by kwonoj** [comment]
I'm curious what 3rd party lib it is - how did it work correctly with babel?

I gave it a quick try and both babel / typescript raises exact same error

https://babeljs.io/repl/#?browsers=ie%2011&build=&builtIns=entry&corejs=3.6&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABFApgZygCgJSIN4C-AUKJLAsulgIYA0iARrnkYm4hAmnADYoB0POAHNMdRtgDcRAkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.16.7&externalPlugins=&assumptions=%7B%7D

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygCgJSIN4C+AUKJLAsulgIYA0iARrnkYm4hAmnADYoB0POAHNMdRtgDcRAkA

Since code tries to redeclare fn with same identifier.

**Comment by kdy1** [comment]
```
function test() {}
function test(a, b) {
    console.log(a, b);
}
```

This is invalid I think?

**Comment by kwonoj** [comment]
yes, that's what I meant. I'm curious if this is typescript overloading instead

```
function test();
function test(a,b) {
}
```

but swc shouldn't fail in that case.

**Comment by kdy1** [comment]
Ah, I see.

**Comment by gotdibbs** [comment]
The package for us is `lottie-web`, they output `EffectsManager` twice for whatever reason in the version we're currently tied to.

I'm working on transitioning from `babel-jest`, so it feels like it must be a versioning issue somewhere if babel is failing for you ... as for typescript ... that actually seems to be succeeding, despite the errors logged in the example above. I also tried another babel repl with success, and jsfiddle's babel version also seems to handle it fine: https://jsfiddle.net/xj40zr3m/

I'm not honestly sure what the correct behavior here should be, but given that code executes fine in the browser, I'd presume it to be a warning not an error? Either way I'm happy to help look or research however I can.

**Comment by kdy1** [comment]
Yeah, actually swc has a test case for minifer where multiple functions with identical name is declared.
But `swc` emits error and will do because it's mistake in most case and it's source of bug. (browser issue)

**Comment by kwonoj** [comment]
https://github.com/babel/babel/issues/12354#issuecomment-726485339 sounds like applies for us as well?

**Comment by kdy1** [comment]
Ah, good point. I forgot to mention that it's invalid in strict mode.

**Comment by gotdibbs** [comment]
Interesting! Thanks for digging into this

I've dug a bit more and found https://github.com/airbnb/lottie-web/issues/1915 which appears to have been fixed, even though it's not yet marked as closed. So I updated our transient dependency on this library and all seems good for us.
