### ISSUE TITLE
[Question] ECMAScript 2019 is released ?

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#320]
Line-72: https://github.com/swc-project/swc/blob/master/README.md#parsers

typo ? :(

**Comment by kdy1** [comment]
- [EsTree](https://github.com/estree/estree) has es2019.md.
 - https://tc39.github.io/ecma262/#sec-ecmascript-language-expressions says it's ECMAScript 2020 spec, so I guess es2019 is already released.

**Comment by kdy1** [comment]
- [EsTree](https://github.com/estree/estree) has es2019.md.
 - https://tc39.github.io/ecma262/#sec-ecmascript-language-expressions says it's ECMAScript 2020 spec, so I guess es2019 is already released.

**Comment by LuoZijun** [comment]
```
Draft ECMA-262 / March 1, 2019
ECMAScript® 2020 Language Specification
```

This is a draft spec, not release. and the features maybe changed when release.

if released, i guess we can find at https://www.ecma-international.org/ecma-262/10.0/index.html
