### ISSUE TITLE
Prevent transpiling of swc helpers

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#3201]
### Describe the bug

When using swc in a bundler that also transpiles node_modules, the `typeof obj` expression in the typeof helper
https://github.com/swc-project/swc/blob/d901b6222f8a77beed64968fcb4764bbacf8c755/packages/swc-helpers/src/_type_of.js#L2

is transpiled to a call to the typeof helper, leading to infinite recursion. (This is using the option to insert import statements for the helper functions, instead of inlining them)

Babel had this exact problem in that past as well and solved it using https://github.com/babel/babel/pull/11049

### Playground link

https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAAyWMwQmAMBAE%2F6li8RH0YwFKsAgLEI0JKJqT8wKK2LtR97PDMiyUOzZiweh8HxeBj8HKRAGdnJsjn9MwF7gUUthJ5IC0QOu3SkthF45WiGGMQXuuAy1okO0fZajw%2F7x6re76AYx4jAJxAAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWFLnKEQg8hXMW4%2BIdkl4bgu9dKE7oTM2%2BeNniJhXmDgizEesmaKn5gBrIRxbIvFaaBjWjBINQnqMiOqiJiLsaMOuQsdAATRJ%2F8sqrM5liYRP4VJhdOsg9XzM%2BmwQZ1LbQ7bzBySu%2BfgOk%2B5ted1L4JOlLi%2FHKYvTwOVeVG%2FQtn0eQh2gAAAA%3D%3D

### Expected behavior

Not infinite recursion

### Version

v1.2.126

### Additional context

cc @devongovett 

https://github.com/parcel-bundler/parcel/issues/7528

**Comment by devongovett** [comment]
FYI, we worked around it for now by hard coding an exception for running preset-env on `@swc/helpers`
