### ISSUE TITLE
Request: drop-in replacement for "node" to run TypeScript scripts

### ISSUE THREAD

**Issue by jameshfisher** [swc-project/swc#3206]
### Describe the feature

I would like to do something like this:

```shell
$ echo 'console.log("hello")' > script.ts
$ npx @swc/node script.ts
hello
```

That is, I'd like a drop-in replacement for `node`, in the same way that `@swc/jest` provides a drop-in replacement for `jest`.

Is this supported by SWC? If so, how? If not, is there a recommended approach?

**Comment by kdy1** [comment]
I'll add one soon.

**Comment by mischnic** [comment]
There's also https://github.com/Brooooooklyn/swc-node

**Comment by kdy1** [comment]
Please see https://github.com/swc-project/swc-node

Thank you @Brooooooklyn!

**Comment by jameshfisher** [comment]
@kdy1 @Brooooooklyn Maybe I'm being stupid, but how do I use https://github.com/swc-project/swc-node to achieve my goal? I want to run something like `npx @swc/node script.ts` to run a TypeScript file using Node. But I can't see anything in the swc-node README, or any examples anywhere, that show how to do that?!

**Comment by Brooooooklyn** [comment]
@jameshfisher https://github.com/swc-project/swc-node/tree/master/packages/register#cli

**Comment by jameshfisher** [comment]
@Brooooooklyn perfect, thanks! 

(I feel like it would be good to put that right at the top of https://github.com/swc-project/swc-node README? I didn't even bother to look at the "register" package because it didn't sound like what I wanted!)
