### ISSUE TITLE
Documentation for transforming `styled-jsx`

### ISSUE THREAD

**Issue by thiskevinwang** [swc-project/swc#3207]
### Describe the feature

Requesting docs/guides for transforming code that uses https://github.com/vercel/styled-jsx

There's a link to an [article that uses rollup and babel](https://medium.com/@tomaszmularczyk89/guide-to-building-a-react-components-library-with-rollup-and-styled-jsx-694ec66bd2), but I'm not quite sure how to accomplish the same with `swc`

### Babel plugin or link to the feature description

styled-jsx/babel

### Additional context

I'm building a component library that uses `<style jsx>` tags, and as far as I know, SWC is treating it as a regular `style` DOM tag.
- [example usage](https://github.com/nextjs-components/nextjs-components/blob/main/packages/core/src/components/Container/Container.tsx#L139-L143)
- [`.swcrc`](https://github.com/nextjs-components/nextjs-components/blob/main/packages/core/.swcrc)

**Comment by kdy1** [comment]
`styled-jsx` is not published as a plugin nor a plugin at the moment.

**Comment by thiskevinwang** [comment]
@kdy1, what's the best path forward for using `swc` with jsx code that uses `styled-jsx`?

**Comment by kdy1** [comment]
@thiskevinwang Currently using next.js is the solution. Code for `styled-jsx` lives at next.js repo and it's not published.

**Comment by metawise** [comment]
> 

Did you find your answer?

**Comment by metawise** [comment]
Styled-jsx not working with TailwindCSS' utilities when I start using SWC, anyone know how to make it work?

**Comment by kdy1** [comment]
It's published, but I forgot to document it.
I'll do it after finishing my current tasks

**Comment by kdy1** [comment]
Sorry I was way too busy.
I documented it
