### ISSUE TITLE
Variable being renamed unnecessarily is breaking code

### ISSUE THREAD

**Issue by Emilios1995** [swc-project/swc#3213]
### Describe the bug

Running the function `f()` from the input code, causes the console to log `"original string"`, whereas running the one outputted by the compiler results in `"new string"` being logged.

### Input code

```typescript
function f() {
  var value$2 = 'original string';
  if (true) {
    var value$21 = 'new string'
    console.log(value$2)
  }
  [].map(function x(_) {
    var value$2; // this causes the previous value$2 to become value$21
    return value$2
  })
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "keepClassNames": true
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAA21OzQqCQBC%2B%2BxRzCFwvSl2lJ4mIbZm1gXVG9keD8N1bLYWgwwfDfL82sYkkDFZV8CoARu0zXMLDCc5QiqeOWDsI0RN3ZZslZEFFn%2FBj%2BLEcFw%2FjtMlX3ggHcVg76dRXV2Vizrhc614Pym4rnur2J7WFpoH4oABGp4Ah3wiDx5EkhX1tFLijkR73MWuOx5g8b7%2Bltyrm4g21Prmx%2BAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNOw7DIBBE77I1bVLQpk7usCJrC4efGCwFId894CC5W828edtogyHdKHGG5HGhhsJf0iTGM0y2qZDqWI8WdpBDUeG8ShkIbr1zMUJIl7yLIm%2BDXeoQmehTFmDuesVhdXJpPiLp4Rh4sRf8BT328b0PrFGpSc4vdzou87RZPCd47n5%2FjK7bygAAAA%3D%3D

### Expected behavior

I think that there are two problems:

1. The compiler shouldn't have renamed the first `value$2` to `value$21` in the first place. It does that because of the second declaration inside `function x(_)`, but it's not necessary since variables are scoped to its closures, so the shadowing is valid.
2. The compiler should notice that the `var value$21` declaration inside the `if` block clashes with the compiler's renaming of `value$2` to `value$21`, so it should probably rename it to something else (or not at all, as mentioned in the previous point.). Notice that the bug is gone if the code is taken out off the `if` block.

### Version

1.2.124

### Additional context

This might seem like an unrealistic example, but it actually broke our application written in [Rescript](https://rescript-lang.org/), whose compiler outputs a lot of variables suffixed with numbers.

Update: Looks like this only started happening on `v1.2.102`

**Comment by Austaras** [comment]
Another case
```js
var h = destination.$$hashKey;
forEach(destination, function (value, key) {
    key;
});
for (var key in source) key = copy(key);
```
transforms to
```js
var h = destination.$$hashKey;
forEach(destination, function(value, key1) {
    key1;
});
for(var key in source)key = copy(key);
```

**Comment by Austaras** [comment]
Yet another [case](https://play.swc.rs/?version=1.2.129&code=H4sIAAAAAAAAA0srzUsuyczPU0gsrsxLdk%2FNSy1KLMkvCi5JLdDQVKiu5UrDrcAQooIrOSexuFjBUSG1oiQ1L6VYwUmhmksBol4hLT8fpArIV1AoLi1ILdJL1NAE8mq5agGzY%2FnjewAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSw7CMAxEr4K87oJNWfQOHCIKLgSlSeRxEVGVu%2BNEldjN580c9Ian5aDiBCxdoSZ1X1pIa2F4CUVpIoVFq4vgZsbJk9UQxmxdzBn8b7f82CP3q%2F4wqBv1PKSw1pObKOB%2Bgiq7eU6fsRnfsJl%2FSd74Ml%2BptR%2BfXRtTqAAAAA%3D%3D)
