### ISSUE TITLE
Not compiling imported file

### ISSUE THREAD

**Issue by trs** [swc-project/swc#3214]
### Describe the bug

Running `swc` with on a file with an import does not compile the included file. See the included repository for a reproduction.

### Input code

```typescript
https://github.com/trs/swc-compile-issue
```

### Config

```json
{
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

### Playground link

https://github.com/trs/swc-compile-issue

### Expected behavior

`dist` folder should have two files: `index.js` and `lib.js`.

### Actual behavior

`dist` folder only has the `index.js` file, causing running it to fail.

### Version

@swc/cli: 0.1.55 @swc/core: 1.2.127

**Comment by kwonoj** [comment]
swc cli does not resolve modules. You need to specify dir https://swc.rs/docs/usage/cli#--out-dir--d or resolve it yourself and use node.js interfaces `transform` instead.
