### ISSUE TITLE
Support for imports within async functions ?

### ISSUE THREAD

**Issue by cyplo** [swc-project/swc#322]
Heya ! 
I'm trying to port a project to SWC and I have some troubles getting it to run.
I think it may have something to do with us using WASM dependencies and thus using async imports.
The current state of the port is at https://github.com/balena-io-playground/reconfix-play/tree/swc - feel free to take a look there.

Please see `src/index.js` within that branch for the context, but basically we're defining a react component in this way:
```
const App = async(() => {
  return import("./App");
});
```

This compiles without any problem, but gets us an error in runtime:

`ReferenceError: _import is not defined[Learn More]`

The code emitted seems to be:
```
var App = Object(_Async__WEBPACK_IMPORTED_MODULE_3__["default"])(function() {
    return _import('./App');
});
```

Hope this helps ! Thanks so much for this project btw :)

**Comment by kdy1** [comment]
It seems like a bug of es3 transforms. You can specify `jsc.target to `es5` / `es2015` to bypass the issue.

**Comment by cyplo** [comment]
Thank you for that, it indeed does work now, using `es2015` as the target :) thanks ! :)
