### ISSUE TITLE
Incorrect output for static methods defined as a class field

### ISSUE THREAD

**Issue by golopot** [swc-project/swc#3222]
### Describe the bug

Compiled code does not run like source code.

### Input code

```typescript
class Foo {
  static f = () => {
    this.g();
  };

  static g = () => {
    console.log(123);
  };
}

Foo.f()
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.127&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQKC5JLMlMVkhTsFXQ0FSwtQMLKiiUZGQW66VraFoDebXWXAiF6WgKk%2FPzivNzUvVy8tM1DI2MYRpqubiANuilaWhyAQDpIl7ecAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

No crash.

### Actual behavior

Uncaught TypeError: _this.g is not a function

### Version

1.2.127

### Additional context

This only happens with typescript parser

**Comment by kdy1** [comment]
Thanks!
