### ISSUE TITLE
Compilation should not remove uninitialized properties from a class

### ISSUE THREAD

**Issue by flyyuan** [swc-project/swc#3232]
### Describe the bug

Compilation should not remove uninitialized properties from a class.
It is useful to have properties in the class that are not assigned initial values. For example, mobx will listen based on the value of the attribute in the class, and if the attribute that is not assigned an initial value is removed, mobx will not be able to listen to the corresponding attribute. Besides, many people are used to declaring class properties without giving them initial values, and swc compilation can create bugs that developers don't expect.

input.js 
```js
class IncStore {
  num = 0
  unInitValue
  inc() {
    this.num += 1
    this.unInitValue += 1
  }
}
const incStore = new IncStore()
window.aaa = incStore
export default incStore
```

output.js (The unInitValue was removed after compilation, expecting it to be there)
```js
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
function _defineProperties(target, props) {
    for(var i = 0; i < props.length; i++){
        var descriptor = props[i];
        descriptor.enumerable = descriptor.enumerable || false;
        descriptor.configurable = true;
        if ("value" in descriptor) descriptor.writable = true;
        Object.defineProperty(target, descriptor.key, descriptor);
    }
}
function _createClass(Constructor, protoProps, staticProps) {
    if (protoProps) _defineProperties(Constructor.prototype, protoProps);
    if (staticProps) _defineProperties(Constructor, staticProps);
    return Constructor;
}
var IncStore = /*#__PURE__*/ function() {
    "use strict";
    function IncStore1() {
        _classCallCheck(this, IncStore1);
        this.num = 0;
    }
    _createClass(IncStore1, [
        {
            key: "inc",
            value: function inc() {
                this.num += 1;
                this.unInitValue += 1;
            }
        }
    ]);
    return IncStore1;
}();
var incStore = new IncStore();
window.aaa = incStore;
export { incStore as default };
```

### Input code

```typescript
class IncStore {
  num = 0
  unInitValue
  inc() {
    this.num += 1
    this.unInitValue += 1
  }
}
const incStore = new IncStore()
window.aaa = incStore
export default incStore
```

### Config

```js
const { config } = require("@swc/core/spack");

module.exports = config({
  //入口文件
  entry: __dirname + "/input.js",
  //输出
  output: {
    path: __dirname + "/dist",
  },
  // swc编译配置
  options:{
    jsc: {
        //解析配置
        parser: {
          syntax: "typescript", //输入文件格式
          tsx: false,    // 是否支持tsx
          dynamicImport: false, //是否支持动态导入
          decorators: false, //是否支持装饰器
        },
        transform: null,
        target: "es5", //转译目标
        loose: false, 
        externalHelpers: false,
        keepClassNames: false
      },
      // 输出文件配置
      module: {
          type: "commonjs",  
          strict: false,
          strictMode: false,
          lazy: false,
          noInterop: false,
          ignoreDynamic: false
        }
  }
});
```

### Playground link

https://github.com/flyyuan/swcUsingDemo

### Expected behavior

Expect to compile to include attributes in the class that are not given initial values

### Actual behavior

Remove attributes in the class that are not given initial values after compilation

### Version

1.2.128

**Comment by doerme** [comment]
m

**Comment by erikian** [comment]
I've filed an issue on Next.js the other day about this problem (https://github.com/vercel/next.js/issues/32356), I'm pretty sure it affects many other projects as well. Looking forward to this fix.

**Comment by kdy1** [comment]
I checked babel repl and babel emits same output

**Comment by RiESAEX** [comment]
also tsc doesn't emit it, swc & babel follow its behavior
https://github.com/microsoft/TypeScript/issues/7777

**Comment by flyyuan** [comment]
> 

Babel do emit suninitialized properties.
I have verified

**Comment by flyyuan** [comment]
> I checked this using babel repl and babel emits nothing for uninitialized properties.

Babel do emit suninitialized properties.
I have verified

**Comment by ckken** [comment]
+1 & mark

**Comment by linhaobin** [comment]
+1

**Comment by kdy1** [comment]
@Austaras Thank you!
