### ISSUE TITLE
Rest parameters undefined

### ISSUE THREAD

**Issue by cecchi** [swc-project/swc#3256]
### Describe the bug

When using rest parameters in a function declaration, the parameter is undefined.

### Input code

```typescript
function foo(...args) {
  console.log(args)
}

foo(1,2,3)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "Edge >= 17"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.129&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9fQ09NLLEov1lSo5lJQSM7PK87PSdXLyU%2FXAIty1XJxgVQZ6hjpGGsCAMQsaGQ5AAAA&config=H4sIAAAAAAAAA0WOTQrDIBCFrxLe2k0XbSHQ7rrsIcRMgiVRcUxpEO%2BeUVKyG97PNy%2FjwwZ9RtCRKdaLN5f0Dz3SFohNtCFBIbFIKa5U5NZxoiQJ4qtYs%2FdM6Ec9Myks1tlxqyDjlxCJ%2BbS0m%2BZ%2Fsgho8cNahdx%2BNeAN5WQcPcvvI1gHKJD7tk6bIXi8hom656O73FHKDhLiHCLTAAAA

### Expected behavior

`args` should be defined.

### Actual behavior

`args` is undefined, because it is declared with block-scope in a `for` loop (i.e. `let` instead of `var`):

```js
function foo() {
    for(let _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++){
        args[_key] = arguments[_key];
    }
    console.log(args);
}
foo(1, 2, 3);
```

Changing the `let` to `var` fixes the issue. Alternatively, `args` and `_len` could be defined outside the loop:

```js
function foo() {
    let _len = arguments.length, args = new Array(_len)
    for(let _key = 0; _key < _len; _key++){
        args[_key] = arguments[_key];
    }
    console.log(args);
}
foo(1, 2, 3);
```

### Version

1.2.124

**Comment by RiESAEX** [comment]
Rest parameters is support in edge >= 15

**Comment by cecchi** [comment]
Interesting, the targets I'm using are slightly different but I reduced it to IE 17 for purposes of the reproduction. Regardless of whether they are supported, SWC is transforming them (unnecessarily?) to invalid code.

**Comment by Smrtnyk** [comment]
Didn't know that IE17 exists

**Comment by cecchi** [comment]
@Smrtnyk Edge, not IE to clarify, but yeah it looks like they changed their versioning after Edge 18 and now have version numbers that appear to mirror Chrome.

In any case, the output changes when I target Edge >= 14 vs Edge >= 13:

Edge >= 13 [[Playground](https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9fQ09NLLEov1lSo5lJQSM7PK87PSdXLyU%2FXAIty1XJxgVQZ6hjpGGsCAMQsaGQ5AAAA&config=H4sIAAAAAAAAA0WOuwrDMAxFfyVozlJKOwTarWM%2FwjiKcfELyyk1xv8e2bhkk3TPPajAhyQsBYKIhLFNlF0SP1gApRUkow4JZsb4tAlDWGdIIipMDaEbZ8Z7wpHOYLXTW24m6W2ISHRGwinzJyuLrF%2F3diiQcsAuvEM9HaOn6T3AFHfe0X17p7%2FBenitCqfnY7pcodYDAqV%2BWtQAAAA%3D)]:

```js
function foo() {
    for(var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++){
        args[_key] = arguments[_key];
    }
    console.log(args);
}
foo(1, 2, 3);
```

Edge >= 14 [[Playground](https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9fQ09NLLEov1lSo5lJQSM7PK87PSdXLyU%2FXAIty1XJxgVQZ6hjpGGsCAMQsaGQ5AAAA&config=H4sIAAAAAAAAA0WOuwrDMAxFfyVozlJoOwTarWM%2FwjiKcfELyyk1xv8e2bhkk3TPPajAhyQsBYKIhLFNlF0SP1gApRUkow4JZsb4tAlDWGdIIipMDaEbZ8Z7wpHOYLXTW24m6W2ISHRGwinzJyuLrF%2F3diiQcsAuvEM9HaOn6T3AFHfe0X17p7%2FBenitCqfnY7pcodYDu52px9QAAAA%3D)]:

```js
function foo() {
    for(let _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++){
        args[_key] = arguments[_key];
    }
    console.log(args);
}
foo(1, 2, 3);
```

The latter output is not valid in _any_ browser, as far as I know. `args` will always be undefined outside the `for` loop if declared with `let`.

**Comment by RiESAEX** [comment]
I think we should make block-scoping enabled when parameters is enabled

**Comment by kdy1** [comment]
@RiESAEX I think we can use `var` instead of `let` in `parameters`? It's similar to enabling `block_scoping` for only `_len` and `args`.
