### ISSUE TITLE
Plugin bytecode cache seems not working

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#3259]
### Describe the bug

I have to double confirm, it looks like wasmer::filesystemcache we use doesn't seem to produce bytecode cache for us. It maybe my fault to incorrectly configure cache.

This does not consider cache expiration yet.

### Expected behavior

- When plugin runs first, expect cache dir `.swc` generated and contains plugin cache
- When swcrc configs custom paths for the cache, cache dir should be generated for those instead
- Next time plugin runs, it should use bytecode cache instead of full-cold compilation

### Version

master (TOT)

### Additional context

Since we made progresses for the meta (https://github.com/swc-project/swc/issues/3167) I think we can now file individual issues instead and will do.

**Comment by RiESAEX** [comment]
I build swc_internal_plugin and load it with 1.2.133
and swc generated the cache.
![image](https://user-images.githubusercontent.com/89718456/150526756-34ac6175-259e-4841-8b31-5afadf5087b5.png)
and with "cacheRoot":"./cache" 
it generate bytecodes at `./cache/plugins/`
I don't know how to check if it's using the cache.

**Comment by kwonoj** [comment]
oh, seems working then? I'll double check if cached byte is actually loaded.

**Comment by kwonoj** [comment]
it was my mistake using integration test to verify which explicitly disables cache (https://github.com/swc-project/swc/blob/main/crates/swc_plugin_runner/tests/integration.rs#L93) 🤦
