### ISSUE TITLE
Unnecessary rest parameter transformation when targeting recent Safari versions

### ISSUE THREAD

**Issue by cecchi** [swc-project/swc#3268]
### Describe the bug

Safari has supported rest parameters since [version 10](https://caniuse.com/rest-parameters). When targeting recent versions of Safari (e.g. "Safari >= 15"), SWC transforms rest parameters using a for loop.

### Input code

```typescript
function foo(...args) {
  console.log(args)
}

foo(1,2,3)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "Safari >= 15"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.129&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9fQ09NLLEov1lSo5lJQSM7PK87PSdXLyU%2FXAIty1XJxgVQZ6hjpGGsCAMQsaGQ5AAAA&config=H4sIAAAAAAAAA0WOPQrDMAxGrxI0Z%2BmQDoH2Bp16AuHKwSX%2BQXJKg%2FHdK5uUbJK%2B9z1U4C0G5gIJWYjbJHvI%2BIUZyHgUwy5lGBXTk8VVqI6QkRfKDZFJszVGoSMdwbvg7N5MJvrEJHJGGJb1T1YV%2Bfja2qFA3hN14RXq6Th6Th4HmHnTncKnd%2FobqocnWmQ33G%2FDZYJaf9Mhm07WAAAA

### Expected behavior

The code should be untransformed:

```js
function foo(...args) {
    console.log(args);
}
foo(1, 2, 3);
```

### Actual behavior

```js
function foo() {
    for(let _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++){
        args[_key] = arguments[_key];
    }
    console.log(args);
}
foo(1, 2, 3);
```

### Version

1.2.129

**Comment by RiESAEX** [comment]
because there is a bug in safari 14.
You can add `bugfixes: true` to env
https://bugs.webkit.org/show_bug.cgi?id=220517
https://github.com/babel/babel/issues/13916

**Comment by kdy1** [comment]
@RiESAEX  Thank you!
