### ISSUE TITLE
Infinite hang with `paths` option and certain package imports

### ISSUE THREAD

**Issue by clhuang** [swc-project/swc#3272]
### Describe the bug

swc simply hangs when run: `yarn run swc hi.ts`

Something about the `handlebars` package, in conjunction with the `paths` option seems to cause swc to go into an infinite loop

### Input code
package.json

```json
{
  "devDependencies": {
    "@swc/cli": "^0.1.55",
    "@swc/core": "^1.2.129",
    "handlebars": "^4.7.7"
  }
}
```

hi.ts
```ts
import h from 'handlebars';
console.log(h);
```

### Config

```json
{
  "jsc": {
    "paths": {
      "server/*": ["./*"]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

`yarn run swc hi.ts` completes, and emits a simple javascript file

### Version

1.2.129

**Comment by ide** [comment]
I was able to reproduce this as well with `jszip@3.5.0` but not `3.6.0`.
* Repro here: https://github.com/ide/swc-freeze
* jszip changelog between those releases: https://github.com/Stuk/jszip/compare/v3.5.0...v3.6.0

**Comment by franky47** [comment]
I have the same issue, and **either** of the following helped in my case:

- Change the root-level import of `handlebars` to a dynamic one:
```diff
- import handlebars from 'handlebars'

async function bootstrap() {
+  const handlebars = await import('handlebars')
}
```

- Add a path entry to `.swcrc` for handlebars:
```json
{
  "jsc": {
    "paths": {
      "handlebars": ["../node_modules/handlebars"]
    }
  }
}
```
