### ISSUE TITLE
Source maps containing emojis might be buggy

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#3288]
### Describe the bug

**Disclaimer**: I'm not sure if this is an issue with SWC or `rust-sourcemap`, I wasn't able to pinpoint the problem as of yet.

In Deno we're using source maps during generation of coverage reports. However the program panics when there's an emoji in original source code (and thus in source map): https://github.com/denoland/deno/issues/10936

### Input code

```typescript
export default function () {
  return "📣❓";
}
```

### Config

```json
n/a
```

### Expected behavior

Source map is generated in such a way that it can later be loaded.

### Actual behavior

Panic when loading a source map:
```
fn generate_coverage_report(
  script_coverage: &ScriptCoverage,
  script_source: &str,
  maybe_source_map: &Option<Vec<u8>>,
) -> CoverageReport {
  let maybe_source_map = maybe_source_map
    .as_ref()
    .map(|source_map| SourceMap::from_slice(source_map).unwrap()); // <--- panics here
   ...
}
```

### Version

swc_ecmascript = { version = "0.108.1" }

**Comment by bartlomieju** [comment]
More info:

Input:
```
export default function () {
    return "📣❓";
}
```

Output:
```
export default function () {
    return "📣❓";
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiZmlsZTovLy9Vc2Vycy9pYi9kZXYvZGVuby9mb28udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsTUFBTSxDQUFDLE9BQU87SUFDWixPQUFPLEtBQUssQ0FBQztBQUNmLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiAoKSB7XG4gIHJldHVybiBcIu2gve2zo+Kdk1wiO1xufVxuIl19
```

```rust
fn main() {
  // {"version":3,"file":"","sourceRoot":"","sources":["file:///Users/ib/dev/deno/foo.ts"],"names":[],"mappings":"AAAA,MAAM,CAAC,OAAO;IACZ,OAAO,KAAK,CAAC;AACf,CAAC","sourcesContent":["export default function () {\n  return \"❓\";\n}\n"]}
    let content = r#"//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiZmlsZTovLy9Vc2Vycy9pYi9kZXYvZGVuby9mb28udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsTUFBTSxDQUFDLE9BQU87SUFDWixPQUFPLEtBQUssQ0FBQztBQUNmLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiAoKSB7XG4gIHJldHVybiBcIu2gve2zo+Kdk1wiO1xufVxuIl19"#;
    let input = content.trim_start_matches("//# sourceMappingURL=data:application/json;base64,",);

    let decoded_map = base64::decode(input).expect("Unable to decode source map from emitted file.");
    eprintln!("decoded map {:?}", decoded_map);

    let s = SourceMap::from_slice(&decoded_map);
    eprintln!("{:#?}", s);

    let r = std::str::from_utf8(&decoded_map);
    eprintln!("{:#?}", r);
}
```

```
❯ cargo run
   Compiling test_sourcemap v0.1.0 (/Users/ib/dev/test_sourcemap)
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/test_sourcemap`
decoded map [123, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 51, 44, 34, 102, 105, 108, 101, 34, 58, 34, 34, 44, 34, 115, 111, 117, 114, 99, 101, 82, 111, 111, 116, 34, 58, 34, 34, 44, 34, 115, 111, 117, 114, 99, 101, 115, 34, 58, 91, 34, 102, 105, 108, 101, 58, 47, 47, 47, 85, 115, 101, 114, 115, 47, 105, 98, 47, 100, 101, 118, 47, 100, 101, 110, 111, 47, 102, 111, 111, 46, 116, 115, 34, 93, 44, 34, 110, 97, 109, 101, 115, 34, 58, 91, 93, 44, 34, 109, 97, 112, 112, 105, 110, 103, 115, 34, 58, 34, 65, 65, 65, 65, 44, 77, 65, 65, 77, 44, 67, 65, 65, 67, 44, 79, 65, 65, 79, 59, 73, 65, 67, 90, 44, 79, 65, 65, 79, 44, 75, 65, 65, 75, 44, 67, 65, 65, 67, 59, 65, 65, 67, 102, 44, 67, 65, 65, 67, 34, 44, 34, 115, 111, 117, 114, 99, 101, 115, 67, 111, 110, 116, 101, 110, 116, 34, 58, 91, 34, 101, 120, 112, 111, 114, 116, 32, 100, 101, 102, 97, 117, 108, 116, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 40, 41, 32, 123, 92, 110, 32, 32, 114, 101, 116, 117, 114, 110, 32, 92, 34, 237, 160, 189, 237, 179, 163, 226, 157, 147, 92, 34, 59, 92, 110, 125, 92, 110, 34, 93, 125]
Err(
    BadJson(
        Error("invalid unicode code point", line: 1, column: 238),
    ),
)
Err(
    Utf8Error {
        valid_up_to: 220,
        error_len: Some(
            1,
        ),
    },
)

```

**Comment by bartlomieju** [comment]
@kdy1 could you provide some pointers regarding this issue? It's becoming somewhat painful for us in Deno, and I'd love to try and tackle it myself.

**Comment by alexander-akait** [comment]
I am afraid source map will be pointer on wrong position with emojis too...

**Comment by kdy1** [comment]
@bartlomieju  I think it comes from `sourcemap` crate?

**Comment by bartlomieju** [comment]
> @bartlomieju I think it comes from `sourcemap` crate?

I'm not so sure anymore - what we are getting from SWC cannot be parsed by `sourcemap` crate (as can be seen on the above example), which led me to believe that something is going wrong when SWC generates the source map for a source (ie, when `SourceMapBuilder` is generating inline source map emojis are not handled properly).

I'd really want to get this fixed, because it completely breaks `deno coverage` tool, which becomes useless if it has false positives.

**Comment by kdy1** [comment]
Okay, I'll investigate

**Comment by kdy1** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/29931815/166674632-33861989-a860-4a76-a5e9-d696a033ca1c.png">

Seems like I should create a rust-based tests

**Comment by kdy1** [comment]
@bartlomieju Seems like sourcemap generated by `swc` works?
See https://github.com/swc-project/swc/blob/22f9ffc863ba38188c0395750a827534bdf727c5/crates/swc/tests/source_map.rs#L303-L325


I copied those from https://github.com/swc-project/swc/blob/22f9ffc863ba38188c0395750a827534bdf727c5/crates/swc/tests/fixture/issues-3xxx/3288/3/output/input.js and https://github.com/swc-project/swc/blob/22f9ffc863ba38188c0395750a827534bdf727c5/crates/swc/tests/fixture/issues-3xxx/3288/4/output/input.ts

Can you point the deno code for generating source maps? I'll check if it's correct

**Comment by bartlomieju** [comment]
@kdy1 that should be this bit: https://github.com/denoland/deno_ast/blob/cadcf596060de2345405cb46abb8b1af5c9de374/src/transpiling/mod.rs#L223-L241

**Comment by kdy1** [comment]
Seems like an issue of base64?

Things to note

 - Your base64 string fails to be decoded if I turn on live mode
<img width="901" alt="image" src="https://user-images.githubusercontent.com/29931815/166679391-3104e64d-3338-4654-b86d-7ec54c514e9e.png">

So I think this is a bug of base64 crates regardless of other issues, as `base64::encode` created malformed base64 string.


 - If I encode your sourcemap json, I got different output and it works 
<img width="924" alt="image" src="https://user-images.githubusercontent.com/29931815/166679106-02364eaa-1867-4050-9b66-a995ce596fc5.png">

It's different from your string, and the value is `eyJ2ZXJzaW9uIjozLCJmaWxlIjoiIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiZmlsZTovLy9Vc2Vycy9pYi9kZXYvZGVuby9mb28udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsTUFBTSxDQUFDLE9BQU87SUFDWixPQUFPLEtBQUssQ0FBQztBQUNmLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiAoKSB7XG4gIHJldHVybiBcIuKdk1wiO1xufVxuIl19`

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/29931815/166679210-d9629b93-5f0f-4a2d-bdb3-05630f3a413a.png">

(It works)

**Comment by kdy1** [comment]
One more investigation:

`String::from_utf8(decoded_map)` fails for your input.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/da5114d269510a7bfa158e398aadb1a5c9919a21/crates/swc/src/lib.rs#L522-L529

Can you try creating `String` with buf first?
