### ISSUE TITLE
When using plugins, the parser option are not deduce from filename

### ISSUE THREAD

**Issue by ArnaudBarre** [swc-project/swc#3297]
### Describe the bug

```js
const filename = "index.tsx"

// Works
await transform(code, {
    filename,
});

// Fails
await transform(code, {
    filename,
    plugin: (p) => visitor.visitProgram(p),
});

// Works
await transform(code, {
    filename,
    plugin: (p) => visitor.visitProgram(p),
    jsc: { parser: { syntax: "typescript", tsx: true } },
});
```

### Expected behavior

Adding a plugin should not lose the ability to compute parser options from filename.

### Actual behavior

Example 2 failed to parse the file (Unexpected jsx opening tag)

### Version

1.2.130

**Comment by kwonoj** [comment]
We do not actively support legacy plugins at this moment. If you have a fix, welcome to accept PR however core team currently do not have bandwidth to look into unfortunately.

**Comment by ArnaudBarre** [comment]
Yeah I had an issue in the past with `jsx` without plugin. I'm always proving parser option now and that's ok
