### ISSUE TITLE
Support llvm compiler backend for the plugin

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#3307]
### Describe the feature

Context: https://crates.io/crates/wasmer-compiler-llvm

It is recommended to use llvm-base compiler backend for the prod env when we run plugins. 

We can't enforce this, but our plugin should be able to opt-in to use most performant backend if it's available. It is unclear at this moment if we should expose explicit config, or should do dynamic fallback based on availability - but given config should be portable across machines, I'm leaning on some sort of detection mechanism.

**Comment by kdy1** [comment]
Problem is that it requires global installation of llvm.
I think `wapm` can be a solution for this problem. (https://github.com/swc-project/swc/issues/2635#issuecomment-1006038273)

cc @syrusakbary Any thoughts?

**Comment by kwonoj** [comment]
@kdy1 

That's the part

> We can't enforce this, but our plugin should be able to opt-in to use most performant backend if it's available

describes. This issue's goal is let `plugin_runner` runs with llvm compiler _if available_, but doesn't enforce or do something around llvm installation at all. This should be suffecient for the experimental phase with instructions `prod-env plugin running`.

**Comment by kwonoj** [comment]
`wapm`, or any other precompiled support would be probably needed eventually but I'd expect that's probably after stablizing initial feature sets.

**Comment by kdy1** [comment]
Yeah I agree. It should be excluded from the initial version.

**Comment by kwonoj** [comment]
ugh, I was under assumption dependency to llvm is somehow runtime, but it is actually compile time:

```
error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_120_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /home/ojkwon/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-120.2.1/src/lib.rs:486:1
    |
486 | / std::compile_error!(concat!(
487 | |     "No suitable version of LLVM was found system-wide or pointed
488 | |        to by LLVM_SYS_",
489 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
496 | |        llvmenv: https://crates.io/crates/llvmenv"
497 | | ));
```

I'll leave this opened for now for backlogging purpose. But if this is hard requirement to have llvm for the compile time, we may not easily have this.

**Comment by kwonoj** [comment]
I'm actually bit unsure llvm is required for the build time and runtime both though :thinking:

**Comment by kdy1** [comment]
I think it's both

**Comment by syrusakbary** [comment]
None of the compilers are needed for processing an already compiled module. That means, that once the module is precompiled (lets say from a `.wasm` to a `.dylib`), the runtime will not need to have any of the compilers installed (that is, it can run fully headless)

**Comment by kwonoj** [comment]
> That means, that once the module is precompiled (lets say from a .wasm to a .dylib)

@syrusakbary 

We do not expect to let plugin author to precompile binary at this moment. In particular, making platform-dependent precompile binary (.so, .dylib) defeats one of the main goal we wanted to achieve via wasm to have single binary to run everywhere.

The story in this issue aimed was (in a theoretical perspective)

- plugin is published as .wasm binary
- swc runs with default compiler if llvm doesn't exists
- or runs with llvm compiler if system have llvm installed
- generated (or compiled) byte stored as cache on those system it'll be reused

There are some stories we need to think about supporting full-precompiled story, but that's currently out of the scope.

**Comment by RiESAEX** [comment]
> plugin is published as .wasm binary

I found `wasmer compile` has `--target <target-triple>` 
Probably not bad to publish plugin's native code since we can cross compile them. 
At least plugin author don't need to use build matrix in github action like in the past.

**Comment by kwonoj** [comment]
I'm going to close this for now, will reopen if there are any breakthrough.
