### ISSUE TITLE
Support `swc_common::errors::HANDLER` in plugin

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#3308]
### Describe the bug

Context: https://github.com/swc-project/swc/blob/f5af22ef716db76a39ea22cc88f3f92745fb4aad/crates/swc_common/src/plugin.rs#L65-L90

Previous `abi_stable` based runtime had those support, while new runtime remove those logics. Host should expose those features to plugins as same as before.

### Expected behavior

-

### Version

master TOT

**Comment by kdy1** [comment]
This can be tested using code in https://github.com/swc-project/swc/pull/2616/files and https://github.com/swc-project/plugins/blob/6b6bedf5e33249a3f365ea9435dc6351600c2818/packages/internal-test/src/lib.rs
