### ISSUE TITLE
Support `swc_common::GLOBALS` in plugin

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#3309]
### Describe the bug

Context: 

https://github.com/swc-project/swc/blob/f5af22ef716db76a39ea22cc88f3f92745fb4aad/crates/swc_common/src/syntax_pos/hygiene.rs#L66-L69

https://github.com/swc-project/swc/blob/f5af22ef716db76a39ea22cc88f3f92745fb4aad/crates/swc_common/src/syntax_pos/hygiene.rs#L99-L102

Similar to https://github.com/swc-project/swc/issues/3308, runtime should support `globals` in the plugin.

### Expected behavior

-

### Version

master TOT

**Comment by kdy1** [comment]
We can create a special wrapper type which is `scoped-tls` if it's not a wasm build or `plugin-mode` is not enabled, and which calls `__emit_diagnostic` if it's wasm build and `plugin-mode` is enabled.
With this way, we can reduce work and provide identical API while testing/publishing.
