### ISSUE TITLE
Expose `use_define_for_class_fields` in SWC config

### ISSUE THREAD

**Issue by cafreeman** [swc-project/swc#3317]
### Describe the feature

When compiling a class with class fields using TypeScript syntax, SWC currently down-levels class fields no matter what version of JS is being targeted.

In other words, this:
```js
class Foo {
  foo = 'foo';
}
```

gets turned into this:
```js
class Foo {
    constructor(){
        this.foo = 'foo';
    }
}
```

no matter what config options you use.

However, the capability to avoid this down-leveling [already exists in SWC](https://github.com/swc-project/swc/pull/1478) (and [is even tested!](https://github.com/swc-project/swc/blob/366dc0eec3e19b4e608dc4df8eb728f6d710f9b7/crates/swc_ecma_transforms_typescript/tests/strip.rs#L3711-L3736)) but is unfortunately simply not exposed as a config option in the the SWC config itself.

Could you please provide a way to actually enable this feature in the SWC config?

**Comment by magic-akari** [comment]
[setPublicClassFields](https://babeljs.io/docs/en/assumptions#setpublicclassfields)

**Comment by cafreeman** [comment]
Hmmm, interesting, but both Babel and SWC preserve class fields when targeting the latest version of ES. SWC only tweaks the class fields when using the TypeScript syntax, so I'm not sure this assumption is playing a role here.

**Comment by Austaras** [comment]
No, typescript has its seperate class field transform pass
