### ISSUE TITLE
Reflect metadata "design:returntype" is undefined 

### ISSUE THREAD

**Issue by galmalka** [swc-project/swc#3319]
### Describe the bug

When using reflect-metadata, the built-in metadata "design:returntype" is always undefined.
The following code demonstrates this well.

### Input code

```typescript
import 'reflect-metadata'

let returnType: unknown;

function decorator(target: any, key: string | symbol, descriptor: PropertyDescriptor): void {
    returnType = Reflect.getMetadata('design:returntype', target, key);
}

class Foo {
    @decorator
    public foo(x: string): string {
        return 'foo';
    }
}

console.log(returnType);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020"
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

[Playground](https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAA0WOQWrEMAxF9z6Fdk4gnQM4FLoo3RVK6QU8jhLMOJaRlc6Ydu5ek0wT7SSe%2Fn9%2BTsQCmnEM6ORpRrGDFauVCijAKAvHr5LQwBIvka6xV2pcohNPEQZ0xFaIG7E8oRiwsXRwwWIgC%2Fs4wS%2FkMp8pdBXOjn2qtIEPpoQs5XW%2FtQa%2ByQ%2Fwo6DO0QvP8Lm5nWrB%2B0Ov0TXNT9FsoFRQd7BJrP1tr%2B5KuWBzhjeiR%2BzLLryuaTkH72Akam7%2Fwu1uvr0cNqArqPv1el%2FTKWYKeAo0NYdw2%2F8BxVekcFQBAAA%3D&config=H4sIAAAAAAAAA02NSwrDMAxE76J1FiFLr7vNIYQtBwf%2FkBSoCb177aSl3QnNmzcn7GLBnFCRhXhc0rLiEwxoqySWQ1WYwJEtjFpYwCgf9JpAGbP4wmm0Im1o2%2BNL3dBfbSVFh4q%2FNvJG2mdIlnmZob9ScUekYRvTPbIlpZJ3ucKQg29gPEbp4iDrh758b3M%2FIFXIAAAA)

### Expected behavior

The metadata should be populated. In the attached example it should contain the class String.

### Actual behavior

The metadata is undefined

### Version

1.2.131

**Comment by jpsatterfield** [comment]
Also running into this issue...

**Comment by t980781** [comment]
Any news on this?
