### ISSUE TITLE
Unexpected token `.`. Expected identifier, string literal, numeric literal or [ for the computed key

### ISSUE THREAD

**Issue by LukeShay** [swc-project/swc#3337]
### Describe the bug

When using decorators that have changed function calls, there is a transpilation error.

### Input code

```typescript
import * as joiful from 'joiful';

class Schema {
  @joiful.string().guid().required()
  public id: string;
}
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "decorators": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        }
    },
    "module": {
        "type": "commonjs"
    },
    "sourceMaps": "inline"
}
```

### Playground link

https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA8vMLcgvKlHQUkgsVsjKz0wrzVFIK8rPVVCHcNStubiScxKLixWCkzNScxMVqrkUgMABIqtXXFKUmZeuoamXXpqZAqSKUgtLM4tSgUywsswUKwWIEmuuWi4A7bsqiWsAAAA%3D&config=H4sIAAAAAAAAA03NQQoDIQyF4btkPSdw3e0cIsS0OKiRJEJlmLtXaQe6C%2BR9%2FCccRhBOaKjGui4b1fENAXw0NtLUHDaITKLoogbBtfO1gStWe4qWpTK%2FkMbjXn1Hf2xnx4iOPz15kdgzL7tCs0dSitTDYD5NuhLv2GYOUs2pMlwfBDeAbK0AAAA%3D

### Expected behavior

The class and decorators should be transpiled.

### Actual behavior

Error occurs saying 

```
Caused by:
    0: failed to process js file
    1: Syntax Error
error: Unexpected token `.`. Expected identifier, string literal, numeric literal or [ for the computed key
```

### Version

1.2.133

**Comment by trymoto** [comment]
Having same issue when trying to move jest tests to swc in our nestjs project.

**Comment by kdy1** [comment]
I tried fixing this, but I'm curious if this is the correct syntax.

https://github.com/babel/babel/blob/89e26a0528cf557bac53c28b1a5918c2f9089681/packages/babel-parser/src/parser/statement.js#L546-L554

Seems like babel does not support this syntax, so I need to look at the legacy proposal.

**Comment by kdy1** [comment]
> Decorator expressions are restricted to a chain of variables, property access with . but not [], and calls (). To use an arbitrary expression as a decorator, @(expression) is an escape hatch.

Seems like babel is wrong.

**Comment by RiESAEX** [comment]
babel has three version of decorators `2021-12` `2018-09` `legacy`.
but I don't even know where to find the previous proposals...
