### ISSUE TITLE
Get value from enum by key

### ISSUE THREAD

**Issue by OrlovAlexei** [swc-project/swc#3338]
### Describe the bug

Hello, i am migrating a project from ts and found this behavior. Can't dynamically get value by key in enum like in ts. Perhaps I need other settings?

### Input code

```typescript
enum Status {
  "foo" = '111',
  "boo" = "222"
}

const name = "foo"
const text = Status[name] 

console.log(text); // log: foo
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA0vNK81VCC5JLCktVqjmUlBQSsvPV1KwVVA3NDRU1wEJJEEElIyMjJS4arm4kvPziksU8hJzU0GiIOVQoZLUihKgEMSwaJCCWAWI8vycVL2c%2FHQNkApNay4A1L6k%2FXQAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm2hXeQOPYRxleDgHxoFGozvXju4ZCfNPD0V2mBpLpSNgKVPOKKaL82kR2ZYcVlpIkWLFuPBtS1GVtaGMB63%2B7PVPiXwACYKLrrl6DKbQhYGrsrE1f%2FJ2lwhffYelPPf6XxRvRzjzuE9QJWd6w%2ByirtzuAAAAA%3D%3D

### Expected behavior

Logging string:  "111"

### Actual behavior

Logging string : "foo"

### Version

1.2.133

### Additional context

Output

```javascript
var Status;
(function(Status) {
    Status["foo"] = "foo"; // not my value by key, waited Status["foo"] =  '111'
    Status["boo"] = "boo"; // not my value by key, waited Status["boo"] =  '222'
})(Status || (Status = {}));
const name = "foo";
const text = Status[name];
console.log(text); // log: 111
```

**Comment by kwonoj** [comment]
This looks like a bug to me.
