### ISSUE TITLE
[Parser]  Destructuring Binding Patterns

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#334]
Spec: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-destructuring-binding-patterns

Hope write more tests about this section.

Currently not support:

*    BindingRestProperty
*    

Problems:
```javascript
// problem: panic, should raise a syntax error.
let {...cc, c} = {};
// problem: Unexpected token, should return a `BindingPattern`.
{a, ...cc};

// Unexpected token, should return object.
let {a: {b=1}, };
{a: {b=1}, };
{a: {b=1, ...cc}={ b: 22, bb:11, bbb:222 } };

```

**Update**:

try-statement: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-try-statement

the `CatchParameter` can be a `BindingIdentifier` or a  `BindingPattern`.

```javascript
// BindingIdentifier
try {
    let e = new Error('Ooops ...');
    e.foo = 1;
    e.bar = 2;
    throw e;
} catch (e) {

}

// BindingPattern
try {
    let e = new Error('Ooops ...');
    e.foo = 1;
    e.bar = 2;
    throw e;
} catch ( {foo=0, bar=100} ) {

}
```

**Comment by LuoZijun** [comment]
Note: pls don't close this issue so quick, i will add more example.

**Comment by kdy1** [comment]
let {a: {b=1}, }; is invalid syntax. It's just cover grammar, and it's syntax error (https://www.ecma-international.org/ecma-262/9.0/index.html#sec-object-initializer-static-semantics-early-errors)

**Comment by LuoZijun** [comment]
@kdy1 

> This production exists so that ObjectLiteral can serve as a cover grammar for ObjectAssignmentPattern. It cannot occur in an actual object initializer.

as a `object initializer`, right, this is a syntax error. but in a `BindingPattern` , this is just fine.

so maybe we should have a list to know when start with `{` and end with `}` should be a `object initializer`, when should be a `BindingPattern`.

```javascript
// as a BindingPattern
let { .... };
const { .... };
var { .... };
try { } catch( { .... } );

// other as a object initializer
```

**Comment by kdy1** [comment]
We parse ambiguous things as expression as expression and then reparse as pattern if necessary. There's also verification step to prevent `{a: {b=1}, };` being treated as a valid expression

**Comment by besok** [comment]
Hey guys! I am a beginner in rust and, obviously, that project but it seems very interesting to me and I would like to aid, kicking off from the small easy task. Would you mind assigning this issue to me and I will try to close it?

**Comment by kdy1** [comment]
@besok I did it. Thank you!

**Comment by besok** [comment]
Hey. I have analyzed common and border cases and it turned out that possible scenarios have been covered. I added a couple of tests to preserve it for the future. 
@kdy1, presumably, the issue can be closed.
