### ISSUE TITLE
Armv7 binary doesn't work in next js

### ISSUE THREAD

**Issue by melsiir** [swc-project/swc#3343]
### Describe the bug

I see swc recently added support for Android armv7 and it work well but when I trying swc in next js it just doesn't work does next has deffrent binary for swc ?

### Input code

```typescript
Failed to load swc binary
```

### Config

Raw nextjs 

### Expected behavior

Everything go well

### Version

1.2.133

**Comment by nearlySplat** [comment]
Happened to me too.

**Comment by kdy1** [comment]
Please use next.js feedback thread for loading error.
