### ISSUE TITLE
Type incorrect on decorator metadata when unioning null

### ISSUE THREAD

**Issue by gregarcara** [swc-project/swc#3371]
### Describe the bug

When unioning null the type on the decorator metadata is `Object` when for example it is `string | null` the type should be `string`. This is causing issues when using type-graphql and typeorm. This is similar to https://github.com/swc-project/swc/issues/2703

### Input code

```typescript
import 'reflect-metadata';

const COL_KEY = Symbol('col');

const column = () => {
    return (object: any, key: string) => {
        Reflect.defineMetadata(COL_KEY, 'value', object, key);
    };
};

class User {
    @column() currency!: string | null;
}

console.log(Reflect.getMetadata('design:type', User.prototype, 'currency'));
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2019",
    "keepClassNames": true
  },
  "module": {
     "type": "commonjs"
   }
}
```

### Playground link

https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA02PwWrDMAyG73kK7WQH0jxAQstg9NSNwUYPOw3XUUM2xw6yPDBd3312k5TpZsn6v0%2FDODliEIRng5o3I7LqFCvRFoV21jM8vT5%2FHvYfsIX3OJ6ckUI7I8r7PL3CaNNYlrDdwaWAVIQcyIJ0p6%2BU2oCysYJvjA14psH2%2F77mepvpdYfnweLL4iAXdAXiR5mAooI57xaVDPLqtS2u2cUo7%2BHokZbYx9krSelAhFbHhxUOv2CDMWlxvsEZrI3r5WrRI98VRId%2B6G3Dccr8DKgncuxyI4mt4aIs2z%2FsblknTAEAAA%3D%3D&config=H4sIAAAAAAAAA02OMQ7CMAxF7%2BK5A7CRFVa4g5WYipLEke1KRFXuTiKEyvaH9%2FT%2BBot6cBsUFCUZS2s2fIMDq4XUy7MYTBDIs6CxKDiTldoEJpj1wZKGFWlGX68%2F6gv9aTcyDGi42ygzWc%2BQng7Hc0%2B8iMolouodE%2B2ZxGGNNBrjUBc8p8R5UWjtA3yjCke%2FAAAA

### Expected behavior

`[Function: String]` is output

### Actual behavior

`[Function: Object]` is output

### Version

@swc/core: 1.2.133

### Additional context

Used [#2703](https://github.com/swc-project/swc/issues/2703) as a reference.

**Comment by kdy1** [comment]
This requires typesystem

**Comment by kdy1** [comment]
Closing as the Closing as the stc is now abandoned. https://github.com/swc-project/swc/issues/571#issuecomment-1915966297
