### ISSUE TITLE
Mobx - observable can't be applied 

### ISSUE THREAD

**Issue by K-Jean** [swc-project/swc#3389]
### Describe the bug

For mobx, class field need to be defined for that you need [this option](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) in the tsconfig.json :

```json
{
    "compilerOptions": {
        "useDefineForClassFields": true,
    }
}
```

When I try to compile my application with swc I have this error : 

> Error: [MobX] Cannot apply 'observable' to 'User@2.elo': Field not found.

And if we follow what the answer in this [stackoverflow](https://stackoverflow.com/questions/67266810/error-mobx-cannot-apply-observable-to-storeuser-field-not-found) said that I need to use **useDefineForClassFields** which I already use.

### Expected behavior

That I can use **useDefineForClassFields** in my tsconfig

### Version

1.2.135

**Comment by Austaras** [comment]
Are you using typescript?

**Comment by K-Jean** [comment]
yes I'm using typescript @Austaras

**Comment by K-Jean** [comment]
Any new for this ? @kdy1
