### ISSUE TITLE
[Parser] export default problem

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#340]
Spec: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-exports

`export default` can follow `HoistableDeclaration`, `ClassDeclaration` and `AssignmentExpression` (not including `FunctionExpression`, `AsyncFunctionExpression`, `GeneratorExpression`, `AsyncGeneratorExpression` and `ClassExpression`).

```javascript
export default function(){};         // syntax error
export default async function(){};   // syntax error
export default async function*(){};  // syntax error
export default class {};             // syntax error
```

**Comment by kdy1** [comment]
Only `async function* (){ } is syntax error` from those is syntax error.
Other stuffs are not syntax error. (babel also supports it). I added a test to ensure that those are not treated as syntax error.

**Comment by LuoZijun** [comment]
```
export default HoistableDeclaration
export default ClassDeclaration
export default [lookahead ∉ { function, async [no LineTerminator here] function, class }] AssignmentExpression;

HoistableDeclaration:
    FunctionDeclaration
    GeneratorDeclaration
    AsyncFunctionDeclaration
    AsyncGeneratorDeclaration

```

`function (){} ` is `Function Expr` not `FunctionDeclaration`.
`class {}` is `ClassExpr` not `ClassDeclaration`.

**Comment by braddunbar** [comment]
I've been looking into this, but I have a question or two. 🙋

It sounds like the goal is to accept both class/function expressions and class/function declarations in export default declarations. Is that right? If so, I think all we need is to add tests for them, which already pass. If not, we need to replace `ClassExpr`/`FnExpr` with `ClassDecl`/`FnDecl` in `DefaultDecl`. I tried this out in a branch locally and it's not too difficult.

Is that how you understand things as well? Let me know what you think!
