### ISSUE TITLE
v1.2.130 breaks "this" context in the backbone model

### ISSUE THREAD

**Issue by jakub-tucek** [swc-project/swc#3413]
### Describe the bug

Version 1.2.130 breaks backbone models in our application with the following error:

```
backbone.js:1102 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'idAttribute')
    at CardCollection.modelId (backbone.js:1102:1)
    at CardCollection.get (backbone.js:997:1)
```

the issue happens on this line:

```
    modelId: function(attrs) {
     // this.model is undefined in this context
      return attrs[this.model.prototype.idAttribute || 'id'];
    },
```

On version 1.2.129, this works fine.

### Config

```
{
  "test": ".jsx?$",
  "sourceMaps": true,
  "inlineSourcesContent": true,
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "decorators": false,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "throwIfNamespace": true,
        "refresh": true,
        "useBuiltins": false,
        "runtime": "automatic"
      }
    },
    "target": "es2015"
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false,
    "ignoreDynamic": true
  }
}

```

### Expected behavior

same as in 1.2.129 version

### Version

1.2.130

**Comment by mikevercoelen** [comment]
Same problem here, crucial.

```
class Previewer extends React.Component {
  dummy = false
  
  componentDidUpdate (prevProps, prevState, snapshot) {
    this.initialize()
  }
  
  initialize = async () => {
    
  }
  
  loadObject = async () => {
    // Breaks, no access to this anymore....
    if (this.dummy) {
      ...
    }
  }
}

```

**Comment by jakub-tucek** [comment]
when I downgraded to 1.2.129, the code mentioned by me above started to work but I noticed some other parts of APP are still broken (issue a bit more similar as by @mikevercoelen - async function, _this_ not accessible). Had to downgrade back to 1.2.125

**Comment by kwonoj** [comment]
this sounds like some regressions around recent changes in https://github.com/swc-project/swc/issues/2716 ?

**Comment by Austaras** [comment]
> Same problem here, crucial.
> 
> ```
> class Previewer extends React.Component {
>   dummy = false
>   
>   componentDidUpdate (prevProps, prevState, snapshot) {
>     this.initialize()
>   }
>   
>   initialize = async () => {
>     
>   }
>   
>   loadObject = async () => {
>     // Breaks, no access to this anymore....
>     if (this.dummy) {
>       ...
>     }
>   }
> }
> ```

This compiles to 
```js
var _this = this;
this.loadObject = _asyncToGenerator(function*() {
     // Breaks, no access to this anymore....
     if (_this.dummy) {
     }
})
```
which seems fine

**Comment by kdy1** [comment]
Can you share more input code?
I can't create a test from the info you wrote

**Comment by kdy1** [comment]
Closing as the author did not provide enough information to debug.
