### ISSUE TITLE
Tagged template literals: source maps are out of place

### ISSUE THREAD

**Issue by iamakulov** [swc-project/swc#3416]
### Describe the bug

Hey,

Thanks so much for maintaining `swc` and especially `@swc/jest`! A client of mine has just lowered their test execution time ~30× by switching to `@swc/jest` (84 minutes → 3 minutes¹).

_[¹ — clarifying as I got a DM with questions: these numbers are from a local MacBook Pro since the primary thing we were focusing on was DX. CI numbers are more modest, unfortunately: they’re in the range of 1.5×-4×.]_

While helping the client to migrate the test suite to `@swc/jest`, I stumbled upon an issue of imprecise source maps. When some code uses a tagged template literal, eg:

```js
import { css } from "linaria"

export const Button = css`
    color: red;
`
```

source maps for the `css` call point to the wrong line.

This matters for us because we use `new Error().stack` to infer line numbers and function names, and with `swc`, the error stack isn’t correct. We had to switch to `esbuild-jest` to get correct source maps in some files.

### Input code

```typescript
import { css } from "linaria"

export const Button = css`
    color: red;
`
```

### Playground link

https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA8vMLcgvKlGoVkguLlaoVUgrys9VUMrJzEssykxU4uJKrQBLJ%2BfnFZcoOJWWlOTnKdiC1CZwKQBBcn5OfpGVQlFqijVXAgAU2FAXSwAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSw6EMAxD75I1C8Syd%2BAQVSegov4UF2kq1LtPOiCxc2L7%2BaIDjsxFxQpYhkJL1X7JUG2F4cSXShNV6KvKyV21lZ2rJhjLvMzqhpzBtz9R9MlvbaBcjkUYILPZgGHZtAd%2Bzq6omD%2FneFz%2FNUVqJeZ0gPoLesoe65O%2Bd5BPcbzaonzyKfjE1H%2BbWk6e0QAAAA%3D%3D

### Expected behavior

1. Grab the transpiled code from the playground link above
2. Save it into a new file
3. Install the `linaria` package next to that file
4. Run `node --enable-source-maps index.js`

You should get an error that will read like this:

```
Error: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.
    at Object.css (/private/tmp/source-map/node_modules/linaria/src/core/css.ts:8:9)
    at Object.<anonymous> (/private/tmp/source-map/input.tsx:3:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

Note the reference in the second line of the stack. It’s `input.tsx:3:22` – linking to line 3 of the playground file:

```
export const Button = css`
```

This is the expected behavior.

### Actual behavior

Instead, the following error is generated:

```
Error: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.
    at Object.css (/private/tmp/source-map/node_modules/linaria/src/core/css.ts:8:9)
    at Object.<anonymous> (/private/tmp/source-map/input.tsx:1:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

The second line of the stack (`input.tsx:1:30`) references the first line of the source file:

```
import { css } from "linaria"
```

No matter how many `css` calls there will be in the file, each tagged template literal will be mapped to the import, not to the place where it’s actually called. This is incorrect.

### Version

1.2.133

### Additional context

- A workaround is to transpile the code down to ES5. That gets rid of tagged template literals and fixes the mappings
- You can see how the source and the generated files are mapped if you copy the generated file, save it, and upload the result into https://sokra.github.io/source-map-visualization/#custom-choose

**Comment by kdy1** [comment]
Actually, I was looking at this exact issue (jest sourcemap)
Does this happen only with template literals?
If so, I can use it for investigating, thanks!

**Comment by iamakulov** [comment]
> Does this happen only with template literals?

That’s the only case I stumbled upon so far!
