### ISSUE TITLE
SWC produces code that crashes for simple function with nested for loops

### ISSUE THREAD

**Issue by pboyer** [swc-project/swc#3417]
### Describe the bug

This code crashes due to an uncaught reference error: `_iterator` is not defined.

The offending code is at line 98.

        for(var _iterator3 = levels[Symbol.iterator](), _step4; !(_iteratorNormalCompletion3 = (_step4 = _iterator3.next()).done); _iteratorNormalCompletion3 = true)_loop(_iterator, _step);

There is clearly a scoping bug here.

### Input code

```typescript
export function selectRooms(building: Building) {
  const roomsByRow: { [key: string]: [string, string, string, string] } = {};

  const { rooms, walls, levels, roomsByLevel } = building;

  function getRoomFloorMaterial(_: Room) {
    return null;
  }

  for (const level of levels) {
    const levelId = level.id;
    const levelRooms = roomsOnLevel(levelId, rooms, roomsByLevel);

    const sortedRooms: Room[] = [];
    for (const room of levelRooms) {
      sortedRooms.push(room);
    }

    sortedRooms.sort((a, b) => a + b);

    const visitedRooms: { [roomId: string]: boolean } = {};

    for (const room of sortedRooms) {
      if (visitedRooms[room.id]) {
        continue;
      }

      const connectedRoomSet: RoomSet = [];
      const roomPrettyName = formatRoomName(room);
      const roomFloorMat = getRoomFloorMaterial(room);

      groupRoomsOnLevel(
        room,
        walls,
        (_, endRoom, wall) =>
          wall.wallType === WallType.VOID &&
          roomPrettyName.toUpperCase() === formatRoomName(endRoom).toUpperCase() &&
          roomFloorMat === getRoomFloorMaterial(endRoom),
        (room) => connectedRoomSet.push(room),
        visitedRooms,
      );

      let areaTotal = 0;
      for (const setRoom of connectedRoomSet) {
        const wallIndex = walls[levelId].wallIndex;
      }

      areaTotal = Math.round(areaTotal) / 10;
      roomsByRow[room.id] = [roomPrettyName, `${areaTotal} SF`, roomFloorMat, FLOOR_MAPPING[levelId]];
    }
  }
  return { rows: Object.values(roomsByRow) };
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA3VUXW%2FaMBR9r9T%2FcB%2BmKtGisL2CmLRuYkJqC6Ld9oAiaoiBbMaOHAeKUP77rh3HNpS9%2BPN%2BnHPvselbKaSCdc1XqhAcKsroSs2E2FXRsi5YXvBNH%2B7tKobT7Q3ASvBKgdRG98eZOPThBPO%2F9NiHSkk0y%2Fowb1cJXJ8zaGAIp2Zwe%2BMDntqQCRwIYzgxuqd6toke9Nb4dcCstwO%2FoQb5iAkhH4misiAsWvRBH1roAJKqWnLgNWMDfdLYIEJC1OIweUGsLQDnGdyOc4RhVmmRD95dm%2FqhhUE%2B4QZ5ZB2TjmVIK7ZUAHo9qHRHzC0gkxLUVop6swXCyi1ZUlassD7HMKn2oLnJ2rKdZ5h9nllkATcd1lEzDo4ehGHSsq62kbaObZCmQxha6XUUkQSWMQy%2FAIGPuHJc2pT7oio8OlSKjjrOA7EshWCU8HNNXIUd5A5wF2uIwiwmAzYmC2wMGlXwmg66I8eoQ4ojR%2FW3UZ6pamuJi7CYofynKCZ1fCI7ihYId0eMAPXBWe1Cn06d6HFVr51f57nB5pezUEiekrZN%2FLZ9N34fLRKg3LBpH5Vukr9uHVI9vBxLpDAcwm%2B7SX9Nxt%2Fh7i60PmecKvGzLKn8Rioaxcb5ogI2dXxh%2BT6oL8nwP0XpQoXkTKG06i7bFmg3sA8F4o7DQuPLK6VY0aoCTg9t3f0dkZR0O4aK0PsXoQjDPn5ybQ4kW7U8tGovAV7KEq11E8Y8p28YzrRxbr%2BLLHVX14QbwsBqbVNEzfPIHcfQg88en%2F%2Bz3RvR2j7vbAKvH04uQgPPo9fkrE8JjB4mk9ni8et0On764aBm%2Fquwg%2F1s9c9%2BwMc%2FWf7BOqR7wmpaRR5MDPrVN%2F8A9FVEkY0GAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

I expect this to produce correct code that doesn't crash.

### Actual behavior

The code crashes

### Version

1.2.133

**Comment by RiESAEX** [comment]
I think this is fixed in #3400
