### ISSUE TITLE
Minification - Missing `reserved` mangle option

### ISSUE THREAD

**Issue by bogy0** [swc-project/swc#3424]
### Describe the feature

Do not mangle property names listed in the `reserved` array as you can see in [Terser's documentation](https://terser.org/docs/api-reference.html#mangle-options).

```
{
  "jsc": {
    "minify": {
      "mangle": { 
         reserved: ['firstLongName']
      }
    }
  }
}
```

### Additional context

In our codebase we have some reserved function names which later in our build process we try to match to post-process it. Without the `reserved` option we are not able to use SWC to minify our code.

We would be grateful for this feature or a workaround suggestion.

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/pull/3476
