### ISSUE TITLE
Extra trailing decimal point after minify turns number into exponential form

### ISSUE THREAD

**Issue by ghbakhtiari** [swc-project/swc#3428]
### Describe the bug

When a `Number.prototype` method is accessed on a number we have two `.` like `10000..toString()`.

After minifying, the number is turned to exponential notation (`10e3`) but the trailing decimal point isn't removed. Causing in a broken code regardless of `target`.

### Input code

```typescript
console.log(10000..toString());
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.135&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1zA0AAI9vZL84JKizLx0DU1NawDOiEazHwAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F8WLLHKHHkK4SnDxD0mBGOO71w4p2Wlmnl6DrzhYGxRkIZ6X1KR4wgrkIopjXxTMwEa1YRDqBhR5J52I2Je1Yw45C92AgeiT3%2BqUuRwLk8gzYdrDn%2BzDFfPnmEUDrYUu5wL9cSgf483L%2B%2BZm7j%2BEq2LdtwAAAA%3D%3D

### Expected behavior

Should output:
```js
console.log(10e3.toString())
```

### Actual behavior

Gives:
```js
console.log(10e3..toString())
```

### Version

1.2.135

### Additional context

In a more complicated scenario, you might have stored the number in a constant and then call a prototype method on the constant. Which then if you have `compress` enabled too, it will cause the same issue.

[playground link](https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA0vOzysuUcgrzU1KLVKwVTA0AAJrrmSgaH5Oql5OfroGRE6vJD%2B4pCgzL11DU9OaCwDIb%2FN5NgAAAA%3D%3D&config=H4sIAAAAAAAAA22TS5LjIAyG78I6i6ksZtEHmF2fgVJAOOqxwYVEOq5U7j7CdmM7mR36%2BCX04mG%2B2JmPhxkhM%2BZ64ikK3M2HQTcAu0yjmJPKFAXoGZ8nI5A7lCrh86%2FzWa%2F7lBhXwckMFClMNZhLw5iRuZ7VqQwYhZsOck7fakoual1S6hHim22BLUXBDvPm6lLfw8hob5CbR30NMnGKB1QEvR1zGvfu0ZNQimo26BG8dclvhXjK6IRuuBNpHBVF1uSO0OOldF1t4vI03qAvINjs%2B9wKfbT5XROx2FAiv6A128VxQUuhq4qCzSglxx%2FNV6J46MVfRM2zB%2BYIwy7%2FmQedxVEZ%2FqOiGHSQMjWqU96yithpcZYotApr1piFsIky%2BuKwVui24Cs8FMTk0WII2u7mzN8k7rrLSqYRU2j32jYI2xAW0%2F4s1ZHWPXiDfzQt2c9j5QPI9ZXxNFxS%2FxZiQLkm%2F4a1E5JeYdYVvo%2BvtESP2mf0u4vC1axV6m8bIHZt154VJF8qeMwNmb%2Fhb%2FPcvt3SHeLPVTfH%2BQdhdVg56gMAAA%3D%3D)

**Comment by alexander-akait** [comment]
Fixed by https://github.com/swc-project/swc/pull/3425
