### ISSUE TITLE
[Parser] regex literal problem

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#343]
Spec: https://www.ecma-international.org/ecma-262/9.0/index.html#prod-RegularExpressionFirstChar

```
RegularExpressionLiteral::
    / RegularExpressionBody / RegularExpressionFlags

RegularExpressionBody::
    RegularExpressionFirstChar RegularExpressionChars

RegularExpressionFirstChar::
    RegularExpressionNonTerminatorbut not one of * or \ or / or [
    RegularExpressionBackslashSequence
    RegularExpressionClass

RegularExpressionNonTerminator::
    SourceCharacterbut not LineTerminator

```

```javascript
let re = /*/g;    // RegularExpressionFirstChar can not be * or \ or / or [
let re = /\a/g;  // RegularExpressionFirstChar can not be * or \ or / or [
let re = ///g;    // RegularExpressionFirstChar can not be * or \ or / or [
let re = /[]/g;  // RegularExpressionFirstChar can not be * or \ or / or [
```

**Comment by Zzzen** [comment]
```js
let re = ///g;    // RegularExpressionFirstChar can not be * or \ or / or [
```

Shouldn't [SingleLineComment](https://www.ecma-international.org/ecma-262/9.0/index.html#prod-SingleLineComment) have higher priority such that it's never recognized as regex?

**Comment by Alex-ley** [comment]
I would agree with @Zzzen, the line included in the example would be treated a comment.

To correctly set up a RegEx to match on a forward slash "/", you would do something like this:

```js
let re = /\//g;   
let myString = "test/string/example";
console.log(myString.match(re));
```

**Comment by besok** [comment]
Hello, can i take this issue?

**Comment by kdy1** [comment]
Of course. It would be really appriciated.

**Comment by besok** [comment]
may you assign it to me otherwise it will hard to find?

**Comment by besok** [comment]
the regex seems to be working fine. The single-line comment and multiline comment has a higher priority and be skipped while parsing. I added a couple of tests which summoned to display that. 
Therefore I guess the issue can be closed.

**Comment by kdy1** [comment]
@besok Thanks! I'll close this with #1303.
