### ISSUE TITLE
Add a node api to get webpack AST

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#3437]
This should be under experimental flags.

See https://github.com/webpack/webpack/issues/13425 for the context

**Comment by vankop** [comment]
@kdy1 what should be done? maybe I could help with this issue. As I understand there is a way to get acorn AST already.

**Comment by kdy1** [comment]
@vankop There's a PR I worked. https://github.com/vercel/next.js/pull/31823/files

Basically you can use `babelify()` from https://docs.rs/swc_estree_compat/latest/swc_estree_compat/babelify/trait.Babelify.html after setting `Flavor` (https://docs.rs/swc_estree_ast/latest/swc_estree_ast/flavor/enum.Flavor.html) to `Acorn`
