### ISSUE TITLE
Named exports not triggering hoisting

### ISSUE THREAD

**Issue by tmayr** [swc-project/swc#3439]
### Describe the bug

We just detected one of our compiled files failing when ran with the following error 

```
cannot access xxx before initialization
```

After a bit of researching, it seems that the code that triggered it was a named export being used before its initialization, this however did not fail with `esbuild` or `tsc`.

I managed to find one big difference in the outputs of `tsc` and `swc` with this test case

```js
// repro case
export { foo }
const foo = 123

// tsc
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
const foo = 123;
exports.foo = foo;

// swc
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = foo;
const foo = 123;
```

Both were tried with the following options
- target: es2019
- module: commonjs

Both transpilation outputs were taken from the playgrounds.

This looks like a bug to me?
Thanks for the time reviewing this!

### Expected behavior

It seems that `swc` is failing to hoist the const definition compared to `tsc` , expected behavior would be what `tsc` is doing

### Version

1.2.136

**Comment by magic-akari** [comment]
input:
```javascript
export { a };
let a = 1;
a = 2;
use((a = 3));

({ a = 4 } = {});
```

TS output([REPL](https://www.typescriptlang.org/play?target=6&jsx=0&module=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQAKLALilQE8BKSmgbgChmQAPABxxg3gG94UeAF8WEEH2EBeeAEYWM+ACYWRUiSUBmWrRbMSgpQBZR8WfxF7mQA)):
```javascript
"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.a = void 0;
let a = 1;
exports.a = a;
exports.a = a = 2;
use((exports.a = a = 3));
(_a = {}.a, exports.a = a = _a === void 0 ? 4 : _a);
```

Babel output([REPL](https://babeljs.io/repl#?browsers=chrome%2075&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAbzgQzgXwNwCgA2x6oC8cAjNkXAEzYCuAzsABSMUDMAlO9lo0hQCzo4xBGi5YgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.17.0&externalPlugins=&assumptions=%7B%7D)):
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.a = void 0;
let a = 1;
exports.a = a;
exports.a = a = 2;
use((exports.a = a = 3));
({ a = 4 } = {});
exports.a = a;
```

swc output([REPL](https://play.swc.rs/?version=1.2.136&code=H4sIAAAAAAAAA0utKMgvKlGoVkhUqLXmykktATJsFQytuUCUkTVXaXGqhgaIbaypac3FpVENljdRqAWS1bVAIQCFE3I1QQAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm13zR16COMqwcE%2FNA7UGN%2B9cnHJTtK8eWp0wNLaKBsBy5hQYzEfWqnUzLDicqGFCvS0GQ%2FuuhjZuSjCeNzuT419SuAJLBRcdFsdMptCFgauyMTd%2F8murpDe5zi03z91aiWkeID6JZplh9eki5zcv5LritG9AAAA)):
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.a = void 0;
exports.a = a;
let a = 1;
a = 2;
use(a = 3);
({ a =4  } = {});
```
