### ISSUE TITLE
A class descriptor's .kind property must be "class", but a decorator created a class descriptor with .kind "undefined"

### ISSUE THREAD

**Issue by AndrewGrachov** [swc-project/swc#345]
```
@folderActions(FOLDER_TYPES.upload)
class FoldersComponent extends PureComponent {
```

```
export function folderActions(folderType) {
	return (Component) => { // eslint-disable-line arrow-body-style
		return (props) => {
```

maybe related

https://github.com/mobxjs/mobx/issues/1352

**Comment by kdy1** [comment]
@AndrewGrachov How should be 

```js

@folderActions(FOLDER_TYPES.upload)
class FoldersComponent extends PureComponent {
}
```
compiled? Issue is too abstract to work on it.

**Comment by AndrewGrachov** [comment]
Hello kdy. I created a minimum reproduceable repo

https://github.com/AndrewGrachov/swc-repro-repo

**Comment by AndrewGrachov** [comment]
It seems, that teh problem is in double wrapping functions.
If I comment out outer function, everything works fine

```
function deco(someString) {
 // return (MyClass) => {
    return (props) => {
      console.log('props!:', props);
      return {...props}
    }
 // }
}
```

**Comment by kdy1** [comment]
Note that current behavior is identical to [it of babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAJgU1DAvDAFBEBbBBlKAJwEswBzASlQD4YBvAKBhkISgFdCwMBZATwDCAGwCGECFRS1GzZqw5cMAB0IglEmvSazmoSCCEIAdEJBl0AchVqIAQgBcFgDQxr6igG5tO-Z250jQLcIAF9vGDDmMLCGYFFxGAAhMQRhMQgtGIABRFBLBAAPEWwlQwsKWPiM_jSEwqgEMDgM5IhUqq0GEKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2&prettier=true&targets=&version=7.4.1)

**Comment by AndrewGrachov** [comment]
They fixed it in 7x.x

**Comment by AndrewGrachov** [comment]
https://babeljs.io/docs/en/babel-plugin-proposal-decorators this one

**Comment by kdy1** [comment]
@AndrewGrachov Is this usage of decorator correct?
I've looked at change logs of decorator package, but no test / actual code is modified.

```js

const deco = (someString) => {
  return (MyClass) => {
    return {
      kind: 'class',
    };
  }
}

```

works, but I'm not sure about what does decorator spec says about it.

**Comment by AndrewGrachov** [comment]
yep. decorate constructor

**Comment by imerkle** [comment]
getting the same error

**Comment by kdy1** [comment]
I think this is fixed
