### ISSUE TITLE
Inline configuration doesn't support TypeScript + JSX

### ISSUE THREAD

**Issue by guybedford** [swc-project/swc#3458]
### Describe the bug

When running SWC with inline configuration options using the `-C` option, setting the syntax to `typescript` works, and also setting `-C jsc.parser.jsx=true` also works for parsing JSX, but these two options cannot be used together - throwing a JSX error in this case.

### Input code

```typescript
swc input.ts -o output.js -C jsc.parser.syntax=typescript -C jsc.parser.jsx=true --no-swcrc
```
```


### Config

_No response_

### Playground link

_No response_

### Expected behavior

It should be possible for the combination to result in the TypeScript JSX mode.

### Actual behavior

The JSX option is just ignored

### Version

@swc/cli: 0.1.53 @swc/core: 1.2.119

### Additional context

_No response_

**Comment by kdy1** [comment]
It's tsx, not jsx

**Comment by guybedford** [comment]
@kdy1 thanks for the quick response, it still doesn't though with the suggestion:

```
swc input.ts -o output.js --no-swcrc -C jsc.parser.tsx=true -C jsc.parser.syntax=typescript
```
