### ISSUE TITLE
CSS parser errors when parsing asterisk before css property

### ISSUE THREAD

**Issue by skittles1412** [swc-project/swc#3472]
### Describe the bug

`parser.parse_all()` returns an `Err` value when parsing a property prefixed by an asterisk (it's a hack for IE 7 and below [source](https://stackoverflow.com/questions/1690642/purpose-of-asterisk-before-a-css-property)). This is not spec compliant but it should not return an error.

### Input code

```typescript
use swc_common::{input::StringInput, BytePos};
use swc_css_parser::{
    lexer::Lexer,
    parser::{Parser, ParserConfig},
};

fn main() {
    let data = "a { *font-size: 16px; }";
    let input = StringInput::new(data, BytePos(0), BytePos(u32::MAX));
    let config = ParserConfig {
        parse_values: false,
        allow_wrong_line_comments: false,
    };
    let lexer = Lexer::new(input, config);
    let mut parser = Parser::new(lexer, config);
    parser.parse_all().unwrap();
}
```

### Expected behavior

`parser.parse_all()` should not return an error. Instead, this hack should be reflected in the AST somehow.

### Actual behavior

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(4), hi: BytePos(5), ctxt: #0 }, ExpectedButGot("\"}\"")) }'
```

### Version

swc_common = "0.17.3", swc_css_parser = "0.69.0"

**Comment by alexander-akait** [comment]
@kdy1 Expected, because it is violate CSS spec, we can implement `ie` option for this, but I think it was bad for design, I want to say change `*` on `_`, i.e. violate many things in CSS:
```
.selector { !property: value; }
.selector { $property: value; }
.selector { &property: value; }
.selector { *property: value; }
.selector { )property: value; }
.selector { =property: value; }
.selector { %property: value; }
.selector { +property: value; }
.selector { @property: value; }
.selector { ,property: value; }
.selector { .property: value; }
.selector { /property: value; }
.selector { `property: value; }
.selector { ]property: value; }
.selector { #property: value; }
.selector { ~property: value; }
.selector { ?property: value; }
.selector { :property: value; }
.selector { |property: value; }
```

**Comment by alexander-akait** [comment]
As you can see `@property` even violate nested at-rules, and `&property` violate nested CSS selectors (new spec)

**Comment by kdy1** [comment]
I also think it should be at most recovered error. 
It's a syntax error anyway.

**Comment by alexander-akait** [comment]
hm, we can do error recovery here :+1: I will look
