### ISSUE TITLE
About lexical analyzer performance issues

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#348]
I wrote the lexical analyzer in two ways and found that there was a significant performance gap between them.

This may be helpful for your subsequent performance optimizations.

1.    https://github.com/LuoZijun/es/blob/master/src/parser/lexer.rs#L1400-L1425
2.    https://github.com/LuoZijun/es/blob/master/src/parser/lexer2.rs#L1535-L1559

Result:

```
1. parser::lexer::bench_tokenization ... bench:   1,910,589 ns/iter (+/- 291,320) = 33 MB/s
2. parser::lexer::bench_tokenization2 ... bench:   3,377,773 ns/iter (+/- 331,006) = 18 MB/s
```

**Comment by kdy1** [comment]
@LuoZijun Can you tell me more about this?
I were busy implementing features, and currently I'm optimizing parser.
