### ISSUE TITLE
"Unambiguous" source type

### ISSUE THREAD

**Issue by seansonb** [swc-project/swc#3493]
### Describe the feature

With babel, you can set your source type to "unambiguous" which checks for the existence of any import/export statements and treats it as a module if found, and a script otherwise. SWC doesn't seem to allow you to set a source type and I couldn't find any documentation around how it decides. Here are two SWC playground links for a script that would not be treated as a module under the 'unambiguous' source type that SWC does treat as a module, and since I'm using commonjs modules, transpiles 'this' to void 0, which is in-line with specs, but I want to be able to treat this as a script without disabling module functionality.

[script](https://play.swc.rs/?version=1.2.130&code=H4sIAAAAAAAAAytLLcpMqwwoyi9ILSqp1CjJyCzWUVB3LCpKrFTXUajmUlAoS8wpTbVSAAvpAPnlRZkliUk5QKGSotJUkEhqXmluahFELC0xpxgsmJyfl5aZXlqErLRW0xoAVhuZVXAAAAA%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t934Dj2EcJXg4B%2BSAjXGd69FDF1pNDNvBlwSwA9oyEJsSnpR%2FIIHChklcGwKbtWWpXzTdKDIJ6k15LWiVKvQEzrIscSj206ouTGJgD8wiUVYzkT7nWsn189txgDtbV1Dci2XwPwPbTjKe7cf%2FAesTJxCuQAAAA%3D%3D)
[module](https://play.swc.rs/?version=1.2.130&code=H4sIAAAAAAAAAytLLcpMqwwoyi9ILSqp1CjJyCzWUVB3LCpKrFTXUajmUlAoS8wpTbVSAAvpAPnlRZkliUk5QKGSotJUkEhqXmluahFELC0xpxgsmJyfl5aZXlqErLRW0xoAVhuZVXAAAAA%3D&config=H4sIAAAAAAAAA0WOSwoDMQiG7%2BI6225yhx5CUmfIkBfqQEPI3RvbQFfq%2F%2FhwwCUB%2FICGLMS2SS%2BKb%2FBAIaMEjk3BrdiSlG%2BaDhT5JLWEPJaVahX6mQ5yLPHoxgk1NyYR8AcmMQvLmWifc3Fyfd0mDNDe1rRKruUSmH%2FQLkd57vT3iQ%2BfOTFluAAAAA%3D%3D)

Maybe this is a bug since it seems like SWC is already making these decisions on the fly, but there is no reason that a script like this one should be treated as a module. 

### Babel plugin or link to the feature description

https://babeljs.io/docs/en/options

**Comment by kwonoj** [comment]
Is this related with https://github.com/swc-project/swc/issues/2541?

**Comment by seansonb** [comment]
@kwonoj It looks like the same thing. So setting isModule to unknown should work the same?

**Comment by kwonoj** [comment]
I haven't tried honestly. Mind give it a shot just in case to see if we have free win?

**Comment by seansonb** [comment]
@kwonoj Looks like it worked. Should probably be added to the docs ;). Thanks for the help! Closing this.
