### ISSUE TITLE
Commonjs Import aliasing

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#351]
### swc version
```
$ grep swc package.json
    "@swc/cli": "0.1.12",
    "@swc/core": "1.0.39",
    "swc-loader": "0.1.4",
```

### .swcrc
```
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Input
```js
import React from 'react';

<div />;
```

### Output
```js
'use strict';
var _react = _interopRequireDefault(require('react'));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
React.createElement('div', null);
```

### Problem
`React` is never defined, resulting in a Reference error when trying to create a React element.

**Comment by NicholasLYang** [comment]
Similar issue, when I compile the output has `import React1 from 'react'` (which tbh I'd prefer to be compiled as a require like babel) but the JSX compiles to `React.createElement`. Creates a nasty runtime bug that's a little tricky to catch.
