### ISSUE TITLE
typeof/instanceof helper function not being brought in when evaluating with 'script' source type.

### ISSUE THREAD

**Issue by seansonb** [swc-project/swc#3510]
### Describe the bug

When evaluating a script that uses typeof with sourceType=script, it attempts to use a helper function '_typeof' that is brought in when sourceType=module, but it's not brought in when the sourceType=script. 

### Input code

```typescript
const obj = {};
const type = typeof obj;
```

### Config

```json
{
  "isModule": "unknown",
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "ecmascript"
    }
  }
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": "true"
}
```

### Playground link

https://play.swc.rs/?version=1.2.130&code=H4sIAAAAAAAAA0vOzysuUchPylKwVaiuteZKBvNLKgtSgQIgKj8NJGsNAJVpYR4oAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t934Dj2EcJXg4B%2BSAjXGd69FDF1pNDNvBlwSwA9oyEJsSnpR%2FIIHChklcGwKbtWWpXzTdKDIJ6k15LWiVKvQEzrIscSj206ouTGJgD8wiUVYzkT7nWsn189txgDtbV1Dci2XwPwPbTjKe7cf%2FAesTJxCuQAAAA%3D%3D

### Expected behavior

Either don't use _typeof helper function, or inline the function.

### Actual behavior

Uses the helper function without bringing it into the script resulting in '_typeof is undefined' execution error.

### Version

1.2.127

### Additional context

It looks like this also happens with instanceof

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/swc-project/swc/pull/4025
