### ISSUE TITLE
Using static property from a class in decorators on the same class

### ISSUE THREAD

**Issue by anzerr** [swc-project/swc#3521]
### Describe the bug

The output code when run throws "ReferenceError: Cannot access 'FormulaRuleEntity' before initialization". The same code built using tsc is valid.

The output code using tsc looks like this
``` javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var FormulaRuleEntity_1;
const Test = (name) => {
    return (target, key) => {
    };
};
let FormulaRuleEntity = FormulaRuleEntity_1 = class FormulaRuleEntity {
};
FormulaRuleEntity.NAME = 'cat';
FormulaRuleEntity = FormulaRuleEntity_1 = __decorate([
    Test(FormulaRuleEntity_1.NAME)
], FormulaRuleEntity);
//# sourceMappingURL=index.js.map
```

### Input code

```typescript
const Test = (name: string): any => {
    return (target: any, key: string) => {
        // stuff
    };
}

@Test(FormulaRuleEntity.NAME)
class FormulaRuleEntity {

    static readonly NAME = 'cat';

}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.138&code=H4sIAAAAAAAAA2VOvQrCMBDeA3mH25qC2L2lokPddBBf4IhpCaZXSC5DkL67iQUR%2FIYb7vuVQi8UGO4mnx4U4WxaCOwtTXULSAn6A7ykgAxvOHoCxegnwx92B0%2BTvoYfbUHTZCKO4%2FZZOylWKaQ4ljJ1XvwcHd6iMwOx5bS%2Fni5DLYV2GAL80SV4CwqMbHVeg4%2BFXILiy9srjVx1RZRb3o8lVxnYAAAA&config=H4sIAAAAAAAAA0WOQQ7DIAwE%2F%2BJzDhWHHvhDH4GIE1EBRrYjFSH%2BXoLS5mbt7ozc4C0ebIPiWJDPS2pW9wELWguK51AUFlAZ0eai4AIremKnxAJW%2BcA%2Basc76oBQzMOYAUQiwT%2BSQg5bPfWeUmEUuSuX9%2Fhb9uFKtB5n0OYH0%2FmEfjsuLsjrGs4fvucDfqLKAAAA

### Expected behavior

The output code should not throw "ReferenceError: Cannot access 'FormulaRuleEntity' before initialization"

### Actual behavior

throw "ReferenceError: Cannot access 'FormulaRuleEntity' before initialization"

### Version

1.2.138

**Comment by andreyvital** [comment]
Here's a link to the SWC playground: https://play.swc.rs/?version=1.2.138&code=H4sIAAAAAAAAA2VOvQrCMBDeA3mH25qC2L2lokPddBBf4IhpCaZXSC5DkL67iQUR%2FIYb7vuVQi8UGO4mnx4U4WxaCOwtTXULSAn6A7ykgAxvOHoCxegnwx92B0%2BTvoYfbUHTZCKO4%2FZZOylWKaQ4ljJ1XvwcHd6iMwOx5bS%2Fni5DLYV2GAL80SV4CwqMbHVeg4%2BFXILiy9srjVx1RZRb3o8lVxnYAAAA&config=H4sIAAAAAAAAA0WOQQ7DIAwE%2F%2BJzDhWHHvhDH4GIE1EBRrYjFSH%2BXoLS5mbt7ozc4C0ebIPiWJDPS2pW9wELWguK51AUFlAZ0eai4AIremKnxAJW%2BcA%2Basc76oBQzMOYAUQiwT%2BSQg5bPfWeUmEUuSuX9%2Fhb9uFKtB5n0OYH0%2FmEfjsuLsjrGs4fvucDfqLKAAAA

**Comment by kdy1** [comment]
Can you file a new issue?

**Comment by andreyvital** [comment]
@kdy1 for sure!

**Comment by rohanrajpal** [comment]
Hey, I'd like to follow the new issue but cant find in the Issues tab, @andreyvital could you please share the issue number?

**Comment by rohanrajpal** [comment]
Hey, following up on this, @kdy1 was a new issue created? I can create one if it hasn't been done yet

**Comment by dbousamra** [comment]
This is still an issue for me. Cannot use NestJS and SWC

**Comment by kdy1** [comment]
Please file a new issue with information required to debug it
