### ISSUE TITLE
Incorrect imports in es6 type

### ISSUE THREAD

**Issue by kaname-png** [swc-project/swc#3546]
### Describe the bug

When looking at the imports I noticed that they all have an extra addendum at the end, I don't know what it means.

Also the paths are not working.

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "target": "es2020",
    "paths": {
      "#arguments/*": ["arguments/*"],
      "#lib/*": ["lib/*"],
      "#root/*": ["*"]
    },
    "baseUrl": "./src"
  },

  "module": {
    "type": "es6"
  }
}
```

### Expected behavior

![image](https://user-images.githubusercontent.com/56084970/153714846-deadd8d7-4ec7-48e2-b282-711b96d50bd0.png)

### Actual behavior

> Output file
![image](https://user-images.githubusercontent.com/56084970/153714949-34466fdb-5792-45a6-88f4-3d4a0f09f438.png)

> Original TypeScript file
![image](https://user-images.githubusercontent.com/56084970/153714968-7ec113fa-b712-4e6f-a9a9-e1fec0f5d15a.png)

### Version

0.1.55

**Comment by RiESAEX** [comment]
I think 0.1.55 is the version of @swc/cli
looks like #3447?
try @swc/core 1.1.2.139

**Comment by kaname-png** [comment]
@kdy1 Sorry I put the cli version by mistake.

```json
"@swc/cli": "^0.1.55"
"@swc/core": "^1.2.138"
```
