### ISSUE TITLE
Using `jsc.paths` strips import extensions

### ISSUE THREAD

**Issue by franky47** [swc-project/swc#3576]
### Describe the bug

When using TypeScript paths in `.swcrc`, the extensions of imports (kept for an ESM output) are stripped, but only if there is at least one item in the `jsc.paths` object (not if it's empty).

Reproduction repository:
https://github.com/franky47/swc-paths-extensions

Note: the Playground **does not** show this behaviour: imports always keep their extensions there.

### Config

```json
{
  "jsc": {
    "baseUrl": "./src",
    "paths": {
      "@modules/*": ["./modules/*"]
    },
    "target": "es2020",
    "parser": {
      "syntax": "typescript"
    }
  },
  "module": {
    "type": "es6"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.140&code=H4sIAAAAAAAAA0WMPQvCMBiE9%2FyK25pCSdDRSRBHpw7d1bcaTfKGfKAg%2FndTAzrccHfPndaYCHeigHwlqFsCPTP5ZNhj5oj9eOBzsZQGHEvGOO3wMNYi5WgCTN4I4wLHjBfcAjLemCM7dFvXhrrl9br7s6m4H6h0dd9anNgntqQsX2SbydrJ1YB1v6gXH2e1V1CxAAAA&config=H4sIAAAAAAAAA0XMMQ7CMAyF4bu8EVW06sCQiUswIYYQXAgKJbJdiajK3YnLwGj%2F%2FrziKQFuxdULnTjBYd8LB3TIXh9i6fh635ZE0u%2Fgzi3%2Fx0vtoJ7vpM2RjMM4bJCF2KSUWf2nNS2ZJHDMitrM74NdWNjsAbaPc5wK3OSTUP0C5p3eqJwAAAA%3D

### Expected behavior

Extensions should not be stripped when using the `jsc.paths` configuration, so that an ESModule output has a chance to run in Node.js.

### Actual behavior

Import paths have their `.js` extension stripped, resulting in import resolution failure in Node.js.

### Version

1.2.140

**Comment by kdy1** [comment]
Yeah, you are correct and I think it should be fixed by checking if the original module specifier has an extension.

**Comment by lu-zen** [comment]
Any workaround/eta for this?

**Comment by sgarnotel** [comment]
There is always a bug with the file extension, the compiled file import `.ts` files instead of `.js`, for example:
```
"use strict";
var _moduloJs = require("./modules/modulo.ts");
var _sumJs = require("./sum.ts");
console.log((0, _moduloJs).modulo((0, _sumJs).sum(1, 2), 2));
```

I fork the @franky47 repo as an example [here](https://github.com/Airthium/swc-paths-extensions) (using `commonjs` module type) .

Thank you for your support.

**Comment by franky47** [comment]
You're not supposed to use .ts as file extensions though, as recommended by the TypeScript compiler (error 2691).

I know it's super confusing when writing TypeScript, that the imported file has a .ts extension, but the final running code will be JavaScript, and import a JavaScript file, which will have a .js extension.

**Comment by sgarnotel** [comment]
Yes, of course, in the `src/main.ts` file this is actually an import of a `.js` file, but in the complied code it transforms the extension to `.ts`.

**Comment by franky47** [comment]
Sorry I misunderstood your comment, that is an issue indeed.

**Comment by kdy1** [comment]
@sgarnotel Filed #4585
