### ISSUE TITLE
Optimize CI

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#3612]
This should consider dependency.

The tool should

 - Check if the same action of the base branch (typically `main`) was successful

 - Skip `cargo test` if the base was successful and the current pull request does not modify it or dependency crates

## Investigation

Both of `push` and `pull_request` have 

 - previous commit (main for PR, previous commit for push)
 - the concept of changeset

So we can use the CI result of previous commit and the changeset to see if we should revalidate the current crate.

**Comment by kwonoj** [comment]
In my 5c, eventually we'll need some build systems like bazel. I would recommend bazel if it works seamlessly with cargo-based ecosystem, but in my understanding it's not yet.

Or if turborepo supports rust :p
