### ISSUE TITLE
Pirvate getter setter are wrongly transformed

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#3618]
### Describe the bug

swc would treat getter and setter as normal method, and generate two seperate weakset

### Input code

```typescript
class MyClass {
  get #a() {}
  set #a(x) {}
}
```

### Playground link

https://play.swc.rs/?version=1.2.141&code=H4sIAAAAAAAAA0vOSSwuVvCtdAbT1VwKCumpJQrKiRqaCtW1QF4xhFcB5tYCAAb9JAAuAAAA&config=H4sIAAAAAAAAA0WOuw6DMAxFf6XyzEA7UIm5Kx9hBUOpyEO2qRqh%2FHsTHmKzrs899gofMdCuEJCFuEwSneIPWiBjUQxPQaHKWI6UF0oVKKOTwbMt%2BEwjmvgi4xnV8w5V0J9BR4o9KkI74CxbHXkkLQfkUd%2BbLJ%2B9FzqACuzkpiEWt%2FE2MIlcK3TjfJIpu6zvlxKsoDHQ5mwgXY6jN0l3gPt35L5bZ%2Fsk68G82Vu6PWtI6Q%2BymPZHFAEAAA%3D%3D

### Expected behavior

Only generate one WeakMap

### Version

1.2.141

**Comment by williamtetlow** [comment]
I'm going to take a look at this

**Comment by Austaras** [comment]
Oh, I've already started working on this issue.

**Comment by williamtetlow** [comment]
no probs! I messaged first as wasn't sure if you had 😄
