### ISSUE TITLE
GitHub Action for SWC - Write projects in TS and bundle them automatically via a github action

### ISSUE THREAD

**Issue by Vadorequest** [swc-project/swc#3625]
### Describe the feature

_This might fall outside what you want to provide._

As I write good-old JS scripts for browser (using `var` and such), I wonder if I couldn't use SWC to “bring together” a bunch of JS files into one (bundle them). While I'm at it, I would probably prefer writing TS. Also, for my own sake, I'd like to split my big JS file into multiple files, to make it easier to maintain the various scripts of the project.

Eventually, I want a single ES3/ES5 file, which would be the compiled result of all the other files within the folder. And I would require that file from my no-code website.

Is this something that could be achieved with SWC?

---

> Example: I would have one JS file for each of my "polyfills", and the bundled distribuable would contain them all in one file. The build step would happen on GitHub and would be performed by a GitHub Action, so that my source files are clean and the process would happen automatically when I push onto the "main" branch.

**Comment by kwonoj** [comment]
Not sure if I understood this correctly - is this https://swc.rs/docs/usage/bundling?

**Comment by Vadorequest** [comment]
Thanks, I had missed that option. I'm digging into it.

Is it possible to minify the output? I tried various ways but couldn't make it work.

**Comment by kwonoj** [comment]
https://swc.rs/docs/configuration/minification

Since this is not a explicit bug report, let me going to close issue. Please refer docs for further details.
