### ISSUE TITLE
[Lexer] Improve codec of HTML escape characters

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#364]
Code Line: https://github.com/swc-project/swc/blob/master/ecmascript/parser/src/lexer/jsx.rs#L60

@kdy1  

Full HTML escape characters support: https://github.com/LuoZijun/es/commit/b67338f43ae445c68ede3b183cb1900c31816c94

Ref: [HTML Character entity references](https://dev.w3.org/html5/html-author/charref)

benchmark:

```
test lexer::htmlentity::bench_escape_html_with_bytes   ... bench:     226,428 ns/iter (+/- 67,908) = 503 MB/s
test lexer::htmlentity::bench_escape_html_with_chars   ... bench:     258,850 ns/iter (+/- 42,165) = 440 MB/s
test lexer::htmlentity::bench_escape_html_with_str     ... bench:     231,982 ns/iter (+/- 87,126) = 491 MB/s
test lexer::htmlentity::bench_unescape_html_with_bytes ... bench:     284,332 ns/iter (+/- 39,198) = 409 MB/s
test lexer::htmlentity::bench_unescape_html_with_chars ... bench:     328,042 ns/iter (+/- 22,807) = 355 MB/s
test lexer::htmlentity::bench_unescape_html_with_str   ... bench:     287,491 ns/iter (+/- 42,134) = 405 MB/s
```

**Comment by LuoZijun** [comment]
@kdy1 

Compared to [htmlescape](https://docs.rs/htmlescape) this library, my implementation is a complete implementation, and also has better performance, if you are interested, it will also improve the performance of SWC Lexer and parse more complex escape sequences.

**Comment by marisasrida01** [comment]
good

**Comment by kdy1** [comment]
For samsung open source project contributors:

This can be done by changing https://github.com/swc-project/swc/blob/53b09aa35652a84f731a765cbb23ee272c157376/ecmascript/parser/src/lexer/jsx.rs#L61-L112 to use faster library.

**Comment by jungwookim** [comment]
@kdy1 why don't you do PR with your changes?

**Comment by kdy1** [comment]
@jungwookim I didn't do it because there was many tasks with higher priority, but I decided to do this now to remove dependency on regex crate.

**Comment by jungwookim** [comment]
@kdy1 Ahhh I see. I came across `swc` last week when I was looking for fast typescript compiler and also came across sos-masters this week. Your project looks interesting and hope I would contribute it later. Cheers.
