### ISSUE TITLE
[TypeScript] const enum should be hoisted

### ISSUE THREAD

**Issue by magic-akari** [swc-project/swc#3648]
### Describe the bug

[TS Playground](https://www.typescriptlang.org/play?module=1#code/MYewdgziA2CmB00QHMAUAxEJ4EECUA3AFBGiQAuABLGAK4C2lmIlA3kZZ5TpQLyUBGIgF8gA)
```javascript
"use strict";
console.log(1 /* A */);
```

### Input code

```typescript
console.log(Foo.A);

const enum Foo {
    A = 1
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  },
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.143&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP13DLz9dz1LTm4koGCpYopOaV5ioAxRSquRSAwFHBVsGQqxYA10T3ajEAAAA%3D&config=H4sIAAAAAAAAAy2LQQ6AIAwE%2F9KzB8PBA3%2FwEQ1Wg0ElbUk0hL9bjLfdmd0KuwTwFTKyEPckz6l4gwd9MkngmBUGUDG0YhJqVpA3UpuQuNE5MHRcS0nU%2F%2F32qanzKPNvlAu1F9feoEVwAAAA

### Expected behavior

see TypeScript output

### Version

1.2.143

**Comment by magic-akari** [comment]
another case:

[TypeScript REPL](https://www.typescriptlang.org/play?target=99&jsx=0#code/MYewdgziA2CmB00QHMAUAxEJ4CECGATvAIICUAUOWHgLawQAOewsABJiKwN7mt+uwAHgxAEALq1CQJsMAFcarfAW69+64qwC8rAIxq+AX0rqpUOIhSoARMWsVj5MzARI0HXIVwUqtekxZ2LFV1IRFxSXAIGXlFZRD1fhxtVgAmA1ZHUyiXSzRrHHtyYyA)

```typescript
console.log(Foo.Bar.A)

namespace Foo {
    export const enum Bar {
        A = 1
    }

    console.log("A")
}

console.log(Foo.Bar.B)

namespace Foo {
    export const enum Bar {
        B = 2
    }

    console.log("B")
}
```

expected output
```javascript
console.log(1 /* A */);
var Foo;
(function (Foo) {
    console.log("A");
})(Foo || (Foo = {}));
console.log(2 /* B */);
(function (Foo) {
    console.log("B");
})(Foo || (Foo = {}));
```

**Comment by magic-akari** [comment]
I think it's partially fixed. When the enum is defined and used in the same file, the const enum will be inlined directly, and the hoist issue will disappear.

**Comment by kdy1** [comment]
Do you think we should close this issue?

**Comment by magic-akari** [comment]
[playground](https://play.swc.rs/?version=1.2.197&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP13DLz9dz1LTmSkYSc0os0oOIc4HFSxRS80pzFYBCCtVcCkDgqGCrYMhVy8WVl5ibWlyQmJyqANQDlUytKMgvKlHAqhGhGcQCGgCikK1WclTS5KoFACf9MSWhAAAA&config=H4sIAAAAAAAAAy2LQQ6AIAwE%2F9KzB8PBA3%2FwEQ1Wg0ElbUk0hL9bjLfdmd0KuwTwFTKyEPckz6l4gwd9MkngmBUGUDG0YhJqVpA3UpuQuNE5MHRcS0nU%2F%2F32qanzKPNvlAu1F9feoEVwAAAA)

```ts
console.log(Foo.A);
console.log(Bar.Foo.A)

const enum Foo {
    A = 1
}

namespace Bar {
    export const enum Foo {
        A = 1
    }

    console.log("A")
}
```

```javascript 
console.log(1);
console.log(Bar.Foo.A);
var Foo;
(function(Foo) {
    Foo[Foo["A"] = 1] = "A";
})(Foo || (Foo = {}));
var Bar1;
(function(Bar) {
    let Foo;
    (function(Foo) {
        Foo[Foo["A"] = 1] = "A";
    })(Foo = Bar.Foo || (Bar.Foo = {}));
    console.log("A");
})(Bar1 || (Bar1 = {}));
```

**Comment by C0kkie** [comment]
Is there any progress of that issue?

**Comment by magic-akari** [comment]
Currently, there is no progress. Furthermore, the new TypeScript 5.0 has made enums even more complex, as opaque computed enum members can now be used.

![Fp330ZqaUAEHk_Y](https://user-images.githubusercontent.com/7829098/228231189-bba2272b-57ed-4179-861c-389b8f0f0400.jpeg)

Reference: https://github.com/microsoft/TypeScript/pull/50528

We cannot completely eliminate const enums like TS, but we can make every effort to replace their references.

**Comment by magic-akari** [comment]
This issue should be closed. 
I will submit a new issue about the complicated enum usage.

**Comment by C0kkie** [comment]
is that something in the near or far future?
