### ISSUE TITLE
Double export when building?

### ISSUE THREAD

**Issue by VincentThomas06** [swc-project/swc#3650]
### Describe the bug

When i try to compile i get an error where it says that some file has exported cluster twice. here are the exports:
```
error: Duplicate export

    |
413 |     export { default as default } from 'cluster';
    |                         ^^^^^^^
    |
note: default was exported at here

    |
409 |     export default cluster;
    |     ^^^^^^^^^^^^^^^^^^^^^^^


error: Return statement is not allowed here

   |
23 |     return;
   |     ^^^^^^^

```

This is the command i use to try and compile: 
`npx swc ../data-access -d ..\..\..\dist\libs\movie\data-access/src --source-maps`

### Input code

```typescript
I dont know what this means but i can happily update this post if anyone can explain
```

### Config

```json
{
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "decoratorMetadata": true,
      "legacyDecorator": true
    },
    "keepClassNames": true,
    "externalHelpers": true,
    "loose": true
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "noInterop": true
  }
}
```
```


### Playground link

https://github.com/VincentThomas06/Projects/tree/dev

### Expected behavior

command to reproduce in the github repo: `cd libs/movie/data-access && npx swc ../data-access -d ..\..\..\dist\libs\movie\data-access/src --source-maps`

I would like it to compile all my code but instead i get this error
```
error: Duplicate export
   
    |
413 |     export { default as default } from 'cluster';
    |                         ^^^^^^^
    |
note: default was exported at here
   
    |
409 |     export default cluster;
    |     ^^^^^^^^^^^^^^^^^^^^^^^

error: Return statement is not allowed here
  
   |
23 |     return;
   |     ^^^^^^^

Caused by:
    0: failed to process js file
    1: error was recoverable, but proceeding would result in wrong codegen
    2: Syntax Error
Successfully compiled: 2003 files with swc (987.74ms)
Failed to compile 2 files with swc.
Error: Failed to compile
    at initialCompilation (C:\Users\vincent\coding\projects-new\node_modules\@swc\cli\lib\swc\dir.js:162:19)
    at async dir (C:\Users\vincent\coding\projects-new\node_modules\@swc\cli\lib\swc\dir.js:222:5)

```

### Actual behavior

I get this error

### Version

    "@swc/cli": "~0.1.52",     "@swc/core": "1.2.118",     "@swc/helpers": "~0.2.14",     "@swc/jest": "0.2.15",

### Additional context

_No response_

**Comment by kdy1** [comment]
In your code, `default` is exported multiple time.

**Comment by VincentThomas06** [comment]
> In your code, `default` is exported multiple times.

Shouldve sayd this earlier. Its not my code. U have not touched the "cluster" library.

**Comment by kdy1** [comment]
Why do you invoke swc for `cluster` library?
I don't know what it is, but if it's not your own code, you are not expected to run swc on it.

**Comment by VincentThomas06** [comment]
> Why do you invoke swc for `cluster` library? I don't know what it is, but if it's not your own code, you are not expected to run swc on it.

This error message has nothing to do with my code. I thought it might be in the internal code inside swc but i don't know. Anyhow i have switched to tsc.

**Comment by Furizaa** [comment]
In case someone googles up this issue: I've had the same one. Problematic package is `@types/node` and upgrading that to a newer version fixed that it me.
