### ISSUE TITLE
Using a type when destructuring function arguments leads to undefined variable

### ISSUE THREAD

**Issue by guidokessels** [swc-project/swc#3660]
### Describe the bug

When destructuring function arguments, if a `<Type>` is used in the default value, it will rename the variable on the line immediately below.
However, the variable will not be renamed in the function body. This creates a `[variable] is not defined` error.

### Input code

```typescript
// Adding a type to Set breaks the
// variable on the next line
function Test1({
  var1 = new Set<number>(),
  var2 = "123", // <- this variable is renamed to `var21`
  var3 = "456"
}) {
  console.log(var1, var2, var3); // <- here `var2` is used
}

// Placing the Set on the last line works
function Test2({
  var2 = "123",
  var3 = "456",
  var1 = new Set<number>()
}) {
  console.log(var1, var2, var3);
}

// Removing the type from Set also works
function Test3({
  var1 = new Set(),
  var2 = "123",
  var3 = "456" 
}){
  console.log(var1, var2, var3);
}
```

### Config

```json
{
  "jsc": {
    "transform": {
      "hidden": {
        "jest": true
      }
    },
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.136&code=H4sIAAAAAAAAA42R0U6EMBBF30n4hwlPkKAEUF9cTfwDo34ABWZ3my0d05ZdjfHf7XRREkLMvjRNp3PvuTNFAU99L%2FUOBLjPdwRH8IoOWoPiYMHtMY6KAo7CSNEqBNL8Bho%2FHCipfXU76s5J%2F%2F6G1pXpVxwBfy%2Fhwf86sdhGj0OL5jHN8qlY%2BWJSVnWSgxffXHlNaWcTfzeoxYA94zTcUDZTa82tN7d3SRx9ZxDcOtKWFF4r2qXsnAeLcNbZ%2FeSwR4NnqYb1R4u9V4ijEO9ZiY5nwNE4%2FZRSCXtOCScyB7vIWv1lneMsIfP%2FpnFpgpnzBQc6%2FoKGdW0NDQFZKEurmPXaStZWsWQH5rsU7weCHvoFSAIAAA%3D%3D&config=H4sIAAAAAAAAAzWLMQrAIBAE%2F3K1RbD0NxIviUKM3G1AEf8eLdLtMLOdku7kOkF81uORe8EVQ%2BC8VmIFOcjLYxiCl5MnE6vdrCVDxYuyrFJbhq%2FToRXWXWLB9ND638cHz112XWwAAAA%3D

### Expected behavior

The variable is renamed in the destructured function argument _and_ in the function body, or not renamed at all. In the case of the examples above renaming the variable shouldn't even be needed.

### Actual behavior

`var2` is renamed to `var21` in the function arguments but not in the function body, leading to the error.

### Version

`>1.2.35`

### Additional context

v1.2.135 works fine. v1.2.136 and up have this error.

**Comment by larstadema** [comment]
Just providing an additional example with this issue as we also encountered this.

https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA2VTTW%2FaQBC9I%2Fk%2FvFsMQia9IkIOKFIjtaIi9BTlsKzHeNv1rrUfIFTx3zu2sWUSn8Y7%2B97MezOrqtq6gBmEx46EDCicrfDgmvghmSSTcKkJv5ytPZ7wL5mAv5PQkZbwwSlz7I6UqWPYUfG87HgyjreHPyTD6vv%2B54%2FXJv2iqSIT1h2iUmZjowmMMLE6kEsm12QirfEBb7aijeXeDN%2Fnuum48LyLFwvsS%2BWhvI8Ea%2FQFVsroPM4lGeRUKMPtQcBRgUZGhgG5o8qemmwoCas9J9c4kiGnJM5Ka0h2IFBTUOWQNucKMbCGe7XcWqe2u84nX9Wm0%2Fm9YAY9stZl5%2BoUT%2Bve1078u%2FLbmswcnsJrG34MdaKnt8CV0kJoT9MxrBQm17TRSv5tHBvz3kRvowMTSOEJJTm6Sw7F0tbkTJM5hhLroe1bsWuzFC1mNrsRzPDb914OIpWBMBecxYVDr9jAJi37oQ5QKbglf4%2FNSWrhRFDWoGaTGrIerTTlt1kgWByIx2tExYf81zN8ywb%2BbkcYH53pi%2FFK8CVVEcg561ozmKnNjhR4RNOuEeUD3%2BK2AAXS4eIaj9Ox1Z%2BMGib3UhT8HtIvo%2Bm3KePtZTHhOSusjD7tHZ%2Fj%2FWPaszlqlaxydcKCn9L1Pz%2BebTbDAwAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1Fm2hG9%2BhhzCuEhz8Q%2BNATfDdK4eE7Ib5PGmnFY7MTsUKWIZCS9X%2ByFBtheHEl0oTVahVZeOu2srCVRuM1%2BP51jTkDCYz2wCeKPrk5zZYLsciDNyRTUu4ml1ZMX%2B3YezHOWXqJOa0gvoNOscen7N9PPIHEdWl27wAAAA%3D
