### ISSUE TITLE
Parser error on TypeScript function with return in a ternary falsy case

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [swc-project/swc#3672]
### Describe the bug

```plaintext
error: Parenthesized expression cannot be empty
 --> input.ts:6:25
  |
2 |   fix: fixable ? null : (): RuleFix => {},
  |                         ^^
```

Alternately, if there are parameters:

```plaintext
error: Expected ',', got ':'
 --> input.ts:2:28
  |
2 |   fix: fixable ? null : (a): RuleFix => {},
  |       
```

### Input code

```typescript
report({
  fix: fixable ? null : (): RuleFix => {},
});
```

### Config

```json
{}
```

### Playground link

https://play.swc.rs/?version=1.2.143&code=H4sIAAAAAAAAAytKLcgvKtGo5uVSUEjLrLACEYlJOakK9gp5pTk5ClYKGppWCkGlOalumRUKtnYK1bU6vFy1mta8XLxcAP60gnc9AAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

No parser errors.

### Actual behavior

error: Parenthesized expression cannot be empty

### Version

1.2.143

### Additional context

The code is valid TypeScript: 

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3nADkmGAXPFCgJ4DcAUKJLAsulgGYCWAHlAEYQjFdIkvUtQxkcCAEoBXXgDEO8ALzwAbklbBqVXPgwAKAN5V48Nu2LnuveAH54KWRHjF9ASmIz5ipQD54hgC+ADRUgW7UQA

**Comment by williamtetlow** [comment]
I can take a look at this

**Comment by williamtetlow** [comment]
interestingly this works

```js
{ 
    fix: fixable ? null : (): RuleFix => {}
}
```

it's the comma at the end of the expression causing issues 😄
