### ISSUE TITLE
Trailing comma following rest element should be an error

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#3676]
### Describe the bug

swc would throw error on
```js
const [...rest, ] = a
```
but not in for in/of

### Input code

```typescript
for ([...rest, ] of a) {}

for ({...rest, } of b) {}
```

### Playground link

https://play.swc.rs/?version=1.2.143&code=H4sIAAAAAAAAA0vLL1LQiNbT0ytKLS7RUYhVyE9TSNRUqK7l4koDSVXDpWpBUkkgKQAoNV3qNAAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSw6DMAxEr1J5zaKtEAvW3XIIKxhKlZ9sUxWh3L0hgNhZkzcvs8JHDLQrRGQh3i5ZvOIPWtAlkhieokIFKjlSninlm9HLENhtuKURzfIiExg18A5V0J9BR4o9KkI7oJVSRx5J8wckz%2FujyXIbgtABVOAmPw3L5jbBRSaR6wn9aE8yZZcL%2FbwFa1lbnA2ky3H0JukOcF9H%2Fls6ZUnWg3lzcHSra0jpD2XbA54UAQAA

### Expected behavior

Should throw error `Unexpected trailing comma after rest element`

### Actual behavior

Compiles normally

### Version

1.2.143

**Comment by magic-akari** [comment]
I am working at this issue.

**Comment by Austaras** [comment]
@kdy1 this is not fixed
```js
for ([...rest, ] of a) {}

for ({...rest, } of b) {}
```
should be error

**Comment by kdy1** [comment]
Thanks!
