### ISSUE TITLE
Jest integration

### ISSUE THREAD

**Issue by DanielRamosAcosta** [swc-project/swc#368]
I've writed a [`swc-jest`](https://github.com/DanielRamosAcosta/swc-jest) plugin. Everithing works fine excepting some strange issue with the source maps. When I `console.log` or `throw` an error, jest gives me the wrong line numbers... It would be great If I could get some help on this.

Do you mind If I publish it at npm? Maybe we could move it into the `swc-project` organization?

Thannks you.

**Comment by kdy1** [comment]
I'd love to see it published. I don't mind if you publish on npm.

I'll fix source map issue soon.

**Comment by DanielRamosAcosta** [comment]
Ok @kdy1, I've published [`swc-jest`](https://www.npmjs.com/package/swc-jest) :)
