### ISSUE TITLE
Error: Error(Msg("data did not match any variant of untagged enum InputSourceMap"), State { next_error: None, backtrace: None })

### ISSUE THREAD

**Issue by Pkoiralap** [swc-project/swc#371]
This is the file where I get error, on console logging the source and options on `transform` function in @swc/core/lib/index.js.

    import '@babel/polyfill';
    import 'unorm'; // polyfill for normalize
    import 'array-flat-polyfill'; // polyfill for .flat()
    
    import {render} from 'react-dom';
    import React from 'react';
    import {Router, browserHistory} from 'react-router';
    import {ToastContainer} from 'react-toastify';
    import {syncHistoryWithStore} from 'react-router-redux';
    import {Provider} from 'react-redux';
    import CreateStore from '../store';
    import routes from '../routes/routes';
    import {success, errorMsg, warning, info} from '../components/toast';
    
    Object.assign = null;
    Object.assign = require('object-assign');
    
    let prevStoredState = localStorage.getItem('reduxState');
    if (prevStoredState === null) {
      prevStoredState = window.__INITIAL_STATE__;
    } else {
      prevStoredState = JSON.parse(prevStoredState);
      prevStoredState = {
        ...prevStoredState,
        assets: {
          ...prevStoredState.assets,
          uploadList: [],
        },
      };
    }
    const store = CreateStore(browserHistory, prevStoredState);
    delete window.__INITIAL_STATE__;
    
    require('../../../../node_modules/react-toastify/dist/ReactToastify.min.css');
    require('../../../static/css/foundation.css');
    require('../../../static/css/vendor/dropzone.min.css');
    require('../../../static/css/vendor/msc-style.css');
    require('../../../static/css/vendor/react-select.css');
    require('../../../static/css/vendor/react-datepicker.css');
    
    require('../../../static/css/fonts.css');
    require('../../../static/css/styles.css');
    require('../../../static/css/app.css');
    require('../../../static/css/calendar.css');
    require('../../../static/css/plugin.css');
    
    document.addEventListener('mousewheel', event => {
      if (document.activeElement.type === 'number') {
        document.activeElement.blur();
      }
    });
    const history = syncHistoryWithStore(browserHistory, store);
    window.success = success;
    window.errorMsg = errorMsg;
    window.warning = warning;
    window.info = info;
    render(
      <Provider store={store}>
        <React.Fragment>
          <Router history={history} routes={routes} />
        </React.Fragment>
      </Provider>,
      document.getElementById('react-root')
    );

The options show

    {
      filename: 'my_path/index.js',
      inputSourceMap: {
        version: 3,
        sources: [
          'my_path/index.js'
        ],
        names: [
          'Object',
          'assign',
          'require',
          'prevStoredState',
          'localStorage',
          'getItem',
          'window',
          '__INITIAL_STATE__',
          'JSON',
          'parse',
          'entity',
          'offset',
          'assets',
          'uploadList',
          'store',
          'browserHistory',
          'document',
          'addEventListener',
          'event',
          'activeElement',
          'type',
          'blur',
          'history',
          'success',
          'errorMsg',
          'warning',
          'info',
          'routes',
          'getElementById'
        ],
        mappings: ';;;;;;AAAA;;AACA;;AACA;;AAEA;;AACA;;AACA;;AACA;;AACA;;AACA;;AACA;;AACA;;AACA;;AAXgB;AACc;AAY9BA,MAAM,CAACC,MAAP,GAAgB,IAAhB;AACAD,MAAM,CAACC,MAAP,GAAgBC,OAAO,CAAC,eAAD,CAAvB;AAEA,IAAIC,eAAe,GAAGC,YAAY,CAACC,OAAb,CAAqB,YAArB,CAAtB;;AACA,IAAIF,eAAe,KAAK,IAAxB,EAA8B;AAC5BA,EAAAA,eAAe,GAAGG,MAAM,CAACC,iBAAzB;AACD,CAFD,MAEO;AACLJ,EAAAA,eAAe,GAAGK,IAAI,CAACC,KAAL,CAAWN,eAAX,CAAlB;AACAA,EAAAA,eAAe,mCACVA,eADU;AAEbO,IAAAA,MAAM,kCACDP,eAAe,CAACO,MADf;AAEJC,MAAAA,OAAO,kCACFR,eAAe,CAACO,MAAhB,CAAuBC,OADrB;AAELC,QAAAA,MAAM,EAAE;AAFH;AAFH,MAFO;AASbC,IAAAA,MAAM,kCACDV,eAAe,CAACU,MADf;AAEJC,MAAAA,UAAU,EAAE;AAFR;AATO,IAAf;AAcD;;AACD,IAAMC,KAAK,GAAG,oBAAYC,2BAAZ,EAA4Bb,eAA5B,CAAd;AACA,OAAOG,MAAM,CAACC,iBAAd;;AAEAL,OAAO,CAAC,oEAAD,CAAP;;AACAA,OAAO,CAAC,oCAAD,CAAP;;AACAA,OAAO,CAAC,6CAAD,CAAP;;AACAA,OAAO,CAAC,0CAAD,CAAP;;AACAA,OAAO,CAAC,6CAAD,CAAP;;AACAA,OAAO,CAAC,iDAAD,CAAP;;AAEAA,OAAO,CAAC,+BAAD,CAAP;;AACAA,OAAO,CAAC,gCAAD,CAAP;;AACAA,OAAO,CAAC,6BAAD,CAAP;;AACAA,OAAO,CAAC,iCAAD,CAAP;;AACAA,OAAO,CAAC,oCAAD,CAAP;;AACAA,OAAO,CAAC,oCAAD,CAAP;;AACAA,OAAO,CAAC,kCAAD,CAAP;;AACAA,OAAO,CAAC,gCAAD,CAAP;;AACAA,OAAO,CAAC,uEAAD,CAAP;;AAEAe,QAAQ,CAACC,gBAAT,CAA0B,YAA1B,EAAwC,UAAAC,KAAK,EAAI;AAC/C,MAAIF,QAAQ,CAACG,aAAT,CAAuBC,IAAvB,KAAgC,QAApC,EAA8C;AAC5CJ,IAAAA,QAAQ,CAACG,aAAT,CAAuBE,IAAvB;AACD;AACF,CAJD;AAKA,IAAMC,OAAO,GAAG,4CAAqBP,2BAArB,EAAqCD,KAArC,CAAhB,C,CACA;;AACAT,MAAM,CAACkB,OAAP,GAAiBA,cAAjB;AACAlB,MAAM,CAACmB,QAAP,GAAkBA,eAAlB;AACAnB,MAAM,CAACoB,OAAP,GAAiBA,cAAjB;AACApB,MAAM,CAACqB,IAAP,GAAcA,WAAd;AACA,sBACE,6BAAC,oBAAD;AAAU,EAAA,KAAK,EAAEZ;AAAjB,GACE,6BAAC,cAAD,CAAO,QAAP,QACE,6BAAC,6BAAD,OADF,EAEE,6BAAC,mBAAD;AAAQ,EAAA,OAAO,EAAEQ,OAAjB;AAA0B,EAAA,MAAM,EAAEK;AAAlC,EAFF,CADF,CADF,EAOEX,QAAQ,CAACY,cAAT,CAAwB,YAAxB,CAPF,E,CAUA;AACA;AACA;AACA',
        sourcesContent: [
          'import \'@babel/polyfill\';\nimport \'unorm\'; // polyfill for normalize\nimport \'array-flat-polyfill\'; // polyfill for .flat()\n\nimport {render} from \'react-dom\';\nimport React from \'react\';\nimport {Router, browserHistory} from \'react-router\';\nimport {ToastContainer} from \'react-toastify\';\nimport {syncHistoryWithStore} from \'react-router-redux\';\nimport {Provider} from \'react-redux\';\nimport CreateStore from \'../store\';\nimport routes from \'../routes/routes\';\nimport {success, errorMsg, warning, info} from \'../components/toast\';\n\nObject.assign = null;\nObject.assign = require(\'object-assign\');\n\nlet prevStoredState = localStorage.getItem(\'reduxState\');\nif (prevStoredState === null) {\n  prevStoredState = window.__INITIAL_STATE__;\n} else {\n  prevStoredState = JSON.parse(prevStoredState);\n  prevStoredState = {\n    ...prevStoredState,\n    entity: {\n      ...prevStoredState.entity,\n      Devices: {\n        ...prevStoredState.entity.Devices,\n        offset: 0,\n      },\n    },\n    assets: {\n      ...prevStoredState.assets,\n      uploadList: [],\n    },\n  };\n}\nconst store = CreateStore(browserHistory, prevStoredState);\ndelete window.__INITIAL_STATE__;\n\nrequire(\'../../../../node_modules/react-toastify/dist/ReactToastify.min.css\');\nrequire(\'../../../static/css/foundation.css\');\nrequire(\'../../../static/css/vendor/dropzone.min.css\');\nrequire(\'../../../static/css/vendor/msc-style.css\');\nrequire(\'../../../static/css/vendor/react-select.css\');\nrequire(\'../../../static/css/vendor/react-datepicker.css\');\n\nrequire(\'../../../static/css/fonts.css\');\nrequire(\'../../../static/css/styles.css\');\nrequire(\'../../../static/css/app.css\');\nrequire(\'../../../static/scss/index.scss\');\n\ndocument.addEventListener(\'mousewheel\', event => {\n  if (document.activeElement.type === \'number\') {\n    document.activeElement.blur();\n  }\n});\nconst history = syncHistoryWithStore(browserHistory, store);\n// history.listen(location => );\nwindow.success = success;\nwindow.errorMsg = errorMsg;\nwindow.warning = warning;\nwindow.info = info;\nrender(\n  <Provider store={store}>\n    <React.Fragment>\n      <ToastContainer />\n      <Router history={history} routes={routes} />\n    </React.Fragment>\n  </Provider>,\n  document.getElementById(\'react-root\')\n);\n\n// Router.run(routes, Router.HistoryLocation, function (Handler) {\n// React.render(<Handler/>, document.body);\n// console.log(Handler)\n// });\n'
        ]
      },
      sourceMaps: true,
      sourceFileName: '/index.js'
    }

finally, the error says

    ERROR in ./src/index.js
    Module build failed (from ./node_modules/swc-loader/src/index.js):
    Error: Error(Msg("data did not match any variant of untagged enum InputSourceMap"), State { next_error: None, backtrace: None })
        at Promise (/path/node_modules/@swc/core/lib/index.js:65:19)
        at new Promise (<anonymous>)
        at Compiler.transform (/path/node_modules/@swc/core/lib/index.js:64:16)
        at Object.transform (/path/node_modules/@swc/core/lib/index.js:115:35)
        at Object.<anonymous> (/path/node_modules/swc-loader/src/index.js:59:17)
     @ multi ./src/index webpack-hot-middleware/client app[0]

NOTE: Some of the paths and things in the logs are tempered with but that should not be an issue ?

I may be missing some configurations details, but I could not find them in the docs. So updating the docs might be helpful as well.

I love this project and initiation, I am trying to migrate from babel to swc. So if in future there is a way to convert the babelrc to swcrc that would be awesome as well.

**Comment by kdy1** [comment]
@Pkoiralap Can you share your webpack configuration related to swc?
I think this is bug of swc-loader.

**Comment by kdy1** [comment]
I fixed this and published `swc-loader@0.1.6`
