### ISSUE TITLE
Multi-line comment being stripped from generated code

### ISSUE THREAD

**Issue by smcenlly** [swc-project/swc#3715]
### Describe the bug

We create some popular developer tools ([Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode), [Wallaby.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode)).

Our tools rely on code comments being correctly in code emitted by SWC.

It appears that SWC sometimes (not always) removes multi-line comment from generated code.

### Input code

```typescript
a() /* IMPORTANT_DO_NOT_REMOVE */ ;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    }
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.144&code=H4sIAAAAAAAAA0vU0FTQ11Lw9A3wDwpx9AuJd%2FGP9%2FMPiQ9y9fUPc1XQ0lewBgAeBNe1IwAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

Generated code should be:

```javascript
a() /* IMPORTANT_DO_NOT_REMOVE */ ;
```

### Actual behavior

Generated code is:

```javascript
a();

```

### Version

@swc/core@1.2.144

**Comment by kwonoj** [comment]
👋 I'm wallaby / quokka daily user.

We really don't have good defined behavior around comment. https://github.com/swc-project/swc/issues/2964 is one of the examples. There is internal consideration to revisit whole comment, but also it doesn't aim to fix specific issues around comment.

How much is this a blocker for you? Is there any workaround you can apply?

**Comment by smcenlly** [comment]
> 👋 I'm wallaby / quokka daily user.

That's awesome :)

---

One of Quokka/Wallaby key features is [Live Comments](https://quokkajs.com/docs/#comments), which gives users a mechanism to always log a value when Wallaby/Quokka runs their code.

We've been recommending people use `swc` over `babel` or `TypeScript` ([see our blog post](https://wallabyjs.com/blog/optimizing-typescript.html)) because of the massive performance benefits. And we're also using `swc` in our own projects.

There's no real work around for us on this issue. It seems to work most of the time, but not always.

I wouldn't say it's a blocker for us per se but it'll definitely affect our customers and perhaps make them choose `babel` instead of `swc` when running their tests if they find it particularly painful.
