### ISSUE TITLE
Erroneous error on interface multiple inheritance

### ISSUE THREAD

**Issue by clhuang** [swc-project/swc#3717]
### Describe the bug

SWC 1.2.144 emits an error on the following code, which does not error in the typescript playground or in SWC 1.2.143.

### Input code

```typescript
interface IThingy extends Record<'a', string>, Record<'c', number> {}

const x: IThingy = {a:"HI", b: 5};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.144&code=H4sIAAAAAAAAA8vMK0ktSktMTlXwDMnIzEuvVEitKEnNSylWCEpNzi9KsVFPVNdRKC4pAsrZ6cAFk4GCeaW5SalFdgrVtVxcyfl5xSUKFVZwU2wVqhOtlDw8lXQUkqwUTGutuQA6mJGjagAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

SWC 1.2.143 emits the correct code:
```js
var x = {
    a: "HI",
    b: 5
};
```

### Actual behavior

SWC 1.2.144 emits the error:
```
error: An interface can only extend an identifier/qualified-name with optional type arguments.
 --> input.ts:1:27
  |
1 | interface IThingy extends Record<'a', string>, Record<'c', number> {}
  |                           ^^^^^^^^^^^^^^^^^^^



Caused by:
    0: failed to process js file
    1: failed to process js file
    2: error was recoverable, but proceeding would result in wrong codegen
    3: Syntax Error
```

### Version

1.2.144

**Comment by kdy1** [comment]
Closing as it's already fixed.
https://github.com/swc-project/swc/issues/3694
