### ISSUE TITLE
Private name generated weak map/set should be marked as pure

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#3718]
### Describe the bug

So compressor could remove them

### Input code

```typescript
class A {
    #b = 123
}
```

### Playground link

https://play.swc.rs/?version=1.2.144&code=H4sIAAAAAAAAA0vOSSwuVnBUqOZSAALlJAVbBUMjY65aAMgGJ8gYAAAA&config=H4sIAAAAAAAAA21TQZLjIAz8C%2BccdvYwhzxgq%2BawtU%2BgCAiHrAGXJDJxpfL3FbaD7WRvqOkWUkvc1YWsOt7VYJAA64nGxOamjgpsNGQxDKwOQhPIm57goAYMV8Pwlf6cLmBZHRkLPA6KDXbAVUk%2Ff3x8iqrPmaDpYkjBj%2FUNm%2BOAQFTPIioRElPjGcT8TXPagzrl3INJb7E2pENi6ABXqc19bwYCfTXYFPU1g4Fy2kGFwekB87CVJxc45CRhAx0Yp212ayMuoPQdrrAhSR4hJZLi9qCDU%2Bm66u38NFxNX8S%2BFt8mK%2BTRpjvnQKx9SfQCLdXOwhmaG11YwWsELpienEsOaefFXwCpszdEycRN%2FRPuZRZ7pv8PKyQvg%2BSxoTLltaoEnTSnQ%2FCtw1o1IAdoJARXLNQO7Zp8AXcNUXCgwXuxu4npO7A9b6ricYDs273YZvw6hDnUz6Xao3UP3sBfUhZv57Hg0fD5FaMxnnL%2FliICn7N7g8UJzq8gygrfhle0JAfiM7jNRaEaLr8tmtS1XXtUILtSgftkyPQNP9Vj%2FXbPHaHfC3FK9A8VB8qvAgQAAA%3D%3D

### Expected behavior

should output empty string

### Actual behavior

output `new WeakMap()`

### Version

1.2.144

**Comment by Austaras** [comment]
Is it currently possible to add comments for elements with `DUMMY_SP`?

**Comment by kdy1** [comment]
No, we can't. I'm not sure how can it be implemented without a huge performance drop.
I considered using `SyntaxContext` for comments, but it means that we have to check for `SyntaxContext` while generating codes.

**Comment by Austaras** [comment]
Ok I got a idea, which may sounds dirty but could work:
As BytePos is a u32, reserve 2**32 - 2**16 for dummy sp, so when generate code, comments can be emitted, and when generate sourcemap, ignore everything larger than 2**32 - 2**16

**Comment by kdy1** [comment]
Sounds reasonable.
Hmm...
Wow, I think it's a quite clever solution. Will you do it? I can do it if you want.

**Comment by Austaras** [comment]
Sure, I will do it tomorrow. Could you point to where swc generates source map?

**Comment by kdy1** [comment]
The actual code lives at https://github.com/swc-project/swc/blob/1196cc81554607323ff11bb211e8914886149ac6/crates/swc_common/src/source_map.rs#L1101-L1199
