### ISSUE TITLE
invite to slack? ;-)

### ISSUE THREAD

**Issue by nchanged** [swc-project/swc#372]
Hey guys! I I got super excited when a friend of mine sent me a link to this project. 

I am the found of [FuseBox](https://github.com/fuse-box/fuse-box) and I am currently working on a brand new version `v4` that is (according to my benches) faster than than any bundler there is by the amount of gratitude) and I am looking at alternatives to transpiling TypeScript since the official one is very slow.

As I understood, you do support the latter? Since that's what FuseBox is build on top of. Does it support source maps? How fast is it comparing to the TypeScript compiler?  Can I feed an AST to generate code? 

Anyway, I have lots of question, but can't get in. Please send me and invite ;-) 

P.S and sorry for the off topic issue ;-)

**Comment by kdy1** [comment]
It's okay, and we support compiling typescript, but we does not support type checking or cross-file compilation like const enum at now.

Slackin link: http://swc-slackin.herokuapp.com
