### ISSUE TITLE
arrows and unsafe_arrows have no effect

### ISSUE THREAD

**Issue by jantimon** [swc-project/swc#3724]
### Describe the bug

I am trying to minify functions with SWC.  

After reading the doc I am not sure why `const x = function (){}` is not converted to `const x = () => {}` with unsafe_arrows

### Input code

```typescript
const x = function () {
  
}

window.z = x
```

### Config

```json
{
    "minify": true,
    "jsc": {
      "target": "es2020",
      "minify": {
        "compress": {
          "ecma": 2020,
          "reduce_vars": true,
          "toplevel": true,
          "arrows": true,
          "unsafe": true,
          "unsafe_arrows": true,
          "passes": 2
        }
      }
    }
  }
```

### Playground link

https://play.swc.rs/?version=1.2.144&code=H4sIAAAAAAAAA0vOzysuUahQsFVIK81LLsnMz1PQ0FSo5lJQ4Krl4irPzEvJL9erAkpXAAA9qELyKgAAAA%3D%3D&config=H4sIAAAAAAAAA22TS5LjIAyG7%2BJ1tj2LPsDs%2BgyUAsJRxoALiXRcqdy9he3GdjI79PHriXh0V7bd56MbITPmeuIpCty7zw5tALaZRulOKlPkYWB8njqB3KNUCX%2Fo3ZAS43p76gJF8lONZFMYMzLXs3qUgFG46SDn9K2m5KLWOaUBIb7ZBthQFOwxb642DQOMjOYGuXnUbJCJUzygIujMmNO4d4%2BOhFJUs0GH4IxNbmvEUUYrdMOdSOOoKLIWd4QOz6Xv6wSX1HiDoYBgs%2B%2FzKDRp87skYjG%2BRH5Ba7WL44KWRlcVeZNRSo6%2FmmuieJjFP0StcwDmCGFX%2F8y9vsVR6f%2Bjouj1IWVqVF95qypir80ZIt86rFVjFsImyuiKxdqh3YKv8NAQk0OD3uu4mzN%2Fk9jLriqZRky%2B3evYYEu%2BWOa4UyusW7CFWeFfLUr2r7HyAHJ5ZTyFcxreQgSUS3JvWOcg6RVmXeD7%2BEpLdKhTRre7KFzN2oB%2BtACxb5v2rCC5UsFjHsf8A%2F90z%2B3T%2FW4If63COdAPMJfU1%2BYDAAA%3D

### Expected behavior

Successfully compiled 1 file with swc.

```js
window.z=()=>{}
```

### Actual behavior

Successfully compiled 1 file with swc.

```js
window.z=function(){}
```

### Version

1.2.144

**Comment by kdy1** [comment]
It's simply not implemented yet
It's not a bug

**Comment by jantimon** [comment]
Maybe we should add this to the docs

**Comment by Austaras** [comment]
+1 it's better to have something like [this](https://swc.rs/docs/migrating-from-babel)

**Comment by kdy1** [comment]
It's now used actually
