### ISSUE TITLE
Maintain number literal text when transpiling?

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#3739]
### Describe the feature

When emitting, swc will emit its f64 value representation of a number literal rather than the text.

For example:

```ts
066;
```

Emits as:

```ts
54;
```

Perhaps it should instead keep the representation as-is? It will cause code to be allowed in strict mode if the diagnostic is not surfaced. That said, it seems reasonable for us to surface this diagnostic from swc instead of relying on v8 so that's what I'm going to do for now.

https://play.swc.rs/?version=1.2.144&code=H4sIAAAAAAAAAzMwM7MGAM7GnskEAAAA&config=H4sIAAAAAAAAA0WOSw6DMAxE7%2BI12264A4eIgkFB%2BcljpKKod68pge7s8cwbN9rgaWxUnYDlnHBkdW8aSY%2FK8BKq0kAKkxYXwR9bnKysZmG87BZLAdOosvNAKeSwHCfIl1SFgZ6zk8tr5BtjnFTm%2FRTar8t4FkklbzAoVILXJ3utU5n5%2F8Zd1S0BU%2Bddhi%2F%2Bl6pn3AAAAA%3D%3D

**Comment by kdy1** [comment]
This requires some huge changes like adding `NumLitKind` to `Number`, just like `StrKind` of `Str`.

**Comment by dsherret** [comment]
Yeah, I don't think it's worth to implement. I thought I would raise the issue anyway though.

**Comment by dsherret** [comment]
I'm going to close this. Don't think it's worth it to implement.
