### ISSUE TITLE
typescript: angle-bracket type assertions

### ISSUE THREAD

**Issue by jrr** [swc-project/swc#374]
Example from the [typescript handbook](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions):

```ts
let someValue: any = "this is a string";
let strLength: number = (<string>someValue).length;
```

tsc handles it but swc errors:

```
> time ./node_modules/.bin/tsc type-assertion-angle-bracket.ts
        5.74 real         8.84 user         0.35 sys
> time ./node_modules/.bin/swc type-assertion-angle-bracket.ts
error: Unexpected token Some(Word(string))
 --> type-assertion-angle-bracket.ts:3:27
  |
3 | let strLength: number = (<string>someValue).length;
  |                           ^^^^^^

[Error: failed to parse module]
        0.13 real         0.11 user         0.02 sys
>
```

..but look at that run time! Dang this thing is _fast_.

Versions:
```
> ./node_modules/.bin/tsc --version
Version 3.4.5
> ./node_modules/.bin/swc --version
@swc/cli: 0.1.18
@swc/core: 1.0.40
```

**Comment by kdy1** [comment]
It seems like you have `.swcrc` with `tsx: true`. Type cast like <string> is invalid in tsx files.


Anyway, it's swc's bug. 
Swc currently does not consider extension while compiling typescript files.

**Comment by jrr** [comment]
Ah, good point! Indeed I discovered this while trying swc on a codebase of mixed .ts and .tsx.
