### ISSUE TITLE
SWC is producing sourcemaps that are causing warnings with ESBuild

### ISSUE THREAD

**Issue by djalbat** [swc-project/swc#3772]
### Describe the bug

Good morning.

ESBuild has started printing warnings this morning for some of my projects transpiled with SWC. For example:

```
 lib/view/span/copied.js#sourceMappingURL:1:3512: warning: Bad "mappings" data in source map at character 663: Invalid source index value: 1
    1 │ ...QAAa,CACrC;QAAW,CACV;QAAW,CAGlC;;;;K;;;IAvGMA,UAAU,iBAAhB,QAAQ;kC;;aAAFA,UAAU,CACFC,QAAQ,EAAEC,OAAO;yC;;kCACrBD,QAAQ,CCZlB,CDYoB;cAEXE,QAAQ,GAAGD,OAAO,CAAC;;;;;YAG1BE,GAAY,EAAZA,CAAY;mBAAZA,QAAQ,CAARA,YAAY,GAAG,CAAC;gBACd,EAAE,EAAE,IAAI,...
      ╵                                                                                                                          ^
```

### Input code

```typescript
To replicate this issue exactly, clone the following repository:

https://github.com/xomicloud/ui-elements

Then `npm install` and `npm run build-debug`.
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": true
        }
    },
    "module": {
        "type": "commonjs"
    }
}
```

### Expected behavior

No warnings.

### Actual behavior

Some warnings.

### Version

1.2.52

**Comment by djalbat** [comment]
I have had confirmation from ESBuild's maintainer that the problem is indeed with the source map:

https://github.com/evanw/esbuild/issues/2066

**Comment by kdy1** [comment]
Can you try the latest version of `@swc/core`? (`v1.2.155`)

Patches in https://github.com/swc-project/swc/pull/4007 are very likely to fix this issue.

**Comment by djalbat** [comment]
No, this has not fixed it for me. You can try for yourself in any one of my projects, for example:

https://github.com/djalbat/concur-algorithm

**Comment by kdy1** [comment]
Can anyone make an executable repro case?
node.js seems to consume sourcemap of swc without any problem.

**Comment by kdy1** [comment]
Can you try the latest version? (`v1.2.156`)
There was a bug fix for a module that only contains `export * from './foo'` and such module is super common, so I think it can be the cause of this.

**Comment by djalbat** [comment]
Hello, unfortunately the bug is still there. You can see it yourself. Clone the following:

https://github.com/djalbat/concur-algorithm

Then run `npm install` and `npm run build-debug`. This will only take you a few seconds. This is the easiest way to see the errors and you can see exactly which files are causing the problem.

Also, Even Wallace's reply may also help you:

https://github.com/djalbat/concur-algorithm

I think you need to check this against Mozilla's https://www.npmjs.com/package/source-map, as Even suggests.
