### ISSUE TITLE
Changes in 1.2.140 broke class inheritance for unresolved super classes in commonjs modules

### ISSUE THREAD

**Issue by JeremyGrieshop** [swc-project/swc#3786]
### Describe the bug

Prior to 1.2.140, if we had:

`A.ts`

```
import {B} from ".";

export class A extends B {

  constructor(x : object) {
    super(x);

    this.field2 = x.field2;
  }
}

export default A;
```

And B was exported from an `index.js`, not quite resolvable, because of circular dependencies, then we would generate commonjs that looked like:

```
...
var A = /*#__PURE__*/ function(B) {
    "use strict";
    _inherits(A, B);
    var _super = _createSuper(A);
    function A(x) {
        _classCallCheck(this, A);
        var _this;
        _this = _super.call(this, x);
        _this.field2 = x.field2;
        return _this;
    }
    return A;
}(_.B);
...
```

After 1.2.140, it now generates:

```
var A = /*#__PURE__*/ function(B) {
    "use strict";
    _inherits(A, B);
    function A(x) {
        var _this;
        _this = B.call(this, x); // <- this is problematic!
        _this.field2 = x.field2;
        return _this;
    }
    return A;
}(_.B);
```

As you can see, _this used to be assigned to `_super.call(this, x)` and now it's been replaced with a more direct call to `B.call(this, x)`.  But, in some cases `B` can be undefined here.  So, trying to import and use this class will throw errors all over the place.

### Input code

```typescript
import {B} from ".";

export class A extends B {

  constructor(x : object) {
    super(x);

    this.field2 = x.field2;
  }
}

export default A;
```

### Config

```json
[
  {
    "test": ".*.js$",
    "module": {
      "type": "commonjs"
    },
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "dynamicImport": true,
        "jsx": true
      },
      "transform": {
          "react": {
              "runtime": "automatic"
          }
      },
      "loose": true
    }
  },
  {
    "test": ".*.ts$",
    "module": {
      "type": "commonjs"
    },
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "dynamicImport": true,
        "tsx": true
      },
      "transform": {
          "react": {
              "runtime": "automatic"
          }
      },
      "loose": true
    }
  }
]
```

### Expected behavior

The previous behavior of using `_createSuper()` should be used instead of directly calling the `.call` method of the super class.

### Actual behavior

Directly calling the super class results in a undefined object being assigned to `_this` and the entire class cannot be imported/used anywhere, due to crashes.

### Version

1.2.140

**Comment by Austaras** [comment]
That's the effect of [constantSuper](https://babeljs.io/docs/en/assumptions#constantsuper) I just recently implemented, you could disable loose for now. `assumption` support is on the way and you would get  a more fine grained control of loose mode by then.

**Comment by kdy1** [comment]
Closing as this is an issue of config.
You should restrict your code if you want to use benefits of `loose`.
Thanks @Austaras
