### ISSUE TITLE
Typescript Path Alias supporting

### ISSUE THREAD

**Issue by JeremyWuuuuu** [swc-project/swc#379]
Hi, I am trying to bring `swc-loader` into my daily job, based on the current working stack:
`React with typescript`, then I encountered a problem which is the `path alias(resolving)`
in `tsconfig.json` I mapped  the paths like this:
```json
{
...
"paths": {
   "@/*": ["src/*"]
},
...
}
```
when I changed the `babel-loader` to `swc-loader`, the path alias (resolving) seems not working anymore:
```javascript
Module not found: Can't resolve '@/types.local' in `~/work/project/src/dux/actions';
```
I wonder that maybe, if swc compiler can read the configurations from the local `tsconfig.json`, and match the functionality?
Any help would be very much appreciated. Thanks.

**Comment by besok** [comment]
hello, can i take on this issue?

**Comment by kdy1** [comment]
Of course, thank you in advance.

**Comment by besok** [comment]
attached the documentation to the future.
https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by wxs77577** [comment]
Thanks for your great project.I'm using nestjs monorepo https://docs.nestjs.com/cli/monorepo, it uses `paths` to define path aliases in `tsconfig.json`.Is there any progress or roadmap on implementation of this feature?

**Comment by kdy1** [comment]
@wxs77577 I'll implement this with a new minor version of swc. (Finally, I have an idea how to implement it correctly)

**Comment by kdy1** [comment]
@wxs77577 Does you use swc via `swc-loader`?

**Comment by wxs77577** [comment]
> @wxs77577 Do you use swc via `swc-loader`?

I just use swc cli.

**Comment by kfirba** [comment]
@kdy1 I saw that you closed the associated PR. Any plans for implementing this?

**Comment by kdy1** [comment]
Yes, but I'm too busy these days.

**Comment by kdy1** [comment]
I started working on this, and I'm not sure if it's correct to support both of babel rewriter and tsconfig rewriter.
What do you guys think?

**Comment by ibraelillo** [comment]
This is still not working for es6. cjs works fine, it seems.

**Comment by kdy1** [comment]
Can you file a new issue?
