### ISSUE TITLE
`/*#__PURE__*/` is removed if `minify.mangle` is specified

### ISSUE THREAD

**Issue by Xenfo** [swc-project/swc#3807]
### Describe the bug

Even with no minify options, SWC removes `PURE` comment.

### Playground link

https://play.swc.rs/?version=1.2.147&code=H4sIAAAAAAAAA31VUW%2BbMBB%2Bz6%2B4vhQiUfKeAJkWtVqldpraVXuo%2BuCAaawajIzR2rH899nGBpuki5QQ353vvu%2B7syFVw7iAHroWP3WkgCOUnFUQfClp937VkdWBsbc22CzIEPmAUS4iuaFk%2FDfixQMuI7V5hyjdo%2FxNL67LEqso%2BfdRIIHHrFztlslsth52B5y%2F7dn7bc7qyFv94Kxpx53xKje%2BKyKdE6B%2BAfAoPigu7OZotNzWBcmRYHwy3aE9ptPyF0dNg%2FnitEzcqgDFfIHfdSXx0eABIS4GWinsGaMY1fAXAlIXWGBekVq6nG2kltYS5XhkNzBTwEmxXUMrOKlfN3JJFTjPkg%2FlpM1UUsaCtGhP51av%2FmwDLlFHxe5cspb8UdFBWwWKRVXoB30NdE4ptXTqpsc3u%2BSkP9lmcRyZSmMrRpZSnWlGkm8%2F7%2B%2B%2BdkKw%2BpriCtci8uXIQllOfUELoz6kiMw%2FhdH%2Bp7aB6mPksUtPAmv0yY%2BhEuwaFA%2BJ0xtCExDHcaOA6eVx7aMdgjgu5XMJaWYwDwJ06hyl9kSFpFhuHO9zi2lpwUCLxeO0fhm26eFK3EnLwrNkYLuFEtEWa68so5%2FjAQxDBxvMatmMM9VGK8DWygtpmoLgnetU7tnIe961A8xa8gn1%2F3hoJlr1CJ5th%2Bdt9FG%2FWO6DxgdUFxTv5OMVD5La62kmCSkh9BItR8Aci47Xn4qm5BzNWqCZGmAoSd6f6WRonnRGXTSsPC1gTq1KfeE6jdaOat6MnVfK8LOMEu8%2B1Ccu7dXvMRvxJv4962hBirRXY390bPJ0pL38cW2mmzLzBND1s9oYh96lvdtJN9CfhrT3125kbw%2FyZMwcdzJ7U6g7K8f3rKtF5g20CxkuZDuG7l5eQujFyZT6VvFU9wifm5YjrPxyS5dDspqhdHqy8pty0i39woODqOgN46ZLWa9v0aPdrGPsTms0o5DZu0VO1kINj60Uy9dQQ9HHd1SpQxZYu3xx%2FANLUQ3lVggAAA%3D%3D&config=H4sIAAAAAAAAA0VPOw6DMAy9i2eGiqEDJ2iPYQWDUiVxZDsSEeLuTUC029Pz%2B3mHjzqYdsgoStKR1mS4wQRWM6kTnw0GMG2USaEBZnIsaCwK04JBO1UTRu%2FeMbPYpTsGoM1IEoYXhUxdfflNMOnCEnubEDo7QUnmI7VeLMYRzTs4WkhgVvoVGcpKTQ%2Bk42Mc27Dok19qT3Acs5D%2BV0VMa7i9PevW3neeS7%2Fv56tn6LN1fgE0FIuCFAEAAA%3D%3D

### Expected behavior

`PURE` comments not to be removed

### Version

1.2.147

**Comment by Austaras** [comment]
It is a bug of playground -- it doesn't output any comments, whether manually written or generated. Actual swc would preserve pure comments.

**Comment by Xenfo** [comment]
Nope playground works. Try it out on local, with same config as playground.

**Comment by Austaras** [comment]
Oh, the minify config is really confusing: remove `jsc.minify` field completely would fix this

**Comment by kdy1** [comment]
@Austaras Thank you!

I found the cause thanks to your comment.

**Comment by Xenfo** [comment]
Hi @kdy1, it seems like the PR didn't fix it. Even with compress not there or set to false, pure comments are being removed.

Playground: https://play.swc.rs/?version=1.2.149&code=H4sIAAAAAAAAA31VUW%2BbMBB%2Bz6%2B4vhQiUfKeAJkWtVqldpraVXuo%2BuCAaawajIzR2rH899nGBpuki5QQ353vvu%2B7syFVw7iAHroWP3WkgCOUnFUQfClp937VkdWBsbc22CzIEPmAUS4iuaFk%2FDfixQMuI7V5hyjdo%2FxNL67LEqso%2BfdRIIHHrFztlslsth52B5y%2F7dn7bc7qyFv94Kxpx53xKje%2BKyKdE6B%2BAfAoPigu7OZotNzWBcmRYHwy3aE9ptPyF0dNg%2FnitEzcqgDFfIHfdSXx0eABIS4GWinsGaMY1fAXAlIXWGBekVq6nG2kltYS5XhkNzBTwEmxXUMrOKlfN3JJFTjPkg%2FlpM1UUsaCtGhP51av%2FmwDLlFHxe5cspb8UdFBWwWKRVXoB30NdE4ptXTqpsc3u%2BSkP9lmcRyZSmMrRpZSnWlGkm8%2F7%2B%2B%2BdkKw%2BpriCtci8uXIQllOfUELoz6kiMw%2FhdH%2Bp7aB6mPksUtPAmv0yY%2BhEuwaFA%2BJ0xtCExDHcaOA6eVx7aMdgjgu5XMJaWYwDwJ06hyl9kSFpFhuHO9zi2lpwUCLxeO0fhm26eFK3EnLwrNkYLuFEtEWa68so5%2FjAQxDBxvMatmMM9VGK8DWygtpmoLgnetU7tnIe961A8xa8gn1%2F3hoJlr1CJ5th%2Bdt9FG%2FWO6DxgdUFxTv5OMVD5La62kmCSkh9BItR8Aci47Xn4qm5BzNWqCZGmAoSd6f6WRonnRGXTSsPC1gTq1KfeE6jdaOat6MnVfK8LOMEu8%2B1Ccu7dXvMRvxJv4962hBirRXY390bPJ0pL38cW2mmzLzBND1s9oYh96lvdtJN9CfhrT3125kbw%2FyZMwcdzJ7U6g7K8f3rKtF5g20CxkuZDuG7l5eQujFyZT6VvFU9wifm5YjrPxyS5dDspqhdHqy8pty0i39woODqOgN46ZLWa9v0aPdrGPsTms0o5DZu0VO1kINj60Uy9dQQ9HHd1SpQxZYu3xx%2FANLUQ3lVggAAA%3D%3D&config=H4sIAAAAAAAAA22QS27DMAxE78K1F4kXReETtKcoCGUUqNUPJB3ECHz3SInjokBXGoyGnCfd6FsdTTeqLArpSpdsfKWJbKlQJ6EaDWTaLJMZA53girAVUZo8R%2B3WkjkF95lqEXvm1oFwNUjm%2BIFY0dPPeRPO6ouk3iZgZw8xZwsJrZdnK4ktOFrbkliKYi8yljNanqDjYRwbWAo5%2BKVvSJzPEV1ZqREXxH3sB6hfLrJq44T%2B9f0%2FXpVwYUM7S%2F29CnjftbJnCcfDZqyd9cWyRVI5zRtQ%2B8oH9Ft70x0WNoSodAEAAA%3D%3D

**Comment by kdy1** [comment]
You have to test it locally

2022년 3월 6일 (일) 오후 10:30, Samuel Corsi-House ***@***.***>님이
작성:

**Comment by Xenfo** [comment]
I have, it doesn't work locally either.
![F2922I6K](https://user-images.githubusercontent.com/46873232/156925635-95232fa2-6357-46e5-a550-130b557de950.png)
.

**Comment by kdy1** [comment]
Your example works if you specify `jsc.minify.format.comments: true`.
You specified `jsc.minify`, so it defaults to minifier mode.

**Comment by Xenfo** [comment]
Are there docs for `jsc.minify.format` options?
