### ISSUE TITLE
Use of `jsc.transform.optimizer` config removes value when variable declared as `null`

### ISSUE THREAD

**Issue by mohdovais** [swc-project/swc#3816]
### Describe the bug

Adding `jsc.transform.optimizer` configuration, even if with empty object `{}` removes `null` assigned to the varaible. Setting `jsc.transform.optimizer` to false fixes the problem but then it only removes if we minify the code.

 I am encountering issue with `react-jsx-runtime.production.min.js`.

### Input code

```typescript
/** @license React v17.0.2
 * react-jsx-runtime.profiling.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';require("object-assign");var f=require("react"),g=60103;exports.Fragment=60107;if("function"===typeof Symbol&&Symbol.for){var h=Symbol.for;g=h("react.element");exports.Fragment=h("react.fragment")}var m=f.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,n=Object.prototype.hasOwnProperty,p={key:!0,ref:!0,__self:!0,__source:!0};
function q(c,a,k){var b,d={},e=null,l=null;void 0!==k&&(e=""+k);void 0!==a.key&&(e=""+a.key);void 0!==a.ref&&(l=a.ref);for(b in a)n.call(a,b)&&!p.hasOwnProperty(b)&&(d[b]=a[b]);if(c&&c.defaultProps)for(b in a=c.defaultProps,a)void 0===d[b]&&(d[b]=a[b]);return{$$typeof:g,type:c,key:e,ref:l,props:d,_owner:m.current}}exports.jsx=q;exports.jsxs=q;
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "externalHelpers": true,
    "target": "es2022",
    "loose": false,
    "transform": {
      "react": {
        "runtime": "automatic"
      },
      "optimizer": {
        "globals": {
          "vars": {
            "process.env.NODE_ENV": "\"production\""
          }
        }
      }
    },
    "minify": {
      "compress": false,
      "mangle": false
    },
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    }
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA2VTYWvbMBD9nl%2BhmuLanaqmG6wQI9iWuhDIkpGkjDGGkeWzo8aRXEnuGkL%2B%2ByQnadbti3X37u7d6Z18fXmJPtWCgzSAZsC4Rc83t6RP3vfQJdIeuHo0L1e6lVasgTRalaIWsiJrIcmjcVk%2BcaiajRbV0qKIx%2BiecciVWmE0kpwgJgskrEGs9KXMgiGHssVSGGRUqzkgrgpAzj0MU6BWFqCRXQL6OlocYVSq1tNJH%2FAU49EwncxT5KjhACOtlEWF0MCt0hukSoeeGlkN4Ae47l20jtBYLbi9SDQ8ta4kClT%2B6AqvmDGikkGcPDONSvoa7jQJYlzRj%2F2b%2FocEXhqlrSH3mlVrkLaDbxNRRkHZSm6FkgGl1G4acIPMN%2Btc1WG4P0mpdLz1DZb0hCQVXR76EKjBk7ox%2FuvzmlMekCDeeao1LUmWzdPhLF1ko8kinU0%2Bj%2BfZ3TSbTBfZwzzNprPsx%2FQh%2Bz4aj7MvaXY%2FmqV3pFv%2BsNXaMU1%2FS9BY0mknhV%2B6Vf4CZMmMi33TqgFtN7ih2xVsBmd9rKH0R5YZqI9WJ7ezd0nvqAR6ijhmeLW%2FdI4Lut1hoLKta1x3R%2FKsRIH6Z5SuwjACGgTvVvEJZMQ1PAY6503QjeGC9d6KEydmlPtXwWJJOKvriOE8DsOz5p%2BbRB6Nip%2F5L8rcJ%2Fbr42HISQEla2vr80x8oqNvI5jF%2ByHcoj3JWy4NttVye36%2BfwODCntjwLHXDjrpatx4nkGBM%2BW1H6wJ369itzsu3v2G9Cn5yzPO7f0BFhnIhcEDAAA%3D&config=H4sIAAAAAAAAA02QsWoDMQyG30XzEcKNNzeQpenWKVAUVXe42JaR5HBpyLvXTkioFwn9vz5JvoJJVeJ3LAaTa%2BUBfoxgugKvzpox7jkW1pfqqAs7TMA2bscRBogixjDNGK3ritlm0dQZykh%2BT2r2kJoLsLok9EBwG0BKq4Zf1u5Zopwao6dn1HssKsRmG87nzeHjbfe1O3w2xrEL35U8SD4C3NobIIUc5kvvIklFW9trp4R5ic8Vm7U0%2FGOmXbLj2q%2BhhEYaikP%2FgfVp%2Fgd%2BFP4AsmycRDIBAAA%3D

### Expected behavior

Please refer to playground link. The variable defined in `function q(c, a, k)` should remain same.

```
var b, d = {}, e = null, l = null;
```

### Actual behavior

```
var b, d = {}, e, l;
```

### Version

1.2.146

**Comment by williamtetlow** [comment]
@mohdovais can this be fixed with [`jsc.transform.optimizer.simplify`](https://swc.rs/docs/configuration/compilation#jsctransformoptimizersimplify)?

```json
"optimizer": {
  "simplify": false,
  "globals": {
    "vars": {
      "process.env.NODE_ENV": "\"production\""
    }
  }
}
```

**Comment by mohdovais** [comment]
@williamtetlow yes, it is fixed with [jsc.transform.optimizer.simplify](https://swc.rs/docs/configuration/compilation#jsctransformoptimizersimplify), however then it just replaces the value and not evaluates expression (as intended by `simplify`).

for example:

```javascript
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react-jsx-runtime.production.min.js');
} else {
  module.exports = require('./cjs/react-jsx-runtime.development.js');
}
```

will become 
```javascript
'use strict';
if ("production" === 'production') {
    module.exports = require('./cjs/react-jsx-runtime.production.min.js');
} else {
    module.exports = require('./cjs/react-jsx-runtime.development.js');
}
```

instead of 
```javascript
'use strict';
module.exports = require('./cjs/react-jsx-runtime.production.min.js');
```

I am currently using `jsc.transform.optimizer.simplify` only but then wrote a plugin to remove dead code on top of it.

I think swc is using JavaScript style loose comparison (value == null) instead of  checking `undefined` or `void 0` when transforming through optimizer.

**Comment by williamtetlow** [comment]
@mohdovais does the output of `react-jsx-runtime.production.min.js` cause error when `null` is removed?

**Comment by mohdovais** [comment]
@williamtetlow  yes, it does. ReactDOM strict-compare ref value for `null`, and in this case finds `undefined` and throws `Error(va(284))`

react-dom.production.min.js v17.0.2 line 139
```javascript
function Qg(a, b, c) {
  a = c.ref;
  if (null !== a && "function" !== typeof a && "object" !== typeof a) {
    if (c._owner) {
      c = c._owner;
      if (c) {
        if (1 !== c.tag) throw Error(y(309));
        var d = c.stateNode;
      }
      if (!d) throw Error(y(147, a));
      var e = "" + a;
      if (
        null !== b &&
        null !== b.ref &&
        "function" === typeof b.ref &&
        b.ref._stringRef === e
      )
        return b.ref;
      b = function (a) {
        var b = d.refs;
        b === Fg && (b = d.refs = {});
        null === a ? delete b[e] : (b[e] = a);
      };
      b._stringRef = e;
      return b;
    }
    if ("string" !== typeof a) throw Error(y(284));
    if (!c._owner) throw Error(y(290, a));
  }
  return a;
}

```

If you need I can setup demo link.

Thanks
