### ISSUE TITLE
Type only import used in implements is not removed

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#3827]
### Describe the bug

title

### Input code

```typescript
import { Foo } from 'foo'

const a = class B implements Foo {
  
}
```

### Playground link

https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAAx3KMQoAIQwEwD6v2M5X2Fj4DxEFwbhi0ol%2FP7ipZ%2BjmcVxkEg%2F9UBE6GUQqlzkKIuosZkgYumfTttz%2BfgWQ9wGsHqkbQgAAAA%3D%3D&config=H4sIAAAAAAAAAz2PSwrDMAxE76J1Fm0WXeQEvYZw5eDgH5IMMSF3r5yS7obRzBt0wCYOlgMqshAPJT0r7rCA9kriOFSFCVTMUm50TkC7EmeMb4qVWH6%2BRRiz%2BMJpUJjQ6SVa1pDIeNi0JNTg4DRILEXM9RhldJFXsjyQzI%2F5aYMp5OD7ILiSKpPIP5wwr%2FHuDtadve%2Fl08b9uF64oC%2Fb%2FAIU2c5e7AAAAA%3D%3D

### Expected behavior

Foo should be striped

### Version

1.2.147

**Comment by duarten** [comment]
I think the bug exists also with "interface Foo extends Type".

**Comment by kdy1** [comment]
Please file another issue instead.
