### ISSUE TITLE
-C flag does not override existing `true` values with `false`

### ISSUE THREAD

**Issue by Choooks22** [swc-project/swc#3834]
### Describe the bug

Trying to override existing settings from `.swcrc` using `-C` does not work if the value change is from `true` to `false`

### Input code

```typescript
$ npx swc -C jsc.externalHelpers=false
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true
  }
}
```

### Expected behavior

`@swc/helpers` is not imported and external helpers are inlined

### Actual behavior

`@swc/helpers` is imported

### Version

@swc/cli: 0.1.55 @swc/core: 1.2.147

**Comment by kdy1** [comment]
This can be fixed by changing the field type to `Option<bool>`
