### ISSUE TITLE
Update swc_ecma_codegen on crates.io?

### ISSUE THREAD

**Issue by erikdesjardins** [swc-project/swc#385]
I want to use #363 without patching the dependency.

**Comment by kdy1** [comment]
I published it.

**Comment by erikdesjardins** [comment]
@kdy1 can you publish again? swc_ecma_transforms is 0.9.0 on crates.io and 0.11.0 in the repo

**Comment by kdy1** [comment]
I'll publish it after landing https://github.com/swc-project/swc/pull/855
