### ISSUE TITLE
[Parser] Starts with Left Curly Brace

### ISSUE THREAD

**Issue by LuoZijun** [swc-project/swc#387]
BlockStatement
-------------------

If a statement starts with a token `LeftCurlyBrace` (`{`) , it must be a `BlockStatement`.

Input:

```javascript
// NOTE: MISSTAKE.
{a: 1}; // should be a syntax error.
```

Spec Quote:

> lookahead ∉ { `{`, `function`, `async [ no LineTerminator here ] function`, `class`, `let` `[` }

SpecRef: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-expression-statement

Destructuring Binding Patterns
------------------------------------
Context:

*   LexicalDeclaration: `let` or `const`
*   VariableStatement: `var`

Input:

```javascript
var {...c, d} = {};    // should be a syntax error, Rest element must be last element
var {...c, ...d} = {}; // should be a syntax error, Only allowed one Rest element
var {...{}} = {};      // should be a syntax error, `...` must be followed by an identifier in declaration contexts
```

SpecRef: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-destructuring-binding-patterns

Object Initializer ( Object Literal )
-----------------------------------------
```javascript
var a = {b = 1}; // should be a syntax error, do not panic :)
```

SpecRef: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-object-initializer

**Comment by LuoZijun** [comment]
Update:

```javascript
// Ok
{a: 1};

// Syntax Error
{a: 1, b:2};

// Ok
{ a: { 1; break a; } };

// Syntax Error: Label not found
{a: 1; break a;};
```

So `{a:1};` should be fine :D

**Comment by kdy1** [comment]
Is {a: 1;} really error?
It seems like a labelled statement
