### ISSUE TITLE
Uncaught TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by wyhaya** [swc-project/swc#388]
My code:
```javascript
const write = (text) => {
    console.log(text)
}
write(1) 
write('2')
write`3`
```

The result in webpack mode for `development`:

![Screen Shot 2019-05-05 at 10 40 21](https://user-images.githubusercontent.com/23690145/57187491-40e79200-6f22-11e9-960a-183793d8decc.png)

The result in webpack mode for `production`:

![Screen Shot 2019-05-05 at 10 43 44](https://user-images.githubusercontent.com/23690145/57187517-b6ebf900-6f22-11e9-81ae-c96bb0198551.png)

Error:

![DFB71E9C-0C8E-4D74-BE09-B3D93CA47DDF](https://user-images.githubusercontent.com/23690145/57187530-fe728500-6f22-11e9-84aa-95040789839b.png)

> Did not find this problem in babel and typescript.

`swc` is a great tool, not sure if it is a problem with swc, maybe it is related to strict mode?

**Comment by kdy1** [comment]
Minimal repro case:

```js
(function(){
	"use strict";
	console.log(function _t(){
		_t = function _t() {
    		return data;
  		};
	}())
}())
```
