### ISSUE TITLE
1++ should be an error

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#3885]
### Describe the bug

If parser is set to js, swc would report error but in ts it won't

### Input code

```typescript
1++
```

### Expected behavior

Should be error

### Version

1.2.150

**Comment by Austaras** [comment]
What does `TsConfig > no_early_errors` do? It doesn't seems like to be of any use.

**Comment by kdy1** [comment]
It ignores some early errors.
I think it's used by Deno
