### ISSUE TITLE
Reduce bundle Size

### ISSUE THREAD

**Issue by onigoetz** [swc-project/swc#3899]
### Describe the feature

Hi, this is not a feature request per-se, but I see that the size of this package is increasing steadily, is there something that can be done to reduce its size ?

Here is a quick recap for `@swc/core-linux-x64-gnu`:

| Version | Size |
| -------- | ---- |
| 1.2.50 | 22M |
| 1.2.100 | 25M |
| 1.2.110 | 25M |
| 1.2.120 | 28M |
| 1.2.130 | 36M |
| 1.2.140 | 44M |
| 1.2.150 | 60M |

Is there a way to reduce the size of the package ?

**Comment by kdy1** [comment]
It's possible to reduce size if we give up performance, but the binary size is expected to increase as ts/js evolves.
It should handle more input, and should transform more syntax.
Also, removing a feature is a breaking change.

**Comment by kdy1** [comment]
I reduced the binary size recently, although you may already know

**Comment by onigoetz** [comment]
I didn't check for each version individually, but I saw in the release notes

I get that it's bound to increase as features are added ( features for which I am very grateful by the way :) )
