### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by rmanoka** [swc-project/swc#390]
I get an UTF error when I try to compile the [`katex.min.js`](https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js).   This is part of the `katex` package on npm.

The file seems to be correct UTF-8,  when run through `iconv` to check encoding.  Please see below for details.

```
$ npx swc katex.min.js 
[Error: code is not utf8: invalid utf-8 sequence of 1 bytes from index 379535]
$ npx swc --version
@swc/cli: 0.1.18
@swc/core: 1.0.42
$ iconv -f UTF-8 katex.min.js -o /dev/null && echo "Success"
Success
```

**Comment by kdy1** [comment]
"code is not utf8" indicates that `String::from_utf8` returned an error.
But if I manually copied content, it works.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac43befdc65979b52e49b8be25484ca1

**Comment by rmanoka** [comment]
Thanks for looking into this.  I believe this issue is related to [Problem with String::from_utf8](https://github.com/rust-lang/rust/issues/54845).  The linked issue suggests that nodejs is a little less conservative with UTF8 than Rust.  This may cause issues with interoperability for this crate (as explained in the initial post, where `katex.min.js` was bundled using nodejs based bundler).

**Comment by kdy1** [comment]
@rmanoka This issue was related with generated code, not input code. I updated swc to allow invalid utf-8 characters and updated misleading error message.

I'm trying to publish v1.0.43, but travis ci's timeout is too short for swc

**Comment by rmanoka** [comment]
@kdy1 Oh, I did not realize that!  Are you saying it is possible for generated code to be non-utf8 even if input code is utf8?

**Comment by kdy1** [comment]
@rmanoka No. swc emits invalid utf8 string only if input contains invalid utf8 character.

**Comment by rmanoka** [comment]
@kdy1 Okay.  My use-case is to try to use swc as a bundler (as the transforms already provide elegant way to detect `require` or `import` dependencies).  The input code `require`s `katex.min.js` which then triggered this error on compilation.  The fix you have pushed above makes a lot of sense and should help.  Looking forward to checking out 1.0.43.

Regarding travis-ci issue:  may be we should consolidate the test cases, and run only important ones through CI?  I'm just guessing, but if you have a plan for this, I could help out.

**Comment by kdy1** [comment]
@rmanoka 
 Tests run on this repo's update.

And I use a separate repository for building prebuilt binaries. (https://github.com/swc-project/node-swc) It only builds binaries without testing. But it exceeeds 50min on macos, which is travis's timeout.

**Comment by rmanoka** [comment]
@kdy1 Not an expert on travis.  Does this help: [build-times-out-because-no-output-was-received](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)?  They suggest using `travis_wait` or making sure something is printed every 10 minutes

**Comment by kdy1** [comment]
@rmanoka Sorry, but it didn't help. 50 minute is a hard limit and is unrelated with build output.

BTW, it seems like a regression of rustc.
