### ISSUE TITLE
SWC Minify - Thread Panicked - Infinite loop detected

### ISSUE THREAD

**Issue by steelbrain** [swc-project/swc#3913]
### Describe the bug

Import of `firebase/auth` on `firebase` npm version `8.10.1` triggers an infinite loop bug in SWC Minify. This is using the version bundled with Next.js v12.1.0 (so current rc).

Since Next.js is thinking of enabling SWC minify by default starting v12.2.0, I'd request this bug be squashed before that happens.

This repository has the entire thing you need: https://github.com/steelbrain/swc-minify-firebase-auth-bug

Steps to repro:

- Clone the repo
- `yarn`
- `yarn build`

-----

This is the last straw before we're able to move our company's webapp to use swc minify. The build time savings are pretty decent, down from 110s to 80s. Thank you for swc minify!

### Expected behavior

Ideally, the SWC minifier would work.

### Version

12.1.0

**Comment by qinyuhang** [comment]
Hi steelbrain:
I confirm it can reproduce with your repo https://github.com/steelbrain/swc-minify-firebase-auth-bug.

Then I change the next.config.js
```
module.exports = {
  swcMinify: false,
};
```

it works just fine.

I trace back to the panic code: https://github.com/swc-project/swc/blob/main/crates/swc_ecma_minifier/src/compress/mod.rs#L241

It looks like the 200 pass is not OK with your example project. Maybe the number should be increased. I am interested in dig into this problem. I'll keep update in this issue.

**Comment by kdy1** [comment]
12.1.0 contains a super old version of minifier, so I think this is not a useful issue.

Currnet next.js canary uses `swc_ecma_minifier@0.81.1`, but recent version is `0.87.2 `
