### ISSUE TITLE
False "Cannot reassign to a variable declared with `const`" error with destructured function arguments in Typescript

### ISSUE THREAD

**Issue by vincentcr** [swc-project/swc#3929]
### Describe the bug

The code below will admittedly seem a bit contrived but it is a boiled down version of something we have in our codebase. 

What seems to trip the compiler is the `const fn3 = ...` assignment. 

Looks like it mistakens the `({x,y} ... => string)` type for a destructured variable declaration.

The code parses and compiles correctly with tsc, ts-node and esbuild.

### Input code

```typescript
function fn1({x,y}: {x: string, y: string}): string {
    return x + y
}

function fn2({x,y}: {x: string, y: string}): string {
   const fn3: ({x,y}: {x: string, y: string}) => string = fn1
   return fn3({x,y})
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.151&code=H4sIAAAAAAAAA0srzUsuyczPU0jLM9SortCprLVSqK6wUiguKcrMS9dRqIQxazVhLIVqLgUgKEotKS3KU6hQ0Fao5Krl4kpDmGREkknJ%2BXnFJUBdxlYKBPQp2NrBdNqCHMyFcAZQO0SzJsgtAFg82JHWAAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

The code should compile to:
```
function fn1({ x, y }) {
  return x + y;
}
function fn2({ x, y }) {
  const fn3 = fn1;
  return fn3({ x, y });
}
```

### Actual behavior

```
error: Cannot reassign to a variable declared with `const`
 --> input.ts:5:15
  |
5 | function fn2({x,y}: {x: string, y: string}): string {
  |               ^
  |
note: x was declared here
 --> input.ts:6:17
  |
6 |    const fn3: ({x,y}: {x: string, y: string}) => string = fn1
  |                 ^

error: Cannot reassign to a variable declared with `const`
 --> input.ts:5:17
  |
5 | function fn2({x,y}: {x: string, y: string}): string {
  |                 ^
  |
note: y was declared here
 --> input.ts:6:19
  |
6 |    const fn3: ({x,y}: {x: string, y: string}) => string = fn1
  |                   ^
```

### Version

1.2.151

**Comment by kdy1** [comment]
I tried fixing this... and seems like it's wasm-only bug.

**Comment by vincentcr** [comment]
@kdy1 I can still reproduce this issue in `1.2.152`:

https://play.swc.rs/?version=1.2.152&code=H4sIAAAAAAAAA42OsQqAIBRF9%2FcVd0xqqTahfkYyXJ5gBor47ykhjnWnu5zD0TcrbyxD8zykMMUskYLE5Z3hc0JsN4v2kAhl7vC3YwSMiJSJdDct1YTfKmX58gVbJT4SsO2N3Gox9Y6Cv7Cg%2FADW9e751QAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D
