### ISSUE TITLE
how to introduce polyfills without polluting the global scope in swc

### ISSUE THREAD

**Issue by duzhijie317** [swc-project/swc#3945]
### Describe the bug

I'm planning to Migrate from Babel to SWC.

I can use @bable/plugin-transform-runtime in babel to avoid polluting the global scope.But I don't know the way how to introduce polyfills without polluting the global scope in swc

That's why I came here for help

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript"
        }
    },
    "env": {
        "targets": [
            "last 2 versions",
            "> 1%",
            "iOS 8",
            "Android >= 4.4"
        ],
        "mode": "usage",
        "coreJs": 3
    },
    "sourceMaps": true
}
```

### Expected behavior

polyfills without polluting the global scope in swc

### Version

1.2.151

**Comment by kdy1** [comment]
Please read docs
