### ISSUE TITLE
offending filename is not listed on compilation error

### ISSUE THREAD

**Issue by vincentcr** [swc-project/swc#3950]
### Describe the bug

Reopening #3931 with repro information: 

The swc cli does not output the offending source filename when there is a compilation error. This can make it very hard to locate the problem on a large codebase.

The tool should emit the standard <filename:linenum:colnum> next to the errors, which makes the lines clickable in many terminals and editors.

I encountered this with issue with #3929.  

### Input code

Given foo.ts with this content:

```typescript
function fn1({x,y}: {x: string, y: string}): string {
    return x + y
}

function fn2({x,y}: {x: string, y: string}): string {
   const fn3: ({x,y}: {x: string, y: string}) => string = fn1
   return fn3({x,y})
}
```

Then run `swc` (with `@swc/core@1.2.151`) as follows: 

```sh
> npx swc foo.ts --out-dir=build

```

### Config

```json
(none)
```

### Expected behavior

Errors should list  offending files in the `<filename:linenum:colnum>` format.

### Actual behavior

swc output:
```
error: Cannot reassign to a variable declared with `const`

  |
5 | function fn2({x,y}: {x: string, y: string}): string {
  |               ^
  |
note: x was declared here

  |
6 |    const fn3: ({x,y}: {x: string, y: string}) => string = fn1
  |                 ^

error: Cannot reassign to a variable declared with `const`

  |
5 | function fn2({x,y}: {x: string, y: string}): string {
  |                 ^
  |
note: y was declared here

  |
6 |    const fn3: ({x,y}: {x: string, y: string}) => string = fn1
  |                   ^


Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/<snip>/node_modules/@swc/cli/lib/swc/util.js:115:15)
    at files (/<snip>/node_modules/@swc/cli/lib/swc/file.js:175:18)
    at async _default (/<snip>/node_modules/@swc/cli/lib/swc/file.js:194:9)
```

Note that `foo.ts` is never mentioned anywhere in the output. Here in this case there is only one file so it's not an issue, but I would get the same output if this was run against the full codebase with 1000s of files.

### Version

1.2.151

**Comment by RiESAEX** [comment]
try `npx swc index.ts --out-dir=build -C error.filename=true`

this field in .swcrc seems be ignored
