### ISSUE TITLE
'eval' and 'arguments' cannot be used as a binding identifier in strict mode

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#3963]
### Describe the bug

I set strict false but get the bug.

### Input code

```typescript
var arguments = 42;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.152&code=H4sIAAAAAAAAAytLLFJILEovzU3NKylWsFUwMbIGAPTGGuMTAAAA&config=H4sIAAAAAAAAA0WNOw7DIAyG7%2BKZtUtu0KGHsIgTEQFGtiuVoty9oLZksv0%2FPjc41MPSoKAoydi0ZsMXLEA%2BoXoJxcD1WJc2jEqnA0PZyUZEb92LzEo%2F10EKOWx1kDynIqR6WZj3%2BE%2BeHZR4fQ6hgdXS56gkzod2qpoEb7P7PR%2B8Xp8ivus8Mt%2BzkXCZ%2BA%2Bo0yOF3AAAAA%3D%3D

### Expected behavior

no error report.
Or how to set the .swcrc to avoid this error？

### Version

1.2.152

**Comment by kdy1** [comment]
Your code is wrong.
`arguments` cannot be used as a binding identifier in strict mode, and all module codes are in strict mode
