### ISSUE TITLE
Automatic polyfill

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#397]
The only hard part is determining api (swcrc file)

**Comment by kdy1** [comment]
@duncanbeevers 
Babel's polyfill is deprecated, and replaced with core-js/system. (https://babeljs.io/docs/en/babel-polyfill)

How do you think about this feature?

**Comment by duncanbeevers** [comment]
In our existing toolchain, we use the `babel-loader` along with [`browserslist`](https://github.com/browserslist/browserslist) to create minimally-polyfilled builds.

The webpack config for `babel-loader` looks roughly like this:

```js
{
  test: /\.js$/,
  loader: 'babel-loader',
  options: {
    presets: [
      [
        '@babel/preset-env',
        {
          modules: false,
          loose: true,
          debug: false,
          useBuiltIns: 'entry',
          corejs: 3,
          targets: [
            'last 3 Chrome versions',
            'last 3 Firefox versions',
            'last 3 Edge versions',
            'Explorer >= 11',
            'last 4 Safari versions',
            'Android >= 6',
          ],
        },
      ],
    ],
  },
};
```

`babel-loader` already leans on `core-js` for its polyfills and I'm happy continuing to use those; the main thing is having a declarative way of specifying a build such that what eventually comes out of `swc` is polyfilled correctly.

I don't know how core-js is supposed to integrate with swc, or if we need to polyfill as a second pass over the swc-generated assets.

It seems that some work went into separating `core-js` from `babel-polyfill`, and that whatever interface was extracted for the two tools to communicate could either be used here;
 * directly such that `swc` was able to answer the same questions `core-js` asks `babel`
 * as a model for a Rust-powered `swc` / `core-js` API; `core-js` polyfills would still be used, but the selection process would use the Rust-land AST or bespoke data structure.

**Comment by kdy1** [comment]
@duncanbeevers I'm currently working on it, and I want to know the reason you used `entry` instead of `usage`.
I guess it's to import only required polyfills, right?

**Comment by cyjake** [comment]
Please make the feature being able to be opted out :-/ 

In practice I'd much prefer using services like polyfill.io over built-in babel polyfill because the former doesn't punish modern browsers with unnecessary load.

**Comment by duncanbeevers** [comment]
@kdy1 I'm not sure why the babel config is `entry` instead of `usage`, other than that it's quite old. I didn't actually have a hand in crafting this part of our config.

**Comment by kdy1** [comment]
@cyjake Definitely I will. Default will be no polyfill, as it's current behavior.

**Comment by kapouer** [comment]
Using external polyfills, like @cyjake does, still makes it necessary to include specific polyfills like babel-runtime-generator when using async/await. I suppose swc will need something similar ?
Also i'm curious on how swc is going to allow factoring of those helper functions to avoid redundancy when compiling multiple files independently.

**Comment by kdy1** [comment]
@kapouer swc currently depends on module loader, as all module loaders currently used handle duplicated requires.

**Comment by youyiqin** [comment]
@kdy1 Hi.I have a question.So if  I want to use a part of polyfill in my code, the only way is use "import "core-js/features/array/includes" like this code?
I just want it automatic import them which were used.
thanks.

**Comment by kdy1** [comment]
@youyiqin Use can set `mode` to `usage`. See: https://swc.rs/docs/preset-env#mode
