### ISSUE TITLE
error: a bin target must be available for `cargo run`

### ISSUE THREAD

**Issue by Diokuz** [swc-project/swc#403]
I got this error when tried to `cargo run` your project.

[StackOverflow said](https://stackoverflow.com/questions/48979557/a-bin-target-must-be-available-for-cargo-run) it happens because of the absence of `src/main.rs`.

So, how to run your project locally?

```
rustc --version
rustc 1.36.0-nightly (7c71bc320 2019-04-30)
```

**Comment by kdy1** [comment]
swc binaet lives at https://github.com/swc-project/node-swc and you should run install `npm install @swc/core @swc/cli` instead

**Comment by Diokuz** [comment]
Well, I want to contribute, not use)

**Comment by kdy1** [comment]
@Diokuz You can run `cargo test` in a crate you want to contribute. Thanks in advance.
