### ISSUE TITLE
Destructure shadow mis-reference

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#404]
### swc version
```
$ grep swc package.json
    "@swc/cli": "0.1.18",
    "@swc/core": "1.0.45",
    "swc-loader": "0.1.6",
```

### Input
```js
function foo(bar) {
  const { foo } = bar;
  return foo;
}
```

### Output (formatted to prevent wrapping)
```js
function _throw(e) {
    throw e;
}
function foo(bar) {
  var ref = bar ? bar :
    _throw(new TypeError("Cannot destructure 'undefined' or 'null'")),
    foo1 = ref.foo1;
  return foo1;
}
```

### Problem
After destructuring, the variable `foo` is `undefined`.
Rather than allowing the inner `foo` to shadow the outer `foo` function, and getting its value from `ref.foo`, it references a non-existent `ref.foo1`.

**Comment by Austaras** [comment]
why generate _throw though?

**Comment by kdy1** [comment]
> why generate _throw though?

What do you mean?
`throw` is a reserved word and `throw` will be changed to _throw if you target es3.


(Anyway, I found a bug. `_throw` is the name of a helper in swc)

**Comment by Austaras** [comment]
@kdy1 
I mean maybe output
``` js
function foo(bar) {
  var foo = bar.foo
  return foo;
}
```
is fine enough. Also Babel works like this. Is there any specific design intent on this behavior?

**Comment by kdy1** [comment]
> @kdy1
> I mean maybe output
> 
> ```js
> function foo(bar) {
>   var foo = bar.foo
>   return foo;
> }
> ```
> 
> is fine enough. Also Babel works like this. Is there any specific design intent on this behavior?

@Austaras Hmm.. I think this case can be handled specially. (As accessing bar.foo throws if bar is null or undefined.). I'll fix it.
