### ISSUE TITLE
Generated sourcemap loses sourcefileinfo in certain cases

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#4044]
### Describe the bug

demo at https://github.com/swc-project/swc/pull/4043

For certain cases, for some filename it loses sourcename in generated sourcemap.

Check CI failure for the added dummy testcase https://github.com/kwonoj/swc/runs/5565361024?check_suite_focus=true

### Input code

```typescript
const input = `
    export * from './createColors'
    export * from './createColorsFromMap'
    export * from './interfaces'
    export * from './rgbHex'
    export * from './rgbaString'
    `;

    let option = {
        sourceMaps: true,
        filename: 'C:\\github\\color-map\\ts\\index.ts',
    }
    const pass = transformSync(input, option);
    const fail = transformSync(input, {
        ...option,
        module: { type: 'commonjs' },
    });

    expect(JSON.parse(pass.map)).toEqual(JSON.parse(fail.map))
```

### Expected behavior

generated map should contain sources info

### Version

latest TOT

**Comment by kdy1** [comment]
Ah, thank you so much for the investigation.
I think I know the fix.
