### ISSUE TITLE
Add back `definite` on `PrivateProp`

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#4050]
### Describe the bug

The `definite` property was removed, but it's not useless. It's useful for analysis to know if this exists or not.

https://github.com/swc-project/swc/pull/3868/files#diff-7691f705debe5b1726316e17ca0361f9fb546ef8df4a7845474514a22de8f5f4L181

cc @Austaras

### Input code

```typescript
class Test {
  #test!:string;
}
```

### Playground link

https://www.typescriptlang.org/play?ssl=3&ssc=2&pln=1&pc=1#code/MYGwhgzhAEAqCmEAu0DeBYAUNaBiJiSAhAFzIBOAlgHYDmA3FgL5A

### Expected behavior

Should have `definite`.

### Version

swc_ecmascript 0.134.0

**Comment by dsherret** [comment]
@Austaras from my understanding, "definite" in this case means is there an `!` for TypeScript or not. Since this removal, I don't see a way to tell if there's an `!` right now without looking at the source text instead of the AST.

**Comment by Austaras** [comment]
Oh you're right. Although I don't know if this is used in anywhere other than type check.

**Comment by dsherret** [comment]
I use it for code formatting.
