### ISSUE TITLE
import statements improperly transformed when using symlinks

### ISSUE THREAD

**Issue by clhuang** [swc-project/swc#4057]
### Describe the bug

if a module is referenced via symlink in the node_modules, imports referencing that module by name are transformed to relative paths, if the `paths` option is utilized in the .swcrc, regardless of if the `paths` option covers that module name.

### Input code

see: https://github.com/clhuang/swc-paths-bug-repro

input code is:
```typescript
import { hi } from '@hello/there';
console.log(hi);
```

`node_modules/@hello/there` is symlinked to another package.

### Config

```json
{
  "exclude": ["node_modules"],
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "transform": null,
    "target": "es2021",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false,
    "baseUrl": "./",
    "paths": {
      "test/*": ["./test/*"]
    }
  },
  "module": { "type": "commonjs" },
  "sourceMaps": true
}
```

### Expected behavior
run `require('@swc/core').transformFile('src/index.ts').then(x => console.log(x.code))`

the import from is not changed, as it does not match any of the paths.
should emit something like
```js
"use strict";
var _there = require("@hello/there");
console.log(_there.hi);
```

### Actual behavior

actual code emitted is:
```js
"use strict";
var _there = require("../somewhere/dist/index");
console.log(_there.hi);
```

but if `jsc.paths` is unset in the .swcrc, we observe the output in the Expected behavior section.

### Version

1.2.156, appears to happen with any version >1.2.135

**Comment by alexeagle** [comment]
This affects Bazel projects as well.

By default Bazel spawns actions in a sandbox, which is a folder with symlinks out to the original sources. That's intended to help you fully declare all inputs to get correct Bazel hermeticity guarantees, but it results in these require paths.
https://github.com/aspect-build/rules_swc/pull/33 is a workaround in Bazel to turn off sandboxing when calling `swc` but then we lose the hermeticity help.

**Comment by kwonoj** [comment]
Reopen as request from @alexeagle this is a still issue need to be looked into.

**Comment by kdy1** [comment]
I think this is fixed by https://github.com/swc-project/swc/pull/8297
