### ISSUE TITLE
Regression: Cannot parse arrow fn exprs in conditional expr cons and alt in object literals in TypeScript

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#4067]
### Describe the bug

Regression of #2174

https://github.com/swc-project/swc/pull/3685#issuecomment-1050701591

This syntax no longer parses, yet it is valid JavaScript. ~~Maybe the TS compiler can't figure out how to parse it right now~~(Edit: it can figure this out now), but it works in V8.

https://astexplorer.net/#/gist/d8417911fb6ea22a87b63d441b2a0e87/20b56c10cf6e34b3e7ddc60e9328702e09c930fd

cc @williamtetlow

### Input code

```typescript
const x = {
    prop: true
        ? fn => ({ })
            : fn => true,
};
```

### Playground link

https://play.swc.rs/?version=1.2.151&code=H4sIAAAAAAAAA0vOzysuUahQsFWo5uVSAIKCovwCK4WSotJUCB8E7BXS8hRs7RQ0qhVqNRHCIGAFlQJp0OHlqrUGAGjLrV1RAAAA&config=H4sIAAAAAAAAA0WOQQ6DMAwE%2F%2BIz1%2FaQP%2FCIKBiUipDIa6RGiL%2FXoaG9edfeWR%2F0QiB3UPECljahburf5EhrYQSJRWkghVmzX8GnCS8Lq50wHrZbcwaTU9l5oBS3ONcGCjkVYaDnbOW3ZeUbY5yUp70Zx9V18Z7Gg0oM%2Bot95Zgn%2Fn9wt%2FSTiLGj2hPnBwXfhU7WAAAA

### Expected behavior

Should parse.

### Actual behavior

```
error: Expected ':', got ','
 --> input.ts:4:25
  |
4 |             : fn => true,
  |                         ^



Caused by:
    0: failed to process js file
    1: failed to process js file
    2: Syntax Error
```

### Version

1.2.151

**Comment by kdy1** [comment]
I think the patch for #2174 was removed for some reasons, but I don't remember the PR removed it.

**Comment by dsherret** [comment]
It was in #3685. I think it's reasonable that this doesn't parse in TS given that the TS compiler can't figure it out, but it should still at least parse in JS.

**Comment by williamtetlow** [comment]
@dsherret this does parse as JS. The playground you shared has language set to Typescript


see

https://play.swc.rs/?version=1.2.151&code=H4sIAAAAAAAAA0vOzysuUahQsFWo5uVSAIKCovwCK4WSotJUCB8E7BXS8hRs7RQ0qhVqNRHCIGAFlQJp0OHlqrUGAGjLrV1RAAAA&config=H4sIAAAAAAAAA0WOSw7DMAhE78La23bhO%2BQQyCGRK%2F8ERKpl5e61G6fdATPzmAYvcWAbFGQhHpPUpPgGC%2BQiimNfFEy39dOGQeg0oMg76bDIo2shZyGwygcZiD75rQ6Qy7EwicxclzDtgW5M58S8HuPQQGuhL%2B%2FZeaLsnf5i17rklf4N7i%2FT4mWZqFHi%2FACR4MgV1gAAAA%3D%3D

**Comment by dsherret** [comment]
@williamtetlow yup, I missed that and my bad! I think though that we should still try to support this in TS because it might be fixed in tsc in the future.

That said, given that it parses in JS and the TS compiler itself has this bug then I think it's very low priority.

**Comment by dsherret** [comment]
I just went to report this to TypeScript's repo and at the last second I discovered it is fixed in the latest TS nightly:

https://ts-ast-viewer.com/#code/MYewdgzgLgBAHjAvDA3gKBpmAHATibALhilwFcBTDLGgfhgDMwkA+GAChRgF8BKamoJjEmrEuQoAaNNwDcQA (select `@next` in Options > Version)

https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302#code/MYewdgzgLgBAHjAvDA3gKBpmAHATibALhilwFcBTDLGgfhgDMwkA+GAChRgF8BKamoJjEmrEuQoAaNNwDcQA

**Comment by williamtetlow** [comment]
No probs 🙂

For context, I can see why TSC doesn't support it at the moment as it's quite a difficult issue to fix.

The following will parse as we can tell that what comes after the `:` is the falsy expression.
```ts
true ? fn => { } : fn => 1
```

but when parsing
```ts
true ? fn => ({ }) : fn => true
```

This bit`({ }) : fn => true` could be the beginning of a type definition or the falsy expression and we assume the former the same way TSC does.

**Comment by williamtetlow** [comment]
O

> I just went to report this to TypeScript's repo and at the last second I discovered it is fixed in the latest TS nightly:
> 
> https://ts-ast-viewer.com/#code/MYewdgzgLgBAHjAvDA3gKBpmAHATibALhilwFcBTDLGgfhgDMwkA+GAChRgF8BKamoJjEmrEuQoAaNNwDcQA (select `@next` in Options > Version)
> 
> https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302#code/MYewdgzgLgBAHjAvDA3gKBpmAHATibALhilwFcBTDLGgfhgDMwkA+GAChRgF8BKamoJjEmrEuQoAaNNwDcQA

Oh ok let me take a look at how they fixed it

**Comment by williamtetlow** [comment]
It looks like pretty simple fix they just do the opposite now 😄 I can take a look

https://github.com/microsoft/TypeScript/pull/47550

**Comment by dsherret** [comment]
@williamtetlow oh nice! Thanks so much for looking into this 🙂
