### ISSUE TITLE
Failing to build swc when used as a Cargo dependency

### ISSUE THREAD

**Issue by edwincoronado** [swc-project/swc#4069]
### Describe the bug

I have a Rust project using `swc` and `swc_common` crate with the following `Cargo.toml`:

```toml
[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
swc = { git = "https://github.com/swc-project/swc", tag = "v1.2.157", features = [
    "plugin",
] }
swc_common = { git = "https://github.com/swc-project/swc", tag = "v1.2.157" }
```

When I run `cargo build --release` I am getting the following error:
```sh
....
   Compiling wasmer-vfs v2.2.1
error: At least the `host-fs` or the `mem-fs` feature must be enabled. Please, pick one.
 --> /Users/edwin.coronado/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-vfs-2.2.1/src/lib.rs:9:1
  |
9 | compile_error!("At least the `host-fs` or the `mem-fs` feature must be enabled. Please, pick one.");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `wasmer-vfs` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
....
```

### Expected behavior

Cargo should compile successfully

### Version

1.2.157

**Comment by kdy1** [comment]
You need to select plugin runtime if you want to use plugin.

**Comment by edwincoronado** [comment]
Thanks for the response @kdy1 , I added

`features = "plugin-rt"` to the `swc_common` dependency but that didn't work. I looked around the repo/documentation for how to select the plugin runtime as you mentioned but couldn't find anything. Do you have an example of such configuration?

Also, I see several PRs open in the [website repo](https://github.com/swc-project/website/pulls) around plugin documentation, I'll make sure to add some answers that I've gathered while I've been working with the new plugin feature there.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/2c3f1fa001f68bd8e4dccb3393149a5979fdbd15/crates/node/Cargo.toml#L16

This is what you should do.
Depend on `wasmer` and `wasmer-wasi` with `default` of each crates.
