### ISSUE TITLE
New miette-based error reporter reporting wrong line

### ISSUE THREAD

**Issue by edwincoronado** [swc-project/swc#4081]
### Describe the bug

The new error reporting is reporting "n + 1" instead of "n" line. I.e.: if error is in line 1, it's reporting line 2.

Example output:
```log
  × Unterminated string constant
   ╭────
 2 │ const x = 'aaaa
   ·           ─────
   ╰────
```

### Input code

```typescript
const x = 'aaaa
```

### Expected behavior

Correct line should be reported

### Actual behavior

"n + 1" line is getting reported instead of "n"

### Version

1.2.158

**Comment by edwincoronado** [comment]
I think it comes from [here](https://github.com/zkat/miette/blob/main/src/handlers/graphical.rs#L709) in the `miette` repo. We might be better off 0-indexing the initial line number on the SWC side. I'll see if I can push a quick PR myself.

**Comment by edwincoronado** [comment]
Update: it looks line this [line in source_map.rs](https://github.com/swc-project/swc/blob/main/crates/swc_common/src/source_map.rs#L287) is what breaks it. It would be an easy fix to just remove the "+ 1" but I don't know if it would have adverse effects in the resulting source map. @kwonoj  @kdy1  maybe you know if this is safe to do?

**Comment by kdy1** [comment]
This seems correct?

It should point `'` in `'aaaa`

**Comment by edwincoronado** [comment]
> This seems correct?
> 
> It should point `'` in `'aaaa`

Hi @kdy1 , I'm talking about the line number, not the column number. The file only has 1 line and it's reporting "2" on the left as such:
<img width="316" alt="Screen Shot 2022-03-18 at 10 04 04 PM" src="https://user-images.githubusercontent.com/7434954/159107735-816ae28f-ac4d-4364-a602-aa7b39e2456c.png">

If I create a new file with these contents (3 lines total):
```js
let x = 1;
const y = 2;
const x = 'aaaa
```

I get this error:
<img width="286" alt="Screen Shot 2022-03-18 at 10 05 45 PM" src="https://user-images.githubusercontent.com/7434954/159107748-b699e2ff-46c0-47e0-ab9a-89aa34b09b40.png">

**Comment by kdy1** [comment]
Ah I see
