### ISSUE TITLE
Feature: Transform object literals to JSON.parse()

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#409]
`JSON.parse()` is faster than parsing javascript object literals. If an object is serializable to JSON, emit it as a `JSON.parse` invocation.

Expose behavior through configuration.

babel [babel-plugin-object-to-json-parse](https://github.com/nd-02110114/babel-plugin-object-to-json-parse)
webpack [use JSON.parse(jsonSource) for JSON modules](https://github.com/webpack/webpack/pull/9349)

**Comment by kdy1** [comment]
I'll implement this in rust, and will expose like `jsc.optimize.xxx`

**Comment by david-fong** [comment]
Does the current implementation handle [this edge case](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#issue_with_plain_json.stringify_for_use_as_javascript)? Sorry for not checking myself; I don't know how to read rust and I'm not familiar with this codebase.

**Comment by kdy1** [comment]
@david-fong  It's not handled.

**Comment by david-fong** [comment]
> @david-fong It's not handled. (I created an issue for it)

Awesome! Thanks.
