### ISSUE TITLE
Support TypeScript module `node12` and `nodenext` emit

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#4099]
### Describe the feature

TypeScript nightly builds include new module options: `"module": "node12"` and `"module": "nodenext"`  I am requesting that SWC support this style of emit.

Specifically, when TypeScript emits CommonJS in this mode, it does *not* transform dynamic imports into dynamic `require()` calls.

Here is an example:
https://github.com/TypeStrong/ts-node-repros/tree/esnext-demo-for-swc

This example has two imports: one static, one dynamic
https://github.com/TypeStrong/ts-node-repros/blob/esnext-demo-for-swc/src/example.ts

When compiled, the static import is converted to `require()` and the dynamic import is left as `import()`
https://github.com/TypeStrong/ts-node-repros/blob/esnext-demo-for-swc/dist-node12/example.js

**Comment by kdy1** [comment]
Such feature already exists

**Comment by cspotcode** [comment]
Is it `dynamicImport`?  I can't find any clear documentation, am I looking in the wrong place?  It doesn't appear to work in the playground, and the config validator says that field is not allowed: "Property dynamicImport is not allowed"

![image](https://user-images.githubusercontent.com/376504/159132921-1d1543bc-1e4b-4e41-a2b9-02bea62e74ed.png)

**Comment by cspotcode** [comment]
I see, it's `ignoreDynamic` which is missing from the TypeScript declarations:

https://swc.rs/docs/configuration/modules#ignoredynamic
https://github.com/swc-project/swc/blob/565a7202eda1435498f7d98a1f9ec1b34d9fdf33/node-swc/src/types.ts#L746

I'll create a separate ticket for updating the type declarations.
