### ISSUE TITLE
Emit `createRequire` for TypeScript `import =` to match `module: nodenext`

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#4101]
### Describe the feature

TypeScript's new `module: nodenext` will emit `const require = createRequire()` as necessary in ESM modules that have `import =` syntax.  Without calling `createRequire()`, the code fails, because `require` is not defined in ES modules on nodejs.

```typescript
import commonjs = require('commonjs'); 
import * as ecmascriptmodule from 'ecmascriptmodule';

commonjs, ecmascriptmodule;
```

When compiled by SWC using target=es2022 and module=es modules, I get: ([playground link](https://play.swc.rs/?version=1.2.157&code=H4sIAAAAAAAAA8vMLcgvKlFIzs%2FNzc%2FLKlawVShKLSzNLErVUIeJqWtaK%2FByZUIUaikkFiukJucmFicXZRaU5OanlOakKqQV5ecqqKMLq1vzcvFywYzRwdBmDQCfLyLFfQAAAA%3D%3D&config=H4sIAAAAAAAAA0WOvQ6DMAyE38UzQ5WhA3NXHiIKJjIiP7KN1Cji3ZtQaLfT3em7q7CKg7FCtizIXUmJat8wgpaM4piywgAqzVLe8WjaskdtDRTzMKalW0qCMC52ExwgUKSldJZLITOK%2FCMb%2FXY3j8YKad67Uc%2B5k%2FlsQFEmp1Oa8bs6APmYGF8l2kDud%2BWeuvAk08U78w82mTMx3gAAAA%3D%3D))

```javascript
const commonjs = require('commonjs');
import * as ecmascriptmodule from 'ecmascriptmodule';
commonjs, ecmascriptmodule;
```

However, TypeScript will include a call to `createRequire`: ([playground link](https://www.typescriptlang.org/play?target=99&moduleResolution=99#code/JYWwDg9gTgLgBAYwiEEB2ArAznAvHKAUwEcBXYIgCgHIkV1tqBKAbjgChRJY4AqOAIY5CCEEIRRgYGKgAmpADaE4AMyjI41EWKwSpMiPKXUW7dnVSYsAGjjbxk6XMWEWQA))

```javascript
import { createRequire as _createRequire } from "module";
const __require = _createRequire(import.meta.url);
const commonjs = __require("commonjs");
import * as ecmascriptmodule from 'ecmascriptmodule';
commonjs, ecmascriptmodule;
```

Is there any way to tell SWC to emit this `createRequire` call?

**Comment by cspotcode** [comment]
Related to #4679 

I may have some time for this soon; can anyone point me in the right direction to implement this fix?

In ts-node I'm hoping to ship support for TS's new nodenext/node16 modes -- mts, mjs, cts, cjs.  But this is a blocker since it means the swc backend can't emit correct mts.

**Comment by kdy1** [comment]
First, you will have to add a module like `nodenext` to https://github.com/swc-project/swc/tree/fe1e62a5e7a4a0037ba8d158879fb68bf9c14520/crates/swc_ecma_transforms_module/src or alternatively add `nodenext: bool` to common js pass (https://github.com/swc-project/swc/blob/9a027ba7c2146ac4dbfce9478d1a259ff491a11f/crates/swc_ecma_transforms_module/src/common_js.rs)

For the latter, you would need to wrap `util::Config` like https://github.com/swc-project/swc/blob/9a027ba7c2146ac4dbfce9478d1a259ff491a11f/crates/swc_ecma_transforms_module/src/amd.rs#L64-L72



---

After then, you can add an import with a specifier named `createRequire`, using `private_ident!` (like https://github.com/swc-project/swc/blob/9a027ba7c2146ac4dbfce9478d1a259ff491a11f/crates/swc_ecma_transforms_module/src/common_js.rs#L466).
Once you have it, you can add imports to the module, and replace/wrap require calls with `createRequire`

**Comment by cspotcode** [comment]
I've hit a snag and need some guidance.

This `createRequire` transformation should only happen when module type = easy, not Commonjs.  So I implemented an es6 transformation that checked for the presence of any TsImportEqualsDecl and, when found, created the necessary import of createRequire and `const require = createRequire(import.meta.url);`

The problem is, typescript stripping runs before the es6 transformation.  This means TsImportEqualsDecl does not exist by the time es6 runs.

How should the typescript stripping pass tell the es6 pass that a TsImportEqualsDecl was stripped?

I thought about the typescript stripping doing the createRequire, but the problem is that for module=Commonjs, we should not do that.

**Comment by magic-akari** [comment]
I believe this feature is already available in swc.

[swc playground](https://play.swc.rs/?version=1.2.207&code=H4sIAAAAAAAAA0utKMgvKlHIzAVTKgq2CkWphaWZRakaSlmBpalFlUqa1gD4Ch%2BpJAAAAA%3D%3D&config=H4sIAAAAAAAAAy2LQQrAIAwE%2F5JzD8Wjf%2BgjREOxtCpJBEX8e03pbZmZHXCxBzugOGIkXdyTuAYWpBdkT7EIzA3E0YmyMLLZza7oyaHeqB9Nl0o5YML29ZGPXwtVnC9KcCT2aQAAAA%3D%3D)

**Comment by kdy1** [comment]
Thank you!
