### ISSUE TITLE
`@swc/jest`: Spread helper in mock causes tests to fail

### ISSUE THREAD

**Issue by chortis** [swc-project/swc#4104]
I'm currently attempting to migrate our repo over from babel-jest to compile tests with SWC and run them in Bazel.

One of the issues I am having is the helpers that are inject, particularly `_objectSpread` in a mock are causing the tests to fail. A common practice in jest for instance is to do something like this:

```
jest.mock('./myModule', () => ({
   ...jest.requireActual('./myModule'),
   func2: mockFunc2,
   func3: mockFunc4
}));
```

This transpiles to 

```
jest.mock('./myModule', () => ({
   _objectSpread({}, jest.requireActual('./myModule'), {
     func2: mockFunc2,
     func3: mockFunc4
   }
}));
```

Due to jests mocking restrictions, it throws an error.

```
 The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: _objectSpread
```

Has anyone encountered this and discovered a workaround?

**Comment by kdy1** [comment]
You should adjust the target.
