### ISSUE TITLE
Awaited promise value is yielded after conversion

### ISSUE THREAD

**Issue by danni-boii** [swc-project/swc#4108]
### Describe the bug

Swc is converting some await functions into generator function while targeting "ES5".

This only happens after @swc/core version 1.2.156. While version 1.2.155 sometimes performs the same behaviour as version 1.2.156.  
That makes me stuck at version 1.2.154.

### Input code

The [connection.ts](https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/candy-machine-ui/src/connection.tsx) file from mextaplex/candy-machine-ui

### Config
I am using webpack. So I chained swc like this.
```js
{
  test: /\.(js|mjs|jsx|ts|tsx)$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'swc-loader',
      options: {
        jsc: {
          parser: {
            syntax: "typescript",
            tsx: true,
            decorators: false
          },
          target: "es5",
        }
      },
    },
  ],
}
```

### Playground link

https://play.swc.rs/?version=1.2.156&code=H4sIAAAAAAAAA81b63PbxhH%2Fzr%2FiPNMxgZqC5abtB%2BrhpI7dceskHkmZfNBoHJA8UmhAgMGBlhSb%2F3t39157B4CSE6cpJxOR99jb2%2Bfv9s7FelM3rfgwEuLf8m6TF80Evr6o1%2BuiXcuq1b%2BqSs7boq7w19lmfibVpq6U%2FKpaQF8rb2nYebGq8nbbyPMW%2FijdtN6WeSsXF01eqZxo2MnYz5qjn68r1Tbbvh63DLb%2Fo6znP13n6hp%2FvJLyRV7OccUatrETy6Zei%2FGXqi7zKn96I2dfZP9R46PRqDC7Fj%2FkZSnbb%2BvW7FEuXjZN3YjOXBp3kC%2FyTSubg1muJNGBzTfLfC49IyCTgA8S7cz2Tv3AI2hf8pHTcANHo91oJG%2BJ0TkIrBUr2RJ3r%2BqGyUOciFzdVXORzJ2eplxnor0tFlMB8iyqVSpOTomlp0%2FFTV60YgkswuZwiWXRrHMiOZPQLHFBmCJavxhMzGmaXyszMxlLCa44EeN1fjtOQUzCbKC9RWbj%2BbDK27xREm0JCQXWQqQ4DYkSUHY7l1dA8fIKZVksBQx%2Bnq1lm4vHj2Ex%2BpqV9eobqVS%2BkiqlnYu%2Brgw2%2FDKfXyfQZkWEH71oI1cSeX9K8p%2BKJPtz%2BnS1PjKDwDSE%2B3FzXZRSJMkaxtO8TN7KOdJNU%2FHo5ERU27JM3QKkiYvrQgn4D0SC%2FDR3oq1F%2Fr4uFqIAmVRFK0VZ1xslbor2Wvwim%2FrgpljAV1DY%2FFoqRwylsM6KaoH8nlgOyly1r7GNryvizidPjlznbhSRLGW1gvVOxbOQhtZHttmq62R9%2Bewq5TT43x31EN1Ggv9WZirY%2BZEzdFlt1%2BJc%2FryV1Vxe3G0kraUb2iIv0c3BWNAb6ft5W2%2B%2Bq17lRUkBwXuMdonlttI%2BomTFrUr9AGL8Jq%2B2eXkm2%2BYu0ebV5z3Qo51%2FKvLqDn8WPjSBHfbHrMuryyscqyBYSTRXE1x1ezoVbyG8FEoeJ9qOxUexBRWAquUivbzS9odmpWCDb2uIM2BNh0emEaZIxRu0Cj1bb7SytK25WfWZXNfv5bnl6UzO62ZxDCKfyWYiZnVdyrw6hWkfdkfRRqGR%2F8yWRQmhL0mocSKK1DsN2gs1e5s59DZjdA%2BUpLaUnZClkq4%2F4vKyQA%2F3ox2BZQ6zDIWRtS7cZrHoiw7Yo3mWC0Ma%2Box63G7e2Z086rKhg5Dxbq%2BW41AuZssYf0hJx%2BILu%2Fd94lRlMZee6qSPqPGs7i6ili6xeICjF%2Bor2gOGj37DSp0F6r9PxDPNG2mSWaeOthDOrHb3rRUEFh13If7ZhBF5MDqwdt05y3TaU0PpXR5edSRAbWMFJlLKMYtYYDs6khWLzCQe28Ud8ZltjmzXsv0BMoyCzgHeVcLi5zwINfZjNsJa%2BJZ4e7Qz3sXjaBZFSj%2FKisG3hQJBUwWxAJ%2FzvIUMq7J1vkla9JJWC8mNN4FezDEpiUSmQRqF6JJRyIcO77i%2BDzKkFcz460IuBMRtx5W3ZjukQe1j6CSkxsTj5gRW4AhcOQqBQxpDLFTvdGOnustwPxh0eybGqQ8k2sV3sZl4ZPcr09M5Nj8oQdHIIEdBFzOfaZiUT0Lb4hl57o4OU3aMgBnGzv5ZK1VsSMhqO0e4A5C3nOXzn6Yi4UgVvRh%2B6OxEQZnw0Ikw6BJ6ddLZIa0lGDYj1MhcoaSGSJlc16VGaWViIfvz6TCwp0GEk7nOAnmb%2FIMj8yV46f0DGTL4YPi1fB9hUJlSbPFCOhKqrFs7ROyA0O7UpmIMto%2B0dUBUm0FWAA1D7L5u6huAmjdDp5%2BE4%2B1tRSayuLjt47krAJpKK5MEbQigHwPoH3AImIgTdOJNyENGPKYklN4ps8Cf48jSraeJ4skTu6rJIoOJF6ZBZj9iY1WMDeyQe1PlYRDt4ODkAI6eq4EbP7ahCvhRx8SVEGeZYwlrpMjrp2X5YsG7bTjmQ5pQwqg4%2FJ7N%2BGE0nKJka1KKDcpwToHzqtjkdxCbZ3BEuZYm9oj6Bgba809kcDacZllm4RYmEIXbUMwuXWx1klYBXAlhJGd1kzd4NkB2E79KGkifm7FO8YyCMbO%2BUUCv47rcPcza5d25nhiG74CeAZmYObW0iVMqZWBntcANk1SKlZdLBoEWYlLS8WMSGHGuOVluP4ULzYGGup%2BLDzqvuJWcs5sZ2PNVWQY4aI%2F0iGJAbWCDFpn4sUwoG0ipECZ18PKRdV8IPXWnhlGITcZ6bZjs4MJ4wli0GEGM3ytxncNxDk%2FvfmRvuCJe%2B4Jbh25PYHNjzM4wasGGOzJKWGCKwKaKx07ZyhD4Ju7s7t2SIwEsaPRiAe6qdwwhG0QccZ5BMKmSRGtmQhqBRckIQ5Bg03XKQCpTsnbamLoHqD3QNFIyImRQXI7VqkpQIWWKymPrBeNf5NvVdUv4AxwIh0orLPxwXJKEkg1odgR7Egs2APBxHYdAJW8SDj0Uk6CZQIRWgpU9sJcwGaZ8wm6wnBMefR6qg51N6J9uSbYUp7Zl64LL0B70alYwThg93koCMVR3MU6%2Ff%2BZ%2BNpAiK2%2F14vzfDPP3VKHEx7jG3q1IETzFXbzgJWBddPlERF9U83K7kAqA8luACSA2D7Q%2FBVmnnwnCRpgrkJOtGQfoEH%2FkYID1kg91deNAaXwi2Q33iP8fpJdo6P3xo0g%2BEXynKQeIDACHSu4HZQw%2F3of8bGiICoF7weiD4egwIH0oJHUH%2Ft1nh6aW3KMHybQPUQVXJRGiZdHWxM78Jow7oYwb4LT4RSYOzNUbCyE1N%2BqnYvO2kcuygJQ3dQGChwj8vQuufFgNj1kexsCzgJ0k5G5iV%2FfQEkGBLSui1DpBK8wU8zCcaRbo%2F323iZyOARlfv3z11fdvLt5dvP7m5XffX0w4fBLBIdUrch6w4%2BOUjkrji2KNha2tYQTLVwGbdcV1YkuTZud85POMGsGrD9ny4QjZNGEFzt6eOWn03ygGJVV%2F%2F2apWOijaTkME%2B%2F1R1BvYL1%2F%2BoC0dgSJ5OLH2ERdxuUQ8P7s6QrBv2caHU6cf0BytGWncxAEjExcbex3y5tDGeyz5K%2F%2FWfbal7t%2BS%2BYayvt%2FYAmFY%2BzBTPXAPLUb3ZOjfkOGclx6i3YFQ9eS%2BKH%2BesWHiOCWZejoGx98e469jDdKYtoTHhqVwBa%2Fr4rbC4ytiXNDMxud5%2Bu8hcyKNos5AIY8Fc8ODw81KU0jyjd40fQ3GrLnUrt%2Fw53tTUaxDFrgAvPQSSfNjXZT0UukA5%2F7oywVbvQZyLyueO5qLbqr7W3XB%2F2%2BLsPrc1cKH%2B3SB5dzaC8D%2BKezxRAFuYlwKGhIbzDHaTrpQSYc9kx7Xy39SjC0F4Dt0p5iFbKMhYxenAG%2BNea5HXexqCtpUxHuJDHplF3tm9vvRzT08WMuC3HApHRsVRbgj0%2Fe7l7Mae%2F88WMCQCnlJgGX4dAiTUyWufu84NBsMASFY53AULTA5%2B8LDHtBXxfz%2BVvXzrgh5DbmTqLRGvj3VrXhPasGk%2BPwcHQfVOU1uKYhGMZRu%2BeWJILy0A%2Fy5lRmw%2BqaYxz3Dr%2Byjql9JtStj2e6qK2fMZ5RlWi691mj%2BEiPbtjbm7ACGtLCbGErorp9CId3Q7p%2FwJBm7%2FPSv6dhNU5%2FxIzWBecNW0LL6c7AqKJ42TEoWveMtYjjQDzDivYpVbYPDoqwdKm9sSwo9PRQcddzni8cnFGsoWdcyRgSwarJ1wLGTwVIIyqEPsi8x%2BKJ0ITp8UxE0xbrU87LbhR%2F2w0Y4L%2FOv%2Fs20%2BmpWN7FgkXBByYHKPEBPI8N%2BFwWFd6gmE2bIG4fTO06eeENLFzN70z0nwyFcCI%2BBH5GoxiJ9Bjv3lPYUFFu%2BEgV3I33vkE%2B3ueWp%2B7V65etOgBfAnB57%2BGjk6jfRWMSq6%2BAaJDs3i0Klc9K6ea8gEMSvkkY2ctOf5cDGDEfqsoYXKSzWbyiJnFTBFfxEaV3HtrYtdhFGdhEvZBRWToimLX1ORlxMsYH0H%2F%2F65gRoIC6ooCO9SJNEMaC95jBvGaiK%2B16Zt6sEDVfdlmYGKr6Lq5%2F041U%2FZpCE%2Fl5K1WbjHvME7jBdVNbBca7T0o87lQTe6D2OnyYa8mFVowRxFHJ1lpd7gRlXAkH6LuGPjd6GP5Asx2ElwzaWww82euJwwUMi2VgEMixudPP%2Bn2xgvlj9PTf5sCPVJbwj1ljhKkfuOKMafyvB0ISvgJJ2P7QVh29VJRrJViBc00p0iyznb1eWIyu7E602aCSzU4s5gUd1eV7OQGF%2FQdkxSCw0gc4kG%2FCkbG2ItwgTz9a6%2B720fyNYjTHPhSiz2hNetoGOdZoE07l%2FqWi5gqvS62qkZgDxDsHT90NAQMgRhLMWZj9%2BPo6xXz3K9FWSx6JwTbY%2BsCmaDUr6jAnk5Ial%2F%2FCK0qtZLMQgcewv1%2FvRsYxWmh60M2gzMG%2F3xe5uJEzBdFaIt5k84%2BC6UYHeoMhMIhfhfasRuY1tFpnJRrdu5THIF4KYTUeP%2B6GpXv9vccYDRD%2F4VwjfXzMANa%2F3TjsEL7jjA%2BHLGj45SCIS4BYVXtg8uJBBUo%2BIABY1Qf4jxwOMB6a4T1nUPyETwp4CmUhpD8xrHRRLhiXXOJ%2BrtJew%2B1SJewcNWoEfnnYQauP4pjgOlQkmn5LeXl%2BoSOhuaL2J%2FeJ6DEIZ32E4Km%2Fz%2Fb7VtFKvpf%2BoKvjJ3CKHqdhzJn9Z4E3P0gadRgBHiyS%2B0kP1Eh%2BnSQGnZa7beDCva9T9phR7waMoWt1Ton%2FjsN2VrYZKk3cCF5T%2BcthVFQxgCzAY6YW4RCY95HtTM2bQl%2FnXVL%2BuUq5Tzbun1rQ%2BDeFgjOKbBIaSutGgo6CKSZZTJda1uNAXQZ46RYEXaaW6s8utMO1cu%2BDPazx6IUVci1SMAqmGrzHBA44rBUe6naj%2FwKN19jHYTkAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

For the `function sendTransactions()` - line 192 at Playground version 1.2.154  
There should be no yield keyword.

### Actual behavior

At line 209  at Playground version 1.2.156

The 'yield' keyword shows up.

### Version

1.2.156

**Comment by kdy1** [comment]
It's an uneducated guess, but seems like `regerenerator` pass has a bug related to `await` in `return`.
(I didn't try anything, just guess)

**Comment by kdy1** [comment]
I investigated this, and this is caused by pass reordering.

`yield` in `_loop` is not transpiled
