### ISSUE TITLE
Add SWC support for istanbul

### ISSUE THREAD

**Issue by onlychans1** [swc-project/swc#4114]
### Describe the feature

Add SWC support for istanbul

### Babel plugin or link to the feature description

https://www.npmjs.com/package/babel-plugin-istanbul

### Additional context

I am using SWC, but need to use istanbul for my Cypress Code Coverage plugin. Since it is not supported by SWC, I am opting out of SWC for Babel. Some other devs also opted out too. Not sure what the progress is on this. 
![image](https://user-images.githubusercontent.com/60107091/159360413-89049ebc-6c0d-45b7-89c2-d0aa28eade39.png)

![image](https://user-images.githubusercontent.com/60107091/159360336-0bcbc17a-c8e0-4fd1-8358-af4859f340c8.png)

https://github.com/vercel/next.js/discussions/30529
https://github.com/vercel/next.js/discussions/30174

**Comment by kwonoj** [comment]
What exactly swc needs to support other than istanbul's comment directive (https://github.com/swc-project/swc/issues/3854#issuecomment-1073000639) ?

**Comment by kwonoj** [comment]
Let's see if it's possible to port into plugin. This requires to port some of istanbul itself (lib-instrument for example)

**Comment by kwonoj** [comment]
This is now available via https://github.com/vercel/next.js/pull/36692 and https://github.com/kwonoj/swc-coverage-instrument, though I expect there'll be some rough edges need to fix forward. It is unclear if we'll move this codes into swc upstream's plugin repo or not at this moment.

Given this'll probably not be included in `@swc/core`, I'll close this issue as sort of complete. Feedbacks, or issues can be reported in next.js directly instead.
