### ISSUE TITLE
failed to resolve d.ts using webpack and swc-loader.

### ISSUE THREAD

**Issue by dartess** [swc-project/swc#412]
source code: 
```
import {Access} from './typings/Access';
const a: Access = 'accessName';
```
when './typings/Access' is './typings/Access.d.ts'

error:
```
Module not found: Error: Can't resolve './typings/Access' in ...
```

To fix this, you need to write `import {Access} from './typings/Access.d';`

I'm not sure that this is `swc-loader` problem, but everything works with `babel-loader` without additional manipulations.

**Comment by marcus-sa** [comment]
Why would you even import a declaration file in the first place?

**Comment by dartess** [comment]
> Why would you even import a declaration file in the first place?

Not enough experience with ts. Studied the question, thank you.
