### ISSUE TITLE
Read amd-module directive to determine AMD module IDs

### ISSUE THREAD

**Issue by amybzhao** [swc-project/swc#4122]
### Describe the feature

Hi! First off thanks so much for adding support for naming AMD modules via the moduleId field in the .swcrc! 

Our team wants to compile a TS project that uses --outDir though, which means that if we want to be able to produce a named AMD module per file we need to generate a .swcrc for each TS file in the project.

I'm wondering if it's possible to also enable swc to read the name from a `/// <amd-module />` directive in a source file to determine the module Id on a per-file basis? This is a pretty standard way of defining AMD module names.

Link to the description of this directive in the TS handbook: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-amd-module-

Our team's also happy to work on an implementation if this is a feature that y'all agree makes sense to support!

**Comment by amybzhao** [comment]
Yay awesome! Just for clarity, does adding this issue to the "Planned" milestone indicate you or someone else on the SWC core team will likely tackle this, or should our team find time to work on this? 

(Disclaimer: We haven't worked with Rust before but definitely can learn 🤷‍♀️ )

**Comment by kdy1** [comment]
I may work on issues marked as `Planned` when I'm not busy, but `Planned` does not guarantee someone will work on this, as there are lots of tasks already.
