### ISSUE TITLE
The StringLiteral `raw` breaking change in plugin visit

### ISSUE THREAD

**Issue by fz6m** [swc-project/swc#4128]
### Describe the bug

I found that the `StringLiteral` type now has an additional `raw` field.

so, the before `v1.2.160` swc plugin, modify `StringLiteral.value` behavior it is now will not working

Now I will need to change `StringLiteral.value` and `StringLiteral.raw` to get it to work.

Is this breaking change as expected?

### Expected behavior

```ts
class AutoCSSModule extends Visitor {

  visitImportDeclaration(expression: ImportDeclaration): ImportDeclaration {

    // < v1.2.160
    expression.source.value = `cccc`

    // Now I still need sync change to `raw` 
    expression.source.raw = `'cccc'`

    return expression;
  }

}
```

### Version

v1.2.160

**Comment by kdy1** [comment]
Yes it's expected.
I forgot changing js interface, though.
