### ISSUE TITLE
Parser bugs

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#4132]
### Describe the bug

Seems like we are eating too much modifiers in https://github.com/swc-project/swc/blob/3e32fdcdd22a46aa3305663eb1f2d00d4e9e3719/crates/swc_ecma_parser/src/parser/class_and_fn.rs#L528-L529

### Input code

```typescript
class A {
  static abstract<T>{}

}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2018",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.160&code=H4sIAAAAAAAAA0vOSSwuVnBUqOZSUCguSSzJTFZITCouKUpMLrEJsauu5eKqBQBwosTTIwAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm0XpeQOPYRxleDgHxoFGozvXju4ZCfNPD0V2mBpLpSNgKVPOKKaL82kR2ZYcVlpIkWLFuPBtS1GVtaGMB63%2B6vVPiXwACYKLrrl6DKbQhYGrsrE1f%2FJ2lwhffYelPPf6XxSvRzjzuE9QJWd6w%2B6QIF4uAAAAA%3D%3D

### Expected behavior

It should be parsed

### Version

1.2.160

**Comment by magic-akari** [comment]
The implementation of `ts_next_token_can_follow_modifier` differs from Babel.
https://github.com/swc-project/swc/blob/bf1924d1a8cc2039b624eecd9730d012c1e47321/crates/swc_ecma_parser/src/parser/typescript.rs#L10-L21

- https://github.com/babel/babel/pull/12356#discussion_r524356105
