### ISSUE TITLE
Typescript and es6 to es5

### ISSUE THREAD

**Issue by Diokuz** [swc-project/swc#414]
Hi there)

Is it possible to configure swc for both – ts and es6?

Looks like I can only set one parser per project https://swc-project.github.io/docs/configuring-swc

**Comment by kdy1** [comment]
@Diokuz `.swcrc` file is a bit misdesigned.

Sadly, you need to use webpack and `swc-loader` to do so at this time.

**Comment by kdy1** [comment]
I have an idea. Adding a field named "match" / "for" should allow this.
I'll do this after fixing #431.

**Comment by kdy1** [comment]
I fixed it in @swc/core v1.0.47 and documented it at https://swc-project.github.io/docs/configuring-swc.html#multiple-entries

**Comment by stavalfi** [comment]
@kdy1 you are fuc*** Santa Claus!! Thank you for all your AMAZING work!!!!!! you are making our development so much better and fun!! thanks you!!!!

cc @novemberborn for ava

**Comment by kdy1** [comment]
@stavalfi Haha, thanks you for using swc. I had hard time implementing swc, and I'd really like to see it being used.

If you are using it at work, can I add a link to the homepage?

**Comment by stavalfi** [comment]
@kdy1 We don't have a website. The closest thing we have is: https://www.linkedin.com/company/octopol/?originalSubdomain=il (maybe hide it under a link: [octopol.io](https://www.linkedin.com/company/octopol/?originalSubdomain=il))

I'm sorry that we can't provide you something fancier :P

**Comment by kdy1** [comment]
@stavalfi  It's enough, thanks!
