### ISSUE TITLE
cargo install swc_* results in error

### ISSUE THREAD

**Issue by kenotron** [swc-project/swc#4141]
### Describe the bug

```
error[E0609]: no field `is_in` on type `&swc_ecma_ast::TsTypeParam`
   --> /Users/ken/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_codegen-0.99.2/src/typescript.rs:956:14
    |
956 |         if n.is_in {
    |              ^^^^^ unknown field
    |
    = note: available fields are: `span`, `name`, `constraint`, `default`
```

Pretty sure this is caused by this? #4008

**UPDATE**

I just tried add swc_ecmascripts 0.138.0 to cargo.toml to any new project and it will result in the above error. 0.137.0 does NOT exhibit this issue.

### Input code

```typescript
I simply run:

`cargo install swc_cli` 

as instructed in the readme inside swc_plugins
```

I'm noob at this repo, but imagining this line: https://github.com/swc-project/swc/blob/main/crates/swc_ecmascript/Cargo.toml#L40

needs to be bumped to 0.96.1?

### Expected behavior

I believe the correct behavior is this ends with the swc_cli tool installed...

### Actual behavior

errors as specified above...

### Version

"latest"

### Additional context

I'm on a M1 Mac when trying this out.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/commit/7053d6769ae737782ce3265d95a09ed9a1d5f66e is the problematic commit.

I fixed it with https://github.com/swc-project/swc/commit/e6088408bf8990bc2fe828a1b2a899ad5a0359c2

**Comment by kenotron** [comment]
Thank you!
