### ISSUE TITLE
Add support for useDefineForClassFields typescript option

### ISSUE THREAD

**Issue by phoenixeliot** [swc-project/swc#4158]
I'm trying to use TypeScript, Jest, and MobX together with @swc/jest.

MobX, as part of its [installation instructions](https://mobx.js.org/installation.html) requires that `useDefineForClassFields` be set to True for typescript (if typescript is used for compilation), or a similar option for babel (if babel is used for compilation).

This option allows this code to have the property be registered ahead of time, even if it is not assigned a value, which MobX requires in order to be able to observe the property:
```
class Foo {
  someProp: someType;
}
```

The `ts-jest` transformer for Jest obeys the `useDefineForClassFields` option, but `@swc/jest` appears not to obey it, and ignores the babel option as well if it's present.

The result is that MobX doesn't work properly with @swc/jest, and requires the workaround of assigning all class fields values upon declaration, like so:
```
class Foo {
  someProp: someType = someValue;
}
```

It would be great @swc/jest didn't force this workaround.

Here's a commit in my repo that you can use to check this: https://github.com/phoenixeliot/line-puzzle/commit/2ce4beb27a420ae227dba583b9bde377a631ae92

In particular, setupTests.ts has the MobX recommended check to see if this feature is working, which throws an error when you run `jest`.

Repro steps:
- Clone my repo (`git clone git@github.com:phoenixeliot/line-puzzle.git; cd line-puzzle`)
- Checkout my test commit (`git checkout 2ce4beb27a420ae227dba583b9bde377a631ae92`)
- `yarn`
- `yarn run test`
Result: The explicit transpiler check in setupTests.ts will throw its error.

Then for comparison, go to jest.config.js and change the commented out lines to:
```js
    // "^.+\\.(t|j)sx?$": ["@swc/jest", { sourceMaps: "inline" }],
    "^.+\\.(t|j)sx?$": ["ts-jest", { sourceMaps: "inline" }],
```
After this, `yarn run test` will work corrrectly.

**Comment by fregante** [comment]
My current solution is to stop SWC from downgrading the code by specifically setting this: (I'm using Node 16.14, it already supports class fields)

```json
        [
            "@swc/jest",
            {
                jsc: {
                    target: "es2022",
                },
            },
        ],
```

**Comment by kdy1** [comment]
I found that it's already implemented.

`jsc.transform.useDefineForClassFields: true` will do the trick.

**Comment by foray1010** [comment]
@kdy1 should we add it to documentation?

**Comment by kdy1** [comment]
Yes

2022년 8월 2일 (화) 오후 5:49, Alex Young ***@***.***>님이 작성:

**Comment by ymor** [comment]
Can I request that it is also added to the swcrc json schema? Thanks.
