### ISSUE TITLE
Panicking when cargo test

### ISSUE THREAD

**Issue by Diokuz** [swc-project/swc#416]
> swc/ecmascript/transforms master cargo test

```
...
test typescript::tests::issue_392_1 ... ok
test typescript::tests::issue_392_2 ... ok
test typescript::tests::issue_357 ... ok
thread panicked while panicking. aborting.
error: process didn't exit successfully: `/Users/d.o.kuznetsov/github/swc/target/debug/deps/swc_ecma_transforms-e327e58e88520958` (signal: 4, SIGILL: illegal instruction)
```

> cargo --version
cargo 1.36.0-nightly (6be12653d 2019-04-19)
rustc --version
rustc 1.36.0-nightly (7c71bc320 2019-04-30)

RUST_MIN_STACK=16777216 didnt helped me

PS: Also, many tests failed. For example `test proposals::decorators::tests::ordering_decorators_exec ... FAILED`

**Comment by kdy1** [comment]
I'm working on the issue at https://github.com/kdy1/swc/tree/issues

**Comment by kdy1** [comment]
This is closed by https://github.com/swc-project/swc/commit/7715c2626bebcffb87c9603aca82ef18b4b0464c
