### ISSUE TITLE
Emitted AST should optionally include comments

### ISSUE THREAD

**Issue by saibotsivad** [swc-project/swc#4165]
### Describe the feature

When using the parse method in the JavaScript lib `@swc/core` to generate AST, comments are not emitted. For example:

```js
const swc = require('@swc/core')
const source = `
/**
 * Hello world!
 */
export class Test {}
`
swc.parse(source, {
    syntax: 'typescript',
    comments: true,
    isModule: true,
}).then(out => {
    console.log(JSON.stringify(out.body, undefined, 4))
})
```

Currently logs this, which notably does not contain the comment:

```json
[ {
    "type": "ExportDeclaration",
    "span": { "start": 25, "end": 45, "ctxt": 0 },
    "declaration": {
        "type": "ClassDeclaration",
        "identifier": {
            "type": "Identifier",
            "span": { "start": 38, "end": 42, "ctxt": 0 },
            "value": "Test",
            "optional": false
        },
        "declare": false,
        "span": { "start": 32, "end": 45, "ctxt": 0 },
        "decorators": [],
        "body": [],
        "superClass": null,
        "isAbstract": false,
        "typeParams": null,
        "superTypeParams": null,
        "implements": []
    }
} ]
```

Of course, storing comments in the AST increases the size significantly, so it makes sense for this to be optional.

Having the comments in the AST is important to enable certain developer tools, so I would like to have it as an option.

**Comment by kwonoj** [comment]
@kdy1 this sounds like similar (not exactly same) discussion we had for plugin transform side comment support.

- Do you think it makes sense if we could have consolidated way to support both?
- if so, any suggestions?

**Comment by kdy1** [comment]
We can return a map in `comments` field for `parse()`.
I don't think this is related to `transform` apis.

**Comment by RoenLie** [comment]
Any updates on this?

**Comment by kwonoj** [comment]
If you see the issue does not have an update, that's reflecting the current state. Core team has small resources and sometimes cannot keep up all the feature improvement request from the community vs. internal priorities we are currently focusing.

**Comment by RoenLie** [comment]
No worries! I just asked since I didn't find it in the milestone it was added to.
You're all doing a great job and it's highly appreciated!

**Comment by recover758126** [comment]
so, this be solved?

**Comment by Nickersoft** [comment]
@kdy1 Was this ever implemented?
