### ISSUE TITLE
Panic when accessing process.env with bracket notation

### ISSUE THREAD

**Issue by zurp** [swc-project/swc#417]
This is an interesting bug!
I'm getting a panic when accessing `process.env` using bracket notation.
Error: `fatal runtime error: failed to initiate panic, error 5`

This works:
```sh
echo "const test = process.weird['x']" | npx swc --no-swcrc -f "test.ts"
```

This fails:
```sh
echo "const test = process.env['x']" | npx swc --no-swcrc -f "test.ts"
```

Screenshot:
![screenshot](https://i.imgur.com/XsdpHx1.png)

Env:
**@swc/cli**: `^0.1.18`
**@swc/core**: `^1.0.45`
Linux 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux

Thanks for the great work!

Edit - This also works:
```sh
echo "const p = process.env; const test = p['x']" | npx swc --no-swcrc -f "test.ts"
```

**Comment by kdy1** [comment]
This is bit weird. I think it would be easy to spot the problem, but I don't have time until september.
I'll fix it when I have enough time.
