### ISSUE TITLE
Failed to parse optional chaining to ES5

### ISSUE THREAD

**Issue by danni-boii** [swc-project/swc#4170]
### Describe the bug

SWC dispatches an error when I use the `useRef` hook with js optional chaining.
This occurs in after @swc/core@1.2.138 - @swc/core@1.2.160 (Current version)

### Input code

```typescript
import React, { useRef } from 'react';

export function TabList() {
  const tabListRef = useRef(null);

  const arrowKeyListener = (event) => {
    const tabList = tabListRef.current;
    if (event.key === 'ArrowLeft') {
      tabList?.scrollLeft -= 50;
    } else if (event.key === 'ArrowRight') {
      tabList?.scrollLeft += 50;
    }
  };

  const leftwardBtnOnClick = () => {
    tabListRef.current?.scrollLeft -= 50;
  };
  const rightwardBtnOnClick = () => {
    tabListRef.current?.scrollLeft += 50;
  };
}
```

### Config
I am using webpack. So I chained the file like this.
```js
{
  test: /\.m?js$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'swc-loader',
      options: {
        jsc: {
          parser: {
            syntax: 'ecmascript',
            jsx: true,
            dynamicImport: true,
            privateMethod: false,
            functionBind: false,
            exportDefaultFrom: false,
            exportNamespaceFrom: false,
            decorators: false,
            decoratorsBeforeExport: false,
            topLevelAwait: false,
            importMeta: false,
          },
          transform: null,
          target: 'es5',
          loose: false,
          externalHelpers: false,
          keepClassNames: true,
        },
      },
    },
  ],
}
```

### Playground link

https://play.swc.rs/?version=1.2.138&code=H4sIAAAAAAAAA6WPy07DMBBF9%2FmKu0uiQsSGVWQQdEklpIgfCGYMVl27GjuUqvK%2FY6cpRDzEgs0sZs49mqs3W8cBHfUynOGAwVNHChGK3QYl533ZFgW9jZwarAzaWTz0jyvtQ1XjUADSWR8QjrucF5OosoMxdcqfmJ7Z7e5on0GyxIms6JVsqCGuRtcXWwI%2BvY0cmBPcjpxWU7ZZ0x5CCJQ3Wb8iFcp6kuEUv268ZGdMvuJc4PLiaIkg4%2BlXWaefX%2F6yLWa2NOOsr0n3Xc9Pt8He26XRcp0bz8p%2BL%2Ffzo7H9cHJ%2B6T%2FSxUwai3eVhb%2BdAwIAAA%3D%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE7zJrb9uF79BDCFcJLv4hOVBjfPfaISU7MfPmoY6POtiOQqIs69KWKn1hwS6SOvGlwkxsRlUOHgaVZOe6CH3MKuSsDLtRUDaIPvmtLZHLsQir3hWlPfzJMUUxv48VdNRW%2BBQ%2BMW7HtfP6usDzgR%2Fs3ILttAAAAA%3D%3D

### Expected behavior

Before version @swc/core@1.2.138,  code can be converted perfectly.

Expected result

```jsx
import React, { useRef } from 'react';
export function TabList() {
    var tabListRef = useRef(null);
    var arrowKeyListener = function(event) {
        var tabList = tabListRef.current;
        if (event.key === 'ArrowLeft') {
            tabList === null || tabList === void 0 ? void 0 : tabList.scrollLeft -= 50;
        } else if (event.key === 'ArrowRight') {
            tabList === null || tabList === void 0 ? void 0 : tabList.scrollLeft += 50;
        }
    };
    var leftwardBtnOnClick = function() {
        var ref;
        (ref = tabListRef.current) === null || ref === void 0 ? void 0 : ref.scrollLeft -= 50;
    };
    var rightwardBtnOnClick = function() {
        var ref;
        (ref = tabListRef.current) === null || ref === void 0 ? void 0 : ref.scrollLeft += 50;
    };
}
```

### Actual behavior

Swc just throw errors claiming either syntax error or failed to process js file.

One funny thing is, when I change the configuration in the swc playground from `javascript` to `typescript`.  
It works perfectly again. 

### Version

1.2.138

**Comment by kdy1** [comment]
I found that this is not a bug. Your code is invalid syntax.

**Comment by danni-boii** [comment]
Just kindly asking. If it is a bug, how come it works at version @swc/core@1.2.137.
And it even works at @swc/core@1.2.160 if I switch the language to typescript at swc playground.

I think it is very odd.

**Comment by danni-boii** [comment]
I guess my syntax is indeed incorrect. It just went undiscovered over the year.
