### ISSUE TITLE
[css-minifier]Support `@keyframes: <string>`

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#4175]
### Describe the feature

[Chrome does not currently support](https://bugs.chromium.org/p/chromium/issues/detail?id=423424#c11) animation names with quotation marks, which is not compliant with the CSS [specification](https://www.w3.org/TR/css-animations-1/#typedef-keyframes-name). 

```
<keyframes-name> = <custom-ident> | <string>

For example, the following two @keyframes rules have the same name, so the first will be ignored:
@keyframes foo { ... }
@keyframes "foo" { ... }
```

If it is `@keyframes "foo" { ... }`, we can safely remove the quotation marks. This is not only Chrome compatible, but also reduces characters.

Also, it is recommended that users use `<custom-ident>` instead of `<string>` in linter

## Background

https://github.com/w3c/csswg-drafts/issues/118#issuecomment-1079828983

cc @alexander-akait

**Comment by yisibl** [comment]
@alexander-akait  Yes, CSS-wide keywords must be kept in quotation marks.

**Comment by yisibl** [comment]
> Also, it is recommended that users use <custom-ident> instead of <string> in linter

Is this linter already available in swc?

**Comment by alexander-akait** [comment]
@yisibl No, we don't have a linter's rule for it right now, now we want to focus on parser/tranformations and mifications, anyway you can send a PR if you want it
