### ISSUE TITLE
SWC ignores parentheses in expressions

### ISSUE THREAD

**Issue by snusbro** [swc-project/swc#418]
<short summary of the problem>

I tried this: 

- create `test.js`, put there:
`const a = 1 - (1 - 1)`
- run `npx swc test.js`

I expected to see this happen: 
`var a = 1 - (1 - 1);`

Instead, this happened:
`var a = 1 - 1 - 1;`

I'm using
`
@swc/cli: 0.1.18
@swc/core: 1.0.45
`

**Comment by mikekosulin** [comment]
Same.

**Comment by kdy1** [comment]
Closed by #5a47c7a
