### ISSUE TITLE
Support linux/arm64

### ISSUE THREAD

**Issue by mr-bjerre** [swc-project/swc#4184]
### Describe the feature

I have a Mac M1 and are trying to run a NextJS app in a docker container (built on debian:bullseye).

I get the following error though

```
error - Failed to load SWC binary for linux/arm64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
info  - Attempted to load @next/swc-linux-arm64-gnu, but it was not installed
info  - Attempted to load @next/swc-linux-arm64-musl, but it was not installed
```

Are there any workaround?

**Comment by kdy1** [comment]
This is not an issue of swc, and m1 mac is supported. (I use m1 mac)

**Comment by kdy1** [comment]
Oh, it was about linux/arm64.
But it's same, see https://www.npmjs.com/package/%40swc%2Fcore-linux-arm64-gnu

**Comment by mr-bjerre** [comment]
sorry but I don't really understand the solution? I mean my dockerfile shouldn't be platform specific as non-m1 and others should be able to build the image too.

**Comment by Brooooooklyn** [comment]
@mr-bjerre I guess you are running `install` command on `macOS` and running your application directly in Docker container. You can not do this as dependencies may be different cross-platform. You should always run `install` command with absolutely the same versions of `Node.js`, package managers, and platform if you want to install for Docker containers.

**Comment by mr-bjerre** [comment]
Ahhh I just realized my issue. I mounted my host volume on the docker container (including node_modules) so the wrong binaries were being used. My mistake - thanks for your help.
