### ISSUE TITLE
Class is not decorate when created from within a static function

### ISSUE THREAD

**Issue by gm3122** [swc-project/swc#4185]
### Describe the bug

When instantiating a class from inside a static function of this class itself, the class decorator is not called.

### Input code

```typescript
class EventEmitter {}

function EventReceiver(): any {
  return <T extends new (...args: any[]) => EventEmitter>(ctor: T): T => {
    return class extends ctor {
      public constructor(...ctorArgs: any[]) {
        console.log("Event")
        super(...ctorArgs);
      }
    };
  };
}

@EventReceiver()
class Button {
  constructor() {}

  public static create() {
    return new Button();
  }

  public clone() {
    return new Button();
  }
}

Button.create(); // not working
new Button().clone(); // working
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true
    },
    "target": "es5"
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.161&code=H4sIAAAAAAAAA41Qu24DIRDs%2BYqVK2hwbydWEsk%2FEF0XuSBkc0K5LBYstiPr%2Fj3APXSXKg0rmNmZYWxnYoTjBYmP344ZA9x7IT4TWXaeBuQVLboLBql2YOgH7gIgIKdA8NAA3hjpIwLhFaTW2oQ2Vt7bScHjYSV%2BkJZ92EGTlZoCFqlZzNYwk15hjjjAOb13zoL1FDmkAhWrMp%2BXdhMdKtN3qDvfyk2NsFEzGNMZVwJqP2J9nX255iM38fSnATGEfEnMuZ7it8ykantz3MiGS%2BqAhlGq9W9LX4OMrPbLRdt5%2BsdCXhke9GSxh%2B0WyDNcffhy1Irlkh5lK2ki%2FAKX0YqEAgIAAA%3D%3D&config=H4sIAAAAAAAAA0WMMQrDMBAE%2F7K12zSq3eYRx%2BUsYhJJ7J0hQuTvtgvjbhdmZmB1RRpoQjeey3sJ%2BSEhejNXvltgwsu0UqLSkYKb%2FScEpfhS%2BT2tj2XRPl%2FUDQmzxVEzf%2BD4XjeqPaVdnR26dNBCggAAAA%3D%3D

### Expected behavior

Button.create() should return a decorated Button.

### Version

1.2.161

**Comment by kdy1** [comment]
Closing as fixed

https://play.swc.rs/?version=1.2.244&code=H4sIAAAAAAAAA41Qu24DIRDs%2BYqVK2hwbydWEsk%2FEF0XuSBkc0K5LBYstiPr%2Fj3APXSXKg0rmNmZYWxnYoTjBYmP344ZA9x7IT4TWXaeBuQVLboLBql2YOgH7gIgIKdA8NAA3hjpIwLhFaTW2oQ2Vt7bScHjYSV%2BkJZ92EGTlZoCFqlZzNYwk15hjjjAOb13zoL1FDmkAhWrMp%2BXdhMdKtN3qDvfyk2NsFEzGNMZVwJqP2J9nX255iM38fSnATGEfEnMuZ7it8ykantz3MiGS%2BqAhlGq9W9LX4OMrPbLRdt5%2BsdCXhke9GSxh%2B0WyDNcffhy1Irlkh5lK2ki%2FAKX0YqEAgIAAA%3D%3D&config=H4sIAAAAAAAAA0WMMQrDMBAE%2F7K12zSq3eYRx%2BUsYhJJ7J0hQuTvtgvjbhdmZmB1RRpoQjeey3sJ%2BSEhejNXvltgwsu0UqLSkYKb%2FScEpfhS%2BT2tj2XRPl%2FUDQmzxVEzf%2BD4XjeqPaVdnR26dNBCggAAAA%3D%3D
