### ISSUE TITLE
'DotAll RegExp flag' is not Converted to ES5 Syntax

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#4192]
### Describe the bug

'DotAll RegExp flag' is only available after ES9. SWC does not convert the syntax.

### Input code

```typescript
const v0 = "Hello\nWorld";
console.info(`Without 's' flag:`, /Hello.World/.test(v0));
console.info(`With 's' flag:`, /Hello.World/s.test(v0));
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es5",
    "loose": false,
    "externalHelpers": false
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.161&code=H4sIAAAAAAAAA0vOzysuUSgzULBVUPJIzcnJj8kLzy%2FKSVGy5koGSuXnpOpl5qXlaySEZ5Zk5JeWKKgXqyuk5SSmWyXoKOiDdeiBNejrlaQWl2iUGWhqYtOKW18xkkYAT3n%2Fr44AAAA%3D&config=H4sIAAAAAAAAA0WNwQ6DQAhE%2F4Wz1178gvbgR5AtNmtY2AAmWuO%2Fd01tPcFMZt5sMHmCfoOK5mTH56sELtADpYKeLNeArsWaNSI77R2EofioVqCXmbkZaC%2BKo%2BO3FmZVpzPeAS1BJsh34krmF6boc2Y6NmOt7ULSUlQmbwgPyyn%2BjK8c9HlhGd%2FrX4g%2BpK1ovejZh5N%2FZkqWPP4q%2Bwfiymdk%2BgAAAA%3D%3D

### Expected behavior

```js
console.info("With 's' flag:", /Hello[\s\S]World/.test(v0));
```

### Version

1.2.161

**Comment by zloirock** [comment]
It can be better to convert the literal to the constructor calling since `core-js` polyfill it and in this case will be available proper `.dotAll`, `.flags`, `.source`, etc.
