### ISSUE TITLE
`new.target` in object literals are not transpiled

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#4193]
### Describe the bug

'new.target' is only available in ES6. SWC does not convert the syntax.

### Input code

```typescript
const v0 = Symbol("Context#bar");
module.exports = {
    get bar() {
        if (new.target === "foo") {
            return;
        }
        return new Proxy(this, v0);
    }
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es5",
    "loose": false,
    "externalHelpers": false
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.161&code=H4sIAAAAAAAAA1WOQQrCMBBF9znFEDcJSHEfsvICgido7VQLbUYmU02R3L0Jiujb%2FfmPz1woRIHHATyc17mjyegjBcEku65lbZ2aqV8mbDDdiSUW76WgcEWBYhj7yZVxABPw2UjLtfbegx6I9K9TYZSFg%2FvesvpvoIzAiSmtRm5j3Jf%2F7NvOKju1AfVjwuC0AAAA&config=H4sIAAAAAAAAA0WNwQ6DQAhE%2F4Wz1178gvbgR5AtNmtY2AAmWuO%2Fd01tPcFMZt5sMHmCfoOK5mTH56sELtADpYKeLNeArsWaNSI77R2EofioVqCXmbkZaC%2BKo%2BO3FmZVpzPeAS1BJsh34krmF6boc2Y6NmOt7ULSUlQmbwgPyyn%2BjK8c9HlhGd%2FrX4g%2BpK1ovejZh5N%2FZkqWPP4q%2Bwfiymdk%2BgAAAA%3D%3D

### Expected behavior

```js
var v0 = Symbol("Context#bar");
module.exports = {
  get bar() {
    if (void 0 === "foo") {
      return;
    }

    return new Proxy(this, v0);
  }

};
```

### Version

1.2.161

**Comment by kdy1** [comment]
There's code for handling `new.target`, so I modified the title.
