### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by norman784** [swc-project/swc#4195]
### Describe the bug

[Here](https://swc.rs/docs/configuration/compilation#multiple-entries) clearly says that it supports multiple entries, in reality it [doesn't](https://github.com/swc-project/swc/blob/main/crates/swc/src/lib.rs#L1258-L1285).

### Expected behavior

I would suggest to update the docs to reflect the actual project features.

### Version

1.2.161

**Comment by kdy1** [comment]
Why do you this it's not supported?

**Comment by kdy1** [comment]
You should read code correctly before saying something like this

**Comment by norman784** [comment]
After your comment I double checked what could be and the issue was that the regex from the text field was invalid, and because that the error message was not clear

```
0: failed to read swcrc file (src/index.tsx)
1: failed to process config file
2: .swcrc exists but not matched
```
