### ISSUE TITLE
[Typescript] Decorator Issue

### ISSUE THREAD

**Issue by chrismcv** [swc-project/swc#421]
Hi, I'm brand new to SWC and trying it on and existing project.

I'm running into an issue with decorators. I'm using a `bind-decorator`. Code is here https://github.com/NoHomey/bind-decorator/blob/master/src/index.ts

I can see it is expecting 3 arguments, but being passed only 1.
![image](https://user-images.githubusercontent.com/145466/65327277-70362d00-dbab-11e9-8c7e-fc71c00ee32e.png)

My `.swcrc` looks like
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    }
  }
}
```
using versions:
@swc/core@1.0.45
swc-loader@0.1.6

Am I doing something wrong?

**Comment by chrismcv** [comment]
May be relevant: Have `['@babel/plugin-proposal-decorators', { legacy: true }]` in my babel config. Suspect legacy is the issue - is this supported?

**Comment by kdy1** [comment]
@chrismcv It is not supported. Only recent spec of decorator is supported.

**Comment by chrismcv** [comment]
@kdy1 - ok, so you don't support typescript decorators? https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by kdy1** [comment]
@chrismcv I think typescript decorators are supported. Does typescript decorator follow legacy spec?

**Comment by chrismcv** [comment]
@kdy1 - they seem to based on the docs I shared there... also the decorator i'm using is a TS one, and is on a TS class - so I suspect it must be using legacy spec.

**Comment by kdy1** [comment]
@chrismcv Then I'll work on it when I have enough time

**Comment by chrismcv** [comment]
@kdy1 - sorry to pester, just wondering what the timeframe for this might be?

**Comment by kdy1** [comment]
@chrismcv Oh.. I forgot the issue. I'll do it soon. (I expect it will be finished until 12 / 27)

**Comment by kdy1** [comment]
@chrismcv I implemented legacy decorators for classes. Is decorator for object literal required?
I'm asking this I'm not sure if it is correct to make parser accept (currently) invalid input.

**Comment by karim10** [comment]
Having the same issue with `lodash-decorators`
