### ISSUE TITLE
Can't resolve 'core-js/modules/es.string.at.js'

### ISSUE THREAD

**Issue by foray1010** [swc-project/swc#4223]
### Describe the bug

The output code contains `require("core-js/modules/es.string.at.js");`, but the path is not valid for `core-js` `3.21.1`

### Input code

```typescript
console.log([].at(0))
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc.json",
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  },
  "module": {
    "type": "commonjs"
  },
  "env": {
    "targets": "chrome >= 88",
    "mode": "usage",
    "coreJs": 3
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.160&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP14iO1Uss0TDQ1AQAUVJaSBUAAAA%3D&config=H4sIAAAAAAAAAyXOwQrDMAgG4FcpsmNpDruUwPYAe4vgpF1ZYlC7tZS8%2B5Lupn6%2F4gEXxZliAA%2BzWVbv3KKchv9UjYUGlsnpFwWHRtDDogj%2BgBxESVqle7Kw1Ru2Z1KUVzYopYfIz%2FVNLdGgOnKMnBaFipQ%2BpwSZyLThLBypu9%2B6cYRzua2sGiaqLdZXHjV2LeUH7dPf07YAAAA%3D

### Expected behavior

should polyfill using the path `esnext.string.at.js`

### Actual behavior

Using `es.string.at.js` which does not exist

### Version

1.2.160

**Comment by zloirock** [comment]
Before import of `core-js`, `swc` should check is this module available in the used version [like it's done in Babel](https://babeljs.io/docs/en/babel-preset-env#corejs). Use `modules-by-versions` part of `core-js-compat`.
