### ISSUE TITLE
Transpiler Code Cause Fatal JavaScript Invalid Size Error

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#4225]
### Describe the bug

The transpiler code causes a serious bug as follows
```js
# Fatal error in , line 0
# Fatal JavaScript invalid size error 178414678
#
#
#
#FailureMessage Object: 0x7ffc1d73d860
 1: 0xb991a1  [/usr/local/bin/node]
 2: 0x1d2c7c4 V8_Fatal(char const*, ...) [/usr/local/bin/node]
 3: 0xea4828  [/usr/local/bin/node]
 4: 0x105eb22  [/usr/local/bin/node]
 5: 0x105f409  [/usr/local/bin/node]
 6: 0x121ca93 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x162fb79  [/usr/local/bin/node]
```
But the original code can run correctly.

### Input code

```typescript
let v0 = new Array(2);
var v1 = v0 || [];
for (var v2 = 0; v2 < v1.length; v2++) {
    var v2 = v1.v2;
    v0.push(v2 * 2);
}
console.log(v0);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.162&code=H4sIAAAAAAAAA8tJLVEoM1CwVchLLVdwLCpKrNQw0rTmKkssUigzBAoD5WpqFKJjrbnS8osUNMDiRkBxA2sQbQNUpJeTmpdekgHia2trKlRzKQABXB1QvszIGiJmoFdQWpyhARTXUgBZUsuVnJ9XnJ%2BTqpeTn65RZqBpDQA1jPPEjgAAAA%3D%3D&config=H4sIAAAAAAAAAy2LQQqAMAwE%2F5KzVy%2F9g48INUpL05YkgkX6dw142t0Z9oGsEcIDHUVJvOmohjcEoMioUVI3mAsYyknmWFff3ParkB9s9C8hNuZWs7pMuv36wKI0X3tLUmhnAAAA

### Expected behavior

Transipler code can run correctly by node as original code.

### Version

1.2.162

**Comment by kdy1** [comment]
This is bug of V8. Please report to them.

I checked their policies and crashes are not considered a security vulnerability, so I'm closing this.

**Comment by RiESAEX** [comment]
I think we renamed a variable wrongly.
```
/// output
var v0 = new Array(2);
var v1 = v0 || [];
for(var v2 = 0; v2 < v1.length; v2++){
    var v21 = v1.v2; // here we rename v2 to v21.
    v0.push(v2 * 2);
}
console.log(v0);

```

**Comment by kdy1** [comment]
Ah, I see. Thank you!
