### ISSUE TITLE
swc-register

### ISSUE THREAD

**Issue by chinedufn** [swc-project/swc#423]
Hey - awesome project!

Quick question:

Is there an `swc` equivalent to [`babel-register`](https://github.com/babel/babel/tree/master/packages/babel-register)?

Reason for asking - I'm looking to replace my usage of `babel-register` when running some `Node.js` tests in order to speed up a test suite.

Thanks!

**Comment by kdy1** [comment]
I'll implement it soon.

**Comment by kdy1** [comment]
I started working on it, but I think this feature is blocked by https://github.com/swc-project/swc/issues/414#issuecomment-544073503.

**Comment by kdy1** [comment]
@chinedufn I've published @swc/register v0.1.0.

**Comment by yang** [comment]
@kdy1 FYI I think the currently published package has only the uncompiled .ts sources.

**Comment by yang** [comment]
I saw you updated the package, thanks! However I think package.json's "main" is still just "index.js" so simply `node -r @swc/register` doesn't work.

**Comment by kdy1** [comment]
@yang I fixed it and published a new version (v0.1.2)
