### ISSUE TITLE
Minification bug with throw error and preserveAllComments

### ISSUE THREAD

**Issue by smvv** [swc-project/swc#4233]
### Describe the bug

Enabling `preserveAllComments` and `compress` gives incorrect output when re-throwing an error:
```
!function() {
    try {} catch (e) {
        throw // hi
        baz(), e;
    }
}();
```

Notice the single line comment and newline between the throw statement and `baz()`.

### Input code

```typescript
function foo() {
  try {
  } catch (e) {
    // hi
    baz()
    throw e
  }
}

foo()
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true,
      "decorators": true
    },
    "preserveAllComments": true,
    "transform": null,
    "target": "es2017",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": false,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true
      }
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.163&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9fQVKjmUlAoKaoE07UKyYklyRkKGqkQcQUFfX2FjEwwKymxSkMTzCrJKMovV0gFqeeq5eICGwMA6HC%2FSFUAAAA%3D&config=H4sIAAAAAAAAA22TS47bMAyG76J1Fm03BbIbDFC0i%2FYKhiJRiVpJNEgqY2PQu5dKPLKd1CvpEx8%2FH343jJUc%2FLQjm6NQhYP5zc4c381oiYHaiecidjJHI%2FMI7CiOYg5GePrw8HOxObofeUSSDsEhWUFaAv89mJFAQ17hJaVXzBmK9KRCtnBAyuZYakoKLJ1BgxngL58%2Bf9WECZHBHINNrA4wCVCx6TukEVqOhf8BGF%2BTZf5lM6w4xxLD3KpxmJsObmfNURcZi50lwreu6oSYQIU93gfLQywC521mhylpG2G4WuoeLZulyFh2qAr4YSQct%2B7FR4moNa3Qg%2FWDQ7%2FW7SOBk3jd1OY1jhoVVnF76OFUz%2Bc2xXtquNpUrUC%2FT7dWaNLud8HIMoRa%2BAEtau%2BOd3QvdLGKYSCQSqXvEcay60UbzeDabMpuNjcedBZ7y%2FAfq1iCDlLmTnUpVlUFzlrcEGPoFTbVQBKhGxH46qBV6NbgC9wVxNHDACFou7szv0Vxl42q9ktg6O%2FaNhvWIdyvw8dS7Wnbgyf4TWXJdh4Lz1Yuj4znfML0FCKDXNA%2FYe2E4CMkXeFpfKS1eNA%2Bg988VG7X24%2Bs3z%2FyqyzLOAQAAA%3D%3D

### Expected behavior

I would expect the output to not crash.

I can think of some options:
1. Move the comment before the `throw` statement.
2. Convert the comment into a multiline comment.
3. Detect that `baz()` has a single line comment attached and don't allow the comma operator trick.

I think the last option is the safest / most conservative. wdyt?

### Actual behavior

```
Uncaught SyntaxError: no line break is allowed between 'throw' and its expression
```

### Version

1.2.163

**Comment by kdy1** [comment]
Your input is wrong.
Line break cannot follow `throw`

**Comment by smvv** [comment]
hi @kdy1 are you sure this input is not valid?
```
function foo() {
  try {
  } catch (e) {
    // hi
    baz()
    throw e
  }
}

foo()
```

I agree that the generated output (newline after `throw`) is incorrect indeed (which is the reported bug).

**Comment by kdy1** [comment]
Oh, I misread it.
I thought the first code is input

**Comment by kdy1** [comment]
My bad, sorry
