### ISSUE TITLE
Empty RegExp becomes comment when compress and preserveAllComments are enabled

### ISSUE THREAD

**Issue by smvv** [swc-project/swc#4234]
### Describe the bug

An empty RegExp (`new RegExp('')`) is minified as `//`.

### Input code

```typescript
bar(new RegExp(''))
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true,
      "decorators": true
    },
    "preserveAllComments": true,
    "transform": null,
    "target": "es2017",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": false,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true
      }
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.163&code=H4sIAAAAAAAAA0tKLNLISy1XCEpNd60o0FBX19QEAHsw7AwTAAAA&config=H4sIAAAAAAAAA22TS47bMAyG76J1Fm03BbIbDFC0i%2FYKhiJRiVpJNEgqY2PQu5dKPLKd1CvpEx8%2FH343jJUc%2FLQjm6NQhYP5zc4c381oiYHaiecidjJHI%2FMI7CiOYg5GePrw8HOxObofeUSSDsEhWUFaAv89mJFAQ17hJaVXzBmK9KRCtnBAyuZYakoKLJ1BgxngL58%2Bf9WECZHBHINNrA4wCVCx6TukEVqOhf8BGF%2BTZf5lM6w4xxLD3KpxmJsObmfNURcZi50lwreu6oSYQIU93gfLQywC521mhylpG2G4WuoeLZulyFh2qAr4YSQct%2B7FR4moNa3Qg%2FWDQ7%2FW7SOBk3jd1OY1jhoVVnF76OFUz%2Bc2xXtquNpUrUC%2FT7dWaNLud8HIMoRa%2BAEtau%2BOd3QvdLGKYSCQSqXvEcay60UbzeDabMpuNjcedBZ7y%2FAfq1iCDlLmTnUpVlUFzlrcEGPoFTbVQBKhGxH46qBV6NbgC9wVxNHDACFou7szv0Vxl42q9ktg6O%2FaNhvWIdyvw8dS7Wnbgyf4TWXJdh4Lz1Yuj4znfML0FCKDXNA%2FYe2E4CMkXeFpfKS1eNA%2Bg988VG7X24%2Bs3z%2FyqyzLOAQAAA%3D%3D

### Expected behavior

Keep `new RegExp('')` or `new RegExp()` in the output, since the current output (`//`) results in a syntax error.

### Version

1.2.163

**Comment by Austaras** [comment]
Is it safe to optimize `new RegExp` to `/abcd/` at all since one could
```js
globalThis.RegExp = class {}
```

**Comment by kdy1** [comment]
Yes, because it's not a normal user is expected to do.
Reading free standing variables is treated as side-effect-free by almost all tools, if not all, but a global variable can be a getter property defined on `window`.

**Comment by Austaras** [comment]
I asked this because terser put it under unsafe options.

**Comment by kdy1** [comment]
Ah, I see. 
Sounds reasonable. I'll move it after checking something more. Thank you!
