### ISSUE TITLE
Nested `await` in a dynamic import is  not handled

### ISSUE THREAD

**Issue by jameslnewell** [swc-project/swc#4253]
### Describe the bug

SWC is generating invalid code for nested `await` statements on the same line which is resulting in syntax errors when running the generated code 

### Input code

```typescript
let pipeline = await import(await resolve(file))
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2018"
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.157&code=H4sIAAAAAAAAA8tJLVEoyCxIzcnMS1WwVUgsT8wsUcjMLcgvKtGAcIpSi%2FNzylI10jJzUjU1AV3i8sMwAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F21WJXfoIYSjBAf%2FkBSoMb57bXDISmLmzatwioW1QkYW4vFJiYo%2FWIFsQLHssoLpWI929ELNgCIfpAOR5fX%2B9NqnJDQBA8FFt5chsylkJpGnwnj4m2zdFdJ2jaCCltzvmIQUT4H2iObYyXfSyhe1P0Sd89u9AAAA

### Expected behavior

Nested `await` statements on the same line does not result in a syntax error.

### Actual behavior

Outputs an `await` statement inside a regular function causing a syntax error.

The actual generated code:
```js
let pipeline = await Promise.resolve().then(function() {
    return _interopRequireWildcard(require(await resolve(file)));
});
```

### Version

"@swc/cli": "^0.1.57",  "@swc/core": "^1.2.163",  "@swc/register": "^0.1.10",

**Comment by kdy1** [comment]
Changed title to respect actual issue.

https://play.swc.rs/?version=1.2.157&code=H4sIAAAAAAAAAyXGwQmAMAwF0Hum%2BMdmCIcJJYVATIqtioi7K%2FhOj0jGFRVtjzotA6tYFMZN%2BLhOdOvqFooFcopNtMzyb9ORfmhp5spMzwvpPzVdTQAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

**Comment by Austaras** [comment]
How does this thing actually work, wasn't top level await only available in `Module`?
