### ISSUE TITLE
Inconsistent minify behavior with `isModule` option

### ISSUE THREAD

**Issue by SukkaW** [swc-project/swc#4266]
### Describe the bug

swc default minify options generates different codes compare to terser with its default options.

### Input code

```typescript
console.log(5 + 10)
const f  =  5 + 10;
const s = 'Su' + 'kka'
let a = (b) => { return b * 5; };
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {},
      "mangle": {}
    }
  },
  "minify": true,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.163&code=H4sIAAAAAAAAAy3IPQqAIBgG4N1TvNunBVGDk9glOoGKNSgK%2FkzR3RPqGR%2BXU83RLzFfXGLGtgrmxjWcgAa%2BU%2F%2FVUXR0GkkhGGLRN5iR3AroHTeKb70kWEyQCo9iL2%2FgUOthAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F8XL3CGHEK4SXPxD40BC8N0rQ0N3j5k3c9MHgZabGitEJ%2BEqnU9aSEJmBI2tkzPNoo0TZDjqrLv0qcC%2FvLc61Qr5CY5yLHG75lmouakAxrbLXPYkk8f4W10P20Ss9X2k52R8ARVy8T%2BaAAAA

### Expected behavior

terser emits:

```js
console.log(15);const f=15;const s="Sukka";let a=o=>5*o;
```

### Actual behavior

swc emits:

```js
console.log(5+10);const f=5+10;const s="Su"+"kka";let a=b=>{return b*5}
```

### Version

1.2.163

**Comment by SukkaW** [comment]
@kdy1 The issue is gone when `isModule` is set to `true`. The issue seems to be static evaluation stop working on script source type.

**Comment by kdy1** [comment]
Actually swc minifieir does not support scripts.

**Comment by kdy1** [comment]
Closing as fixed https://play.swc.rs/?version=1.3.52&code=H4sIAAAAAAAAAy3IPQqAIBgG4N1TvNunBVGDk9glOoGKNSgK%2FkzR3RPqGR%2BXU83RLzFfXGLGtgrmxjWcgAa%2BU%2F%2FVUXR0GkkhGGLRN5iR3AroHTeKb70kWEyQCo9iL2%2FgUOthAAAA&config=H4sIAAAAAAAAA02NSw7DIAxE95wCed1FxbJ3yCEQdSIifrKJ1Cji7iWE0O48bzR%2Bh5ASVjbwkkc9a0iaGGnkSngPWX8qATResyGbMjzuduWzmrVjbKhcDWRNC%2Ba2YvVUqi%2FAxch4LzrzNth5%2F3ea6BMh88nKcHkdFoeNXS7Rfb8Pmbb2FSxP8b25oRLlCzGj8nDsAAAA
