### ISSUE TITLE
JSON file with array fails to parse `unexpected token ; in JSON ...`

### ISSUE THREAD

**Issue by tedbyron** [swc-project/swc#4275]
### Describe the bug

trying to import a JSON file that has an array will fail to parse with:

```
Module parse failed: Unexpected token ; in JSON at position 328 while parsing near '...k, li 98076"`
```

There are no semicolons in the JSON file so it must be swc-loader adding the semicolon for some reason.

### Input code

JSON array with this shape: 
```typescript
[
  {
    "foo": "bar"
  },
  {
    "foo": "baz"
  }
]
```

### Config

```js
{
  jsc: {
    parser: {
      syntax: 'typescript',
      dynamicImport: true,
      tsx: true,
    },
    target: `es2015`,
    baseUrl: '.',
    transform: {
      react:
        {
          runtime: 'automatic',
          importSource: 'preact',
          pragma: 'h',
          pragmaFrag: 'Fragment'
        }
    }
  }
}
```

### Expected behavior

JSON imports should work, whether they contain an object or an array

### Actual behavior

JSON imports with arrays fail to parse

### Version

1.2.164

**Comment by kdy1** [comment]
This is not related to swc.
You are not expected to process json with swc
