### ISSUE TITLE
Undefined variable when using template literals 

### ISSUE THREAD

**Issue by AGawrys** [swc-project/swc#4276]
### Describe the bug

There's an undefined instead of the actual string when using template literals.
Seems to happen on most new versions, and not on some older ones. For example, in version 1.2.67, this occurs
`var foo='foo-';console.log(foo);var A="".concat(foo,"bar");var B="".concat(foo,"bar2");console.log("test",foo,A,B);`

Which looks more correct

### Input code

```typescript
const foo = 'foo-';

console.log(foo)
const A = `${foo}bar`;
const B = `${foo}bar2`;

console.log("test", foo, A, B)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": true,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": true,
        "side_effects": true,
        "switches": false,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true
      },
      "mangle": {
        "toplevel": true,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.164&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVVAHUrrq1lxcyUDB%2FJxUvZz8dA2gmCZYoETBEagmQaUaKFKblFiUYA0VdkIRNkpAM0CpJLW4REkHZIeOgqOOgpMmAK4OWQ90AAAA&config=H4sIAAAAAAAAA41TwXLjIAz9F845tDuzO51%2BwN76DQwxwlGLgUHCjSeTf1%2FhONhOetgbejzEk550UZ%2FUqfeLSiYT5HqiKbA5q3cF3WCoy5hYHYQmkDOe4HpQbHIPXCn06%2BX1t1z7GAkWwkENGNBNNVkXh5SBqJ7lURkgMDWeyTl%2BS8i5SHSM0YMJT7E2pDEw9JDXp1303iQCPZrcXtTfTEaKYQcVBqtTjmn7PFhkjEHCBlowVnfRroVYzNAxjrAhSR4hBRJxe9DCsfR9beLtaxiNL4ahxee5FfLpHTlFJNauhDX9DVrEblm3OhcWOp2BS26ZPiOGXSu%2BAESmN0TBDBv5M%2B7Eij3T%2FcDC4MRHnhoqJq%2BqAvRSm0Z0rcCqGjIjNFIGWzqoFXZr8gXcqiW0oME5afaKfSN3p40onhJE1%2B6la8atFtxCfR%2BpPVqn4An8K6p4dmOPD4ZPjxhNwzH6pxQD8CnaJ1gawfERzDLA5%2FSIlmBB2gx2c1GohrVK2bXBhL5O2kVxTB5G8P9n8Q9YyjhWz%2FargPDWziJJ9uf15b7q1yog2rIIEAPmpf%2BjruuS38QgfSy8Wfc%2FByciRlgEAAA%3D

### Expected behavior

Expect no undefined.
Variables A and B should be something to the effect of "foobar" and "foobar2", respectively.

### Actual behavior

We get an undefined in a string
`console.log("test",a,"undefinedbar","undefinedbar2")`

### Version

1.2.164

**Comment by Austaras** [comment]
This is caused by

https://github.com/swc-project/swc/blob/431f70d5632ffca7e57ed4fc2dac7d38ca2e614b/crates/swc_ecma_minifier/src/compress/optimize/strings.rs#L124

which doesn't seem to make any sense...

**Comment by kdy1** [comment]
Oh, yeah I agree
I think we need some reviewers for my works
