### ISSUE TITLE
_dec is not a function

### ISSUE THREAD

**Issue by amic81** [swc-project/swc#4283]
Hi,
I'm encountering an error using swc-loader as typescript compiler : **_dec is not a function** in a project Angular.

I have this service : 

![immagine](https://user-images.githubusercontent.com/90618618/162395103-0e021eb5-3269-4055-971a-e2b24f5fa701.png)

used in 

```
@NgModule({
  imports: [
    BrowserModule,
    UpgradeModule,
    HttpClientModule
  ],
  providers: [
    TestService
  ]
})
```

and this configuration in webpack :

`loader: "swc-loader", options: {
								jsc: {
									externalHelpers: true,
									parser: {
										syntax: "typescript",
                                        decorators: true
									},
                                    transform: {
                                        legacyDecorator: true,
                                        decoratorMetadata: true
                                    }
								}
							}`

but during compilation I get the following error : 

![immagine](https://user-images.githubusercontent.com/90618618/162396265-67be683f-371b-4687-a07d-b5f4f3a631d1.png)

What identifies the error **_dec is not a function**?

Additional NOTES

I compile the file **test.service.ts** with **npx swc** :

import * as swcHelpers from "@swc/helpers";
import regeneratorRuntime from "regenerator-runtime";
import * as angular from 'angular';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
var _class;
var _dec = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:paramtypes", [
    typeof HttpClient === "undefined" ? Object : HttpClient
]), _dec1 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", Function), _dec2 = function _dec2(target, key) {
    return Inject(HttpClient)(target, undefined, 0);
}, _dec3 = Injectable();
export var TestService = _class = _dec3(_class = _dec2(_class = _dec1(_class = _dec((_class = /*#__PURE__*/ function() {
    "use strict";
    function TestService(http) {
        swcHelpers.classCallCheck(this, TestService);
        this.http = http;
    }
    var _proto = TestService.prototype;
    _proto.getData = function getData() {
        var _this = this;
        return swcHelpers.asyncToGenerator(regeneratorRuntime.mark(function _callee() {
            var opts, response;
            return regeneratorRuntime.wrap(function _callee$(_ctx) {
                while(1)switch(_ctx.prev = _ctx.next){
                    case 0:
                        opts = {
                            params: new HttpParams({
                                fromString: "test=1"
                            })
                        };
                        _ctx.next = 3;
                        return _this.http.get("https://service_test", opts);
                    case 3:
                        response = _ctx.sent;
                    case 4:
                    case "end":
                        return _ctx.stop();
                }
            }, _callee);
        }))();
    };
    return TestService;
}()) || _class) || _class) || _class) || _class) || _class;
angular.module("prova").service("TestService", TestService);

**Comment by pjurczynski** [comment]
I've come across the same issue but in jest (I try to use swc only for testing). I've fixed it by adding a reflect metadata polyfill
https://github.com/rbuckton/reflect-metadata
