### ISSUE TITLE
Generators don't maintain block scopes

### ISSUE THREAD

**Issue by kcirtaptrick** [swc-project/swc#4286]
### Describe the bug

Block scoped variables in generators are mutated out of scope, async code within generator has unexpected behavior.

### Input code

```typescript
console.log([
  ...(function* () {
    for (const i of [1, 2, 3]) {
      Promise.resolve().then(() => {
        console.log(`async: ${i}`);
      });
      yield i;
    }
  })(),
]);
```

### Config

```json
none
```

### Playground link

https://play.swc.rs/?version=1.2.164&code=H4sIAAAAAAAAA03NwQoCIRAG4LtP8R86jCFCdSvqGfa%2BLGyYlmAOqAXL4rtnVEu3mfk%2F%2FjEcMwerA1%2BpF4DWmtwjmuI5rkESczsCjhPINFvgwQ79RmGrsBt%2BAOgS3322OtlW%2BLQkdbnZSK3ieFoQYP4ejuc8RbPHavZ1lIevqcs0eRsu8J%2B1indEUomhgRflW74FuAAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

```
[ 1, 2, 3 ]
async: 1
async: 2
async: 3
```
variables should maintain their scope and not be mutated by future scopes for async references

### Actual behavior

```
[ 1, 2, 3 ]
async: 3
async: 3
async: 3
```
`i` was mutated, causing all async references to become `3`

### Version

1.2.164

**Comment by miemiewang** [comment]
I have same problems, When will this bug be fixed

**Comment by zhusiyi111** [comment]
When will this problem be solved?

**Comment by kdy1** [comment]
@zhusiyi111 Are you trying to annoy me?
I'm really curous. Why do you need to left a comment?
Do you think ldfting a such comment will have any positive effect?


You are sending a spam mail to all watchers, who are much more likely to have interest on project.
