### ISSUE TITLE
"Unexpected token `div`. Expected jsx identifier" occurs when using ternary expressions

### ISSUE THREAD

**Issue by Clarkkkk** [swc-project/swc#4296]
### Describe the bug

Note that besides #2237 and #3661, the error still occur in this specific use case:
1. Use `Array.prototype.map` and implicitly return the expression with parentheses (or no parentheses) 
2. Use a ternary expression inside
3. Specify the return type of the function prop of the component inside that ternary expression

### Input code

```typescript
import React from 'react';

interface ListProps {
  callback: () => void
}

const SomeList = ({ callback }: ListProps) => {
  callback()

  return <div />
}

const list = [0]

const MyComponent = (): JSX.Element => {
  return <div>
    {
      list.map(() => (
        true ? <SomeList callback={ (): void => console.log('do something')} /> : <div />
      ))
    }
    </div>
}
```

### Config

```json
{
  "jsc": {
    "transform": {
      "hidden": {
        "jest": true
      }
    },
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.165&code=H4sIAAAAAAAAA1WPP0%2FDMBDF90j5Dm%2BLvaTMIQkD6oJAQnRBQgzGcYtV%2F4kctxKK8t3JxbShXnz3dO9397TtfYh4U0JG7IO3KALVxX2e5Zl2UYW9kArPeoivwfcDxjwDpDDmS8hjBcbRtDh73eXZRB7p3RCx81aRBw3YeB3HVK2kxXhDY5wAQFDxFBzqTp%2BxaW%2B4JjE%2F7j5X7eXn0c8xnHLLOl7hafdebo2yi%2FK35B%2B0pR5JpkfQ0oqepTDsogMxnBQeUF%2FjXE5txmUR5SYLHeKNKo0%2FsKLzGOb5%2BK3doeDTHAHVGiaBOU%2FVlL56k86a21%2BWEFrIkgEAAA%3D%3D&config=H4sIAAAAAAAAAzWLMQrAIBAE%2F3K1RbD0NxIviUKM3G1AEf8eLdLtMLOdku7kOkF81uORe8EVQ%2BC8VmIFOcjLYxiCl5MnE6vdrCVDxYuyrFJbhq%2FToRXWXWLB9ND638cHz112XWwAAAA%3D

### Expected behavior

Compiled as expected

### Actual behavior

Here is the output of the playground:
```
  [31mx[0m Unexpected token `div`. Expected jsx identifier
    ,-[[36;1;4minput.tsx[0m:16:3]
 [2m16[0m | return <div>
    : [31;1m        ^^^[0m
    `----


Caused by:
    0: failed to process input file
    1: failed to process input file
    2: Syntax Error
```

### Version

1.2.165

**Comment by Clarkkkk** [comment]
@kdy1 Is it supposed to be fixed in v1.2.169? Because I saw the [same error](https://play.swc.rs/?version=1.2.169&code=H4sIAAAAAAAAA1WPP0%2FDMBDF90j5Dm%2BLvaTMIQkD6oJAQnRBQgzGcYtV%2F4kctxKK8t3JxbShXnz3dO9397TtfYh4U0JG7IO3KALVxX2e5Zl2UYW9kArPeoivwfcDxjwDpDDmS8hjBcbRtDh73eXZRB7p3RCx81aRBw3YeB3HVK2kxXhDY5wAQFDxFBzqTp%2BxaW%2B4JjE%2F7j5X7eXn0c8xnHLLOl7hafdebo2yi%2FK35B%2B0pR5JpkfQ0oqepTDsogMxnBQeUF%2FjXE5txmUR5SYLHeKNKo0%2FsKLzGOb5%2BK3doeDTHAHVGiaBOU%2FVlL56k86a21%2BWEFrIkgEAAA%3D%3D&config=H4sIAAAAAAAAAzWLMQrAIBAE%2F3K1RbD0NxIviUKM3G1AEf8eLdLtMLOdku7kOkF81uORe8EVQ%2BC8VmIFOcjLYxiCl5MnE6vdrCVDxYuyrFJbhq%2FToRXWXWLB9ND638cHz112XWwAAAA%3D) in this version.

**Comment by PerfectionVR** [comment]
If it helps, if you revert to 1.2.160 it works.

**Comment by Clarkkkk** [comment]
> If it helps, if you revert to 1.2.160 it works.

Thanks! Really good to know.

**Comment by kdy1** [comment]
It was issue of wasm build, and it works properly for node binaries
