### ISSUE TITLE
swc hangs with paths and handlebars

### ISSUE THREAD

**Issue by andrewda** [swc-project/swc#4298]
### Describe the bug

I'm trying to switch a Node.js webpack/tsc project over to `swc`. I've defined several paths in my `.swcrc`:

```json-with-comments
// ...
    "baseUrl": ".",
    "paths": {
      "@app/common": [
        "dist/common/src"
      ],
      "@app/common/*": [
        "dist/common/src/*"
      ]
    },
// ...
```

Then, when compiling the code below with `swc`, the compiler hangs until I quit it with ctrl-c. 

```
$ SWC_DEBUG=1 swc --sync test.ts

```

Removing the handlebars dependency from the code below or removing the paths from the `.swcrc` allows the compilation to complete successfully. 

### Input code

```typescript
import fs from 'fs';
import hbs from 'handlebars';
import { join } from 'path';

const path = join(__dirname, 'test.hbs');

const a = hbs.compile(fs.readFileSync(path, 'utf8'));

console.log(path);
console.log(a);
```

### Config

```json
{
  "sourceMaps": true,
  "module": {
    "type": "commonjs",
    "strict": true
  },
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "baseUrl": ".",
    "paths": {
      "@app/common": [
        "dist/common/src"
      ],
      "@app/common/*": [
        "dist/common/src/*"
      ]
    },
    "keepClassNames": true
  }
}
```

### Expected behavior

`swc` should not hang. I would at least expect an error message if something is wrong with my configuration.

### Actual behavior

`swc` hangs indefinitely.

### Version

```
@swc/cli: 0.1.57
@swc/core: 1.2.165
```

**Comment by RiESAEX** [comment]
seems duplicate of #3272

**Comment by andrewda** [comment]
Yes indeed, thanks @RiESAEX !
