### ISSUE TITLE
Bundler

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#43]
# Status

 - [x] Bundling of es6 modules.
    - [x] normal import
    - [x] aliased import
    - [ ] namespaced import
       - [x] de-globing (& tree shaking)
       - [ ] namespaced import with dynamic key
 - [x] Tree shaking.
 - [x] `Resolve` /  Load` trait for extensibility
 - [ ] Chunking
 - [ ] Dynamic imports
    - [x] Loading
 - [ ] swc integration
    - [x] Simple optimizations
    - [x] Transform
    - [ ] Optimize helpers (remove duplicate)
    - [ ] .swcrc integration
 - [ ] "esnext" in package.json
 - [ ] `spack.config.js`

This is a very hard part. I'm considering moving the source code of node-swc to this repository.

 - [ ] codegen: Multiple SourceFile

This is required to create the correct source map.

 - [ ] Bundling of non-js assets

Need to determine plugin api.

**Comment by TheLarkInn** [comment]
Maybe we can work to take the most time intensive pieces of existing bundlers and avoid overlapping work :) <3 webpack team :)

**Comment by anru** [comment]
@kdy1 btw, there is https://pax.js.org/ for that purpose

**Comment by kdy1** [comment]
@anru I were porting it, but I stuck at api design.

At now, I don't have a clear idea about plugin api.

**Comment by LuoZijun** [comment]
@kdy1 

Note: The `pax` work with `--es-syntax-everywhere` option should be define `process.env` object.

```bash
px --es-syntax-everywhere in.js out.js
```

**Comment by TheLarkInn** [comment]
@kdy1 if you have intention to make a bundler, our team would be happy to share our learnings and design from webpack if you find it valuable. Feel free and reach out!!!!

**Comment by kdy1** [comment]
I used (and tried) many build tools, but I doubt that there is a clear winner. So I want to hear various opinions about the bundlers.

I want to determine the plugin api. Interop with javascript from rust is a very hard task, so I want to write it once.

---

Can anyone here help me determining api related to the plugins? Any opinion is welcome.

I think important parts of plugin api are

 - When to run

I'm considering something like a loader from webpack.

 - What should a plugin responsible for

I have no idea.

**Comment by nick-at-hawkfish** [comment]
In my opinion, Rollup's plugin architecture and ease-of-use is much better than Webpack. I'd suggest using Rollup as inspiration on how to write a solid plugin system. See https://rollupjs.org/guide/en/#plugins-overview

**Comment by wldcordeiro** [comment]
> In my opinion, Rollup's plugin architecture and ease-of-use is much better than Webpack. I'd suggest using Rollup as inspiration on how to write a solid plugin system. See https://rollupjs.org/guide/en/#plugins-overview

I like this suggestion as well! I do think the two serve slightly different usecases (basically libraries vs apps) primarily so perhaps building a tool that is able to work in the two modes maybe hard. I do find rollup to be an easier tool to configure and use though with its architecture so totally a better inspiration there!

**Comment by kdy1** [comment]
@nick-at-hawkfish @wldcordeiro Thank you guys for opinions. I really need some, but it is very hard to hear from real users.

**Comment by wldcordeiro** [comment]
This could be a fun learning opportunity contributing for Rust. Thanks for the responsiveness. I'm testing this tool out with some projects and see lots of potential. 😄

**Comment by jrop** [comment]
@kdy1 You really should take @TheLarkInn up on his offer to share learnings 😄 He is on the Webpack core team, after all!
