### ISSUE TITLE
Expose a high level Rust API/crate(lib.rs) that node-swc uses via neon bindings

### ISSUE THREAD

**Issue by izelnakri** [swc-project/swc#431]
Hi there, thank you for your amazing work!

Finally I've some free time to experiment with swc and I've made significant progress lately on porting my ember-cli alternative(mber) to rust: https://github.com/izelnakri/mber-rust

I see that you've a high-level node.js API via @swc/core(node-swc repo), however after investigating the internals I found that it includes lots of custom rust code inside the neon binding to achieve that: https://github.com/swc-project/node-swc/blob/master/native/src/lib.rs#L154

Can we import the Compiler from a rust crate instead? Existing crates are very low-level. The proposed crate could provide a even higher-level abstraction to make it possible to do batch transpilations in Rust. I'm currently trying to achieve that to remove serialization/deserialization cost of neon per each JS file Im transpiling:

Proposed API:

```rust
use swc;

// let options_hashmap_or_struct = // create a struct or hashmap

assert_eq!(swc::transform(
"class Foo {}
 class Bar extends Foo {}", 
options_hashmap_or_struct
), "define('a', ['@swc/helpers'], function(swcHelpers) { ... }")

```

**Comment by kdy1** [comment]
@izelnakri Actually, compiler related code lives in node-swc just because it reduces number of commit. But if you want compiler in swc, I'm willing to move compilers back into swc repository. I'll do it when I have some time.

**Comment by izelnakri** [comment]
Thank you! I'd really appreciate it. Can contribute back with writing the necessary documentation on docs.rs if necessary. Thanks again!

**Comment by kdy1** [comment]
@izelnakri I'm sorry for delay. I have midterm exam next week.

I'll move high-level codes to swc repository from node-swc after publishing node-swc@1.0.46, which is very important for users who use node@12.

**Comment by kdy1** [comment]
@izelnakri I moved apis back into the swc repository. 

```rust
extern crate swc;

use std::{path::Path, sync::Arc};
use swc::{
    common::{
        errors::{ColorConfig, Handler},
        SourceMap,
    },
    config::Options,
};

fn main() {
    let cm = Arc::<SourceMap>::default();
    let handler = Handler::with_tty_emitter(ColorConfig::Auto, true, false, Some(cm.clone()));
    let c = swc::Compiler::new(cm.clone(), handler);

    let fm = cm
        .load_file(Path::new("foo.js"))
        .expect("failed to load file");

    c.process_js_file(
        fm,
        Options {
            ..Default::default()
        },
    );
}
```


I think an api to add custom transform is required, right? So I want to hear about how are you going to use swc.

**Comment by izelnakri** [comment]
Hi Dong, thank you for all this work! This would certainly help, however I would like to simplify the API further and/or have few higher level changes as well. 

Would you be available for a quick chat? Do you use discord?

In my own cli I have a wrapper that will wrap the swc high-level API and transpile file contents per file basis: https://github.com/izelnakri/mber-rust/blob/master/src/transpilers/convert_es_module.rs#L19

Later we(or I :)) can implement the necessary babel addons for babel parity feature-wise.

**Comment by kdy1** [comment]
My discord username is 강동윤#1866. Can you chat now?

**Comment by kdy1** [comment]
I'm going to close the issue. If you have an idea about better api, please file a new issue.

**Comment by Tarnadas** [comment]
Hey @kdy1,
please take a look at the feature request I made in the wasm-bindgen project.
I cannot seem to find swc/core on crates.io.
Do I need to use it as a git dependency?

**Comment by kdy1** [comment]
@Tarnadas I didn't publish it because I think there's no need to depend on swc itself. 
Can you tell me which crate you need?

 If you really need all of swc, I'll publish swc to crates.io

**Comment by kdy1** [comment]
@Tarnadas Besides, if you need any help using swc, please feel free to ping me on github or slack

**Comment by Tarnadas** [comment]
I have not yet looked deep into it. I assume I would need all the functionalities of swc to implement the feature request, so that basically the example you provided can be implemented.

I will let you know when it gets accepted or rejected.
