### ISSUE TITLE
Better versioning error message between plugin - host

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#4333]
### Describe the feature

We do allow breaking changes without major version bump in experimental phase, but still general ergonomics for the error itself is not great. Error message like 

```
Error: failed to handle: failed to invoke plugin: failed to invoke `/the/path/to/plugin.wasm`

Caused by:
    Incompatible Export Type

Stack backtrace:
  0: _rust_eh_personality
  1: _wasmer_vm_f64_nearest
```

is cryptic enough to guess if it comes from versioning difference between host to plugin. We may need to have runtime validation logic for compatible version and raise proper error message instead.

### Additional context

https://github.com/swc-project/swc/discussions/3540#discussioncomment-2568463=

**Comment by jantimon** [comment]
Big +1

We ran into this issue and are now searching which dependency version we have to use for our wasm plugin. Currently we are using `swc_plugin = "0.27.0"` and `swc = "0.164.0"`

```
Panic: PanicInfo { payload: Any { .. }, message: Some(failed to invoke plugin: failed to invoke `/path/to/my.wasm` as js transform plugin at /path/to/my.wasm

Caused by:
    Incompatible Export Type), location: Location { file: "/Users/jannicklas/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.164.0/src/plugin.rs", line: 207, col: 14 }, can_unwind: true }
```
