### ISSUE TITLE
error: Expected unicode escape in v1.2.111 and later

### ISSUE THREAD

**Issue by m-allanson** [swc-project/swc#4348]
### Describe the bug

swc errors when parsing the below input. I discovered this when updating from an older version of swc which successfully handles the input.

### Input code

```typescript
const CodeBlock = () => <codeblock codestring="<script type=\"module\" src=\"myFile.js\"></script>"></codeblock>
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.111&code=H4sIAAAAAAAAA0vOzysuUXDOT0l1yslPzlawVdDQVLC1U7BJBgolgYVArOKSosy8dFslm%2BLkosyCEoWSyoJU2xil3PyU0pzUGCWF4qJkELfSLTMnVS%2BrOEbJzkYfotQOxIQbZgcAFnTzeXAAAAA%3D&config=H4sIAAAAAAAAA0WOuw6DMAxF%2F8VzBsTQgbkrH2EFg1LlJdtIjRD%2F3oQGsVnX5z4O%2BIiF6YCMLMTtkhIVvzAB2YBi2WUFU7EqKe90GlDkjbQRMg7jUL8%2BJSGYVvRCBoKLbi0ty6aQmUSeF8bN32SLYoyyJg6N9rShLW%2ByiVET%2F%2FsMLLcwk%2BKCin1ItYe07C3uAC2ZrkUvOJ8FvdXJ3MHL%2BAP%2FY77A9QAAAA%3D%3D

### Expected behavior

In swc v1.2.107 and earlier, the input is compiled to:

```js
const CodeBlock = ()=>React.createElement("codeblock", {
        codestring: "<script type=\\\"module\\\" src=\\\"myFile.js\\\"></script>"
    })
;
```

### Actual behavior

In swc v.1.2.111 and later, swc throws the following error:

```
error: Expected unicode escape
 --> input.jsx:1:69
  |
1 | const CodeBlock = () => <codeblock codestring="<script type=\"module\" src=\"myFile.js\"></script>"></codeblock>
  |                                                                     ^



Caused by:
    0: failed to process js file
    1: failed to process js file
    2: Syntax Error
``` 

### Version

1.2.111

**Comment by kdy1** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/29931815/163712401-203081cd-f5de-41e5-b6c9-b40465deb0dc.png">
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/29931815/163712407-03891b08-b2b1-4c0b-81dd-9a0a97c747ca.png">

I found that this is not a bug.
The input is wrong
