### ISSUE TITLE
Retrieve tokens from parser

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#436]
Hello. Thanks for this great library!

**Question**

Is there a way to get the tokens from the result of running a `Parser` struct's `parse_script()/parse_module()` methods? For example, say I have a function declaration... is there any way to tell the body's opening brace's location? I could manually parse and figure this out from the text, but it would be nice if there was a solution in the library.

It seems like I could maybe get it from `parser.input`, but that's private and would using that mean the lexer would run over the file twice? I would also temporarily just try creating my own `Lexer` object, but seems like that's private too?

**How babel does it**

FWIW, and you probably know this, Babel has a tokens array that can be returned on the source file level (seems to work similar to how the comments work in this library). I'm not sure, but if this doesn't exist in the library then an easy way to implement it would probably be along those same lines. (Or maybe just a way to hook into the lexer? I'm not sure)

**Side question and my use case**

The reason I'm asking is because I am investigating using this library to write a code formatter. I have a JS/TS formatter implementation using babel [here](https://github.com/dsherret/dprint) and as part of a project for learning Rust I've started converting over some of this code to Rust. I was thinking it would be fun to port over the JS and TS parsing code too. Do you know of any blockers I might encounter while working on this? Thanks!

**Comment by kdy1** [comment]
@dsherret I've started working on this. I will

 - Move `Input` trait to swc_common
 - Make lexer public
 - Provide a way to create `Input` from tokens.

**Comment by dsherret** [comment]
@kdy1 oh that is awesome. Thank you so much!

Yes, based on my research I think this is all that I'm missing to start work on this :)

**Comment by kdy1** [comment]
Fixed and published
 - swc_common@0.3.2 (Input trait)
 - swc_ecma_paresr@0.11.0

and additionally

 - swc_ecma_codegen@0.7.3
 - swc_ecma_transforms@0.1.3

**Comment by dsherret** [comment]
@kdy1 this is amazing! Thanks so much @kdy1!

I'm excited to get using this. I'll probably start in a couple of days.
