### ISSUE TITLE
Namespaces are not exported properly

### ISSUE THREAD

**Issue by hampustagerud** [swc-project/swc#4393]
### Describe the bug

Hello! Thank you for all the hard work put into this project! 😄

I am trying to replace babel with swc in a webpack project but I have stumbled upon an issue regarding namespaces:

### Input code

```typescript
namespace foo {
  export const bar = 0;
}

export { foo };
```

### Playground link

https://play.swc.rs/?version=1.2.170&code=H4sIAAAAAAAAA8tLzE0tLkhMTlVIy89XqOZSAILUioL8ohKF5Py84hKFpMQiBVsFA2uuWi4uqEQ1WG2tNQCBHekmPAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

The typescript compiler produces:

```javascript
var foo;
(function (foo) {
    foo.bar = 0;
})(foo || (foo = {}));
export { foo };
```

[Typescript playground](https://www.typescriptlang.org/play?#code/HYQwtgpgzgDiDGEAEAzA9mpBvAUE-SEAHjGgE4AuS8awUVARiGUgLxIAMA3DgL445ipStlQYkvLkiA)

### Actual behavior

The generated code looks like

```javascript
var foo;
(function(foo1) {
    var bar = foo1.bar = 0;
})(foo || (foo = {}));
export { };
```
so when the code is running after bundling everything exported like this becomes undefined.

### Version

latest

### Additional context

I tried cloning the repo and started looking into it but it will probably take more time for me to understand where to fix it than it will take for someone experienced to actually fix it 🙂 I managed to add a test to confirm it wasn't working in master but then I wasn't sure if it's a parser issue or a codegen issue 😅 Hopefully there can be a PR that I can learn from!

**Comment by DarkRoku12** [comment]
Related issue: https://github.com/swc-project/swc/issues/2669

**Comment by Bird-mw** [comment]
I am experiencing similar problems, when an exported namespace is used within the same file it becomes undefined.

I have tested different versions of @swc/core and it seems to only happen after version 1.2.172, as it works fine in 1.2.171
