### ISSUE TITLE
pure_funcs is not working when minify

### ISSUE THREAD

**Issue by ClarkXia** [swc-project/swc#4396]
### Describe the bug

pure_funcs is not working when setup config for minify code

### Input code

```typescript
const { code } = await swc.minify(`console.log('__LOG__');console.warn('__WARN__');`, {
  compress: { pure_funcs: ['console.log']}
})
```

### Expected behavior

remove code of `console.log('__LOG__')`

### Version

1.2.170

**Comment by kdy1** [comment]
It's not implemented yet
