### ISSUE TITLE
Spreading async generators inside of another async generator produces an error

### ISSUE THREAD

**Issue by AgentEnder** [swc-project/swc#4405]
## Current Behavior

When using `yield* asyncGenerator()`, swc-node throws stating that the intermediate value was not an iterator

## Expected Behavior

swc-node produces output that runs in the same manner as code built with`tsc`

## Example

Consider the below code:

> generator.ts
```typescript
async function* asyncGenerator(
) {
  for (let i = 5; i < 10; i++) {
    yield new Promise((res) => setTimeout(() => res({ success: true }), 5));
  }
  yield { success: true };
}

export default async function* execute(
) {
  yield* asyncGenerator();
}
```

> consumer.js
```javascript
const swcNode = require("@swc-node/register/register");

(async () => {
    swcNode.register();
    const generator = require("./generator").default;
    for await (const p of generator()) {
        console.log(await p);
    }
})();
```

This will throw with `TypeError: yield* (intermediate value) is not iterable`

## Reproduction
See: https://github.com/AgentEnder/swc-node-async-generator

**Comment by kdy1** [comment]
I investigated this and seems like babel helper is changed a lot.
So this issue requires analyzing babel helpers

**Comment by AgentEnder** [comment]
Wow! Excellent speed @kdy1 , do you know when the fix should be released?

**Comment by kdy1** [comment]
I triggered the action for publishing.
https://github.com/swc-project/swc/actions/runs/2237162292
