### ISSUE TITLE
Typescript 3.7

### ISSUE THREAD

**Issue by Diokuz** [swc-project/swc#442]
Hey, another thank you for swc project!

Could you provide any plans for typescript 3.7 support?

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

Optional chaining is supercool, but we cannot use it for now :(

**Comment by kdy1** [comment]
This seems like a must. I'll implement it soon.

**Comment by vislogurov** [comment]
I join the issue starter above. There are several business projects using the latest TypeScript and idle without swc( Appeal to your mind)))

**Comment by kdy1** [comment]
@vislogurov I'm sorry, but what do you mean by idle? English is not my first language and I cannot understand it.

Anyway, I'll implement this feture by Friday at least.

**Comment by vislogurov** [comment]
@kdy1 idle === `work without purpose or effect; pointless.` Great to hear about soon implementation)  👍

**Comment by kdy1** [comment]
I've implemented this feature, and it is available with swc@v1.0.49+
