### ISSUE TITLE
React fast refresh transform not being applied to React class components

### ISSUE THREAD

**Issue by chrismcv** [swc-project/swc#4431]
### Describe the bug

Enabled `transform.react.refresh` in `.swcrc` and expecting to see the output annotated with $RefreshSig. 

### Input code

```typescript
import React from "react";

class Simple extends React.Component {
  render() {
    return <div>hi</div>;
  }
}

export default Simple;
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true,
      "react": {
        "refresh": true
      }
    },
    "keepClassNames": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.171&code=H4sIAAAAAAAAAyWLQQ5AMBRE9016h9lhwwGIjRvgAg1fNNFWfj%2BRiLvTWM28vBnr9sCCnswkWDg4ZJx6Vmul1bSZGDFYt280UhTQJeTn%2BO%2FLLnxvT15wawXwp4jz4qfEcrBHM9uzXW1TpayTerR6XkQ1DJl5AAAA&config=H4sIAAAAAAAAA2WOQQrDMAwE%2FyJy9AtyLqWXXNIXCEdJXRzbSDIkhP69NsQlUJ20ml2xB7zFQn8AbUoc0D%2FIJ2KBXjmTgYQsxNUge1DcoAfdE4lllxQMqGzNOpGNjBpb%2BFMoY5A58lofeFrQ7rfm%2BosNpDihYgNMaLUGmWYmeV3WkZZSpBt%2FqgPT2NNdWVGV0er0nr0vMqDmQs6OZQw4GeKUPZ23L9BAlnQUAQAA

### Expected behavior

Code should be annotated with 

```
$RefreshReg$(_c, "Simple");
```

### Actual behavior

No code output,... also same on cli.
https://github.com/chrismcv/swc-repro

### Version

1.2.171

### Additional context

This is the result of me digging into vite HMR not working with https://github.com/iheyunfei/vite-on-swc

**Comment by Austaras** [comment]
`react refresh` is, by design, applied only to hooks and function components.
