### ISSUE TITLE
pnpm workspaces + spack node_module resolution error

### ISSUE THREAD

**Issue by hevans90** [swc-project/swc#4443]
### Describe the bug

I have a simple `pnpm` workspaces setup where I have a root `package.json`/`pnpm-lock.yaml` and a `packages` directory with some `npm` packages.

I wanted to try out `swpack` to bundle the code in one of my packages, and copied your example here: https://github.com/swc-project/cli/tree/master/examples/spack-basic

But this is what happens when I try it:

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/12142999/165279558-e532251a-5037-48e5-b529-854a20403bf4.png">

Here's my config, and proof there is an `index.ts` file at the root of the package:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/12142999/165279492-cf3bc39f-1426-4ad0-9aa7-86dce430e9d2.png">

Any ideas?

### Expected behavior

An outputted bundle.

### Version

@swc/cli: 0.1.57 @swc/core: 1.2.172

**Comment by kwonoj** [comment]
Title is bit misleading https://github.com/swc-project/swc/issues/3247 is tracking. pnpm / or alternative pkg mgr resolution is not yet supported.

**Comment by RiESAEX** [comment]
I thought swc support pnpm after our module resolver follow soft links.

**Comment by kwonoj** [comment]
> I thought swc support pnpm after our module resolver follow soft links.

I thought it's partially supported? like _some_ cases it may not work and we don't guarantee  pnpm resolution as officially supported.
