### ISSUE TITLE
`collapse_vars` generated unexpected code

### ISSUE THREAD

**Issue by sapjax** [swc-project/swc#4444]
### Describe the bug

```ts
const test = () => {
  let a = 0;
  let b = 0;
  let c = [1, 2, 3, 4, 5].map((i) => {
    a += i;
    b += i;
    return i;
  });
  return [a, b, c];
};

const [a, b, c] = test();
console.log("test", a, b, c);
```
which should print in the console:
```
"test",  15,  15,  [1, 2, 3, 4, 5] 
```

But after compiled, the code became ❌:
```js
var ref = function() {
    var a1 = 0;
    var b1 = 0;
    return {
        a: a1,
        b: b1,
        c: [
            1,
            2,
            3,
            4,
            5
        ].map(function(i) {
            return a1 += i, b1 += i, i;
        })
    };
}(), a = ref.a, b = ref.b, c = ref.c;
console.log('test', a, b, c);
```
which will print in the console:
```
"test",  0,  0,  [1, 2, 3, 4, 5] 
```
the values `0 0` should be `15 15`, the `a` and `b` value on the `e` object is determinate before `c` be calculated.

I found this is related to the `collapse_vars` options and this only happened when the `Env Targets` is enabled with empty or has `IE` include.

### Input code

```typescript
const test = () => {
    let a = 0
    let b = 0
    let c = [1, 2, 3, 4, 5].map(i => {
      a += i
      b += i
      return i
    })
    return { a, b, c }
  }
  const { a, b, c } = test()
  console.log('test', a, b, c)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": false,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": false,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": false,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": false,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": false,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": false,
        "typeofs": false,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": ""
  }
}
```

### Playground link

[https://play.swc.rs/?version=1.2.171&code=H4sIAAAAAAAAA1WO....](https://play.swc.rs/?version=1.2.171&code=H4sIAAAAAAAAA1WOwQqDMAyG7z7Ff7NlQdzmjvVFxEMrZQjVDldP4rubYrd1gQS%2BLyEJMPj5HRAsFwUhoVpsBTicDdDs6i%2BZPxqYuivhRrgTGsKjryb9EuNvBXjBRWFMYHJYbFiXOeEui8xt0ARDfGFnHfN8MvN8O74sZGp6Zyvnn6KMtqTPoDwAcIatCeAAAAA%3D&config=H4sIAAAAAAAAA22TS5LcIAyG78J6FplUJYs%2BQHZzBoo2wq2JDRQSPe3q8t0jbA%2FY7uzQxy%2F05Kk%2BqVOXp4omEaRyosmzeaiL4ikCdQkjqzfFJIhThlnOJvXAogD6%2BeP9l9wOIRCoizMDwZsa0aObyltdGGMConIWpzyCZ6o6k1L4auY1hAGMpzVOs7UhjZ6hh9TEXRgGEwn03aTqUcKZhBT8AWUGq2MKce%2FuLTIGL2aFFozVXbCtEosJOsY77ETyjog8SXJHaOGa%2B740cQ0NdzNkw00Fj6UZErWiW0Bi7bKnEzqmu7K11A2h0wk4J%2F8d7jOgP0r%2BAkiqgyHyZoQTdzKP2qWV%2FEeF3skweapUJh2rm4de6tOIrhVZEofECFWVwOYOSpFde32Dh3wJLWhwTlpenekLubvt0ipbGVyzpXVmF3419Wm1NlqW4QX%2Bkbx4P5ONj4ZvZ0bTeA3DyxMj8C3YFyyt4HCGSfb4Ec80ewvSabC7i0zF3P7caHxfF24uINhcwHPpyPIZf6u5fb7vNaGPTbgtpb8vPssXloyVmud%2FFPD73AUEAAA%3D)

### Expected behavior

the value of `a` and `b` should be `15`

### Actual behavior

the value of `a` and `b` are `0`

### Version

1.2.171

### Additional context

I also create an issue in the Next.js repo earlier https://github.com/vercel/next.js/issues/36472 
seems it should be here

**Comment by kdy1** [comment]
Thank you so much for reducing the input.
Actually reducing test case is much harder than fixing it
