### ISSUE TITLE
exclude in .swcrc config

### ISSUE THREAD

**Issue by maxlamaison** [swc-project/swc#4454]
### Describe the bug

Hello, 

We are currently trying to exclude files from our compilation. But the `exclude` option does not seem to work.

We are launching this command: `swc src -d dist --config-file .swcrc`

we've also tried this one with the ignore tag: 

`swc src -d dist --config-file .swcrc --ignore src/test/**`.

It throws this in both cases (but somehow manages to compile the other files): 

```
Caused by:
    stream did not contain valid UTF-8
Successfully compiled: 127 files with swc (71.89ms)
Failed to compile 1 file with swc.
Error: Failed to compile:
src/test/fixtures/video.ts
    at initialCompilation (/Users/max/Documents/corporate/rendering/node_modules/@swc/cli/lib/swc/dir.js:172:19)
    at async dir (/Users/max/Documents/corporate/rendering/node_modules/@swc/cli/lib/swc/dir.js:16:5)
```

This is expected behavior since `video.ts` is a MPEG-TS file.

### Config

```json
{
  "exclude": ["src\/after\/.*", "src\/test\/.*"],
  "jsc": {
    "baseUrl": "./",
    "keepClassNames": true,
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    },
    "target": "es2022"
  },
  "module": {
    "strict": true,
    "type": "commonjs",

    // These are defaults.
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  },
  "sourceMaps": false
}
```

### Expected behavior

It excludes the folder we want to exclude from the compilation.

### Actual behavior

It ignores the exclude and/or --ignore tag.

### Version

@swc/core: 1.2.171, @swc/cli: 0.1.57

**Comment by maxlamaison** [comment]
Maybe this is not the best place for this issue? After digging a little bit, we found out that the node CLI does not use the ignore tag: [https://github.com/swc-project/cli/blob/master/src/swc/compile.ts](https://github.com/swc-project/cli/blob/master/src/swc/compile.ts) ?

**Comment by kwonoj** [comment]
the file under /swc is irrelevant if you're using `@swc/cli`. I just tried this locally and seeing exclusion works as expected. Please provide minimal reproducible repo.
