### ISSUE TITLE
Intra-statement comment interferes with function return value (again)

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#446]
### swc version
```
$ grep swc package.json
    "@swc/cli": "0.1.18",
    "@swc/core": "1.0.49,
    "swc-loader": "0.1.6",
```

### Input
```js
() => {
  return (
    // Interfering comment
    foo.bar || false
  );
};
```

### Output
```js
'use strict';
(function() {
    return // Interfering comment
foo.bar || false;
});
```

### Problem
The comment and newline is inserted between the `return` statement and the body of the return expression.

**Comment by kdy1** [comment]
I'll fix this in a fundamental way.

# The cause

 - Wrong transformation changes start position of span of member expression to not match with it of object of member expression
