### ISSUE TITLE
Private fields should not be accessible outside the class

### ISSUE THREAD

**Issue by 0xe** [swc-project/swc#4464]
### Describe the bug

Private fields should be checked for private access.

### Input code

```typescript
class Foo {
	#bar;

#privateMethod() {
    return 'hello world';
  }
}

var f = new Foo();
foo.#bar;
foo.#privateMethod();
```

### Config

```json
{
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "ecmascript"
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.172&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5uJUTkossubiUi4oyixLLEn1TS3JyE%2FR0ARKKQBBUWpJaVGegnpGak5OvkJ5flFOiro1UKaWq5aLqyyxSCFNwVYhL7UcZJqGpjVXWn6%2BHsREMAvNUGsARdmggXoAAAA%3D&config=H4sIAAAAAAAAAy3LMQ6DMBBE0btM7TaN78AhVpsNAmFs7awlEPLdA1GqXzz9CysV%2BUKIzxbIML6Q0MRp%2FgDPPeR4QItQfWmBMRJKfffNfuvZ7kJrKXVfiRtZu6tN0ogc3i1h4fQfPrLRxhe4j3L6eQAAAA%3D%3D

### Expected behavior

Syntax error that private name cannot be accessed.

Eg:

```
  x Illegal access to private class property.
    ,----
 14 | foo.#bar;
    : ^^^^^^^^
    `----

  x Illegal access to private class property.
    ,----
 15 | foo.#privateMethod();
    : ^^^^^^^^^^^^^^^^^^
    `----
```

### Actual behavior

Gets transpiled to the following:

```
...
var Foo = function Foo() {
    "use strict";
    _classCallCheck(this, Foo);
    _classPrivateMethodInit(this, _privateMethod);
    _classPrivateFieldInit(this, _bar, {
        writable: true,
        value: void 0
    });
};
var f = new Foo();
foo.#bar;
foo.#privateMethod();
```

### Version

1.2.160

**Comment by guybedford** [comment]
This PR seems to be breaking private properties generally:

```js
export class Pool {
  #x;
  constructor (x: number) {
    this.#x = x;
  }
}
```

```
  x Illegal access to private class property.
    ,-[src/common/pool.ts:22:5]
 22 | this.#x = x;
    : ^^^^^^^
    `----

Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (C:\Users\Guy\Projects\generator\node_modules\@swc\cli\lib\swc\util.js:113:15)
    at files (C:\Users\Guy\Projects\generator\node_modules\@swc\cli\lib\swc\file.js:173:18)    
    at async _default (C:\Users\Guy\Projects\generator\node_modules\@swc\cli\lib\swc\file.js:192:9)
```

**Comment by 0xe** [comment]
> This PR seems to be breaking private properties generally:
> 
> ```js
> export class Pool {
>   #x;
>   constructor (x: number) {
>     this.#x = x;
>   }
> }
> ```
> 
> ```
>   x Illegal access to private class property.
>     ,-[src/common/pool.ts:22:5]
>  22 | this.#x = x;
>     : ^^^^^^^
>     `----
> 
> Error: Failed to compile 1 file with swc.
>     at Object.assertCompilationResult (C:\Users\Guy\Projects\generator\node_modules\@swc\cli\lib\swc\util.js:113:15)
>     at files (C:\Users\Guy\Projects\generator\node_modules\@swc\cli\lib\swc\file.js:173:18)    
>     at async _default (C:\Users\Guy\Projects\generator\node_modules\@swc\cli\lib\swc\file.js:192:9)
> ```

This seems to be happening only with `typescript`. Equivalent JS transpiles correctly:

```
export class Pool {
  #x;
  constructor (x) {
    this.#x = x;
  }
}
```
