### ISSUE TITLE
Split ES minifier into multiple crates

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#4472]
Debug compile takes too much time, and it's slowing me down

**Comment by Austaras** [comment]
What's the difference between `Pure` and `Optimizer`?

**Comment by kdy1** [comment]
`Pure` is stateless and uses all cpu cores (via rayon)
`Optimizer` is stateful, and it uses the current thread.

Due to the perf issue, `Pure` does not use the analysis result currently.

**Comment by kdy1** [comment]
Closing as moving tests to a separate crate will be enough
