### ISSUE TITLE
Module build failed (from ./node_modules/swc-loader/src/index.js): TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by jelaxshan** [swc-project/swc#4484]
### Describe the bug

It seems there is a compatibility issue with swc-loader and webpack. I am currently using webpack: 4.46.0

### Expected behavior

No errors

### Version

"@swc/core": "^1.2.173",     "swc-loader": "^0.2.0",     "webpack": "^4.46.0",

**Comment by kdy1** [comment]
Use 0.1.15 instead

**Comment by slicejacob** [comment]
@kdy1 - I'm running into this same issue (I'm using the exact same versions that @jelaxshan is using). I tried your suggestion but run into the same issue. 

Do you have any other suggestions?

**Comment by cseoaneredondo** [comment]
I have the same problem, using the same versions. Could you help us please?

**Comment by jcerone-boom** [comment]
I'm also running into this issue. @kdy1 your fix worked. I'm using `@craco/craco": "^6.3.0"`. My swc specific versions were: 

```
"@swc/core": "^1.2.122",
"swc-loader": "^0.1.15"
```
