### ISSUE TITLE
Weird behavior for let and const inside for..in in an async function

### ISSUE THREAD

**Issue by juji** [swc-project/swc#4486]
### Describe the bug

`let` variable inside a `for ... in` loop is behaving incorrectly when the loop is halted by `await`

### Input code

```typescript
const obj = {
  a:'a',
  b:'b',
  c:'c',
  d:'d',
}

const wait = n => new Promise(r => setTimeout(r,n))

const action = async () => {

  for(let i in obj){

    // halt for a second
    await wait(1000)

    // this one is trouble
    wait(1000).then(() => console.log(i))
    
  }
  
  console.log('done')
}


action()
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.173&code=H4sIAAAAAAAAA01QwarCMBC8F%2FoPc0sCovVa8H3DO%2FgDaRptJGYhWRER%2F91sI%2BhlM8zODJN1lAqDpgsOePYdYEdl1UbQNKqpITcq19A8qlnQq%2B%2F6zq3euw1czQmHPyR%2Fx3%2BmayheZyGK52O4erqxzptkzNdmHQeqJtjySA7aiPwpe%2BBEWUfPCAhJupkPD%2Bx2WGxkUcDW9Jo1t41de8jQ%2B2EYzI%2BDl1BAyaM%2BnOk2Rd92X%2FWWF590KyH9KPptpLMOUlmkMl8y1nv8KNRck5X5nKTv2r90Jd4mYQJiWwEAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8eB2KM716ZumQlMe%2FNdDphaeuUuUDK%2FNBi5Zs2EhsYtrhcyaim0c4eMgxVLofUqeClzKcEWdRQcNHtbS7ZFHIR4EEcD%2F83hw6F9Llm0Km2rHdWQoonaDxDq%2BzwXvav%2FgXU82csuwAAAA%3D%3D

### Expected behavior

```
a
b
c
done
d
```

### Actual behavior

```
b
c
d
done
d
```

### Version

1.2.173

### Additional context

was run by node v14

**Comment by lausek** [comment]
Is this really unexpected behavior? The second `wait` does not block and it will surely dispatch the closure in the second loop iteration. At that time, `i` was already altered to contain `b`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures#creating_closures_in_loops_a_common_mistake

**Comment by juji** [comment]
yes, it is unexpected...

please try it in a nodejs...
`a` should be logged out... and `d` should be not be logged twice, since `i` was declared with `let`

please try it with other compilers like `babel` ... or no-compiler with `nodejs`

`let` should live inside bracket closure, therefore `a b c done d` is expected

**Comment by juji** [comment]
if you are really curious..

also try this:


```js
const action = async () => {

    // for(let i in obj){
    //   await wait(1000)
    //   wait(1000).then(() => console.log(i))
    // }

    for(let i=0;i<5;i++){
        await wait(1000)
        wait(1000).then(() => console.log(i))
    }

    console.log('done')

    /*
    expecting: 0 1 2 3 done 4
    got: 0 1 2 3 done 4
    */
  }

```


that turns out OKAY...

which is why, the behavior inside `for ... in` is unexpected
