### ISSUE TITLE
Tagged template literals should accept type arguments

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#4494]
### Describe the bug

Related to https://github.com/vercel/next.js/issues/36589

### Input code

```typescript
const Header = styled.header<{
  shrink: boolean;
  hidden: boolean;
  mobileView: boolean;
}>``
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": {
        "inline": 3,
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": false,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "sequences": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.174&code=H4sIAAAAAAAAA0vOzysuUfBITUxJLVKwVSguqcxJTdHLAPNtqrkUFIozijLzsq0UkvLzc1IT86yBQhmZKSmpeShCuflJmTmpYZmp5UjCtXYJCQBUilMZYAAAAA%3D%3D&config=H4sIAAAAAAAAA22TQZbbIAyG78I6i077Oos5QHc9A4%2BAcDS1hYtEJn55uXtF7GA76Q59%2FBLSD1zNJ3vzcTWjywy5rngicRfzYcAPjn3GUcxBZYqi6xluByMudyBVwt%2B%2Fvf3U7T4lhkVwMAMSxqkW82kYMzDXNVKPpKIfB6P5ZQASbiku5%2FSloeSi0TGlHhy9xNaxRRLoIK%2BpPvW9Gxns2eWWUQ92GTnRDhWBYMecxm06BRRMpGGDAVywPoV1poAZvOAZNiKtoyJibW4PAxxL11U%2F56Ph7PriBFp8ubuih7a8U0IWGwvxE1q6nRNnNA%2B6qDDaDFIyPTSfCWnnxR8A7bN3zOSGTf93HvUu9sr4HxVS1DuVqVG98LUrgk6Hs4ixTVi7hiwITZQhFA91Qr8WX%2BBuIMYAFmJUu1syf6H406YrmUZIse2rbS6ulzCH9vGo9rS%2Bgxf4S9uS7X0sfHByemY8DcfUv5QYQE4pvGB1QtIzzPqEL%2BMzLRRAfYaw2Shcw8UF%2BFuA%2FMNT%2FYmDo649vlsFKZQKrneH7l%2F03dzWLzkXQv696O51%2FgGRKYQUBgQAAA%3D%3D

### Expected behavior

It should compile, I think?

### Version

1.2.174

**Comment by magic-akari** [comment]
The `jsc.parser.syntax` should be `typescript`.

**Comment by kdy1** [comment]
Oh you are right, thanks!
