### ISSUE TITLE
Error when using reflect-metadata

### ISSUE THREAD

**Issue by kaname-png** [swc-project/swc#4528]
### Describe the bug

I was previously on version "1.2.174" of "@swc/core" and now I get this error.

It's not **@sapphire/decorators** fault because the code was working fine with the previous version I had installed of "@swc/core", and now that I upgrade to the latest version "1.2.177" I get this error.

It seems to have to do with reflect-metadata.

![image](https://user-images.githubusercontent.com/56084970/166839196-b865da01-5844-422c-8291-a4881623f9f4.png)

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "externalHelpers": false,
    "baseUrl": "./src",
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "paths": {
      "#arguments/*": ["arguments/*"],
      "#commands/*": ["commands/*"],
      "#listeners/*": ["listeners/*"],
      "#preconditions/*": ["preconditions/*"],
      "#decorators": ["lib/decorators/index.ts"],
      "#api/*": ["lib/api/*"],
      "#lib/*": ["lib/*"],
      "#root/*": ["*"]
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  },
  "module": {
    "type": "es6"
  }
}
```

### Expected behavior

A correct compilation and execution of the application.

### Actual behavior

An error when running the application that was previously missing when using the previous version of @swc/core.

### Version

1.2.177

**Comment by kdy1** [comment]
> It's not @sapphire/pieces fault because the code was working fine with the previous version I had installed of "@swc/core", and now that I upgrade to the latest version "1.2.177" I get this error.


This is wrong

**Comment by kdy1** [comment]
I aligned decorator pass to match one of tsc

**Comment by kdy1** [comment]
Also, please post input

**Comment by kaname-png** [comment]
Code of @sapphire/decorators
https://github.com/sapphiredev/utilities/blob/5ec1e44cc6a882afaa98a6d4e60fa47f3216f0a4/packages/decorators/src/utils.ts#L73

Basically that is the code I use from that package, which as I said before did not cause this error.

**Comment by kdy1** [comment]
No, I need the input to the compiler

**Comment by kaname-png** [comment]
@kdy1 This input?

```typescript
import { RouteOptions, Route } from @sapphire/plugin-api'';
import { ApplyOptions } from '@sapphire/decorators';
 

@ApplyOptions<RouteOptions>({ route: 'vote' })
export class VoteRoute extends Route {
 // Well, the error comes from the decorator, the rest of the code is just methods
}
```

**Comment by kdy1** [comment]
Yeah that's what I need for debugging

**Comment by xiaoyu-tamu** [comment]
experience the same issue when upgrade from 1.2.179 to 1.2.181

```
ERROR [Scheduler] TypeError: Cannot read properties of undefined (reading 'getAccounts')
```

**Comment by kdy1** [comment]
Do you have `tsconfig.json`?
If so, I think relevant options are `useDefineForClassFields`, `experimentalDecorators`, and `emitDecoratorMetadata `.

Alternatively the output for the file generated by `tsc` will work.

**Comment by kdy1** [comment]
I failed to reproduce this. 
I wrote the output at https://github.com/swc-project/swc/pull/4640 but it works without any issue.
Please provide more information so I can reproduce it
