### ISSUE TITLE
Import resolver should use original extension

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#4585]
Yes, of course, in the `src/main.ts` file this is actually an import of a `.js` file, but in the complied code it transforms the extension to `.ts`.

_Originally posted by @sgarnotel in https://github.com/swc-project/swc/issues/3576#issuecomment-1120881898_

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/6833bb9c6de3869660f79854f8a1247083c544d2/crates/swc_ecma_transforms_module/src/path.rs#L103-L113

We should accept original extension instead of `had_speicifer` (Name is wrong)

**Comment by MohamedLamineAllal** [comment]
The merge above does fix the problem for when we use a pattern like this:
```json
paths: {
    "@Core/*": "./src/Core/*"
}
```
and when we make an import like `import {} from '@Core/index.js'`

However,

there it doesn't if we set  

```json
    "paths": {
         "@Core": ["./src/Core/index.js"]
    },  
```

Work ok on typescript when `module: "nodenext"` is used. And the extension as `.js` for the type checking.

The first pattern may just be better to conform to esm. And we know from code directly. However, that may break creating aliases that map to a files directly (one to one). 

In the example above the output of the import 
```ts
import { logHello } from '@Core` 
```
is

```ts
import { logHello } from "@Core";
```

just the same.

While if we change the path config to a `.ts` extension 
```json
    "paths": {
         "@Core": ["./src/Core/index.ts"]
    },  
```

The output become:

```ts
import { logHello } from "./Core/index";
```

The extension is stripped. In tsconfig whatever u pick up a file ending with .ts or .js. Would be recognized correctly. And the type checking happens correctly and so does the emitting.

I understand that this can be an edge case. And can be worked around through the initial pattern. Many do handle their aliases mapping to a file directly.  And following the tsconfig way and support make sense. See if it's worth handling. Also if performance wise it make sense to opt out of handling it or the fix can be simple. I wanted to share the case. It's a no-blocker. So you know better.

**Comment by kdy1** [comment]
Please file another issue if there's a problem
