### ISSUE TITLE
Runtime automatic is not working

### ISSUE THREAD

**Issue by davbrito** [swc-project/swc#4606]
### Describe the bug

When updated from @swc/core from v1.2.177 to v1.2.181 the runtime automatic not qorks. It instead outputs with the classic runtime:

Before update:
![image](https://user-images.githubusercontent.com/39559632/167668064-7b3dc209-17b4-49e0-8461-9919f956cfc6.png)

After updating:
![image](https://user-images.githubusercontent.com/39559632/167666821-9a14d3c3-cd8c-4baa-9ee5-1f669f33f632.png)

### Config

```json
{
  "jsc": {
    "target": "es2017",
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dts": true,
      "dynamicImport": true
    },
    "externalHelpers": true
  },
  "sourceMaps": true,
  "module": {
    "type": "es6"
  }
}
```

### Expected behavior

The compiler should use the automatic runtime for jsx

### Actual behavior

It's generating the code with the classic runtime with `React.createElement`

### Version

1.2.181

**Comment by sannajammeh** [comment]
Getting the same.

**Comment by kdy1** [comment]
Seems like caused by #4575 
I'll work on this.

**Comment by kdy1** [comment]
It works with `.swcrc`

**Comment by davbrito** [comment]
It's worth noting that my build scripts look like this:
![image](https://user-images.githubusercontent.com/39559632/167768750-07ed2599-bb98-455b-b07d-44501020a89e.png)

**Comment by kdy1** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/29931815/167768888-c97f75d5-45c0-4d85-bcdb-3438db9d70c1.png">

Hmm..

Yeah, it's the most important thing I guess.

Seems like `jsc.transform.react` is overriden by the value provided by js-world invokation
