### ISSUE TITLE
First source mapping is missing

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#4608]
### Describe the bug

It looks like the first mapping in the source map is missing.

I'm seeing this problem both for the npm packages as well as with the crates

### Input code

```typescript
console.log();
console.log();
```

### Expected behavior

There's a mapping for `console -> console` on the first line as there is on the second line.

### Actual behavior

https://evanw.github.io/source-map-visualization/#NjQAY29uc29sZS5sb2coKTsKY29uc29sZS5sb2coKTsKCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LmpzLm1hcDE5MAB7InZlcnNpb24iOjMsInNvdXJjZXMiOlsiLi4vaW5kZXguanMiXSwic291cmNlc0NvbnRlbnQiOlsiY29uc29sZS5sb2coKTtcbmNvbnNvbGUubG9nKCk7XG4iXSwibmFtZXMiOlsibG9nIiwiY29uc29sZSJdLCJtYXBwaW5ncyI6Ik9BQU8sQ0FBQ0EsR0FBRyxFQUFFLENBQUM7QUFDZEMsT0FBTyxDQUFDRCxHQUFHLEVBQUUsQ0FBQyJ9

![Bildschirmfoto 2022-05-10 um 21 59 04](https://user-images.githubusercontent.com/4586894/167711871-d0bf7874-9810-44c8-910f-e8a68ff0b110.png)

### Version

1.2.181

**Comment by kdy1** [comment]
Seems like caused by a PR for removing dummy comments by @0xe 
I'll fix this issue by reserving `BytePos(0)` for dummy purpose and shifting all bytepos by 1

**Comment by mischnic** [comment]
Thanks! 

But https://github.com/swc-project/swc/commit/97808349a29d968866679813fc20b3ed0bbdfa74 has bumped the version on some packages that didn't actually get published.

This was correctly published: https://crates.io/crates/swc_ecma_ast/versions
This wasn't: https://crates.io/crates/swc/versions
This wasn't: https://crates.io/crates/swc_ecmascript/versions
