### ISSUE TITLE
#4458 (corejs version decision) is probably a breaking change

### ISSUE THREAD

**Issue by pan93412** [swc-project/swc#4612]
### Describe the bug

Before the #4458 has merged, we usually specify `corejs` version with only the major version:

    corejs: 3 // it will take the latest version which the user installed, for example: 3.22.5

However, we need to specify the exact version of `corejs` now after this commit:

    corejs: 3.22.5

And when we specify the version with only the major version, it seems that only takes the features in `3.0.0`:

    corejs: 3 // → 3.0.0

As the official guide had used `corejs: 3` in their example before this PR, without saying that is a discouraged pattern, I think it is a breaking change.

### Expected behavior

- `corejs: 3` should take the latest version of `3.x.x`.

### Actual behavior

- `corejs: 3` seems takes `3.0.0`.

### Version

1.2.181

**Comment by Austaras** [comment]
So basically, #1606

**Comment by zloirock** [comment]
Yes,  this is actually the expected behavior. But it should be [documented](https://swc.rs/docs/configuration/supported-browsers).

**Comment by SukkaW** [comment]
Fixed by https://github.com/swc-project/website/pull/163

cc @pan93412 @Austaras, @zloirock
