### ISSUE TITLE
Crashed on empty string when parsing

### ISSUE THREAD

**Issue by g-plane** [swc-project/swc#4635]
### Describe the bug

I'm calling parser API in my own Rust code. When I pass an empty string to parser, it will crash:

```
thread 'main' panicked at 'parser should not create an error with dummy span'
```

### Expected behavior

No crashes and AST should be constructed.

### Version

Unreleased

### Additional context

This bug was possibly introduced since #4616 with https://github.com/swc-project/swc/commit/67942d57319454a0304632d5d9e504e26a2c8068 .

**Comment by kdy1** [comment]
Are you using css crates?

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/5a53bb771d27a59b1e6c221ee03587068cee1f26/crates/swc_css_parser/src/error.rs#L25-L27

This is the cause.
I think this should be removed

**Comment by g-plane** [comment]
Yes, I'm using CSS parser.
