### ISSUE TITLE
Optional column mapping for codegenerator

### ISSUE THREAD

**Issue by h-a-n-a** [swc-project/swc#4637]
### Describe the feature

Currently, swc will map column to column on sourcemap generation, which results large sourcemaps. Personally, providing an option for column mapping would be better for performance-wise.

**Comment by h-a-n-a** [comment]
@kdy1 I'm very glad to implement this feature, is it ok for me to implement this now?

**Comment by h-a-n-a** [comment]
> Of course, I can provide some guidance if you want.

@kdy1 Sure! I'm very glad to have from your guidance before real coding

**Comment by kdy1** [comment]
Firstly, you can add a method with a default implementation to https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc_common/src/source_map.rs#L1312-L1332

In this way, we can add a flag to `swc_common` without breaking downstream crates.
I'm not sure about the name, but `fn emit_columns(&self) -> bool { true }` or similar will work.

---

Then to expose it to js world, we can add the implementation of function we added to https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc/src/lib.rs#L541-L587

You can add a field then return it from the new method (`emit_columns`)

---

After then, you can add a argument to `print`. https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc/src/lib.rs#L419-L431

It has too many args, but refactoring it is out of scope of this, so let's just add an argument to the last. 

---

`process_js_inner` calls `print`. https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc/src/lib.rs#L1070-L1115

You can add a field to `BuiltInput` for the new config, and pass it.
To do it, you will need to add an argument to the function for creating `BuiltInput`.
https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc/src/config/mod.rs#L267-L279

---

Finally, you can add a field to https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc/src/config/mod.rs#L765-L802

It can be something like `emit_sourcemap_columns: BoolConfig<true>`.
`BoolConfig` has a method named `into_bool` and you can use it while creating `BuiltInput`

**Comment by kdy1** [comment]
Ahh...
 I forgot the most important part.



You can add filtering logic for columns in https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc_common/src/source_map.rs#L1140-L1247

**Comment by h-a-n-a** [comment]
> Ahh... I forgot the most important part.
> 
> You can add filtering logic for columns in
> 
> https://github.com/swc-project/swc/blob/073ca87012842f4a2b8f2e93d57e0b09831c9641/crates/swc_common/src/source_map.rs#L1140-L1247

Thank you for the guidance, It helps a lot!
