### ISSUE TITLE
js plugin: Interfaces that extend imported types throw errors during transform calls that use plugins

### ISSUE THREAD

**Issue by therealparmesh** [swc-project/swc#4648]
### Describe the bug

I'm seeing the same issue as the person in the comments in https://github.com/swc-project/swc/issues/3827. It was requested that we make a new issue, so here's a new issue! 😄 

If I implement an empty plugin and use it within a `transformFile` call, I get an error:
```
Error: failed to deserialize Program

Caused by:
    missing field `expression`
```

However, things work if I downgrade to version 1.2.143.

### Input code

```typescript
import React from 'react';
import { Button } from 'somewhere';

export interface NewButtonProps extends React.ComponentProps<typeof Button> {}
```

### Expected behavior

No error.

### Version

1.2.182

### Additional context

Example code:
```js
class Plugin extends Visitor {
  visitTsType(e) {
    // the default behavior is to throw an error here, so we override it
    return e;
  }
}

const compiled = await transformFile(filePath, {
  jsc: {
    target: 'es2019',
    externalHelpers: true,
    parser: {
      syntax: 'typescript',
      tsx: true,
      dynamicImport: true,
    },
  },
  plugin: (m) => new Plugin().visitProgram(m),
  sourceMaps: true,
});
```

**Comment by amcoder** [comment]
I'd also love to know if it is intended that `visitTsType` is not implemented and if not what the intended implementation should be.

**Comment by kwonoj** [comment]
Closing as this is bit outdated - please use new wasm plugin instead. We are open to accept fix for the existing visitor but core team may not have time to look into.

**Comment by therealparmesh** [comment]
Sad to see this - use cases other than transpiling include AST traversal. Maybe we can reopen this in the future if there’s sufficient demand?

**Comment by kdy1** [comment]
@therealparmesh  No. `demand` does not matter at all here

**Comment by therealparmesh** [comment]
Just want to clarify something. By “demand” - I mean it in an economic sense (like in “supply and demand”) not as a command or something. Apologies for any confusion.

**Comment by kdy1** [comment]
I'm not confused at all. I mean the number of users want it does not matter at all.
