### ISSUE TITLE
Consider erroring/panicking when someone creates a source file with `BytePos(0)`

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#4656]
### Describe the feature

Since swc now treats `BytePos(0)` as a magic value (which as I've said, it should rather be `BytePos(u32::MAX)`), I think that `SourceFile::new(...)` and other similar structs should panic when someone creates a source file with `BytePos(0)`. This will prevent API consumers from accidentally creating source files with this position which could lead to bugs that cause confusion for them.

**Comment by kdy1** [comment]
I'll retry on this weekend
