### ISSUE TITLE
Exclude/ignore files

### ISSUE THREAD

**Issue by zxti** [swc-project/swc#466]
Let's say we have a bunch of 3rd party "vendor" JS included in our source directory.  I know that @swc/register ignores node_modules, but can we get it to also exclude another file/directory (like such a "vendor" directory)?

Other examples include auto-generated source.

Thanks.

**Comment by kdy1** [comment]
Fixed. (Not published yet)


See

https://github.com/swc-project/swc/blob/8c7005d7ab364023aff236f3a95e16ebc61cc118/tests/projects/issue-466-1/.swcrc#L1-L10


and

https://github.com/swc-project/swc/blob/8c7005d7ab364023aff236f3a95e16ebc61cc118/tests/projects/issue-466-2/.swcrc#L1-L10
