### ISSUE TITLE
cli: `/dev/null` is treated as stdin compile mode

### ISSUE THREAD

**Issue by hochhaus** [swc-project/swc#4661]
### Describe the bug

Currently swc_cli (as installed from `https://unpkg.com/@swc/core-linux-x64-gnu@1.2.182/swc`) does not allow running with both inputs from files and stdin reading from `/dev/null` at the same time.

For example:

```
$ swc compile --out-file /tmp/foo.js input.ts < /dev/null
Error: Cannot specify inputs from stdin and files at the same time
```

This causes issues when attempting to run `swc` from frameworks (such as go) which read stdin from `/dev/null` by default exec'ing processes.

https://pkg.go.dev/os/exec#Cmd

> If Stdin is nil, the process reads from the null device (os.DevNull).

### Expected behavior

Do not exit with an error when compiling files while `stdin` is reading from `/dev/null`.

### Version

0.51.0

**Comment by kdy1** [comment]
@kwonoj Do you think this is a bug?

**Comment by kwonoj** [comment]
No, I wouldn't consider this as a bug, as error message clearly indicate we do not support this. This was implicit undefined behavior in previous cli. Maybe considered as an enhancement but in my honest opinion caller should specify single input. Not sure why golang tries those behavior though.

**Comment by hochhaus** [comment]
Thanks for the fast reply.

Can you comment a bit more on the requirement for stdin when specifying an input file list? Must it be a TTY?
