### ISSUE TITLE
Error: internal error in Neon module: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by zxti** [swc-project/swc#467]
I have a project with just:

```
yarn add express
```

But then this `example.ts` does not work, I narrowed this down from a larger working codebase:

```
import { NextFunction, Request, Response } from "express";
import express from "express";

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
});
app.use(
  express.static()
);
```

The error I get is:

```
Error: internal error in Neon module: called `Option::unwrap()` on a `None` value
```

**Comment by kdy1** [comment]
@zxti Did you confitured swc to parse typescript?

I've written an integration test for this, but it worked.

https://github.com/kdy1/swc/blob/3e6bb4603d10a61a533717e0ce9f8e8ca0ebdac9/tests/projects.rs#L5-L27

You need `.swcrc` like
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false
    }
  }
}
```



Btw, I need to improve error message.

**Comment by zxti** [comment]
Yes I did, I also now see the main difference is that my .swcrc specifies this (since I have to run in node using @swc/register):

```
  "module": {
    "type": "commonjs"
  }
```
