### ISSUE TITLE
Testing with real-world codes

### ISSUE THREAD

**Issue by zxti** [swc-project/swc#468]
This is a very promising project!  However I notice I've been easily encountering various bugs trying to get started on various real-world codebases.  I can continue filing these, but that might not be the most efficient approach (and it's hard to tell what are different manifestations of the same underlying bug).

Would you consider creating an issue to track the pass rate against test suites from other projects like typescript/babel/sucrase, or even the source code from large existing JS/TS projects?

Even just having the tests in place may also help guide contributors' efforts.

**Comment by kdy1** [comment]
> Would you consider creating an issue to track the pass rate against test suites from other projects like typescript and babel, or even the source code from large existing JS/TS projects?

I copied almost all tests from babel. And in https://github.com/kdy1/swc/tree/typescript , I copied almost all tests from typescript.


I agree that we need some tests for large codebases.. Can you recommend some projects?
I'll use this issue to track tests for large codebases.

**Comment by zxti** [comment]
I see!  Yes I can recommend a few.  Thank you for continuing to improve swc.

**Comment by zxti** [comment]
I seem to have trouble simply trying to build the Typescript codebase (a recent commit, a78342a160) using swc.  I immediately run into errors/crashes.  Do you also see this?  Similar story for various other large projects I tried.

My .swcrc is just:

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

Here's what I see:

```
$ swc `find ~/proj/others/TypeScript/src -name '*.ts'`
error: Expected ';', '}' or <eof>
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/playbackRef.ts:2:11
  |
2 | namespace Playback {}
  |           ^^^^^^^^
  |
note: This is the expression part of an expression statement
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/playbackRef.ts:2:1
  |
2 | namespace Playback {}
  | ^^^^^^^^^

error: Expected ';', '}' or <eof>
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/parallel/shared.ts:1:11
  |
1 | namespace Harness.Parallel {
  |           ^^^^^^^
  |
note: This is the expression part of an expression statement
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/parallel/shared.ts:1:1
  |
1 | namespace Harness.Parallel {
  | ^^^^^^^^^

[Error: failed to parse module]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

... [about 3000 more lines of errors before a panic]
```

**Comment by kdy1** [comment]
Seems like typescript parser is not enabled. I'll imvestigate it.

**Comment by kdy1** [comment]
I've managed to narrow it down.

If you change swcrc to 
```json
{
  "test": ".*.ts$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

typescript parser is enabled, and swc emit different error (another bug..).

Relevant code: https://github.com/swc-project/swc/blob/ec086a1dabe2e620fc08c3fbc940ef8dabf6b4fe/src/config.rs#L374-L389

I'll fix this today if possible

**Comment by zxti** [comment]
Hmm, maybe I'm doing something wrong, but when trying the latest, I'm still seeing errors:

```
$ cat .swcrc
{
  "test": ".*.ts$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
$ cat package.json
{
  "name": "swcplay",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@swc/cli": "^0.1.18",
    "@swc/core": "^1.1.5",
    "@swc/register": "^0.1.4"
  }
}
$ yarn swc `find  ~/proj/others/TypeScript/src/ -name '*.ts*'`
error: Expected ';', '}' or <eof>
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/parallel/worker.ts:1:11
  |
1 | namespace Harness.Parallel.Worker {
  |           ^^^^^^^
  |
note: This is the expression part of an expression statement
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/parallel/worker.ts:1:1
  |
1 | namespace Harness.Parallel.Worker {
  | ^^^^^^^^^

error: Expected ';', '}' or <eof>
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/playbackRef.ts:2:11
  |
2 | namespace Playback {}
  |           ^^^^^^^^
  |
note: This is the expression part of an expression statement
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/playbackRef.ts:2:1
  |
2 | namespace Playback {}
  | ^^^^^^^^^

error: Expected ';', '}' or <eof>
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/parallel/host.ts:1:11
  |
1 | namespace Harness.Parallel.Host {
  |           ^^^^^^^
  |
note: This is the expression part of an expression statement
 --> /Users/zxti/proj/others/TypeScript/src/testRunner/parallel/host.ts:1:1
  |
1 | namespace Harness.Parallel.Host {
  | ^^^^^^^^^
```

**Comment by kdy1** [comment]
@zxti I created a new issue. I'll fix it soon.

**Comment by zxti** [comment]
OK, I have checked out a few projects (angular, typeorm, rxjs, ionic, tslint) as subdirectories of the current directory (so .swcrc is above the source files).

I also updated .swcrc to specify target:

```
{
  "test": ".*.ts$",
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

Now I see output like the following (note that I have to run multiple processes which is why you see some aborts interleaved):

```
$ find angular -name '*.ts*' | xargs -n 999 yarn swc > /dev/null
fatal runtime error: failed to initiate panic, error 5
error Command failed with signal "SIGABRT".
error: jsc.taraget should be es5 or upper to use getter / setter
  --> angular/aio/content/examples/hierarchical-dependency-injection/src/app/hero.ts:20:7
   |
20 |   get name() { return this.hero.name; }
   |       ^^^^

error: jsc.taraget should be es5 or upper to use getter / setter
  --> angular/aio/content/examples/hierarchical-dependency-injection/src/app/hero.ts:21:7
   |
21 |   get tax()  { return this.income ? .10 * this.income : 0; }
   |       ^^^

...

error: Unexpected token Some(Word(HTMLInputElement))
  --> angular/aio/content/examples/binding-syntax/src/app/app.component.ts:29:23
   |
29 |     let testButton = <HTMLInputElement> document.getElementById('testButton');
   |                       ^^^^^^^^^^^^^^^^

...

error: import(...) expressions requires `jsc.parser.dynamicImport` to be true
  --> angular/aio/content/examples/router/src/app/app-routing.module.ts:20:25
   |
20 |     loadChildren: () => import('./admin/admin.module').then(mod => mod.AdminModule),
   |                         ^^^^^^

...

[much more output]
```

**Comment by kdy1** [comment]
I updated the title to represent bug correctly.
I'll investigate it.

**Comment by zxti** [comment]
Hi, I saw that you released a fix for the first few bugs, but I see that the others are still there, including the panics.

Anyway, the original title / intent of this issue was to suggest this approach of just trying to run the compiler on some real world codebases (rather than reporting all the individual bugs).  Once it works on these codebases like typescript, angular, etc., that would be a great milestone.  Hopefully this effort will one day make swc usable.

I will probably leave this issue here for now. It's a promising project and I understand it is hard. I certainly could never do something like this myself!

**Comment by kdy1** [comment]
@zxti I reopened it.

**Comment by piaoger** [comment]
I remember I mentioned three.js as a real world example for validation.

Today, I found it's used for benchmark in another project [esbuild](https://github.com/evanw/esbuild)similar to swc but written in golang:

```
This benchmark approximates a large JavaScript codebase by duplicating the three.js library 10 times and building a single bundle from scratch, without any caches. The benchmark can be run with make bench-three.
```

**Comment by kdy1** [comment]
@piaoger I've heard about it, but it's bit different from swc. It's rather similar to spack, the bundler I'll going to write, but spack will have more features related to ffi. spack will support plugin and loader written in javascript. (It is main cause why development of spack is delayed)

**Comment by piaoger** [comment]
@kdy1 
thanks for you response.  I just want to let you know that maybe three.js can be a real world case for validation. It seems that there are many test cases.

**Comment by kdy1** [comment]
@piaoger Oh.. Great idea. It seems like test suite of three.js is easy to run (while being many), so I'll find a way to test it on ci without making forking swc slower.
