### ISSUE TITLE
Source map generation sometimes adds extra source 

### ISSUE THREAD

**Issue by seansonb** [swc-project/swc#4691]
### Describe the bug

Some scripts generate an extra source "<<jsx-config-pragma.js>>" that has the content "React.createElement". I'm not sure what causes this in particular, but this example script will generate the extra source in the mappings. 

### Input code

```typescript
export class Class {

	constructor(name, instructor, units) {
		this.name = name;
		this.units = units;
		this.instructor = instructor;
		this.instructor.addClass(this);
	}

	getInstructor() {
		return this.instructor;
	}

	getName() {
		return this.name;
	}

	getUnits() {
		return this.units;
	}
}
```

### Config

```json
{
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "ecmascript" 
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true,
  "isModule": "unknown"
}
```

### Expected behavior

The generated source map for the given source code is:

`{"version":3,"sources":["<anon>","<<jsx-config-pragma.js>>"],"sourcesContent":["export class Class {\n\n\tconstructor(name, instructor, units) {\n\t\tthis.name = name;\n\t\tthis.units = units;\n\t\tthis.instructor = instructor;\n\t\tthis.instructor.addClass(this);\n\t}\n\n\tgetInstructor() {\n\t\treturn this.instructor;\n\t}\n\n\tgetName() {\n\t\treturn this.name;\n\t}\n\n\tgetUnits() {\n\t\treturn this.units;\n\t}\n}","React.createElement"],"names":["Class","name","instructor","units","addClass","getInstructor","getName","getUnits"],"mappings":"AAAA;;;;;;;;;;;;;;;;;;;;;;;;AAAO,IAAA,AAAMA,KAAK,iBCAd,ADAG;;aAAMA,KAAK,CAELC,IAAI,EAAEC,UAAU,EAAEC,KAAK;;QAClC,IAAI,CAACF,IAAI,GAAGA,IAAI,CAAC;QACjB,IAAI,CAACE,KAAK,GAAGA,KAAK,CAAC;QACnB,IAAI,CAACD,UAAU,GAAGA,UAAU,CAAC;QAC7B,IAAI,CAACA,UAAU,CAACE,QAAQ,CAAC,IAAI,CAAC,CAAC;;;;YAGhCC,GAAa,EAAbA,eAAa;YATd,OASCA,SAAAA,aAAa,GAAG;gBACf,OAAO,IAAI,CAACH,UAAU,CAAC;aACvB;;;YAEDI,GAAO,EAAPA,SAAO;YAbR,OAaCA,SAAAA,OAAO,GAAG;gBACT,OAAO,IAAI,CAACL,IAAI,CAAC;aACjB;;;YAEDM,GAAQ,EAARA,UAAQ;YAjBT,OAiBCA,SAAAA,QAAQ,GAAG;gBACV,OAAO,IAAI,CAACJ,KAAK,CAAC;aAClB;;;;CACD,EAAA;QApBYH,KAAK,GAALA,KAAK"}`

I would expect this to only include the one source passed in, instead of two with a source that relies on using React.

### Actual behavior

An extraneous source is created

### Version

1.2.160

**Comment by 0xe** [comment]
In [`lookup_source_file_in`](https://github.com/swc-project/swc/blob/main/crates/swc_common/src/source_map.rs#L985), when searching in `self.files`, i see that it contains entries unrelated to the source:

```
[
    SourceFile(<anon>),
    SourceFile(<<jsx-config-pragma.js>>),
    SourceFile(<<jsx-config-pragma.js>>),
    SourceFile(<<jsx-config-pragma.js>>),
    SourceFile(<<jsx-config-pragmaFrag.js>>),
]
```

The first entry `SourceFile(<anon>)` being the actual input source.

**Comment by kdy1** [comment]
I know the cause

**Comment by DerGernTod** [comment]
looks like this is still an issue in 1.2.198. for me it causes problems when generating lcov reports from test runs with @swc/jest. my config looks like this:
```
        "^.+\\.(t|j)s$": ["@swc/jest", {
            sourceMaps: "inline",
            module: {
                strict: false,
                strictMode: false
            },

            jsc: {
                target: "es5",
                parser: {
                    syntax: "typescript",
                    dynamicImport: true
                }
            }
        }]
```
the lcov.info file ends with this:
```
SF:source\core\asyncCore\actions\<<jsx-config-pragma.js>>
FNF:0
FNH:0
DA:1,1
LF:1
LH:1
BRF:0
BRH:0
end_of_record
```
and the coverage report fails with
```
Error: ENOENT: no such file or directory, open 'C:\project\packages\my-package\test-results\lcov-report\core\asyncCore\actions\<<jsx-config-pragma.js>>.html'
    at Object.openSync (node:fs:585:3)
    at FileWriter.writeFile (C:\project\node_modules\.pnpm\istanbul-lib-report@3.0.0\node_modules\istanbul-lib-report\lib\file-writer.js:185:41)
    at HtmlReport.onDetail (C:\project\node_modules\.pnpm\istanbul-reports@3.1.4\node_modules\istanbul-reports\lib\html\index.js:411:44) 
    at LcovReport.<computed> [as onDetail] (C:\project\node_modules\.pnpm\istanbul-reports@3.1.4\node_modules\istanbul-reports\lib\lcov\index.js:28:23)
    at Visitor.value (C:\project\node_modules\.pnpm\istanbul-lib-report@3.0.0\node_modules\istanbul-lib-report\lib\tree.js:38:38)        
    at ReportNode.visit (C:\project\node_modules\.pnpm\istanbul-lib-report@3.0.0\node_modules\istanbul-lib-report\lib\tree.js:88:21)     
    at C:\project\node_modules\.pnpm\istanbul-lib-report@3.0.0\node_modules\istanbul-lib-report\lib\tree.js:92:19
    at Array.forEach (<anonymous>)
    at ReportNode.visit (C:\project\node_modules\.pnpm\istanbul-lib-report@3.0.0\node_modules\istanbul-lib-report\lib\tree.js:91:28)     
    at C:\project\node_modules\.pnpm\istanbul-lib-report@3.0.0\node_modules\istanbul-lib-report\lib\tree.js:92:19
```

unfortunately i don't have the option to switch to es2021 because lots of tests fail then (i'm not exactly sure why, probably related to some patched polyfill that won't initialize on that target...)

**Comment by kdy1** [comment]
Please file a new issue

2022년 7월 21일 (목) 오후 7:57, Gernot Raudner ***@***.***>님이 작성:
