### ISSUE TITLE
Guidelines on implementing plugins?

### ISSUE THREAD

**Issue by cyjake** [swc-project/swc#470]
Need to port https://www.npmjs.com/package/babel-plugin-import

A simple regex replacer might suffice but I'd like to learn the recommended way to implement plugins for swc.

**Comment by kdy1** [comment]
Currently plugin system is not ready yet.

I'm considering 

 
# A. Embed plugins in swc binary



This make deploying plugins easier, and makes 

(codes will live in a module like contrib-xxx)



---

I personally want to go with `A`, as with it I can update plugins when types of ast node is changed.

**Comment by kdy1** [comment]
Currently plugin system is not ready yet.

I'm considering 

 
# 1. Embed plugins in swc binary

This make deploying plugins easier, and allow me maintaining plugins on swc update.
(codes will live in a module like contrib-xxx)

Also, this option allows me to update plugins when types of ast node is changed.



# 2. dll / so based

Seems ideal option, but dependency hell might occur.

# 3. Custom binary built by user with additional transform

It means building a rust library / command line app which depends on swc. If you pick binary, deploying would not be that hard.

See: https://github.com/izelnakri/mber-rust

# 4. IPC-based plugin
protobuf work in this way, and it allows writing plugin in any language.

# 5. js plugin interface 

I though this is the best, but context switching and serializing native object is **really** slow.

# 6. DSL
There's some languages written in rust. 
See: https://github.com/gluon-lang/gluon 

---

Which option do you prefer?

**Comment by kdy1** [comment]
Closing in favor of #471.

**Comment by kdy1** [comment]
Javascript based plugin is almost done, and there's a basic example of using plugin.
See https://github.com/swc-project/node-swc/blob/d51369e43e590fa66ddc2db6ca39976cdd185ac9/__tests__/transform/plugin.js

**Comment by kdy1** [comment]
@cyjake See https://swc-project.github.io/docs/usage-plugin

**Comment by cyjake** [comment]
Awesome! I'll try implementing babel-plugin-import this week

**Comment by matzeeable** [comment]
Hey @cyjake !

Are there any news about the plugin? :-)

**Comment by cyjake** [comment]
@matzeeable @kdy1 Probably a bit too late for this experiment since the js api will be deprecated in swc v2, anyway here it goes https://github.com/cyjake/swc-plugin-import/blob/master/src/import.ts#L32

How do I replace one `ImportDeclaration` with multiple ones? For example,

```js
import { debounce, throttle } from 'lodash';
```

should be replaced with,

```js
import debounce from 'lodash/debounce';
import throttle from 'lodash/throttle';
```

I think I'll give it a try no matter the stable API is in JavaScript or in Rust. Trying to replace babel with swc in my own bundler called [Porter](https://github.com/erzu/porter) in the foreseeable month.

**Comment by kdy1** [comment]
@cyjake I documented about it at https://docs.rs/swc/0.65.0/swc/#cutomizing
I wrote document for someone building a custom node binding, but plugin api will be almost identical.

**Comment by ankitchouhan1020** [comment]
If anyone is still looking for one, here is my implementation. [swc-plugin-transform-import](https://github.com/ankitchouhan1020/swc-plugin-transform-import).
