### ISSUE TITLE
hygiene regression with renamed functions

### ISSUE THREAD

**Issue by jpm4** [swc-project/swc#4706]
### Describe the bug

See repro; `Foo` gets renamed to `Foo1` as in this issue: https://github.com/swc-project/swc/issues/1600#issuecomment-893864913 (credit to jdb8 for figuring out the repro here too)

### Input code

```typescript
var Foo = function () {
  function Foo() {}
  return Foo;
}();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.186&code=H4sIAAAAAAAAAytLLFJwy89XsFVIK81LLsnMz1PQ0FSo5lJA8IHSIKFaoFhRaklpEVjEmqtWQ9MaAMEniZs%2BAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8aBWqM714bUrKSmPdmOp3wtHWqrBBdH1o2%2FtJG4hPDa6hGbmoz2jlChiNjPcSWgtdksRTITR2lkMPe1pIvqaoAD%2BJ8xL855lAqn2sFnazVeVcllXyCxjN0lwPet216yfgBCKaI9boAAAA%3D

### Expected behavior

Function should not be renamed

### Actual behavior

```"use strict";
var Foo1 = function() {
    var Foo = function Foo() {
    };
    return Foo;
}();
```

### Version

1.2.186

### Additional context

On the playground, v1.2.101 works while v1.2.102 breaks, so it seems likely to be this PR: https://github.com/swc-project/swc/pull/2408

We were previously on v1.2.81 with `experiments.optimizeHygiene` set (which no longer exists - does this option still exist in a different form or is it meant to be enabled by default?).

Note also that with mangling on there's no bug.

**Comment by kdy1** [comment]
```js
var Foo1 = function() {
    var Foo = function Foo() {
    };
    return Foo;
}();

```

This does not seem like a bug

**Comment by jdb8** [comment]
@kdy1 thanks for taking a look! I'm curious to understand how this differs from the original case in https://github.com/swc-project/swc/issues/1600#issuecomment-893864913: as mentioned there, I realise that the renaming of functions and variables like this shouldn't break the code directly (as all references in scope should be updated to the new name), but that in cases where function names are expected to stay consistent with the input code it can break things (React enzyme tests is one example, on components that lack an explicit `displayName` attribute).

It also differs from babel's output for the same input, which [leaves `Foo` unchanged](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=G4QwTgBAYg9jEF4IDMCuA7AxgFwJY3QgAoBKCAbwCgIUMd9DYZSKBfaiMAU21TEbgBuSq1KCgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=Node-16&version=7.18.0&externalPlugins=&assumptions=%7B%7D).

Do you have more context on why this wouldn't be considered a bug, or at least something that could be improved? Especially given that this output seems to have changed back after `1.2.101`, and was previously working fine under the `optimizeHygiene` flag in `1.2.81`.

**Comment by kdy1** [comment]
Because input code has clearly two bindings.

```js
// first one
var Foo = function () {
  // second one
  function Foo() {}
  return Foo;
}();
```



and those two are different from each other
