### ISSUE TITLE
Javascript plugin

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#471]
I decided to go with javascript plugin interface (**v1**) and ipc plugin interface (**v2**).

I found a way to minimize performance drop caused by context switching. (https://github.com/neon-bindings/neon/issues/401#issuecomment-479894519)

# js plugin (v1.1)

 - [x] Fix serialization of `BytePos`, `SyntaxContext`
 - [x] Don't omit empty fields.
This is an optimization for v8's hidden class.
 - [x] `neon-serde` -> serde_json with JSON.parse
 - [x] update types of ast (.d.ts file)
 - [x] neon support for calling javascript code from rust: https://github.com/neon-bindings/neon/pull/375
 - [x] optimize performance of serialization / deserialization
 - [x] guide for writing plugin

# Note
 - I'll rewrite popular plugins in rust

**Comment by rowanoulton** [comment]
Excited to see where this goes! Do you have any examples of what a JS plugin would look like? From our side, we'd love to see an equivalent for `babel-preset-env`.

**Comment by kdy1** [comment]
@rowanoulton In low level, it would be a simple ast to ast transformation, and there will be a helper (https://github.com/swc-project/plugin-utils) which allows visitor pattern.
