### ISSUE TITLE
swc fails to resolve import "path" aliases in tsconfig/jsconfig

### ISSUE THREAD

**Issue by localip** [swc-project/swc#4729]
### Describe the bug

Import aliases from tsconfig/jsconfig FAIL to get resolved.

 

### Input code

```typescript
tsconfig.json:

{
  "compilerOptions": {
    "baseUrl": "./src/",
    "outDir": "dist",
    "target": "ESNext",
    "jsx": "react",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "downlevelIteration": true,
    "noUnusedParameters": false,
    "useDefineForClassFields": false,
    "paths": {
      "@components/*": [
        "components/*"
      ]
    }
  }
}


Import any of those aliases and attempt to compile with swc, it will succeed except it won't actually resolve those imports.
```

### Config

```json
Default options as swc automatically picks up tsconfig.json
```

### Playground link

Cannot provide as tsconfig.json won't exist.

### Expected behavior

Import aliases are meant to compile to their relative paths.

### Actual behavior

Import aliases don't get resolved at all, causing only the main file to get compiled.

### Version

v1.2.187

**Comment by kwonoj** [comment]
Please provide reproducible minial repo.

also

> Default options as swc automatically picks up tsconfig.json

Not sure if I understood this correctly. SWC does not reads tsconfig.json.

**Comment by kdy1** [comment]
We don't look at `tsconfig` nor `jsconfig`
