### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped Segmentation fault

### ISSUE THREAD

**Issue by feirpri** [swc-project/swc#4752]
### Describe the bug

I got Segmentation fault when i  use '@swc/core'

### Input code

```typescript
node -e 'new worker_threads.Worker(`console.log(require("@swc/core"))`, { eval: true })'
```

### Expected behavior

build successfully

### Actual behavior

{
  version: '1.2.189',
  plugins: [Function: plugins],
  Compiler: [class Compiler],
  parse: [Function: parse],
  parseSync: [Function: parseSync],
  parseFile: [Function: parseFile],
  parseFileSync: [Function: parseFileSync],
  print: [Function: print],
  printSync: [Function: printSync],
  transform: [Function: transform],
  transformSync: [Function: transformSync],
  transformFile: [Function: transformFile],
  transformFileSync: [Function: transformFileSync],
  bundle: [Function: bundle],
  minify: [Function: minify],
  minifySync: [Function: minifySync],
  __experimental_registerGlobalTraceConfig: [Function: __experimental_registerGlobalTraceConfig],
  getBinaryMetadata: [Function: getBinaryMetadata],
  DEFAULT_EXTENSIONS: [
    '.js',  '.jsx',
    '.es6', '.es',
    '.mjs', '.ts',
    '.tsx'
  ]
}
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault

### Version

1.2.189

**Comment by kdy1** [comment]
cc @Brooooooklyn

**Comment by alexander-akait** [comment]
Do we have dynamic `import(...)`? There is bug in Node.js

**Comment by feirpri** [comment]
No dynamic import(...) in code. Is there any method to print detail error message or execution stack?

**Comment by Brooooooklyn** [comment]
@feirpri what's the system in your qemu env?

**Comment by feirpri** [comment]
> 

CentOS Linux release 7.7.1908 (Core)

**Comment by Brooooooklyn** [comment]
@feirpri It's a known issue in rust: https://github.com/rust-lang/rust/issues/91979
