### ISSUE TITLE
Babel plugin

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#476]
If we modify ast node, we can use babel plugins as swc plugin.

**Comment by haikyuu** [comment]
@kdy1 is this possible? 

I'm porting a library that uses some custom babel plugins to swc. Can I just use those plugins? What are the changes I need to make (with some example code if possible)?

Thanks a lot

**Comment by kdy1** [comment]
@haikyuu Yes, it's possible, but it requires lots of work.
