### ISSUE TITLE
fixer: object spread should have a paren for seq exprs

### ISSUE THREAD

**Issue by wbinnssmith** [swc-project/swc#4761]
### Describe the bug

This generates invalid JS. It seems to only occur when there isn't a local binding for the object, i.e. `var x = ...` does not reproduce this.

### Input code

```typescript
x = {
    ...(0, foo)
}
```

### Config

```json
{
  "jsc": {
    "minify": {
      "compress": false,
      "mangle": false
    },
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2018"
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA6tQsFWo5lIAAj09PQ0DHYW0%2FHxNrloAliq7FBcAAAA%3D&config=H4sIAAAAAAAAA0XNwQqEMBAD0H%2FJuYddT0v%2FZiijVGy3TOZgEf99FVe8JeFBNsxMiBtKrnnsZ0rf0kxJxFEWakCROi36r3tAE6PaSdmry4oI702ZLDdHgHN9sItN6gdRDq%2F3B8d0X13kBzg5QxKCAAAA

### Expected behavior

Sequence expression is retained in generated code:

```
x = {
    ...(0, foo)
}
```

### Actual behavior

Sequence expression is not retained in generated code:

```
x = {
    ...0, foo
}
```

### Version

1.2.189

**Comment by kdy1** [comment]
I modified the title
