### ISSUE TITLE
downtranspiling of class method into ES5 can generate function declaration with invalid function name

### ISSUE THREAD

**Issue by Shinyaigeek** [swc-project/swc#4774]
### Describe the bug

in latest swc(v1.2.189), downtranspiling of class method into ES5 can generate function declaration with invalid function name, such as function declaration with reserved keyword function name. This causes runtime or parsing error.

### Input code

```typescript
export class Foo {
	let() {}
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA0utKMgvKlFIzkksLlZwy89XqObizEkt0dBUqK7lqgUAk3%2FrGh4AAAA%3D&config=H4sIAAAAAAAAA0WNSw7DIAxE7%2BI16y5yhxwCUSei4iePIxUh7l6oiLIbj%2BfNNPrA0daoWAHLVKhJ7Zc20loYTnxRMqQY1mEDuBsKOYPXaSj65I86UZdjEQael01nuJN9kDG%2Fr2m0f%2FsYYbyoPx2L89hXUOXi%2FgMhdKqapgAAAA%3D%3D

### Expected behavior

```javascript
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
export var Foo = function() {
    "use strict";
    function Foo() {
        _classCallCheck(this, Foo);
    }
    var _proto = Foo.prototype;
    _proto.let = function _let() {};
    return Foo;
}();
```

### Actual behavior

```javascript
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
export var Foo = function() {
    "use strict";
    function Foo() {
        _classCallCheck(this, Foo);
    }
    var _proto = Foo.prototype;
    _proto.let = function let() {};
    return Foo;
}();
```

### Version

1.2.189

**Comment by kdy1** [comment]
Seems like we should use `Ident::verify_symbol` from https://github.com/swc-project/swc/blob/26578c8c0a71e6abcd602f3352e6c4ddf8c259cc/crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs#L946-L959

**Comment by Shinyaigeek** [comment]
@kdy1  Thanks! I sent PR 👍 (but my approach was different from what you suggested) #4775
