### ISSUE TITLE
"_classPrivateFieldLooseBase is not defined" error in swc/core 1.2.146

### ISSUE THREAD

**Issue by henrik242** [swc-project/swc#4795]
### Describe the bug

Upon upgrading to `"@swc/core": "1.2.146"` I'm getting `_classPrivateFieldLooseBase is not defined`:

```
[App] ReferenceError: _classPrivateFieldLooseBase is not defined
[App]     at new GithubServiceAccount (/Users/foo/src/bar/baz-web/dist/services/github-service-account.js:112:9)
[App]     at Function.fromEnv (/Users/foo/src/bar/baz-web/dist/services/github-service-account.js:28:16)
```
Here's the offending generated code: 
```
    constructor(token, logger){
        Object.defineProperty(this, _client, {
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, _token, {
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, _parseOwnerAndRepo, {
            value: parseOwnerAndRepo
        });
        _classPrivateFieldLooseBase(this, _token)[_token] = token;
        _classPrivateFieldLooseBase(this, _client)[_client] = new _githubClient.default(token, logger);
    }
```

### Input code

```
export default class GithubServiceAccount {
  static fromEnv(logger: FastifyLoggerInstance): GithubServiceAccount {
    return new GithubServiceAccount(githubServiceToken(), logger);
  }

  #client: GithubClient;
  #token: string;

  constructor(token: string, logger: FastifyLoggerInstance) {
    this.#token = token;
    this.#client = new GithubClient(token, logger);
  }
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020",
    "keepClassNames": true,
    "loose": true
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "strictMode": true,
    "lazy": false,
    "noInterop": true
  },
  "sourceMaps": "inline"
}
```

### Expected behavior

Error should not be thrown :) 

### Version

1.2.146

### Additional context

1.2.145 works fine, and every version after it doesn't.

**Comment by Austaras** [comment]
You should upgrade `@swc/helpers` too, or you could disable loose mode

**Comment by kdy1** [comment]
I don't think it happens with newer version of swc

**Comment by henrik242** [comment]
> You should upgrade @swc/helpers too, or you could disable loose mode

@Austaras: I don't have a specific dependency to `@swc/helpers`, should I add one?  There's no transparent dependency to it in `package-lock.json` either.

But setting `"loose": false` in `.swcrc` works, thanks! What exactly does this do?

> I don't think it happens with newer version of swc

@kdy1: I get the same error with `1.2.194`

**Comment by kdy1** [comment]
Then please post enough input.

See https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA3WPTQrCMBCF955iwE0L4gFaXIioCO70AnWc1mCdyGRSFfHupo3iD7pJmLyX976h89GKwpbKwtcKWBfOwdzozm9WJI1BGiNazwrXHoDTQg1CKfYw5SapbVWRZDArnJrysuzGBQcXI6XZ%2FxwAIfXCwHT66Uqq98e13RMn6QBiYZqHiFsvHH2sDbE%2Bmybd1Kp9bb9kAVgMV3nrRRvAxKNaST7UZ%2By%2FPR7EujNuGHNhBN2dvwmRJCivlSJOLPtiv90B7M1vH3gBAAA%3D&config=H4sIAAAAAAAAA02Puw7CMAxF%2F8VzB%2BjA0JmBhY%2BwglsF5SXbRURV%2Fp0krVQ2P%2B49vt7gLQamDRKyELdKclD8wgSaE4lhmxQGUKmjGZ1QqQ3yQlolJONlvNa1i1EIJuWVBvA22Dk3lok%2BMYkc1rrCsDj6IzEGmSP7pna0oMl3MpFRI%2B%2B4KqKvEgd0D3KJWE63j6%2B10baetee5QTkDHEetPA%2Fhno%2FCp3v6FxUHUMoPZaTcCQkBAAA%3D

If it really happens, please file a new issue with enough information
