### ISSUE TITLE
Incorrect use of exported function in module's other functions

### ISSUE THREAD

**Issue by eliashoo** [swc-project/swc#4822]
### Describe the bug

Modules other functions should use live binding instead of local function directly

### Input code

```typescript
export const thing = () => {
    console.log("hello")
}

export const other = () => {
    thing()
}
```

### Config

```json
{
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "tsx": false
      },
      "target": "es5",
      "loose": false,
      "minify": {
        "compress": false,
        "mangle": false
      }
    },
    "module": {
      "type": "commonjs"
    },
    "minify": false
  }
```

### Playground link

https://swc-play.vercel.app/?version=1.2.165&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlEoycjMS1ewVdDQVLC1U6jmUgACkEx%2BTqpeTn66hlJGak5OvpImVy0XVyqyxvySjNQiNI1gwzRAagFUTES3ZAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1tt3kDj2ESZXg4B8aBWqM7165OGQnzedNoxMbrY2KE7CMCzWp%2B9JKWgtjE1%2BUFlKYtLsA7vY4OVgtwniZF3IGT3eh6JPf6yBtORZh4LFcOsKd7AaK%2BXMNof3HDGiVmNMJ6g9olj3eM61ycf8BnwbyVboAAAA%3D

### Expected behavior

*other* uses exports.thing

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.other = exports.thing = void 0;
exports.thing = function () {
    console.log("hello");
};
exports.other = function () {
    exports.thing();
};
```

### Actual behavior

*thing* is used directly in *other*'s body

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.other = exports.thing = void 0;
var thing = function() {
    console.log("hello");
};
exports.thing = thing;
var other = function() {
    thing();
};
exports.other = other;

```

### Version

1.2.194

### Additional context

This is issue when patching exported function from external module in unit tests.

PS. SWC playground seems broken. wasm.js was renamed to wasm-web.js in swc 1.2.171 in jsdeliver.

**Comment by kdy1** [comment]
No swc is correct.
Please search for issues before creating one

**Comment by eliashoo** [comment]
I couldn't find reference to the bug neither in swc or typescript repos before opening this issue. Maybe i'm just missing related search tems.

But after checking how rollup, swc and babel transpiles that same code I can see that swc is consistent with others. Could you point me to related issue?
