### ISSUE TITLE
Minifier: `if_return` removes return

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#4841]
### Describe the bug

`if_return` incorrectly removes a return (and adds `void void ...` which is unneeded).

### Input code

```typescript
global._processChunk = function _processChunk(chunk, async, newReq) {
  if (chunk) {
    if (!async) {
      return true;
    }
    var newReq = this.write();
    newReq.callback = callback;
    return;
  }
  cb();
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": false,
        "booleans": false,
        "booleans_as_integers": false,
        "collapse_vars": false,
        "comparisons": false,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "defaults": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": false,
        "ecma": 5,
        "evaluate": false,
        "expression": false,
        "global_defs": {},
        "hoist_funs": false,
        "hoist_props": false,
        "hoist_vars": false,
        "ie8": false,
        "if_return": true,
        "inline": 0,
        "join_vars": false,
        "keep_classnames": false,
        "keep_fargs": false,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": false,
        "module": false,
        "negate_iife": false,
        "passes": 1,
        "properties": false,
        "pure_funcs": [],
        "pure_getters": false,
        "reduce_funcs": false,
        "reduce_vars": false,
        "sequences": false,
        "side_effects": false,
        "switches": false,
        "top_retain": [],
        "toplevel": false,
        "typeofs": false,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_symbols": false,
        "unsafe_undefined": false,
        "unused": false
      },
      "mangle": true
    },
    "transform": {
      "legacyDecorator": true
    },
    "externalHelpers": true
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA1VOQQ7CMAy78wpz26RpH0Cc%2BAEfQG2UsYqqhbRlQmh%2FhzbswMVybMfJ1Udr%2FHi5SyRO6TSXcMMRUwmUXQz4MzqqOMCkV6ABgZczP3q8d4CboK6OKuxbcFMA4VwkIEvhQ5PWhk8jv67v5Ty7NC7iMne9htQayXhvDdXvNqq%2BtlZe68jWvfUDHe99gdgAAAA%3D&config=H4sIAAAAAAAAA22UzW7bMAzH38XnHNoCG4ach2KXPcEwGIxEOdpkURWpNEbQdy%2BVeLac7Cb%2BRFH8%2BEuX7g%2Bbbn%2FpEmTGXFc8RYFzt%2B%2FQjMAm%2ByTdTt0UOQiMH7tOIA8o1YVfnl6edTsQMc4Ou2700bupBjM0pozMda2HyohRePGDnOl9NQ9EASE%2Bgh6491FwwLxuGgoBEmN%2Fgg0dtRTPFLesCNo%2BZUotjtaLp6jmAi2C7Q1ZbIiDEpqsrc9oxJ%2BwQRpYT0XWfLfQ4qEMQ%2B3sTGtXu%2F0XXZwgFJDVH8%2FXVmlCCxoCHSBoEFc7qJ0%2FkmfpXWmqu6FtaTe2aYzHb%2Bva9RmlZL1IcqkgBh81kycdNPm4PfkXUYsLwBxhxDvudKr36D9uPjrVhEwLVcE0%2BY5kS9O5iIM2pvferSzp%2FTXqsy61Vszim0tSyVjbYhT9%2Bj3bqlFpFZPRFrO4beGmYsa3gtE08dlb7NE5HXwD372YY%2BMlOnBtLPh4y0LtgCcMq8OUkNx6QOcITY03s797FjOtKn6Ar1qLtIqZ%2BQhyfGAoR7IPIbSbQvcw61s7p3vK03ig8BChRBWo6sc2G4UXU2U7QhzqfKva6v%2BR9VE7ymP9FoIO20zf0VAGobw44VmHp2%2FzB4Z0neLM%2F2nlcu3m9RP62n2sn86saP45%2B12PfQK5EfEO6AQAAA%3D%3D

### Expected behavior

...

### Actual behavior

```js
function _processChunk(chunk, async, newReq) {
	if (chunk) {
		if (!async) {
			return true;
		}
		var newReq = this.write();
		void void (newReq.callback = callback); // <-----
	}
	cb();
}
```

### Version

Both 1.2.189 and 19562af0c7ce2453e1fa54f8955dad924bd67007

**Comment by kdy1** [comment]
Thank you so much for such detailed issue reporting!
As you may know, finding the problematic pass is the most hard part of debugging minifier 😄
