### ISSUE TITLE
SWC can't strip useless parentheses during minification

### ISSUE THREAD

**Issue by SukkaW** [swc-project/swc#4845]
### Describe the bug

SWC can't strip useless parentheses during minification.

### Input code

```typescript
let f = window.__anything;
const str = (f ? "bEvNbr " : "") + ((f ? "WhAZY " : "") + ((f ? "kLKrsq " : "") + ((f ? "bLIxaN " : "") + ((f ? "bOjOhu " : "") + ((f ? "lksDzB " : "") + ((f ? "edsxqC " : "") + "fygwnR kQBRAp fwqTyU sJymt jdraHW hcJKTR eqrBPF kVZHcH dwawJR iATxZH jQenOz glXlAQ ejfOAg imuUWK jePIQM eCuFxb ieWmMp YseoS "))))));

console.log(str);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es2022",
    "loose": true,
    "minify": {
      "compress": {},
      "mangle": {}
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true,
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA4WSy26CQBSG9zzFH1aaJj5ATdOArUFQEaqlujFchvtFGCjg05fKglpBz2Zmzvzfl7M4Iclh4wWlF1tJOTke9bjOXS92poyZxDQHzbPme2TjFazx%2Fr02MrB4BsuOGTT1hNHl%2FK02pLncYX%2BV%2BZ%2FrssFSymh6E%2B4DOshYLip93QsNgX9g2ZfdYhC%2BJ%2BgkYUDfzvxdySNRJyMWrdLZQ1krZO3aKWMVgcKr3Al2mW7rHahYRzl8K9MFDa4pSlsVJM34zRzB50EwBVilXooqPG5bHQT4ConlM5zwK%2BQUEN%2BWOQdeVOw0CT7ZLJQVyKyYVwY8okWrE%2FaUJB9gB4frH%2Fu2e93pXu1tPGUuS5eEZBImzqhZvab1A1UZqs6iAgAA&config=H4sIAAAAAAAAAzWMSwrDMAxE76K1F8WLLnyHHEK4anCJP0gy1ITcvVGc7maGeW%2BHj0QIOzRkIbYkoyh%2BIQDFjBI5NYXDgSKvpDaLf3gPDrZahSAod3KQU0nvYXysuTGJnPnEMpZ1I8uHtfrqVwMdjS7Z0%2BR%2FerqSLPdvdqmdIy3YZC7HD3Z6E2S2AAAA

### Expected behavior

```js
let e=window.__anything;const n=(e?"bEvNbr ":"")+(e?"WhAZY ":"")+(e?"kLKrsq ":"")+(e?"bLIxaN ":"")+(e?"bOjOhu ":"")+(e?"lksDzB ":"")+(e?"edsxqC ":"")+"fygwnR kQBRAp fwqTyU sJymt jdraHW hcJKTR eqrBPF kVZHcH dwawJR iATxZH jQenOz glXlAQ ejfOAg imuUWK jePIQM eCuFxb ieWmMp YseoS ";console.log(n);
```

### Actual behavior

```js
let a=window.__anything;console.log((a?"bEvNbr ":"")+((a?"WhAZY ":"")+((a?"kLKrsq ":"")+((a?"bLIxaN ":"")+((a?"bOjOhu ":"")+((a?"lksDzB ":"")+((a?"edsxqC ":"")+"fygwnR kQBRAp fwqTyU sJymt jdraHW hcJKTR eqrBPF kVZHcH dwawJR iATxZH jQenOz glXlAQ ejfOAg imuUWK jePIQM eCuFxb ieWmMp YseoS ")))))))
```

### Version

1.2.189

**Comment by Austaras** [comment]
Could you provide a more concise reproduction?

**Comment by Austaras** [comment]
Simpliefied repro:
```js
console.log(a + ('d' + (b ? 'c' : 'd')))
```
should be
```js
console.log(a + 'd' + (b ? 'c' : 'd'))
```
after compress
