### ISSUE TITLE
Regression in 1.2.189 -> 1.2.194 - type-only namespace is not defined.

### ISSUE THREAD

**Issue by bradzacher** [swc-project/swc#4851]
### Describe the bug

In the @typescript-eslint project we consume SWC via `@swc/jest`. We have the code/config as below.

In our current version (1.2.189) - our tests run amazingly!
However [dependabot attempted to bump the version to 1.2.194](https://github.com/typescript-eslint/typescript-eslint/runs/6661076466?check_suite_focus=true), and it our test suite to fail with the error `ReferenceError: AST is not defined`.

I believe this is because SWC is not emitting the `AST` namespace due to it being a type-only namespace.

I can't provide a true playground repro because v194 is not available on the playground at the time of filing.

### Input code

```typescript
import { TSESTree, AST_TOKEN_TYPES } from '../ts-estree';

namespace AST {
  export type TokenType = AST_TOKEN_TYPES;

  export type Token = TSESTree.Token;

  export type SourceLocation = TSESTree.SourceLocation;

  export type Range = TSESTree.Range;
}

export { AST };
```

### Config

```json
// consumed via @swc/jest
{
  jsc: {
    target: 'es2019',
    transform: {
      react: {
        runtime: 'automatic',
      },
    },
  },
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA22PPQvCMBCG9%2FsVt3XR%2BgOCg0MnRcXc4lRCOaVIPkgiKCX%2F3TQoWOt2vPc8L3e9dtZHHJBkI8kzL3AjqaXDttm3dD42EhNevNVY1fUqhiWHmKlKABilOTjV8WjgAIj8KGXx6RjJ3tjQOK1%2FG7P7h83c54a6BDNM2rvveGc7FXs74aebmXhS5srffAkEJIA3NpQfkoAX9KmwUxABAAA%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1Fm0XhfoOPYRwleDgH5ICNcZ3r21SshtmRk9TYRcLpkJGFuKhpETFLxjQkkksu6ywgEq3lA9qXSNvpL1B8rjdXz31KQmBWdELLRBcdGsZLJtCZhK5Ioyb%2FzdbZ4X0OYZR57vJfEK7GOedk%2FdZnBt%2BJYyKhrcAAAA%3D

### Expected behavior

Our tests should pass as they did with v1.2.189.

### Actual behavior

The type-only namespace should continue to be exported.

### Version

1.2.194

**Comment by kwonoj** [comment]
Hi! I just checked with 1.2.189 and it also doesn't export anything for type only:
<img width="1227" alt="Screen Shot 2022-05-30 at 7 31 54 PM" src="https://user-images.githubusercontent.com/1210596/171081206-1a38bdee-cbe4-4f3b-9855-986f98c141e8.png">

Also this matches to typescript's behavior (https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQMoFFXKgUxwGjgEEsB9ZAeQGl0A5cgTQAVM4BfOAMyghDgHIAdIID0MAM4BaHOJi4c-ANwAoZQDsAhiBlgNAYxzEsiZXDg4AHpFhwYATzCHkEANY41yB4YC8R5OWo6RhZUFVNzK2h4e0cUV3c4XzRMbDxBZzc1MLNLa2ivOFQIAFcoAwAZCD0NGGAINUSUDCx5QSLSiqqauqzVHMibGMMAJQ01AHMfJpTW0YmcFTZVXKjEP3ZFIA)

Do we have a minimal repro 1.2.189 or any working version exports type-only namespace?

**Comment by kwonoj** [comment]
For me it looks like regression is opposite, it tries to export non-existent type-only namespace instead like `export { AST };`.

**Comment by bradzacher** [comment]
> Do we have a minimal repro 1.2.189 or any working version exports type-only namespace?

I think the regression is that in 189 it emits `export {}` (correct), but in 194 it emits `export {AST}`? I'm not 100% sure as I can't check the playground.

All I can say for sure is that in 189 our tests pass fine, but in 194 our tests fail with the above error.

**Comment by kwonoj** [comment]
Yes, that's what I mentioned in

> For me it looks like regression is opposite, it tries to export non-existent type-only namespace instead like export { AST };.

This is clearly a bug fix I believe,  wanted to clarify if I understood the issue correctly.
