### ISSUE TITLE
external helpers cannot be imported from projects with `type: "module"`

### ISSUE THREAD

**Issue by nickluger** [swc-project/swc#4854]
### Describe the bug

[This PR](https://github.com/swc-project/swc/pull/4767) changed the way how external helpers are imported, to import only the used external helpers, instead of the entire namespace, as described in this issue: https://github.com/swc-project/swc/issues/2745.

This causes a runtime bug, for example when using a rest spread (which uses the `_object_without_properties` helper). I'm not sure whether other helpers are affected, too, but I could reproduce this one. 

It compiles without complaints, but running the compiled file causes.

```
TypeError: _object_without_properties is not a function
    at file:///home/runner/SWC-helpers-import-broken/dist/index.js:6:29
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

This is fully **reproduced** here: https://replit.com/@nickbluey/SWC-helpers-import-broken#src/index.ts. Please fork the thing and run `npm run build` and `npm run start` to see the error message. (Not using SWC playground as it has no helpers and also this is a runtime issue).

I assume this has something to do with ESM/CJS interoperability, as the code in `@swc/helpers/lib_objectWithoutProperties.js` is CJS, but the consumer is ESM, and the exporting code is exporting like `exports.default = _objectWithoutProperties;`.

### Input code

```typescript
const obj = {
  a: 1,
  b: 2
};

const { a, ...other } = obj;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2015",
    "externalHelpers": true
  }
}
```

### Expected behavior

The generated code `import _object_without_properties from "@swc/helpers/lib/_object_without_properties.js";` should resolve to the function.

### Actual behavior

See error above.

### Version

v1.2.196

**Comment by kdy1** [comment]
I modified the title to express the issue correctly.
But I'm not sure how can I fix this issue. `node.js` does not support `esnext`, right?

Then I'm not sure about the way to guide node.js to use other files

**Comment by kdy1** [comment]
Maybe we can change helpers to `type: "module"` so node js can handle it.

**Comment by kdy1** [comment]
Oh, I was wrong.
Due to version of `@swc/core` used by `@swc/helpers`, it was not publsihed

**Comment by kdy1** [comment]
>
> Oh, I was wrong.
> Due to version of @swc/core used by @swc/helpers, it was not publsihed

This is why I closed this issue. I thought it was problem of helper being not published. I just didn't change title after lefting a comment.

**Comment by nickluger** [comment]
OK, great thanks!

**Comment by devongovett** [comment]
I think the `inject_helpers` pass should probably have an option to add imports to the `src` folder rather than `lib` when outputting ESM? Node's interop does weird things with the CommonJS version:

```
> await import('@swc/helpers/lib/_ts_decorate.js')
[Module: null prototype] {
  __esModule: true,
  default: { default: [Getter] }
}
```

The double `default` key generated by node is what messes it up. Before #4767 when the helpers were imported from `@swc/helpers` without a subpath the interop happened to work correctly.

In order for `import('@swc/helpers/src/_ts_decorate.js')` to work in node, you'd need to rename the files to `.mjs` as well.

**Comment by kdy1** [comment]
@devongovett  Thanks! I got the idea from your comment.

**Comment by devongovett** [comment]
Thanks @kdy1! Looks like `swc_ecma_transforms_base` and `swc_ecma_transforms_module` hasn't been released yet? Looks like only `swc_ecma_transforms_compat` got bumped in the release commit: https://github.com/swc-project/swc/commit/2d1fbe8dcda3eae65888e63c2709ff0173125c3d.

**Comment by kdy1** [comment]
Fixed with https://github.com/swc-project/swc/commit/0782c533b55a8da177b91eb1914daa845c1ce0a1
The publish script sometimes works srangely.

@devongovett  Thanks for the notice!
