### ISSUE TITLE
Module not found due missing .js extension on compile

### ISSUE THREAD

**Issue by juanlatorre** [swc-project/swc#4857]
### Describe the bug

The compiled JS fails because of the missing .js on import statements, here is a repo with the issue; [Repro](https://github.com/juanlatorre/swc-test)

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.196&code=H4sIAAAAAAAAA3VVTW%2FiMBC98yu8OVTpKk2117BU225pF4kWFhCXqqrcZEishti1HbYI8d93%2FJEQUHsB2%2FPm682zw9aCS012ZPi4jMifyXwRkelkhr8lz3OQZE9Wkq9JEF9CtQn6PeYcVlRpttpG6HnnljMQJe7b3XsNSrfuHo8Bmgj3kori73jJtxTzeDePzo3tvbzYOOOF974QZZ2z6lBFyjPIoWpL9PsuoNLwoTsAuz8AdiSVQDXMQW463f5qKtjynF5WGLbrotIC1rRDzZpndQmqi6kV3DJFX0sYVVpyJSDVjFeHDEgnlFxcZg51wbowwxPWigRSIcigoTvctWM5bxG5I9J3MDhq6OeuR4iE9%2BRkLn17jANLjsbX7%2B2vQuNiY7L3MiFa1hDhScqlSoixERLHcYh6iUfzl9vhcjieTB%2BGjwtydoZ9c8lwRAkJvgdYpPHcO3dLvFmaDliVJ6a1GDfmzA0WEzzZBF%2BQF7r0hHjORquEhOdkcGXUG9%2BO5tc34%2BHL6HExm8ynw9%2BL0eSRfBsMjPpKBUFkvV1Rz%2BZnTdUbZEMpO70VtMpKmFKpoDE0FDTGJS1ZRk1BpwjbqlNH1LMjMj1KXmuwtdcSGQ0uvbhsQWvQBc%2Bw8eB%2BuAgiEkzxDpr%2FydTUPw9spS6xRM7UtkpJiCON3ABt%2B650JwcJSuACUAn0H2Un%2BohdpFGV8jUO4QGUwhvm4jXsmk27NJfa89a3%2FysuSehSPVV0DRHZ0LKGZ8JXbe64AJqBVOedmBjIH4cdNx903%2BsdUEpTXauwDeb2HukhUGUHwCvPtta896x%2FLYfBQQ6oV3SxA4KcKY2FffomNcQIqgszPf8oeTmhFEVJtxNh9NCqCOvkXC%2B2AhJSVxmsWAVZQ6p6Y2IG6JQQW0n3%2FBaEhBTvb9bVHdrwVbnZXpeioK%2BgT2wF%2FzcGurpjUGbq2FawDGZYylEqK9NGnriMS9M%2BXi9iHq%2FEfwAKrnBtPgmINShdICbsCO7zN8A%2FwqGbiPXEhtIiDEHKjre%2F%2FjGYS2RtbsJC8hRlGcMH0%2BEPH6Xf%2Bw9fKKLBqgYAAA%3D%3D&config=H4sIAAAAAAAAA02NwQrCMBBE%2F2WPUqzk4KEnf8CjJ%2FGQxm2NJGnY3YKh9N9NQkCPw7w3s8GbDQwbjJrxRg4GOPZMBjqIWl5cqotfnqtD7g8w3HP9i4%2B9A9E0o2QPWZ2UqiIxUjE5BdGf3EmKyIZsFMiKt8FOqQBm8ZGQ882kHWOudJgdtrgXtp4VtmzUm%2FP%2FRvMsXxsotOL%2BBXGHtH%2FXAAAA

### Expected behavior

node dist/server.js should start the api correctly.

### Actual behavior

on node dist/server.js I get an error:

```bash
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<user>/swc-test/dist/env' imported from <user>/swc-test/dist/server.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:981:10)
    at defaultResolve (node:internal/modules/esm/resolve:1078:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Version

1.2.196

### Additional context

Currently running Node v16.14.0 and

```json
{
    "@swc/cli": "^0.1.57",
    "@swc/core": "^1.2.196",
}
```

**Comment by kdy1** [comment]
You should write `'./env.js'` instead if you want it

**Comment by juanlatorre** [comment]
Do you know if there is a custom plugin or config to add the ".js" extension on compiled files? something like:

`import x from "./folder"` -> `import x from "./folder/index.js"`
`import x from "./file"` -> `import x from "./file.js"`

I couldn't find any, I'm thinking of creating a custom plugin for this, but want to leave it as "last resort" thing to do
