### ISSUE TITLE
Line from website example does not compile

### ISSUE THREAD

**Issue by maor-benami** [swc-project/swc#4858]
```plugin: (m) => new JSXPlugin().visitProgram(m)```

Does not compile using `swc` and `syntax: 'typescript'`.
Could not find out why, anyone can help?

```
Error: Method visitTsType not implemented.
```

**Comment by kwonoj** [comment]
Dupe of https://github.com/swc-project/swc/issues/4648.

Please note JS plugin is not complete, as well as not actively maintained at this moment. We recommend to use new experimental wasm plugin instead.
