### ISSUE TITLE
Support for "const enum/enum"

### ISSUE THREAD

**Issue by Algram** [swc-project/swc#486]
Hi,

first of all thanks for this project. I could not find any information regarding the support of `const enum`. Can you elaborate if it is?

![image](https://user-images.githubusercontent.com/5053729/70063168-9df61400-15e7-11ea-9933-3e8338df08bc.png)

Thanks!

**Comment by kdy1** [comment]
swc currently does not support const enums, just like babel.
It's not supported because swc works file by file.

I'm working on it, but I guess it would take some time.

**Comment by Algram** [comment]
@kdy1 thanks for the insanely fast answer!
I suppose this also means normal enums, e.g.

```typescript
enum Foo {
  Hello = 'hello'
}
```

are also currently not supported?

**Comment by kdy1** [comment]
Normal enums are supported, and I tried to make swc follow tsc's output as possible.

**Comment by Algram** [comment]
@kdy1 Ok I guess I am missing something then. This is my config
```json
{
  "jsc": {
    "target": "es2019",
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": true
    }
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  }
}

```

I am using the `swc-loader`, yet I get the following error:

![image](https://user-images.githubusercontent.com/5053729/70064005-17423680-15e9-11ea-905e-d2e5cc1d3fc7.png)

**Comment by kdy1** [comment]
It seems like a bug of typescript pass.
I'll fix it tomorrow (it's over 12pm in my country)

**Comment by nisimjoseph** [comment]
I am trying to replace the normal compiler of Webpack with SWC, but the "const enum"s are not replaced.
any configuration change I am missing which needs to be done for the TypeScript build?

**Comment by stackinspector** [comment]
I'm using the `deno bundle` command from Deno 1.17.1, which treats `enum` and `const enum` the same. So what the current status of this issue is?

**Comment by dhlolo** [comment]
It seems that swc supports const enum/enum, but it doesn't support '[inline](https://www.typescriptlang.org/docs/handbook/enums.html#:~:text=enum%20members%20are-,inlined,-at%20use%20sites)' feature till now as [issue#3648](https://github.com/swc-project/swc/issues/3648) mentioned.
