### ISSUE TITLE
Wrong completion value when destructing on exported value

### ISSUE THREAD

**Issue by Jack-Works** [swc-project/swc#4866]
### Describe the bug

The completion value for destructing assign on exported bindings are wrong.

### Input code

```typescript
export let a, b
console.log([a, b] = [1, 2])
```

### Config

```json
This translation is wrong on all targets: including CommonJS, AMD, SystemJS, and UMD.
```

### Playground link

https://play.swc.rs/?version=1.2.196&code=H4sIAAAAAAAAA0utKMgvKlHISS1RSNRRSOLlSs7PK87PSdXLyU%2FXiAYJxSrYKkQb6igYxWoCAMtZwJQtAAAA&config=H4sIAAAAAAAAA0WMSwoEIQxE75K1i8Fl32EOEex04%2BCPJMKIePdRcOhViqqX1%2BEjDo4OBVmIV5KWFL9wALmI4tgXBTOxWV0YhIYBRb5JFyL2Ze2cQ85CGzAQffJXWzKXY2ESeSZMd%2FiTY7piPusqOmgr80KNJ4zHsf%2B8vDeoXGn8AN7HW6K4AAAA

### Expected behavior

The completion value should be `[1, 2]`

![image](https://user-images.githubusercontent.com/5390719/171551521-bcc99c0a-b199-4239-be4d-946aaea1d5bc.png)

### Actual behavior

The completion value is `2`

### Version

1.2.196

### Additional context

The correct translation should be

```js
console.log(([
    [a, b] = [1, 2], // store completion value here
    exports.a = a,
    exports.b = b
][0])); // read it out by [0] here
```

**Comment by kdy1** [comment]
Investigation:

Seems like the modules pass is not aware of destructuring.

It works for es5 https://play.swc.rs/?version=1.2.196&code=H4sIAAAAAAAAA0utKMgvKlHISS1RSNRRSOLlSs7PK87PSdXLyU%2FXiAYJxSrYKkQb6igYxWoCAMtZwJQtAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE7zJrb7vJHXoI4SjBxT8kBWqM714bUrLSMO9pOj7qsXVUEmVZSVs2%2BmID%2B0TqJVSDm9qsDorKw8FITral6GuyWIryTR1SyOFoa8mXVIVVH0T5jH9zzKFU9msVHdbqvKC0Yzwb91%2FQ9y2aXDx%2BSdFDLbUAAAA%3D

**Comment by magic-akari** [comment]
This issue will go away after #4758 is merged.
It's OK if someone fixes it before.
