### ISSUE TITLE
Support for Path Mapping

### ISSUE THREAD

**Issue by Algram** [swc-project/swc#487]
Are you planning to support `path mapping`?

https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

Thanks a lot!

**Comment by kdy1** [comment]
I will implement it, but it would take some time.

**Comment by opiation** [comment]
@Algram, is this different than the older #379?   If not, might I suggest closing this issue in favor of #379 to consolidate upvotes and discussion?  @kdy1, would you agree?

**Comment by kdy1** [comment]
Oh... You are right
