### ISSUE TITLE
Binary and Octal literals are not being transpiled to ES5 properly

### ISSUE THREAD

**Issue by Arutselvan** [swc-project/swc#4870]
### Describe the bug

Binary and Octal literals are not being transpiled properly to ES5 syntax. The support for Binary and Octal literals were introduced in ES2015: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#numeric_literals

### Input code

```typescript
function test() {
    return (0b111110111 === 503 && 0o767 === 503);
}
test();
```

### Config

```json
{
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "ecmascript"
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA0srzUsuyczPUyhJLS7R0FSo5lIAgqLUktKiPAUNgyRDEDAAYgVbW1sFUwNjBTU1BYN8czNzmICmNVctF0S3NQD4ftayTgAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t934Dj2EcJXg4B%2BSAjXGd69FDF1pNDNvBlwSwA9oyEJsSnpR%2FIIHChklcGwKbtWWpXzTdKDIJ6k15LWiVKvQEzrIscSj206ouTGJgD8wiUVYzkT7nWsn189txgDtbV1Dci2XwPwPbTjKe7cf%2FAesTJxCuQAAAA%3D%3D

### Expected behavior

The numerical literals should be converted to integers. (For the octal literal `0o767` ,  it should be either `0767` or `503`). 

The following output for the input code was obtained from Babel transpiler. 

```typescript
var test = function test() {
  return 503 === 503 && 503 === 503;
};
test();
```

### Actual behavior

The binary and octal literals are not transpiled correctly.

The following output was obtained using swc:

```typescript
var test = function test() {
    return 0b111110111 === 503 && 0o767 === 503;
};
test();
```

The above code when run in ES5 environment throws the following error:

```
missing ; before statement
    <refname> : Line(2) column(24)
    return (0b111110111 === 503 && 0o767 === 503);
```

### Version

1.2.189

**Comment by edwincoronado** [comment]
Looks like this is a regression and broke in v1.2.164. Was working in v1.2.163.

**Comment by Austaras** [comment]
result of #4245
