### ISSUE TITLE
Typescript metadata is wrong for primitives that include undefined

### ISSUE THREAD

**Issue by javiergonzalezGenially** [swc-project/swc#4874]
### Describe the bug

If a decorated object property is a primitive and includes undefined (e.g.  `number | undefined`) then the design type is incorrectly assumed to be `__metadata("design:type", Object)` instead of `Number` (or `String` or whatever).
Removing undefined from the type definition makes it work.

### Input code

```typescript
const decorator: any = () => {}

class PaginationQuery {
  @decorator()
  limit: number | undefined;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.196&code=H4sIAAAAAAAAAz3LPQ5AQBAG0H5O8ZX2CoQ4AkcYu0MmYTbZn0JwdyrlK56PlguC%2BJi4xNSC7USPxqEfcD1EfuecMfGmxkWjzVXSiYuA8V%2BN%2B7jroaWF1WORhBvVgqxqEjp66AUCwuu4ZwAAAA%3D%3D&config=H4sIAAAAAAAAA02MQQrDMBAD%2F6JzXuBzr32EsDelJYnN7gZijP9ehybQm5Bm1PCxiNBQqCZ6Jqub80CA1yIW9V0cE9xGNXMxmZAkZqVnNQTXXfqYlZvNWdfzYZEXY33c1A%2F6057iTHRedu9f34zLp4YAAAA%3D

### Expected behavior

The metadata should ignore undefined and use the primitive at least (like tsc does)

### Actual behavior

The metadata is assumed to be Object when undefined is used alongside the primitive

### Version

1.2.196

**Comment by kdy1** [comment]
Please search before filing an issue
