### ISSUE TITLE
"ReferenceError: id is not defined"  in private class fields

### ISSUE THREAD

**Issue by danr-za** [swc-project/swc#4891]
### Describe the bug

We're getting the following error since v1.2.173, and it seems to be related to private fields in classes.

```js
Uncaught ReferenceError: id is not defined
    at _classPrivateFieldLooseKey (broadcast-channel.ts:1:1)
    at 11128 (broadcast-channel.ts:8:24)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at 74333 (email-validator.ts:6:2)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at 27528 (index.ts:27:43)
```

As can be seen in the playground, a variable named `id1` is created, but `_classPrivateFieldLooseKey` is using `id`.

### Input code

```typescript
export class LocalStorageChannel {
  readonly #channelName: string
  #listeners: MessageListener[]

  constructor(channelName: string) {
    this.#channelName = channelName
    this.#listeners = []
    window.addEventListener('storage', (event) => this.onStorageEvent(event))
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.197&code=H4sIAAAAAAAAA71UTYvbMBC9%2B1dM2UPkELx3g7u0pYeFbS9beik9KPY4EZUlI8lxw27%2Be8eylChxzgVjmA%2B9efNmJPzba%2BPAHXuEb2gt3%2BGLsA4VGqiAKRyDt4zhrwdULofqIxy0aLLscb3OYA0%2F9sICfRx6LY%2BtkBKcBjv0Hn9rNG9qbh3Ue64UShAKXnnLjZgOP6vpHJoWawejNrLZgJsARz3IBrZI4c8R4ktE6HqJHZHhTmgFTChHCLzGiUarDbSDGwxZ5N8Zn5RTsccM555rya2FF11z%2Beq0odYi8lsGYJA3WskjPATG33lHIlhnhNpR%2FEEGmWx5K9yv3xkl1FpR8lATNLsDkfsq4Nss0hoke2IlOeeClEElpsAoVKPHgjeNn0okwFZ2bmi1AYbneXkYrUKz%2FkSIki5wmkj3Rhy4Q7iXVULqy0s%2F%2F9CFaEOhIlT%2BRPrBh6oCmegL7%2B8wZ%2F3Bo48uuo%2ByTAOg6SlvnPzfCzqfD4KTELSgV4vJVt1sUetv0HDHy1CSMn9yOSCccg83bQibMaOyoNtbrS98ooulDPIzv1m%2BYStFTTfAxgTWxesTxn4lW5hfqlFh0T077NhCmg10l6JpucX456WhK13CRY4sbaKEONP7txrgej%2FPehT9YPcsmrdMDHb6gP%2BNDFQLevTwuFgUaL6DMQkZj3njm7c0GP7c3BX1FR8KvySL96eK41tEnp7uPSvZPz7XtchsBQAA&config=H4sIAAAAAAAAA0WNSQrDMAxF76J1Fk0XLfgOOYRxleDiCUmBGuO7Vw4u3Ul%2FeL%2FBmx2YBsUSI42LaxL7AQNSC7IjXwQWEFZpt4Gx62PpQNEI8v22PtUOOTOCETpxgeiT3%2BtguRwLIfOsqmXTEfBHUlTMr3MI7Zq7kA%2Fof8bsed5mcEz0L%2FMvGIu3AAAA

### Expected behavior

Should build succesffully

### Version

v1.2.197

**Comment by kdy1** [comment]
Oh... `id` is renamed due to a bug of helper system
