### ISSUE TITLE
When I was developing some functions of css-module, I found some problems with parse css

### ISSUE THREAD

**Issue by zhusjfaker** [swc-project/swc#4894]
### Describe the bug

https://swc-css.netlify.app/

content
```
.c :global(.tap #h2 ::visible) h3 :global {
  display: inline-block;
  width: 20px;
}

```

![image](https://user-images.githubusercontent.com/31839470/172339527-8b31000b-8c90-414a-969b-e00904fc8f54.png)

### Input code

```typescript
.c :global(.tap #h2 ::visible) h3 :global {
  display: inline-block;
  width: 20px;
}
```

### Config

```json
default
```

### Expected behavior

![image](https://user-images.githubusercontent.com/31839470/172339681-283cc13d-6c5a-4228-a22c-2d39575c1d7d.png)

parse ast-> css_node 

is  PreservedToken  not  CompoundSelector or  CompoundSelectorList

is the  ast parse result correct?

### Version

0.105.0

### Additional context

swc_atoms = "0.2.11"
swc_css = "0.105.0"
swc_css_ast = "0.93.1"
swc_css_codegen = "0.102.0"
swc_css_codegen_macros = "0.2.0"
swc_css_parser = "0.101.4"
swc_css_visit = "0.92.0"
swc_css_minifier = "0.67.0"
serde = "1.0.127"
serde_json = "1.0.66"
swc_common = "0.18.8"

**Comment by kdy1** [comment]
cc @alexander-akait

**Comment by alexander-akait** [comment]
@zhusjfaker CSS doesn't have `:global` and etc, so we use presevred tokens here
