### ISSUE TITLE
swc can not compile some legal js code when parser set to 'typescript'

### ISSUE THREAD

**Issue by fatpandaria** [swc-project/swc#4911]
### Describe the bug

swc failed to compile the following code under the typescript mode.

### Input code

```typescript
const r=n=>{return true?(true):t=>{}}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true,
      "decoratorsBeforeExport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true,
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "runtime": "automatic", // or classic
        "throwIfNamespace": true,
        "useBuiltins": true,
        "development": true
      }
    },
    "target": "es2015",
    "loose": true,
    "externalHelpers": true,
    // Requires v1.2.50 or upper and requires target to be es2016 or upper.
    "keepClassNames": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.197&code=H4sIAAAAAAAAA0vOzysuUSiyzbO1qy5KLSktylMoKSpNtdcAkZpWJUDh2louAL2McbkmAAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

swc should be able to compile this legal js file under ts mode

### Actual behavior

throw an error

### Version

1.2.197

**Comment by bernardocorbella** [comment]
+1 since I think my example could be caused by the same issue.

This is what happens with `d3-array` dependency `cumsum.js` file.

playground link: https://play.swc.rs/?version=1.2.198&code=H4sIAAAAAAAAA12OQQqDMBBF957iLxMixUXpopIWN71H0AQETcqYCZbauzdaaaGr%2BcNj3nw73wNFdNYZHiIc%2Bzb2waPlceJRJDOwnUpsMziJZ4G8EDKERlWi952d11hnQjYyedyGYOLp2BCZx8FRGEVmwC775eCgtQZnheu97TZyRYK%2BQKwflIZKWBZUcmPnf%2FaxiLT3UGqvOsnvlayL1xs7ixJh5gAAAA%3D%3D&config=H4sIAAAAAAAAAzXIwQmAMAwF0F3%2BuRN0B4cIMYIituSnYCndXT14e7yBg4o8UMVp%2Fon9CrmREb0a1fcaSAi%2BtclJS1hNi0sUJ3J4szkTWJqrLVL%2FewBbolr5WgAAAA%3D%3D

**Comment by Ayc0** [comment]
I also encountered this issue, and I noticed this was introduced in SWC v1.2.146

v1.2.145 | v1.2.146
-|-
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/22725671/192738515-23416a92-ad88-4612-a1cf-5a35cba8ddd1.png"> [playground](https://play.swc.rs/?version=1.2.145&code=H4sIAAAAAAAAA2WNzQrCMBAG732K79iQIj2IB8sqXnyP0CYQaBNIsqFifXfTn5OedpdhZg27Plnv0PMUeaqzGlnHBtv0RuBdoRwBBYLQNrBu0PO6doUEnTg4PEev0uX8CEG9Tib4vw6ICFxMY50eigjckUE31GtYEmTGsqAVG7v%2Bsr1S5%2BO9lEc5it0SXfX5AvY9S%2BPLAAAA&config=H4sIAAAAAAAAA02PUQqEMAxE75JvT%2BAN9mMPEWJcKqYpSQor4t23FRf9mxkyb8gOixOMOxQ0Z%2BvKtxz4hRFiK%2BxkqQQMEN6isMoDTExqGGoO44yr92jLKIleUtTiSo9WMsw%2Bq0nnGiPFKWqOJNwWsIYKRiI42rWknOatX5BKMfabL5g%2FK9%2FgVdUf1rUa8RvLo3HB%2Flan2gH7%2BVWbbhOiefG2%2FANtEDZcBAEAAA%3D%3D) | <img width="1164" alt="image" src="https://user-images.githubusercontent.com/22725671/192738352-adbc1393-10df-4e97-822a-b4072419a013.png"> [playground](https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA2WNzQrCMBAG732K79iQIj2IB8sqXnyP0CYQaBNIsqFifXfTn5OedpdhZg27Plnv0PMUeaqzGlnHBtv0RuBdoRwBBYLQNrBu0PO6doUEnTg4PEev0uX8CEG9Tib4vw6ICFxMY50eigjckUE31GtYEmTGsqAVG7v%2Bsr1S5%2BO9lEc5it0SXfX5AvY9S%2BPLAAAA&config=H4sIAAAAAAAAA02PUQqEMAxE75JvT%2BAN9mMPEWJcKqYpSQor4t23FRf9mxkyb8gOixOMOxQ0Z%2BvKtxz4hRFiK%2BxkqQQMEN6isMoDTExqGGoO44yr92jLKIleUtTiSo9WMsw%2Bq0nnGiPFKWqOJNwWsIYKRiI42rWknOatX5BKMfabL5g%2FK9%2FgVdUf1rUa8RvLo3HB%2Flan2gH7%2BVWbbhOiefG2%2FANtEDZcBAEAAA%3D%3D)

**Comment by leonardomaier** [comment]
The same thing started to happen here by upgrading the `recharts` lib which is dependent on `d3-*` libs. 

Pretty much the same error as @bernardocorbella described.
