### ISSUE TITLE
`this` inside arrow function compiles to (void 0) for CommonJS

### ISSUE THREAD

**Issue by karoldembowski** [swc-project/swc#4935]
### Describe the bug

Using `this` keyword compiles down to `void 0` when setting module option to CommonJS

### Playground link

https://play.swc.rs/?version=1.2.197&code=H4sIAAAAAAAAA32NOw6DMBBEe59iOkwDPRHcBdnrBMnZjfyRIiHuzuIqDZlmpdmnebbHvGA30Iwj6PshV8hjx9E6J5wl0hDlactry0MQ6S8yUa6xTKjsKWxM3hzGvMVXhXVFUmksZnR6uoexN6b2%2Fu%2BilCRNcCuzFDWvHte0hF%2F7CXkam2jKAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F21WJXfoIYSjBAf%2FkBSoMb57bXDISmLmzatwioW1QkYW4vFJiYo%2FWIFsQLHssoLpWI929ELNgCIfpAOR5fX%2B9NqnJDQBA8FFt5chsylkJpGnwnj4m2zdFdJ2jaCCltzvmIQUT4H2iObYyXfSyhe1P0Sd89u9AAAA

### Expected behavior

expected to return `this`

### Version

1.2.197

**Comment by Austaras** [comment]
Arrow in global context would have `this` set to `undefined` in es module, this is expected.

**Comment by karoldembowski** [comment]
@Austaras Sorry, maybe I should be more explicit, when compiling CommonJS -> CommonJS. `this` in cjs module is expected to return the `module.exports` object

**Comment by Austaras** [comment]
Then you should set source type to `script`
