### ISSUE TITLE
Re-exported TypeScript types are not stripped

### ISSUE THREAD

**Issue by jasongerbes** [swc-project/swc#4964]
### Describe the bug

TypeScript types are not being stripped when re-exported from another file.

### Input code

```typescript
// types.ts
export interface ExampleType {};

// index.ts
export { ExampleType } from './types';
```

### Config

```json
{
    "jsc": {
        "target": "es2017",
        "parser": {
            "syntax": "typescript",
            "decorators": false,
            "dynamicImport": true
        },
        "transform": {
            "decoratorMetadata": true,
            "legacyDecorator": true
        },
        "keepClassNames": true,
        "externalHelpers": false,
        "loose": true
    },
    "module": {
        "type": "es6",
        "strict": true,
        "noInterop": true
    },
    "sourceMaps": true
}
```

### Expected behavior

Re-exported TypeScript types should be stripped:

```js
// types.js
export { };

// index.js
export { };
```

### Actual behavior

TypeScript types are stripped from the source file, but not from files that re-export them:

```js
// types.js
export { };

// index.js
export { ExampleType } from './types';
```

### Version

1.2.118

**Comment by superamadeus** [comment]
[Type-Only Imports and Exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)

Common problem with this class of compiler. It's difficult for the compiler to know if what you're importing/exporting is *just* a type.

It's best to use the following to export types (which results in the desired output):
```
export type { ExampleType } from './types'
```

**Comment by jasongerbes** [comment]
Thanks @superamadeus, I had already switched to type-only imports/exports as a workaround to this limitation in SWC.

It may be worth documenting this as an official limitation and recommended solution is that is the official stance. I'd recommend including a link to these lint rules:

- [typescript-eslint/consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md)
- [typescript-eslint/consistent-type-exports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-exports.md)
