### ISSUE TITLE
when i dev css-module change swc-css parse find pesudo-class can not parse right 

### ISSUE THREAD

**Issue by zhusjfaker** [swc-project/swc#4977]
### Describe the bug

https://github.com/swc-project/swc/pull/4954#discussion_r895690814

### Input code

```typescript
:global(.a,.b){}
:global(.a, #.b){}
```

### Config

```json
default
```

### Expected behavior

.a.b{}
.a .b{}

### Actual behavior

.a .b{}
.a .b{}

### Version

swc_css_parser 0.102.0

**Comment by zhusjfaker** [comment]
![image](https://user-images.githubusercontent.com/31839470/173803509-388f7e8c-af4e-4694-96d5-dc95e75e6cd3.png)

**Comment by zhusjfaker** [comment]
![image](https://user-images.githubusercontent.com/31839470/173803576-d219a017-3885-4a25-84aa-ac76173edbc2.png)

**Comment by zhusjfaker** [comment]
pub fn convert_pseudo_global_class(pseudo_class: PseudoClassSelector) -> Vec<ComplexSelectorChildren> {
    let mut list = vec![];
    for select_list_wrap in pseudo_class.children.unwrap() {
      if let PseudoClassSelectorChildren::CompoundSelectorList(select_list) = select_list_wrap {
        for mut complex_selector in select_list.children {
          list.append(&mut complex_selector.children)
        }
      }
    }
    list
  }

**Comment by zhusjfaker** [comment]
```rust

pub fn convert_pseudo_global_class(pseudo_class: PseudoClassSelector) -> Vec<ComplexSelectorChildren> {
    let mut list = vec![];
    for select_list_wrap in pseudo_class.children.unwrap() {
      if let PseudoClassSelectorChildren::CompoundSelectorList(select_list) = select_list_wrap {
        for mut complex_selector in select_list.children {
          list.append(&mut complex_selector.children)
        }
      }
    }
    list
  }

```

**Comment by alexander-akait** [comment]
`#.b` is invalid selector

**Comment by alexander-akait** [comment]
Also you can use `.a,.b`, you should use [`complex-selector`](https://www.w3.org/TR/selectors-4/#grammar) here, why you want to use `selector-list`/`complex-selector-list` here?
