### ISSUE TITLE
modules that neither export nor import shouldn't be wrapped in define-call

### ISSUE THREAD

**Issue by jrieken** [swc-project/swc#4989]
### Describe the bug

This is maybe controversial and something we can tackle on our end but it is different from how `tsc` behaves

### Input code

```typescript
namespace foo {
  someglobal.fn();
}
```

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "exclude": "\\.js$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "amd",
    "noInterop": true
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.203&code=H4sIAAAAAAAAA8tLzE0tLkhMTlVIy89XqOZSUCjOz01Nz8lPSszRS8vT0LTmqgUAxm2peCQAAAA%3D&config=H4sIAAAAAAAAA0WOTQ6DQAhG70JcNmpceoPewc1kxL84wwQw1RjvXqzR7sjj%2Bx7skIkfMDioYVBNdVFMQjG%2FoCgx5sR9IR%2FPHl6Aq5%2BXFi3dNPkkmaFJPNQ7JMeCfE6yRXWrRXRLKJ7HpBZTMdS5WfAFLXpiZ3KBWnnBw9aOe1QroVRlVVphJhJ8KmGMY7edek8hMYr8Vy728508zBWoXU6w%2Fz4wpwutCSO9oyJTeo7e0qv5BTnH4YgMAQAA

### Expected behavior

With tsc the define-call is skipped because the code doesn't export or import anything.

https://www.typescriptlang.org/play?module=2#code/HYQwtgpgzgDiDGEAEAzA9mpBvAUEpUakA5gDZoBGIpAdCsABQCUA3DgL5A

### Actual behavior

The code is wrapped in a define call making it hard ti transpile code that actually bootstraps the AMD logic

### Version

1.2.203

### Additional context

relates to, but not strictly needed for, https://github.com/microsoft/vscode/issues/150025

**Comment by magic-akari** [comment]
Input
```JavaScript
const hello = "world";
console.log(hello);
```

- [rollup.js](https://rollupjs.org/repl/?version=2.75.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwaGVsbG8lMjAlM0QlMjAlNUMlMjJ3b3JsZCU1QyUyMiUzQiU1Q25jb25zb2xlLmxvZyhoZWxsbyklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJhbWQlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

```JavaScript
define((function () { 'use strict';

	const hello = "world";
	console.log(hello);

}));
```

**Comment by kdy1** [comment]
I think we should follow behavior of `tsc` for ts-specific things

TSC: https://www.typescriptlang.org/play?#code/HYQwtgpgzgDiDGEAEAzA9mpBvAUEpUakA5gDZoBGIpAdCsABQCUA3DgL5A

**Comment by kdy1** [comment]
You can use `isModule: "unknown"` to make swc behave identical as tsc.

https://play.swc.rs/?version=1.2.203&code=H4sIAAAAAAAAA8tLzE0tLkhMTlVIy89XqOZSUCjOz01Nz8lPSszRS8vT0LTmqgUAxm2peCQAAAA%3D&config=H4sIAAAAAAAAA0WOTQ6CQAxG79KwNGBccgMX3sDNZKgIMu2kLRFCuLvFH9w1r9%2F32gUKjXdMAWq4m%2BW6qnplKj9QjQVLlrbSZ5QIB8ApDmODnr5ey14LR71GqBfIQRRlm3QmC5NHbM6oUbpsHjN1dAuD4gEajCzB5Qq1yYirr4O0aF5CPR1PRy8MzIp7JXXU3eZNHzllQdX%2FKlA7%2FJKruxI34waW9wfuDKlxIfGZDIXzfvQn%2FYo6vXybMNKD%2BEmwvgDqvBMKIQEAAA%3D%3D


But `.swcrc` does not support this field...

How do you invoke swc?

**Comment by magic-akari** [comment]
> You can use `isModule: "unknown"` to make swc behave identical as tsc. (While allowing other files to be handled as module)
> 
> https://play.swc.rs/?version=1.2.203&code=H4sIAAAAAAAAA8tLzE0tLkhMTlVIy89XqOZSUCjOz01Nz8lPSszRS8vT0LTmqgUAxm2peCQAAAA%3D&config=H4sIAAAAAAAAA0WOTQ6CQAxG79KwNGBccgMX3sDNZKgIMu2kLRFCuLvFH9w1r9%2F32gUKjXdMAWq4m%2BW6qnplKj9QjQVLlrbSZ5QIB8ApDmODnr5ey14LR71GqBfIQRRlm3QmC5NHbM6oUbpsHjN1dAuD4gEajCzB5Qq1yYirr4O0aF5CPR1PRy8MzIp7JXXU3eZNHzllQdX%2FKlA7%2FJKruxI34waW9wfuDKlxIfGZDIXzfvQn%2FYo6vXybMNKD%2BEmwvgDqvBMKIQEAAA%3D%3D
> 
> But `.swcrc` does not support this field...
> 
> How do you invoke swc?

cannot agree more.
If there is neither an export nor an import in the file, TypeScript assumes it is a script.

**Comment by kdy1** [comment]
@magic-akari Do you mean we should support it in `.swcrc`?

**Comment by magic-akari** [comment]
> @magic-akari Do you mean we should support it in `.swcrc`?

Sure. We can follow Babel config. https://babeljs.io/docs/en/options#sourcetype

**Comment by jrieken** [comment]
@kdy1 Is https://swc.rs/docs/configuration/compilation#multiple-entries actually supported inside .swcrc? E.g declaring an array of configs in it I get errors complaining about invalid JSON

**Comment by jrieken** [comment]
@kdy1 there you go. It looks like it failing as soon as I put the config-object into an array (e.g works when it's a top-level object)

```json
[
	{
		"test": "\\.ts$",
		"jsc": {
			"parser": {
				"syntax": "typescript",
				"tsx": false,
				"decorators": true
			},
			"target": "es2020",
			"loose": false,
			"minify": {
				"compress": false,
				"mangle": false
			}
		},
		"module": {
			"type": "amd",
			"noInterop": true
		},
		"minify": false
	}
]
```

**Comment by kdy1** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/29931815/178765855-d051cc19-98ae-4e4b-8eca-2a323325f8b3.png">

Hmm....
Seems like deserialization itself is successful

**Comment by jrieken** [comment]
Funny... I see the error below running `npx swc --config-file .swcrc src --copy-files --out-dir out` in this branch (https://github.com/microsoft/vscode/tree/joh/swc)

```
jrieken@jrieken-m1-pro vscode % npx swc --config-file .swcrc src --copy-files --out-dir out
failed to process input file

Caused by:
    0: failed to read swcrc file (src/bootstrap-amd.js)
    1: failed to process config file
    2: .swcrc exists but not matched
```

**Comment by kwonoj** [comment]
@jrieken  I.. don't think we support top level array as config unless if I miss something? Please allow me a dumb q, any specific reason you need to use array instead of an object for the swcrc config?

**Comment by kdy1** [comment]
@kwonoj  We support top level array
