### ISSUE TITLE
Import token followed by square bracket panics

### ISSUE THREAD

**Issue by nayeemrmn** [swc-project/swc#4991]
### Describe the bug

`import[expr]` within an expression panics.

### Input code

```typescript
const str = "meta";

console.log(import[str]);
```

### Expected behavior

Syntax error

### Actual behavior

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.104.0/src/parser/expr.rs:1186:43
```

### Version

swc_ecma_parser 0.104.0

**Comment by magic-akari** [comment]
According to the [spec](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-meta-properties), you have to use literal property access expression.
`import[expr]` is not valid.
