### ISSUE TITLE
Online repl

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#50]
ratel-rust have one, and it looks great

**Comment by kdy1** [comment]
It would be really hard as swc depends on rustc-ap crates.
Some rustc-ap crates can't be compiled as wasm.

```
cargo build --release --target wasm32-unknown-emscripten
   Compiling darling_core v0.7.0
   Compiling pmutil v0.2.0
   Compiling swc_atoms v0.1.0 (https://github.com/swc-project/swc.git#67daa279)
   Compiling sourcemap v2.2.1
   Compiling rustc-ap-rustc_data_structures v297.0.0
error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:195:21
    |
195 |                     os::F_WRLCK
    |                     ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:197:21
    |
197 |                     os::F_RDLCK
    |                     ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:200:29
    |
200 |                 let flock = os::flock {
    |                             ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:208:37
    |
208 |                 let cmd = if wait { os::F_SETLKW } else { os::F_SETLK };
    |                                     ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:208:59
    |
208 |                 let cmd = if wait { os::F_SETLKW } else { os::F_SETLK };
    |                                                           ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:224:29
    |
224 |                 let flock = os::flock {
    |                             ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:229:29
    |
229 |                     l_type: os::F_UNLCK,
    |                             ^^ Use of undeclared type or module `os`

error[E0433]: failed to resolve. Use of undeclared type or module `os`
   --> /Users/kdy1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-297.0.0/flock.rs:233:42
    |
233 |                     libc::fcntl(self.fd, os::F_SETLK, &flock);
    |                                          ^^ Use of undeclared type or module `os`

error: aborting due to 8 previous errors
```

**Comment by Skalman** [comment]
Unfortunate that compiling to Webassembly seems difficult.

More search terms: Playground
Ref: #106

**Comment by dsherret** [comment]
Is it possible to do this now? I think so, right? I am using swc in a playground for dprint.

**Comment by kdy1** [comment]
@dsherret It's possible. But I'm not sure about the roadmap. I was too busy due to corona 19. And now, I have lots of bugs to fix.

**Comment by SirJosh3917** [comment]
What's the status on this? I'd like to see swc be able to be compiled to wasm.

My usecase is that I've got [a project](https://github.com/SirJosh3917/denoporter) that makes use of typescript that runs on [Cloudflare Workers](https://workers.cloudflare.com/), and often running the typescript compiler on imports takes longer than 50ms, which is hitting the limits of a cloudflare worker. To get under the limit without using regex hacks, I'd like to use rust and swc to compile to wasm and then run that in a cloudflare worker.

**Comment by kdy1** [comment]
It's absolutely doable. I just do not have enough time.
I'll setup auto deployment for wasm anyway.

**Comment by 9oelM** [comment]
Now that @swc/wasm-web is successfully published, it should be duly possible to make an online repl. I'm happy to work on this. Can I do this?

**Comment by kdy1** [comment]
@9oelM Of course. Thanks a lot!
I always wanted an online repl but I had too many bugs to fix.

**Comment by 9oelM** [comment]
Alright I find some problems with that while trying to bootstrap the project with `@swc/wasm-web`. I will file some issues.

**Comment by 9oelM** [comment]
#1291

**Comment by 9oelM** [comment]
https://9oelm.github.io/swc-wasm-demo/ 

@kdy1  

how should I move it into this repo?

**Comment by kdy1** [comment]
Wow, cool!

I think it would be great if it's integrated with the [website](https://github.com/swc-project/website), just like babel's one.
But it would need some design work and using react

So for now, uploading it to https://swc.rs/repl would be enough.
Can you make a pr to the public directory at https://github.com/swc-project/website/tree/master/website/static ? (with repl directory)

**Comment by 9oelM** [comment]
Yeah. I'm not a designer so perhaps somebody else could help later on the design 😂

Okay. I will do that soon. I'm recently busy with work stuffs, so I will do it in a few weeks.

Thank you!

FYI, this demo project already uses React :)

**Comment by kdy1** [comment]
@9oelM Sounds great. I hope I can do some design work...

**Comment by Danue1** [comment]
Are we ready to make swc available on the web?

**Comment by kdy1** [comment]
I think so, swc has `@swc/wasm-web`.

**Comment by 9oelM** [comment]
Sorry i've been busy last few months. I will start working on it (basically porting what we have already on https://9oelm.github.io/swc-wasm-demo/). Btw, @kdy1 do you want it to be included in https://github.com/swc-project/website or make a separate repl website? I think it makes sense to include it together inside https://github.com/swc-project/website

**Comment by kdy1** [comment]
I also think website is a proper repository to store repl.

**Comment by 9oelM** [comment]
Ok. then I will make one more page in the Docusaurus website.

**Comment by kdy1** [comment]
Thanks a lot!

**Comment by 9oelM** [comment]
@kdy1 i think we can close this and open other issues for further improvements

**Comment by kdy1** [comment]
Yes, you are right.

**Comment by kdy1** [comment]
Thanks!

**Comment by Danue1** [comment]
Respectful!
