### ISSUE TITLE
swc considers `{ foo }` and `{ foo: foo }` different

### ISSUE THREAD

**Issue by Mokshit06** [swc-project/swc#5019]
### Describe the bug

The swc parser considers an object property shorthand different from typing out the value as well.

When using `visit_expr` on an the code, if it is `{ foo: foo }`, it gets called with the expr being the identifier `foo`, but when I run it with `{ foo }`, `visit_expr` isn't called.

### Input code

```typescript
// calls visit_expr
const foo = 'foo';
const bar = { foo: foo };

// doesn't call visit_expr
const foo = 'foo';
const bar = { foo };
```

### Config

```json
Default config
```

### Expected behavior

Both `{ foo }` and `{ foo: foo }` similarly and call `visit_expr` when the key is visited.

### Version

0.190.0

**Comment by kdy1** [comment]
Those are different from each orther
