### ISSUE TITLE
cli not recursively compiling on windows

### ISSUE THREAD

**Issue by parisholley** [swc-project/swc#5021]
### Describe the bug

docker container: `mcr.microsoft.com/windows/servercore:1809-amd64`

command: `swc src/scripts/* src/libs/* -d build`

on linux box, above handles all nested folders with *, on windows, nothing is compiled (but works if I do the files individually)

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "module": {
    "type": "commonjs",
    "strictMode": false
  },
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

### Expected behavior

should build everything in nested folders

### Version

0.1.57 (cli) / 1.2.177 (core)

### Additional context

Here is a command I am using to workaround in Powershell:

```powershell
get-childitem src -recurse | ? { $_.FullName -like "*api\*" } | foreach-object {.\node_modules\.bin\swc $_.FullName -d build}
```

**Comment by kdy1** [comment]
Is this still an issue?
