### ISSUE TITLE
Use identical generator transform as `tsc`

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5027]

**Comment by SukkaW** [comment]
Would you mind sharing some details about the proposed change?

`regenerator-runtime` is indeed a bit heavy (2.66 KiB after minified + gzipped), but it is also performant.

Here are some benchmark results I have done last year on Node.js 16.13.1:

![image](https://user-images.githubusercontent.com/40715044/175448585-bc0c3e20-3dcd-41b9-bb7f-38c894bb997a.png)
![image](https://user-images.githubusercontent.com/40715044/175448592-92ed2103-5845-466f-9f24-06027d395197.png)

- babel: regenerator-runtime used by babel-preset-env
- fast-async: https://github.com/MatAtBread/fast-async
- babel-plugin-transform-async-to-promises: https://github.com/rpetrich/babel-plugin-transform-async-to-promises

Benchmark suite: https://github.com/SukkaW/promise-performance-tests

**Comment by kdy1** [comment]
Thank you!

I didn't know the performance difference.

**Comment by kdy1** [comment]
I think we should also consider the output size

**Comment by huozhi** [comment]
@SukkaW Can you share the code about the benchmark you did? Looks like the Finbonacci one is cirtical but not for others with performance and it takes more memory.

If users are using swc to bundle tiny libs, the 2.66kb might be a issue for bundle size of those libs. We might inline external helpers since they're not too large for the bundle

**Comment by SukkaW** [comment]
> @SukkaW Can you share the code about the benchmark you did? Looks like the Finbonacci one is cirtical but not for others with performance and it takes more memory.

Here is the benchmark suite I forked from V8: https://github.com/SukkaW/promise-performance-tests

And here is the source code of the Fibonacci tests: https://github.com/SukkaW/promise-performance-tests/blob/master/lib/fibonacci-async.js

And here are the outputs:

- https://github.com/SukkaW/promise-performance-tests/blob/master/build/fibonacci-async-babel.js
- https://github.com/SukkaW/promise-performance-tests/blob/master/build/fibonacci-async-fast-async.js
- https://github.com/SukkaW/promise-performance-tests/blob/master/build/fibonacci-async-to-promises.js
- https://github.com/SukkaW/promise-performance-tests/blob/master/build/fibonacci-async-tsc.js

**Comment by huozhi** [comment]
I tried the tests case and it breaks with some errors such as

```
ReferenceError: regeneratorRuntime is not defined
```

I feel this is the major problem that we need to manage polyfill dependencies after compilation, and make those polyfills work. tsc regenerator transform solves this problem. I wouldn't imagine tsc vs babel transform will have huge significant difference in browser as tsc has become the quite popular choice today
