### ISSUE TITLE
Can't set up typescript parsing.

### ISSUE THREAD

**Issue by anurbol** [swc-project/swc#503]
I've adapted the example https://swc-project.github.io/rustdoc/swc_ecma_parser/index.html#example-parser
for TypeScript, but still only valid JS code gets parsed, for example:
```
let foo = 123
```
generates AST just fine, but this:
```
type foo = string
```
as well as 
```
namespace Foo {}
```
```
interface Foo {}
```
generates an error `Expected ';', '}' or <eof>`

My adapted parser code is below:
```
let cm: Arc<SourceMap> = Default::default();
let session = Session { handler: &Handler::with_tty_emitter(ColorConfig::Auto, false, false, Some(cm.clone())) };
let fm = cm.new_source_file(FileName::Custom("x.ts".into()), file_text.into());

let mut parser = Parser::new_from(session, Capturing::new(Lexer::new(
        session,
        Syntax::Typescript(Default::default()),
        JscTarget::Es2019,
        SourceFileInput::from(&*fm),
        None,
)));
```

I am building against the very latest master branch of SWC (I only use Parser and Common), cloned minutes before this issue created.

What am I missing? Please help.

**Comment by kdy1** [comment]
I think you are invoking `parse_script()`. You should use `parse_module()` or `parse_typescript_module()` instead.

**Comment by anurbol** [comment]
@kdy1 OMG, I think that I didn't restart the server after rebuilding or something.... My bad, I am so sorry. However, without your help I couldn't see the problem is on my side and advance further, thank you!!

**Comment by kdy1** [comment]
@anurbol It's okay :)
I'm happy because of your interest on swc!

**Comment by anurbol** [comment]
@kdy1 I am making a commercial product (for the  last 2 years, finishing soon) with the help of your great library, and I give you a promise that the project will become a sponsor of SWC once it starts to make revenue :-) Hopefully it will make revenue 😃

**Comment by kdy1** [comment]
@anurbol Thank you! I hope you suceeds :)
