### ISSUE TITLE
Circular class imports break when upgrading 1.2.205 -> 1.2.206

### ISSUE THREAD

**Issue by kelleyvanevert** [swc-project/swc#5047]
### Describe the bug

When upgrading from 1.2.205 to 1.2.206, SWC changes how it compiles exports.

In version 1.2.205:

<img width="840" alt="Screenshot 2022-06-27 at 21 36 27" src="https://user-images.githubusercontent.com/43432/176021802-8c641c4a-cee7-4007-aab0-3389db825e67.png">

In version 1.2.206:

<img width="651" alt="Screenshot 2022-06-27 at 21 49 11" src="https://user-images.githubusercontent.com/43432/176023761-9a2f8744-645a-47ba-9c6c-8c47ff4c6d4b.png">

I have a bunch of model classes in my codebase, which of course circularly reference each other.

To avoid circularity problems, the ORM I use uses the "late binding" hack popular in the JavaScript community, referencing bindings with anonymous functions, e.g. `@OneToMany(() => Book)` instead of just `@OneToMany(Book)`. However, this seems to no longer work after the compilation change of SWC 1.2.206.

### Input code

```typescript
// Person.ts
import { Book } from "./Book";

export class Person {
    books = new Collection<Book>();
}

// Book.ts
import { Person } from "./Person";

export class Book {
    author?: Person;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2018",
    "baseUrl": "src",
    "paths": {
      "lib/*": ["lib/*"],
      "app/*": ["app/*"],
      "fixtures/*": ["fixtures/*"],
      "test-utils/*": ["test-utils/*"]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

Running this code after building it, or running it with `node -r @swc/register` should work.

### Actual behavior

Running the code after building it, or running it with `node -r @swc/register`, produces this error:

```
$ NODE_ENV=script node -r @swc/register src/fixtures/command.ts reapply
/Users/kelley/mywheels/api/src/app/core/models/Fleet.ts:6
    get: ()=>Fleet,
             ^

ReferenceError: Cannot access 'Fleet' before initialization
    at Object.get [as Fleet] (/Users/kelley/mywheels/api/src/app/core/models/Fleet.ts:16:14)
    at Object.<anonymous> (/Users/kelley/mywheels/api/src/app/core/models/FleetContractType.ts:13:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._compile (/Users/kelley/mywheels/api/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.newLoader [as .ts] (/Users/kelley/mywheels/api/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
error Command failed with exit code 1.
```

### Version

1.2.206

**Comment by magic-akari** [comment]
The Input code you provide cannot reproduce this issue, since the `Person` and `Book` are both used as type and will be striped.

The following is equivalent esm code 

```javascript
// Person.js
import { Book } from "./Book";

export class Person {
    constructor(){
        this.books = new Collection();
    }
}


// Book.js
import { Person } from "./Person";

export class Book {
}
```

And the transformed CJS as following.
```JavaScript
// Person.cjs
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "Person", {
    get: ()=>Person,
    enumerable: true
});
class Person {
    constructor(){
        this.books = new Collection();
    }
}

// Book.cjs
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "Book", {
    get: ()=>Book,
    enumerable: true
});
class Book {
}
```

Both work well. But you are using decorator which is more complex.

A valid minimal reproducible examples is one that works fine in esm mode and crashes in the transformed cjs code.

**Comment by kdy1** [comment]
cc @magic-akari

**Comment by kdy1** [comment]
Oh sorry I missed the comment

**Comment by clhuang** [comment]
In my codebase, I've noticed that the order of the resulting imports does not seem to be the same, which can cause issues.
With the following code:
```ts
export { b } from './b';
export { a } from './a';
import { q } from './a';
console.log(q);
```

[swc 1.2.218 target ES2020](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQMW7DMAxF78KxMOIgo9cu6dBunYqgYGWmTSqJAkkXNgLfPVTsJhv1PvSkzwvQGOLQE3QfkLmnz8T9EEnh0MBZA3QXKChKUiedsuEIHdhUSIOcikEDpo6OGJUa6CmwoLEodCZDJVPGdAovqbDYAme%2FI5j1yJKgy0OMDlC%2ByXMg3W13W9dGZqW7mEYjyRj3FAtV%2B8p%2FicpzRNU3TPTAX6j0LtF9m9ZdBe1Hbw1un9b2qfbdtI%2Bj1%2FWSfyT3SMKCjdT%2B4TofZq%2BwLKpK6zb8pcApcT4reKg8SKBXLOse5itFZs6jaQEAAA%3D%3D)
[swc 1.2.218 target ES2019](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQwU7DMAyG38VHVK3Abb1ygQPcOKEJmdSDjSSObHdqNfXdcday3ZzvV77k9xloDHHoCboPyNzTZ%2BJ%2BiKSwa%2BCoAbozFBQlqZNO2XCEDmwqpEEOxaABU0d7jEoN9BRY0FgUOpOhkiljOoSXVFhsgbPfEcy6Z0nQ5SFGByjf5DmQPt4%2FbF0bmZWuYhqNJGN8plio2lf%2BS1SeIqq%2BYaIb%2FkKld4nu27TuKmg%2Femlw%2BbS2d7Xvpr0dva6XPJFcIwkLNlL7h%2Bu8m73CsqgqrdvwlwKnxPmo4KHyIIFesax7mP8Aw9UzdGkBAAA%3D)
[swc 1.2.205 target ES2020](https://play.swc.rs/?version=1.2.205&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQMW7DMAxF78KxMOIgo9cu6dBunYqgYGWmTSqJAkkXNgLfPVTsJhv1PvSkzwvQGOLQE3QfkLmnz8T9EEnh0MBZA3QXKChKUiedsuEIHdhUSIOcikEDpo6OGJUa6CmwoLEodCZDJVPGdAovqbDYAme%2FI5j1yJKgy0OMDlC%2ByXMg3W13W9dGZqW7mEYjyRj3FAtV%2B8p%2FicpzRNU3TPTAX6j0LtF9m9ZdBe1Hbw1un9b2qfbdtI%2Bj1%2FWSfyT3SMKCjdT%2B4TofZq%2BwLKpK6zb8pcApcT4reKg8SKBXLOse5itFZs6jaQEAAA%3D%3D)
[swc 1.2.205 target ES2019](https://play.swc.rs/?version=1.2.205&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQwU7DMAyG38VHVK3Abb1ygQPcOKEJmdSDjSSObHdqNfXdcday3ZzvV77k9xloDHHoCboPyNzTZ%2BJ%2BiKSwa%2BCoAbozFBQlqZNO2XCEDmwqpEEOxaABU0d7jEoN9BRY0FgUOpOhkiljOoSXVFhsgbPfEcy6Z0nQ5SFGByjf5DmQPt4%2FbF0bmZWuYhqNJGN8plio2lf%2BS1SeIqq%2BYaIb%2FkKld4nu27TuKmg%2Femlw%2BbS2d7Xvpr0dva6XPJFcIwkLNlL7h%2Bu8m73CsqgqrdvwlwKnxPmo4KHyIIFesax7mP8Aw9UzdGkBAAA%3D)

in the first one, the resulting transpiled code imports b then a; in the latter three the resulting code imports a then b. 

I've also noticed in some scenarios where a circular import would cause things to be undefined the program instead crashes, IMO this is probably preferable behavior.

**Comment by clhuang** [comment]
One example that fails under 1.2.218 but not under 1.2.205 (target ES2020) is:
```ts
// index.ts
export { default as ClassA } from './a';
export { default as ClassB } from './b';
import foo from './b';

console.log(foo);

// a.ts
import { ClassA } from '.';
export default class ClassB {
}

export const foo = 'baz';
export const bar = () => new ClassA();


// b.ts
import { ClassA } from '.';
export default class ClassB {
}

export const foo = 'baz';
export const bar = () => new ClassA();
```

**Comment by magic-akari** [comment]
> In my codebase, I've noticed that the order of the resulting imports does not seem to be the same, which can cause issues. With the following code:
> 
> ```ts
> export { b } from './b';
> export { a } from './a';
> import { q } from './a';
> console.log(q);
> ```
> 
> [swc 1.2.218 target ES2020](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQMW7DMAxF78KxMOIgo9cu6dBunYqgYGWmTSqJAkkXNgLfPVTsJhv1PvSkzwvQGOLQE3QfkLmnz8T9EEnh0MBZA3QXKChKUiedsuEIHdhUSIOcikEDpo6OGJUa6CmwoLEodCZDJVPGdAovqbDYAme%2FI5j1yJKgy0OMDlC%2ByXMg3W13W9dGZqW7mEYjyRj3FAtV%2B8p%2FicpzRNU3TPTAX6j0LtF9m9ZdBe1Hbw1un9b2qfbdtI%2Bj1%2FWSfyT3SMKCjdT%2B4TofZq%2BwLKpK6zb8pcApcT4reKg8SKBXLOse5itFZs6jaQEAAA%3D%3D) [swc 1.2.218 target ES2019](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQwU7DMAyG38VHVK3Abb1ygQPcOKEJmdSDjSSObHdqNfXdcday3ZzvV77k9xloDHHoCboPyNzTZ%2BJ%2BiKSwa%2BCoAbozFBQlqZNO2XCEDmwqpEEOxaABU0d7jEoN9BRY0FgUOpOhkiljOoSXVFhsgbPfEcy6Z0nQ5SFGByjf5DmQPt4%2FbF0bmZWuYhqNJGN8plio2lf%2BS1SeIqq%2BYaIb%2FkKld4nu27TuKmg%2Femlw%2BbS2d7Xvpr0dva6XPJFcIwkLNlL7h%2Bu8m73CsqgqrdvwlwKnxPmo4KHyIIFesax7mP8Aw9UzdGkBAAA%3D) [swc 1.2.205 target ES2020](https://play.swc.rs/?version=1.2.205&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQMW7DMAxF78KxMOIgo9cu6dBunYqgYGWmTSqJAkkXNgLfPVTsJhv1PvSkzwvQGOLQE3QfkLmnz8T9EEnh0MBZA3QXKChKUiedsuEIHdhUSIOcikEDpo6OGJUa6CmwoLEodCZDJVPGdAovqbDYAme%2FI5j1yJKgy0OMDlC%2ByXMg3W13W9dGZqW7mEYjyRj3FAtV%2B8p%2FicpzRNU3TPTAX6j0LtF9m9ZdBe1Hbw1un9b2qfbdtI%2Bj1%2FWSfyT3SMKCjdT%2B4TofZq%2BwLKpK6zb8pcApcT4reKg8SKBXLOse5itFZs6jaQEAAA%3D%3D) [swc 1.2.205 target ES2019](https://play.swc.rs/?version=1.2.205&code=H4sIAAAAAAAAA0utKMgvKlGoVkhSqFVIK8rPVVDX009St%2BZKhUkkIkkkAiUyc6EShWgSyfl5xfk5qXo5%2BekahZrWAPMkOH9aAAAA&config=H4sIAAAAAAAAA0WQwU7DMAyG38VHVK3Abb1ygQPcOKEJmdSDjSSObHdqNfXdcday3ZzvV77k9xloDHHoCboPyNzTZ%2BJ%2BiKSwa%2BCoAbozFBQlqZNO2XCEDmwqpEEOxaABU0d7jEoN9BRY0FgUOpOhkiljOoSXVFhsgbPfEcy6Z0nQ5SFGByjf5DmQPt4%2FbF0bmZWuYhqNJGN8plio2lf%2BS1SeIqq%2BYaIb%2FkKld4nu27TuKmg%2Femlw%2BbS2d7Xvpr0dva6XPJFcIwkLNlL7h%2Bu8m73CsqgqrdvwlwKnxPmo4KHyIIFesax7mP8Aw9UzdGkBAAA%3D)
> 
> in the first one, the resulting transpiled code imports b then a; in the latter three the resulting code imports a then b.
> 
> I've also noticed in some scenarios where a circular import would cause things to be undefined the program instead crashes, IMO this is probably preferable behavior.

I confirmed that there is a bug in compat pass, which will be fixed soon.



> One example that fails under 1.2.218 but not under 1.2.205 (target ES2020) is:
> 
> ```ts
> // index.ts
> export { default as ClassA } from './a';
> export { default as ClassB } from './b';
> import foo from './b';
> 
> console.log(foo);
> 
> // a.ts
> import { ClassA } from '.';
> export default class ClassB {
> }
> 
> export const foo = 'baz';
> export const bar = () => new ClassA();
> 
> 
> // b.ts
> import { ClassA } from '.';
> export default class ClassB {
> }
> 
> export const foo = 'baz';
> export const bar = () => new ClassA();
> ```

Tips: Rewrite import path with `.js` suffix and add `type:module` to `package.json`, you can run it in native node esm environment.

Transformed cjs code.

```JavaScript
// index.js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    ClassA: ()=>_aJs.default,
    ClassB: ()=>_bJs.default
});
const _aJs = /*#__PURE__*/ _interopRequireDefault(require("./a.js"));
const _bJs = /*#__PURE__*/ _interopRequireDefault(require("./b.js"));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
console.log(_bJs.default);


// a.js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    default: ()=>ClassB,
    foo: ()=>foo,
    bar: ()=>bar
});
const _indexJs = require("./index.js");
class ClassB {
}
const foo = 'baz';
const bar = ()=>new _indexJs.ClassA();


// b.js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    default: ()=>ClassB,
    foo: ()=>foo,
    bar: ()=>bar
});
const _indexJs = require("./index.js");
class ClassB {
}
const foo = 'baz';
const bar = ()=>new _indexJs.ClassA();

```

You can get the same result. The ClassB is printed in both case.

**Comment by a88zach** [comment]
For those using TypeORM,  using the `Relation` type resolved the issue for me 
https://typeorm.io/#relations-in-esm-projects

**Comment by magic-akari** [comment]
It's interesting to see the linked issue.
Our module transforms allow you to do `circular imports`, but that doesn't mean you can `use before define`.

> This is just how `import` and `export` in JavaScript works. An import or export statement is only a declaration that the file either has dependencies or exposes live bindings to dependents. They just declare properties about the file and are not evaluated inline. At a high level, it works something like this (ignoring complexities such as top-level await):
>
> 1. Order all module files to be evaluated such that dependencies come before dependents
> 2. Use `import` and `export` to replace references to imports with references to the underlying exports
> 3. Ignore all `import` and `export` statements with paths since they have now served their purpose
> 4. Evaluate all code in the order in step 1

> ...

_Originally posted by @evanw in https://github.com/evanw/esbuild/issues/1395#issuecomment-869026051_

If we follow these steps to process these input (entry:index.ts)

```TypeScript
// File one.ts
import * as entities from './'
@Entity()
export class One {
  @Column(() => entities.Two) two: entities.Two
}

// File two.ts
import * as entities from './'
@Entity()
export class Two {
  @Column(() => entities.One) one: entities.One
}

// File index.ts
import { One } from './one'
import { Two } from './two'

export default { One, Two }
```

We can get a single file output.
```typescript
// bundle.ts
@Entity()
export class One {
  @Column(() => entities.Two) two: entities.Two
}

@Entity()
export class Two {
  @Column(() => entities.One) one: entities.One
}

export default { One, Two }
```

I am not familiar with decorators or TypeORM, but I suspect that there is also a `use before define` issue in this bundle.ts.

**Comment by stevefan1999-personal** [comment]
@magic-akari Actually, this is exactly what I did [here](https://github.com/typeorm/typeorm/pull/9216)

**Comment by magic-akari** [comment]
@stevefan1999-personal I may have misunderstood. 
But what I'm trying to show is that the original broken code may contains `use before define` issue.

**Comment by stevefan1999-personal** [comment]
> @stevefan1999-personal I may have misunderstood. The example code maybe wrong. (maybe fixed by the lazy trick) But what I'm trying to show is that the original broken code may contains `use before define` issue.

Oh sorry its me who misunderstood😂But this actually worked because the JS reference is created later

**Comment by xahhy** [comment]
Is this issue still active? we pinned the version to 1.2.205 due to this bug which we are using TypeOrm with swc

**Comment by stevefan1999-personal** [comment]
@xahhy I think this is a serious issue, as the problem stems from type system refactoring, and some fixtures aren't correctly implemented

**Comment by magic-akari** [comment]
> Is this issue still active? we pinned the version to 1.2.205 due to this bug which we are using TypeOrm with swc

check https://github.com/swc-project/swc/issues/5047#issuecomment-1188874962

**Comment by Nesci28** [comment]
Same issue in a NestJS project with Circular dependancies in the DI.  swc/core version to 1.2.205 doesnt not have that bug.

Manually droping the lines:
```js
Object.defineProperty(exports, "TestClass", {
    enumerable: true,
    get: ()=>TestClass
});
```
Below the line:
```js
let TestClass = class TestClass {
...
}
```
Fixes the issue.

**Comment by kelleyvanevert** [comment]
I made a small repo with a reproduction of the bug:

https://github.com/MyWheels/swc_mikroorm_circular_import_bug

Indeed, I'm not sure "whose bug" this is. Whether it's swc, MikroORM, or reflect-metadata. But the combination breaks.

I'd love to resolve the situation though, because I'm currently stuck on swc `1.2.205` :)

**Comment by kdy1** [comment]
@magic-akari WIll moving export statements fix this issue?

**Comment by magic-akari** [comment]
No, We should not do it.
We should define all the export name before any code execution.

**Comment by kdy1** [comment]
Ah, yeah I think I get the reason and you are right

**Comment by kelleyvanevert** [comment]
Before, swc would define the export name as undefined at the top of the file, and then redefine at the bottom, like so:

```ts
exports.Reservation = void 0;

...

class Reservation {
  ...
}

...

exports.Reservation = Reservation;
```

There must be good reasons to have changed this, but, it does seem like a compromise geared to solving exactly this situation.. ? (But I'm guessing here, i don't know :))

**Comment by magic-akari** [comment]
@kdy1 
I suggest accepting  https://github.com/swc-project/swc/issues/5047#issuecomment-1188874962 as the best answer.
It is also accurately described in its documentation as being caused by circular references.
Other decorator-based ORMs should have a similar solution.

**Comment by kdy1** [comment]
I see and ah... I think I got the exact cause.
This seems like https://github.com/swc-project/swc/issues/1457

**Comment by magic-akari** [comment]
@kelleyvanevert
Now swc will try to preserve ESM behavior when transform ESM to CommonJS.

You do not need ESM behavior?
Try this:

```JavaScript
exports.Reservation = class Reservation {

}
```

Are you using TypeScript? Try this

```TypeScript
class Reservation {

}

export = {
    Reservation,
}
```

**Comment by magic-akari** [comment]
> I see and ah... I think I got the exact cause.
> This seems like #1457

Oh, that's a terrible reason.
If someone really doesn't want hoisted import, there's a TS syntax `import x = require()` for them.

**Comment by myknbani** [comment]
Also encountered this issue, and pinning to `1.2.205` definitely removes the `Cannot access X before initialization` message.  Also using Nest.js. Circular deps probably the culprit.

**Comment by nerdyman** [comment]
You can also work around this by defining a type and importing it with the `type` keyword.

E.g.

```ts
@Entity()
export class Parent extends AggregateRoot {
  constructor() {
    super();
  }

  @PrimaryKey()
  id!: string;
}

// Declare an explicit type.
export type ParentType = Parent;
```

```ts
import type { ParentType } from './parent';
import { Parent } from './parent';

@Entity()
export class Child {
  @ManyToOne(() => Parent, { primary: true })
  parent!: ParentType;
}
```

**Comment by ticup** [comment]
Same issue here, we hard to give a reproducible example, but I'm certain it's due to circular references of classes and initialisation of those classes in the root of files.

Pinning to 1.2.205 solves it.

**Comment by dustin-rcg** [comment]
Can someone please explain **why** this solves the problem?
```
type Type<T> = T;
```

If all it does is indicate to swc that this is merely a type reference and not a value, then shouldn't swc be able to do this without the wrapper type? Would this be the same as what `tsc` does regarding [importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues)? See also [Type-Only Imports and Export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export).

Shouldn't swc be able to discern that these are type-only references, and do whatever magic that `Type<T>` does?

What makes it strange is that, in the same file, folks **are** using the imports as value types, but wrapped in an arrow function `type => FooBar` for the entity decorators. So I guess the import can't just be dropped. But then **what is the magic** that makes `Type<T>` work in this case??

**Comment by thekip** [comment]
@dustin-rcg it's because it will transpile into 

```ts
type Type<T> = T;

public myProperty: Type<TestClass>;

 ↓ ↓ ↓ ↓ ↓ ↓
__metadata("design:type", typeof Type === "undefined" ? Object : Type)
```
Without `Type<T>`
```ts
public myProperty: TestClass;

 ↓ ↓ ↓ ↓ ↓ ↓
__metadata("design:type", typeof TestClass === "undefined" ? Object : TestClass)
```

Note it uses `Type` which is not exists in runtime, normally it would use `TestClass` which is exists, and getter from here would be called: 

```ts
Object.defineProperty(exports, "TestClass", {
    enumerable: true,
    get: ()=>TestClass
});
```

@kdy1 could you elaborate more why this issue is considered resolved? The current implementation of SWC generates different code that TSC normally would do. And this breaks adoption of SWC in many backend projects because of this issue. 

Changing the frameworks code or code in projects codebase is not a solution. swc-jest docs states that this is "drop-in replacement for ts-node" which is actually not. Just changing one to another breaks everything. 

So maybe it's good idea to create an additional flag which will enable 1.2.205 transpilation behaviour? 

If you need minimal repo i prepared one, but think issue is already localized and there are no need in the additional repo. 

PS looking how may  "Cannot access before initialization" issues appears in github this problem is worse looking IMO

**Comment by kdy1** [comment]
Your input is wrong. It's wrong because ESM is a standard

**Comment by thekip** [comment]
Well, not every framework is ready for "standard", the ecosystem right now in painful transition process and such things make it even more painful. 
So having additional flag would be much appreciated. As well as documenting it somewhere. I spent more than 8 hours in total to find what was the reason it's not compiling.

**Comment by thekip** [comment]
I've created a related issue in NestJS GraphQL Repo https://github.com/nestjs/graphql/issues/2568
