### ISSUE TITLE
Detailed control of compat pass

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5052]
### Describe the feature

This is now possible thanks to https://github.com/swc-project/swc/pull/4758

This is required for some cases, like disabling `typeof` pass.

**Comment by magic-akari** [comment]
Some ideas.

1. Unify preset env and target env
    generate FeatureSet from browserlist, or generate FeatureSet from es target version. This means that es target version is also an env preset.
    And then apply the compat pass according the FeatureSet.  (Just like what env preset  does now)

2. reorgnize the compat pass if needed
    Since we know the final env target, we don't need to split one pass into different esXXXX pass to apply.(eg: regexp)
    We can also combine some related passes.(eg: es2015::spread, es2018::object_rest_spread)
    the esXXXX function API may be deprecated. 

3. pass FeatureSet to every compat pass.
    Maybe we have two methods to transform the syntax. The simple one need some feature X.
    Now we know if the final env target supports feature X.
    And we know whether a subsequent pass will be applied.
    If the target environment does not support feature X, we can use another syntax instead of feature X and convert it to a worse result in subsequent passes.

4. disable some pass by edit the FeatureSet
    If we enable some Feature from the start, corresponding pass will be disabled.
    We can expose it as a config to the user. [This is what esbuild does](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#01446).

**Comment by kdy1** [comment]
> pass FeatureSet to every compat pass.

I think we can use `Optional` for each features and pass `FeatureSet` only to `esxxxx()`

**Comment by Austaras** [comment]
I don't believe 3 would be useful.
