### ISSUE TITLE
Compiling `import * as`  results incorrect output in typescript 

### ISSUE THREAD

**Issue by mrbayrmagnai** [swc-project/swc#5054]
### Describe the bug

I tried this typescript code to compile es2017. It results wrong code. Output code throws error `Refference Error`.

### Input code

```typescript
import * as deff from 'sdf';


export default {
  deff
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2017"
  },
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.206&code=H4sIAAAAAAAAA1PIzC3ILypR0FJILFZISU1LU0grys9VUC9OSVO35uLiSq0ASwNlEktzShSquRTAqrhqASevvRo5AAAA&config=H4sIAAAAAAAAAy2NwQrDMAxD%2F0XnHLZdBvmHfYRxvbHS1MF2YKXk35dAb0J6kk6szsgnKpmLTeXHHvRDRhxVnO1bAwnhw3rT5pKwCKtRqDlyWJM%2BYrKPxCiJP273J4bl2ozlRfWiEooubZP5MacHzFqK7quj9z%2Fc9hIXiQAAAA%3D%3D

### Expected behavior

Output code doesn't have to throw any error.

### Actual behavior

It throws an error. Because `deff` doesn't exist

### Version

1.2.206

**Comment by magic-akari** [comment]
We should handle the binding ident.

another case:

```JavaScript
import * as deff from 'sdf';

export const a = {
  deff
}
```

**Comment by kdy1** [comment]
Oh this sounds like a huge one
