### ISSUE TITLE
Question: how to get comments?

### ISSUE THREAD

**Issue by anurbol** [swc-project/swc#506]
It's me again :') 

I am trying to understand how should comments be extracted. So I have this code (simplified to save your time): 

```
    let comments: Comments = Default::default();
    let mut parser = Parser::new_from(session, Capturing::new(Lexer::new(
        ...,
        ...,
        ...,
        ...,
        Some(&comments),
    )));
    let module = parser.parse_typescript_module().unwrap();

    let mut it = module.body.iter();
    while let Some(node) = it.next() {
        visit_node(node, &uast);
    }

/* ... */

fn visit_node(node: &ModuleItem) {
  // how to get comments of the node?
}
```

What should my `visit_node` function look like to get the `node`'s (leading) comment? 

I can see that there's the `Comments::leading_comments(&self, pos: BytePos)` method, that accepts 
`BytePos`. What is that byte pos? Is it the `Span::lo` of the `node`? Just want to be sure. I hope this is a simple question that won't take much time.

**Comment by kdy1** [comment]
Yes. You can use span.lo() to get leading comments of a node.
Also you can get trailing comments by using traling_comments(span.hi())

I hope this help.

https://github.com/swc-project/swc/blob/3ec395ba7519a552d20d8120877fae2f270de887/ecmascript/codegen/src/comments.rs#L56-L72


https://github.com/swc-project/swc/blob/3ec395ba7519a552d20d8120877fae2f270de887/ecmascript/codegen/src/comments.rs#L37-L55

**Comment by anurbol** [comment]
@kdy1 Thank you so much! 😀
