### ISSUE TITLE
top-level `eval` breaks the variable renamer

### ISSUE THREAD

**Issue by chentsulin** [swc-project/swc#5068]
### Describe the bug

When using `eval()` with styled-components, it generates duplicated `_templateObject` functions.

### Input code

```typescript
import styled from 'styled-components';

const C1 = styled.div`
  position: absolute;
`;

const C2 = styled.div`
  position: absolute;
`;

const debug = eval('');
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.207&code=H4sIAAAAAAAAA5XLuwqAMAyF4T1Pka06KOhocfJFvDRKoTZiYsG3V1Bwdjz85%2FPrxrui6BnI4bzziuYZxcR3ixRVjAWYOIpiV2H7nkvnUw%2BIG4tXz7HBYRQOh5KF%2FgP1T%2BBoPJbbUBpCZkxu4QJigxVtowAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSw7DIAxE7%2BJ1tu2CO%2FQQiDoRFT95HKkIcfcCSpXdaGb8PI0%2BcGQaFStgmQo1qf2SIa2F4cQXpY0Uw1I5uQ9t5WAdDcZjRCFnMJndBvBG0Se%2F1wlyORZh4I5sOsK%2F2Qco5vc5jbZ%2BLeCT%2Bs247jxeV3EN%2BAFJDkBftAAAAA%3D%3D

### Expected behavior

It should not output duplicated function name: `_templateObject`.

### Actual behavior

It generates duplicated `_templateObject`:

```js
function _taggedTemplateLiteral(strings, raw) {
    if (!raw) {
        raw = strings.slice(0);
    }
    return Object.freeze(Object.defineProperties(strings, {
        raw: {
            value: Object.freeze(raw)
        }
    }));
}
function _templateObject() {
    var data = _taggedTemplateLiteral([
        "\n  position: absolute;\n"
    ]);
    _templateObject = function _templateObject() {
        return data;
    };
    return data;
}
function _templateObject() {
    var data = _taggedTemplateLiteral([
        "\n  position: absolute;\n"
    ]);
    _templateObject = function _templateObject() {
        return data;
    };
    return data;
}
import styled from "styled-components";
var C1 = styled.div(_templateObject());
var C2 = styled.div(_templateObject());
var debug = eval("");
```

### Version

1.2.207

**Comment by chentsulin** [comment]
This bugs was initially introduced by `v1.2.204`.

**Comment by kdy1** [comment]
This can be fixed by creating a new mark (named `specified_mark`) to `resolver` and creating marks from `resolver` with the specified mark as the parent.

**Comment by Thisen** [comment]
This issue also comes up when using the `@swc/plugin-loadable-components` as it utilizes `eval`.
