### ISSUE TITLE
Generic function as a generic function argument fails (`An arrow function is not allowed here`)

### ISSUE THREAD

**Issue by sliftist** [swc-project/swc#5077]
### Describe the bug

The code below fails to transpile. My apologies if this is a duplicate, I searched for an existing ticket, but couldn't find one.

### Input code

```typescript
Promise.all<<T>() => void>([]);
```

### Config

```json
{
    "jsc:" {
        "target": "es2022",
        "parser": {
            "syntax": "typescript",
        }
    }
}
```

### Playground link

https://play.swc.rs/?version=1.2.144&code=H4sIAAAAAAAAAz2MQQrEIBRD9%2F8UWdZNF7PU1l7CE0z5doSpgv1CQbx7ZZAJZJGQvC8LfEoaFQfLprE4O93aKawWDg0rajO0p3gJrnSyfEI8eiu5sCEKHtO%2FVqiErg6cO62vfIm7hBQHFk51jxWQWUqOuM0vN2pE47rNSyznm7OdXuoBc33z66QAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWLLnKHHsK4SnDxD40CDcZ3rx1cspNmnp4qfeBorVSsgGVMOJPaL62kZ2E48UVpIUWPNhvArS9WdtaOMMzDmF6HnMETWCj65LdzyFyORRi4K5v28Cdbd8X8PkZQr3%2BX80ntdsw7j9cEVQ5uPx%2Bqcl%2B4AAAA

### Expected behavior

I am 95% sure this shouldn't throw, although it could just be a configuration issue on my end.

The typescript playground doesn't throw: https://www.typescriptlang.org/play?jsx=0&module=1#code/AoJw9gtglgzgpgOgIYBsUB50BUB8AKASgAIBeHIgNzCgBN8BtAXQIG4g

### Actual behavior

Throws `An arrow function is not allowed here`

### Version

1.2.207

**Comment by kdy1** [comment]
Closing as fixed

https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAz2MQQrEIBRD9%2F8UWdZNF7PU1l7CE0z5doSpgv1CQbx7ZZAJZJGQvC8LfEoaFQfLprE4O93aKawWDg0rajO0p3gJrnSyfEI8eiu5sCEKHtO%2FVqiErg6cO62vfIm7hBQHFk51jxWQWUqOuM0vN2pE47rNSyznm7OdXuoBc33z66QAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWLLnKHHsK4SnDxD40CDcZ3rx1cspNmnp4qfeBorVSsgGVMOJPaL62kZ2E48UVpIUWPNhvArS9WdtaOMMzDmF6HnMETWCj65LdzyFyORRi4K5v28Cdbd8X8PkZQr3%2BX80ntdsw7j9cEVQ5uPx%2Bqcl%2B4AAAA
