### ISSUE TITLE
Converted CommonJS cannot be imported using native ESM

### ISSUE THREAD

**Issue by sounisi5011** [swc-project/swc#5084]
### Describe the bug

In swc 1.2.206 and later, exported fields are assigned to the `exports` variable using the internal function `_export()`. However, the native ESM in Node.js cannot discover dynamically defined export fields.

### Input code

```typescript
import path from 'path';

export const PACKAGE_ROOT = path.resolve(__dirname, '../..');

export function getFixturesPath(subpath: string): string {
    return path.resolve(__dirname, '../fixtures', subpath);
}
```

### Config

```json
// This config was generated by @swc/jest
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "transform": {
      "hidden": {
        "jest": true
      }
    }
  },
  "sourceMaps": "inline",
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.206&code=H4sIAAAAAAAAA32NMQvCMBCF9%2FyK29JCibviUEQdHFrEPdR6rQGTlMtFCuJ%2FNy0VN296cO%2F7nrGDJ4ah4Tt05C3IKcqNEDjOn9a7wFCXu1N53OtzVV1gO9cVYfCPJ2Za3wy5xmIBUqmVUjL%2F4V10LRvvoEc%2BmJFjoupEZyFeJ8saApNxff4N8BKQjjBV3d%2BhbtHJAhZZ2n2LD9YBty%2FSAAAA&config=H4sIAAAAAAAAAxWNQQrDMAwE%2F6JzDyHH%2FKGPELbS2sSykWRoCPp75duyO8M%2BUDXB8cBAUZKV9GbDHxxg9yBNUoaBv8BQPmRRk%2B7bvkE0gqxnl7asb8mZeKVKGpjJJPfwtE9J9Mah4Ra%2BClO4red50cLXSyypt9a5Krj%2FAe6AQguUAAAA

### Expected behavior

The converted CommonJS file can be imported using the `import` statement.

### Actual behavior

If you try to import on Node.js, which supports native ESM, the following error is thrown:

```
import { getFixturesPath, PACKAGE_ROOT } from './helpers/index.cjs';
                          ^^^^^^^^^^^^
SyntaxError: Named export 'PACKAGE_ROOT' not found. The requested module './helpers/index.cjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './helpers/index.cjs';
const { getFixturesPath, PACKAGE_ROOT } = pkg;
```

### Version

1.2.206

### Additional context

This problem is caused by the fact that the exported fields are not statically defined. Therefore, if the following statement exists in the generated code, this error will not be thrown.

```diff
  "use strict";
  Object.defineProperty(exports, "__esModule", {
      value: true
  });
  function _export(target, all) {
      for(var name in all)Object.defineProperty(target, name, {
          get: all[name],
          enumerable: true
      });
  }
+ exports.PACKAGE_ROOT = exports.getFixturesPath = void 0;
  _export(exports, {
      PACKAGE_ROOT: ()=>PACKAGE_ROOT,
      getFixturesPath: ()=>getFixturesPath
  });
  ...
```

**Comment by magic-akari** [comment]
Could you try `importInterop: node`

**Comment by sounisi5011** [comment]
@magic-akari 
> Could you try `importInterop: node`

What hierarchy in the config should it be written in?
I am checking [the documentation](https://swc.rs/docs/configuration/swcrc) and [the JSON schema](https://json.schemastore.org/swcrc), but I cannot find `importInterop`.
I don't know if it should be in the root of the config, under `"jsc": { ... }`, or under `"module": { ... }`.

**Comment by magic-akari** [comment]
@sounisi5011 Sorry, I didn't notice that the swc containing the  `importInterop `  hasn't been released yet.

**Comment by kdy1** [comment]
I'll publish a new version. Thank you for the hard work!

I was too busy because of the new typescript type checker 🤣

**Comment by sounisi5011** [comment]
Thanks for the very quick release!!!
When `@swc/core@1.2.208` is released I will try `importInterop`.

**Comment by magic-akari** [comment]
Note: the reexport syntax(`export * from "mod"`) is still not recognized by node until https://github.com/nodejs/cjs-module-lexer/pull/71  is merged.

**Comment by sounisi5011** [comment]
Using [`@swc/core@1.2.208`](https://www.npmjs.com/package/@swc/core/v/1.2.208) and `importInterop` together, I was able to solve this issue. Thank you very much!

[playground link](https://play.swc.rs/?version=1.2.208&code=H4sIAAAAAAAAA32NMQvCMBCF9%2FyK29JCibviUEQdHFrEPdR6rQGTlMtFCuJ%2FNy0VN296cO%2F7nrGDJ4ah4Tt05C3IKcqNEDjOn9a7wFCXu1N53OtzVV1gO9cVYfCPJ2Za3wy5xmIBUqmVUjL%2F4V10LRvvoEc%2BmJFjoupEZyFeJ8saApNxff4N8BKQjjBV3d%2BhbtHJAhZZ2n2LD9YBty%2FSAAAA&config=H4sIAAAAAAAAAxWNQQrDMAwE%2F6JzDyHH%2FKCHPsLYamsTS0KSoSH475Vvu8sMe0OzDMcNktRQV7KLPP3gAL8ELWsVh%2FkAT%2FpBjxlt3%2FYNYtFE9mbty%2FrWUpBWamiBuQ6cMzzjoRlfSSzcSmclDLdzGScuvHZh9Sc5KksgxGUB6zxa5t6ZmsGcf%2Fzj3UOrAAAA)

Apparently [the reexport syntax is still not available](https://github.com/swc-project/swc/issues/5084#issuecomment-1172318749), but that seems to be a https://github.com/nodejs/cjs-module-lexer/pull/71 issue, so I'm closing this issue.

**Comment by wintercounter** [comment]
I'm on 1.2.210 but `importInterop` is still not available. Did I miss something?

```
1: failed to deserialize .swcrc (json) file: unmatched data: 32:1
2: unknown field `importInterop`, expected one of `strict`, `strictMode`, `lazy`, `noInterop`, `ignoreDynamic` at line 32 column 1
```
