### ISSUE TITLE
Regex - exp property is string literal

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#511]
The definition of a regular expression literal is currently as follows:

```rust
#[ast_node("RegExpLiteral")]
pub struct Regex {
    pub span: Span,

    #[serde(rename = "pattern")]
    pub exp: Str,

    #[serde(default)]
    pub flags: Option<RegexFlags>,
}
```

Note `exp: Str` and `Str` is defined as the following:

```rust
#[ast_node("StringLiteral")]
pub struct Str {
    pub span: Span,

    pub value: JsWord,

    /// This includes line escape.
    #[serde(default)]
    pub has_escape: bool,
}
```

Question: Why is it defined as a string literal? This would make me think it was something like `/"some string"/`. Is there something better this could be? In babel and the ts compiler it's just a string property.

Thanks!

**Comment by kdy1** [comment]
Hmm.. it seems like a mistake. Btw, Str is not "foo". `Lit::Str()` is. And Str is just a text with span.

**Comment by dsherret** [comment]
Yeah, it's not too bad for me and I easily work around it.

By the way, the regex flags are also a string literal:

```rust
pub type RegexFlags = Str;
```
