### ISSUE TITLE
jsx-runtime import should have .js extension

### ISSUE THREAD

**Issue by mohd-akram** [swc-project/swc#5113]
### Describe the bug

It seems that the issue in react-dnd/react-dnd#3423 is due to swc emitting the jsx-runtime import as `react/jsx-runtime` instead of `react/jsx-runtime.js`, which is a problem in ES6 mode.

### Expected behavior

swc should emit a valid jsx-runtime import statement in ESM mode.

### Version

1.2.168

**Comment by mischnic** [comment]
This shouldn't be necessary, there's an entry in the package exports for the extensionless version: https://unpkg.com/browse/react@18.2.0/package.json

See https://github.com/babel/babel/issues/12210

**Comment by mohd-akram** [comment]
Yeah, that was added in React 18. TBH I just ended up upgrading React to resolve this. Maybe this isn't worth changing.
