### ISSUE TITLE
Using function overloads reports a "... is defined multiple times" error [SWC 1.2.209]

### ISSUE THREAD

**Issue by sounisi5011** [swc-project/swc#5115]
### Describe the bug

In SWC 1.2.209, an error occurs when using [function overloads in TypeScript](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads).

### Input code

```typescript
function makeDate(timestamp: number): Date;
function makeDate(m: number, d: number, y: number): Date;
function makeDate(mOrTimestamp: number, d?: number, y?: number): Date {
  if (d !== undefined && y !== undefined) {
    return new Date(y, mOrTimestamp, d);
  } else {
    return new Date(mOrTimestamp);
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.209&code=H4sIAAAAAAAAA42NQQrCMBBF9znFd1MS6AlaSjfu3XiBaCYQNKOkCSVI726siLUiuBv%2BvP%2B%2BTXyM7sLw%2BkRbHUlG52mI2l8bcPIHCqrB49EK%2B8X6F1PDvM%2F8T3MX9uuhIukXln6lwU0AzkIabLoOiQ1Zx2RQVcifkZpZIFBMgcE0zgaZayyHy6BqCziBzgP96CwLT1pMdyxCm%2Fc2AQAA&config=H4sIAAAAAAAAA6tWyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpRqa2sB6iQk7CoAAAA%3D

### Expected behavior

No error occurs.

### Actual behavior

When using function overloads within TypeScript code, SWC reports "the name `makeDate` is defined multiple times" error.

### Version

1.2.209

**Comment by Austaras** [comment]
Well I forget about ts in #5092
