### ISSUE TITLE
Integration test for the plugin against published version

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#5117]
### Describe the feature

To prevent issues like https://github.com/swc-project/plugins/issues/48

Having tests under swc's workspace is not able to catch issues like this as it compiles against the latest TOT of codes itself. We need tests which pick up published versions of plugin to run against swc compiled against PR or given commit.

Currently, this is not an immediate blocker as we allow breaking changes under experimental flag, but we'll need this for the stable release.

**Comment by kdy1** [comment]
We now uses `@swc/plugin-jest` for integration tests
