### ISSUE TITLE
Non-intuitive AST node for default export function and class

### ISSUE THREAD

**Issue by iheyunfei** [swc-project/swc#5119]
### Describe the bug

I notice that `export default function foo() {}` will be parsed to `DefaultExportDecl`, which is expected.
But `export default function () {}` will be also parsed to `DefaultExportDecl`, which should be `DefaultExportExpr`

The problem is that every declaration must have a name in scope. The other AST node works great, but for the `DefaultExportDecl`, even though it is a declaration, it could be an expression actually.

### Expected behavior

The current `ExportDefaultDecl` is
```rust
pub enum DefaultDecl {
    #[tag("ClassExpression")]
    Class(ClassExpr),

    #[tag("FunctionExpression")]
    #[is(name = "fn_expr")]
    Fn(FnExpr),

    #[tag("TsInterfaceDeclaration")]
    TsInterfaceDecl(TsInterfaceDecl),
}
```

I wonder could we make it like 
```rust
pub enum DefaultDecl {
    #[tag("ClassExpression")]
    Class(ClssDecl),

    #[tag("FunctionExpression")]
    #[is(name = "fn_expr")]
    Fn(FnDecl),

    #[tag("TsInterfaceDeclaration")]
    TsInterfaceDecl(TsInterfaceDecl),
}
```

And for the case `export default function() {}` or `export default class {}`, we could parsed them to `ExportDefaultExpr`.

I guess this change will affect a lot of code. For me, it just needs me to write more code to handle it, so I'm ok with the current behaviors. Only raise this issue for being kind of neat freak.

### Version

latest

**Comment by kdy1** [comment]
No it should be `DefaultExportDecl`

The specification explicitly excludes function expressions and class expressions from `export default` + Expression

https://tc39.es/ecma262/#sec-exports

**Comment by magic-akari** [comment]
`DefaultExportDecl` will be hoisted.

```JavaScript 
// foo.js
import foo from "./foo.js";

foo(); // print foo

export default function () {
  console.log("foo");
}
```

```JavaScript
// bar.js
import bar from "./bar.js";

console.log(bar); // ReferenceError: Cannot access 'bar' before initialization

export default 1
```
