### ISSUE TITLE
Add ExprStmt?

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#512]
Right now the `Stmt` enum is as follows:

```rust
#[ast_node]
pub enum Stmt {
    #[tag("BlockStatement")]
    Block(BlockStmt),

    #[tag("EmptyStatement")]
    Empty(EmptyStmt),

    // ...etc...

    #[tag("*")]
    Expr(Box<Expr>),
}
```

So since it goes straight from the `Stmt` enum to the `Expr` there is no way to get a struct node for the expression statement that would have a span that may include the semi-colon (or I might be missing something... I'm new to Rust).

**Proposed Change**

```rust
#[ast_node]
pub enum Stmt {

    // ...etc...

    #[tag("ExpressionStatement")]
    Expr(ExprStmt),
}

#[ast_node("ExpressionStatement")]
pub struct ExprStmt {
    pub span: Span,

    pub expr: Box<Expr>,
}
```

**Comment by kdy1** [comment]
I published a new version of ast / parser / codegen with a fix.

**Comment by dsherret** [comment]
Wow, awesome! Thanks again @kdy1!
