### ISSUE TITLE
SWC outputs only `<br>` elements

### ISSUE THREAD

**Issue by johannesvollmer** [swc-project/swc#514]
We have switched from Babel to swc, which worked fine. In the next PR of our project, suddenly all elements created with `document.createElement(tag_name_const)` were turned into `<br>` elements, which of course breaks the whole website. This problem only occured on a MacBook in all browsers, but in no browser on a Windows laptop.

We had to temporarily switch back to Babel (which made it work again) because we had no time to investigate the issue. I plan to update this Issue later with more information, which is why I do not expect any bug fixing work to this issue right now. Our project is currently private but I want to try to reproduce the error from scratch later.

**Comment by kdy1** [comment]
Closed because there's nothing doable
