### ISSUE TITLE
When transfile for of syntax to ES5, swc use Symbol.iterator

### ISSUE THREAD

**Issue by 0xWOF** [swc-project/swc#5140]
### Describe the bug

When transfile for of syntax to ES5, swc use Symbol.iterator. But Symbol.iterator is ES6 Object.
Symbol can be polyfilled. So I think it is not "must be solved" issue.

Additionally, Babel and Typescript do not have this issue.

### Input code

```typescript
for (const item of [1, 2, 3]) {
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.210&code=H4sIAAAAAAAAA0vLL1LQSM7PKy5RyCxJzVXIT1OINtRRMNJRMI7VVKjmUgACrloArMkFVCYAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

do not use Symbol.iterator

Babel example

```
"use strict";

for (var _i = 0, _arr = [1, 2, 3]; _i < _arr.length; _i++) {
  var item = _arr[_i];
}
```

### Actual behavior

use Symbol.iterator

```
var _iteratorNormalCompletion = true, _didIteratorError = false, _iteratorError = undefined;
try {
    for(var _iterator = [
        1,
        2,
        3
    ][Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true){
        var item = _step.value;
    }
} catch (err) {
    _didIteratorError = true;
    _iteratorError = err;
} finally{
    try {
        if (!_iteratorNormalCompletion && _iterator.return != null) {
            _iterator.return();
        }
    } finally{
        if (_didIteratorError) {
            throw _iteratorError;
        }
    }
}

```

### Version

1.2.210

### Additional context

Babel, Typescript do not have this issue.

Babel example (defaults, ie 9)
```
"use strict";

for (var _i = 0, _arr = [1, 2, 3]; _i < _arr.length; _i++) {
  var item = _arr[_i];
}
```

https://babeljs.io/repl#?browsers=defaults%2C%20ie%209&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYewTgBAFAxiB2BnALhAlsgpgWwiYEA2gIwA0EATOQMwC6AlBAN4BQAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.18.7&externalPlugins=&assumptions=%7B%7D

Typescript example (ES5)

```
"use strict";
for (var _i = 0, _a = ['1', '2', '3']; _i < _a.length; _i++) {
    var item = _a[_i];
}
```

https://www.typescriptlang.org/play?target=1#code/GYewTgBAFAxiB2BnALhAlsgpgWwiYEA2gOQCMxANBMQEyXUDMxAugJQQDeAUAL5A

**Comment by magic-akari** [comment]
Note: TypeScript's option `downlevelIteration` is disabled by default.
