### ISSUE TITLE
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///path/to/data.json" needs an import assertion of type "json"

### ISSUE THREAD

**Issue by ghost** [swc-project/swc#5143]
### Describe the bug

It seems that SWC doesn't correctly compile module assertations for nodenext.  When compiling it removes the assertation and outputs code that breaks when run using node 18 with `TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///path/to/data.json" needs an import assertion of type "json"`.  

### Input code

```typescript
import data from './data.json' assert {type: 'json'};

console.log(data)
```

### Config

```json
{
  "test": ".*.ts$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true,
      "privateMethod": false,
      "functionBind": false,
      "topLevelAwait": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "importMeta": false,
      "jsx": false,
      "tsx": false
    },
    "transform": {
      "legacyDecorator": false,
      "decoratorMetadata": false
    },
    "baseUrl": "src",
    "paths": {
      "app/*": ["*"],
      "types/*": ["types/*"]
    },
    "target": "es2022",
    "loose": false,
    "keepClassNames": false,
    "externalHelpers": false
  },
  "module": {
    "type": "nodenext",
    "strict": true,
    "strictMode": true,
    "noInterop": false,
    "lazy": false
  },
  "sourceMaps": true,
  "inlineSourcesContent": true,
  "emitSourceMapColumns": true,
  "minify": true
}
```

### Expected behavior

I would expect that it shouldn't remove assertations when compiling to JS.  

### Actual behavior

The output code ends up being:

```
import data from './data.json'  // this here is the issue
console.log(data);
//# sourceMappingURL=../src/index.js.map
```

With the assertation removed, which then breaks as soon as you try run it.  

When compiling with typescript the same output code looks like:

```
import data from './data.json' assert { type: 'json' };
console.log(data);
//# sourceMappingURL=../src/index.js.map
```

### Version

1.2.204

**Comment by kdy1** [comment]
Use `keepImportAssetions`.

Also, please search issues before filing one

**Comment by kdy1** [comment]
It's documented at https://swc.rs/docs/configuration/compilation#jscexperimentalkeepimportassertions
