### ISSUE TITLE
`this` get's transpiled to `(void 0)` in object getters in `CommonJS` mode

### ISSUE THREAD

**Issue by wintercounter** [swc-project/swc#5162]
### Describe the bug

`this` get's transpiled to `(void 0)` in object getters in `CommonJS` mode.

Babel doesn't touch it: https://babeljs.io/repl/#?browsers=node%2010&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=MYewdgzgLgBCBGArGBeGBvAUDGBDAXDAIwA02MA5gKazwAUAlBuQJABONArm2DFABYBLCADpc5AL6YJQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-3%2Ctypescript&prettier=false&targets=Node-18&version=7.18.8&externalPlugins=&assumptions=%7B%7D

### Input code

```typescript
const obj = {
  a: 1,
  get b() {
  	return this.a
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "transform": {
      "hidden": {
        "jest": true
      }
    }
  },
  "sourceMaps": "inline",
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.210&code=H4sIAAAAAAAAA0vOzysuUchPylKwVajm5VJQSLRSMNQBMdJTSxSSNDQhopxFqSWlRXkKJRmZxXqJIJFaXq5aAAxN2nw9AAAA&config=H4sIAAAAAAAAAxWNQQrDMAwE%2F6JzDyHH%2FKGPELbS2sSykWRoCPp75duyO8M%2BUDXB8cBAUZKV9GbDHxxg9yBNUoaBv8BQPmRRk%2B7bvkE0gqxnl7asb8mZeKVKGpjJJPfwtE9J9Mah4Ra%2BClO4red50cLXSyypt9a5Krj%2FAe6AQguUAAAA

### Expected behavior

`this` should be untouched, regardless of the target module.

### Actual behavior

`this` becomes `(void 0)`

### Version

1.2.210

**Comment by magic-akari** [comment]
duplicate #5157

**Comment by kdy1** [comment]
Closing as duplicate
