### ISSUE TITLE
Plugin template should use latest versions

### ISSUE THREAD

**Issue by ahhshm** [swc-project/swc#5163]
### Describe the bug

I get this error in the plugin template created with `swc plugin new --target-type wasm32-wasi`:
```
error[E0433]: failed to resolve: could not find `Serialized` in `swc_plugin`
   |
18 | #[plugin_transform]
   | ^^^^^^^^^^^^^^^^^^^ could not find `Serialized` in `swc_plugin`
   |
   = note: this error originates in the attribute macro `plugin_transform` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I don't know why no one else mentioned that before. Apparently this started happening since `swc_plugin = "0.72.0"`

### Expected behavior

Well, that error shouldn't happen :)

### Version

`swc --version`:
```
SWC 0.76.1
```

`rustup --version`: 
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.62.0 (a8314ef7d 2022-06-27)`
```

**Comment by kdy1** [comment]
Can you try `cargo update`?

**Comment by ahhshm** [comment]
Thanks for the swift response. I ran `cargo update`:
```
 ➜  cargo update
    Updating crates.io index
    Updating hashbrown v0.12.1 -> v0.12.2
    Updating swc_common v0.22.0 -> v0.22.1
```
But I still get the error.

**Comment by kdy1** [comment]
Please use `swc_common@0.23`

https://crates.io/crates/swc_common

**Comment by ahhshm** [comment]
I still get the error though. Actually, I just started a fresh swc plugin with `swc plugin new --target-type wasm32-wasi` and these dependencies (which are the defaults):
```toml
serde = "1"
swc_plugin = "0.76.0"
```
I still get the error when building the project.

**Comment by kdy1** [comment]
You should update other crates too

**Comment by kdy1** [comment]
cc @kwonoj
We may need a build script to replace default versions

**Comment by ahhshm** [comment]
> You should update other crates too

Well, all of the crates are in their latest version. I'm sorry, I don't understand what you mean by "other crates" because `serde` and `swc_plugin` are the only crates in a fresh swc plugin.

**Comment by kdy1** [comment]
Can you try updating `swc_plugin` again?

https://github.com/swc-project/swc/commit/793c423a2438bff1db05162bc552bcde6d05a67c should fix it

**Comment by ahhshm** [comment]
Yes, that fixed it. Thank you.
