### ISSUE TITLE
swcx (pure rust CLI) doesn't write sourcemap file

### ISSUE THREAD

**Issue by alexeagle** [swc-project/swc#5171]
### Describe the bug

Trying to use the pure rust CLI for performance under Bazel, thanks @kwonoj for the fix in #5124 but hit the next problem.

### Input code

```typescript
1
```

### Config

```json
{
  "sourceMaps": true
}
```

### Expected behavior

should write a sourcemap file at the `--source-maps-target` path

### Actual behavior

no sourcemap file is written anywhere that I can find

### Version

1.2.211

### Additional context

Here's my repro:

```
$ wget https://registry.npmjs.org/@swc/core-linux-x64-gnu/-/core-linux-x64-gnu-1.2.211.tgz
$ tar -xzvf core-linux-x64-gnu-1.2.211.tgz
$ chmod u+x package/swc
$ echo 1 > input.ts
$ jq --null-input '.sourceMaps = true' > .swcrc
$ ./package/swc compile input.ts --source-maps true --out-file my.js --source-maps-target my.js.map
$ ls
core-linux-x64-gnu-1.2.211.tgz  input.ts  my.js  package
```

I can't find `my.js.map` anywhere, and can't find another way to invoke the CLI such that this file is written.

**Comment by kwonoj** [comment]
Ugh, there seems stupid bug / unimplemeted to emit sourcemap with `--out-file`. Not an answer to close, but to confirm emission working if you try `--out-dir` instead

```
compile a.js --config-file ./.swcrc --out-dir ./boo
```

It emits sourcemap correctly.

**Comment by alexeagle** [comment]
hmm I can't get it to produce a sourcemap file with --out-dir either...

```
$ ./package/swc compile input.ts --config-file ./.swcrc --source-maps true --out-dir ./boo --source-maps-target ./boo/input.js.map
$ ls boo
input.js
```
similar without any `--source-maps-target`

**Comment by alexeagle** [comment]
interesting, `--config-file ./.swcrc` fails to read the config file (with the leading `./`) but works without it.
```
./package/swc compile input.ts --config-file .swcrc --source-maps true --out-dir ./boo --source-maps-target ./boo/input.js.map
$ ls boo
input.js  input.js.map
```
so there we go, yup
