### ISSUE TITLE
set AMD module id from cli

### ISSUE THREAD

**Issue by leafo** [swc-project/swc#522]
There doesn't appear to be a way to individually set the `moduleId` when compiling an AMD module using the command line tool. It is possible to set the the `moduleId` in the config file, but that would be reused across all modules compiled with that project's config.

Potential solutions:

* Add a `--module-id=hello` CLI argument to set it
* Add a way to override config values from CLI, something like `--config module.moduleId=hello`

**Comment by kdy1** [comment]
Fixed with @swc/cli@0.1.20

**Comment by leafo** [comment]
Wow, that was fast. Thanks for adding it, will test it out soon
