### ISSUE TITLE
emitted modules incompatible with node cjs

### ISSUE THREAD

**Issue by vincentcr** [swc-project/swc#5220]
### Describe the bug

Since 1.2.206, emitted exports are no longer compatible with "standard" node-style exports. 

In 1.2.205 and earlier versions, exports would be done with `exports.xyz = ...`.  Now they are emitted as as readonly properties on the `exports` object. This breaks code like jest.spyOn or sinonjs which rely on the ability to mutate exports. 

I realize the new output is more "correct" and closer to the esm specs, however it is incompatible with with most node code out there, and also with the output generated by Typescript when the `"module": "commonjs"` is set. 

Notably it breaks packages like `sinonjs`. Attempts to mock exported methods will fail with errors like:
```TypeError: Descriptor for property foo is non-configurable and non-writable```

### Input code

```typescript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.foo = foo;
function foo(x) {
    return x + 1;
}
```
```


### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    },
    "target" : "es2021"
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.215&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMz1NIy8%2FXqNBUqOZSAIKi1JLSojyFCgVtBUOuWgDDJZOCKwAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSw6DMAxEr1J5zaJUahfcgUNEwaCg%2FGSbqhHK3esIWnb2zPiNd1jZwrBDNsRIbeISxXxgACkZ2ZLLAh0IqzQbz1h1MbSgaAT5ce%2BfavuUGM9AB8FFN5cGsylkQubLMnHxv2RVVkjT1gQtFnJW%2FsljHdOkptCmSntIS5UZUlwZ6tV03jgeT9xxgfHdyMe%2F%2BgRExd36F9T6BTsBftP6AAAA

### Expected behavior

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.foo = foo;
function foo(x) {
    return x + 1;
}
```

### Actual behavior

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "foo", {
    enumerable: true,
    get: ()=>foo
});
function foo(x) {
    return x + 1;
}
```

### Version

1.2.215

**Comment by kwonoj** [comment]
dupe: https://github.com/swc-project/swc/issues/5205

**Comment by kdy1** [comment]
See pinned issue
