### ISSUE TITLE
all loop code needs to be put into a _loop function

### ISSUE THREAD

**Issue by wsjhdwzq** [swc-project/swc#5270]
### Describe the bug

in a for loop, declare a variable with `let` is different with `var`, and `let` will be transformed to `var` when target set to `ES5`, sometimes this transform will cause a unexpected result, like this:
```
for(let i=0; i<5; i++){
  //when you use var to declare i, console will log the same value for 5 times
  setTimeout(()=>console.log(i), 0);
}
```
when using `swc` to transform the code above, the result will be:
```
var _loop = function(i) {
    setTimeout(function() {
        return console.log(i);
    }, 0);
};
for(var i = 0; i < 5; i++)_loop(i);
```
all loop code was put into a `_loop` function, but if you dont use `i`, and declare a new variable in the loop, just like this
```
for(let i=0; i<5; i++){
  let j = Math.random();
  setTimeout(()=>console.log(j), 0);
}
```
the code wont be put into a `_loop` function

### Input code

```typescript
for (let i = 0; i < 10; i++) {
    let j = Math.random();
    setTimeout(()=>{
        console.log(j);
    }, 0);
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAA0vLL1LQyEktUchUsFUwsAZSNgqGIFpbW1OhmpdLAQhA0llAad%2FEkgy9osS8lPxcDU1riFxxaklIZm5qfmmJhoamrR1UBwgk5%2BcV5%2Bek6uXkp2tkwZTX6igYgNi1AFJnLEt4AAAA&config=H4sIAAAAAAAAA0WMSw7DIBBD7zJrtu0id%2BghRnQSUfHTmEpFiLsXGqrsLPv5NXrB0tYos0J0JtRY%2BEMbiQ0Mqy4XMgMb1c4e0g0V1kPKRHAbm08JslZDwUW312myKWQV4Jo4Hv5P9iEK6fmeRaNSs%2FyEd%2BqXY%2F0cHgs8n18oc7pftgAAAA%3D%3D

### Expected behavior

var _loop = function _loop(i) {
  var j = Math.random();
  setTimeout(function () {
    console.log(j);
  }, 0);
};

for (var i = 0; i < 10; i++) {
  _loop(i);
}

### Actual behavior

for(var i = 0; i < 10; i++){
    var j = Math.random();
    setTimeout(function() {
        console.log(j);
    }, 0);
}

### Version

1.2.218

**Comment by Austaras** [comment]
No, this case need to be wrapped because there's a function captured lexically declared `j`.
