### ISSUE TITLE
Parser reports syntax error with conditional expression, arrow fns and brackets

### ISSUE THREAD

**Issue by robations** [swc-project/swc#5274]
### Describe the bug

The parser syntax errors on valid TypeScript, involving:

- conditional expression
- arrow functions
- brackets ()

# [Example 1](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAAz2KuwqEMBQF%2B3zFlL4aW%2BXqtxjJVu5VYgIB9d%2FXCO5Uh5nj0rb6wLzqHvgoQjF1aPxa5xvsO0%2BNy1IiA4fhxrsQvWIREXJ7bGYk5Vuiomipmcp%2F6t5UYx%2FZm6s3P7I0fzuCAAAA&config=H4sIAAAAAAAAA21PywqDQAz8l5w91B6K%2BA%2F9hhK2UbbdR9isUpH990bxQaGnJDOTZGaGlxhoZ2BMQmnpZAoZP9BCnpjEJMsZKsiiUIdOqOiAqaesEpLrpW6UdjEKbYIKvA22m5ZjJnpOJHJSGHpHC5UjOxrJHdSbiB%2FGoUhAT%2FKLd38wTnbETFojn5Sl5ugFO0y2vuzWi5r38TlsDjTgGuIG5TS9n5H7Jsxp0JnCuO6s0fUbQClfija3Dj4BAAA%3D) - original (fails)

```ts
export const fn = (a: number, b: number|null) => {
    return b === null
        ? x => x * (1 + a)
        : x => x + b
    ;
};
```

Output:

```
  x Expected ':', got ';'
   ,-[input.ts:5:5]
 5 | ;
   : ^
   `----
...
```

# [Example 2](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAAz2KQQ6CMBQF9z3FLFtwwxby9SyU1BV%2BSG2TJurdsY0yq5eZF8q%2BxcSy6TNxVwQ7j2h%2B%2BBAv%2BP98a15Xh1x5Gb7EkHJUPCJCbc1WbthSf4UOO9AzO3fGkV%2Fr8U1O5jOZA6O1B4CEAAAA&config=H4sIAAAAAAAAA21PywqDQAz8l5w91B6K%2BA%2F9hhK2UbbdR9isUpH990bxQaGnJDOTZGaGlxhoZ2BMQmnpZAoZP9BCnpjEJMsZKsiiUIdOqOiAqaesEpLrpW6UdjEKbYIKvA22m5ZjJnpOJHJSGHpHC5UjOxrJHdSbiB%2FGoUhAT%2FKLd38wTnbETFojn5Sl5ugFO0y2vuzWi5r38TlsDjTgGuIG5TS9n5H7Jsxp0JnCuO6s0fUbQClfija3Dj4BAAA%3D) — Parenthesise first arrow fn (fails)

```ts
export const fn = (a: number, b: number|null) => {
    return b === null
        ? (x => x * (1 + a))
        : x => x + b
    ;
};
```

# [Example 3](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAAz2KOw6DMBAFe59iShPSpAUtnAVHTgULcmzJUpK7g8NnqqeZ5%2FMyh8hz1nfkpQh2aNA0OR%2FuuHN%2BNY1jhXR8DBvBxxQUh4hQ2t8WenK5ZW7YBzVDdaUGe7Qat%2BvW%2FFqzAk0FsAqEAAAA&config=H4sIAAAAAAAAA21PywqDQAz8l5w91B6K%2BA%2F9hhK2UbbdR9isUpH990bxQaGnJDOTZGaGlxhoZ2BMQmnpZAoZP9BCnpjEJMsZKsiiUIdOqOiAqaesEpLrpW6UdjEKbYIKvA22m5ZjJnpOJHJSGHpHC5UjOxrJHdSbiB%2FGoUhAT%2FKLd38wTnbETFojn5Sl5ugFO0y2vuzWi5r38TlsDjTgGuIG5TS9n5H7Jsxp0JnCuO6s0fUbQClfija3Dj4BAAA%3D) — Parenthesise second arrow fn (compiles OK)

```
export const fn = (a: number, b: number|null) => {
    return b === null
        ? x => x * (1 + a)
        : (x => x + b)
    ;
};
```

# [Example 4](https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAAz3KPQ6AIBQD4J1TdPRvcYU8PYsYnPBhEBIS9e4KCXZqvtakw%2FmA1fEZsDEIzSLBcdfGD9C13hytbUETLoEv3oToGRpEhLwVzZmR8i2hw%2FijrNhDF1TiUeIFPAYOwnwAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm0XpeQOPYRxleDgHxoFGozvXju4ZCfNPD0V2mBpLpSNgKVPOKKaL82kR2ZYcVlpIkWLFuPBtS1GVtaGMB63%2B6vVPiXwACYKLrrl6DKbQhYGrsrE1f%2FJ2lwhffYelPPf6XxSvRzjzuE9QJWd6w%2B6QIF4uAAAAA%3D%3D) — Simplify first arrow fn (compiles OK)

```ts
export const fn = (a: number, b: number|null) => {
    return b === null
        ? x => x * 1
        : x => x + b
    ;
};
```

### Input code

```typescript
Several examples, will add in markdown section for clarity.
```

### Config

```json
See links in examples
```

### Playground link

See examples

### Expected behavior

All examples above are expected to compile without errors (should be valid TypeScript). An expanded version of Example 1 was previously compiling okay with `tsc`.

### Actual behavior

Syntax error

### Version

1.2.218

### Additional context

Also tried removing whitespace, but it doesn't seem to affect the behaviour.

**Comment by kdy1** [comment]
Closing as fixed.

https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAz2KuwqEMBQF%2B3zFlL4aW%2BXqtxjJVu5VYgIB9d%2FXCO5Uh5nj0rb6wLzqHvgoQjF1aPxa5xvsO0%2BNy1IiA4fhxrsQvWIREXJ7bGYk5Vuiomipmcp%2F6t5UYx%2FZm6s3P7I0fzuCAAAA&config=H4sIAAAAAAAAA21PywqDQAz8l5w91B6K%2BA%2F9hhK2UbbdR9isUpH990bxQaGnJDOTZGaGlxhoZ2BMQmnpZAoZP9BCnpjEJMsZKsiiUIdOqOiAqaesEpLrpW6UdjEKbYIKvA22m5ZjJnpOJHJSGHpHC5UjOxrJHdSbiB%2FGoUhAT%2FKLd38wTnbETFojn5Sl5ugFO0y2vuzWi5r38TlsDjTgGuIG5TS9n5H7Jsxp0JnCuO6s0fUbQClfija3Dj4BAAA%3D

https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAz2KQQ6CMBQF9z3FLFtwwxby9SyU1BV%2BSG2TJurdsY0yq5eZF8q%2BxcSy6TNxVwQ7j2h%2B%2BBAv%2BP98a15Xh1x5Gb7EkHJUPCJCbc1WbthSf4UOO9AzO3fGkV%2Fr8U1O5jOZA6O1B4CEAAAA&config=H4sIAAAAAAAAA21PywqDQAz8l5w91B6K%2BA%2F9hhK2UbbdR9isUpH990bxQaGnJDOTZGaGlxhoZ2BMQmnpZAoZP9BCnpjEJMsZKsiiUIdOqOiAqaesEpLrpW6UdjEKbYIKvA22m5ZjJnpOJHJSGHpHC5UjOxrJHdSbiB%2FGoUhAT%2FKLd38wTnbETFojn5Sl5ugFO0y2vuzWi5r38TlsDjTgGuIG5TS9n5H7Jsxp0JnCuO6s0fUbQClfija3Dj4BAAA%3D

https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAz2KOw6DMBAFe59iShPSpAUtnAVHTgULcmzJUpK7g8NnqqeZ5%2FMyh8hz1nfkpQh2aNA0OR%2FuuHN%2BNY1jhXR8DBvBxxQUh4hQ2t8WenK5ZW7YBzVDdaUGe7Qat%2BvW%2FFqzAk0FsAqEAAAA&config=H4sIAAAAAAAAA21PywqDQAz8l5w91B6K%2BA%2F9hhK2UbbdR9isUpH990bxQaGnJDOTZGaGlxhoZ2BMQmnpZAoZP9BCnpjEJMsZKsiiUIdOqOiAqaesEpLrpW6UdjEKbYIKvA22m5ZjJnpOJHJSGHpHC5UjOxrJHdSbiB%2FGoUhAT%2FKLd38wTnbETFojn5Sl5ugFO0y2vuzWi5r38TlsDjTgGuIG5TS9n5H7Jsxp0JnCuO6s0fUbQClfija3Dj4BAAA%3D

https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAz3KPQ6AIBQD4J1TdPRvcYU8PYsYnPBhEBIS9e4KCXZqvtakw%2FmA1fEZsDEIzSLBcdfGD9C13hytbUETLoEv3oToGRpEhLwVzZmR8i2hw%2FijrNhDF1TiUeIFPAYOwnwAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm0XpeQOPYRxleDgHxoFGozvXju4ZCfNPD0V2mBpLpSNgKVPOKKaL82kR2ZYcVlpIkWLFuPBtS1GVtaGMB63%2B6vVPiXwACYKLrrl6DKbQhYGrsrE1f%2FJ2lwhffYelPPf6XxSvRzjzuE9QJWd6w%2B6QIF4uAAAAA%3D%3D
