### ISSUE TITLE
Option to preserve comments?

### ISSUE THREAD

**Issue by elsassph** [swc-project/swc#528]
Is there an option to preserve source comments? This is sometimes necessary for instance for Webpack "magic" comments like `webpackChunkName` to name bundles.

**Comment by kdy1** [comment]
## Cause
Currently comments are stored based on span, but while fixer removes span, span-comment map is not updated.

There's two way to fix it.
 - Make fixer don't strip parens.
 - Update span-comment map while fixing ast.

I prefer second one, and this requires knowing how magic comments are shaped

@elsassph Can you share an example of magic comments?

**Comment by elsassph** [comment]
Thanks, I'll give it a try
