### ISSUE TITLE
Make `TransformPluginProgramMetadata::transform_context` lazy

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#5281]
### Describe the feature

This isn't worth RFC in my opinion, a small proposal to `TransformPluginProgramMetadata`.

Currently global context metadata to the plugin (`transform_context`, `experimental`) is eagerly passed into plugin's context per each plugin execution. We limit surface of `transform_context` at this moment, but as it'll grow it can be a burden for the serialization / deserialization.

Instead, as same as other metadata does (`comments`, `source_map`) propose to change it to be lazely requested from plugin only if needed. Same as comments / source_map it doesn't have any memoization and each call will requires fn invocation to call host side serialization / deserialization, but these are mostly static context avoid those repeated calls fairly easy.

Proposed pseudo interface will looks like below:

```

enum TransformPluginContext {
  FilePath,
  ...
}

impl TransformPluginProgramMetadata {
  // Returns specific context metadata corresponding to the key.
  fn get_context(context_key: TransformPluginContext): String;
  // Returns all context metadata as hashMap
  fn get_context_map(): HashMap<TransformPluginContext, String>;
  // Returns experimental context 
  fn get_experimental_context(context_key: &Str): Option<String>;
  fn get_experimental_context_map(): HashMap<String, String>;
}
```

get_context* represents current `transform_context`. This is a typed interface with known set of enum key, in result gaurantee to return value instead of `Option<T>`. But it still doesn't support return type deserialization - it'll be returned as string either can be plain string or JSON-stringified depends on the type of the context for the simplicity of the interface.

get_experimental* represents newly added experimental property. This is untyped interface to allow non-semver breaking changes.

**Comment by kwonoj** [comment]
This'll effectively makes to remove existing eager property (`transform_context` and `experimental`) as well.

Thoughts? @kdy1

**Comment by kdy1** [comment]
I think this way is better than passing them to all plugins.
(Actually I considered suggesting something similar when reviewing PR for experimental metadata.)

**Comment by kwonoj** [comment]
Let's do it then 🚢 :shipit: 

I hope this could be the last piece of breaking changes before stabilization (but.. who knows? ¯\_(ツ)_/¯)
