### ISSUE TITLE
SWC doesn't behave the same when it comes to symbol properties with experimental decorators

### ISSUE THREAD

**Issue by CMCDragonkai** [swc-project/swc#5291]
### Describe the bug

See:

```ts
function CreateDestroy() {
  return <
    T extends {
      new (...args: any []): { };
    },
  >(constructor: T) => {
    const constructor_ = class extends constructor {
      // This property will not exist
      public prop = 100;
    };
    return constructor_;
  };
}

@CreateDestroy()
class X {
  public static createX() {
    // return new this(); // Swap to this, and it works
    return new X();
  }
  public constructor () {
    console.log('X constructor');
  }
}

async function main () {
  const x = X.createX();
  // @ts-ignore
  console.log(x.prop);
}

void main();
```

When using `tsc`, both `return new this();` and `return new X();` behaves the same. They both construct the decorated class.

When using `swc`, only `return new this();` works. The `return new X();` ends up constructing the **undecorated** class, and not the decorated class.

Quick workaround, always use `return new this();` in decorated classes.

### Input code

```typescript
function CreateDestroy() {
  return <
    T extends {
      new (...args: any []): { };
    },
  >(constructor: T) => {
    const constructor_ = class extends constructor {
      // This property will not exist
      public prop = 100;
    };
    return constructor_;
  };
}

@CreateDestroy()
class X {
  public static createX() {
    // return new this(); // Swap to this, and it works
    return new X();
  }
  public constructor () {
    console.log('X constructor');
  }
}

async function main () {
  const x = X.createX();
  // @ts-ignore
  console.log(x.prop);
}

void main();
```

### Expected behavior

It should behave the same as `tsc`.

### Actual behavior

The `swc` thinks that `new X();` is for the non-decorated class.

### Version

1.2.218

### Additional context

First reported here: https://github.com/TypeStrong/ts-node/issues/1844

And discovered here: https://github.com/MatrixAI/js-workers/pull/4

**Comment by falkenhawk** [comment]
We are experiencing the same issue in our code.
@kdy1 the issue seems similar to those addressed already in  https://github.com/swc-project/swc/pull/4905 and https://github.com/swc-project/swc/pull/5263 but still there is something wrong, but I cannot find what exactly is wrong.

**Comment by kdy1** [comment]
Closing as fixed.


https://play.swc.rs/?version=1.3.24&code=H4sIAAAAAAAAA11RQU7DMBC85xVzayKVtFxbWlWCH9BDJISQcd1gEezI3pBGVf%2FO2nVDIJeNdnZnZsfHzkjS1uDRKUHqSXlydsgLnDPAKeqcwQP%2FAnuoEylz8BEKn1E98rIshav9CsIMeHktVjjjso4TlzmXbS6tYdJOknUr7AtstokhApjAb9hANsL7UWoCjrKLBfYf2qN1tlWOBvS6aWAs8Zb2lKba7r3RMg4x6%2F1ymTxdS7psqh0ARi9ZtvuXRXb1VEUHideTIC4yTlYpr%2BgtUYdwiG3mxTp0n3vRgmxszTmrAzSht%2B7TT%2F2EJSaLVn61piGMSqFpG1U2ts5n1XRmlvb5EuEHI3G8vfGX0ObGcA3%2FxNlU5XhFWGSzO%2FJ3ujbWqeyv0KkMeRYxpW%2BrD5GR134ATCLoV0YCAAA%3D&config=H4sIAAAAAAAAA0WOQQ7DIAwE%2F%2BJzDhWHHvhDH4GIE1EBRrYjFSH%2BXoLS5mbt7ozc4C0ebIPiWJDPS2pW9wELWguK51AUFlAZ0eai4AIremKnxAJW%2BcA%2Basc76oBQzMOYAUQiwT%2BSQg5bPfWeUmEUuSuX9%2Fhb9uFKtB5n0OYH0%2FmEfjsuLsjrGs4fvucDfqLKAAAA
