### ISSUE TITLE
Class constructor Visitor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by nbouvrette** [swc-project/swc#5309]
I was just trying out the SWC plugins (JavaScript, not Rust) and maybe I am missing something but documentation is hard to find. I tried to do this "Hello world" plugin and I am getting a `Class constructor Visitor cannot be invoked without 'new'`

```ts
import { Module, plugins, Program, transformSync } from '@swc/core';
import Visitor from '@swc/core/Visitor.js';

class testVisitor extends Visitor {
  visitModule(module: Module): Module {
    module.body.forEach((content) => {
      console.dir(content);
    });

    return module;
  }
}

function testPlugin() {
  return (program: Program) => new testVisitor().visitProgram(program);
}

const input = `const hello = "world";`;

const output = transformSync(input, {
  plugin: plugins([testPlugin()]),
});

console.log(output);
```

This triggers:

```sh
hello-world\lib\swc-plugin\index.js:23
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^

TypeError: Class constructor Visitor cannot be invoked without 'new'
    at new MessageModulesTransformer (hello-world\lib\swc-plugin\index.js:23:42)
    at hello-world\lib\swc-plugin\index.js:34:40
    at hello-world\node_modules\@swc\core\index.js:78:17
    at Compiler.transformSync (hello-world\node_modules\@swc\core\index.js:220:43)
    at Object.transformSync (hello-world\node_modules\@swc\core\index.js:325:21)
    at Object.<anonymous> (hello-world\lib\swc-plugin\index.js:37:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

I tried to open a [discussion](https://github.com/swc-project/swc/discussions/5298) but since I am getting no answers, I presume this is an issue.

**Comment by kwonoj** [comment]
Please do not create duplicate issue & discussions.

**Comment by nbouvrette** [comment]
@kwonoj I don't think I can delete the discussion. But I think this is probably an issue? if this is an issue, shouldn't we re-open this issue?

**Comment by kwonoj** [comment]
It isn't clear if it's coming from your setup or if there's an actual issue, at least it worked for me when I used those. Not getting answers in discussion doesn't automatically mean it needs to be looked as a bug.

**Comment by nbouvrette** [comment]
@kwonoj I honestly don't have anything special on my setup - it's a very basic app. How long should I wait before I open an issue? Unless there is some sort of "hello world" plugin doc you could refer me to so that I can compare my setup, I am pretty much blocked with this error

**Comment by kwonoj** [comment]
> How long should I wait before I open an issue

I don't believe you'll need to open an issue. Discussion is treated same as issue, unfortunately SWC is OSS that people's doing volunteer job to resolve things and we don't have someone actively looking those issues. If you can debug yourself it'd be appreciated, but otherwise opening issue will remain same unless someone have free time to look into.

**Comment by nbouvrette** [comment]
Ok, make sense - thanks. I'll see if there is anything else I can do on my end.
