### ISSUE TITLE
Invalid memory read when processing template literal

### ISSUE THREAD

**Issue by Maxdamantus** [swc-project/swc#5325]
### Describe the bug

Random bytes are printed in a generated string literal. Simple way of reproducing (on x86_64):

```sh
$ npm install @swc/core@=1.2.219
$ node -e 'const source = "`${100}testing`"; console.log(require("@swc/core").transformSync(source));'
{ code: '"".concat(100, "@ԡp0\\x7f\\0\\0\\x03\\0\\0\\0\\0\\0");\n' }
```

### Input code

```typescript
`${100}testing`
```

### Expected behavior

The code should contain the string "testing".

### Actual behavior

A string literal with random bytes is generated. In more complex code, this seems to usually result in a segmentation fault.

### Version

1.2.219

**Comment by Maxdamantus** [comment]
Will note that this seems to specifically occur when the text before the first subexpression is empty, ie, the issue occurs in template literals such as:
```js
`${0}test`
```
but not:
```js
`test${0}test`
```

**Comment by kdy1** [comment]
Okay, I investigated this and this was an issue of serialization/deserialization for plugins.
