### ISSUE TITLE
Expose dependency graph to users

### ISSUE THREAD

**Issue by roman01la** [swc-project/swc#533]
Hello! I'm exploring SWC as a base for a build tool. One of the things that I'd like to have, is a dependency graph starting at an entry point module. Ideally it could be separate CLI/API operation that emits dependency graph. Is this something SWC could have?

**Comment by kdy1** [comment]
@roman01la It would be not hard, but I doubt if it should be supported by swc.
Can you provide an usecase?

**Comment by kdy1** [comment]
I closed this by mistake

**Comment by nicksrandall** [comment]
@roman01la, I’m working on a similar tool. You can get this by generating an AST of the file and then searching for import declarations and then recursively searching those files for more imports.

**Comment by kdy1** [comment]
Closing as wontfix. This is too opinionated.
