### ISSUE TITLE
Relative paths without file extensions in TS code should have `.js` extension appended when compiled

### ISSUE THREAD

**Issue by skra-pa-pa** [swc-project/swc#5346]
### Describe the bug

In TypeScript code, import statements of other `.ts` files are written without the `.ts` file extension, but in node (or browser) with ESM, a path including file extension is used. SWC should add a `.js` file extension to relative imports from TS.

### Input code

```typescript
// foo.ts
const foo: string = "foo"
export { foo }

// index.ts
import someLib from "somLib"
import { foo } from "./foo"
console.log(foo)
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "module": {
    "type": "es6"
  },
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.220&code=H4sIAAAAAAAAA8vMLcgvKlFIy89XSCvKz1VQ0tMHspW4gISGJpe%2BvkJqRUFqcklqipVCJlalelnFSgA5CE0GRQAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWLLnKHHsK4SnDxD40CDcZ3rx1cspNmnp4qfeBorVSsgGVMOJPaL62kZ2E48UVpIUWPNhvArS9WdtaOMMzDmF6HnMETWCj65LdzyFyORRi4K5v28Cdbd8X8PkZQr3%2BX80ntdsw7j9cEVQ5uPx%2Bqcl%2B4AAAA

### Expected behavior

SWC would transform relative imports without file extension from TypeScript to imports with `.js` extension.

### Actual behavior

SWC does not transform these import paths, so Node fails when running them.

### Version

"@swc/core": "^1.2.220"

### Additional context

I have to use ESM with Node because some of my dependencies only work with it.

May be related to #1934, not sure

**Comment by magic-akari** [comment]
No, it's not true.
[TypeScript 🔗](https://www.typescriptlang.org/play?jsx=1&sourceMap=true#code/JYWwDg9gTgLgBAMwhRUIjgIgHQHokSYBQBAFAJRG65wCmAHmLQMYy0AmAXHKJLIslToseAtgBWAZ0xA) never touch the path in import/export statement.
Neither [Babel 🔗](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAMwhRUIjgIgHQHokSYBQBAFAJRG65wCmAHmLQMYy0AmAXHKJLIslToseAtgBWAZ0xA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ctypescript&prettier=false&targets=&version=7.18.9&externalPlugins=&assumptions=%7B%7D) nor [esbuild 🔗](https://hyrious.me/esbuild-repl/?version=0.14.48&mode=transform&input=import+foo+from+%22.%2Ffoo%22%0Afoo%28%29%0A%2F%2F+expected%3A+import+foo+from+%22.%2Ffoo.js%22&options=--loader%3Dts) supports this either.


- check https://github.com/microsoft/TypeScript/pull/35148

**Comment by MohamedLamineAllal** [comment]
yes. However there is an issue with paths translation. if you take 

```json
    "paths": {
      "@Core": ["./src/Core/index.js"]
    },  
```

Work ok on typescript when `module: "nodenext"` is used. The latest typescript does enforce us to add the extension. And the extension in `.js` and not `.ts`.

The paths resolver (import alias resolver). Should be able to handle that if it's esm. As it is, it doesn't.

And that breaks all the paths resolution for esm modules.
