### ISSUE TITLE
Variable named await

### ISSUE THREAD

**Issue by dispalt** [swc-project/swc#5359]
### Describe the bug

technically await is not a reserved keyword so you should be able to use it as a variable name.  However swc throws when you do, I can't easily change this code because it's a dependency

### Input code

```typescript
function timeout(await) {
  // Do stuff
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2021",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": true,
        "keep_classnames": true,
        "keep_fnames": true,
        "keep_private_props": true,
        "ie8": true,
        "safari10": true
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "",
    "bugfixes": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.221&code=H4sIAAAAAAAAA0srzUsuyczPUyjJzE3NLy3RSCxPzCzRVKjmUlDQ11dwyVcoLilNS%2BOqteYCAOqwK8MrAAAA&config=H4sIAAAAAAAAA2VPSQ7CMAz8i889AAeE%2BgfegEyYVIFsitOKqsrfSUsLQpxsz2KPJ7qLonaiyEmQ5k5Gn%2FlJLUE5FpVMzNRUWYU0W0FpKHPqkGeJHHaHfaVtCAJqc%2BrRkDPe6HHepYKLCSKrtVLsO4uZyiFaDLCb6QHEi7Is4tlBfmD9D8VkBs6oNcQPY3DaWmHNyex377mUmtqFW7%2FeHiOW9Ecq37hrRCPnVfjeBD8snuXneorqu9e%2B0%2Ba5RSrlBScipgBHAQAA

### Expected behavior

I would expect it to allow await as a parameter name.

### Version

1.2.221

**Comment by kdy1** [comment]
No you are using es module and `await` is reserved in a strict mode.
