### ISSUE TITLE
Import and export specifier node names

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#536]
I wanted to make the following recommendations on the AST node names for import specifiers:

* `ImportDefault` -> `ImportDefaultSpecifier`
* `ImportStarAs` -> `ImportStarAsSpecifier` (or `ImportNamespaceSpecifier` as babel calls it?)
* `ImportSpecific` -> `ImportNamedSpecifier`

The comments for these should also probably be updated (ex. on `ImportDefault` it should go from `/// e.g. `import foo from 'mod.js'`` to `/// e.g. `foo` in `import foo from 'mod.js'``).

Note that the export specifier names should probably be switch to be consistent as well if we decide to do this:

* `NamespaceExportSpecifier` -> `ExportNamespaceSpecifier`
* `DefaultExportSpecifier` -> `ExportDefaultSpecifier`
* `NamedExportSpecifier` -> `ExportNamedSpecifier`

**Comment by dsherret** [comment]
Also, `ImportSpecifier::Specific` should probably be changed to `ImportSpecifier::Named`. That would match up with `ExportSpecifier::Named`.

**Comment by kdy1** [comment]
I'm not sure if such consistency worth  a breaking change.
Maybe I can export aliased ones.

**Comment by dsherret** [comment]
Would it be a big inconvenience to current users? The library isn't 1.0 yet so shouldn't it not be a big deal to do any breaking change?

**Comment by kdy1** [comment]
@dsherret You are right, but updating swc_ecma_transforms would require lots of work.
