### ISSUE TITLE
No type metadata for decorated properties with user defined types

### ISSUE THREAD

**Issue by ItamarMalka** [swc-project/swc#5360]
### Describe the bug

some ORM libraries e.g sequelize depend on decorated property metadata in order to resolve the model properties for it.
When using swc as a transformer they fail because swc transforms any type into a  `"design:type": Object` even for simple types e.g `type a = string` / `type b = '123' | '456'` etc... 

### Input code

```typescript
type someType = string;
@decorator
function someDecorator(): string {
    return 'some decorator';
}

class Foo {
    @someDecorator()
    someProp: someType
}

console.log(returnType);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2019"
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.222&code=H4sIAAAAAAAAAyupLEhVKM7PTQ0BMWwVikuKMvPSrbkcUlKT84sSS%2FKLuNJK85JLMvPzwMpcYMIamlZQxQrVXApAUJRaUlqUp6AOUqUA161uzVXLxZWck1hcrOCWnw9V64BmFFgQJBZQlF9gBXcPWGt%2BXnF%2BTqpeTn66BsQKkIymNQDlWb%2BOuQAAAA%3D%3D&config=H4sIAAAAAAAAA02NSw7CMAxE7%2BJ1F8COrNn2EFbiVKnyk%2B1KRBV3J2lBsLM8b97ssIoFs0NFFuJxScuKTzCgrZJYDlVhAke2MGphAaO80WsCZcziC6fRirSgbY8vdUJ%2FtZkUHSr%2B2sgLaZ8huV2ud%2BivVNwWadjGdI9sSankVY4w5OAbGI9RujjI%2FKEP3xujmtUiyAAAAA%3D%3D

### Expected behavior

same as tsc output:

```
__decorate([
    someDecorator(),
    __metadata("design:type", String)
], Foo.prototype, "someProp", void 0);
```

### Actual behavior

```
_decorate([
    someDecorator(),
    __metadata("design:type", typeof someType === "undefined" ? Object : someType)
], Foo.prototype, "someProp", void 0);
```

### Version

1.2.222

### Additional context

The said example works properly when the type is inlined into the property, maybe there is a way to evaluate the type metadata in the same manner?

**Comment by sq-ricardo-pereira** [comment]
I'm using Nestjs 10 with swc/core 1.3.68 and the problem keeping. Unfortunately I can't use it in my project =/.

**Comment by kdy1** [comment]
Closing as the stc is now abandoned. https://github.com/swc-project/swc/issues/571#issuecomment-1915966297
