### ISSUE TITLE
`the name default is exported multiple times` in global declaration file

### ISSUE THREAD

**Issue by MarvelSQ** [swc-project/swc#5362]
### Describe the bug

in global declaration file, where declare multiple modules

### Input code

```typescript
declare module 'a' {
    const Component: any;
    export default Component;
}

declare module 'b' {
    const Component: any;
    export default Component;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.222&code=H4sIAAAAAAAAA0tJTc5JLEpVyM1PKc1JVVBPVFeo5lIAguT8vOISBef83IL8vNS8EiuFxLxKa7BMakVBflGJQkpqWmJpDpISa65aLq4UNPOSKDIPADGKN8ueAAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

no error report

### Actual behavior

```bash

  x the name `default` is exported multiple times
   ,-[input.ts:3:5]
 3 | export default Component;
   : ^^^^^^^^^^^^|^^^^^^^^^^^^
   :             `-- previous exported here
 4 | }
 5 | 
 6 | declare module 'b' {
 7 |     const Component: any;
 8 |     export default Component;
   :     ^^^^^^^^^^^^|^^^^^^^^^^^^
   :                 `-- exported more than once
   `----

Error: 
  > Exported identifiers must be unique
```

### Version

1.2.222

**Comment by magic-akari** [comment]
Yes, We should never touch anything in declare module block.
https://github.com/swc-project/swc/pull/5316#discussion_r930864523
