### ISSUE TITLE
Support Mangle Properties cache

### ISSUE THREAD

**Issue by dispalt** [swc-project/swc#5386]
### Describe the feature

So esbuild implements something for this:
https://esbuild.github.io/api/#mangle-cache its basically to make mangle properties worth it by persisting over multiple files.
Webpack via terserPlugin does the same with `nameCache` any chance we could get something like that in `swc`?

I like the way `esbuild` does it, it's subtle but you keep feeding it the same map and it grows. Obviously you can't use this feature and run files in parallel.

**Comment by dispalt** [comment]
Do you think you'll get to this, I guess I could take a crack at it...

**Comment by kdy1** [comment]
It would be nice if you work on it, but I'm not sure about the API

**Comment by kdy1** [comment]
Basically name mangler works in parallel, even for a single file

**Comment by dispalt** [comment]
Hmm, yeah that is a problem, but it must keep track of the renames successfully within a single file, right?  Otherwise I would imagine it wouldn't work...

**Comment by kdy1** [comment]
Yes

**Comment by kdy1** [comment]
I'll work on this
