### ISSUE TITLE
Number to Fixed unexpected error

### ISSUE THREAD

**Issue by gkio** [swc-project/swc#5397]
### Describe the bug

Hello everyone. 

I have a problem i am using the latest swc/core but when i use this kind of code it throws an error
`var hasToFixedBugs = (1000000000000000128).toFixed(0) !== '1000000000000000128'` it should keep the parenthesis and transform to string and then fixed to 0 but it removed and tries number to fixed 

```
var hasToFixedBugs = 1000000000000000128.toFixed(0) !== '1000000000000000128';
                     ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
```

`npm ls`

```
├── @swc-node/register@1.5.1
├── @swc/cli@0.1.57
├── @swc/core@1.2.223
```

### Expected behavior

keep the parenthesis

### Version

1.2.223

**Comment by Austaras** [comment]
This is better to be fixed at codegen

**Comment by gkio** [comment]
https://codesandbox.io/s/practical-mccarthy-58l3fc here is a sandbox to test the issue
