### ISSUE TITLE
Unexpected token `div`. Expected jsx identifier

### ISSUE THREAD

**Issue by Anoga** [swc-project/swc#5401]
### Describe the bug

swc throws the following error:

  x Unexpected token `div`. Expected jsx identifier
    ,-[input.tsx:26:5]
 26 | <div id={props?.id} className={props?.classes}>
    :  ^^^
    ----

Caused by:
    0: failed to process input file
    1: failed to process input file
    2: Syntax Error`

 It fails to compile the following Input code:

### Input code

```typescript
import React, { ReactNode } from 'react';
interface TitleCountsArrs {
  count: string | number;
  label: string;
}

interface WrapperItemProps {
  id?: string;
  classes: string;
  children?: ReactNode;
  titleCountsArrs?: TitleCountsArrs[];
  titleProps?: any;
  showSeeMore?: boolean;
}

interface ProfileItemTitleProps {
    titleProps?: any
}

interface ProfileItemTitleCountsProps {
  titleCountsArrs?: TitleCountsArrs[];
}

const WrapperItem: React.FC<WrapperItemProps> = (props) => {
  return (
    <div id={props?.id} className={props?.classes}>
      <ProfileItemTitle titleProps={...props.titleProps}>
        <ProfileItemTitleCounts titleCountsArrs={props?.titleCountsArrs} />
      </ProfileItemTitle>
      {props.children}
    </div>
  );
};

const ProfileItemTitle:React.FC<ProfileItemTitleProps> = (props) => {
    
    return (
        <div className="section-title">
            <div className="section-title-text font-xl">{props?.titleProps.sectionTitle}</div>
            {props?.children}
            <div className="section-right">
                <ProfileItemTitleRight  {...props?.titleProps} />
            </div>
        </div>
    );
}

const ProfileItemTitleCounts: React.FC<ProfileItemTitleCountsProps> = (props) => {
  if (!props?.titleCountsArrs.length) {
    return;
  }
  return (
    <ul className="profile-box-counts auto-flex text-gray">
      {props?.titleCountsArrs.map((item, index) => {
        return (
          <li key={`TITLE_COUNTS_${index}`}>
            <strong>{item.count}</strong>
            <label>&nbsp;{item.label}</label>
          </li>
        );
      })}
    </ul>
  );
};

WrapperItem.displayName = 'WrapperItem';
export default WrapperItem;
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment"
      }
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.223&code=H4sIAAAAAAAAA41VbWvbMBD%2Bnl%2BhhbHGUDvf68ZlhA0KWzbajH0Yo1XscyImS0aWNwfP%2F3168YvsmHb5EKTTc3fPPXeSSZZzIdED4Fheo9oudjwB1KBU8AxdCW25CheESRApjgHtiaSw5SWTxXshClQvEIr19gYVUhB2RH8RK7MDiFCdUHwA2p2Ei2bhRPoucJ6DuJeQfRU8t6FIcjfAVWSKiwKKkelEaCKAKVzPV9vlmJg6nlD98bOHmXwKgdlZ24oT%2F%2FMI8JkLUMYD5xQwm7BVLimhoNnu%2BxCG8mXMlz0to8H%2Fv4iriDFnhXRVawUIPm5vp1pGaINWuV55aBOZNAJkKRhaGca3CfmttN7UBnMXkKSxWu9wBr21Vb%2BJjI%2FympbiVL6pgyAwfsFg7D1nfG190%2Br73BN7g9Y9i%2FU0VHdifYNuQhpb6lrVqhGeUjHsZJyGuOmlnG30jJ4Imb%2BRrL20g5bLAmJJOPNNQctBkFexvoRKopQz6Vd0GY2EMaSCFm5oNn2dw6%2Fv40iQ15ILcjzJCdHZDj5ooMrSNd7l5vSr69qInrP1nOmeHxJn0F%2B4TDM9IilavZkfqIACO8qT1%2FbStlE%2FBs3FXSmpK1NuGfgHXvmxnWFcSu6nFCqkW%2BYfBT4vxzN5mT7D%2BWpFVBnXiLAEKmeuZsdK8aAE%2FYLzpn7e3%2B8%2FfXjafvm22z8%2Bva2Nf%2FPcTARXTyZnx6jWSQLDVM1IaxwjzSsdvWOHIg8t3FgU3J64JNaUDHsvbJeN1122kjp3zXmWgoQUOcVnLaJq1JVzpL4vUJkvUQIpLunokQsX%2FwB3mw%2FDpgYAAA%3D%3D&config=H4sIAAAAAAAAA0WPPQ7CMAyF7%2BK5QoAEQ3bYunADK7hVUPMjO5VaVb07cVroYtl%2B732JF5A4sqUWk4DJPFIDH7FgFkjIQqydzCHjBAbynEgsu5ShgSzTllhLzxiki%2BzVzoQ2VwJj77HkXro52SJkegzkKShgk5%2Bl%2Fi06VHVVKHJPBQQk1%2FPlVhJDjEJgOhyk%2FNO74LpZH7LRJyaRQ8LQDz%2Bnsnx8j7pY6g2VeYf1YOw5J%2B1urId9AUCqj4seAQAA

### Expected behavior

It should compile fine and produce appropriate JS file.

### Version

1.2.223

**Comment by Dev-Siri** [comment]
Is there a workaround for this problem?

**Comment by davidianbonner** [comment]
What is the solution to the problem?
