### ISSUE TITLE
[swc_cli] Generated plugin template fails to compile

### ISSUE THREAD

**Issue by JohnDaly** [swc-project/swc#5412]
### Describe the bug

An SWC plugin template generated with `swc plugin new --target-type wasm32-wasi my-first-plugin` will not compile:

```
error[E0432]: unresolved imports `swc_plugin::ast`, `swc_plugin::plugin_transform`, `swc_plugin::TransformPluginProgramMetadata`
 --> src/lib.rs:1:18
  |
1 | use swc_plugin::{ast::*, plugin_transform, TransformPluginProgramMetadata};
  |                  ^^^     ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TransformPluginProgramMetadata` in the root
  |                  |       |
  |                  |       no `plugin_transform` in the root
  |                  could not find `ast` in `swc_plugin`
```

`swc_plugin` v0.89.0 seems to be incomplete. I was able to get things to compile after making the following changes:
1. Set the version of `swc_plugin` to be `"0.88.2"` in the `Cargo.toml`
2. Update the import for `swc_plugin` to be:

```rs
use swc_plugin::{ast::*, metadata::TransformPluginProgramMetadata, plugin_transform};
```

### Expected behavior

I expect to be able to compile the plugin that is generated via the CLI 

### Version

SWC 0.88.0

**Comment by kwonoj** [comment]
Yes, that's known for now

https://github.com/swc-project/swc/issues/5393#issuecomment-1205650351
