### ISSUE TITLE
TypeError: Class constructor App cannot be invoked without 'new'

### ISSUE THREAD

**Issue by 2Steaks** [swc-project/swc#5419]
Hi, I'm trying to use this to test a Next.js application where we are testing the actual App page component, however I am getting the following error `TypeError: Class constructor App cannot be invoked without 'new'` I've tried configuring the `.swcrc` in multiple ways but without success. Has anyone experienced this with class components?

**Comment by vitalyiegorov** [comment]
Trying to setup `swc-loader` with our NestJS backend project and having same issue with some of our classes.
```TypeError: Class constructor [class] cannot be invoked without 'new'```

**Comment by kdy1** [comment]
Please provide some information for debugging
