### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#5433]
### Describe the bug

The original code can be run by the node, but after the translation, when the node is used again, the error is as follows:
```shell
RangeError: Maximum call stack size exceeded
```

### Input code

```typescript
function* v0(){
    try{
        var v1 = yield v2();
    }catch(v9){
    }
}
var v1 = ({foo : 10});
const v3 = JSON.stringify(v1, v0);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.224&code=H4sIAAAAAAAAA0srzUsuyczP01IoM9DQrOZSAIKSokoIAwTKEosUygwVbBUqM1NzUhTKjDQ0rcGStcmJJckZGmWWUF21XLVccMUa1Wn5%2BQpWCoYGtUDlyfl5xSUKZcZACa9gfz%2B94pKizLz0zLRKjTJDHaDFmtYAlv7mnocAAAA%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8eB2KM716ZumQlMe%2FNdDphaeuUuUDK%2FNBi5Zs2EhsYtrhcyaim0c4eMgxVLofUqeClzKcEWdRQcNHtbS7ZFHIR4EEcD%2F83hw6F9Llm0Km2rHdWQoonaDxDq%2BzwXvav%2FgXU82csuwAAAA%3D%3D

### Expected behavior

It can run normally after transpling.

### Version

1.2.224

**Comment by Austaras** [comment]
Surprisingly, this could be fixed by #5173

**Comment by Austaras** [comment]
This is the same problem as following code:
```js
JSON.stringify({}, function () { return {g: ''}})
```
the replacer function returns an object that has keys, then `JSON.stringify` would iterate over those keys and call them with replacer again, so browser would throw too much recursion. Changing to follow code
```js
JSON.stringify({}, function () { 
    const a = {};
    Object.defineProperty(a, 'g', { value: '', enumerable: false });
    return a;
}) 
```

The generator object returned by `regenerator-runtime` has a few keys, so this issue happens.

So this is not a issue of swc and should be closed.

**Comment by kdy1** [comment]
Thank you for investigating!
