### ISSUE TITLE
Const enum inlining

### ISSUE THREAD

**Issue by vjancik** [swc-project/swc#5435]
### Describe the feature

[https://play.swc.rs/?version=1.2.224](https://play.swc.rs/?version=1.2.224&code=H4sIAAAAAAAAA0vOzysuUUjNK81VCEktLsnMS1eo5lIAgrDEnNJUQwVbBUM9Ax2EiBFQxAgkUsvFlQzUm5%2BTqpeTn64B1awH0aZpzQUABXsmEVkAAAA%3D&config=H4sIAAAAAAAAA3WUS3LbMAyG76J1FqkXnU4O0F3PwKFFUEZCERoCVKzx5O4F9aAsO9kJHwEQj1%2B8Ne%2FcNm%2B3ZrCJIZUvnqLYa%2FPWyDQAtwkHaV4aYUXeBoYvNWzqQNQF%2BPR6OulxjxH9VMJb6ocEzOVb3XIPUXgNfVGS6FNNSVmtM1EAG59sY9lgFOgg7aEthWAHBjPaVCPKbTYhUzygLODMkGi4o9GhIEVNtjEH1pmWHFSACVrBEXYXzaEukbWwWskMHZxz15WRLZ4w2pCt1FxwncegN9a4CyGL8TnyAzpUuqClydULvUkgOcXN550wHubwAaB1BsscbQ975My97uHo6b%2Fxwuh1iTJVGuiuqgidNmcQfe2wVA1JcJ9WApdbKB22e%2FIVHhpidGDAe512DeZPlPayJyvyI19NnZr1%2Bw4W02x6OtIigSf4V6uS%2B3WsvLdyeWQ89WcKTyl6kAu5J6yDEHqESdV7HR5pjg50zODuDjIXs8pUly9kQvm%2FtjmrIDTGdIHOVb76G%2FY2dkWWt0ZoCDBCOG70Rz18w%2FSSsSx4leImPPiz78yqjvDX6%2FYMfM0KYdifhZ5cXuvR3c3Pw%2B9GOfK%2F9WRpaHsslrj%2F%2BaB4oYMEAAA%3D)

I might be unaware of a use-case, but the names of enums should be extractable and the values of enums directly replacable in expressions (they already are). For enums with many variants or with verbose names this saves considerable resulting file size.

ts-loader (without transpileOnly, last checked in 2018) does this.

Please let me know if you need a project for reproducing the issue.

**Comment by kwonoj** [comment]
Dupe https://github.com/swc-project/swc/issues/940
