### ISSUE TITLE
Variables with names starting with `mock` are not considered when hoisting `jest.mock()` calls

### ISSUE THREAD

**Issue by jackyef** [swc-project/swc#5448]
With `babel-jest` it seems like `jest.mock()` calls are hoisted to the top of the file. `swc` seems to have this transformation as well, so no issue with that.

The problem occurs when the `jest.mock()` calls depends on other variable, for instance:
```ts
const mockCreate = jest.fn().mockResolvedValue(undefined)
jest.mock('twilio', () => () => ({ messages: { create: mockCreate } }))
```

With `babel`, this code works fine because [`jest` makes an exception for variables with names starting with `mock`](https://github.com/facebook/jest/issues/8148#issuecomment-473998156). With `swc`, it seems like this isn't the case and we end up with the following error:

```
ReferenceError: Cannot access 'mockCreate' before initialization
```

Quoting this comment from ts-jest repo: https://github.com/kulshekhar/ts-jest/issues/1088#issuecomment-623033610
>What happens is that when doing the hoisting for mock, the babel plugin checks variables that are being used in the mock factory to ensure that everything being used will be within scope after hoisting.

**Comment by emmmarosewalker** [comment]
Same issue, confirming the error is gone when downgrading to "@swc/core": "1.2.160" (was on 1.2.232)

**Comment by RobinTail** [comment]
```
Test suite failed to run

    ReferenceError: Cannot access 'compressionMock' before initialization

      25 |
      26 | const compressionMock = jest.fn();
    > 27 | jest.mock("compression", () => compressionMock);
         |                                ^
```

.swcrc:
```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es2016",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": true
  },
  "minify": false
}
```

package.json
```
    "@swc/core": "1.3.1",
    "@swc/jest": "0.2.22",
```

**Comment by aleksandr-sidorov** [comment]
I have the same issue while migrating a jest testing project from `ts-jest/babel` to swc.
In my case the latest working versions are
```
"@swc/core": "1.2.205",
"@swc/jest": "0.2.24",
```

**Comment by b-smets** [comment]
Any updates on this? Can confirm this is still an issue with @swc/jest 0.2.29.

**Comment by kdy1** [comment]
`jest.mock('twilio', ...) ` does not conform to the ESM standard.

Please see https://github.com/swc-project/swc/issues/5205
