### ISSUE TITLE
Meta property parsing for `import.meta`

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#545]
Expressions such as `import.meta` in the following...

```ts
const test = import.meta.someProp;
```

...should be parsed as a `MetaPropExpr`.

Right now this import meta proposal is supported in TypeScript.

References:

* https://github.com/tc39/proposal-import-meta#proposed-solution
* https://astexplorer.net/#/gist/85d9c7560b8a9e00beab91dede16f5df/adbeb94ef5440c5e79a61e81b8b6c926f073252b
* https://ts-ast-viewer.com/#code/MYewdgzgLgBLC8MCWBbADiATlAdCgplAIYDcQA (gives a compile error, but I should fix it so it targets esnext)

**Comment by Austaras** [comment]
@kdy1 seems like `import.meta` is only available in typescript? But this is a [js proposal](https://github.com/tc39/proposal-import-meta#proposed-solution) and has already landed in browsers
