### ISSUE TITLE
Inconsistencies between ECMA and HTML mininfier

### ISSUE THREAD

**Issue by daxpedda** [swc-project/swc#5454]
I was learning how to minify JS files from the [ECMA minifier CLI](https://github.com/swc-project/swc/blob/7437f53047853dad28d5b0274137a4167e74976c/crates/swc_ecma_minifier/src/cli/bin.rs). It uses all three transforms, the `resolver`, `hygiene` and `fixer`.

I discovered that the HTML minifier, [when it minimizes JS](https://github.com/swc-project/swc/blob/9d793f1cd3f2e23ba5b286783e0633a13690f1c2/crates/swc_html_minifier/src/lib.rs#L1452-L1571), only uses the `resolver` transform.

Is this intentional? Or a bug?

**Comment by kdy1** [comment]
It's a bug.
It should use fixer
