### ISSUE TITLE
swc is removing parenthesis incorrectly

### ISSUE THREAD

**Issue by Nikaple** [swc-project/swc#5505]
### Describe the bug

The outmost parenthesis cannot be removed in following code:

### Input code

```typescript
(function(){}(), console)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es5",
    "minify": {
      "compress": false,
      "mangle": false
    },
    "loose": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.233&code=H4sIAAAAAAAAA9NIK81LLsnMz9PQrK7V0NRRSM7PK87PSdUEAHCXoCcZAAAA&config=H4sIAAAAAAAAA02LSwqAMBBD75K1Wze9zVCmUumPSReKeHctKrjLS%2FIOrPRwB5oY1UbiXrpscFCfhd5i6zgndLFF%2B6g5Y0KOJYZ9%2FH3NzZSEC5Ko9yRlSfribaZa%2BcPPfPgCbUYHSoEAAAA%3D

### Expected behavior

`(function(){}(), console)`

### Actual behavior

`function() {}(), console;`

which triggers an error: `Uncaught SyntaxError: Function statements require a function name`

### Version

1.2.233

**Comment by magic-akari** [comment]
After some investigation, I found this interesting fact.

Without parenthesis, `function (){}`, `function (){}` or `class {}` is not allowed in the *first position* of a sequence expression.

But this is valid JavaScript code.

```JavaScript
console , function() {}()
```

**Comment by kdy1** [comment]
@magic-akari `function` or `class` starts declaration, and the specification explicitly excludes `function` and `class` in the first work in statement position from expression list
