### ISSUE TITLE
Should archived types for AST nodes be `repr(C)`?

### ISSUE THREAD

**Issue by overlookmotel** [swc-project/swc#5513]
### Describe the bug

Prior to #5414, archived types for AST node structs were `repr(C)` and archived AST enums were `repr(u32)`.

#5414 disabled `bytecheck` as a temporary measure to fix a bug, but also removed `archive_attr(repr(C))` from structs and `archive_attr(repr(u32))` from enums. i.e. archived types like `ArchivedArrayExpression` used to be `repr(C)` and now they're not.

I have no strong opinion on whether this is a good thing or not. I assumed `repr(C)` had been added to archived types originally to ensure stable serialization format across NAPI and WASM plugin builds. But maybe it's not required.

Anyway, just wondering if this was an intentional change and one which will be long-lasting?

I'm asking because it affects my work on #2175, which uses rkyv's archived types as the serialization format. It'd be useful to know whether to adapt the code for this if it's a permanent change, or just wait until `repr(C)` returns, if it's only temporary.

### Expected behavior

n/a

### Version

1.2.233

**Comment by kwonoj** [comment]
We hope it to be a temporary thing but can't promise when, as we need to verify enabling repr + bytecheck won't cause regression. repr(C|u32) was only for the checked archived deserialization with compatibility, so if we can't make it work probably we won't bring it back though.

**Comment by kwonoj** [comment]
I'd consider this as sort of subset or duplicate to https://github.com/swc-project/swc/issues/5513.

**Comment by overlookmotel** [comment]
Thanks for the super-swift reply (as ever).

The unsafe code guidelines say [here](https://rust-lang.github.io/unsafe-code-guidelines/layout/structs-and-tuples.html#default-layout-repr-rust):

> The default layout of structs is not specified.
> ...does not guarantee determinism between executions of the compiler -- two executions may select different layouts, even if all inputs are identical.

So, *in theory* at least, the memory representations of an archived struct in swc binary and in a WASM plugin (compiled against same version of swc) could be different.

In practice, the types for AST nodes are simple (no generics etc) so it's unlikely to be a problem. So it depends how strict you want to be.

The only way to completely guarantee it is `repr(C)`. The downside of `repr(C)` is less efficient memory representations, as it won't re-order fields to reduce padding, or use [discriminant elision on enums](https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#discriminant-elision-on-option-like-enums).

A partial "best of both worlds" solution would be for the `ast_node` macro to re-order fields automatically to reduce padding, and then the archived structs could be `repr(C)` while maintaining most of the efficiencies of `repr(Rust)`. That would be a little complicated to implement, so you may well say that it's not worth it.

**Comment by overlookmotel** [comment]
> I'd consider this as sort of subset or duplicate to #5513.

#5513 is this issue. Which issue were you meaning to point to please?

**Comment by kwonoj** [comment]
Sorry, it was https://github.com/swc-project/swc/issues/5472. Not sure why I referred self recursive.

First, I wouldn't deny usefulness of guidelines. However, in practical way if that happens we'll have more places to break - we have several chains of non-determinstic gaurantee across bytes, including rkyv serialization, and wasm runtime itself, and others. 

Meanwhile, I'd like to clarify this shouldn't belong to public specification of SWC's interface. As noted above, the only reason we introduced repr was to enable proper bytecheck for the serialization. Both are internal implementaion in my opinion and we do not gaurantee it'll be persist over non-semver version changes.

**Comment by overlookmotel** [comment]
Thanks for coming back. That's all clear.

I understand it's not part of the public interface, however it is part of an internal API between SWC and plugins. Similarly, it would affect the new Rust->JS interface for `parse()` etc - which is I hope is also going to be internal to SWC.

I feel like you've answered my question, so closing the issue. Thanks for clarifying.
