### ISSUE TITLE
Block scoping issue when "isModule" is "unknown"

### ISSUE THREAD

**Issue by 0xe** [swc-project/swc#5532]
### Describe the bug

Block scoping regression from swc version 1.2.209.

### Input code

```typescript
var ret = [];
{
    function foo () { return 1 }
    ret.push(foo() === 1);
    {
        function foo () { return 2 }
        ret.push(foo() === 2);
    }
    ret.push(foo() === 1);
}

ret;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es5"
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true,
  "isModule": "unknown"
}
```

### Playground link

https://play.swc.rs/?version=1.2.209&code=H4sIAAAAAAAAAytLLFIoSi1RsFWIjrXmquZSAIK00rzkksz8PIW0%2FHwFDU2FapCK0qI8BUOFWrACIFevoLQ4QwOoAChva2urYKhpDZaCmIDXFCOoKThMMoKahNeqWi4uoIw1FwCH4H0TvwAAAA%3D%3D&config=H4sIAAAAAAAAAy2LQQ7CQAwD%2F%2BJzr1z2D31EFCLUwiarJCuoqv4dInGyPdac2IPRTgzyEK8WhyZ90CDcKdi3kbgWJPlDsnDcane7z5eUkMf4Jdh6N92jzrDpLCuNQEufsmCL9S9g6lPtrbi%2BpMnM530AAAA%3D

### Expected behavior

Should transpile to

```javascript
"use strict";
var ret = [];
{
    var foo = function foo() {
        return 1;
    };
    ret.push(foo() === 1);
    {
        var foo1 = function foo1() {
            return 2;
        };
        ret.push(foo1() === 2);
    }
    ret.push(foo() === 1);
}ret;
```

### Actual behavior

```javascript
var ret = [];
{
    var foo = function foo() {
        return 1;
    };
    ret.push(foo() === 1);
    {
        var foo = function foo() {
            return 2;
        };
        ret.push(foo() === 2);
    }
    ret.push(foo() === 1);
}ret;
```

### Version

1.2.209

**Comment by Austaras** [comment]
Don't know why but this behavoior is aligned with babel.

**Comment by kdy1** [comment]
Thank you for the explanation!
