### ISSUE TITLE
Expected byte position of comments in CommentMap at end of file

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#555]
Given the following code:

```ts
if (true) {
}
// 2
```

It has the following comment maps:

```
Leading: {BytePos(10): [Comment { kind: Line, span: Span { lo: BytePos(12), hi: BytePos(16), ctxt: #0 }, text: " 2" }]}
Trailing: {}
```

Should something be changed here so this makes more sense? I'm not sure what the solution should be. FWIW, Babel includes these as trailing comments of the if statement.

**Comment by kdy1** [comment]
Thank you for reporting a bug related to an edge case.

Do you think marking the last comment as trailing comment of if statement makes sense?

**Comment by dsherret** [comment]
> Do you think marking the last comment as trailing comment of if statement makes sense?

@kdy1 just updated my original comment. Yeah, that makes sense and it's what babel does.

**Comment by kdy1** [comment]
@dsherret Fixed it

**Comment by dsherret** [comment]
@kdy1 wow that was super fast. It works! Thanks! :)
