### ISSUE TITLE
core-js3 compat failure since swc 1.2.231 - 1.2.239 (current)

### ISSUE THREAD

**Issue by vipero07** [swc-project/swc#5554]
### Describe the bug

stack backtrace:
   0:     0x7ffc7efb90af - wasmer_vm_raise_trap
   1:     0x7ffc7efd5d2a - wasmer_vm_raise_trap
   2:     0x7ffc7efb2c99 - wasmer_vm_raise_trap
   3:     0x7ffc7efbbb1b - wasmer_vm_raise_trap
   4:     0x7ffc7efbb79b - wasmer_vm_raise_trap
   5:     0x7ffc7efbc0c9 - wasmer_vm_raise_trap
   6:     0x7ffc7efbbfcd - wasmer_vm_raise_trap
   7:     0x7ffc7efb9ce7 - wasmer_vm_raise_trap
   8:     0x7ffc7efbbca9 - wasmer_vm_raise_trap
   9:     0x7ffc807d6ab5 - wasmer_vm_raise_trap
  10:     0x7ffc807d6bc3 - wasmer_vm_raise_trap
  11:     0x7ffc7edc3eb5 - wasmer_vm_raise_trap
  12:     0x7ffc7f8eb7ed - wasmer_vm_raise_trap
  13:     0x7ffc7efa1b2c - wasmer_vm_raise_trap
  14:     0x7ffc808022f1 - wasmer_vm_raise_trap
  15:     0x7ffc7f8d833c - wasmer_vm_raise_trap
  16:     0x7ffc8021bb38 - wasmer_vm_raise_trap
  17:     0x7ffc7f910362 - wasmer_vm_raise_trap
  18:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  19:     0x7ffc7f90738f - wasmer_vm_raise_trap
  20:     0x7ffc7f90841f - wasmer_vm_raise_trap
  21:     0x7ffc7f905298 - wasmer_vm_raise_trap
  22:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  23:     0x7ffc8021b8b4 - wasmer_vm_raise_trap
  24:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  25:     0x7ffc7f90841f - wasmer_vm_raise_trap
  26:     0x7ffc7f905298 - wasmer_vm_raise_trap
  27:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  28:     0x7ffc8021b8b4 - wasmer_vm_raise_trap
  29:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  30:     0x7ffc8021b8b4 - wasmer_vm_raise_trap
  31:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  32:     0x7ffc8021bfa0 - wasmer_vm_raise_trap
  33:     0x7ffc7f90778c - wasmer_vm_raise_trap
  34:     0x7ffc7f90841f - wasmer_vm_raise_trap
  35:     0x7ffc7f905298 - wasmer_vm_raise_trap
  36:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  37:     0x7ffc8021b84f - wasmer_vm_raise_trap
  38:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  39:     0x7ffc8021b8b4 - wasmer_vm_raise_trap
  40:     0x7ffc8021ba2a - wasmer_vm_raise_trap
  41:     0x7ffc7f91016f - wasmer_vm_raise_trap
  42:     0x7ffc8021bb86 - wasmer_vm_raise_trap
  43:     0x7ffc7edc46d1 - wasmer_vm_raise_trap
  44:     0x7ffc7f59e444 - wasmer_vm_raise_trap
  45:     0x7ffc7f624668 - wasmer_vm_raise_trap
  46:     0x7ffc7ed23c0a - Ordinal0
  47:     0x7ffc7ed17d6e - Ordinal0
  48:     0x7ffc7eb5da56 - Ordinal0
  49:     0x7ffc7eb5a736 - Ordinal0
  50:     0x7ffc7ea53c86 - Ordinal0
  51:     0x7ffc7eb1a0ef - Ordinal0
  52:     0x7ffc7e9de579 - Ordinal0
  53:     0x7ff61d58cc0e - uv_queue_work
  54:     0x7ff61d578d0d - uv_poll_stop
  55:     0x7ff61e38e760 - v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
  56:     0x7ffd2fa97034 - BaseThreadInitThunk
  57:     0x7ffd2fc82651 - RtlUserThreadStart
[!] (plugin swc) Error: failed to handle: failed parse corejs3-compat data.json: Error("unknown field `bun`, expected one of `chrome`, `and_chr`, `and_ff`, `op_mob`, `ie`, `edge`, `firefox`, `safari`, `node`, `ios`, `samsung`, `opera`, `android`, `electron`, `phantom`, `opera_mobile`, `rhino`, `deno`", line: 4, column: 9)

Stack backtrace:
   0: wasmer_vm_raise_trap
   1: wasmer_vm_raise_trap
   2: wasmer_vm_raise_trap
   3: Ordinal0
   4: Ordinal0
   5: Ordinal0
   6: Ordinal0
   7: uv_queue_work
   8: uv_poll_stop
   9: v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
  10: BaseThreadInitThunk
  11: RtlUserThreadStart

### Config

```json
{
      "jsc": {
        "parser": {
          "syntax": "typescript",
          "dynamicImport": true,
          "decorators": false,
          "tsx": false
        },
        "target": "es5",
        "externalHelpers": true,
        "loose": false,
        "minify": {
          "compress": {
            "arguments": false,
            "arrows": true,
            "booleans": true,
            "booleans_as_integers": false,
            "collapse_vars": true,
            "comparisons": true,
            "computed_props": true,
            "conditionals": true,
            "dead_code": true,
            "directives": true,
            "drop_console": false,
            "drop_debugger": true,
            "evaluate": true,
            "expression": false,
            "hoist_funs": false,
            "hoist_props": true,
            "hoist_vars": false,
            "if_return": true,
            "join_vars": true,
            "keep_classnames": false,
            "keep_fargs": true,
            "keep_fnames": false,
            "keep_infinity": false,
            "loops": true,
            "negate_iife": true,
            "properties": true,
            "reduce_funcs": false,
            "reduce_vars": false,
            "side_effects": true,
            "switches": true,
            "typeofs": true,
            "unsafe": false,
            "unsafe_arrows": false,
            "unsafe_comps": false,
            "unsafe_Function": false,
            "unsafe_math": false,
            "unsafe_symbols": false,
            "unsafe_methods": false,
            "unsafe_proto": false,
            "unsafe_regexp": false,
            "unsafe_undefined": false,
            "unused": true,
            "const_to_let": true,
            "pristine_globals": true
          },
          "mangle": {
            "toplevel": false,
            "keep_classnames": false,
            "keep_fnames": false,
            "keep_private_props": false,
            "ie8": false,
            "safari10": false
          }
        }
      },
      "minify": true,
      "env": {
        "targets": {
          "node": "4.4.3"
        },
        "mode": "usage",
        "coreJs": "3.24"
      }
    }
```

### Expected behavior

 The code should compile and not fail because bun is unexpected, especially since I'm not targeting bun.

### Version

1.2.231 - 1.2.239 (current)

**Comment by kdy1** [comment]
This is already fixed and will be fixed by the next version
