### ISSUE TITLE
Utils for merging Expr?

### ISSUE THREAD

**Issue by arlyon** [swc-project/swc#5565]
### Describe the feature

Hi! I have hand-written a few utils for merging first objects and now more generally Exprs. You can select a strategy for entities that can't be merged such as merge left, merge right, or fail.

Does this exist in the codebase already? Is there capacity for a utils crate that houses these 'quality of life' utilities?

**Comment by kdy1** [comment]
No, It does not exist.
If it's reasonably general, please consider contributing one
