### ISSUE TITLE
TypeError: (0 , _testPolyfill.default) is not a function (noInterop is as by default "false")

### ISSUE THREAD

**Issue by denisoby** [swc-project/swc#5573]
### Describe the bug

Trying to switch jest compilation to swc, using instructions from https://github.com/swc-project/jest
Fails on first import (as taken from https://rmwc.io/installation, but looks like library doesn't matter)

I'm NOT using `noInterop` property in my configuration (so it stays by default as "false")

### Input code

```typescript
import Adapter from 'enzyme-adapter-react-16';
import rmwcTestPolyfill from '@rmwc/base/dist/test-polyfill';
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "paths": {
      "*.scss": ["./identity-object-proxy.js"],
      "*.svg": ["./identity-object-proxy.js"]
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": false
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "target": "es5",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false
  },
  "minify": false
}
```

### Expected behavior

Resulting issue
```
 TypeError: (0 , _testPolyfill.default) is not a function
```

### Actual behavior

Works correctly

### Version

1.2.241

### Additional context

tsconfig.json
```
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "newLine": "lf",
    "noEmit": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es5",
    "experimentalDecorators": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": [
    "src/**/*",
    "./typings/*",
    "public/scripts"
  ]
}
```

**Comment by kdy1** [comment]
You need `importInterop: "node"`

**Comment by kdy1** [comment]
See https://play.swc.rs/?version=1.3.24&code=H4sIAAAAAAAAA8vMLcgvKlFwTEksKEktUkgrys9VUE%2FNq6rMTdVNhAjqFqUmJpfoGpqpW3NlQpQX5ZYnh6QWlwTk51SmZebkQPU5gMT1kxKLU%2FVTMotL9EuASnQLoGrUrQHLaBMHbAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNMQ7DMAhF78KctUtu0KGHIC6JHNnGAiI1inz3YslRJtB%2Fn8cFuwaYL6goStI3PYvhD2agkFGDxGowec2jFZNSm8BQNrJe0ZezxKw06AQ5lrie3RQ4VyHVB2HZ0t1sLsr8PXpwgZ3VZz%2FJXHZ1a8yVxd7FSLg6WnChBO15MKRRP8NiclD7AxET4crSAAAA
