### ISSUE TITLE
Minifier should not inline a nested class if it uses properties of super in key

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5606]
### Describe the bug

Minifier inlines `Inner` and it breaks code.

### Input code

```typescript
"use strict";
class Hello {
  toString() {
    return 'hello';
  }
}

class Outer extends Hello {
  constructor() {
    super();
    class Inner {
      [super.toString()] = 'hello';
    }

    return new Inner();
  }
}

expect(new Outer().hello).toBe('hello');
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es2021",
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    },
    "loose": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.241&code=H4sIAAAAAAAAA02OsQ7CMAxE93yF1aXJ0h%2BIWJhgYmBEDChYgBQ5VeKISqj%2FjpNUkPHsu3c35ISQOL4cD1Y5f0sJDuh9gI8C4HCWFz20qRIgIudIMD6LZbRyW9WqttwpM0bAhZHuPcUFkobsOMQfKOUZRdkqWvxIJPH2BrhUx%2FRfcIVd31ua%2B0mE70Zo0DoLlxkd6%2FKq27SZKsAIdo96o4n%2FCzOCw%2F0GAQAA&config=H4sIAAAAAAAAA22TS3LjMAxE76K1F5Msc4C5BgsmQRkZflQE6FiVyt0HtCxKsrNTPwEg2AC%2Fh0%2B2w8f3MEFhLO2L5yRwGz4GtBHYFppk%2BDkNAmVEaZjf%2F7y%2FDachUiI%2FtxSb41SQuX1rWI2YRIWHwHhSUvKXSilV1TnngJBetAE2lARHLFuqzSHAxGiuUHpGOw0KcU4HVAWdmUqedjQ5EspJi63MIThjs8MOqKAVuuIWojU0JLE21ju5Q4fnOo7NpiUSrxAqSK%2BFt7sNemLPu2RiMb4mfkKHThe0XPIRRd4UlFrSGvOZKR18%2BIeofQZgThBxy7xzr3M4Rvpfoih5HaLMnYa86yrhqJczRL7fsHWNRWhzq6CrFtsN7Vb8AQ8XYnJo0Ht1uyfzF4m9bMVknjD7LtU18NsMFmnWfTrStgIv8K92JftxPHgEuTwznuM5h5cSEeWS3QtWIyQ%2Fw6Lbe5ueaU0O1WZ0ux%2BVm%2BxrqsOXbEJ7X6vPuhCaY8aQz3199RlGSGNfy5%2F7wHgn1ze56P%2F0pMps3gMAAA%3D%3D

### Expected behavior

It should not inline `super` into a class

### Version

1.2.241

**Comment by Austaras** [comment]
Seems like once again, it's same as terser. Maybe same reason as terser/terser#1244

**Comment by kdy1** [comment]
Oh, thank you!
Then let's just ignore 😄
