### ISSUE TITLE
Object rest should not move variable declarations to inner scopes

### ISSUE THREAD

**Issue by lmestel** [swc-project/swc#5608]
### Describe the bug

`o` is not accessible from module scope and cannot be exported. 
That results in an error like `Module parse failed: Export 'o' is not defined`.

If you remove the `...p` in line 5, there is no need for the swc helpers and the result is correct. So it seems, that the bug has something to do with the injection of the helpers.

### Input code

```typescript
import { jsx as c } from "react/jsx-runtime";
import i from "react-markdown";

const o = r => c(i, { children: r }),
  s = ({ text: r, renderText: t = o, ...p }) => c("div", { children: t(r) });

export { s as RichText, o as defaultRenderFn };
```

### Config

```json
{
  "minify": false,
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "topLevelAwait": true,
      "importMeta": true
    },
    "transform": {
      "legacyDecorator": true,
      "react": {
        "runtime": "automatic"
      }
    },
    "target": "es5",
    "loose": false,
    "externalHelpers": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.242&code=H4sIAAAAAAAAA1WPwQ6CMBBE73zFhBMkBe8aPPoBxB8gbQlVaMl2URLCv7uABz3uvMnMjhvGQIwFjzijidBY0VIYkJJtNJ9ELmjy7AabXhJ3uN2vpRgaeprw9sITHXxkBFQgVFfozCnJ1p3rDVl%2FFnXNVQJEcWQL2M4sooJAY%2Bm%2BnywsKJRlOYr7iEmNe6X%2FUZxRLlxK7fzdELcFtdPdFqTkDTmNbZup53ovuHmslw%2FvIRwv8wAAAA%3D%3D&config=H4sIAAAAAAAAA2WQwU7EMAxE%2F8XnvXLpjdWCQAL%2BwUqnJSiJI8ddWlX9dxJQyyJu0UxmNH4rRZ%2F8sFA3cCg40Udx1K2UWQu0vcqSjGfqCC5yceqz0Yn6JXH07jlmUaPOdKrZrP7KhlfYu%2FS7OEzJmZd09unQMLfYBQNPwR5V4l%2FjjSNKZodbq4cTZRMt%2F5UzBlE8zLdjTPILrgj3n%2BwP0X%2FvrQP5R9nqP%2BVUajy2YwNGdstlL95jCnbWfJ2S%2BYhKgyeTyOYdba2EdYQ1SOWu0gkiBQdSzAZNHJ4QMn7n7%2BBXchKzopQjETmNYS%2FYtu0L0hFFsqYBAAA%3D

### Expected behavior

```js
import _object_without_properties from "@swc/helpers/src/_object_without_properties.mjs";
import { jsx as c } from "react/jsx-runtime";
import i from "react-markdown";
var o = function(r) {
    return c(i, {
        children: r
    });
}, s = function(_param) {
    var r = _param.text, tmp = _param.renderText, t = tmp === void 0 ? o : tmp, p = _object_without_properties(_param, [
        "text",
        "renderText"
    ]);
    return c("div", {
        children: t(r)
    });
};
export { s as RichText, o as defaultRenderFn };
```

### Actual behavior

```js
import _object_without_properties from "@swc/helpers/src/_object_without_properties.mjs";
import { jsx as c } from "react/jsx-runtime";
import i from "react-markdown";
var s = function(_param) {
    var o = function(r) {
        return c(i, {
            children: r
        });
    }, r = _param.text, tmp = _param.renderText, t = tmp === void 0 ? o : tmp, p = _object_without_properties(_param, [
        "text",
        "renderText"
    ]);
    return c("div", {
        children: t(r)
    });
};
export { s as RichText, o as defaultRenderFn };
```

### Version

1.2.242

**Comment by kdy1** [comment]
We should apply `inject_helpers` before applying the minifier
