### ISSUE TITLE
`descriptor` is undefined in decorators when used in a method that has a Symbol as name

### ISSUE THREAD

**Issue by kaname-png** [swc-project/swc#5653]
### Describe the bug

Currently I want to apply a decorator to a method that has as name a Symbol, but when I compile with `@swc/core` + `@swc/cli` I get that its descriptor is `undefined`.

> With `@swc/core`

![image](https://user-images.githubusercontent.com/56084970/187087210-65dcf6c4-a938-453f-9545-ae938e3dcd95.png)

> With `tsc (typescript)`

![image](https://user-images.githubusercontent.com/56084970/187087431-faa7b12d-9258-4357-bf40-cb678d78eb1a.png)

### Input code

```typescript
export function TestDecotor() {
  return (t: Object, key: string | symbol, descriptor: PropertyDescriptor) => {
    console.log(t, key, descriptor);
  };
}

export class TestClass {
  @TestDecotor()
  public [Symbol.for("abc")]() {
    return console.log("ok method");
  }

  @TestDecotor()
  public def() {
    return console.log("ok method");
  }
}

new TestClass();
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "keepClassNames": true,
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  },
  "module": {
    "type": "es6"
  }
}
```

### Playground link

https://github.com/kaname-png/swc-core-bug-decorators-descriptor

### Expected behavior

Get the data correctly from your descriptor.

### Actual behavior

You get an undefined descriptor.

### Version

1.2.244

**Comment by kdy1** [comment]
Closing as duplicate.
Please search before filing an issue

**Comment by kaname-png** [comment]
@kdy1 can you tell me what is the issue? I can not find it.
