### ISSUE TITLE
"extends" property for .swcrc files 

### ISSUE THREAD

**Issue by aminya** [swc-project/swc#5654]
### Describe the feature

It would be nice if `.swcrc` files could be extended from other config files similar to how `tsconfig.json` works.

### Additional context

This allows reusing config files without copy-pasting.

**Comment by kwonoj** [comment]
General designs around configuration may need some thoughts indeed, meanwhile we're trying to approach very carefully to introduce something new into the existing config system, including things like inheritance.

While ours are not as complex as much, https://eslint.org/blog/2022/08/new-config-system-part-1/ explains things we feel in common as SWC grows & getting matured.
