### ISSUE TITLE
The react variable is forcibly renamed  in "jsx function"

### ISSUE THREAD

**Issue by xlianghang** [swc-project/swc#5660]
### Describe the bug

![image](https://user-images.githubusercontent.com/90079525/187176531-1cf633e3-2d0b-48a8-9e88-dd9695b22918.png)

### Playground link

https://play.swc.rs/?version=1.2.244&code=H4sIAAAAAAAAA%2BNKLK7MS1ZIK81LLsnMz1MoSs1LSS3SyMlM0lSo5lIAguT8vOIShaDUxOQSBVsFoIQemG2NLuni74ssD%2BRClBSllpQW5SnYpGSW2dnog0hrrlouAG6cM7Z4AAAA&config=H4sIAAAAAAAAA0WOSwrDMAwF76K1FyGLLnyHHkK4SnDxD0mBGuO7104N3UnvjQY1eIsD26AgC%2FGcpCbFD1ggF1Ec%2B6JgBjYi5Yu6AUU%2BSSch%2B7Zvow05C%2F16A9Enf9SpcjkWJhGwBwaZFaYz0Fr7UMX8umbQQGuhW%2FmA%2FnesOy%2FPBd4vfAECR8u8tgAAAA%3D%3D

### Expected behavior

"React" not should be renamed to "React1"

### Version

1.2.244

**Comment by kdy1** [comment]
You can declare `React` on top level if you want to override it.
The injected  `React` for jsx syntax should not clash with a local variable

**Comment by xlianghang** [comment]
> You can declare `React` on top level if you want to override it. The injected `React` for jsx syntax should not clash with a local variable and this is not a bug

My scene is rendered at runtime and I have no way to declare it globally

```jsx
async function render(lib) {
    const React = lib.React;
    const ReactDOM = lib.ReactDOM;
    return ReactDOM.render(<div></div>, document.getElementById('app'));
}
```
