### ISSUE TITLE
Issue parsing arrow function in conditional expression

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#568]
Here's some code from the TypeScript compiler in [checker.ts](https://raw.githubusercontent.com/microsoft/TypeScript/master/src/compiler/checker.ts):

```ts
const filterFn: (t: Type) => boolean = operator === SyntaxKind.EqualsEqualsToken ?
                        (t => areTypesComparable(t, valueType) || isCoercibleUnderDoubleEquals(t, valueType)) :
                        t => areTypesComparable(t, valueType);
```

The following error occurs:

> not yet implemented: reparse_expr_as_pat, pat_ty = BindingPat, expr = Arrow(ArrowExpr { span: Span { lo: BytePos(109), hi: BytePos(193), ctxt: #0 }, params: [Ident(Ident { span: Span { lo: BytePos(109), hi: BytePos(110), ctxt: #0 }, sym: Atom('t' type=inline), type_ann: None, optional: false })], body: Expr(Bin(BinExpr { span: Span { lo: BytePos(114), hi: BytePos(192), ctxt: #0 }, op: "||", left: Call(CallExpr { span: Span { lo: BytePos(114), hi: BytePos(146), ctxt: #0 }, callee: Expr(Ident(Ident { span: Span { lo: BytePos(114), hi: BytePos(132), ctxt: #0 }, sym: Atom('areTypesComparable' type=dynamic), type_ann: None, optional: false })), args: [ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(133), hi: BytePos(134), ctxt: #0 }, sym: Atom('t' type=inline), type_ann: None, optional: false }) }, ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(136), hi: BytePos(145), ctxt: #0 }, sym: Atom('valueType' type=dynamic), type_ann: None, optional: false }) }], type_args: None }), right: Call(CallExpr { span: Span { lo: BytePos(150), hi: BytePos(192), ctxt: #0 }, callee: Expr(Ident(Ident { span: Span { lo: BytePos(150), hi: BytePos(178), ctxt: #0 }, sym: Atom('isCoercibleUnderDoubleEquals' type=dynamic), type_ann: None, optional: false })), args: [ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(179), hi: BytePos(180), ctxt: #0 }, sym: Atom('t' type=inline), type_ann: None, optional: false }) }, ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(182), hi: BytePos(191), ctxt: #0 }, sym: Atom('valueType' type=dynamic), type_ann: None, optional: false }) }], type_args: None }) })), is_async: false, is_generator: false, type_params: None, return_type: None })'

This also fails with babel, but is fine with the TS compiler: https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZgSwDZQKYCcBiYBcMAUUeAKgJ4AOqAlDALwB8MARiCEqgIZh0wiXocoIdHVq0YAZVJgoHAB4BpBGAAmAOgCiARwCuHJBG16DxEAGtU3APwAoGPYeOnzh4TqMO6VGUoQAwiAAtuSeHEzshAA0MABu-jreFNQwAD4pMAj-IBjACOGoAKqqGAAiIDr5RvoQUbHxiZRUNDh2Lm1tsAwwng2oWcGh-bVxSAk-1ADcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.7.7&externalPlugins=

Note this happens because of the type annotation on the variable declaration (see [here how this compiles](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZgSwDZQKYCcBiYYF4YgAOGAhlCOnrvgMoCeYUJAHgNIJgAmAdAKICOAVxJIIA4aIAqIANaocAfgBQMVWvUbNagBSxcAPhgl0qSXWIQAwiAC2hYyQBGSVLoA0MAG4jBp86gBKGAAfYJgEKxAMYARnVABVLgwAERBBOPERCHcvHz9iAKCALhUtMrK9Q2N81Ei7Bzic7yRfMwKAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.7.7&externalPlugins=)). Edit: Actually, in swc removing the type annotation doesn't fix the problem...

(This is low priority)

**Comment by dsherret** [comment]
Also, I'm not sure if I'm doing something wrong, but with an optimized build it seems to take swc 17.1s to parse [checker.ts](https://raw.githubusercontent.com/microsoft/TypeScript/master/src/compiler/checker.ts)... but if I use `@typescript-eslint/typescript-estree` it takes 1.3s... why is swc so slow in this scenario?

**Comment by kdy1** [comment]
Closing as fixed https://play.swc.rs/?version=1.3.9&code=H4sIAAAAAAAAA42NvQrCQBCEe59iygTEB4icFv40lsYH2CQrHJ63cW8jBvLwJqSyCDjFMDDDfLXEZLj7YKznWCCzAmXfcg63QyUSmCIcpGUlE4VzDtc%2BGn0uPjab06ujkGYv5cER%2BxUWlNn0ScrTfzrIsyWlKnBma7wpdDxzhwF%2BbFlrP5a32LAepRvjTPld5ygWeX%2Fhtl9KDfeMAQEAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWLLnKHHsK4SnDxD40CDcZ3rx1cspNmnp4qfeBorVSsgGVMOJPaL62kZ2E48UVpIUWPNhvArS9WdtaOMMzDmF6HnMETWCj65LdzyFyORRi4K5v28Cdbd8X8PkZQr3%2BX80ntdsw7j9cEVQ5uPx%2Bqcl%2B4AAAA
