### ISSUE TITLE
Minifier should drop function identifiers while inlining

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5682]
### Describe the feature

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/29931815/187591855-15008fe9-c987-449d-9fae-f62651991884.png">

swc vs terser

**Comment by Austaras** [comment]
Where does this come from? I guess that's because swc currently need an extra pass to strip identifier.

**Comment by kdy1** [comment]
https://github.com/vercel/ms/blob/78ce59eab01c197b9133bf9752ae01fbc11f4976/src/index.ts

I think this is the source.

Yes, it's an issue of `passes` but this affects real-world code
