### ISSUE TITLE
minifier should inline a simple function with a throw statement

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5685]
### Describe the feature

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/29931815/187592988-91452183-924f-4a1c-a5ee-13f0f64bca0a.png">

swc vs terser

**Comment by Austaras** [comment]
Where does this case came from? Seems likely to be fixed by #5607

**Comment by Austaras** [comment]
I cannot reproduce this result in terser playground, and this contradicts to my knowledge of terser inline pass -- it has basically no support for inlining functions with multiple usage.

**Comment by kdy1** [comment]
Oh, my bad.
It was https://github.com/vercel/styled-jsx/blob/41443ab141fb2f2382ceaf8d8896d0e1b7644987/src/stylesheet-registry.js and it was inlined as a single-usage

**Comment by Austaras** [comment]
This is still a valid issue though -- and would indeed be fixed by #5607
