### ISSUE TITLE
minifier should consider injection of `var` while evaluating function invokations

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5687]
### Describe the feature

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/29931815/187593416-5172cf01-76cc-4b8d-b3db-d0bf1fbffd5e.png">

swc vs terser

**Comment by Austaras** [comment]
Cost of iife: 
```js
function(a,b,c){}(...)
```
14+(count of param)*2-1
Cost of invoked function, worst case
```js
var a,b,c;
a=...,b=...,c=...,
```
5+(count of param)*5-1

So only when param count > 3 we should stop invoke IIFEs, which is quite rare.

And once again, where is the source code?

**Comment by kdy1** [comment]
Input seems like https://github.com/vercel/styled-jsx/blob/2a31e7395f76bb997909734cf59a0abc7f4bbdd9/src/stylesheet-registry.js

**Comment by Austaras** [comment]
Then for the third time, it's because terser cannot handle conflicting ident names. Change arguments name of `styles` from `options` to `aaa` would enable terser to inline it.
