### ISSUE TITLE
how can i output code with indentLevel  2

### ISSUE THREAD

**Issue by bwy111** [swc-project/swc#5701]
### Discussed in https://github.com/swc-project/swc/discussions/5676

<div type='discussions-op-text'>

<sup>Originally posted by **bwy111** August 30, 2022</sup>
I want to output code with indentLevel 2, but i always get 4.
```
{
  "minify": {
    "format": {"indentLevel":2}
  }
}
```
The option indentLevel is not available.
Thanks!</div>

this is a bug?
or not implemented yet?

**Comment by kdy1** [comment]
It's not implemented
