### ISSUE TITLE
_ is not defined error when awaiting a promise in a class method call

### ISSUE THREAD

**Issue by ymor** [swc-project/swc#5704]
### Describe the bug

When awaiting a promise in a class method call it's generating `_ = instantiatedClass.method`  however its not defining `_` anywhere. 
If I move the promise out of the method call it works as expected.

### Input code

```typescript
class Example {
  doSomethingOnClass = () => {

  }
}


const doSomething = async () => {
  const ex = new Example();
  ex.doSomethingOnClass(await Promise.resolve('some string'));
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "loose": false,
    "target": "es5"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": ""
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.245&code=H4sIAAAAAAAAA2WNTQrCMBBG94HcYXZNNr2A1I24VvAEQzpoID%2BSCTZFcvcmiii4%2B%2BC9x2ccMsOxoL87gqcUAHO8RE%2F5ZsP1FA4vPoHSMO0770aVovYlhYmB82%2FRVOQ1mG8A8JaoNBZo%2BZwpveuQyvh%2FqHBBm%2BGcordMYyKO7kFq4OYB59TMQfe%2BbiYHFbrAAAAA&config=H4sIAAAAAAAAAz2NQQoDMQwD%2F%2BLzXnvZP%2FQRJnWKSxIH2ykNy%2F69Thd6E5JGOuBlCfYDOqqRLmWzOX5gB5%2BdLCl3hw3cwnIddIZWbJZF66orYfKfGM25UoA4XCo6JzijXUQs3IzFKFjUJ0UfyG4QaeXGef5jtrs8RqHrawNq77V9URZYTH4BvQAvWrQAAAA%3D

### Expected behavior

Code not to fail.

### Actual behavior

The following error occurs `Uncaught (in promise) ReferenceError: _ is not defined`

### Version

1.2.245

### Additional context

In reality I'm calling code similar to this from react in a change handler.  I'm not sure if that has any effect on the issue.

**Comment by albert-gonzalez** [comment]
Same issue here.

This bug happens since version 1.2.244. In 1.2.242 it works as expected.

Best regards!

**Comment by ymor** [comment]
Just to add if you end up wrapping it multiple times, you get many `_ = x.y` even when its different classes/methods

**Comment by carlosala** [comment]
From my side, in `v1.3.0` version works properly!

**Comment by magic-akari** [comment]
> From my side, in `v1.3.0` still works bad. It properly defines what's called `_`, but does not work as expected.

@carlosala  It works for me.

https://play.swc.rs/?version=1.3.0&code=H4sIAAAAAAAAA2WOSwrCMBCG94HcYXZNNrmA1I24VvAEIQ41kIdkgo2Id3fSIhaEWc33v1ywRHBsNt4DwksKgGu%2B5Ij15tN0SoeFj6CahnG%2FCgBcTpQDmpAnBv33loJPik7qNoK9lp7JgfoFrCJszBLO33aldx1iM%2F8LlJ2tr3AuOXpCU5DrH6gGYh1QLawcdPcvIzZ%2BDv0A4WlrB%2BMAAAA%3D&config=H4sIAAAAAAAAAz2NQQoDMQwD%2F%2BLzXnvZP%2FQRJnWKSxIH2ykNy%2F69Thd6E5JGOuBlCfYDOqqRLmWzOX5gB5%2BdLCl3hw3cwnIddIZWbJZF66orYfKfGM25UoA4XCo6JzijXUQs3IzFKFjUJ0UfyG4QaeXGef5jtrs8RqHrawNq77V9URZYTH4BvQAvWrQAAAA%3D

**Comment by ymor** [comment]
Yea the playground generates what I expect too, even with multiple wraps.  Though upgrading to `v1.3.0` managed to break a load of tests and my build times have shot up.  But will investigate and log as new issues when I find out more.

**Comment by carlosala** [comment]
Yes, looks like new issues appeared.
