### ISSUE TITLE
DCE must use graph

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5709]
### Describe the feature

![image](https://user-images.githubusercontent.com/29931815/187861076-e2233e49-09c4-4847-bad4-5365f1d657a7.png)

We need graph to remove this.

I'll implement this after finishing https://github.com/swc-project/swc/pull/5699

**Comment by Austaras** [comment]
I cannot quite get what you mean from the picture above -- but if you're referring to remove unused function that refers each other, I believe we could somewhat use `infects` field in `UsageInfo`

**Comment by kdy1** [comment]
> remove unused function that refers each other

Yeah, it's exact. Sorry for a bad issue 🤣 

Problem is that DCE should use a separate analyzer. With the current pass limit, 2, DCE cannot remove enough items.
That's why I'm working to apply DCE multiple time without relying on `pass`. (https://github.com/swc-project/swc/pull/5699)
