### ISSUE TITLE
TypeScript type checker

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#571]
See https://github.com/dudykr/stc

**Comment by dsherret** [comment]
I'm just looking at this: https://github.com/kdy1/swc/tree/e88e5e4c824926e5f3a5240986c33bb30f7508b5/typescript/checker

Won't re-writing the TS type checker in rust be a lot of work? There's so many edge cases! Why not just do what babel does and tell people to run the typescript type checker over the code with emitting? Alternatively, you could build something into the swc JS package that uses the typescript compiler api to do this as well.

**Comment by dsherret** [comment]
What might be neat is something that converts swc AST nodes to TypeScript compiler api nodes. So you could parse the nodes with swc, send them over to JS, convert them to typescript compiler api nodes, then it could do the type checking.

**Comment by kdy1** [comment]
@dsherret I'm porting tsc because it is wall-clock grade slow.

**Comment by dsherret** [comment]
True, it could be faster, but there's a whole team of developers working on TypeScript daily. It will be very hard to get all the edge cases, but perhaps you could repurpose the tests the typescript team uses in the typescript repo.

Anyway, you have a long and continually expanding road ahead of you :)

**Comment by kdy1** [comment]
I'm already using tests in typescript repository :)
I know that it's a very hard task, but it's fun for me.

**Comment by dsherret** [comment]
That’s awesome. Well, you’ve done an excellent job with the library and you’re very fast at programming so good luck! 😀

**Comment by IronSean** [comment]
The other approach you can use with babel is do just do compilation, and run the type checker without emitting in a separate thread so even if it's slower, your build still finishes fast. That might currently work with swc? But the idea of a much faster type checker is also very exciting!

**Comment by kyegupov** [comment]
@kdy1 what's the current status? What's the most up-to-date branch in your fork? I have a feeling you won't be able to pull this alone. Maybe we can create a plan to "move Mount Fuji" and get more people involved?

**Comment by kdy1** [comment]
@kyegupov 

As for the current state of affairs, type reasoning is somewhat implemented. Just look at my fork's dts Branch. To create a dts file, you need to know the type of exported function and variables, so type reasoning is required. There are many functions that have been implemented, but there is still a long way to go.

But I'm so busy these days that I don't have time to invest in SWC.

I want to make money. Although I think I will quit today due to pay issue, I got a job and I am preparing for my business. Unfortunately, in the case of type systems, you have to invest a lot of time, but you can't afford it. I expect some money if many people spend it later, but it takes too much time.

Also, the work is very difficult. It takes almost three days, 14 hours a day, to solve one type-inference test.

**Comment by nayeemrmn** [comment]
https://deno.land/v1#tsc-bottleneck

**Comment by trivikr** [comment]
FYI: TypeScript team doesn't have any plan to port TSC to Rust for reasons explained in tweet thread https://twitter.com/drosenwasser/status/1260722414012358657

**Comment by wongjiahau** [comment]
We need to recruit a few developers to achieve this.

**Comment by sciepsilon** [comment]
I'm interested! I don't know if I'm up to the task, but I'll at least spend the next couple days poking around the code and getting up to speed. 
> We need to recruit a few developers to achieve this.

**Comment by divy-work** [comment]
@sciepsilon I've formed a little team together with @wongjiahau to help @kdy1 work on this. 

Fell free to email!

**Comment by cakekindel** [comment]
Hi! 👋 I'm also very interested in helping with a rust port of TSC 😄, is this project public?

**Comment by wongjiahau** [comment]
@cakekindel Hi if you're interested you can join us at https://discord.gg/AN7QZs

**Comment by wongjiahau** [comment]
Sorry the link above was temporary, I just update it with a permanent one.

**Comment by mdbetancourt** [comment]
> The other approach you can use with babel is do just do compilation, and run the type checker without emitting in a separate thread so even if it's slower, your build still finishes fast. That might currently work with swc? But the idea of a much faster type checker is also very exciting!

i think this idea isn't useful for check errors (we can with the IDE) but is very cool for lib which depend on typechecks (metadata), for example in loopback there is 3 different results depending on what you use
ts-node with typecheck: it's okay (Function)

ts-node with transpile-only: error (Object)
![image](https://user-images.githubusercontent.com/22435967/96663664-1ad4ce00-131f-11eb-87f8-0eb69e1cb95c.png)
swc: error (undefined)
![image](https://user-images.githubusercontent.com/22435967/96663834-83bc4600-131f-11eb-934e-3e0355e3c81f.png)

Sample repo: https://github.com/mdbetancourt/ts-node-loopback you can try changing .mocharc ts-node/register to @swc-node/register

**Comment by kdy1** [comment]
Current status, as someone asked about it on slack.

Typescript type system can be implemented in three steps. Those are namely type inference, `.d.ts` generation, and type checking.

Currently the type inference and `.d.ts` generation is almost there.
I’m applying it to the famous libraries like rxjs to find bugs.
There are some, but it's being improved steadily.

For type checking, it can only check very simple errors. As there are so many type checking rules, it will be time-consuming task.

But it’s not open sourced, and I’m not going to open source it.

**Comment by remorses** [comment]
@kdy1 i hope you can start some sort of business with this project and be able to compete with tsc, I would be happy to pay to have a faster tsc and tsl alternative 

Wish you all the best!

**Comment by NoPhaseNoKill** [comment]
@kdy1 I would be interested in helping you out with this project. The type-checking for TS - considering it will be the main thing most web-developers use in the next 5 years - is horrendously slow. 

I also have buy-in from the company I work for to work on this for 2/3 months full-time. Please let me know if you're interested

**Comment by kdy1** [comment]
@NoPhaseNoKill 
Thank you, but the program has been implemented a lot and there are a lot of challenges to get help from others.
Of course, it would be great if it was completed quickly, but it's a proprietary software and I'm preparing a business with it.

**Comment by NoPhaseNoKill** [comment]
No worries at all. If you need anyone at any stage to test anything on medium/larger sized repositories, please let me know.

**Comment by kdy1** [comment]
@NoPhaseNoKill Thanks you for understanding. I would absolutely need tester. I'll ping you at the time.

**Comment by millsp** [comment]
> Typescript type system can be implemented in three steps. Those are namely type inference, `.d.ts` generation, and type checking.

@kdy1 It would be awesome if you could add also transformer plugins that leverage the type system

**Comment by andersekdahl** [comment]
We have a compilation step implemented as a TypeScript transformer that evaluates CSS in JS into static css.

Basically takes code like this:
```ts
function giveMeRed() {
  const red = 'red';
  return red;
}
const Comp = styled.div({ color: giveMeRed() });
const node = <Comp />;
```
And turns it into:
```js
const node = <div className="a" />;
```
```css
.a { color: red; }
```

It uses the TS type checker to go through great lengths to evaluate styles at compile time, and it would be really great if the type checker in swc would allow us to achieve the same results.

Important aspects of the TS type checker for us is being able to get a symbol from an identifier, and for it to work across modules.

Anyway, I understand how big of a task it is to recreate TypeScript, just thought that our use-case might be interesting to hear about.

**Comment by s-kris** [comment]
> @dsherret I'm porting tsc because it is wall-clock grade slow.

I literally decided to do this and landed here via my search journey. The discord link is dead, can you please share it again?
Thank you!

**Comment by kdy1** [comment]
@s-kris It will be developed as a propriety software.

**Comment by s-kris** [comment]
Ah! I just read [this](https://github.com/swc-project/swc/issues/571#issuecomment-752933785)
But it is an excellent business case. Enterprises would love to pay, it'll save them a load of programmer-hours. 
Wish you the best :)

**Comment by pbadenski** [comment]
Could you perhaps add a "X tests out of Y tests" to the status? To give a rough idea of how close you are to the finish line :D

**Comment by remorses** [comment]
It would also be cool to have a newsletter with new updates and progress made

**Comment by Nerixyz** [comment]
> 
> 
> It would also be cool to have a newsletter with new updates and progress made

There's already a blog with news on [swc.rs/blog](https://swc.rs/blog/).

**Comment by kdy1** [comment]
@pbadenski I'll do so :).

@remorses It seems good, but sometimes I don't have enough time to work on stc, so the mailing period might be strange.

**Comment by fabiospampinato** [comment]
@kdy1 It might be early, but are you seeing some encouraging performance numbers that you can share publicly?

If this is significantly faster and works well I can't imagine how anybody who writes TS professionally could pass on paying for something like this.

**Comment by kdy1** [comment]
> It might be early, but are you seeing some encouraging performance numbers that you can share publicly?

Yes, although I didn't do many optimizations, it's quite fast.
Compared to tsc, it's **very** fast.

**Comment by pbadenski** [comment]
Here's a random idea, what about crowd funding the effort? If it helps the
progress I'd definitely buy licenses up front on the back of amazing swc
experience.

**Comment by praveenperera** [comment]
> Here's a random idea, what about crowd funding the effort? If it helps the progress I'd definitely buy licenses up front on the back of amazing swc experience.
> […](#)

That's a good idea, [Onivim 2](https://onivim.io) did something similar. Where the earlier you got in the cheaper the license was.

**Comment by kdy1** [comment]
I love the idea of ` the earlier you got in, the cheaper the license was `, but I'm not sure about the funding because it's too hard to estimate when I can finish it.
Thanks anyway!

**Comment by s-kris** [comment]
@kdy1 It's okay. Just put a basic demo and open a payment page. I'm ready to purchase it as an early backer. If it goes viral it's for the best.

**Comment by JesusTheHun** [comment]
@kdy1 I have a large and heavily typed project. I would be more than willing to run some tests. Also if I can help in any way to make the development faster, please let me know. I'll buy your product day 1.

**Comment by JesusTheHun** [comment]
Also I second the idea of early backing. 
I'm willing to put a couple thousands dollars on the table if that can help you spin up the whole thing.
I need this yesterday.

**Comment by kdy1** [comment]
@JesusTheHun Thank you so much, but it's okay. I think I can match all tsc errors (few thousands test files) within a year even if I do it alone.

**Comment by prantlf** [comment]
As @nayeemrmn mentioned, from [TSC Bottleneck](https://deno.com/blog/v1#tsc-bottleneck) in Deno:

> TSC must be ported to Rust. If you're interested in collaborating on this problem, please get in touch.

Compete or cooperate? Or are you a Deno guy already, @kdy1 ? :-)

**Comment by kdy1** [comment]
@prantlf My tsc implementation is not related to deno and I don't think someone else is working on the typescript type checker.

**Comment by Beraliv** [comment]
Hey!

I'm really excited about the Rust port of tsc! 🔥

I'm still learning Rust, but if I can help with anything simple, I would love to contribute!

**Comment by kdy1** [comment]
I'm sorry but it's a proprietary software.

**Comment by Beraliv** [comment]
Ah, sorry, missed the message about it

Good luck!

**Comment by kdy1** [comment]
@lf94  I'm still working hard on it. I think few months are required to implement it fully.

TypeScript supports really weird use-cases, like returning an object literal from the constructor of a class.

**Comment by Jack-Works** [comment]
> TypeScript supports really weird use-cases, like returning an object literal from the constructor of a class.

Because it's valid JavaScript 🤣

**Comment by icaro-capobianco** [comment]
We would have flying cars by now if JS wasn't so messy, good luck mate, I am hoping you can do this!

**Comment by sanchezweezer** [comment]
> @lf94 I'm still working hard on it. I think few months are required to implement it fully.
> 
> TypeScript supports really weird use-cases, like returning an object literal from the constructor of a class.

May just ignore this cases in your compiler (or do it at first time)? I this this limitations isn't block main work flow... but missing this feature really block me to migrate all my projects to your compiler...

**Comment by kdy1** [comment]
@sanchezweezer Yeah, I'm going to do it, but it's kinda hard to skip some of tests. I have to skip one by one.

**Comment by OnkelTem** [comment]
Good luck @kdy1 
We're really interested in your work, ain't we folks?
Yeah, is there anything you can share by now?

**Comment by thomaschaaf** [comment]
@kdy1 will it stay closed source even with the support from vercel?

**Comment by kdy1** [comment]
@thomaschaaf I can't be sure at the moment. I decided to focus on making it work on simple real-world projects for now.

Previously I focused on implementing validation rules.

**Comment by Songkeys** [comment]
The status hasn't been updated for months. May we know the current progress?

**Comment by kdy1** [comment]
@Songkeys Not so much progress in the number of passing tests. I had too much tasks related to swc.

I made some improvements anyway.


 - optimized the performance,

Now it takes less than 3 seconds to create 6648 errors, while 5621 of them is a correct error. 

 - reduced the compile time,

Previously one module was so big and took 35+ seconds to compile in **debug*** mode, but it now takes less than 15 seconds.

 - resolved lots of tech debts

I restructured the project, resolved lots of lints.

**Comment by kdy1** [comment]
I unassigned myself just because it shows up in the task list.
I got a question about this from discord server, and I'm writing this to prevent confusion

**Comment by charrondev** [comment]
Is there any chance of this coming under a FoSS license? I’d be happy to land PRs getting more conformance tests passing if that were the case.

I’m not really sure that it will be possible to keep up to date with typescript itself if it’s just one guy working on it alone as an entire development team (backed by one of the richest companies in the world) forges ahead with changes to the language.

It’s almost backwards (in that I would expect the massive company to be the one with the proprietary project).

**Comment by kdy1** [comment]
No, and I'll hire developer once I earn money out of it.
And it's the biggest reason - I can't maintain it by myself so FOSS is not an option.

**Comment by franco-roura** [comment]
I guess we could still help you (If you want to) build a pipeline that takes the output of your tests and updates https://stc.dudy.dev/docs/status/ automatically when you push code to your closed source repo.

I know for a fact maintaining progress status websites is a boring task, and you're getting a lot of attention from the community. We all want to see you achieve this kind of goals dude, SWC marked the start of a new era for web development.

**Comment by kdy1** [comment]
@franco-roura 
I didn't work on the new type checker recently because I was busy due to a commercial project.
That's why I didn't update the numbers.

**Comment by osdiab** [comment]
Given that Vercel is leaning into SWC and an SWC-based typechecker would probably be the single biggest thing Vercel can do to speed up my NextJS builds, curious @leerob if there's any interest to provide resources to this effort.

Similarly, I can say the same thing RE:

- typescript-eslint performance is slow and often gets issues about it, if SWC typechecking was there it would make it 100x better
- As a result of that, VSCode also gets slow, so the biggest perf win I could think of for editing on a daily basis would be an SWC type checker, VSCode team ought to think about supporting this project

**Comment by wongjiahau** [comment]
Osdiab, using SWC-Typechecker with VS Code is probably not as easy as it sounds, because building a language server requires a very different architecture from that of a compiler.

**Comment by franco-roura** [comment]
> @osdiab, using SWC-Typechecker with VS Code is probably not as easy as it sounds, because building a language server requires a very different architecture from that of a compiler.

Yeah, specially if you’re not only looking for “compiled or failed” logs but also in-code error highlighting, autocompleting, actions applied when the file is saved, real-time detection per file and not per project, etc.

**Comment by kdy1** [comment]
I'll also provide a fast IDE plugin, of course.
It requires some more work, but it definitely worths the effort.

**Comment by andyfleming** [comment]
I ultimately think that a commercial version won't gain as much traction as a FOSS project. @zackradisic is starting an open source alternative called `tyty` ( https://zackoverflow.dev/writing/tyty ), but it's still early in development.

**Comment by kdy1** [comment]
@andyfleming  I already chatted with him. But still, I want fair rewards for my work and I'm sure open-sourcing the new typescript type checker will not give me enough rewards.

**Comment by sloonz** [comment]
Have you thought of a gofundme (or similar) "give me X money and it will be released under a open-source license" ? Might be an interesting experiment even if it fails.

**Comment by jrylan** [comment]
Honestly at this point, companies heavily invested in TypeScript that are profitable or have significant venture funding should be sponsoring this and making it OSS. Deno, and Vercel immediately come to mind. Deno especially, since the type checking is Deno is quite a bottleneck, if they could improve it, they would improve the developer experience, leading more people to adopt Deno, which would lead more devs to their paid hosting service. @kitsonk @ry

@kdy1 I want you to make money from this project, you deserves tons of money. But I think you're underestimating how lazy and unmotivated people are to change. The number of people that will pay for a faster type checker instead of just using the free one that's slower is a tiny tiny tiny fraction. I think it would be a hard sell in the corporate world as well. "You want the company to pay for a type checker that is 100x faster, but a free one is available? Just use the free one..."

You need sponsors, not licensors. 

Also another route to consider is the fact that Microsoft has been adopting Rust lately, if you truly perfected the type checking with all the existing nuances and absolutely obliterated the performance of the JS-based TS type checker, they could easily be convinced through sheer community demand into adopting your project and sponsoring/hiring you to work on it full-time.

**Comment by kitsonk** [comment]
The communication between @kdy1 and the Deno project is common and frequent.  It just doesn't always occur in public forums.  Also, recognise that just because something is a good idea doesn't mean that everyone agrees on what the right approach and priority is for something.

**Comment by kdy1** [comment]
https://kdy1.dev/posts/2022/1/tsc-go

**Comment by andyfleming** [comment]
@kdy1 Great to hear!

It's interesting you mention building a replacement bundler as well. Are there major shortcomings of esbuild today?

**Comment by charrondev** [comment]
> It's interesting you mention building a replacement bundler as well. Are there major shortcomings of esbuild today?

The bundler is this repo? It predates work on the typechecker.

@kdy1 I like the pragmatic choice here and am glad vercel is sponsoring the work!

**Comment by leerob** [comment]
We (Vercel) are very excited about all the amazing work @kdy1 is doing 🎉 🚀

**Comment by andyfleming** [comment]
@charrondev Compiler ≠ Bundler

The swc compiler, if I understand correctly, only strips the TypeScript types from the files. It doesn't _bundle_ in the dependencies, tree-shake, and build output bundles.

**Comment by kwonoj** [comment]
> The swc compiler, if I understand correctly, only strips the TypeScript types from the files. It doesn't bundle in the dependencies, tree-shake, and build output bundles.

Just to correct:

SWC have a bundler as well and it's work in progress for major improvement. SWC is set of the various tooling, transpilation is one of those part.

https://github.com/swc-project/swc/issues/3016

**Comment by cmoog** [comment]
@leerob Can you comment on how this will interoperate with Microsoft's tsc proper? It is difficult to evaluation what this means for swc, tsc, and the Web without any indication of the dynamic between the two teams.

In particular, what does @DanielRosenwasser think of this effort?

**Comment by andyfleming-shopify** [comment]
I vaguely remember the TypeScript team saying they didn't plan on writing the compiler in a different language. I think part of the rationale has to do with dog-fooding.

**Comment by andyfleming** [comment]
I vaguely remember the TypeScript team saying they didn't plan on writing the compiler in a different language. I think part of the rationale has to do with dog-fooding.

**Comment by fabiospampinato** [comment]
> I vaguely remember the TypeScript team saying they didn't plan on writing the compiler in a different language. I think part of the rationale has to do with dog-fooding.

I remember the same kind of argument. The thing is there is some merit to that, but no sane people would argue in favor of browsers implementing JS in JS, at some point the language becomes important enough that enormous effort is put into it to make it faster, I guess the TS maintainers believe TS is either not important enough, is fast enough, or they physically don't have the resources to make it faster..

**Comment by somebody1234** [comment]
@fabiospampinato see [this comment](#issuecomment-629717164)

**Comment by yanckst** [comment]
I have high expectation on this feature. I just replace the `babel-loader` and I saw huge performance benefits. I guess that having the other work in progress features detailed here [tsc-go](https://kdy1.dev/posts/2022/1/tsc-go) will have huge impacts as well.

Good job on that! 🚀

**Comment by stavalfi** [comment]
Hi, is there an update ? :)

**Comment by austindd** [comment]
So, I'm interested in contributing to this effort, and I have a few questions to ask the swc maintainers:

1. What would an ideal "TypeScript checker" do within the swc pipeline?
2. Is it mostly just to scan the AST/source and errors/warnings?
3. What about propagating type information within the core AST nodes?
4. Should type information be used to perform optimizations?
5. Should it have a public API?
6. Should the core AST implementation be changed to the TypeScript compiler AST, or should there be a conversion step to translate between them?

It would be a huge step forward to create an outline that addresses these and other questions.

**Comment by kdy1** [comment]
@stavalfi No due to some internal issues.

@austindd 

1. It verifies type
2. No
3. Not sure if I'll implement this
4. Maybe
5. Of course
6. Conversion is better

**Comment by kdy1** [comment]
Also, I'm considering withdrawing the plan for open-sourcing it

**Comment by gamer003** [comment]
You haven’t even shipped anything and you’re already saying “maybe I’ll just take my ball and go home”. Get out of here with that nonsense. You’re holding on to some delusion that everyone is going to pay you for this tool. They’re not. We're not entitled to you doing this work for free, but that doesn't mean that the community will accept a paid solution.

All you’re doing is delaying someone else leading the charge on this. This game is annoying and childish.

And what is Vercel paying you for? It’s in their best interest for you to contribute this as OSS, and here you are embarrassing them instead. ( @leerob ).

(That's the correct pattern for projects like this, in my opinion, by the way. A company that has a vested interest in a technology or stack should be sponsoring an effort like this. I assumed that was what was happening at this point.)

**Comment by KnorpelSenf** [comment]
> 4. Maybe

If you're talking about optimising runtime code, then this won't be possible because TS types don't actually guarantee anything. There can't be assumptions about the code that would allow it to run faster, because all data types could be completely different from what TS believes.

**Comment by fabiospampinato** [comment]
Personally I'm much more interested in this project not getting abandoned then in what form it will be licensed. I'd really like to experience another esbuild type of step change where suddenly we realize that we have been actually writing it wrong, and it's possible to make it 50~100x faster. And type checking performance is a much bigger problem than bundling performance in my opinion, with HMR even WebPack is fast after a bit, but TS is just too slow, unacceptably slow.

**Comment by osdiab** [comment]
If it's good I/my company would pay for it but if it comes in 5 years then TypeScript itself may have changed significantly/I might not even be using it anymore, so I'm more interested in this existing ASAP above how it ends up being licensed. Anything that increases the chance that this will materialize sooner in good quality, I am in favor of. But it's kdy1's project and so that's his decision to make.

**Comment by gamer003** [comment]
Smaller companies might pay for a solution, but at big companies licensing software (even if a low price) can be complicated and a liability.

Regardless, there's clearly enough support for someone to tackle the project, but either work on it or don't

I'd rather see someone else take on the project at this point. Working without transparency and talking about changing the licensing on a whim are major red flags.

![Red Flags](https://i.giphy.com/media/6r4R1HHNsfZGuOtO5V/giphy.gif)

**Comment by kdy1** [comment]
I'm sorry to confuse you. The TypeScript Type Checker will be released as an open-source.

I changed my mind thanks to one famous company that wanted to donate to the project.
(I forgot that Vercel wasn't the only sponsor)



Btw, I think tsc would be changed a lot while I stopped working on it...

**Comment by KnorpelSenf** [comment]
@kdy1 if I understood you correctly, you've dropped the plan to port tsc to Rust and will port it to Go instead. Are you willing to share the source code of your abandoned attempt in Rust?

**Comment by kdy1** [comment]
No, it's umm.. Too dirty?

In fact, there are some codes that are embarrassing to disclose as an open-source even though I wonder who will look at it. There are many rules that I didn't know, so I changed the code so often and the code became spaghetti.


e.g.
The `Type` enum has `ClassInstance` and `Instance` because I didn't know that the code below is valid.

```js
class Factory {
    static create() {
        return new this()
    }
}
```

**Comment by KnorpelSenf** [comment]
Haha that's fair, I think we all know what it's like to read old code of ourselves :D

I am mainly just asking out of interest. I am not too familiar with the code base of TSC so I'm intrigued how one would go about implementing it. As it's already clear that this approach won't turn out too useful, I doubt that I'll turn it into something useful. But hey, maybe I can learn something :)

**Comment by goloveychuk** [comment]
@kdy1 are you sure you will have better performance by porting to go?
The theory here - because 90% of type checking is conditions checks, `nodejs` (after warming, classes compilations and optimisations) could be as much fast as `go`.
Maybe it make sense to explore multithreading instead.

**Comment by kdy1** [comment]
Yep. The main problem is the cpu core it uses.

Problem is not optimization

**Comment by goloveychuk** [comment]
So by porting you mean making it multithreaded too (using coroutines, channels, etc)?

**Comment by kdy1** [comment]
Of course. What's the point of porting to go at the first place if we are going to use only 1 core?
If go is single-threaded or javascript was multi-threaded, I wouldn't start it. If then, contributing to `tsc` is the correct way.

**Comment by chentsulin** [comment]
This discussion about multi-threaded compilation might be relevant: https://github.com/microsoft/TypeScript/issues/30235

**Comment by willstott101** [comment]
Just to join the dots for anyone unaware, there's a public repo where work on `stc` kdy1's type checker is taking place:

https://github.com/dudykr/stc

**Comment by kdy1** [comment]
Closing as the stc is now abandoned. TypeScript was not something that I could follow up on in an alternative language.

**Comment by Kingwl** [comment]
Sorry to hear that, but respect you for your contributions and efforts here!
