### ISSUE TITLE
ES2015 and up don't handle ESM default exports correctly

### ISSUE THREAD

**Issue by lgibso34** [swc-project/swc#5768]
### Describe the bug

I ran into this when using @swc/jest. The error is `ReferenceError: Cannot '_default' before intialization`

`const` seems to have start being used in 1.2.212 causing this issue. Previous versions were using `var` which gets hoisted.

![image](https://user-images.githubusercontent.com/35611471/188654691-c96d752b-85ad-4395-989a-2640fc6cb8c6.png)

### Playground link

https://play.swc.rs/?version=1.2.212&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUdDQVLC1U6jm5VIAgqLUktKiPAWljNScnHwlXq5aAErKsCUtAAAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1Fm2hG9%2BhhzCuEhz8Q%2BNATfDdK4eE7Ib5PGmnFY7MTsUKWIZCS9X%2ByFBtheHEl0oTVahVZeOu2srCVRuM1%2BP51jTkDCYz2wCeKPrk5zZYLsciDNyRTUu4ml1ZMX%2B3YezHOWXqJOa0gvoNOscen7N9PPIHEdWl27wAAAA%3D

### Expected behavior

The code should compile correctly in a usable manner and not error.

### Version

1.2.212

**Comment by magic-akari** [comment]
The error occurred because of TDZ which is expected.
We try to keep this feature when transformed from ESM to CJS.

See this example, run it in node native ESM environments, you will get the error.

```JavaScript 
import foo from "./index.js"; // self import

console.log(foo); // ReferenceError: Cannot access 'foo' before initialization

export default () => {
    return "hello";
};
```

move the `console.log` as following.
```JavaScript 
import foo from "./index.js"; // self import

export default () => {
    return "hello";
};

console.log(foo); // [Function: default]
```

**Comment by kdy1** [comment]
I tested using chrome but
```js
Object.defineProperty(window, "__esModule", {
    value: true
});
Object.defineProperty(window, "default", {
    enumerable: true,
    get: ()=>_default
});
const _default = ()=>{
    return "hello";
};
```

worked.
So this issue is invalid

**Comment by lgibso34** [comment]
I'll try to create a repo where I am experiencing this.

I ran into this at work so I'll have to try and recreate this on my home machine.

**Comment by lgibso34** [comment]
Okay [here is a repo](https://github.com/lgibso34/swc-issue) to reproduce the issue.
I do wonder if this is actually an issue or just a limitation with CommonJS now that I understand what is happening. I think @magic-akari is right about the TDZ issue. I look forward to understanding this from you all's perspective.


Files of interest: 

- https://github.com/lgibso34/swc-issue/blob/master/src/temp.tsx
- https://github.com/lgibso34/swc-issue/blob/master/src/constants.tsx

1. So `temp.tsx` default exports a React component.
2. That React component is imported in `constants.tsx` and placed in an object.
3. `temp.tsx` imports `somethingElse` from `constants.tsx` but in CommonJS (what Jest uses) technically the JS object that `<Temp>` is stored in is also "pulled in" or whatever the term is. (no tree shaking like ESM)
4. This causes the `ReferenceError: Cannot '_default' before intialization`


Is this just expected with CommonJS?


IMPORTANT: 
This code WORKS if you change the `jsc` `target` to `es5` (not what I want to do).  And of course it works with babel before trying out `swc`. I would expect `swc` to just work as a drop in replacement for babel and I would expect it to work for `ES2015` and up.

Thanks for looking!

**Comment by magic-akari** [comment]
@lgibso34 try this https://gist.github.com/magic-akari/5a8a1bee1c78aa94b383572bed2ce44e 
clone and run npm test, you will get the same error in native ESM environment.

This line is where the error is located.
https://github.com/lgibso34/swc-issue/blob/361404abc0f8aba226ecfa6d9f05af5f8e7d0202/src/constants.tsx#L4

You can get rid of the error by using the lazy trick.

```JavaScript 
const someObj = {
  Temp: ()=> Temp,
};
```

**Comment by lgibso34** [comment]
Thank you for spending the time on this. I appreciate your feedback. The lazy trick is a good solution.

Could you explain why this is happening? Like it works when you set the target to ES5 and it worked with babel previously.
Could you answer some of my questions above just so I have a better understanding?

I'd like to leave here with complete understanding since to me it "seems" like an issue that it works with ES5 but not with ES2015 and up. I know now that it may not be an issue with `swc` but I'd like fully be aware of why.

Thanks again.

**Comment by magic-akari** [comment]
When you write `import`/`export` statements, because they are ESM syntax, swc attempts to preserve the behavior of the ESM feature.

If you do not need / do not care the ESM behaviour, try the following.

```typescript
import foo = require("./foo");  // CTS syntax, cjs require in TypeScript

function x(){
}

// `module.exports = ` in CTS
export = {
    bar: 42,
    x,
}
