### ISSUE TITLE
One comment line is removed

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#5783]
### Describe the bug

One of the comments gets removed

### Input code

```typescript
function x(y) {
  return y && // 96 is one less than the char code
  // for "a" so this is checking that
  // it's a lowercase character
  false;
};
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2019",
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "isModule": true,
  "module": {
    "type": "es6"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.249&code=H4sIAAAAAAAAAyWMwQrCQAxE7%2F2KoYeqp94E6deEmLWLywaSFC3ivxspDHOZ96ZsnaNqx%2Fu8X%2FAZAJPYrGPHNGGecbuiOrQLmrgjVupZAl7JwHqXVBIrahhphGuuKWR4FX7W%2Fvg7cVA1Tg5C05cYkx8vxCGWe6Hmsgzf5QefqlMMlAAAAA%3D%3D&config=H4sIAAAAAAAAAy2MSw6CUAxF99I4JKAOTGQPLqKpFR7xfdL2RQlh7xZwdnvv6VngpDRyROhhNCvad92kObVHq5aF2yxDpx8SggYmJegXKCjKsiWdk%2BHX35mcJwnFdswrk8prA4YysG2EXs%2BXu68mmPSVJW4CYSTbQ00WIjuI1XJECwTr6oKgj%2Fysbz6MDcT%2FtYDNhXfxzckfbCK5rswAAAA%3D

### Expected behavior

= Input

### Actual behavior

```js
function x(y) {
    return y && // for "a" so this is checking that
    // it's a lowercase character
    false;
}
;
```

### Version

1.2.249

**Comment by RiESAEX** [comment]
use `jsc.preserveAllComments = true`
https://play.swc.rs/?version=1.2.249&code=H4sIAAAAAAAAAyWMwQrCQAxE7%2F2KoYeqp94E6deEmLWLywaSFC3ivxspDHOZ96ZsnaNqx%2Fu8X%2FAZAJPYrGPHNGGecbuiOrQLmrgjVupZAl7JwHqXVBIrahhphGuuKWR4FX7W%2Fvg7cVA1Tg5C05cYkx8vxCGWe6Hmsgzf5QefqlMMlAAAAA%3D%3D&config=H4sIAAAAAAAAAzWMSw7CMAxE72KxrFpggUR2iDWHsIJbUuUn2wGqqncnLbCbGb15M%2BzEPiggGHioZjFdN0qK7XcVTUxt4qGTl2ULDYxiwcyQkYV4TTJFxXe9k628ZZd1w%2BrUoxdaGshMFX7SxftrCoGiChjlQg0o8kC6vuW4P5zrUxmj9InDKmdCq1soUV2gCmLRFFCdhWWpbie3dC%2Be%2FsLwazPolGkTnyr5AdsWiWLoAAAA

**Comment by kdy1** [comment]
`jsc. preserveAllComments` is for typescript types, and I think we should preserve comment in this case even without the option
