### ISSUE TITLE
`Scope`'s `data.all` loses values when using function scopes in a resolver

### ISSUE THREAD

**Issue by 4JX** [swc-project/swc#5789]
### Describe the bug

While playing around with the resolver I found out that it does not handle function block scopes well.
![](https://cdn.discordapp.com/attachments/631118340638769152/1017598031379566662/unknown.png)

It would seem that when renaming functions, the data at `data.all` decreases by 1 with each rename. This can be seen by adding a debug log here:
```diff
@@ -171,6 +171,7 @@ impl Scope {
         // We can optimize this
         // We only need to check the current scope and parents (ignoring `a` generated
         // for unrelated scopes)
+        dbg!(&self.data.all);
         if let Some(lefts) = reverse.get(symbol) {
             for left in lefts {
                 if left.1 == id.1 && *left.0 .0 == id.0 {
```

![](https://cdn.discordapp.com/attachments/631118340638769152/1017596194840649810/unknown.png)

Which means the check for 
```rs
if self.data.all.contains(left) {
    return false;
}
```
Will never trigger, always returning the same name for all variables.

I assume that this behavior is not intended, and that it stems from the calls to `prepare_renaming` which are only done when functions are involved, but this is just a wild guess.

### Input code

```rs
fn main() {
    tracing_subscriber::fmt()
        .with_max_level(LevelFilter::TRACE)
        .init();

    let path = Path::new("./main.js");

    let cm = Arc::<SourceMap>::default();

    let fm = cm.load_file(path).unwrap();

    let module =
        parse_file_as_module(&fm, Default::default(), ES_VERSION, None, &mut vec![]).unwrap();

    swc_common::GLOBALS.set(&swc_common::Globals::new(), || {
        let handler = Handler::with_tty_emitter(ColorConfig::Auto, true, false, Some(cm.clone()));
        let c = swc::Compiler::new(cm.clone());

        let unresolved_mark = Mark::new();
        let top_level_mark = Mark::fresh(Mark::root());

        let module = module.fold_with(&mut resolver(unresolved_mark, top_level_mark, false));

        let process = c.process_js(&handler, module.into(), &Options::default());

        let output = process.code;

        println!("{output}");
    });
}
```

### Expected behavior

It should not lose values like it does right now.

### Version

Git rev b5deaa7

**Comment by kdy1** [comment]
No this is intended and not a bug
