### ISSUE TITLE
JSXAttr - Cannot access child JSXExpressionContainer node (it doesn't exist)

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#584]
In the following code:

```ts
const t = <test other={4} />;
```

There exists a JSX expression container (`{4}`).

See how babel does it here: https://astexplorer.net/#/gist/2d0719965754c06060a1df22226b25c8/58256bfb6f00f76351f71be3e1908744d98f395b

However, that is not accessible in the AST. It goes straight from the attribute to the number literal instead.

Should it instead go from attribute -> expression container -> number literal? I can work around attribute -> number literal if not and that's no big deal for me. I just wanted to point out this to have a discussion. Maybe it's an inconsistency?

Also, see how the typescript compiler does it here: https://ts-ast-viewer.com/#code/MYewdgzgLgBLC8MA8UCm0YigC1QJ3gG8AWAXxgHoA+AbiA

**Comment by kdy1** [comment]
Fixed it and published a new version
