### ISSUE TITLE
function arguments are unexpectedly replaced with void 0 in recursive functions

### ISSUE THREAD

**Issue by chentsulin** [swc-project/swc#5846]
### Describe the bug

When "Minify" and "Compress" are enabled and all of compress options are disabled, function arguments seem be unexpectedly transformed in recursive functions.

![](https://user-images.githubusercontent.com/3382565/189840498-872cb285-d44e-4ad4-a196-d6ba1b4fc124.png)

And the following code is broken in the latest Next v12.3.0 with `swcMinify: true`.

### Input code

```typescript
function processNode(
    node: DataNode,
    index?: number,
    parent?: { node: DataNode; pos: string; level: number },
    pathNodes?: DataNode[],
  ) {
    const children = node ? node[mergeChildrenPropName] : dataNodes;
    const pos = node ? getPosition(parent.pos, index) : '0';
    const connectNodes = node ? [...pathNodes, node] : [];

    // Process node if is not root
    if (node) {
      const key: Key = syntheticGetKey(node, pos);
      const data = {
        node,
        index,
        pos,
        key,
        parentPos: parent.node ? parent.pos : null,
        level: parent.level + 1,
        nodes: connectNodes,
      };

      callback(data);
    }

    // Process children node
    if (children) {
      children.forEach((subNode, subIndex) => {
        processNode(
          subNode,
          subIndex,
          {
            node,
            pos,
            level: parent ? parent.level + 1 : -1,
          },
          connectNodes,
        );
      });
    }
  }

  processNode(null);
```

https://github.com/react-component/tree/blob/63644b4edd0386cd3d3153837a2998c989dbf47c/src/utils/treeUtil.ts#L225-L268

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": false,
        "booleans": false,
        "booleans_as_integers": false,
        "collapse_vars": false,
        "comparisons": false,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": false,
        "evaluate": false,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": false,
        "hoist_vars": false,
        "if_return": false,
        "join_vars": false,
        "keep_classnames": false,
        "keep_fargs": false,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": false,
        "negate_iife": false,
        "properties": false,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": false,
        "switches": false,
        "typeofs": false,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": false,
        "const_to_let": false,
        "pristine_globals": false
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.0&code=H4sIAAAAAAAAA2WSTW%2BDMAyG7%2F0VvhU0RtcrqOthm6ZqUsUd9UBpKFFpgpJ0WlXx3%2Bd8kCDKARI7r533Mc2N1YpyBr3gNZFyz08kWgAw%2FGbwWalKRxKMUHYif9sM2O16JEJH%2BkoQpjD0mB3PoecyA6kEZeccOvJLulEIg5WqVp%2BU26AqD8kihgdma86kgrql3Qk7wMaUh635lFcizuTD5QrB%2B311JQfI4OTqyNyXwGsE9Zmogkuq3Ub26inmE2ssxgLLt2WQ4puRWpmCoUaZpqm%2Fe2KiunV5yBeoXK2gsBjtedoA1UsFgnOlGTYQ6Yy1Oba6kHsGP%2BSObeSdqZYoWn8ThRFzONE24nwi0E7xsK1hZ5W4tTEzbrQ9t8QePmq8F3pCDoMzF6CAnlbXjQo3QJc3O3iBdTLpj8WmxGxqMFTw1lXXHav6EumLGyfDDJefta7lQI0xD8vt04aLr6puo0jejubvBFzs7BQ37x7L7I%2B2zyiZBnZTZuD1c7Qzok9gAkFPCDm%2BroNgCMtnWABuxoMjhIymFvRA4vwf3GsSbrADAAA%3D&config=H4sIAAAAAAAAA22TTZLjIAyF78K6F11ZzKIP0Ls%2BA0VAOGQAuZBIx5XK3UckLhvbs0Mfz7J%2BHg91Jau%2BHmo0haC0E02ZzV19KZ5GIFvCyOpDMQnyJhI8JTBlABYJ0OnzdJLriEgwCz5UCjn4qSWzmMYCRO0sH9UEmWnRmVLwdw3PiBFMPgJtSIfMMEBZLy3GaEYCfTMbmqSVQJi3rDI4PRYce5xd4IBZwgU6ME5bdGszLhSwHG7QiSSPiDJJeVvo4FyHoQ1ypnAzsRpeZXB%2FDUR%2Bu6ALBmLta1fyG23rfbNNt8HrAlzLmuuKIW81fwGk2GiIskmw416Wskf%2FkYXsZaU8LVT23VWWYZAWdQh%2B7bPVDoVDl6qAqxZao%2FYANyVTcKDBe5l7B38D20uXrvkT%2FRrL%2FExXwDvUO4%2FNtFniAL%2BlMO4XM%2FNk%2BLJnNKUzxkOKBHxBd8AyDMY9LOLn%2B7inNTuQYYPrLip1YfMda0Yd2xNcpi3ekK%2F0EPG8%2BlneajJ5WFz6bABdbeDxGuDrEf9Rz%2FXRcqnNWfQz61r8%2FAd9p4itKAQAAA%3D%3D

### Expected behavior

```ts
const connectNodes = node ? [...pathNodes, node] : [];
```

`pathNodes` should be kept.

```ts
const connectNodes=node?[...pathNodes,node]:[];
```

### Actual behavior

```ts
const connectNodes = node ? [...pathNodes, node] : [];
```

`pathNodes` is replaced with `void 0`.

```ts
const connectNodes=node?[...void 0,node]:[];
```

### Version

1.2.239+

### Additional context

I guess this bug was been introduced in one of these commits:
https://github.com/swc-project/swc/compare/a9aadbe800fa6c2c7ee24363b00fd77d3497ddfd...v1.2.239

**Comment by Austaras** [comment]
This works as expected -- you don't pass pathNodes, so it's inlined with undefined

**Comment by kdy1** [comment]
@Austaras Seems like issue is the call in function body

**Comment by chentsulin** [comment]
@Austaras 

The first time the `processNode` function is called, the following `children` variable fallbacks to the value of an outer variable called `dataNodes`:

```ts
const children = node ? node[mergeChildrenPropName] : dataNodes;
```

And then the `processNode` function is called again in the `forEach` loop:

```ts
  if (children) {
      children.forEach((subNode, subIndex) => {
        processNode(
          subNode,
          subIndex,
          {
            node,
            pos,
            level: parent ? parent.level + 1 : -1,
          },
          connectNodes,
        );
      });
    }
```

This time, the fourth argument is present, so I think `pathNodes` should not be inlined with `void 0`:

```ts
function processNode(
    node: DataNode,
    index?: number,
    parent?: { node: DataNode; pos: string; level: number },
    pathNodes?: DataNode[],
  ) {
    const children = node ? node[mergeChildrenPropName] : dataNodes;
    const pos = node ? getPosition(parent.pos, index) : '0';
    const connectNodes = node ? [...pathNodes, node] : [];
```

**Comment by Austaras** [comment]
Oh, I know. This can be reduced to
```js
function foo(x) {
  console.log(x)
  if (z) {
    foo([1])
  }
}

foo()
```
and is indeed caused by my PR which remove recursively referenced function.
