### ISSUE TITLE
visit_mut_program not called

### ISSUE THREAD

**Issue by ido-pluto** [swc-project/swc#5849]
### Describe the bug

I create a plugin for SWC

I implement a visitor with `VisitMut` and only `visit_mut_program` method isn't being called
 

### Input code

```typescript
impl VisitMut for DynamicImports {

    fn visit_mut_program(&mut self, program: &mut Program) {
      println!("{}", "visit_mut_program called");
      VisitMutWith::visit_mut_children_with(call, self);
    }

    fn visit_mut_call_expr(&mut self, call: &mut CallExpr) {
        self.visit_mut_call_expr_like(call);
        VisitMutWith::visit_mut_children_with(call, self);
    }

    fn visit_mut_expr_stmt(&mut self, expr: &mut ExprStmt) {
        if let Expr::Call(call) = &mut *expr.expr {
           ...
        }
        
        VisitMutWith::visit_mut_children_with(expr, self);
    }

    fn visit_mut_ident(&mut self, ident: &mut Ident) {
        self.stop_method_to_return_ident(ident);
        VisitMutWith::visit_mut_children_with(ident, self);
    }
}
```

### Expected behavior

call to `visit_mut_program`, so I can edit the `Program` struct

### Version

swc_core = { version = "0.23.5", features = ["plugin_transform"] }

### Additional context

Happens when using the `test` macro

**Comment by orionmiz** [comment]
Have you been running the test without any parameters which can show the stdout in test?

If so, read these stackoverflow answers: [why-doesnt-println-work-in-rust-unit-tests](https://stackoverflow.com/questions/25106554/why-doesnt-println-work-in-rust-unit-tests)
