### ISSUE TITLE
SWC adds a redundant semicolon after `export default function...`

### ISSUE THREAD

**Issue by chilipepperhott** [swc-project/swc#5850]
### Describe the bug

SWC seems to be adding a redundant semicolon after all `export default function...`

It doesn't seem to happen when `minify` is enabled.

This is not a huge bug by any means, but it does influence the ability for SWC to format code. I know that it is not it's current objective, but it has potential.

### Input code

```typescript
export default function test(){
    return "hi"
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.0&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUUgrzUsuyczPUyhJLS7R0KzmUgCCotSS0qI8BaWM1JycfCVrrlprAEdTyJM2AAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F00WXeQOPYRwlODiH5ICNcZ3r11cshtm3rwKb7GwVcjIQjySlKj4gQ3IBhTLLiuYjvXqQC%2FUDCjySToQWR%2Fr0mefktAEDAQX3VGGzKaQmUTuCePp%2F2TrrpD2axQVtGT6OZ%2FQbsf8OXlNUPmi9gUibsF1uAAAAA%3D%3D

### Expected behavior

SWC should not add a semicolon if one is already there.

### Actual behavior

SWC adds a semicolon:

```javascript
export default function test() {
    return "hello";
};
;
```

### Version

1.3.0

**Comment by orionmiz** [comment]
Semicolon after block statement is not necessary.

Parser treats it as a empty statement.

Also, other parsers transform like that as well.

So it's not a bug.

You can test in other parser from here:
[AST Explorer](https://astexplorer.net/)

**Comment by magic-akari** [comment]
Yes, it's empty statement.

see this example
```JavaScript
function test(){
    return "hello";
};;;;;
```

```JavaScript 
function test() {
    return "hello";
}
;
;
;
;
;
```

https://play.swc.rs/?version=1.3.0&code=H4sIAAAAAAAAA0srzUsuyczPUyhJLS7R0KzmUgCCotSS0qI8BaWM1JycfCVrrlprEAAA9aeUfysAAAA%3D&config=H4sIAAAAAAAAAy2LQQ6AIAwE%2F9IzB8PBA3%2FwEQ1WgxElbUkkhL8LxttmZrbCIR5chYQsxGNJuRQfcEA%2BongOScH0rKMNT6FmQJF30pGInayFjuK95pPGX0uiT82DB1l%2Bo5ypvdeOdBRwAAAA
