### ISSUE TITLE
[TS] Exports not working as expected

### ISSUE THREAD

**Issue by maugenst** [swc-project/swc#5858]
### Describe the bug
In Typescript it is allowed to have more than one export, also of different types, per file. Swc does NOT export others than classes. See below.

### To reproduce:
Transpile this code snippet:
```
export interface ITest {
    run(props: TestType): void;
}

export type TestType = {
    a: string;
    b: ObjectType;
};

export type ObjectType = {
    b: any;
};

export class Test implements ITest {
    constructor(props: TestType) {
        this.run(props);
    }

    run(props: TestType): void {
        console.log(`Type: ${typeof props}`);
    }
}

new Test({a: 'a', b: {b: 'Hallo'}});
```
or open the playground (link below)

### Config
```
{
  "test": ".ts?$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true
    },
    "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true
    },
    "target": "es2022"
  },
  "exclude": [
    "src/app/static/"
  ],
  "module": {
    "type": "es6"
  }
}
```

### Expected behavior
The generates js file should have the types exported.

### Actual behavior
Generated files does NOT have the types exported.

```
export class Test {
    constructor(props){
        this.run(props);
    }
    run(props) {
        console.log(`Type: ${typeof props}`);
    }
}
new Test({
    a: 'a',
    b: {
        b: 'Hallo'
    }
});
```

### Version
@swc/cli: 0.1.57, @swc/core: 1.3.0

### Additional context
No response

**Comment by kdy1** [comment]
Types are expected to be stripped out

**Comment by maugenst** [comment]
Hm ... Thanks for the quick reply ... So I tested you advice and the stripped out types are converted like this:

Input:
```
export type TestType = {
    a: string;
    b: ObjectType;
};

export type ObjectType = {
    b: any;
};
```

Output:
```
export { };
```

https://play.swc.rs/?version=1.3.0&code=H4sIAAAAAAAAA0utKMgvKlEoqSxIVQhJLS4JATFsFaq5FIAg0UqhuKQoMy%2FdGsxNslLwT8pKTQYrsuaqtebiSkXSjpCDGwDUkZhXCVYKAD5F5hZpAAAA&config=H4sIAAAAAAAAA0WPwQqDQAxE%2FyX0KLV46MFLL1Loof2B0kOIUSy77pJEUMR%2Fr9uivSUzE15mBmM1KOFoejlABm8lKGeIKMqSJp16w3FN2BRZSbpoa8x0lRp0yhnUTEHQgiiUJkNSph59Rzcfg9ie4zGtFTc4OLtK8Fv8ZzzQs0Yk%2FlvLChLstQni0y%2BOW6Sp2ng7bhPubFij4f8apeVUj7U4FQUsCUZuqBnKJ6hQjjHmamgd5fDKwId6cJxYqe738AzL8gHd4d2DJwEAAA%3D%3D

Is this also an expected behavior?

**Comment by kdy1** [comment]
yes

**Comment by maugenst** [comment]
what is your advice?

**Comment by maugenst** [comment]
Even a single export of a type is producing this:

```
export type TestType = {
    a: string;
    b: ObjectType;
};
```
Output:
```
export { };
```
