### ISSUE TITLE
Support for React Fast Refresh

### ISSUE THREAD

**Issue by IronSean** [swc-project/swc#588]
I took a look and couldn't find any mention of this anywhere. React has replaced `react-hot-loader` with with a new Fast Refresh system, which can be integrated with watch builds, babel, and webpack in order to do Hot Module Reloading.

I'm still working out exactly where the boundaries are myself in terms of what work to support this belongs in swc and what belongs in react or an external webpack plugin. But I wanted to at least get this on the radar as a Feature Request.

**Comment by jansedlon** [comment]
This is really important feature!

**Comment by phaistonian** [comment]
What I did, until this is supported, is to chain babel (`babel-loader`) as the last loader to _only_ hook the `page-refresh/babel` plugin.

It works like a charm.

**Comment by jansedlon** [comment]
@phaistonian Are you sure that u used it as a **last** loader? If use it as a last loader i get
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jansedlon/Documents/Work/AstrumQ/sportnect-frontend/src/index.js: Unexpected token (62:8)

  60 | const render = () => {
  61 |     ReactDOM.render(
> 62 |         <ApolloProvider client={client}>
     |         ^
```

If I use it as a first, I get 
```
ERROR in ./src/app-sportnect.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .inputSourceMap must be a boolean, object, or undefined
```

😅

**Comment by phaistonian** [comment]
Here's the loaders chain I use.

```js
[
  {
    loader: 'babel-loader',
    options: {
      cacheDirectory: true,
      envName: 'developmentWithReactRefreshAnsSWC',
      cacheCompression: false,
    },
  },
  {
    loader: 'swc-loader',
    options: {
      sync: false,
    },
    exclude: /(node_modules|bower_components)/,
  },
]
```

**Comment by kdy1** [comment]
Where can I find information about it?

I'm going to implement it soon.

**Comment by phaistonian** [comment]
@kdy1 

- [React package](https://github.com/facebook/react/tree/5b89d353e27a7ef07b40929f7343ebcc43bdaa58/packages/react-refresh) - contains the babel plugin
- [webpack loader](https://github.com/pmmmwh/react-refresh-webpack-plugin)
- A [blog post](https://mariosfakiolas.com/blog/what-the-heck-is-react-fast-refresh) on what this is about

**Comment by phaistonian** [comment]
@jansedlon Encountered this issue on a different repo.

Turns out babel expected an object and the swc-loader sends JSON string.

[This PR](https://github.com/swc-project/swc-loader/pull/13) introduces the `parseMap` option needed to make sure the callback from transformations passes an object not a JSON string.

```js
{
 loader: 'babel-loader',
}
{
  loader: 'swc-loader',
  options: { parseMap: true },
},
```

**Comment by jansedlon** [comment]
@phaistonian I'll try that, thanks!

**Comment by vovaguguiev** [comment]
I've started working on this issue, see: https://github.com/swc-project/swc/pull/1077. My approach so far is to port the original tests from the facebook/react repo: https://github.com/facebook/react/blob/b7d18c4daf244b991858cc9b0706b64589f4fd60/packages/react-refresh/src/__tests__/ReactFreshBabelPlugin-test.js and make sure they pass in my implementation. Please feel free to give early feedback if you have comments regarding the implementation

**Comment by kdy1** [comment]
Will be fixed with next version
