### ISSUE TITLE
`swc_html_parser` fails building

### ISSUE THREAD

**Issue by daxpedda** [swc-project/swc#5881]
### Describe the bug

Currently `swc_html_parser` version 0.31.3 can't build, failing with things like:
```
error: no rules expected the token `"application/xhtml+xml"`
    --> /home/daxpedda/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_html_parser-0.31.3/src/parser/mod.rs:8787:66
     |
8787 | ...                   js_word!("text/html") | js_word!("application/xhtml+xml")
     |                                                        ^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
```

### Version

`swc_html_parser` 0.31.3

### Additional context

I found that a lot of these missing "words" were added in https://github.com/swc-project/swc/pull/5838. So I assume what's missing is a new release for `swc_atoms`. I tried depending on the git version of `swc_atoms`, which did fix my problem.

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/commit/f0ca48784825382678dca56d59948758bfed5857
