### ISSUE TITLE
@swc\core\native\index.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by IronSean** [swc-project/swc#589]
I'm attempting to use swc with a project on windows 10 and getting the following error:

```
ERROR in ./ts/apps/index.tsx
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: \\?\$MY_DIRECTORY$\node_modules\@swc\core\native\index.node is not a valid Win32 application.
\\?\$MY_DIRECTORY\node_modules\@swc\core\native\index.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Development\JNC\royal_app_suite\src\Web\node_modules\@swc\core\index.js:53:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Development\JNC\royal_app_suite\src\Web\node_modules\swc-loader\src\index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
 @ multi ./ts/apps/index.tsx app[0]
```

I'm using windows 10 cmd prompt (not WSL).
node v2.13.1, x64 version.
webpack 4.41.4

The binary is `win32-x64`, should I be using 32-bit node? Or downloading rust myself to build it for x64? The installation instructions are a little unclear there, I interpret it to mean "the npm install command will install a prebuilt binary if it can. If you want to or need to build your own you should install rust. If you need to install rust on windows go to rustup.rs", but that installing rust is not necessary if you are using the prebuilt binary.

**Comment by IronSean** [comment]
node v2.13.1, x64 version.

**Comment by chrismcv** [comment]
Seeing the same thing with v12.14.1 on x64 node.

**Comment by Zerowalker** [comment]
same on 13.7.0 x64

**Comment by kdy1** [comment]
Do you use arm?

**Comment by Zerowalker** [comment]
Not that i know of, i just install swc with npm, and the node i use is x64.
Perhaps the one set for x64 isn't x64?

**Comment by aelbore** [comment]
im seeing the same issue. i got simple code only
![swc-error](https://user-images.githubusercontent.com/18069807/73726801-24a3aa80-476b-11ea-9d85-1c19ce165fdf.png)

**Comment by kdy1** [comment]
I hit this on my windows vm. I'll investigate this.

**Comment by Zerowalker** [comment]
Is it deploying the wrong build?

**Comment by kdy1** [comment]
@Zerowalker Yeah, I guess it's generating a binary fir x86 (32bit). According to log, irs target is i686.

**Comment by Zerowalker** [comment]
Ah that explains it, hope it's easy to fix!

**Comment by kdy1** [comment]
I think I fixed it with v1.1.19

**Comment by Zerowalker** [comment]
I still seem to have the issue, anyone else?

**Comment by kdy1** [comment]
@Zerowalker Did you installed v1.1.19?

**Comment by Zerowalker** [comment]
Yeah, i installed the latest (v1.1.19),
then i tried running "npx swc", and it fails complaining it's not a win32 application.

What did you change in appveyor?

**Comment by kdy1** [comment]
@Zerowalker I switched from appveyor to github actions. I thought it's fixed because logs from the actions do not print target-related messages. So I assumed that it was successfully built for win32-x64 nodejs.

**Comment by Zerowalker** [comment]
How does it know what to build, isn't it set somewhere, maybe that's where it's wrong?
The command to build it, the script i guess. Though i guess you already looked at that:s

**Comment by kdy1** [comment]
![image](https://user-images.githubusercontent.com/29931815/74141650-aba8c500-4c3a-11ea-9f54-64bb67694982.png)

swc@v1.1.19 works on windows.

```cmd
C:\Users\kdy\projects\swc-lab>cat package-lock.json | grep 'swc'
  "name": "swc-lab",
    "@swc/cli": {
      "resolved": "https://registry.npmjs.org/@swc/cli/-/cli-0.1.22.tgz",
    "@swc/core": {
      "resolved": "https://registry.npmjs.org/@swc/core/-/core-1.1.19.tgz",
```

**Comment by Zerowalker** [comment]
It indeed works, it i never really updated and had to uninstall and stuff until i could get it to work.
Sorry for wasting your time:(

Thanks!
