### ISSUE TITLE
Question on parser generated AST tree

### ISSUE THREAD

**Issue by 3cp** [swc-project/swc#590]
I try to evaluate swc parser to replace my usage of `@babel/parser`.

Is the AST compatible with `@babel/parser` result?

Also, `@babel/parser` has an `estree` plugin (which I use) to generate estree compatible AST tree. Does swc have something equivalent to produce `estree` output?

**Comment by kdy1** [comment]
> Is the AST compatible with @babel/parser result?
It's similar, but not same. For example, swc's does not have LogicalExpression and it's part of BinaryExpression.
Note that typings for the ast are provided.

> Also, @babel/parser has an estree plugin (which I use) to generate estree compatible AST tree. Does swc have something equivalent to produce estree output?

It does not currently. I'm not sure about roadmap here, but I think I would implement the feature.
