### ISSUE TITLE
isModule: 'unkown' not work correctly

### ISSUE THREAD

**Issue by willson-wang** [swc-project/swc#5921]
### Describe the bug

Why is there such a scenario, because some npm packages output commonjs and the syntax is es2015, but the environment in which our project needs to run is es5, so we need to process npm packages through babel or swc

Set sourceType: 'unambiguous' like babel to correctly identify esm and commonjs

### Input code

```typescript
const code = `
const index = [1, 2, 3].findIndex((item) => item === 1)

module.exports = {
	index
}
`
```

### Config

```json
{
    "filename": "input.js",
    "sourceMaps": false,
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "tsx": true
      },
      "target": "es5",
      "loose": false
    },
    "minify": false,
    "isModule": 'unknown',
    "env": {
      "targets": "ie 11",
      "mode": "usage",
      "coreJs": "3"
    }
  }
```

### Expected behavior

// commonjs module by require('core-js/xxx') not import ('core-js/xxxx'), If there is an import module in the commonjs module, the bundle finally built by webpack will report an error when running
require("core-js/modules/es.array.find-index.js");

var index = [
    1,
    2,
    3
].findIndex(function(item) {
    return item === 1;
});
module.exports = {
    index: index
};

### Actual behavior

when "isModule": true  => output import("core-js/modules/es.array.find-index.js");
when "isModule": false or 'unkown' => thread '<unnamed>' panicked at 'not implemented: automatic polyfill for scripts'

### Version

1.3.2

**Comment by kdy1** [comment]
`isModule` is unrelated to CJS
