### ISSUE TITLE
Next.js Chart.js broken when `swcMinify` enabled for non-development builds

### ISSUE THREAD

**Issue by grempe** [swc-project/swc#5935]
### Describe the bug

This bug was originally filed here where more details can be found. The issue has been narrowed down to seemingly broken output from swc.

https://github.com/chartjs/Chart.js/issues/10673

https://github.com/reactchartjs/react-chartjs-2/issues/1071

With NextJS, the library works well on development. But an error is thrown after running the app after building it.
`RangeError: minimumFractionDigits is out of range`.

If the next.js config is changed to `swcMinify: false` and a production build is done the issue goes away.

It seems that during production this line:

https://github.com/chartjs/Chart.js/blob/d4e106cc9cf19a273e5485ffaf6158f663e65717/src/helpers/helpers.intl.js#L4

The minimumFractionDigits and maximumFractionDigits in the options become NaN instead of 0.

There is sample code here created by the original filer of the bug:

https://github.com/LouisJackson/react-chart-test/blob/main/next.config.js

### Playground link

https://github.com/LouisJackson/react-chart-test/blob/main/next.config.js

### Expected behavior

React should not die when a page with the Chart compiled with swc is accessed.

### Version

"dependencies": {     "chart.js": "^3.9.1",     "next": "12.3.0",     "react": "18.2.0",     "react-chartjs-2": "^4.3.1",     "react-dom": "18.2.0"   },

**Comment by siinghd** [comment]
Would like to add that this started happening to me from version 12.3.

**Comment by alexphl** [comment]
Can confirm that the last release of Next where this issue doesn't occur is 12.2.5. 
Breaking change must have happened between that and 12.3.
