### ISSUE TITLE
Expression statement with dynamic import is parsed as expression statement and empty statement

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#594]
An expression statement with a dynamic import like the following:

```ts
import("test");
```

Is incorrectly parsed as an expression statement and an empty statement:

```
Node kind: Module
Text: "import(\"test\");"
Node kind: ExprStmt
Text: "import(\"test\")"
Node kind: CallExpr
Text: "import(\"test\")"
Node kind: Ident
Text: "import(\"test\")"
Node kind: ExprOrSpread
Text: "\"test\""
Node kind: Str
Text: "\"test\""
Node kind: EmptyStmt
Text: ";"
```

**Comment by dsherret** [comment]
That identifier's span looks like it needs to be fixed too:

```
Node kind: Ident
Text: "import(\"test\")"
```

**Comment by dsherret** [comment]
@kdy1 oh, I just realized the fix for this. Would it be ok if I started on this? Sorry! I should have spent a few minutes looking before filing.

**Comment by kdy1** [comment]
@dsherret Of course. Thanks!
