### ISSUE TITLE
Can't refer to class being defined in static function if it has a generic with the same name

### ISSUE THREAD

**Issue by airhorns** [swc-project/swc#5949]
### Describe the bug

`@swc` compiles erroneous code if you define a class with a generic type parameter with the same name as the class, and try to instantiate the class in a static function on the class. 

### Input code

```typescript
import type { Anything } from "anywhere";

class Example<Example> {
  static static = () => {
    return new Example();
  };
}
```

### Output code

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
class Example1 {
    static static = ()=>{
        return new Example(); // errors because the class is named Example1
    };
}

```

### Config

```json
{
  "env": {
    "targets": {
      "node": 16
    }
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "tsx": true
    },
    "target": "es2020",
    "loose": false
  },
  "module": {
    "type": "commonjs",
    "lazy": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.3&code=H4sIAAAAAAAAAzXLMQqFMBBF0T6reFjpGqKChQsJMn4DZgyTEQ2SvX9BrW5xuD7ETRSaI%2BHCwFkXzz8UzLIFVI7zsZBQZY2ZVpcSxtOFuFL7tsdlgKRO%2FfSlQ92gewQQ0l0YTMf31o29pVhT%2Fjx2lj1%2BAAAA&config=H4sIAAAAAAAAAy2OMQ7DIAwA%2F%2BKZIc3Qgd8gcKtGgJHtVKERf69pup2s89knYH2DP0EDP1FlYqWE4G%2F3MRxsEueoBRbkSdKrhgM8aG8okV9NwUHCSByU2ALKOzpQOS60yNW2HZR1WRfzM5HYjUfIMoVCac%2F4e8OqJkYqheomUw2f%2Fi%2BNLwcpK3iuAAAA

### Expected behavior

swc doesn't rename the class constant such that references to it in static functions work fine

### Actual behavior

swc rename the class constant but doesn't use the renamed constant in static functions and code breaks

### Version

1.3.3

### Additional context

 - This same code worked ok on `1.2.183`, discovered this bug when upgrading to `1.3.3`
 - The bug goes away if the name of the class and the generic parameter aren't the same
 - The bug goes away if there is no type import in the file

**Comment by kdy1** [comment]
Closing as fixed

https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAzXLMQqFMBBF0T6reFjpGqKChQsJMn4DZgyTEQ2SvX9BrW5xuD7ETRSaI%2BHCwFkXzz8UzLIFVI7zsZBQZY2ZVpcSxtOFuFL7tsdlgKRO%2FfSlQ92gewQQ0l0YTMf31o29pVhT%2Fjx2lj1%2BAAAA&config=H4sIAAAAAAAAAy2OMQ7DIAwA%2F%2BKZIc3Qgd8gcKtGgJHtVKERf69pup2s89knYH2DP0EDP1FlYqWE4G%2F3MRxsEueoBRbkSdKrhgM8aG8okV9NwUHCSByU2ALKOzpQOS60yNW2HZR1WRfzM5HYjUfIMoVCac%2F4e8OqJkYqheomUw2f%2Fi%2BNLwcpK3iuAAAA
