### ISSUE TITLE
Simplify licensing section to only mention Apache since project was relicensed

### ISSUE THREAD

**Issue by mbrukman** [swc-project/swc#5957]
### Describe the bug

The [`README.md`](https://github.com/swc-project/swc/blame/21cbc0d561109290c03e740d4c8ecffec1eb56f9/README.md#L88-L93) says that the project is under both MIT and Apache licenses and mentions files `LICENSE-MIT` and `LICENSE-APACHE`:

https://github.com/swc-project/swc/blob/21cbc0d561109290c03e740d4c8ecffec1eb56f9/README.md#L88-L93

However, commit https://github.com/swc-project/swc/commit/806c9db1a1c40e26402a08010ca74bc0f4221dab changed the project to be under the Apache license, deleted `LICENSE-MIT`, and renamed `LICENSE-APACHE` to simply `LICENSE`.

Should this section be updated accordingly to match what was done in that commit? 

However, that commit didn't say anything the license change, just said "chore(node): Publish v1.2.121" so was that an intentional change?

### Expected behavior

Expect the LICENSE file(s) and "License" section in `README.md` to match.

### Actual behavior

The present LICENSE file(s) and "License" section in `README.md` do not match.

### Version

As of latest commit https://github.com/swc-project/swc/commit/132a9380df0d8923587ecee14a655f9ecedc7ce2

### Additional context

Sorry if this isn't the right format for raising this issue; the only 2 templates available are "bug" and "feature request" and this feels more like a bug than feature request.

**Comment by kdy1** [comment]
It was intentional. I just forgot updating README.md
