### ISSUE TITLE
Ability to add `displayName` to all React components to prevent names from getting mangled

### ISSUE THREAD

**Issue by stevenpetryk** [swc-project/swc#5958]
### Describe the feature

It would be potentially useful to transform React components such that they're always given a `displayName` (when a reasonable name can be inferred):

**In**:

```ts
import * as React from 'react'

const Foo = () => {
    return <h1>Foo</h1>
}
```

**Out**:

```ts
import * as React from 'react'

const Foo = () => {
    return <h1>Foo</h1>
}

Foo.displayName = "Foo"
```

This way, the app remains debuggable even after mangling. This is something we did at Discord with [babel-plugin-add-react-displayname](https://www.npmjs.com/package/babel-plugin-add-react-displayname), and we were sort of sad to lose display names in prod (and especially in Sentry/error tracking).

### Babel plugin or link to the feature description

babel-plugin-add-react-displayname

### Additional context

We are considering implementing this as an SWC plugin, but it would be handy if it were built into SWC for those who need it, since there is already [swc_ecma_transforms_react::display_name](https://rustdoc.swc.rs/swc_ecma_transforms_react/fn.display_name.html).

**Comment by kwonoj** [comment]
Technically, `swc_ecma_transforms_react::display_name` is to support `@babel/plugin-transform-react-display-name`, isn't it? It's part of feature parity to `@babel/preset-react`, so for me it feels natural swc/core have those features built in.

In opposite, `babel-plugin-add-react-displayname` feels more 3rd party features would be feasible to be written in plugin instead.

**Comment by kwonoj** [comment]
BTW TIL discord uses SWC internally, cool to hear. (SWC's public community runs on discord 👍 )

**Comment by stevenpetryk** [comment]
> Technically, `swc_ecma_transforms_react::display_name` is to support `@babel/plugin-transform-react-display-name`, isn't it? It's part of feature parity to `@babel/preset-react`, so for me it feels natural swc/core have those features built in.

Totally—I just meant that there is _some_ precedent there for computing displayNames already. Definitely makes sense that you'd want to keep parity with Babel though.

> TIL discord uses SWC internally, cool to hear

We use it for the app as of today—just finished the migration from babel-loader to swc-loader :) We've been testing it in CI for a few weeks and just shipped to prod this morning. Saves us 2-3 mins.

<img width="1117" alt="CleanShot 2022-09-26 at 16 26 22@2x" src="https://user-images.githubusercontent.com/1724000/192398048-e7e854f2-b7cc-42b7-a4aa-64cb9f8abf33.png">

**Comment by kwonoj** [comment]
> We've been testing it in CI for a few weeks and just shipped to prod this morning. Saves us 2-3 mins

Lovely! 🎉 

I can't suggest to bake this feature into core as we're trying to keep core's size / api surfaces to not to grow exponentially, but happy to land things in https://github.com/swc-project/plugins probably if you're going to make a PR.

**Comment by Cr3atable** [comment]
Is it vital that mangling is enabled? Disabling it would resolve this issue quite well and I don't imagine your bundle size would be majorly impacted either given you're only using SWC's transform API.
