### ISSUE TITLE
Async function that returns an array fails when used inline

### ISSUE THREAD

**Issue by jheising** [swc-project/swc#5985]
### Describe the bug

In the following code, both `goodFunction` and `badFunction` should be functionally equivalent:

```javascript
async function getArray() {
    return ["1", "2"]
}

function findInArray(id, someArray) {
    console.log(someArray);
    return someArray.find(item => item === id);
}

async function goodFunction() {
    const theArray = await getArray();
    findInArray("2", theArray);
}

async function badFunction() {
    findInArray("2", await getArray());
}
```

Yet when compiled and run, the function `badFunction` will result in the error `TypeError: someArray.find is not a function`. 

If we look at the console, when `goodFunction` calls `findInArray` it results in an output of `[ '1', '2' ]` as expected. Yet in the case of `badFunction` calling `findInArray` results in an output of `1` — only the first array item is passed.

Upon looking at the compiled javascript for the `badFunction` function, we see the following:
```
findInArray.apply(void 0, _tmp.concat(_state.sent()));
```

This is functionally equivalent to:
```
findInArray.apply(void 0, ["2", "1", "2"]);
```
Which is why we see a value of `"1"` being passed in as the second parameter to the `findInArray` function.

### Input code

```javascript
async function getArray() {
    return ["1", "2"]
}

function findInArray(id, someArray) {
    console.log(someArray);
    return someArray.find(item => item === id);
}

async function goodFunction() {
    const theArray = await getArray();
    findInArray("2", theArray);
}

async function badFunction() {
    findInArray("2", await getArray());
}

(async () => {
    await goodFunction();
    await badFunction();
})();
```

### Config

```json
None
```

### Expected behavior

Both `goodFunction` and `badFunction` should function exactly the same.

### Version

@swc/cli: 0.1.57 @swc/core: 1.3.3

**Comment by kdy1** [comment]
It's already fixed

**Comment by jheising** [comment]
@kdy1 that was quick thanks! What version will the fix be in?

**Comment by kdy1** [comment]
The next minor release, 1.3.4
