### ISSUE TITLE
ReferenceError: undefined1 is not defined

### ISSUE THREAD

**Issue by cauthmann** [swc-project/swc#602]
With `1.1.14` no longer panicking, I ran swc over our complete codebase and ran the testsuite. >80% of our tests passed, the remaining tests failed for just two reasons:
  * `Cannot find module '@babel/runtime/regenerator'`, so maybe it should be a dependency? Manually installing it fixed the affected tests.
  * `ReferenceError: undefined1 is not defined`

Minimal testcase for the second:
```javascript
undefined;
for (let a of b) {
}
```

`npx swc --no-swcrc test.js`
```javascript
undefined1;
var _iteratorNormalCompletion = true, _didIteratorError = false, _iteratorError = undefined;
try {
    for(var _iterator = b[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true){
        var a = _step.value;
    }
} catch (err) {
    _didIteratorError = true;
    _iteratorError = err;
} finally{
    try {
        if (!_iteratorNormalCompletion && _iterator['return'] != null) {
            _iterator['return']();
        }
    } finally{
        if (_didIteratorError) {
            throw _iteratorError;
        }
    }
}
```
See the first line: `undefined` got mangled into `undefined1`. It happens with other `undefined`'s across the code, but only if one of them is used before a `for .. of` loop. It does not seem to happen with identifiers other than `undefined`.

As a quick test, I did `s/undefined/(void 0)/g` on the affected tests: 100% pass. I'll check for private codebases later, I'm sure there are more automated tests somewhere.

**Comment by Laaas** [comment]
@kdy1 I don't this is a proper fix. This will happen with all non-declared variables, no? I recently had this happen to me with `console` which was turned into `console1`. You can detect whether a variable is a global by checking whether it is declared explicitly anywhere. Maybe I should try fixing this myself.

**Comment by Laaas** [comment]
nevermind, it seems like you fixed this already
