### ISSUE TITLE
Usage of forwardRef in NestJS decorator is not captured by SWC

### ISSUE THREAD

**Issue by RobertMenke** [swc-project/swc#6024]
### Describe the bug

NestJS has a strategy for dealing with [circular dependencies](https://docs.nestjs.com/fundamentals/circular-dependency), which is the use of a function called `forwardRef`.

### Input code

```typescript
// a.ts
@Injectable()
export class A {
    constructor(
          @Inject(forwardRef(() => B))
          private readonly b: B
    ) {}
}

// b.ts
@Injectable()
export class B {
    constructor(
          private readonly a: A
    ) {}
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020",
    "keepClassNames": true,
    "baseUrl": "."
  },
  "module": {
    "type": "commonjs",
    "strictMode": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.4&code=H4sIAAAAAAAAA32OTQrCMBCF93OKWSYbuy8oaXZuvcEknYISkjIZrVJ6d6XdFETf8v3wPXfON45KIbGxwM%2BxiGJMVCt2OAN%2BFEuuKveoRcxqbHLb0gxFJpL%2BwoMxFo8n9NbuaqNcH6SMwtSXnF4YWvRrbnFeYAFoGgwHreB%2BX%2FH%2Fr3wxqMVux3gDB1vo%2BeUAAAA%3D&config=H4sIAAAAAAAAA02OMQ7CMAxF7%2BK5QlXHrrCWjQOYxFQtSR3ZrkRU9e4kggo26%2Bu%2F%2F7zBrA76DRKKktRL82L4gh4sJ1InUzJowJNjQWNR6E1W2hswwUUfLLFSgUZ0%2BXK0PqU%2FbCBDj4Y%2FGmUkKxrSru3aongSpXNA1StG0mPhjko3CaV4goJF9mugaqzvldRxjLzMWgbUZHI2sKevZX8D5J%2BHyd8AAAA%3D

### Expected behavior

I would expect that the code compiles because `tsc` does not error

### Actual behavior

ReferenceError: Cannot access 'MyClassName' before initialization

### Version

1.3.4

**Comment by kdy1** [comment]
Please search before filing an issue https://github.com/swc-project/swc/issues/5047
