### ISSUE TITLE
deep function attribute destructuring combined with spread operator is not working as expected

### ISSUE THREAD

**Issue by hombrew** [swc-project/swc#6029]
### Describe the bug

swc/ES5 transpiles into code that assings the whole array to a spread variable.

### Input code

```typescript
type ThingInput = {
    queryKey: Array<{url: string, id: string}>
}

function thing({queryKey: [{url, ...query}]}: ThingInput) {
    console.log(url);
    console.log(query);
}

thing({queryKey: [{url: 'https://www.google.com', id: '1'}]})
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": false,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.4&code=H4sIAAAAAAAAA22OPQvCMBCG9%2FyK29JCSXGNH%2BAorm7iIDWmhZqr6YUSSv6716oo6E3Hy%2FvccxQ7A4e6cXbnukCwhlEAzz0YH%2Fcmath6f46rMfhWQ0%2BemwU0l%2FeeNiIJcQ2uogYd0HQpGz%2F0cQILUErNWTol%2FaXLX7YKXY%2BtUS3ajPv58iedac5Z9t%2BhQdZEXa%2FLchgGZREtoxXe5PNduZAszx9hTP5j8AAAAA%3D%3D&config=H4sIAAAAAAAAA3VTwXLjIAz9F845tIfd6eQDeus3MMQIR10MDBJuPJn8e0XsYjvp3tDjSTzpiav6pE4dryqZTJDriabA5qKOiqcE1GVMrA6KSSDOBW5yNrkHFgbQH7nyMRKoozOe4KAGDOimWqiLQ8pAVM%2BSUQYITI1nco5fNNc8qFOMHkx4irUhjYGhh7ymdtF7kwj0aHLLqK%2BZjBTDDioMVqcc0zY9WGSMQcIGWjBWd9GujVjM0DGOsCFJHSEFEnF70MKp9H0d4Pw0jMYXw9Diy30U8mjLO0ck1q4EeoAWtXPiDM2NLix0OgOXHH44nxHDbhb%2FAESnN0TBDBv9d9yJF3um%2B4WFwYmRPDVUXF5VBeilOY3oWodVNWRGaKQMtnRQO%2BzW4gu4a4jQggbnZNwtmb6Qu%2FNGVd3G6Nq9jM241YQ51D9LtUfrHjyB7yKLt34s%2BGD4%2FIjRNJyifyoxAJ%2BjfYJlEhwfwSwrfEmPaAkWZM5gNxeFarh8tcGEvu7aVXFMHkbwe5v%2Ba%2FIvWMo4Vtf2vwHhbTXCyHLg68sC3G5VQbRlUSAO3D%2F9X3Vb%2F%2FlsB9LHwrsL%2FwaUHvMLVwQAAA%3D%3D

### Expected behavior

> https://www.google.com
> { id: '1' }

### Actual behavior

> https://www.google.com
> { '0': { url: 'https://www.google.com', id: '1' } }

### Version

1.3.4

### Additional context

destructring in two steps works as expected

```typescript
({ queryKey }: ThingInput) => {
  const [{ url, ...query }] = queryKey;
  console.log(url);
  console.log(query);
};
```

**Comment by kdy1** [comment]
I investigated this, and babel has a same problem. I used lots of time to diff the output of babel and swc :(
