### ISSUE TITLE
JSX parsing failure when mixing ts, tsx, js and jsx files

### ISSUE THREAD

**Issue by EvHaus** [swc-project/swc#6030]
My project is a bit of a mess. I have a mixture of `ts`, `tsx`, `js` and `jsx` files. I'm trying to switch from `babel-jest` to `@swc/jest` for running tests and running into issues when `swc` is processing `.jsx` files. I'm getting these types of errors:

```
      x Expression expected
         ,-[/myproject/myfile.jsx:165:5]
     165 | return <Component {...props} someProp={someValue} />;
```

and

```
x Expected a semicolon
        ,-[/myproject/myfile_test.jsx:92:11]
     92 | const component = <span className="main-body" />;
```

If I convert those files to `.tsx` then the errors go away. However, it would be a big project to convert everything to TypeScript at this stage. I'm wondering if there's some setting I can use to try to get `@swc/jest` to play nice with `.jsx` files for now.

My Jest configuration is as follows:

```js
  transform: {
    '.*\\.(ts|tsx|js|jsx|mjs)?$': [
      '@swc/jest',
      {
        jsc: {
          experimental: {
            plugins: [['jest_workaround', {}]],
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      },
    ]
  }
```

I tried a few different ways of setting `jsc.parser.jsx: true` just for `.jsx` files in the configuration, but that seems to cause all sorts of new unrelated failures. Maybe I'm doing it wrong, but I'm struggling to figure out how to do it.

Any advice on what I might be doing wrong?

**Comment by kdy1** [comment]
Please file a new issue with the input form filled

**Comment by EvHaus** [comment]
Apologies. Recreated here https://github.com/swc-project/swc/issues/6031
