### ISSUE TITLE
Allow Visitors to hold onto references from the AST

### ISSUE THREAD

**Issue by jwong101** [swc-project/swc#6032]
### Describe the feature

As it stands right now, the visitors can't store references to any part of the AST, since there's no way to constrain the references to AST nodes.
```rust
struct ExampleVisitor<'ast> {
    funcs: HashMap<Id, &'ast Function>,
}

impl<'ast> Visit for ExampleVisitor<'ast> {
    fn visit_fn_decl<'elided>(&mut self, n: &'elided FnDecl) {
        let id = n.ident.to_id();
        let fun = &*n.function;
        // doesn't compile, since we can't constrain 'elided
        self.funcs.insert(id, fun);
    }
}
```

However, if the `Visit` trait was generic over a lifetime such as:
```rust
trait Visit<'ast> {
    fn visit_fn_decl(&mut self, n: &'ast FnDecl);
    fn visit_expr(&mut self, n: &'ast Expr);
    // rest of visitor functions
    // ...
}
```
Then visitors would be able to store references to AST nodes encountered during the visit call.

Furthermore, we could change the `VisitWith` trait to:
```rust
trait VisitWith<'ast, V: ?Sized + Visit<'ast>> {
    fn visit_with(&'ast self, v: &mut V);
    fn visit_children_with(&'ast self, v: &mut V);
}
```
Which would allow `n.visit_with_children(self)` for visitors implementing the updated trait.
 
This would require a major semver bump, unless we create another Visit trait(like VisitRef or something). I'd be happy to make a PR to either create a new Visit + VisitWith trait or update the current one if this change is acceptable to y'all.

**Comment by kdy1** [comment]
There's another variant of Visitor which provides the references to all parent nodes.

https://rustdoc.swc.rs/swc_ecma_visit/trait.VisitAstPath.html

**Comment by kdy1** [comment]
And I consider this as a needlessly complicating change
