### ISSUE TITLE
Global `this` is compiled to `void 0` via CLI even when `isModule: false`

### ISSUE THREAD

**Issue by lynxtaa** [swc-project/swc#6037]
### Describe the bug

When using SWC Playground the compilation output is correct. 

But using the same config and running `npx swc 1.js` locally I'm getting `void 0` istead of `this`. Maybe related to https://github.com/swc-project/swc/issues/4935

### Input code

```typescript
// 1.js
console.log(this)
```

### Config

```json
{
	"jsc": {
		"parser": {
			"syntax": "ecmascript",
			"jsx": false
		},
		"target": "es2020",
		"loose": false,
		"minify": {
			"compress": false,
			"mangle": false
		}
	},
	"module": {
		"type": "commonjs"
	},
	"minify": false,
	"isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.4&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1yjJyCzW5AIAEo1OGBIAAAA%3D&config=H4sIAAAAAAAAA0WMSwrEIBBE79JrFyHL3CGHaJxOMPjDciAi3n2UMWTVTdWrV%2BmCpq1S5ARJ40PxmW%2FaSLRj6GRiJtWxHh1sIU1R5nRKHgjWZV16bUOATECRM94cZch0cDEJ8FbsT%2FuQrbtc%2BHxHUCmX2O%2BYuOAvUHtFc2ywT%2Fo%2F%2FwHmRZEgvgAAAA%3D%3D

### Expected behavior

I'm expecting the output to be `console.log(this)` when running `npx swc 1.js` locally. In playground the output is correct

### Actual behavior

```sh
$ npx swc 1.js
Successfully compiled 1 file with swc.
"use strict";
console.log(void 0);


//#sourceMappingURL=data:application/json;charset=utf-8;base64,IntcInZlcnNpb25cIjozLFwic291cmNlc1wiOltdLFwibmFtZXNcIjpbXSxcIm1hcHBpbmdzXCI6XCJcIixcImZpbGVcIjpcInN0ZG91dFwifSI=
```

### Version

1.3.4

**Comment by kdy1** [comment]
I can't repro from the playground. Can you check it?

**Comment by lynxtaa** [comment]
@kdy1 My issue is that in playground it produces a correct output but via @swc/cli with the same config the output is different

**Comment by kdy1** [comment]
Did you remove common js module config?

**Comment by lynxtaa** [comment]
Oh, now it works! 

I seems a bit strange that `swc` replaces top level `this` with `void 0` when using `type: 'commonjs'`. Maybe top level `this` should remain untouched since in CommonJS it equals to `module.exports`? 

I know it's a bad practice to use `this` for accessing `module.exports` but sometimes I use `swc` in legacy codebases and expect it to just work :)

**Comment by kdy1** [comment]
If you want common js behavior, you can use `module.exports` instead of ESM syntax
ESM is a standard. https://github.com/swc-project/swc/issues/5205
