### ISSUE TITLE
Faulty compression leads to arrays with holes / Removes assignments passed by value

### ISSUE THREAD

**Issue by icyJoseph** [swc-project/swc#6039]
### Describe the bug

Alright, I've got my case:

```js
function foo() {
  let walker = 0;

  let arr = [];

  function bar(defaultValue) {
    const myIndex = walker;
    walker += 1;

    console.log({ arr });

    if (arr.length < myIndex + 1) {
      arr[myIndex] = defaultValue;
    }
  }

  return bar;
}

const bar = foo();

bar(null);
bar(null);
bar(null);
bar(null);
bar(null);
```

When compiled with `swc` using this `.swcrc` file:

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es5",
    "minify": {
      "compress": true,
      "mangle": true
    }
  }
}
```

Outputs code that causes the walker to `+1` before the `if`-statement that assigns the first default value. So for the first item we are setting the index 1, which creates a whole on the array.

```js
var l = (function () {
  var l = 0,
    n = [];
  return function (u) {
    (l += 1),
      console.log({
        arr: n,
      }),
      n.length < l + 1 && (n[l] = u);
  };
})();
l(null), l(null), l(null), l(null), l(null);
```

The final log outputs: `{ arr: [ <1 empty item>, null, null, null, null ] }`, but since the very beginning there's a hole at the beginning of the array.

`package.json` used:

```json
{
  "name": "swc-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@swc/cli": "^0.1.57",
    "@swc/core": "^1.3.4"
  }
}
```

If we set ` "compress": false,` on the `.swcrc` file, then the bug goes away, aka the last log would be : `{ arr: [ null, null, null, null ] }` - no log ever shows the hole in the array.

What does this mean for Next.js? Well that perhaps a new version with a fixed version of SWC is needed to be able to use the minifier. I'll try to report the bug to SWC as best as I can so that they can fix it.

This was first observed with libraries that use this custom React hook: https://github.com/react-component/overflow/blob/master/src/hooks/useBatchFrameState.tsx - You see the core of the issue is that:

```js
    const myIndex = walkingIndex;
    walkingIndex += 1;

    // Fill value if not exist yet
    if (statesRef.current.length < myIndex + 1) {
      statesRef.current[myIndex] = defaultValue;
    }
```

The compression removes `myIndex` and replaces it with `walkingIndex`, which means that by the time the if statement runs, the indexing value is at `1`, and we set `defaultValue` as second place, leaving a whole behind in the array. Reference: https://github.com/vercel/next.js/discussions/41125

### Input code

```typescript
function foo() {
  let walker = 0;

  let arr = [];

  function bar(defaultValue) {
    const myIndex = walker;
    walker += 1;

    console.log({ arr });

    if (arr.length < myIndex + 1) {
      arr[myIndex] = defaultValue;
    }
  }

  return bar;
}

const bar = foo();

bar(null);
bar(null);
bar(null);
bar(null);
bar(null);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es5",
    "minify": {
      "compress": true,
      "mangle": true
    }
  }
}
```

### Expected behavior

Same behaviour between `jsc.minify.compress` set to `false` and set to `true`. In this case, that when the variable can be passed as value, and not reference, the compressor should not optimise away the `intermediate` holder.

```js
var a = n;
n += 1;
```

In the above, `a` ought to survive compression because it gets passed `n` by value.

### Actual behavior

The compressor incorrectly removes the variable that received it's assignment by value, as if it has been done by reference, which impacts actual runtime behaviour.

### Version

1.3.4

**Comment by icyJoseph** [comment]
A bit more info:

- Changing `bar` to an arrow function fixes the issue

```js
let arr = [];

function foo() {
  let walker = 0;
  // this works
  const bar = (defaultValue) => {
    const myIndex = walker;
    walker += 1;

    if (arr.length < myIndex + 1) {
      arr[myIndex] = defaultValue;
    }
  }

  return bar
}

const bar = foo();
bar(null);
console.log(arr); // [null]
```

- Directly returning the function also works

```js
let arr = [];

function foo() {
  let walker = 0;
  // this works
  return function bar(defaultValue) {
    const myIndex = walker;
    walker += 1;

    if (arr.length < myIndex + 1) {
      arr[myIndex] = defaultValue;
    }
  }
}

const bar = foo();
bar(null);
console.log(arr); // [null]
```

The closure seems to necessary, moving `walker` to the outer scope also works in all cases.

Last but not least a [playground link](https://play.swc.rs/?version=1.3.4&code=H4sIAAAAAAAAA01PQQ6CMBC89xVzxJAQOSMP8ANeCIcKWySubVLbqDH%2B3S1FYtI2u7Mzs1OmAO09WnR9o5SJdgizszDOFTu8FcDCeGi%2BUiLtG0HkbLyz9sVIRkcOJ82RsgYYnL0H3F5HO9JThNmhWWarW9milpUJmQ0KSVEx2SlccNiEJeqfI1LObh30Yvm%2FNht%2FVLryeArRL%2BGU9DmLNCJa%2FtWoFNtGZinT1DFV7KaUQZAvD8HjGBQBAAA%3D&config=H4sIAAAAAAAAA3VUQZLjIAz8C%2Bccdg67tTUP2Nu8gSIgHGYxciHhiSuVv69IbIiT2ZvVtERLanNRn2TV%2B0VNJhPk%2BkVLYnNW7wrsaMjmMLE6CE0gbyLB9aDY5AG4UuinnEVEgvX0oMaQgl9qJYvjlIGofktGGSExNZ7JGb8k5FwkOiJGMOkl1oZ0SAwD5J5qMUYzEejZ5JZRbzM5EKYdVBicnjJOD2hygQMmKbZhDozTFh00IGSwHGboFKkhlEQirCm5gQ6OZRjq9O5MmE0shlstON%2FGIDe2vBMGYu1Loidop%2FQO3ZtcWcHrDFxy2jifGNJuDn8BRGc0RMmM0DNvuJc97Jn%2BG1ZIXpbIS0Nlw11VgkGa0yH41mFVDZlDn1YGVyzUDm0vvoK7hig40OC9TLsl01dge%2BrFeJkAfQtlasb3HdxDvflpj1YLvIB%2FRBU%2FrmPFR8OnZ4yW8YjxpcQIfEL3AssgGJ%2FBLO49T89oSQ5kzOAeDgrVsNlUls%2BoY%2F3VtjmLISRHDxGPzb7yR44mDdWWF8U4RZgh7jf6Xz98g8klc13wasXNePC778yIj8Lbj%2B1FuFYF6MqqQLZ1ext%2BqWt%2FDrYy9LESb8r%2FAcUOSIWABAAA)

**Comment by kdy1** [comment]
Seems like this issue is partially fixed - `transform()` + `minify()` works, but `transform()` with minify option is not fixed.
So... I'm not sure how should I reproduce this

**Comment by kdy1** [comment]
Oh I think this can be an issue of `PatOrExpr` issue
