### ISSUE TITLE
Invalid handling of captured block scoped variables

### ISSUE THREAD

**Issue by cauthmann** [swc-project/swc#604]
I was hoping that my previous bug report would be my last, but I found more testcases in a hobby project. They revealed a huge bug in swc.

Block level scoped variables (those declared with `let` or `const`) have special behaviour in loops for the purpose of capturing. Each time the loop is executed, a new scope is created, so you can safely do this:
```javascript
let functions = [];
for (let i = 0; i < 10; i++) {
	functions.push(function() {
		console.log(i);
	});
}
functions[0]();
functions[7]();
```
As `i` is a new variable each time, this will output
```
0
7
```
swc `1.1.14` does not handle this correctly:
`npx swc --no-swcrc test.js`
```javascript
var functions = [];
for(var i = 0; i < 10; i++){
    functions.push(function() {
        console.log(i);
    });
}
functions[0]();
functions[7]();
```
`var i` has no special scoping rules. Its value is `10` after the end of the loop, and the transformed code will output
```
10
10
```

Babel avoids this by introducing an additional function to simulate the fresh scope:
```javascript
var functions = [];

var _loop = function _loop(i) {
  functions.push(function () {
    console.log(i);
  });
};

for (var i = 0; i < 10; i++) {
  _loop(i);
}

functions[0]();
functions[7]();
```
which will correctly output
```
0
7
```

This is a pattern I use quite frequently in react apps, to create lists of elements with event handlers. This bug would break tab bars, simulated radio buttons, accordion widgets and a lot of other things.

**Comment by cauthmann** [comment]
Somewhat related, `let` and `const` variables have a temporal dead zone, and they must not be accessed before initialization. Both of these should throw:
```javascript
console.log(i);
let i = 0;
```
```javascript
foo();
let i = 0;
function foo() {
	console.log(i);
}
```
`ReferenceError: Cannot access 'i' before initialization`

Even babel gets these two wrong. The first one should be easy enough to catch at compile time, the second would require runtime checks.

**Comment by kdy1** [comment]
I published a new version.
