### ISSUE TITLE
Dead code elimination doesn't remove unused variables

### ISSUE THREAD

**Issue by L-as** [swc-project/swc#607]
E.g. a file with just `{let a}` is kept as-is when optimization is enabled, even though it is not used anywhere. This is useful in conjunction with removing dead branches.

I took a look at the dce module, but am not sure how hard it would be to add, though it would be a nice feature in any case.

Thanks for making swc, seems like a herculean effort

**Comment by kdy1** [comment]
@Laaas It's a known issue. I've been working on it for a while, but it requires some more work and I forgot it. Thank you for reporting it.
