### ISSUE TITLE
Module not found: Error: Can't resolve '@swc/helpers/src/_create_for_of_iterator_helper_loose.mjs'

### ISSUE THREAD

**Issue by ymor** [swc-project/swc#6091]
### Describe the bug

I'm getting the following error after updating from 1.3.4 to 1.3.6
`Module not found: Error: Can't resolve '@swc/helpers/src/_create_for_of_iterator_helper_loose.mjs' `
I'm assuming a new version of @swc/helpers is required due to https://github.com/swc-project/swc/pull/6034/ 

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      },
      "useDefineForClassFields": true
    },
    "loose": true
  },
  "sourceMaps": true
}
```

### Expected behavior

Code to compile without errors

### Actual behavior

Module not found: Error: Can't resolve '@swc/helpers/src/_create_for_of_iterator_helper_loose.mjs'

### Version

1.3.6

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/commit/4f92225db78ed796fdba75328821a4914997de9e
