### ISSUE TITLE
Parsing an async generator function returns a syntax error

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#612]
**Input code**

```ts
async function* agf() {}
```

**Expected behavior**

Ability to parse this.

ECMAScript 2018 proposal: https://github.com/tc39/proposal-async-iteration#async-generator-functions

**Version**

Latest

**Additional context**

The code that causes this in swc is here: https://github.com/swc-project/swc/blob/480015d407c74f12f8454e553dd8e65e131ab0ce/ecmascript/parser/src/parser/class_and_fn.rs#L764

**Comment by dsherret** [comment]
Sorry, maybe this is not a bug, but just a feature to implement :)

Is this a lot of work to implement? Perhaps it could be parseable, but just an error during transformation? I'd like to be able to parse this at least for my use case.

Thanks!

**Comment by kdy1** [comment]
@dsherret I fixed it and published a new version of swc_ecma_parser

**Comment by dsherret** [comment]
Amazing! Thanks so much @kdy1!! 😄
