### ISSUE TITLE
swc.minify() always assumes strict mode

### ISSUE THREAD

**Issue by joebeachjoebeach** [swc-project/swc#6130]
### Describe the bug

`swc.minify()` always behaves as if the passed-in code is in strict mode, regardless of whether `JsMinifyOptions["module"]` is `true` or `false`. You can successfully configure `swc.transform()` in this way with `Options["isModule"]`, but there doesn't seem to be a way to pass this configuration directly to `minify` _or_ to have `minify` look for and use a `.swcrc` file.

### Input code

```typescript
swc.minify('const f = () => "\240";', {
    compress: {
        defaults: false,

        arguments: false,
        arrows: false,
        booleans: false,
        booleans_as_integers: false,
        collapse_vars: false,
        comparisons: false,
        computed_props: false,
        conditionals: true,
        dead_code: true,
        directives: false,
        drop_console: false,
        drop_debugger: false,
        ecma: 5,
        evaluate: false,
        expression: false,
        hoist_funs: false,
        hoist_props: false,
        hoist_vars: false,
        ie8: false,
        if_return: false,
        inline: 0,
        join_vars: false,
        keep_classnames: false,
        keep_fargs: false,
        keep_fnames: false,
        keep_infinity: false,
        loops: false,
        module: false,
        negate_iife: false,
        passes: 1,
        properties: false,
        reduce_vars: false,
        sequences: false,
        side_effects: false,
        switches: false,
        toplevel: false,
        typeofs: false,
        unused: false,
    },
    format: { comments: false, semicolons: true },
    mangle: { toplevel: false },
    module: false,
    toplevel: false,
    ecma: 5,
});
```

### Config

```json
// see object passed to `minify` above
```

### Expected behavior

Because `JsMinifyOptions["module"]` is set to `false` in the configuration object passed to `swc.minify()`, I expect the following output:
```js
const f=()=>"\xa0";
```

### Actual behavior

Instead, I receive the following error:
```
× Legacy octal escape is not permitted in strict mode

    ╭────
01 │ const f = () => "\240";
    ·                  ──
    ╰────
Caused by:
    0: failed to parse input file
    1: error was recoverable, but proceeding would result in wrong codegen
    2: Syntax Error
```

### Version

1.3.6

### Additional context

I can get this to work in the playground, but only because the playground allows a full `.swcrc` where I can set `isModule` to `true`. I'm assuming the playground uses `transform` instead of `minify`.

**Comment by andersk** [comment]
`Compiler::minify` unconditionally parses as a module here:

https://github.com/swc-project/swc/blob/e0d4220264ec3926f0a5d6b774ea782f2e511a08/crates/swc/src/lib.rs#L1045

Shouldn’t this be based on `opts.module`?

**Comment by kdy1** [comment]
Yeah, it should use `opts.module`. It's a kind of _legacy_.
