### ISSUE TITLE
Strings in jsx attribute values are incorrectly parsed as JSXExprContainer

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#615]
**Describe the bug**

In the following code...

```ts
let c = <Test attrib="5" />;
```

...no JSXExprContainer exists, yet the string is parsed as a JSXExprContainer with an empty span.

**Comment by dsherret** [comment]
Oh! This is what's causing #614! I can submit a fix.

**Comment by kdy1** [comment]
@dsherret Nice catch!

**Comment by dsherret** [comment]
@kdy1 actually, I'm not sure what the best fix for this is. Might be best for you to do it.

**Comment by kdy1** [comment]
I'll fix it soon.

**Comment by kdy1** [comment]
@dsherret Fixed and published a new verison.

**Comment by dsherret** [comment]
Amazing once again. Thanks @kdy1!
