### ISSUE TITLE
Blockers to use SWC as the build tool in vscode

### ISSUE THREAD

**Issue by ElianCordoba** [swc-project/swc#6160]
### Describe the bug

I saw [this comment](https://github.com/microsoft/vscode/pull/163660#issuecomment-1279164859) from one of the vscode devs (or manager?) mentioning a couple of points that SWC is lackying / could improve in order to consider making it the build tool for the project.

Not that you have to address them, just sharing it in case you are interested in aspects to improve the project.

### Expected behavior

.

### Version

1.3.8

**Comment by kwonoj** [comment]
There are existing tracking issues for some, and if there aren't please create specific issues for each.
