### ISSUE TITLE
Optional Chaining with Ecmascript

### ISSUE THREAD

**Issue by mmhand123** [swc-project/swc#618]
**Describe the bug**
Wasn't quite sure if this should be a bug or feature request, but it seemed like it might have been worked on in #529 so thought it might fall under bug. Trying to add the `optionalChaining` property when the parser is `ecmascript` results in a `Failed to parse config file` error.

**Input code**
Anything with optional chaining fails with the default ecmascript parser -
`someObj?.someProperty`.

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "numericSeparator": true,
      "classPrivateProperty": true,
      "classProperty": true,
      "functionBind": true,
      "nullishCoalescing": true,
      "optionalChaining": true
    }
  }
}

```

**Expected behavior**
Expected optional chaining to be configureable for `ecmascript` from #525 and #529 but again, might be wrong and it might not have been implemented, in which case this would probably be a feature request 😅 

**Version**
The version of @swc/core: 1.1.17

**Comment by kdy1** [comment]
Oh.. I forgot adding it to ecmascript config.

**Comment by mmhand123** [comment]
Awesome, thank you!
