### ISSUE TITLE
Reserve empty import statements for there could have side effects

### ISSUE THREAD

**Issue by iheyunfei** [swc-project/swc#6192]
### Describe the feature

Currently
```js
import { unused } from 'unused'
import { unused2 } from './unused'
```
will be compressed to
```js
``` 
with `unused` option.

[playground link](https://play.swc.rs/?version=1.3.9&code=H4sIAAAAAAAAA8vMLcgvKlGoVijNKy1OTVGoVUgrys9VUIdw1bkyUeWN4Ar09KFKAGLO1XNCAAAA&config=H4sIAAAAAAAAA22TQZLjIAxF7%2BJ1FlNZzKIPMLs5A0VAOHQDciGRjiuVu49I3Abbs0OPj5DE5zF8khk%2BHsOkM0GuK5oT6%2FvwMYCJmkz2Ew8nkQlyOhA8TwPrPAJXCZ1%2Fnc%2ByHRAJFsFpiD55N9dkBuOUgaiu5VCJkJhWnc4Zv1t4QQyg0xEoTconhhFy2zQYgp4I1E1vaJRWPGHassJg1ZRx6nGynj0mCVdoQVtl0LZmrM9g2N%2BgE0keESWS8rbQwqWMYx3kQuGmQ9HcZHB%2FDUSuXdEVPbFypSv5jbb1vtmmW%2B9UBi655fpEn7aaLwApNmiipCPsuJNH2aP%2FyHxy8qQ8r1Teu6sswSgtKu9d67PWDpl9lyqDLQZqo%2BYANyWTt6DAOZl7B789m2uXjucJ0LVY5qe7At6h2nlsodUSB%2FhHCuP%2BYRYeNV%2F3jOZ4wXBIEYGvaA9YhsG4h1n8fJ%2F2tCQLMmyw3UahGnIub9eKCxhVqD9wHbZYQw6pMeCl2Vm%2BatRpXE36rABtqeDxmt%2FrD%2F8enu3P%2FjiL%2Fi7Ceu3zH0Xb6%2FYoBAAA).

IMO, there should be an option called `is_imported_module_has_side_effects` enabled by default.

With `is_imported_module_has_side_effects` and `unused` enabled, 
```js
import { unused } from 'unused'
import { unused2 } from './unused'
```
will be compressed to 
```js
import 'unused'
import './unused'
``` 

--edited
Wrong playground link. Fixed now.

**Comment by kdy1** [comment]
I think it can be the default behavior even without an option. It's simply not implemented because it's not useful for next.js bundles

**Comment by kdy1** [comment]
Sorry, I misread it. I'm not sure if an export of ESM can have a side effect on access

**Comment by iheyunfei** [comment]
> Sorry, I misread it. I'm not sure if an export of ESM can have a side effect on access

I guess the key is that top-level statements of imported modules could have side effects, not the exports.

```js
// index.js
import { foo }  from './foo'

// foo.js
console.log('foo.js')
export const foo = 'foo'
```

**Comment by kdy1** [comment]
This behavior is shared among lots of tools.
If you want to preserve imports, you can use `import 'foo'`, without `{}`

**Comment by kdy1** [comment]
Well terser simply preserves it. Hmm...

**Comment by iheyunfei** [comment]
> This behavior is shared among lots of tools. If you want to preserve imports, you can use `import 'foo'`, without `{}`

The above example I gave was wrong, which cause some misunderstanding. I fixed just now.

**Comment by kdy1** [comment]
I think we should align this behavior with terser. I hope terser playground had a feature to share code :/

**Comment by Austaras** [comment]
There's already a [PR](https://github.com/terser/repl/pull/45) but seems nobody is reviewing it.

**Comment by iheyunfei** [comment]
@kdy1 I like to give a try on this. If we align this behavior with terser, I guess we just simply preserve specifiers.

**Comment by kdy1** [comment]
Yeap, and you would need to patch the DCE pass ( https://github.com/swc-project/swc/blob/e74ef8d9ed5b1a70dc57a97a7877ccbe099dd23a/crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs )

Thank you in advance!
