### ISSUE TITLE
Putting an optimizer makes swc parse react-dom.js extremely slow

### ISSUE THREAD

**Issue by hanayashiki** [swc-project/swc#6194]
### Describe the bug

SWC becomes very slow because of a subtle change in `config.jsc.transform`

### Input code

```typescript
https://gist.github.com/hanayashiki/bf760c729f8c4bb695ef6888200d332e
(too long to paste here)
```

### Config

```json
{
  "jsc": {
    "transform": {
      "optimizer": {}
    },
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  }
}
```

### Playground link

This crashes the playground...

### Expected behavior

SWC should transform the file in one second, but in fact 4s+ on my MacBook Prop 2019

### Actual behavior

SWC should transform the file in one second, but in fact 4s+ on my MacBook Prop 2019

```bash
yarn swc react-dom.js --config-file .swcrc
//... omit output
Done in 4.27s.
```

While if I remove the `optimizer` from `transform`

```json
{
  "jsc": {
    "transform": {

    },
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  }
}
```

The run finishes within one second

```
yarn swc react-dom.js --config-file .swcrc
// ...
Done in 0.67s.
```

### Version

1.3.9

### Additional context

SWC is great!

**Comment by hanayashiki** [comment]
Well, seems this config triggers optimization, and that's why it is slower

But when i run 

```bash
yarn esbuild react-dom.js --minify
// ...
Done in 0.26s.
```

Compared to 4.27s in swc. There might be a performance problem in swc's minification triggered by this `react-dom.js` file.

**Comment by kdy1** [comment]
Hmm... I can't reproduce using Rust-based benchmark system.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/29931815/196590897-80d3a43b-a227-4d98-af21-6ae03678c290.png">

What are your CPU and OS?

**Comment by kdy1** [comment]
It's intel mac, right? I'll check

**Comment by kdy1** [comment]
Can't repro even with `yarn swc`
<img width="677" alt="image" src="https://user-images.githubusercontent.com/29931815/196591506-ed00de45-6cf0-40aa-9c27-bcd2d0c0c4a0.png">

**Comment by kdy1** [comment]
Oh my bad I copied wrong config file

**Comment by hanayashiki** [comment]
> It's intel mac, right? I'll check

yeah it is

**Comment by hanayashiki** [comment]
thank you. The fix is so fast!
