### ISSUE TITLE
Stable Rust

### ISSUE THREAD

**Issue by ajacksified** [swc-project/swc#620]
swc looks awesome; in my tests, it compiles our app in about 1/4 the time! Do you plan on maintaining compilation with stable rust? There was an issue about a year ago (#117), but since then it seems to have broken again:

```
error[E0554]: \`#![feature]\` may not be used on the stable release channel 
\--> common/src/lib.rs:1:31  
1 | #![cfg_attr(feature = "fold", feature(specialization))]
  |                               ^^^^^^^^^^^^^^^^^^^^^^^`
```

I'm on rustc 1.41.0 and stay regularly up to date.

**Comment by kdy1** [comment]
> it compiles our app in about 1/4 the time!

Glad to hear that. :)

Currently swc uses specialization heavily for visitor pattern. It can be removed, but it will be really lots of work. So only parser / codegen / ast is supported on stable rust.

**Comment by ajacksified** [comment]
> Currently swc uses specialization heavily for visitor pattern. It can be removed, but it will be really lots of work. So only parser / codegen / ast is supported on stable rust.

Understandable - it'll prevent us from using swc, but I'll watch for when specialization lands in stable!

**Comment by kdy1** [comment]
@ajacksified I'm curious, are you using swc from rust?
If not, do you mean that you do not trust nightly ruatc?

**Comment by ajacksified** [comment]
> @ajacksified I'm curious, are you using swc from rust?
> If not, do you mean that you do not trust nightly ruatc?

I only have access to libc 2.12, so I can't use the precompiled swc in npm, and was hoping to use my own precompiled swc. I do not trust nightlies for production work, and even if I did, the rest of my team doesn't, which is a fair stance to take, IMO.

**Comment by kdy1** [comment]
@ajacksified I got it. It's understandable
.

**Comment by cztomsik** [comment]
@ajacksified maybe just wait for https://github.com/swc-project/swc/issues/106 that would solve it.

**Comment by dancespiele** [comment]
Is there any news about this?

**Comment by kdy1** [comment]
@dancespiele swc now provides visitors which work on stable rust.
It's mainly for rust users and swc will **not** change to it.

**Comment by dancespiele** [comment]
ok great however I don't see documentation in https://crates.io/crates/swc_ecma_visit . Where can I find it?

**Comment by kdy1** [comment]
@dancespiele You can see it at https://docs.rs/swc_ecma_visit/0.2.0/swc_ecma_visit/ .
I'll modify ci script to upload it on github.

**Comment by fahrradflucht** [comment]
@kdy1 I'm interested in your general thoughts around the use of `specialization`. Reading through https://github.com/rust-lang/rust/issues/31844 it doesn't sound like it will be stabilized in its current form and people even talk about de-implementing it, which is kind of understandable given how scary some examples in https://github.com/rust-lang/rust/issues/33017 look.

What do you think is the way forward here for swc? Do you think there is a possibility to switch to `min-specialization` (https://github.com/rust-lang/rust/pull/68970)?

**Comment by kdy1** [comment]
@fahrradflucht Hmm... I'll switch to min-specialization if min-specialization is going to be stabilized or current specialization is going to be de-implemented. However, if not, I don't want to do it at the moment because I'm too busy.


If it's really required, I can even make swc compilable with stable rustic. I don't want to do it just because It's really time-consuming and it makes organizing code much harder.

**Comment by kdy1** [comment]
Migrated to stable rustc 
:)
