### ISSUE TITLE
Ability to get if a nested namespace does not have a declare keyword

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#623]
**Describe the feature**

A TsModuleDecl has `declare: true` when within a nested namespace.

```rust
Ok(TsModuleDecl {
    span: span!(start),
    declare: self.ctx().in_declare,
    id: TsModuleName::Ident(id),
    body: Some(body),
    global: false,
})
```

So this means there's no way to tell if there's a `declare` keyword on the nested namespace.

```ts
declare module "@dsherret/package" {
    namespace packageName {
    }
}
```

Would it be possible to change the parser to only have `declare` on nodes that have a declare keyword?

**Comment by kdy1** [comment]
@dsherret As `declare` is invalid in ambient context, all children of a `declare` module should not be `declare`.


```ts
declare module "@dsherret/package" {
    declare namespace packageName {
    }
}
```

Results in error

**Comment by dsherret** [comment]
Yeah, I guess I could keep track of whether it's in a declare context or not.

**Comment by kdy1** [comment]
@dsherret I found a way to fix the issue. I'll fix it soon.

**Comment by dsherret** [comment]
Sweet. Thanks! No rush!

Yeah, it seems like babel and typescript both don't mark those nodes as "declare". TypeScript does use some flags to say the node is in an ambient context though.
