### ISSUE TITLE
I can't compile swc_plugin_runner tests

### ISSUE THREAD

**Issue by Bruce-Hopkins** [swc-project/swc#6232]
### Describe the bug

I'm attempting to contribute to the project, so I tried to run the tests first. For some reason, I get this error when I try to compile:

```bash
error[E0061]: this function takes 0 arguments but 1 argument was supplied
   --> crates/swc_plugin_runner/tests/rkyv.rs:24:5
    |
24  |     init_plugin_module_cache_once(&None);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ----- argument of type `&Option<_>` unexpected
    |
```

This causes my terminal to force exit. 

### Input code

Run the bash command:

```bash
cargo test --all --no-default-features --features swc_v1 --features memory_cache
```

### Expected behavior

The tests run smoothly

### Actual behavior

The tests fail

### Version

The main branch

### Additional context

I'm using Fedora 35.

**Comment by kdy1** [comment]
You need `__rkyv` feature

**Comment by Bruce-Hopkins** [comment]
> You need `__rkyv` feature

How do I implement this? I can't seem to run the test, or most of the cargo commands because they keep failing.

**Comment by kdy1** [comment]
`--features rkyv-impl`
