### ISSUE TITLE
Seems all satisfies expressions are parsed as "as expression"

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#6238]
### Describe the bug

It seems all satisfies expressions are parsed as `TsAsExpression`. The expected test output in the PR for it seem to indicate that as well.

Side note: can we rename `TsSatisfactionExpression` to `TsSatisfiesExpression`? TypeScript calls it `SatisfiesExpression`

### Input code

```typescript
const test = testingtesting satisfies other;
```

### Playground link

https://play.swc.rs/?version=1.3.10&code=H4sIAAAAAAAAA0vOzysuUShJBRK2YCozLx1KKRQnlmQWp2WmFivkl2SkFlkDAN47ODUsAAAA&config=H4sIAAAAAAAAAy2NsQrDMAxE%2F0VzhrZDoV5bsvUjRCIXFcc2OhsaQv69dsh2nN47bfTFRG6jzAaxnrDGwj9yVNYsmExzoYEKWlWsyt4y20dKIwS3y%2FXRr8YRPtnSByrkJV6jjMmegYFRJcw49eYvaa5BOtpfHDt36r1G9Ss5zwEykOJ9gof4B7AXfpKrAAAA

### Expected behavior

Parsed as `TsSatisfactionExpression`.

### Actual behavior

Parsed as `TsAsExpression`.

### Version

1.3.10

**Comment by nissy-dev** [comment]
Can I take this issue? Or, it is better to wait for official TS 4.9 release?

**Comment by kdy1** [comment]
It would be nice if you work on it
