### ISSUE TITLE
A way to downlevel only generators to ES5

### ISSUE THREAD

**Issue by thorn0** [swc-project/swc#6253]
### Describe the feature

There is a [JS interpreter for .NET called Jint](https://github.com/sebastienros/jint) whose [support for ES features](https://github.com/sebastienros/jint#ecmascript-2015-es6) up to ES2021 is pretty solid, however it doesn't support generators. Unfortunately, SWC isn't flexible enough for that, so we have to downlevel everything to ES5 while it'd preferable to do that only for generators.

**Comment by jridgewell** [comment]
The `preset-env` plugin should support this:

```jsonc
{
  "env": {
    "targets": "last 1 Chrome versions",
    "include": [ "transform-regenerator" ]
  }
}
```

That'll force the generator -> regenerator transform, while using the latest Chrome releases supported features for everything else.

**Comment by thorn0** [comment]
Thanks. Overlooked this.

**Comment by thorn0** [comment]
It doesn't work though. See an [isolated example](https://play.swc.rs/?version=1.3.10&code=H4sIAAAAAAAAAytLLFJIVLBVSNLQ1EgrzUsuyczP01LQyMwrKC3xLygp1lSo5lJQSM7PKy5RqAaqrAWqLUotLs0pseaq1bQGALGIj5o%2FAAAA&config=H4sIAAAAAAAAA0WOywrCQAxFf0WyrtC6EHTr2i8QF8M0rSPzIknFUubfzZRKd8nNuYcs8GYL1wWyIUaqE89RzBeugDYYtuSyQKOYRoPxjKUBMTSiVIRPbXfRs0%2BJcQMaCC66Ya4ym0ImZN5PJo7%2BTxZ1hdRPNVhA5oyr8wxld2w9x%2FcNFJp0x%2FhZO%2Bsnqofbi1LAQ9e2%2Bo6L1k%2B9wg8QMpGHROFIOGJEMpIInqX8ACN5KfX7AAAA).

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/8da12aa05fa602feb290acd6ee8b0e14409035b7/node-swc/__tests__/transform/preset-env_test.mjs#L4-L28

**Comment by thorn0** [comment]
Still doesn't work with 1.3.11 - [playground](https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA0srzUsuyczP01JI0yjUVKjmUlBIzs8rLlGoVkhUqFWwVSi05qoFANP3KF0lAAAA&config=H4sIAAAAAAAAA0WOywrCQAxFf0WyrtC6EHTr2i8QF8M0rSPzIknFUubfzZRKd8nNuYcs8GYL1wWyIUaqE89RzBeugDYYtuSyQKOYRoPxjKUBMTSiVIRPbXfRs0%2BJcQMaCC66Ya4ym0ImZN5PJo7%2BTxZ1hdRPNVhA5oyr8wxld2w9x%2FcNFJp0x%2FhZO%2Bsnqofbi1LAQ9e2%2Bo6L1k%2B9wg8QMpGHROFIOGJEMpIInqX8ACN5KfX7AAAA)

**Comment by kdy1** [comment]
Playground it unrelated and I already verified that it's working with `@swc/core`

**Comment by thorn0** [comment]
SWC 1.3.11 can't compile that code with that config:

package.json
```json
{
  "dependencies": {
    "@swc/cli": "0.1.57",
    "@swc/core": "1.3.11"
  }
}
```

.swcrc
```json
{
  "env": {
    "targets": "last 1 Chrome versions",
    "include": [ "transform-regenerator" ]
  }
}
```

input.js
```js
function* f(q) {
  const { a } = q;
}
```

Result:
```console
d:\dev\repro>npx swc input.js
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\swc_ecma_transforms_compat-0.136.21\src\es2015\generator.rs:997:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: called `Option::unwrap()` on a `None` value
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (d:\dev\repro\node_modules\@swc\cli\lib\swc\util.js:113:15)
    at files (d:\dev\repro\node_modules\@swc\cli\lib\swc\file.js:173:18)
    at async _default (d:\dev\repro\node_modules\@swc\cli\lib\swc\file.js:192:9)
```

**Comment by kdy1** [comment]
Problem is that you have ES2015 in your input
