### ISSUE TITLE
module umd not working on m1 mac

### ISSUE THREAD

**Issue by samuelgja** [swc-project/swc#6263]
### Describe the bug

Error when tried `transform` or `parse` to `module.type` => **umd** on MacBook Air (M1, 2020) mac.

### Input code

```typescript
import { parseSync, printSync, transform } from '@swc/core'
const code = `
console.log('test')
`

transform(code, {
  jsc: {
    parser: {
      syntax: 'ecmascript',
    },
    target: 'es3',
  },
  module: {
    type: 'umd',
  },
  minify: true,
  isModule: true,
}).then((d) => {
  console.log(d)
})
```

### Expected behavior

Should compile **UMD** it any supported platform

### Actual behavior

crash:

```
thread '<unnamed>' panicked at 'not implemented: determine_export_name(Anon)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_module-0.153.22/src/umd/config.rs:85:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

(node:4140) UnhandledPromiseRejectionWarning: Error: failed to handle: not implemented: determine_export_name(Anon)
```

### Version

1.3.11 - but I tried also previous version.

**Comment by YangYongAn** [comment]
I have same problem:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/4987317/202659048-048f5193-2376-45f4-8a8a-da715ed1089c.png">

**Comment by HiWayne** [comment]
MacBook Pro (Intel i5, 2020) has same problem.

**Comment by andormade** [comment]
It is platform independent, I'm also unable to generate UMD modules on amd64 linux.

**Comment by zxlisrich** [comment]
same problem on mac12

**Comment by janpoem** [comment]
can see https://github.com/swc-project/swc/blob/9daa0e2c6a6d31e8694d180408362d5f6883403e/crates/swc_ecma_transforms_module/src/umd/config.rs#L71

should specify the filename, such as :

```js
{
  filename: 'test',
  jsc: {
    parser: {
      syntax: 'typescript',
      tsx: true,
    },
    target: 'es5',
  },
  module: {
    type: 'umd',
  },
}
```
