### ISSUE TITLE
ReferenceError: Cannot access 'isServer' before initialization 

### ISSUE THREAD

**Issue by zackshen** [swc-project/swc#6269]
### Describe the bug

Hi kyd1:

`swc` is a very awesome tool. Last year I forked Next.js v11 to modify it. used swc version is `1.2.205`, I add some  custom code like below in some file

```
export const isServer = typeof window === 'undefined'
export const isClient = typeof window !== 'undefined'
```

Recently when I work in my monorepo project which include the forked next.js v11,  packages which compiled with swc
had a symlink of dependency problem, so find the CHANGELOG from swc github, upgrade swc to `1.3.11`, the symlink problem resolved. My another project use modify next.js as meta framework, the project run `next dev` works well, finally 
crash at `next build`, error looks like:

```
ReferenceError: Cannot access 'isServer' before initialization 
```

### Input code

```typescript
export const isServer = typeof window === 'undefined'
export const isClient = typeof window !== 'undefined'
```

### Config

```json
{
  "jsc": {
    "target": "es2016",
     "parser": {
       "syntax": "typescript",
       "dynamicImport": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlHILA5OLSpLLVKwVSipLEjNT1Moz8xLyS9XsLW1VVAvzUtJTcvMS01R50pF1eWck5maV4KhSxFVFwA%2FeLKTawAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F20WXeQOPYRwlODgH5ICNcZ3rw0OWUnMvHkVTrGwVsjIQjw%2BKVHxByuQDSiWXVYwHevRjl6oGVDkg3Qgsrzen177lIQmYCC46PYyZDaFzCTyVBgPf5Otu0LarhFU0JL7HZOQ4inQHtEcO%2FlOWvmi9gdzYh3WvQAAAA%3D%3D

### Expected behavior

`next build` pass sucessfully.

### Actual behavior

Run `next build` cause error:

```
ReferenceError: Cannot access 'isServer' before initialization 
```

### Version

1.3.11

**Comment by kdy1** [comment]
Your repro is wrong

<img width="641" alt="image" src="https://user-images.githubusercontent.com/29931815/198192078-8f8a4baf-99d4-405b-90ef-122321118518.png">
