### ISSUE TITLE
ReferenceError: Cannot access 'isServer' before initialization

### ISSUE THREAD

**Issue by zackshen** [swc-project/swc#6271]
### Describe the bug

Hi kyd1:

`swc` is a very awesome tool. Last year I forked Next.js v11 to modify it. used swc version is `1.2.205`, I add some  custom code like below in some file

```
export const isServer = typeof window === 'undefined'
export const isClient = typeof window !== 'undefined'
```

Recently when I work in my monorepo project which include the forked next.js v11,  packages which compiled with swc
had a symlink of dependency problem, so find the CHANGELOG from swc github, upgrade swc to `1.3.11`, the symlink problem resolved. My another project use modify next.js as meta framework, the project run `next dev` works well, finally 
crash at `next build`, error looks like:

```
ReferenceError: Cannot access 'isServer' before initialization 
```

full example code at [https://github.com/zackshen/swc-build-error-repro](https://github.com/zackshen/swc-build-error-repro)

### Input code

src/index.js

```typescript
export * from "./error";
export * from './mod_a';
export const isServer = typeof window === 'undefined'
export const isClient = typeof window !== 'undefined'
```

src/mod_a.js

```javascript
import { mod_b } from "./mod_b";

export function mod_a() {
    mod_b()
}
```

src/mod_b.js
```javascript
import { isServer } from "./index";

export function mod_b() {
    if (isServer) {
        console.log('blablabla')
    }
}

function new_instance() {
    if (isServer) {
        return { server: true }
    }
    return { server: false }
}

export const instance = new_instance()
```

src/error.js
```javascript
export const Error = () => {}
```

### Config

```json
{
  "jsc": {
    "target": "es2016",
     "parser": {
       "syntax": "typescript",
       "dynamicImport": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**final compiled file `dist/index.js`**
if `_export` statement moved to the file end , `yarn test` will pass.

```javascript

"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for (var name in all) Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}

_export(exports, {
    isServer: () => isServer,
    isClient: () => isClient
});
_exportStar(require("./error"), exports);
// ======= Error ============
// ** Call chain ---> mod_a ---> mod_b ---> index
// ======= Error ============
_exportStar(require("./mod_a"), exports);
function _exportStar(from, to) {
    Object.keys(from).forEach(function (k) {
        if (k !== "default" && !Object.prototype.hasOwnProperty.call(to, k)) Object.defineProperty(to, k, {
            enumerable: true,
            get: function () {
                return from[k];
            }
        });
    });
    return from;
}

const isServer = typeof window === 'undefined';
const isClient = typeof window !== 'undefined';

```

### Playground link

https://github.com/zackshen/swc-build-error-repro

### Expected behavior

`yarn test` pass successfully.

### Actual behavior

Run `yarn test` cause error:

```
ReferenceError: Cannot access 'isServer' before initialization 
```

### Version

1.3.11

**Comment by kdy1** [comment]
Your code is wrong
<img width="677" alt="image" src="https://user-images.githubusercontent.com/29931815/198229500-367b6ccd-61fa-4aff-8a90-1df4acd899d0.png">

I did `"type": "module"` and patched imports/exports and did `node src/index.js`

**Comment by zackshen** [comment]
@kdy1 thanks，It's wrong of my code.
