### ISSUE TITLE
IIFE causing AST to not visit it

### ISSUE THREAD

**Issue by ramon-villain** [swc-project/swc#6292]
### Describe the bug

Hey there, I'm porting a babel plugin that extracts strings from function calls (gettext/localization stuff).

With babel, this snippet would have received 3 visits (2 for `translate` and one for the IIFE) to `CallExpr`
```js
const a = translate("transform"); 
const b = (() => translate("transform"))();
```
https://astexplorer.net/#/gist/87057f51b642e6cbd25df31c5c1c3855/a5c5e4dc30c5229db8e8d627ed9639945a106781

But the same is not happening with SWC, we only get 2 visits (the inner `CallExpr` is ignored.

It seems like a bug to me, I tried to have workarounds, but it can get really ugly, I'm wondering if that's expected or not.

### Input code

```typescript
use swc_core::ecma::{
    transforms::testing::test,
    visit::{as_folder, VisitMut},
};
use swc_core::ecma::ast::CallExpr;

pub struct TransformVisitor;

impl VisitMut for TransformVisitor {
    fn visit_mut_call_expr(&mut self, n: &mut CallExpr) {
        dbg!(&n.callee);
    }
}

test!(
    Default::default(),
    |_| as_folder(TransformVisitor),
    boo,
    // Input codes
    r#"const a = translate("transform"); const b = (() => translate("transform"))();"#,
    // Output codes after transformed with plugin
    r#"const a = translate("transform"); const b = (() => translate("transform"))();"#
);
```

### Expected behavior

`CallExpr` is visited 3 times

### Version

0.40.31

**Comment by kdy1** [comment]
You should read plugin docs

**Comment by ramon-villain** [comment]
@kdy1 I couldn't find anything in the docs that helped me, I also searched for issues and discussions here on Git, are you saying that this is not a bug from your perspective?
