### ISSUE TITLE
[Bug]: Unable to use `await` as an identifier in `ExprStmt`

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6301]
### Describe the bug

SWC fails to transpile `input.js`, which uses `await` as an identifier.

### Input code

```typescript
// input.js
try { await; } catch { console.log("caught"); }
```

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA9PXV8jMKygt0csq5iopqlSoVkgsT8wssVaoVUhOLEnOAAok5%2BcV5%2Bek6uXkp2soJSeWpmeUKGkCFQAAP70bcTsAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`input.js` is a valid JavaScript program:
```console
$ d8 input.js
caught
```
so it should be transpiled by SWC.

### Actual behavior

SWC crashes when the `input.js` is given:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/68288688/199188970-db930701-c272-4ccf-9438-db07c8df5958.png">

### Version

1.3.11 (default SWC playground)

**Comment by kdy1** [comment]
I modified title as 

```js
try { const await = foo; } catch { console.log("caught"); }
```

worked

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA9PXV8jMKygt0csq5iopqlSoVkjOzysuUUgsT8wsUbBVSMvPt1aoVUhOLEnOgErm56Tq5eSnayglJ5amZ5QoaQIVAAAV6m%2FcRwAAAA%3D%3D&config=H4sIAAAAAAAAA0XMSwqAMAxF0b1k3KkT9%2BAiQo1S6Y%2B8Cop077agdBbePeShA5bmhzIrRPuFOxa%2BaCaxgWHV5UKmsTZt7CHVUGHdpXSCqTWfEuSrhoKLbrv7J5tCVgFG4rj7X9Y67NcdlrSeQ7xQZKP4ngAAAA%3D%3D
