### ISSUE TITLE
[Bug]: Re-assignment to class during static field initialization

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6307]
### Describe the bug

Mutable assignment to class name should throw `TypeError` during an initialization of static fields.
However, the transpiled code terminates without any error.

### Input code

```typescript
class x { static y = x = 0 ; }
```

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA0vOSSwuVqhQqFYoLkksyUxWqFSwBXJtFQwUrBVqFQB8P0%2FWHwAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

Mutable assignment to class name should throw `TypeError` during an initialization of static fields:
```console
$ node input.js
input.js:1
class x { static y = x = 0 ; }
                       ^

TypeError: Assignment to constant variable.
    at <static_initializer> (/Users/p51lee/dev/esmeta-plrg/input.js:1:24)
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/input.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

The output code terminates without any error.
```console
$ node output.js
// terminates without error
```

### Version

1.3.11 (default SWC playground)

**Comment by alexander-akait** [comment]
hm, babel do the same https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEAe0G9oQC5hQS2NAntAvHAdAAzQDc0AvtEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D - no errors and no extra runtime

**Comment by p51lee** [comment]
I have also submitted a bug report to babel: https://github.com/babel/babel/issues/15000

**Comment by Austaras** [comment]
I believe swc should report error in this case -- swc reject const reassignment, although it is valid JS. Or we could drop const reassignment lint, that would also make swc consistent.

**Comment by kdy1** [comment]
I think we should catch this too

**Comment by Austaras** [comment]
I'm a bit cautious about this -- const reassignment is not "hard error", it's runtime error
```js
try {
    const a = 1
    a = 2
} catch (e) {
    console.log(e)
}
```
But I don't believe anyone would rely on this.

**Comment by kdy1** [comment]
Oh, you are right... But same here. I don't expect people to rely on it
