### ISSUE TITLE
Some comments are missing in swc_ecma_parser 0.18.0

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#632]
**Describe the bug**

It was strange, but I only noticed this after clearing out my cargo.lock file, so I think this might be a problem with a downstream dependency.

**Input code**

```ts
if (true) { /* 1 */ // 2
    true;
    true;
}
```

**Expected behavior**

Both comments.

**Actual behaviour**

Only one comment:

```
Leading: {}
Trailing: {BytePos(11): [Comment { kind: Line, span: Span { lo: BytePos(20), hi: BytePos(24), ctxt: #0 }, text: " 2" }]}
```

Using this code on a `swc_common::comments::Comments`:

```rust
let (leading_comments, trailing_comments) = comments.take_all();

println!("Leading: {:?}", leading_comments);
println!("Trailing: {:?}", trailing_comments);
```

Full file is [here](https://github.com/dsherret/dprint/blob/8983ce321a24bebcae9b2fd3a0600c049644c2d2/packages/rust-dprint-plugin-typescript/src/parse_swc_ast.rs)

**Version**

0.18.0 of swc_ecma_parser
0.5.0 of swc_common
0.16.0 of swc_ecma_ast

**Comment by dsherret** [comment]
Also, dashmap did a minor bump about 3 hours ago. Perhaps it might have been because of that.

**Comment by dsherret** [comment]
@kdy1 thanks for fixing this! This is interesting though as the problem did seem to occur because of DashMap.

It makes me wonder though why swc is using a concurrent map for the comments. Is this because swc is being optimized for a single file's compilation or is this actually faster when compiling many files?

Most people will be compiling many files at the same time, so won't it be faster to instead parallelize across files at a high level rather than within one at a low level? Maybe I'm wrong, but I think that would simplify things and speed it up in many cases overall because there wouldn't be any locks or thread contention. I guess it could be slower if the last file being compiled is way bigger than the previous files since only a single thread would be working on it, but that could be mitigated by doing a quick rough sort for file size (ex. only iterate over the last X number of files and throw anything big to the start or if iterating, store a collection of small files to compile at the end in order to keep thread utilization up).

Anyway, I haven't looked at how compilation works at a high level in swc so I'm probably wrong, but it would be interesting to know what you've discovered.

**Comment by kdy1** [comment]
> thanks for fixing this! This is interesting though as the problem did seem to occur because of DashMap.

I was very confused by the result. (It works on my computer ™). 

 > It makes me wonder though why swc is using a concurrent map for the comments. Is this because swc is being optimized for a single file's compilation or is this actually faster when compiling many files?

Concurrent hashmap is for easier development and performance. If I use one hashmap per input file, I have to somehow manage the comments. I could add it to `SourceFile`, but I didn't want to create lots of `RefCell<FxHashMap<BytePos, Vec<Comment>>>`-s.

The second reason is the design of syntax_pos from rustc. If I store comments in `SourceFile`, I need to do lookup by iteration on every `BytePos` to comment conversion. This happens frequently while emitting javascript codes. Additionally, the actual bottleneck is file io I think.



> Most people will be compiling many files at the same time, so won't it be faster to instead parallelize across files at a high level rather than within one at a low level? Maybe I'm wrong, but I think that would simplify things and speed it up in many cases overall because there wouldn't be any locks or thread contention. 

swc is well-parallelized with concurrent hashmap. With 4 physical core + HT, swc outperforms babel over 68x times. But I think your suggestion can be used to improve throughput. Storing comments as local variables and appending to a global concurrent map would improve performance at a cost of using more memory.


> I guess it could be slower if the last file being compiled is way bigger than the previous files since only a single thread would be working on it, but that could be mitigated by doing a quick rough sort for file size (ex. only iterate over the last X number of files and throw anything big to the start or if iterating, store a collection of small files to compile at the end in order to keep thread utilization up).

I'm sorry, but I think I didn't understand the sentence in the parenthesis correctly.
swc works on the thread pool of the node js and there are multiple threads.
