### ISSUE TITLE
[Bug]: SWC crashes on assignment to `const`

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6326]
### Describe the bug

SWC fails to compile `input.js`, which contains assignment to `const`

### Input code

```typescript
try { const x = 0 ; x ++ ; } catch { console.log("caught") }
```

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAAyspqlSoVkjOzysuUahQsFUwULAG0traQKpWITmxJDkDKp2fk6qXk5%2BuoZScWJqeUaKkqVDLBQBaXXFTPQAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`input.js` is a valid javascript program:
```console
$ node input.js
caught
```

### Actual behavior

SWC crashes when the input.js is given:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/68288688/199428983-177c58c9-d3d1-4d4a-b9d3-02c80f27455c.png">

### Version

1.3.11 (default SWC playground)

**Comment by kdy1** [comment]
This is not a bug
