### ISSUE TITLE
Mangler inserts wrong function name on anonymous function declaration

### ISSUE THREAD

**Issue by hyp3rflow** [swc-project/swc#6344]
### Describe the bug

After the mangling, the second return value (return value of var `he`)'s logic becomes wrong.

### Input code

```typescript
function a() {}
var te = function() {
    function n(e) {}
    var t = null;
    return {
        init: function(e) {
            return t = new n(e);
        }
    }
}();
var he = function() {
    function n() {
        a();
    };
    var t = null;
    return {
        init: function(e) {
            return t
        }
    }
}();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.12&code=H4sIAAAAAAAAA62OMQ6AIAxFd07REa4g8TDElEhCakJAB8PdhYrKYOJix9ff128TTdEtBEYq2LNYTYCIMIJti4oFlLkAkESOVsjxkqbkvWYSMKZA7aaOIxeHR4eq23UHbMGN7foOnF%2ByyLLA%2Bmz%2B6tbrjWyqrP9u%2B9rwALbE1g9NAQAA&config=H4sIAAAAAAAAA22OSwrDMAxE76J1Fu2iUHKHnqEIVw5O%2FRGSExqC714b8qHQlYZ5g3grjGqgX4FRlKQlXWLGD%2FRAJqAacZyhq7NaWfRKpYOMMlBuE71V5lNS2mgHwUVnl%2FbJpMBCqifCOHhqKCf2NJM%2F0JuIn8ajasRA%2BtvbPx2LmzFTvYlP5Oh%2BZEWL4q6X3btU85Be02awcL3NMaQ4KpTTfP%2Blj22dZaLyBbcl34krAQAA

### Expected behavior

The `init` function in the `he` variable's logic should be same as before.
`return t` should reference variable inside `he`, not the function itself.

### Actual behavior

`return t` reference the function itself.

### Version

1.3.12

### Additional context

I think this result occurs in very tricky situation.
If you rename the function `init` to another or remove some lines, it works well :(

**Comment by kdy1** [comment]
Seems like this only happens if you specify `jsc.minify` on `transform()`. I couldn't reproduce this using the minifier test system, but I could with the transform testing system.

Also, `target = ES2015` works, so I guess this is an issue of handling of span hygiene in block scoping pass.
