### ISSUE TITLE
Support top level await in more than just expression statements

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#635]
**Describe the feature**

Top level await can appear in any expression. Currently this fails to parse properly:

```ts
const t = await test;
```

Parses as:

```
Node kind: VarDecl
Text: "const  t  =  await  test ;"
Node kind: VarDeclarator
Text: "t  =  await"
Node kind: Ident
Text: "t"
Node kind: Ident
Text: "await"
```

Sorry, I missed this earlier. I should have noticed that in the original PR for top level await. I think the code just needs to be changed to not have special handing for when something is top level or not? I'm not sure, but would be good to find and read the spec.

**Comment by dsherret** [comment]
Awesome. Thanks @kdy1! Any chance for a release if you have the time?

**Comment by kdy1** [comment]
@dsherret I published it.
