### ISSUE TITLE
[Bug]: `this` inside class computed function throws `TypeError`

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6356]
### Describe the bug

Hello,

`input.js` is expected to be terminated normally but the output code results in `TypeError`.

This is because `this` on the line 27 of the output code is `undefined`, since it is inside a function:
```js
// output.js
...
   20 var x = function() {
   21     "use strict";
   22     function x() {
   23         _classCallCheck(this, x);
   24     }
   25     _createClass(x, [
   26         {
   27             key: this[0],
   28             value: function value() {}
   29         }
   30     ]);
   31     return x;
   32 }();
```

### Input code

```typescript
class x { [ this [ 0 ] ] ( ) { } }
```

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA0vOSSwuVqhQqFaIVijJyCwGUgYKsUCooaAJFKwFQgC%2F%2F8VBIwAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`input.js` is expected to be terminated normally:
```console
$ node input.js # no error

```

### Actual behavior

The output code results in `TypeError`:
```console
$ node output.js
output.js:27
            key: this[0],
                     ^

TypeError: Cannot read properties of undefined (reading '0')
    at output.js:27:22
    at Object.<anonymous> (output.js:32:2)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Version

1.3.14 (default SWC playground)

**Comment by Austaras** [comment]
Oh, this is fun -- class content is always strict mode, however computed keys is not class content.
