### ISSUE TITLE
[Bug]: Non-contructable functions become constructable

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6369]
### Describe the bug

`case 1`~`case 8` in input.js throws TypeError but `output.js` is terminated without error since all four non-constructable functions became constructable:

### Input code

```typescript
/* arrow */
var f1 = () => {};
new f1();                        // case 1
class C1 extends f1 {};          // case 2

/* async function */
var f2 = async function () {};
new f2();                        // case 3
class C2 extends f2 {};          // case 4

/* genertor */
var f3 = function * () {};
new f3();                        // case 5
class C3 extends f3 {};          // case 6

/* method */
var {f4} = {f4(){}};
new f4();                        // case 7
class C4 extends f4 {};          // case 8
```

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA43O3QrCIBTA8Xuf4lxuu5GpfcBYNz2JOFdBKahrxdi7dxo4qRbMG8Ej5%2F%2BjBUjnbA8FJXfpoC2hhiyH%2BgDDWBGje3zK8gr%2BHEpBSa%2BhJOoqvYdjCfoRtGn8exWu%2BP3KCKFY9U%2BjoO2MChdr5jzD%2FNcINTOFraDwSGGJwpYpYqKctNEuWDcjOCKS7APAVwA2EcATgC8DthPgpsPZNjE%2FtGJEAF5ZPowxLFaEdzEsUlgsh%2FcvL2rCRfkBAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`case 1`~`case 8` in `input.js` throws `TypeError`:
```console
$ node input.js
input.js:3
new f1();
^

TypeError: f is not a constructor
    at Object.<anonymous> (/input.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

 `output.js` is terminated without error since all four non-constructable functions became constructable:
```console
$ node output.js # no error
```

### Version

1.3.14 (default SWC playground)

### Additional context

I'm curious whether these behaviors are intended or not.

**Comment by Austaras** [comment]
This is yet another case for babel spec mode, same as #5094 -- I don't believe there's any intention to implement it in SWC.

**Comment by kdy1** [comment]
Thanks!

**Comment by Austaras** [comment]
If it's decided not to implement spec mode, then #5094 can be closed too.
