### ISSUE TITLE
Wrong transform of template string with escaped newlines

### ISSUE THREAD

**Issue by simnalamburt** [swc-project/swc#637]
**Describe the bug**
Escaped newlines in template string literal is badly transformed.

**Input code**
```js
`\
`
```

**Config**
```json
{"env":{"targets":{"node": "13"}}}
```

**Expected behavior**
```js
`\
`;
```

**Actual behavior**
```js
`\\n`;
```

**Version**
The version of @swc/core: 1.1.19

**Additional context**
I'd like to fix it myself but I don't know where to start.

**Comment by simnalamburt** [comment]
I just manually executed swc_ecma_parser and looks like the parsing itself is OK.

```
Tokens: [
  TokenAndSpan {
    token: BackQuote,
    had_line_break: true,
    span: Span {
      lo: BytePos(0), hi: BytePos(1), ctxt: #0
    }
  },
  TokenAndSpan {
    token: Template {
      raw: Atom('\\n' type=inline),
      cooked: Atom('' type=static),
      has_escape: true
    },
    had_line_break: false,
    span: Span {
      lo: BytePos(1),
      hi: BytePos(3),
      ctxt: #0
    }
  },
  TokenAndSpan {
    token: BackQuote,
    had_line_break: false,
    span: Span {
      lo: BytePos(3),
      hi: BytePos(4),
      ctxt: #0
    }
  }
]
```

**Comment by simnalamburt** [comment]
https://github.com/swc-project/swc/blob/add63826bdc6e4417a3a0fa522806b7177edc92f/ecmascript/codegen/src/lib.rs#L343-L386

Escape codes of plane string literals (`'yo'` or `"yo"`) are partially handled by multiple `replace()` call. It partial since escaped hexadecimal values (e.g. `\x1b`) are not being handled.

But escape codes of template string literals are not handled at all as you can see below:

https://github.com/swc-project/swc/blob/add63826bdc6e4417a3a0fa522806b7177edc92f/ecmascript/codegen/src/lib.rs#L988-L991

There're two options.

1.  Let's perfectly handle and print escape codes, looking at <https://www.ecma-international.org/ecma-262/10.0/index.html#sec-literals-string-literals>. It'll be tedious for obvious reasons

2.  Let's just print the raw input as it is, without any changes. Super easy and can't be failed.

Me and @kdy1 have agreed to try the option 2.

**Comment by simnalamburt** [comment]
I took a look at [`TplElement`](https://swc-project.github.io/rustdoc/swc_ecma_ast/struct.TplElement.html) and I failed to find out how to print the raw input as-is.

**Comment by kdy1** [comment]
I noticed that `TplElement.raw` stores 

```js
`\n`
```
as
```js
"\\n"
```

And printing with `TplElement.raw` should require lots of replacing anyway.

Maybe fixing 

https://github.com/swc-project/swc/blob/4b7222cbfeec94b4826558928cb5d72edaad188e/ecmascript/parser/src/lexer/mod.rs#L57-L80

might work

**Comment by simnalamburt** [comment]
I managed to make a test cases for this issue but need more time to fix it.

https://github.com/simnalamburt/swc/commit/7e15a09e236c8da44fa3047f488051f6f6f57944
