### ISSUE TITLE
[Bug]: arguments is not being remapping in arrow functions

### ISSUE THREAD

**Issue by ClarkXia** [swc-project/swc#6371]
### Describe the bug

Using `arguments` in arrow function, it turns out to not being remapping like `this`

```js
function add(a, b) {
    const d = () => {
        return arguments.length;
    }
    return d();
}
add(1,2); // output 2
```

compiled code:

```js
function add(a, b) {
    const d = function() {
        return arguments.length;
    }
    return d();
}

add(1,2); // output 0
```

It appears to happen when i configure "env" .

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA0srzUsuyczPU0hMSdFI1FFI0lSo5lIAguT8vOIShRQFWwUNTQVbO6goCBSllpQWATUUpZfmpuaVFOvlpOall2RYgxXUciEpSdHQtOaqBQCbbnioYwAAAA%3D%3D&config=H4sIAAAAAAAAA1WOOw7CMAyGr4I8Z4CFoSMTC4eIUrcKSpzIdlGrKncnUSMqNuvz%2F9rhLQ6GHbJlQW6XbKR2hQHQRSuOfVYwVVbRZIOggWkhpz7Rw9MIg%2FKCxQCuikw2PDFkZDm4gZCS4M8ZPflpay3R0hzOh0sxM4p0UGpgTOPSFDvolrHtkTuUM6M7vby68ChE%2BjTPf69anlFrOni83K5QyhcGyx1n%2BQAAAA%3D%3D

### Expected behavior

Keywords like `arguments` and `this` should being remapping in arrow functions

### Version

1.3.14

**Comment by luhc228** [comment]
I also met the same problem.
