### ISSUE TITLE
[Bug]: (Crash) Using private static fields with `in` operator in itself

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6373]
### Describe the bug

The input program is expected to be terminated without error, but SWC fails to transpile it.

### Input code

```typescript
class x { static #y = #y in x ; }
```

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA0vOSSwuVqhQqFYoLkksyUxWUK5UsAURmXlAUWuFWgCOG5gLIQAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t%2B0id8ghhKsEF%2F%2BQFIgxvnvlkpCdZubpdfiKh6VDRRbieUnLiicsQD6heA5VwRlm1YZRaDhQ5J10IvKyLZYidK0OUshha9PkS6pMIs%2BEeY83OUyUyueYRQdtlf7CN4zHoXzYW5D14mYeP5P5%2B3m0AAAA

### Expected behavior

`input.js` is terminated normally:
```console
$ node input.js # no error
```

### Actual behavior

SWC fails to transpile `input.js`:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/68288688/200516983-eb59e784-23c0-4874-8c8d-d0973c7dd2f1.png">

### Version

1.3.14 (default SWC playground)

**Comment by alexander-akait** [comment]
For tests purposes, also failed with:
```
class a2 { static #y = y in x ; }
class a3 { static #y = ++y in x ; }
```
