### ISSUE TITLE
Add `cargo test` of subpackages to the CI

### ISSUE THREAD

**Issue by simnalamburt** [swc-project/swc#638]
Looks like `cargo test` of swc_ecma_parser, swc_ecma_transform, etc have been broken for a long time. Let's manage it with CI!

**Comment by kdy1** [comment]
It's tested with cargo test ---all

**Comment by simnalamburt** [comment]
Then you should add swc_ecma_parser, swc_ecma_transform, etc as a member of workspace member of root crate. Currently, `cargo test` of swc_ecma_parser and swc_ecma_transform do fail and they're not covered by `cargo test --all`

parser:

![image](https://user-images.githubusercontent.com/4435445/74092773-13142700-4b0c-11ea-8366-0da2707d2196.png)

transformer:

![image](https://user-images.githubusercontent.com/4435445/74092777-20311600-4b0c-11ea-8c57-e5a7f03d524e.png)

**Comment by kdy1** [comment]
You need to invoke with --all-features

**Comment by simnalamburt** [comment]
I'm afraid it still do not cover the errornous tests of swc_ecma_parser, swc_ecma_transform.

**Comment by kdy1** [comment]
I think parser test is gailing be ause of crlf. It should be lf. Also, you should initialize submodule.

swc_ecma_transforms require jest to be installed globally and you need to invoke npm i from the /ecmascript/transforms

**Comment by simnalamburt** [comment]
I just followed [CONTRIBUTING.md#getting-your-development-environment-set-up](https://github.com/swc-project/swc/blob/f8c358c/CONTRIBUTING.md#getting-your-development-environment-set-up) and confirmed that `RUST_BACKTRACE=full cargo test --color always --all --all-features` does not invoke [`ecmascript/parser/src/lexer/tests.rs`](https://github.com/swc-project/swc/blob/f8c358c9ac4d36c33a8ead390e42acbd8004e56c/ecmascript/parser/src/lexer/tests.rs). It fails at the compilation step.

I'll try to fix it, but I honestly don't know why not.

**Comment by simnalamburt** [comment]
Wow sorry it is are being invoked, it was my mistake. Sorry to bother

**Comment by kdy1** [comment]
It's ok :)
