### ISSUE TITLE
Path to swcrc & swc.js

### ISSUE THREAD

**Issue by Lawlzer** [swc-project/swc#6381]
### Describe the feature

1) The path to the swc config should be changeable via the CLI (with something similar to Babel's --config-file)

2) JS should be supported as a SWC file type (swc.js)

### Babel plugin or link to the feature description

https://babeljs.io/docs/en/config-files

### Additional context

1) This can be done in Babel via --config-file ./path-goes-here
This is provides an easy workaround for [this](https://dot-config.github.io/)
(All "root" tools I use have this in some variant, including ESLint, Prettier, Babel, Jest, Lint-staged, and TSConfig)

2) This is supported by Babel by default.
This would give us much more flexibility (enabling/disabling/adding something based on an ENV variable, or specifying file paths, or whatever we want)

**Comment by kwonoj** [comment]
1. https://swc.rs/docs/usage/cli#--config-file
2. supporting js as config is not something we are looking for at this moment. SWC core team have a goal to support config can be dynamic, but it is not strictly scoped to support js-only and evaluating possible options.
