### ISSUE TITLE
`transformSync` method configures `systemjs` type error

### ISSUE THREAD

**Issue by long-woo** [swc-project/swc#6398]
### Describe the bug

Type `systemjs` cannot be assigned to type `nodenext`.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/3394035/201111098-55ed6ae5-c662-4d69-bb69-aa97a0e23f14.png">

### Input code

```typescript
const { code } = transformSync(source, {
  jsc: {
    parser: {
      syntax: "typescript",
      tsx: true,
    },
    target: "es5",
  },
  module: {
    type: "systemjs",
  },
  isModule: true,
  sourceMaps: "inline",
});
```

### Expected behavior

typescript check passed

### Version

1.3.14

**Comment by kwonoj** [comment]
https://codesandbox.io/p/sandbox/holy-wave-pty9bo?file=%2Fnode_modules%2F%40swc%2Fcore%2Ftypes.d.ts&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A852%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A852%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clabdmgkh000al0g66fl2h2vt%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Ftsconfig.json%2522%252C%2522%252Findex.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clabdlmyx0007l0g6ffwi0jby%2522%252C%2522key%2522%253A%2522clabdlmtn005q3b6i87fdp7ct%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5000%252C%2522key%2522%253A%2522clabdlffn000m3b6i1ywhj3xx%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1210596/201172211-7eadafd2-12f9-4b43-b6b1-ed663b10c4f4.png">

Please provide reproducible code via https://codesandbox.io/. See attached codesandbox works fine.

**Comment by long-woo** [comment]
Sorry, I used '@ swc/wasm web`

**Comment by long-woo** [comment]
@kwonoj https://stackblitz.com/edit/typescript-svlvz9?file=index.ts
