### ISSUE TITLE
[Bug]: Memory leak when invoking functionality from a WASM plugin

### ISSUE THREAD

**Issue by stahlbauer** [swc-project/swc#6404]
### Describe the bug

I have written a plugin that uses the `metadata.source_map` to guide some decisions. Calling methods of this object, in particular `span_to_snippet`, leads to a memory leak.

Here is an example of a plugin that reproduces the issue:

```
#[plugin_transform]
pub fn process_transform(
    mut program: Program,
    metadata: TransformPluginProgramMetadata,
) -> Program {

    for i in 1..50000 {        
        let j: u32 = i;
        println!("i {} j {}", i, j);
        metadata.source_map.span_to_snippet(Span::new(BytePos(j), BytePos(j+10), SyntaxContext::empty()));
    }

    program
}
```
I have used this plugin in my test environment which invokes it two times. This results in the following memory graph:

![with_sourcemap_access_leak](https://user-images.githubusercontent.com/15855927/201302182-ff6826fb-cc96-407c-b2f4-5b67ecf4791d.png)

Removing the loop also eliminates the memory leak.

![without_sourcemap_access](https://user-images.githubusercontent.com/15855927/201302242-04d55ab9-f9d0-4163-83d4-a5e1eb63bab0.png)

Note that I am using a version of SWC that allows for using the full 4GB of WASM memory---see https://github.com/swc-project/swc/pull/6378 .

### Expected behavior

The memory should be freed after use.

### Version

1.3.14

**Comment by kwonoj** [comment]
I'm bit unsure if this is expected amount of pressure or if there's an actual leak. If leak is true, it'll be probably allocated buffer in the wasm memory space is not explicitly freed somewhere.

**Comment by stahlbauer** [comment]
@kwonoj Are you planing to address this proactively? Which means are currently in place to free memory allocated in context of sharing data between the native process and the WASM world?

**Comment by kwonoj** [comment]
Need confirmation on https://github.com/swc-project/swc/issues/6404#issuecomment-1312305783 .

**Comment by stahlbauer** [comment]
See, for example, https://www.oreilly.com/library/view/what-is-webassembly/9781492076902/ch04.html#:~:text=WebAssembly%20doesn't%20have%20a,for%20managing%20allocation%20of%20memory.

**Comment by kwonoj** [comment]
I meant _someone_. If I have some time I could, but I can't promise anything. 

I am aware wasm / rust both is not GC collectable. But there still can be pressure if some memories allocated in very short time frame, which is example code does exactly. The exact thing need to be confirmed is an evidence allocated memory is not dropped correctly once it is completed used and goes out of the scope from plugin transform.

**Comment by stahlbauer** [comment]
Thanks for the clarification. Just wanted to ensure that you are no waiting for exactly my confirmation (which could delay fixing this significant issue without intent).

**Comment by kdy1** [comment]
I investigated this, and seems like this happens only if the value sent from the host to the plugin is `Err`

**Comment by kdy1** [comment]
My mistake, I can't reproduce this with `--nocapture` 
Maybe a large file required?

**Comment by kdy1** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/29931815/214530284-424f9889-0b06-4ac7-9ef2-8cd65071e415.png">

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/214530339-8b2a48f8-34af-41ce-9fb6-bc5e55b055bb.png">

With a large file, I can reproduce with `Ok`, and the plugin halts after 4.21GB
