### ISSUE TITLE
SourceMap performance issue

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#6411]
### Describe the bug

Input: A large bundle generated by webpack.
minify: 2s without `sourcemap`, and 20s with `sourcemap`

When minify and transform very large file, enable source map will have huge impact on performance, very huge impact that sometimes even slower than `terser`.

[Reprod repo here](https://github.com/JSerFeng/swc_sourcemap_perf_issue/tree/main)

### Playground link

As the file is too large, I think we better download the reprod repo locally

### Expected behavior

SourceMap should be slow to generate, but shouldn't be this slow

### Actual behavior

2s without `sourcemap`
20s with `sourcemap`

### Version

1.3.14

**Comment by JSerFeng** [comment]
Additional information.
MacOs Monterey 12.1
CPU: 2.6 GHz Intel Core i7
32 GB mem

**Comment by willstott101** [comment]
I can repro this with `@swc/core` but not a locally built swc...
```
will@will-ubuntu:~/repos/others/swc_sourcemap_perf_issue$ npm run bench

> perf_issue@1.0.0 bench
> esno bench.ts

swc: 1.861s
terser: 23.946s
swc sourcemap: 24.095s
terser sourcemap: 24.888s
```
```
will@will-ubuntu:~/repos/others/swc_sourcemap_perf_issue$ npm i ../swc/swc-core-1.3.19.tgz 
...
```
```
will@will-ubuntu:~/repos/others/swc_sourcemap_perf_issue$ npm run bench

> perf_issue@1.0.0 bench
> esno bench.ts

swc: 8.311s
terser: 24.047s
swc sourcemap: 8.592s
terser sourcemap: 24.509s
```
Not sure I can dig more without some additions to CONTRIBUTING.md about building the node package. As far as I got was seeing that serializing sourcemaps isn't benched in then `minify` bench.

https://github.com/swc-project/swc/blob/48bbebf5e9cc8d3336fc48ca8b07f51486f8da04/crates/swc/benches/minify.rs#L49 should be `BoolOrDataConfig::from_bool(true)` I reckon.

Once it is... then the benchmark is massively slowed down (like, x10 slower or worse) by: https://github.com/swc-project/swc/blob/48bbebf5e9cc8d3336fc48ca8b07f51486f8da04/crates/swc_common/src/source_map.rs#L974

Commenting that out or even using `NODE_LOG=off` makes the benchmark ok again though. So unless I can repro the `@swc/core` result with a local built I think I am out of ideas.

**Comment by hardfist** [comment]
@kdy1  It seems that if the sourcefile contains lots chinese characters it will have serious performance problems, most of the time are spent on 
![PhyjKiqlnx](https://user-images.githubusercontent.com/8898718/204168794-be5a2ee5-dc3e-4995-b0fe-477f119eaf02.jpg)
compared to asci-only file 
![hpdfsolSAb](https://user-images.githubusercontent.com/8898718/204168861-4fb49a22-2a2e-49bc-beb0-82afd8ec9d8e.jpg)

when I remove all the chinese character from code, the sourcemap generation cost reduce from 37s to 1s

**Comment by kdy1** [comment]
@hardfist Can you share a test input?

**Comment by hardfist** [comment]
@kdy1 https://github.com/hardfist/swc-minify-perf/blob/main/BizCharts.js

**Comment by kdy1** [comment]
Let's see if https://github.com/swc-project/swc/pull/6523 fixes it.
Performance issue is fixed, but I'm not sure if all souremap tests will pass

**Comment by JSerFeng** [comment]
Thanks !
