### ISSUE TITLE
Eval function breaks async function (name conflict)

### ISSUE THREAD

**Issue by ambar** [swc-project/swc#6413]
### Describe the bug

There's a `eval` call after two async functions in file-type@16:

https://github.com/sindresorhus/file-type/blob/b5fe3b9596711a42c0141d97a11e4f0fa5fcc7a0/core.js#L1417-L1419

swc generates two `_fromTokenizer` functions, which are considered invalid in ESM:

```bash
Identifier '_fromTokenizer' has already been declared
```

### Input code

```typescript
async function fromTokenizer() {}
async function _fromTokenizer() {}
eval()
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczPU0grys8Nyc9OzcusSi3S0FSoruVKRFURj0VJallijoYmFwCmDQFwTAAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSw7DIAxE7%2BI123bBCbrpISzqRFT8ZDtSEOLuhYgq25k3T9PgKw5sAzqVOGF4USjEAlb5IAMFWYgnIDUpnmCBXERx7IuCGesRbRiEugFF3kknIo%2FRhZyFVmsg%2BuS3Ok0ux8IkcleY9vAn%2BxDF%2FDlm0EBroUv4hH471s7Le4HzbP8Bh3dPJ8wAAAA%3D

### Expected behavior

The transform works correctly, and the function names do not conflict.

### Actual behavior

Module parse error.

### Version

1.3.14

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/5068
