### ISSUE TITLE
[1.3.15] File extension is added as `ts` after compilation and makes error `Cannot find module`

### ISSUE THREAD

**Issue by JeffGuKang** [swc-project/swc#6414]
### Describe the bug

File extension is added as `ts` after compilation.

Expectation
```
const _app = _interopRequireDefault(require("./app"));
```

Result: swc/core@1.3.15 
```
const _app = _interopRequireDefault(require("./app.ts"));
```

`Error: Cannot find module './app.ts'`

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "dynamicImport": true,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020",
    "externalHelpers": false,
    "keepClassNames": true,
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"],
      "src/*": ["*"]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

`
const _app = _interopRequireDefault(require("./app"));
`

### Actual behavior

```
const _app = _interopRequireDefault(require("./app.ts"));
```

`Error: Cannot find module './app.ts'`

### Version

1.3.15

### Additional context

It makes huge error for our production server. 😭 
_No response_

**Comment by kdy1** [comment]
Use .js extension

**Comment by JeffGuKang** [comment]
> Use .js extension

Could you explain more about it? 
It was working well until 1.3.14 with typescript parser.

**Comment by kdy1** [comment]
It was a bug and it's fixed.
Use .js extension for import statments

**Comment by JeffGuKang** [comment]
Related to https://github.com/swc-project/swc/pull/4620

**Comment by kdy1** [comment]
I know, but problem is your code, not swc

**Comment by JeffGuKang** [comment]
> I know, but problem is your code, not swc

Thank you for reply. 

I am only using typescript files. So I cannot understand how to use js extension.
I tried to call app.ts from `@/app` from server.ts file.

server.ts
```
`import App from '@/app'` // src/app.ts
```

.swcrc
```
...
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"],
      "src/*": ["*"]
    }
...
```

What did i miss?

**Comment by coadtan** [comment]
in `.swcrc` in you set

```
    "paths": {
      "~/*": ["*"]
    }
```

I got `app.ts` **(with .ts extension)** import in my compiled .js
causing node execute failed subsequently

However, if the paths is set to 

```
    "paths": {
      "~/*": ["src/*"]
    }
```

I got `"./src/app"` **(without .ts extension)** import in my compiled .js

But I want to use `["*"]` and I don't need .ts extension in my compiled .js files.

Any advice on this, please...

**Comment by kdy1** [comment]
Use `.js` extension instead

**Comment by devcloser** [comment]
@kdy1  Could you clarify further please? What should I do to use .js extension instead?

**Comment by kdy1** [comment]
Use `.js` for import statements

**Comment by JeffGuKang** [comment]
Related to https://github.com/swc-project/swc/issues/6432
