### ISSUE TITLE
Minifier does not respect toplevel: false

### ISSUE THREAD

**Issue by levmv** [swc-project/swc#6418]
### Describe the bug

Different behaviour between online playground and real tool. Also, swc mangles top level global variable :(

### Input code

```typescript
var foo = function () { }
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.15&code=H4sIAAAAAAAAA1MqLU5VKC4pykwuUbLmKkssUkjLz1ewVUgrzUsuyczPU9DQVKhWqAUAf4u9HCcAAAA%3D&config=H4sIAAAAAAAAA22PSw7CMAxE7%2BJ1F7AAod6BMyArTKpAPlYcEFXVu5NCP0Ji5dG8sTUe6KaG2oGEsyJPSvtY%2BEUtwQRWk50UamqsWpa9YmyocO5QpogeKvMpKWbaUHDR2X66ZFKQDNUNcew8JlSSeDzhV3QH5GI8q0YO0F%2Ff%2FvEkuycX1JlkQw6nVStbzm6%2FW3qPtXlI18fcoBd8PjjSuJVezuh5Dn5X39hJ70MnAQAA

### Expected behavior

var foo=function foo(){};

### Actual behavior

`var n=function n(){};`

### Version

1.3.15

### Additional context

Online playground shows everything right. But when I copy config from playground to .swcrc file and execute cli tool  (`npx swc 'in.js' --config-file=.swcrc --out-file='out.js'`) its returns different (and wrong) code. 

We have some projects with dependencies like `https://github.com/ganlanyuan/tiny-slider/blob/master/dist/min/tiny-slider.js` and this behaviour is blocking us from upgrade from babel/terser to swc :(
Now its working correct only with fully disabled `mangle`

**Comment by kdy1** [comment]
Seems like this is an issue of `@swc/cli`

**Comment by alexander-akait** [comment]
@kdy1 @levmv I think it is fixed by https://github.com/swc-project/swc/pull/6455

**Comment by alexander-akait** [comment]
Due this line https://github.com/swc-project/swc/pull/6455/files#diff-b4393f90be8365cea45795284fd3ac8a9a83588712ee73573b39d8f39fb1bc6fR124

**Comment by levmv** [comment]
@alexander-akait 
Great job! Thanks a lot!

**Comment by levmv** [comment]
Sorry, didn't test it right away and now see that issue isn't solved by Alexander's PR :(

@kdy1, would you reopen ticket, please?

**Comment by kdy1** [comment]
No, please file a new one instead

**Comment by kdy1** [comment]
Oh nevermind
