### ISSUE TITLE
 SyntaxError: Unexpected token '-'

### ISSUE THREAD

**Issue by meabed** [swc-project/swc#6420]
### Describe the bug

When using null collapsing and dash in accessing object properties, it transform the variable in a incorrect js variable name

Codesandbox: https://codesandbox.io/s/swc-bug-1-3-15-1s90ov?file=/src/index.ts

### Input code

```typescript

Snippet: 

    // breaks swc SyntaxError: Unexpected token '-'
    // it breaks only in latest version 1.3.15
    // it works in 1.3.14
    const test = req.headers["test-dash"] ?? req.headers["test-dash-2"];

    // works
    const test2 = req.headers["test-dash"] || req.headers["test-dash-2"];

```
```


### Config

_No response_

### Playground link

https://codesandbox.io/s/swc-bug-1-3-15-1s90ov?file=/src/index.ts

### Expected behavior

It should work

### Actual behavior

```
/sandbox/src/index.ts:13
    var _req_headers_test-dash;
                         ^

SyntaxError: Unexpected token '-'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
```

### Version

1.3.15

### Additional context

_No response_

**Comment by kdy1** [comment]
I think https://github.com/swc-project/swc/commit/574502a81684e42e2ee60e362544d32d8ddf717d is the cause.
cc @Austaras
