### ISSUE TITLE
`swcrc` schema don't have `keepClassNames` options

### ISSUE THREAD

**Issue by imranbarbhuiya** [swc-project/swc#6421]
### Describe the bug

https://json.schemastore.org/swcrc don't have `jsc.keepClassNames` option

### Expected behavior

https://json.schemastore.org/swcrc to have `jsc.keepClassNames` option

### Version

^1.3.15

### Additional context

I can create a pr if someone can link me to the schema file

**Comment by kwonoj** [comment]
Same as https://github.com/swc-project/swc/issues/6427

We do not manage https://json.schemastore.org/swcrc .
