### ISSUE TITLE
Minifier doesn't respect side-effect in getter or setter

### ISSUE THREAD

**Issue by iheyunfei** [swc-project/swc#6422]
### Describe the bug

Minifier doesn't respect side-effect in getter or setter

### Input code

```typescript
let getter_effect = 'FAIL';
let setter_effect = 'FAIL';
let proto = {
	get foo() {
		getter_effect = 'PASS';
	},
	set bar(value) {
		setter_effect = 'PASS';
	}
};
let obj1 = {
	__proto__: proto
};
let obj2 = {
	__proto__: proto
};
let unused = obj1.foo;
obj2.bar = 0;

assert.strictEqual(getter_effect, 'PASS');
assert.strictEqual(setter_effect, 'PASS');
```

### Config

```json
{
  "jsc": {
    "transform": {
      "react": {
        "refresh": {}
      }
    },
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "isModule": true,
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.15&code=H4sIAAAAAAAAA32PsQrCMBCG5%2BQpsrWFUtTR4NBBQXAQ%2BgAhrVdRQqPJxUX67l6NiFLtmLvv%2Fu%2BPARRHQASnoG2hQbESyabc7hLJDe38xO7iLFqa3TmjCNFam2bDg40C92VV0RHrc84oUdTapTdtAkR%2BJHnzvI8qW5%2Fn0aTUU6vUMvo%2FiMU0Ebrg4UDMEFZQW8mHo4LK0HAmOdfeg8PCozs1uL4GbdKvr%2BSvZpn8hfo%2F6AO30%2BKDYwEAAA%3D%3D&config=H4sIAAAAAAAAA21TQbIiIQy9C2sXUy5m4QFm989AIYSWPw3pSoLfLsu7T7CVtnV25PHySF7C1XyzN4erEXKFI1JuAYHzshwiAZ%2F0eLvddmZyxEDtguci7mIOBnx27ClNYnaqpZBQBeWKowGkMXj%2Fa7%2FX2xGRwRyiGxl2JqeS4ty0POZJX%2BF21qSaoQh3niPCH15kd%2BaIOIJW%2Bh5bxzYVgQFoTfU4jm5isGdHPaO95igxlg1UBYKdCKcXtIQkCYuKPbEALliPATqQCLykM6wU1VBKYS2sV3IHAxzrMDT%2FFiac3ViddC243G3QF3veCROLjbXwG7SpdIGWJh%2BsFC2BVCpPzjemsvHhL4DWOTrm4jKsmXc86hy2zPgfVipRhyhzR3XCa1UFBm3OphR7h61qIEmrWwShemgd%2BlX8AW4a4hTAQozqdk%2FmnyT%2BtIrJPAHGHqprLq4zWEL73Kct2lbgA%2FyjVcnrOB54dnJ6x3jORxw%2FJDLICcMHrEYIvoOk23uZ3tFaAqjNEF4uKrewr6kOX9CO7bc9fdaF0Bw7jHjs66ufMrsy9LVsPzpjqA243s27%2F9bfRvHEX4%2BbRfH5W5fEf5vNM1k2BAAA

### Expected behavior

__Notice that terser also generated wrong code, the `obj1.foo` should not be removed.__

![image](https://user-images.githubusercontent.com/49502170/201511024-f6ca0be5-2577-431c-bd77-86bf2e4d4bda.png)

### Actual behavior

```js
let getter_effect = 'FAIL', setter_effect = 'FAIL';
assert.strictEqual(getter_effect, 'PASS'), assert.strictEqual(setter_effect, 'PASS');
```

### Version

1.3.15

**Comment by iheyunfei** [comment]
# Another case 

https://play.swc.rs/?version=1.3.15&code=H4sIAAAAAAAAA8tJLVEoSi0uzSlRsFVQd3P09FG35krOzysuUSjNKy1OTQEKV3Nx6unpAUnOdKDqgqL8Ag1NkCAnJ0JngGNwMFAnJ2ctFxDVWnMlFhenFpXoFZcUZSaXuBaWJuZoQFTrQBVrWgMAKX5%2BGXwAAAA%3D&config=H4sIAAAAAAAAA12PS27DMAxE78K1F4EXWfgOPYNBKCNXrfUJKRc1DN89VGIkQbQajN6Qw41%2B1NGwUWFRSFO6psr%2FNBBcZHUSSqXOMLM8z4q9o8oyoTZE%2B1Pf2%2Fecs%2BIAOoohBb%2B2YS7HIlBtOqQ5JINOHQkui8P4Z0tpqLJY5hcoo08c8WHZrqejuC5IriE2JWHiijEEjwdg1SKnacZbVeGkPktsDQTs6kN4a%2FVtcrdnqXxZWmqjuhbcDzvT%2FjrkuCvo1wHet90AmeQznj0BAAA%3D

## input
```js
let result = 'FAIL';
const unused = {
	...{
		get prop() {
			result = 'PASS';
		}
	}
};
assert.strictEqual(result, 'PASS');
```

## output
```js
assert.strictEqual('FAIL', 'PASS');

```

**Comment by Austaras** [comment]
If terser generates same code then it shouldn't be a issue?

**Comment by iheyunfei** [comment]
> If terser generates same code then it shouldn't be a issue?

I guess this means terser also has the bug. The expected output should be like 

```js
let result = 'FAIL';
({
	...{
		get prop() {
			result = 'PASS';
		}
	}
});
assert.strictEqual(result, 'PASS');

```

https://rollupjs.org/repl/?version=3.3.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJsZXQlMjByZXN1bHQlMjAlM0QlMjAnRkFJTCclM0IlNUNuY29uc3QlMjB1bnVzZWQlMjAlM0QlMjAlN0IlNUNuJTVDdC4uLiU3QiU1Q24lNUN0JTVDdGdldCUyMHByb3AoKSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3RyZXN1bHQlMjAlM0QlMjAnUEFTUyclM0IlNUNuJTVDdCU1Q3QlN0QlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuYXNzZXJ0LnN0cmljdEVxdWFsKHJlc3VsdCUyQyUyMCdQQVNTJyklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by kdy1** [comment]
Closing as this is not useful

**Comment by iheyunfei** [comment]
I'm a little confused. Is the current goal of the minifier to align everything(including the bug) with the terser?

**Comment by kdy1** [comment]
No, but we simply don't care.

**Comment by iheyunfei** [comment]
> No, but we simply don't care.

Get it. Would you accept contributions to this?

**Comment by kdy1** [comment]
Yes, I'll reopen this is you are going to implement it
