### ISSUE TITLE
jsc.react.transform.importSource not represented in https://json.schemastore.org/swcrc

### ISSUE THREAD

**Issue by kavsingh** [swc-project/swc#6427]
### Describe the bug

https://json.schemastore.org/swcrc does not include `jsc.react.transform.importSource` .  including `importSource` in config is considered invalid

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "module": { "type": "commonjs" },
  "jsc": {
    "paths": { "~/*": ["./src/*"] },
    "parser": { "syntax": "typescript", "tsx": true },
    "transform": {
      "react": { "runtime": "automatic", "importSource": "@emotion/react" }
    }
  },
  "env": {
    "targets": ["> 2%", "last 2 versions", "IOS >= 10", "Android >= 5"],
    "mode": "entry",
    "coreJs": "3"
  }
}
```

### Expected behavior

https://json.schemastore.org/swcrc includes `jsc.react.transform.importSource` , `importSource` config is considered valid

### Actual behavior

`jsc.transform.react.importSouce` is considered invalid
<img width="630" alt="image" src="https://user-images.githubusercontent.com/813450/201543833-4858cbca-c5e1-4290-9b06-7286ab248380.png">

### Version

@swc/core@1.3.16 , unsure about json schema version

**Comment by kdy1** [comment]
It's not an issue of our end
