### ISSUE TITLE
Cannot find module '@swc/helpers/src/_object_destructuring_empty.mjs'

### ISSUE THREAD

**Issue by shaonialife** [swc-project/swc#6452]
### Describe the bug

I saw that `_object_destructuring_empty.mjs` already existed in the `packages/swc-helpers/src` directory, but it wasn't published to npm

### Input code

```typescript
function foo({ ...opts }) {
  console.log(opts);
}

foo({ a: 1 })
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "legacyDecorator": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.17&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9eoVtDT08svKClWqNVUqOZSUEjOzyvOz0nVy8lP1wCJa1pz1XJxQZQmWikYAtUBAD%2FFlm1BAAAA&config=H4sIAAAAAAAAA02OOw6DQAxE7%2BKaNimoU6TJIazNgDban2wjsULcPbsEiZT2vPls9FFH40ZYDZI4PBEKRGk0WTBQYVFIB7Qm45VGslqgTnwxGsi0vSYOir0dLDOsIdBb00LOilMdKPrkp9qTXI5FoHpJnOaAvxzhpFOW2OmAmV19wGVhy%2FIbtjcq5vfSXdux6Gi9034VneFeXyd4GL%2FDO1%2Bf8QAAAA%3D%3D

### Expected behavior

```shell
$ node input.mjs
{ a: 1 }
```

### Actual behavior

```shell
$ node input.mjs
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/node_modules/@swc/helpers/src/_object_destructuring_empty.mjs' imported from /path/to/input.mjs
```

### Version

1.3.17

**Comment by alexander-akait** [comment]
@shaonialife Can you try `rm -rf node_modules/@swc/helpers && npm i` (maybe transitive deps)?

**Comment by kdy1** [comment]
@alexander-akait I didn't publish a new version of helpers yet, so it will not help
