### ISSUE TITLE
Optional chaining with type assertion is transpiled incorrectly when targetting es2020 or later

### ISSUE THREAD

**Issue by rowan-lovejoy** [swc-project/swc#6459]
### Describe the bug

Valid TypeScript expressions containing optional chaining with a type assertion inside parentheses on the left-hand side of an assignment are transpiled to invalid JavaScript when the target is set to es2020 or later.

### Input code

```typescript
(myValue.children?.children[0] as ChildType).value = 'My Value';
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "throwIfNamespace": true
      }
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.18&code=H4sIAAAAAAAAA9PIrQxLzClN1UvOyMxJKUrNs4ezog1iFRKLFZxB3JDKglRNvTKQSgVbBXXfSgWwLnVrAOCeY6RAAAAA&config=H4sIAAAAAAAAA0WMQQ7CMAwE%2F%2BJzD1WP%2FQEX%2FmBFTgmKk8h2BFXF34mBittqd3YOuGuA9YCGoiSedC%2BGT1jB9kYaJDWDCUxHZdLpNbJg0ViFHRfCYJ%2FQiyWmccRuldFS8N9N6uMSr8ikDQP9JG5B2Wg8gXSZl3mwuVYdQMSsNAGnkuLu5lC5Can%2BJyxbPkl3ney3eAMFz4431QAAAA%3D%3D

### Expected behavior

The expression is transpiled to valid JavaScript, as it is when targetting es2019 or older:

`(myValue.children?.children[0] as ChildType).value = 'My Value';`

becomes

` (_myValue_children = myValue.children) === null || _myValue_children === void 0 ? void 0 : _myValue_children.children[0].value = 'My Value';`

### Actual behavior

The type assertion and parentheses are simply stripped away, leaving an invalid statement with optional chaining on the left-hand side:

`(myValue.children?.children[0] as ChildType).value = 'My Value';`

becomes

`myValue.children?.children[0].value = 'My Value';`

### Version

1.3.18

**Comment by JSmith01** [comment]
I'd say es2019 transpilation is incorrect too. In case when type is missing and parentheses are there it will lead to "cannot set props of undefined" - so for the case of empty children you have to receive "cannot set properties of undefined" error.

In fact using optional chaining as the left-hand side of assignment is ambiguous. You might have runtime error or syntax error depending on parentheses.
