### ISSUE TITLE
Support auto-accessors

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#6477]
### Describe the feature

TypeScript 4.9 (released on Tuesday) supports auto-accessors:

```
class Person {
    accessor name: string;

    constructor(name: string) {
        this.name = name;
    }
}
```

It would be nice if swc supported this keyword.

### Babel plugin or link to the feature description

https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#auto-accessors-in-classes

https://github.com/microsoft/TypeScript/pull/49705

**Comment by dsherret** [comment]
Babel is also missing this feature. They've started working on it here: https://github.com/babel/babel/pull/15209

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/swc/issues/7193
