### ISSUE TITLE
Support `reactRemoveProperties` option

### ISSUE THREAD

**Issue by peterhirn** [swc-project/swc#6481]
### Describe the feature

This feature is available in the Next.js Compiler, documentation: https://nextjs.org/docs/advanced-features/compiler#remove-react-properties, impl: https://github.com/vercel/next.js/pull/31606.

It would be great if this feature could be ported here and exposed to `webpack` through `swc-loader`.

**Comment by kwonoj** [comment]
I believe this should be a plugin, not core.

**Comment by ruiaraujo012** [comment]
I'm looking for this feature too.

**Comment by g-plane** [comment]
I made a SWC plugin "swc-plugin-react-remove-properties": [GitHub repo](https://github.com/g-plane/swc-plugin-react-remove-properties), [npm](https://www.npmjs.com/package/swc-plugin-react-remove-properties).

**Comment by peterhirn** [comment]
Awesome, thanks!

Unfortunately SWC plugins currently [don't support Yarn PnP](https://github.com/swc-project/swc/issues/3247), `pnpm` works fine.
