### ISSUE TITLE
Support type only imports and exports (TS 3.8)

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#649]
**Describe the feature**

The TS 3.8 release will happen in a couple of weeks. It has a new type only imports and exports feature:

https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-rc/#type-only-imports-exports

Probably:

* For parsing, the only trouble might be differentiating between a type alias and a type-only export (ex. `export type `). I think it should be fairly straightforward for import declarations.
* For transforming, these should just be stripped from the output.

**Comment by kdy1** [comment]
@dsherret I've agonized it for a while. What should we do on old type-only imports?

> In conjunction with import type, we’ve also added a new compiler flag to control what happens with imports that won’t be utilized at runtime: importsNotUsedAsValues. This flag takes 3 different values:

Should we add a field to `.swcrc`?

**Comment by dsherret** [comment]
I'm not sure. Maybe that part of it could be deferred and moved into a separate issue?
