### ISSUE TITLE
Satisfies messing up Enum

### ISSUE THREAD

**Issue by brenleyTugboat** [swc-project/swc#6490]
### Describe the bug

Below is the input code for a minimal reproduction. 

This causes `IntegrationTypeEnum`  to be renamed to `_$IntegrationTypeEnum`

### Input code

```typescript
export const IntegrationTypeEnum = {
  AWS: 'aws',
} as const;

export const IntegrationServiceProductNames = {
  [IntegrationTypeEnum.AWS]: {},
} as const satisfies any;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.19&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlHwzCtJTS9KLMnMzwupLEh1zSvNVbBVqOZSUHAMD7ZSUE8sL1bX4apVSCyGaLDm4krFoT84tagsMzk1oCg%2FpTS5xC8xN7UYalQ0Flv0gObHWilU1yKbrlAMVFOclgnUmZhXaQ0ACpRI%2FaoAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

`IntegrationTypeEnum`  exported as `_$IntegrationTypeEnum` when using satisfies

### Version

1.3.19

**Comment by blixt** [comment]
It's possible this bug is related to one I posted in `@swc/jest`: https://github.com/swc-project/jest/issues/130

It's probably a general `swc` bug then.

**Comment by brenleyTugboat** [comment]
Can confirm this now works in 1.3.20. Thanks @kdy1!
