### ISSUE TITLE
Simplify expression in optional chaining.

### ISSUE THREAD

**Issue by nicksrandall** [swc-project/swc#6492]
### Describe the bug

Similar to what is supported by non-optional chaining, it would be great if the key expression could be simplified during minification. 

### Input code

```typescript
const obj = { key: 42 };
const val = obj?.[null || 'key']
console.log('val', val)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "importSource": "preact",
        "development": true
      }
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.19&code=H4sIAAAAAAAAA0vOzysuUchPylKwVahWSEvMS660UjAxUqi15koGS5Ul5gClgArs9aLzSnNyFGpqFNTB6tRjwUryc1L1cvLTNdSBKtV1QOo1AfhU17pVAAAA&config=H4sIAAAAAAAAA21TS7IbIQy8C2svUl5k8Q6QXVY5AIVBjPUyoCkk%2FDzlenePmLEZj50darob%2FbiZT%2Fbm42YmVxhKO%2FGcxV3Nh5F5AvYFJzEHI6yQlArfei4uc6SSGr2A87IcahZMoEJXhZIT9KrDNFGRP1SLb1fTSj%2BYABcYaUqQ5e7bjF0ZQGMDfPxxPCptJGLVRTcyHEzCjHFuj3lKasXcziqqzYc7z5VCX7z6HsyJaATN%2BDW2ji1mgQHKJvU0jm5isBdXuqK95goy5R1UBYKdCk1PaA4oSFnNHlgAF6ynAB3AAl7wAhtFPZSSWRPrmSxggFMdhjaYlQkXN1Yn3QuuSxv0xa47E7LYWDO%2FQLtMV2gt8s7CaAtILfnB%2BSTMuz78BdA8R8ecXYJNueBR57Bnxv%2BwMEcdoswd1QlvWWUYtDiLGHuFLWsoglu3CoTqoVXoN%2FM7uCuIMYCFGLXbXcxfKP68mbUlp9hD7ZqL2wzW0D72aY%2B2FXgDf2lW8jyOO67%2F4fyK8ZxONL5ZJJAzhTdYGyH0Chbd3uv0itYcQNsM4emicgv7murwhewIsvVZF0I1dhjp1NdXP2Vyeehr2X5polAbcFuat%2FzWn%2BZ7%2B52rH%2FLvO2%2Fx%2BQd0Pd7PaQQAAA%3D%3D

### Expected behavior

Current output: 
```
const val={key:42}?.[null||"key"];console.log("val",val);
```

I would expect the same level of optimization available for non-optional chaining to work for optional chaining.

### Actual behavior

The expression above can be safely simplified to:
```
console.log("val",42);
```

This is already supported when not using optional chaining. 

### Version

1.3.19

**Comment by iheyunfei** [comment]
Would the following output be good enough? @kdy1 
```js
console.log('val', { key: 42 }?.['key'])
```

**Comment by kdy1** [comment]
I think so
