### ISSUE TITLE
wasm-web plugin path not found on web

### ISSUE THREAD

**Issue by adminy** [swc-project/swc#6512]
### Describe the bug

The plugin is silently not loaded

### Input code

```typescript
import initSwc, { transformSync } from 'https://unpkg.com/@swc/wasm-web@1.3.19/wasm-web.js'
await initSwc()
const code = '...'
transformSync(code, {
    jsc: {
      experimental: {
        plugins: [
          [
            'https://unpkg.com/swc-plugin-another-transform-imports@0.2.1',
            { ... }
          ]
        ]
      }
    }
})
```

### Expected behavior

for the link to be resolved as a fetch or at least allow me to pass in the wasm buffer as a plugin.

### Actual behavior

plugin has to be a string path, cannot be an arraybuffer wasm, and it has no mechanism for reading in url paths.

### Version

1.3.19

### Additional context

I'm trying to do this entirely from the browser.

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/3934

**Comment by adminy** [comment]
@kwonoj I don't see the how that feature addresses the loading methods for a plugin.

**Comment by kwonoj** [comment]
#3934 is umbrella tracking for enabling plugin support. There's no plugin support in wasm host yet, regardless of how it is being configured.

**Comment by adminy** [comment]
But I'm not talking about wasm host. I was refering to wasm web

**Comment by kwonoj** [comment]
That is wasm host. Wasm host means swc runtime host is wasm, not napi bindings - wasm-node/wasm-web.

**Comment by adminy** [comment]
Thank you for the explanation
