### ISSUE TITLE
TypeScript `satisfies` operator causes SWC to not recognize objects

### ISSUE THREAD

**Issue by brandongit2** [swc-project/swc#6514]
### Describe the bug

The specific form of this bug I'm encountering is that SWC is tree-shaking an object since it doesn't appear to recognize that it's being used.

```ts
import A from "module"

const obj = {
  foo: A
} satisfies any

console.log(obj.foo) // undefined
```

Seems to be related to #6490 and https://github.com/swc-project/jest/issues/130.

My version of the bug can be worked around by adding a reference to the object like so:

```ts
import A from "module"

A // just to make reference to it

const obj = {
  foo: A
} satisfies any

console.log(obj.foo) // works
```

### Expected behavior

`A` should not be tree-shaken.

### Version

@next/swc 13.0.5

**Comment by kdy1** [comment]
Already fixed by https://github.com/swc-project/swc/commit/0cee0e1af7f8c476fe3622e687e6b953aef8cd31

**Comment by kdy1** [comment]
Thanks!
