### ISSUE TITLE
disabling `sourceMap` does not work

### ISSUE THREAD

**Issue by leander-hass** [swc-project/swc#6519]
## Description

I am not able to disable `sourceMaps`, they are always generated.

## Input

`test.ts`

```ts
class Arr {
    static create(): any[] {
        return [];
    };
}
```

Command: `.\node_modules\.bin\swc --config-file="/path/to/.swcrc" --out-file="test.js" "test.ts"`

## Config

`.swcrc`

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
            "dynamicImport": false,
            "decorators": false
        },
        "transform": null,
        "target": "es2022",
        "loose": false,
        "externalHelpers": false,
        "keepClassNames": true,
        "minify": {
            "compress": {
                "unused": false
            },
            "mangle": false
        }
    },
    "minify": true,
    "sourceMaps": false,
    "inlineSourcesContent": false
}
```

## Expected Behaviour

sourcemaps should not be generated

## Actial Behaviour

sourcemaps are generated and created as files

## Version

@swc/cli 0.1.57
@swc/core 1.3.20

_Originally posted by @mrceperka in https://github.com/swc-project/swc/discussions/4892_

**Comment by kdy1** [comment]
Please provide a repro

**Comment by leander-hass** [comment]
Added repro to issue

**Comment by leander-hass** [comment]
It seems the issue is no longer present. I do not get generated sourcemaps anymore. I'll regard this as done.
