### ISSUE TITLE
`jsc.paths` inconsistent with typescript behaviour

### ISSUE THREAD

**Issue by meskill** [swc-project/swc#6530]
### Describe the bug

The [docs](https://swc.rs/docs/configuration/compilation#jscpaths) points out to the typescript site and I expect that swc will handle this settings as it works with typescript. But it is inconsistent in many ways.

For example, I have a project with three files:
- `src/index.ts`
- `src/folder/file1.ts`
- `src/folder/file2.ts`

1 and 2 file with the content below.

In case of compiling 1 and 2 file I've got different behavior, depending on the config and file's path

## baseUrl is ignored when several possible locations are provided

Output in this case:
```ts
// index.ts
import jq from "jquery";
import file from "./folder/file2";
console.log(jq, file);

// folder/file1.ts
import jq from "jquery";
import file from "folder/file2";
console.log(jq, file);
```

After looking at [code](https://github.com/swc-project/swc/blob/20692cdff1df4491382820cb38dae6fdeda12223/crates/swc_ecma_loader/src/resolvers/tsc.rs#L169) and testing swc calls it is clear that baseUrl is not used for check for file existense. Also, it adds `./` to the import to check file existence that may resolve in some cases, but won't work in case nested directories (that might break imports for external packages).

## Single possible location doesn't check for file existence

Output in this case:
```ts
// index.ts
import jq from "./jquery";
import file from "./folder/file2";
console.log(jq, file);

// folder/file1.ts
import jq from "../jquery";
import file from "./file2";
console.log(jq, file);
```

If there is only one location for paths, it will be used without any checks for file existence - [code](https://github.com/swc-project/swc/blob/20692cdff1df4491382820cb38dae6fdeda12223/crates/swc_ecma_loader/src/resolvers/tsc.rs#L189)

## Exact pattern checks only single location

You can specify list of possible locations inside `jsc.paths`, but [according to source code](https://github.com/swc-project/swc/blob/20692cdff1df4491382820cb38dae6fdeda12223/crates/swc_ecma_loader/src/resolvers/tsc.rs#L203) and [code](https://github.com/swc-project/swc/blob/20692cdff1df4491382820cb38dae6fdeda12223/crates/swc_ecma_loader/src/resolvers/tsc.rs#L210) swc checks only first entry. Also, it adds `./` to the import in some cases that might be wrong, as it should be resolved relative to baseUrl (that might break imports for external packages)

### Input code

```typescript
import jq from 'jquery';
import file from "folder/file2";

console.log(jq, file)
```

### Config

```json
{
  "module": {
    "type": "es6"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "baseUrl": "./src",
    "paths": {
      "*": [
        "./*",
        // to check fallbacks
        // "*" 
      ]
    }
  }
}
```

### Expected behavior

The behaviour should be the same as it works with typescript

### Actual behavior

Some imports are ignore and some of them 

### Version

@swc/core@1.3.18

### Additional context

Might be related to other issues: https://github.com/swc-project/swc/issues/1324, https://github.com/swc-project/swc/issues/2725 but these issues seems like more about specific use cases

**Comment by kdy1** [comment]
Can you provide a complete repro?
I'm working on this, but I'm not sure what is the correct behavior

**Comment by meskill** [comment]
> Can you provide a complete repro? I'm working on this, but I'm not sure what is the correct behavior

Sorry, I don't have anything else. When I created the issue I tried to replace some big internal project from babel to swc and during this I faced the problems on swc side. To figure things out I've tested some simple examples that I put in the description.
After all, I ended up with webpack plugin that utilizes tsconfig settings.
