### ISSUE TITLE
Transform Error when function have types (typescript code)

### ISSUE THREAD

**Issue by aelbore** [swc-project/swc#654]
**Describe the bug**
Transform Error when function have types

![swc-error-typescript](https://user-images.githubusercontent.com/18069807/74294607-63dc8780-4d79-11ea-8402-ffee82b0bb8c.png)

**Expected behavior**
It should have no error

**Version**
The version of @swc/core: 1.1.20

**Comment by kdy1** [comment]
Can you share your swcrc file?

**Comment by kdy1** [comment]
Closing as automatic typescript detection is implemented.
