### ISSUE TITLE
Fallback bindings does not support filesystem access

### ISSUE THREAD

**Issue by Mechalicious** [swc-project/swc#6542]
### Describe the bug

npx swc .\src\main.js

operating system: windows 11
node version: 18.12.1
npx version: 9.1.2
proc:  i7-9750H

i tried with a project:

the ts contain a console.log
don't really know where the error come from
i already tried deleting and reinstalling node_modules and deleting the lock json

### Input code

```typescript
content of main.js/ts:
console.log("test");
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2020",
    "paths": {
      "@functions/*": ["./src/functions/*"]
    },
    "baseUrl": "."
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

compile

### Actual behavior

Fallback bindings does not support filesystem access.
Error: Failed to compile 1 file with swc.

### Version

 "@swc/cli": "^0.1.57",     "@swc/core": "^1.2.164",

**Comment by kwonoj** [comment]
This happens when either napi bindings are not installed, or not able to load due to some of system configuration issue.

1. Check node_modules to ensure if swc/core's native binding is installed
2. If 1 exists, try to load `*.node` file directly to check if your system can load those binary correctly.

**Comment by Mechalicious** [comment]
![Capture d’écran 2022-11-29 193525](https://user-images.githubusercontent.com/119442651/204616696-6251fa85-2456-4962-a1bb-c69939d1dd72.png)
you mean this file right ?
otherwise what do you mean by loading a .node file ?

**Comment by kwonoj** [comment]
```
let x = require(.../*.node);
console.log(x)
```

**Comment by Mechalicious** [comment]
I'm sorry but i'm unsure of the syntax or what i'm supposed to do
![requirenode](https://user-images.githubusercontent.com/119442651/204618048-ae53ed37-b2d1-4d92-b52e-03c80a701ca7.png)

**Comment by kwonoj** [comment]
That is an example, you should specify actual path to .node file you can locate.

**Comment by Mechalicious** [comment]
![file2](https://user-images.githubusercontent.com/119442651/204620069-d4169b3f-823d-4820-9d4c-506a93191eff.png)
![file1](https://user-images.githubusercontent.com/119442651/204620078-fc3075a3-3db6-4877-9eff-a3474e1c5fe8.png)
there is not apparent problem with node and require on my system ?

**Comment by kwonoj** [comment]
**actual path to .node file**, not requiring any arbitary file.

**Comment by kwonoj** [comment]
We'd like to provide help as much, but we can't instruct 1:1 on each step via comment. Please ensure you are importing **actual *.node** file and share error message, core team will try to read those error message.

**Comment by Mechalicious** [comment]
Thanks for the hint ! 
I resolved the issue by installing python and rust 
I'm closing the issue
