### ISSUE TITLE
Compilation failed after update to swc_core latest

### ISSUE THREAD

**Issue by IWANABETHATGUY** [swc-project/swc#6551]
### Describe the bug

![image](https://user-images.githubusercontent.com/17974631/204770549-414ab8c9-2879-4e50-9138-94bc07058540.png)

### Input code

```typescript
any code could reproduce this error
```

### Config

```json
You don't need
```

### Expected behavior

The Compilation should not failed

### Version

swc_core latest version

### Additional context

using None wasm target `swc_core` you could reproduce this error,

**Comment by kdy1** [comment]
This is not an issue of swc

**Comment by IWANABETHATGUY** [comment]
Not sure if it is related to https://github.com/swc-project/swc/pull/6547/files
