### ISSUE TITLE
SWC generate wrong sourcemap when have mutibyte character after 1.3.20

### ISSUE THREAD

**Issue by IWANABETHATGUY** [swc-project/swc#6552]
## Minimal reproduce repo
https://github.com/IWANABETHATGUY/swc-sourcemap-issue
## How to reproduce
1. git clone 
2. pnpm i 
3. node index
###  @swc/core 1.3.20
![image](https://user-images.githubusercontent.com/17974631/204831023-4c3af10b-75c1-42c7-8c45-4c6509bd9c17.png)
### @swc/core 1.3.21
![image](https://user-images.githubusercontent.com/17974631/204831521-5f83241e-4678-4751-8c8c-362a0743974f.png)

### Input code

```typescript
const xxx = ', something'
console.error(`❌ ${message}`);

const bbb = ''
```

### Config

```json
{
    sourceMaps: true,
    jsc: {
      parser: {
        syntax: "ecmascript",
        jsx: false,
      },
      target: "es5",
      loose: false,
      minify: {
        compress: false,
        mangle: false,
      },
    },
    module: {
      type: "commonjs",
    },
    minify: true,
    isModule: true,
}
```

### Expected behavior

Should generate right source map

### Version

@swc/core 1.3.21

**Comment by kdy1** [comment]
So should we revert https://github.com/swc-project/swc/commit/47908a49d3d773b7ffacf6ffa6e38c7e091101cb?

**Comment by kdy1** [comment]
Can you check if it's the cause?

**Comment by IWANABETHATGUY** [comment]
Yeah, I could help

**Comment by IWANABETHATGUY** [comment]
The issue is gone after I revert that pr.

**Comment by jridgewell** [comment]
This particular issue is caused by bug 2 in https://github.com/swc-project/swc/pull/6574.

**Comment by IWANABETHATGUY** [comment]
> 

Thanks
