### ISSUE TITLE
panic: not implemented: emit_ts_const_assertion

### ISSUE THREAD

**Issue by cschroeter** [swc-project/swc#656]
Source code
```ts
export const x = { text: 'hello' } as const
```

.swcrc
```json
{
  "jsc": {
    "target": "es2018",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

Panic message
```bash
$ swc --sync src/fail.ts -o fail.ts
Error: internal error in Neon module: not implemented: emit_ts_const_assertion
```

**Comment by kdy1** [comment]
Oh... I forgot stripping out const from the assertion expression. I'll fix it soon.

**Comment by cschroeter** [comment]
Thanks for the quick reply. Awesome tool by the way. We've managed to decrease build time from 56 seconds to 0.9 seconds .lmfa0

**Comment by kdy1** [comment]
@cschroeter 
> We've managed to decrease build time from 56 seconds to 0.9

Cool. Great news to me.
