### ISSUE TITLE
Generates corresponding .d.ts file

### ISSUE THREAD

**Issue by cschroeter** [swc-project/swc#657]
It would be great if we could specify (like source maps) an option to also generate declaration files.

**Comment by kdy1** [comment]
I've been agonized if it is possible without fully blown typescript parser. I thinks it's not possible yet. 


(I'm working on a fully-blown typescript compiler, but It would take some time.)

**Comment by cschroeter** [comment]
Okay, I get it. Unfortunately the advantage of swc is kind of lost when you need the declaration files, since you have to run `tsc --emitOnlyDeclaration` anyway

**Comment by kdy1** [comment]
Reopening as I checked an output from tsc and I noticed that it's possible without a full type checker.
My ts checker branch contains enough code to emit types of **correct** typescript files.

**Comment by cschroeter** [comment]
If this were to work, that would be wonderful

**Comment by zheeeng** [comment]
Any progress on it?

**Comment by kdy1** [comment]
@zheeeng I'm still working on the new typescript type checker.

**Comment by onichandame** [comment]
Where are we tracking the progress on the type emitter?

**Comment by kdy1** [comment]
@onichandame There's no one, mainly because it will not be open sourced.

**Comment by bfaulk96** [comment]
> @onichandame There's no one, mainly because it will not be open sourced.

Do you mean this feature won't be available for use in other projects? Or simply that the code itself won't be open-sourced?

**Comment by kdy1** [comment]
> Do you mean this feature won't be available for use in other projects? Or simply that the code itself won't be open-sourced?

Code will not be open sourced, and using it in/with other projects will be restricted based on the license model.

**Comment by bfaulk96** [comment]
Makes sense, that's totally fair. Nice work so far on swc!

**Comment by behnammodi** [comment]
Hi there, has any progress?

**Comment by eric-burel** [comment]
Hi, I've commented on Esbuild a similar issue, but same question for SWC: could you at least point users to a possible pattern/documentation/resource to generate the .d.ts files?

I don't think .d.ts should be regenerated all the time, it's often ok to generate them only when publishing the app for instance. So we could keep using tsc or whatever for this step. However I completely fail to find some decent documentation about how to just generate those files after the build.

**Comment by kdy1** [comment]
@behnammodi https://github.com/swc-project/swc/issues/571 is used instead of this issue, as generating `.d.ts` files requires full typescript type checker.

@eric-burel TypeSciprt is a huge beast and porting it is not easy. It's simply not support neither by esbuild nor swc at the moment.

**Comment by eric-burel** [comment]
Yeah I get that the port is hard, no problem with that, but is there a palliative that could use `swc` + any other solution that could focus on just the `.d.ts`? Without waiting for a full port?

It seems to me that if I use `swc-loader` (in replacement to `babel-loader`) coupled `ts-loader` in my webpack config, there are redundant build operations so the gain is limited.
 
For instance, I'd like `ts-loader` to just focus on creating the .d.ts, which might be faster than actually building/type checking, but I am not sure if that make sense and I haven't found any thread about that. Again maybe what I am asking doesn't make sense from a technical standpoint, I don't really know.

**Comment by kdy1** [comment]
> is there a palliative that could use swc + any other solution that could focus on just the .d.ts? While waiting for a full port?

No. It's simply impossible. You need full type system to generate `.d.ts` files.

**Comment by bfaulk96** [comment]
@kdy1 Man, I wish Microsoft would realize how valuable this is and just hire you to replace their current TS type system with the Rust-based one you're working on 😅

**Comment by MarkKahn** [comment]
> You need full type system to generate .d.ts files.

Why?  You'd of course need a full type system to validate types, but to generate the .d.ts files can't you just pass the types through from src->d.t.s without checking anything?

**Comment by kdy1** [comment]
Bexause you can't know type

**Comment by MarkKahn** [comment]
You need to be able to parse types, but you don't need to understand them (e.g. need a full type system):

    import { whatever, somethingElse } from 'file';
    export function foo(x: whatever): somethingElse {
      // implementation
    }

can be used to create a `.d.ts` of:

    import { whatever, somethingElse } from 'file';
    export declare function foo(x: whatever): somethingElse;

**Comment by kdy1** [comment]
No you can't know the type id it's not specified.

(All validations are not required for generating .d.ts, but I don't think you meant this)

**Comment by MarkKahn** [comment]
What am I missing, lol?  I don't see why you need type ids to generate a `.d.ts`.

Let's say you matched `somethingElse` in my example above.  You don't care if that's literally `somethingeElse`, `string`, or `Promise<[Array<Err | null> | null, UnpackAllOrNull<T>]>`.  If you copy it 1:1 into a `.d.ts` file, that's valid, no?

**Comment by kdy1** [comment]
No.

```ts
function foo<T>(arr: T[]) {
    for (const a of arr) {
        if (typeof a === 'string') return a
    }
} 
```

Do you think you can infer the return type without full type system?

**Comment by MarkKahn** [comment]
> Assuming all types are explicit.

😁

All of ours are anyway, because we've enabled  `typescript-eslint/explicit-module-boundary-types`.  I realize this is a pretty large limitation, but it's not necessarily a bad one.  You don't want exported types randomly changing, so explicitness is good here anyway.

**Comment by kdy1** [comment]
I don't think the user of such feature is enough to justify effort required for this.

**Comment by casamia918** [comment]
I really need this feature. My project is monorepo. So, I want to transpile shared package by using swc. 
But as the d.ts file is not generated, I should still use tsc instead.

**Comment by XiNiHa** [comment]
> I really need this feature. My project is monorepo. So, I want to transpile shared package by using swc. But as the d.ts file is not generated, I should still use tsc instead.

When referencing other packages' types that are in the same workspace, you don't have to build `.d.ts` files since they're just TypeScript source files.

**Comment by onichandame** [comment]
> > I really need this feature. My project is monorepo. So, I want to transpile shared package by using swc. But as the d.ts file is not generated, I should still use tsc instead.
> 
> When referencing other packages' types that are in the same workspace, you don't have to build `.d.ts` files since they're just TypeScript source files.

In the context of monorepo I believen packages live in different workspaces. After all yarn v2 uses the word `workspace` as a synonym to `package`.

**Comment by XiNiHa** [comment]
> In the context of monorepo I believen packages live in different workspaces. After all yarn v2 uses the word `workspace` as a synonym to `package`.

@onichandame According to [the documentation](https://yarnpkg.com/features/workspaces), a workspace itself is a package. However, it also hosts several sub-projects which are also packages. Therefore a single workspace package hosts many sub-packages, and the sub-packages can cross-reference each other.

**Comment by fguitton** [comment]
How exciting, Vercel would be supporting the effort ! https://kdy1.dev/posts/2022/1/tsc-go 🥳

**Comment by ShivamJoker** [comment]
Any updates on this? If we want to publish our packages on npm this wont be ideal solution

**Comment by eric-burel** [comment]
@ShivamJoker check the linked article https://kdy1.dev/posts/2022/1/tsc-go
At the moment you need `tsc` to generate `.d.ts` and `.d.ts.map`

**Comment by ShivamJoker** [comment]
okay so there is gonna be a new lib which will have all these features?

**Comment by kdy1** [comment]
It will be added to swc

**Comment by alexn-s** [comment]
are there any news for this feature?

**Comment by sayjeyhi** [comment]
@kdy1 any progress on this?

**Comment by kdy1** [comment]
Update: See https://github.com/dudykr/stc
