### ISSUE TITLE
Can not exclude other tsx files

### ISSUE THREAD

**Issue by cschroeter** [swc-project/swc#658]
**Describe the bug**
`swc` failes to compiles my source code with the given regex to exclude spec files. I've double checked that the regex is correct on https://rustexp.lpil.uk/

**Input code**
$ swc --sync -s true src/ -d dist/
Error: unmatched

**Config**
```json
{
  "test": ".*.tsx$",
  "exclude": ".*.spec.tsx$",
  "jsc": {
    "target": "es2018",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

**Expected behavior**
I would expect that the compile transpiles everything that is not a test file

**Version**
The version of @swc/core: 1.1.20

**Comment by kdy1** [comment]
Fixed and published new version of swc/core and swc/cli
