### ISSUE TITLE
SWC produces invalid code if types have a trailing coma

### ISSUE THREAD

**Issue by skutyepov** [swc-project/swc#6589]
### Describe the bug

If types contain a trailing coma, swc adds to the actual code, which is a syntax error. 

For reference, TSC handles it correctly. [TSC playground ref.](https://www.typescriptlang.org/play?target=7#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWNWgCgG8AoOOAQwBoy4AjG8gOhamAGcYSBfALjlLkK-TlEwoA5o3oiYYyTW4BKAWTQ52EADbAmWiBILUGcNpyU8gA)  

### Input code

```typescript
export function func({
  a,
  b,
  ...rest
}: {
  a: string,
  b: string,
}) {
 console.log(a,b, rest)
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.21&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMzwMzNKq5FBQSdYBEEojQ09MrSi0u4aq1UgBLWCkUlxRl5qWDFSA4tZog6eT8vOL8nFS9nPx0jUSdJB0FkFZNrloAL7Tel2gAAAA%3D&config=H4sIAAAAAAAAAxWKQQqAMAwE%2F7JnD5JjfxNKFEWkZHNoKfm79TYzzMTNijLR1Gn%2BE8cb2lEQoxmrXy2wIbjSoQ8tl6ifFmsxyi6CzA%2Br99KJSAAAAA%3D%3D

### Expected behavior

SWC should not add trailing coma after `...rest`

### Actual behavior

SWC adds trailing coma: `{ a, b, ...rest,}`, which isn't valid syntax

### Version

1.3.21

### Additional context

The issue goes away if trailing coma from types is removed.
```
export function func({
  a,
  b,
  ...rest
}: {
  a: string,
  b: string // (no coma here)
}) {
 console.log(a,b, rest)
}
```

**Comment by alexander-akait** [comment]
ts playground does the [same](https://www.typescriptlang.org/play?target=7#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWNWgCgG8AoOOAQwBoy4AjG8gOhamAGcYaBfALjlLkK-TlEwoA5o3oiYYyTwCUAsmhzsIAG2BNNECQWoM4bTopLcgA)

**Comment by skutyepov** [comment]
@alexander-akait in your example TSC produces the following error:
> A rest parameter or binding pattern may not have a trailing comma. 

Also, input in your example is invalid, the issue with SWC is a bit different. Given _valid_ input, SWC produces _invalid_ output.

<img width="1391" alt="swc-vs-tsc" src="https://user-images.githubusercontent.com/86685583/206292363-5b9c108d-04d6-454c-9c3f-50d950617af7.png">

**Comment by alexander-akait** [comment]
Yeah, I see, let's fix it :+1:
