### ISSUE TITLE
swc_ecma_codegen emits `/` in some mapped types

### ISSUE THREAD

**Issue by kevinbarabash** [swc-project/swc#6616]
### Describe the bug

I'm using swc_ecma_codegen directly to emit a .d.ts file.  It should look like this:
```
declare type Custom<A> = {
    -readonly [P in keyof A]+?: A[P];
}
```
but the actual output was:
```
declare type Custom<A> = {
    -readonly [P in keyof A]+/: A[P];
}
```

### Expected behavior

The following should be output 

### Version

swc_ecma_codegen = 0.127.16

### Additional context

Updating https://github.com/swc-project/swc/blob/main/crates/swc_ecma_codegen/src/typescript.rs#L508 to output a `?` instead of `/` should fix the issue.  I can work on a PR for this.

**Comment by alexander-akait** [comment]
Yeah, feel free to send a PR :+1:
