### ISSUE TITLE
minify wrongly transform inner scope variable to global scope variable

### ISSUE THREAD

**Issue by hardfist** [swc-project/swc#6628]
### Describe the bug

enable copress
![image](https://user-images.githubusercontent.com/8898718/207024454-b804cd02-b84a-4fea-8b31-27f19a240b80.png)
disable compress
![image](https://user-images.githubusercontent.com/8898718/207025493-3a0f7879-d7dc-41b7-a083-166e9003fa62.png)

### Input code

```typescript
The code is too large to paste here, I will try to make make minimal demo asap
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    },
    "externalHelpers": true,
    "transform": {
      "react": {
        "refresh": {}
      }
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": true,
  "isModule": true
}
```

### Expected behavior

should generate a var declaration instead of use global variable

### Actual behavior

generate a global variable 

### Version

1.3.22

### Additional context

when I disable compress it works correctly

**Comment by IWANABETHATGUY** [comment]
Here is a minimum demo: 
https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAA31RzU7DMAy%2B8xTmlFSqKu26iRNvwI4IRVlmWFipi%2B2OoqnvTvqzrZsmcku%2BX8f2vamCRqrAZnB8ADh4Bud%2BcFP7sHdftG1KFOfgaUAB%2FCYs4SIaCTlgWxOr5DMt43cTGZ3LJimAaQRBlGNQs5re%2BkBM9qZt26vHT3GBaB978NjlEwKwRpGU%2FYKBeJswezvC6ZyczzjeEACs7qIUPFg9U6VMZRI8LrJ8gnZexqC1etYRW80suvmFURtONbComZT0t8aijKJYIc979DW6FIEXcZfZs2%2BgSqhMUvqwV8PeZRhcLE3yOvjSZv8yJnD4yqH3nT2%2FmrRg89aXGSr9ASAWCAEgAgAA&config=H4sIAAAAAAAAA21TQZLjIAz8i8%2B57mUesLWXfQNFQDhkAbkkkYkrlb%2BPsBMcJ%2BsTNC1ZarVuw5nd8HUbJksM1E48F7HX4WsAly07ipMMB6UpFGxiuB8GsTSCNAr%2F0reEyPB4PQw5lhjmlslhngiY21kjaoYi3HmWCL%2F1KlT1dkRMYMvH3Vg2sQiMQFuow5TsxGAulnpE%2B5ulyFh2UBXwZiKcXtDio0QsmuyJebDeOPTQgUjgJF5go2gOpRTWwnolC%2BjhWMexqbcy4WJTtdJzwXWRQf%2FY404YWUyohd%2BgXaUrtDb5YMVgCKRSeXLOGMtOh38AWmeyzMVm2CIXPOgc9szwH1YsQYcoc0d1wltVBUZtzsQYeoetaiCJm1oEvjpoHbot%2BQPcNcTRg4EQVO0ezN9R3GlLJvMEGPpVVbNhm8F6NU8%2F7dFmgQ%2Fwt1Ylr%2BN44NnK6R3jOR8xfaTIICf0H7AKIfgOkrr3Or2jtXhQmcG%2FPFRu125THb6gSW3VnjqrITTGjAmP3b66kdmWsdvy3iwnQGrwP5Am2LwhpCsVkHJbSQLrZD0E9ad2frvrp8nQ15bstgiva64iZixnHu7beq8JI%2F99kJdCfgBjNo%2FwTwQAAA%3D%3D

## Before minify, exec result 
![image](https://user-images.githubusercontent.com/17974631/207309931-28d0d3ba-7dac-4f1c-9f6f-17a9a0b3f5b4.png)
## After minify, exec result
![image](https://user-images.githubusercontent.com/17974631/207309982-1df095c1-f83e-4eba-be27-0ccd669a3c34.png)

**Comment by kdy1** [comment]
I think this is fixed by https://github.com/swc-project/swc/pull/6478.
IIFEs are not invoked anymore if there's `eval`
Can you try the main branch?

**Comment by IWANABETHATGUY** [comment]
Here is another demo: 
https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAA31TTW%2FbMAy9%2B1eoxg4SahjNNVkPw87DiqHYJQgCJWVSb6pkyFK3YvV%2F36M%2FFKUpqoM%2FSL73SIqUh2j3oXFWSCX%2BFd93v2gf6gc6NJbuvGvJhxdJf1vnQ1eJcrul7pt7iIbKCuEC51mbSEsRfKSiV6siEW5HmAzaHylUQhujJszBefmsvbD6iURjB9f70jOYI2dFPmTjE3m9M5N0lTwIXzLhmiGbwcxp9cWcT6pmZIOgjgaYOXGpMh1PIXrUMkWtRr5R7aszBik7%2FzE2hX1aTPChT1x%2FconbSwoOoMwhSBJ8%2FUgykVMdO7oz8YguZhzoWIOm5dk0ByGb3JBfhAP4alGJDu%2BbSnA%2BVLcDbVcbssfwuILzs%2FB4XV%2Br1RmLE6%2BvWXwbu0d5rsOH72OJtC4cIw73eOlyLZfTLYU9c%2FVZAr0g09HH8kmheMvQVyckil5v8I9hkfMFYZB2ev%2F7%2FqWF%2BSr1l%2BZG0prqn5r7dbPBo8Q3NoOtX4yBYTFY8V0ya07HPTs33OJy1SxM7Q9s2XtzQdg4zm9IMk3QaQ7khMW67qktJ8J7PqCz9Oc0drKc5rpUVT6niEt%2FI3xeAHgGJsgrqf4DQEM32D4EAAA%3D&config=H4sIAAAAAAAAA21TQZLjIAz8i8%2B57mUesLWXfQNFQDhkAbkkkYkrlb%2BPSGwcJ%2BsTNC1ZarVuw5nd8HUbJksM1E48F7HX4WsAly07ipMMB6UpFGxiuB8GsTSCNAr%2F0reEyLC8HoYcSwxzy%2BQwTwTM7awRNUMR7jxLhN96Fap6OyImsOXjbiybWARGoC3UYUp2YjAXSz2i%2Fc1SZCw7qAp4MxFOL2jxUSIWTbZiHqw3Dj10IBI4iRfYKJpDKYW1sF7JA%2FRwrOPY1Hsy4WJTtdJzwfUhg%2F6xx50wsphQC79Bu0qf0LPJhRWDIZBKZeWcMZadDv8AtM5kmYvNsEU%2B8KBz2DPDf1ixBB2izB3VCW9VFRi1ORNj6B22qoEkbmoR%2BOqgdei25Au4a4ijBwMhqNo9mL%2BjuNOWTOYJMPSrqmbDNoPn1ax%2B2qPNAh%2Fgb61KXsex4NnK6R3jOR8xfaTIICf0H7AKIfgOkrr3Or2jtXhQmcG%2FPFRu125THb6gSW3VVp3VEBpjxoTHbl%2FdyGzL2G15b5YTIDX4H0gTbN4Q0pUKSLmtJIF18jwE9ad2frvrp8nQ15bs9hBe11xFzFjOPNy39V79yH8X9qOSH1xfKklQBAAA

![image](https://user-images.githubusercontent.com/17974631/207598892-e2d846c7-e26d-46f4-9f80-0d8630354aa1.png)

The semantic of the code after minify is not the same as before, you could see. 
`e` has been writen twice, the second time assignment cause `e.plugins` is undefined, which will lead the runtime error 
![image](https://user-images.githubusercontent.com/17974631/207599372-74a6b553-ac31-430c-808c-e850c027ff29.png)

**Comment by kdy1** [comment]
Ah. We have to go up to the scope with any variable which may interact with eval.
But I think aborting completely on `eval` is fine

**Comment by hardfist** [comment]
It did fix my project, Thanks
