### ISSUE TITLE
swc_css_parser 0.138 and higher cannot be compiled on the stable channel

### ISSUE THREAD

**Issue by nicoburns** [swc-project/swc#6630]
### Describe the bug

Trying to compile `swc_parser_css` on latest stable fails for version >= `0.138.0`:

```
   Compiling swc_css_parser v0.138.7
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/name/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_css_parser-0.138.7/src/lib.rs:1:1
  |
1 | #![feature(box_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `swc_css_parser` due to previous error
```

### Expected behavior

Code compiles on stable Rust.

### Actual behavior

Code does not compile

### Version

0.138, 0.139, 0.140

### Additional context

Previous Github issues lead me to believe you are targeting the the stable compiler (if you're not then you can ignore this). I believe this issue was introduced by this PR https://github.com/swc-project/swc/pull/6593

**Comment by alexander-akait** [comment]
Because `swc_css` and `swc_html` are still experimental we decided to use new feature to reduce code and simplify logic, `swc_ecma` is only `stable`

**Comment by kdy1** [comment]
MSRV is nightly
