### ISSUE TITLE
Cannot determine type-graphql type implicitly

### ISSUE THREAD

**Issue by PhakornKiong** [swc-project/swc#6642]
### Describe the bug

I'm exploring the move from `ts-jest` to `swc/jest` for a project.

Compilation step is all good.

But when i start to run the test, i get multiple occurence of the following error (does'nt happen when using `ts-jest`)

`Cannot determine GraphQL input type for 'destinationCurrency' of 'ConvertFxArgs' class. Is the value, that is used as its TS type or explicit type, decorated with a proper decorator or is it a proper input value?`

I'm aware that it can be solved by explicitly passing the `types` to `type-graphql` like how i did it for `sourceCurrency`

However this is quite a major roadblock to doing this for the entire project.

Not sure if this is a bug

### Input code

```typescript
import { ArgsType, Field } from 'type-graphql';
import { Currency } from '@xp-universal-sdk/core-commons';

enum Currency {
  USD = 'USD',
}

@ArgsType()
export class ConvertFxArgs {
  @Field(() => String)
  sourceCurrency: Currency;
  
  // This is causing error
  @Field()
  destinationCurrency: Currency;

  @Field()
  amount: number;
}
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2018",
    "loose": false,
    "externalHelpers": false,
    // Requires v1.2.50 or upper and requires target to be es2016 or upper.
    "keepClassNames": false
  },
  "minify": false
}
```

### Expected behavior

Expect `swc/jest` to be a drop in replacement and work nicely with `type-graphql`

### Actual behavior

Require explicit types to be passed to `type-graphql` decorator. Only happens with `swc/jest` and not `ts-jest`

### Version

1.3.22

### Additional context

Compiled output from `swc`
```javascript
export let ConvertFxArgs = class ConvertFxArgs {};
__decorate(
  [Field(() => String), __metadata('design:type', typeof Currency === 'undefined' ? Object : Currency)],
  ConvertFxArgs.prototype,
  'sourceCurrency',
  void 0
);
__decorate(
  [Field(), __metadata('design:type', typeof Currency === 'undefined' ? Object : Currency)],
  ConvertFxArgs.prototype,
  'destinationCurrency',
  void 0
);
```

Compiled output from `tsc`
```javascript
let ConvertFxArgs = class ConvertFxArgs {};
__decorate(
  [type_graphql_1.Field(() => String), __metadata('design:type', String)],
  ConvertFxArgs.prototype,
  'sourceCurrency',
  void 0
);
__decorate(
  [type_graphql_1.Field(), __metadata('design:type', String)],
  ConvertFxArgs.prototype,
  'destinationCurrency',
  void 0
);
```

Looks like the 2nd argument passed to `__metadata` caused this error

**Comment by kdy1** [comment]
This requires type checker so this is a duplicate
