### ISSUE TITLE
Incorrectly parsing @types/ import

### ISSUE THREAD

**Issue by pierre-aurele-martin** [swc-project/swc#6671]
### Describe the bug

Hello :) 

I've got two issues with how swc transpile typescript code :) Took me a while to figure out what's wrong and I'm not sure how I can reach a solution I could actually deploy.

I guess it's related to swc not type checking and therefore that we can't do much for now but I'm trying anyway :) 

Sample code is extracted from a `nestjs` app wrote in typescript, using `@nest/support-express`. Only particularity of this is that nestjs heavily relies on decorator. Which is why we opt to try to get faster  build with swc.

`pnpm` is our package manager - no idea if it's relevant or not.

This is a shortened `package.json` that we have. There is not much in but it's important:
```json
{
  "name": "@acme/api",
  "dependencies": {
    "@nestjs/platform-express": "7.6.18"
  },
  "devDependencies": {
    "@types/express": "4.17.13"
  },
  
  "main": "build/main.js"
}
```

### Input code

```typescript
import { Injectable, NestMiddleware } from '@nestjs/common';
import { NextFunction, Request, Response } from 'express';

@Injectable()
export class ApmUserContextMiddleware implements NestMiddleware {
  use(req: Request, _: Response, next: NextFunction): void {
    return next();
  }
}
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020",
    "loose": true,
    "externalHelpers": true
  },
  "minify": false,
  "module": {
    "type": "commonjs",

    // These are defaults.
    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.23&code=H4sIAAAAAAAAA12OPQvCMBCG9%2FyK22yh4N4uFUFwsIPgLDU9ISW5pLlUC6X%2F3bSgVbfjvffjUcZZH2CEI7UoQ33TmEGFHE6qaTQ%2Ba48wwd1bA5uSot7yVlpjLG0Kod7hCodw6EkGZSmDM3Z9dM4HO0u8NuDgPDLHqCjXwSQV8TE3SV0zw86ZC6PfWwqx9wsk7mk0SIH%2FEUcB0DMmHrt83b%2FmH4QMKHblP6RpDg%2BrmiUM4DH0nhZbkhZRmsQkXlQa1x0fAQAA&config=H4sIAAAAAAAAA02PwY6DMAxE%2FyXaY1WqHjn3sD3wEZYxFJTEkW20pdX%2B%2BxpRYG%2FJaObN%2BB2%2BFB%2BUINThYVa0rqpROZ9XVY2Fzix9pT8oGE5hVAz1OxQQJVleOmeDp8dtLqQoQzG3mbpkMtEptHOGNOA9FRYLdQdRF5WQBRyvq%2B%2FXMwJZO5a0YCP1gPNtc%2B2wTWjIoAWDIw3Sk%2FMD6fVyvfiGyKy0BelpJBniN8VC%2F0rTkIdu3mclbqdIy4DlHKchp8R5VOepyYDHBeu34XbviPA6SJnv2Su5fBTvUp4EqYGy1f8BVqTtjn4BAAA%3D

### Expected behavior

Two things are problematic here:

`const _tsDecorate = require("@swc/helpers/lib/_ts_decorate.js").default;`

So I need to add @swc/helpers as a PROD dependency... Which is strange considering @swc/core and @swc/cli are devDeps.

Also problematic, if you look at the `.js.map` file: 

`\nimport { NextFunction, Request, Response } from 'express';`

The typescript code is not importing from `express`, it's importing from `@types/express`. `tsc` will get that and remove the import. `swc` won't, therefore, my build code expect to have the `express` package installed. It is not. Code fail :) 

### Actual behavior

I guess the `@swc/helpers` is required to help with decorators... But again, it's strange to have to set it up as a dependency just to get this one script...

Writing this issue, I found new doc about the fake `express` import that I need to try. Still, the behaviour might be questioned (or not).

### Version

1.3.23

### Additional context

Thanks for all the work ! I am really struggling with `tsc` build times and I surely hope that with time I'll be able to implement a fully functional build process using `swc` !

**Comment by kwonoj** [comment]
Not sure if I understood 

>swc won't, therefore, my build code expect to have the express package installed. It is not. Code fail :)

correctly. The repro you shared, it's output is 

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "ApmUserContextMiddleware", {
    enumerable: true,
    get: ()=>ApmUserContextMiddleware
});
const _tsDecorate = require("@swc/helpers/lib/_ts_decorate.js").default;
const _common = require("@nestjs/common");
let ApmUserContextMiddleware = class ApmUserContextMiddleware {
    use(req, _, next) {
        return next();
    }
};
ApmUserContextMiddleware = _tsDecorate([
    (0, _common.Injectable)()
], ApmUserContextMiddleware);

```

Which does not have references to `express` correctly. What actually fails?

**Comment by pierre-aurele-martin** [comment]
No, the express import is generated in the source file .map.js (which doesn't appear in the playground) but I've put the sample code in the OP

**Comment by pierre-aurele-martin** [comment]
So, reading your messages, I figured most of my issue out. Thanks for that.

For `@swc/helpers`, it's the option `externalHelpers: true` -> it's actually written in the doc. I somehow missed it.

And I focused on the sourcemap wrongly... they are not used in prod but it's the first place where I finally found `express` so it grasp my focus...

[But: check in this playground](https://play.swc.rs/?version=1.3.23&code=H4sIAAAAAAAAA1VQQW6DQAy88wrfgCiCO6kqqjwgUdMPRBs3bAtrZHujRoi%2F15A0NBdrNZ6dGY%2FvemKFAbYUlKltkdewJ9E1vKPACJ9MHaR1QNEvKR11HYV0k%2Fi%2Ff8bqKQg%2BqPjTM4oYZyEd%2FDn4cEC%2BeLcwi1JmvJDbYvpSLzmydFpT1DRPTHRScu1RZFYzeGHCkAA4S6EcnRJnPZOiUzwB4%2FFEob2C%2FI9QPSfKYRgTkyhXK5uwgv3u8AHl3X6GbvjdGbRBM4zMGBSixZ%2FXpc166i7L7XWUa3Bw18hq6ykboLf82jDFc1OBpbUycsso1aPHvIK9teMFXy7kT6%2FzbWCOXoqnG4pobH2L2myJvj1mJpNvjDwmY%2FIL0WLM59cBAAA%3D&config=H4sIAAAAAAAAA2WPsW7DMAxE%2F0XoGMRBRs8dmsEfQci0I0MSBZJGowT991Jw7QzdeAe%2BO%2FLlPsTfMYHr3V21SN91i1A%2Bb64oMZ6J506%2BPXt3cot4179cARbkNknNCg%2FDtRYUz6GoramYpbziyY01Qwr%2BlgqxHiZ6YrB02ZwfQxiyTMSppUacwdfPfesfNqDCCApvGnhGi3co18v1YidEIsEdxIciZ4hfGAu20gmiNC6FHKb6p03SuEZsF7R3LM5TSpQXsUBRDl6P1U0ONB4lEZ51nzPdslVSeVcJrexxgHLU%2FwLBeHnGfgEAAA%3D%3D)

Express is indeed required... No idea why.

I found that the option `decoratorMetadata: true` is responsible for that. By setting it to false, it disappear .

So I still have some test to perform but it's starting to look good :)

**Comment by kwonoj** [comment]
that's due to metadata output differences looks like.

```
    __metadata("design:paramtypes", [
        typeof _express().Response === "undefined" ? Object : _express().Response
    ])
```

**Comment by pierre-aurele-martin** [comment]
Ok, I think I've got the bug.

Paste this code in the playground - it'll require express: 
```
import { Injectable, NestMiddleware, Post } from '@nestjs/common';
import { NextFunction, Request, Response } from 'express';

@Injectable()
export class ApmUserContextMiddleware implements NestMiddleware {
  @Post()
  use(req: Request, _: Response, next: NextFunction): void {
    return next();
  }
}
```

Now the exact same code w/o `@Post`:

```
import { Injectable, NestMiddleware, Post } from '@nestjs/common';
import { NextFunction, Request, Response } from 'express';

@Injectable()
export class ApmUserContextMiddleware implements NestMiddleware {
  use(req: Request, _: Response, next: NextFunction): void {
    return next();
  }
}
```

And it won't.

It require express to generate this code:
```
 __metadata("design:paramtypes", [
        typeof _express().Request === "undefined" ? Object : _express().Request,
        typeof _express().Response === "undefined" ? Object : _express().Response,
        typeof _express().NextFunction === "undefined" ? Object : _express().NextFunction
    ])
```

So my current situation is that I need metadata for the transpiled code to work. But it also break the same code in other parts.

Any advice on how I could handle the situation ?

**Comment by pierre-aurele-martin** [comment]
That's the solution I found: `import type { Response } from 'express';`

Like this, it doesn't require express even with `decoratorMetadata: true`

So I can close this issue, is there a bug or not ? I don't know... I think a rule of thumb would be to never require a package which is not in `dependencies`. I can't think of a reason to do so but may be there is...

Anyhow, thanks for the help ! We'll finally be able to enjoy fast build !
