### ISSUE TITLE
minify should not remove licence comments

### ISSUE THREAD

**Issue by tbjgolden** [swc-project/swc#6677]
### Describe the bug

Many users will be unaware that they could be breaking their software licence by having `minify: true`.

Other minifiers seem to use the convention that if a comment:

- starts with a ! (e.g. `/*! license ... */` or `//! license ...`), OR
- looks like it contains a JSDoc licence `/** @license */`

that it should not be removed with the default minify settings.

### Input code

```typescript
/*! MIT @lorem example.org */

foo();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.23&code=H4sIAAAAAAAAA9PXUlTISM3JyVcozy%2FKSVHQ0ufiSsvP19C05gIAxeneNhsAAAA%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t%2B0id8ghhKsEF%2F%2BQFIgxvnvlkpCdZubpdfiKh6VDRRbieUnLiicsQD6heA5VwRlm1YZRaDhQ5J10IvKyLZYidK0OUshha9PkS6pMIs%2BEeY83OUyUyueYRQdtlf7CN4zHoXzYW5D14mYeP5P5%2B3m0AAAA

### Expected behavior

Comment is not removed

### Actual behavior

Commit is removed

### Version

1.3.23

**Comment by alexander-akait** [comment]
Looks like we don't remove them, we just don't print them, try to disable `minify`

**Comment by tbjgolden** [comment]
Been doing some research:

The defacto standard has been to not remove comments with an exclamation at the start: `/*! ... */`, `//! ...`, or to remove comments containing: `@license`.

- `terser`, `uglify`, support this option behaviour by default
- google closure compiler does not remove these comments 
- `babel` minify supports `@license` by default, but not `!`
- `esbuild` has this option `--legal-comments` but has it disabled by default
- `swc` has this option `compress.format.comments: "some"` but has it disabled by default

Only `esbuild` and `swc` do not try to preserve legal comments by default - perhaps it would make sense for both projects to enable it.

https://github.com/evanw/esbuild/issues/2745

**Comment by ishowta** [comment]
When I specify an empty object for minify in playground `"minify": {}`, the comment disappears, but when I remove the `minify` field, the comment appears.

**Comment by ishowta** [comment]
@tbjgolden I was just looking into minifier license preservation too, at least if I don't specify a config file, the license comments are preserved. I confirmed that Nextjs13 (which uses swc internally) also preserve the license comments. please see my above comment.
