### ISSUE TITLE
Helper functions are positioned in between class and jsdoc comment

### ISSUE THREAD

**Issue by rplc** [swc-project/swc#6683]
### Describe the bug

If you have a doc code for a class, helper functions/import statements will be positioned in between doc code and class (see playground link).

To answer the question upfront why this matters: One potential use of swc for me would be to transpile the source code before running an old program to generate our doc codes from this.

### Input code

```typescript
/**
 * This is just a doc code for the class Foo.
 */
class Foo {
    async bar() {
        return 'foo';
    }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "preserveAllComments": true
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.23&code=H4sIAAAAAAAAAz3KQQqAIBSE4b3gHWZXucgDtO8EXcDUqAgf%2BHQR0d1Ton5m9TFaKSmgMK0bo2zPnGDgyMKS81goIq0e9jDMGIn6etdS%2FICrSMnwGSxmE9vuo1r0KceAZiFqhpdvKe4HI9b%2FKXgAAAA%3D&config=H4sIAAAAAAAAA0WNOwrDMAxA76LZaztkK517COEqwcU%2FJKXUhNy9VjB4E3pPTwd8xMNyQEUWYpukZcUfLEA%2BoXgOVcF1ra9WjEKnA0XeSE2RW2exFKFBHaSQw9qs5EuqTCITYd4izY5R4i89YnyWlChrd5V3Y6m8d3MP0Fbp%2BnWHc%2BZHMshriNfdHzhZ%2FNXQAAAA

### Expected behavior

I would expect the helper functions to be generated above the doc code. I.e. in the order helper functions, followed by the doc code, followed by the class.

### Version

1.3.23

**Comment by alexander-akait** [comment]
This is generated code, so a lot of things can be ugly. Why you need it? Can you have real use case why it is bad for you?

**Comment by rplc** [comment]
As I've said before:
We need to transpile the source code before using the transpiled output to generate doc codes from.
Yeah for sure the transpiled output is ugly but in this case it matters where the helper functions are placed.

**Comment by kdy1** [comment]
Closing as not planned
