### ISSUE TITLE
Windows line endings break source maps

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#6694]
### Describe the bug

A block comment before a function produces invalid sourcemaps

![Bildschirm­foto 2022-12-20 um 18 24 14](https://user-images.githubusercontent.com/4586894/208728187-2c0d6475-f971-411b-a160-f07e472ab299.png)

### Input code

(See https://github.com/swc-project/swc/issues/6694#issuecomment-1360240667, this is due to Windows line endings)

```typescript
/**
 * foo
 * @param data foo
 * @returns foo
 */
export const fixupRiskConfigData = (data: any): types.RiskConfigType => {
  if (x) {
    return 123;
  } else {
    return 456;
  }
};
```

### Config

```json
{
	"jsc": {
		"parser": {
			"syntax": "typescript"
		},
		"target": "es2022"
	},
	"sourceMaps": true,
	"inlineSourcesContent": true
}
```

### Expected behavior

The sourcemap should be correct

### Version

1.3.23

### Additional context

Found in https://github.com/parcel-bundler/parcel/issues/8691

**Comment by jridgewell** [comment]
We recently had improvements to our sourcemap code. Running the example in the [playground](https://play.swc.rs/?version=1.3.23&code=H4sIAAAAAAAAA0vOzysuUchPylKwVahWSEvMS660UjAxUqi15koGS5Ul5gClgArs9aLzSnNyFGpqFNTB6tRjwUryc1L1cvLTNdSBKtV1QOo1AfhU17pVAAAA&config=H4sIAAAAAAAAA21TS7IbIQy8C2svUl5k8Q6QXVY5AIVBjPUyoCkk%2FDzlenePmLEZj50darob%2FbiZT%2Fbm42YmVxhKO%2FGcxV3Nh5F5AvYFJzEHI6yQlArfei4uc6SSGr2A87IcahZMoEJXhZIT9KrDNFGRP1SLb1fTSj%2BYABcYaUqQ5e7bjF0ZQGMDfPxxPCptJGLVRTcyHEzCjHFuj3lKasXcziqqzYc7z5VCX7z6HsyJaATN%2BDW2ji1mgQHKJvU0jm5isBdXuqK95goy5R1UBYKdCk1PaA4oSFnNHlgAF6ynAB3AAl7wAhtFPZSSWRPrmSxggFMdhjaYlQkXN1Yn3QuuSxv0xa47E7LYWDO%2FQLtMV2gt8s7CaAtILfnB%2BSTMuz78BdA8R8ecXYJNueBR57Bnxv%2BwMEcdoswd1QlvWWUYtDiLGHuFLWsoglu3CoTqoVXoN%2FM7uCuIMYCFGLXbXcxfKP68mbUlp9hD7ZqL2wzW0D72aY%2B2FXgDf2lW8jyOO67%2F4fyK8ZxONL5ZJJAzhTdYGyH0Chbd3uv0itYcQNsM4emicgv7murwhewIsvVZF0I1dhjp1NdXP2Vyeehr2X5polAbcFuat%2FzWn%2BZ7%2B52rH%2FLvO2%2Fx%2BQd0Pd7PaQQAAA%3D%3D), and pasting that into the [visualizer](https://evanw.github.io/source-map-visualization/#Nzg5AC8qKgogKiBmb28KICogQHBhcmFtIGRhdGEgZm9vCiAqIEByZXR1cm5zIGZvbwogKi8gZXhwb3J0IGNvbnN0IGZpeHVwUmlza0NvbmZpZ0RhdGEgPSAoZGF0YSk9PnsKICAgIGlmICh4KSB7CiAgICAgICAgcmV0dXJuIDEyMzsKICAgIH0gZWxzZSB7CiAgICAgICAgcmV0dXJuIDQ1NjsKICAgIH0KfTsKCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnpiM1Z5WTJWeklqcGJJbWx1Y0hWMExuUnpJbDBzSW5OdmRYSmpaWE5EYjI1MFpXNTBJanBiSWk4cUtseHVJQ29nWm05dlhHNGdLaUJBY0dGeVlXMGdaR0YwWVNCbWIyOWNiaUFxSUVCeVpYUjFjbTV6SUdadmIxeHVJQ292WEc1bGVIQnZjblFnWTI5dWMzUWdabWw0ZFhCU2FYTnJRMjl1Wm1sblJHRjBZU0E5SUNoa1lYUmhPaUJoYm5rcE9pQjBlWEJsY3k1U2FYTnJRMjl1Wm1sblZIbHdaU0E5UGlCN1hHNGdJR2xtSUNoNEtTQjdYRzRnSUNBZ2NtVjBkWEp1SURFeU16dGNiaUFnZlNCbGJITmxJSHRjYmlBZ0lDQnlaWFIxY200Z05EVTJPMXh1SUNCOVhHNTlPeUpkTENKdVlXMWxjeUk2V3lKbWFYaDFjRkpwYzJ0RGIyNW1hV2RFWVhSaElpd2laR0YwWVNJc0luZ2lYU3dpYldGd2NHbHVaM01pT2lKQlFVRkJPenM3TzBOQlNVTXNSMEZEUkN4UFFVRlBMRTFCUVUxQkxITkNRVUZ6UWl4RFFVRkRReXhQUVVGdlF6dEpRVU4wUlN4SlFVRkpReXhIUVVGSE8xRkJRMHdzVDBGQlR6dEpRVU5VTEU5QlFVODdVVUZEVEN4UFFVRlBPMGxCUTFRc1EwRkJRenRCUVVOSUxFVkJRVVVpZlE9PTQyNAB7InZlcnNpb24iOjMsInNvdXJjZXMiOlsiaW5wdXQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiLyoqXG4gKiBmb29cbiAqIEBwYXJhbSBkYXRhIGZvb1xuICogQHJldHVybnMgZm9vXG4gKi9cbmV4cG9ydCBjb25zdCBmaXh1cFJpc2tDb25maWdEYXRhID0gKGRhdGE6IGFueSk6IHR5cGVzLlJpc2tDb25maWdUeXBlID0+IHtcbiAgaWYgKHgpIHtcbiAgICByZXR1cm4gMTIzO1xuICB9IGVsc2Uge1xuICAgIHJldHVybiA0NTY7XG4gIH1cbn07Il0sIm5hbWVzIjpbImZpeHVwUmlza0NvbmZpZ0RhdGEiLCJkYXRhIiwieCJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Q0FJQyxHQUNELE9BQU8sTUFBTUEsc0JBQXNCLENBQUNDLE9BQW9DO0lBQ3RFLElBQUlDLEdBQUc7UUFDTCxPQUFPO0lBQ1QsT0FBTztRQUNMLE9BQU87SUFDVCxDQUFDO0FBQ0gsRUFBRSJ9), I'm getting correct sourcemaps:
<img width="1280" alt="Screen Shot 2022-12-20 at 3 40 36 PM" src="https://user-images.githubusercontent.com/112982/208762191-199bd0dc-9d3e-4064-a55b-25022a0d6006.png">

**Comment by mischnic** [comment]
Turns out, this is actually due to Windows line endings. Reproduction:

```js
const { transformSync } = require("@swc/core");

let output = transformSync(
  `/**
 * foo
 * @param data foo
 * @returns foo
 */
export const fixupRiskConfigData = (data: any): types.RiskConfigType => {
  if (x) {
    return 123;
  } else {
    return 456;
  }
};`.replaceAll("\n", "\r\n"),

  {
    jsc: {
      parser: {
        syntax: "typescript",
      },
      target: "es2022",
    },
    sourceMaps: "inline",
    inlineSourcesContent: true,
  }
);

console.log(output.code);
```

I got the reproduction from a Git repo, and copying that code into the issue of course normalized the line endings...

**Comment by mischnic** [comment]
([And related to that, someone also reported similar sourcemap problem in Parcel](https://github.com/parcel-bundler/parcel/issues/8302))

![Bildschirm­foto 2022-12-20 um 22 04 40](https://user-images.githubusercontent.com/4586894/208766198-035e22c7-66ac-4598-b6be-9a3534ce3119.png)

swc Repo for that:

```js
const { transformSync } = require("@swc/core");

let output = transformSync(
  ` console.log("test1") // line 1 correct

let text = \`
    1
    1
    1
    1
    1
    1
    \`

console.log("test2") // this should be line 12, instead 17 in devtools

let test0
let test1

console.log("test3")  // this only woks because last line if you add more content it wont work`.replaceAll("\n", "\r\n"),

  {
    jsc: {
      parser: {
        syntax: "typescript",
      },
      target: "es2022",
    },
    sourceMaps: "inline",
    inlineSourcesContent: true,
  }
);

console.log(output.code);
```

**Comment by jridgewell** [comment]
Ah, ok, seems we need to update:
- https://github.com/swc-project/swc/blob/3922ef5539da4e51d0e6a44872dc31609facd494/crates/swc_common/src/syntax_pos/analyze_source_file.rs#L243-L245
- https://github.com/swc-project/swc/blob/3922ef5539da4e51d0e6a44872dc31609facd494/crates/swc_common/src/syntax_pos/analyze_source_file.rs#L133-L134
