### ISSUE TITLE
Sourcemaps generated based on initial src, plugins ignored

### ISSUE THREAD

**Issue by joonarahko** [swc-project/swc#6700]
### Describe the bug

First of all, thanks for all the amazing work you are putting into SWC 🙏 🎖️ 

My problem is as follows, I am using a 3rd party plugin @formatjs/swc-plugin with @swc/core 1.3.2. Using the 3rd party plugin with source maps results in broken source maps. I know the JS based plugins are being replaced with native rust ones but as there is not a good alternative for formatjs yet, hoping to get the existing plugin to work. I cannot unfortunately yet use the new experimental formatjs plugin.

Let me know if I can help repro in other ways such as by adding a failing test case etc. There is a little more detail on debugging I did on my end today.

### Input code

```typescript
const validate = require("sourcemap-validator");
const assert = require("assert");
const { transform } = require("@swc/core");
const { FormatJSTransformer } = require("@formatjs/swc-plugin");

const input = `
  const msgs = defineMessages({
    header: {
      defaultMessage: \`Hello World!\`,
      description: 'The default message',
    },
  });
`;

(async () => {
  const swcWithoutFormatJs = await transform(input, {
    filename: "test.js",
    sourceMaps: true,
    jsc: {
      parser: {
        decorators: true,
        dynamicImport: true
      }
    }
  });

  const swcWithFormatJs = await transform(input, {
    filename: "test.js",
    sourceMaps: true,
    jsc: {
      parser: {
        decorators: true,
        dynamicImport: true
      }
    },
    plugin: (m) =>
      new FormatJSTransformer({
        filename: "test.js",
        overrideIdFn: "[hash:base64:10]"
      }).visitProgram(m)
  });

  console.log("================= swcWithoutFormatJs ========================");
  console.log(swcWithoutFormatJs);
  console.log("================= swcWithFormatJs ========================");
  console.log(swcWithFormatJs);

  // this assert is ok
  assert.doesNotThrow(
    () => validate(swcWithoutFormatJs.code, swcWithoutFormatJs.map),
    "The sourcemap is not valid"
  );

  // this assert fails if we apply the formatJS plugin
  assert.doesNotThrow(
    () => validate(swcWithFormatJs.code, swcWithFormatJs.map),
    "The sourcemap is not valid"
  );
})();
```

### Config

```javascript
{
  filename: "test.js",
  sourceMaps: true,
  jsc: {
    parser: {
      decorators: true,
      dynamicImport: true
    }
  },
  plugin: (m) => (
    new FormatJSTransformer({
      filename: "test.js",
      overrideIdFn: "[hash:base64:10]"
    }).visitProgram(m),
  )
}
```

### Playground link

https://codesandbox.io/s/hopeful-jerry-hbzq8j

### Expected behavior

I would expect that the sourcemap would be generated after the formatjs plugin has finished running so that the sourcemaps get generated correctly.

### Actual behavior

I used a debugger and stepped through the code and it seems like [bindings.transform](https://github.com/swc-project/swc/blob/caaf491da51b32424baf280513cf554c59aae72a/node-swc/src/index.ts#L202) does get called correctly with the transformed code. However, the WASM return source map that matches the initial source code prior to the formatjs plugin. This results in the sourcemap not being valid.

Screenshot from the debugging with slightly altered code. See how the callValue has the correct AST and resValue has correct code under the code property but the map property contains a sourcemap for the initial input before the plugin transform.

![Screen Shot 2022-12-20 at 9 11 51 PM](https://user-images.githubusercontent.com/28296253/208826657-1b6f8f1d-7fbe-45f8-b858-13049a16d982.png)

![Screen Shot 2022-12-20 at 9 12 01 PM](https://user-images.githubusercontent.com/28296253/208826659-2e8cf3a1-7ee9-4de5-bb2e-6b153ee360ff.png)

### Version

1.3.23

**Comment by kwonoj** [comment]
Unfortunately, we do not actively working on legacy plugin, as you may be aware current focus is new experimental plugin system. 

We are welcome to accept PR if you can bring fixes & if it's not massively breaking changes. However, core team is probably not able to find resources to dig this into.

**Comment by joonarahko** [comment]
Was able to fix it like this:

https://codesandbox.io/s/stoic-river-4zl110?file=/index.js

Downside is that I have to parse -> transform -> convert back to source, but at least I end up with correct source maps :)

**Comment by kwonoj** [comment]
I'll be closing this for now as an adequate workaround is available.
