### ISSUE TITLE
Compress binary releases

### ISSUE THREAD

**Issue by xnuk** [swc-project/swc#6706]
### Describe the feature

Playing with [v1.3.24 release] binaries, I find that compressing them can reduce sizes into about 1/3. This can reduce network traffics.

```sh
$ sha256sum swc-*
fa2b3ba6c58c4742da4011b84cfdda8fbc2a153d9d25be6431083ce9c40cbec6  swc-linux-x64-musl
4a28408c09de0c19bbc83920927853ad93c06619b06497baa2d1c3ea8d322bcc  swc-win32-x64-msvc.exe

$ gzip --keep swc-linux-x64-musl swc-win32-x64-msvc.exe
$ zstd -k swc-linux-x64-musl swc-win32-x64-msvc.exe

$ du --bytes --human-readable --apparent-size --summarize swc-*
36M	swc-linux-x64-musl
12M	swc-linux-x64-musl.gz
11M	swc-linux-x64-musl.zst
37M	swc-win32-x64-msvc.exe
12M	swc-win32-x64-msvc.exe.gz
11M	swc-win32-x64-msvc.exe.zst

# https://upx.github.io/
$ upx swc-linux-x64-musl
$ du --bytes --human-readable --apparent-size --summarize swc-linux-x64-musl
12M	swc-linux-x64-musl
```

[v1.3.24 release]: https://github.com/swc-project/swc/releases/tag/v1.3.24

**Comment by kwonoj** [comment]
Do you suggest published npm pkg should be zipped and it need to be extracted when installed?

**Comment by xnuk** [comment]
> Do you suggest published npm pkg should be zipped and it need to be extracted when installed?

npm packages are already shipped with `.tgz`, so this won't be the case. I just meaning the Github releases.

**Comment by kwonoj** [comment]
> Github releases.

Github releases are for archiving, not explicitly being used. What's the usecase?

**Comment by kwonoj** [comment]
Closing this for now.
