### ISSUE TITLE
not support *zoom: 1

### ISSUE THREAD

**Issue by hardfist** [swc-project/swc#6718]
### Describe the bug

Expected '{' (Recoverable) (17..18)
Unexpected token (Recoverable) (9..10)

### Input code

```typescript
div {
 *zoom: 1;
}
```

### Config

```json
{}
```

### Playground link

https://swc-css.netlify.app/?code=eJxLySxTqOZSUNCqys_PtVIwtOaqBQA4hgVl

### Expected behavior

not report error

### Actual behavior

report error

### Version

0.141.5

**Comment by kdy1** [comment]
@alexander-akait Is this valid syntax?

**Comment by alexander-akait** [comment]
@kdy1 

No, errors are expected, I can implement the `ie_legacy` option, but we can't handle all IE bugs, because IE6/7 parser is very very very buggy, so we developers should ignore such errors

**Comment by kdy1** [comment]
Thank you for description!
I think it's fine then.
