### ISSUE TITLE
contos6.9 Compilation error

### ISSUE THREAD

**Issue by zhouzyc** [swc-project/swc#6724]
### Describe the bug

 { "@swc/core": "^1.3.4" } Compilation error ;
yarn dev:h5;
yarn run v1.22.17
$ cross-env BUILD_ENV=dev taro build --type h5
?? Taro v3.5.10
thread '' panicked at 'attempt to divide by zero', library/std/src/sys/unix/thread.rs:552:70
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

locking version "resolutions": { "@swc/core": "1.3.3" } normal;

### Expected behavior

Normal compilation

### Version

^1.3.4

**Comment by kwonoj** [comment]
what is `taro build`? please provide reproducible codes, **without** other external tools to confirm if this is swc/core issue or not.
