### ISSUE TITLE
install swc_cli failed

### ISSUE THREAD

**Issue by lishoulong** [swc-project/swc#6733]
### Describe the bug

I think we should have a pre dependencies doc for installing 'swc_cli', especially for newer.
```
cargo install swc_cli
```

Updating crates.io index
  Downloaded swc_cli v0.91.11
  Downloaded 1 crate (32.9 KB) in 2.58s
  Installing swc_cli v0.91.11
error: failed to compile `swc_cli v0.91.11`, intermediate artifacts can be found at `/var/folders/zd/lnd478dn09vgfd72vv8tzjrw0000gn/T/cargo-installVIvc8H`

Caused by:
  failed to select a version for the requirement `swc_core = "^0.50.1"`
  candidate versions found which didn't match: 0.23.5, 0.23.4, 0.23.3, ...
  location searched: crates.io index
  required by package `swc_cli v0.91.11`

> I looked the issues, and find the following commands:
```
cargo install swc_cli --locked
```

Updating crates.io index
  Installing swc_cli v0.91.11
error: failed to select a version for the requirement `swc_core = "=0.50.3"`
candidate versions found which didn't match: 0.23.5, 0.23.4, 0.23.3, ...
location searched: crates.io index
required by package `swc_cli v0.91.11`

> and suddenly I find my rust version is nightly-x, it is slightly old version, and I switch to the 'stable-x86_64-apple-darwin
', then the installing work.

Default host: x86_64-apple-darwin
rustup home:  /Users/lishoulong/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-2021-09-30-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-2021-09-30-x86_64-apple-darwin (default)
rustc 1.57.0-nightly (11491938f 2021-09-29)

> So i suggested we should add pre environments in the [page](https://github.com/swc-project/swc/discussions/3540)

### Expected behavior

we should install swc_cli smoothly

### Actual behavior

[it errors with ](error: failed to compile `swc_cli v0.91.11`)

### Version

v0.91.11

**Comment by kdy1** [comment]
It's fixed
