### ISSUE TITLE
Class is not transpiling after 1.3.21

### ISSUE THREAD

**Issue by forbid403** [swc-project/swc#6740]
### Describe the bug

Hello,

Class is not transpiling after 1.3.21.
1.3.20 is fine.

Please tell me if I'm missing something.
Thanks!!

### Input code

```typescript
class Example {
  doSomethingOnClass = (x) => {
    console.log(x)
  }
}

const doSomething = async () => {
  const ex = new Example();
  ex.doSomethingOnClass(await Promise.resolve('some string'));
}

doSomething();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "useBuiltins": true
      }
    },
    "loose": false,
    "target": "es5"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "",
    "dynamicImport": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.21&code=H4sIAAAAAAAAA2WOSwrCMBCG94HcYXZNNrmA1I24VvAEIQ41kIdkgo2Id3fSIhaEWc33v1ywRHBsNt4DwksKgGu%2B5Ij15tN0SoeFj6CahnG%2FCgBcTpQDmpAnBv33loJPik7qNoK9lp7JgfoFrCJszBLO33aldx1iM%2F8LlJ2tr3AuOXpCU5DrH6gGYh1QLawcdPcvIzZ%2BDv0A4WlrB%2BMAAAA%3D&config=H4sIAAAAAAAAAz2NOw4CMQxE7%2BJ6W5qUdBQcwsp6kVF%2Bsh1EtNq747CCbqSZeW%2BHp0YIOzQUJZlJRzF8QwAbjTQKN4NjARMsulXJcyOE0b6hF%2BNMvsZuNaNxhAW60rVzMi4KwaTT4YBUq%2Fpww6TkOJQHOQJILxOfufA2%2FjXrva490XlfgMpr6s6XQ8Et6yiYOd5yq2I%2FzwdHogp70QAAAA%3D%3D

### Expected behavior

https://play.swc.rs/?version=1.3.20&code=H4sIAAAAAAAAA2WOSwrCMBCG94HcYXZNNrmA1I24VvAEIQ41kIdkgo2Id3fSIhaEWc33v1ywRHBsNt4DwksKgGu%2B5Ij15tN0SoeFj6CahnG%2FCgBcTpQDmpAnBv33loJPik7qNoK9lp7JgfoFrCJszBLO33aldx1iM%2F8LlJ2tr3AuOXpCU5DrH6gGYh1QLawcdPcvIzZ%2BDv0A4WlrB%2BMAAAA%3D&config=H4sIAAAAAAAAAz2NOw4CMQxE7%2BJ6W5qUdBQcwsp6kVF%2Bsh1EtNq747CCbqSZeW%2BHp0YIOzQUJZlJRzF8QwAbjTQKN4NjARMsulXJcyOE0b6hF%2BNMvsZuNaNxhAW60rVzMi4KwaTT4YBUq%2Fpww6TkOJQHOQJILxOfufA2%2FjXrva490XlfgMpr6s6XQ8Et6yiYOd5yq2I%2FzwdHogp70QAAAA%3D%3D

This is version 1.3.20 with same code.

### Version

1.3.21

**Comment by kdy1** [comment]
Your `env.target` is wrong
