### ISSUE TITLE
No rules expected the token `"-moz-element"`

### ISSUE THREAD

**Issue by MrToy** [swc-project/swc#6759]
### Describe the bug

When upgrading swc_css_parser  to  v0.142.1 and its [dependencies.swc_atoms] version = "0.4.32", something went wrong

### Expected behavior

Compiling swc_css_parser v0.142.1
error: no rules expected the token `"-moz-element"`
    --> /Users/toy/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_css_parser-0.142.1/src/parser/values_and_units/mod.rs:1619:44
     |
1619 |             js_word!("element") | js_word!("-moz-element") => {
     |                                            ^^^^^^^^^^^^^^ no rules expected this token in macro call

error: could not compile `swc_css_parser` due to previous error

### Version

swc_css_parser = v0.142.1

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/commit/48902b60d3cd6b81f7d331064e03dbee3cf28cca
