### ISSUE TITLE
Dropping unused imports by simplifier()

### ISSUE THREAD

**Issue by manucorporat** [swc-project/swc#6771]
### Describe the feature

While i understand why it's not an always safe optimization, we rely on it at Qwik. This bug fix is preventing us to update to latest SWC.
https://github.com/swc-project/swc/issues/6503

It would be great to have an option to enable the previous behaviour where unused imports are dropped!

**Comment by manucorporat** [comment]
This issue is preventing us from upgrading Qwik to the latest of SWC, wondering @kdy1 can give me a little guidance of how you will like to implement an option for this, maybe a new option of the simplifier?

**Comment by kdy1** [comment]
I'm not going to work on this in a near future, but I think we need an option under `jsc.transforms.optimization`
