### ISSUE TITLE
SWC Compress + Svelte = Error

### ISSUE THREAD

**Issue by rikschennink** [swc-project/swc#6780]
### Describe the bug

I don't know wether this problem originates in Svelte or in SWC, I lean towards SWC.

When I enable `compress` in the `.swcrc` config and then compress a Svelte built target the resulting file will throw an error when loaded in a browser.

I've set up a repository here: https://github.com/rikschennink/swc-svelte-problem

I ran into this because NextJS has enabled SWC to compress JS and since that time my Svelte based library can no longer be used with NextJS unless NextJS is configured to use Terser as JS compressor.

### Config

```json
{
    "jsc": {
        "minify": {
            "compress": true, // set to false and it no longer errors
            "mangle": false
        }
    }
}
```

### Expected behavior

It should work with and without `compress` enabled

### Actual behavior

When `compress` is enabled the Svelte app no longer loads and throws the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'context')
    at I (test-swc.js:197:49)
    at new ft (test-swc.js:336:43)
    at swc.html:18:13
```

This error is thrown because `current_component.$$` (Svelte specific) is somehow missing.

We can circumvent this by passing `context: []` to the App constructor but now the error will be thrown on the App child component.

### Version

1.3.25

**Comment by kdy1** [comment]
This is bug of swc

**Comment by rikschennink** [comment]
@kdy1 But what is it caused by, as-in what's it doing wrong, eliminating too much code?

**Comment by kdy1** [comment]
I don't know. I didn't investigate it yet

**Comment by rikschennink** [comment]
Ah okay, it seemed you knew because of the fast reply. 👍

**Comment by rikschennink** [comment]
🙏 Waw that was fast. Fingers crossed NextJS pulls this in asap.
