### ISSUE TITLE
using `parse_file_as_expr` to parse `import.meta` will throw `SyntaxError::ImportMetaInScript`

### ISSUE THREAD

**Issue by iheyunfei** [swc-project/swc#6781]
### Describe the bug

![image](https://user-images.githubusercontent.com/49502170/211561872-2d9d83b7-7cf5-4304-b70b-5413a3527e66.png)

![image](https://user-images.githubusercontent.com/49502170/211562435-8298bc13-6662-4722-89f1-f8e82781fde5.png)

### Expected behavior

Should parse successfully.

### Version

newest

### Additional context

Just doing some expression replacements such as `import.meta` => `true`.

**Comment by iheyunfei** [comment]
I found the cause and wonder how to fix it. 

Maybe accept a `IsModule` option in `parse_file_as_expr`?

**Comment by kdy1** [comment]
I think it's OK to unconditionally allow paring of `import.meta`

**Comment by iheyunfei** [comment]
Thanks for the quick reply. I would like to open a PR for it. Would you accept a fix in this way
![image](https://user-images.githubusercontent.com/49502170/211565403-64605d4a-3393-446c-988b-66eb354332ef.png)
or else?

**Comment by kdy1** [comment]
I'll accept, and thank you in advance!
