### ISSUE TITLE
Transpile RegEx 'unicode' flag

### ISSUE THREAD

**Issue by tjwds** [swc-project/swc#6798]
### Describe the bug

SWC does not transform regular expressions which use the 'u' flag when targeting JavaScript versions or browsers which do not support it.

### Input code

```typescript
const foo = /😎/u;

console.log(foo, bar);
```

### Config

```json
{
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "ecmascript"
    },
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true,
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.26&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVdD%2FMH9Gi36pNRdXMlA0PydVLyc%2FXQMop2nNBQCkzhmqKAAAAA%3D%3D&config=H4sIAAAAAAAAA3WUS27jMAyG7%2BJ1FtPFAIMeoLs5g8BIlKNUFg2RSmMUuftQsS3HSWdnfiIpPn75uzuz7d6%2FO4Hco3TvHfLv7tCNkBlzPeApCVzrgR2AbQ6jdLdDN4QU%2FFQdLA1jRub6rUnKgEnU8BAZD0oyfakpuah1JIoI6cU2wCYkwR7zFmopRhgZzQVyi6i3QQ5MaYeKoDNjpvGBJhckUNJkK3MIzlhy2EDIaCVccHPRHOqSWAtrldyhw2Pp%2BzqU2RMvEAtIy4XX%2Bxj0xhZ3osBifEn8hHaVzmhucvEK3mSUktPqc6aQdnP4RNQ6IzAnGHCLvHOve9h7%2Bh%2B8QvK6RJkajfRQVcJemzMh%2BNZhrRqzhG1aGV2xWDu0W%2FIF7hri4NCg9zrtFsxfQexpSybTiOSbqVMDv%2B1gNs2qpz2tEniBH1qVPK5j4QPI6ZnxNBwpvqQYUE7kXrAOQugZZlXvdXymJTnUMaN7OChczSZTXb6QifX1rXNWQWiM6SMdm3zro4PUV1nqc6Ux4gXjfqP%2F1cMPTC%2B51AUvUlyFh3%2B2nYHqKLz9WsDtVisgV5YKdFv6V9DJD5TOXP8JTCVb%2FAubiNa%2FxJzgH3jjPGdtBAAA

### Expected behavior

Unicode-flagged RegExps should be transformed; this example would become `/(?:\uD83D\uDE04)/`  Here's a Babel example:

https://babeljs.io/repl#?browsers=ios%209&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MD0heDcCB7aCuBuAKENEhABsBTAOnJAHMAKBEASiKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.12&externalPlugins=&assumptions=%7B%7D

### Actual behavior

SWC does not transform the RegExp; this throws an error in older browsers.

### Version

1.3.26

**Comment by kdy1** [comment]
This is duplicate
