### ISSUE TITLE
`mangle.toplevel` should be `true` by default for modules

### ISSUE THREAD

**Issue by antonybudianto** [swc-project/swc#6804]
### Describe the bug

I used swc/core v1.3.26 latest and used minify with mangled true. However, the build result is unexpected, the variables are not mangled. (video + playground attached)
If I used 1.3.25+1.3.24, mangling worked as expected

https://user-images.githubusercontent.com/7658554/212251411-5fb7f74a-2f0e-4310-8698-47a558c65aff.mov

### Config

```json
{
        minify: true,
        jsc: {
          minify: {
            compress: true,
            mangle: true,
            format: {
              asciiOnly: true,
              comments: /^ webpack/,
            },
          },
          target: 'es5',
          parser: {
            syntax: 'typescript',
            tsx: true,
          },
          experimental: {
            plugins: [
              [require.resolve('@swc/plugin-loadable-components'), {}],
            ],
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      }
```

### Playground link

https://play.swc.rs/?version=1.3.26&code=H4sIAAAAAAAAA0vOzysuUcitDC4tSC1yLE8tzs9NDUssUrBV0MjTVLC1U6jmUgCCZKCy%2FJxUvZz8dKC4NVctVzJYYx5QIYZmDaXERCWgIoiSJKxKDDW5uNANBQD1lbo2jAAAAA%3D%3D&config=H4sIAAAAAAAAA3WUTZLjIAyF78I6i54spqZygNnNGShihEMPRi4k3HGlcvcWNv5LZnbmQxIP6ZmH%2BqRGXR6qN4kglS8aI5u7uigee6Am%2BZ7VSTEJ4pThKd8mtcASAXT%2BOJ9lNyASqIszgeCkOh%2B9G0sth6kzXL4a7DqITJJF2IGSMoL6BERlWyrmul%2BLmJTwi%2BYzT%2BqKGMDEt7U2pH1kaCFtqQ2GYHoCPZi0ZpTTTPKE8YAyg9V9wn5Ho%2FXsMUqxhVkwVjdoYQU%2BQcN%2BgC1EakhIJBG2KpmghWtu29LcORIGE7LhtRbcpzbIiWveDT2xdjnSCzoondF8yRrlnU7AOcUl5hN9PPThL4DoDIYomg62zIk7mcMx0tWoHfLRyYB5XFNl%2BpuoCK3cTXvv1gsW0ZDYb3US2NxAuWCzKajwcB%2FyFjQ4J81ek%2BnLc3PbihWfoluX0jTjthHMS73Y6UiLA97gb1HF%2B2lULk6%2BvTIauyuGtxId8A3tG5ZGML7CJOa99680RwvSZrC7jUxlubpUZs%2BoQ%2FkTlz6LHyRHtwGvO%2Ff2MuzSrrP8dJ2JbTHoQzH2AQYIRwf81xn%2FYHLeUGZdTblYEH5t4zPiKP%2Fjo4LnsyhAm6sCGdz0ivwsz8HyasyaPf2pcdOj8w34mdNWqAQAAA%3D%3D

### Expected behavior

Variables should be mangled properly, just like previous version

### Actual behavior

Variables not mangled!

### Version

v1.3.26

**Comment by kdy1** [comment]
You need `mangle.toplevel = true`

https://play.swc.rs/?version=1.3.26&code=H4sIAAAAAAAAA0vOzysuUcitDC4tSC1yLE8tzs9NDUssUrBV0MjTVLC1U6jmUgCCZKCy%2FJxUvZz8dKC4NVctVzJYYx5QIYZmDaXERCWgIoiSJKxKDDW5uNANBQD1lbo2jAAAAA%3D%3D&config=H4sIAAAAAAAAA42UTZLjIAyF78I6i54spqZygNnNGShihEMPRi4k3HGlcvcWNv5LZjE78yGJh%2FTMQ31Soy4P1ZtEkMoXjZHNXV0Ujz1Qk3zP6qSYBHHK8JRvk1pgiQA6f5zPshsQCdTFmUBwUp2P3o2llsPUGS5fDXYdRCbJIuxASRlBfQKisi0Vc92vRUxK%2BEXzmSd1RQxg4ttaG9I%2BMrSQttQGQzA9gR5MWjPKaSZ5wnhAmcHqPmG%2Fo9F69hil2MIsGKsbtLACn6BhP8AWIjUkJJIIW5VM0MI1t21p7hwJgwnZ8FoL7lMb5MQ174aeWLsc6QUdlM5ovmSN8k4n4JziEvOJPh768BdAdAZDFE0HW%2BbEnczhGOlq1A756GTAPK6pMv1NVIRW7qa9d%2BsFi2hI7Lc6CWxuoFyw2RRUeLgPeQsanJNmr8n05bm5bcWKT9GtS2macdsI5qVe7HSkxQFv8Leo4v00Khcn314Zjd0Vw1uJDviG9g1LIxhfYRLz3vtXmqMFaTPY3UamslxdKrNn1KH8iUufxQ%2BSo9uA1517exl2addZfrrOxLYY9KEY%2BwADhP8zxj%2BYHDeUUVdPLg6EX9v0jBjK%2F%2Fio4PksAtDmKkDmNj0iP8trsDwasxhPf2rc9OZ8AxRf%2F6inBAAA

**Comment by kdy1** [comment]
I changed the title because it's matter of the default value

**Comment by kdy1** [comment]
I tested it and `mangle: true` works.

https://play.swc.rs/?version=1.3.26&code=H4sIAAAAAAAAA0vOzysuUcitDC4tSC1yLE8tzs9NDUssUrBV0MjTVLC1U6jmUgCCZKCy%2FJxUvZz8dKC4NVctVzJYYx5QIYZmDaXERCWgIoiSJKxKDDW5uNANBQD1lbo2jAAAAA%3D%3D&config=H4sIAAAAAAAAA2VTS7LjMAi8i9ZZTGUxixxgdnMGlWIhR29k4QKUF1fq3X2QP3Kc7EQDLWjgab64M5enGR0xUH3xlMU9zMXINAJ3FEcxJyOskFCBH3076kE0Avj863xWb0JkMJfgEsPJDDHHMFWugDQ4qa8OhwGysGYxDmCURqGRgLm6lbGs%2FpXEEeE3L3%2BezBUxgcsftnVsYxbogfbUDlNyI4O9O2oZ9TdHkTEfoCLg7Ug4vqDZR4mYlWzDPDhvO%2FTQgEjQSbzDHqIcGpJZC2uVzKCHa%2Bn7Ku4SCXeXipPGBY9ZBv2x5d0wsthQMr9Bh0oXaGlyjYrBEkihvMV8YcwHHf4BaJ3JMWc3wJ4540HncIwMa9QLFHPQAcvUUnX6e1EZeu3Nxhhag7VoIIk7D4EvHdQGu72CFTz0w9GDhRBU7JbM31G6205W9xRDM1U0F%2FYRLKbd1umI1g34AP9oVfI6jRXXTb69YzwNV0wfFAPIDf0HrEIIvoOky%2FsY39GSPajM4F8chavZtlRnL2hTvcRNZ90HzbF9wuvL9o467CrXWY9ucLlP62R%2Bqo2%2BVPs5yzjf9O96nNsNLwyR%2F65xc95%2FbXzUIjYEAAA%3D
