### ISSUE TITLE
Implement a javascript bundler similar to Rollup

### ISSUE THREAD

**Issue by nicksrandall** [swc-project/swc#681]
I'd like to take on the work to implement a Javascript bundler (similar to Rollup ) based on SWC's AST. I'm documenting this here in case anybody else would like to get involved or has feedback on how such a thing should be implemented. I'm admittedly new to Rust and I think this could be a good project to help me learn.

One of the problems that I see with current bundlers is that they do not share the AST with other plugins. So, for example, if I was going to create a JavaScript project and used Rollup to bundle, run Babel, and Terser or Closure Compiler for minification, each of those tools would be parsing and serializing the Javascript between each step. I'd like to explore a solution where the JS is parsed once into and AST and then various plugins/optimizations could be performed right on the AST.

The scope of this project would be to parse the javascript files and it's dependencies (imports), build a dependency graph, tree-shake the modules in the graph so that only items that used are included, and then output a new JS file where everything has been combined into a single file. I'd also like to support code-splitting/chunking so that we can keep the JS bundles small.

RollupJS is a great tool and I plan to shamelessly borrow from many of the things that they have learned over the past few years.

I'm planning to perform this work under my own github username but I'm totally open to transferring it to swc-project (if owners/community think it would be better that way).

**Comment by nick-at-hawkfish** [comment]
Looks like this work has recently been resurrected in #43. I'm also open to helping out there if that would be better.

**Comment by kdy1** [comment]
I'm alteady working on a bundler. I've made some success, and tree shaking and module merging are implemented.

The remaining tasks are handling js interop / chunking / dynamic import / cjs imports.


To see the working code, please refer to https://github.com/kdy1/swc/tree/spack/spack

I'm currently working on a .d.ts generater, and I'll build a bundler.

**Comment by kdy1** [comment]
Sorry for late response. Github was down.
