### ISSUE TITLE
SWC installs several node modules. Is this normal?

### ISSUE THREAD

**Issue by drnkwati** [swc-project/swc#6810]
### Describe the bug

Hi
When I run the following to download pre-built binaries, I get several hundred node modules as well.
```bash
pnpm i -D @swc/cli @swc/core
```
I expected to see a few compiled binaries in node_modules/.bin folder as advertised on the https://swc.rs website.
Is there a way to get just the required binaries during installation.
thanks 

### Expected behavior

I expected to see a few compiled binaries in node_modules/.bin folder as advertised on the https://swc.rs website.

### Version

1.3.26

**Comment by kwonoj** [comment]
There are necessary dependencies to drive native bindings, e.g https://www.npmjs.com/package/@swc/cli?activeTab=dependencies so having some js dependency is expected.

**Comment by drnkwati** [comment]
Esbuild come with no extra node modules. The point of using rust programming language is to achieve speed and use less JavaScript. 
Are my missing something?

**Comment by kwonoj** [comment]
Esbuild doesn't bring dependency but have javascript in its pkg : https://unpkg.com/browse/esbuild@0.16.17/lib/

Esbuild and swc both uses javascript to properly bootstrap native binding and there is nothing wrong tonuse either bringing own javascript or 3rd party dependencies.

I'm not sure why you are looking for 0 javascript dependencies, but the core functionality and performance is achieved by native bindings suffeciently.

**Comment by drnkwati** [comment]
Esbuild has optional JavaScript only. The installation is very minimal and clean.

https://unpkg.com/browse/esbuild@0.16.17/package.json

I have been using it to bundle projects without those dependencies and it works great.

Either way, swc is a good project. I was just trying it out and the speed is impressive. 
Thumbs up to the team 👍
