### ISSUE TITLE
call parse_module() happen to infinite loop

### ISSUE THREAD

**Issue by zzq-191** [swc-project/swc#6832]
### Describe the bug

when i use parse_module() function to parse ant-design-4.12.2.zip_\ant-design-4.12.2\components\_util\__tests__\wave.test.js, the function happen to infinite loop and can't exit. ant-design-4.12.2.zip is a js component.

### Input code

```typescript
let mut parser = Parser::new(syntax, input, None);
let module = parser.parse_module();
```

### Expected behavior

don't happen to infinite loop and return ast data

### Version
swc_ecmascript = { version = "0.209.4", features = ["parser"] }
swc_common = "0.29.23"
swc = "0.241.6"
swc_atoms = "0.4.29"
swc_ecma_parser = "0.124.1"
swc_ecma_ast = "0.95.7"

**Comment by kdy1** [comment]
Please post the link to file at least

**Comment by zzq-191** [comment]
ant-design componnet link: https://github.com/ant-design/ant-design/releases/tag/4.21.2
target file path: components\_util\__tests__\wave.test.js
