### ISSUE TITLE
`span_to_source` is extremely inefficient for Wasm plugins

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#6852]
Instead of passing only a string, we send the whole `SourceFile` **twice**.

https://github.com/swc-project/swc/blob/1bf9b3777ef3b79376c4253cbf3c9f92a01dba0a/crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs#L130-L139

This makes `span_to_string` extremely slow when the input is large.

Found while working on https://github.com/swc-project/swc/issues/6404

**Comment by kwonoj** [comment]
ugh looks like caching attempt only local to host side, not skipping to sending to guest with serialization

https://github.com/swc-project/swc/blob/1bf9b3777ef3b79376c4253cbf3c9f92a01dba0a/crates/swc_plugin_runner/src/imported_fn/source_map.rs#L58

Probably better / correct way is skipping to include originalLoc if guest already allocated same sourceFile.
