### ISSUE TITLE
Implement transform-async-generator-functions / proposal-async-generator-functions

### ISSUE THREAD

**Issue by endercrest** [swc-project/swc#6856]
### Describe the feature

In
```js
async function* agf() {
  await 1;
  yield 2;
}
```

Out
```js
var _asyncGenerator = ...

let agf = (() => {
  var _ref = _asyncGenerator.wrap(function* () {
    yield _asyncGenerator.await(1);
    yield 2;
  });

  return function agf() {
    return _ref.apply(this, arguments);
  };
})();
```

### Babel plugin or link to the feature description

@babel/plugin-proposal-async-generator-functions

### Additional context

I stumbled onto [comparison-babel.md](https://github.com/swc-project/website/blob/087914e4cbb57d317d82b567dbe8c999a45f5751/docs/comparison-babel.md) that initially made me thought it was already supported. However, after trying to use it, that was not the case.

After doing some digging, I can see some of the very initial ground work for it is in place:
https://github.com/swc-project/swc/blob/ad8d043f1d75b2df5a5e2fe43fba1ec843d2fad4/crates/swc_ecma_transforms_base/src/feature.rs#L78
https://github.com/swc-project/swc/blob/ad8d043f1d75b2df5a5e2fe43fba1ec843d2fad4/crates/swc_ecma_preset_env/src/transform_data.rs#L97

However, it looks to still be in a list of TODOs.
https://github.com/swc-project/swc/blob/ad8d043f1d75b2df5a5e2fe43fba1ec843d2fad4/crates/swc_ecma_preset_env/src/lib.rs#L277

The babel variant is currently used by MeteorJS alongside their custom async/await transformer. The project that I am working on has since moved to swc and migrated over a custom variant of Metoer's async/await transformer. However, without this transfomer, we are not able to utilize async generators.

https://github.com/meteor/meteor/blob/0ee038b24b95b3a955cb3c9b18cdaec3b0f8f9fd/npm-packages/meteor-babel/options.js#L199

I would greatly appreciate any time and thought towards this.

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.28&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczP01JITE%2FT0FSo5uVSUKjMTM1JUTCyBrETyxMzSxQMgexaXi5eruT8vOIShcyS1CIFW4gWkCiIr5eXWlGioalXkpGap1GmYGunAFKbn5Oql5OfrlGmqUltZQDZhB0jwQAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSw7DIAwFr1J5zaLtIovcoYdAxImo%2BMkmVRHi7jWIKjvbb97IFd5sYK2QNDFSn7iErL%2BwAhqv2ZBNGZRgctq1Y2wKsqYDc0f4eX8sErsYGSegwNtg99JlJvpEyHxFOhzuTzZx%2Bbid%2FVAhl4TDuUC7HLNn%2BTXBTKfsGD6jMz4RPYS44U2a7QeuPz8U0wAAAA%3D%3D

It's already supported

**Comment by endercrest** [comment]
@kdy1 This seems to be implemented through `transform-async-to-generator`. Which also transforms non-generator async functions. So I think there is still a need for building out this transform separately.

https://play.swc.rs/?version=1.3.29&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczP01IoSS0u0dBUqOZSUKjMTM1JUTA0MrbmquXigilR0AIpMcKqJhHFMLBZxlCFieWJmSUKAUX5uZnFqXpFqcX5OWWpGkaaQH0AnYf%2FiYMAAAA%3D&config=H4sIAAAAAAAAA0WPQQrDMAwE%2F6JzAiXH%2FKEvKD0IRwkOtmQkpzQE%2F702uOQkMZpd0AW7OZgvSKhG2jY7OeMXZiAX0Zz6lGGoWkUrBqMyQEbdKDfFpsc01XMQMerCANGzX89W5iQmJbP7hLyFv1lqV5TlaOCCfKY6WyQK7wblLuphb89ud0D8aUnPLhxLxS%2FIimyraByxPuLGLONGTIpZFN6l%2FADzFiXO8QAAAA%3D%3D

**Comment by kdy1** [comment]
Can you file an issue?

**Comment by endercrest** [comment]
@kdy1 I think re-opening this issue would capture this. This issue is asking for `transform-async-generator-functions` to be implemented (which is separate from `transform-async-to-generator`).

**Comment by kdy1** [comment]
I don't think so, it's about splitting an existing pass

2023년 1월 27일 (금) 오전 3:27, Thomas Cordua-von Specht ***@***.***>님이
작성:
