### ISSUE TITLE
Bug in the minifier in 1.3.29

### ISSUE THREAD

**Issue by lukeapage** [swc-project/swc#6864]
### Describe the bug

We got integration test failures with a upgrade from 1.3.28 to 1.3.29

I can see that there are minified code differences, but its very hard to see what the problem is:

![image](https://user-images.githubusercontent.com/309321/215068656-75d96623-a0e4-4c0a-a01e-689c18c8d3c5.png)

### Input code

```typescript
I can work on a repro if you need it, but it will take some time, please let me know. I'll have a go after filing this issue, but I think you should consider reverting the probable cause commit until the bug is found as anyone upgrading could get bugs in production.
```

### Config

```json
N/A - no swcrc

We use these options


        compress: {
            // all are default values unless commented
            arguments: false,
            arrows: true,
            booleans: true,
            booleans_as_integers: false,
            collapse_vars: true,
            comparisons: true,
            computed_props: true,
            conditionals: true,
            dead_code: true, // defaults to false
            defaults: true,
            directives: true,
            drop_console: false,
            drop_debugger: false, // defaults to true
            ecma: 5,
            evaluate: true,
            global_defs: {},
            hoist_funs: false,
            hoist_props: true,
            hoist_vars: false,
            if_return: true,
            inline: true,
            join_vars: true,
            keep_classnames: true, // defaults to false
            keep_fargs: false,
            keep_infinity: false,
            loops: true,
            negate_iife: true,
            passes: 0,
            properties: true,
            pure_getters: ``,
            pure_funcs: [],
            reduce_funcs: false,
            reduce_vars: true,
            sequences: true,
            side_effects: true,
            switches: true,
            top_retain: ``,
            toplevel: true,
            typeofs: true,
            unsafe: false,
            unsafe_arrows: false,
            unsafe_comps: false,
            unsafe_Function: false,
            unsafe_math: false,
            unsafe_symbols: false,
            unsafe_methods: false,
            unsafe_proto: false,
            unsafe_regexp: false,
            unsafe_undefined: false,
            unused: true,
        },
        mangle: {
            // all defaults except keepClassnames/keepFnames which can be disabled for integration tests
            topLevel: true,
            keepClassNames: true,
            keepFnNames: true,
            keepPrivateProps: false,
            reserved: [],
        },
```
```


### Playground link

_No response_

### Expected behavior

Code to run as it did in 1.3.28

### Actual behavior

_No response_

### Version

1.3.29

### Additional context

_No response_

**Comment by kdy1** [comment]
A repro is required

**Comment by kdy1** [comment]
@Austaras Seems like https://github.com/swc-project/swc/pull/6850 is the cause

**Comment by Austaras** [comment]
Yes, seems like something is wrongly inlined. But it's really hard to infer what happened just from the screenshot

**Comment by Austaras** [comment]
If a reduced report is hard, the whole generated JS file(before and after upgrade) is fine too.

**Comment by lukeapage** [comment]
am looking into trying to make a repro.

**Comment by lukeapage** [comment]
Here is a repro:

https://play.swc.rs/?version=1.3.29&code=H4sIAAAAAAAAA31STWuDQBC9F%2FofpjcFkabHpAZ6aKGHUAi9iQQbx2RBZ8u6RqXxv3fdNbqatJ7c8X3NW7H%2B5kJCWtJeMk4gMOcnfBM838RSsNq5vwP15PqwhC3GCaeseREibp6np0JB6LBee4bCkiWYkRq48GOmp1gAYbXp9f7TWY0MRgnWH%2Bl78sm3OuASqMy%2FUCjMiBK8mifstSCAnZ8qFccs4oGDJEXjGWUXgvUloI6egrPzGe2zMsFigCaua6M0ch5MOenZaooTKEtBoJWsT615bd1hj876QS0ycerZJntPb22GIvgZ0kEeIQgCWEzYQ926hYrJIy%2FlUETnNbhf9AZK%2BBjZwk9XBew5FbL7a2JGqunXbkHlYwvMqrDjhOGUqdCRB%2FPhIoqiG6UBZgX%2BtWjo%2B75Z0aaOsa4uLpq0o1rRFz4vu7%2BJ0el8Hq%2Bl%2FQVQDhftTQMAAA%3D%3D&config=H4sIAAAAAAAAA42UwZLbIAyG34VzDtscOp08QG99BoYY4bDFyIOEN55M3r3CdiBO9tAbfEjiR%2Frtm%2FqkTp1uajSJIJUVzZHNVZ0UzyNQl%2FzI6qCYBHHKcJe1ST2wRAAdP45HOQ2IBOrkTCA4qMFH7%2BZSq8NhTEBU1pKUB4hMNc6khF%2B0lj2oM2IAE9%2F22pD2kaGH1FI7DMGMBHoyqWaU20zyhHGHMoPVY8LxiUbr2WOUYg9mwVjdoYUKfIKO%2FQQtRGpISCQRVpUs0MI5933p3xoJkwnZcK0F16UNcmPNu6An1i5HekE7pStaH7lFeacTcE7xEfOJPu768BdAdAZDFM0ALXPhTuawj3TfRPnoZIg8VyoTbqoi9PI47b2rLyyqIbFv3UpgcwflhV0rvsHdg8hb0OCcdLsm05fn7tKKFS%2Biq1vpmnFtButWP%2Fy0p8UCb%2FC3qOLncWx8MHx5ZTQPZwxvJQbgC9o3LI1gfIVJ3HsdX2mOFqTNYJ8OMpVttakMn1GH8rU9%2BiyGkBzdBzxX%2B8pHOZjYF1veFOMYYILwf3b4hskdU5nv5sSH7%2BBXG5kRG%2FkfHxu434sAtHkTIMNa%2Fg4%2F1b39DVYxnv5scYvufx0FfaCABAAA

after running the output through prettier:

1.3.28:
```
export function removeFromMatrix(t, e) {
  var r,
    i,
    n = _.find(t, (t, r) => {
      if (_.includes(t, e)) return (i = r), t;
    });
  if (!n) return t;
  if (1 === n.length) {
    if (2 === (r = _.without(t, n))[0].length) {
      let t = r[0];
      r = [[t[0]], [t[1]]];
    }
  } else (r = [...t])[i] = _.without(n, e);
  return r || t;
}
```
1.3.29:
```
export function removeFromMatrix(t, e) {
  var r,
    i = _.find(t, (t, r) => {
      if (_.includes(t, e)) return t;
    });
  if (!i) return t;
  if (1 === i.length) {
    if (2 === (r = _.without(t, i))[0].length) {
      let t = r[0];
      r = [[t[0]], [t[1]]];
    }
  } else (r = [...t])[r] = _.without(i, e);
  return r || t;
}
```

It loses the i = r assignment inside the function:
![image](https://user-images.githubusercontent.com/309321/215080396-df5c21f9-d178-4ce0-86a0-ff14eed46f63.png)

**Comment by kdy1** [comment]
@Austaras Will you work on it? If not, I'll work on this and publish a new version.
(I'm asking this just to prevent duplicate work)

**Comment by Austaras** [comment]
I'm currently working on it.

**Comment by kdy1** [comment]
Thank you so much!
