### ISSUE TITLE
call parse_module() happen to infinite loop when parse ant-design-4.12.2\components_util_tests_\wave.test.js

### ISSUE THREAD

**Issue by zzq-191** [swc-project/swc#6874]
### Describe the bug

when i use parse_module() function to parse ant-design-4.12.2.zip\ant-design-4.12.2\components_util_tests_\wave.test.js, the function happen to infinite loop and can't exit.

ant-design componnet link: https://github.com/ant-design/ant-design/releases/tag/4.21.2
target file path: components_util_tests_\wave.test.js

### Input code

```typescript
let mut parser = Parser::new(syntax, input, None);
let module = parser.parse_module();
```

### Expected behavior

return ast data object.

### Actual behavior

can't exist from parse_module() and happen to infinite loop.

### Version

swc_ecmascript = { version = "0.213.7", features = ["parser"] } swc_common = "0.29.23" anyhow = "1.0.38" serde_json = "1.0.66" serde = "1.0.127" swc = "0.245.7" swc_atoms = "0.4.29" swc_ecma_parser = "0.124.1" swc_ecma_ast = "0.96.1"

### Additional context

post target file link information.

**Comment by kdy1** [comment]
Please post the file

**Comment by kdy1** [comment]
![Uploading image.png…]()
