### ISSUE TITLE
hoisting bug

### ISSUE THREAD

**Issue by kapouer** [swc-project/swc#688]
In @swc/core 1.1.28,
```
function test() {
  if (typeof Missing == typeof EXTENDS) {
    console.log("missing")
  }
  var EXTENDS = "test";
}
```

is compiled as

```
function test() {
    if (typeof Missing == typeof EXTENDS) {
        console.log('missing');
    }
    var EXTENDS1 = 'test';
}
```

But this is what is expected:
```
function test() {
    if (typeof Missing == typeof EXTENDS) {
        console.log('missing');
    }
    var EXTENDS = 'test';
}
```

Or this, which is better style:
```
function test() {
    var EXTENDS;
    if (typeof Missing == typeof EXTENDS) {
        console.log('missing');
    }
    EXTENDS = 'test';
}
```

**Comment by thecotne** [comment]
@kapouer this example functions don't demonstrate any actual problem since all 4 of them print "missing" in console (i have only tested in chrome)

in the example below `before` is printing `missing` and `after` will throw `Uncaught ReferenceError: EXTENDS is not defined`

```js
function before() {
  if ((void 0) === EXTENDS) {
    console.log("missing")
  }
  var EXTENDS = "test";
}
function after() {
  if ((void 0) === EXTENDS) {
    console.log("missing")
  }
  var EXTENDS1 = "test";
}
```

**Comment by kapouer** [comment]
@thecotne indeed the first function does not print anything useful, it's just an example that is not compiled according to spec (the variable shouldn't be renamed).
