### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jantoine1** [swc-project/swc#6881]
### Describe the bug

After updating from 1.3.30 to 1.3.31, running the following command results in a "segmentation fault (core dumped)" error:
`swc src -d dist --only src/**/*.ts,src/**/*.tsx --source-maps inline`. I've tried to get an error message by passing the --sync option, but it doesn't produce any additional output. I've also tried setting the SWC_DEBUG environment variable to 1, but I'm not seeing  a backtrace being output to stdout or to a file in the working directory, but I may not be setting this correctly so that "swc" is getting it. I'll continue working on this.

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2017"
  },
  "module": {
    "type": "commonjs",
 
    // These are defaults.
    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  }
}
```

### Expected behavior

The same result I get with v1.3.30:
`Successfully compiled: 50 files with swc (20.5ms)`

### Actual behavior

After updating "@swc/core" to v1.3.31, I no longer get a successful message and instead receive the following:
`Segmentation fault (core dumped)`

### Version

1.3.31

### Additional context

~~This is only occurring in one out of about 20 modules, all with their own unique, so I'm guessing it has something to do with the specific dependencies of this module.~~
This is occurring on most modules which are part of a larger project with shared peer dependencies.

**Comment by kwonoj** [comment]
We need either dump itself or reproducible inputs.

**Comment by Brooooooklyn** [comment]
@jantoine1 could you please provide your system information as well, like `CPU` and `Operation System (with version)` kernel version etc?

**Comment by gillycheesesteak** [comment]
I am also having this issue on an Apple Silicon M1 MacBook Pro:
System Version: macOS 13.0 (22A380)
Kernel Version: Darwin 22.1.0

**Comment by jantoine1** [comment]
@kwonoj

My initial post was incorrect. This is occurring across most of my modules. The 1.3.31 release occurred as I was working towards the end of my build process, so it was the last module that installed it. I'll work on a reproducible module.

@Brooooooklyn

I am building using the official Node v16.13.1 docker image which uses Debian Buster. I could upgrade to the latest 16.19 or move up to 18 and test there.

CPU: i7-10700
Memory: 16GB DDR4
