### ISSUE TITLE
setTimeout in async functions doesn't work properly

### ISSUE THREAD

**Issue by Yoskutik** [swc-project/swc#6898]
### Describe the bug

I tried to run a loop in an asynchronous function. In each iteration of the loop I created a variable using keyword `const`. Then I called `setTimeout` and created a function, that logs the created variable. According to EcmaScript standard each function must have different variables, because they were declared using `const`. But SWC generated in the way so every function logs a variable that was created on the last iteration.

### Input code

```typescript
(async () => {
  const arr = [
    'value1',
    'value2',
    'value3',
  ];

  // for (const value of arr) {
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    setTimeout(() => {
      console.log('value', value);
    }, 0);
  }
})();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es5",
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "env": {
    "targets": "> 0.25%"
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.32&code=H4sIAAAAAAAAA1WOzQrCMBCE73mKuSWhoa16rPUpvBUPoaS1EBNIU0Ek725%2BKOpld4fZ%2FXaYXF9mBOPoL3gTYLRm9ZDOoccQNUCfUm%2FqQMWPOv6pU1a3jsTaNJisAyucbMNOCcgzP5taeSzxQdvFdk5mrZWZ%2FT3qqiqLe5SC6NPSsMQfyVmVvy4PZTfPvsn3E6tVre3MSjYqCoGXyyDQ5jGQwBnvPoOX9uoAAQAA&config=H4sIAAAAAAAAAzWMQQrDMAwEv1IWeguhBHzxoX8RRgkusWskExpC%2Fh4LpzetdnYOfDTAHygkymKX7rnSDx4cEmmQWCrOAZVk4WpvdRiQYo7zbnz4piKsCj%2FTqtwqysvKdzzblPNmYDc0Du%2FHa5zc07R%2FT4cv3NlLNY8AAAA%3D

### Expected behavior

Will output 

```
value value1
value value2
value value3
```

### Actual behavior

Outputs

```
value value3
value value3
value value3
```

### Version

1.3.32

**Comment by kdy1** [comment]
I investigated this, and this only happens for preset-env mode. I think I know the solution, so I'll try.
