### ISSUE TITLE
swc rust cli incorrectly strips imports with leading underscore

### ISSUE THREAD

**Issue by Aghassi** [swc-project/swc#6923]
### Describe the bug

Between versions `1.3.23` (node binary) and `1.3.34`(rust binary), the following syntax broke for us

```js
import { _Component } from './Component'

/** react code **/

<_Component> </Component>
```

### Input code

```typescript
import React from 'react'
import ReactDOM from 'react-dom'
import {_Component} from './Component'

const App = (
  <div>
    <_Component></_Component>
    <p>Hello World</p>
  </div>
)
ReactDOM.render(App, window.document.getElementById('react_root'))
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.34&code=H4sIAAAAAAAAA01OSwrCMBDd5xSzSwuaXCAW%2FIEuRHDjskgTJZBkwhgtIt7d1Grtat68H8%2F6iJTgYE5NgjOhB04d5syOlNV%2BNxanGv1geNZLzCiYkF5fk5ADxRlrMFwTzGOEGRQMQGl7r%2FLN6B%2BtlBw9vRqrjXEO4YjktJKxo5X8pEv22yXIBG2oyP0TaG3Q2AqNzc3nHnExae1MBxePrS769TUhJl6W7A3j3dx5%2FAAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1FiGLLnyHHsK4SnDxD0mBGuO7VzYJ2Q0zo6dp8GUHpkGxxEhDcU1if2BAakF25IvAAsJqCZ3YVVs6ULSBvK3bqmnImRHMbgPjAtEnv9fBcjkWQuYnsukId7MrK%2BbPOYw2303mC%2FrDuO48v6%2Fi3PAHuM3Ro7cAAAA%3D

### Expected behavior

This should transpile appropriately and be referenced as dot notation on the object being imported instead of having the import stripped out completely and still referenced.

### Actual behavior

The import line is removed, but the object is still referenced, leading to an undefined object.

### Version

1.3.34

**Comment by Aghassi** [comment]
Some additional context, here is a picture of the diff I'm seeing internally on code that is now broken when trying to upgrade 
Source code: 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/3680126/217887624-43d1adb1-1745-4808-8439-5c8d98f7521e.png">
 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/3680126/217887709-7f628d26-a9b9-4851-8f42-8f0456dd22a6.png">


Transpiled code (diff):
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/3680126/217887515-bf2d91ae-d4dc-4358-9405-d91895c7d35c.png">

![image](https://user-images.githubusercontent.com/3680126/217887262-a0109791-0b48-496a-aef8-8936b4e88bf3.png)

**Comment by Aghassi** [comment]
I'm using `rules_swc` so I'm curious if maybe there is a config layering issue, I will add more info here as I dig

**Comment by mattem** [comment]
Perhaps ee3a1071a5dbe0f2b718dd4f2e9959076cfa337c changed the way SWC visits jsx elements and only considers those that start with an uppercase ansii character? Changing the repro to also start with a lower case breaks it too. Works in 1.3.32.

**Comment by kdy1** [comment]
Oh I think it's correct, I didn't know that `_` is a valid prefix for jsx components.
I'll fix it right away and publish a new version.

**Comment by Aghassi** [comment]
Thanks for the fix @kdy1 ! Looking forward to the new version when it publishes!

**Comment by kdy1** [comment]
It's published I think

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/releases/tag/v1.3.35
