### ISSUE TITLE
[@swc/plugin-emotion] a comment in styled-components affects lines below the comment.

### ISSUE THREAD

**Issue by jlee0425** [swc-project/swc#6925]
### Describe the bug

I have project setup with`@emotion/styled`, `craco` and I'm trying to adapt `swc-loader` in my project.
While doing so, I found a couple of bugs in `@swc/plugin-emotion`:
1. `labelFormat` includes `filename` breaks the whole styling.
2. `comments` in styled components affect the styles below the comment(not commented) and they gets ignored as well.

### Input code

```typescript
export const IconWrapper = styled.span`
  width: 30px;
  height: 30px;

  position: absolute;
  //top: 50%;
  top: 389px;
  right: -15px;

  cursor: pointer;
`;
```

### Config

```javascript
{
      test: /\.(js|mjs|jsx|ts|tsx)$/,
      include: paths.appSrc, // `src` folder in cwd
      loader: require.resolve('swc-loader'),
      options: options: {
          jsc: {
            target: 'es5',
            externalHelpers: true,
            parser: {
              syntax: 'typescript',
              tsx: true,
              dynamicImport: true,
            },
            transform: {
              react: {
                runtime: 'automatic',
              },
            },
            experimental: {
              plugins: [
                // disable plugin in production due to `failed to invoke` error in production build
                isEnvProduction || [
                  '@swc/plugin-emotion',
                  {
                    sourceMap: true,
                    autoLabel: 'dev-only',
                    labelFormat: '[local]',
                  },
                ],
              ].filter(Boolean),
            },
          },
        },
    }
```

### Expected behavior

Comments only affect the lines that are commented, not affecting any other line.
Expected CSS(I deleted commented lines):
<img width="182" alt="image" src="https://user-images.githubusercontent.com/40153724/217975629-507cbfc7-f91e-4e99-add7-d426f20071b8.png">

### Actual behavior

Comments in a line in between styles affect the line below the comment.

Actual CSS(with a comment):
<img width="205" alt="스크린샷 2023-02-10 오전 10 13 49" src="https://user-images.githubusercontent.com/40153724/217975355-46f4c045-3edd-4941-96b6-4f9bf1642607.png">

### Version

"@swc/core": "1.3.34", 
"@swc/helpers": "0.4.14",     
"swc-loader": "0.2.3",     
"@swc/plugin-emotion": "2.5.41",

**Comment by mintplo** [comment]
Same Problem Here.

```
.delayed-activation-button-progress {
  position: absolute;
  top: 0;
  left: 0;
  width: 0;
  height: 100%;
  z-index: 2;
  background: rgba(0, 0, 0, 0.2);
  border-radius: 5px;
  transform: translateZ(0); // GPU Acceleration Target
}

.animate-delayed-button-progress {
  animation: button-progress 1500ms;
  animation-delay: 200ms;
  animation-timing-function: linear;
}
```

the style after `// GPU Acceleration Target` comment line is ignored.

**Comment by Codex-** [comment]
Oh neat, I fixed this bug:
- https://github.com/swc-project/plugins/pull/154
- https://github.com/swc-project/plugins/pull/155
- https://github.com/swc-project/plugins/pull/156

Can you test if this is still an issue for you? :)

**Comment by jlee0425** [comment]
@kdy1 cc. @Codex- 
Could you close the issue if they have been fixed and merged?
I would like to also know if they are published and if so, a link to the version it's shipped on would be perfect.

**Comment by Codex-** [comment]
The latest version of `@swc/plugin-emotion` `2.5.48` includes the changes required.

I'm not an `@swc-project` member, just a pr contributor, so cannot close issues. As you're the author of this issue, if you can confirm this has been resolved for you then you can close the issue

**Comment by kdy1** [comment]
@Codex- 
Thank you!
