### ISSUE TITLE
Minifier should not drop `new` for `RegExp`

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#6941]
### Describe the bug

I'm not sure if this is important, though.

Reported by https://github.com/vercel/next.js/discussions/30237#discussioncomment-4961296

### Input code

```typescript
const pattern = /[abc]+/g;

const instance1 = RegExp(pattern);
const instance2 = new RegExp(pattern);

instance1 === pattern // true
instance 2 === pattern // false
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.35&code=H4sIAAAAAAAAA0vOzysuUShILClJLcpTsFXQj05MSo7V1k%2B35uJKBstlAonEvORUQ6BsUGq6a0WBBlS5pjWaEiOgkrzUckxlXEiG2NrCrdPXVygpKk2FyyoYoUunJeYUpwIAjgX8hqQAAAA%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1FiGLLnyHHsK4SnDxD0mBGuO7VzYJ2Q0zo6dp8GUHpkGxxEhDcU1if2BAakF25IvAAsJqCZ3YVVs6ULSBvK3bqmnImRHMbgPjAtEnv9fBcjkWQuYnsukId7MrK%2BbPOYw2303mC%2FrDuO48v6%2Fi3PAHuM3Ro7cAAAA%3D

### Expected behavior

It should pass

### Version

1.3.35

**Comment by andersk** [comment]
Based on the comment at https://github.com/swc-project/swc/commit/594089488b8b3498d59fb8e07c518ef2071d83bb#diff-671927f9f8892091ded45850d4642521fa87cd1b0ee1aba677ca7739aed217e9R252-R253, this optimization seems to have been motivated by the following sentence in the ECMAScript specification:

> Thus the function call `RegExp(…)` is equivalent to the object creation expression `new RegExp(…)` with the same arguments.

However, I think that sentence is wrong. It contradicts the detailed steps in the following section of the specification, as well as the empirical behavior of JavaScriptCore, SpiderMonkey, and V8:

```js
> r = /a/;
/a/
> RegExp(r) === r
true
> new RegExp(r) === r
false
```

I’ve opened a thread at https://es.discourse.group/t/is-regexp-really-equivalent-to-new-regexp/1637 to ask about the spec contradiction, but I think this optimization for `new RegExp(…)` needs to be removed.

Cc @magic-akari (#4932).
