### ISSUE TITLE
Missing parentheses in CommonJS output

### ISSUE THREAD

**Issue by cherreratapia** [swc-project/swc#6948]
### Describe the bug

When transpiling code from TS to JS with SWC with CommonJS target.
You can see how SWC removes parentheses from a condition, that could led to unexpected behaviour in runtime.

### Input code

```typescript
const a: boolean = true;
const b: boolean = true;
const c: boolean = false;

const condition: boolean = a || (b & c);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "minify": {
      "compress": false,
      "mangle": false
    },
    "loose": false
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
}
```

### Playground link

https://play.swc.rs/?version=1.3.35&code=H4sIAAAAAAAAA0vOzysuUUi0UkjKz89JTcxTsFUoKSpNteZKBksk4ZJIRpZIS8wpBsrApPLzUjJLMvPzkJUkKtTUKGgkKagpJGtacwEAc3qVc3YAAAA%3D&config=H4sIAAAAAAAAA02NwQ7DIAxD%2FyXnHSaO%2FYd9BGJpRQcBYaoNIf59YarU3eLYfu60w9HSKdsCLvNCk2o%2FtFBtmeGKz5VuVKGv1QbwUGHLxlUjDHM3Ru3oxa9t1l2KuTBwptWysgW%2ByiEl%2FMmYnse0%2B29PmQqISXbQuLAnyuNxpumQl6S30PgC4Nd%2BgcIAAAA%3D

### Expected behavior

I'd expect this to be as the [TS output](https://www.typescriptlang.org/play?ts=4.9.5#code/MYewdgzgLgBAhgLhgIxCANgUzmGBeGKAJwFdMBuAKFElmSVQ21wOLKpuhmAbSx3wwAZnHQQKlauC40AJgEso88LyYCCcGAB8tMABTIYAMm4BKKkA) that maintain the parentheses 

```javascript
const a = true;
const b = true;
const c = false;
const condition = a || (b & c);
```

### Actual behavior

Missing parentheses in the condition
```javascript 
const a = true;
const b = true;
const c = false;
const condition = a || b & c;
```

### Version

1.3.35

**Comment by korobochka** [comment]
I'd like to emphasise that without parens expression semantics changes, resulting in different runtime behaviour.
We've checked different versions of swc in playground and different options, all seem to have this issue, so it's not a recent regression.

**Comment by magic-akari** [comment]
I think it works as expected.
This behavior is not related to TypeScript or CommonJS.

It's a safe transform, and Babel does the same thing.
https://babeljs.io/repl/#?code_lz=IYAgPmIBQEYgZPEBjAlAbiA

**Comment by korobochka** [comment]
You are right, sorry for spam 🤕 
Please close the issue.

```
let res = [];
for(const a of [true, false]) for(const b of [true, false]) for(const c of [true, false]) res.push(a || (b && c))
console.log(res)
```
[true, true, true, true, true, false, false, false]

```
let res = [];
for(const a of [true, false]) for(const b of [true, false]) for(const c of [true, false]) res.push(a || b && c)
console.log(res)
```
[true, true, true, true, true, false, false, false]
