### ISSUE TITLE
Source maps are wrong when using sourceMaps="inline"

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#6955]
### Describe the bug

We're running our mocha tests using `swc-register` and we had `sourceMaps: "inline"` - since I thought that would make sense for running unit tests. I have just realised (and it took me probably 1 year to do so) that source maps aren't working correctly for nearly all files in the project. I then switched sourceMaps setting to `sourceMaps: true` and the source maps are correct now - ie they point to the right lines in the original source code.

### Config

```json
{
  "env": {
    "targets": {
      "node": "19.0"
    }
  },
  "jsc": {
    "target": "es2019",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": "inline" | true
}
```

### Expected behavior

1. Source maps generated with `sourceMaps: "inline"` should be correct, whereas at the moment they point to the wrong lines in an original file.
2. I also believe that source maps generated with `sourceMaps: "inline"` and `sourceMaps: true` should be identical.

### Version

1.3.35

**Comment by kdy1** [comment]
Closing as there's no workable thing
