### ISSUE TITLE
jsc.target is ignored when env is specified

### ISSUE THREAD

**Issue by quolpr** [swc-project/swc#6956]
### Describe the bug

When I specify `mode` & `coreJs` in `env` swc ignores `jsc.target`. You can test it my removing/adding `env` in config in playground

### Input code

```typescript
const foo = {};
foo?.bar.baz?.()
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "importMeta": true
    },
    "transform": {
      "react": {
        "refresh": true
      }
    },
    "target": "es2019",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "mode": "entry"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.31&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVaiuteYCsuz1khKLgLjKXk9DEwBsEhSNIAAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSw7CMAxE7%2BJ1F8ACid6hh7CCC0HNR7aLiKrcnbi0dGd55j3NAi9x0C%2BQkYXYLilR8QM9aMkkjn1W6EClvUachDrwISfWgRShV56ptpgxypg4mIEJnf6OkUmeW8tqyA9qEZBcTudb804pCf3NwUc%2FFkNdCrmxckQYH9PeNFdI99keyzp0dV6hHo59rAxb0UZ0QPFtTKNXJioXqPULJiXVeAgBAAA%3D

### Expected behavior

Output should be

```
var _foo_bar, _foo_bar_baz, _ref;
const foo = {};
(_foo_bar_baz = (_ref = _foo_bar = foo === null || foo === void 0 ? void 0 : foo.bar) === null || _ref === void 0 ? void 0 : _ref.baz) === null || _foo_bar_baz === void 0 ? void 0 : _foo_bar_baz.call(_foo_bar);
```

### Actual behavior

Output

```
const foo = {};
foo?.bar.baz?.()
```

### Version

1.3.31

**Comment by quolpr** [comment]
Update: I noticed that the behavior is the same even if I set empty object to env: `env: {}`

**Comment by mintplo** [comment]
Same Here Problem.

- env is set up (
- jsc.target is set up (`target: es5`)

jsc.target is ignored

**Comment by kdy1** [comment]
This is intentional, but I think we need to throw an exception for the wrong config.
