### ISSUE TITLE
Dead loop parser if parse jsx content as normal js.

### ISSUE THREAD

**Issue by underfin** [swc-project/swc#6961]
### Describe the bug

The swc parser will dead loop at parser jsx content using js syntax, it should be a print syntax error.

### Input code

```typescript
export default function ViewItemLabel(props) {
            const labelContent = <Text color="dark-gray">1</Text>;
            if (fieldLabelPlacement === 'top') return <Label>{labelContent}</Label>;
            return <Label>{labelContent}</Label>;
          }
```

### Expected behavior

Should be print syntax error.

### Actual behavior

Dead loop, the program isn't exit.

### Version

master code

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/issues/7189
