### ISSUE TITLE
legacy decorators with decorate before exports makes bugs

### ISSUE THREAD

**Issue by ben-lau** [swc-project/swc#6984]
### Describe the bug

When I use the legacy decorator while using the esm default export, swc will transform the code be like this:

![image](https://user-images.githubusercontent.com/16952163/221106882-32b25986-8d2f-4579-af53-50068469ca6a.png)
Then when running the code, an error will be reported: Uncaught ReferenceError: App is not defined.

**I think the decorate method should be executed inside the iife.**

### Input code
```javascript

import React from 'react'
import { withRouter } from 'react-router-dom'

export default
@withRouter
class App extends React.Component {
    render() {
        console.log(this.props)
        return <div>134</div>
    }
}
```

### Config
```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "decorators": true,
      "dynamicImport": true,
      "decoratorsBeforeExport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "minify": {
      "compress": false
    }
  },
  "isModule": "unknown",
  "env": {
    "mode": "usage",
    "coreJs": "3",
    "dynamicImport": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA02NwQ6CQAxE7%2F2K3sADGKNHYjT%2BAX9A2CKbLNtNtyiJ4d9dwKhzms6bZuwQWBRralrFTnjATBafgd3IC59W%2B5pHJcH5v1LIGhaGhwyAprVuqGtGp3D5fUHrmhjxGgLSpORN3ObKG6cJTz6NACZJYiT57nMuatlHdlQ6vufa21gG4RB3Xy6ko3isjH2cD8dTtV%2FMSmeY4Q2v7l5S3QAAAA%3D%3D&config=H4sIAAAAAAAAA22PvW7DQAyD30Wzt24egxRIC%2BQhhDs6uPb%2BIMmtjcDvHjlAmiFdSX6UeKUvDTReCYtBKucTcocojSYzBuosCtkDulbjhUZCKKxBUjcanF4e0YjQhK094bhWLil8lN7EXmMHTE3wvjzdbSATrup62W9mXDisxwfxUnGGcWTjP7qkmqZ1R0MrXaD%2By8RZsbmZ9NzinOEb5vpd22%2F1Aag%2Fe7y0eNeVL3DV%2B%2FHpLL3RvzO27QYUx7KWOQEAAA%3D%3D

### Expected behavior

 The class should be correctly decorated before exporting

### Actual behavior

The decorate method call with using the no define class, then make an error: Uncaught ReferenceError: App is not defined.

### Version

1.3.36

**Comment by ben-lau** [comment]
@kdy1 hello, why remove this from the `Planned`? Is it be resolved?

**Comment by kdy1** [comment]
Because I'll never work on this

**Comment by ben-lau** [comment]
why? It's not a bug or any other reason?

**Comment by magic-akari** [comment]
The following codes is parsed as `ExportDefaultExpression` in swc.

```JavaScript
export default
@dec
class App { }
```

And the following is parsed as `ExportDefaultDeclaration`.

```JavaScript
@dec
export default
class App { }
```

Is this expected? @kdy1

**Comment by kdy1** [comment]
Umm... No, I don't think so.
Both should be export default expr I guess

**Comment by magic-akari** [comment]
> Umm... No, I don't think so. Both should be export default expr I guess

I think they should be `ExportDefaultDeclaration`, since you can use `App` in the same file.

**Comment by kdy1** [comment]
Makes sense. I think you are right
