### ISSUE TITLE
Wrong loop variable scope when destructuring is used

### ISSUE THREAD

**Issue by Knagis** [swc-project/swc#6988]
### Describe the bug

With ES2017 target (when object destructuring requires a helper function), loop variables get emitted with `var` instead of `const`, breaking their scoping within callbacks.

### Input code

```typescript
for (const a of [1,2,3]) {
    const { ...rest } = {};
    setTimeout(() => { console.log(a) });
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2017",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vLL1LQSM7PKy5RSFTIT1OINtQx0jGO1VSo5uVSAAKIVLWCnp5eUSqQVatgq1Bdaw2RLE4tCcnMTc0vLdHQ0FSwtQOqA6nPz0nVy8lP10jUVKjVBCqt5eUCAARxsoRnAAAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1Fm0XLfgOPYRwleDgH5ICNcZ3r21SshtmRk9TYRcLpkJGFuKhpETFLxjQkkksu6ywgEq3lA9qXSNvpL1B8rjdXz31KQmBWdELLRBcdGsZLJtCZhK5Ioyb%2FzdbZ4X0OYZR57vJfEK7GOedk%2FdZnBt%2BFe0Yj7cAAAA%3D

### Expected behavior

```
for (const a of [1, 2, 3]){
    const rest = _extends({}, _objectDestructuringEmpty({}));
    setTimeout(()=>{
        console.log(a);
    });
}
```

### Actual behavior

```
for (const _ref of [1, 2, 3]){
    var a = _ref;
    const rest = _extends({}, _objectDestructuringEmpty({}));
    setTimeout(()=>{
        console.log(a);
    });
}
```

### Version

1.3.36

### Additional context

Really nasty bug :(

**Comment by kdy1** [comment]
Closing as dup

**Comment by kdy1** [comment]
Not sure if destructuring was used in original issue
