### ISSUE TITLE
Can't specify core-js specific version

### ISSUE THREAD

**Issue by quolpr** [swc-project/swc#6995]
### Describe the bug

In the doc it mentions that you can specify `core-js` specific version:
<img width="1461" alt="Screenshot 2023-03-01 at 23 33 22" src="https://user-images.githubusercontent.com/7958527/222263595-bfc5a1ec-ae89-46f0-a001-8d400549afdd.png">

But if I do so, then all `core-js` imports will be imported. And, also, playground will be showing config error that only number can be passed:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/7958527/222263911-737e011c-7f43-41bb-8acf-f8257ffbc896.png">

### Playground link

https://play.swc.rs/?version=1.3.37&code=H4sIAAAAAAAAA8vMLcgvKlFQT84vStXNKla35uJKzs8rLlFILCpSsFWIjgUKAJl6BaXFGRpGxpoAkcK9%2BTAAAAA%3D&config=H4sIAAAAAAAAA0WOawrCMBCEryL7uxSt4KNHEDxEiNsaaR7sbsVQeneT2Np%2FszszHzPBizW0EwRFjJQVRyfqAy1IDMiaTBCoQDi9OjUwVmBs8CR3FAWt0Ihzskk57jzZTCBUWn6iI%2BTnksoxRT0mC5Cb%2FeGSuIP3jH%2ByNc50MVe1tyF1ebOU64c1mVnWP8b8mMrQwjzBvDHWsXxfgnlEBejepVOWJDywcRp3ac4VCrSgnFBMp%2FaEtxw61s25bmCevx%2FxGDExAQAA

You can notice that it includes imports that already are in all browsers since 2019 (my env target), like:
> import "core-js/modules/es.array.push.js";

### Expected behavior

Even with specific version, swc should import only needed core-js imports or doc should be changed.

### Version

1.3.37

### Additional context

Here is the case when I'm specifying core-js as just `3` — https://play.swc.rs/?version=1.3.37&code=H4sIAAAAAAAAA8vMLcgvKlFQT84vStXNKla35uJKzs8rLlFILCpSsFWIjgUKAJl6BaXFGRpGxpoAkcK9%2BTAAAAA%3D&config=H4sIAAAAAAAAA0WOSw7CMAxEr4K87oKPhKBHQOohouCUoOYj2yCqqnfHCS3djT0zTzPBky20E2RDjFQUj1HMB1qQMSNb8lmgAWF9OTMwNuBDTiQdioFW6IWz2mQiu0ShEAiNlZ9whPxYUiVmqEe1APm4P1yUO6TE%2BCcHH70bS9WmkLXLm2ViP6zJwgrp%2FiqPqQ6tzDPMG2Mdy90SLCMawPiunbpE8cA%2BWtzpnCtUaEVFoVFPmwhvGjrN8xdHTE0JKgEAAA%3D%3D , and it works correctly

**Comment by kdy1** [comment]
The doc is correct. This is a problem of schema
