### ISSUE TITLE
Invalid emitted code when using optional chaining twice.

### ISSUE THREAD

**Issue by joac** [swc-project/swc#7003]
### Describe the bug

I found that code using [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) twice don't work as expected.

Given the following snippet:
```typescript
const a = ["hello", "world"];

a.filter?.((a) => true).map?.((a) => console.log(a));
```
I expect after running `scw --no-swcrc reproducer.ts -o reproducer.js && node reproducer.js` to have:
```
hello
world
```
As an output.
But the code generated don't work as expected.
```javascript
var _a_filter, _a_filter_map, _a_filter1;
var a = [
    "hello",
    "world"
];
(_a_filter_map = _a_filter = (_a_filter1 = a.filter) === null || _a_filter1 === void 0 ? void 0 : _a_filter1.call(a, function(a) {
    return true;
}).map) === null || _a_filter_map === void 0 ? void 0 : _a_filter_map.call(_a_filter, function(a) {
    return console.log(a);
});
```
If I use `tsc` I get:

```js
"use strict";
var _a, _b, _c;
const a = ["hello", "world"];
(_c = (_a = a.filter) === null || _a === void 0 ? void 0 : (_b = _a.call(a, (a) => true)).map) === null || _c === void 0 ? void 0 : _c.call(_b, (a) => console.log(a));
```
That works as expected.

### Input code

```typescript
const a = ["hello", "world"];

a.filter?.((a) => true).map?.((a) => console.log(a));
```

### Playground link

https://play.swc.rs/?version=1.3.37&code=H4sIAAAAAAAAA0vOzysuUUhUsFWIVspIzcnJV9JRUCrPL8pJUYq15uJK1EvLzClJLbLX09BI1FSwtVMoKSpN1dTLTSxACCUDzcjPSdXLyU8HimhaAwCkjiqEVAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1tt3kDj2ESZXg4B8aBWqM7165OGQnzedNoxMbrY2KE7CMCzWp%2B9JKWgtjE1%2BUFlKYtLsA7vY4OVgtwniZF3IGT3eh6JPf6yBtORZh4LFcOsKd7AaK%2BXMNof3HDGiVmNMJ6g9olj3eM61ycf8BnwbyVboAAAA%3D

### Expected behavior

I expect after running `scw --no-swcrc reproducer.ts -o reproducer.js && node reproducer.js` to have:
```
hello
world
```

### Actual behavior

No output

### Version

1.3.37

**Comment by jridgewell** [comment]
Looks like we're missing some quotes around the assignment:

```diff
--- A
+++ B
@@ -3,9 +3,9 @@
     "hello",
     "world"
 ];
+(_a_filter_map = (_a_filter = (_a_filter1 = a.filter) === null || _a_filter1 === void 0 ? void 0 : _a_filter1.call(a, function(a) {
-(_a_filter_map = _a_filter = (_a_filter1 = a.filter) === null || _a_filter1 === void 0 ? void 0 : _a_filter1.call(a, function(a) {
     return true;
+})).map) === null || _a_filter_map === void 0 ? void 0 : _a_filter_map.call(_a_filter, function(a) {
-}).map) === null || _a_filter_map === void 0 ? void 0 : _a_filter_map.call(_a_filter, function(a) {
     return console.log(a);
 });

**Comment by jridgewell** [comment]
I suspect the bug is in https://github.com/swc-project/swc/blob/a504e2a11d4d95e5bda31b1c0bbe00c713f61ecf/crates/swc_ecma_transforms_compat/src/es2020/opt_chaining.rs#L448-L462, but I'm not sure of the fix yet.

**Comment by kdy1** [comment]
I'll check. Thank you so much for the investigation.
