### ISSUE TITLE
ReferenceError: Cannot access 'XXX' before initialization

### ISSUE THREAD

**Issue by leonard-henriquez** [swc-project/swc#7005]
### Describe the bug

SWC did not crash, but the app (NestJS) crashes at startup with the following error:

```
ReferenceError: Cannot access 'StepGraphQL' before initialization
```

### Input code

```typescript
input code

import { Field, ObjectType } from '@nestjs/graphql';
import { IsNumber, Min } from 'class-validator';
import { BaseModel } from '../../../common/graphql/base.gql-model';
import { TaskGraphQL } from '../../tasks/graphql/task.object';

@ObjectType('Step')
export class StepGraphQL extends BaseModel {
  @Field({ nullable: true })
  name?: string;

  @Field(() => [TaskGraphQL], { defaultValue: [] })
  tasks: TaskGraphQL[];

  @Field(() => String, { nullable: true })
  workspaceId?: string;

  @Field(() => String, { nullable: true })
  workspaceTemplateId?: string;

  @Field()
  @IsNumber()
  @Min(0)
  position: number;
}


output code is in reproduction link
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "noInterop": false,
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./"
  },
  "minify": false
}
```

### Playground link

[Playground link](https://play.swc.rs/?version=1.3.37&code=H4sIAAAAAAAAA42STW%2FCMAyG7%2FkVvrVIpd25jK3aYRPSGNpA2wFxSFsDgXyUJmVMiP%2B%2BNKxdtS9NyiGJXz9%2BbZmJQpUGjnDLkOcBTNINZmb2ViCcYFkqAV4iUZuNjlYlLdY77g0Ia5JG%2BqESKZYBjJlsEzJOte7vKWc5NarsJtxQjWOVI2%2FFYRidT6aEULKpEqVWGa52vC9qeZcxo3p7V6se779QjI20Pt0rVK4fm06Sz9Z8b2qw8HoED47pDEP913DxYFDmuuP3SAASNyT%2FCLLinKYcYzBlZSfVs0FJBV7HoE3J5MrWa%2BV%2BD4ZXMO%2FYXgS2jRyXtOLmmfLKcuaLM8W1EHd7nC%2B%2Bw6auSE35ycmrKre6oBmO8j8M%2FZMxQ1Fwan5j1dqkWYPzy66Cf1HfCqWZYUrGtkIdHpATIVEEH1M39ZJ1hv7CzFpV5gm14nvMHV%2FDECaCmcuOLgDPTcm7GpB389I%2BIb8CAAA%3D&config=H4sIAAAAAAAAAz2PsW7DMAxE%2F4XoaNhtlwJa2yVDuuUDGJl27EqiQNJohCD%2FXglpvN7j3fFu8KL%2BQhHBwcUsqxuGVTn1D1WNhXqWedBfLx46UN7E0xGzgjPZqIPI4xYI3A0SH5KRcAY3YdDKrORKwHOMnFaFewer%2BnZrKDNZZaTvr28fNTmjKEljWpLhtbJmVy9LtspH8ixYH9qbx5IwLv4QM4s9xFpggkknltiiAs3oy9fTujufwpEMRzTc3T9E%2BTOg6jdG2pvOqHSSUF%2FqhzYiLmmZyv%2FM%2Bx%2Fdev%2FiRQEAAA%3D%3D)

### Expected behavior

I expect code to run without error

### Actual behavior

App crashes at startup

### Version

@swc/core: "^1.3.37"

### Additional context

Im a using a NestJS app.
I followed this guide: https://docs.nestjs.com/recipes/swc.

**Comment by kdy1** [comment]
- https://github.com/swc-project/swc/issues/5205
 - https://github.com/swc-project/swc/issues/1686
 - https://github.com/swc-project/swc/issues/5204

**Comment by leonard-henriquez** [comment]
@kdy1 I'm sorry but I don't understand what's the problem and what the solution to my problem !
