### ISSUE TITLE
Typescript enum behavior mismatch

### ISSUE THREAD

**Issue by eolme** [swc-project/swc#7015]
### Describe the bug

Enums with mixed value types are compiled differently:

### Input code

```typescript
export enum Test {
    A = 10,
    B = "test",
    C
}
```

### Expected behavior

[Typescript playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwCrAM7wN4CwAUHKXAIJwC8cAjAAwA0xZcAQtXAEQw4xfMSZAMLEAvkA):

```js
export var Test;
(function (Test) {
    Test[Test["A"] = 10] = "A";
    Test["B"] = "test";
    Test[Test["C"] = void 0] = "C";
})(Test || (Test = {}));
```

### Actual behavior

[SWC playground](https://play.swc.rs/?version=1.3.37&code=H4sIAAAAAAAAA0utKMgvKlFIzSvNVQhJLS5RqOZSAAJHBVsFQwMdMNsJyFYqAcopQfjOXLUA1P0XBzYAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D):

```js
export var Test;
(function(Test) {
    Test[Test["A"] = 10] = "A";
    Test["B"] = "test";
    Test[Test["C"] = 11] = "C";
})(Test || (Test = {}));
```

### Version

1.3.37

**Comment by magic-akari** [comment]
The output of TypeScript is not valid.

The actual behaviour of TypeScript is Error report:
TS1061: Enum member must have initializer.

**Comment by eolme** [comment]
@magic-akari wait, are you saying that the compiler of the language that is the reference implementation does not compile correctly?

**Comment by magic-akari** [comment]
> @magic-akari wait, are you saying that the compiler of the language that is the reference implementation does not compile correctly?

<img width="661" alt="image" src="https://user-images.githubusercontent.com/7829098/222975871-902c2c19-8b87-4c03-9897-a56b9fc7a498.png">

You could check the Errors panel.

**Comment by magic-akari** [comment]
In my opinion, the goal of SWC is to generate vlaid outputs for vlaid inputs.
For invalid inputs, the output is unpredictable. 
SWC may attempt to produce results that match the expected ones, or report an error message to help users identify the issue.
In some cases, it may also produce invalid outputs, but it is not practical to expect swc's output to match that of other tools, such as TypeScript.

Please correct me if I am wrong. @kdy1

**Comment by kdy1** [comment]
I agree with you

**Comment by kdy1** [comment]
Thank you!
