### ISSUE TITLE
Module resolver / path rewrites / aliases

### ISSUE THREAD

**Issue by lostpebble** [swc-project/swc#702]
**Describe the feature**

Making use of `babel-plugin-module-resolver`, babel currently allows me to do something like this:

```json
plugins: [[
  "module-resolver",
  {
    "alias": {
      "^@gt/([^/]+)/build/(.+)": "@gt/\\1/src/\\2",
      "^@vs/([^/]+)/build/(.+)": "@vs/\\1/src/\\2",
      "^@sc/([^/]+)/build/(.+)": "@scr/\\1/src/\\2",
    },
    "extensions": [".js", ".jsx", ".ts", ".tsx"],
  },
]]
```

**Babel plugin or link to the feature description**

https://github.com/tleunen/babel-plugin-module-resolver

**Additional context**

This is exceptionally useful to me because I use a monorepo for my projects, and split up parts of my projects into different modules so that they can be re-used in multiple apps. Things like `@gt/node-utils` and `@gt/services` etc.

The way I've set it up is that when each of those individual modules are built - their code is imported with something like:

```ts
import { createFile } from "@gt/node-utils/build/filesystem/FileUtils"
```

I expect these imports to work, even if the code in those modules hasn't actually been built yet- because I'm always jumping between these separate monorepo modules to improve them and add new features.

I hardly ever actually "build" the modules in my day to day, as I can just use babel to rewrite the paths using `babel-plugin-module-resolver` so when my code is being compiled for dev or even production builds, it always hits the current source code in each module.

This could be related to #379, as I am using `tsconfig.json` to set up path aliasing so that TypeScript intellisense functions correctly in my IDE:

```
"paths": {
      "@gt/common-utils/build/*": ["gt-common-utils/src/*"],
      "@gt/node-utils/build/*": ["gt-node-utils/src/*"],
      "@vs/vs-server/build/*": ["vs-server/src/*"],
      "@gt/gt-server/build/*": ["gt-server/src/*"],
      "@gt/gt-frontend/build/*": ["gt-frontend/src/*"],
      "@gt/services/build/*": ["gt-services/src/*"],
      "@gt/task-function-utils/build/*": ["gt-task-function-utils/src/*"]
    }
```

**Comment by ws456999** [comment]
Is there any progress?

**Comment by kdy1** [comment]
@ws456999 Sadly, not yet.

I recently got an idea about such api, but it's blocked by https://github.com/neon-bindings/neon/issues/73 / https://github.com/infinyon/node-bindgen/issues/37 (I'll switch to node-bindgen if required)

**Comment by SirJosh3917** [comment]
Any progress on this? I also use this feature.

**Comment by aelbore** [comment]
this is a good feature

**Comment by JulienKode** [comment]
Is there any update about this issue ? 
or any workaround

**Comment by pbadenski** [comment]
+1 we're migrating to a monorepo layout and it's a bit challenging without this feature

**Comment by kdy1** [comment]
I started working on this, and I'm not sure if it's correct to support both of babel rewriter and tsconfig rewriter.
What do you guys think?

**Comment by lostpebble** [comment]
Well I just need to be able to tell the compiler to rewrite certain import paths when it encounters them and follow that new path for the module instead- whatever allows the most customization in this regard is the better one for me.

So I'd say the babel one is better? Since it uses a regex syntax and seems like you can use it for quite complex rewrites, as you can see I could do the same thing with a lot fewer lines than I could do with Typescript.

**Comment by pbadenski** [comment]
We only need tsconfig - so from our perspective simple matching is enough. As @lostpebble pointed out babel rewriting seems to be a superset, so sounds like a solution that makes more people happy :D  Automated parsing of tsconfig would be nice, but if I need to duplicate this config in `.swrc` - I don't really mind.

**Comment by kdy1** [comment]
Thanks for the response!
I decided to implement `tsconfig.paths` because I want to make a complete typescript compiler :)

**Comment by vjpr** [comment]
NOTE: To get this to work you must specify a `module` option in your config or modules are left untouched:

```
{
   "jsc": { ... },
   "module": {
     type": "commonjs"
   }
}
```

**Comment by vjpr** [comment]
> but I thunk you should specify baseUrl in .swcrc

I specified `baseUrl: 'src'` just like I have in `tsconfig.json`, and it doesn't have any effect.

**Comment by athrunsun** [comment]
@kdy1 There's nothing in the documentation about `baseUrl`, could you provide more details on this?

**Comment by kdy1** [comment]
@athrunsun You can refer to documentation for `baseUrl` of typescript.

**Comment by vjpr** [comment]
The problem with the current code is that `base_url` is not used in the `TsConfigResolver`.

```
paths: {"@src/*": ["*"]}
```

If we have:

_src/foo/index.js_

```
import from '@src/index'
```

It should resolve `@src/index` to absolute path `<base_url>/index`, and then determine the relative path from `src/foo/index` to `<base_url>/index`.

https://github.com/swc-project/swc/blob/427df9a979dee9f0737c3234085a52f7a79ea19a/ecmascript/loader/src/resolvers/tsc.rs#L121-L184
