### ISSUE TITLE
swc_common depends on two versions of ahash

### ISSUE THREAD

**Issue by ry** [swc-project/swc#703]
swc_common 0.5.8 depends on dashmap and hashbrown each depend on different versions of ahash.

**Comment by kdy1** [comment]
Hmm.. I'll consider sending a pr.

**Comment by Delilas56** [comment]
#554

**Comment by ry** [comment]
I haven’t looked into how these are being used but they both seem to provide hashmap implementations. Is this really necessary? Why not use std’s HashMap to reduce complexity?

**Comment by kdy1** [comment]
Hmm... I initially did it in the name of the performance, but this can be reverted as HashMap from std is same as one from hashbrown (I mean SwissTable,  if I remember correctly).
