### ISSUE TITLE
Crash when --source-file-name used with non-es6 module type - `index out of bounds: the len is 0 but the index is 0`

### ISSUE THREAD

**Issue by normano64** [swc-project/swc#7035]
### Describe the bug

Running the native cli binary on a typescript file that only contain types cause a crash when the `--source-file-name` flag is used together with the `commonjs`/`umd`/`amd` module type, it doesn't crash with the `es6` module type
```
./swc-linux-x64-gnu compile --source-file-name test.ts --config-file .swcrc test.ts 
```
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sourcemap-6.2.2/src/types.rs:655:9
```

It seems to work fine for the `es6` module type because it still produces a sourcemap when the file is types only while the others are producing empty sourcemaps

### Input code

```typescript
export type Test = {};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Expected behavior

Compiles without crashing

### Actual behavior

Crashes
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sourcemap-6.2.2/src/types.rs:655:9
```

### Version

1.3.38

**Comment by chenyukang** [comment]
@kdy1 assign to me?
btw, seems we don't have triagebot such as https://rustc-dev-guide.rust-lang.org/rustbot.html.

**Comment by chenyukang** [comment]
@realtimetodie 
This crash happened at this line: https://github.com/swc-project/swc/blob/bb80c659b3619c4dd98f34efdfc1094b8d46d114/bindings/swc_cli/src/commands/compile.rs#L549

Will this function need to be removed? since #1388 is resolved.

The rootcause is when we set `non-es6` in config file, the `node` here is a module whose `body` is a `vec` of `stmt`, all of the `stmt`'s span is dummy.

https://github.com/swc-project/swc/blob/bb80c659b3619c4dd98f34efdfc1094b8d46d114/crates/swc_ecma_codegen/src/lib.rs#L95

```json
begin to emit node: Module(Module { span: Span { lo: BytePos(1), hi: BytePos(23), ctxt: #0 }, body: [Stmt(Expr(ExprStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, expr: Lit(Str(Str { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: Atom('use strict' type=dynamic), raw: None })) })), Stmt(Expr(ExprStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, expr: Call(CallExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, callee: Expr(Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('Object' type=static), optional: false }), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('defineProperty' type=dynamic), optional: false }) })), args: [ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('exports' type=inline), optional: false }) }, ExprOrSpread { spread: None, expr: Lit(Str(Str { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: Atom('__esModule' type=dynamic), raw: None })) }, ExprOrSpread { spread: None, expr: Object(ObjectLit { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, props: [Prop(KeyValue(KeyValueProp { key: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('value' type=inline), optional: false }), value: Lit(Bool(Bool { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: true })) }))] }) }], type_args: None }) }))], shebang: None })
```

so after emitting, the `src_map_buf` is still empty, which introduced an empty source_map:

https://github.com/swc-project/swc/blob/bb80c659b3619c4dd98f34efdfc1094b8d46d114/crates/swc/src/lib.rs#L498


I think an empty `source_map` here is expected since the code is only valid for `es6`?

**Comment by kdy1** [comment]
I think we may skip #L549 when `src_map_buf` is empty
