### ISSUE TITLE
minify + compression improvement ?

### ISSUE THREAD

**Issue by kapouer** [swc-project/swc#704]
I understand the idea that gzip should do the heavy lifting of compressing js files.
However the end result is still kind of "too heavy":
- concatenated bundle: > 500ko
- uglified and gzipped: 73ko
- uglified and brotli: 61ko
- swc+minify and gzipped: 130ko
- swc+minify and brotli: 100ko

I suppose it's not a high priority to improve on this, hence the request ;)

**Comment by kdy1** [comment]
Currentlyswc does not do anything smart to minify bundle.
I'm busy working on a type inference engine to generate .d.ts files and I'll write a bundler and optimizer after it.

**Comment by kdy1** [comment]
I'll close this when I add the javascript apis.
Currently the minifier is beta (in rust side) and there's no js apis.
