### ISSUE TITLE
Using `accessor` as class method results in incorrect code.

### ISSUE THREAD

**Issue by AlexanderSimacan** [swc-project/swc#7042]
### Describe the bug

When compiling a class with a method named `accessor`, the resulting code removes the method name.

### Input code

```typescript
class SomeClass {
    accessor() {
        return '🦦';
    }
}
class SomeOtherClass {
    static accessor() {
        return '🦦';
    }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.38&code=H4sIAAAAAAAAA0vOSSwuVgjOz011BrOquRSAIDE5ObW4OL9IQxMqAAJFqSWlRXkK6h%2FmL1umbg0WruWq5UqGm%2BBfkpFahGxMcUliSWYySaYBACfgxeKQAAAA&config=H4sIAAAAAAAAA22PzQrCQAyE3yXnHrQHkb6DzyBhzZbV%2FQnJtljKvrvbUlsETxnmG8LMDE810M3AKEqyKJ1ixjd0kCcmNeI4QwNZq5VloFI1Sk%2B5JkjbU9tW6lNSgs6iV2oguOjstPwyKbCQ6oEw9p4WlBN7Gsnv6EXEd%2BNRNWIg%2FfXtH4%2FFjZip3sQHcnTdtaJFcefTZpRSy4f0GLYGdd864gLlKP19o7ctuI7%2BAI9bgSwoAQAA

### Expected behavior

SWC correctly compiles classes with methods named `accessor`.

### Actual behavior

The compilation removes the name of methods named `accessor`.

### Version

1.3.38

### Additional context

This is also a problem when using Axios:
https://github.com/axios/axios/blob/v1.x/lib/core/AxiosHeaders.js#L262

**Comment by kdy1** [comment]
Oh.. I think this is caused by accessor support PR
