### ISSUE TITLE
Object spread operator is unnecessarily transformed when used with React

### ISSUE THREAD

**Issue by spmonahan** [swc-project/swc#7044]
### Describe the bug

When spreading props onto a React component [object literal spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals) is converted to `Object.assign` despite all target browsers natively supporting object literal spread [according to caniuse](https://caniuse.com/mdn-javascript_operators_spread_spread_in_object_literals).

### Input code

```typescript
const Component = (props) => {
    return <div {...props}/>
}

const obj = { a: 1, b: 2};
// This is transformed to Object.assign
<Component {...obj}/>

// This is not transformed
const clone = { ...obj };
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "env": {
    "targets": {
      "chrome": "84",
      "edge": "84",
      "firefox": "75",
      "opera": "73",
      "safari": "14.1"
    },
    "bugfixes": true
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": false
    },
    "externalHelpers": true,
    "transform": {
      "react": {
        "useBuiltins": true
      }
    },
    "target": "es2019"
  },
  "minify": false,
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA1WOQQ6CMBBF9016h7%2FUxJToEoENB3DjBaBUhcgMaUc3hLtbaow6meW898YyBUHN48TkSFBiM3mewhZlhVkrxPFOHp5QdP0TszEmHSxZpdWilVY2KbgdIjyjybHfoc1xWI5aZRnOtz4grviGwoX96DoI49QOzoppQuivpFXxfWFNRFsK%2FBmI5dfyKdt75FL7DWINvwC%2FeYK%2B2AAAAA%3D%3D&config=H4sIAAAAAAAAAz2QS27DMAxE7yJ0adh1kyKtl1m1ixyCVShbgfUBSbU2gt69FFxnNzMCH4e6mye2EwYwg5lEMg9dd%2BMU2y1lSYRtorHjH0vWNAbjtxnuRoBGFK7STpQC6vzbsb5fx4d2ntClRe3pVW3KSHXP6aCGwQF5df2x7c1vY77K6PyCihQqqMGNbcVnIEaqitcoUGmyZmRLPouChJdtpDFXtIlAKyvEwcw1WiMEbz9DTiT%2FqbJxEaQI8wfOWop3gBBEdolCXUcIVqoojOfiZ%2FFxL6eE7QO0DPLLc%2F9eLwg%2Berc%2BVnMqZPECeZ%2F6A0dP8b5sAQAA

### Expected behavior

I expect that object literal spread should not be converted to `Object.assign` when used with React components with the provided config.

### Actual behavior

Object literal spread on React components is converted to `Object.assign` but usage outside of React is not converted.

### Version

1.3.36

**Comment by suxin2017** [comment]
![play swc rs_ (1)](https://user-images.githubusercontent.com/28481035/224193698-118bdc81-b95b-41e8-9f8a-e26581cace6a.png)
I switched the Target to ES2017 is ok

**Comment by spmonahan** [comment]
I think that's a worse situation that what we have targeting ES2019. With ES2017 now Object.assign is transformed to `_extends` and the spread literal is converted to `_objectSpread` meaning we now have much more code than before.

I'd like for everything in the output to be spread since the target browsers all support it natively. E.g., the output should be:

`Reat.createElement("div", {...props}), // etc` and `const clone = { ...obj }`

**Comment by suxin2017** [comment]
> I think that's a worse situation that what we have targeting ES2019. With ES2017 now Object.assign is transformed to `_extends` and the spread literal is converted to `_objectSpread` meaning we now have much more code than before.
> 
> I'd like for everything in the output to be spread since the target browsers all support it natively. E.g., the output should be:
> 
> `Reat.createElement("div", {...props}), // etc` and `const clone = { ...obj }`

I'm sorry, I misunderstood your initial meaning

**Comment by spmonahan** [comment]
No worries, thanks for picking this up so quickly!

One question: in looking at your PR, is using spread vs Object.assign for React not dependent on browser environment targets?

**Comment by magic-akari** [comment]
I believe that we may directly use the native object spread expression `{...}`.
As we should leave the task of downgrading syntax to the compat module.
What is your opinion on this? @kdy1

**Comment by kdy1** [comment]
I agree. Having an option for it is my mistake.

**Comment by spmonahan** [comment]
One thing we've noticed while looking at the linked PR is there appears to be an undocumented `useSpread` option. When we enable this we're getting the output we want but I'm curious if this is an option we should use or if we should wait for a fix to this issue?

**Comment by kdy1** [comment]
You should use it
