### ISSUE TITLE
Could not compile `swc_core@0.67.4` in Rust nightly 2022-12-31

### ISSUE THREAD

**Issue by hyf0** [swc-project/swc#7061]
### Describe the bug

![image](https://user-images.githubusercontent.com/49502170/224522044-9afdeb51-6498-4fc7-abe1-591d8e637c2f.png)

If I switch the nightly version SWC used,  then everything is ok.

It's not just 2022-12-31 that could not compile and seems all 2023-xx-xx could not compile.

### Expected behavior

Should compile without errors.

### Version

See title

**Comment by kdy1** [comment]
Oh now I found the cause...
Layout optimization is changed
