### ISSUE TITLE
.swcrc jsc.paths doesn't compile as intended

### ISSUE THREAD

**Issue by johnny-fuse** [swc-project/swc#7066]
### Describe the bug

Having my .swcrc file written as follows:
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./src",
    "paths": {
        "shared/*": ["../../../shared/*"]
    },
  },
  "minify": false
}
````

And my tsconfig.json written as follows:
```json
{
	"compilerOptions": {
		"outDir": "dist",
		"baseUrl": "src",
		"paths": {
			"shared/*": ["../../../shared/*"]
		},
		"sourceMap": true,
		"inlineSources": true,
		"target": "es2017"
	},
	"noImplicitAny": false,
	"strictNullChecks": false,
	"extends": "../../tsconfig.json"
}
```

When using tsc I'm receiving the right bundle with the shared directory bundled in the dist, but when using the swc build the dist directory doesn't contain the shared folder at all

### Expected behavior

shared directory should be compiles as part of the bundle

### Actual behavior

Bundled code doesnt' include the shared directory at all

### Version

1.3.38

**Comment by kdy1** [comment]
Closing as there's no information required for repro. Also, please search issues before filing one.

**Comment by johnny-fuse** [comment]
I've searched it and there is nothing similar to the best of my search... and you post a link for a duplicated issue?

**Comment by johnny-fuse** [comment]
@kdy1 I think the issue only happens when referring to outer scope of the baseUrl... meaning going backwords with ../
