### ISSUE TITLE
Source Map Format invalid

### ISSUE THREAD

**Issue by PSeitz** [swc-project/swc#707]
### Sourcemap Format
Example Output
```json
{
  "version": 3,
  "sources": [
    "// import { add } from './add';\r\n// export {add} from './add'\r\n\r\nconsole.log(\"start\")\r\nexport function add(num1: number, num2: number){\r\n    return num1 + num2;\r\n}\r\nconst res = add(3, 4);\r\n\r\nconsole.log(res)\r\n"
  ],
  "names": [],
  "mappings": ";;;;Q,G,G,G;A,E,6B;A,E,0B;A,O,C,G,E,K;S,G,C,I,E,I;W,I,G,I;;I,G,G,G,C,C,E,C;A,O,C,G,C,G",
  "file": "index.js"
}
```

According to https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit
```json
"sources": ["foo.js", "bar.js"],
"sourcesContent": [null, null],
```
_sources_ should not contain the content, but the path to the original files

### Probable root cause
here the file content is added
https://github.com/swc-project/swc/blob/ffbb5163aa6a4acb46c0618b4b3605e268a5532c/common/src/source_map.rs#L1024

Should be probably something like this
```rust
if f.name.is_real(){
    builder.add_source(&f.name.to_string());   
}
```

**Comment by kdy1** [comment]
You are right. Thank you very much!
