### ISSUE TITLE
`export { type <ident> }` does not result in `<ident>` being marked as a type

### ISSUE THREAD

**Issue by lucacasonato** [swc-project/swc#7076]
### Describe the bug

`export { type <ident> }` does not result in `<ident>` being marked as a type, and as such does not get stripped out unless declared with `type` in the import.

Additionally `export {}` is omitted with `export { type <ident> }` even though it should not be. This is the distinguishing factor between `export { type <ident> }` and `export type { <ident> }`

### Input code

```typescript
import { A } from "./a.ts";
export { type A };
```

### Playground link

https://play.swc.rs/?version=1.3.39&code=H4sIAAAAAAAAA8vMLcgvKlGoVnBUqFVIK8rPVVDS00%2FUKylWsuZKrYDKlVQWpIIUWAMAXodgqi4AAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

```js
export {};
```

### Actual behavior

```js
import { A } from "./a.ts";
```

### Version

swc_ecma_transforms_typescript@0.164.10

### Additional context

TSC behaviour with isolated modules: https://www.typescriptlang.org/play?isolatedModules=true#code/PTAECMDoBcGcCgCWBbADgewE7VAb1AIKgC+oAZpusqAESTACGkAVrDQNzwCmAHhtnlDQAnqi6ES7IA

Babel bug: https://github.com/babel/babel/issues/15493

**Comment by kdy1** [comment]
Thanks!
