### ISSUE TITLE
Negative numbers in types are not parsed as unary expressions

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#708]
**Describe the bug**

Given the following code:

```ts
type test = -1;
const t = -1;
```

It parses like so:

```
Node kind: Module
Text: "type test = -1;\nconst t = -1;"
Node kind: TsTypeAliasDecl
Text: "type test = -1;"
Node kind: Ident
Text: "test"
Node kind: TsLitType
Text: "-1"
Node kind: Number
Text: "1"
Node kind: VarDecl
Text: "const t = -1;"
Node kind: VarDeclarator
Text: "t = -1"
Node kind: Ident
Text: "t"
Node kind: UnaryExpr
Text: "-1"
Node kind: Number
Text: "1"
```

**Expected behavior**

I would expect both numbers to parse within unary expressions. So:

```
Node kind: TsLitType
Text: "-1"
Node kind: UnaryExpr
Text: "-1"
Node kind: Number
Text: "1"
```

**Version**

0.19.2 of parser

**Comment by kdy1** [comment]
@dsherret Currently `TsLitType` cannot store `UnaryExpr` or its siblings like `BinExpr` and I'm not sure if allowing usage of arbitrary expression in a `TsLit` is a good idea.

Anyway, I verified (and added a test) that `type test = -1;` is parsed as `TsList` with -1 as a value.

**Comment by dsherret** [comment]
Hmmm... yeah I wasn't thinking too much when I opened this 😅 -- I was only thinking about what TypeScript does...

![image](https://user-images.githubusercontent.com/1609021/76219780-c136ed80-61ec-11ea-838c-63ec83b2b6f9.png)

...but Babel does the following:

![image](https://user-images.githubusercontent.com/1609021/76219839-dca1f880-61ec-11ea-8e28-bcd107703864.png)

Yup, arbitrary expressions in a `TsLit` is not a good idea.

Ah, ok I didn't realize the value of the number was negative in this case. I've only been looking at the text because I need to get the text as-is. Anyway, for me it is not a big deal as when I encounter a `TsLit` that's a `Number` I will just look at the whole text of the `TsLitType`.

Thanks and thank you for adding the test! I'm going to close this because I think what swc is doing here is sufficient. 🙂
