### ISSUE TITLE
swc has different behavior when transform class with `setPublicClassField`  

### ISSUE THREAD

**Issue by IWANABETHATGUY** [swc-project/swc#7085]
### Describe the bug

**swc 1.4.40** 
https://play.swc.rs/?version=1.3.40&code=H4sIAAAAAAAAA0vOSSwuVghILErNK1Go5uXiLMnMTbVSKM1LSU3LzEtNUahRyCvNTUotUrBVyEstV3BJLEnV0NQrS8wpTfVP09C05uWq5eXi5UoGm%2BOckZmTopBaUZKal0KUqRDtAEx0itCFAAAA&config=H4sIAAAAAAAAA0WNQQ7DIAwE%2F%2BJzDhWHHvKHPgJRJ6IFg1iiFiH%2BXoiocrN3x%2BNKLxhaK0WdwGlMKJL1l1bKJTJMsjHTQhk92rQDt77otHPuCEPdlOq1CwE8gYW8FbuVITPBx8TAVWnZ3Z9s3eXD8xhBPf%2Bdzju1yzHvLB4TpEPeEj5C7QdrmxBuvQAAAA%3D%3D
![image](https://user-images.githubusercontent.com/17974631/225269914-e89a5070-3a23-4f20-9abe-cde376e8daa1.png)

**swc 1.4.39** 
![image](https://user-images.githubusercontent.com/17974631/225269976-2a5fe1a0-9e62-4dfc-be09-6b59b73ada8a.png)

** typescript**
![image](https://user-images.githubusercontent.com/17974631/225270040-7923358a-0508-4169-ae66-c78ec8335ce9.png)
https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKYCcCmA7ALtA3gKAJBoEsBbJALmgFcUATJAMwJSWugB9oUKiAjJBaALwckAd2gARMGiQAKAJQA6AG5gQFJAHk68gNzYAvtmyhIMAMIALAiBZIAHtJox4ydFjyES5KrQZMW7Jw8fHqGQA

**babel **
![image](https://user-images.githubusercontent.com/17974631/225270100-0f5c7ec3-ca67-4fad-915f-90f319193079.png)
https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEAKYCcCmA7ALtA3gKAJBoEsBbJALmgFcUATJAMwJSWugB9oUKiAjJBaALwckAd2gARMGiQAKAJQA6AG5gQFJAHk68gNzYAvtmyhIMAMIALAiBZIAHtJox4ydFjyES5KrQZMW7Jw8fHqGQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.21.3&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.19.6&assumptions=%7B%22setClassMethods%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%7D

### Input code

```typescript
class Parent {
	time: undefined | number = new Date().valueOf();
}

class Child extends Parent {
	time: undefined | number;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": "unknown"
}
```

### Playground link

https://play.swc.rs/?version=1.3.39&code=H4sIAAAAAAAAA0vOSSwuVghILErNK1Go5uXiLMnMTbVSKM1LSU3LzEtNUahRyCvNTUotUrBVyEstV3BJLEnV0NQrS8wpTfVP09C05uWq5eXi5UoGm%2BOckZmTopBaUZKal0KUqRDtAEx0itCFAAAA&config=H4sIAAAAAAAAA0WNQQ7DIAwE%2F%2BJzDhWHHvKHPgJRJ6IFg1iiFiH%2BXoiocrN3x%2BNKLxhaK0WdwGlMKJL1l1bKJTJMsjHTQhk92rQDt77otHPuCEPdlOq1CwE8gYW8FbuVITPBx8TAVWnZ3Z9s3eXD8xhBPf%2Bdzju1yzHvLB4TpEPeEj5C7QdrmxBuvQAAAA%3D%3D

### Expected behavior

Should generate same code as typescript and babel

### Actual behavior

class Parent {
    time = new Date().valueOf();
}
class Child extends Parent {
    time;
}

### Version

1.4.40

### Additional context

1.4.39 works well

**Comment by kdy1** [comment]
I think this is fixed by https://github.com/swc-project/swc/pull/7065

**Comment by kdy1** [comment]
See https://babeljs.io/repl#?browsers=node%2016&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEAKYCcCmA7ALtA3gKAJBoEsBbJALmgFcUATJAMwJSWugB9oUKiAjJBaALwckAd2gARMGiQAKAJQA6AG5gQFJAHk68gNzYAvtmyhIMAMIALAiBZIAHtJox4ydFjyES5KrQZMW7Jw8fHqG2EA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.21.3&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.19.6&assumptions=%7B%22setClassMethods%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%7D

The class fields are not transformed by the typescript pass.

**Comment by IWANABETHATGUY** [comment]
Would you mind explaining which one is expected? 

![image](https://user-images.githubusercontent.com/17974631/225278426-6e35a161-6727-43c9-8f1d-ef762773268b.png)

because these two pieces of code have different semantic: 
```js
class Parent {
  time = new Date().valueOf();
}
class Child extends Parent {
  time;
}
console.log((new Child().time))
```
output: 
```bash
undefined
```

```js
class Parent {
    time = new Date().valueOf();
}
class Child extends Parent {
}
console.log((new Child().time))
```

```bash
1678875405638
```

**Comment by kdy1** [comment]
I mean our behavior is identical to the one of babel.

**Comment by kdy1** [comment]
@magic-akari What do you think?

**Comment by IWANABETHATGUY** [comment]
According to the typescript, the second is expected, but swc will yield the first output in the latest version.

**Comment by kdy1** [comment]
Then use `useDefineForClassFilelds`. https://github.com/swc-project/swc/issues/6985

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.40&code=H4sIAAAAAAAAA0vOSSwuVghILErNK1Go5uXiLMnMTbVSKM1LSU3LzEtNUahRyCvNTUotUrBVyEstV3BJLEnV0NQrS8wpTfVP09C05uWq5eXi5UoGm%2BOckZmTopBaUZKal0KUqRDtAEx0itCFAAAA&config=H4sIAAAAAAAAA02OsQ7CMAxE%2F8VzB9SBoSuoGx8RtW4VSJzIlwiqKv9OUlWCzfa9u%2FNOT0w07BSNgrVN2CSZDw2UtsiY1MZEHSXU02IcuNTF6MqpIoz%2B0vdVdiGAT6Ajb8UuWwubgo%2FKwE8ysjr%2Bi1IjWIL6RmfwnRcrPAa9OQOMlt1czUkzl0r7MOfm3o%2FnjgeuVH6FZ4nF4wQpy0vCW6h8AStHOUDqAAAA

**Comment by kdy1** [comment]
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/29931815/225281768-f3cf0220-e429-4111-b0e3-a5a90080dd7d.png">

**Comment by magic-akari** [comment]
I'm away from keyboards now.
I will take a look as soon as possible.

**Comment by IWANABETHATGUY** [comment]
> 

Thanks for your work and the detailed explanation
