### ISSUE TITLE
Uisng @swc/jest crashes with thread '<unnamed>' panicked at 'failed to invoke plugin

### ISSUE THREAD

**Issue by AbhiPrasad** [swc-project/swc#7092]
### Describe the bug

`@swc/jest` causes jest to crash in CI when using the [`jest_workaround` plugin](https://github.com/magic-akari/jest_workaround).

GH action run: https://github.com/getsentry/sentry-javascript/actions/runs/4437301786/jobs/7787193218

PR w/ crash: https://github.com/getsentry/sentry-javascript/pull/7484

SWC versions:
```
    "@swc/core": "1.3.40",
    "@swc/jest": "0.2.24",
```

`jest_workaround` versions:
```
  "jest_workaround": "0.1.16",
```

### Expected behavior

Not crash when running jest

### Actual behavior

```
> @sentry/core:test

$ jest
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/home/runner/work/sentry-javascript/sentry-javascript/packages/core/test/lib/base.test.ts")'

Caused by:
    0: RuntimeError: out of bounds memory access
    1: heap_get_oob', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.255.3/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
error Command failed with exit code 139.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Version

1.3.40

**Comment by kdy1** [comment]
This is not a bug of swc/core

**Comment by AbhiPrasad** [comment]
Hey @kdy1 - is this a problem with `jest_workaround`? Or with `jest`? What do I need to do to investigate this further?

**Comment by kdy1** [comment]
I think `jest_workaround` is the cause.
See https://swc.rs/docs/plugin/selecting-swc-core

**Comment by AbhiPrasad** [comment]
Awesome, opened a bug report (https://github.com/magic-akari/jest_workaround/issues/30) with `jest_workaround`, thank you!

**Comment by magic-akari** [comment]
> I think `jest_workaround` is the cause.
> See https://swc.rs/docs/plugin/selecting-swc-core

I have updated the `swc_core` dependencies to the latest version.
The issue did not get resolved, even though it worked fine on my unit tests.
Besides an incompatible version of `swc_core`, I cannot find other reasons for the `out of bounds memory access`.
@kdy1  Do you have any leads on this?

**Comment by kdy1** [comment]
Oh it's pinned. Hmm

**Comment by AbhiPrasad** [comment]
The branch with the tests failing is on https://github.com/getsentry/sentry-javascript/tree/abhi-build-swc-jest. Please let me know if you need me to debug/run anything to test stuff out.

**Comment by kdy1** [comment]
@AbhiPrasad Can you run CI again with `RUST_BACKTRACE=1`?

**Comment by kdy1** [comment]
I ran in locally with `@swc/core@1.3.41` with `jest_workaround@0.69` but it worked.
I'm using Apple M1 Max chip

**Comment by AbhiPrasad** [comment]
Works for me locally as well - going to hard-pin the deps you mentioned and run in CI.

Unfortunately [downloading node](https://status.nodejs.org/) is having problems, so CI might flake a couple times while we wait.
