### ISSUE TITLE
Unnecessary to import 'array.push' polyfill

### ISSUE THREAD

**Issue by Lancernix** [swc-project/swc#7100]
### Describe the bug

env targets is set `chrome 60`, it seems unnecessary to import the `array.push` polyfill.

### Input code

```typescript
const c = [1,2,3,4].push(5);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "chrome 60",
    "coreJs": "3.29",
    "mode": "usage"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA0vOzysuUUhWsFWINtQx0jHWMYnVKygtztAw1bQGAKMvA4McAAAA&config=H4sIAAAAAAAAA0WOXQrCQAyEryJ5LiKKBXsEwUOENa0r3R%2BSrViWvbvZpdK3ZGbyZTK8xcCQISILcZ1k9Qm%2FMAAZh2LYxgSdxlQacRYqHSTkiVKNyFW9OQShze3AWW%2FHtZJMcJFJZLfQT%2FM%2FWRTkwnOpQoa0RmrAHsrO2O6sPLZg4kV38p9202ooHsyLg6NDf9I2JjDdq3g5nm%2FQflTyIjgRlPIDGgkQX%2FIAAAA%3D

### Expected behavior

```js
const c = [1,2,3,4].push(5);
```

### Actual behavior

```js
import "core-js/modules/es.array.push.js";
const c = [1,2,3,4].push(5);
```

### Version

1.3.41

**Comment by zloirock** [comment]
`Array.prototype.push` is buggy even in the latest Chrome.

**Comment by Lancernix** [comment]
@zloirock Thanks, I know why. As you said, I tested it in Babel and the results were different. Two compilers gave different results, It makes me a little confused.
![image](https://user-images.githubusercontent.com/26547236/226575118-fe56143e-6425-43d2-8e89-5cc978de5a4e.png)

**Comment by zloirock** [comment]
@Lancernix that because Babel REPL uses an obsolete version of `core-js` - as you can see on your screenshot, it's `corejs: '3.21'`.

**Comment by Lancernix** [comment]
@zloirock I used `core-js@3.29.1` in my local env and got the same result with Babel REPL.
![image](https://user-images.githubusercontent.com/26547236/226594534-950cff44-bd62-4c6f-b5ba-b20489f51195.png)

**Comment by zloirock** [comment]
@Lancernix in this case, write an issue here https://github.com/babel/babel-polyfills - it should be injected.
