### ISSUE TITLE
SWC does not remove interface when used with parameter decorator

### ISSUE THREAD

**Issue by 8NAF** [swc-project/swc#7101]
### Describe the bug

When using a parameter decorator with a parameter of type interface, `swc` does not remove that interface, leading to errors at runtime.

### Input code

```typescript
// sub.ts
export interface Interface {
  p: string
}



// main.ts
import { Interface } from './sub.js'

function ParameterDecorator() {
  return function(
    target: any,
    propertyKey: string | symbol,
    parameterIndex: number,
  ) { }
}

class Class {
  public constructor(
    @ParameterDecorator()
    i: Interface,
  ) { }
}

const c = new Class({ p: '' })
console.log('success')
```

### Config

```json
{
	"$schema": "https://json.schemastore.org/swcrc",
	"jsc": {
		"parser": {
			"syntax": "typescript",
			"decorators": true,
			"dynamicImport": true
		},
		"transform": {
			"decoratorMetadata": true,
			"legacyDecorator": true
		},
		"target": "es2022",
		"loose": false,
		"externalHelpers": false,
		"keepClassNames": true
	},
	"sourceMaps": true,
	"module": {
		"type": "es6"
	},
	"minify": false
}
```

### Playground link

https://replit.com/@8NAF/swc-issues-7101

### Expected behavior

The interface should be removed.

### Version

1.3.41

### Additional context

I can fix this issue by using `import type { Interface } from './sub.js'`, but I still opened the issue for the following 3 reasons:
- I am using `typescript-eslint`, and it will automatically remove `type` when importing with interfaces (specifically, with this [rule](https://typescript-eslint.io/rules/consistent-type-imports/)).
- The interface will be removed if it is not used with a parameter decorator, but it will not be removed if it is used with one, which causes inconsistency.
- `tsc` can handle this case normally without any runtime errors.

**Comment by magic-akari** [comment]
This requires a cross-file type system, which is impossible for workflow like swc and Babel that compile files one by one.

When using swc, it is recommended to set `importsNotUsedAsValues` to `error` in the tsconfig.json file.\
To improve other compatibilities, `isolatedModules` should be set to `true`.

In the case of typescript-eslint, if it removes `type` while TS considers it to be a `type`, then it is a bug in typescript-eslint.

**Comment by 8NAF** [comment]
@magic-akari 

ok, I understand.

But I have a note for those who are using vscode, should not set `importsNotUsedAsValues` to `error`.

When using the value of `error`, vscode's auto import feature always add `import type` for everything, including classes. Therefore, classes are removed when compiled, leading to decorators not working correctly.

When using the other two values (`remove` and `preserve`), vscode's auto import feature  doesn't add `import type`, but report an error when there is no `import type` for an interface, and not report an error when using a class as a type, which makes everything safer.

**Comment by 8NAF** [comment]
By the way, can you add this note somewhere in your documentation? I found someone else who encountered a similar problem([#1839](https://github.com/swc-project/swc/issues/1839)), but it happened with method decorators.

**Comment by magic-akari** [comment]
> When using the value of error, vscode's auto import feature always add import type for everything, including classes. Therefore, classes are removed when compiled, leading to decorators not working correctly.

Class can be used as a value, as well as a type.
Perhaps, VSCode may erroneously add 'type', however, TypeScript's type-check captures this error, avoiding it being deferred to runtime.
Conversely, without the `type` modifier, SWC or Babel cannot distinguish between them. The imported binding can be either a class or an interface (as with your current issue). TS's leniency may postpone errors until runtime.


tsc can eliminate implicit type imports due to its cross file type system awareness.
Therefore, having errors detected during type-checking phase facilitates compatibility when migrating to other tools.

---

@kdy1 We should document more information to assist TS users when Integrating with SWC.

**Comment by kdy1** [comment]
I made https://swc.rs/docs/migrating-from-tsc but not sure how should I describe this problem
