### ISSUE TITLE
No diagnostic for missing paren in if statement

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#7104]
### Describe the bug

No diagnostic given for missing paren in if statement header.

### Input code

```typescript
const foo = <T extends {}>() => {
    if (bar() {
        console.log(1);
    }
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "transform": {
      "useDefineForClassFields": true,
      "react": {
        "importSource": "https://esm.sh/preact",
        "runtime": "automatic"
      }
    },
    "loose": false
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVbAJUUitKEnNSylWqK6109BUsLVTqOblUgCCzDQFjaTEIqAYVAAEkoF683NS9XLy0zUMNa0hErW8XLXWAJRuJZFWAAAA&config=H4sIAAAAAAAAA1WQvW7DMAyE9z6FoTmoCw8ZsrbIlilPQCh0w0J%2FICkgRuB3jyTHcbqJ3%2FF04N0%2Fus78iTWH7l6eZUjAgvyaC5EpKNwKMTolFMuU1OxWVaVKyhkbmRfBKPAvajWhDF%2FDYFbOEGSM7N8TsuAPjhTwGPnbgciR0F3k%2Be8rihGsvvkKIp8i6zlmtljDrqpJDn2P4j%2Fl2qfFstsMnIOSb7uQNXpQsuYpz%2F8ucDFK3RvBSb2tcePjJTvc6qqVLFfuzbZEgcZp9TZEclqdrav5AeQIxLB6AQAA

### Expected behavior

Typescript gives a `')' expected` error.

### Actual behavior

```ts
const foo = ()=>{
    if (bar()) <invalid>;
    {
        console.log(1);
    }
};
```

### Version

1.3.41

**Comment by chenyukang** [comment]
@kdy1 
I would like to have a try to fix it, please assign to me?

**Comment by kdy1** [comment]
Thank you!
