### ISSUE TITLE
Should require jsx runtime in Script

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#7119]
### Describe the bug

Missing require for `jsx runtime` if source type is script

### Input code

```typescript
<div></div>
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "externalHelpers": true,
    "target": "es2022"
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA7NJySyzs9EHkQD5kTeICwAAAA%3D%3D&config=H4sIAAAAAAAAA1WPPQ6DMAxGd06BPHeoGHuCLj2EFUwVlD%2FZRgIh7t4kBUq3%2BD3n%2B%2BS1aVsYxcCjXfMzDwlZiM85E1mC4pwJ6JJIDNukcDusSlHKE52oJxMZNbLsport60EZgwyR%2FbWDCY1eQEFTUOup9OKk0aNaA7ve%2FhJpVuKA7kku0Vl61CG%2FqUQDSXfvuhJRP4KP%2FeTod3m5ruyZ6H0Mo1w2bbDDkt2ATmowWHkd3ytstg9IVTefSwEAAA%3D%3D

### Expected behavior

const _jsxRuntime = require("react/jsx-runtime");
_jsxRuntime.jsx("div", {});

### Actual behavior

/*#__PURE__*/ _jsx("div", {});

### Version

1.3.41

**Comment by JSerFeng** [comment]
Found the reason, you can leave this to me

**Comment by kdy1** [comment]
Thanks!
