### ISSUE TITLE
Error with Enum, TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by XAMEUS** [swc-project/swc#7124]
### Describe the bug

Hi, 👋 

`tsc` transforms some declared enum into its value while `swc` looks like it does not.

I might have missed something in the configuration to make it work? 

### Input code

```typescript
export declare const enum EnumA {
  A = "A",
  B = "B",
  C = "C",
}

export const f = (a: EnumA) => {
  console.log(a);
};

console.log("Hello World!!!");
f(EnumA.A);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2020",
    "baseUrl": "."
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA02MQQrCMBBF93OKn6xSkB7AUiEtgjdwHdqpm7GR2IIgvbuTZONmeMz%2F%2F%2FHnFdOGmScJiTHF9b2B1%2F2Jqx6PLwEePay3J8Uh41BwzDgqHkRcLXW9aODCuQoa9JciyVkUbiU%2BXGg6Ojqi%2F5%2B9sUjEPSaZjTFWK4sritYr%2FwCajC53qAAAAA%3D%3D&config=H4sIAAAAAAAAA1VPSQ7DIAy88wrkcw8Vx%2F6hj0DUiYjYhB2pKMrfCymkzc2exTPehJSwkIGH3OpYl6QzYT73ilAJrN8VAS4JyWSbGG6DZWrUpB3hAe1fBljnGbm5kNRdqe4AFyPhcHTM22Cn8p9pok8Zia7CJtVhdnhNFD0VfHytB9l%2FaX1bg3rNx7AQ%2FJQj8bwOlp7DznlFsX8AqE9BlhwBAAA%3D

### Expected behavior

tsc output (with replaced constant and generated comment):
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.f = void 0;
const f = (a) => {
    console.log(a);
};
exports.f = f;
console.log("Hello World!!!");
(0, exports.f)("A" /* EnumA.A */);
```

### Actual behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "f", {
    enumerable: true,
    get: ()=>f
});
const f = (a)=>{
    console.log(a);
};
console.log("Hello World!!!");
f(EnumA.A); // <- 💥 TypeError: Cannot read properties of undefined
```

### Version

1.3.41

### Additional context

I do not have control over how the enum is defined (external `index.d.ts` lib), I found a way to make `swc` [work if I could change it](https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA0utKMgvKlFIzSvNVXAFEo4K1VwKCo4KtgpKjko6QKYTiOkEZjqDmM5AZi0XVypEX3J%2BXnGJQhpQQiPRCmKApoKtHdgQkFx%2BTqpeTn66RqKmNVetNRcXspiSR2pOTr5CeH5RToqioqISUEmaBtgIPUcgGwDAW%2FAfmgAAAA%3D%3D&config=H4sIAAAAAAAAA1VPSQ7DIAy88wrkcw8Vx%2F6hj0DUiYjYhB2pKMrfCymkzc2exTPehJSwkIGH3OpYl6QzYT73ilAJrN8VAS4JyWSbGG6DZWrUpB3hAe1fBljnGbm5kNRdqe4AFyPhcHTM22Cn8p9pok8Zia7CJtVhdnhNFD0VfHytB9l%2FaX1bg3rNx7AQ%2FJQj8bwOlp7DznlFsX8AqE9BlhwBAAA%3D).

**Comment by XAMEUS** [comment]
Thank you @kwonoj 🙏 

Working [ts playground](https://www.typescriptlang.org/play?target=9&module=1#code/KYDwDg9gTgLgBAE2AYwDYEMrDsiA7AZ3mDwFcBbOAUTPIEE4BvAKDjgYF44AiO7gGlZwAQnC7dhAoQGExPaVIC+zZqEiwc+InABmcgBToAXNVp0AlGIB8TIbkIRUwAHSoIAc0PmA3M0W-mewJHFzdPbgAJYFQ3OAB1aFQEAEJU7h9mHX0aCjpnC28gA) (set to `commonjs`).

The problem seems to be related to the `declare`, without it, it [works](https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIzSvNVXAFEo4K1VwKCo4KtgpKjko6QKYTiOkEZjqDmM5AZi0XVyqy7jSghEaiFcQATQVbO7AhILn8nFS9nPx0jURNa65aay4uZDElj9ScnHyF8PyinBRFRUUloJI0DbAReo5ANgCFsiUFoAAAAA%3D%3D&config=H4sIAAAAAAAAA1VPSQ7DIAy88wrkcw8Vx%2F6hj0DUiYjYhB2pKMrfCymkzc2exTPehJSwkIGH3OpYl6QzYT73ilAJrN8VAS4JyWSbGG6DZWrUpB3hAe1fBljnGbm5kNRdqe4AFyPhcHTM22Cn8p9pok8Zia7CJtVhdnhNFD0VfHytB9l%2FaX1bg3rNx7AQ%2FJQj8bwOlp7DznlFsX8AqE9BlhwBAAA%3D). But it my case I cannot change it as it is exposed by some lib I am using.

So this problem seems not related to the `const enum` mentioned in the other issue.

**Comment by kwonoj** [comment]
The playground link you shared shows this 
![image](https://user-images.githubusercontent.com/1210596/226976707-3aa3e3ea-7b8e-46e5-8aca-6d36b9adde55.png)

which should raise same error.

**Comment by XAMEUS** [comment]
@kwonoj Executing it with node it works, I executed it with node:
![tsc-vs-swc](https://user-images.githubusercontent.com/8436574/227145105-d94ad97a-27c8-421e-a7e5-139947754c0c.gif)
