### ISSUE TITLE
rust side support import_interop function

### ISSUE THREAD

**Issue by underfin** [swc-project/swc#7130]
### Describe the feature

babel has this feature at here https://babeljs.io/docs/babel-plugin-transform-modules-commonjs#importinterop. It is important control the special request module interop behavior.

**Comment by kdy1** [comment]
It's implemented, just not documented

**Comment by underfin** [comment]
@kdy1 Now only support `Babel/Node/None`, the function or object is missing.

**Comment by kdy1** [comment]
What object? babel doc does not have object, and function is not planned

**Comment by underfin** [comment]
The function interface is `(specifier: string, requestingFilename: string | undefined) => "babel" | "node" | "none"`, it will use diffrent interop by `specifier`. Maybe we can support `Object(HashMap<string, 'babel' | 'node' | 'none'>)`, what do you think, I'm working on rspack and meet the problem at a esm file which import cjs file and also import other esm file.Like this:
```
// a.mjs
import b from './b.cjs'  // this import_interop should be `node`
import c from './c.mjs' // this import_interop should be `swc`
```
Hope get feedback for you, i can do it if you approve the feature request.

**Comment by kdy1** [comment]
A rust-side function is fine, and I think you can create `ImportInteropConfig` type with `Box<dyn for<'aa> FnMut(&'aa str, Option<&'aa str>) -> ImportInterop>` as a varaint

**Comment by underfin** [comment]
Yeah, it's ok with rspack. Thanks a lot!

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/7134#issuecomment-1482247759
