### ISSUE TITLE
Emit deep imports for helpers when using Common JS

### ISSUE THREAD

**Issue by andersekdahl** [swc-project/swc#7144]
### Describe the feature

Currently when using external helpers SWC will output something like this for ESM:
```js
import _create_class from "@swc/helpers/src/_create_class.mjs";
```

And something like this for CJS:
```js
var _create_class = require("@swc/helpers").create_class;
```

I discovered this when analyzing this issue: https://github.com/webpack/webpack/issues/16861

While I do believe that issue to be a webpack issue and not a SWC issue it would most likely not have happened if SWC emitted deep require statements instead of requireing from the entry point which exports all helpers. Eg, if the require statement would have looked like this:
```js
var _create_class = require("@swc/helpers/lib/_create_class.js").default;
```

This would also have the added benefit of getting smaller bundles when using CJS since you'd only import the helpers actually used. To my knowledge webpack won't be able to correctly tree shake unused requires from lib/index.js.

**Comment by magic-akari** [comment]
The root cause: The exported function name is `createClass` instead of `create_class`.

Solution:
To reduce the complexity of conversion, I believe we should always use `snake_case` in both file name and exported function name.
In addition, named exports are less problematic than `default` exports, so I prefer to change all to named exports. 

What are your thoughts?  @kdy1

**Comment by kdy1** [comment]
I agree, `camelCase` isn't required at all.
Can we do it without breaking apps? We currently have no validation for the version of `@swc/helpers`.

**Comment by andersekdahl** [comment]
Ah, didn't notice that there was a mismatch between the used name and the exported name. However, even if I manually patch `@swc/helpers/lib/index.js` to export the names that the require statement expect webpacks/terser still strips it out completely. But I guess that's a webpack issue and not a SWC issue.

**Comment by magic-akari** [comment]
> I agree, `camelCase` isn't required at all.
> Can we do it without breaking apps? We currently have no validation for the version of `@swc/helpers`.

We can declare `peerDependencies` in the package.json of `@swc/helpers`. Would this approach suffice in validating the versions?

```json
"peerDependencies": {
    "@swc/core": ">1.3.42"
}
```

**Comment by kdy1** [comment]
Good idea. I never thought that I can use it to do such thing

**Comment by magic-akari** [comment]
I think I should keep using default exports.
so there will be no breaking change.
