### ISSUE TITLE
SWC Playground -  Code to crash

### ISSUE THREAD

**Issue by intpp** [swc-project/swc#7146]
### Describe the bug

If you try to do this `const SuperComponent = (` (put an opening round bracket at the end of the line with the component's initialization), it will crash the browser.

### Input code

```typescript
import React from 'react';

const SuperComponent = 
<If condition={true}>
    <div>asdas</div>
</If>
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.42&code=H4sIAAAAAAAAAxWKOw6AIAxA956imyMHEFicXPUEhE%2FSAWpKdTHeXXjTS96jerEoHjlExSJccZHpywoQuXXF876ybDy%2BlpuiQ7B7wdESKXFzr8qdPw84sIkeH3oK3ZqpYM1e%2FA8BGJN5ZAAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSQ7CMAxF9z1F5DVbWHCHHsIKbpUqk%2BJUIqp6d9JMwM7%2Bg598TELAxhKe4shjXjwGpjD2rHCyEd9ZAZIGWQblI9y6u%2FFlxbBTUc5qQMSwUiwlvrc0aOeYsragZmqaUVYt6ZcnnfGBmP%2BDVxTtqke%2F4qaGBONeezHbHzF5qvgHfEMdNg6D4rk3yxPnB%2BvJL0oTAQAA

### Expected behavior

The playground should display an error instead of crashing.

### Version

1.3.42

**Comment by kdy1** [comment]
Your link does not crash

**Comment by intpp** [comment]
![SWC Playground memory leak](https://user-images.githubusercontent.com/2384433/227769710-f8eb7fa4-3997-4364-aee9-199315a3549b.png)

I'm sorry, I forgot to write the reason, and I checked it in Google Chrome and Safari.
