### ISSUE TITLE
Could not compile custom plugins with a stable rust

### ISSUE THREAD

**Issue by thekip** [swc-project/swc#7149]
### Describe the bug

Tried to build a plugin with swc_core@0.69.x and get 

```
   Compiling errno v0.2.8
   Compiling num_cpus v1.14.0
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/tim/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.8/src/lib.rs:20:33
   |
20 | #![cfg_attr(target_os = "wasi", feature(thread_local))]
   |                                 ^^^^^^^^^^^^^^^^^^^^^
```

> λ rustc --version
> rustc 1.65.0 (897e37553 2022-11-02)

However, compiles with `nightly-2022-09-23`

### Expected behavior

Compiles with stable rust

### Version

0.69

**Comment by thekip** [comment]
If it's intended, I think it should be written in Plugin doc page. Because as far as i remember not every nightly and even not every stable version of Rust would work [because of the issue](https://github.com/swc-project/swc/issues/6807)

**Comment by kdy1** [comment]
It's not intended, we don't maintain errno-0.2.8

**Comment by kdy1** [comment]
Oh, wait, you build `swc_ecma_transforms_testing` for wasm?
I think something is wrong there.

You can do like https://github.com/swc-project/plugins/blob/bb8f9a4b30a7130f50582f681db858ff98df921f/packages/emotion/transform/Cargo.toml#L33-L37 to avoid building the fixture testing system into the final Wasm file

**Comment by thekip** [comment]
Well, it builds with stable rust but for development / testing still need to use nightly, which is I thinking is not good. 
It may work well during dev, and not build in CI.   

Also, this configuration was generated by SWC CLI, maybe it should be updated (if not already) to split prod / dev deps?

**Comment by kdy1** [comment]
I'll update the plugin template

**Comment by kdy1** [comment]
Oh plugin template was correct

**Comment by thekip** [comment]
I think this could be closed.
