### ISSUE TITLE
Unable to make custom plugins work with next-swc 13.2.4 

### ISSUE THREAD

**Issue by thekip** [swc-project/swc#7150]
### Describe the bug

Related issue https://github.com/lingui/swc-plugin/issues/39

The custom plugin don't work in NextJS after updating to 13.2.4 

I followed https://swc.rs/docs/plugin/selecting-swc-core doc and updated swc_core dep to 0.69 and rust to `nightly-2022-09-23` (as in the SWC repo itself) and recompiled the plugin. 

It still doesn't work. The error message is unusual. It's not a LayoutError from rkyv as if the AST layout is changed. It's 

> memory allocation of 6182582528 bytes failed

With no more details. 

Platforrm: Mac m1 

I also tried bumping version to the latest 0.72 but had no luck. 

### Expected behavior

should work

### Version

0.69

**Comment by kdy1** [comment]
Closing in favor of https://github.com/vercel/next.js/issues/46989#issuecomment-1486989081

I'll publish a new version soon and document this issue.
