### ISSUE TITLE
[RFC] a new transform module type

### ISSUE THREAD

**Issue by cyjake** [swc-project/swc#7160]
### Describe the feature

as a bundler developer, which is called [porter](https://porterhq.github.io/porter), I've been migrating the code transformation layer to SWC in the past few weeks. previously the transform + minify processes are carried out separately, with Babel + UglifyJS namely. Since SWC can merge these two process, I'm trying to do it likewise in porter. 

But there are a few obstacles need to be cleared, currently porter uses a wrapping of CommonJS internally, the format looks like below:

```js
define(id, deps, function(require, exports, module) {
  // CommonJS script
});
```

With Babel + UglifyJS, this process is carried out like:

1. transform code with Babel, into CommonJS
2. wrap the result in said format
3. hand it over to UglifyJS to minify the code if production

With SWC however, step two needs to be merged into SWC, which leaves me with two options:

1. implement it as a SWC plugin
2. add a new transform module type

the first one seems legit at first, but the module type still needs to be set, ES Module couldn't be used because of the syntax, AMD, UMD, or SystemJS can't be used because of the different require behavior, CommonJS on the other hand, reserves the require/exports/module identifiers in the result, which bloats the bundle.

hence I've added the new module type to form a MVP, any advice about implementing this wrapping more elegantly and works with SWC better?

oh, about the conditional require I've mentioned in said pr https://github.com/swc-project/swc/pull/7159 , I think it can be refactored as a plugin or crate that is enabled by default. the usage is quite common in NPM packages, eliminating unnecessary requires helps the module resolving performance.

### Additional context

<https://porterhq.github.io/porter/swc>

**Comment by cyjake** [comment]
The original three steps process is still possible with SWC of course, which is the current implementation in porter. It is just that since we can do it in one pass, why should I stop at current place.

**Comment by kdy1** [comment]
Closing as I'll never accept this PR

**Comment by magic-akari** [comment]
How do you use SWC?

## 1. Introduction of SWC in Rust project.

In this case, `swc_ecma_transforms_module` can be completely skipped.
You can write your own module transforms to replace existing ones or import `swc_ecma_transforms_module::common_js` module to simplify operations.

> CommonJS on the other hand, reserves the require/exports/module identifiers in the result, which bloats the bundle.

If I didn't misunderstand, are the final function parameters renamed from `require` ?

SWC uses `mark` to mark a variable as the same reference, `swc_ecma_transforms_module::common_js` modules use `unresolved_mark` to determine if `require` is the global `require`. Passing the same mark should solve the problem.

## 2. Use precompiled SWC binary with SWC WASM plugin.

In this case, `swc_ecma_transforms_module` can still be skipped.

Use `ESM` module type, and transform all the import/export module statement in your plugins.

It's recommended to check swc implementation of the plugin ordering to ensure that no new `import/export` module statements are inserted after your plugin is executed.

**Comment by cyjake** [comment]
@magic-akari Thanks for the tips! Currently I'm using it through the node binding, `require('@swc/core').transform()`, with few plugins. Both advices seems promising, I'll give them a try.

> > CommonJS on the other hand, reserves the require/exports/module identifiers in the result, which bloats the bundle.
> If I didn't misunderstand, are the final function parameters renamed from require ?

Yep, the function parameters are require/exports/module just like CommonJS in node.js, which should be ok to be compressed or mangled. The benefit of this was that processing of CommonJS modules can be skipped.

**Comment by cyjake** [comment]
> Closing as I'll never accept this change
ouch! roger that, will try other approach as adviced by @magic-akari , thanks anyway!
