### ISSUE TITLE
`@swc/core-win32-x64-msvc` doesn't load inside node v18.15.0

### ISSUE THREAD

**Issue by viceice** [swc-project/swc#7161]
### Describe the bug

`@swc\core-win32-x64-msvc` doesn't load in node v18.15.0. It loads fine in node v18.14.2.

```
@swc/core@npm:1.3.42 STDERR Error: The specified module could not be found.
@swc/core@npm:1.3.42 STDERR \\?\c:\h\jenkins\workspace\xxx\node_modules\@swc\core-win32-x64-msvc\swc.win32-x64-msvc.node
@swc/core@npm:1.3.42 STDERR     at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
@swc/core@npm:1.3.42 STDERR     at Module.load (node:internal/modules/cjs/loader:1117:32)
@swc/core@npm:1.3.42 STDERR     at Module._load (node:internal/modules/cjs/loader:958:12)
@swc/core@npm:1.3.42 STDERR     at Module.require (node:internal/modules/cjs/loader:1141:19)
@swc/core@npm:1.3.42 STDERR     at require (node:internal/modules/cjs/helpers:110:18)
@swc/core@npm:1.3.42 STDERR     at Object.<anonymous> (c:\h\jenkins\workspace\xxxx\node_modules\@swc\core\binding.js:68:41)
@swc/core@npm:1.3.42 STDERR     at Module._compile (node:internal/modules/cjs/loader:1254:14)
@swc/core@npm:1.3.42 STDERR     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
@swc/core@npm:1.3.42 STDERR     at Module.load (node:internal/modules/cjs/loader:1117:32)
@swc/core@npm:1.3.42 STDERR     at Module._load (node:internal/modules/cjs/loader:958:12) {
@swc/core@npm:1.3.42 STDERR   code: 'ERR_DLOPEN_FAILED'
@swc/core@npm:1.3.42 STDERR }
@swc/core@npm:1.3.42 STDERR @swc/core was not able to resolve native bindings installation. It'll try to use @swc/wasm as fallback instead.
```

### Input code

```typescript
node -e 'require("@swc\core-win32-x64-msvc")'
```

### Expected behavior

native module loads

### Actual behavior

native module doesn't load

### Version

1.3.42

**Comment by viceice** [comment]
`@swc/core-linux-x64-gnu@1.3.42` works fine on linux with node v18.15.0

**Comment by Brooooooklyn** [comment]
@viceice this is not a bug of SWC nor Node.js, ref: https://github.com/npm/cli/issues/4828

**Comment by viceice** [comment]
@Brooooooklyn It's not a npm issue, because the module is there. I verified that file exists before.  I'm using yarn v3+ to install with node_modules linker

**Comment by viceice** [comment]
Use this minimal test file
```json
{
  "name": "test",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@swc/core-win32-x64-msvc": "1.3.42"
  }
}
```

```console
npm i --no-package-lock
node -e 'require("@swc/core-win32-x64-msvc")'
```

**Comment by Brooooooklyn** [comment]
@viceice what are you expected from `node -e 'require("@swc/core-win32-x64-msvc")'` ?

You should try `node -e 'console.log(require("@swc/core-win32-x64-msvc"))'`

![图片](https://user-images.githubusercontent.com/3468483/228616912-5650c2d7-dc9d-411e-a587-cbf0ea688ef8.png)


> node -e 'require("@swc\core-win32-x64-msvc")'

this is invalid, `\` should be `/` in package name

**Comment by viceice** [comment]
yes, sorry. it's not a swc error, but a windows docker issue. please see the linked nodejs issue.

**Comment by viceice** [comment]
the solution is to install the Microsoft VC++ libs.

not sure if the is an option to detect the missing libs on a new plain system
