### ISSUE TITLE
Property set by extended class overwritten if type is redefined in subclass

### ISSUE THREAD

**Issue by x3cion** [swc-project/swc#7167]
### Describe the bug

The input code produces following for B:

```
class B extends A {
    constructor(...args){
        super(...args);
        _defineProperty(this, "config", void 0);
    }
}
```

This overwrites the config property, although its set in the parent constructor and shouldn't be altered.

### Input code

```typescript
interface ConfigA {
    a: string;
}

interface ConfigB extends ConfigA {
    b: string;
}

const configs: Record<string, ConfigA | ConfigB> = {
    a: { a: 'a' },
    b: { a: 'a', b: 'b' }
}


class A {
    config: ConfigA;
    constructor(config: ConfigA) {
        this.config = config;
    }   
}

class B extends A {
    config: ConfigB;
}

const b = new B(configs['b']);

b.config === configs.b // should be true
```

### Config

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "jsx": false,
            "dynamicImport": false,
            "privateMethod": false,
            "functionBind": false,
            "exportDefaultFrom": false,
            "exportNamespaceFrom": false,
            "decorators": false,
            "decoratorsBeforeExport": false,
            "topLevelAwait": false,
            "importMeta": false
        },
        "transform": null,
        "target": "es2021",
        "loose": false,
        "externalHelpers": false,
        "keepClassNames": false
    },
    "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.43&code=H4sIAAAAAAAAA3WQzwqDMAzG74LvkJsTRO86B3NvsOvYwdaqBWnBVDZwvvvin3absEBLm37J70ulMqKvSy7golUtmzOMvgcUZQpoeqmazPcm3%2FM9uVMWIJ5GqAr3lWxfybVCA3xRYQpXwXVfHVdN5Kpftu8J8i8T47wFZQBT5NrbXDRfAkZvG4lYXYkIzssKTS0kc1miD9zo%2FrBThLZyDtNKjFcBeVoPW4uJlh1vQX6%2B4w%2B8%2BP0ORh2VeECxOcAbDXIPs1nBHDS3WIwZJAlgq4euAiaA%2FIs3jKTBQb0BAAA%3D&config=H4sIAAAAAAAAA1VPSQ7DIAy88wrkcw9tjv1DH4GoExGxCTtSUZS%2FFxJIm5s9i2e8CilhJg1PuZaxLFElwnTuBaHsWX0KApwjkk4mMtw6y1SpUVnCHdoOBlilCbm6kIb78GgOsCEQdkfDnPFmzP%2BZOriYkOgqrFLlJ4vXRNFSwYX3spPtl9q3NijXXPAzwU%2FZE8%2FrYOjV7ZwWFNsXnyAMiRwBAAA%3D

### Expected behavior

Property set in super constructor should not be overwritten without assignment in the subclass.

### Actual behavior

Property set in super constructor is overwritten by subclass constructor, even without assignment in subclass.

### Version

1.3.43

**Comment by magic-akari** [comment]
Do you mean [useDefineForClassFields: false](https://play.swc.rs/?version=1.3.43&code=H4sIAAAAAAAAA3WQzwqDMAzG74LvkJsTRO86B3NvsOvYwdaqBWnBVDZwvvvin3absEBLm37J70ulMqKvSy7golUtmzOMvgcUZQpoeqmazPcm3%2FM9uVMWIJ5GqAr3lWxfybVCA3xRYQpXwXVfHVdN5Kpftu8J8i8T47wFZQBT5NrbXDRfAkZvG4lYXYkIzssKTS0kc1miD9zo%2FrBThLZyDtNKjFcBeVoPW4uJlh1vQX6%2B4w%2B8%2BP0ORh2VeECxOcAbDXIPs1nBHDS3WIwZJAlgq4euAiaA%2FIs3jKTBQb0BAAA%3D&config=H4sIAAAAAAAAA22QzQqDMBCE7z6F5Oyh9dhri7c%2BRNCNRPIjOxEU8d0brbEKvSWz38wsO2d5LjrU4pHP8Rk%2FgaWD8mwPKYoD6EVKO6o8P40EKk2mQUSUNKANW4pvQC8ZxGc3JhfkGBURpp5Qs%2B6DKNI0YPybEyS3FFYXobyV990hjPeg5Ng1q51W07mz9rZnAq7gikrXGro2ZnursL4ZtmE6Rtx33SCmWe86iB%2BZGo90ofFO9sADZcsHfxemLV0BAAA%3D)?
