### ISSUE TITLE
props key of window is transformed

### ISSUE THREAD

**Issue by ClarkXia** [swc-project/swc#7174]
### Describe the bug

Object has a key of `window` is been transformed to _$window. when window is used outside of a function.

### Input code

```typescript
const isBrowser = typeof window !== "undefined";

function test({
  window
}) {
  create({ window })
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "chrome 44"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.44&code=H4sIAAAAAAAAAzXMQQqAIBBG4f2c4s%2BVnSHcdJPQEdzMhI5IhHePoJYPPl5UaYbS9qqjcUWAXSdrxiiSdGAJAa5L4lyEk9uIcpdoRQXGzfxN%2BCjNFW%2FFyoexv%2F%2FDXGnSA6wxs91nAAAA&config=H4sIAAAAAAAAA1WOSw6DMAxE9zlF5HWXqIveoYeIUkNT5Sc7VEWIu5NAQmFnz4yfZxZSwoc1POScx7xERYx07FnhySf1ywqkKSJrMjHBrbmJi9Ury7hJy%2B6ADYGxOVVzxpt%2BOrN1cJGQ%2BRosUeUHi1eyqHRw4TVuZu1cepV%2ByHf4h9qzAwyGn%2B0y0bhr6L8nkKIBU2kD%2Bk3Boey6jSiWFRxKM0YqAQAA

### Expected behavior

The property key should not be transformed

### Version

1.3.44

**Comment by kdy1** [comment]
I tried using targets, and I think this is a bug in one of `bugfix` transforms.

https://play.swc.rs/?version=1.3.44&code=H4sIAAAAAAAAAzXMQQqAIBBG4f2c4s%2BVnSHcdJPQEdzMhI5IhHePoJYPPl5UaYbS9qqjcUWAXSdrxiiSdGAJAa5L4lyEk9uIcpdoRQXGzfxN%2BCjNFW%2FFyoexv%2F%2FDXGnSA6wxs91nAAAA&config=H4sIAAAAAAAAA22PSwrDMAxE9z6F0bqLttAueocewrhKcPEPS4GakLvXTuyQQnfSvJE0moWU8CYNDzmXsjRRJcK090Wh7Fl9igKcI5JOJjKcOmWqaFCWcJWWjYANgbCTpjnjzZCPu3VwMSHRr7FalR8t%2Ft3MKo3INQ%2FS9Xy5gWgMXHhN61D7pebdfPeDqYfYD4KhZ5%2FkNKFYvl%2FKJckXAQAA
