### ISSUE TITLE
Can not import named-export from transpiled cjs

### ISSUE THREAD

**Issue by snowyu** [swc-project/swc#7180]
### Describe the bug

The transpiled cjs code can not be imported by named. Only workaroud is: `import lib from 'lib'; const fn = lib.fn`

```
//test.mjs
import {fn} from 'lib';
```

The codes to be transpiled:

### Input code

```js
// fn.js
export function fn(){}
export default fn
```
```js
// fn2.js
export function fn2(){}
export default fn2
```

```typescript
//index.js

export * from './fn.js'
export * from './fn2.js'
```

### Config

```json
{
  "jsc": {
    "target": "es2015",
    "keepClassNames": true,
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true,
    },
    "minify": {
      "compress": false,
      "mangle": false,
    },
    "transform": {
      "legacyDecorator": true,
    }
  },
  "module": {
    "type": "commonjs",
    "importInterop": "node",
  },
}
```

### Expected behavior

Can be imported by name.

### Actual behavior

raise error:

```
SyntaxError: Named export 'fn' not found. The requested module 'lib' is a CommonJS module, which may not support all module.exports as named exports.
```

### Version

1.3.42

### Additional context

```
@swc/cli: 0.1.62
@swc/core: 1.3.42
node: v18.15.0
```

**Comment by magic-akari** [comment]
You should use `importInterop : node`

https://swc.rs/docs/configuration/modules#importinterop

**Comment by magic-akari** [comment]
This is due to the limitation of  transpiled `export *` cannot be statically detected in commonjs.(https://github.com/nodejs/cjs-module-lexer)

This is an unfixable issue.

**Comment by magic-akari** [comment]
I tested it locally and found that it works fine.

**Comment by snowyu** [comment]
Sorry, my fault it should two function files to test:

https://replit.com/@snowyu/swc-node-interop#index.mjs
