### ISSUE TITLE
remeda findIndex.lazy behaves differently when running in dev mode vs. built

### ISSUE THREAD

**Issue by cassus** [swc-project/swc#7181]
### Describe the bug

[remeda](https://github.com/remeda/remeda) findIndex.lazy behaves differently when running in dev mode vs. built in a NextJS app

### Input code

```typescript
import { pipe, findIndex } from "remeda"

console.log(
    pipe(
      ["1", "2", "3"],
      // uses 'lazy' mode
      findIndex((g) => g === "3"),
      (x) => x,
    ),
    pipe(
      ["1", "2", "3"],
      (x) => findIndex(x, (g) => g === "3"),
      (x) => x,
    ),
  )
```

### Config
- no .swcrc file

- using the default NextJS config, with {swcMinify: true}

### Expected behavior

logs `2 2` to the console both in dev mode and when built

### Actual behavior

- in dev mode
  - logs `2 2` to the console both 
- when built
  - logs `undefined 2` to the console both 

### Version

next@npm:13.2.4 -> "@next/swc-darwin-arm64": 13.2.4

**Comment by cassus** [comment]
Also happens with `{swcMinify: false}` in next.config.js

**Comment by kdy1** [comment]
If so it's not a bug of swc
