### ISSUE TITLE
@swc/core 1.3.44 crashes when used with @swc/jest

### ISSUE THREAD

**Issue by mbriziarelli** [swc-project/swc#7183]
### Describe the bug

I was using @swc/core 1.3.42 and @swc/jest 0.2.24 to run tests on my MacBook Pro M1 Apple Silicon. 
I upgraded @swc/core to version 1.3.44. The test cannot be run anymore, the terminal is reporting a `SIGSEGV` error and all jest related subprocesses are killed.
I switched back to @swc/core 1.3.42 and the tests are running fine again.

### Input code

```typescript
// My jest configuration
const commonConfig: Config = {
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest', swcConfig as Record<string, unknown>],
  },

  restoreMocks: true,
  rootDir: process.cwd(),
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/build/',
    '<rootDir>/.next/',
    '<rootDir>/.yalc/',
  ],
  moduleNameMapper: {
    '\\.(css|less|scss|sass|sss|styl)$': 'identity-obj-proxy',
    '\\.(svg|jpe?g|png|gif|pdf|xlsx)$': '<rootDir>/testing/module-mappers/dummy-image.ts',
    ...aliases,
  },
  snapshotFormat: {
    escapeString: true,
    printBasicPrototype: true,
  },
}
```

### Config

```json
// my SWC configuration
const swcConfig: SWCConfig = {
  jsc: {
    experimental: {
      plugins: [['jest_workaround', {}]],
    },
    parser: {
      syntax: 'typescript',
      tsx: true,
    },
    target: 'es2021',
    keepClassNames: true,
  },
}
```

### Expected behavior

I can upgrade @swc/core to the latest version and run my tests using @swc/jest without crash.

### Actual behavior

If I upgrade @swc/core to 1.3.44, all the jest unit tests using @swc/jest are crashing. `SIGSEGV` error. 

### Version

1.3.44

**Comment by mbriziarelli** [comment]
If this can help you, this is the crash log taken from MacOS Console App
[crash.log](https://github.com/swc-project/swc/files/11122285/crash.log)

**Comment by kdy1** [comment]
I'm using M1 mac too, and I ran it locally, I guess...
I'll check it again

**Comment by kdy1** [comment]
Ah, you are using `jest_workaround`. It's the cause.
cc @magic-akari 
I'll check if I can implement backward compatibility without bloating binary

**Comment by magic-akari** [comment]
what's the version of jest_workaround you are using?
It should be upgraded as well.

**Comment by morlay** [comment]
Not just in jest. with my custom cli, I got same error


```
with exit code 139 (interrupted by signal 11: SIGSEGV)
```

```
$ node --version
v19.6.0
$ pnpm --version
8.1.0

```

revert to `@swc/core 1.3.42`, everything works well.


By the way. `@swc/core 1.3.44` run with tsx works well too `tsx ./src/bin/index.ts`. 
may some wrapper could save this issue.

**Comment by mbriziarelli** [comment]
@kdy1 . I'm not using `NODE_OPTIONS='--experimental-vm-modules' ` like in your example. Maybe it has an influence. Let me try.

**Comment by magic-akari** [comment]
> @magic-akari . I'm using jest_workaround 0.69.0 with jest: 29.5.0

You could try upgrade to 0.72.6

**Comment by mbriziarelli** [comment]
@magic-akari : problem solved ! Thank you so much and thank you also to @kdy1 for quick answer.
I confirm that swc/core@1.3.44 + jest_workaround@0.72.6 altogether solve the problem.
My jest tests are running like before.

**Comment by mbriziarelli** [comment]
And I add: without changing anything else in my jest configuration. Just upgrading the dependencies and it works out of the box.

**Comment by magic-akari** [comment]
What is the recommended approach for plugin authors?  @kdy1 
Currently, I am keeping the plugin version number in sync with the rust version number of `swc_core`.
For better user comprehension, should I change it to match the npm version number of `@swc/core` ?

**Comment by kdy1** [comment]
I think the rust version would be better.
The reason is that there are multiple runtimes, and https://swc.rs/docs/plugin/selecting-swc-core exists
