### ISSUE TITLE
Next Build / SWC - Compiler bundles unused js code in static chunks when not precompiling typescript sources before

### ISSUE THREAD

**Issue by gurkerl83** [swc-project/swc#7192]
### Describe the bug

The bug report was originally created in the Next repo; here is the link https://github.com/vercel/next.js/issues/47738. The SWC repo seems the correct place to re-describe the problem.

Use a mono repo structure without a pre-compilation step in the respective modules e.g.

```
packages
	- common
		- src
			- components
				- CompA
				- CompB
				- CompC
				- index.ts export all components e.g. export { CompA } from './CompA'
			- index.ts export all components export * from './components'
		- package.json references index.ts; because it is no precompilation step involved, we do not reference something like /dist/index.js
```

```
pages
	- A <= use CompA and CompB in page A // import {CompA, CompB} from 'common'
```

Execute the next build with bundle analyze attached, respectively look at the static/chunks/pages folder
**All components in the common module are bundled, most importantly CompC, even not used on the page**

### Expected behavior

The swc compiler should apply tree-shaking bundling only components which are actually used by a page and not all exports defined in a mono repo module. The expected behavior is that it should not matter if the compiler sees either js or ts; unused components have to be always omitted from bundling in the final js file because this gets sent to the user.

### Actual behavior

All components in the common module are bundled, most importantly CompC, even not used on the page. Precompiling the typescript of a mono-repo before using it on a page actually omits unused components. However, when the compiler sees the mono-repo in a typescript form tree-shaking is not applied, and unused components get bundled in the final js file.

### Version

Unknown, tested on latest Next version as well as canary version 13.2.5-canary.20

### Additional context

Doing all steps identically but executing a build process of the individual modules of a mono repo does not produce this overhead; CompC gets not included in a js bundle in the static/chunks/pages folder.

Looking at the source code of the SWC-compiler, respectively the Visitor.ts file here https://github.com/swc-project/swc/blob/main/node-swc/src/Visitor.ts, depending on what the compiler sees, raw typescript files, or js bundles, different handling is executed (export/import/namespaces). 

I do not know any internals here, but it seems either the typescript option is incomplete or an tree-shaking optimizing step is skipped when the compiler sees typescript files from a monorep module. 

Imagine when you have, instead of a lightweight CompC, a much larger typescript file with imports from external dependencies, although I still need to check if external libraries of js are also increasing the final bundle. 

Either way, this produces much larger bundle sizes; in our case, the bundle size doubles. 

The only solution right now is to execute a prebuild step to compile the typescript version of modules used to javascript and feed the result to pages.

A lot of folks are probably unaware of those consequences, meaning at least the documentation has to provide a hint to avoid this problem, or you fix it in the swc compiler.

**Comment by kdy1** [comment]
Please provide a repro

**Comment by gurkerl83** [comment]
I provide a repo, but why closing with reason "not planned"?

**Comment by kdy1** [comment]
Because there's no repro
