### ISSUE TITLE
Finish auto accessor and stage 3 decorator

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#7193]
### Describe the feature

I implemented the stage 3 decorator partially with https://github.com/swc-project/swc/pull/6950, but I need to handle

 - logic for duplicate keys
 - auto accessors

I decided to split the PR as auto accessor is another task, and support for duplicate keys has significantly lower priority

**Comment by miso-belica** [comment]
Sorry for being nosy but the https://github.com/swc-project/swc/discussions/5053#discussioncomment-5543835 is really confusing for me. Does this task mean finishing the whole spec of decorators as implemented in TSv5? I just want something to subscribe and know when it is done I can try swc again with my app. If this task is not the case, can you point me somewhere else, please? It seems you are the most competent person when it comes to decorators implementation in swc. Thank you for pushing this forward and your help 🙂

**Comment by yf-yang** [comment]
@miso-belica I found this https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion, not sure when the doc was updated, in my scenario it works.

**Comment by yay** [comment]
@yf-yang Thanks for the link. Any idea how to use this with React SWC plugin?
https://github.com/vitejs/vite-plugin-react-swc/issues/85
