### ISSUE TITLE
Peer dependency issue with `@swc/helpers`

### ISSUE THREAD

**Issue by utkdmr** [swc-project/swc#7207]
### Describe the bug

When installing `@swc/core` package, got the following peer dependency warning:

```
 @swc/core 1.3.45
 └── ✕ unmet peer @swc/helpers@">0.4.14 <0.5": found 0.5
```

There is no `@swc/helpers` version in that range.

The version condition for the package should be fixed.

### Expected behavior

Installing helper package without peer dependency warning.

### Version

1.3.45

**Comment by kdy1** [comment]
Closing as duplicate
