### ISSUE TITLE
@swc/core peerDependency of @swc/helpers is not optional

### ISSUE THREAD

**Issue by kgregory** [swc-project/swc#7212]
### Describe the bug

From the [getting started](https://swc.rs/docs/getting-started) section of the docs:

> ... run the following to download pre-built binaries:
>
> [pnpm]: pnpm i -D @swc/cli @swc/core

pnpm reports a missing peer dependency

```
devDependencies:
+ @swc/cli 0.1.62
+ @swc/core 1.3.46

 WARN  Issues with peer dependencies found
.
└─┬ @swc/core 1.3.46
  └── ✕ missing peer @swc/helpers@^0.5.0
Peer dependencies that should be installed:
  @swc/helpers@^0.5.0
```

This is because `@swc/helpers` was added as a peer dependency in #7147 and published as [1.3.45](https://github.com/swc-project/swc/releases/tag/v1.3.45)

The version was very recently adjusted in #7206 and published as [1.3.46](https://github.com/swc-project/swc/releases/tag/v1.3.46).

Was this done to declare compatible ranges or is this truly a requirement to use `@swc/core`?  If it isn't requirement, should `@swc/helpers` be made optional via [peerDependenciesMeta](https://pnpm.io/package_json#peerdependenciesmetaoptional)?

### Expected behavior

Peer dependency of `@swc/helpers` should be optional

### Actual behavior

`@swc/helpers` is a required peer dependency of `@swc/core`

### Version

1.3.46, 1.3.45

**Comment by magic-akari** [comment]
Thanks.
Use `@swc/core` with `@swc/helpers` is possible. 
We should only limit the version number of those who need `@swc/helpers`.

Therefore, it should be marked as optional.
