### ISSUE TITLE
Error for typescript code

### ISSUE THREAD

**Issue by aelbore** [swc-project/swc#722]
**Describe the bug**

**Input code**
Please see attached file
**Config**
Please see attached file

**Expected behavior**
It should compile the typescript code

**Version**
The version of @swc/core:  1.1.35

![swc-error](https://user-images.githubusercontent.com/18069807/76715687-5f383400-6768-11ea-82df-4c4f63304e5e.png)

**Comment by kdy1** [comment]
@aelbore It seems like a bad error reporting.
Syntax should be "typescript", not "typescipt"
