### ISSUE TITLE
Getting `segmentation fault` when running tests

### ISSUE THREAD

**Issue by omry-hay** [swc-project/swc#7227]
### Describe the bug

Getting a `segmentation fault` error when running unit tests.

### Config

```json
N/A
```

### Expected behavior

Run test without errors

### Version

1.3.44

### Additional context

This happens from `1.3.44` until `1.3.46`
Happens on my Mac and on GitHub actions (Ubuntu 20.04)
Using `swc/core` and `swc/core-darwin-x64` as dev dependencies.

**Comment by kdy1** [comment]
Closing as no repro
