### ISSUE TITLE
"hoist_props" results in incorrect code when optional-chaining with brackets

### ISSUE THREAD

**Issue by ashvinsrivatsa** [swc-project/swc#7228]
### Describe the bug

SWC produces incorrect output for a construct involving optional-chaining with brackets (`a.?[b]`) when the `hoist_props` option is enabled.

In the sample input code below, the issue goes away if instead of `something.getFoos()`, you have just `getFoos()`. It also goes away if you use non-bracket optional-chaining (e.g. instead of `foos?.[0]`, you have `foos?.bar`).

### Input code

```typescript
function f() {
    const foos = something.getFoos();
    return foos?.[0];
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": false,
        "booleans": false,
        "booleans_as_integers": false,
        "collapse_vars": false,
        "comparisons": false,
        "computed_props": false,
        "conditionals": false,
        "dead_code": false,
        "directives": false,
        "drop_console": false,
        "drop_debugger": false,
        "evaluate": false,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": false,
        "join_vars": false,
        "keep_classnames": false,
        "keep_fargs": false,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": false,
        "negate_iife": false,
        "properties": false,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": false,
        "switches": false,
        "typeofs": false,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": false,
        "const_to_let": false,
        "pristine_globals": false
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.46&code=H4sIAAAAAAAAA0srzUsuyczPU0jT0FSo5uVSAILk%2FLziEoW0%2FPxiBVuF4vzc1JKMzLx0vfTUEjegmIamNURZUWpJaVEeWJ29XrRBLFC4FgAhTma0TwAAAA%3D%3D&config=H4sIAAAAAAAAA32UPZLbMAyFe5%2FCozpFxkWKHCDdnoFDi6BMr0hoCNBrzY7vHujP62RBdRI%2BPEF8BPB5OB6bK7XN7%2BOnPMrLYDNBfr5LhMbE9i6RBtpoqc1h4ObHRq80IW97gjn0WEjDNnfAs4pOP0%2BnVdH0iASbYo3FkIIfX2u2GIcMRC8xiconS4TE9K9%2BZRk%2FNHBG7MGmPWQsmZAYOshaWot9bwcCc7MVHsW1QKgWmWhhcGbIOOgJyQUOmCSuYAfWmRYdaCxkaDncQBVKPREmkkPWsINz6br5vv%2FncLN9saxJ4T5fjvyyAi8YiI0vqhkL3JzgXL7DisnBmwxcslbyiiHVdO8A4kJviZKNqk9zhpfeqsNdaUhe%2BpdHhUuzq1eeoBNnTQhes3eyBzIHtWQGV1qY%2FG13cMUMCg4MeC9No%2BKPwO1FLcvjAOg1Ihdt1WMswFQHc%2BXTfOzgP3JQ1jttzYiWL3VKYzyjOlibHPiCbidBroOxjrOsjftQ5yU5kAYBp6YUUsE0tmwYTT%2Fv0O8dIpMi3zRdj%2BeXtbFmPJ7bOdrUfU3%2FsqAPa0IT0ZUZrqt%2FuuNlYf9qvpK23fz8hybQ26acJvjw%2BAsikoHlRgYAAA%3D%3D

### Expected behavior

The call to `something.getFoos()` is retained.

### Actual behavior

The call to `something.getFoos()` is removed, causing an observable change in behavior.

### Version

1.3.46

**Comment by kdy1** [comment]
Investigation: This only occurs while minifying with `transform()`
