### ISSUE TITLE
Block-scoped variable / arrow-function / for-loop interaction

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#723]
**Describe the bug**
for-loop incorrectly compacted to function body.

**Input code**
```ts
function foo() {
  const lod = { 0: { mig: 'bana' }};

  for (let i = 0; i < 1; i++) {
    const { mig } = lod[i];

    return false;

    (zap) => zap === mig;
  }

  return true;
}
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

**Expected behavior**
Running this code through `node` directly and invoking `foo` I get the expected output `false`, thanks to the early-return in the for-loop.

```
$ node src/index.ts
false
```

Running through `swc` first, I see the `true` fallback, due to the function-wrapping of the for-loop body.
```
$ swc src/index.ts | node
true
```

The TypeScript compiler rejects this code as invalid;

```
$ tsc src/index.ts
src/index.ts(4,3): error TS4091: Loop contains block-scoped variable 'mig' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher.
```

**Version**
The version of @swc/core: 1.1.35

**Comment by kdy1** [comment]
Fixed with `swc@1.1.49`. Sorry for delay.
