### ISSUE TITLE
`asciiOnly` option in minify ignored

### ISSUE THREAD

**Issue by tquetano-netflix** [swc-project/swc#7240]
### Describe the bug

When using the minifier, even with `format.asciiOnly = true` set, it seems to revert escaped unicode to its original format.

### Input code

```typescript
export default {
  \u3131: '\u11B0',
  '\u3141': '\u11B1',
  ['\u3142']: '\u11B2',
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": {
        "dead_code": true,
        "drop_console": true,
        "drop_debugger": true,
        "passes": 3
      },
      "format": {
          "asciiOnly": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.49&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUajmUlCIKTU2NDa0UlCPKTU0dDJQ1wGKqYMETQzVYaKGYNFoiLCReixM3AgoXgsAr%2BRefFQAAAA%3D&config=H4sIAAAAAAAAA32RwU7DMAyG73uKKucdQAhp4h0Qj4BM61QpSRzF6bRq6rvjZs1IoXBJ4%2B%2B3m9%2F29dA0auBWvTRXuUoQIDLGeyyEJ5%2FgIkRh64DbaEJSx6IOvEgaLGNG801RCWKPKVfx85quLBGjsBRHXJEz3uipfq8lFyIyV0xoh9C9t9Rty29SpCCSZ7J%2FqR1%2BjH2f%2B%2FohB2DG5a2nlc331jRFB2ljQ6hMwJg3b6f1X7%2FKHPg%2BG6ncJwoWz2jLqCoDn4ji3ooNDy472c3Q%2F6ohmjMklC%2BFvSSDpx3KoCGax4fNAqWVQzlzU8pRN1YNqTSFJVoW5cgPrL4zyzLLkJXh11KdhzV%2FAZYANHlyAgAA

### Expected behavior

No "restoration" of escaped values, just keeping them as-is.

```js
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),Object.defineProperty(exports,"default",{enumerable:!0,get:function(){return _default}});var _default={\u3131: '\u11B0',\u3141: '\u11B1',\u3142: '\u11B2'};
```

### Actual behavior

All escaped unicode values are restored to their prior versions:

```js
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),Object.defineProperty(exports,"default",{enumerable:!0,get:function(){return _default}});var _obj,_default=((_obj={ㄱ:"ᆰ",ㅁ:"ᆱ"})["ㅂ"]="ᆲ",_obj);
```

### Version

1.3.49

### Additional context

I tested this on older versions as well, and am getting the same output, so this appears to be consistent.

Interesting side-note: in my local output, I actually see the values are retained:

```js
{ㄱ: "\u11B0",ㅁ: "\u11B1",ㅂ: "\u11B2"}
```
However, object properties are restored to originals as they are in the playground.

**Comment by kdy1** [comment]
I investigated this, and there are several problems.

https://play.swc.rs/?version=1.3.49&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUajmUlCIKTU2NDa0UlCPKTU0dDJQ1wGKqYMETQzVYaKGYNFoiLCReixM3AgoXgsAr%2BRefFQAAAA%3D&config=H4sIAAAAAAAAA31RQU7EMAy87ysqnzmAEAjxB8QTkLd1S5YkjuJ0RbXq33HTZmmhcEmTGXs6Hl8OVQUnqeG5uuhVHwGjULy%2BFZHBJ%2FxUBKh2KHU0IcFNYU8yUS1aoQyNMwPcp9CntU79PklPEKiKMbCpTxi7mSR5WOTBMgsplmJPC%2BSMN%2B2w0WUXIomsMEUbwuat5mbbPlORg1Je2P7FNnTsuy7n8IMOKELTv%2B4XbLxG0XJ0mDY2qmXWV2%2BHRetXm0PfZSMr94mDpTPZEu3KwAeRurdqw6PLTnYr2n%2FZEM0ZE%2BmXw16RoacdVLDFaO5uNwvXUQ7lzEOB46ZfDQRpCDQv9hG%2Bi8oeS75g5KU05pzGLy8YStmdAgAA


 
- There's `jsc.output.charset=ascii` but we should use `format` if `jsc.output` is not specified.
- Documentation is not enough
- ascii_only of swc_ecma_codegen does not handle property names.

I'll work on all of them soon
