### ISSUE TITLE
Minifier does not remove PURE calls with sequence expression

### ISSUE THREAD

**Issue by devongovett** [swc-project/swc#7241]
### Describe the bug

SWC does not respect PURE annotations on function calls with a sequence expression, e.g. `/*#__PURE__*/ (0, forwardRef)(Test)` whereas `/*#__PURE__*/ forwardRef(Test)` works correctly. This code with the sequence expression is often generated by transpilers and bundlers.

### Input code

```typescript
(function () {
function forwardRef() {
    return something();
}

function Test() {
    return 'Test';
}
const _Test = /*#__PURE__*/ (0, forwardRef)(Test);
function Other() {
    return 'Other';
}
const _Other = /*#__PURE__*/ (0, forwardRef)(Other);


console.log((0, _Test));

})();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": true,
      "mangle": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.49&code=H4sIAAAAAAAAA4WPwQrCMAyG732KgIelQ5x38ejZMfRcZLbbYDbQdniQvbtNDnPowdzy98uXBt3k2zSQB9TwUkvnKDxv4d5YJznkCjZNwUOkh0394DvUBzUr9Zm52Ji%2B6YLDgsGWfExguIcjVOXGmPranIwpK8D9drVRI0PZvpjPqbfhRy3p2i3BX7lQ2a5kjEa7G6lDpuRzmp9mna97A%2FgQhbocAQAA&config=H4sIAAAAAAAAA12PPQ7DIAyF95wCee5QMXToHXoIRJ2ICALCTlUU5e6h%2FKRVN%2Ft7fvbzNggBM2m4iy2XuQkqEsazz4TSwuqdCaB2inQ0geHS1Zk%2B0qgsYUF7VYBVnJCLi%2BRVyuYA6z1hdzTmzGLG9HtTexciEmXGccXzmlPLZPGPsg8WX2grrSmGlgScf67F0f7jFLCmusF3qAfoa8HQoxvL0v0AMOH1HyoBAAA%3D

### Expected behavior

The `Other` function in the input code should be removed because the `forwardRef` call is pure. This is already the case without the `(0, forwardRef)` syntax ([example](https://play.swc.rs/?version=1.3.49&code=H4sIAAAAAAAAA9NIK81LLsnMz1PQ0FSo5oLz0vKLyhOLUoJS08DiCkBQlFpSWpSnUJyfm1qSkZmXrqFpzVXLxYXQE5JaXIKuWh0kqA5SmJyfV1yiEA%2FiK9gq6Gspx8cHhAa5xsdr6SPbBpIHGgw31L8kI7UIw1SwKLKxYAF85oIVAA3mAuvIz0nVy8lP19Aw0IE4SRMkVasJ9BMAR2Lg9xIBAAA%3D&config=H4sIAAAAAAAAA12PPQ7DIAyF95wCee5QMXToHXoIRJ2ICALCTlUU5e6h%2FKRVN%2Ft7fvbzNggBM2m4iy2XuQkqEsazz4TSwuqdCaB2inQ0geHS1Zk%2B0qgsYUF7VYBVnJCLi%2BRVyuYA6z1hdzTmzGLG9HtTexciEmXGccXzmlPLZPGPsg8WX2grrSmGlgScf67F0f7jFLCmusF3qAfoa8HQoxvL0v0AMOH1HyoBAAA%3D)), and Terser also removes it.

### Actual behavior

SWC does not remove treat the `forwardRef` call as pure when written as `(0, forwardRef)`. Some libraries and bundlers produce code like this to avoid setting any `this` context.

### Version

1.3.49

### Additional context

This can commonly affect libraries in the React ecosystem which use `forwardRef` a lot, leading to applications including many unused components. We noticed this in a Next.js project while investigating https://github.com/adobe/react-spectrum/issues/4356. Disabling the `swcMinify` option in `next.config.js` reduces the bundle size.

**Comment by kdy1** [comment]
I investigated this, and the problem is that `/*#__PURE__*/` is attached to `0, forwardRef`.

**Comment by kdy1** [comment]
And the minifier itself does not have a problem. I think this is related to _moving_ of comments.

**Comment by devongovett** [comment]
Thank you!
