### ISSUE TITLE
Invalid variable assignment name change in ES5 with eval

### ISSUE THREAD

**Issue by coalman** [swc-project/swc#7253]
### Describe the bug

The compiled code assigns a variable that doesn't exist `bmRnd1`. The variable declaration isn't renamed to match the assignment. I ran into this with `lottie-web@5.7.12` (build/player/lottie.js file). Upgrading that dependency fixed the problem (bmRnd is just a function definition in the updated code).

### Input code

```typescript
var bmRnd;
function a() {
  bmRnd = function () {};
}
eval('');
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.49&code=H4sIAAAAAAAAAz2KTQqAIBBG93OKb6eeYegSLdpbagQ2gqmb8O4JQsv302zGfq%2FimChUOcqVBDlVcZuN1T86RHsavIS5YcG%2F6WbjTED2pWbBMDy4M3UiP0grZfgDK1lJ%2FmUAAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYygZyCxKLi1CI4HyhSXJlXklgBFFFKTc5NLE4uyiwoUdKByWYVg6TSEnOKU8FCtRAZpZLEovTUErCuYlOw8lquWgDsxhJabwAAAA%3D%3D

### Expected behavior

swc should rename (or not rename?) both the variable declaration and the variable assignment to `bmRnd`.

### Actual behavior

swc renames the variable assignment to a different name from the variable declaration. This results in a runtime error for the built code.

### Version

1.3.46

### Additional context

I'm not 100% sure if this is expected in ES5 with eval (maybe it is?).

**Comment by zhaomenghuan** [comment]
I have also encountered a similar issue. Is there any progress on this problem now?

```
function fn() {
  fn = function () {
    return {};
  };
}

eval('');

function callFn() {
  fn();
}
```

This code will be compiled into the following content：

```
"use strict";
function fn1() {
    fn1 = function fn1() {
        return {};
    };
}
eval("");
function callFn() {
    fn();
}
```

If there is no eval expression, this is as expected. it will be compiled into something like this.

```
"use strict";
function fn() {
    fn = function fn() {
        return {};
    };
}
function callFn() {
    fn();
}
```

**Comment by hyf0** [comment]
I'm going to keep investigating this Sunday. I have found the cause and need to apply an appropriate fix.
