### ISSUE TITLE
Bug in instance method definition in node with `es2019` target since version 1.3.40

### ISSUE THREAD

**Issue by gheorghetutunaru** [swc-project/swc#7260]
### Describe the bug

Since `@swc/core` version 1.3.40, the way instance methods are handled has changed.

When running a service locally and calling an instance method not defined in the class directly, but later using `class.prototype.functionName = function() {}`, it gives an error that the method is not defined : `user.validate is not a function  > TypeError: user.validate is not a function` and the value of `user.validate` is actually `undefined`.

If I change the instantiation to be inside the class (like in `UserB` in the playground) it works as before. On version 1.3.39 both types of instantiation work as expected.

### Input code

```typescript
class UserA {
  password: string;

  validate!:(password: string)=> boolean;
}

UserA.prototype.validate = function(password) {
  return this.password === password;
}

const user = new UserA();
user.validate("hello");



class UserB {
  password: string;

  validate(password: string){
    return this.password === password;
  }
}
const userB = new UserB();
userB.validate("hello");
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2019",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.40&code=H4sIAAAAAAAAA42PQQ6CMBBF9yTcYWRFNxwAUxN7Bw9QoUqTpkPaAWIMd7eUUI26YDkz%2F%2F95vzHSe7h45c7wzDOAPswTurYGT07b%2BzHPlvUojW4lqUNdfisYP8EV0Shpg3he9DGv6h0S0qNX1eYGDrfBNqTRphi2%2FnWKBmeBOu2r7QSc8wS0ZTdoPcEQPoQ0q6YVvmThvizTr7LolDFYsNggOlNXsavrb9Po2scKMEfgN6744BWJV%2FwBfgFRMyd6lQEAAA%3D%3D&config=H4sIAAAAAAAAA1VPSQ7CMAy85xWRzxyAAxL8gUdEwa2Csil2JaKqfydpk0Jv9iye8SykhDdpeMi5jGWJKhGmfS8IZc%2FqUxDgHJF0MpHh1FmmSg3KEq7QsjHAKo3I1YV0PV%2FuzQE2BMLuaJgz3gz5P1MHFxMSHYVVqvxo8ZgoWiq48JpWsv1S%2B24NbvAT9bD9MBh6dienCcXyBaIK9Y0XAQAA

### Expected behavior

The method should be well defined even for the `UserA` example

### Version

1.3.40

**Comment by kdy1** [comment]
Thank you for the explanation!

**Comment by gheorghetutunaru** [comment]
Thank you for the explanation ! Since it worked before in our Node.js environment I assumed that it was an `swc` issue, but in the end all I had to do was replace `validate!` by `declare validate` 🤦
