### ISSUE TITLE
Mangling redeclares variable in destructuring when `eval()` is present

### ISSUE THREAD

**Issue by nolanlawson** [swc-project/swc#7261]
### Describe the bug

When `eval()` is present, the SWC minifier may redeclare a variable that has already been declared, leading to a syntax error when the JavaScript is parsed by the browser.

This only occurs when `eval()` is present, and it only occurs with `{ mangle: true }`.

### Input code

```typescript
export function func(a, b) {
  const { c: d } = a;
}
eval('');
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.50&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMzwMzNBJ1FJI0Faq5FBSS8%2FOKSxSqFZKtFFIUahVsFRKtuWq5UssSczTU1TWtAUyFWmI%2BAAAA&config=H4sIAAAAAAAAA32QSw7CMAxE9z1F5TULQAIh7sAZkBWcKiVprDhUVIi7k34C5SM2%2Bcy8iZW5FWUJtSjYl7d0TBfGIBSe96RI10S8JgVIORQVDEdYZLeW3tJohQbpPjoQMVQUh5Ssl6vNlADrvVBOTJozjdHdfKbyjgOJvIM9ik1laYb2ozxbasl%2Bwsk6E%2FFRWRRp0NHXc5nQf10OpsVIaff8CzK0%2B6EKagxmtXxrJ%2FVT5HVoCpw%2FXWYfgtgxja1t4QXlgp5DwMghJ2O4UHF%2FAE8y38fLAQAA

### Expected behavior

The variable should not be redeclared, and there should be no syntax error.

### Actual behavior

The output is:

```js
export function func(c, n) {
    const { c: n  } = c;
}
eval('');
```

Note that the variable `n` is redeclared. If you run this in a browser you will get the error:

    SyntaxError: Identifier 'n' has already been declared

Here is [a repro](https://codepen.io/nolanlawson-the-selector/pen/WNarXmB) you can load in a browser.

You can also verify with ESLint. [Here is a repro in the ESLint Playground](https://eslint.org/play/#eyJ0ZXh0IjoiZXhwb3J0IGZ1bmN0aW9uIGZ1bmMoYywgbikge1xuICAgIGNvbnN0IHsgYzogbiAgfSA9IGM7XG59XG5ldmFsKCcnKTtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOlsiZXJyb3IiXSwiZm9yLWRpcmVjdGlvbiI6WyJlcnJvciJdLCJnZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOlsiZXJyb3IiXSwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8tY2xhc3MtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbXBhcmUtbmVnLXplcm8iOlsiZXJyb3IiXSwibm8tY29uZC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3QtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZHVwZS1hcmdzIjpbImVycm9yIl0sIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby1kdXBlLWVsc2UtaWYiOlsiZXJyb3IiXSwibm8tZHVwZS1rZXlzIjpbImVycm9yIl0sIm5vLWR1cGxpY2F0ZS1jYXNlIjpbImVycm9yIl0sIm5vLWVtcHR5IjpbImVycm9yIl0sIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1lbXB0eS1wYXR0ZXJuIjpbImVycm9yIl0sIm5vLWV4LWFzc2lnbiI6WyJlcnJvciJdLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOlsiZXJyb3IiXSwibm8tZXh0cmEtc2VtaSI6WyJlcnJvciJdLCJuby1mYWxsdGhyb3VnaCI6WyJlcnJvciJdLCJuby1mdW5jLWFzc2lnbiI6WyJlcnJvciJdLCJuby1nbG9iYWwtYXNzaWduIjpbImVycm9yIl0sIm5vLWltcG9ydC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW5uZXItZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWludmFsaWQtcmVnZXhwIjpbImVycm9yIl0sIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjpbImVycm9yIl0sIm5vLWxvc3Mtb2YtcHJlY2lzaW9uIjpbImVycm9yIl0sIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjpbImVycm9yIl0sIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6WyJlcnJvciJdLCJuby1uZXctc3ltYm9sIjpbImVycm9yIl0sIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjpbImVycm9yIl0sIm5vLW9iai1jYWxscyI6WyJlcnJvciJdLCJuby1vY3RhbCI6WyJlcnJvciJdLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOlsiZXJyb3IiXSwibm8tcmVkZWNsYXJlIjpbImVycm9yIl0sIm5vLXJlZ2V4LXNwYWNlcyI6WyJlcnJvciJdLCJuby1zZWxmLWFzc2lnbiI6WyJlcnJvciJdLCJuby1zZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjpbImVycm9yIl0sIm5vLXNwYXJzZS1hcnJheXMiOlsiZXJyb3IiXSwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOlsiZXJyb3IiXSwibm8tdW5kZWYiOlsiZXJyb3IiXSwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOlsiZXJyb3IiXSwibm8tdW5yZWFjaGFibGUiOlsiZXJyb3IiXSwibm8tdW5zYWZlLWZpbmFsbHkiOlsiZXJyb3IiXSwibm8tdW5zYWZlLW5lZ2F0aW9uIjpbImVycm9yIl0sIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6WyJlcnJvciJdLCJuby11bnVzZWQtbGFiZWxzIjpbImVycm9yIl0sIm5vLXVudXNlZC12YXJzIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtYmFja3JlZmVyZW5jZSI6WyJlcnJvciJdLCJuby11c2VsZXNzLWNhdGNoIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtZXNjYXBlIjpbImVycm9yIl0sIm5vLXdpdGgiOlsiZXJyb3IiXSwicmVxdWlyZS15aWVsZCI6WyJlcnJvciJdLCJ1c2UtaXNuYW4iOlsiZXJyb3IiXSwidmFsaWQtdHlwZW9mIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19).

### Version

1.3.50

### Additional context

Possibly related to #7253.

For comparison, [Terser](https://try.terser.org/) does not have this issue:

![Screenshot of Terser playground showing the proper syntax output](https://user-images.githubusercontent.com/283842/231819922-7df1d3f2-8ca5-4cd3-be2c-4d698f7f19a7.png)

**Comment by kdy1** [comment]
Investigation:

 - If `b` is used, [it works properly](https://play.swc.rs/?version=1.3.50&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMzwMzNBJ1FJI0Faq5FBSS8%2FOKSxSqFZKtFFIUahVsFRKtoaL5Oal6OfnpGkmaXLVcqWWJORrq6prWAD1fXU5PAAAA&config=H4sIAAAAAAAAA32QSw7CMAxE9z1F5TULQAIh7sAZkBWcKiVprDhUVIi7k34C5SM2%2Bcy8iZW5FWUJtSjYl7d0TBfGIBSe96RI10S8JgVIORQVDEdYZLeW3tJohQbpPjoQMVQUh5Ssl6vNlADrvVBOTJozjdHdfKbyjgOJvIM9ik1laYb2ozxbasl%2Bwsk6E%2FFRWRRp0NHXc5nQf10OpsVIaff8CzK0%2B6EKagxmtXxrJ%2FVT5HVoCpw%2FXWYfgtgxja1t4QXlgp5DwMghJ2O4UHF%2FAE8y38fLAQAA)

 - But using `d` [is not enough](https://play.swc.rs/?version=1.3.50&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMzwMzNBJ1FJI0Faq5FBSS8%2FOKSxSqFZKtFFIUahVsFRKtoaL5Oal6OfnpGimaXLVcqWWJORrq6prWAIsUn7ZPAAAA&config=H4sIAAAAAAAAA32QSw7CMAxE9z1F5TULQAIh7sAZkBWcKiVprDhUVIi7k34C5SM2%2Bcy8iZW5FWUJtSjYl7d0TBfGIBSe96RI10S8JgVIORQVDEdYZLeW3tJohQbpPjoQMVQUh5Ssl6vNlADrvVBOTJozjdHdfKbyjgOJvIM9ik1laYb2ozxbasl%2Bwsk6E%2FFRWRRp0NHXc5nQf10OpsVIaff8CzK0%2B6EKagxmtXxrJ%2FVT5HVoCpw%2FXWYfgtgxja1t4QXlgp5DwMghJ2O4UHF%2FAE8y38fLAQAA).

My guess is that this is about the usage list, and seems like the name mangler is trying to _reuse_ `n` for a variable name because the parameter is not used.

**Comment by kdy1** [comment]
@Austaras Do you have any idea? I tried several things like making `belong_to_fn_scope` always true and it worked, but there were too many regressions
