### ISSUE TITLE
Path aliases are not working properly with files

### ISSUE THREAD

**Issue by doichev-kostia** [swc-project/swc#7265]
### Describe the bug

SWC does not correctly resolve path aliases for standalone files.

in the config, I have a mapping

```json
{
    "baseUrl": ".",
    "paths": {
      "utils/*": ["./src/utils/*"],
      "~/container": ["./src/container.ts"]
    },
}
```
SWC work perfectly with aliases to directories. However, it doesn't add the extension to the resolved **file** alias

so, instead of `./container.js` it outputs `./container` which is invalid import

[Reproduction](https://github.com/doichev-kostia/swc-absolute-import-issue/tree/master)

Sorry, I could not make it work in Stackblitz, so I just created a repo, but the example is clear

[input](https://github.com/doichev-kostia/swc-absolute-import-issue/blob/master/src/utils/helper.ts)
[output](https://github.com/doichev-kostia/swc-absolute-import-issue/blob/master/build/utils/helper.js)

### Input code

```typescript
// helper.ts

import { MyContainer } from '~/container';

export const helper = () => {
  const container = new MyContainer('helper');

  container.print();
};
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "baseUrl": ".",
    "paths": {
      "utils/*": ["./src/utils/*"],
      "~/container": ["./src/container.ts"]
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false
}
```

### Expected behavior
```js
import { MyContainer } from "../container.js";
export const helper = ()=>{
    const container = new MyContainer('helper');
    container.print();
};
```
### Actual behavior
```js
import { MyContainer } from "../container";
export const helper = ()=>{
    const container = new MyContainer('helper');
    container.print();
};
```
### Version

^1.3.50

**Comment by doichev-kostia** [comment]
Related to
https://github.com/swc-project/swc/issues/4585#issuecomment-1219984287

**Comment by kdy1** [comment]
Did you try `npx tsc` from your repro? `tsc` generates 

```js
import { MyContainer } from '~/container';
export const helper = () => {
    const container = new MyContainer('helper');
    container.print();
};
//# sourceMappingURL=helper.js.map
```

and it seems like `'~/container'` is not transpiled at all.
