### ISSUE TITLE
Missing tokens in 0.21.7

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#728]
**Describe the bug**

Tokens are missing in the output and are not captured.

**Input code**

```ts
export interface ResolvableMethods {
}
```

**Expected behavior**

Five tokens.

**Actual behaviour**

Only two:

```ts
Token: TokenAndSpan { token: Word(export), had_line_break: true, span: Span { lo: BytePos(0), hi: BytePos(6), ctxt: #0 } }
Token: TokenAndSpan { token: Word(interface), had_line_break: false, span: Span { lo: BytePos(7), hi: BytePos(16), ctxt: #0 } }
```

**Version**

parser 0.21.7

**Additional context**

Related to fix for #726. I was thinking that perhaps instead of doing a "revert" it could instead only capture a token if the lo position is greater than the previous token's lo position?

**Comment by kdy1** [comment]
@dsherret Oh.. It seems like a great idea. I'll do it tommorow (as it's time to go bed in my country)

**Comment by dsherret** [comment]
@kdy1 sounds good! I pegged the swc version to 0.21.6 on my side in the meantime, so no rush.

Thanks and have a good sleep!

**Comment by dsherret** [comment]
@kdy1 it works well. Thanks 🙂
