### ISSUE TITLE
new Set(['key1', 'key2']),  use Loop traversal ， can't  get attribute

### ISSUE THREAD

**Issue by yangaihe** [swc-project/swc#7285]
### Describe the bug

new Set(['key1', 'key2']),  use for of Loop traversal ， can't  get attribute

### Input code

```typescript
let setter = new Set(['key11', 'key22'])
for(let key of setter) {
    console.log('key===', key)
}
```

### Config

```json
{
  "env" : {
      "mode": "entry",
      "coreJs": 3,
      "forceAllTransforms": true,
      "dynamicImport": true,
      "targets": {
      },
  },
  "jsc": {
    "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true,
        "react": {
          // runtime: "automatic", // or classic
          "runtime": "automatic", //
          "throwIfNamespace": true,
          "useBuiltins": true,
          "development": false,
        },
      },
      "loose": true,
      "parser": {
        "syntax": "ecmascript",
        "jsx": false,
        "decorators": true,
      },
      "target": "es5",
  },
  "module": {
    "type": "commonjs"
  },
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.49&code=H4sIAAAAAAAAA8tJLVEoTi0pSS1SsFXISy1XCE4t0YhWNzRU11FQNzJSj9Xk0tdXeLZrwvMFjVxp%2BUUaOUAN2amVCvlpUH2aCtVcCkCQnJ9XnJ%2BTqpeTn66hDlRha2sLNAPI0OSq5QIA7rpPd2cAAAA%3D&config=H4sIAAAAAAAAA2VSu27DMAzc8xUC5wAZii7ZWnRJgXTKDxAKkyrQwyDpNEbgf69kxI4jexAk3olH3fm%2BMgYoXsFszT3vywchHQm2pa7cwXos28T0LRl4m0qnxJY%2BvD8wRsmHUGDllibGsYsYnN2FJrHWoCKfScudUbsv2LDARewEgI4CM24uezqj7b4oj4aauOpf5EdoT4pHVFxSmNDqS1tjNhvDbVQXKNuAraaA6iysC5DYWI8izs4uwIMOC%2F6cpL%2Bc%2FnanHwwkDVpaDJM5rdBn67y6WHv5eNCVfGpCzibDJ%2FQyw%2Fv1qtqAT0lqHWiQhfjVSumi4m2I3QYUy65RmNl0kdtS8OlvPWxfhTw0lnd45pv%2FstbTLOKuGeyzKYQULwIT08l%2B5BaJVf8PfP2zz7YCAAA%3D

### Expected behavior

keep source code   ### for  ### of

### Actual behavior

keywords ###  for ### of  was replaced with  ### for ###  i++

### Version

1.3.49

**Comment by magic-akari** [comment]
It's about `loose` which contains `iterableIsArray`.

https://babeljs.io/docs/assumptions#iterableisarray

**Comment by kdy1** [comment]
Closing as this is the expected behavior for the loose mode.

**Comment by yangaihe** [comment]
> It's about `loose` which contains `iterableIsArray`.
> 
> https://babeljs.io/docs/assumptions#iterableisarray

swc.config  
`loose : false ` 
solved this problem
