### ISSUE TITLE
Unexpected renaming of variables with containing `eval()` and enabling `Env Targets`

### ISSUE THREAD

**Issue by hyf0** [swc-project/swc#7295]
### Describe the bug

Unexpected renaming of variables with containing `eval()` and enabling `preset`

### Input code

```typescript
var bmRnd;
function roundValues(flag) {
  if (flag) {
    bmRnd = Math.round;
  } else {
    bmRnd = function (val) {
      return val;
    };
  }
}

eval('');
```

### Playground link

https://play.swc.rs/?version=1.3.51&code=H4sIAAAAAAAAAytLLFJIyg3KS7HmSivNSy7JzM9TKMovzUsJS8wpTS3WSMtJTNdUqOZSUMhMU0DiKUB0Kdgq%2BCaWZOiBtVgDxWsVUnOKU9GUwE3WKEvMgelXUChKLSktylMAilmDRWrBBnDVcnGlAsU01NU1rQFINUtUnwAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw6DMAzdOUVkqVtVUYYOHXqDHiJKDQoiH8WhIkLcvSEkFDb7fe25Ygx6EvBkcxzjYrkjdPseEQra8ykigEJxEk5aD9fC9rRSLR8IE7RsDHjuOvTJRU3dNNkBgzGExZExJbVsw7FTGGUdEp2Fq5TrbsBzY5VbQZnPmMj8iw8Wtwse8BeVsj0YJL2L07txw1B%2FD0HpmfUaeLH6Vt8vKa9afrOlEn5AAQAA

### Expected behavior

`bmRnd` should not be renamed.

### Actual behavior

```js
var bmRnd;
function roundValues(flag1) {
    if (flag1) {
        bmRnd1 = Math.round;
    } else {
        bmRnd1 = function bmRnd1(val1) {
            return val1;
        };
    }
}
eval('');

```

### Version

1.3.51

**Comment by kdy1** [comment]
I think this is duplicate of https://github.com/swc-project/swc/issues/7253

**Comment by hyf0** [comment]
> I think this is duplicate of #7253

It seems so :).

**Comment by zhaomenghuan** [comment]
I have also encountered a similar issue. Is there any progress on this problem now?

```
function fn() {
  fn = function () {
    return {};
  };
}

eval('');

function callFn() {
  fn();
}
```

This code will be compiled into the following content：

```
"use strict";
function fn1() {
    fn1 = function fn1() {
        return {};
    };
}
eval("");
function callFn() {
    fn();
}
```

If there is no eval expression, this is as expected. it will be compiled into something like this.

```
"use strict";
function fn() {
    fn = function fn() {
        return {};
    };
}
function callFn() {
    fn();
}
```
