### ISSUE TITLE
Unexpected token u in JSON

### ISSUE THREAD

**Issue by MuTsunTsai** [swc-project/swc#7301]
### Describe the bug

In my project I'm running unit tests with mocha + ts-node + @swc/core. Not sure if this is a bug of @swc/core or of ts-node, but ever since I updated to @swc/core 1.3.50+ it shows the following error when I try to run the test:

![image](https://user-images.githubusercontent.com/39870664/233248765-cf132e44-585a-4d9e-8d57-9a000700489d.png)

### Expected behavior

There shouldn't be an error.

### Version

1.3.50,1.3.51,1.3.52

### Additional context

Although the source of the error seems to be in ts-node, but downgrading to @swc/core 1.3.49 solves the issue.

**Comment by kdy1** [comment]
Please provide a repro

**Comment by MuTsunTsai** [comment]
@kdy1 Well, if I must, the repo is https://github.com/bp-studio/box-pleating-studio in [DEV](https://github.com/bp-studio/box-pleating-studio/tree/DEV) branch. To reproduce the error:

1. Use PNPM to perform `pnpm install` after cloning the repo and checking-out DEV branch.
2. Run `pnpm test`. Mocha should run without problem.
3. Run `pnpm update -L` to force update @swc/core to the latest version.
4. Run `pnpm test` to see the error.

Please reopen the issue if that's not too much to ask for.

**Comment by kdy1** [comment]
Thank you, but as it's not a minimal repro, I don't think this can be fixed shortly.

https://antfu.me/posts/why-reproductions-are-required

**Comment by MuTsunTsai** [comment]
Maybe this will help. I've traced the issue down to this part:

https://github.com/swc-project/swc/blob/d5c0dec40c1bb46bb5674242aa0a85f51c0826f7/node-swc/src/index.ts#L232-L236

I believe that this `transformSync` method is in Rust so that the debugger won't allow me to step in further. In version 1.3.49, this always returns an object with both `code` and `map` properties, where the map could be an empty map like this:

```
{"version":3,"sources":[],"names":[],"mappings":""}
```

But since version 1.3.50, it could return an object with only `code` but not `map` (i.e. the property is missing), if the file being processed essentially contains no executable code (for example, it contains only TypeScript definitions), and it is because of the missing `map` that results in later error in ts-node. This breaking change of behavior feels more like unplanned to me.

**Comment by MuTsunTsai** [comment]
@kdy1 Following the idea above, I've created a minimal repo here:
https://github.com/MuTsunTsai/swc-bug-demo

After `npm install`, run `npm run test` to see the error. Downgrade to v1.3.49 and there's no error.

**Comment by kdy1** [comment]
Thank you so much for the investigation! This is an easy issue and I'll fix this tomorrow

**Comment by kdy1** [comment]
Investigation takes an  _unknown_ amount of time, while fixing is very easy in most cases.

**Comment by MuTsunTsai** [comment]
@kdy1 True, and glad that it is also the case here. I admit that it did take me a while to go this far. Hope to see it fixed in the next version.

**Comment by MuTsunTsai** [comment]
Confirm fixed in v1.3.53
