### ISSUE TITLE
Transform optional chaining maybe incorrectly, inconsistent with babel

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#7312]
### Describe the bug

If a is `undefined`, this code can run in browser directly, and Babel transformed like this:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/57202839/233581829-b08de93f-9d9d-4353-8e6d-1aeb2f4c8e59.png">

SWC output:
(a === null || a === void 0 ? void 0 : a.b())();

Is this an expected behavior

### Input code

```typescript
a?.b()()
```

### Config

```json
{
  "jsc": {
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.52&code=H4sIAAAAAAAAA0u010vS0NTQ5AIA1MkElQkAAAA%3D&config=H4sIAAAAAAAAA1VQyw6DMAy77ytQzly3w%2F5hHxF1AXWiDyWpNIT497WFMji1tR3b6XLrOviIgWe35Gt%2BKKOXIbA7oAwyodETUKDk1TrKIGDS4FCtgZ1e67n2m2NEFuKzncxe8VtGdY4khm1U6BurUijlRBcbRR6plACS%2B66GKQQpHQachHbMWW%2BH%2BZxngotMIldhkaIfp2P%2B1rrXSHDhnSrZfiZ33eIf8Be1sMMYrLzaZF1i%2FQEQs2upZQEAAA%3D%3D

### Expected behavior

if a is undefined, code can run successfully

### Actual behavior

Output code is `(a === null || a === void 0 ? void 0 : a.b())();`, an Error has been thrownÏ

### Version

1.3.52

**Comment by JSerFeng** [comment]
Seems that parsed AST is inconsistent with Babel, 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/57202839/233586254-9a959e14-335b-4d52-b48c-f60f61f45855.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/57202839/233586521-b243ad9d-6b3d-4bbd-b91d-c0ad03c1e8f6.png">

**Comment by JSerFeng** [comment]
Can you leave this to me, maybe I can fix this

**Comment by kdy1** [comment]
Of course, thank you!
