### ISSUE TITLE
Directive not preserved for commonjs

### ISSUE THREAD

**Issue by jaslong** [swc-project/swc#7315]
### Describe the bug

```
// input.ts
"use client"

export function ReactClientComponent() {
    return "Hello world"
}
```

`swc input.ts -o output.js -C module.type=commonjs`

```
// output.js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "ReactClientComponent", {
    enumerable: true,
    get: function() {
        return ReactClientComponent;
    }
});
"use client";
function ReactClientComponent() {
    return "Hello world";
}
```

Notice how `"use client"` is underneath the helpers generated by swc, which doesn't work with Next.js, which expects `"use client"` to come before any expressions.

Related to https://github.com/swc-project/swc/issues/6508

### Expected behavior

`"use client"` should be either 1 line above or below `"use strict"`. I believe either is acceptable for Next.js.

```
// output.js
"use client";
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "ReactClientComponent", {
    enumerable: true,
    get: function() {
        return ReactClientComponent;
    }
});
function ReactClientComponent() {
    return "Hello world";
}
```

### Version

@swc/cli: 0.1.62 @swc/core: 1.3.53

**Comment by ammmze** [comment]
Until this gets resolved, I created a shell script that I run after running swc to hoist all the `"use client";` directives to the top of the files. See the [gist here](https://gist.github.com/ammmze/ce38fc64ecb257a8bfd3f98cbf6db8e6).
