### ISSUE TITLE
React Constant Element transformation support

### ISSUE THREAD

**Issue by SukkaW** [swc-project/swc#7318]
### Describe the feature

> This plugin can speed up reconciliation and reduce garbage collection pressure by hoisting React elements to the highest possible scope, preventing multiple unnecessary re-instantiations.

- https://babeljs.io/docs/babel-plugin-transform-react-constant-elements
- https://github.com/facebook/react/issues/3226
- https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-react-constant-elements

### Babel plugin or link to the feature description

https://babeljs.io/docs/babel-plugin-transform-react-constant-elements

### Additional context

```jsx
// In
const Hr = () => {
  return <hr className="hr" />;
};

const WithChildren = (props) => {
  return <div className={props.className}>
    <hr />
  </div>;
}

// Out
var _hr, _hr2;

const Hr = () => {
  return _hr || (_hr = <hr className="hr" />);
};

const WithChildren = (props) => {
  return <div className={props.className}>
    {_hr2 || (_hr2 = <hr />)}
  </div>;
}
```

**Comment by kwonoj** [comment]
It looks like babel supports via plugin, any reason it can't be swc plugin?

**Comment by kwonoj** [comment]
Closing as not hearing any more information for the core between plugin. If you still believe this should be in a core transform, please feel free to file a new RFC https://github.com/swc-project/swc/discussions/4162 with usecases that it cannot be done by plugin.
