### ISSUE TITLE
`node_modules` is making swc slown, CPU/RAM high consumer

### ISSUE THREAD

**Issue by pp0rtal** [swc-project/swc#7324]
### Describe the bug

When running swc on a large 10K files project;
- it takes 5s without node_modules
- it takes 40s with node_modules and fills 10Gb ram

![high](https://user-images.githubusercontent.com/572334/233981196-f42c511e-98ee-407f-abb5-df3d3f971061.gif)

### Input code
My sources are at the same level as `node_modules`

```typescript
node ./backend/node_modules/@swc/cli/bin/swc.js ./backend/ --out-dir ./backend_dist -w
```

### Config

```json
{
    "exclude": [
        "\\.d\\.ts$",
        "backend\\/node_modules"
    ]
}
```

### Expected behavior

Behave the same as if `node_modules` folder were not existing.

### Actual behavior

Fill 10Gb RAM instead of 400Gb for my project.

### Version

1.3.53

### Additional context

About my `node_modules`:
- That's a 100k files `node_modules` folder,
- I tried with half `node_modules` files and it takes still half RAM so it's not a specific file creating a bug

**Comment by kdy1** [comment]
Your regex seems wrong.
I'll reopen this once you provide a repro

**Comment by pp0rtal** [comment]
@kdy1 Thank you for answering

It can't be my `exclude` list as I have thousand error if I dont exclude `node_modules` (I don't have failures here, and I do have the expected output).

For traceability, I reopened a new issue with an isolated use-case https://github.com/swc-project/swc/issues/7325 
this way I hope you'll be able to reproduce the issue.
