### ISSUE TITLE
Abstract property is override to undefined

### ISSUE THREAD

**Issue by vlourenco-stf** [swc-project/swc#7326]
### Describe the bug

In line 106 of playground:

```ts
_define_property(_assert_this_initialized(_this), "data", void 0);
```

The value of `data` passed by the constructor defined in the class is override by this lazy initialized property.

The latest version that this pattern worked was in: `1.3.35`, in this version, we don't have this line to override.

### Input code

```typescript
function enumerable(value: boolean) {
  return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {};
}

export abstract class DefaultPaginatedProxy<T> {

  //#region Constructor

  constructor(
    data: T[],
    query: DefaultPaginatedQuery,
    total: number,
  ) {
    // @ts-ignore
    this.data = data;
    this.count = data.length;
    this.page = query.page;
    this.limit = query.limit;
    this.total = total;
  }

  //#endregion


  //#region Public Properties

  @enumerable()
  public page!: number;

  @enumerable()
  public limit!: number;

  @enumerable()
  public total!: number;

  @enumerable()
  public count!: number;

  public abstract data: T[];

  //#endregion

}

export type ClientProxy = number[];

export class ClientPaginatedProxy extends DefaultPaginatedProxy<ClientProxy> {
  @enumerable()
  public data!: ClientProxy[];
}

const t = new ClientPaginatedProxy(12, 12, 12);

console.log(t);
```

### Config

```json
{
  "sourceMaps": "inline",
  "module": {
    "type": "commonjs",
    "strict": true
  },
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "minify": {
      "compress": false,
      "mangle": false
    },
    "externalHelpers": false,
    "keepClassNames": true,
    "loose": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.53&code=H4sIAAAAAAAAA41TwW7CMAy99ys87VIkBtqO7YaQ4LYLk7hNO6TFlEgh6VJno5r49zlJgbKNiQOq7PdsPzuPtdMlSaMBtduiFYXC9EMohxkUxigUegBfCYBFclbD%2BkBPSdgKKQOh2yHU1tRoqX3GNoOGrNTVEFbYlFbWZGwGi44wP%2Ba47T5P9kmCu9pYAlFwnSgJSiWaBua4Fk7RQlRSC8IVN9i1j8sJi2E14%2FGtxcrrmBnNda7kjh4oT2HKIcBKkMhg%2Bfo2DOG7Q8sSf3Z%2F8enIIENCZcDXKND6VNzfz4QpNXey0sZipG5kM%2FID4CnMyU%2FZ0jhNXXqkUFe06aG1qJDBICYEPUzJraQjGKIeGtQxGr4%2Bv%2B%2FOgXoVL5Kc32fhCiXLw%2F0lNh6e9h57wHEdSV7JzWH1%2FB9iUHUVM%2Bi8ihkuds7skKMzjm%2BZ%2F176ZCRqa4SZkqgpmIavFXuGuo4UTdaxzjwGuCPue8mBvcaTYIwL63itvE2P7sezyuBQ8C%2Bs8fNPBen9wxDib5DHAv4jjpSpUhrk30VkN9axAwAA&config=H4sIAAAAAAAAA31Su27DMAzc8xWG5g5ppqBrO3RJf6Eg5LOhVC%2BQchAj8L9Xiu3ETYxOBu%2FFE%2BHLpqqUhI41DhRFvVXKeGs81EthXKg7i4xe8pTn1McyKR2cC%2F4oV1VJSGx0ykziDhkaru6j6IWVuEWRKMhuu9vN1kgs4JuuhPU%2B0bkoyzrRbGKa1CVHCtWQFdywGjowpcByrzCVKA4mL01gt1xi0ZLuP2bj5HtOPCBRTYnWgp3xpumXqfkukSHy1NCRbxeHHHuFaHGCfRRn6geI39qSiCeHp7hZ0fzLRjYnSsjfENdEBvsVVKghNq%2FbmZqY4c%2FLcU5gT%2FYTNoIfwq%2Fb30v5r6ne%2FbTKhiBYZI9%2Fyu2SIzxsfgEwy23fmAIAAA%3D%3D

### Expected behavior

To data not be override by `void 0` and the value sent by `constructor` is saved inside the class.

### Actual behavior

The property `data` is undefined when passing valid value inside the `constructor`.

### Version

1.3.53

### Additional context

This issue was introduce at [v1.3.40](https://github.com/swc-project/swc/blob/main/CHANGELOG.md#1340---2023-03-13) by this commit: https://github.com/swc-project/swc/commit/bb6dde794326838b2069c7f86fb900eee36027bc

**Comment by vlourenco-stf** [comment]
I don't know why but `jsc.transform.useDefineForClassFields=false` fix the issue on the playground but didn't fix in my setup, I'm using `@swc/core` with `NestJS` to test.

**Comment by kdy1** [comment]
This is not a bug. Read docs.

**Comment by vlourenco-stf** [comment]
This one: https://swc.rs/docs/configuration/compilation#jsctransformusedefineforclassfields?

It didn't mention that when you use abstract class and set some abstract field inside the abstract class, you will loose the value defined when `useDefineForClassFields` is `true`.

Makes more sense to abstract fields be defined in the abstract class too, since any class that will use that field will need to implement it.

If we emit the `data` property inside the abstract class, it became:

```
let DefaultPaginatedProxy = class DefaultPaginatedProxy {
    constructor(data, query, total){
        this.data = data;
        this.count = data.length;
        this.page = query.page;
        this.limit = query.limit;
        this.total = total;
    }
    page;
    limit;
    total;
    count;
    data;
};
```

And it produces:

```
ClientPaginatedProxy {
  page: undefined,
  limit: undefined,
  total: 12,
  count: undefined,
  data: 12
}
```

Which is the correct output we expect when we set `data` inside the constructor, instead of:

```
ClientPaginatedProxy {
  page: undefined,
  limit: undefined,
  total: 12,
  count: undefined,
  data: undefined
}
```

**Comment by vlourenco-stf** [comment]
Oh, I think I understand what happens, when we combine: `abstract fields` with `decorators`, it overrides the initial value of `data` to declare the decorator.

Babel has the same behavior: [playground]( https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUzCAtsgTgQwEYA2yAFAG44EjIBcieccROYAlIgN4BQiiWyUILElCRYCRMSg4sAc361mATwA0iAA5Y4a7FEUBpZItoBnKFhhgZqgCbJjEc2qhwstAAqbtWXQBE7DmCcXNnYAXwBuTlDOTmQADzUXKER8U1xoRAgCHGNjRD9gHBACKDccGQscKGRrDzg4xQAeABUAPg4YngB6LoBiPgrxAGEENJBoF07M0bNx5yxibh5EayqcWmaAbQBdZSWeAEcqLCN85ELi0vLK6usARWOVfcRnKQJaNHQ8bD2eEOeeogAAJQYwAWhgMjALmQzygAAsYMYAHSrKSIAC8KzWkWWL0RKIgcHAySxaJwyKIlgRuOWCKRyLU5WQmMQR2wikZzNpPHpKIIMHQMFJbMelMFwp5-IZrworNlBFp0SWPV6qGsA3gYBiKr6mvEbhAhBgEEQdS8sDsUyBqAw2HwRGILCWaiNAtNTLkAEIPhhvlhIksbZ97YQSM6eK7jaaBUKoD7EJ9_YGeMG7bgw06XW6TS84G8E0nsCngbbMBnHRH1DnTUSSYW_cWplH3Sk8GkcBlyRsdiXVer9dqojF4olvC9FNpEEMBahSpoGqyi1heyOEklMtlctPZ2ArhUwFUanVF_FqmBrHkCkUSmUD0fagumjOYHOT4p2lxU2XQ5Xs9HsSkBMXzfJ9V2VIkwFMF4l2QAB3HdXz3O8bmPJ9iAARgAJlUbDcKwlhA0g4xGGQSk4BkSRCKAA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cstage-2%2Cstage-3%2Ctypescript&prettier=true&targets=&version=7.21.4&externalPlugins=&assumptions=%7B%7D)

Well, I will ask to babel team if this is a thing that is suppose to happen.

**Comment by vlourenco-stf** [comment]
You are correct, is a behavior that is suppose to happen accords https://github.com/babel/babel/issues/14291#issuecomment-1047241816

Dawn, what a weird behavior since I just want to reduce the boilerplate of my code.

**Comment by kdy1** [comment]
https://swc.rs/docs/migrating-from-tsc#usedefineforclassfields
