### ISSUE TITLE
Error.cause undefined using TypeScript

### ISSUE THREAD

**Issue by rentalhost** [swc-project/swc#7337]
### Describe the bug

I really don't know if it is a bug, but when we are working with `Error` class (maybe others), and we need to set the property name to type it, it causes that the property name is keept when it must be dropped in that case.

In that example specifically, the property `cause` is set by own `Error` class calling `super()`. As it is indirectly related, so the property must be dropped to that works.

Using `loose` option will drop that, but I don't know if it is really expected, because it affects others non-related codes.

### Input code

```typescript
class ExampleError extends Error {
  public cause: number; // I just set it, so when I use `.cause` I can see that it is a number!

  public constructor (message: string, options: { cause: number }) {
    super(message, options);
  }
}

try {
  throw new ExampleError("message", { 
    cause: 123 // Nice, `cause` here expects a number!
  });
}
catch (error) {
  console.log((error as ExampleError).cause); // typeof error.cause === 'number'
  // Expects: Number(123)
  // Receive: undefined
}
```

### Config

```json
{
  "jsc": {
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.55&code=H4sIAAAAAAAAA1VQu24CMRDs%2FRUTGu4kBErSgSgpaCjyBRizcI4O%2B2SvAwjdv2fPvkRQ7uzsPNa0OkZsbvrStbQJwQfQjckdBczTQwFdOrTWwOgUaQmXLgcKKywW2OI7RUYkhuUZose1ISewELGf54O9jEY7IRG40QMTNkKPOm%2FqycC7yCEZFt%2FqQjHqs%2FgJZN15Bt%2BxFcISj9ck6OucEoipo%2FB3%2BH9Qr2TZq14pDvfM5Cb4KxxdX4pXk%2FFyMhOLLDj6vH98Dm131ojqfmzVUCD5VUeGn9uIlRj2ymg2DSoalEu%2BoZ1vad76c1Vw6NfX1%2BVjdf4t3zvyJ2RiwbFerzEtRlMRFNKm%2BC%2Bxy2glSeuy%2BSJD9kfCJ3ekk3V0VP0vPOcZ2%2B0BAAA%3D&config=H4sIAAAAAAAAA41VS27jMAzd9xSB1110sigGPUB3cwZBsShHHVk0RCpNUOTuQzl26jR0MKs4fHqk%2BPjR19Nm03xQ27xtvuRT%2FnC2iTzm%2FmoSYwbb8sJQTSVx6EGMjS2MveXQNhN8Hn%2FPzxePg80EeemOTontsVL5NAC1OQzcPM8oU4W8jQQ3ftjmDuotGqDty3Y7MZqISDAzJlsfUvCnZcwW%2ByED0W0W4rL0kJhu%2BROW8bMCnMvSvkOMICKtI8aSCYmhg6w5bjFGOxCYg82Kl3pTmwOhFqKChcGZIeOg4skFDpgk5j3qwDrTogMFChlaDgfQaBJLaIkkPSWfEXawK1031vkHGw42FstKTDiOJZHbKl73GIiNL0mT8AKuaHABJ3F%2FMoM3GbjkdM%2F7wJBWavIXQBSIlijZHjS%2F4wkv%2FbTG9g%2BZIXlpWT4puPS3lmWCTkQ1IXhF2aoMZA5aNTO40kJVttWuM8Er8lFwYMB76RXFNX0Gbvda0Dro6BVA6mu91lUXwFyncAWvA%2FEAfpcsWW%2Bw6YRsrv06Sqd%2Bh%2FFBgB54j%2B7BASkF4zqcZUsch3W8JAfSGuDUI4VG4H4JyAAwmjjuy7vekPEQj6aLuPteE%2FPuvu7h3qZunPfFvmQcIhwgrrXxf4zIQ1TudqhdPU%2F23fTCb60prQxe%2BPVy82xcn6GnKammR1cWCY09eXlOXpvvQ%2FPLMavWBPozE0edzv8Av3zsNDUHAAA%3D

### Expected behavior

`console.log((error as ExampleError).cause);` must returns `123`

And output:

```ts
try{throw new class extends Error{
  // cause; (drop that! so .cause will return 123 correctly)
  constructor(s,e){super(s,e)}}("message",{cause:123})}catch(s){console.log(s.cause)}
```

### Actual behavior

`console.log((error as ExampleError).cause);` will returns `undefined`

And the output:

```ts
try{throw new class extends Error{
  cause;
  constructor(s,e){super(s,e)}}("message",{cause:123})}catch(s){console.log(s.cause)}
```

### Version

1.3.55

**Comment by kdy1** [comment]
This is not a bug

**Comment by magic-akari** [comment]
Use `declare` if you do not want to overwrite it.

- babel/babel/issues/14291#issuecomment-1047241816
