### ISSUE TITLE
The useDefineForClassFields is documented but not in the schema at https://json.schemastore.org/swcrc

### ISSUE THREAD

**Issue by air2** [swc-project/swc#7338]
### Describe the bug

The new setting use.. is now documented (As mentioned in #7173) however it does not appear in the schema published at
"https://json.schemastore.org/swcrc" I do not know if this schema is managed by this project, but I expect it to be, because it it is used in the official documentation. 

It would be really nice if the schema can be updated.

Also the documentation contains no example syntax of the setting, like other settings have.

### Expected behavior

I expect all supported settings to be in the published schema.

### Version

1.3.55

**Comment by kwonoj** [comment]
This has been mentioned couple of time in this repo, but we do not own / manage schema's under https://json.schemastore.org.

**Comment by air2** [comment]
Ok I created an update in that repo, my rust may be a bit rusty, my json skills should be fine, so here it is:
https://github.com/SchemaStore/schemastore/pull/2933 ;)
