### ISSUE TITLE
SWC panics when calling `get_context` on `v0.75.*`

### ISSUE THREAD

**Issue by jcoon97** [swc-project/swc#7350]
### Describe the bug

SWC appears to panic when calling `get_context` from a Wasm plugin on `v0.75.*`. When `get_context` is called on `v0.74.*`, however, the program does not panic and an `Option` is returned as expected.

I've created a [reproducible repository](https://github.com/jcoon97/swc-get-context-issue) as well, which, when built, should reproduce the stacktrace output below.

### Expected behavior

When `get_context` is called with `&TransformPluginMetadataContextKind`, the function is expected to return `Option<String>` without panicking.

### Actual behavior

Program halts and panics, terminating the process, and outputting the following stacktrace:

```shell
Panic: PanicInfo { payload: Any { .. }, message: Some(failed to invoke plugin: failed to invoke plugin on 'Some("input.js")'

Caused by:
    index not found), location: Location { file: "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\swc-0.260.41\\src\\plugin.rs", line: 219, col: 14 }, can_unwind: true }
Backtrace:    0: wasmer_vm_imported_memory32_atomic_notify
   1: wasmer_vm_imported_memory32_atomic_notify
   2: canonical_abi_free
   3: wasmer_vm_imported_memory32_atomic_notify
   4: wasmer_vm_imported_memory32_atomic_notify
   5: wasmer_vm_imported_memory32_atomic_notify
   6: wasmer_vm_imported_memory32_atomic_notify
   7: wasmer_vm_imported_memory32_atomic_notify
   8: wasmer_vm_imported_memory32_atomic_notify
   9: canonical_abi_free
  10: wasmer_vm_imported_memory32_atomic_notify
  11: wasmer_vm_imported_memory32_atomic_notify
  12: canonical_abi_free
  13: canonical_abi_free
  14: canonical_abi_free
  15: canonical_abi_free
  16: canonical_abi_free
  17: canonical_abi_free
  18: canonical_abi_free
  19: canonical_abi_free
  20: canonical_abi_free
  21: canonical_abi_free
  22: uv_queue_work
  23: uv_poll_stop
  24: v8::internal::compiler::ToString
  25: BaseThreadInitThunk
  26: RtlUserThreadStart

failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("input.js")'

Caused by:
    index not found
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (C:\Users\xxx\swc-get-context-issue\example\node_modules\@swc\cli\lib\swc\util.js:149:15)
    at files (C:\Users\xxx\swc-get-context-issue\example\node_modules\@swc\cli\lib\swc\file.js:201:19)
    at async _default (C:\Users\xxx\swc-get-context-issue\example\node_modules\@swc\cli\lib\swc\file.js:220:9)
```

### Version

swc_core `v0.75.*`, @swc/core `^1.3.56`

**Comment by kwonoj** [comment]
I tried on my Windows machine, and it works fine: 

![image](https://user-images.githubusercontent.com/1210596/236112013-a6b7312f-2ed8-4053-8386-ceddc32e1d96.png)

Can you trigger example on the CI?

**Comment by kwonoj** [comment]
Also your config is incorrect:

https://github.com/jcoon97/swc-get-context-issue/blob/ed6b217b145fc8d72da923c3ae94cd9fa10377f7/example/.swcrc#L6

It should be an absolute path.

**Comment by jcoon97** [comment]
Updated project to use absolute path and also created a GitHub Action as well. Still getting an error, though it's `RuntimeError: unreachable`.

[Job can be found here](https://github.com/jcoon97/swc-get-context-issue/actions/runs/4879327365/jobs/8705790916), and [raw log output can be found here](https://pipelines.actions.githubusercontent.com/serviceHosts/8a051912-434f-42e0-968f-a68336440c46/_apis/pipelines/1/runs/3/signedlogcontent/2?urlExpires=2023-05-04T05%3A19%3A11.9353417Z&urlSigningMethod=HMACV1&urlSignature=emu0W%2FTQZeucKQIgm%2FPBneYPheZ1%2B4Smy9yqotkvs2E%3D).

**Comment by kwonoj** [comment]
Try to disable lto, looks like latest wasmer have some unexpected behavior with lto optimized binaries.

https://github.com/kwonoj/swc-get-context-issue/commit/f2e675093e882f2e5fec4c5c61e2a0b49181cd60

https://github.com/kwonoj/swc-get-context-issue/actions/runs/4900822397/jobs/8751738024
