### ISSUE TITLE
SWC transpiling arrow functions as `async *() => ` which breaks my build

### ISSUE THREAD

**Issue by ItamarMalka** [swc-project/swc#7353]
### Describe the bug

We started experiencing errors with the swc transpiling... from versions after 1.3.38
for some reason swc transpiles our arrow functions to async* arrow functions...	
I couldn't reproduce it on a playground but any help would be nice 🙏 

### Input code

```typescript
describe('Get Something', () => {
	it('should do something', () => {
		expect(true).toBeTrue()
	});
})
```

### Config

```json
{
  jsc: {
    parser: {
      syntax: 'typescript',
      decorators: true
    },
    transform: {
      legacyDecorator: true,
      decoratorMetadata: true
    },
    experimental: {
      // this is a workaround we use for esm->cjs compatibility https://github.com/swc-project/swc/issues/3843
      plugins: [['jest_workaround', {}]]
    }
  },
  module: {
    type: 'commonjs'
  }
}
```

### Expected behavior

Should be transpiled into a regular arrow function e.g 
```
describe('Get Something', () => {
...
});
```

### Actual behavior

It gets tanspiled into 
```
describe('Get Something', async *()=>{
...
});
```
which errors out...

### Version

1.3.38

### Additional context

I do remember seeing a PR in the changlog changing something to do with async* arrow functions but I couldn't find it right now...

**Comment by kwonoj** [comment]
Please provide playground link, or reproducible repo via gh or codesandbox or similar.
