### ISSUE TITLE
spread syntax differs between swc loose mode and babel loose mode

### ISSUE THREAD

**Issue by lsdyi** [swc-project/swc#7354]
### Describe the bug

I'm migrating my code's compiler from babel to swc, and my code crashed because the generated code with loose config is kind of different from babel.
Code contains es spread syntax. While babel with loose config removes all TypeError and other stuff, swc with loose config remains the same as non-loose config. TypeError is the key reason of my code crash.

### Input code

```typescript
const data = {}
const temp  = [...data.demo, ...data.demo2]
```

### Playground link

**babel**
https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=MYewdgzgLgBAJgQygmBeGBvAvgKFJWKAUwFsAHGNGAbQDp7Fla5SQAaGe5pBZ1gJgC6QA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.21.8&externalPlugins=&assumptions=%7B%7D 
**swc**
 https://play.swc.rs/?version=1.3.56&code=H4sIAAAAAAAAA0vOzysuUUhJLElUsFWoruVKBvNLUnMLFIAC0Xp6eiA5vZTU3HwdBWSeUSwALJOS2TsAAAA%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxGd06BPHdth94hh7CoExHxJ0ykoih3LyFA2w2%2Fz%2FYzu5ASVlbwlHt5liJgZIqjLoSzS%2FguBEhZZBV1SHDr6cpnNKNhqui4EkgYF0p1iu%2BtHYz3TIWluFFDVjs951%2Bf8jZEYu5rh8qiWwz920QzgvWvrYbtHykHuuwP%2BDZ12VgMmqc%2BeV4ljg%2F3WmjeEwEAAA%3D%3D

### Expected behavior

Using es spread syntax in loose config, swc behaves the same as babel.

### Version

@swc/core: 1.3.56 @babel/core: 7.21.8

**Comment by lsdyi** [comment]
Hello @kdy1 , hope everything goes on well. Could you kindly update me on this issue's status? And if is it possible for me to make PR for this issue?

**Comment by kdy1** [comment]
There's no update, and yes, of course! I'm open to a PR for fixing this
