### ISSUE TITLE
swc generates a different prototype chain than tsc

### ISSUE THREAD

**Issue by rafaelliu** [swc-project/swc#7357]
### Describe the bug

The way swc defines class properties generates a different prototype chain from tsc, with semantic differences.

swc uses `Object.defineProperty` to define a property (even if not initialized) at the class object, while tsc either doesn't define any property (if it's not initialized) or initializes it with `this`.

One issue is user-define properties defined elsewhere in the prototype chain are never reached. Also, the initialization of the property for a code compiled with tsc will use any current set accessor (or an error will be throw if none is set).

### Input code

```typescript
class MyClass {
   myProp: number;
}

Object.defineProperty(MyClass.prototype, 'myProp', { value: 42 })
console.log(new MyClass().myProp)
```
```


### Config

```json
Using ts-node with `swc: true`
```

### Expected behavior

same as tsc, generate a JS not defining any property:

```
let MyClass = class MyClass {
};
export { MyClass };
```

Which prints "42"

### Actual behavior

swc generates a property, and will use `Object.defineProperty`:

```
export let MyClass = class MyClass {
    constructor(){
        _define_property(this, "myProp", void 0);
    }
};
```

Which prints "undefined"

### Version

1.3.56

### Additional context

Even when initializing the property, tsc is more flexible in that it uses `this`:

```
let MyClass = class MyClass {
    constructor() {
        this.componentManager = 42;
    }
};
export { MyClass };
```

swc:

```
export let MyClass = class MyClass {
    constructor(){
        _define_property(this, "myProp", 42);
    }
};
```

**Comment by rafaelliu** [comment]
Hi @kdy1, it took a while to troubleshoot the issue, and then some more to report it compiling different cases and comparing outputs.

I understand its your prerogative to choose what goes and what doesn’t go into swc, but would you care provide a word or two?

**Comment by kdy1** [comment]
Search before filing an issue.

**Comment by TiddoLangerak** [comment]
For future reference, as this issue is a dead end at the moment.

The behaviour can be toggled by disabling the [useDefineForClassFields](https://swc.rs/docs/configuration/compilation#jsctransformusedefineforclassfields) option.
