### ISSUE TITLE
Writing the type of a property in a class causes the property to be declared as a value

### ISSUE THREAD

**Issue by pvcresin** [swc-project/swc#7366]
### Describe the bug

When you write the type of a property in a class, that property is declared as a value.
This is a behavior that does not exist in tsc, babel, or esbuild, and it changes the behavior of the generated code.
This causes bugs in libraries that change behavior depending on whether a property has a value or not.

Reproducible Repository
- https://github.com/pvcresin/tsc-babel-esbuild-swc-diff

## input.mts

```typescript
export class A {
  // foo type
  foo?: string;
}

const a = new A();

console.log(`"foo" in a = ${"foo" in a}`);
```

## compiled code

tsc.mjs

```javascript
export class A {
}
const a = new A();
console.log(`"foo" in a = ${"foo" in a}`);
```

babel.mjs

```javascript
export class A {}
const a = new A();
console.log(`"foo" in a = ${"foo" in a}`);
```

esbuild.mjs

```javascript
export class A {
}
const a = new A();
console.log(`"foo" in a = ${"foo" in a}`);
```

swc.mjs

```javascript
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}
export class A {
    constructor(){
        // foo type
        _define_property(this, "foo", void 0);
    }
}
const a = new A();
console.log(`"foo" in a = ${"foo" in a}`);
```

## result

```sh
$ node dist/tsc.mjs
"foo" in a = false

$ node dist/babel.mjs
"foo" in a = false

$ node dist/esbuild.mjs
"foo" in a = false

$ node dist/swc.mjs
"foo" in a = true
```

### Input code

```typescript
export class A {
  // foo type
  foo?: string;
}

const a = new A();

console.log(`"foo" in a = ${"foo" in a}`);
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "target": "es2015",
    "keepClassNames": true,
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.56&code=H4sIAAAAAAAAA0WLMQqAMBAE%2B7xiEYvYaK%2BI%2BJOEEIMQ7oI5UBH%2FbtDCbmeZ8UfiTeCizRkzLgV0HRZmyJl8oTKnHlm2lcKgbqUcUxZYjCC%2FY9bN8H0cfRs5aFOVpMJKr1NfP96muA%2F%2FviYocQAAAA%3D%3D&config=H4sIAAAAAAAAA1WPTQ7CIBCF9z0FmbULNdGFd%2FAQBKcNhr8w00TS9O4FSlF3zPfe480sgxDwJgUPseRnHoKMhLHPmVByLD%2BZAKeApKIODKdDZSoSxxkrWXcBWMYJuYSQrufLrQXAeE%2BY8SgNYWNWOz2m30rlbYhI9G8sVukm0%2FN749BawfrXXMV2Sll33%2BAOX9NR1j8GTc8jWe9YN%2BKXZ60WAQAA

### Expected behavior

Expected generated code

```javascript
export class A {}
const a = new A();
console.log(`"foo" in a = ${"foo" in a}`);
```

### Version

1.3.56

**Comment by kdy1** [comment]
Search before filing an issue
