### ISSUE TITLE
swc-loader won't compile with v1.1.37

### ISSUE THREAD

**Issue by leebenson** [swc-project/swc#737]
Aftering bumping to v1.1.37, and compilation no longer works with `swc-loader` in Webpack.

**Webpack config (snippet)**:

```js
{
  module: {
    rules: [
      {
        test: /\.(j|t)sx?$/,
        exclude: /node_modules/,
        use: {
          loader: "swc-loader",
          options: {
            test: ".*.tsx?$",
            jsc: {
              target: "es2015",
              parser: {
                syntax: "typescript",
                tsx: true,
                decorators: true,
                dynamicImport: true
              },
              transform: {
                react: {
                  pragma: "emotionCore.jsx",
                  pragmaFrag: "React.Fragment",
                  throwIfNamespace: true,
                  development: !isProduction,
                  useBuiltins: true
                }
              }
            }
          }
        }
      }
    ];
  }
}
```

**Error:**

>   Module build failed (from ./node_modules/swc-loader/src/index.js):
>   Error: Error(Msg("data did not match any variant of untagged enum InputSourceMap"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
>       at /Users/leebenson/dev/project/node_modules/@swc/core/index.js:103:34
>       at new Promise (<anonymous>)
>       at Compiler.<anonymous> (/Users/leebenson/dev/project/node_modules/@swc/core/index.js:102:20)
>       at Generator.next (<anonymous>)
>       at /Users/leebenson/dev/project/node_modules/@swc/core/index.js:8:71
>       at new Promise (<anonymous>)
>       at __awaiter (/Users/leebenson/dev/project/node_modules/@swc/core/index.js:4:12)
>       at Compiler.transform (/Users/leebenson/dev/project/node_modules/@swc/core/index.js:90:16)
>       at Object.transform (/Users/leebenson/dev/project/node_modules/@swc/core/index.js:185:21)
>       at Object.<anonymous> (/Users/leebenson/dev/project/node_modules/swc-loader/src/index.js:69:21)

**Comment by kdy1** [comment]
@leebenson Fixed it with swc-loader@0.1.9
