### ISSUE TITLE
Loopback models return properties 'undefined' for swc version > 1.3.22

### ISSUE THREAD

**Issue by josemotta** [swc-project/swc#7373]
### Describe the bug

Using jest/swc for tests compiler in a Loopback 4 project, I suddenly started receiving an error at the creator() for every model declared at Loopback. Curiously this same code was working fine previously. After a lot of digging, I figured out that swc compiler was the reason for the error. Just changing the version at package.json the error is gone:

- from "version": "1.3.57" (the latest now)
- to "version": "1.3.22"

Any hint? I checked that input data at constructor is ok but the results show all properties returning 'undefined'. I am using [Neptune](https://github.com/wesleymilan/loopback-connector-neptune) but the error happens even before any access to the connector.

Is there any change in swc after 1.3.22 that may cause this error?

### Input code

```typescript
import {Entity, model, property} from '@loopback/repository';

@model({
  settings: {
    type: 'vertex',
    retry: {
      max: 5,
      delay: 100,
    },
    labels: ['Creator'],
  },
})
export class Creator extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  id?: string;

  @property({
    type: 'string',
    required: true,
  })
  name: string;

  @property({
    type: 'string',
    required: true,
  })
  email: string;

  constructor(data?: Partial<Creator>) {
    console.dir(data, {depth: 5}); // data is ok here
    super(data);
  }
}
```

### Expected behavior

The properties should return with their values set correctly.

### Version

> 1.3.22

**Comment by kdy1** [comment]
Search before filing an issue

**Comment by josemotta** [comment]
Sorry, I've searched for a month for this error and could not find any references to it.

**Comment by josemotta** [comment]
Just solved this issue changing to esbuild-jest! There is a 'undefined plague' bug using the swc with loopback that returns all properties undefined when we call the constructor for an entity model. The exact same code is running fine now, just changing the transformer to esbuild.

Changes in jest.config.ts:

`  // transform: {
  //   '^.+\\.(t|j)s$': ['@swc/jest'],
  // },
  transform: {
    '^.+\\.tsx?$': 'esbuild-jest'
  }`

**Comment by kdy1** [comment]
Ah, id the problem is about undefined, it's a problem of `useDefineForClassFoelds`.
You should read documentation first
