### ISSUE TITLE
Could swc/core/visitor get some information like scope ,parent node ...

### ISSUE THREAD

**Issue by congxiaobai** [swc-project/swc#7378]
### Describe the feature

Like babel-traverse ， when I visit  some node of AST , I can get  scope,path ,state 。

**Comment by kdy1** [comment]
https://rustdoc.swc.rs/swc_ecma_visit/trait.VisitMutAstPath.html

**Comment by congxiaobai** [comment]
> https://rustdoc.swc.rs/swc_ecma_visit/trait.VisitMutAstPath.html
Can I  use in Node Project?
