### ISSUE TITLE
Compiling with compress removes function's name

### ISSUE THREAD

**Issue by diasbruno** [swc-project/swc#7384]
### Describe the bug

To reproduce this behavior:

```js
const A = new function A() {};
```

Compiles to:

```js
const A = new function() {};
````

### Input code

```typescript
const A = new (function A() {});
```

### Config

```json
{
  "minify": true,
  "jsc": {
    "target": "es5",
    "minify": {
      "compress": {
	"unused": true
      },
      "mangle": false
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.57&code=H4sIAAAAAAAAAz2OTQqDMBCF9znF2yUB8QAVCzmHSIlh%2BodOSjrionr3xli6fe%2FN902I%2FBY4tGBacJ05yCMynLH4bEr9g8lLuJs4PClIBfHDSHmhgFAA7CfKjKOvS5bmIDHVe9PkXSKZE8OU025Pe6zrQer0Rff2R7eNyuLD56riANwJ%2BaP2XHRxpHqMN6NfXoQSa6s2%2BwUblmO%2ByQAAAA%3D%3D&config=H4sIAAAAAAAAA32US5LjIAyG932KlNe9nVnMAXo3Z6AICIc0Ri4k0nF15e4jY%2BcxHTk7W59%2BCSSh77fdrjuS6%2F7svuVTfkZbCMrtXyw0ZbZnsXTgBkuuxJG79ys90oyCTQTNdFlIx7b0wE1Fv1b3LiESXN1X2xBzDNNjQofDWIDowSZWiVcHyEz%2F61dW8GsGXOqjfY%2BYwOYXxFgyMTP0ULTADlOyI4E52aJEmU9qSyTUUsywMngzFhxVnn3kiFlyPlMP1huHHhQUCziOJ9BkkktkmeR6yn0a9rCvfd%2Ba%2FEMNJ5uqZSUnnFtL5LRK1ANGYhNq1kq4wI0aLHAt7k9lDKYA15KfdUeMeaMnnwBSgWSJsh1Ai9s8gszTljq8VMYcZGR5UrjMt3bLDL0U1cQYlMrOlYHCUetmAV8dzJV12nFWvFE%2Bih4MhCCzooSmr8juoCXlaQQMCpD%2B2qBN1QLM7RVu8PlBvMAfckvWB2z1GCwftilNwx7TiwQD8AH9CwdpBeM2LrIlzuM2r9mDjAZ41aVSA89LQB4Ao0ltWT7NhjwPiWj6hPv7mlgdLrclPNjc39%2F7soffVoduQF8bXDf83N9lL%2F%2Fu7k7XLXw7eBfp71XZkl7%2BAVPL6HotBgAA

### Expected behavior

```js
const A = new function A() {};
```

### Actual behavior

```js
const A = new function() {};
```

### Version

npx swc --version  @swc/cli: 0.1.62 @swc/core: 1.3.57

### Additional context

Removing the function name in some contexts may cause unintended problems,
because it is used as function's name. 

```js
function match(object, table) {
  const name = object.constructor.name;
  return (table[name] || table['_'])(object);
}

const A = new function A() {};
match(A, { A: () => console.log("is A") });
// is A

const B = new function() {}
match(B, { B: () => console.log("is B") });
// Uncaught TypeError: undefined is not a function
```

**Comment by magic-akari** [comment]
You can use `"keep_fnames": true`

**Comment by diasbruno** [comment]
Thanks, @magic-akari. Didn't saw this option :man_facepalming:
