### ISSUE TITLE
My plugins don't work for 8 days

### ISSUE THREAD

**Issue by HeartyPorridge** [swc-project/swc#7386]
### Describe the bug

wasm-bindgen rep's comment on this - https://github.com/rustwasm/wasm-bindgen/issues/3413#issuecomment-1546281926

I ask you to carefully check my question. Please don't close it until I fix the problem.

My problem - https://github.com/swc-project/swc/issues/7381.

If I download any of these plugins from npm it works in my next js. If I compile any of these plugins myself - same error
https://github.com/swc-project/plugins/tree/main

I saw this - https://github.com/swc-project/swc/issues/6997
I follow all instructions.
Any plugin I compile doesn't work in Next js.

This problem has been with me for 8 days. Help me understand

### Expected behavior

Next js doesn't break

### Version

https://swc.rs/docs/plugin/selecting-swc-core

**Comment by kdy1** [comment]
Please provide a repro, hopefully with failing CI

**Comment by kdy1** [comment]
We have integration tests for `@swc-project/plugins`, so we already verified that the official plugins are working with the current main branch.

**Comment by HeartyPorridge** [comment]
> Please provide a repro, hopefully with failing CI

https://github.com/HeartyPorridge/my-first-plugin/tree/main - repository.
I also put a wasm file in it that I compiled.

Please write back to me.
1) Does the plugin you are compiling work?
2) Does the plugin that I compiled work?

I beg you not to ignore me. I can't do it myself :(
