### ISSUE TITLE
Transform logical assignment panic when using together with private prop

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#7394]
### Describe the bug

es2021 introduced logical assignment ( ||=, &&=, ??= )
es2022 introduced private field ( this.#bar )

When transform logical assignment, SWC assert that there must not have any private field, as it should be processed by es2022::class_properties pass. [Code](https://github.com/swc-project/swc/blob/4a53951fe3fae82f231f444e6363a9290bc58337/crates/swc_ecma_transforms_compat/src/es2021/logical_assignments.rs#LL127C28-L127C28)

However private class field is supported from chrome 74, while logical assignment is supported from chrome 85.

So if I use browserslist query: chrome 75, it won't transform private field, but it will transform logical assignment, and logical assignment will find the private field, then assert failed

### Input code

```typescript
class Foo {
  #bar

  bar() {
    this.#bar ||= 1
  }
}
```

### Config

```json
{
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
  },
  "env": {
    "targets": "chrome 75"
  },
}
```

### Playground link

https://play.swc.rs/?version=1.3.57&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQUE5KLOIC0kBKQxMsoqBQkpFZrAeSUKipsVUwBIrVctUCADAllIY3AAAA&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYygZySxKL01BIgXym12MjAyEhJByJekFhUnFoEVwcUKa7MK0msAKksqSxILU4uyiwogaoGmVMMkiopKk0Fi9SCJMCEUmpeGbp1xSBTkjOK8nNTFcxNlSBKawGa4cWUnQAAAA%3D%3D

### Expected behavior

Transform correctly

### Actual behavior

Panic

### Version

1.3.57

**Comment by kdy1** [comment]
Closing as fixed.

https://play.swc.rs/?version=1.3.107&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQUE5KLOIC0kBKQxMsoqBQkpFZrAeSUKipsVUwBIrVctUCADAllIY3AAAA&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYygZySxKL01BIgXym12FRJByJYkFhUnFoEVwQUKa7MK0msACkrqSxILU4uyiwogaoGGVIMkiopKk0Fi9SCJIBELQDrZ4gVbwAAAA%3D%3D
