### ISSUE TITLE
`UsingDecl ` -> `TsUsingDecl`

### ISSUE THREAD

**Issue by punkeel** [swc-project/swc#7395]
### Describe the bug

Using swc from a Rust project, complains that `UsingDecl` isn't handled.

### Expected behavior

If it is a typescript-specific type, would it make sense to name it `*Ts*UsingDecl` to be in line with the current naming scheme of prefixing these types with Ts?

### Version

0.75.46 -> 0.76.7

### Additional context

cc @l4yton
Related issue: #7322

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/7316
