### ISSUE TITLE
SWC temporarily creates empty files and then writes data there

### ISSUE THREAD

**Issue by dko-slapdash** [swc-project/swc#7411]
### Describe the feature

Hi.

I noticed that, while building, when SWC is ready to write to a destination *.js file, and there is already such a *.js file, it first truncates the file to 0 length and then appends the compiler output. This produces a short time interval during which the file is technically empty. And if the file is picked up by e.g. node process during this period (examples: nodemon on dev environment as shown on the screenshot below, a node process restart in production etc.), then node basically reads nothing from this file (so all of the exports disappear). We even got an outage because of this once.

![CleanShot 2023-05-17 at 19 38 25@2x](https://github.com/swc-project/swc/assets/46383452/0fb9dece-9a00-4871-883f-1bf15ef20237)

A common way to solve this is to make file writes atomic: write to a *.js.tmp file nearby and then rename-over (rename is atomic in all OSes). This way, there will be no period of time when a destination file is empty.

P.S.
Increasing nodemon delay doesn't help here, because there could be multiple concurrent recompilations, and the behavior is still prone to race conditions.

**Comment by kwonoj** [comment]
I'm not sure if this is some kind of problem we want to fix / change. For me honestly, atomic behavior gain is not very high for the usecase of swc. You already explained this is coming from some sort of external watcher, and I don't immediately see other cases it can cause trouble, even for those watcher probably it makes some annoyances.

Am I missing something? any particular issue that blocked by this behavior? and any other prior references of existing js tooling? (I am aware other _apps_ do those a lot for several reasons, asking for the references for the similar dev tooling)

**Comment by dko-slapdash** [comment]
@kwonoj Not quite, it is not related to watchers. Basically, it doesn't matter how exactly a watcher works: in all cases there is a chance of having a race condition and picking up changes when a file is empty yet. It may appear empty even if I just manually restart a Node process when SWC compilation is in progress (or a Node process restarts by e.g. pm2 or any other orchestrator due to the previous node process crash).

I've never seen such a behavior in vanilla tsc or in webpack, so I assume they handle this. It's actually a pretty common pattern to compile in an atomic way via renaming (I suspect gcc does it too when building an elf executable for instance).

**Comment by kwonoj** [comment]
>  vanilla tsc or in webpack, so I assume they handle this.

If you can provide a proof / reference they do atomic file copying, would like to read it more. However, I still do not believe this is something we'll need to fix in an urgent manner.

**Comment by dko-slapdash** [comment]
@kwonoj Not quite too, it's unrelated to how exactly node.js or rust fs or whatever else flushes buffers. The effect will appear in any programming language when one overwrites a file by truncating it and writing over (or same effect, using "w" write mode in C's fopen() call). The only way to behave atomically in any of the languages and any of the OSes/FSes is to create a temporary file, write there, then rename-over.

It's a bit of work to provide evidences about tsc/webpack, I think it's enough to just mention that I've never seen any empty-file effect with them through the last 5 years at least (and I see the empty-file effect with swc literally every day when I restart our dev environment; sometimes I see it in production when a web server is crash-restarted while the new code is being built). But here is a link to how rsync does this (no magic: temp file + rename, it's a very well-known pattern): https://stackoverflow.com/a/6903839

And here you are about gcc:

<img width="792" alt="CleanShot 2023-05-22 at 14 44 03@2x" src="https://github.com/swc-project/swc/assets/46383452/643274a0-72a7-4f73-8df9-e969a26da29f">

**Comment by dko-slapdash** [comment]
Ugh hm... Well, thanks anyways. :-)
