### ISSUE TITLE
import xxx from '.' will be transpiled to the root file by mistake

### ISSUE THREAD

**Issue by tangye1234** [swc-project/swc#7417]
### Describe the bug

After swc 1.3.52，the swc will transpile the path '.' by mistake.

Command: `swc src -d dist`

Expect: `import x from '.'` should be  relative path index in the same source dir
Actual: `import x from '.'` will be compiled to the package root file by mistake

Notice. I have a path alias and jest profile.

### Input code

```typescript
// root index.js
require('./dist/index.js')

----------------------

// src/index.ts

async function main() {
  import('./lib/foo')
}

main()


// src/lib/index.ts

export default {}

----------------------

// src/lib/foo.ts

import o from '.'

export default function bar() {
  console.log(o)
}
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "target": "es2022",
    "parser": {
      "dynamicImport": true,
      "syntax": "typescript",
      "tsx": false,
      "decorators": false
    },
    "baseUrl": ".",
    "paths": {
      "@/*": [ "src/*" ]
    }
  },
  "exclude": ["\\btest\\b"],
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

// dist/lib/foo.js

const _ = /*#__PURE__*/ _interop_require_default(require("./index.js"));
...

### Actual behavior

// dist/lib/foo.js

const _ = /*#__PURE__*/ _interop_require_default(require("../../index.js"));
...

### Version

1.3.53+

**Comment by tangye1234** [comment]
👌 1.3.52
❌ 1.3.53+

**Comment by kdy1** [comment]
Do you know how does `tsc` behave?

**Comment by tangye1234** [comment]
> Do you know how `tsc` behave?

I've tested tsc and it is OK.

**Comment by tangye1234** [comment]
In my project, I get two snapshots for both building:
TSC:
![image](https://github.com/swc-project/swc/assets/447084/243a296e-44a3-4e1f-b1c2-2e7b21817db8)

SWC@latest
![image](https://github.com/swc-project/swc/assets/447084/463c6ab4-3e6d-4fd3-9170-92594765389e)

SWC@1.3.52
![image](https://github.com/swc-project/swc/assets/447084/cf361cf9-8198-4fce-94c9-46ae8199b922)

**Comment by kdy1** [comment]
I can't repro. Please see https://github.com/swc-project/swc/pull/7655

**Comment by kdy1** [comment]
I'll test again using the testing system of `swc` crate
