### ISSUE TITLE
Expose swc as a crate

### ISSUE THREAD

**Issue by DusterTheFirst** [swc-project/swc#742]
**Describe the feature**
It would be useful to be able to access and extend the compiler api of swc from rust and crates.io. From lib.rs it shows that the core swc module has not been published to crates.io but a few of the sub-crates have
![image](https://user-images.githubusercontent.com/14093962/78089809-6e3cfa00-7396-11ea-8764-a0ef4129e36b.png)

I feel like this could be useful in build scripts or could be use to extend the swc library with a custom runner (ex. embedding it into another project)

**Comment by kdy1** [comment]
@DusterTheFirst I think managing version will be too hard.
If it is absolutely required, I will publish it, but if not, I don't want to manage it

**Comment by DusterTheFirst** [comment]
Understandable
