### ISSUE TITLE
Plugins cannot import and use variables due to renaming in a later pass

### ISSUE THREAD

**Issue by arlyon** [swc-project/swc#7430]
### Describe the bug

I would like to support a 'fake' component that is essentially an injection point for my SWC plugin. Simply put my plugin converts this:

```tsx
import { TailwindStyle } from "stailwc";
const style = <TailwindStyle />;
```

To this:

```tsx
import { css, Global } from "@emotion/react";
const style =  <Global styles={css`lots of css`}/>
```

I have confirmed this works as demonstrated by this test: https://github.com/arlyon/stailwc/blob/master/src/test.rs#L39-L56, however it seems in a later step that this SWC does a renaming pass, detects that Global now clashes (despite that being the intention), and renames it.

### Input code

```typescript
import { TailwindStyle } from "stailwc";
const style = <TailwindStyle />;
```

### Config

```json
N/A
```

### Playground link

N/A

### Expected behavior

I expect my variables to be preserved.

### Actual behavior

SWC renames the import to `Global1`, breaking code.

```js
function _tagged_template_literal(strings, raw) {
    if (!raw) {
        raw = strings.slice(0);
    }
    return Object.freeze(Object.defineProperties(strings, {
        raw: {
            value: Object.freeze(raw)
        }
    }));
}
function _templateObject() {
    var data = _tagged_template_literal([
        "" // styles
    ]);
    _templateObject = function _templateObject() {
        return data;
    };
    return data;
}
import { css, Global as Global1 } from "@emotion/react";
var style = /*#__PURE__*/ React.createElement(Global, {
    styles: css(_templateObject())
});


//# sourceMappingURL=index.js.map
```

This can be avoided by inserting this code anywhere on the page, which works but is hacky.

```
// currently needed due to a swc bug
// ===
import { Global } from "@emotion/react";
Global;
// ===
```

New output is as follows: 

```js
// truncated template functions

import { css, Global } from "@emotion/react";
// currently needed due to a swc bug
// ===
import { Global as Global1 } from "@emotion/react";
Global1;
// ===
var style = /*#__PURE__*/ React.createElement(Global1, {
    styles: css(_templateObject())
});
```

Seems like `css` is not renamed, only the `Global` component is renamed. `css` is also imported and used but is not affected.

### Version

`swc_core@0.76.9`, `@swc/core@1.3.59`

**Comment by kdy1** [comment]
Please read docs
