### ISSUE TITLE
SWC could not parse `() => <Component<any>></Component>` while tsc could

### ISSUE THREAD

**Issue by hyf0** [swc-project/swc#7444]
### Describe the bug

tsc: https://www.typescriptlang.org/play?target=99&ts=5.0.4#code/BQSgBAvAfGA8DCB7AtgB0QOwKYYC6wEMMBPKKWAeiTUx1yiA

### Input code

```typescript
() => <Component<any>></Component>
```

### Playground link

https://play.swc.rs/?version=1.3.59&code=H4sIAAAAAAAAA9PQVLC1U7Bxzs8tyM9LzSuxScyrtLOz0YcL2HEBABELyhojAAAA&config=H4sIAAAAAAAAA02OvQ6DMAyEd54i8tyhytChbxOlpgoiEPmM1Ajx7nWgPyyW7zv7dGvnHA2IdHerrSZKELD8tBHUScPLCGktjCipKF2%2BrqJZKgvvZDsM0iBP1vbE8FfvPw%2BU05T6eo6Pcy7CgLE%2BjDjF7IPy%2FFhG%2FhdsJY7cG7WjbnsDOkAxqsUAAAA%3D

### Expected behavior

```js
"use strict";
() => React.createElement(Component, null);
```

### Actual behavior

```

  x Unexpected token `Component`. Expected jsx identifier
   ,-[input.tsx:1:1]
 1 | () => <Component<any>></Component>
   :        ^^^^^^^^^
   `----


Caused by:
    0: failed to process js file
    1: Syntax Error
```

### Version

1.3.59

### Additional context

This should be a regression, we don't hit the problem in the previous version.

**Comment by ifightcrime** [comment]
I tried `@swc/core@1.3.62` and I might be running into a similar issue. This started happening after I upgraded next.js from `13.4.1` -> `13.4.4`:

```
./features/bookings/form/bookable-fields.tsx
Error: 
  x Unexpected token `ConnectForm`. Expected jsx identifier
    ,-[/workspace/features/bookings/form/file.tsx:28:1]
 30 | }) => (
 31 |   <ConnectForm<BookableFieldsType>>
    :    ^^^^^^^^^^^
    `----

Caused by:
    Syntax Error
```

**Comment by kdy1** [comment]
@ifightcrime Please file an issue
