### ISSUE TITLE
References to destructured exports in namespaces aren't resolvable at runtime

### ISSUE THREAD

**Issue by yseymour** [swc-project/swc#7453]
### Describe the bug

Inside a namespace, referring to an exported property in the namespace generally works because it gets emitted as a `var` binding. However, when the export is defined using destructuring syntax, there are no such bindings and so any references to exports declared that way fail at runtime.

### Input code

```typescript
export namespace cli {
  export const { options, args } = parseCommandLine();
  export function run() {
    const command = args.shift();
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2022",
    "loose": false,
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.60&code=H4sIAAAAAAAAA0XMQQqDMBCF4b2neEuF0guUrtx6iWE62oCZhEwEQXL3xkZw9%2BDxf7LHkDKUvFgkFvDqcHSAtIODWsaBELOr8wFKi6HgjUjJZAzek34mp9IPrzubN%2BUzQNq0H%2F4gLotbUoWTetrXzbm1pSs%2FQPhzc48AAAA%3D&config=H4sIAAAAAAAAA22Quw6DMAxF934F8tyhYuzclY%2BwgkFB5CHbSEWIf294hFLRLfZ1zr32dCsK6MTAs5jSMxURWYiPOnVk9Irv1AEdI4lhGxXuWVVZpAZ7oaNXkwmMGliSpDzQKsybDorcki48kvJRljsL%2BhCEflmgjF6awO4cqKcWzfjKJrvH1b0ixRoV%2F4Vw1ttmPFNNcJFJ5LKNQ9%2F2R7CNcttJ4EI9rOJ%2BvuVEy2qJ5oLvBL6T2fGgg5Uqf18Dzh87elJPjwEAAA%3D%3D

### Expected behavior

Either emit a `var` binding for each destructured property, or rewrite the reference to the exported property from `args` to `cli.args` (`tsc` does the latter).

### Actual behavior

```js
var cli;
(function(cli) {
    ({ options: cli.options , args: cli.args  } = parseCommandLine());
    function run() {
        const command = args.shift();
    }
    cli.run = run;
})(cli || (cli = {}));
```

At runtime, `ReferenceError: args is not defined`

### Version

1.3.60

### Additional context

Here's the [tsc output](https://www.typescriptlang.org/play?module=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAdYBnEAYRwFtKpVgAZLVEACgEoAueAb3hwOx5iXWgE8ANPFgBzYfGIYYTaQG0AuvAC+AbgBQIAB4EcMDPFRRKIYkTAJIWHroCQh46fhghZ3v0GpiSRliLXgAXkIScioaOkZmdj1XIxMzFHR-eBg0didnZy8Asy9qWmBwqRhZADpiAAssRAxE3XgtXU0gA), for comparison.

```js
var cli;
(function (cli) {
    var _a;
    _a = parseCommandLine(), cli.options = _a.options, cli.args = _a.args;
    function run() {
        const command = cli.args.shift();
    }
    cli.run = run;
})(cli = exports.cli || (exports.cli = {}));
```

I had a quick look but only found #3073 as a possible related issue, which was quite a while ago.

**Comment by magic-akari** [comment]
I will fix this issue in #7202  . But it will take a long time. feel free if anyone can provide a quick fix.
