### ISSUE TITLE
Support the format preamble format option in swc.minify

### ISSUE THREAD

**Issue by mgol** [swc-project/swc#7475]
### Describe the feature

See https://swc.rs/docs/configuration/minification#jscminifyformat

> `preamble`, Currently noop

It should be possible to pass `preamble`. SWC should be able to insert it to the minified file without breaking source map associations.

### Additional context

FWIW, jQuery is currently switching from UglifyJS to Terser in https://github.com/jquery/jquery/pull/5258. We considered switching to SWC instead as it's way faster and optimizes better than Terser but the lack of the `preamble` option is a blocker for us at the moment.

**Comment by limerickgds** [comment]
@kdy1 Is this already in progress? If it's not urgent, maybe I can submit a PR next week?

**Comment by kdy1** [comment]
Not yet, and it would be so great. Thank you in advance!
