### ISSUE TITLE
`this` incorrectly transformed to `void 0` in CJS module

### ISSUE THREAD

**Issue by nwalters512** [swc-project/swc#7476]
### Describe the bug

In Node, `this` refers to `module.exports` in CommonJS files (assuming `this` doesn't otherwise have a value, such as within class member functions). However, SWC is transforming `this` to `(void 0)`, which breaks code that relies on this fact.

### Input code

```typescript
module.exports.foo = () => {
  console.log('foo()');
};

module.exports.bar = () => {
  this.foo();
};

module.exports.bar();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.61&code=H4sIAAAAAAAAA8vNTynNSdVLrSjILyop1kvLz1ewVdDQVLC1U6jmUlBIzs8rzgfK5%2BSna6gDJTU01TWtuWqtubhyUTUmJRahaCzJyASbpoFTOUgGAHfLSAx%2BAAAA&config=H4sIAAAAAAAAA1VPSwrDIBDdewqZdRfFZe%2FQQ4idBMUfjoFKyN2rVtNmN%2B%2FP7IxzMKTgwfd6VhBlIkwnrgwVn%2BW7MoDKSVJJxwy3qRpq0iItYaeOrwJZphVzT5G4CzESYEMgnInBOe31Uv43VXAxIdHV2KzSrxavi2ysgguvrYvjl1xiQ63NBW8Ifs65eLaDpueM57QhOz4ElsQAHAEAAA%3D%3D

### Expected behavior

I would expect `this` to appear in the output instead of `(void 0)`.

### Actual behavior

`this` is replaced with `(void 0)` in the output:

```js
"use strict";
module.exports.foo = ()=>{
    console.log('foo()');
};
module.exports.bar = ()=>{
    (void 0).foo();
};
module.exports.bar();
```

### Version

1.3.61

### Additional context

I'm not arguing that using `this` instead of `module.exports` is advisable; the latter is definitely clearer and less error-prone. However, when running some legacy code through SWC that _did_ use this, it did not execute correctly. I would not expect SWC to break otherwise functional code.

**Comment by jridgewell** [comment]
This is the correct behavior. You have `"isModule": true` in your configuration, which means that the file is interpreted as ESM and then transformed into CJS. For reference, [Babel behaves the same way](https://babeljs.io/repl#?browsers=Chrome%2060&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=LYewJgrgNgpgdDAHgBxAJwC4Gc4DMQgAEAvIQBQCUJAfIQN4BQhhAxiAHZYixxQgDmZAOT4QlIRQDcDAL7SGoSDySpMOAEYBDNCXJVitRswwALAJY5RlaXIYLw0eCvTY4WtNYZA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.22.4&externalPlugins=&assumptions=%7B%22iterableIsArray%22%3Atrue%7D)
