### ISSUE TITLE
Compiled code wrong after setting es5 and loose mode

### ISSUE THREAD

**Issue by LinsRock** [swc-project/swc#7477]
### Describe the bug

The following code compiles with the wrong es5 code after turning on loop mode with swc.

Output error code:

```javascript
var list = new Set({
    name: "leo"
});
var newList = new Set([].concat(list));

```

### Input code

```typescript
const list = new Set({name: 'leo'})

const newList = new Set([...list])
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.61&code=H4sIAAAAAAAAA0vOzysuUcjJBBK2Cnmp5QrBqSUa1XmJualWCuo5qfnqtZpcXMlgRUBZH1R10Xp6eiCtsZoAXbKqoEcAAAA%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxG95wCee7aDr1DD4GoE1HxJ9uRiqLcvZAAbTf8PtvPbJNS8GIDd7WVZymSJkYadSGcg%2Bh3ISA5IRuySeDSU%2BEazdoxHmg%2FExBNC0qdQr62dnAxMhYmtGJD3gY751%2BfiT4RMve1Q%2BV1WBz%2B26ZmBB%2Bf6xG2f9RbT%2FsNvk1dNhaD5UefrFdN%2BwdwPc9oEwEAAA%3D%3D

### Expected behavior

The expectation is that the logic of the downgraded code will be the same as the original code

### Version

1.3.61

**Comment by kdy1** [comment]
You should disable loose mode if you want your code to work. The loose mode has lots of assumptions, and your code does not respect it.
