### ISSUE TITLE
Plugin execution fails if plugin binary enables LTO

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#7479]
### Describe the bug

For the tracking purpose.

After recent upgrade to wasmer@3, we are observing plugin execution failure if the plugin binary is compiled with LTO enabled.

We do not have any clue yet - just know disabling lto makes it work in general.

### Expected behavior

Do not panic / crash

### Version

@latest

**Comment by niieani** [comment]
Thanks @kwonoj for referring me here. Based on your issue description, it seems like we do have a clue now.
In my experience the plugin works with LTO enabled, as long as `metadata.get_transform_plugin_config()` isn't called. 
It seems that this is in some way responsible for the crash.

**Comment by kdy1** [comment]
I think this issue can be closed as we updated `wasmer` to `v4.2.5` with https://github.com/swc-project/swc/pull/8624

**Comment by kdy1** [comment]
Note: The official plugins use LTO.

https://github.com/swc-project/plugins/blob/2324cb2aec86c2fa0cdd528f0edc7743cf259a86/Cargo.toml#L34
