### ISSUE TITLE
request: release newer version of swc_ecma_transforms

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#748]
Currently latest version of `swc_ecma_transforms` available at [`crates.io` is 0.7.0](https://crates.io/crates/swc_ecma_transforms). 

Unfortunately I'm unable to use it with latest version of `swc_common` because of conflict with `dashmap` version.

Thanks in advance!

**Comment by kdy1** [comment]
I published it

**Comment by bartlomieju** [comment]
Thank you @kdy1!
