### ISSUE TITLE
After turning on the compress switch, the compiled result of the factory function is empty

### ISSUE THREAD

**Issue by LinsRock** [swc-project/swc#7495]
### Describe the bug

After turning on the compress switch, the compiled result of the factory function is empty, why is this?

### Input code

```typescript
function funFactory() {
  return async function fun() {
    console.log('test')
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": true,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": true,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": true,
        "drop_debugger": true,
        "evaluate": true,
        "expression": true,
        "hoist_funs": true,
        "hoist_props": true,
        "hoist_vars": true,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": true,
        "keep_fargs": true,
        "keep_fnames": true,
        "keep_infinity": true,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": true,
        "reduce_vars": true,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": true,
        "unsafe_arrows": true,
        "unsafe_comps": true,
        "unsafe_Function": true,
        "unsafe_math": true,
        "unsafe_symbols": true,
        "unsafe_methods": true,
        "unsafe_proto": true,
        "unsafe_regexp": true,
        "unsafe_undefined": true,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.62&code=H4sIAAAAAAAAA0srzUsuyczPU0grzXNLTC7JL6rU0FSo5lJQKEotKS3KU0gsrsxLBsnClUHlFRSS8%2FOK83NS9XLy0zXUS1KLS9Q1geK1XLUAPtLDzlUAAAA%3D&config=H4sIAAAAAAAAA32UTW7jMAyF9z1F4HW3ncUcoLs5g6BYlKOOLBoilcQocvdS%2FkmDhurOfh9pWk8kP18Oh%2B6D%2Bu7v4VMe5WWymSDf30WhObG9itLxPAH1OUzcve6UqSJvI8Ei3VbSsc0DcM0CetvCu4hIsIdv2hhS8PNjwR7HKQPRgyaqfK%2BMkLjKnAu8PqKMF0U%2FIkaw6RdiLJmQGAbISlSPMdqJwJytjkdxKxBqFSosDM5MGSeVJxc4YBIrnqkD60yPDhQUMvQczqClSS1JSySna1AHxzIMyw3%2FwHC2sVhWEuG63If87DM7YSA2vmgerKxhwAp1Z4M3Gbhkpd4HhtTI%2Bg8gp4%2BWKNlRs2cJ8NJITfZbYkheWpXnZyxtrZ0wwSB2mhC84ml1BTIHrVwGV3qopvZtqntAwYEB76VFNHoJ3J%2B0knW00StALtZq%2F7%2FqpjV6G65T0KbvckBWu2oLGC2fmpDm8Yja8OzJwCd0bS43wNikWXbCdWrikhxIO4DTIgppep1LNowmLnvxqR9kHOSDZoh4%2FN4JW8Dtvm9Hm4Z436Hryn3ZAroRXVngtszrra4r%2BE%2F3HbQv3PsW7gL92zOXorcv%2B0WVgBgGAAA%3D

### Expected behavior

After turning on the compress switch, the compiled result of the factory function is empty

### Version

1.3.62

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.62&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMzwMx3BKTS%2FKLKjU0Faq5FBSKUktKi%2FIUEosr85JRlEHlFRSS8%2FOK83NS9XLy0zXUS1KLS9Q1geK1XLUAGN420VwAAAA%3D&config=H4sIAAAAAAAAA32UTW7jMAyF9z1F4HW3ncUcoLs5g6BYlKOOLBoilcQocvdS%2FkmDhurOfh9pWk8kP18Oh%2B6D%2Bu7v4VMe5WWymSDf30WhObG9itLxPAH1OUzcve6UqSJvI8Ei3VbSsc0DcM0CetvCu4hIsIdv2hhS8PNjwR7HKQPRgyaqfK%2BMkLjKnAu8PqKMF0U%2FIkaw6RdiLJmQGAbISlSPMdqJwJytjkdxKxBqFSosDM5MGSeVJxc4YBIrnqkD60yPDhQUMvQczqClSS1JSySna1AHxzIMyw3%2FwHC2sVhWEuG63If87DM7YSA2vmgerKxhwAp1Z4M3Gbhkpd4HhtTI%2Bg8gp4%2BWKNlRs2cJ8NJITfZbYkheWpXnZyxtrZ0wwSB2mhC84ml1BTIHrVwGV3qopvZtqntAwYEB76VFNHoJ3J%2B0knW00StALtZq%2F7%2FqpjV6G65T0KbvckBWu2oLGC2fmpDm8Yja8OzJwCd0bS43wNikWXbCdWrikhxIO4DTIgppep1LNowmLnvxqR9kHOSDZoh4%2FN4JW8Dtvm9Hm4Z436Hryn3ZAroRXVngtszrra4r%2BE%2F3HbQv3PsW7gL92zOXorcv%2B0WVgBgGAAA%3D

It should be exported. Unused functions should be removed
