### ISSUE TITLE
Support decorators on method parameters

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#750]
It seems like swc does not support decorators on parameters in methods and I forgot about this as well.

The following is valid TypeScript code:

```ts
class MyClass {
    myMethod(@myDecorator myParameter: string) {}
}
```

But the following error happens:

```
Line 2, column 14: Unexpected token Some(At)
```

Perhaps it's time for a `Parameter` AST node? https://ts-ast-viewer.com/#code/MYGwhgzhAECyCeBhcVoG8BQ1vQLb1gFMAXACwHsATACgAF8ARQ4cgJzGLb3gAUx3cJQqwBc0CMVYBLAHYBzAJToAvhmVA

**Comment by kdy1** [comment]
Is this valid in ecmascript? I failed to find any reference... It seems like valid only in typescript.

**Comment by dsherret** [comment]
It’s only valid TypeScript at the moment.
