### ISSUE TITLE
swc-loader breaks legacy-style webpack code splitting

### ISSUE THREAD

**Issue by Retsam** [swc-project/swc#7505]
### Describe the bug

Webpack supports code splitting via dynamic `import` syntax, but it also supports an older, legacy approach using `require.ensure`. This pattern, while no longer the recommended approach, has a bit more flexibility than the `import` approach making it difficult to migrate certain patterns away from it.  

This previously worked in SWC but stopped working in 1.2.204.  

As input, I've provided the example code from [webpack's documentation](https://webpack.js.org/api/module-methods/#requireensure) - and the relevant issue is also noted there:

> Although the implementation of `require` is passed as an argument to the callback function, using an arbitrary name e.g. `require.ensure([], function(request) { request('someModule'); })` isn't handled by webpack's static parser. Use require instead, e.g. `require.ensure([], function(require) { require('someModule'); })`.

SWC is now changing the parameter name, but that name is important to webpack's parsing analysis.

### Input code

```typescript
var a = require('normal-dep');

if (module.hot) {
  require.ensure(['b'], function (require) {
    var c = require('c');

    // Do something special...
  });
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.204&code=H4sIAAAAAAAAA02NOw7CMBQEe59iOzsSOAdAdNwCURjnJbFk%2BwV%2F0qDcHUNAop7ZndUkGJyR6FFdIiUjp2D8caBFdich3AgVeKie9Mylw1Pg52qKubbJVd7l7YCxRlscR6gv32VgbQn7n7Cf5zfqe1wYmQOV2cUJeSHrjNdaN7w1a3sBY1PcrKAAAAA%3D&config=H4sIAAAAAAAAA1WPSw7CMAxE9z1F5DVbWHAHDhEFtwrKT7ErEVW9O%2FkDu%2FjNTMY%2BFiHgRQru4sjPPAQZCeOcM6HkWL4zAU4BSUUdGC5DZSoSxx0rOZsALOOGXEJI1%2B4G4z1hZqs0hJ1Z7fSafvuUtyEi0b%2BxWKXbzMy3uqVXgvXPvYr9jrJrq7%2FB1zTK5seg6TGS9YjzA2yuiPwTAQAA

### Expected behavior

To be properly handle the code splitting, the output code needs to look like:

```ts
require.ensure(['b'], function (require) {
                             // ^^^^^^^^ - the param name is important here for webpack analysis
    var c = require('c');

    // Do something special...
});
```

### Actual behavior

The actual output is:
```ts
require.ensure(['b'], function (require1) {
    var c = require1('c');

    // Do something special...
});
```
and the webpack build breaks

### Version

1.2.204

### Additional context

Tried various module settings - both ES6 and CJS reproduced the issue.

**Comment by Austaras** [comment]
@kdy1 do you believe this issue is worth fixing?

**Comment by kdy1** [comment]
No, I don't.
Thank you!
