### ISSUE TITLE
source Map 

### ISSUE THREAD

**Issue by ygs-code** [swc-project/swc#7510]
### Describe the bug

Print while developing the environment

console.log() source code location is incorrect

### Input code

```typescript
Print while developing the environment

console.log() source code location is incorrect
```

### Config

```json
{
    "sourceMaps": true,
    "inlineSourcesContent": true,
    "jsc": {
        // 编译规则
        "target": "es5", // 输出js的规范
        "parser": {
            // 除了 ecmascript，还支持 typescript
            "syntax": "ecmascript",
            // 是否解析jsx，对应插件 @babel/plugin-transform-react-jsx
            "jsx": false,
            // 是否支持装饰器，对应插件 @babel/plugin-syntax-decorators
            "decorators": true,
            // 是否支持动态导入，对应插件 @babel/plugin-syntax-dynamic-import
            "dynamicImport": true
            // ……
            // babel 的大部分插件都能在这里找到对应配置
        },
        "minify": {} // 压缩相关配置，需要先开启压缩
    },
    "env": {
        // 编译结果相关配置
        "targets": {
            // 编译结果需要适配的浏览器
            "ie": "11" // 只兼容到 ie 11
        },
        "corejs": "3" // corejs 的版本
    },
    "minify": true // 是否开启压缩
}
```

### Expected behavior

Hope the source Map is located correctly

### Version

    "swc-loader": "^0.2.3",

### Additional context

  "dependencies": {
    "@swc/core": "^1.3.62",
    "cache-loader": "^4.1.0",
    "case-sensitive-paths-webpack-plugin": "^2.4.0",
    "clean-webpack-plugin": "^4.0.0",
    "compression-webpack-plugin": "^10.0.0",
    "copy-webpack-plugin": "^11.0.0",
    "cross-env": "^5.1.1",
    "css-minimizer-webpack-plugin": "^5.0.0",
    "directory-named-webpack-plugin": "^4.0.1",
    "dotenv": "^16.0.1",
    "esbuild": "^0.17.19",
    "esbuild-loader": "^3.0.1",
    "extended-define-webpack-plugin": "^0.1.3",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "glob": "^10.2.7",
    "happypack": "^5.0.1",
    "html-webpack-plugin": "^5.5.1",
    "json-loader": "^0.5.7",
    "less-loader": "^11.1.2",
    "mini-css-extract-plugin": "^2.7.6",
    "postcss-loader": "^7.3.2",
    "raw-loader": "^4.0.2",
    "sass": "^1.63.2",
    "sass-loader": "^13.3.1",
    "source-map-loader": "^4.0.1",
    "style-loader": "^3.3.3",
    "swc-loader": "^0.2.3",
    "terser-webpack-plugin": "^5.3.9",
    "thread-loader": "^4.0.2",
    "typescript": "^5.1.3",
    "url-loader": "^4.1.1",
    "webpack": "^5.86.0",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.0",
    "webpack-hot-plugin": "^0.0.3",
    "webpack-node-externals": "^3.0.0",
    "webpackbar": "^5.0.2"
  },

**Comment by kdy1** [comment]
Closing as duplicate

**Comment by ygs-code** [comment]
> Closing as duplicate

This is a bug and I don't understand why you shut it down without fixing it.

**Comment by ygs-code** [comment]
<img width="1571" alt="image" src="https://github.com/swc-project/swc/assets/20044598/c1c7a7a0-55be-4e03-913e-5ff801a87a2b">You may print me a journal。I open the log, do not know this log source in which position? Isn't that a bug? babel knew where the log was in the source code when he was developing it。

My swc configuration ： https://github.com/ygs-code/wepback-swc-esbuild  ，You download it.

There are also problems with swc and copy-webpack-plugin plug-ins

**Comment by kdy1** [comment]
This issue is completely useless, so I closed it. See https://github.com/swc-project/swc/issues/7506
