### ISSUE TITLE
Panicked when compiling with JS plugins

### ISSUE THREAD

**Issue by guiled** [swc-project/swc#7516]
### Describe the bug

Since the version of swc-code 1.3.17 I have an panicked error (see actual behaviour)

I use JS plugins. If I disable all of them, everything is OK, but if I have a plugin (even if it is an plugins that does nothing special), I have this error.

I manage to isolate the input code that raises this error (see input code section).
Here are some codes that don't raise errors
```js
function myGlob() {
    let a = 42;
};
myGlob();
```

```js
myGlob = function () {
    return 42;
};
myGlob();
```

### Input code

```typescript
myGlob = function () {
    let a = 42;
};
myGlob();
```

### Expected behavior

no error

### Actual behavior

Got this error 

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 5 but the index is 6', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_common-0.29.14/src/syntax_pos/hygiene.rs:386:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: failed to handle: index out of bounds: the len is 5 but the index is 6] {
  code: 'GenericFailure'
}
```

### Version

1.3.17

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/6255
