### ISSUE TITLE
[Optional chaining] ts only has first method attribute assertion ， case result wrong

### ISSUE THREAD

**Issue by yangaihe** [swc-project/swc#7526]
### Describe the bug

ts only has first method attribute assertion ， case result wrong

### Input code

```typescript
var themeConfig = {
    compHome: [
        {
            compKey: "TaskPage"
        },
        {
            compKey: "DDDDD"
        }
    ]
}
const ret = themeConfig?.compHome.find((item) => {
      return item.compKey === "TaskPage";
    });
    console.log("ret====", ret)
```

### Config

```json
{
  "env" : {
      "mode": "entry",
      "coreJs": 3,
      "forceAllTransforms": true,
      "dynamicImport": true,
      "targets": {
      },
  },
  "jsc": {
    "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true,
        "react": {
          // runtime: "automatic", // or classic
          "runtime": "automatic", //
          "throwIfNamespace": true,
          "useBuiltins": true,
          "development": false,
        },
      },
      "loose": true,
      "parser": {
        "syntax": "ecmascript",
        "jsx": false,
        "decorators": true,
      },
      "target": "es5",
  },
  "module": {
    "type": "commonjs"
  },
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.63&code=H4sIAAAAAAAAAytLLFIoyUjNTXXOz0vLTFewVajmUgCC5PzcAo%2F83FQrhWgwHwSq4SyYCu%2FUSisFpZDE4uyAxPRUJbh8rQ5BTS4ggKQDzIrlquVKzs8rLlEoSi0BugXJZfZ6MCfppWXmpWhoZJak5moq2NrBbQBqKS3KUwCJ60HtUbC1tUVynzVYZa2mNdSLecX5Oal6OfnpGkpAzUC1tko6IGM0AVbn3%2FMWAQAA&config=H4sIAAAAAAAAA2VSu27DMAzc8xUC5wAZii7ZWnRJgXTKDxAKkyrQwyDpNEbgf69kxI4jexAk3olH3fm%2BMgYoXsFszT3vywchHQm2pa7cwXos28T0LRl4m0qnxJY%2BvD8wRsmHUGDllibGsYsYnN2FJrHWoCKfScudUbsv2LDARewEgI4CM24uezqj7b4oj4aauOpf5EdoT4pHVFxSmNDqS1tjNhvDbVQXKNuAraaA6iysC5DYWI8izs4uwIMOC%2F6cpL%2Bc%2FnanHwwkDVpaDJM5rdBn67y6WHv5eNCVfGpCzibDJ%2FQyw%2Fv1qtqAT0lqHWiQhfjVSumi4m2I3QYUy65RmNl0kdtS8OlvPWxfhTw0lnd45pv%2FstbTLOKuGeyzKYQULwIT08l%2B5BaJVf8PfP2zz7YCAAA%3D

### Expected behavior

![image](https://github.com/swc-project/swc/assets/20334773/e6f72010-d0a5-41f7-af8c-dc1a8d7d84d0)

### Actual behavior

![image](https://github.com/swc-project/swc/assets/20334773/f7a28b16-5728-499e-84bd-5564285b5fef)

### Version

1.3.63

**Comment by loxygenK** [comment]
I also encountered to this behavior, and I'm believing the issue reproduced by this repository is the same cause of this issue:
https://github.com/loxygenK/swc-core-optional-chaining-this-issue

[`input.js`](https://github.com/loxygenK/swc-core-optional-chaining-this-issue/blob/main/input.js) transpiled by `@swc/core` (v1.3.63) outputs following to stdout:
```js
{ b: { c: [Function: returnThis] } }
```

`node input.js` outputs below on the other hand:
```js
{ c: [Function: returnThis] }
```

`@swc/core` with version 1.3.62 and older outputs as same as the `node input.ts` one.

#7441 might be related to this issue.
