### ISSUE TITLE
support dynamic import in amd module like tsc

### ISSUE THREAD

**Issue by moyy** [swc-project/swc#755]
swc version:

"@swc/cli": "^0.1.24",
"@swc/core": "^1.1.39",

====================== new feature

if translate to amd module with tsc, dynamic import now is support by require function. please consider support the feature in swc?

====================== tsc example

such test.ts show as below:

``` ts

export const read = () => {
        
    import("./b").then(({funcB}) => {
        funcB();
    });
}

```

and use tsc with version 3.8.3 in cmd line: "tsc -m 'amd' -t 'es2015' test.ts"

now get the output:

``` js

// Note: amd can add the require function
define(["require", "exports"], function (require, exports) {
    
    "use strict";
    
    Object.defineProperty(exports, "__esModule", { value: true });
    
    exports.read = () => {
        // Note: dynamic import now translate Promise and require
        new Promise((resolve_1, reject_1) => { require(["./b"], resolve_1, reject_1); }).then(({ funcB }) => {
            funcB();
        });
    };
});

```

====================== swc example

in swc, now: 

``` js

const swc = require("@swc/core");
const {readFileSync} = require("fs");

let srcPath = "src/test.ts";

let {code} = swc.transformFileSync(srcPath, {
    minify: false,

    module: {
        type: "amd", 
        moduleId: srcPath.slice(0, srcPath.lastIndexOf(".")),
    },
    
    jsc: {
        target: "es2015",
        
        parser: {
            syntax: "typescript",
            decorators: true,
            dynamicImport: true,
        },
    }
});

console.log(code);

```

we get the output as follow: 

``` js

define('src/test', [
    'exports'
], function(_exports) {
    'use strict';
    Object.defineProperty(_exports, '__esModule', {
        value: true
    });
    _exports.read = void 0;
    var read = function() {
       // Now: the import not translate now 
        import('./b').then(function(param) {
            var funcB = param.funcB;
            funcB();
        });
    };
    _exports.read = read;
});

```

**Comment by moyy** [comment]
and if i config the parser "dynamicImport" to false, and run the script, and get the except:

Error: failed to parse module
    at Compiler.transformFileSync (node_modules\_@swc_core@1.1.39@@swc\core\index.js:155:22)
    at Object.transformFileSync (node_modules\_@swc_core@1.1.39@@swc\core\index.js:197:21)
    at Object.<anonymous> (index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by kdy1** [comment]
@moyy Hmm... It seems like a breaking change. Bundlers typically depend on the dynamic import expressions.
Is the change of tsc enabled by default?

**Comment by moyy** [comment]
AS I kown,it's default feature in tsc with amd module, because I dont configure anymore. Hmm, can you confider that add  configure item: support tsc mode If user configure it, cant impl almost like tsc. that can avaoid affected old user? ------------------ 原始邮件 ------------------
发件人: "&#xAC15;&#xB3D9;&#xC724;"<notifications@github.com>
发送时间: 2020年5月1日(星期五) 下午4:11
收件人: "swc-project/swc"<swc@noreply.github.com>;
抄送: "moyy"<412001799@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [swc-project/swc] support dynamic import in amd module like tsc(#755)




 
@moyy Hmm... It seems like a breaking change. Bundlers typically depend on the dynamic import expressions.
 Is the change of tsc enabled by default?
 
&mdash;

**Comment by ws456999** [comment]
i have same problem

**Comment by moyy** [comment]
AS I kown,it's default feature in tsc with amd module, because I dont configure anymore. Hmm, can you confider that add  configure item: support tsc mode If user configure it, cant impl almost like tsc. that can avaoid affected old user?

**Comment by kdy1** [comment]
Oh... I didn't know that it's the default behavior.
I'll implement this as an enabled-by-default feature.
