### ISSUE TITLE
Optional chaining is not removed from ES2018 code

### ISSUE THREAD

**Issue by krasnoperov** [swc-project/swc#7553]
### Describe the bug

Nested optional chaining is not removed from ES2018 code

### Input code

```typescript
array?.map((el) => el?.field)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2018",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.63&code=H4sIAAAAAAAAA0ssKkqstNfLTSzQ0EjN0VSwtVNIzbHXS8tMzUnRBACKHDUQHQAAAA%3D%3D&config=H4sIAAAAAAAAA1VPSQ7DIAy85xXI5x7anqr%2BoY9A1ImI2IQdqVGUvwcI0PZmz%2BIZb4MQMJOCp9jSmJYgI2Hse0JodSw%2FCQFeA5KKOjBcGsuUKY4LFmQ%2FCWAZJ%2BRsQrpfb49qAOM9YYJHaQgrZrXT4%2FobqbwNEYn%2BhVkq3WS6%2F0wcaipY%2F14KWV%2FJdXODdM16NxN8lS2xXwdNr2Yvz%2BwHqlCzbBsBAAA%3D

### Expected behavior

```
"use strict";
array === null || array === void 0 ? void 0 : array.map((el)=>{
    return el === null || el === void 0 ? void 0 : el.field;
});
```

### Actual behavior

Second optional chaining is still there:
```
"use strict";
var _array_map, _object;
(_object = array) === null || _object === void 0 ? void 0 : (_array_map = _object.map) === null || _array_map === void 0 ? void 0 : _array_map.call(_object, (el)=>el?.field);
```

### Version

1.3.63

### Additional context

Version 1.3.62 generates valid code.

**Comment by kdy1** [comment]
Closing as duplicate
