### ISSUE TITLE
Reexporting of types not handled properly

### ISSUE THREAD

**Issue by maugenst** [swc-project/swc#7555]
### Describe the bug

Assuming that swc checks the type before adding it to the export list as types are not exported and export statements are removed. This code will fail during runtime.

### Input code

```typescript
// Test1.ts
export type TestType = {
    a: string;
};

export class TestClazz {
    constructor(props: TestType) {
        console.log(props);
    }
}
```

```typescript
// index.ts
export {TestClazz, TestType} from './Test1';
```

### Config

```json
{
    "module": {
        "type": "es6"
    },
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
            "decorators": true,
            "dynamicImport": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "target": "es2022",
        "loose": false,
        "minify": {
              "compress": false,
              "mangle": false
        }
    },
    "minify": false,
    "isModule": true,
    "sourceMaps": true,
    "inlineSourcesContent": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.65&code=H4sIAAAAAAAAA03PzQrCMAwA4HueIrc5kBWvK558hb1AqXUMalOaCPuh7%2B6smzOnkHzkRynsHMulEQY3RkqCMkVXit0nueICuIZpkSUNodeQNezWesNc8M2bed6spbDalxVKp5gocvubV29kZ%2BRd46n%2FslqXXoYMoBQO4e7Gv8OWY9H5ODDjI9ETq0aVRyoNb97pPjbUAAAA&config=H4sIAAAAAAAAA31RsU7FMAzc%2BYqnzB1QBwZWWBg68QVW6lZBSRzZrkT01H%2BnyaN9LQWy5e5y9l2uD5flmED95NE8X671XjHNqSAG5clUdG5u4g%2BxR2UCFuQDVnHJUeGzeBQvseySmuaoUSmCAbzgD6ZHSwxKLItAeTrxOUJw9i0kYv2WbIq52QVhiDIQh%2FOGHkew%2BXWd9Megle5QoQeFf4cBj6i33trHtt3lNZ5I8JzWBBfdkE%2FbLYylkBhFfq%2BoPIU4%2Bs3zvtHhwzb%2FnYdx0q2ffs9shCa22EE6lm5c9C7ie2XlhaJi3DqfvwD1pXu8RQIAAA%3D%3D

### Expected behavior

```javascript
// Test1.js
export class TestClazz {
    constructor(props) {
        console.log(props);
    }
}
//# sourceMappingURL=Test1.js.map
```

```javascript
// index.js
export { TestClazz } from './Test1';
//# sourceMappingURL=index.js.map
```

### Actual behavior

```javascript
// Test1.js
export class TestClazz {
    constructor(props){
        console.log(props);
    }
}

//# sourceMappingURL=Test1.js.map
```

```javascript
// index.js
export { TestClazz, TestType } from './Test1';

//# sourceMappingURL=index.js.map
```
And here the error occurs during runtime, as TestType is not exported. Expect that swc also removes type- or other exports from direct re-exports.

### Version

1.3.65

**Comment by kdy1** [comment]
Read the docs
