### ISSUE TITLE
support remove type only import like tsc

### ISSUE THREAD

**Issue by moyy** [swc-project/swc#756]
# support remove type only import like tsc

## tsc example

``` ts

import {funcA} from "./a"

export const read = () => {
    
}

```

now use tsc with cmd:  tsc -m "amd" -t "es2015" src/test.ts

we get the code:

``` js

// Note:  the a module is removed in output code

define(["require", "exports"], function (require, exports) {
    "use strict";
    
    Object.defineProperty(exports, "__esModule", { value: true });
    
    exports.read = () => {
    };
    
});

```

## swc example

``` js

const swc = require("@swc/core");
const {readFileSync} = require("fs");


let srcPath = "src/test.ts";

let {code} = swc.transformFileSync(srcPath, {
    minify: false,

    module: {
        type: "amd", // "amd", "commonjs"
        moduleId: srcPath.slice(0, srcPath.lastIndexOf(".")),
    },
    
    jsc: {
        target: "es2015", //  "es3" | "es5" | "es2015" | "es2016" | "es2017" | "es2018" | "es2019"
        
        parser: {
            syntax: "typescript",
            decorators: true,
            dynamicImport: true,
        },
    }
});

console.log(code);

```

run swc, we get code as follow, note the a module already exist.

``` js

define('src/test', [
    'exports',
    './a'
], function(_exports, _a) {
    'use strict';
    Object.defineProperty(_exports, '__esModule', {
        value: true
    });
    _exports.read = void 0;
    var read = function() {
    };
    _exports.read = read;
});

```

## typescript reference, Module side-effects

https://github.com/microsoft/TypeScript/wiki/FAQ#Modules

https://www.typescriptlang.org/docs/handbook/modules.html

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-exports

**Comment by moyy** [comment]
swc version:

"@swc/cli": "^0.1.24",
"@swc/core": "^1.1.39",

**Comment by kdy1** [comment]
How can we know if funcA is type-only import?
In javascript, an import statement can have side effects.


If you use funcA only in type position, swc treat the import as type-only import and will remove it.

**Comment by nayeemrmn** [comment]
Ref https://github.com/denoland/deno/pull/7413#issuecomment-690780261.
