### ISSUE TITLE
SWC minify and webpack DLL/Federation interoperability issues

### ISSUE THREAD

**Issue by kvet** [swc-project/swc#7568]
### Describe the bug

Hi,

I found that in the default minification configuration, swc removes a bit more than it should. Please take a look at the attached playground...

There is a `specific_microfront` variable that was defined and it was left untouched as it should, but the assignment to this variable was removed. Currently, I've disabled the `compress.unused` configuration to overcome the issue.

### Playground link

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA61XW2%2FbNhR%2BdoD8hxM91FLnWe82ggLrMqDACmzp3oJAYCQqZiKTLkklzQL99x1SpCTatJuiMwxYJs%2F1O1c9EQlqR0tWs7LYslKKWgqu1%2Bdn%2BXv7ySGtW15qJniawSvkOTzTux0pH38TQistyW5CO0taRQFPWamTqZDZEyoqCsdabEXVNlQVBVxC%2Bnp%2B1lPmkDiCvEQjCONU5pRr%2BZIPNu7IPU1Wnn60rShajrqrPRULoN92Qmq1mGiX9GvLJC0KdMjoNrb15J%2FJDi3Cw1myTFYw9RzPZpLqVnL4S4otU3RJmia9uc2WekN5iJIjjJ2lETvSZJk%2FC%2FlIpVpqlWTZGjr8ZojgrDs%2F69a9jfdUo3WDUO8hHn8pxY72RkbEL6%2BRzVMZmf7ZoG%2F8ivGIdIBk4dDJDO3sw4jVTf90m%2FY3qwEZSZVonmgawcZSzvRGimfg9BmupBQynX%2B2kiCZwy9OPj7ME6gEVcCFxjgypYFxGFJjObcAzWadUW%2Bfjznf8orWyFMZIheICSAeYMZZgLDaEEkt0cLeTWBmNaQXMXVfMhdpo8oI5WRrgE7QAtI2OnHHoql8DKJibgzf7dqqSgfid%2B9GxovLSxgtzGAf0%2BSjR8oaz0jD%2FiXGL6gJa2gFRAH6u8Ef0khKqhe4o5SPxEjyzPQGCFSsrqnEUuwVgjIak6OQO%2BNhat8E%2BRjLp9SwTGF2ccFSz%2BGfDVO%2Bkk3gNFYKaIF2KSxC9BpTxrQH6546P4tpqNKhFbz2NbCKFiheYO0tDPBoS5zG3CARWpitx%2B7VZYtJK0NEsQlGWpUrpr739H%2BW3rdLuDZsR4U%2BfG2pfPlxqQ9%2FG75ArH%2Fu%2B7N1xP39%2BU8%2BFW3jR31Vl6Tc0O9NhsJS2fHw2gVzJCLYhXgI1JTEn8VyzkH2qbKgjTxG7scNLR8Bi9xZjelnWs%2B%2B7dZ4e1q5BnZ51Jcbr%2B42cMh2kkCEqeuhYe3b5mtoyuHjHMrtDnzCjNQUq9m0COdXSngFu1abRsA4VhT26152duDn9u0e9kN0ajarVuCvF%2BFVI0hF8bomjaJ7d86zFaZB6NzRpDCeXn2jZYuu6jHtYskxiywkow%2FL0sz3sJL8JPS%2Fy5PbxUkb%2F2jI%2FdRA7MI9EAGhU9PfIKpatvSk2Os%2BPYxgX%2F2inugJ6F0ubY9nUXei9gy9moKMqu4eaKmnO84AbJBPsf68jWQW8p2q%2FgMLDis0pqk8kcNxdT%2F%2FCTvie79E57Llmm0pLrzbHdF2xXOLgosfhKwX4S4VBh%2B5f%2B%2BZr3reof3VAvuUVcHuWMP0Sz%2FZueC%2F4oTeCv7iY3ikQEb0%2BOEOetCk3LaKYxqJXWhwdXGJVhRUuV73IeSbxYZtz3Uzd7jMb3HywurNjGaXDonj20FvLy4HQFbe%2BC7bYx13BLxen2hJXXqk%2FP%2FnVNqriGkZgNnUzDsRKAH2NQpbfIOrC78388zsTndN2G9QgtJE6na3d%2FonNiAnw%2FcrHBwODdc4jg91R2DnefT1522vfSGikdfWQPyg9FgH6TLz3rL%2BD0uijNgDDwAA&config=H4sIAAAAAAAAA42VzY7bIBCA73mKyOcednuoVn2A3voMiMDgkGLGYsAba7Xv3jGxs0k9tnqymW9%2BYH7g43A8Nhcyzc%2FjB%2F%2FyoteJIN3XLKExZn1lSQOm02SS73PzbaEXmpDTgaCKPm%2BkyTq1kKsVfX95fZstmoBIsFjMss5H78bHmJ2ObYAHyeQR%2BwADhGfjiv4A9MoETRR1B7Sl4XZpn%2FygM%2FAXe0nJw5sgJe108q8vT0m4p4EVDHZ9AqLnw3B2SgcxS4F0Svg%2BgZzKo%2FyEGEDHHaI0KR8ztJAkxwZD0D2BGnQSvEw75bMQSiEmWDLYe3pWPFqfPUaOuaYWtFUGLQjIJzDZDyCZcSw2i4QBhPNUbOFU2ra27D%2FWMOhQuKICudaS8G4Fr2f0lJUrUUrhDW7k4Abn5K7ax6kEuaS4trugjxs1%2Bd%2FO5n7ast7veh8dT18eBc6jKp0yQjuNifdOyOyUGUjZS9VMYIuBKbNG2s6MN9JH3oIC57hXBNf07rM5S0Hz2AM6AXB9tZO66gbUfQo3%2BDQQO%2FgXnzLLDTZrdDqftymN3QnDToAO8hntjgKXIuM2TnxLXPttXqIFbg2wokqhCtaXAA9ARhXq1b%2FqDR4P9qjagKeva2K5MefvYVnUK7Tp0JaHl6DW8%2Faq%2FGi%2BlJYHZInYePq9GN4330AcHhzVB2raRFMdHT7%2FAoX%2FIggNBwAA

### Expected behavior

The assignment to an untouched variable shouldn't be removed

### Version

1.3.66

**Comment by kdy1** [comment]
Please read docs

**Comment by kdy1** [comment]
There's an option named `toplevel`
