### ISSUE TITLE
Specific but simple transformation fails with "index out of bounds" if a plugin is defined

### ISSUE THREAD

**Issue by rene-leanix** [swc-project/swc#7570]
### Describe the bug

The following Node.js code can be used to reproduce the issue. (`@swc/core@1.3.65` is installed)

```js
require('@swc/core').transformSync('fn((obj) => obj?.method());', { plugin: (module) => module });
```

This will throw a GenericFailure error with the message 'failed to handle: index out of bounds: the len is 3 but the index is 3'.

### Expected behavior

The code compiles to

```js
fn(function(obj) {
    var _obj;
    return (_obj = obj) === null || _obj === void 0 ? void 0 : _obj.method();
});
```

which it does, if the plugin is removed.

### Version

1.3.65

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/6255
