### ISSUE TITLE
`@swc/jest` class-transformer @Expose, @Exclude throw error Unexpected token `@`. Expected identifier...

### ISSUE THREAD

**Issue by omairnabiel** [swc-project/swc#7573]
### Describe the bug

While switching from `ts-jest` to `@swc/jest` few tests are failing due to decorators, with error.

`Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key`

### Input code

```typescript
import { Expose, Exclude } from 'class-transformer';

class Rule {
  @Exclude()
  id!: string;

  @Exclude()
  valueSource!: string;

  @Expose()
  field!: string;

  @Expose()
  value!: string;

  @Expose()
  operator!: string;

  @Expose()
  rules!: [Rule];

  @Expose()
  combinator!: string;

  @Expose()
  not!: boolean;
}
```

### Expected behavior

The tests should run without failing similar to `ts-jest`

### Version

@swc/core: 1.3.66, @swc/jest: 0.2.26

**Comment by kdy1** [comment]
I think you need `.swcrc`.

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA32PsQ4CIQyGd56iTqeJvoC3uPgCOhoHjiuGBCgpYEwu9%2B5yxDhIzomU7%2Bvf1rhAnGCC8ytQxH15lc0jwgyayUGnrIzxkFj6qIkdctcLUT%2Fhki3CJABOn6btrhRm3BwhJjb%2BUcwf%2BJQ245UyK2ysZX6VtEHbhnxxzVjHFJBlIl43uOwdC74tB9wbrMgNxv%2BP8JQKHIgsSt%2BL%2BQ36eJSQRwEAAA%3D%3D&config=H4sIAAAAAAAAA32RMW7DMAxF955C4BwgU5eMRZcO6R0ImU4VSKJAUk2MIHevbNSuUxfdKP4n8uvr9uQcnNXDwd1a2Q4mmLVnSUtrakc6oR9eybOgsTTRpNLuB%2Bhm6UiGHRpuESH09jDWuf3eSc0WEh0cYDVOaMHDbhRYnI%2BoGvzqAnzjsOHXkH0IX976d0ykBT1tzDSmKr3UEC1k%2FUvu6JMil0R59Nxj1JV%2Bn8ulgMis9JuEgqIkj1nqkA2v4wNsKKReQjFY5WR6%2FSff2ezGgKGcaPQKpM%2FTvEmDxF2NtPrhtnSkPKfE%2BaywkEGPMzttuH8Bzt5Mrx8CAAA%3D
