### ISSUE TITLE
Differing transpilation than tsc for constructor parameter properties

### ISSUE THREAD

**Issue by phiresky** [swc-project/swc#7574]
### Describe the bug

swc results in different runtime behaviour than tsc for constructor(readonly x) {}. This is not related to #7435.

### Input code

```typescript
class Foo {
	constructor(readonly game: string) {}

	x = this.game.toUpperCase();
}
```

### Config

```json
swc --config jsc.target=es2022
```

### Playground link

https://play.swc.rs/?version=1.3.61&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5uJMzs8rLikqTS7JL9IoSk1Myc%2FLqVRIT8xNtVIAimfmpWsqVNdycXFWKNgqlGRkFuuB5PRK8kMLClKLnBOLUzU0rblquQCXZn2sVAAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D

### Expected behavior

tsc outputs the following: 

```js
class Foo {
    game;
    constructor(game) {
        this.game = game;
    }
    x = this.game.toUpperCase();
}
```
this code is broken because the this.game assignment happens after the x assignment.

### Actual behavior

```js
class Foo {
    game;
    constructor(game){
        this.game = game;
        this.x = this.game.toUpperCase();
    }
    x;
}
```

this code works because the assignment of x is moved into the constructor by swc.

### Version

1.3.66

**Comment by kdy1** [comment]
@magic-akari AFAIK, Implicit class properties in typescript have no specification about execution order, right?

**Comment by magic-akari** [comment]
tsc input:

```TypeScript
class Foo {
	constructor(readonly game: string) {}
	x = this.game.toUpperCase();
}
```

tsc output:
```JavaScript 
"use strict";
// @target: es2022
// @useDefineForClassFields: true
class Foo {
    game;
    constructor(game) {
        this.game = game;
    }
    x = this.game.toUpperCase();
}

"use strict";
// @target: es6
// @useDefineForClassFields: true
class Foo {
    constructor(game) {
        Object.defineProperty(this, "game", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: game
        });
        Object.defineProperty(this, "x", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: this.game.toUpperCase()
        });
    }
}

"use strict";
// @target: es2022
// @useDefineForClassFields: false
class Foo {
    constructor(game) {
        this.game = game;
        this.x = this.game.toUpperCase();
    }
}


"use strict";
// @target: es6
// @useDefineForClassFields: false
class Foo {
    constructor(game) {
        this.game = game;
        this.x = this.game.toUpperCase();
    }
}
```

**Comment by kdy1** [comment]
Thank you!
