### ISSUE TITLE
Nested generics in TSX script fail to compile

### ISSUE THREAD

**Issue by alshdavid** [swc-project/swc#7580]
### Describe the bug

SWC errors when using nested generics in a `.tsx` file in a specific configuration. 

[SWC Playground](https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA0vOzysuUUitSMwtyElVsFXQ0FSwtVOo5lJQKEotKS3KAzMVFNJK85KtFJITc3KSEpOzbUoqC1Lz0xSK83NTSzIy89JtQoAChjoKIMrIzk4jv6AkE2gwyKi80pwcTaAZtdZctdYAU5fgz24AAAA%3D&config=H4sIAAAAAAAAA02OvQ6DMAyEd54i8tyhytChbxOlpgoiEPmM1Ajx7nWgPyyW7zv7dGvnHA2IdHerrSZKELD8tBHUScPLCGktjCipKF2%2BrqJZKgvvZDsM0iBP1vbE8FfvPw%2BU05T6eo6Pcy7CgLE%2BjDjF7IPy%2FFhG%2FhdsJY7cG7WjbnsDOkAxqsUAAAA%3D)
[Typescript Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBAhgGzQIxRA1gHgBUA+ACgkwC5FSUAnAc2vFzDgHcwBKRAXmMRgQGHgG8AvgChJoSLASIAznAC2AUygALGGAZEANAFUyKaoX2IqiQ12qjEpxOcvVDicYlGTEiOhpB0SF4+Pij63iGYEeIA3JJSklAAngAOak6pagCMfEpQdDoMcclpGWkATLlCKphqdHGSEAiKUIhqAB4oKilo6bw0PPyeEX5QAUERPrIQ1KgY2Hj4JWpwwEqqGtq6RJlZFoSZ5cRkcCnyYIp8AkIi0XGx0h1dPWqkXDFAA)

The code that fails:
```typescript
const example = () => {
  return {
    func: callback<typeof something<Type1, Type2>>(options => null)
  };
};
```

SWC succeeds when the nested generics are externalised ([playground](https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAAyupLEhVcE7MyUlKTM72LyjJzM8rVrBVKAEK56cpFOfnppZkZOal24QABQx1FECUkR0XVzJQWYlCakVibkFOKlC9hqaCrZ1CNZeCQlFqSWlRHpipoJBWmpdspZAMNd4GzR47jXyYhXYKeaU5OZpATbXWXLXWADSvpiqWAAAA&config=H4sIAAAAAAAAA02OvQ6DMAyEd54i8tyhytChbxOlpgoiEPmM1Ajx7nWgPyyW7zv7dGvnHA2IdHerrSZKELD8tBHUScPLCGktjCipKF2%2BrqJZKgvvZDsM0iBP1vbE8FfvPw%2BU05T6eo6Pcy7CgLE%2BjDjF7IPy%2FFhG%2FhdsJY7cG7WjbnsDOkAxqsUAAAA%3D))

```typescript
type CallbackOptions = typeof something<Type1, Type2>

const example = () => {
  return {
    func: callback<CallbackOptions>(options => null)
  };
};
```

I have tried different variations to see where the problem is but they seem to compile as expected

```typescript
const example = callback<typeof something<Type1, Type2>>(options => null)
```

### Settings

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "minify": {
      "compress": false
    },
  },
  "module": {
    "type": "es6"
  }
}
```

### Expected behavior

To strip the types

### Additional Info

This started happening with version 1.3.59 but was passing prior to that

[playground 1.3.58](https://play.swc.rs/?version=1.3.58&code=H4sIAAAAAAAAA0vOzysuUUitSMwtyElVsFXQ0FSwtVOo5lJQKEotKS3KAzMVFNJK85KtFJITc3KSEpOzbUoqC1Lz0xSK83NTSzIy89JtQoAChjoKIMrIzk4jv6AkE2gwyKi80pwcTaAZtdZctdYAU5fgz24AAAA%3D&config=H4sIAAAAAAAAA1WQvW7DMAyE9z6FoTmoCw8ZsrbIlilPQCh0w0J%2FICkgRuB3jyTHcbqJ3%2FF04N0%2Fus78iTWH7l6eZUjAgvyaC5EpKNwKMTolFMuU1OxWVaVKyhkbmRfBKPAvajWhDF%2FDYFbOEGSM7N8TsuAPjhTwGPnbgciR0F3k%2Be8rihGsvvkKIp8i6zlmtljDrqpJDn2P4j%2Fl2qfFstsMnIOSb7uQNXpQsuYpz%2F8ucDFK3RvBSb2tcePjJTvc6qqVLFfuzbZEgcZp9TZEclqdrav5AeQIxLB6AQAA)
[playground 1.3.59](https://play.swc.rs/?version=1.3.59&code=H4sIAAAAAAAAA0vOzysuUUitSMwtyElVsFXQ0FSwtVOo5lJQKEotKS3KAzMVFNJK85KtFJITc3KSEpOzbUoqC1Lz0xSK83NTSzIy89JtQoAChjoKIMrIzk4jv6AkE2gwyKi80pwcTaAZtdZctdYAU5fgz24AAAA%3D&config=H4sIAAAAAAAAA1WQvW7DMAyE9z6FoTmoCw8ZsrbIlilPQCh0w0J%2FICkgRuB3jyTHcbqJ3%2FF04N0%2Fus78iTWH7l6eZUjAgvyaC5EpKNwKMTolFMuU1OxWVaVKyhkbmRfBKPAvajWhDF%2FDYFbOEGSM7N8TsuAPjhTwGPnbgciR0F3k%2Be8rihGsvvkKIp8i6zlmtljDrqpJDn2P4j%2Fl2qfFstsMnIOSb7uQNXpQsuYpz%2F8ucDFK3RvBSb2tcePjJTvc6qqVLFfuzbZEgcZp9TZEclqdrav5AeQIxLB6AQAA)

### Version

1.3.66

**Comment by kdy1** [comment]
Closing as duplicate

**Comment by alshdavid** [comment]
@kdy1 Are you referencing https://github.com/swc-project/swc/issues/7187

My test case passes when placed in the same configuration. I am not sure if that means it has a different cause.

[playground](https://play.swc.rs/?version=1.3.44&code=H4sIAAAAAAAAA0vOzysuUUitSMwtyElVsFXQ0FSwtVOo5lJQKEotKS3KAzMVFNJK85KtFJITc3KSEpOzbUoqC1Lz0xSK83NTSzIy89JtQoAChjoKIMrIzk4jv6AkE2gwyKi80pwcTaAZtdZctdYAU5fgz24AAAA%3D&config=H4sIAAAAAAAAA1WQvW7DMAyE9z6FoTmoCw8ZsrbIlilPQCh0w0J%2FICkgRuB3jyTHcbqJ3%2FF04N0%2Fus78iTWH7l6eZUjAgvyaC5EpKNwKMTolFMuU1OxWVaVKyhkbmRfBKPAvajWhDF%2FDYFbOEGSM7N8TsuAPjhTwGPnbgciR0F3k%2Be8rihGsvvkKIp8i6zlmtljDrqpJDn2P4j%2Fl2qfFstsMnIOSb7uQNXpQsuYpz%2F8ucDFK3RvBSb2tcePjJTvc6qqVLFfuzbZEgcZp9TZEclqdrav5AeQIxLB6AQAA)

**Comment by kdy1** [comment]
My bad. I didn't read it carefully. Sorry for the mistake.

**Comment by alshdavid** [comment]
All good, thanks for re-evaluating!
