### ISSUE TITLE
optional chain error (@swc/core>=1.3.63) when using swc-plugin-vue-jsx

### ISSUE THREAD

**Issue by ja-plus** [swc-project/swc#7586]
### Describe the bug

[swc-plugin-vue-jsx github](https://github.com/g-plane/swc-plugin-vue-jsx)
Generate the wrong code. When using `swc-plugin-vue-jsx` and optional chain (`?.` )

### Input code

```typescript
let a = {};
a.b = 1;
let b = a?.b;
```

### Config

```json
{
  "env": {
    "targets": {
      "chrome": "49"
    },
    "mode": "usage",
    "coreJs": "3.31",
  },
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "externalHelpers": true,
    "experimental": {
      "plugins": [  // remove the plugin will be normal
        [
          "swc-plugin-vue-jsx",
          {}
        ]
      ]
    }
  },
}
```

### Expected behavior

var a = {};
a.b = 1;
var b = a === null || a === void 0 ? void 0 : a.b; // @swc/core@1.3.62 result

### Actual behavior

var _this;
var a = {};
a.b = 1;
var b = (_this = this) === null || _this === void 0 ? void 0 : _this.; // here

### Version

&gt;= 1.3.63

### Additional context

Plugin's author thinks it is a SWC bug

**Comment by kdy1** [comment]
I think this is a duplicate

**Comment by kdy1** [comment]
Closing as already fixed

**Comment by jridgewell** [comment]
@kdy1 Which commit fixed this? It seems like this might be related to https://github.com/swc-project/swc/issues/7572, which was using a different plugin.

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA8tJLVFIVLBVqK615krUSwKyDK25coCCIGaivV6SNQBamkXTIgAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D


It's fixed in [v1.3.64](https://play.swc.rs/?version=1.3.64&code=H4sIAAAAAAAAA8tJLVFIVLBVqK615krUSwKyDK25coCCIGaivV6SNQBamkXTIgAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D) so the fix should be https://github.com/swc-project/swc/commit/4644d005d2ca06ad002dc7c6ff6c4d19e1734970

**Comment by jridgewell** [comment]
I think this is a different bug:

```
var b = (_this = this) === null || _this === void 0 ? void 0 : _this.;
```

Notice that weird `this.;`, that seems like it's different than the receiver context that #7526 fixed.

**Comment by cjthompson** [comment]
I ran into this same error when upgrading from 1.3.58 to 1.3.66.

Here's some examples of the errors:
input:
```ts
const validDate = parse(value, `${parseFormat.join('-')}${parts.groups?.tz ? ' XXX' : ''}`, new Date());
```
output:
```js
const validDate = (0, _datefns.parse)(value, `${parseFormat.join('-')}${this?. ? ' XXX' : ''}`, new Date());
```

input:
```ts
const searchKey = options?.namespaceIncluded ? `//${key}` : `//mismo:${key}`;
```
output:
```js
const searchKey = (void 0)?. ? `//${key}` : `//mismo:${key}`;
```

input:
```ts
export const isPlural = memoize((word?: string): boolean =>
  Boolean(word && (word?.endsWith('S') || word?.endsWith('s')) && !NON_PLURAL_WORDS.includes(word.toUpperCase()))
);
```
output:
```
const isPlural = (0, _memoize.memoize)((word)=>Boolean(word && ((void 0). || (void 0).) && !NON_PLURAL_WORDS.includes(word.toUpperCase())));
```

**Comment by fz6m** [comment]
### Minimal reproduction

1. create an empty swc plugin, do nothing:

```rust
use swc_core::{
    ecma::{ast::Program, visit::FoldWith},
    plugin::{plugin_transform, proxies::TransformPluginProgramMetadata},
};
use swc_core::ecma::{
    visit::{as_folder, VisitMut},
};

pub struct TransformVisitor;

impl VisitMut for TransformVisitor {
    
}

#[plugin_transform]
pub fn auto_css_modules(program: Program, _: TransformPluginProgramMetadata) -> Program {
    program.fold_with(&mut as_folder(TransformVisitor))
}
```

2. transform tsx and use optional chaining:

```ts
import { transformSync } from '@swc/core'

const run = async () => {
  const code = `
<Exception
  route={matchedRoute}
  noFound={runtimeConfig?.noFound}
  notFound={runtimeConfig?.notFound}
  unAccessible={runtimeConfig?.unAccessible}
  noAccessible={runtimeConfig?.noAccessible}
>
  {runtimeConfig.childrenRender
    ? runtimeConfig.childrenRender(<Outlet />, props)
    : <Outlet />
  }
</Exception>
`;
  transformSync(code, {
    jsc: {
      experimental: {
        plugins: [
          [
            require.resolve(
              '../target/wasm32-wasi/release/swc_plugin_auto_css_modules.wasm'
            ),
            {}
          ],
        ],
      },
      parser: {
        syntax: 'typescript',
        dynamicImport: true,
        tsx: true,
      },
      target: 'es2015',
      minify: {
        compress: false,
        mangle: false,
      },
      transform: {
        react: {
          runtime: 'automatic',
          pragma: 'React.createElement',
          pragmaFrag: 'React.Fragment',
          throwIfNamespace: true,
          development: true,
          useBuiltins: true,
        },
      },
    },
    module: {
      type: 'es6',
      ignoreDynamic: true,
    },
    minify: false,
    isModule: true,
    sourceMaps: false,
    filename: 'index.tsx',
  })
}

run()
```

3. error occurred:

```ts
thread '<unnamed>' panicked at 'invalid utf8 character detected: FromUtf8Error { bytes: [118, 97, 114, 32, 95, 116, 104, 105, 115, 44, 32, 95, 116, 104, 105, 115, 49, 44, 32, 95, 116, 104, 105, 115, 50, 44, 32, 95, 116, 104, 105, 115, 51, 59, 10, 105, 109, 112, 111, 114, 116, 32, 123, 32, 106, 115, 120, 68, 69, 86, 32, 97, 115, 32, 95, 106, 115, 120, 68, 69, 86, 32, 125, 3
......
```

If don't use the swc plugin, everything works fine.

**Comment by kdy1** [comment]
@fz6m It's a separate issue. Please file one.

**Comment by kdy1** [comment]
If this does not occur with a Wasm plugin, it's a bug of the Wasm plugin.

**Comment by kdy1** [comment]
Please tell the plugin author to check AST using playground.
I think the plugin is generating a wrong AST

**Comment by kdy1** [comment]
codegen does not panic on invalid AST, and correct codegen does not mean that AST is correct

**Comment by ja-plus** [comment]
@g-plane here
