### ISSUE TITLE
Source maps not generated in swc.minify

### ISSUE THREAD

**Issue by mgol** [swc-project/swc#7588]
### Describe the bug

When you run the exact code snippet that is shared in the docs at:
https://swc.rs/docs/configuration/minification#swcminifycode-options
just with the `console.log` at the end:
```js
import swc from "@swc/core";
 
const { code, map } = await swc.minify(
  "import foo from '@src/app'; console.log(foo)",
  {
    compress: false,
    mangle: true,
  }
);
 
console.log('map', map);
```
you'll see `map` is undefined.

There's also no option documented on that page that would allow enabling source maps.

The described return type: `Promise<{ code: string, map: string }>` - is also incorrect because of that.

### Input code

```typescript
Doesn't matter
```

### Config

```json
No config file
```

### Playground link

Playground doesn't produce source maps so it wouldn't help with this issue.

### Expected behavior

1. The source map should be generated
2. If there's an option to enable source maps, it should be documented on the minify page

### Actual behavior

No source maps are generated.

### Version

1.3.66

### Additional context

This is me trying to switch jQuery minification from Terser to SWC again since my previous blocker, the missing `preamble` option, was fixed in #7475.

**Comment by mgol** [comment]
@jridgewell that doesn't work:
```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: unknown field `source_map`, expected one of `parse`, `compress`, `mangle`, `format`, `ecma`, `keep_classnames`, `keepClassnames`, `keep_fnames`, `keepFnames`, `module`, `safari10`, `toplevel`, `sourceMap`, `outputPath`, `inlineSourcesContent`, `emitSourceMapColumns` at line 1 column 44] {
  code: 'InvalidArg'
}

Node.js v18.16.1
```

**Comment by mgol** [comment]
Oh, it's `sourceMap`, I see. Could it be added to the documentation?

**Comment by jridgewell** [comment]
Oh, sorry! I forgot about the [snake_case to camelCase](https://github.com/swc-project/swc/blob/ed9a4ae5bc73b54641fc3f60843eb96c8cff6145/crates/swc/src/config/mod.rs#L1052) conversion.

> Could it be added to the documentation?

Happy to accept a PR!

**Comment by mgol** [comment]
@jridgewell I was looking into a PR but I am confused about source map options. You mentioned SWC tries to follow Terser's SM options but whatever I try, SWC-produced source maps contain an inline source in the `sourcesContent` field. jQuery doesn't use that but it instead uses the `sources` field pointing to the `jquery.js` source file.

I tried to pass `includeSources: false` but it's not a recognized option, apparently:
```
Fatal error: unknown field `includeSources`, expected one of `filename`, `url`, `root`, `content` at line 1 column 326
```

**Comment by jridgewell** [comment]
That one is called `inline_sources_content`/`inlineSourcesContent`: https://github.com/swc-project/swc/blob/ed9a4ae5bc73b54641fc3f60843eb96c8cff6145/crates/swc/src/config/mod.rs#L1090-L1091

I'm not sure why we diverged from Terser's naming there…

**Comment by mgol** [comment]
Oh, and this option is not under `sourceMap` but at the top level; that works, thanks!

One last question: I can't make the `sources` field populated properly; I'm getting `"sources":["<anon>"]` in the map file. I thought specifying [`sourceMap.root`](https://github.com/swc-project/swc/blob/ed9a4ae5bc73b54641fc3f60843eb96c8cff6145/crates/swc/src/config/mod.rs#L1112) would set it bit that does not happen... Is there any other option that I need to set?

**Comment by mgol** [comment]
@jridgewell Hey, can you answer my last question? I'd be happy to work on the site updates once that is clarified (plus finalize switching jQuery from Terser to SWC).

**Comment by mgol** [comment]
Oh, and also, apart from a malformed `source` property, the `file` property is also missing - it should point to the minified file.

Here's what we had in jQuery when using UglifyJS:
```json
{
	"version": 3,
	"file": "jquery.min.js",
	"sources": [
		"jquery.js"
	],
	"names": [
		"global",
		"factory",
		"..."
	],
	"mappings": ";CAUA,SAAYA,EAAQC,..."
}
```
I've posted the UglifyJS version as we have some issues with Terser's `file` & `source` fields (https://github.com/jquery/jquery/issues/5285); the UglifyJS ones look correct.

Here's what I'm getting with SWC:
```json
{
	"version": 3,
	"sources": [
		"<anon>"
	],
	"names": [
		"global",
		"factory",
		"..."
	],
	"mappings": ";CAUA,AAAE,SAAUA,..."
}
```

**Comment by kdy1** [comment]
@mgol What's the option you passed to `terser`? 

```json
"sources": [
		"jquery.js"
	],

```

Basically, this is impossible for `minify(code: string)` because it does not know if the input is a file. So there should be another option (of `terser`) swc does not handle...

**Comment by kdy1** [comment]
Closing as not actionable
