### ISSUE TITLE
Writing custom transform plugins in Rust?

### ISSUE THREAD

**Issue by vovaguguiev** [swc-project/swc#759]
Is it currently possible to write a custom transform plugin and use swc from Rust code? My planned use-case is a Rusty program that compiles to WASM, accepts Uint8Array containing the data of the file to transform (custom transformation) and returning Uint8Array back to JS

**Comment by kdy1** [comment]
If you guys need any help while doing so, please feel free to ping me on github / slack. I'll help as mich I can

**Comment by vovaguguiev** [comment]
I've just started, but I think I got it so far. I'll ping you on Slack if I will have other questions thanks!
