### ISSUE TITLE
SWC do not work properly when I use import path aliases in Windows Device?

### ISSUE THREAD

**Issue by siamahnaf** [swc-project/swc#7592]
### Describe the bug

I want to use swc into nestjs. I already create an [issue ](https://github.com/nestjs/nest/issues/11891) into nestjs and we can understand that swc doesn't behave perfectly when we use `SWC` into a Windows Device?

Here is my tsconfig.json-

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

I do not create any `.swcrc` configuration file because as I am using `nestjs`, `nest cli` package automatically doing it for me?

The error is -

![image](https://github.com/nestjs/nest/assets/78312010/51fe365f-6dc6-4608-85c2-82327aa7c9c9)

Here is another picture, I am showing one of the build files-

![image](https://github.com/nestjs/nest/assets/78312010/5c6c5bd8-cddc-4080-9fc5-0cf0b2ad994c)

In the picture I can I see that-

const _studententity = require("G:/Codestation21/e-campus/server/src/student/model/student.entity");

SWC compile path like above. Why swc compile in this way where default typescript compiler compile like-

const _studententity = require("../student/model/student.entity");

Why swc give the full path of the file when compilation?

`Note: ` The problem only occured when we use Windows device. But in unix or macOs it works perfectly?

`Please Note: I already find a similar issue in SWC. I can't figure out anything because issue was closed just by said that they can't reproduce it ` 

### Playground link

https://github.com/siamahnaf/swc-error

### Expected behavior

SWC should compile path like
`const _studententity = require("../student/model/student.entity");`

Instead of-

`const _studententity = require("G:/Codestation21/e-campus/server/src/student/model/student.entity");`

### Version

1.3.66

```[tasklist]
### Tasks
```

**Comment by kdy1** [comment]
Closing as duplicate

**Comment by siamahnaf** [comment]
Can you give me the actual issue link?

**Comment by siamahnaf** [comment]
> Closing as duplicate

@kdy1 I want to see the solution. Please give me the actual link as you say it duplicate?
