### ISSUE TITLE
BigInt Exponentiation incorrectly converted to Math.pow

### ISSUE THREAD

**Issue by aureliusbtc** [swc-project/swc#7606]
### Describe the bug

BigInts shouldn't be transpiled to Math.pow as it results in a TypeError:

TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)

### Input code

```typescript
const power = 18n;
const base = 10n;
base ** power
```

### Config

```json
NextJS default
```

### Expected behavior

Should return an exponentiated BigInt in place of Math.pow conversion

### Version

latest nextjs

**Comment by kdy1** [comment]
Is this fixable? 

[babel playground](https://babeljs.io/repl#?browsers=chrome%2010&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBADiA7gUwE4wLwwIwA4wDcAUKJLAEYCGEymOADIUVTTAFRvxJpA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.22.5&externalPlugins=&assumptions=%7B%7D)

**Comment by kdy1** [comment]
It's flaw of javascript, not SWC nor babel IMO
