### ISSUE TITLE
Debugging Typescript file with VS Code shows transpiled Javascript file

### ISSUE THREAD

**Issue by dotoleeoak** [swc-project/swc#7609]
### Describe the bug

I tried to debug Typescript file with @swc/require, but in VS Code, the breakpoint is hit in transpiled Javascript file, not Typescript. I assume that the sourcemap is broken, or not generated.

It seems this issue is related, but it is Jest case. I don't have jest.config.js.
https://github.com/swc-project/jest/issues/61

Below is the example repo with reproduction.
https://github.com/dotoleeoak/swc-debugging

### Breakpoint set on Typescript

<img width="600" alt="image" src="https://github.com/swc-project/swc/assets/19747913/bec5429a-0e13-48d2-8449-175256a71409">

### Debugger shows transpiled Javascript

<img width="600" alt="image" src="https://github.com/swc-project/swc/assets/19747913/57928dfe-f6fe-4415-8b5d-151b5aa21e58">

### Config

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "sourceMaps": "inline",
    "jsc": {
        "parser": {
            "syntax": "typescript"
        }
    }
}
```

### Expected behavior

The breakpoint has to be hit in Typescript file with correct sourcemap.

### Actual behavior

The breakpoint is hit in transpiled Javascript file.

### Version

1.3.67

**Comment by kdy1** [comment]
Please read docs about sourcemaps

**Comment by dotoleeoak** [comment]
@kdy1 Thanks for the comment. I tried `"inline"` and `true` option both for source map, but the behavior is same.

**Comment by dotoleeoak** [comment]
For everybody who are suffering from the same issue:
I solved this issue by replacing `@swc/register` with `@swc-node/register`.
As my guess `@swc/register` is not actively maintained, so it would be better to use the latter one.
