### ISSUE TITLE
Evaluator does not handle binary expressions

### ISSUE THREAD

**Issue by levi-nz** [swc-project/swc#7626]
### Describe the feature

Evaluator does not handle binary expressions: https://github.com/swc-project/swc/blob/7544ea960bf0be097cda2224747eb561b5748317/crates/swc_ecma_minifier/src/eval.rs#L92

Not sure if this is intended, but somewhere (can't find the link right now) it states the equivelent of Babel's `path.evaluate()` is to use Evaluator, but this is misleading since it can't handle binary expressions.

When using the `swc_ecma_transforms::optimization::simplify::simplifier` transform, binary expressions like `5 + 5 + 5 + 5` are evaluated into `20` so this feature does exist somewhere, just not in Evaluator specifically. I think this needs to be more clear because beginners (like me) have nowhere to look regarding evaluation.

Couldn't find an issue related to evaluator so decided to create one.

**Comment by kdy1** [comment]
I believe you are not using it correctly.

**Comment by levi-nz** [comment]
> I believe you are not using it correctly.

Could you please elaborate further? This isn't very helpful. I provided a link which shows the Evaluator doesn't handle binary expressions. Somewhere on the SWC documentation, it states Evaluator is equivelent to Babel's `path.evaluate()`. I know this feature exists because `simplifier` does this some how.
