### ISSUE TITLE
Jest with swc, `Cannot use 'import.meta' outside a module`

### ISSUE THREAD

**Issue by Codex-** [swc-project/swc#7636]
### Describe the bug

I've been adopting the usage of `@swc` for testing in our Jest test suite for a react application and encountered the issue where when attempting to transpile `import.meta.env` swc does not transpile this module code to anything cjs compliant.

Reproduction: https://github.com/Codex-/swc-jest-import-meta

### Input code

```typescript
if (import.meta.env.MODE === "test") {
  console.log("test");
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "importMeta": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA33MQQ5AMBAAwPu%2BYm%2B4tJ%2FATbyhqcUmq5V2CRF%2F5y4xDxhrsXUsGXjEkpc1JjULqTMUdtP1dVPhBfjyMeQoZCROZaGUtajgBrAWm2MV9qxy4uzCIDR8si3J%2F%2FMAvPJxp4cAAAA%3D&config=H4sIAAAAAAAAA1VPSwrDIBDdewqZdRchy96hhxA7CYo%2FHAOVkLtXjabNbt6f2RnnoEnCk%2B%2FlLCCISBgvXBjKLolPYQClFSSjCgkeQ9VUpUUYwkYdpwJJxBVTS9E8zVNPgPGecCQ6Z5VTS%2F7flN6GiER3Y7UKtxq8L7K%2BCta%2Ftyb2X1IOFdU2650m%2BDnH4tUOil4jnuKG7PgC3iNNFRwBAAA%3D

### Expected behavior

Some compilation error where the syntax isn't handled, or for jest specifically, `process.env["MODE"]`? Unsure what the best solution is here

### Actual behavior

Takes the commonjs invalid `import.meta.env...` verbatum 

### Version

1.3.68

**Comment by Codex-** [comment]
Or is this a case where using a plugin is expected, such as https://www.npmjs.com/package/@import-meta-env/swc

**Comment by kdy1** [comment]
Yeah you should use a plugin. `import.meta.env.MODE` is not a standard

**Comment by Codex-** [comment]
For anyone stumbling across this, I've published this plugin to handle a basic transformation for this: https://github.com/Codex-/swc-plugin-import-meta-env
