### ISSUE TITLE
Renamer assigns a function name caused a failure on assigning variable in function body

### ISSUE THREAD

**Issue by h-a-n-a** [swc-project/swc#7643]
### Describe the bug

This is a bug introduced from `1.3.43` and future versions.

~Although it is an internal project for our company and I haven't dig into this completely,
I can still give you some input of this issue.~

The following input code is transpiled incorrectly.
For the input code, there's no function name assigned to `C1`, which means `C1` can be overridden. However, for the actual behavior, `C1` is assigned as a function name, which, in strict mode, is a `TypeError: Assignment to constant variable.`: 
```js
// simple example for describing the behavior after mistranspilation.
'use strict';
var C = function C() {
  return (C = Object.assign); // TypeError: Assignment to constant variable.
};
C(); 
```

From my perspective, this might be an issue related to renamer and maybe introduced by this PR: https://github.com/swc-project/swc/pull/7116.

~More information will be added as soon as I can create a minimal repro.~

Edit: 
Added a minimal repdocution.
To make the behavior as expected, you can either comment out Line A or Line B.

### Input code

```typescript
var a = function (e, t, n) {
  'use strict';
  var y = function (e, t, n, r, o) {
    var C = function (n) {}; // Line A
  };
  var C = function () {
      return C = Object.assign;
  }
};
eval(); // Line B
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "mangle": false,
      "compress": false
    },
  },
  "module": {
    "type": "commonjs"
  },
  "isModule": false,
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.3.43&code=H4sIAAAAAAAAA22MQQqEMBAE73lF31QIfkD2tA%2FwDTGMkmUZYTIJiPh3o%2BJB8Nh0VWUncPhgTOw1zIyaLNSCG6wGqFIkRJXgterKzgVf3nALsZgv6cK%2BD%2BzobUdhuzPP%2FzYBIU3C590PP%2FLauhjDxKdsik7Z%2FeumMzvyUFLzuwAAAA%3D%3D&config=H4sIAAAAAAAAA2VPSw4CIQzdewrStVs33sFDNMhMIBQIxUQymbsLDDBGN03frw%2B2ixBgWMJdbGUtIGBkFScuDGeX8F0YUJKQZdQhwXWohqu0oGXVqP1QIGFcVWopvnU7WO9ZDXvnSDu95O9CQrfaH1uhpacQFfN%2FXRtA%2Fvlqsf6TlENFNUfeGYbp1PwY3llxvuM4vn8Aznx4DBsBAAA%3D

### Expected behavior

```ts
var a = function (e, t, n) {
  'use strict';
  var y = function (e, t, n, r, o) {
    var C = function (n) {};
  };
  var C = function THIS_IDENTIFIER_SHOULD_BE_NOT_THE_SAME_AS_C() {
      return C = Object.assign;
  }
};
eval();
```

### Actual behavior

```ts
var a = function a1(e1, t1, n1) {
    "use strict";
    var y1 = function y1(e1, t1, n1, r1, o1) {
        var C1 = function C1(n1) {};
    };
    var C1 = function C1() {
        return C1 = Object.assign;
    };
};
eval();
```

### Version

1.3.43 - now

**Comment by h-a-n-a** [comment]
I will send a PR to fix this issue.

**Comment by h-a-n-a** [comment]
After I dig into the implementation of the renamer, I found there're two PRs that related to this feature.

https://github.com/swc-project/swc/pull/7116
https://github.com/swc-project/swc/pull/6818

In the second PR, revisit was introduced to make sure that synthesized symbols are get renamed. However, the problem gets a little bit trickier after this:
https://github.com/swc-project/swc/pull/6818/files#diff-26c1c635df737c157e92900996b4e8ede3b3218203a9cf318c80019fc560c140R243
The main idea behind the fix is to avoid the naming conflict between the symbol of the function and the symbol of the variable. However, revisiting will retrigger the scope analyzer and loses the original parent scope information. I would like to give the best solution to this fix. Any thoughts on this? @kdy1

**Comment by h-a-n-a** [comment]
Other thing that looks weird to me is the logic related to `eval`. The eval finder will look directly dig into the AST nodes and test if any `eval` exists and use the `eval` related visit for every nodes no matter which scope that `eval` locates. I don't know how babel handled this, but It looks to me that this wouldn't be better with visiting along with the eval information of each scope?

**Comment by kdy1** [comment]
Hmmm... This sounds quite similar to https://github.com/swc-project/swc/pull/7615.
Honestly, I didn't understand the exact cause of #7615, so it may be different, but I'll check it it's related. #7615 is being published, so let's wait.

About `eval`, it's simply lacking caching feature.

```js
const a = () => {
     const b = 1
     const c = () => {
         const c1 = () => {}
         const c2 = () => eval()
    }

    const d = () => {
        const d1 = () => {}
         const d2 = () => {}
    }
}

```

we need to mark `a`, `c`, `c2` as a scope containing eval

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.70&code=H4sIAAAAAAAAA22MQQqEMBAE73lF31QIfkD2tA%2FwDTGMkmUZYTIJiPh3o%2BJB8Nh0VWUncPhgTOw1zIyaLNSCG6wGqFIkRJXgterKzgVf3nALsZgv6cK%2BD%2BzobUdhuzPP%2FzYBIU3C590PP%2FLauhjDxKdsik7Z%2FeumMzvyUFLzuwAAAA%3D%3D&config=H4sIAAAAAAAAA2VPSw4CIQzdewrStVs33sFDNMhMIBQIxUQymbsLDDBGN03frw%2B2ixBgWMJdbGUtIGBkFScuDGeX8F0YUJKQZdQhwXWohqu0oGXVqP1QIGFcVWopvnU7WO9ZDXvnSDu95O9CQrfaH1uhpacQFfN%2FXRtA%2Fvlqsf6TlENFNUfeGYbp1PwY3llxvuM4vn8Aznx4DBsBAAA%3D

Okay it's fixed
