### ISSUE TITLE
Bug: _interop_require_wildcard helper missing

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#7650]
### Describe the bug

`_interop_require_wildcard` is missing, if has `module` configured to `commonjs`

### Input code

```typescript
const a = require('foo')
console.log(a)
import('other')
```

### Config

```json
{
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
    },
  },
  "isModule": "unknown",
  "module": {
    "type": "commonjs"
  },
}
```

### Playground link

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA0vOzysuUUhUsFUoSi0szSxK1VBPy89X1%2BRKBkrk56Tq5eSnayRqcmXmFuQXlWio55dkpBYBpQEdbRHiOAAAAA%3D%3D&config=H4sIAAAAAAAAAz2NSwqAMAwF956iZO1CXHoHD1FqED9NSxNREe9u6m%2BT5A3Dy1EYAyM7aMyhpwaxqUfRDMh1VVdQPjzaxJh%2BTwnvJHbLpuwR2aUhymufed0DBm5Dt8yYvYUmCivdEvgPf4%2B1JEsueB9oZHgqzgsyPIPvowAAAA%3D%3D

### Expected behavior

`_interop_require_wildcard` presents

### Actual behavior

`_interop_require_wildcard` is missing

### Version

1.3.66

**Comment by kwonoj** [comment]
I'm not really sure this is a bug: you forced input as `cjs` and use esm import syntax?

**Comment by magic-akari** [comment]
> [Dynamic import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) is supported in both CommonJS and ES modules. In CommonJS modules it can be used to load ES modules.

https://nodejs.org/api/esm.html#import-expressions



The key issue is that we should not run any module transformations when compiling from CJS to CJS.
However, swc always considers the input source to be ESM.

Currently, we only have three options for the input source: Module, Script, and Unknown. 
We should try to skip the module transformations based on the input source.
