### ISSUE TITLE
Decorators are not working I am using 1.3.68

### ISSUE THREAD

**Issue by vaghesh-sb** [swc-project/swc#7651]
### Describe the bug

I am using class-validator to validate in my express project with node js 
but it does not work and while  build I am getting this error.
  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key

### Input code

```typescript
export class TestDto {

  @IsInt()
  @IsOptional()
  public nStart: number

  @IsInt()
  @IsOptional()
  public nLimit: number

  @IsBoolean()
  @IsOptional()
  public bActivate: boolean

  @IsString()
  @IsOptional()
  public sSearch: string
}
```

### Config

```json
We are using default config of SWC.
```

### Expected behavior

It should compile.

### Actual behavior

It is giving error as mentioned in my description

### Version

1.3.68

**Comment by kdy1** [comment]
https://swc.rs/docs/configuration/compilation#jscparser
