### ISSUE TITLE
new module transformer on 1.2.206 broke * imports + spyOn combination

### ISSUE THREAD

**Issue by davidmatas** [swc-project/swc#7652]
### Describe the bug

Version 1.2.206 introduce some bug for `import * as` declaration

Prior to that version code like this worked without problems:

### Implementation file

```
export const useGetRequest = () => {}...
```

### Test file
```
import * as hook from '../../useGetRequest/useGetRequest';

jest.spyOn(hook, 'useGetRequest')
```

Now when I executed the test it fails with the following error:

```
    TypeError: Cannot redefine property: useGetRequest
        at Function.defineProperty (<anonymous>)

      15 |   constructor() {
      16 |     this.jestSpy = jest.fn();
    > 17 |     this.jestMock = jest.spyOn(hook, 'useGetRequest')
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": true
    },
    "target": "es2015"
  },
  "sourceMaps": true
}
```

### Expected behavior

I guess it should work like in the previous version. It seems TS and Babel already had this problem. [Stackoverflow thread](https://stackoverflow.com/questions/67872622/jest-spyon-not-working-on-index-file-cannot-redefine-property/69951703#69951703)

### Version

1.2.206 and later

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/7435
