### ISSUE TITLE
Certain types of comments (like: `//!`) are not removed during minification

### ISSUE THREAD

**Issue by emzoumpo** [swc-project/swc#7653]
### Describe the bug

NOTE: This was originally posted as a Next.js bug: https://github.com/vercel/next.js/issues/52600 , but it turns out that it can be isolated to SWC completely (reproduction url below).

Special comments like ones starting with: `//!` (that are still valid comments, like the ones from Better Comments) are not removed during minification.
![253031366-e560e512-34b2-4cc2-874b-1c0a24411ddb](https://github.com/swc-project/swc/assets/2103443/119ebd0b-6ad3-453b-a75d-3d5313bc4a25)

### Playground link

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA2VSTWsbMRC9%2B1e8npyakL2HtlDagwsNgdjQY1BXsysR7YwZae0Y4%2F%2Fe0XrbJI1uGt68L6lZrfDVexxlVCgl2jsuaMUTAimhE0UJhJjzSChimJ2KH1vCqlnQ8060wFPnxlTQjdyWKIy1DHT1EacFDF9GZXzycW%2B3y2ma7f33%2B1t8C9Q%2BIXamELNJIJeYEpjIk4frCl3E3c409y5BuunOdDDTuHPsetJXtB%2BwDdVzSnKI3MPWdqTliCH2oSATDUjxyeKUKuelglhMnvubNzxrOdCe9HpGxqEGrdVEhqivxsToDWOzB3KtpVcZ4GNunXrje0M3ubZSl9m65WJLGcJWYjh6dVNnwVIS1%2FGEblM01M27cC%2Frc22Vds7XBsc94TeVA9GFZkNqMbCJBnogNuP%2FW3PsJ%2BQ%2FJ9fwl6euU6U%2B5jJt%2FW0%2FJzH5EtzcIVdF%2ByevKF5s%2B%2BpIZczpuKHyg5l0vb37%2Bfl0wuNjKEO6xXJN9l74JZr8EufzvNt8WZwXfwBOxzIxnwIAAA%3D%3D&config=H4sIAAAAAAAAA1WNvQ7CMAwG9z5F5JmVhZWFBd7BKi4KOD%2ByXalV1XcnLQmCzd%2BddF465%2BCpPZzcUs4yMoqSfHchOkfDqRCwOZP24rPBoVnTTZmMtJP1I8AEow5JQpFxZG4Y5UG2tUiPNQKcklKNVESTkUTkC3Em0SIHZG32RZTPjKo3DPQn9%2FcQfPTD%2FFMEr9d0H7l96dbuDVk6N%2Fn6AAAA

### Expected behavior

All comments are removed from the code.

### Actual behavior

Only some comments are removed from the code. Others are included, along with newlines into the minified result.

### Version

1.3.66

**Comment by nicksan222** [comment]
Toggling the "compress" makes them go away
