### ISSUE TITLE
Two named exports creates invalid CommonJS

### ISSUE THREAD

**Issue by snyamathi** [swc-project/swc#7665]
### Describe the bug

Two or more named exports will yield a file that cannot be parsed by the CJS lexer and has issues with being imported.

### Input code

```typescript
export const foo = 'foo';
export const bar = 'bar';
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript"
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIy89XsFVQB1Lq1lypyDJJiUUgGSClbg0Aikj%2FLjMAAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYygZyCxKLi1CI4HyhSXJlXklgBFFFKTc5NLE4uyiwoUQJL1gLJWh2QEbn5KaU5qQhTSioLQDyl5Pzc3Py8rGKQ%2BlquWgCZ2NHCbwAAAA%3D%3D

### Expected behavior

Typescript compiler with similar settings will output the following:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bar = exports.foo = void 0;
exports.foo = 'foo';
exports.bar = 'bar';
```

This is analyzable by the node CJS lexer and will work with a destructuring import.

### Actual behavior

We get the following which cannot be statically analyzed and gives errors

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    foo: function() {
        return foo;
    },
    bar: function() {
        return bar;
    }
});
var foo = "foo";
var bar = "bar";
```

```
$ node --input-type=module -e "import { foo } from './index.cjs';"
file:///xxx/[eval1]:1
import { foo } from './index.cjs';
         ^^^
SyntaxError: Named export 'foo' not found. The requested module './index.cjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './index.cjs';
const { foo } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async ESMLoader.eval (node:internal/modules/esm/loader:390:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

### Version

1.3.66

**Comment by kdy1** [comment]
No. This is expected. You should set interop mode to `node` because `cjs-module-lexer`, which is used by node.js to import cjs modules, is not smart enough. https://swc.rs/docs/configuration/modules#importinterop

I added it to https://github.com/swc-project/swc/issues/7435.

**Comment by snyamathi** [comment]
Thank you - I've updated my playground link with the suggested config and that does work 

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIy89XsFVQB1Lq1lypyDJJiUUgGSClbg0Aikj%2FLjMAAAA%3D&config=H4sIAAAAAAAAA22OsQ6DMAxE93wF8sxQMXbryGcgsKpQElu2kUCIf69DS9uhm33ne74tVBWM2sO12nz0BRdGiQmzddNHdf2ByG1iErupolikrO6bzHic7PUrz524%2FZvU1VmLK2Aro%2FYS2aA%2BXdPlH8Y6uaOVEGpzaRoIbw8SDfOE38LxKNVmQyEugUwDwonxj0XrKSXKox6YsIcnn7uXefgAAAA%3D

🙏
