### ISSUE TITLE
Variable named as `NaN` cannot be resolved

### ISSUE THREAD

**Issue by magic-akari** [swc-project/swc#7685]
### Describe the bug

Variable `NaN` is incorrectly renamed.

### Input code

```typescript
{
    let NaN = 1;
    console.log(NaN);
}
```

### Config

```json
{
  "jsc": {
    "minify": {
      "compress": false
    },
    "parser": {
      "syntax": "ecmascript"
    },
    "target": "es2022"
  }
}
```

### Playground link

[playground](https://play.swc.rs/?version=1.3.70&code=H4sIAAAAAAAAA6vmUgCCnNQSBb9EPwVbBUNrsEByfl5xfk6qXk5%2BugZQQtOaqxYAp6nlwyoAAAA%3D&config=H4sIAAAAAAAAA1WLwQqAIBBE736FeO4QHvubRdYw0mTXQyL%2Be5tB1G3mzZumtDYbO7PoJlFKDCn4%2BnYh7oiZkFmYh51x8D49egZipK%2FONRU4hRh0EdhRyMX8PgVoxTIMtrO199pVvwAnblc2jAAAAA%3D%3D)

### Expected behavior

The output should be exactly the same as the input.

### Actual behavior

```JavaScript
{
    let NaN1 = 1;
    console.log(NaN);
}
```

### Version

1.3.70

### Additional context

- #4596
- #7684 

_No response_

**Comment by magic-akari** [comment]
https://github.com/swc-project/swc/blob/549e138443101a5cf837cdd7357e41123d700640/crates/swc_ecma_transforms_base/src/resolver/mod.rs#L272-L275

I don't think this is true.

**Comment by kdy1** [comment]
Ah...

```js
{
    let NaN = 1;
    console.log(NaN);
}
```
prints 1

and

```

{
    var NaN = 1;
    console.log(NaN);
}
```

prints `NaN`, so yeah, the code is wrong.

**Comment by Austaras** [comment]
`NaN` can be shadowed in non strict mode, but cannot be overridden.
