### ISSUE TITLE
Unique key error if `key` prop passed after spreading props to a component with multiple children

### ISSUE THREAD

**Issue by SuttonKyle** [swc-project/swc#7686]
### Describe the bug

A couple specific conditions have to be met for this to be an issue, but from what I can tell, it comes down to:
- Mapping over some array to render elements that have `key` props, when:
- `key` is passed after spreading props, and
- the component taking the `key` props has multiple adjacent children.

This is clearer in the example code, and I'm not sure what's causing it, but when the compiled code is run in a React environment, it throws the key error `Warning: Each child in a list should have a unique "key" prop.`

### Input code

```typescript
const WorkingComponent = () => {
  const options = ["a", "b", "c"];
  const spreadableStyles = { style: { color: "green" } };
  return <div>
  {options.map(o => {
    const caption = `${o}-working`
    const key = `${o}-key`
    return <div className="whatever" key={key} {...spreadableStyles}><div>{caption}</div><div /></div>
  })}
  </div>
}

const BrokenComponent = () => {
  const options = ["1", "2", "3"];
  const spreadableStyles = { style: { color: "red" } };
  return <div>
  {options.map(o => {
    const caption = `${o}-broken`
    const key = `${o}-key`
    return <div className="whatever" {...spreadableStyles} key={key}><div>{caption}</div><div /></div>
  })}
  </div>
}

export default function App() {
  return (
    <div className="App">
      <WorkingComponent />
      <BrokenComponent />
    </div>
  );
}
```

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "env": {
    "mode": "usage",
    "coreJs": "3.30.1"
  },
  "jsc": {
    "externalHelpers": true,
    "loose": true,
    "parser": {
      "decorators": true,
      "dynamicImport": true,
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2017",
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6",
    "ignoreDynamic": true
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.20&code=H4sIAAAAAAAAA62SP0%2FDMBDF93yKk8XQSpAI2NomErCzMDAgpLrOtVRNbMtxWyrL352zk6ZVYODfcrrTO%2Fv9%2FBKhZGPhWZnNWq4eVK2VRGkhh9EY8gJcAiDiitJ2TQ0pL4yzS2CLUAR7nfYrjTbIS76o8MkeKgy7DprQTqgRqlJmAmxlECUDDz6cNGi3RsKsXO8KGl1nk9Zcj9SR4GggeFTp3vmFU%2F5q32LPz1Y2eOhl6lvpzARExZvmkdeYs%2F0bt7hDw8Kp3FHx4NI0Hb7DFxHPdfZ%2BloUx3pYV7UA2fuypdqNPkpbn3qgNyu8Gex0yvQnl9ufBGiz%2FJ9ZFZP57ql9mecr6V6niu1bGQolLvq0sLLdSRPY7rSlYd3r6KDIO4WiNFVEh7dNfn%2FXS8LN1So81nhLMB9Sxt3w8AwAA&config=H4sIAAAAAAAAA12QzWrDMBCE734KI3osTtJACzn3kBb6EIuydRysH3ZXrU3wu3flnzjpRUgz%2BrSjuRZlaZ7YntGBOZTmLBIPm82Fg68mlSUQVoHqDf9asuY5E%2Bh%2F9PZVt3pw4YSZTQw1jr6KVqlPzvK%2B2m%2BrnVF5GNkL25XFTpA8tEdsI1K%2BL5RwfqMNgfFRikCMdONVOaGOAg35CGen9%2BAa%2B%2BFiIPlvcu8FupxP%2BohsqYlibq5wNwOjMszTBajG%2FJRBftnu3pbPCoHn70DuPhghWLkTspS8NG4sC5IEB9JYM9tDsaxTTdpqanFtKsecJr8uY5vaa8vv0zfXvBPPIZHFL4hLL8VQFH%2BR18dV7wEAAA%3D%3D

### Expected behavior

The compiled code should not have a key error regardless of whether the key is passed before or after spreading props.

### Actual behavior

The compiled code leads to a console error stating `Warning: Each child in a list should have a unique "key" prop.`

### Version

1.3.66

**Comment by kdy1** [comment]
This behavior was intentional.

https://github.com/swc-project/swc/blob/aff07b1a0a61bfc60422a2d308c99e1f02ee1237/crates/swc_ecma_transforms_react/src/jsx/static_check.rs#L4-L8


Does babel support this?
