### ISSUE TITLE
Folder for stable Rust

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#769]
**Describe the feature**
With amazing work done in https://github.com/swc-project/swc/pull/743 it's now possible to use `Visitor` in stable Rust - I use it extensively in both `deno` and `deno_lint` and it works like a charm! It would unlock a lot more possibilities if `Folder` could be made to work on stable Rust as well. @kdy1 I'm not that familiar with SWC code, but with some guidance I think I could try to get it working. Let me know what you think.

CC @dsherret

**Comment by kdy1** [comment]
I'll write one at the weekend.

**Comment by kdy1** [comment]
I implemented it and published swc_ecma_visit@0.2.0

**Comment by kdy1** [comment]
cc @ry

**Comment by bartlomieju** [comment]
@kdy1 thank you! I will try it out this weekend

**Comment by dsherret** [comment]
Thanks a lot @kdy1!

@bartlomieju FYI, I am updating deno doc to use the latest swc right now.
