### ISSUE TITLE
ESM typescript compilation exports types as values

### ISSUE THREAD

**Issue by 3axap4eHko** [swc-project/swc#7693]
### Describe the bug

When exporting types from other modules, the ESM compilation treats them as values and exports them, but the final js failures at the runtime. Steps to reproduce:
1. Create an npm package and set its type as a module
```bash
mkdir test
cd test
npm init -y
npm pkg set type='module'
```
2. Create `src/Test.ts`
```typescript
export interface Test {}
```
3. Create `src/index.ts`
```typescript
export { Test } from "./test.js";
```
4. Compile it
```bash
npx swc ./src -d ./build
``` 
6. Run the build
```bash
node ./build/index.js
```
Got the error
```
SyntaxError: The requested module './test.js' does not provide an export named 'Test'
```

### Config

```json
{
  "module": {
    "type": "es6"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2022"
  }
}
```

### Expected behavior

Types must be omitted in js when compiled in ESM

### Version

1.3.70

**Comment by kwonoj** [comment]
Dupe https://github.com/swc-project/swc/issues/7555

**Comment by 3axap4eHko** [comment]
@kwonoj could you please point out where I can find a solution?
