### ISSUE TITLE
`core-js` import is not added for `Promise.allSettled`

### ISSUE THREAD

**Issue by zuisong** [swc-project/swc#7712]
### Describe the bug

Promise.allSettled is not resolved by swc 

And babel can resolve it

[swc playground link](https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA0WOywrCMBBF94X%2Bw10mUKRu6%2BMbBN2Ji9iOEEgmJZlYRfrvtmjpagbOvWeGXn2IgkfmVmxgJEfUK58acPZ3irrBKQZvE%2B2fwXZHfMoCiCQ5MpiGhSoVKWkc%2FgEgkVysp5BlJhV80ruZjPMYy6IsTHpzu172xrLSU9sMxsri3RjnziTiqIO6%2Fr7b1rWusO43PRm%2FCH36sMkAAAA%3D&config=H4sIAAAAAAAAA1VPOw6DMAzdOUXkuUOXMnToDXqINDU0FfnIDhUIcXcSSChs9vv4%2BU2VEPBlBXcxxTEuXhIj7XtEeLRBDhGBMHpkRdoHuBQ2cKIa2TGu0LwxECS1GJIL%2BZbl0DnHWOQZM9rqZjwGKmc8IfNZmKTSth2e46ocCca9%2B5XMRdKzW3wNf1EJ2w%2BD5mdxBuo3DO3vcGhtkr4B9SFnUDxEfS2VXn3b6AE521NSNS85P6oZVwEAAA%3D%3D)

[babel playground link](
https://babeljs.io/repl#?browsers=chrome%20%3E%3D%2060&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAMwK4DsDGMCWEVwM4A2wwYAFALZ4BccKS5ARsFAJQ0AKUE5mewAPADcImACYA-OAG8AUHDhRgMJFFwpgAdziduvYKVKK8LOAF5Js-fL4wAKpnLAISGIeB4ANHEosA3HLgAXz8ZQJkZAEM8AE90RFQMbFxyCMwUUhZZCI1U-B0ePgA6CIICAGUlGCJROFIAbUJiMgBGAAZWli9GklI2joBdFlCgA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ctypescript&prettier=true&targets=Electron-22&version=7.22.9&externalPlugins=&assumptions=%7B%7D)

### Input code

```typescript
export function sleep(ms: number): Promise<void> {
  return new Promise((res) => {
    setTimeout(res, ms);
  });
}

async function main(){
await Promise.allSettled ([sleep(100), sleep(100)])
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "chrome > 60",
    "bugfixes": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA0WOywrCMBBF94X%2Bw10mUKRu6%2BMbBN2Ji9iOEEgmJZlYRfrvtmjpagbOvWeGXn2IgkfmVmxgJEfUK58acPZ3irrBKQZvE%2B2fwXZHfMoCiCQ5MpiGhSoVKWkc%2FgEgkVysp5BlJhV80ruZjPMYy6IsTHpzu172xrLSU9sMxsri3RjnziTiqIO6%2Fr7b1rWusO43PRm%2FCH36sMkAAAA%3D&config=H4sIAAAAAAAAA1VPOw6DMAzdOUXkuUOXMnToDXqINDU0FfnIDhUIcXcSSChs9vv4%2BU2VEPBlBXcxxTEuXhIj7XtEeLRBDhGBMHpkRdoHuBQ2cKIa2TGu0LwxECS1GJIL%2BZbl0DnHWOQZM9rqZjwGKmc8IfNZmKTSth2e46ocCca9%2B5XMRdKzW3wNf1EJ2w%2BD5mdxBuo3DO3vcGhtkr4B9SFnUDxEfS2VXn3b6AE521NSNS85P6oZVwEAAA%3D%3D

### Expected behavior

`Promise.allSettled` should be polyfill

### Version

1.3.71

**Comment by kdy1** [comment]
I can't repro

https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA0WOywqDMBBF94L%2FMDsTELFb%2B%2FiGQrsrXaQ6lkAyI5mkUor%2FXkRtV3fgzH1An6iNlgnEIQ7KSwOU%2FAODbuAc2FvBw4ttd4JPngEEjCkQEI4bVSqgaDiuDwCC8Wo9coozKcGL3s9kmmXKszwz8qYWfs3eWFJ6dZvR2LhlV8a5C8bosAN1Wxbu6lqX8L%2FvejG2TMIOK8dPVfTMhV7blvgvtvTj1ukAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D

**Comment by kdy1** [comment]
I tried it using the chrome developer tool

**Comment by kdy1** [comment]
Ah do you mean we need a polyfill?

**Comment by zuisong** [comment]
> Ah do you mean we need a polyfill?

Yes, it need a polyfill when env target is `chrome>=60`

<img width="1461" alt="image" src="https://github.com/swc-project/swc/assets/19145952/7cdfd46c-b6c0-4abe-ad38-bc5286c0a0aa">
