### ISSUE TITLE
Class method decorators not working 

### ISSUE THREAD

**Issue by shudv** [swc-project/swc#7730]
### Describe the bug

I have a decorator that simply catches and exception and logs it. I can't get it to work with @swc/jest and the decorator is always ignored. 

Here is the [playground link](https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA41T0Y7aMBB8R%2BIfVtE9JIgGtY%2BgiqtOtLqqhep6VR9OqJhkSXw1NnWcchTl37u2Ey6EU1VLSDbZmZ0Zr%2FFpp7QBLg3qDUsQbmdaK%2F1JZYud4UoWcOz3gNZoMPAbGMA3yX%2BVCIZlYBTwFKXhmwOYHAEtGoTKmuKR31DtdAyF0Vxmk37vkhPutW0v8DcKUJt%2FkrmiNl1lGT3bAD6jyVUKKSZKM0MEpDFhJsmBydSyed7CFjvA9Y5ptgVVG26MW1hZGLXlf%2FBCDqE0mlJT3bv%2Fa0Xa0Ye9KWViW%2FhSl3dYNx9f5B%2BNievQ3ILv2WJoBKY3LS7NMy6Z8EE4fNQQuNhHMPNWXNjrAxnYsFIYKz%2FnWS7oZ6CUObkQmJLOAotnfEKyTA1%2B28QW%2B%2FN0CitHvpp0AXZcnsvtyRZ%2FmM1nd7c3q9NQ2HXyVyeLqfcSmpwXztAQ4jhmOvOnh%2BV5TM0SaCiygqy5z5Pzr0ZfAHzGFmClnuUYJ0wIJ%2BDUO%2BoQVvXlh%2B7Wo5fImUBtwsBFFHTxTVZKYEzDE64ero4u1mpJO0qsWsIruDp%2B%2FLqYx3746d35bkNYrB8xMXGGZrGXX7TaUafDnG2xqPVE1SrqCD4%2F1tPlA2hpq9p3Uxd1bqaurprH2O8lghUF3CPdfJ3DdWvej3YcxhCwR%2Fb0w8kLhn6k6M%2FvTEvyFkBV692Va8ETMERWD0LUvP52yCbXat9N3ZG%2FHoPEvR%2F7MHjPfqJ1uaOsMYiGLwDeXAK8ynZ11bg%2BmQ4tyHoOoyhuy538BRMlkUxpBQAA&config=H4sIAAAAAAAAA2WPSw6DMAxE95wCed1Fy5I79BBRMCiIxJFtpCLE3ZvwSVt1F8%2BLZzxrVdcwioW2XtMzDdGwIJc5KbIENa%2BkgC4RxbKLCreLqmTUm0mwaB1aYqPEkpDyjDvYDg5qeEDNfijNvXmcXjARCf56gXfB9cv3NZZ8ZBT5C%2FUmDFPZPxKrMxU8dfMOz5a5Sb4guXkKo8Dn55VY3MHJ81rfy2xvI0NDaTYBAAA%3D). 

If you try to execute the compiled JS above, the exception is thrown nonetheless. Ideally the decorator should suppress it.

I have tried various permutations and combinations for .swcrc file but can't get it working. Can someone help? Thanks!

### Config

```json
{
    "jsc": {
      "target": "es2021",
      "parser": { "syntax": "typescript","decorators": true }
    }
}
```

### Playground link

https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA41T0Y7aMBB8R%2BIfVtE9JIgGtY%2BgiqtOtLqqhep6VR9OqJhkSXw1NnWcchTl37u2Ey6EU1VLSDbZmZ0Zr%2FFpp7QBLg3qDUsQbmdaK%2F1JZYud4UoWcOz3gNZoMPAbGMA3yX%2BVCIZlYBTwFKXhmwOYHAEtGoTKmuKR31DtdAyF0Vxmk37vkhPutW0v8DcKUJt%2FkrmiNl1lGT3bAD6jyVUKKSZKM0MEpDFhJsmBydSyed7CFjvA9Y5ptgVVG26MW1hZGLXlf%2FBCDqE0mlJT3bv%2Fa0Xa0Ye9KWViW%2FhSl3dYNx9f5B%2BNievQ3ILv2WJoBKY3LS7NMy6Z8EE4fNQQuNhHMPNWXNjrAxnYsFIYKz%2FnWS7oZ6CUObkQmJLOAotnfEKyTA1%2B28QW%2B%2FN0CitHvpp0AXZcnsvtyRZ%2FmM1nd7c3q9NQ2HXyVyeLqfcSmpwXztAQ4jhmOvOnh%2BV5TM0SaCiygqy5z5Pzr0ZfAHzGFmClnuUYJ0wIJ%2BDUO%2BoQVvXlh%2B7Wo5fImUBtwsBFFHTxTVZKYEzDE64ero4u1mpJO0qsWsIruDp%2B%2FLqYx3746d35bkNYrB8xMXGGZrGXX7TaUafDnG2xqPVE1SrqCD4%2F1tPlA2hpq9p3Uxd1bqaurprH2O8lghUF3CPdfJ3DdWvej3YcxhCwR%2Fb0w8kLhn6k6M%2FvTEvyFkBV692Va8ETMERWD0LUvP52yCbXat9N3ZG%2FHoPEvR%2F7MHjPfqJ1uaOsMYiGLwDeXAK8ynZ11bg%2BmQ4tyHoOoyhuy538BRMlkUxpBQAA&config=H4sIAAAAAAAAA2WPSw6DMAxE95wCed1Fy5I79BBRMCiIxJFtpCLE3ZvwSVt1F8%2BLZzxrVdcwioW2XtMzDdGwIJc5KbIENa%2BkgC4RxbKLCreLqmTUm0mwaB1aYqPEkpDyjDvYDg5qeEDNfijNvXmcXjARCf56gXfB9cv3NZZ8ZBT5C%2FUmDFPZPxKrMxU8dfMOz5a5Sb4guXkKo8Dn55VY3MHJ81rfy2xvI0NDaTYBAAA%3D

### Expected behavior

The decorator should work!

### Actual behavior

It just does not!

### Version

1.3.68

**Comment by shudv** [comment]
Here is a [minimal repro](https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA22SQWrDMBBF9wbfYTBZWJDqAAmFQumipY0L7S6ERlEmtooiGWlMmgbfvbZlByepdkLzn%2F78GfwprSNQhtDthER4fnLOulebZyUpazyc4giaQyKfgSenTD6PozqO4giDdlcZ2ZaCFCSLTp7aIJ7d4NgMhDkOUIdUOTMiVJ7sXv3i9nHEcipXRug3pMJuOz1rAQHRnrN%2Bi9I6QbgNtSkVyneCKXDOhcvDbbm6tDEcjdRY8pWm7nl%2B%2BUruRhB6aAVwD5c%2BuRRadwbOf7MrYB0SgxTbPtl%2FcNlEZjVybfN0vZyc%2Blx5M416BXcwOb18ZAse5qJ2x4CaQrb5Rkk8R8oO5t3ZEh0dF2KPvv%2BM1Wt25eby2o8mdDcyXo%2BD74uuYu%2Br62FP4khq4T18oqehyYfRspzCciVe7EuNX53BBOreX1lttJJAjbifKhsWcZwYFc4ewOABAjRpBckQeX22krYlrZOUMT6Gzv8A3%2F2iLgsDAAA%3D&config=H4sIAAAAAAAAA2WPSw6DMAxE95wCed1Fy5I79BBRMCiIxJFtpCLE3ZvwSVt1F8%2BLZzxrVdcwioW2XtMzDdGwIJc5KbIENa%2BkgC4RxbKLCreLqmTUm0mwaB1aYqPEkpDyjDvYDg5qeEDNfijNvXmcXjARCf56gXfB9cv3NZZ8ZBT5C%2FUmDFPZPxKrMxU8dfMOz5a5Sb4guXkKo8Dn55VY3MHJ81rfy2xvI0NDaTYBAAA%3D).

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA21SQWrDMBC8G%2FyHxeRgQaoHJBQKpYeWNi60txAaVdnYKopkpDUhNf57bcsOTtK9SZoZzc4uKEPo9kIiPD85Z92rzbOSlDUe6jiCtkjkC%2FDklMmXcdTEUXu9r4zsQCAFyaInpjbQFjdCbAHCnEY5h1Q5M1GoPNmD%2BsXd40TLqVwZod%2BQCrvr%2BawTCBJdnfk7lNYJwl3AplQo3xPmwDkXLg%2Bn9ebSxlgaqbXkK0398%2FLyldwNIfTQEeAeLn1yKbTuDZz%2FZleCTUgMUuz6ZP%2BJyzYyq5Frm6fb9awecuXtHJoN3MGsfvnIVjxMRO1PQWoO2fcPSuI5UnY0786W6Oi0Egf0w2es2bIrN5fHYTShu4nxZhr8ALqKfUA344bEkdTCe%2FhET2OTD5NlqcNaJV4cSo1fvcEEmsFfWX1rJYFa8jBVNq7gNDEqnD2CwSME0aQjJGPkzdlK2kE6JyljfCq6%2FAONdbx8%2FwIAAA%3D%3D&config=H4sIAAAAAAAAA2WQSwrDMAxE9zlF0LqFNIUueoduuzeOElziD5ICDSF3r52P09KdpfGMHjMVZQkv1nAvp%2FiMQ1DESHmOGx6dqHfcgIwBWZMJAqddFU5Sq3rGvGtQe1LiiaMkNOAizKsOoqhDSXnIdVVftizovWf8zQJrnGnHbxrtbSBk%2Fjtqlev67P%2B9SMpx68keQQfjE4mNd4kn0tTn6gqrudgCwPpmWJK3ilINK%2F4Njk87aaYCw4%2FduZQwfwBTAqpubgEAAA%3D%3D

It works.
