### ISSUE TITLE
Loose transpilation of spreads to ES5 is incorrect

### ISSUE THREAD

**Issue by isker** [swc-project/swc#7736]
### Describe the bug

Loose transpilation of spreads generates an `[].concat(...)` that is incorrect under some circumstances.

### Input code

```typescript
const sequence = [
    ...[['foo', 123 ]],
    ['bar', 456],
];
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.73&code=H4sIAAAAAAAAA0vOzysuUShOLSxNzUtOVbBViOZSAAI9Pb3oaPW0%2FHx1HQVDI2OF2FgdsHi0elJiEVDMxNQMKBJrDQBDgoERPwAAAA%3D%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxGd06BPHdth94hh7CoExHxJ0ykoih3LyFA2w2%2Fz%2FYzu5ASVlbwlHt5liJgZIqjLoSzS%2FguBEhZZBV1SHDr6cpnNKNhqui4EkgYF0p1iu%2BtHYz3TIWluFFDVjs951%2Bf8jZEYu5rh8qiWwz920QzgvWvrYbtHykHuuwP%2BDZ12VgMmqc%2BeV4ljg%2F3WmjeEwEAAA%3D%3D

### Expected behavior

```js
> sequence
[ [ 'foo', 123 ], [ 'bar', 456 ] ]
```

### Actual behavior

```js
> sequence
[ [ 'foo', 123 ], 'bar', 456 ]
```

### Version

1.3.73

### Additional context

This is due to Array.prototype.concat behaving differently for Array or Array-like arguments than for all other arguments.  See the documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#description.

The fix would then seem to be to wrap all such arguments to `concat` in an extra Array.

**Comment by KthulupwnsAsura** [comment]
const sequence = [
    [['foo', 123 ]];
    ['bar', 456],
