### ISSUE TITLE
Error in compile class

### ISSUE THREAD

**Issue by pasalino** [swc-project/swc#7751]
### Describe the bug

I try to compile and execute tests with swc but I receive this error:
```
Unexpected token `_logger`. Expected * for generator, private key, identifier or async
        ╭─[/src/controllers/base-worker.controller.ts:14:1]
     14 │ 
     15 │ @Injectable()
     16 │ export class BaseWorkerConsumer {
     17 │     private _logger: Logger
        ·             ───────
     18 │ 
     19 │     constructor(
     20 │         @Inject(RABBIT_MQ_PUBLISHER_SERVICE)
        ╰────
```

```

```

### Input code

```typescript
@Injectable()
export class BaseWorkerConsumer {
    private _logger: Logger

    constructor(
        @Inject(RABBIT_MQ_PUBLISHER_SERVICE)
        private readonly rabbitMqPublisherService: RabbitMqPublisherService
    ) {
        this._logger = new Logger(this.constructor.name)
    }
}
```

### Config

```json
{
    "$schema": "http://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": false,
            "dynamicImport": false,
            "privateMethod": true,
            "functionBind": false,
            "exportDefaultFrom": false,
            "exportNamespaceFrom": false,
            "decorators": true,
            "decoratorsBeforeExport": true,
            "topLevelAwait": true,
            "importMeta": true,
            "classPrivateProperty": true,
            "classProperty": true
        },
        "target": "es2022",
        "loose": true,
        "externalHelpers": true,
        // Requires v1.2.50 or upper and requires target to be es2016 or upper.
        "keepClassNames": true
    },

    "minify": false
}
```

### Expected behavior

Compile and execute

### Version

 versions:  "@swc/core": "^1.3.74", "@swc/jest": "^0.2.27",

**Comment by kwonoj** [comment]
https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA41T0Y7aMBB8R%2BIfVtE9JIgGtY%2BgiqtOtLqqhep6VR9OqJhkSXw1NnWcchTl37u2Ey6EU1VLSDbZmZ0Zr%2FFpp7QBLg3qDUsQbmdaK%2F1JZYud4UoWcOz3gNZoMPAbGMA3yX%2BVCIZlYBTwFKXhmwOYHAEtGoTKmuKR31DtdAyF0Vxmk37vkhPutW0v8DcKUJt%2FkrmiNl1lGT3bAD6jyVUKKSZKM0MEpDFhJsmBydSyed7CFjvA9Y5ptgVVG26MW1hZGLXlf%2FBCDqE0mlJT3bv%2Fa0Xa0Ye9KWViW%2FhSl3dYNx9f5B%2BNievQ3ILv2WJoBKY3LS7NMy6Z8EE4fNQQuNhHMPNWXNjrAxnYsFIYKz%2FnWS7oZ6CUObkQmJLOAotnfEKyTA1%2B28QW%2B%2FN0CitHvpp0AXZcnsvtyRZ%2FmM1nd7c3q9NQ2HXyVyeLqfcSmpwXztAQ4jhmOvOnh%2BV5TM0SaCiygqy5z5Pzr0ZfAHzGFmClnuUYJ0wIJ%2BDUO%2BoQVvXlh%2B7Wo5fImUBtwsBFFHTxTVZKYEzDE64ero4u1mpJO0qsWsIruDp%2B%2FLqYx3746d35bkNYrB8xMXGGZrGXX7TaUafDnG2xqPVE1SrqCD4%2F1tPlA2hpq9p3Uxd1bqaurprH2O8lghUF3CPdfJ3DdWvej3YcxhCwR%2Fb0w8kLhn6k6M%2FvTEvyFkBV692Va8ETMERWD0LUvP52yCbXat9N3ZG%2FHoPEvR%2F7MHjPfqJ1uaOsMYiGLwDeXAK8ynZ11bg%2BmQ4tyHoOoyhuy538BRMlkUxpBQAA&config=H4sIAAAAAAAAA2WPSw6DMAxE95wCed1Fy5I79BBRMCiIxJFtpCLE3ZvwSVt1F8%2BLZzxrVdcwioW2XtMzDdGwIJc5KbIENa%2BkgC4RxbKLCreLqmTUm0mwaB1aYqPEkpDyjDvYDg5qeEDNfijNvXmcXjARCf56gXfB9cv3NZZ8ZBT5C%2FUmDFPZPxKrMxU8dfMOz5a5Sb4guXkKo8Dn55VY3MHJ81rfy2xvI0NDaTYBAAA%3D
