### ISSUE TITLE
Add ability to disable `lexical` dep

### ISSUE THREAD

**Issue by Manishearth** [swc-project/swc#7752]
`swc` uses the `lexical` family of crates for parsing numbers. It's a fast crate, but unfortunately it has a number of soundness issues, and so far there has been no movement from upstream on this (or accepting any of the patches opened so far):

 - https://github.com/Alexhuszagh/rust-lexical/issues/95
 - https://github.com/Alexhuszagh/rust-lexical/issues/101
 - https://github.com/Alexhuszagh/rust-lexical/issues/102
 - https://github.com/Alexhuszagh/rust-lexical/issues/104

It would be nice for users of `swc` to be able to choose whether `lexical` is used. I would recommend making `lexical` an optional dependency, enabled by default, so that people can use `swc` with `no-default-features` if they wish to avoid the dep. The `num` family of crates is well established and has alternate code that does the same stuff as `lexical`, though perhaps not as optimized.

We have a patch we can submit to support this.

**Comment by kdy1** [comment]
It's fine to switch to `num` completely, but I don't want it to be optional dep. It's too much for the maintainers

**Comment by Manishearth** [comment]
It's a relatively small patch. How about we provide both options (remove the dep completely vs make it optional) and you can choose?

**Comment by kdy1** [comment]
Who? Removing dep completely is fine, but I'm not sure what you are saying

**Comment by Manishearth** [comment]
Oh, I was saying that the patch to make it optional is not much more complicated and you can choose which PR to land.: whether to land the one making it optional or the one removing it completely. But if you strongly prefer removing the dep we can just do that.
