### ISSUE TITLE
unknown field `eval`, expected one of `properties`, ...

### ISSUE THREAD

**Issue by danieltroger** [swc-project/swc#7754]
### Describe the bug

Same kind of issue as #7738 but for a different `.terserrc`

### Input code

.terserrc

```json
{
  "mangle": {
    "eval": true,
    "properties": {
      "regex": "^(?!__core-js_shared__).*_$"
    }
  },
  "compress": {
    "unsafe": true,
    "arguments": true,
    "ecma": "2020",
    "passes": 4,
    "unsafe_arrows": true
  },
  "format": {
    "ecma": 2020
  }
}
```

### Expected behavior

No error and similar compression behavior as terser

### Actual behavior

[parcel.zip](https://github.com/swc-project/swc/files/12262228/parcel.zip)

```
daniel@mmmmmmmmmm parcel % yarn build
🚨 Build failed.

@parcel/optimizer-swc: unknown field `eval`, expected one of `properties`, `props`, `toplevel`, `topLevel`, `keep_classnames`, `keepClassNames`, `keep_fnames`, `keepFnNames`, `keep_private_props`, `keepPrivateProps`, `ie8`, 
`safari10`, `reserved` at line 1 column 324

  Error: unknown field `eval`, expected one of `properties`, `props`, `toplevel`, `topLevel`, `keep_classnames`, `keepClassNames`, `keep_fnames`, `keepFnNames`, `keep_private_props`, `keepPrivateProps`, `ie8`, `safari10`, 
  `reserved` at line 1 column 324

daniel@mmmmmmmmmm parcel % 
```

### Version

`@parcel/optimizer-swc@2.9.4`

**Comment by danieltroger** [comment]
Tysm!

@mischnic can/do you need to bump SWC?

**Comment by mischnic** [comment]
No, the next `@swc/core` patch version is compatible with what Parcel is requiring. So you'll just need to bump your lockfile.

**Comment by danieltroger** [comment]
@kdy1 sorry for hijacking this issue but the terserrc shown above now fails with the following

```
🚨 Build failed.

@parcel/optimizer-swc: failed to parse `^(?!__core-js_shared__).*_$` as regex at line 1 column 325

  Error: failed to parse `^(?!__core-js_shared__).*_$` as regex at line 1 column 325

```

Do you know what I'm doing wrong?

**Comment by kdy1** [comment]
Error message says `^(?!__core-js_shared__).*_$` is not a valid regex

**Comment by kdy1** [comment]
https://rustexp.lpil.uk/

**Comment by danieltroger** [comment]
But it's valid for terser, why is it not valid for SWC?

**Comment by danieltroger** [comment]
It seems like it's a limitation by SWC/rust and there's no good workaround :( https://chat.openai.com/share/92673420-52ba-45b0-8c0f-dcdfb5b2ad50

I'll keep using terser then. Thank you for your efforts nevertheless.

**Comment by kdy1** [comment]
I don't think it's a limitation, and your regex can be easily adjusted. The reason is that swc is written in Rust and you don't have a js-compatible regex engine which is both fast and small.

**Comment by danieltroger** [comment]
Makes sense. I don't know regex though and chatGPT failed to give me an adjusted regex. Do you know how I could get an adjusted rust-compatible regex? It should only mangle property names ending on `_` and not starting with `__core-js_shared__`.

I tried again https://chat.openai.com/share/806c629d-1a6b-479f-bec1-114a801e7457 and the regex it gave me is failing in your tester, just like the original one.

**Comment by kdy1** [comment]
@danieltroger While trying to fix it I found that it works if `regex/fancy-regex` is enabled. I'll fix it soon.

**Comment by kdy1** [comment]
Ah... it was not `regex/fancy-regex` but it was a separate crate

**Comment by danieltroger** [comment]
@kdy1 any updates on the regex situation?

**Comment by kdy1** [comment]
No, and I'm not going to use `fancy-regex` for swc

**Comment by danieltroger** [comment]
Ok, so there's currently no way to mangle only properties ending on underscore and not starting with `__core-js_shared__`? 😔
