### ISSUE TITLE
swc/jest cant use `env` with `jsc.target`

### ISSUE THREAD

**Issue by jleider** [swc-project/swc#7759]
### Describe the bug

I think due to changes here: https://github.com/swc-project/swc/issues/6956 that state you can't set both `env` and `jsc.target` causes issues with `swc/jest`. I have an `env` specified in my `.swcrc` for bundling code for the web. However, when running jest it complains that `env` and `jsc.target` can not be used together. I have tried passing an empty object for `env` and setting `env` to `null` on the custom swc config passed to `swc/jest` as well as manually reading the `.swcrc` file and deleting the `env` property, however I still get an error saying they can not be used together. 

### Input code

```typescript
const fs = require("fs");

const swcConfig = JSON.parse(fs.readFileSync(".swcrc", "utf-8"));
delete swcConfig.env;


module.exports = {
  cacheDirectory: "./node_modules/.cache/jest",
  clearMocks: true,
  setupFilesAfterEnv: [
    "jest-extended/all",
    "./jest.setup.js",
  ],
  testEnvironment: "jest-environment-jsdom",
  testRegex: ".*\\.(test|spec)\\.(j|t)sx?$",
  transform: {
    "^.+\\.tsx?$": ["ts-jest", {
      tsconfig: "./tests/tsconfig.json",
      babelConfig: "./babel.config.json",
    }],
    "^.+\\.js$": ["@swc/jest", swcConfig],
    "^.+\\.svg$": "<rootDir>/tests/react/svgJest",
    "^.+node_modules/(d3-array|internmap|htmldiff|escape-string-regexp|preact).+\\.jsx?$": "jest-esm-transformer",
  },
  verbose: true,
};
```

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "env": {
    "mode": "usage",
    "coreJs": "3.32.0"
  },
  "jsc": {
    "externalHelpers": true,
    "loose": true,
    "parser": {
      "decorators": true,
      "dynamicImport": true,
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6",
    "ignoreDynamic": true
  },
  "sourceMaps": true
}
```

### Expected behavior

I would expect to be able to overwrite the `env` data by passing a custom swc config object to `swc/jest`.

Also, the error message itself is fairly cryptic because `swc/jest` seems to automatically apply a `jsc.target` implicitly. Its non-obvious as to why this even fails at first. 

### Actual behavior

Receive an error from jest: 

```
`env` and `jsc.target` cannot be used together
```

### Version

>1.3.72

**Comment by kdy1** [comment]
@inomdzhon Look at your `.swcrc`

**Comment by inomdzhon** [comment]
> @inomdzhon Look at your `.swcrc`

Ohhh I got it https://github.com/swc-project/swc/pull/7704

Thanks 🙏
