### ISSUE TITLE
Minification API Bug: first part of the string surrounding template strings variables copied after every other variable inside template string

### ISSUE THREAD

**Issue by janlent1** [swc-project/swc#7769]
### Describe the bug

The minification is broken if minifying a complex template string with multiple variables and functions. 

### Input code

```typescript
Here is a repo https://github.com/janlent1/reproMinifierIssueSwc
npm install 
npm run build
brokencodesmallSmallestRepro.js will be minified to outputMinifiedCodeBroken.js

Both are pushed, so yeah you will see that the 
.ThisshouldOnlyBeonTop {
        ${absolute()}
        asda-asdasda: asdad-asdsa;
    }

is copied without the ${absolute()} after every variable into the output string.
```

### Config

```json
I added it to the minifierCaller.js inline: {"compress":{"ecma":2015},"module":false,"ecma":2015,"mangle":true, "sourceMap": undefined}
```

### Playground link

https://github.com/janlent1/reproMinifierIssueSwc

### Expected behavior

It should transpile to the same string as before minification.

### Actual behavior

It adds the first few lines after every variable in the template string. 

### Version

@swc/core@ 1.3.44, 1.3.73,1.3.74

**Comment by kdy1** [comment]
I created #7770 because this issue is pretty hard to read. Please follow the guideline if you want to open an issue

**Comment by janlent1** [comment]
@kdy1 sorry will do next time and thank you for looking into this!
