### ISSUE TITLE
Support decorator on method

### ISSUE THREAD

**Issue by rvhelden** [swc-project/swc#778]
When using a decorator on a method, give the following error.

error: Unexpected token Some(At)

Here is the following AST

https://ts-ast-viewer.com/#code/MYGwhgzhAECyCeBhcVoG8BQ1vQAJmABcBLAewDsscBbeWAU0IAtSATACloAUwAnMao3q8AXNAiFexcgHMAlOgC+GZRnoAPAA6lehaK3qg+9aADMAruSJly0AiQrtCfGYzEB5AEYArQ4QA00ILMbAByAvRiElKygZq8pJrChPAAIvQQwMSahDpiXAlJumkZwFI5OnL5hcklmeW5vADcQA

Here is the documentation describing the feature: https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by kdy1** [comment]
Did you enable decorators?

See: https://swc-project.github.io/docs/configuring-swc.html#jscparser

**Comment by rvhelden** [comment]
I didn't, and it works correctly now, thank you
