### ISSUE TITLE
Cannot find module with certain package.json exports config

### ISSUE THREAD

**Issue by trsdln** [swc-project/swc#7781]
### Describe the bug

While trying to import `formdata-node` I'm getting `Cannot find module 'formdata-node' from...`.

### Input code

```typescript
import { FormData } from 'formdata-node';

console.log(FormData);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
    },
  },
}
```

### Expected behavior

Should import module without errors

### Actual behavior

Throws error `Cannot find module 'formdata-node' from...`.

### Version

1.3.73

### Additional context

I assume that root cause is unsupported `exports` configuration variant at `formdata-node`'s `package.json`:

```json
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "node": {
        "types": "./@type/index.d.ts",
        "import": "./lib/index.js"
      },
      "browser": {
        "types": "./@type/browser.d.ts",
        "import": "./lib/browser.js"
      },
      "default": {
        "types": "./@type/index.d.ts",
        "import": "./lib/index.js"
      }
    },
    "./file-from-path": {
      "types": "./@type/fileFromPath.d.ts",
      "import": "./lib/fileFromPath.js"
    }
  },
```

Removing it resolves this issue.

**Comment by kdy1** [comment]
This has nothing to do with SWC

**Comment by trsdln** [comment]
@kdy1 Excuse me for asking potentially stupid question, but if I'm using `jest + @swc/jest + @swc/core` where this issue should be reported? Or is this user error?
