### ISSUE TITLE
 Error: failed to handle: base_dir(./src) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.

### ISSUE THREAD

**Issue by ian-at-memo** [swc-project/swc#7795]
### Describe the bug

Hello, I have a standard Typescript repo with a set of react components, and I am using rollup to compile them. This wasn't happening yesterday, but when I tried to do a build today upon install, I get the below error. I've looked through the src/index.ts file but there isn't a place where "./src" is called directly. Any ideas? And why is it only happening today?
```
src/index.ts → dist/index.js, dist/index.es.js...
thread '<unnamed>' panicked at 'base_dir(./src) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs:104:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[!] (plugin swc) Error: failed to handle: base_dir(./src) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
src/index.ts
Error: failed to handle: base_dir(./src) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
```

### Expected behavior

I expected it to build as normal, which it was before installation

### Version

^1.3.61

**Comment by ian-at-memo** [comment]
I assume it was related to this merge request because it was merged yesterday and has to do with the baseUrl property?

https://github.com/swc-project/swc/pull/7775/files

**Comment by ian-at-memo** [comment]
I did add that, I tried both of the below and it didn't do anything. Unfortunately I can't give you a repo because it's a private project on a different git host. I  fixed the issue by downgrading.

```
{ 
    jsc: {
     baseUrl: "./src"
    }
}
```
```
{ 
    jsc: {
     baseUrl: "./src"
    }
}
```

**Comment by winstxnhdw** [comment]
@kdy1 I have a daily dependabot workflow to bump `swc/core` on every release. The latest release broke the CI. Take a look here https://github.com/winstxnhdw/chatgpt-bill-bot/actions/runs/5823783150

**Comment by kdy1** [comment]
@winstxnhdw It seems like a bug of `@swc-node/register`.

@Brooooooklyn `jsc.baseUrl` should be a fully resolved value if it's passed as values instead of `.swcrc`.

**Comment by winstxnhdw** [comment]
Any update of when this change will be released?
