### ISSUE TITLE
Unconditional UB found in swc_ecma_parser around char::from_u32_unchecked

### ISSUE THREAD

**Issue by Manishearth** [swc-project/swc#7797]
https://github.com/swc-project/swc/blob/7fac0270c46fa041d75d1b0d693350c116e30e3e/crates/swc_ecma_parser/src/lexer/mod.rs#L69-L73

This calls [`char::from_u32_unchecked()`](https://doc.rust-lang.org/stable/std/primitive.char.html#method.from_u32_unchecked) on a u32 that is known to be not a valid Unicode Scalar value, which is a straight violation of the unsafe docs and may stop working at any time.

I suspect this branch exists for handling surrogate code points: I would suggest writing manual escaping code rather than attempting to use the builtin `escape_unicode()`

**Comment by kdy1** [comment]
Yeap, the branch exists for surrogates

**Comment by Boshen** [comment]
If anyone wants to tackle this, I have an implementation with everything referenced here: https://github.com/web-infra-dev/oxc/blob/99a4816ce7b6132b2667257984f9d92ae3768f03/crates/oxc_parser/src/lexer/mod.rs#L1349-L1374

```rust
    /// Surrogate pairs
    /// See background info:
    ///   * `https://mathiasbynens.be/notes/javascript-encoding#surrogate-formulae`
    ///   * `https://mathiasbynens.be/notes/javascript-identifiers-es6`
    fn surrogate_pair(&mut self) -> Option<SurrogatePair> {
        let high = self.hex_4_digits()?;
        // The first code unit of a surrogate pair is always in the range from 0xD800 to 0xDBFF, and is called a high surrogate or a lead surrogate.
        if !((0xD800..=0xDBFF).contains(&high) && self.peek() == '\\' && self.peek2() == 'u') {
            return Some(SurrogatePair::CodePoint(high));
        }

        self.current.chars.next();
        self.current.chars.next();

        let low = self.hex_4_digits()?;

        // The second code unit of a surrogate pair is always in the range from 0xDC00 to 0xDFFF, and is called a low surrogate or a trail surrogate.
        if !(0xDC00..=0xDFFF).contains(&low) {
            return Some(SurrogatePair::HighLow(high, low));
        }

        // `https://tc39.es/ecma262/#sec-utf16decodesurrogatepair`
        let astral_code_point = (high - 0xD800) * 0x400 + low - 0xDC00 + 0x10000;

        Some(SurrogatePair::Astral(astral_code_point))
    }
```

**Comment by kdy1** [comment]
Wow, thank you!
