### ISSUE TITLE
`.swcrc` loaded via `--config-file` does not resolve `jsc.baseUrl`

### ISSUE THREAD

**Issue by kushuh** [swc-project/swc#7800]
### Describe the bug

I recently upgraded from `"@swc/core": "^1.3.70"` to `"@swc/core": "^1.3.76"`, and my configuration does not compile anymore.

### Input code

Running the compile command: 

```typescript
npx swc package --config-file .build.swcrc --copy-files -d dist
```

### Config

In my `.build.swcrc` file.

```json
{
  "jsc": {
    "baseUrl": ".",
    "transform": {
      "react": {
        "runtime": "automatic",
        "importSource": "react"
      }
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "paths": {
      "@components/stateless": [
        "package/components/stateless"
      ],
      "@components/stateful": [
        "package/components/stateful"
      ],
      "@internal": [
        "internal-components"
      ],
      "@contexts": [
        "package/contexts"
      ],
      "@hooks": [
        "package/hooks"
      ],
      "@lib/backend": [
        "package/lib/backend"
      ],
      "@lib/api": [
        "package/lib/api"
      ],
      "@lib": [
        "package/lib"
      ],
      "@public/*": [
        "package/public/*"
      ],
      "@styles/*": [
        "package/styles/*"
      ]
    }
  },
  "module": {
    "type": "es6",
    "strict": false,
    "lazy": true,
    "noInterop": false
  },
  "minify": false
}
```

### Expected behavior

I expect a compilation success (worked well up until at least `"@swc/core": "^1.3.70"`)

### Actual behavior

I get this error during compilation:

```
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'base_dir(.) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.base_dir(.) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', ', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.28/src/path.rs::104104::1313
```

### Version

`"@swc/cli": "^0.1.62"` `"@swc/core": "^1.3.76"`

**Comment by sambauers** [comment]
Can confirm this seems to affect @swc/core v1.3.76 and reverting to v1.3.75 removes the issue.

**Comment by kdy1** [comment]
@kushuh If it still occurs, please provide a minimal reproduction .

**Comment by kdy1** [comment]
https://github.com/swc-project/jest/commit/b17afb5e910bc96b71bc15a0185c93ebff7800f2 is about `@swc/jest`

**Comment by sambauers** [comment]
Can confirm this works now for Jest provided I specify a `baseUrl`, without a `baseUrl` it fails. Docs say `baseUrl` is required with `paths` specified, so I guess that's OK 😄

**Comment by kushuh** [comment]
I was able to confirm the issue is not present on `1.3.75`. Here is a minimal reproduction example: https://github.com/kushuh/bug-swc-base-url

**Comment by kushuh** [comment]
I was also able to reproduce the issue without using jest 🤔

**Comment by kdy1** [comment]
Ah, `npx swc` invokes the native CLI... I only patched js API 🤣 
 I'll fix it and publish a new version later today.

**Comment by kdy1** [comment]
Oh the problem was `--config-file`

**Comment by kdy1** [comment]
Postponing to working hours as it's about `--config-file`, not default option
