### ISSUE TITLE
Unable to minify react-virtuoso

### ISSUE THREAD

**Issue by paveldvorak5** [swc-project/swc#7802]
### Describe the bug

can you check this issue?
https://github.com/web-infra-dev/rspack/issues/3774

### Input code

```typescript
Just include the package and use the example, it will crash.
```

### Expected behavior

App crashes when the package is compiled

### Version

0.5.1

### Additional context

they use @swc/helpers "version": "0.5.1

**Comment by kdy1** [comment]
Please provide a repro

**Comment by paveldvorak5** [comment]
You mean an example? It's here
https://github.com/paveldvorak5/virtuoso

**Comment by kdy1** [comment]
No, input to the swc minifier
