### ISSUE TITLE
Better config file parse error reporting

### ISSUE THREAD

**Issue by p7g** [swc-project/swc#781]
**Describe the feature**

When there is an issue with the config file provided, the error is simply "Failed to parse config file". It would be helpful if it would report what and where the error was.

**Additional context**

It seems like `serde_json::ErrorImpl` has a sensible [implementation of `Display`][1], so maybe it would suffice to simply propagate the result [here][2] and [here][3] rather than making a `failure::Context`?

[1]: https://docs.serde.rs/src/serde_json/error.rs.html#333
[2]: https://github.com/swc-project/swc/blob/master/src/lib.rs#L305
[3]: https://github.com/swc-project/swc/blob/master/src/lib.rs#L321

**Comment by kdy1** [comment]
@p7g Well, serde_json only provides error message like `data did not match any variant of untagged enum Rc` for untagged enums.

**Comment by kdy1** [comment]
By the way, I optimized error message for single-item cases, as I think it would be most frequently used
