### ISSUE TITLE
crash when compiling empty or type-only file with sourcemaps

### ISSUE THREAD

**Issue by jbedard** [swc-project/swc#7822]
### Describe the bug

A panic occurs when generating source-maps for an empty or types-only file. Seems to only happen with the binary and not the npm cli.

See the [line it crashes on](https://docs.rs/sourcemap/6.2.3/src/sourcemap/types.rs.html#655). Note the version of sourcemap is not the latest.

Type-only fails with commonjs modules and sourcemaps enabled:
swcrc.json:
```
{
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

```
> echo "export type Foo = number" > b.ts
> swc-darwin-x64 compile --source-file-name b.ts --config-file swcrc.json --source-maps true --out-file b.js b.ts
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sourcemap-6.2.3/src/types.rs:655:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Empty fails without any swcrc:
```
> echo '' > d.ts
> ./swc-darwin-x64 compile --source-file-name d.ts --source-maps true --out-file d.js d.ts
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sourcemap-6.2.3/src/types.rs:655:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Input code

```typescript
export type Foo = number
```

### Config

```json
{
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

### Expected behavior

Output an empty file + sourcemap

### Version

SWC 0.91.63 (from v1.3.77)

**Comment by supercairos** [comment]
I have the same issue :(

**Comment by Zemnmez** [comment]
I have found a workaround to this issue: putting a single comment in the file fixes it, assumedly because it makes the JS file length nonzero.
