### ISSUE TITLE
@swc/helpers latest version has been downgraded

### ISSUE THREAD

**Issue by nuintun** [swc-project/swc#7825]
### Describe the bug

![image](https://github.com/swc-project/swc/assets/1730277/0b4b5966-31bf-4d8d-9c60-ae55ff97798d)

### Expected behavior

Set the correct latest version

### Version

0.5.1

**Comment by kdy1** [comment]
I fixed it. https://www.npmjs.com/package/@swc/helpers?activeTab=versions
