### ISSUE TITLE
SyntaxError: Expecting Unicode escape sequence \uXXXX.

### ISSUE THREAD

**Issue by 9aoy** [swc-project/swc#7826]
### Describe the bug

format.ascii_only does not handle the key correctly.

### Input code

```typescript
window. a = {Д: 'A', Å: 'A', Ð: 'D', Þ: 'o', å: 'a'}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "format": {
        "ascii_only": true
      },
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAAyvPzEvJL9dTSFSwVai%2BMMVKQd1RXUfhcCuMMQHIcAEx5gEZ%2BSDGUiAjUb2WCwBBjI6COgAAAA%3D%3D&config=H4sIAAAAAAAAA32VS3LbMAxA9zmFR%2Bts00UP0F3PwKFFUKZLERoCdKzJ5O6FKPkTC9LOwsOP%2BPnr7XBoztQ2vw9f8lM%2BBpsJ8v1bJDQmtleRNND2ltocBm7eb%2FRME%2BJcoEq%2BZ9CwzR1wNaKPRbuJiASL9iLqQwp%2BfA7nMfeWnyQik6ghGExxfI51jyYaLfZDBqIXu9yVHhJPYm8jwfszy%2FhJP7Kp8iNiBJt2iLFkQmLoIGuOW4zRDgTmYrPiZcrU5kCohZhgYXBmyDioPLnAAZPEXFMH1pkWHSgoZGg5XEAzk1hilkiep7ynYgfH0nV1MF6s4WJjsazEhGttiWSreD1hIDa%2BJK2EM9yowQyX4r5aBm8ycMlpbXfGkDZ68g9AKhAtUbI9aH6rhpd52rL2u5YheRl0HhUuS6G9MkEnRTUheKWyU2Ugc9C6mcGVFqbKtlo6C94oHwUHBryXWVFc02fg9qQF5XEA9AqQ%2FlqvTdUMzH0LN%2Fi0EDv4j7yS9QFbNOSWnLYpjf0R406AHviEbkdBWsG4jbNcieuwzUtyIKMBTlUpVMH6CMgCMJpYL%2BxqNmQ9xKPpIh4fZ2J1MXubuse%2Bz8f7bVFoenSlwuVfYervfMx%2FNQ%2Bl2%2B2%2BZdAE%2BnszrDG%2F%2FwP0lKxbYAYAAA%3D%3D

### Expected behavior

window.a={"\u0414":"A","\xc5":"A","\xd0":"D","\xde":"o","\xe5":"a"};

### Actual behavior

window.a={\u0414:"A",\xc5:"A",\xd0:"D",\xde:"o",\xe5:"a"};

### Version

1.3.74

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/7805
