### ISSUE TITLE
Can't use ESM with `jsc.paths`

### ISSUE THREAD

**Issue by Nickersoft** [swc-project/swc#7829]
### Describe the bug

Hey folks,

I've come into a bit of a pickle. Node 19 [drops support for `es-module-specifier-resolution`](https://stackoverflow.com/questions/74660824/nodejs-v19-drops-support-for-es-module-specifier-resolution-node-which-makes-i), which I have been using to support extension-less imports in my ESM codebase.

I realized this makes it impossible for me to continue using `jsc.paths` in my TypeScript project, as `ts` files automatically have their extensions removed, yet if I use `js` as an extension, SWC can't find the path and doesn't transform the import.

## Example

```
"paths": {
    "@my/pkg": ["libs/pkg/src/index.ts"]
}
```

results in:

```
import { fn } from 'libs/pkg/src/index';
```

and

```
"paths": {
    "@my/pkg": ["libs/pkg/src/index.js"]
}
```

results in:

```
import { fn } from '@my/pkg';
```

### Input code

```typescript
import { fn } from '@my/pkg';
```

### Config

```json
{
  "module": {
    "type": "es6"
  },
  "jsc": {
    "baseUrl": ".",
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "importMeta": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "paths": {
      "@my/pkg": ["libs/pkg/src/index.ts"],
    }
  }
}
```

### Expected behavior

I think that SWC should provide a similar mechanism to how [TypeScript supports ESM](https://2ality.com/2021/06/typescript-esm-nodejs.html#typescript), where TS files can be imported as JS (i.e. `jsc.paths` should find and transform the path appropriately).

Better yet, now that you [_can_ import `ts` files in TS](https://github.com/microsoft/TypeScript/issues/53316), what I really wish is that you could just always use `ts` extensions for everything and SWC would be smart enough to know to replace them with `js` in the transpiled code instead of just removing the extension.

### Actual behavior

Right now, SWC defaults to removing TS extensions unless you manually import TS files as JS (which luckily TS supports), however, this breaks down when using `jsc.paths` as described above. Starting in Node 19, this will result in un-runnable code without a custom loader.

### Version

1.3.77

**Comment by Nickersoft** [comment]
Hey @kdy1! Excited to see this marked as planned. Curious out of the suggestions above, what approach do you think the SWC project will take here? Or are you still unsure?

**Comment by kdy1** [comment]
I prefer following the direction of `tsc`, but I'm not sure if `tsc` has one. Mainly because I didn't read your comment yet... I need some time 😄

**Comment by Nickersoft** [comment]
Haha sure thing – regardless, super happy this is getting looked at and let me know if I can help in any way :)

**Comment by kdy1** [comment]
I think 

```json

{
  "module": {
    "type": "es6"
  },
  "jsc": {
    "baseUrl": ".",
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "importMeta": true
    },
    "paths": {
      "@my/pkg": ["libs/pkg/src/index.js"],
    }
  }
}
```

is a better API

**Comment by kdy1** [comment]
But maybe we need an option to fully qualify index.js even if we can remove it from the import.

**Comment by kdy1** [comment]
Filed https://github.com/swc-project/swc/issues/7861
