### ISSUE TITLE
Running test using swc/jest with coverage is 5x times slower than running it without coverage!

### ISSUE THREAD

**Issue by chestozo** [swc-project/swc#7840]
### Describe the bug

I am trying to switch to `@swc/jest` instead of standard `ts-jest`.
Running locally a single test takes 2x less time which is 🔥 
But on CI I was getting longer run times.

So I've started googling similar issues and found this post
https://www.reddit.com/r/typescript/comments/v8cc5t/no_speed_difference_after_replacing_tsjest_with/

and after some more experiments I discovered that running tests with `--coverage` is much slower than without it.

For example:
```
yarn jest test.spec.ts --no-cache
Time:        50.664 s

yarn jest test.spec.ts --no-cache --coverage
Time:        244.773 s
```

So running our tests with `--coverage` ON on CI using `@swc/jest` is slower compared to standard `ts-jest`.
Is it a known issue?

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "transform": {
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment"
      },
      "legacyDecorator": true      
    },
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs",
    "noInterop": true
  },
  "minify": false,
  "isModule": true
}
```

### Expected behavior

No such tests run time degradation.

### Version

"@swc/core": "^1.3.77"

### Additional context

Other related dependencies:
```
"@swc/core": "^1.3.77"
"@swc/jest": "^0.2.29"
"jest": "27.5.1"
```

**Comment by kwonoj** [comment]
Jest creates coverage via babel, so if you're enabling babel there's actually 2 path of transform via swc and babel both. Do you think this is an issue of @swc/core does something incorrect when there's transform runs against coverage-enabled codes? Is there a repro outside of jest which rules out babel?

**Comment by kdy1** [comment]
Closing as there's a no miminal repro

**Comment by chestozo** [comment]
@kwonoj @kdy1 so maybe this is an issue of swc/jest?

**Comment by kdy1** [comment]
No

**Comment by chestozo** [comment]
@kdy1 why?
