### ISSUE TITLE
swc says "Expected ',', got 'className'" when compiling my webpack + swc based react project.

### ISSUE THREAD

**Issue by shibisuriya** [swc-project/swc#7841]
### Describe the bug

I have a webpack based react project (I use swc-loader instead of babel-loader).

The github link to the project - https://github.com/shibisuriya/swc-import-bug

This is my directory structure.
├── common
│   └── chart
│       └── index.jsx
└── project
    ├── package.json
    ├── public
    │   └── index.html
    ├── src
    │   ├── App.jsx
    │   ├── index.js
    │   └── style.css
    ├── webpack.config.js
    └── yarn.lock

 The thing is I have a folder called common which has a component called chart... 
I am importing the chart component into App.jsx... 
The project doesn't build... swc says 

  × Expected ';', got 'from'
   ╭─[/Users/shibisuriya/Desktop/personal-projects/swc-import-bug/common/chart/index.jsx:1:1]
 1 │ import React from 'react'
 2 │
 3 │ function Chart() {
 4 │    return <div>Hello from chart component</div>
   ·                    ────
 5 │ }
 6 │
 7 │ export default Chart;
   ╰────

Thank you.

### Config

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": true,
            "dynamicImport": false,
            "privateMethod": false,
            "functionBind": false,
            "exportDefaultFrom": false,
            "exportNamespaceFrom": false,
            "decorators": false,
            "decoratorsBeforeExport": false,
            "topLevelAwait": false,
            "importMeta": false
        },
        "transform": null,
        "target": "es5",
        "loose": false,
        "externalHelpers": false,
        // Requires v1.2.50 or upper and requires target to be es2016 or upper.
        "keepClassNames": false
    },
    "minify": false
}
```

### Playground link

Use the github link that I provided.

### Expected behavior

The project should build normally.

### Actual behavior

The project doesn't build.

### Version

1.3.78

**Comment by kwonoj** [comment]
This is not an swc side issue, you configured path _outside_ of where swc can reference its config and transpilation option. I.e, if `common` is under `project` swc picks up transpilation correctly.

We can't offer help how you organize your codes per the tooling (webpack) and its loaders, something you need to figure out / troubleshooting.
