### ISSUE TITLE
May be a problem with types.ts declaration file

### ISSUE THREAD

**Issue by Ossianaa** [swc-project/swc#7844]
### Describe the bug

https://github.com/swc-project/swc/blob/6a8ea89f4bffd6e6104a370653661bcc5b748b9a/packages/types/index.ts#L1543

body?: BlockStatement;
The `Fn` Under what circumstances can there be no `body`

why not `body: BlockStatement`?

### Input code

```typescript
none
```

### Config

```json
none
```

### Expected behavior

body?: BlockStatement; -> body: BlockStatement;

### Version

1.3.78

**Comment by kdy1** [comment]
Please refer to usages before filing an issue.

```ts
declare function foo();
```
