### ISSUE TITLE
Incorrect minification of rollup commonjs wrapper

### ISSUE THREAD

**Issue by SukkaW** [swc-project/swc#7847]
### Describe the bug

I am using swc to minify a bundled version of Node.js-powered CLI.

Here is a part of the code (CommonJS wrapper generated by `@rollup/plugin-commonjs`):

```js
var state;
var hasRequiredState;

function requireState () {
	if (hasRequiredState) return state;
	hasRequiredState = 1;

	var ERR_INVALID_OPT_VALUE = requireErrors().codes.ERR_INVALID_OPT_VALUE;
	function highWaterMarkFrom(options, isDuplex, duplexKey) {
	  return options.highWaterMark != null ? options.highWaterMark : isDuplex ? options[duplexKey] : null;
	}
	function getHighWaterMark(state, options, duplexKey, isDuplex) {
	  var hwm = highWaterMarkFrom(options, isDuplex, duplexKey);
	  if (hwm != null) {
	    if (!(isFinite(hwm) && Math.floor(hwm) === hwm) || hwm < 0) {
	      var name = isDuplex ? duplexKey : 'highWaterMark';
	      throw new ERR_INVALID_OPT_VALUE(name, hwm);
	    }
	    return Math.floor(hwm);
	  }

	  // Default value
	  return state.objectMode ? 16 : 16 * 1024;
	}
	state = {
	  getHighWaterMark: getHighWaterMark
	};
	return state;
}
```

After minification, it becomes this:

```js
var fv,fE;
// redacted
function cz(){if(fE)return fv;fE=1;var e=cH().codes.ERR_INVALID_OPT_VALUE;return{getHighWaterMark:function(t,r,n,i){var s=null!=r.highWaterMark?r.highWaterMark:i?r[n]:null;if(null!=s){if(!(isFinite(s)&&Math.floor(s)===s)||s<0){var o=i?n:"highWaterMark";throw new e(o,s)}return Math.floor(s)}return t.objectMode?16:16384}}}
```

Note that after the minification, the `fv` (which originally is the `state`) is no longer assigned.

I couldn't find the minimum reproduction (my guess is that some code somewhere has interfered with the compression), so I have attached the full code in the GitHub Gist.

### Input code

```typescript
// https://gist.github.com/SukkaW/0a02d14521418685c6bc822c043bbe6a
// The playground URL is too long to attach
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "minify": {
      "compress": true,
      "mangle": true,
      "module": true
    }
  },
  "minify": true,
  "isModule": true,
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

The minified code should not produce any error.

### Actual behavior

```
TypeError can not read property (`getHighWaterMark`) of `undefined`
```

### Version

1.3.78

### Additional context

I am able to reproduce the issue since swc 1.2.166. The issue doesn't happen on 1.2.165.

**Comment by SukkaW** [comment]
Also the diff between 1.2.166 and 1.2.165: https://github.com/swc-project/swc/compare/v1.2.165...v1.2.166

**Comment by Austaras** [comment]
This can be reduced to [playground](https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA2WPsQ7CIBCG5%2FIUt5UmpgnRGNPGuLp00cEZKW3RBiJcXQzvLi2pmnoDgfs%2FPo50cBIcWiUwLUkzaIHKaLDyMSgrz8hR0gxeBEKpBmjH3Slm9RRmAcXB6uAIp3LilgzsgcXklw3dqB2rlXhUbXcJfVtxey9gHoW6%2BMyXXYpyc71JgZWpJRyAbaEIy3q3KT83%2FLTzJfFk%2FENLs9n35DZKVn9TkyQRRjvTy7w3LWWMZcS%2FAaNa35UvAQAA&config=H4sIAAAAAAAAA32VTbKbMAzH9zlFhnUXbXftAbrrGTwOlolT22IsOS%2FMm9y9gkBeJgg2maCfPsxfsvg8HI%2FNhdrm9%2FFT%2FspDbwtBeT6LhYbM9iaWBtpkqS2h5%2BbbQi80Im8jwWS6P0jDtnTAUxT9%2FP7j1xzRRESCJWK2pZCDH15rJpu7%2BOYm5hZTX4DoxVWsUqkmyEzv%2FhMr%2BDECLvXVfkKMYPMOMZZMyAwdFC1xizHansBcbVGyjCe1JRBqJUZYGZzpC%2FYqzy5wwCw119SBdaZFBwoKBVoOV9DCpJaEZcK1sAt2cKpdN7X%2FLRquNlbLSk24TS2R0ypZzxiIja9Zk%2FABNzR4wFnc98jgTQGuJa%2FjLhjyRk%2F%2BAYgC0RJlm0DLO3l4maetaL8bGbKXSeZB4TL22ltm6ERUE4JXlB2VgcJB62YBV1sYlW2148x4Qz4KDgx4L7OipKaPwO1ZK8pDD%2BgVIP21XpuqBzDPW7jBxwuxg%2F%2FIW7I%2BYLNHsnzepjSkE8adAgn4jG7HQVrBuI2LbIlbv81rdiCjAU51qTSB9RKQC8Bo4rRGV7Mh10Mymi7i6WtNzA73w%2FI7reOvBfss3gT6i67G17Fr0mKZvwVjv8cNLu1JmC%2FUjAkP9%2F9vsNE9NQYAAA%3D%3D), seems like the problem lies in analyze of `fn_local`(again)

**Comment by SukkaW** [comment]
> This can be reduced to [playground](https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA2WPsQ7CIBCG5%2FIUt5UmpgnRGNPGuLp00cEZKW3RBiJcXQzvLi2pmnoDgfs%2FPo50cBIcWiUwLUkzaIHKaLDyMSgrz8hR0gxeBEKpBmjH3Slm9RRmAcXB6uAIp3LilgzsgcXklw3dqB2rlXhUbXcJfVtxey9gHoW6%2BMyXXYpyc71JgZWpJRyAbaEIy3q3KT83%2FLTzJfFk%2FENLs9n35DZKVn9TkyQRRjvTy7w3LWWMZcS%2FAaNa35UvAQAA&config=H4sIAAAAAAAAA32VTbKbMAzH9zlFhnUXbXftAbrrGTwOlolT22IsOS%2FMm9y9gkBeJgg2maCfPsxfsvg8HI%2FNhdrm9%2FFT%2FspDbwtBeT6LhYbM9iaWBtpkqS2h5%2BbbQi80Im8jwWS6P0jDtnTAUxT9%2FP7j1xzRRESCJWK2pZCDH15rJpu7%2BOYm5hZTX4DoxVWsUqkmyEzv%2FhMr%2BDECLvXVfkKMYPMOMZZMyAwdFC1xizHansBcbVGyjCe1JRBqJUZYGZzpC%2FYqzy5wwCw119SBdaZFBwoKBVoOV9DCpJaEZcK1sAt2cKpdN7X%2FLRquNlbLSk24TS2R0ypZzxiIja9Zk%2FABNzR4wFnc98jgTQGuJa%2FjLhjyRk%2F%2BAYgC0RJlm0DLO3l4maetaL8bGbKXSeZB4TL22ltm6ERUE4JXlB2VgcJB62YBV1sYlW2148x4Qz4KDgx4L7OipKaPwO1ZK8pDD%2BgVIP21XpuqBzDPW7jBxwuxg%2F%2FIW7I%2BYLNHsnzepjSkE8adAgn4jG7HQVrBuI2LbIlbv81rdiCjAU51qTSB9RKQC8Bo4rRGV7Mh10Mymi7i6WtNzA73w%2FI7reOvBfss3gT6i67G17Fr0mKZvwVjv8cNLu1JmC%2FUjAkP9%2F9vsNE9NQYAAA%3D%3D), seems like the problem lies in analyze of `fn_local`(again)

The more proper re-production case would be like this:

```js
'use strict';
function requireState() {
    if (hasRequiredState) return state;
    hasRequiredState = 1;
    return state = {
        getHighWaterMark: function(o) {
            return o.objectMode ? 16 : 16384;
        }
    };
}
if (g()) {
    var state, hasRequiredState;
    const a = requireState()
		console.log(a.getHighWaterMark())
}
```

which swc minifies into:

```js
'use strict';
if (g()) {
    var state, hasRequiredState;
    let a = hasRequiredState ? state : (hasRequiredState = 1, {
        getHighWaterMark: function(o) {
            return o.objectMode ? 16 : 16384;
        }
    });
    console.log(a.getHighWaterMark());
}
```

and `state` is never re-assigned.
