### ISSUE TITLE
Spread operator doesn't work for generators and iterators

### ISSUE THREAD

**Issue by Yoskutik** [swc-project/swc#7850]
### Describe the bug

The compiled version of code, that contains spread operator over generators and iterators doesn't work as it suppose to.

### Input code

```typescript
const spread = (iterable) => [...iterable];

const genObj = (function* () {
  yield 1;
  yield 2;
  yield 3;
})();

const urlSearchParamsIterator = new URLSearchParams('?a=1&b=2').entries();

console.log(spread(genObj));
console.log(spread(urlSearchParamsIterator));
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true,
      "tsx": true,
      "jsx": true
    },
    "loose": true
  },
  "env": {
    "targets": "> 0.25%",
    "mode": "entry",
    "coreJs": "3.27",
    "loose": true,
    "bugfixes": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA3WPMQvCMBSE9%2FyKN9nEIdA6hugsCIriJA5p%2BqyRmEiSIiL%2Bd1uL1UG3493H3TvtXUwQLwFVBRKoSRhUaZGBnMKOc%2F4%2B7AUh%2BgXX6JblqYMPjdPJeDcGyuBOAG4GbQW5GGTxkRNBHoyyIaYJdoMq6ONKBXWO864n%2BdDmOrzCdr34dmk2UzIflbLIGEeXgsE4ZHmL3Pqa9ito%2Fx9r3R%2Fmn9aWfgLGMECDCgEAAA%3D%3D&config=H4sIAAAAAAAAA22OzQrCMBCE732KsOBNilRE8OBd3yKma2mxTdjdloTSdzet%2FRHxtvPNLDN9ohRUbOCi%2BnhG4TQx0qoj4dCI9pGABIdsqHQC%2B8XNQ6Pr0txqZ0liSKjF1RT2v6ha0USGjwEvaxk3Y8KATbcNE00FCo87ruqQZqfdPAJqm4%2BvMS4UFmgs4X1KH9PsDH9qZvRoi2fpkb%2FKk%2BENE9GDihgBAAA%3D

### Expected behavior

Will output

> [1, 2, 3]
> [['a', '1'], ['b', '2']]

### Actual behavior

Outputs

> [{ ... }]
> [URLSearchParams Iterator]

### Version

1.3.78

### Additional context

Such problem is not presented in Babel or TypeScript (if it configured right)

**Comment by Yoskutik** [comment]
Maybe, instead of `[].concat(...)` it would be better to use `Array.from`

**Comment by kdy1** [comment]
You are using `loose` mode.

**Comment by Yoskutik** [comment]
Oh, thank you very much. Didn't know that "loose" option affects iterations
