### ISSUE TITLE
there isn't globalThis polyfill when env is ios_saf 11

### ISSUE THREAD

**Issue by liucan233** [swc-project/swc#7862]
### Describe the bug

When I use babel,  env is ios_saf 11, babel added globalThis polyfill, but **swc is not**.

### Input code

```typescript
console.log(Promise.resolve)
console.log(globalThis)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "ios_saf 10",
    "coreJs": 3,
    "mode": "usage"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.79&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1wgoys%2FNLE7VK0oFCpWlanIlI0mm5%2BQnJeaEZGQWawIAoy6w3DQAAAA%3D&config=H4sIAAAAAAAAA1WPTQrCMBCF9z1FmLULRXDhEQTPIEOclpTmh0wqltK7m6RJbXeZ903eezM3QkDPEu5ijs84OPRMfpujwpMJ%2BI0KkNTI0isX4FRpzwm1ODBlaVkJDNYyVVI0rYxqp723tNp5Yj4uplU03UBH56a4g7bvMcPSOUyOcj%2B%2BwX%2Bphm3GoPhZfwY%2FrhqZz84IfUchtQFl%2BcXYisu53Bq7enokdq3n2HeOHRk7ysHN8gMao%2Ff5UQEAAA%3D%3D

### Expected behavior

add globalThis polyfill, like as babel: https://babeljs.io/repl#?browsers=ios_saf%2011&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUykCMCG0AqAFgJYQCUQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.22.11&externalPlugins=&assumptions=%7B%7D

### Version

1.3.79

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.79&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1wgoys%2FNLE7VK0oFCpWlanIlI0mm5%2BQnJeaEZGQWawIAoy6w3DQAAAA%3D&config=H4sIAAAAAAAAA1WPTQrCMBCF9z1FmLWIVXDhEQTPIEOclpTmh0wqltK7m6ZJtbvM%2BybvvZkqIaBjCTcxxWccHHomv81R4dEE%2FEQFSGpk6ZULcCi04wU12DMlaV4J9NYyFZI1rYxqxn9vabXzxLxfXFbRtD3tnavsDtq%2BhgRz5zA6Sv34Cr%2BlErYZg%2BJH%2BRn8sGpk3n9G6FsKSxtQlp%2BMjahP%2BdbY1dM9scvxXBc1dknZA2NLKb2avz7eo61WAQAA

Your `.swcrc` is wrong.
