### ISSUE TITLE
When using @swc/helpers with @swc/core 1.3.79, the build output path has added node_modules.

### ISSUE THREAD

**Issue by hi-otto** [swc-project/swc#7863]
### Describe the bug

I have provided a minimal demo for reproduction in the following repository:
https://github.com/hi-otto/swc-1.3.79-bug

### Input code

```typescript
import test from '~/util/test';

class X {

}

console.log(test, X);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./src/*"
      ]
    },
    "externalHelpers": true
  }
}
```

### Playground link

https://github.com/hi-otto/swc-1.3.79-bug

### Expected behavior

why 1.3.79 add `node_modules` before `@swc/helpers`

## dist-1.3.78/index.js
```
import { _ as _class_call_check } from "@swc/helpers/_/_class_call_check";
import test from "./util/test";
var X = function X() {
    "use strict";
    _class_call_check(this, X);
};
console.log(test, X);

```

## dist-1.3.79/index.js
```
import { _ as _class_call_check } from "node_modules/@swc/helpers/esm/_class_call_check";
import test from "./util/test";
var X = function X() {
    "use strict";
    _class_call_check(this, X);
};
console.log(test, X);

```

### Version

1.3.79

**Comment by kdy1** [comment]
Are you using windows?

**Comment by kdy1** [comment]
We need some more integration tests. It works on swc testing system... I filed https://github.com/swc-project/swc/issues/7865

**Comment by hi-otto** [comment]
> Are you using windows?

mac

**Comment by kdy1** [comment]
Let's wait for https://github.com/swc-project/swc/actions/runs/5976742103

**Comment by m-nouman-munir** [comment]
Ok

**Comment by m-nouman-munir** [comment]
with v1.3.80 I'm facing `⠋  TSC  Initializing type checker...Error: Cannot find module 'src/app.module'`
