### ISSUE TITLE
Compiled code uses full path for all NPM imports

### ISSUE THREAD

**Issue by Nickersoft** [swc-project/swc#7869]
### Describe the bug

I just upgraded to the latest version of SWC and now all my compiled code uses a full path for NPM imports, which won't run for me:

<img width="770" alt="image" src="https://github.com/swc-project/swc/assets/2104129/a9c43c60-1460-40b8-af09-127ed7317d95">

### Input code

```typescript
import { Logger } from "@nestjs/common";
```

### Config

```json
{
  "module": {
    "type": "es6"
  },
  "jsc": {
    "baseUrl": ".",
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "importMeta": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "paths": {
      "@lg/database": ["libs/database/src"],
      "@lg/notifications": ["libs/notifications/src"],
      "@lg/eventing": ["libs/eventing/src"],
      "@lg/test": ["libs/test/src"],
      "@lg/i18n": ["libs/i18n/src"],
      "@lg/authentication": ["libs/authentication/src"],
      "@lg/assessments": ["libs/assessments/src"]
    }
  }
}
```

### Expected behavior

NPM imports should be preserved as originally written

### Actual behavior

(see above)

### Version

1.3.79

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/7864

**Comment by Nickersoft** [comment]
@kdy1 Is this being addressed? The other issue was closed shortly after being opened.

**Comment by Nickersoft** [comment]
I think you meant to reference #7863. Will keep my eye on it!
