### ISSUE TITLE
Error handling functionDecl in block

### ISSUE THREAD

**Issue by Ossianaa** [swc-project/swc#7875]
### Describe the bug

when define a functiondecl in loop, next loop can't find the decl.

and then It causes a compress error

### Input code

```typescript
for (var i = 1; ; i++) {
    if (i == 1) {
        function b() {
            console.log('call ok');
        }
    } else {
        b();
        break;
    }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "mangle": false,
      "compress": {
        
      },
      "format": {
        "wrapFuncArgs":true
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.80&code=H4sIAAAAAAAAA1WMSQqAMAxF94J3%2BDsrguC6eJhaWimGBuqwkd7diOLwVsmfPCeozSQE9Og0NELT1NjLAkLwUGKI80gnfo12CRwxqJ9%2BYjnOTK4lHlVlDRF4qmr9hvJ1Zjia3bctY5%2FYkJyZ7l8q%2BQB97bcEqQAAAA%3D%3D&config=H4sIAAAAAAAAA12Quw7CMAxF935F5JkVBjYWNj7CCm6VqnnITgVV1X9vSJNSWCL7%2Blw%2FMjdKQS8armpOYUoCshDveVJkchHfSQHSFkWzCRFOtdrLp9TiIJSlZatARO4oZpecCw6D90IVL5o1zrTTcaBF1w1%2FWJK1t4FJ5IAqVYJlp1rPFuMPAy%2FGcB%2BdvnGX3JFHqramvrkBWP8c8%2BTyGXEKtJ1wgS9UF97XAyOP6szdlxWY5AKfWAEAAA%3D%3D

### Expected behavior

it shouldn't crash

### Version

1.3.80

**Comment by Austaras** [comment]
This is the expected result -- your input is es module, which implies strict mode, and in strict mode, function declaration is strictly block scoped. So the `b()` in the else branch is referring to some global var b.

And as a suggestion, never declare functions in block, their behaviours differ in many runtimes.
