### ISSUE TITLE
swc_ecma_quote tests are failing

### ISSUE THREAD

**Issue by Havunen** [swc-project/swc#7877]
### Describe the bug

**1 Clone repo
2 run the tests**

`cargo test -p swc_ecma_quote`

    Finished test [unoptimized + debuginfo] target(s) in 0.15s
     Running unittests src/lib.rs (target/debug/deps/swc_ecma_quote-2430af88bd0b5ea1)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests swc_ecma_quote

running 4 tests
test crates/swc_ecma_quote/src/lib.rs - quote (line 91) ... FAILED
test crates/swc_ecma_quote/src/lib.rs - quote (line 75) ... FAILED
test crates/swc_ecma_quote/src/lib.rs - quote (line 35) ... FAILED
test crates/swc_ecma_quote/src/lib.rs - quote (line 59) ... FAILED

failures:

---- crates/swc_ecma_quote/src/lib.rs - quote (line 91) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:98:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "import thing from \"$thing\";" as ModuleItem,
12 | |                 thing: Str = "foo".into(),
13 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:98:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "import thing from \"$thing\";" as ModuleItem,
12 | |                 thing: Str = "foo".into(),
13 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::ModuleItem;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:98:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "import thing from \"$thing\";" as ModuleItem,
12 | |                 thing: Str = "foo".into(),
13 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::ModuleDecl;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:98:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "import thing from \"$thing\";" as ModuleItem,
12 | |                 thing: Str = "foo".into(),
13 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::ImportSpecifier;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:98:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "import thing from \"$thing\";" as ModuleItem,
12 | |                 thing: Str = "foo".into(),
13 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
   |
2  + use swc_ecma_ast::Ident;
   |

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0433`.
Couldn't compile the test.
---- crates/swc_ecma_quote/src/lib.rs - quote (line 75) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Stmt;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Decl;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::VarDeclKind;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Pat;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Expr;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:82:13
   |
10 |   let _stmt = quote!("const $name = 4;" as Stmt, name =
   |  _____________^
11 | | Ident::new("ref".into(), DUMMY_SP));
   | |___________________________________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Lit;
   |

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0433`.
Couldn't compile the test.
---- crates/swc_ecma_quote/src/lib.rs - quote (line 35) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Stmt;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Decl;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::VarDeclKind;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Pat;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Expr;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:42:13
   |
10 | let _stmt = quote!("const $name = 4;" as Stmt, name = Ident::new("ref".into(), DUMMY_SP));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Lit;
   |

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0433`.
Couldn't compile the test.
---- crates/swc_ecma_quote/src/lib.rs - quote (line 59) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:66:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "const $name = $val;" as Stmt,
12 | |                 name = Ident::new("ref".into(), DUMMY_SP),
13 | |                 val: Expr = 4.into(),
14 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:66:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "const $name = $val;" as Stmt,
12 | |                 name = Ident::new("ref".into(), DUMMY_SP),
13 | |                 val: Expr = 4.into(),
14 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Stmt;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:66:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "const $name = $val;" as Stmt,
12 | |                 name = Ident::new("ref".into(), DUMMY_SP),
13 | |                 val: Expr = 4.into(),
14 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Decl;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:66:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "const $name = $val;" as Stmt,
12 | |                 name = Ident::new("ref".into(), DUMMY_SP),
13 | |                 val: Expr = 4.into(),
14 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::VarDeclKind;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `swc_core`
  --> crates/swc_ecma_quote/src/lib.rs:66:13
   |
10 |   let _stmt = quote!(
   |  _____________^
11 | |                 "const $name = $val;" as Stmt,
12 | |                 name = Ident::new("ref".into(), DUMMY_SP),
13 | |                 val: Expr = 4.into(),
14 | |             );
   | |_____________^ use of undeclared crate or module `swc_core`
   |
   = note: this error originates in the macro `$crate::swc_ecma_quote_macros::internal_quote` which comes from the expansion of the macro `quote` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
2  + use swc_ecma_ast::Pat;
   |

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0433`.
Couldn't compile the test.

failures:
    crates/swc_ecma_quote/src/lib.rs - quote (line 35)
    crates/swc_ecma_quote/src/lib.rs - quote (line 59)
    crates/swc_ecma_quote/src/lib.rs - quote (line 75)
    crates/swc_ecma_quote/src/lib.rs - quote (line 91)

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s

error: doctest failed, to rerun pass `-p swc_ecma_quote --doc`

### Playground link

main branch

### Expected behavior

tests pass for all packages

### Actual behavior

tests are failing

### Version

main

**Comment by kdy1** [comment]
This is not a bug and I don't this maters

**Comment by kdy1** [comment]
One solution is to add `,ignore` to all of them, but I'm not sure if it worths

**Comment by Havunen** [comment]
Can we change the type of this issue to something else then? I would like to at least improve the CONTRIBUTING.md scripts to make it easier to contribute to this project

**Comment by Havunen** [comment]
Ok I understand this issue now better. The contributing doc has a script which runs all the tests, but CI script runs the tests only for specific set of crates and some of them has special parameters too. It would be nice to extract those steps somewhere so CI pipeline could be easily replicated locally.
