### ISSUE TITLE
swc not emit any transformation for 'using' keyword.

### ISSUE THREAD

**Issue by dudubs** [swc-project/swc#7879]
### Describe the bug

No any transformation for resource management

### Input code

```typescript
using x = a();
```

### Config

```json
{
  
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true,
  "experimental": {
    "plugins":["proposal-explicit-resource-management"]
  },
 
}
```

### Playground link

https://play.swc.rs/?version=1.3.80&code=H4sIAAAAAAAAAystzsxLV6hQsFVI1NC0BgCXu343DgAAAA%3D%3D&config=H4sIAAAAAAAAA1VQzWrDMAy%2B5ymCzg2UjF32DrvuMnYwrhJcbMtICjSUvvvkNU4z44MlfX%2FWvet7u3AVDx%2F93Z5WKLssE3HaW%2B3ABT2xU%2BIvZAmUDQHjeRyH8xvsyMfpqVMcC%2FJBBGTN6m6VpGtB8RyKwqlNVepIecHW6o5y6nhGrWSU940FkUjQepOLstEghRym9ejrKRVGkf%2FACnV5jjv%2FaddtlpDosvwN214sc7U3tUT5KvBCNsddHYJ8Nnr7EeCtIIeEtoT4ki1xmUO2bN9QmAqJi4MhY%2FBBB0tNC3scLKmbsXLhZ%2FPtHr8zRB2tvwEAAA%3D%3D

### Expected behavior

expect to any transformation for resource management.

### Actual behavior

just as input code, 
`using x = a();`

### Version

1.3.80

**Comment by ffMathy** [comment]
I tried version 1.3.81. It gives a different error now.

```
TypeError: Property [Symbol.dispose] is not a function
```

In this case, I don't have a `Symbol.dispose`, because I am using the async variant `Symbol.asyncDispose`.

So there is a bug still.

cc @kdy1

**Comment by kdy1** [comment]
Please file another issue with a repro

**Comment by ffMathy** [comment]
Already did. It's #158. But it was closed prematurely. The repro in there is still the same.

**Comment by ffMathy** [comment]
Submitted here: #7902.
