### ISSUE TITLE
expect(jest.fn()).toHaveBeenCalledWith(...expected), swc/jest error

### ISSUE THREAD

**Issue by Amitgupta76** [swc-project/swc#7897]
### Describe the bug

The thing is I'm trying to implement swc/jest in my repo.
But when I implemented it there seems to be the error of tohavebeencalledwith.

This is the import statement:
`import * as mixpanelTest from '../../../../utils/mixpanel';`

This is the mock function that I used:
`jest.mock('../../../../utils/mixpanel', () => {
  const actualModule = jest.requireActual(
    '../../../../utils/mixpanel',
  );
  return {
    __esModule: true,
    ...actualModule,
  };
});`

This is the error I get:
`  expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "Publish Action Plan Button Clicked", ObjectContaining {"AdminId": "123", "AdminRole": "coach", "MemberId": "1234", "PlanNumber": 3, "PlanType": "Co-created plan", "PublishType": "Edit Plan"}

    Number of calls: 0`

### Input code

```typescript
it('calls mixpanel with correct data when "Publish" button is clicked after creating new plan', async () => {
      renderComponent({
        initialJotaiValues: [
          [currentAdminAtom, ADMIN],
          [actionPlansAtom, [actionPlanWithReminders, activeActionPlan]],
        ],
        apolloMocks: [MOCK_CREATE_ACTION_PLAN_SUCCESS],
        actionPlanFormContainerProps: { ...baseProps, isNewActionPlan: true },
      });

      const nextButton = screen.getByRole('button', {
        name: ACTION_PLAN_FORM_BUTTONS.NEXT,
      });

      userEvent.click(nextButton);

      const publishButton = screen.getByRole('button', {
        name: ACTION_PLAN_FORM_BUTTONS.PUBLISH,
      });

      userEvent.click(publishButton);

      await waitFor(() => {
        expect(mixpanelTrackSpy).toHaveBeenCalledWith(
          MIXPANEL_EVENT_LABELS.PUBLISH_PLAN,
          expect.objectContaining({
            AdminId: ADMIN.id,
            AdminRole: ADMIN.role,
            MemberId: MOCK_USER.id,
            PlanType: actionPlanWithReminders.planType,
            PlanNumber: 3,
            PublishType: MIXPANEL_EVENT_LABELS.PUBLISH_TYPE_NEW_PLAN,
          }),
        );
      });
    });
```

### Config

```json
"transform": {
      "^.+\\.(ts|tsx)$": [
        "@swc/jest",
        {
          "jsc": {
            "transform": {
              "react": {
                "runtime": "automatic"
              }
            }
          }
        }
      ]
    }
```

### SWC Info output

 Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
        CPU: (10 cores)
            Models: Apple M2 Pro

    Binaries:
        Node: 18.17.0
        npm: 9.8.0
        Yarn: 1.22.19
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.3.80
        @swc/helpers: N/A
        @swc/types: 0.1.4
        typescript: 4.7.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The mock function should work properly. Instead what I think the issue is that swc is creating multiple parallel instances which is the key to the fastness compared to ts/jest. But this same thing is creating the issue. In one instance the mock function is called, but it is getting called in the other instance which is why the number of calls received is zero. I expect that mock function should work properly and there must be an accurate number of calls that is received.

### Version

0.2.29

**Comment by kwonoj** [comment]
>  I think the issue is that swc is creating multiple parallel instances

This is clearly not true. 

There are intended behaviors of swc transformation, check exisitng pinned issues / discussions for the jest support and raise to discussion for q/a.

And lastly there's no one able to answer if there's no minimal repro
