### ISSUE TITLE
ERR_UNSUPPORTED_DIR_IMPORT

### ISSUE THREAD

**Issue by ZiiMakc** [swc-project/swc#7898]
### Describe the bug

SWC version 1.79+ omits `/index.js` in imports when compiled, which results in runtime error for this imports:
```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'redacted/modules/ping/gql' is not supported resolving ES modules imported from 'redacted'
```

Probably [this MR](https://github.com/swc-project/swc/pull/7852) is the cause.
Directory imports [are not allowed](https://nodejs.org/api/esm.html#esm_import_statements):
> Mandatory file extensions
>A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes >(e.g. './startup/index.js') must also be fully specified.
>This behavior matches how import behaves in browser environments, assuming a typically configured server.

### Input code

```typescript
typescript:

import { pingIndex } from "../modules/ping/gql/index.js";
```

compiled (swc 1.79):
```
import { pingIndex } from "../modules/ping/gql"; # this is not correct
```

compiled (swc 1.78):
```
import { pingIndex } from "../modules/ping/gql/index.js"; # works as expected
```
```


### Config

```json
{
	"$schema": "https://json.schemastore.org/swcrc",
	"module": {
		"type": "es6",
		"strictMode": true,
		"noInterop": false
	},
	"jsc": {
		"parser": {
			"syntax": "typescript",
			"dynamicImport": true
		},
		"transform": { "legacyDecorator": true, "decoratorMetadata": false },
		"target": "es2022",
		"externalHelpers": true,
		"keepClassNames": true,
		"paths": {
			"@app/*": ["./src/*"]
		},
		"baseUrl": "."
	},
	"sourceMaps": true
}
```

### Playground link

Can't reproduce in playground.

[Reprodution repo](https://github.com/ZiiMakc/swc_err)

### SWC Info output

Some resent npx issue doesn't allow to run this, error:
```
Cannot read properties of undefined (reading 'isStream')
```

### Expected behavior

Compiled code should include `index.js` as it was defined.
```
import { pingIndex } from "../modules/ping/gql/index.js";
```

### Actual behavior

Compiled code omits `index.js`.
```
import { pingIndex } from "../modules/ping/gql";
```

### Version

1.79+

**Comment by kdy1** [comment]
Reopening as fix was reverted. https://github.com/swc-project/swc/pull/7906
