### ISSUE TITLE
Import assertions are blanket converted to import attributes

### ISSUE THREAD

**Issue by PaulSinghDev** [swc-project/swc#7908]
### Describe the bug

When using the `jsc.experiment.keepImportAssertions` flag the SWC compiler simply takes all assertions and outputs the new `with { type: "some-type" }` syntax regardless of what the input was. 

This causes issues with Node being able to run the code and generates a syntax error when trying to run the generated code. As it has been accepted that the `assert` syntax will not be getting removed there is no need to blanket change the syntax as this causes more issues than it solves.

### Input code

```typescript
import packageJSON from "./package.json" assert { type: "json" };
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2022",
    "experimental": { "keepImportAssertions": true }
  },
  "module": {
    "type": "es6"
  },
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.82&code=H4sIAAAAAAAAA8vMLcgvKlEoSEzOTkxP9Qr291NIK8rPVVDS04eK6WUV5%2BcpKSQWF6cCFVaXVBakWikogQVrrbmS8%2FOK83NS9XLy0zWQDNG0BgDW5p%2FHWQAAAA%3D%3D&config=H4sIAAAAAAAAA0VOOw7CMAzdc4rIMwPKwMDGyMAhomKhQNNYtiu1qnL3OrSUze%2FvxXkPb%2Bng6hc7DVBkQT6wMTIPGidjQGdC6TiRwlespy2jkV%2BozYESziHAzuNEyCmj5fvW6OGDSPdMhfUmNqOpDGKK8oi%2Bur0RcnmOPf5%2Fartb%2BwUOU5LHz9birroVVF6is80AAAA%3D

### Expected behavior

The type of assertion is preserved.

### Actual behavior

The assertion is transformed into the newer `with` syntax.

### Version

1.3.82

### Additional context

I have solved this issue for me by downgrading to swc version `1.3.80`. However, I think a more flexible solution is required.

**Comment by kdy1** [comment]
The option should be removed or renamed, I think, but this is not a bug.

**Comment by PaulSinghDev** [comment]
Sorry @kdy1 I wasn't sure what to label it as. I just went for bug as it was causing me issues. 

I figure it shouldn't be too much of a challenge to check whether the dev used `assert` or `with` and then just output the same as the input. 

I have tried changing the target version but it seems as though the compiler just wants to always output code with `with`

**Comment by magic-akari** [comment]
https://github.com/swc-project/swc/blob/766d3e8896f6b134c5429e13cc5d96e90d560a5f/crates/swc_ecma_ast/src/module_decl.rs#L74-L88

During the process of parsing code into an AST, we lose the information required to differentiate whether it represents a "with" statement or an "assert" statement.
The transformation can still be implemented in the WASM plugin, but it require the addition of extra information to the AST.

There are two potential solutions: 
1. Modify the AST to record the current with/assert variant.
2. Assume that the coexistence of both variants is not possible and generate the expected code during code generation based on the selected option.

**Comment by Austaras** [comment]
Seems to me that adding an option to codegen would be the most logical solution.
