### ISSUE TITLE
Avoid IIFEs for static class member definition with `useDefineForClassFields: false`

### ISSUE THREAD

**Issue by bradzacher** [swc-project/swc#7922]
### Describe the bug

I'm trying to understand SWC's output for static class members with `useDefineForClassFields: false`.

```ts
// input
class Foo {
  static x = 1;
}

// output
class Foo {
}
(()=>{
    Foo.x = 1;
})();
```
```ts
// input
class Foo {
  static x = 1;
  static y = 1;
}

// output
class Foo {
}
(()=>{
    Foo.x = 1;
})();
(()=>{
    Foo.y = 1;
})();

```
[playground](https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQrDMBBE0btMncK4VJvgeyzOKCgostjZQIzR3WN3nwf%2FwFsr0oFuLvpV2lvYDwmxd2r10gPjhjB%2FMU6m5mmecIpbU978c11f8cFcGpfN79WkpbA%2BhZStimOMPzSlFQlqAAAA)

Why does SWC use an IIFE to define the static class member?

The reason I ask is because:
a) [this doesn't match TS's output](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oQC5iwS2GgA9oBeaARgG5UBfIA)
b) this causes down-stream problems with other tools (https://github.com/google/closure-compiler/issues/4116)

I tried to investigate via the PR that introduced this output (https://github.com/swc-project/swc/pull/7055) however the PR doesn't include any information about why an IIFE was introduced.

I'm not sure why the extra bytes are generated specifically for class properties. I understand  using them for static blocks - but I don't understand why they're used for class properties.

### Expected behavior

.

### Version

1.3.83

**Comment by magic-akari** [comment]
It's not introduced in #7055 .
It's changed in #7056, check it: https://github.com/swc-project/swc/pull/7056/files

**Comment by magic-akari** [comment]
It's similar to the TypeScript pass. https://github.com/swc-project/swc/blob/0864cfe94eb1ba6c5149657a7b657387ed267532/crates/swc_ecma_transforms_typescript/src/transform.rs#L635-L640

I will fix this soon.

**Comment by bradzacher** [comment]
Thank you so much for fixing this!
This is a big help in us migrating to SWC.
