### ISSUE TITLE
[WRONG] `jsc.experimental.keepImportAssertions` is `experimental`, explicitly

### ISSUE THREAD

**Issue by meabed** [swc-project/swc#7923]
### Describe the bug

The bug is described here: https://github.com/TypeStrong/ts-node/issues/2056

With version 1.3.83, swc renames the experimental configuration option jsc.experimental.keepImportAssertions to jsc.experimental.keepImportAttributes as per https://github.com/swc-project/swc/pull/7914 

### Suggestion to keep other libraries working without so much failure:
- Adding jsc.experimental wrong or non-supported keys shouldn't throw an error ( maybe warning )
- Alias renamed keys to the new keys to it still backward compatible

The error during running ts-node: 
```
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"commonjs","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es2015","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false}},"keepClassNames":false,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `keepImportAssertions`, expected one of `plugins`, `keepImportAttributes`, `emitAssertForImportAttributes`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 396
```

### Expected behavior

The build should be working normally

### Version

1.3.83

**Comment by kdy1** [comment]
keepImportAssertions is **explixitly** marked as an experimental option. Please read docs.

**Comment by meabed** [comment]
@kdy1 I understand its experimental, what is the harm of throwing a warning instead of error?

**Comment by kdy1** [comment]
It gives a good impression to people who don't understand the word `experimental`

**Comment by meabed** [comment]
@kdy1 I understand, although I think warning gives the same impression, error is more obstructive action and not as helpful.

**Comment by cpojer** [comment]
@kdy1 I understand your explanation regarding the option being experimental, yet it appears that `ts-node`, for some reason, chose to make use of this configuration option. By changing this in `swc` in a minor patch you are breaking any user of `ts-node` + `swc`. Users do not have control over a fix until `ts-node` merges this PR: https://github.com/TypeStrong/ts-node/pull/2057/files

I've been advertising for this approach on [my blog](https://cpojer.net/posts/fastest-frontend-tooling-in-2022#ecmascript-modules-in-nodejs) and expect it is quite commonly used. I don't know how long it will take for `ts-node` to publish a new release, but it would be great if you could revert this change until `ts-node` has published an update to their project.

**Comment by dandrei** [comment]
My previously-working `ts-node` installation is now broken after installing the latest `@swc/core` version.

**Comment by josser** [comment]
Anyone can help with the quickfix for this? 
I don't have keepImportAssertions in any configuration files. Is It somewhere in ts-node internals or so?

**Comment by kdy1** [comment]
@josser The fix is already published as `v1.3.84`.

https://github.com/swc-project/swc/blob/f66da772202a6f065488fbabb7e0a9d9a2d7089d/CHANGELOG.md#1384---2023-09-11

**Comment by vluoto** [comment]
> Is It somewhere in ts-node internals or so?

https://github.com/TypeStrong/ts-node/issues/2056

**Comment by cpojer** [comment]
`ts-node` already has the necessary fixes on the `main` branch, we just need a new release.

**Comment by meabed** [comment]
Thank you @kdy1, I really think supporting the community to transition smoothly should be more important than debating this issue resolution, but as you could see the fix may or may not land soon in ts-node, and I know everyone will appreciate your support and flexibility on this issue.

And I want to highlight the same approach in nextjs for example when you configure experimental features and they change or get removed - it shows warning and not error.

<img width="1628" alt="image" src="https://github.com/swc-project/swc/assets/45731/f16c592d-507f-4e9b-a377-26bc054a4f5a">

I think this is good balanced approach in ensuring library users knows what is the issue and not stopping their workflow or stuck in old version because of it.

**Comment by kdy1** [comment]
I added an alias with https://github.com/swc-project/swc/pull/7995

**Comment by kdy1** [comment]
Honestly, I'm really against such PR, but I don't want to think/debate about it

**Comment by meabed** [comment]
Thank you @kdy1 appreciate it.

**Comment by meabed** [comment]
@kdy1 this workflow is stuck in installing node: https://github.com/swc-project/swc/actions/runs/6284619630/job/17066167501

**Comment by meabed** [comment]
Not sure if it's related, but After updating to "@swc/core": "1.3.88"
I get another error with `noInterop`

```
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"es6","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es2015","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false}},"keepClassNames":false,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `noInterop`, expected `resolveFully` at line 1 column 391

```

**Comment by kdy1** [comment]
@meabed https://github.com/swc-project/swc/issues/7963

**Comment by meabed** [comment]
Thanks @kdy1

Curios question is there away to replace ts-node with swc fully with type checking?
