### ISSUE TITLE
unused logger defined by `console.log.bind(null, ...)` is not treeshaked

### ISSUE THREAD

**Issue by B2o5T** [swc-project/swc#7927]
### Describe the bug

client import server utils with `logger`, he is only removed from bundle after adding `/* @__PURE__ */` before `console.log.bind...`

### Input code

```typescript
export const logger = {
  info: console.log.bind(null, '-', 'info'),
}
```

### Expected behavior

tree shake unused logger

### Version

next.js 13.4.19

**Comment by kwonoj** [comment]
>Version: next.js 13.4.19

Are you saying this is next.js behavior? then please create an issue in next.js. If not, please provide swc only repro. If latter, please feel free to create a new issue.

**Comment by B2o5T** [comment]
@kwonoj Yeah but Next.js use swcMinify by default

**Comment by kwonoj** [comment]
That doesn't mean it is actually swc bug or not. Next.js uses swc and then have lot more features for the bundling. Again, if you believe if this is a bug in swc core itself, please provide a repro with swc only.

**Comment by B2o5T** [comment]
@kwonoj ok, I added repro in https://github.com/swc-project/swc/issues/7929

Didn't saw that you have a nice playground with shared link
