### ISSUE TITLE
`emitAssertForImportAttributes` does not emit assert for import attributes

### ISSUE THREAD

**Issue by isaacs** [swc-project/swc#7928]
### Describe the bug

#7914 added an option to emit `assert` for import attributes.

However, it does not do that. It emits `with` for import attributes.

This is even verified [by the tests](https://github.com/swc-project/swc/blob/main/crates/swc/tests/fixture/issues-7xxx/7908/), you can observe the same output in both cases, regardless of whether the `emitAssertForImportAttributes` is set.

As far as I can tell, it does nothing.

### Input code

```typescript
import packageJSON from "./package.json" assert { type: "json" };

console.log(packageJSON)
```

### Config

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "typescript"
        },
        "target": "es2022",
        "experimental": {
            "keepImportAttributes": true,
            "emitAssertForImportAttributes": true
        }
    },
    "module": {
        "type": "es6"
    },
    "isModule": true
}
```

### Expected behavior

Expect `emitAssertForImportAttributes` to emit assert for import attributes.

### Actual behavior

Emits `with` for import attributes, regardless of whether `emitAssertForImportAttributes` is set or not.

### Version

1.3.83

### Additional context

I realize that this is an experimental feature. I am reporting the results of the experiment, that it clearly either does not work as intended, or if the intent of `emitAssertForImportAttributes` to do something other than emit `assert` for import assertions, then that is a very bad name for the flag.

**Comment by kdy1** [comment]
Yeah, I didn't realize that the test is wrong. I was too busy at that times due to a talk I did yesterday. I'm now not too busy, so I will be able to do it correctly. 😄

**Comment by isaacs** [comment]
@kdy1 Fantastic! I'm not too familiar with your normal project timelines, any idea when we might expect it to be moved out of experimental status? It would be nice to have a way for ts-node users to import JSON from es modules, but you'll probably fix the flag long before V8 support `import/with` 😅
