### ISSUE TITLE
Reopen: unused logger defined by console.log.bind(null, ...) is not treeshaked #7927

### ISSUE THREAD

**Issue by dimaMachina** [swc-project/swc#7929]
### Describe the bug

client import server utils with `logger`, he is only removed from bundle after adding `/* @__PURE__ */` before `console.log.bind...`

### Input code

```typescript
export const logger = {
  info: console.log.bind(null, '-', 'info'),
}
```

### Playground link

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA0vOzysuUcjJT09PLVKwVajmUlDIzEvLt1JIBkrk56TqAaX0kjLzUjTySnNydBTUo%2FNSK0qKEmPVNXW4arm4kpH0G6EYoKGpYGuHbIwGQq8OWDOyXmMUvfpaCg7x8QGhQa7x8Qpa%2BsQ5BgCQd36SywAAAA%3D%3D&config=H4sIAAAAAAAAA32US3LbMAyG9zmFR%2Bts20UPkF3PwKFJUKbDh4YAHWsyvnshSrLdGNJOwocfIAEQ32%2BHQ3dG0%2F05fPMn%2Fwy6IJT7P1twTKSvbOnARI2m%2BIG695WecUJOB4Rmus2kI116oKbCX4t7F3JGWN0XW%2FTJu%2FE5oclxKID4ZGMrx6sREuH%2F%2BoWV%2FDUBKvXZfsw5gE47RGlUPhH0UKTAJoegBwR10UWIMp1UF49ZSjHBSmDVUPIg8mQ9%2BZw45yu1oK0y2YKAfAFD%2FgKSjHOxLCFfT7hPwxaOte9bk3%2Bo4aJD1STkhGtrCZ9WiHrKHkm5mqQSznCjBjNcivtT6Z0qQLWkV905%2B7TRk08ArkDQiElHkOI2D8fztKV2u0qfHI8sjQLn%2BZZumaDnoirvnVDZqTJQyEvdLGCrgamyRjrOgjfKh96CAud4VoTQ%2BOXJnKSkNA6QnQC4v9pJUzUDdX%2BFG3x6EDv4g29J8oAtHlHTaZviGI857CSIQKdsdxy4FZS3ceEtcR22eU0WeDTAii4VG3hdAvwAKKvQluXLbPDz4IiqD%2Fn4WBOLw%2B2%2BhKNO%2FeO9z3v4bXHoYra1wWXDT%2F2d9%2FLv7uG0buH1BJ3Hv6uw5bz9A1EN%2Bh8sBgAA

### Expected behavior

tree shake unused logger

### Version

1.3.74

**Comment by kdy1** [comment]
Closing as not planned.
