### ISSUE TITLE
Unused types still not remove when casting value in typescript

### ISSUE THREAD

**Issue by aelbore** [swc-project/swc#793]
**Describe the bug**
Casting value in typescript doesnt remove the types in transform
**Input code**
```typescript
  mockfs({
    'dist': {},
    './types/types.ts': `
      export interface IPerson {
        fName: string
        lName: string
        age: number
      }
    `,
    './src/input.ts': `
      import { IPerson } from '../types/types'

      export function createPerson() {
        const a = {} as IPerson
      }
    `,
  })

  const content = await fs.promises.readFile('./src/input.ts', 'utf-8')

  const { code } = await transform(content, { 
    jsc: {
      parser: {
        syntax: 'typescript',
        decorators: true,
        dynamicImport: true,
        tsx: true
      },
      target: 'es2019'
    }
  })

  /// code output
  // import { IPerson } from '../types/types';
  // export function createPerson() {
  //     const a = {
  //     };
  // }

  /// expected should be 
  // export function createPerson() {
  //     const a = {
  //     };
  // }
```

**Config**
Please see code above

**Expected behavior**
it should remove the import of the types since it is not use in the output code

**Version**
The version of @swc/core: 
1.1.47

**Additional context**

**Comment by kdy1** [comment]
Hmm... I thought I fixed it but it seems like there's a bug.
Sorry for inconvenience.

**Comment by aelbore** [comment]
@kdy1 no worries, the difference of this bug is you only used it as casting the object inside function. other other cases is you use it as parameters.
by the way good work, im currently using swc in my own project as bundler in javascript (zero config)

**Comment by aelbore** [comment]
if you use interface as type parameter it works fine which is you already fixed.
but this bug is i just only use it as casting type inside function.
heres another code for this case 
```typescript
  mockfs({
    'dist': {},
    './types/types.ts': `
      export interface IPerson {
        fName: string
        lName: string
        age: number
      }

      export interface Options {
        person: IPerson | IPerson[]
      }

    `,
    './src/input.ts': `
      import { IPerson, Options } from '../types/types'
      
      export function createPerson(options?: Options) {
        const a = options?.person as IPerson
      }
    `,
  })
```

**Comment by kdy1** [comment]
@aelbore I fixed it. :) Thanks for reporting!

**Comment by aelbore** [comment]
@kdy1 thats so quick. thanks ^^
