### ISSUE TITLE
Added a couple of javascript files as sym links, the project doesn't build.

### ISSUE THREAD

**Issue by shibisuriya** [swc-project/swc#7931]
### Describe the bug

I have a project which uses swc-loader instead of babel-loader in webpack... I sym linked a couple of files that are not present in the project from outside to /src folder... So technically those files can be accessed. But when I start the build... The build fails... 
repo -> https://github.com/shibisuriya/swc-import-bug/tree/main/project/src

common is the folder that has been sym linked... 

### Input code

```typescript
Check this simple webpack based project -> https://github.com/shibisuriya/swc-import-bug/tree/main/project/src
```

### Config

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": true,
            "dynamicImport": false,
            "privateMethod": false,
            "functionBind": false,
            "exportDefaultFrom": false,
            "exportNamespaceFrom": false,
            "decorators": false,
            "decoratorsBeforeExport": false,
            "topLevelAwait": false,
            "importMeta": false
        },
        "transform": null,
        "target": "es5",
        "loose": false,
        "externalHelpers": false,
        // Requires v1.2.50 or upper and requires target to be es2016 or upper.
        "keepClassNames": false
    },
    "minify": false
}
```

### Playground link

https://github.com/shibisuriya/swc-import-bug/tree/main/project/src

### Expected behavior

The project should build.

### Actual behavior

![image](https://github.com/swc-project/swc/assets/69033713/5d86f8ef-76fe-4704-b015-a212f79b5541)

### Version

^1.3.78

### Additional context

I can't move the files physically inside the project... Since I am working with a third party lib that provides some jsx files on a remote machine (smb).

**Comment by kdy1** [comment]
This is not a bug of swc.

https://github.com/shibisuriya/swc-import-bug/blob/336d4c1c41709564e1ab94d04e84ddf8ab79c39a/project/webpack.config.js#L15


`swc-loader` is explicitly disabled for files in `node_modules`

```js
  module: {
    rules: [
      {
        test: /\.(jsx|js)$/,
        exclude: /(node_modules)/,
        use: {
          // `.swcrc` can be used to configure swc
          loader: "swc-loader",
        },
      },
    ],
  },
```

**Comment by shibisuriya** [comment]
But the common folder is not in node_modules.... it's in a folder outside of project and sym LinkedIn inside ./src.
