### ISSUE TITLE
Calling `metadata.get_transform_plugin_config()` crashes SWC

### ISSUE THREAD

**Issue by niieani** [swc-project/swc#7934]
### Describe the bug

I'm developing [an SWC plugin](https://github.com/niieani/promock/blob/main/src/lib.rs). The plugin works, but I wanted to add configuration options.
As soon as I add a call to `metadata.get_transform_plugin_config();` and build, SWC will crash while loading.

```rust
#[plugin_transform]
pub fn process_transform(program: Program, metadata: TransformPluginProgramMetadata) -> Program {
    let v = metadata.get_transform_plugin_config(); // <-- this line is all it takes
    program.fold_with(&mut as_folder(TransformVisitor))
}
```

You can reproduce it with the default code that is generated by executing:

```shell
swc plugin new --target-type wasm32-wasi swc-test
```

And then adding that line to execute `get_transform_plugin_config()`.

### Input code

```typescript
n/a
```

### Config

```json
n/a
```

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Max

    Binaries:
        Node: 20.4.0
        npm: 9.7.2
        Yarn: 4.0.0-rc.50
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.3.83
        @swc/helpers: N/A
        @swc/types: 0.1.4
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

SWC doesn't crash.

### Actual behavior

Crash:

```
    failed to handle: failed to invoke plugin: failed to invoke plugin on 'None'

      Caused by:
          0: failed to invoke `./swc-test/target/wasm32-wasi/release/swc_test.wasm` as js transform plugin at ./swc-test/target/wasm32-wasi/release/swc_test.wasm
          1: RuntimeError: unreachable
      Stack backtrace:
         0: _napi_register_module_v1
         1: _wasmer_vm_imported_memory32_atomic_notify
         2: _napi_register_module_v1
         3: _napi_register_module_v1
         4: _napi_register_module_v1
         5: _napi_register_module_v1
         6: _napi_register_module_v1
         7: _napi_register_module_v1
         8: _napi_register_module_v1
         9: <unknown>
      Stack backtrace:
         0: _napi_register_module_v1
         1: _wasmer_vm_imported_memory32_atomic_notify
         2: <unknown>
```

### Version

0.83.0 (swc_core)

### Additional context

I'm not a Rust developer, this is my first Rust project, so maybe I'm doing something wrong. Please be mindful of that.

**Comment by kwonoj** [comment]
try to disabling LTO first.

**Comment by niieani** [comment]
Hi @kwonoj! I'm sorry, not sure what that means or how to do it :) 
like I mentioned in the issue description, I've never coded in Rust before today.

**Comment by niieani** [comment]
Hi @kwonoj! Thanks. I didn't know what this meant at first (this is my first day coding in Rust), but ChatGPT helped out lol.
It seems that disabling LTO made it work. Does it mean that if we want to use get_transform_plugin_config(), we need to opt out of the optimization? 
Perhaps we could point it out in the documentation. Unless I'm misunderstanding.

**Comment by kwonoj** [comment]
Please refer https://github.com/swc-project/swc/issues/7479
