### ISSUE TITLE
Incorrect module type detection in files with side-effect imports

### ISSUE THREAD

**Issue by SuperOleg39** [swc-project/swc#7940]
### Describe the bug

Hello!

We use [async boundary](https://webpack.js.org/concepts/module-federation/#uncaught-error-shared-module-is-not-available-for-eager-consumption) pattern in our application entry point for correct Module Federation works, and have one-liner entry point with side-effect import - `import('./bootstrap')`

Configuration - SWC parameter `isModule: 'unknown'`

Also, we have a custom SWC plugin with `visit_mut_module` usage.

After switching to SWC transpiler, I noticed that plugin logic from `visit_mut_module` not running for this entry.

Looks like SWC detect that this file is not a ES Module.

### Input code

```typescript
import('./bootstrap')
```

### Config

```json
`isModule: 'unknown'` is used
```

### Playground link

https://play.swc.rs/?version=1.3.27&code=H4sIAAAAAAAAA8vMLcgvKtFQSitW0rTm5eLlSs7PKy5RKEkFErYKicWVeckKGpoKtnYK1bXWAPgg1uMtAAAA&config=H4sIAAAAAAAAA1WPMQ6DMAxFd06BPHdth56gSw8RUYPSBieyjQpC3J0EElq2%2BL%2Bf7%2B%2B5qmt4SwP3eo7POATDgnzMUZGJ1IxRAZ0CSsM2KFwKVUmoNU5wk5adAI6KTMY90AVkiR7lATNUwx1qikS55ixw3guWrKz1lmw7%2FbdpfB8YRc7GZDXUOTx3qXIf6P1r2GC%2BMl2yr7%2FBz1SWHcFg5Vl%2BwkAf8l%2BCalkBb%2BJADDYBAAA%3D

### Expected behavior

SWC parse this input and detect that is ES module

### Version

1.3.62

**Comment by magic-akari** [comment]
FYI, it is valid to use dynamic `import` in CommonJS. Check it: https://nodejs.org/api/modules.html?hightlight=import#enabling

You can add `export {}` to keep the ESM context.

**Comment by SuperOleg39** [comment]
> FYI, it is valid to use dynamic `import` in CommonJS. Check it: https://nodejs.org/api/modules.html?hightlight=import#enabling
> 
> You can add `export {}` to keep the ESM context.

Good point, thanks!

Reasonable enough to close the issue)
