### ISSUE TITLE
Expose jsc.experimental.disableBuiltinTransformsForInternalTesting as a feature

### ISSUE THREAD

**Issue by niieani** [swc-project/swc#7942]
### Describe the feature

It would be great to be able to use SWC with plugin-only configuration. Currently that's possible with the `jsc.experimental.disableBuiltinTransformsForInternalTesting: true` option, but the name suggests that it's supposed to be used only "for internal testing". 
But I see this as a feature, for folks that might want to use SWC for plugin-only transformations.

### Babel plugin or link to the feature description

In Babel this is achievable, because everything is a plugin, including the default transformations.

**Comment by kwonoj** [comment]
The name explicitly clarifies this is for internally evaluating if we'll make it as public feature or not. It'll be an official RFC if we find there'll be the way, otherwise it won't be.
