### ISSUE TITLE
`undefined` is passed for the "context.metadata" field in a decorator metadata

### ISSUE THREAD

**Issue by arklanq** [swc-project/swc#7957]
### Describe the bug

When switching from tsc to swc to transpile TypeScript to JavaScript code I have noticed that `context.metadata` argument for decorators becomes undefined.

More context:
* I am trying to replace tsc with swc for faster source code transpilation in a relatively modern Node.js app.
* I am using '2022-03' decorators ("stage 3 decorators"), see swc config below.
* I am using the latest version of TypeScript (5.2+).
* I am using SWC within Rollup bundler, thanks to [rollup-plugin-swc3](https://www.npmjs.com/package/rollup-plugin-swc3) package.
* I have polyfilled decorator-metadata feature for my node.js with `core-js/proposals/decorator-metadata-v2.js`.

### Input code

```typescript
type ClassTarget = abstract new (...args: unknown[]) => unknown;

function inject<Class extends ClassTarget>(
  target: Class,
  context: ClassDecoratorContext<Class>
): void {
  console.debug(context.metadata); // undefined
}

@inject
class App {

  foo() {
    return 'bar';
  }

}

const app = new App()
app.foo();
```

### Config

```js
const config = {
    // --- Plugin options
    include: /\.ts$/,
    exclude: /node_modules/,
    tsconfig: 'tsconfig.json',
    // --- SWC options
    env: {
      targets: 'node >= 18.14',
      // 'entry' mode imports too much polyfills
      // 'usage' mode doesn't work as expected
      mode: undefined,
      coreJs: coreJsPackageManifest.version,
      dynamicImport: true,
    },
    jsc: {
      parser: {
        syntax: 'typescript',
        tsx: false,
        decorators: true,
        dynamicImport: true,
      },
      transform: {
        // Stage 3 decorators
        decoratorVersion: '2022-03',
      },
      externalHelpers: true,
      keepClassNames: true,
      // Use `env` option instead
      target: null,
    },
    minify: PRODUCTION_BUILD,
    sourceMaps: true,
  }
```

### Playground link

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA02QwU7EIBCG7zzF3BYSw95b22jWR%2FBm9jCF6aa6Dg1MdzXGd3eENTHhwPzwffxBPleCwxlLecZ8IoEBcCqSMQgwXcF67%2FWgdLDxG6crvxwdDOPf1BszbxxkSQwLv1KQ%2ByoD%2BhDiWP6rR2sApG67lt9pEBKLXr4lTxRSRkn50OJmG43r4JKWCF%2BNKOlMPtK0neyN9%2B8kGFHQ9bDfa71I88IUzbcxD62ZCbXZ47qqRj1zStZVI0Am2TLDbsK86zVRStfvSwKowFA%2FQ1HrjM6%2Bsr35AYrFObg%2BAQAA&config=H4sIAAAAAAAAA22QPQ%2BCQAyGd3%2FFpbMaQQdjoouLLo7uDRSDwt2lrQZC%2BO8efiAap7bv0%2B9mZAycJYGVaYIbAo8sxH0cFKmtYhUU0NqTJJx7hfGbqnQow0Ko11JKHKM6loCUrwNSWyzzZF96x%2FoF26cBZbSSOS6HK%2FQNj8SSO9stE8%2FieDKbw3c5VUpssdhR4elnPlyI%2FLZAkQOWNGSPaiB7%2B%2FxBkU%2BkXRJYl5LZrE20nEaL17y%2Fl3SdRu0dcYStD1QBAAA%3D

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
        CPU: (8 cores)
            Models: Apple M1

    Binaries:
        Node: 18.17.0
        npm: 9.8.1
        Yarn: 1.22.19
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.3.82
        @swc/helpers: 0.5.1
        @swc/types: 0.1.4
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

With tsc:

```
function someDecorator(...) {
  console.log(context.metadata) // [Object: null prototype] {}
}
```

### Actual behavior

With swc:

```
function someDecorator(...) {
  console.log(context.metadata) // undefined
}
```

### Version

1.3.82

### Additional context

Maybe this could be helpful:
https://github.com/microsoft/TypeScript/issues/55453

**Comment by arklanq** [comment]
I have investigated the issue a bit more and found out that the decorators' metadata doesn't work at all. 
Metadata is not saved after modifications are made in decorator body, have a look at an example below:

```tsc
type ClassTarget = abstract new (...args: unknown[]) => unknown;

function inject<Class extends ClassTarget>(
  target: Class,
  context: ClassDecoratorContext<Class>
): void {
  context.metadata = Object.create(null); // Manually initializing metadata object, the same way tsc does
  context.metadata.foo = 'bar'; // Seeding example data
}

@inject
class App { }
```

```tsc
// tsc
console.debug(App[Symbol.metadata]); // [Object: null prototype] { "foo": "bar" }
```

```tsc
// swc
console.debug(App[Symbol.metadata]); // null
```

**Comment by kdy1** [comment]
I think your repro isn't working.

https://play.swc.rs/?version=1.3.85&code=H4sIAAAAAAAAA02QwU7EIBCG7zzF3BYSw95b22jWR%2FBm9jCF6aa6Dg1MdzXGd3eENTHhwPzwffxBPleCwxlLecZ8IoEBcCqSMQgwXcF67%2FWgdLDxG6crvxwdDOPf1BszbxxkSQwLv1KQ%2ByoD%2BhDiWP6rR2sApG67lt9pEBKLXr4lTxRSRkn50OJmG43r4JKWCF%2BNKOlMPtK0neyN9%2B8kGFHQ9bDfa71I88IUzbcxD62ZCbXZ47qqRj1zStZVI0Am2TLDbsK86zVRStfvSwKowFA%2FQ1HrjM6%2Bsr35AYrFObg%2BAQAA&config=H4sIAAAAAAAAA22QsQ6CQAyGd5%2Fi0lmNoIMx0cVFF0f3BopB4e7SVgMhvLsHKmLidO3%2FXdu%2FbSbGwFUS2JgmhCHxyEI85EGR2ipWQQGtPUnCuVeYfqhKhzIshAYtpcQxqmMJSPk%2BIrXFMk%2BOpXesP7B9PaCMVjLH5djC0PBMLLmznZl4EcezxRJ%2By6lSYovFgQpP%2FfyRNbgR%2BX2BIicsaWyuLweyj%2B8hFPlC2n0C61Iyu62J1vNo9R74d5Wu06R9AlfYLbtVAQAA

**Comment by arklanq** [comment]
> I think swc is emitting the expected output for your repro.
> 
> https://play.swc.rs/?version=1.3.85&code=H4sIAAAAAAAAA02QwU7EIBCG7zzF3BYSw95b22jWR%2FBm9jCF6aa6Dg1MdzXGd3eENTHhwPzwffxBPleCwxlLecZ8IoEBcCqSMQgwXcF67%2FWgdLDxG6crvxwdDOPf1BszbxxkSQwLv1KQ%2ByoD%2BhDiWP6rR2sApG67lt9pEBKLXr4lTxRSRkn50OJmG43r4JKWCF%2BNKOlMPtK0neyN9%2B8kGFHQ9bDfa71I88IUzbcxD62ZCbXZ47qqRj1zStZVI0Am2TLDbsK86zVRStfvSwKowFA%2FQ1HrjM6%2Bsr35AYrFObg%2BAQAA&config=H4sIAAAAAAAAA22QsQ6CQAyGd5%2Fi0lmNoIMx0cVFF0f3BopB4e7SVgMhvLsHKmLidO3%2FXdu%2FbSbGwFUS2JgmhCHxyEI85EGR2ipWQQGtPUnCuVeYfqhKhzIshAYtpcQxqmMJSPk%2BIrXFMk%2BOpXesP7B9PaCMVjLH5djC0PBMLLmznZl4EcezxRJ%2By6lSYovFgQpP%2FfyRNbgR%2BX2BIicsaWyuLweyj%2B8hFPlC2n0C61Iyu62J1vNo9R74d5Wu06R9AlfYLbtVAQAA

Mmm... it does not for me. I have copy-pasted the code from output to a plain javascript file and when executed with Node.js got the same results. Still `context.metadata` remains undefined.

PS: I have also upgraded all related dependencies so all the tests I run are based on the latest versions of `@swc/*`.

```
-  "@swc/cli": "^0.1.62",
-  "@swc/core": "^1.3.82",
-  "@swc/helpers": "^0.5.1",
+  "@swc/cli": "^0.1.62",
+  "@swc/core": "^1.3.85",
+  "@swc/helpers": "^0.5.2",
```

**Comment by kdy1** [comment]
If so, please provide a minimal reproduction with the swc playground

**Comment by kdy1** [comment]
Your code does **not** produce `undefined`.

![Uploading image.png…]()


What browser do you use?

**Comment by arklanq** [comment]
@kdy1 Ahh, you don't see the output, as I am using `console.debug` which is unsupported in a browser environment.

Let me start from scratch with (this time) valid and a bit more descriptive reproduction:

### Issue reproduction / Github
https://github.com/arklanq/swc-issue-7957-reproduction

### Issue reproduction / CodeSandbox
https://codesandbox.io/p/sandbox/crazy-mopsa-n9tgzv?welcome=true

### Issue reproduction / SWC Playground
[I cannot create valid issue reproduction on SWC Playground, because I need to import](https://play.swc.rs/?version=1.3.85&code=H4sIAAAAAAAAA31TTW%2FaQBS8%2B1c8cTFOzVrNEQpqRS%2BtqqQSkXqIIrG2H7B02XX3A0oR%2F73PXuwEQnJBZvx2dmbeWGwqbRzEhTY4WNusMrrSlkublUgYd9oMNuh4yR0fbG%2FZ2sajKHL7CmEqubUP3CzRwRh4bp3hhQOFO%2BgzxuiFHYJXv5XeqcenBMaT9h8xLLwqnNAKhFpj4T41ZIB%2FHarSvqSe9CMA1zwOA54SUGjlaPiEfG2lTgMc2CZRMoStFiUc6ER2Qz9wA9%2Bs9QhKs48wgPmJh7UW54B%2FPLmH2KsSF0JhGZNE6MKAVrhlgW%2F2awrau8o7W6d4Tke5PPOE%2BYfZ%2B%2FOHYxjMgkurJTKpl%2F1rszF8gO%2Bz%2BztG0Qu1FIt9%2F3IqSUaQZc8qUrAr7WUJOUZ1Khn8QBdbcCtUsOGKzMs9ORZOcCn%2B4bWIdF6vjE7fNw8sUP%2Bk5qBxnYQU4vZInDYrANhy6XHYnisMcod95aVM0uY9Kr9Bw3NJQ854DCgRLsTSv8J3Rrhz7JiMTq5mtCsEq0nCiqKpd0gWoQuv83Bpjy20rqPNuaGmH6Poc2hoVDQN%2FVJV5IXguk8v2nRLbbrT4S76CkKM1FkLlm%2BxvLw%2FBdxiDWm%2FXMGOlNZ6S5gfenR%2Fb9yj63vHeXusqx%2BLLitHgh5n%2B02uZWfhifTXocbRZd%2FeGG46R40769sbs1c6d20yqTfxH%2BylQrddBAAA&config=H4sIAAAAAAAAA22QPQ%2BCQAyGd3%2FFpbMaQQdjoouLLo7uDRSDwt2lrQZC%2BO8efiAap7bv0%2B9mZAycJYGVaYIbAo8sxH0cFKmtYhUU0NqTJJx7hfGbqnQow0Ko11JKHKM6loCUrwNSWyzzZF96x%2FoF26cBZbSSOS6HK%2FQNj8SSO9stE8%2FieDKbw3c5VUpssdhR4elnPlyI%2FLZAkQOWNGSPaiB7%2B%2FxBkU%2BkXRJYl5LZrE20nEaL17y%2Fl3SdRu0dcYStD1QBAAA%3D)

**Comment by arklanq** [comment]
@kdy1 This is a fairly new feature that was introduced recently in TypeScript 5.2, so maybe Babel team is not rushing to implement it now. Anyway, it is a stage 3 proposal so we can be almost sure the feature will land soon in ECMA standard so we should not ignore it.

Some reference:
* [TS 5.2 changelog](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#decorator-metadata)
* [Decorator metadata proposal](https://github.com/tc39/proposal-decorator-metadata)

**Comment by arklanq** [comment]
Sure, I'll keep an eye on the issue then.
