### ISSUE TITLE
TypeScript identifier resolver incorrectly handles block scopes

### ISSUE THREAD

**Issue by eandre** [swc-project/swc#7967]
### Describe the bug

I'm using `swc_ecma_transforms_base::resolver` to determine which declaration a given identifier refers to.

I'm defining multiple TypeScript interfaces with the same name, each within its own block (using a top-level BlockStmt). However, `swc_ecma_transforms_base::resolver` maps them to the same `swc_ecma_ast::Id`. See example below

### Input code

TypeScript:
```typescript
{
    interface Foo {}
}

{
    interface Foo {}
}
```

Rust:
```rust
    let globals = Globals::new();
    GLOBALS.set(&globals, || {
        let lexer = Lexer::new(
            Syntax::Typescript(Default::default()),
            EsVersion::Es2022,
            StringInput::from(file.as_ref()),
            None,
        );
        let mut parser = Parser::new_from(lexer);
        let ast = parser.parse_module().unwrap();

        let mut resolver = swc_ecma_transforms_base::resolver(Mark::new(), Mark::new(), true);
        let ast = ast.fold_with(&mut resolver);

        // Here I expect the two separate `Foo` idents to have different ids,
        // since they're in different blocks.
    });
```

### Config

Using the Rust library.

### Playground link

View the AST tab:
https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA6vmUgCCzLyS1KK0xORUBbf8fIXqWq5aLq5qHDIAgwgOgDIAAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D

### Expected behavior

I expect the two `Identifier` AST nodes inside the `TsInterfaceDeclaration` nodes to have different `ctxt` values inside their spans.

### Actual behavior

The two `Identifier` nodes have the same `ctxt` value `2`, which means they get mapped to the same `swc_ecma_ast::Id` even though they're different types.

### Version

1.3.85

**Comment by kdy1** [comment]
I think those are same

**Comment by eandre** [comment]
What do you mean? Interface definitions are block-scoped. For example:

foo.ts:
```typescript
{
  interface Foo {}
}

typeof Foo;
```

```shell
$ tsc --noEmit foo.ts
foo.ts:5:8 - error TS2304: Cannot find name 'Foo'.

5 typeof Foo;
         ~~~
Found 1 error in foo.ts:5
```

**Comment by eandre** [comment]
Ping @kdy1, I'm very confused why this was closed. Can you elaborate on my questions above? I'm happy to contribute the change if you agree with my reasoning.

**Comment by 0f-0b** [comment]
This also affects `using` declarations ([playground](https://play.swc.rs/?version=1.3.98-nightly-20231113.1&code=H4sIAAAAAAAAA6tWKC3OzEtXSMvPV7BVyCvNyVGo5arGJggAkY%2Fs%2FioAAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYygZyCxKLi1CI4HyhSXJlXklgBFFEqqSxILU4uyiwoUQJL1upA9JQkFqWnloBUpBYbGRgZgWTBckqZxb75KaU5qUC5kqLSVK5aAM10JExxAAAA)).

```ts
{ using foo = null }
{ using foo = null }
```
