### ISSUE TITLE
Inlining single-use functions doesn't respect `reduce_funcs` option

### ISSUE THREAD

**Issue by stevenlele** [swc-project/swc#7973]
### Describe the bug

When `jsc.minify.compress.reduce_funcs` is set to `false`, swc still inlines single-use functions because it doesn't check this option.

In fact, I don't think you should be using `||` in the `if` condition. It will make this feature impossible to turn off.

https://github.com/swc-project/swc/blob/1c89e815445e59f0472f355b63e14664ab4e1d91/crates/swc_ecma_minifier/src/compress/optimize/inline.rs#L672-L681

Terser's documentation: https://terser.org/docs/options/#compress-options

Terser's implementation: https://github.com/terser/terser/blob/7612ca2f855efb6dc2ea406fb43190fa421e250b/lib/compress/inline.js#L184-L189

### Input code

```typescript
function foo() {
  function bar() {
    console.log("bar")
  }
  console.log("foo")
  bar()
}
```

### Playground link

https://play.swc.rs/?version=1.3.85&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9fQVKjmUlBIgwklJRZBhRQUkvPzivNzUvVy8tM1lIASSppA4VouNAmgIWAJsE6uWgAkzYVVXQAAAA%3D%3D&config=H4sIAAAAAAAAA12PMQ7DIAxFd06BPHdth96hZ6gQMRURBGRD1SjK3UNIaNIuCL%2F%2FbX9PQkroWcNdTuVbiqiIkb51ITwOSX0KAdResSYbE1ya2vMqGeUYK5o3BZKiF6baxdfdDi4ExmbfmbeDNeN5oQ4%2BEjKfWKGEXdb4NHnQ%2FDti2xeiwze6f2kW7a3JwIcuOzzuTWPELeUNDlPLlCjXSWD50RpXJmaxAECXTGg7AQAA

### Expected behavior

Single-use functions should not be inlined.

### Version

1.3.85

**Comment by kdy1** [comment]
A test case from `terser`:

Input:
https://github.com/swc-project/swc/blob/49b3c2715c3b418d982443f47e2c70e6959fd16f/crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_t161_top_retain_1/input.js#L1-L7

Config: (in test case, `reduce_funcs` is false by default)

https://github.com/swc-project/swc/blob/49b3c2715c3b418d982443f47e2c70e6959fd16f/crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_t161_top_retain_1/config.json#L1-L5

terser output:
https://github.com/swc-project/swc/blob/49b3c2715c3b418d982443f47e2c70e6959fd16f/crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_t161_top_retain_1/output.terser.js#L1-L9
