### ISSUE TITLE
jsc.transform.react.pragma doesn't work

### ISSUE THREAD

**Issue by luveti** [swc-project/swc#798]
**Describe the bug**
Setting `jsc.transform.react.pragma` doesn't override the default of `React.createElement`

**Input code**
```js
const test = () => {
	return <div>Hello world!</div>
};
```

**Output code**
```js
'use strict';
var test = function() {
    return React.createElement('div', null, 'Hello world!');
};
```

**Config**
```json
{
	"test": "test.js",
	"module": {
		"type": "commonjs"
	},
	"jsc": {
		"target": "es3",
		"transform": {
			"react": {
				"pragma": "redom.el"
			}
		},
		"parser": {
			"syntax": "ecmascript",
			"jsx": true
		}
	}
}
```

**Expected behavior**
It should use the provided `pragma` value.

**Version**
The version of @swc/core: 1.1.48

**Additional context**
The following command was used:
`swc --out-file test.compiled.js test.js`

**Comment by kdy1** [comment]
You have to remove `"test": "test.js",`
