### ISSUE TITLE
Add config.jsc.assumptions JS API

### ISSUE THREAD

**Issue by GeorgeZhangZHY** [swc-project/swc#7988]
### Describe the feature

since assumptions are already implemented #3215, there are cases where we need to fine tune assumptions rather than set loose to true/false. e.g. In my case, I need to set `iterableIsArray: false` while keeping `loose: true`

### Babel plugin or link to the feature description

https://babeljs.io/docs/assumptions

**Comment by kdy1** [comment]
It already exists.
https://github.com/swc-project/swc/blob/276be28ae132758d4584f81a4c9d857f2725ae4c/crates/swc/src/config/mod.rs#L1425

**Comment by GeorgeZhangZHY** [comment]
https://swc.rs/docs/configuration/compilation 
I checked again, there's no such config api both on the website and latest @swc/types package

**Comment by kdy1** [comment]
It's simply not documented

**Comment by GeorgeZhangZHY** [comment]
passing assumptions to config to result in an error 
https://play.swc.rs/?version=1.3.88&code=H4sIAAAAAAAAA1NQUFBIzs8rLlFIVLBVyEstV%2FBNLNDQtOZSgEskASWijXQU9PT0EmOtAfM3nyYxAAAA&config=H4sIAAAAAAAAA21Qu27DMAzc8xWG5s4duhUJgnbIR7DyOVCgF0gaiBH43ys7luM03cg73vHI265pzEWs%2BWhupSxNJhbw2hdEhqh0LYjRIUMsu6zmrbIqE9WRF6xYC5uYNLEUSrnHTIx33ihTlC5x2C7xOJMdDlW46F4dT1BqSenvQC84oHMRx8R7TyJHB99KjfYUILjoumG73aaQGSIvlwSKZ49%2FXXBVcCT%2FBZ%2BxXrqQPiXBBppFJqS2n92WX0%2F%2FnP4KeTePoZpuTWKcnKqyGppyYh%2ByuhTlYehKJPrx%2BJZPZnoyGXfjL0lXRwLtAQAA

**Comment by kdy1** [comment]
It should be `jsc.assumptions`

**Comment by GeorgeZhangZHY** [comment]
setting iterableIsArray did not change the result
https://play.swc.rs/?version=1.3.88&code=H4sIAAAAAAAAA1NQUFBIzs8rLlFIVLBVyEstV%2FBNLNDQtOZSgEskASWijXQU9PT0EvXKEnNKU4s1NGOtAWMCyHo6AAAA&config=H4sIAAAAAAAAA21Ru27DMAzc8xWG5q7t0K1oELRDPoKxz4YKvUDSQIQg%2F17ZsQy76SbxHjziboemMT%2FSmvfmVp7lk4gFvP7LRHJQupaJ0ZwgLduk5qWiKhPUkxOssw5tZNLIUiDlETNwf%2BBGmYL0kf12icNAbT5W4aJ7djxDqSOlv4RRcERvA06RPx2JnCxcJzXaLoC3wfZ5u72NPjFEni7xFAaHf11wVXAg9wWXsF66gCXA6JPaGGS7xxYJXRy%2B5YOZ8k5TfV2Mgn0Qo8QDdKoA8moOC9n42I1zuqW7qZ8H6W1DqteuhsbKuSrndu6%2FEVamNQcCAAA%3D

**Comment by kdy1** [comment]
Then, plese file an issue. Someone may fix it.
