### ISSUE TITLE
Compilation error since @swc/core 1.3.79 on Nest.js projects

### ISSUE THREAD

**Issue by Akaryatrh** [swc-project/swc#7990]
### Describe the bug

When updating from `@swc/core` from version `1.3.78` to `1.3.79` (and any version above), compilation fails with a brand new Nest.js project using `swc` as compiler and type-checker (configured inside `nest-cli.json` file).
The issue can be seen here: https://codesandbox.io/p/sandbox/dawn-hill-9858zs?file=/package.json:34,5-34,28 (but also encountered on my local machine)

**Steps to reproduce:**
- open a new terminal
- run `npm start`
- see that compilation fails with `Error: Cannot find module 'src/app.module'`
- modify `"@swc/core": "^1.3.87"` to `"@swc/core": "1.3.78"` (no caret) inside `package.json`
- run `npm i && npm start`
- see that it compiles successfully

### SWC Info output

Output from CodeSandBox terminal
```
    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
        CPU: (2 cores)
            Models: AMD EPYC

    Binaries:
        Node: 20.5.1
        npm: 9.8.0
        Yarn: 1.22.19
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.3.87
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A
```

### Expected behavior

Compilation should run successfully

### Actual behavior

Currently, the compilation fails with the following error:
```
Error: Cannot find module 'src/app.module'
Require stack:
- /workspace/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/workspace/dist/main.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

### Version

Since @swc/core@1.3.79

**Comment by kdy1** [comment]
Closing as this is not about the latest version

**Comment by chavychaze** [comment]
it's also in the `1.3.88`. Same issue

**Comment by Akaryatrh** [comment]
> it's also in the `1.3.88`. Same issue

Commit https://github.com/swc-project/swc/commit/f374ad903a066ebf3a7e54a3656cb3fc44b37445 is not part of any release yet.

**Comment by chavychaze** [comment]
> > it's also in the `1.3.88`. Same issue
> 
> Commit [f374ad9](https://github.com/swc-project/swc/commit/f374ad903a066ebf3a7e54a3656cb3fc44b37445) is not part of any release yet.

thanks, then will be waiting for version `1.3.89`

**Comment by chavychaze** [comment]
still the same error - `Error: Cannot find module 'src/app.module'`, setting manually `NODE_PATH` not helping, btw

**Comment by kdy1** [comment]
If so please file a new issue with  a minimal reproduction

**Comment by chavychaze** [comment]
sorry, my bad forgot to re-build a container. Thank you!!!

**Comment by bigjoevtrj** [comment]
1.3.90 and this issue still opens

**Comment by kdy1** [comment]
@bigjoevtrj If so, please file a new issue with a minimal reproduction
