### ISSUE TITLE
Uninitialized class property is defined with value "void 0" in es2015

### ISSUE THREAD

**Issue by smvv** [swc-project/swc#8000]
### Describe the bug

When transpiling to `es2015`, swc initializes an uninitialized class property to `undefined`:
```js
// [...]
class Base {
    constructor(){
        _define_property(this, "data", 1);
    }
}
export class Foo extends Base {
    constructor(...args){
        super(...args);
        _define_property(this, "data", void 0);
    }
}
```

When `es2022` is used, it does not initialize the property:
```js
class Base {
    data = 1;
}
export class Foo extends Base {
    data;
}
```

Similarly, [tsc](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQ1oBMwBcwC5oA7AVwFsAjBAJ2gF5oBGVAX1VVEhgDEB7X6AgAeOBEUwx4EJGgwZseAISFSlGq3bBeRCLxAIAdCF4BzABRmiCAO7Q+vMwEpHBhWEdA) and [esbuild](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImNsYXNzIEJhc2Uge1xuICBkYXRhOiBudW1iZXIgPSAxXG59XG5cbmV4cG9ydCBjbGFzcyBGb28gZXh0ZW5kcyBCYXNlIHtcbiAgICBkYXRhITogbnVtYmVyXG59In1dLFsiZXNidWlsZC5jb25maWcuanNvbiIseyJjb250ZW50Ijoie1xuICBcImZvcm1hdFwiOiBcImVzbVwiLFxuICBcImNkblVybFwiOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2XCJcbn0ifV1d) skip the initialization.

### Input code

```typescript
class Base {
  data: number = 1
}

export class Foo extends Base {
    data!: number
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.87&code=H4sIAAAAAAAAA0vOSSwuVnBKLE5VqOZSUEhJLEm0UsgrzU1KLVKwVTDkquXiSq0oyC8qUUgGq3TLz1dIrShJzUtB0gXRpwjTyFULABjS7aVWAAAA&config=H4sIAAAAAAAAA1VPSQ7CMAy85xWRzxwACQ78gUdEwa2Csil2JaKqfydpk0Jv9iye8SykhDdpeMi5jGWJKhGmfS8IZc%2FqUxDgHJF0MpHh1FmmSg3KEq7QsjHAKo3I1YV0PV9uzQE2BMLuaJgz3gz5P1MHFxMSHYVVqvxo8ZgoWiq48JpWsv1S%2B24N7vAT9bD9MBh6dienCcXyBbnuEC8XAQAA

### Expected behavior

Skip the initialization of uninitialized class properties when target is `es2015`-`2021` output.

It's not initializing to `undefined` when target is `es2022`.

### Actual behavior

By setting the uninitialized property's value to `undefined`, it overrides the property value set in the base class.

### Version

1.3.87

### Additional context

Related issue: https://github.com/swc-project/swc/issues/3232

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/7435

**Comment by magic-akari** [comment]
You can run this code in modern browsers with native class support.
You will get `undefined`.

```JavaScript
class Base {
    data = 1;
}
class Foo extends Base {
    data;
}

console.log(new Foo().data); // undefined
```

TypeScript support class field syntax before it is standardized.
And TypeScript's class field has different semantics with native class field.

This is why `useDefineForClassFields` exists.
When target is set to `es2022` or higher, TypeScript will use native class field semantics.

But you should not rely on the behavior of target default value.
You should always set `useDefineForClassFields` to `true` or `false` explicitly.
Once it works in TypeScript, it will work in swc.
