### ISSUE TITLE
v1.3.89 causes "ReferenceError: theme is not defined" in Antd design

### ISSUE THREAD

**Issue by Kamahl19** [swc-project/swc#8007]
### Describe the bug

I have upgraded [vite-plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) to latest which uses latest swc 1.3.89. When trying to import `theme` from Antd design https://github.com/Kamahl19/react-starter/blob/main/src/common/styleUtils.ts#L3 it throws `ReferenceError: theme is not defined`. When I use override to use v1.3.88, it works. Is the issue caused by SWC, vite plugin or is there a problem in Antd exports? Since this is the patch upgrade, shouldnt it be backward compatible? Thanks! 

### Expected behavior

Should import same as in 1.3.88

### Actual behavior

Throws ReferenceError: theme is not defined

### Version

1.3.89

**Comment by kdy1** [comment]
@magic-akari Can you take a look?

**Comment by magic-akari** [comment]
investigating:

```
export const createStyles = <
  T extends Record<string, SerializedStyles | ((theme: Theme) => SerializedStyles)>,
>(
  arg: T,
) => arg;
```

The `theme` is incorrectly removed due to this reference.
