### ISSUE TITLE
Unable to use .jsx files which are inside node_modules using swc loader.

### ISSUE THREAD

**Issue by shibisuriya** [swc-project/swc#8019]
### Describe the bug

I have a bunch of .jsx files inside a npm package, I am trying to use them using webpack swc-loader, by using this configuration,

    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: (modulePath) => {
          if (/node_modules/.test(modulePath)) {
            if (/\/@kissflow\/common-main\//.test(modulePath)) {
              return false;
            } else {
              return true;
            }
          } else {
            return false;
          }
        },
        use: {
          loader: "swc-loader",
        },
      },
      {
        test: /\.css$/i,
        use: ["style-loader", "css-loader"],
      },
    ],
    
 But swc doesn't understand that the jsx files inside of @kissflow/common-main package needs to be transpiled... It throws error... 

### SWC Info output

![image](https://github.com/swc-project/swc/assets/69033713/0272ae66-65bf-4a95-bad8-2592c4c21bba)

### Expected behavior

I should be able to use jsx files that are present inside node_modules if I want to... 

### Version

    "@swc/core": "^1.3.78",     "swc-loader": "^0.2.3",

**Comment by shibisuriya** [comment]
I do understand that the jsx files inside of node_modules should be transpile by swc or babel before distrubution... But this is a bug on the loader itself...

**Comment by kdy1** [comment]
Your config is wrong
