### ISSUE TITLE
ts_decorate helpers gets inlined before import statements

### ISSUE THREAD

**Issue by Havunen** [swc-project/swc#8041]
### Describe the bug

```
import swcCore from '@swc/core';

const res = swcCore.transformSync(scriptContent, {
  // Some options cannot be specified in .swcrc
  filename: filePath + (scriptLang === 'tsx' ? '.tsx' : ''),
  sourceMaps: true,
  // Input files are treated as module by default.
  isModule: true,
  module: {
    type: 'es6'
  },
  // All options below can be configured via .swcrc
  jsc: {
    parser: {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    transform: {},
    loose: true
  },
})

return res

```

### Input code

```typescript
import Vue from 'vue'
import Dropdown from '@/template/views/eNotice/components/Dropdown.vue'
import TextArea from '@/template/views/eNotice/components/TextArea.vue'

@Component<Requirements>({
  components: {
    TextArea,
    Dropdown
  },
})
export default class Requirements extends Vue {
}
```

### SWC Info output

function _ts_decorate(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for(var i = decorators.length - 1; i >= 0; i--)if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
}
import Vue from 'vue'
import Dropdown from '@/template/views/eNotice/components/Dropdown.vue'
import TextArea from '@/template/views/eNotice/components/TextArea.vue'

export { Requirements as default };

### Expected behavior

function _ts_decorate(decorators, target, key, desc) { }  helper should be placed after import statements

### Actual behavior

function _ts_decorate(decorators, target, key, desc) { } method is placed above import statements which causes invalid output

### Version

1.3.90

**Comment by kdy1** [comment]
ESM imports are hoisted anyway

**Comment by Havunen** [comment]
> ESM imports are hoisted anyway

I am transpiling vue templates to be used in jest native ESM runner and the code does not execute. Where this hoisting process is supposed to happen?

**Comment by Havunen** [comment]
Or is it so that `swcCore.transformSync` does not hoist imports?

**Comment by Havunen** [comment]
Ah you are right the problem is something else
