### ISSUE TITLE
Default exported class with decorators are not transformed correctly

### ISSUE THREAD

**Issue by alekitto** [swc-project/swc#8049]
### Describe the bug

Decorators 2022-03 proposal transformer does not transform decorators on default-exported classes

### Input code

```typescript
export default @dec class {}
```

### Expected behavior

Valid transformed code is emitted

### Actual behavior

Decorator is ignored and not transformed.

### Version

main

### Additional context

A couple of tests are present in the `swc_ecma_transforms_proposal` crate to ensure the correct behaviour is respected, but they are not executed in the test suite as the glob does not include the `.mjs` files

**Comment by kdy1** [comment]
It seems like it's transpiled.

https://play.swc.rs/?version=1.3.91&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUXBISU1WSM5JLC5WqK7l5QIAoKijER4AAAA%3D&config=H4sIAAAAAAAAA02Luw6DMAxFd74i8sxQZezanX%2Bw0kuVlkBku1IR4t%2Bx0oe6%2BZ7js3Uh0F0TncPmp4%2FKopDfdqLrbPxyQkiFNUmuRv3XXpEWYVtE%2FcPkiSb2tydjucFaq%2FEU46ejB1AvE6sOXPBXto5KnvO4Oh15UnT7AYHPKMymAAAA

What's the problem? Can you describe it more?

**Comment by kdy1** [comment]
Ah nevermind I didn't set version.

https://play.swc.rs/?version=1.3.91&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUXBISU1WSM5JLC5WqK7l5QIAoKijER4AAAA%3D&config=H4sIAAAAAAAAA01OuQ7CMAzd8xWRZ5CqsLGyM7JbwUGB5pAdJKqq%2F970SMXmd3tUWsNbLFz1WM8KMrIQH7gyMsSCv8oA2YBi2ecCp6Y%2BySbGkliqo%2FCXVmHadCjILyprVkxnzJ6DD1G%2B9Shyx0At2TKMUVzi8P%2FEMfMgFp%2FiUrkUnrsLbItqX4Xgo3dDNTjshdQ0A0OgCkHkAAAA

**Comment by alekitto** [comment]
Wow! Super-quick!
Thanks @kdy1
