### ISSUE TITLE
A bit pissed about https://github.com/swc-project/swc/issues/8058

### ISSUE THREAD

**Issue by DNA-PC** [swc-project/swc#8059]
### Describe the feature

https://github.com/swc-project/swc/issues/8058

Wait, I spend 20mn doing all of that and you close the issue automatically when I did provide the link given [here](https://play.swc.rs/?version=1.3.91&code=H4sIAAAAAAAAA81WbW%2FiRhD%2Bzq%2BYRpVsp2RJ21M%2FgO4QzZto0xAVUukURWSxB%2FDFeN3d9XE0x3%2FvrL2LbaBK1U%2BVEuSdfWZ35pmXnVYoUqXhfnBzNb0dDS6ng4vJ8I%2Fh5CO8By%2FjC7wVPPJ6rRJ2O54eIqe%2FXhn0Mw91%2FDnWm7NvXw9B22d3xuXV9eDhdjK9GN1dD29I8bUFYHVjVF14hE4HBjsBYMpnCUYw20CEc54nmhTgiMkkfmrTj0Kt43RBR70WyMdD6JPbA1jjbCnEy4NMupDmSdI21199yTDUCpSWdJJFRpjwTRd%2BOofT8ueHdwZ7acQwQ71GTCHkSaLaEKdkBjkcqUJ52zL%2F216r1Tk9bZHqRPLwRUGuUDrnN4w2OpYlbfYtCRsiiatNGoJv8G2YEmYeLwx32wDefyh8KfWqHcZYk%2Bo2kMiqkiVOI%2BFK39tAk14iyIOxFpJEbIF6qHHl%2F2PcA%2Bj34bxnaLj%2BOIQLkWoepwpOJvEKlear7AQirvnuNomKAlhYXplgvLoklE0GAFzxmMJh5H1WLExcaxqpWBOYdJDRpx8QseWWSJBFOMsX%2FvNjg8MnS81z236UOmT4cE45AFxiSTrFG0ziExO8iF48B79U6bMqT%2FssTsMkj1D5h9QEgXXkDZPq3JNh9WXQ2x2gwRXi2GY2%2Be4scsneZ8fSHL5%2BtUy%2Facv%2BHWTPvqikrGTkm%2F3NPqsqKdhVl15KClWKa7iSUsjDa482CziDO%2BEqE3KZQCbF5zjCiMF9glyhEwBvwKjsThwj7OjRNStP2LNleVv55ZvUOmuGAj6Af%2Bhu0Q6olL8%2FPz8PKo%2BbEbvnm6QsLLcPRVp3d0nf3smpULBbcGUS2xgSMC2G49G46EJ%2BUEG1K6%2BuKYVKbvJTpF3w7l0Ge9VmblqcqW%2BDYUuJc7dnM%2BRf54j1qpYiVuIypFbuGX2g6WBrHmuYow6XR8isotKuMbVCvRSRcWc0ntQ8WSKPUKpuDQrgDcIQM%2B0RnGdZEpd%2Bdj4pkdZUCWe6FKb6bLLJ8Ch6B95WejMRUe%2F%2FZTy6Y%2BWjEM83%2Fr73js6gdzQZfnfNr%2BTCkcPMpX5FHfWkn%2FM4iWyztNJywbKqVVfOu5O6e1dV5lOy6JwI8xR5XqMjNFx80U0mGykFRS1c8HCJ0YCA9cqoo4pyGKa%2Fqe5B32jWSsVulX2V5w%2BZKQN6Ruk%2BK208SeqtJ6kNRQl%2FB54XuPIGTCgHX%2F8zvzv24kUqJEb%2FPwLdsuhkEnUuU%2BtRrxg7%2FHKAmOdp0SHAD3ZDQ1Xv3uNFrrRYgQplnOknuEnEjCd2WbQTmsPmQsJS60x1Ox0qHbaKPpFWTLXHFaWh1EzIRSehV3LBaRzIMi%2BoHu79uUbin3ks0fcY69BfruNEdRogL2B27GsODCZAdk7wNDVDb%2Bse9GK2ao5Wx%2B%2Ffq8fGnh21yqjuT5Swi1A97vVJ0nMMoXi3yNbZ8iXhf%2BHLj2zFsjjDSCJfsRS16zXbKoI7tuqNeFFE4swF5ogb1IyPSINWaxsUveVvLoCge%2BoLAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D)?

And then, I cannot even update the main post because it's locked? How bad a joke is that?

**Comment by kdy1** [comment]
cc @balazsorban44 It seems like #8058 has a link to `play.swc.rs`, which is listed at

https://github.com/swc-project/swc/blob/89676946e6db6e23ac48878c5f54a702a1a325fe/.github/workflows/nissuer.yml#L23

Is this a misconfiguration?

**Comment by balazsorban44** [comment]
Yeah, it's missing https://github.com/balazsorban44/nissuer#validate-reproduction-urls

`reproduction-link-section`. the default `### Link to reproduction(.*)### To reproduce`

won't match your template

**Comment by balazsorban44** [comment]
This should not be an issue anymore @DNA-PC! It was a flick in the initial setup 🙏

**Comment by kdy1** [comment]
Cloisng as fixed by https://github.com/swc-project/swc/pull/8060
Thank you!
