### ISSUE TITLE
Visit comments in swc plugin

### ISSUE THREAD

**Issue by JasonGrass** [swc-project/swc#8080]
### Describe the feature

I'm trying to develop an SWC plugin for handling comments, like this: [no-warning-comments - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-warning-comments ) 

but I didn't find any API in `swc_ecma_visit` related to comments. 

I'd appreciate any guidance on this, or a link if I just missed a doc page. 

THANKS 

### Additional context

Also, I found there is no information about the comments in the AST output at the playground.
https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA8tJLVFIVNDXVwjxd%2FHn5QIAz5rJoQ8AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

Is there any direct correlation between the two?

I also trying to find an example of comments handling in `swc_ecma_lints`(https://github.com/swc-project/swc/tree/main/crates/swc_ecma_lints/src/rules),  but there doesn't seem to be any here either.

**Comment by kwonoj** [comment]
Closing as invalid, plugin interface already provides access to the comments.

**Comment by JasonGrass** [comment]
> Closing as invalid, plugin interface already provides access to the comments.

any doc page?

**Comment by JasonGrass** [comment]
I've figured out where my confusion lies. 
It seems that there is no API for directly accessing comments, instead, it's done indirectly through `swc_core::plugin::proxies::PluginCommentsProxy`.

Direct API, such as `visit_expr` in `swc_ecma_visit`,  
At the very beginning, what I was thinking about was whether there exists an API like `visit_comments`.

But in reality, AST and comments are separate, and there seems to be no way to independently access the content of the comments. Or, are there other APIs?

maybe this's why comments are missing at #6321 
and why there is no information about the comments in the AST output at the playground.
https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA8tJLVFIVNDXVwjxd%2FHn5QIAz5rJoQ8AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

PS I'm not sure if the above thoughts about comments are completely correct.

**Comment by magic-akari** [comment]
The issue your provided in swc playground is fixed in #7853 (v1.3.79).
You can try the latest [swc](https://play.swc.rs/?version=1.3.92&code=H4sIAAAAAAAAA8tJLVFIVNDXVwjxd%2FHn5QIAz5rJoQ8AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D).
