### ISSUE TITLE
Generate code from AST

### ISSUE THREAD

**Issue by Minilo-ng** [swc-project/swc#8086]
### Describe the feature

In package "@swc/core", we can find "parse" function to parse code as AST, but there is no function like "generate" to generate code from AST。

**Comment by emersonlaurentino** [comment]
@kdy1 this would be a very useful function/helper, since it doesn't exist in swc, would you have any suggestions since `escodegen` doesn't know how to read the SWC AST?

**Comment by kdy1** [comment]
It's already supported

**Comment by emersonlaurentino** [comment]
can u exemplify or share the documentation please, because I looked a lot in `@swc/core` and couldn't find it.
