### ISSUE TITLE
Ability to disable TS enum value inlining?

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#8114]
### Describe the feature

Given the following code:

```ts
enum D {
  A,
  B,
}

(D as any).A = 5;
console.log(D.A);
```

swc 1.3.88 outputs 5 and 1.3.89 outputs 0. This is because swc started inlining enums within a module.

```js
var D;
(function(D) {
    D[D["A"] = 0] = "A";
    D[D["B"] = 1] = "B";
})(D || (D = {}));
D.A = 5;
console.log(0);
```

Is there a way to disable this optimization? Although unlikely, I'm concerned it might cause bugs in people's Deno code since it would be a breaking change.

**Comment by kdy1** [comment]
@magic-akari Thoughts?

**Comment by dsherret** [comment]
It seems it would just be the ability to disable this line:

https://github.com/swc-project/swc/blob/787a465d8d87ac5a10dbf93f950c0af812e5364f/crates/swc_ecma_transforms_typescript/src/transform.rs#L90

**Comment by magic-akari** [comment]
There is an assumption option called `ts_enum_is_readonly`. However, we have deprecated it.

**Comment by dsherret** [comment]
Can we undeprecate that?

**Comment by dsherret** [comment]
I'm going to open a PR for at least the Rust API to have this.

**Comment by magic-akari** [comment]
> Can we undeprecate that?

@kdy1 Should we do this?

**Comment by kdy1** [comment]
Not sure. Personally I think `ts_enum_is_readonly: true` is similar to `isolatedModules: true`.

**Comment by dsherret** [comment]
@kdy1 the typescript compiler does not do this with `isolatedModules: true`

https://www.typescriptlang.org/play?isolatedModules=true#code/KYOwrgtgBAIlDeAoKUCCAaZUBCmC+iiAFHAIYDOUpIAngJQB0qUAvFAKwDciAxgPYhyfADbAGwvgHMSTOtyA

**Comment by kdy1** [comment]
I mean, I think all projects should enable it

**Comment by dsherret** [comment]
It woud be nice, but it's a breaking change. Most projects probably shouldn't be using enums anyway, so deoptimizing this is not a big deal imo.

**Comment by kdy1** [comment]
I filed https://github.com/swc-project/swc/discussions/8116

**Comment by nayeemrmn** [comment]
> Not sure. Personally I think `ts_enum_is_readonly: true` is similar to `isolatedModules: true`.

This is incorrect that's only for `const enum`. But even for those, if you reassign a const enum variant with `isolatedModules`, you'll get a type error but it gets transpiled in a mutable non-inlined way.

This is incompatible with tsc and shouldn't be the default. Let alone be non-configurable.

**Comment by magic-akari** [comment]
Yes, this is not exactly the same as the behavior of tsc.
We try to inline enum as much as possible whenever it is safe, just like what esbuild did in 2021.

> Enum inlining is active whether or not you use enum or const enum because it improves performance.

https://github.com/evanw/esbuild/blob/main/CHANGELOG-2021.md#0147

**Comment by nayeemrmn** [comment]
@magic-akari Thanks for the context. 

> Cross-module inlining of TypeScript enum constants (https://github.com/evanw/esbuild/issues/128)
> 
> This release adds inlining of TypeScript `enum` constants across separate modules. It activates when bundling is enabled and when the enum is exported via the `export` keyword and imported via the `import` keyword:

So esbuild does it with cross-module enums when bundling.

But when doing per-module transpilation with swc under `isolatedModules`, this optimisation is limited to module-scoped enums. So,
- Does it really unlock similar performance improvements? Maybe.
- Within a single module, is it feasible to detect mutations to the enum and de-opt?
