### ISSUE TITLE
declare member of class in JS throws TS1031

### ISSUE THREAD

**Issue by Pangoraw** [swc-project/swc#812]
**Describe the bug**
When parsing a Javascript file in which a class has a `declare` function, swc returns an error refering to TS1031. This is problematic because some class have methods called declare (see https://github.com/denoland/deno/issues/5978).

**Input code** `test.js`
```javascript
class A {
  declare() {}
}
```

**Expected behavior**
The function should be parsed since the code is in a `.js` file.

**Version**
The version of @swc/core: on master

**Additional context**
Maybe this condition in [class_and_fn.rs](https://github.com/swc-project/swc/blob/master/ecmascript/parser/src/parser/class_and_fn.rs#L301) should be guarded by:
```rust
if self.input.syntax().typescript() && eat!("declare") {
```
like others TSxxx syntax errors.

I would be happy to open a PR to fix this bug :+1:

**Comment by kdy1** [comment]
Sorry for inconvenience.

The parser has some bugs. It will be all fixed by https://github.com/swc-project/swc/pull/811 and the new version will be published tomorrow.

**Comment by kdy1** [comment]
Published a new version of `swc_ecma_parser`.

**Comment by dsherret** [comment]
@kdy1 is this completely fixed? I tried it out on the minified code and get:

```
Line 11, column 158649: Unexpected token Some(LParen)
this.scope=e}declare(e,t){retur...
```

**Comment by kdy1** [comment]
@dsherret I don't think so. Reopening...

**Comment by kdy1** [comment]
I thought being able to parse all test files from tsc was enough, but it was not

**Comment by dsherret** [comment]
Thanks @kdy1! It's fixed now. 😀
