### ISSUE TITLE
SWC crashes when trying to parse a bundle created by Next.js

### ISSUE THREAD

**Issue by andersekdahl** [swc-project/swc#8130]
### Describe the bug

Our use case is that we first produce app bundles through the normal Next.js build, but we leave environment variables. When the app starts upp in an environment we run an AST transform on the bundles to replace the environment variables. We're currently using the TypeScript compiler API to do so, which isn't all that fast. So we wanted to try out SWC for this, but hit a road bump pretty quickly when SWC crashed with a hard error one of our bundles.

### Input code

```typescript
https://github.com/andersekdahl/swc-crash-repro/blob/main/bundle.js
```

### Config

```json
No config, all defaults
```

### Playground link (or link to the minimal reproduction)

https://github.com/andersekdahl/swc-crash-repro

### SWC Info output

thread '<unnamed>' panicked at 'index out of bounds: the len is 1141 but the index is 2415', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_common-0.33.0\src\syntax_pos\hygiene.rs:395:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: failed to handle: index out of bounds: the len is 1141 but the index is 2415] {
  code: 'GenericFailure'
}

Node.js v18.13.0

### Expected behavior

It shouldn't crash

### Actual behavior

It crashes

### Version

1.3.93

**Comment by kdy1** [comment]
I tried it on the playground and it worked. I think the problem is usage of `Visitor` (JavaScript) which is going to be removed and not tracked.

https://github.com/swc-project/swc/issues?q=is%3Aissue+index+out+of+bounds%3A+the+len+is%3Aclosed
