### ISSUE TITLE
Using `using` incorrectly changes the order of subsequent statements and function declarations

### ISSUE THREAD

**Issue by KnorpelSenf** [swc-project/swc#8131]
### Describe the bug

If you use the `using` keyword, then the transpiled code will mess up the order of the statements and function declarations after. This means that some closures are no longer able to reference previously defined variables.

The example code below explains this better than any wall of text :)

The code was compiled like this:
```sh
$ cat test.ts
function f() {
    using c = { [Symbol.dispose]() {} };
    const answer = 42;
    function g() {
        console.log(answer);
    }
    g();
}
f();
$ npx swc test.ts > test.js
```

### Input code

```typescript
function f() {
    using c = { [Symbol.dispose]() {} };
    const answer = 42;
    function g() {
        console.log(answer);
    }
    g();
}
f();
```

### Config

```json
n/a
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0srzUsuyczPU0jT0FSo5lIAgtLizLx0hWQFW4Vqhejgytyk%2FBy9lMzigvzi1FiQolqFWmuwwuT8vOIShcS84vLUIqBqEyOIcBrMyHS4kTDV%2BTmpejn56RoQPZoQ9bVgEqjYmquWKw1EAQBs9kq9lQAAAA%3D%3D&config=H4sIAAAAAAAAA1WPPQ7DIAyF95wCee5QZejQuWsPgaiDiPgTdqREUe5ekgBtJvB7%2FvzstRMCRlLwFGv%2B5iLKRJhanZWJjNcvVDaLnCa8VYMWz3LOKqByklQykaG5I80XYDsfYJk08kFRf%2B%2F7QoANgTDLg7RUEHDGm2H5X0YFFxMSXRv3Vum1bfyZ2JVUcOEzHWY5kpeI5wYP%2BDXVsDYYDL0ruR%2FSbV9S7O3mMAEAAA%3D%3D

> Note: the playground does not currently seem to support `jsc.parser.usingDecl` so it is not possible to see a reproduction of the issue there.

### SWC Info output

```
$ npx -y swc-info@latest

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #1 SMP Debian 5.10.197-1 (2023-09-29)
        CPU: (4 cores)
            Models: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz

    Binaries:
        Node: 18.9.0
        npm: 8.19.1
        Yarn: 1.22.19
        pnpm: 7.27.0

    Relevant Packages:
        @swc/core: 1.3.93
        @swc/helpers: N/A
        @swc/types: 0.1.5
        

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A
```

### Expected behavior

The emitted code can be run and outputs `42`.

For example, I would expect the emitted code to look like this:

```ts
function f() {
    try {
        var _stack = [];
        var c = _using(_stack, _define_property({}, Symbol.dispose, function() {}));
        var answer = 42;
	    function g() {
	        console.log(answer);
	    }
        g();
    } catch (_) {
        var _error = _;
        var _hasError = true;
    } finally{
        _dispose(_stack, _error, _hasError);
    }
}
f();
```

### Actual behavior

The emitted code crashes with the following error.
```
error: Uncaught ReferenceError: answer is not defined
        console.log(answer);
                    ^
```

This is because the emitted code looks like this:

```ts
function f() {
    function g() {
        console.log(answer);
    }
    try {
        var _stack = [];
        var c = _using(_stack, _define_property({}, Symbol.dispose, function() {}));
        var answer = 42;
        g();
    } catch (_) {
        var _error = _;
        var _hasError = true;
    } finally{
        _dispose(_stack, _error, _hasError);
    }
}
f();
```

### Version

1.3.93

### Additional context

If you simply replace `using` by `const` in the input code snippet above, the code works as expected.

**Comment by KnorpelSenf** [comment]
Strangely enough, the emitted code does work as expected.

To give you more context, I am using SWC through Deno which crashes with the described error. I thought that the behaviour of SWC would explain the problem, but I think I'll have to investigate this further.

Feel free to ignore this issue until then :)

**Comment by KnorpelSenf** [comment]
In fact, before I open the same issue on @denoland/deno, perhaps @lucacasonato can provide more information?

Here is the reproduction example for Deno:

```sh
$ cat /tmp/test.ts 
function f() {
    using c = { [Symbol.dispose]() {} };
    const answer = 42;
    function g() {
        console.log(answer);
    }
    g();
}
f();
$ deno run !$
deno run /tmp/test.ts
error: Uncaught ReferenceError: answer is not defined
        console.log(answer);
                    ^
    at g (file:///tmp/test.ts:5:21)
    at f (file:///tmp/test.ts:7:5)
    at file:///tmp/test.ts:9:1
```

**Comment by kdy1** [comment]
Playground: https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0srzUsuyczPU0jT0FSo5lIAgtLizLx0hWQFW4Vqhejgytyk%2FBy9lMzigvzi1FiQolqFWmuwwuT8vOIShcS84vLUIqBqEyOIcBrMyHS4kTDV%2BTmpejn56RoQPZoQ9bVgEqjYmquWKw1EAQBs9kq9lQAAAA%3D%3D&config=H4sIAAAAAAAAA1WPPQ6DMAyFd06BPHeoGDr0Diy9gZUaFJQ%2FxUYCIe5OgJCWKfHz%2B%2FzspaprGFjBu17SNxUBI1MsdVJoCkYrLR9iP0ZFLTrsyZKT5JI40uNy8uwEp6QCKYusog4CpTvwdAPW8wHB2JMcFDfPpskEGO%2BZktyh4YyA1U538%2F92ytsQiflu3K3oelP4M7HKqWD9dzya%2BWqZA50bvOBnusLKYNDcXuR%2BSLVuXQ5m3kEBAAA%3D

**Comment by KnorpelSenf** [comment]
Omg that explains a lot, thank you! I wish `deno --version` would output the used SWC version. It would be much easier to investigate such issues.
