### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by coderaiser** [swc-project/swc#8135]
### Describe the feature

Is it possible to preserve comments while parsing? I see that https://github.com/swc-project/swc/issues/2964 is closed, and some PR is merged, but I don't see comments in AST when use:

```js
const swc = require('@swc/core');

const ast = swc.parseSync('/* comments */', {
    syntax: 'typescript',
    preserveAllComments: true,
});
```

Is it supported?

**Comment by kwonoj** [comment]
#2964 is a different issue; it is transform strips out the comment if the comment is being attached to the types. Then it got sidetracted with other comments bit though.

As already clarified in https://github.com/swc-project/swc/issues/2964#issuecomment-1030633307, currently js bindings does not give an access to the comments in its parse interfaces. There are internal discussions for the future of parse interface itself, so no immediate plan to touch existing codes for now.
