### ISSUE TITLE
Cannot parse return type on next line in arrow function after upgrade to swc_ecma_parser 0.24.0

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#814]
**Describe the bug**

**Input code**

```ts
const testing = ():
    string =>
{
    return "";
};
```

Has error: "Parenthized expression cannot be empty"

Additionally...

```ts
const testing = (
    param: string,
    other: number,
):
    | string
    | number
    | number
    | number
    | string =>
{
    return 5;
};
```

Has error: "Expected Arrow, got Some(Colon)"

The second example is a common scenario for how prettier and dprint format union types in arrow functions.

**Expected behavior**

No error.

**Version**
0.24.0 of swc_ecma_parser

**Comment by kdy1** [comment]
Published a new version

**Comment by dsherret** [comment]
Thanks @kdy1! This is fixed now.

Sorry! I noticed one small issue I didn't notice last time and opened #817 to fix. Please feel free to edit that PR in case I didn't implement the fix properly.
