### ISSUE TITLE
Property 'expression' does not exist on type 'ModuleItem'

### ISSUE THREAD

**Issue by emersonlaurentino** [swc-project/swc#8150]
### Describe the bug

The types for `moduleItem` expression are not working as they should. When I try to access a moduleItem like `ExportDefaultExpression`, it should be possible to access the `expression` attribute without an error in the typescript, as the field exists. However, the error occurs
```cmd
Property 'expression' does not exist on type 'ModuleItem'
```

### Input code

```typescript
const ast = parseFileSync(filePath, {
  syntax: "typescript",
  target: "es5",
});

const configNode = ast.body.find(
  (node) => node.type === "ExportDefaultExpression"
);

console.log(configNode?.expression.value);
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUUjOz0vLTLdScAbTCrYK1VwKCnmJualWCkq5lboFRflZqcklSjpA0ZTM4hKXzCKgBIgFFKq15uJKrSjILypRSElNSyzNgRlnDQCHcjH6XAAAAA%3D%3D&config=H4sIAAAAAAAAA32UO5LbMAxA%2Bz2FR3XapMgBtssZODQJytxQhIYAvdbs%2BO6BJPqTNaROwsOP%2BH29HQ7dB7nu9%2BFLPuVntIWg3P9FQlNmexFJx9MI5Eocuftxo0wz4lJhkVxX0LEtPfBsBPSzaXcJkUBkwSaCJhtijmF6judwGAsQPclEKv7qAJnpf%2FvGCn5SS%2BNJfkRMYPMOMZZMzAw9FM2xw5TsSGDOtihe5kxtiYRaiBlWBm%2FGgqPKs48cMUvMV%2BrBeuPQg4JiAcfxDJqZxBKzTPI85T0L9nCsfb%2F0%2BJs1nG2qlpWYcFlaItkqXk8YiU2oWSvhCjdqsMJW3O%2BWMZgCXEt%2BtfvAmDd68hdAKpAsUbYDaH4XjSDztGUddi1jDjKyPClc5lt7ZYZeimpiDEpl58pA4ah1s4CvDubKOi2dhjfKR9GDgRBkVhTX9BnZnbSg85JjUID01wZtqlZg7lu4weeF2MHv8krWB6xpDJZP25Sm4YhpJ8AAfEK%2FoyCtYNzGRa7EZdzmNXuQ0QCvqlRawOsRkAVgNGk5li%2BzIeshHk2f8Pg4E03her%2FBg839Y9%2FXO%2FzWFLoBfV1gO%2FBzf9e7%2FKt7KN2u8D3xLtKfm%2BUS9PoP1Dzh9ywGAAA%3D

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
        CPU: (8 cores)
            Models: Apple M1 Pro

    Binaries:
        Node: 16.18.0
        npm: 9.8.1
        Yarn: 1.22.19
        pnpm: 7.30.1

    Relevant Packages:
        @swc/core: 1.3.93
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

It should be possible to access expression inside the moduleItem without having a typescript error

### Actual behavior

Property 'expression' does not exist on type 'ModuleItem'

### Version

1.3.93

**Comment by emersonlaurentino** [comment]
@kdy1 what is the reason for closing the issue without any details?

**Comment by kdy1** [comment]
You should narrow type instead
