### ISSUE TITLE
Async function that returns an array fails when used inline

### ISSUE THREAD

**Issue by PIMBA** [swc-project/swc#8155]
### Describe the bug

In the following code, both `goodFunction` and `badFunction` should log same value: `[[1,2,3], [1,2,3]]`,
Yet when compiled and run, the function `badFunction` will log `[1,2]`.

Seems like [this issue](https://github.com/swc-project/swc/issues/5985) is not yet been fixed.

### Input code

```typescript
const someFn = (xx, x, y) => [x, y];

const getArray = () => [1, 2, 3];

const goodFunction = async () => {
    const rb = await getArray();
    const rc = await getArray();
    console.log(someFn(1, rb, rc));
}

const badFunction = async () => {
    console.log(someFn(1, await getArray(), await getArray()))
}

goodFunction();
badFunction();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "tsx": false
    },
    "transform": {
      "legacyDecorator": true
    },
    "target": "es5",
    // "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "loose": false
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUSjOz011y1OwVdCoqNBRAKJKTQVbO4VoECvWmosrGawqPbXEsagosRKkDiJvqKNgpKNgjKQkPz%2FFrTQvuSQzH2RcYnFlXjJUcTWXAhBAlBUlgSTLEzMRhmpoWiMrSMarID8nVS8nP10D4m4NoDOKkoA4WROophbmlqREwk7BNAjdUkwRTU2QHcg%2BBTkNyTYQFwBaeLBJWAEAAA%3D%3D&config=H4sIAAAAAAAAA21QOw6DMAzdewrkuRJTO3Tu2kNYwaBU5CM7SI0Qd28CCQWpW%2Fw%2Bfi%2BeL00Db1HwaOb0TINHFuJ9TohEG%2FCTEAjRkyjWPsC1sh0pxxgcS1IEnmhngmRTj6PQCi0bA4HRSu%2FYHENGGlDFZ11Wdp19yAOF3IPkVgq0bbI6J1STitZoq%2Ft4DFDOeCaRszBL0Q4j%2FW162nwpOBjXTauhXCxfZWt1h5%2BoFtjDQMurOte%2FLV%2BC%2BQzufQEAAA%3D%3D

### Expected behavior

Both `goodFunction` and `badFunction` should function exactly the same.

### Version

1.3.94-nightly

**Comment by kdy1** [comment]
# Investigation

This is a bug of `es2015::generator` pass.

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUSjOz011y1OwVdCoqNBRAKJKTQVbO4VoECvWmosrGawqPbXEsagosRKkDiJvqKNgpKNgjKQkPz%2FFrTQvuSQzH2RcYnFlXjJUcTWXAhBAlBUlgSTLEzMRhmpoWiMrSMarID8nVS8nP10D4m4NoDOKkoA4WROophbmlqREwk7BNAjdUkwRTU2QHcg%2BBTkNyTYQFwBaeLBJWAEAAA%3D%3D&config=H4sIAAAAAAAAA21QSwqDMBDdewqZdcG20C667raHCHGUFPNhJkKDePcmmliF7jLvM%2B9lpqqu4c0SHvUUn3FwghhpmyPCwXjxiQj44JAlKefhVNgWpSXhLXFUeBpxYzwnUycGxgWaVwY8CcOdJb0PGbAXMjzLsrzr6BPUo089kK%2Fnyy13aJrotpaxhGW5VkZ1YZ8hrXaEzEdhkgrTD%2Fi37GFzlXHQth0XQz5aOsxa7A4%2FUSmwhYHiV3Eu35u%2FBtCBiIABAAA%3D
