### ISSUE TITLE
TypeScript-Bug-ES2022 : Optional property should be not show

### ISSUE THREAD

**Issue by sunrabbit123** [swc-project/swc#8160]
### Describe the bug

property x should be not show

This worked fine until 1.3.39, when the
since then.

Of course, i only checked with the playground.

[tsc](https://www.typescriptlang.org/play?target=9&useDefineForClassFields=true#code/MYGwhgzhAECC0G8BQ1XQA4FcBGICWw0AHgPwBc0EALgE54B2A5gNwprAD291NmwVHGgAoGeKgEpkaadADy2AFYBTfgDpIEPI3pCqACzwQANNFETW0gL5JrSUBugAhaEqJUl9ACYx4UtFlwCaGxySloGFhskOy4IDhAlVRAORiF6JQB3JyFxcWYgA)
[swc 1.3.40](https://play.swc.rs/?version=1.3.40&code=H4sIAAAAAAAAA2WNQQqEMAxF9z1Fli0MHkAXw3iBOcM0hpqhpIONKIh3t9aNMH%2BXz8t%2FGD85wws2AyW%2F2UdGWJ8tZJ1YQldrTFLOGTVNloXVXfSZt%2F8SalNGOIjVkfMDKnJ97mY3BqujB1qVZPiz%2BZvtpIssRWpiClZogd461x3E1VqbpwAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdcwrkuUPF0KF36CEQdSIqfsKuVBTl7oUAabPZ7%2BP3vE5CwIs03MVaxrJElQjTsReEsmf1KQhwjkg6mchwGSxTpWZlCXdoawywSgtydSHJq5TdATYEwuHomDPezPk%2FUwcXExKdhVWq%2FGLxnDj1VHDh%2Bd7J%2Fkvt2xrc4CcaYcdhMPQYznZ2%2BwKZmnC1GAEAAA%3D%3D)
[swc 1.3.39](https://play.swc.rs/?version=1.3.39&code=H4sIAAAAAAAAA2WNQQqEMAxF9z1Fli0MHkAXw3iBOcM0hpqhpIONKIh3t9aNMH%2BXz8t%2FGD85wws2AyW%2F2UdGWJ8tZJ1YQldrTFLOGTVNloXVXfSZt%2F8SalNGOIjVkfMDKnJ97mY3BqujB1qVZPiz%2BZvtpIssRWpiClZogd461x3E1VqbpwAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdcwrkuUPF0KF36CEQdSIqfsKuVBTl7oUAabPZ7%2BP3vE5CwIs03MVaxrJElQjTsReEsmf1KQhwjkg6mchwGSxTpWZlCXdoawywSgtydSHJq5TdATYEwuHomDPezPk%2FUwcXExKdhVWq%2FGLxnDj1VHDh%2Bd7J%2Fkvt2xrc4CcaYcdhMPQYznZ2%2BwKZmnC1GAEAAA%3D%3D)

### Input code

```typescript
class A {
    public x?: string;
    constructor(init){
        Object.assign(this, init);
    }
}

class B extends A {
    public b?: string;
}

console.log(new B());
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.40&code=H4sIAAAAAAAAA2WNQQqEMAxF9z1Fli0MHkAXw3iBOcM0hpqhpIONKIh3t9aNMH%2BXz8t%2FGD85wws2AyW%2F2UdGWJ8tZJ1YQldrTFLOGTVNloXVXfSZt%2F8SalNGOIjVkfMDKnJ97mY3BqujB1qVZPiz%2BZvtpIssRWpiClZogd461x3E1VqbpwAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdcwrkuUPF0KF36CEQdSIqfsKuVBTl7oUAabPZ7%2BP3vE5CwIs03MVaxrJElQjTsReEsmf1KQhwjkg6mchwGSxTpWZlCXdoawywSgtydSHJq5TdATYEwuHomDPezPk%2FUwcXExKdhVWq%2FGLxnDj1VHDh%2Bd7J%2Fkvt2xrc4CcaYcdhMPQYznZ2%2BwKZmnC1GAEAAA%3D%3D

### SWC Info output

Noop

I found out while working on the playground.

### Expected behavior

I expected next code
```ts
"use strict";
class A {
    constructor(init) {
        Object.assign(this, init);
    }
}
class B extends A {
}
console.log(new B());
```

### Actual behavior

x should be not show, but x is exists

```ts
class A {
    x;
    constructor(init){
        Object.assign(this, init);
    }
}
class B extends A {
    b;
}
console.log(new B());
```

### Version

1.3.40

**Comment by magic-akari** [comment]
- #7435
- https://swc.rs/docs/migrating-from-tsc#usedefineforclassfields
- https://www.typescriptlang.org/tsconfig#useDefineForClassFields
