### ISSUE TITLE
Minification issue (Plotly)

### ISSUE THREAD

**Issue by agusterodin** [swc-project/swc#8162]
### Describe the bug

I am using a library called Plotly to render WebGL plots. I noticed that as of Next.js 13.5.4, Plotly now displays an error saying WebGL is not supported. My browser absolutely supports WebGL (Chrome on MacOS). Switching back to Next.js 13.5.3 or setting swcMinify: false in next.config.js fixes the issue. This is likely an issue with SWC minification.

### Playground link (or link to the minimal reproduction)

https://github.com/agusterodin/next-plotly-webgl-error-reproduction

### Expected behavior

Next 13.5.3
![Screenshot 2023-10-20 at 3 39 18 PM](https://github.com/swc-project/swc/assets/10248395/2ba4ac58-19f7-42b6-9f10-9ccda7ff91bb)

### Actual behavior

Next 13.5.4+ when swcMinify: true
![Screenshot 2023-10-20 at 3 40 12 PM](https://github.com/swc-project/swc/assets/10248395/31941ff0-a87e-4db3-a01b-98a4e639ca08)

### Version

Version included in Next 13.5.4+

**Comment by Austaras** [comment]
Have you tried nextjs canary?

**Comment by agusterodin** [comment]
Just tried with Next.js 13.5.7-canary.13 (latest build as of Oct 21st). Issue persists.

**Comment by Austaras** [comment]
A bit of anti-climax -- this is fixed by Next.js 13.5.7-canary.16

**Comment by kdy1** [comment]
Thank you!
