### ISSUE TITLE
Problem with SWC working in Nestjs

### ISSUE THREAD

**Issue by peiyanlu** [swc-project/swc#8170]
### Describe the bug

When using SWC in Nestjs, there was an issue with hot updates. Please refer to https://github.com/nestjs/nest/issues/12623

### Playground link (or link to the minimal reproduction)

https://github.com/peiyanlu/nest-swc-test

### SWC Info output

    Operating System:
        Platform: win32
        Arch: x64
        Machine Type: x86_64
        Version: Windows 10 Home China
        CPU: (32 cores)
            Models: 13th Gen Intel(R) Core(TM) i9-13980HX

    Binaries:
        Node: 18.16.0
        npm: N/A
        Yarn: N/A
        pnpm: 8.6.6

    Relevant Packages:
        @swc/core: 1.3.93
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Service hot update is normal

### Version

1.3.93

**Comment by kdy1** [comment]
You should fill out more information

**Comment by kdy1** [comment]
At least post an error message, or if there's no one, please reduce it to a minimal one at least.
