### ISSUE TITLE
Class methods are removed 

### ISSUE THREAD

**Issue by patricklafrance** [swc-project/swc#8178]
### Describe the bug

With my development build, everything works fine, however with my production build, the methods of a class are being removed.

With my production build, the following:

```ts
export class LocalModuleRegistry {
    #registrationStatus: ModuleRegistrationStatus = "none";
    readonly #deferredRegistrations: DeferredRegisteration[] = [];

    async registerModules<TRuntime extends AbstractRuntime = AbstractRuntime, TContext = unknown>(registerFunctions: ModuleRegisterFunction<TRuntime, TContext>[], runtime: TRuntime, { context }: RegisterLocalModulesOptions<TContext> = {}) {
        // ....
    }
}

const localModuleRegistry = new LocalModuleRegistry();

export function registerLocalModules<TRuntime extends AbstractRuntime = AbstractRuntime, TContext = unknown>(registerFunctions: ModuleRegisterFunction<TRuntime, TContext>[], runtime: TRuntime, options?: RegisterLocalModulesOptions<TContext>) {
    return localModuleRegistry.registerModules(registerFunctions, runtime, options);
}
```

Is being transpiled to:

```js
var c, n, p = (c = /*#__PURE__*/ new WeakMap(), n = /*#__PURE__*/ new WeakMap(), function() {
    (0,_class_private_field_init._)(this, c, {
        writable: !0,
        value: "none"
    }), (0,_class_private_field_init._)(this, n, {
        writable: !0,
        value: []
    });
}), m = new p();
function u(e, r, s) {
    return m.registerModules(e, r, s);
}
```

Therefore, when `registerLocalModules` is begin called with the production build, the following error is thrown:

```
main.30cd532b73d4e85ba393.js:8407 Uncaught (in promise) TypeError: m.registerModules is not a function
    at u (main.30cd532b73d4e85ba393.js:8407:14)
    at src_bootstrap_tsx-webpack_sharing_consume_default_react-dom_react-dom-webpack_sharing_consume-3e2598.30cd532b73d4e85ba393.js:79:81
    at __webpack_require__.a (main.30cd532b73d4e85ba393.js:10490:13)
    at ./src/bootstrap.tsx (src_bootstrap_tsx-webpack_sharing_consume_default_react-dom_react-dom-webpack_sharing_consume-3e2598.30cd532b73d4e85ba393.js:37:21)
    at Function.__webpack_require__ (main.30cd532b73d4e85ba393.js:10427:42)
```

I tried a few options and found out that if I activate the `loose` option it works fine:

```json
  "jsc": {
     "loose": true
  }
```

I also noticed while playing in SWC playground that it seems to work fine when `minify` options are turned off:

```json
  "jsc": {
    "minify": {
      "compress": false,
      "mangle": false
    }
  }
```

Or when I change the `env` section for a `target`  field, it works fine (but I cannot do this because the transpiled code must match a `browserlist` file configuration):

```json
  "jsc": {
     "target": "es2022"
  }
```

So that might be configuration related but I can't find out how to fix it.

### Input code

```typescript
interface DeferredRegisteration {
    index: string;
    fct: DeferredRegisterationFunction;
}

export interface RegisterLocalModulesOptions<TContext> {
    context?: TContext;
}

export interface LocalModuleRegistrationError {
    // The registration error.
    error: unknown;
}

export class LocalModuleRegistry {
    #registrationStatus: ModuleRegistrationStatus = "none";
    readonly #deferredRegistrations: DeferredRegisteration[] = [];

    async registerModules<TRuntime extends AbstractRuntime = AbstractRuntime, TContext = unknown>(registerFunctions: ModuleRegisterFunction<TRuntime, TContext>[], runtime: TRuntime, { context }: RegisterLocalModulesOptions<TContext> = {}) {
        const errors: LocalModuleRegistrationError[] = [];

        if (this.#registrationStatus !== "none") {
            throw new Error("[squide] [local] The registerLocalModules function can only be called once.");
        }

        runtime.logger.debug(`[squide] [local] Found ${registerFunctions.length} local module${registerFunctions.length !== 1 ? "s" : ""} to register.`);

        this.#registrationStatus = "in-progress";

        await Promise.allSettled(registerFunctions.map(async (x, index) => {
            runtime.logger.debug(`[squide] [local] ${index + 1}/${registerFunctions.length} Registering local module.`);

            try {
                const optionalDeferedRegistration = await registerModule(x as ModuleRegisterFunction<AbstractRuntime>, runtime, context);

                if (isFunction(optionalDeferedRegistration)) {
                    this.#deferredRegistrations.push({
                        index: `${index + 1}/${registerFunctions.length}`,
                        fct: optionalDeferedRegistration
                    });
                }
            } catch (error: unknown) {
                runtime.logger.error(
                    `[squide] [local] ${index + 1}/${registerFunctions.length} An error occured while registering a local module.`,
                    error
                );

                errors.push({
                    error
                });
            }

            runtime.logger.debug(`[squide] [local] ${index + 1}/${registerFunctions.length} Local module registration completed.`);
        }));

        this.#registrationStatus = this.#deferredRegistrations.length > 0 ? "registered" : "ready";

        return errors;
    }
}

const localModuleRegistry = new LocalModuleRegistry();

export function registerLocalModules<TRuntime extends AbstractRuntime = AbstractRuntime, TContext = unknown>(registerFunctions: ModuleRegisterFunction<TRuntime, TContext>[], runtime: TRuntime, options?: RegisterLocalModulesOptions<TContext>) {
    return localModuleRegistry.registerModules(registerFunctions, runtime, options);
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "useBuiltins": true
      }
    },
    "minify": {
      "compress": true,
      "mangle": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "env": {
    "chrome": "79",
    "firefox": "115",
    "android": "4.4.3",
    "edge": "116",
    "ios": "12.2",
    "opera": "73",
    "safari": "14.1",
    "samsung": "21"
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA81WS2%2FaQBC%2BR8p%2FmDo5GJU6zdUJRFHbnFK1SnJDSDjrwVg1u3R3LUDI%2F73rfRg%2FEVJ7KBdgH9%2FMfPPNzKZUIl9GBOErLpFzjF8wSYVajGTKKBwuL0B9UhrjLgQheUqTO7O2JDLsv%2FWUU1J%2Bq4PF5cXlBe42jEsF4my508%2BMRNl3FucZih%2Bb8oq4f%2FvC1LmdnDrbxPx%2FCMFtDeLW8IwJ4883zhl3cDc38LZC4LV9wPJAYPb17xBy%2BouybTsEkkVC9JjZO%2FSrOu6rjGQuQuh6ZHZgAh5lFD3LKMcoZjTbw1XcoNXcEQNsz%2BYKZza%2FK90sUSKxp8TGh9yye%2F%2F2klOZrhEUf0hjAY%2FvJTCRbn3SXhlXfKs9S8fUd7gux63wjhuVxSPOdDYfAzerKpvV%2FsHlGIrwTG1M4FCMHOlWJUKa5CmXTgmhzZfW9xJ8uUpF0JM%2F%2BDBxeWpYLD9yxdkWKG5BQ%2FveTPzO0xjnMMtKF%2BY1rTVDgqXlCUhEQWf9HdXvLMNY%2FSUYeKO7o7Gi7q2lMMhYkiAPYnzPE3%2FRMf3EchrD9aGTsiBDmshVAfogrLVHw%2Bc0AbfwAJ7wIATPK0CyKqhgMWpQOUijIjGlnzacJRyF8BqXom2USvjJ2ToVGCgSXlFKxURXbsE62vhG4v5ubBrTCCbTdmbO5Oj6oBHgI9wWN6eocrJU%2Fa9BWzt8TcGxH9Q%2FRqJMaznKdC03K1xRZIhoFq%2B%2FUzU9VGWtop1WBTZ2RdX1zyk%2BFQ7GP%2BHVqKP6Zqp7e1WwycXKH7in7ZuJsjg3AYvxMJaeRCci6L9Z1OurWmwuFaoiJVmB35wKvYy0FKdv%2BP2m%2F0KHj3ZaASMkV3HCdpVmxxZTyjNqCXSAOQ3T3eqXi2msJ7M6gNehuWjj%2F%2BtSfa5F35zzhK03GUqMTdUeXTy7hZ2SvO2WU%2Fhc9krnH8a6aZazfd9sehxlzm06hXWnsO8N0yuynofGRI%2BbnieIb4KwL5VqvPQNn%2F%2F6NWAKWTyc%2BRSoatHS2cNZ0HoMdd2udU1rviSz%2BAM%2FdbYvHgsAAA%3D%3D&config=H4sIAAAAAAAAA1WQTW6EMAyF95wCZV0hQelU7bI3sYJDU5Ef2UlVNJq7NwkEmF3yPfs92%2FembcUPS%2FHZ3tMzfTwQIx3%2FRHi1Af4SEWH1yJK0D%2BKlqoGzFChiIY9NEIHAsnJkrk6EIMMFZBRt0AazO8TgDAQtD%2FOkR8avqJegLV9jUtBTnNFWq%2FWaJZ3xhFy7jnkN2HnBp5Gb3UcYN8Wi7bfI%2B%2BbJkG%2FiLKpRChYuvgLt79kkv8ltC71%2F7JsIpQmVKzfs%2B7dKwU7k9JTp2I3da%2BU4zbiV3irSjgsZuqEi55GgxByNDApIl8Kx609qONo546EvezSPf1txmT74AQAA

### SWC Info output

    Operating System:
        Platform: win32
        Arch: x64
        Machine Type: x86_64
        Version: Windows 10 Enterprise
        CPU: (12 cores)
            Models: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

    Binaries:
        Node: 20.6.1
        npm: N/A
        Yarn: N/A
        pnpm: 8.8.0

    Relevant Packages:
        @swc/core: N/A
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

No error with the production build.

### Actual behavior

I get the following error:

```
main.30cd532b73d4e85ba393.js:8407 Uncaught (in promise) TypeError: m.registerModules is not a function
    at u (main.30cd532b73d4e85ba393.js:8407:14)
    at src_bootstrap_tsx-webpack_sharing_consume_default_react-dom_react-dom-webpack_sharing_consume-3e2598.30cd532b73d4e85ba393.js:79:81
    at __webpack_require__.a (main.30cd532b73d4e85ba393.js:10490:13)
    at ./src/bootstrap.tsx (src_bootstrap_tsx-webpack_sharing_consume_default_react-dom_react-dom-webpack_sharing_consume-3e2598.30cd532b73d4e85ba393.js:37:21)
    at Function.__webpack_require__ (main.30cd532b73d4e85ba393.js:10427:42)
```

Because the `registerModules` method seems to be removed from the class:

```js
var c, n, p = (c = /*#__PURE__*/ new WeakMap(), n = /*#__PURE__*/ new WeakMap(), function() {
    (0,_class_private_field_init._)(this, c, {
        writable: !0,
        value: "none"
    }), (0,_class_private_field_init._)(this, n, {
        writable: !0,
        value: []
    });
}), m = new p();
function u(e, r, s) {
    return m.registerModules(e, r, s);
}
```

### Version

1.3.93

**Comment by kdy1** [comment]
This is due to the pass marking all functions from `@swc/helpers` as `PURE`. Those should be marked as SIDE_EFFECT_FREE` I guess

**Comment by kdy1** [comment]
It was not the case. IIRC I removed it

**Comment by kdy1** [comment]
Closing as already fixed.

https://play.swc.rs/?version=1.3.96-nightly-20231025.1&code=H4sIAAAAAAAAA81WS2%2FaQBC%2BR8p%2FmDo5GJU6zdUJRFHbnFK1SnJDSDjrwVg1u3R3LUDI%2F73rfRg%2FEVJ7KBdgH9%2FMfPPNzKZUIl9GBOErLpFzjF8wSYVajGTKKBwuL0B9UhrjLgQheUqTO7O2JDLsv%2FWUU1J%2Bq4PF5cXlBe42jEsF4my508%2BMRNl3FucZih%2Bb8oq4f%2FvC1LmdnDrbxPx%2FCMFtDeLW8IwJ4883zhl3cDc38LZC4LV9wPJAYPb17xBy%2BouybTsEkkVC9JjZO%2FSrOu6rjGQuQuh6ZHZgAh5lFD3LKMcoZjTbw1XcoNXcEQNsz%2BYKZza%2FK90sUSKxp8TGh9yye%2F%2F2klOZrhEUf0hjAY%2FvJTCRbn3SXhlXfKs9S8fUd7gux63wjhuVxSPOdDYfAzerKpvV%2FsHlGIrwTG1M4FCMHOlWJUKa5CmXTgmhzZfW9xJ8uUpF0JM%2F%2BDBxeWpYLD9yxdkWKG5BQ%2FveTPzO0xjnMMtKF%2BY1rTVDgqXlCUhEQWf9HdXvLMNY%2FSUYeKO7o7Gi7q2lMMhYkiAPYnzPE3%2FRMf3EchrD9aGTsiBDmshVAfogrLVHw%2Bc0AbfwAJ7wIATPK0CyKqhgMWpQOUijIjGlnzacJRyF8BqXom2USvjJ2ToVGCgSXlFKxURXbsE62vhG4v5ubBrTCCbTdmbO5Oj6oBHgI9wWN6eocrJU%2Fa9BWzt8TcGxH9Q%2FRqJMaznKdC03K1xRZIhoFq%2B%2FUzU9VGWtop1WBTZ2RdX1zyk%2BFQ7GP%2BHVqKP6Zqp7e1WwycXKH7in7ZuJsjg3AYvxMJaeRCci6L9Z1OurWmwuFaoiJVmB35wKvYy0FKdv%2BP2m%2F0KHj3ZaASMkV3HCdpVmxxZTyjNqCXSAOQ3T3eqXi2msJ7M6gNehuWjj%2F%2BtSfa5F35zzhK03GUqMTdUeXTy7hZ2SvO2WU%2Fhc9krnH8a6aZazfd9sehxlzm06hXWnsO8N0yuynofGRI%2BbnieIb4KwL5VqvPQNn%2F%2F6NWAKWTyc%2BRSoatHS2cNZ0HoMdd2udU1rviSz%2BAM%2FdbYvHgsAAA%3D%3D&config=H4sIAAAAAAAAA1WQTW6EMAyF95wCZV0hQelU7bI3sYJDU5Ef2cmoaDR3bxII0F3yPfs924%2BmbcUPS%2FHZPtIzfTwQIx3%2FRHi1AX4TEWH1yJK0D%2BKlqoGzFChiIc9NEIHAsnJkrk6EIMMFZBRt0AazO8TgDAQtD%2FOkR8avqJegLV9jUtC%2FOKOtVus1SzrjCbl2HfMasPOS8xQsvM%2Fc7EbCuCkWcT9GXjiPhnwTZ1HNKg4Fob2fTfKb3LbR%2B8e%2BilCaULlyxL5%2FqxTsRE5PmY7d2L1WjtOMW%2BmtIu24kKEbKnIeCUrM0ciggHQpHLv%2BpIajnTMe%2BrJH8%2FwDAO8fDPkBAAA%3D

**Comment by patricklafrance** [comment]
Thank you @kdy1 🙏🏻
