### ISSUE TITLE
CSS module :global function syntax

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#8179]
### Describe the bug

Currently SWC css module pass cannot handle cases like this 

```
.a:global(.b .c).d {
  color: red
}
```

SWC ignores `.d`

I tried fix this, but current algorithm seems hard to implement

[lightningcss demo](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Atrue%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.a%3Aglobal(.b%20.c).d%20%7B%5Cn%20%20color%3A%20red%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

### Playground link (or link to the minimal reproduction)

None

### Expected behavior

.d should be renamed

### Actual behavior

.d stay as is

### Version

1.3.95

**Comment by kdy1** [comment]
We need more domains in allowlist 🤣

**Comment by JSerFeng** [comment]
Sry, I'll try to make a repro repo

**Comment by kdy1** [comment]
You don't need to

**Comment by kdy1** [comment]
It's just issue manager bot configured wrongly

**Comment by JSerFeng** [comment]
I believe the cause is [here](https://github.com/swc-project/swc/blob/ed9bfa9faf2d374a19a179cb14871b7407a4f566/crates/swc_css_modules/src/lib.rs#L544), continue without handle other sub_class_selectors, but I failed to fix it 🥹

**Comment by kdy1** [comment]
# Investigation

The current output is 

```
.__local__a.b.d .c {
  color: red;
}
```

**Comment by JSerFeng** [comment]
Thanks for reply, here is the result of css-loader, which I believe using postcss under the hood, and lots of users use css module this way.

![image](https://github.com/swc-project/swc/assets/57202839/c6b6c286-d0a2-4aff-9d16-a549f512c220)

![image](https://github.com/swc-project/swc/assets/57202839/5cf2d4ea-4c67-4984-9b9a-c7df4541d747)
