### ISSUE TITLE
Leading pipe before types and new line emits error

### ISSUE THREAD

**Issue by strobelm** [swc-project/swc#818]
**Describe the bug**
A leading pipe in combination with a newline causes `error: Expected Arrow, got Some(Colon)`
**Input code**
```
// pipe-broken.ts
export const test = (str: string | undefined):
    | string
    | undefined => {
    return str === undefined ? undefined : str;
    };

error: Expected Arrow, got Some(Colon)
 --> pipe-broken.ts:1:46
  |
1 | export const test = (str: string | undefined):
  |
``` 

while without the newline the code compiles:
```
 pipe-working.ts
export const test = (str: string | undefined): | string
    | undefined => {
    return str === undefined ? undefined : str;
    };

// compiler output
export var test = function(str) {
    return str === undefined ? undefined : str;
};
```
**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    }
  }
}
```

**Expected behavior**
The code should compile, it does for both versions on TS playground.

**Version**
The version of @swc/core: 
+ @swc/cli@0.1.24
+ @swc/core@1.1.52

**Additional context**
Awesome project! Thx!

**Comment by kdy1** [comment]
It seems like it's already fixed by https://github.com/swc-project/swc/pull/816.
Anyway, I added some tests and I'm going to publish a new version.
