### ISSUE TITLE
In projects that mix js, ts, jsx, tsx, the build results of version 1.3.79 have file extensions .js, .jsx.

### ISSUE THREAD

**Issue by hi-otto** [swc-project/swc#8184]
### Describe the bug

I've put the minimal reproduction in this git repository: [https://github.com/hi-otto/swc-bug-report](url)

### Input code

```typescript
// a: a/index.jsx, b: b/index.js, c: c/index.ts, d: d/index.tsx
// index.ts
import a from '~/a';
import b from '~/b';
import c from '~/c';
import d from '~/d';

console.log(a, b, c, d);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "baseUrl": "./",
    "paths": {
      "~/*": [
        "./src/*"
      ]
    }
  }
}
```

### Playground link (or link to the minimal reproduction)

https://github.com/hi-otto/swc-bug-report

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
        CPU: (8 cores)
            Models: Apple M1

    Binaries:
        Node: 18.16.0
        npm: 9.5.1
        Yarn: 1.22.15
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.3.79
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The output results of 1.3.78 and 1.3.79 are different, and I expect it to be like 1.3.78.
It should be `import a from "./a";` instead of import a from `"./a/index.jsx";`

## dist-1.3.78/index.js
```
import a from "./a";
import b from "./b";
import c from "./c";
import d from "./d";
console.log(a, b, c, d);
```

## dist-1.3.79/index.js
```
import a from "./a/index.jsx";
import b from "./b/index.js";
import c from "./c";
import d from "./d";
console.log(a, b, c, d);
```

### Version

1.3.79

**Comment by kdy1** [comment]
https://github.com/kdy1/repro-swc-8184

You can make it resolve fully, but not remove `.js`.
Currently behavior is not ideal, though

**Comment by zhaomenghuan** [comment]
When is this issue expected to be fixed? I also have a strong dependency on this.

**Comment by kdy1** [comment]
@zhaomenghuan Feel free to send a PR
