### ISSUE TITLE
Minify asciiOnly option does not take effect

### ISSUE THREAD

**Issue by chestozo** [swc-project/swc#8189]
### Describe the bug

Here https://swc.rs/docs/configuration/minification is says
`asciiOnly`, Defaults to `false`. Implemented as v1.2.184 and aliased as `ascii_only` for compatibility with terser.

On terser website here https://terser.org/docs/options/ is says
`ascii_only` (default `false`) -- escape Unicode characters in strings and regexps (affects directives with non-ascii characters becoming invalid).

In current version 1.3.95
`minify.format.asciiOnly` seems to not take effect and output is the same in both cases (`true|false`).

[Playground link](https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUcgtTlewVVAKObwy5%2FDK5IzEovTUIoUc9cSCgpzM5MSSzPw8IyWuZKDS%2FJxUvZz8dA2gBk0uAIZO9gU8AAAA&config=H4sIAAAAAAAAA3VSO0%2FDMBDe%2Byuim1uBOjAwMSEh8ehedTg5l3LIL%2FkcSFT1v2MnTkmgTHG%2Bu%2B%2FhO59WVQUfouC%2BOqVj%2BqHOU2BDNqK%2BoAn3uj2ylQTtC1RVe3iQL3UzljYSe031RjnjnU18gfWFPkjULF5j%2F4qGkkwMLa3nZZFwDW5Y03%2BU6PwzfZJ%2BSpYh7jC%2BDwEPiyZDaNkeNYk8Fq2hC9jW1MGyWYnsgvPXzGwmelQ5CcClcj6U4%2Fg9jxzwGITCfILSp5l2mRx7T6IC%2BwiTA0TpiulCJmI4Uswkku3t9rYQQDsnOUiDWkpMMGy56eeWeRch3XvZmFsxD%2BQP3LhgMM4UEoaimN%2Bs7ufxUsBlzIBWMnvuHgjVL7HQ2sjDLgHb6JIZK1gqrooqGFe3Q8byMvPUxkHcwU%2FTdOdpXcDyMhGHuOdvOfZJA%2BQCAAA%3D)

### Input code

```typescript
const msg = "Télécharger l'application"
console.log(msg)
```

### Config

```json
{
  "jsc": {
    "experimental": {
      "plugins": [
        ["@swc/plugin-styled-components", {
          "displayName": true,
          "ssr": true,
          "fileName": true,
          "topLevelImportPaths": [],
          "meaninglessFileNames": ["index"],
          "cssProp": true,
          "namespace": ""
        }]
      ]
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false,
      "format": {
        "asciiOnly": true
      }
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUcgtTlewVVAKObwy5%2FDK5IzEovTUIoUc9cSCgpzM5MSSzPw8IyWuZKDS%2FJxUvZz8dA2gBk0uAIZO9gU8AAAA&config=H4sIAAAAAAAAA3VSO0%2FDMBDe%2Byuim1uBOjAwMSEh8ehedTg5l3LIL%2FkcSFT1v2MnTkmgTHG%2Bu%2B%2FhO59WVQUfouC%2BOqVj%2BqHOU2BDNqK%2BoAn3uj2ylQTtC1RVe3iQL3UzljYSe031RjnjnU18gfWFPkjULF5j%2F4qGkkwMLa3nZZFwDW5Y03%2BU6PwzfZJ%2BSpYh7jC%2BDwEPiyZDaNkeNYk8Fq2hC9jW1MGyWYnsgvPXzGwmelQ5CcClcj6U4%2Fg9jxzwGITCfILSp5l2mRx7T6IC%2BwiTA0TpiulCJmI4Uswkku3t9rYQQDsnOUiDWkpMMGy56eeWeRch3XvZmFsxD%2BQP3LhgMM4UEoaimN%2Bs7ufxUsBlzIBWMnvuHgjVL7HQ2sjDLgHb6JIZK1gqrooqGFe3Q8byMvPUxkHcwU%2FTdOdpXcDyMhGHuOdvOfZJA%2BQCAAA%3D

### Expected behavior

Symbols like `é` should not be changed during minification.

### Actual behavior

Getting `\xe9` instead in output regardless of `asciiOnly` option value.

### Version

1.3.95

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUcgtTlewVVAKObwy5%2FDK5IzEovTUIoUc9cSCgpzM5MSSzPw8IyWuZKDS%2FJxUvZz8dA2gBk0uAIZO9gU8AAAA&config=H4sIAAAAAAAAA3VSS0%2FDMAy%2B71dUPm8C7cCBEyckJEC7TxOyUncE5SU7hVbT%2FjtJm44WxqnpZ3%2BP2Dmtqgo%2BRMF9dUrH9ENdINaWXERzQRMeTHvUThK0L1BV7eFBvtTNWNpI7A3VG%2BVt8C7xBdYX%2BiBRawkG%2B1e0lGQit7Sel0X4GtxoQ%2F9Rog%2FP9EnmKVly3GF8HwIeFk2W0Gl3NCTyWLSGLtCupg6WzUpkxz5cM3OZGFDlJACXyvlQjuP3PHIgIAvxfILSp5l2mRz7QKJYhwiTA0TpiulCJiIfKWYSyfZ2e1sIYLyXHKRBIyUmWO10088t8y443XvZmFsxD%2BQP3Hi2GGcKCUNRWr95Z%2Fp5vpRwmZPRSabP7ZlQ%2FVLj1kU9LBOwjT65aQVLxVVRBevrdghZnmYe2ziJO%2Fhpmi497Qu0vEzEIe75G5Iz5ITlAgAA


It's `ascii_only`

**Comment by chestozo** [comment]
I tried both - they don't work
<img width="1636" alt="image" src="https://github.com/swc-project/swc/assets/498934/eddacc87-70ac-4cdd-b686-343952606a36">

**Comment by chestozo** [comment]
I expect `é` to **not be transformed** into `\xe9` but it is

**Comment by chestozo** [comment]
I misspelled in my initial report
should be
Symbols like `é` **should not be changed** during minification.

**Comment by chestozo** [comment]
This is what I get using terser `ascii_only` option:
```
$ npx terser <(echo 'var i = "Télé"') --format ascii_only=false
var i="Télé";

$ npx terser <(echo 'var i = "Télé"') --format ascii_only=true
var i="T\xe9l\xe9";
```
