### ISSUE TITLE
Does not add imports to Object.groupBy core-js polyfill when { env: { mode: 'usage' }}

### ISSUE THREAD

**Issue by 9aoy** [swc-project/swc#8193]
### Describe the bug

When using { env: { mode: 'usage' }}, swc fails to add imports to`Object.groupBy` core-js polyfills.

I noticed that swc has defined `object/group-by`. I don’t know why it cannot take effect.

<img width="478" alt="image" src="https://github.com/swc-project/swc/assets/22373761/a7af0cb0-81d0-4648-8813-3fe416489506">

### Input code

```typescript
const data = [{ name: 'a', type: 'a' }, { name: 'b', type: 'a'}, { name: 'c', type: 'b'}];

const result = Object.groupBy(data, ({ type }) => type);
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "decorators": true
    },
  },
  "env": {
    "targets": [
      "> 0.01%",
      "not dead",
      "not op_mini all"
    ],
    "mode": "usage",
    "coreJs": "3"
  },
  "isModule": "unknown",
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUUhJLElUsFWIrlbIS8xNtVJQT1TXUSipLIAwFWp1FOAyScgyyBLJCIkk9dpYay6uZLDZRanFpTklQNP9k7JSk0v00ovySwucKjVAduooaFSDNSnUairY2oGZmtZcANataFGVAAAA&config=H4sIAAAAAAAAA3WQP2vDMBDFd38KIcjmFtvdOnTqUAJZu4RSDulibPQP3bnYhHz3yq5sJ0M36b1393vStRBC9qTkq7imY7rgyBgdmA80ASMlg%2BOA5Z8ZIBLGLZwUmhzDmBSJygKp2AWW5er2ND4sSJJG5SOw31Yvxi0DOIKji4%2F2nrGNfKZCnXczrama%2BqludpTBFtT0vkb%2FxZ6QQQNDClzAUMYXuYJE97P%2FBUNskeei53XPm6ieq%2Fqwc51noRH0o%2BLDt%2B1cJ8AYuehf%2BYHWa5z7DwQt5hmZquFxxsgXuTVJycHgXZkpLJPKW%2BtdT3uyo9OaXZ5UFrdfdQwnJtgBAAA%3D

### Expected behavior

```js
require("core-js/modules/esnext.object.group-by.js");
require("core-js/modules/es.object.create.js");
var data = [
    {
        name: "a",
        type: "a"
    },
    {
        name: "b",
        type: "a"
    },
    {
        name: "c",
        type: "b"
    }
];
var result = Object.groupBy(data, function(param) {
    var type = param.type;
    return type;
});

```

### Actual behavior

```js
require("core-js/modules/es.object.create.js");
var data = [
    {
        name: "a",
        type: "a"
    },
    {
        name: "b",
        type: "a"
    },
    {
        name: "c",
        type: "b"
    }
];
var result = Object.groupBy(data, function(param) {
    var type = param.type;
    return type;
});

```

missing `esnext.object.group-by.js`

### Version

1.3.94-nightly-20231016.1

**Comment by kdy1** [comment]
Problem is coreJs: "3".

Try full version like 3.x.xx

**Comment by 9aoy** [comment]
Try to specify the corejs version, but it still didn’t work. I created a reproducible project. Can you help me take a look?
```

https://github.com/9aoy/swc-polyfill-8193/tree/main
- pnpm install
- pnpm build  (see the output file => `output.js` )

**Comment by kdy1** [comment]
https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA0vOzysuUUhJLElUsFWIrlbIS8xNtVJQT1TXUSipLIAwFWp1FOAyScgyyBLJCIkk9dpYay6uZLDZRanFpTklQNP9k7JSk0v00ovySwucKjVAduooaFSDNSnUairY2oGZmtZcANataFGVAAAA&config=H4sIAAAAAAAAA3WQvW7DMAyE9zyFoTktamfL3KEoECBTd0JmUhuSKJB0YSPIu4dO%2FJMM3aS703ekLpuicK14ty8udrQL9oqcIHxhyMhihnKH24eZgQV5CZsiQ1LoTXHoI4jnJqvbzm4r%2FQvApBo9MSgt6LtxnQqUIcmJOD53LE9%2BbKCG0thWfVTlW1mtVQHP4IfPOfpv7QEValB4ad9MEzhMf%2BtXRKpx7OoEzjg1OcPg9zi7273vylmV3yZnrI9MmQTC024PrqG6gCtah3xHe4qRUituSTZymLMnA9kG1xsxQ63GpQEAAA%3D%3D
