### ISSUE TITLE
Wrong scope for private fields with optional chaining & type cast in function call

### ISSUE THREAD

**Issue by MrZillaGold** [swc-project/swc#8211]
### Describe the bug

<img width="448" alt="Снимок экрана 2023-11-02 в 22 51 20" src="https://github.com/swc-project/swc/assets/42776347/e7187e42-5189-457a-80a1-2bb7e2243a31">

### Input code

TypeScript

```typescript
class Child {
	#num = 42

	num() {
		return this.#num;
	}
}

class Parent {
	#child = new Child();

	getChildNum() {
		return this.#child?.['num']();
	}
}

const parent = new Parent();

// BUG HERE! 
// If you remove `any` type cast and brackets, then everything works
console.log((parent?.['getChildNum'] as any)(...[123])) // expected 42, actually error

// This variant works without error
// console.log(parent?.['getChildNum'](...[123]))
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.95&code=H4sIAAAAAAAAA3WQQUvDMBTHz82neOKhLYwMp7cxBGWoFxHR0ygsps%2B2LEtKkrYG2Xf3Nd2hh3lLwvv%2Ffv8XqYRz8Fg3qoRfllzr7ggbuFsxltAxy8fHxKLvrAZfN46PE2uWnNiJMRnDb8Ki9jEtI2cDGoeJmeVrIlXo4%2B31MjGm7vkuJXRajJEz3mjnoZ3wE3RyRepyCQ%2BfT%2FC8fd9ewXh7%2BYZgOrB4ND3CXuiwBx9aBCkII3QJX1bIA3q3IDFqwB5toAq6gsHYg4tCo5ArU2XZ5B1rzeqnBQhHrJBnnPPdzeq2yHMgOf60KD2W9HULENJ3QqkAaK2xseoHbQq9sI2gXaINhsbXpvPnIZqZ6%2F%2Bxz61%2F%2F7%2FaxLsBAAA%3D&config=H4sIAAAAAAAAA21QSQ7CMAy89xWVzwgBEhz4A4%2BwiluCmkW2QVRV%2F07SJqUHLlE8E8%2BSsapreEoD13qM1zgEZCFe54jI4BQ%2FEQEdAknDJijsCquSqBZ7oRmaFgYUuSNNWySnw%2FGcN6D3XijCyi%2FKkDXOtMPWsvE2MIkU5dXNout6%2Bm%2FI6KT1bLdCTNjoBkgFGTuLKRi%2B7f4BmZmqcs6CYP39NTvlf0ndlzYX%2BD0qydeUYORWNlPFavoCTPjyb2MBAAA%3D

### Expected behavior

Code works correctly without errors

### Version

1.3.95

**Comment by Austaras** [comment]
No idea what's the correct semantic is, but swc generates identical output as [tsc](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDCAWBLEATaBvAUASAMQDsBXAW2gF5oAWAJkxyOIAoBKDHbAJwFMAXQj-NB5IIAOgIkA3DgC+mOZlCQYABTDd8PNnmBJU5aPi4B3OHpQtpOAOa8EyFADkSLbZ179BwxGNy6HAPyiANoA5AyhALqWsvJ0wAD2+BBaAA7qXJoGRqZqGjwxmAD0RdAAQgCqAOLQABIAogBK9QCE0MWlAJIAZtAAngmE0NzECQBuXNAABmD4fVNCfamTwJBas2gARhxgwADWvBAANELwmdBcExx93vjW0MYJHHsQikkQCSBcoiAJ1oyMdL5IJhWw8eyoZzEKLQSCwubMRiiZHBACM1AAzJFmKwShcAB7LYA8LhoGgnXZ8MAgEB9C4cDhPIA)

**Comment by jridgewell** [comment]
The current throw behavior is correct. By casting the optional chain as `(foo?.bar as any)()`, you change the `this` context of the method call to be `undefined`. Note that `(foo?.bar)()` is special, and keeps `foo` context.

**Comment by kdy1** [comment]
Thank you so much for the explanation!
