### ISSUE TITLE
JSX automatic contains classic output when jsx spread comes before other props

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#8215]
### Describe the bug

It seems the emit output contains the classic output when a jsx spread comes before other props.

### Input code

```typescript
const TabButton = (tab) => {
  const props = { className: tab };

  return (
    <button {...props} key={tab}>
      {tab}
    </button>
  )
}
const TabButton2 = (tab) => {
  const props = { className: tab };

  return (
    <button key={tab} {...props}>
      {tab}
    </button>
  )
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "react": {
        "importSource": "npm:react",
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.96-nightly-20231103.1&code=H4sIAAAAAAAAA0vOzysuUQhJTHIqLSnJz1OwVdAoSUzSVLC1U6jmUlBIBksXFOUXFAOlqhWScxKLi%2F0Sc1OtFIDKFGqtuYCKilJLSovyFDSATAUFmySIQdV6enpgfbUK2amVttVA5bV2YBUKCmAORLU%2BRDlIRpOrlisZ1TlG1HMP3BFILiPoHgB6b3fKHgEAAA%3D%3D&config=H4sIAAAAAAAAA1WQPQ7CMAyFd05ReWZAHRi4AxMnsIJbBdVJZDsSFerdSdMfyhIl33vPjv05NQ281MGt%2BZRreSQUJdnfhegYDN%2BFADlGdeKTwXlTXzpLJpkqmRYBDKUnqyFtL227BmCIUangDgellbEPvhuPLV3kJKT6b5ytGPphz%2F93FAzaReFjISF0dgAFeU5R7BGzuLkQhMS3xXb%2BmSQH81x1zBYZzTtY5em0nbU1cHzm%2Bqd1gzYmWga%2Fws%2B0zbjPA17vW7Kub%2FoCEngkRo0BAAA%3D

### Expected behavior

Should use jsx automatic for everything.

### Actual behavior

```
import { jsx as _jsx } from "npm:react/jsx-runtime";
import { createElement as _createElement } from "npm:react";
const TabButton = (tab)=>{
    const props = {
        className: tab
    };
    return /*#__PURE__*/ _createElement("button", {
        ...props,
        key: tab
    }, tab);
};
const TabButton2 = (tab)=>{
    const props = {
        className: tab
    };
    return /*#__PURE__*/ _jsx("button", {
        ...props,
        children: tab
    }, tab);
};
```

### Version

1.3.96-nightly-20261103.1

**Comment by kdy1** [comment]
This is intentional and the source code has comments for this

**Comment by dsherret** [comment]
Huh, interesting. Thanks! Seems like both TypeScript and Babel also do this:

https://www.typescriptlang.org/play?jsx=4#code/MYewdgzgLgBAKgQwEYCECuUrhgXhgCimQEpcA+GAbwFgAoGGUSWABwCcQWJcrGAbBBAgA5BAFsApgC4YRJDAC+Abjp0GbCVDRswBNQxgAeJBiy7KAOivtOEBTADWEgJ45KchWX0GqH70YB6E0xwL3oYYjoFOiZoeGR0ELAAJh5CEnIqfVjWDi4eSn5BEXFpWWRFFVp9DS0dPXCGY1NsJ1d3ZHtLazy7MJ8GDqRoxsDgs36IqKA

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBAKgQwEYCECuUrhgXhgCimQEpcA-GAbwCgYZRJYAHAJxCYlyvoBsEIIAOQQBbAKYAuGESQwAvgG5qtGCzFQ0LMARV0APEgxZtlAHTnW7CHJgBrMQE8clGXLK66VVx70B6Q5jg7nTE1HLUDNDwyOiBYABMXIQk5FQqkcxsHFyUvPxCopLSyPJKKmoaWjqeMAZG2PZOLsg2ZhZZ1sE1Xi0-_vVgXaFyQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.2&externalPlugins=&assumptions=%7B%7D
