### ISSUE TITLE
bug: Unexpected token `Bar`. Expected jsx identifier

### ISSUE THREAD

**Issue by layershifter** [swc-project/swc#8243]
### Describe the bug

SWC can't compile very specific code that contains JSX:

```
  x Unexpected token `Bar`. Expected jsx identifier
   ,-[input.tsx:1:1]
 1 | export const Foo = (props) => {
 2 |   return originalMessage ? <Bar>
   :                             ^^^
 3 |     <Baz>
 4 |       {(): unknown => null}
 5 |     </Baz>
   `----


Caused by:
    0: failed to process js file
    1: Syntax Error
```

### Input code

```typescript
export const Foo = (props) => {
  return originalMessage ? <Bar>
    <Baz>
      {(): unknown => null}
    </Baz>
  </Bar> : null;
};
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "baseUrl": "./",
    "target": "es2019",
    "keepClassNames": true,
    "minify": {
      "compress": false
    }
  },
  "isModule": true,
  "module": {
    "type": "es6"
  },
  "minify": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAAy3MuwqEMBSE4T5PMaVW9l4ibLGdDxEkiBjOCScJisF3343afTA%2FYw%2FPEjEzhYgvMwZUXtiHGoNGVoDYmITAsi4rGTfZEMxiMaL%2FGNH%2FAEXnIyBXdYtEG%2FFO5YKSc9dTNW9WIBrtvXXq6tQPUKpzMYYAAAA%3D&config=H4sIAAAAAAAAA1VQu27DMAzc8xUGkbGwmw4FmrVTh3TrB7AKnSg1JYGk0RqB%2F72WX3A28e54d%2BJ9VxSwV3clRjgWcDVLeqyqm8ZQTrBaFCqjXCr9deLgKa%2Fc1A3y%2B%2FAchoSiJOs8INoFw79saF0ideKTjYsja5opk5ZW6NwFZO8%2BOEWxmRy5fpKACQato%2FA2RgidbYAMtcE8U47G1iKjeQcz3T84fqPSlzRZWVawxKBcKFsC6cvz4W3Bf4jSe4Oqn8ikD%2B2BffB1t%2B3lIichzboaG51%2FspuzwespntuGNjbACzLfNN9tqvEK6%2BKaNLn2%2Fy88py2%2BAQAA

### SWC Info output

N/A

### Expected behavior

Code compiles

### Actual behavior

Compilation fails. If the snippet will be formatted with Prettier to following:

```tsx
export const Foo = (props) => {
  return originalMessage ? (
    <Bar>
      <Baz>{(): unknown => null}</Baz>
    </Bar>
  ) : null;
};
```

It will be compiled.

### Version

1.3.96

### Additional context

[Babel compiles](https://babeljs.io/repl#?browsers=node%208&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wGIQnAvHACjCgjFQEo8A-OAbwCg44pgYBXKZOaASwHMeyAIYAbALLBUqIX2BwA_HAA8AISFQqjJsrUAvTdu20C5AFxw2yANbIIAdy64ayNiJEBfLUyUB6PQeU_dRpzFzcAbnp3SKA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.23.2&externalPlugins=&assumptions=%7B%7D) the original snippet

**Comment by nnnnoel** [comment]
Fail 1
```typescript
export const Foo = (props) => {
  return originalMessage ? <Bar>
    <Baz>
      {(): unknown => null}
    </Baz>
  </Bar> : null;
};
```

Succes 1
```typescript
export const Foo = (props) => {
  return originalMessage ? (<Bar>
    <Baz>
      {(): unknown => null}
    </Baz>
  </Bar>) : null;
};
```

Success 2
```typescript
export const Foo = (props) => {
  return originalMessage ? <Bar>
    <Baz>
      {() => null}
    </Baz>
  </Bar> : null;
};
```
