### ISSUE TITLE
TS assertion on left hand side of binary expr leads to parsing error

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#8244]
### Describe the bug

Got this report in dprint.

### Input code

```typescript
const test = availableZoom as any <= zoom;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.97-nightly-20231107.1&code=H4sIAAAAAAAAA0vOzysuUShJBRK2ColliZk5iUk5qVH5%2BbkKicUKiXmVCja2ClVArjUAxAP7ByoAAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D

### Expected behavior

Should parse.

### Actual behavior

  x Expression expected
   ,-[input.ts:1:1]
 1 | const test = availableZoom as any <= zoom;
   :                                    ^
   `----

Caused by:
    0: failed to process js file
    1: Syntax Error

### Version

20231107 nightly

**Comment by kdy1** [comment]
# Investigation

`<` in `<=` is lexed as a part of `any` (generic)

**Comment by kdy1** [comment]
Closing as a duplciate of https://github.com/swc-project/swc/issues/7621 and I'll update #7621
