### ISSUE TITLE
Minifier incorrectly omits arrow param parenthesis with comment

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#8251]
### Describe the bug

Input code is syntactically valid, output code is not.

### Input code

```typescript
y = (value // some comment
) => foo();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    },
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.97&code=H4sIAAAAAAAAA6tUsFXQKEvMKU1V0NdXKM7PTVVIzs%2FNTc0r4dJUsLVTSMvP19C05gIAh6EF2ycAAAA%3D&config=H4sIAAAAAAAAA32UO5LbMAxA%2Bz2FR3WKjIsUOUC6nIFDi6BMhyQ0BOi1Zsd3D%2FTzeteQOgkPP%2BL38XY4NBdqm9%2BHD%2FmUn94WgvL4FwkNme1NJA20yVJbQs%2FNj5VeaETeRoJJdJ9JExEJVrLIUsjBD8%2B%2BW0x9AaInmUht6WqCzPTVfmEF30fApT7LT4gRbN4hxpIJmaGDojluMUbbE5irLYqXMVNbAqEWYoSVwZm%2BYK%2Fy7AIHzBLzlTqwzrToQEGhQMvhCpqZxBKzTPI85T0TdnCqXTf185s1XG2slpWYcJtaItkqXs8YiI2vWSvhDDdqMMOluN8tgzcFuJb8anfBkDd68g9AKhAtUbYJNL%2BThpd52rL2u5YhexlZHhQu8629MkMnRTUheKWyY2WgcNC6WcDVFsbKtlo6C94oHwUHBryXWVFc03vg9qwF5aEH9AqQ%2FlqvTdUMzGMLN%2Fi4EDv4j7yS9QFbNJLl8zalIZ0w7gRIwGd0OwrSCsZtXORK3PptXrMDGQ1wqkqlCbweAVkARhOBtdmQ9RCPpot4%2BjwTi8L9cW%2BTzd3nvn85uSxzPrlugI4%2Fj8fmbWFNQlcno%2BXIj32f9X49Ka3Xec2sCfR3NZxyuf8Hw%2FodQi8GAAA%3D

### Expected behavior

At least
```js
y = (value // some comment
) => foo();
```
but why does it not completely remove the comment?
```js
y = value => foo();
```

### Actual behavior

Invalid syntax:
```js
y=value// some comment
=>foo();
```

### Version

1.3.97

**Comment by mischnic** [comment]
To stress this again:
First of all, this is about invalid syntax if the comment is preserved.

But I would have expected the minified to also just remove the comments completely.

**Comment by kdy1** [comment]
I think it's a problem of the mismatching default value. 

[The SWC minifier strips the comment correctly](https://play.swc.rs/?version=1.3.97&code=H4sIAAAAAAAAA6tUsFXQKEvMKU1V0NdXKM7PTVVIzs%2FNTc0r4dJUsLVTSMvP19C05gIAh6EF2ycAAAA%3D&config=H4sIAAAAAAAAA42VwZLaMAyG732KHZ976HDooQ%2FQ2z6Dx8RyMBtbGUtmYXZ49yoGFihEgRvyF0mWfllfP97kZ7bUmT9vX%2B1PM4yuEJQ7W7PTIbPbi91Alxx1JY5sft4zW5qA4AaC74PjlTEDIsGFuLGnmGM4PMbsMI0FiB5O2qkrfU2QmR493jAFPyeAS312vkYcwOUXCOvIxszQQ9ECdjgMbiSwO1cUr9PNXImEWugJqgzejgVHlcs%2BcsQsOc1THpy3HXpQkFig47gDzY3kIm4ySVmUOjTMw7r2fVPTjDfYuaE6VnKCfZOA3E6JtsFIbEPNWmtO0EItT9C5eXOeYrAFuJY872eLMS9o4ANAKjk4ouwSaPEaGUTvS97CS55iDjJwfFA4mVStShl6aZqNMSidmyoNhaOmpgK%2BdjB1rtPSPmMLbaHowUIIomElJH1G7jZaUnwYAYMCiM5c0NR%2FAuz367PATYP%2BAvZXqsT6IJzJ5HizTNEhrXF4IXAC3qB%2FAZSWMy5jRV7R%2FbjM1exBpApeRSs1YP5xlIFmtAOwplUZe4lk%2BwHX12f0Djzef2eSy%2F3cG2gCFmnC88Ul7b7sLUOYwNyHebo6Waa%2FXcAArX6tVqdvzoRJ6GtL5WaRTyo%2B8b%2F%2Fgy%2Fb9loLE%2Bn94qLd%2B%2FgPotWtlB8IAAA%3D) if there's 

```
             "format": {
                "comments": "some"
            }
```

but it should be default...

**Comment by kdy1** [comment]
I fixed both
