### ISSUE TITLE
Regression in 1.3.79

### ISSUE THREAD

**Issue by alexeagle** [swc-project/swc#8258]
### Describe the bug

Bazel uses SWC via rules_swc.

You can see the bump in this PR is red
https://github.com/aspect-build/rules_swc/pull/216

```
==================== Test output for //examples/paths:test_test:
5c5
< const _moduleA = require("../../../../../../.cache/bazel/_bazel_runner/4b45c25630ed5c5c6ea[70](https://github.com/aspect-build/rules_swc/actions/runs/6818819711/job/18545103923?pr=216#step:7:71)d3e83a5966d/sandbox/linux-sandbox/41/execroot/aspect_rules_swc/examples/paths/src/modules/moduleA");
---
> const _moduleA = require("./modules/moduleA/index");
FAIL: files "examples/paths/src/index.js" and "examples/paths/expected.js" differ.
```

I had a look through https://github.com/swc-project/swc/compare/v1.3.78...v1.3.79 but I don't see the issue. Maybe https://github.com/swc-project/swc/pull/7852 is the culprit just since it's the big refactoring in this commit range.

FYI @realtimetodie as you originally fixed this symlink handling

### Input code

```typescript
import { moduleA } from "@modules/moduleA";

moduleA();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2021",
    "baseUrl": "./src",
    "paths": {
      "@modules/*": [
        "./modules/*"
      ]
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.79&code=H4sIAAAAAAAAA8vMLcgvKlGoVsjNTynNSXVUqFVIK8rPVVBygAgU60MllKy5uKBMDU1rLgD0Oi%2BDOAAAAA%3D%3D&config=H4sIAAAAAAAAA02OMQ7CMAxF95wi8ogQhY5MXICRCXUIwQKqtolsR6KqencSElo2%2B%2F1vPU9Ka2jZwlFPcYyLN8RIyx4Jj4OYdyQgo0e29PIC33De5hsx9EBJDeR6Xx%2Bg8JthvFCXgl3FZH%2FcG3nyv%2BLUu3vokKtNpNdCdbpag0KbbFbFDrmw%2Fp9%2BTELr%2Bt4NLcPSZBfI4tn4pBYKqGb1AagcGT8AAQAA

### Expected behavior

const _moduleA = require("./modules/moduleA/index");

### Actual behavior

const _moduleA = require("../../../../../../../shared/cache/bazel/user_base/09a27d1eeea3b44d1580773090924b4d/sandbox/linux-sandbox/629/execroot/aspect_rules_swc/examples/paths/src/modules/moduleA");

### Version

1.3.79

### Additional context

Note that Bazel sets up the inputs as a symlink tree, so this is likely a change in symlink handling.

**Comment by kdy1** [comment]
It should be related to https://github.com/swc-project/swc/pull/7852

**Comment by kdy1** [comment]
But please create a minimal repro that can be used by the core team for investigation.
Closing as there's no repro

**Comment by kdy1** [comment]
The most important thing was matching `tsc`. So the test case was wrong.
