### ISSUE TITLE
In @swc/jest, jsc path opitons is not working properly depending @swc/core version 

### ISSUE THREAD

**Issue by hayoung123** [swc-project/swc#8259]
### Describe the bug

we using @swc/core and @swc/jest for testing our project.

@swc/core Since version 1.3.79, an issue has occurred jsc path option in jest.config.

In the jest.config path , we set `@config` to `./src/config/beta.json`. 
However, an error occurs when jest searches for ./src/config/@config.
```
 Cannot find module '../config/@config' from 'src/mocks/handlers.ts'
```

### Input code

```typescript
//jest.config 

module.exports = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['jest-config/setupTests.js'],
  testMatch: '<rootDir>/src/__tests__/**/*.test.(ts|tsx)',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': [
      '@swc/jest',
      {
        sourceMaps: true,
        jsc: {
          parser: {
            syntax: 'typescript',
            tsx: true,
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
          baseUrl: '.',
          paths: {
            '@config': ['src/config/beta.json'],
            '@pay/*': ['src/*'],
            '@/*': ['src/*'],
          },
        },
      },
    ],
  },
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)(\\?.*)?$':
      'jest-transform-stub',
    '\\.svg$': '<rootDir>/../../packages/jest-config/svg.js',
  },
};


//setupTest.js
require('@testing-library/jest-dom');
require('jest-canvas-mock');
```

### Playground link (or link to the minimal reproduction)

this is issue for jest environment

### SWC Info output

    CPU: (10 cores)
        Models: Apple M1 Max

    Binaries:
        Node: 20.4.0
        pnpm: 8.6.10

    Relevant Packages:
        @swc/core: 1.3.79
        @swc/helpers: N/A
        @swc/types: N/A
        @swc/jest: 0.2.29
        typescript: 5.0.4

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

`@config` path is set to `./src/config/beta.json`.

### Actual behavior

`@config` path is set to `./src/config/@config`.

### Version

after 1.3.79

**Comment by kdy1** [comment]
Maybe https://github.com/swc-project/swc/issues/8184? Anyway, we can't investigate without a minimal reproduction
