### ISSUE TITLE
passing `let let` to the parser should throw an error 

### ISSUE THREAD

**Issue by sapphi-red** [swc-project/swc#8269]
### Describe the bug

`let` is reserved in `let`/`const`/`class` declarations in non-strict mode, but SWC parser doesn't reject them.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#:~:text=(also%20reserved%20in%20const%2C%20let%2C%20and%20class%20declarations)

### Input code

```typescript
{
    let let
}
{
    const let = 0
}
{
    class let {}
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.97&code=H4sIAAAAAAAAA6vm5VIAgpzUEhDm5arl5aqGCCXn5xWDBRVsFQxQJHISi4vBEtW1YHEAdYxiO0QAAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdcwrkuUPF0CF36CEs6kRE%2FISpVBTl7iUB0mbz%2B%2FnZ6yAELKxgFGsZCwgYmeKJC8PZJfwUBkhZZBV1SHDr6sK7NKFhOqitKpAwzpSOFMu7lC0Bxnumnmic1U5P%2Bb9TeRsiMV%2BNuxXdbOjaOLRWsP71PsT2S8qB6gUP%2BJl62bkYND97sq7dvnp7734YAQAA

### Expected behavior

Throws an error like `Unexpected reserved word 'let'`.

### Actual behavior

No error happens.

### Version

1.3.97

### Additional context

This errors with most parsers on https://astexplorer.net/.

**Comment by kdy1** [comment]
You selected `Source Type: Script`.

SWC correctly emits an error if the type is `Module`.

https://play.swc.rs/?version=1.3.97&code=H4sIAAAAAAAAA6vm5VIAgpzUEhDm5arl5aqGCCXn5xWDBRVsFQxQJHISi4vBEtW1YHEAdYxiO0QAAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERBGQTqSjK3UsIpM3m9%2FOzVyElTGzgKdcyFhA1MdKJC8N5TvpTGEDjNRuyMcGtqxPv0qAdY6W2Q4GkacRUU6zuSrUEuBAYe6Jx3s52yP%2BdJvhIyHw17lY9jw6vjaK1gg%2FvpYrtl5QjHhc84GfqZedisPzqyUQLiu0LtK2NIRcBAAA%3D

**Comment by kdy1** [comment]
Oh, my bad. You were talking about non-strict mode. I misread it.
