### ISSUE TITLE
JSDoc Parser

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#827]
It would be useful if swc could be used to parse JSDocs similarly to how the TS compiler parses them.

Use cases:

1. Type checking
2. Automatically formatting JS docs.
3. Analyzing JS docs for information.

I think it should be lazily parsed as parsing and storing this information is not so useful when compiling.

**Comment by kdy1** [comment]
I'll implement it tomorrow.

**Comment by dsherret** [comment]
@kdy1 oh, there is no rush on this!! Hope you have a relaxing sleep 😄

**Comment by mattd3v** [comment]
@dsherret I've been working on the Deno doc generation command, and am currently working on [moving it to its own crate](https://github.com/denoland/deno/issues/6123). There may be a lot in common with this and what I've been doing, so I'd love to help!

**Comment by kdy1** [comment]
Is there any reference about ast types of jsdoc?

**Comment by dsherret** [comment]
@kdy1 yeah, it's probably a lot of work. The AST nodes used in the TS compiler are outlined here:

https://github.com/microsoft/TypeScript/blob/master/src/compiler/types.ts

Also, they can be viewed by going to https://ts-ast-viewer.com and in the "Options" area enabling "Show internals". Then it will show the `jsDoc` property on nodes.

**Comment by kdy1** [comment]
@dsherret Thanks! I'll take a look.

**Comment by iykekings** [comment]
@kdy1 what is the status of this? I don't know my way around swc yet, but let me know if there is any way I can help. 🎉

**Comment by kdy1** [comment]
@iykekings Currently it's almost wild land and WIP on https://github.com/kdy1/swc/tree/jsdoc. I got some spare time and working on it. 

I recently decided to use nom because it does not require complex parsing algorithm. I think I should do some groundwork to split works. I'll write a comment on the issue after doing such groundwork.

**Comment by kdy1** [comment]
@iykekings I think I can accept prs from now on. It's still wild but it contains basics of jsdoc parsing.
