### ISSUE TITLE
Tagged template literals: minify does not shake pure tag function

### ISSUE THREAD

**Issue by jdanyow** [swc-project/swc#8275]
### Describe the bug

Unused tagged template literals are not tree shaken away from the minified output when the tag function is marked as pure using the `/*#__PURE__*/` directive and/or by `jsc.minify.compress.pure_funcs` configuration.

I'm not sure if this would be considered a bug or a feature request.

### Input code

```typescript
/*#__PURE__*/
function pure_html(strings, ...values) {
  return { strings, values };
}

// ✅ This is tree-shaken from the minified output.
const a = `<span>aaaa</span>`;

// ❌ This is not tree-shaken from the minified output,
// despite the "pure_html" function being declared pure
// using the __PURE__ directive and by 
// `jsc.minify.compress.pure_funcs` configuration.
const b = pure_html`<span>bbbb</span>`;

// ✅ This is not tree-shaken from the minified output.
export const c  = pure_html`<span>cccc</span>`;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "pure_funcs": ["pure_html"]
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA42QQU7DMBBF9z7FV9lAVZwDtLBjjxCsE8eZNIbGjjx2RVV1yY4jwOU4CXZKI4RYdOSFNTN%2Fvt4v5hdlef%2F0cFeW80K00epgnMUQPZVd6DeXHLyxa15ASrlVm0h8hb0APIXoLfaYFo5THJbiIERR4OvjDY%2BdYaQXPNE1d%2BqFLFrveoSO0BtrWkMNXAxDDFJoZzlA4QbVigdlb1WqVTF%2Bq%2BXx6Of7dNS6cNbhRRY2xIMJNM5nmWyGibamRJA29Eb5pMrwWRI5t7PgFBEa4ylptgRlG9Q75L3qmbUcPXdSu37wxCzHBLMDV0hcrVlHr7LbCbNOmFPMP7x1qj%2B8v0I8l1cKeh2cDzgaafzjpFNNTt%2F37f80BQIAAA%3D%3D&config=H4sIAAAAAAAAA1WPTQ7CIBBG9z1FM2sXpgsX3sETGGMITisNf2EgkTS9u0Ch1h3zvvnCm6Xre5iJw7Vf0jMNljlCt8%2BJUNSefRIB5IoRd8J6OLV0phyNTBIWtG4JeOYm9KVFw3kYagOkMYStUZkSWozx%2BCc3yjokOrDsFhw%2Bx6B55nd4eyXhUeN1N1JMTxL%2Fpbq6AMq8QgnruT5a3CQv8FtqPt6F4giCbq2YWbd%2BAdH3Ab05AQAA

### Expected behavior

When a template tag function is marked "pure", minification should take it into consideration when considering whether an expression has side-effects.

### Version

1.3.94-nightly-20231016.1

**Comment by kdy1** [comment]
`__PURE__` directive here is used in a wrong way, so it should have no effect.

**Comment by kdy1** [comment]
Also, you can't use `target: "es5"` with `pure_funcs` for template literals. You should perform `minify()` with pure_funcs and then `transform()`.

I'll close this issue with fix for `pure_funcs` for template literals.

**Comment by jdanyow** [comment]
Thanks @kdy1! I've updated the description and playground link to target es2022. In my real use-case I was not targeting es5, I think that's just what the SWC Playground defaults to and I didn't notice it.

With regards to the `/*#__PURE__*/` directive, are you saying it needs to be included every time the template literal tag function is *used* rather than once when the tag function is *declared*?

**Comment by kdy1** [comment]
Yeap. I think what you intended is https://github.com/javascript-compiler-hints/compiler-notations-spec/blob/adeb6d0663692625f09257ed25a44e9051de9d85/no-side-effects-notation-spec.md

**Comment by jdanyow** [comment]
@kdy1 there may be a separate but similar issue where `/*#__NO_SIDE_EFFECTS__*/` has no effect in relation to tagged template literals.

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA41QPU7DMBTefYpPZYGqJAdoYYFUYoGh3V0neSEWiR3ZLwWp6sjGEeBynAS7gYgihj55sPS%2B35dOz6S8f5Cru9tMZstldrNeSTlNRdWbgrU1qLltzj07bR79DEmSbFXTk7%2FATgCOuHcGO4yAYYv9XOyFSFN8vr9iXWuP8NgRXfpaPZFB5WwLrgmtNrrSVML23PWciMIaz1C4wmbhO2WuVZhFevhu5oPox9soaiyfJDyLxJJ8p5kO%2B0lsNsFYNKfQICCKRrnAetZcR0qE%2FnMilNpRIG7pJ3EeEkfJ79R5mD%2Bpf53i1NSJoJfOOsbgUeDYpAgzmnwB5kd9bcwBAAA%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxG95wCee5QMXTIHXoIRJ2IiD9hIhVF3L1AIG03%2B33%2B9ORjYgw2kjCzo4xl8SIQhmsvhJKN4l0IoDSCZFA%2Bwm2kG9VoEZqwoXwmEEVYMbYW8TvnvQHaOcLR6Mwoq5b065TO%2BIBEleXLZYRdNf7rpq4E4157C%2FsjMXk89Q%2F4Hg1TDHuzg6LnKFY25Q%2F48FuFEwEAAA%3D%3D
