### ISSUE TITLE
Sourcemaps not generated/usable

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#828]
**Describe the bug**
Sourcemaps are not generated when `inputSourceMap` is specified.

**Input code**
```tsx
// index.tsx
import React from 'react';
import ReactDOM from 'react-dom';

const container = window.document.createElement('div');
window.document.body.appendChild(container);

ReactDOM.render(<div>App</div>, container);
```

**Config**
webpack+swc config
```js
// webpack.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const SriPlugin = require('webpack-subresource-integrity');

module.exports = {
  mode: 'development',
  entry: './src/index.tsx',
  resolve: {
    modules: [__dirname, '../../node_modules'],
    extensions: ['.tsx', '.js'],
  },
  output: {
    crossOriginLoading: 'anonymous',
  },
  module: {
    rules: [
      {
        test: /\.tsx$/,
        use: {
          loader: 'swc-loader',
          options: {
            inputSourceMap: true,
            jsc: {
              parser: {
                syntax: 'typescript',
                tsx: 'true',
              },
            },
          },
        },
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new SriPlugin({ hashFuncNames: ['sha256', 'sha384', 'sha512']}),
  ],
};
```

**Expected behavior**
Sourcemaps should allow debugging the original source. Instead, only the transformed source is visible.
![2020-06-08 at 7 36 PM](https://user-images.githubusercontent.com/7367/84099853-636a9b00-a9bf-11ea-8205-28f376e628a5.png)

**Version**
```
    "@swc/cli": "0.1.24",
    "@swc/core": "1.1.54",
    "swc-loader": "0.1.12",
```

**Additional context**

**Comment by kdy1** [comment]
Sorry, after chatting on slack, I forgot about it.
Thanks for the reminder. The fix will be trivial.

**Comment by kdy1** [comment]
Oh... Sorry, I thought I fixed it.
I tested it within swc-loader/exmaple bit I failed to verify source map because of codes related to debugging.

**Comment by duncanbeevers** [comment]
I'm also not clear on when to use the `sourceMap` directive versus `inputSourceMap` and how the `[true, false, `inline`]` values affect the option.

I see `sourceMap` in the `swc-loader` example and `inputSourceMap` elsewhere. I've tried a bunch of combinations without success, but it would be nice to understand what the directives mean and which I should be using.

**Comment by kdy1** [comment]
`inputSourceMap` is related to source map generated by previous pass (e.g. loader).

`sourceMap` is related to how swc put the generated source map with file.
Also `sourceMap: false` make swc not emit source map.
