### ISSUE TITLE
SWC output causes accessing `this` before `super()`

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#8300]
### Describe the bug

If I have a class Foo extends Bar, access `this` inside a fn decl, the output code declare a _this variable to store this, however it should not access this before super();

### Input code

```typescript
class Foo extends Bar {
    constructor() {
        super();
        for (const i of [1]) {
            test(() => {
                this.i = i
            })
        }
    }
}

function test(f){
    f()
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "env": {
    "targets": [
        "chrome >= 51",
        "edge >= 15",
        "firefox >= 54",
        "safari >= 10",
        "ios_saf >= 10"
      ],
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.98-nightly-20231117.1&code=H4sIAAAAAAAAA12MsQoCMRBE%2B3zFlEkjWMtZWPgTYnHkshiQrGQ3IEj%2B%2FXKX41BfsbDzhvHPUQRXZoS3hjQJLmPGx6DhOYnm4pWzdVu2IOUVWnLaA%2BIMu7YRwYTb8f7dX9AgatvKcP4Tq3xEOUQMiD%2Bquv2tpt9qDJXkNXLqk%2BT6HFln6gy%2Bp95ezQAAAA%3D%3D&config=H4sIAAAAAAAAA1WQTQ6CMBCF95yi6ZqFJOLCRG%2FgCYwxDUyxhFIyUwyEcHfbWrDuOu978%2FO6ZIzxlip%2BZot7umIQSIB77RSaeysmp3CotKAK1WB5vtGWPJKiIwjS%2BiW8M4ZgI1HTqldyTmdXRg8IRP9GbxV908H%2F5CxO59rUY4DxZjsPEO6jE99N0L8Th8AGrF9zjxv88hcaDex6YWWxB%2FKddRPUokxVqRCkmYL9mAISUqAKDYdUV4aejkUQ9Uf%2BS7H9xp6cK7pt0SyOkK0fVhicpaABAAA%3D

### Expected behavior

this should be accessed after super() call

### Actual behavior

```javascript
class Foo extends Bar {
    constructor(){
        var _this = this, _loop = function(i) {
            test(()=>{
                _this.i = i;
            });
        };
        super();
        for (var i of [
            1
        ])_loop(i);
    }
}
function test(f) {
    f();
}

```

### Version

1.3.97

**Comment by Austaras** [comment]
Although this doesn't directly address this issue, but you could manually set `env.bugfixes` to true to avoid this transform.
