### ISSUE TITLE
Release tag v1.3.97 disappeared from the repository

### ISSUE THREAD

**Issue by jirutka** [swc-project/swc#8307]
### Describe the bug

There used to be tag v1.3.97. We updated the swc package in Alpine Linux to 1.3.97 between 2023-11-10 and 2023-11-15, and now we find that this tag has disappeared.

Please never ever remove or recreate release tags that have already been created – they should be treated as immutable. This is a serious problem for downstreams.

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.97&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP11APycgsVsgsLi5NVShJzS3ISSxJBXIViktKCzJTFOzibdQ1Abtarn4wAAAA&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

N/A

### Version

1.3.97

**Comment by kdy1** [comment]
I removed it because the build is broken ans the release is not created properly from start

**Comment by jirutka** [comment]
So what are we supposed to do? Downgrade the swc package to 1.3.96?

**Comment by kdy1** [comment]
You can't upgrade to `v1.3.97`, see https://www.npmjs.com/package/@swc/core
It's not created at all.

The latest version is still `v1.3.96`.

**Comment by jirutka** [comment]
Please read again the description of this issue. I’ve packaged swc for Alpine Linux and already upgraded the package to 1.3.97… https://pkgs.alpinelinux.org/packages?name=swc

**Comment by kdy1** [comment]
Oh... Sorry. I'll not delete tags in the future. I never thought someone can build an automation based on the git tag

**Comment by kdy1** [comment]
And I'll restore the tag
