### ISSUE TITLE
Support stable rust

### ISSUE THREAD

**Issue by xobs** [swc-project/swc#8316]
### Describe the feature

There are a few places where `#[feature(box_patterns)]` is used, mostly in css but also in one HTML crate:

* swc_css_prefixer (#8385)
* swc_css_lints (#8384)
* swc_css_compat (#8386)
* swc_css_modules (#8381)
* swc_css_minifier (#8389)
* swc_css_parser (#8378)
* swc_html_minifier (#8380)
* swc_css_codegen (#8379)

Additionally, there is a `#![feature(type_name_of_val)]` and `#![feature(never_type)]` in swc_estree_compat.

### Additional context

`#![feature(...)]` enables nightly features, and means that such crates cannot work on stable Rust. It also means the code is susceptible to rot as the feature is adjusted, reworked, removed, or even stabilized. Removing the nightly requirement allows code to stay functional for a longer amount of time.

**Comment by kdy1** [comment]
Closing as done. Thank you, @magic-akari
