### ISSUE TITLE
SWC builds incorrect import statements for ESM when using folder import

### ISSUE THREAD

**Issue by thiagomini** [swc-project/swc#8338]
### Describe the bug

SWC infers that when we have a TS import statement like `import Foo from './folder/index.js`, it should be compiled to `import Foo from './folder'`. The issue is that this **doesn't work** for ESM, so it throws an error when we try to run that file. Notice that I've specifically set the configuration to build using ESM configuration.

```bash
yarn start                                                              thiago@DESKTOP-PGCU253
yarn run v1.22.19
$ node dist/import.js
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/thiago/Development/pessoal/swc-import-issue/dist/folder' is not supported resolving ES modules imported from /home/thiago/Development/pessoal/swc-import-issue/dist/import.js
    at new NodeError (node:internal/errors:406:5)
    at finalizeResolution (node:internal/modules/esm/resolve:227:11)
    at moduleResolve (node:internal/modules/esm/resolve:845:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  url: 'file:///home/thiago/Development/pessoal/swc-import-issue/dist/folder',
  code: 'ERR_UNSUPPORTED_DIR_IMPORT'
}
```

### Input code

```typescript
import { User } from './folder/index.js';

console.log(User);
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "esnext",
    "baseUrl": "./"
  },
  "module": {
    "type": "es6"
  },
  "minify": false
}
```

### Playground link (or link to the minimal reproduction)

https://github.com/thiagomini/swc-import-issue

### SWC Info output

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
        CPU: (20 cores)
            Models: 12th Gen Intel(R) Core(TM) i7-12700K

    Binaries:
        Node: 20.9.0
        npm: 10.1.0
        Yarn: 1.22.19
        pnpm: 8.6.7

    Relevant Packages:
        @swc/core: 1.3.99
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 5.3.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Output code should be:

```js
import { User } from './folder/index.js';
console.log(User);
```

### Actual behavior

Output code omits the `index.js` file:

Output code should be:

```js
import { User } from './folder';
console.log(User);
```

### Version

1.3.99

### Additional context

Just run `yarn start` to reproduce the error in the given repro.

**Comment by kdy1** [comment]
Set `module.resolveFully: true`
