### ISSUE TITLE
BigInt literals, nullishCoalescing, numericSeparator breaks 

### ISSUE THREAD

**Issue by radioman09** [swc-project/swc#834]
**Describe the bug**
When passing code like 
**Input code**
```js
var foo =  2n + 7n;
//Error: internal error in Neon module: not implemented: compute_line_starts(char = '2')
```
```js
var ano = { some: {
	ne:  {
		
	}
}};
var foo = ano.some.ne?.sdf?.snop;
const someValue = "test" ?? "default value";
//failed to parse module
```

**Config**
```js
var transpiledJs = swc.transformSync(js, {
	minify: true,
	jsc: {
		parser: {
			nullishCoalescing: true,
			numericSeparator: true
		}
	}
});
```

**Expected behavior**
The code should transform and compile all code without errors.

**Version**
The version of @swc/core: 
"@swc/core": "^1.1.56"

**Comment by kdy1** [comment]
To use code like

```js
var foo = ano.some.ne?.sdf?.snop;
```

 you need optional changing (not bullish coalescing)

**Comment by radioman09** [comment]
I should have been more clear. These two broke independently. I tried to compile with optional chaning first and that failed. After that, I removed the optional chaining code and added nullish coalescing code. That also failed.
```js
var foo = ano.some.ne?.sdf?.snop;
//failed to parse module
```
```js
const someValue = "test" ?? "default value";
//failed to parse module
```

**Comment by radioman09** [comment]
> To use code like
> 
> ```js
> var foo = ano.some.ne?.sdf?.snop;
> ```
> 
> you need optional changing (not nullish coalescing)

I should have been more clear. These two broke independently. I tried to compile with optional chaining first and that failed. After that, I removed the optional chaining code and added nullish coalescing code. That also failed.
```js
var foo = ano.some.ne?.sdf?.snop;
//failed to parse module
```
```js
const someValue = "test" ?? "default value";
//failed to parse module
```

**Comment by kdy1** [comment]
Hmm... Do you mean that you used 

```js
var transpiledJs = swc.transformSync(js, {
	minify: true,
	jsc: {
		parser: {
			nullishCoalescing: true,
			numericSeparator: true
		}
	}
});
```

for 

```js
const someValue = "test" ?? "default value";
```

? Then it is a bug..

**Comment by radioman09** [comment]
> Hmm... Do you mean that you used
> 
> ```js
> var transpiledJs = swc.transformSync(js, {
> 	minify: true,
> 	jsc: {
> 		parser: {
> 			nullishCoalescing: true,
> 			numericSeparator: true
> 		}
> 	}
> });
> ```
> 
> for
> 
> ```js
> const someValue = "test" ?? "default value";
> ```
> 
> ? Then it is a bug..

I just tried it again, by itself.

error: Nullish coalescing operator(??) requires jsc.parser.Coalescing
      --> <anon>:155455:12
       |
155455 | var some = "sdf" ?? "thing"
       |            ^^^^^

Error: failed to process js file

Caused by:
    failed to parse module

**Comment by kdy1** [comment]
I'll investigate this further.

**Comment by kdy1** [comment]
I found that

```js
var transpiledJs = swc.transformSync(js, {
	minify: true,
	jsc: {
		parser: {
                         // This is added
                         syntax: 'ecmascript',
			nullishCoalescing: true,
			numericSeparator: true
		}
	}
});
```

works.
