### ISSUE TITLE
optional chain  of array are wrongly transformed 

### ISSUE THREAD

**Issue by hardfist** [swc-project/swc#8355]
### Describe the bug

array.map's  this is lost when transform optional chain of array which cause 
```js
Array.prototype.map called on null or undefined
```

### Input code

```typescript
const newString = (upstream[0] as FirstStepResolvedConfig)
        ?.newProduct!.map(({ product_name }) => product_name)
        .filter(i => i !== '')
        .join('、');
```

### Config

```json
no swcrc
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA1WLsQrCMBRFd7%2FidkqyFHeJDoKz2FFEQvtanrRJSF51EEG%2F1R9RUVDvdu%2B5B0AdfBZ4OlWS2Hew0GPMksgN2%2BkOLmPFKUslFDeUQ3%2BkZhl8y52Z4JNF%2BdTXKTRjLUU5uKj1GfHd994NhIuBnf9NX7tsuRdKml8XRmEtlPrBh8Beq%2Fv1pszsAZMxWsKwAAAA&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D

### SWC Info output

no 

### Expected behavior
```js
const newString = (_a = upstream[0]) === null || _a === void 0 ? void 0 : _a.newProduct.map(({ product_name }) => product_name).filter(i => i !== '').join('、');
```

### Actual behavior
```js
var _upstream_;
var newString = ((_upstream_ = upstream[0]) === null || _upstream_ === void 0 ? void 0 : _upstream_.newProduct.map)(function(param) {
    var product_name = param.product_name;
    return product_name;
}).filter(function(i) {
    return i !== "";
}).join("、");

```
### Version

1.3.99

**Comment by magic-akari** [comment]
fixed in #8332 (v1.3.100 not published yet)
