### ISSUE TITLE
Unexpected enum variant in AssignExpr

### ISSUE THREAD

**Issue by shqld** [swc-project/swc#8377]
### Describe the bug

Expressions in `left` of `AssignExpr` are `PatOrExpr::Pat(Pat::Expr(_))` instead of `PatOrExpr::Expr(_)`, but this looks inconsistent with documentation.

https://github.com/swc-project/swc/blob/7327f257d2133ba2507990a73a11a2f58dfd826c/crates/swc_ecma_ast/src/pat.rs#L34-L36

I'm not sure if it's the documentation or the implementation that might be incorrect, or if I might have misunderstood something.

### Input code

```typescript
o.n = 42;
```

### Playground link (or link to the minimal reproduction)

https://github.com/shqld/repro/tree/swc/8376

### Expected behavior

Either documentation or implementation is corrected.

### Version

swc_ecma_ast = "0.110.12", swc_ecma_parser = "0.141.30"

**Comment by kdy1** [comment]
Reopening as I closed this by my mistake

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/swc-project/swc/pull/8604
