### ISSUE TITLE
JSX pragma not working Typescript

### ISSUE THREAD

**Issue by JonathanCallewaert** [swc-project/swc#838]
I'm working on a React App (Typescript) that is compiled using SWC. To style components, I use the ***emotion*** package (https://github.com/emotion-js/emotion). With this package, you can add a css prop to an element but this requires a JSX pragma. The example React code looks like this: 
```javascript
/** @jsx jsx */
import { jsx } from '@emotion/core';
import * as React from 'react';

const Test = () => {
   return <div css={{ height: '50px', width: '50px', backgroundColor: 'red'}} />
}
```

**Config**
My .swcrc file looks like this:
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

**Expected behavior**
The emotion package should convert the css prop to a className when build but this fails due to the JSX pragma that isn't working. I'm not sure if this is a bug or a wrong config.
The compiled output of my code looks lik this:
```javascript
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _emotion_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @emotion/core */ "./node_modules/@emotion/core/dist/core.browser.esm.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! react-dom */ "./node_modules/react-dom/index.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(react_dom__WEBPACK_IMPORTED_MODULE_2__);
/** @jsx jsx */



react_dom__WEBPACK_IMPORTED_MODULE_2__["render"](react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement('div', {
    css: {
        backgroundColor: 'blue'
    }
}, 'test'), document.getElementById('root'));
```
As you might notice jsx has not been used here
I have made an example repo which you can find here: https://github.com/JonathanCa97/SWC-Typescript-Webpack-React-Emotion

**Version**
1.1.55

**Comment by kdy1** [comment]
I'll add support for pragma after #829 is merged.
See: #107.

**Comment by JonathanCa97** [comment]
Okay thank you for the quick response :) !!

**Comment by JonathanCa97** [comment]
@kdy1 any progress on this ?

**Comment by kdy1** [comment]
@JonathanCa97 It's still blocked by #829. I'm too bust these days. Sorry for it.

**Comment by JonathanCa97** [comment]
Hi @kdy1 , sorry to insist but do you have any idea when you would have time? I would like to use SWC in a new product but I really need a Fix for this

**Comment by kdy1** [comment]
@JonathanCa97 I'll try implementing jsdoc parser now. First try was delayed by my mistake (trying to use same token system), but I'll use nom at this time, and it will not take lots of time.

Also, I think I will have spare time everyday mainly due to time difference. (Currently I'm in it)

**Comment by GuillaumeCisco** [comment]
Just came into this issue, what saved my day was putting: `"importSource": "@emotion/react"` in my `.swcrc` config file like :
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "refresh": true,
        "importSource": "@emotion/react"
      }
    }
  }
}
```

Then I can directly use `import { css } from '@emotion/react'` in my code :tada: 

Issue linked to this code: https://github.com/emotion-js/emotion/pull/2353
