### ISSUE TITLE
setting script to true crashes swc

### ISSUE THREAD

**Issue by radioman09** [swc-project/swc#839]
**Describe the bug**
When setting script: true, swc will crash.
**Input code**
var foo = 9;
**Config**
```js

var transpiledJs = swc.transformSync(js, {
	minify: true,
	script: true,
	jsc: {
		parser: {
			nullishCoalescing: true,
			numericSeparator: true,
		}
	}
});

   // Error: Error(Msg("unknown field `script`"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })


```

**Expected behavior**
 file should be parsed as a script instead of module.

**Version**
The version of @swc/core: 
v1.1.56

**Comment by kdy1** [comment]
You can use `isModule: false` instead of `script: true`. I'll close the issue from swc-website commit.
