### ISSUE TITLE
SyntaxError: Unexpected token 'with' when using import assertions

### ISSUE THREAD

**Issue by queengooborg** [swc-project/swc#8392]
### Describe the bug

When using import assertions (`import bcd from "@mdn/browser-compat-data" assert {type: "json"}`), a syntax error is thrown by Node:

```
SyntaxError: Unexpected token 'with'
  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
  at async link (node:internal/modules/esm/module_job:68:21)
```

By using `import()` instead, I'm able to bypass the problem:

```js
const { default: bcd } = await import("@mdn/browser-compat-data", {
  assert: { type: "json" },
});
```

### Input code

```typescript
import bcd from "@mdn/browser-compat-data" assert {type: "json"}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKlFISk5RSCvKz1VQcshNydNPKsovL04t0k3Ozy1ILNFNSSxJVFJILAYKlShUl1QWpFopqGcV5%2Bep1wIA3Ku0iUAAAAA%3D&config=H4sIAAAAAAAAA2VPOw6DMAzdOQXy3KFi7NYD9BBRMCiIxJFtJBDi7g0B0lbd%2FD5%2Bz16ruoZBLDzqNY0JRMOCXHBiZAlq5sQAWm%2FEsosKt0sdZJc6MwoWzvlIrE9JQeooSDIoT5jl7XCBGu5Rc6o096Y5E2EkEvxNBO%2BC65bvmyz5yCjyV%2B1N6MeyfzRWZyt4aqcsnr%2FqEncEgVoMOCt8nFdjSQcnr2s9P7O9AZ2HeVY8AQAA

### SWC Info output

Operating System:
    Platform: darwin
    Arch: arm64
    Machine Type: arm64
    Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
    CPU: (10 cores)
        Models: Apple M1 Max

Binaries:
    Node: 18.17.1
    npm: 9.6.7
    Yarn: 1.22.19
    pnpm: N/A

Relevant Packages:
    @swc/core: 1.3.100
    @swc/helpers: N/A
    @swc/types: 0.1.5
    typescript: 5.1.6

SWC Config:
    output: N/A
    .swcrc path: N/A

Next.js info:
    output: N/A

### Expected behavior

Naturally...no syntax error.

### Version

1.3.81+

### Additional context

I opened #8391 just a bit ago, but it was quickly closed and locked by a bot because I didn't post a playground link (and I didn't because import assertions aren't working in the playground altogether).  I understand the point in automatically closing an issue that is invalid -- I'm an owner of MDN's browser-compat-data, and we get a LOT of spam.  But locking the thread rubbed me the wrong way, especially as I had a valid reason for not including a playground link.  And instead of being given the opportunity to just edit the issue and add a link, I have to open a new one instead (this one) -- and because the original issue was locked, I couldn't just copy and paste the markdown into this new issue.  This experience is something I feel could, and should, be improved.

**Comment by kdy1** [comment]
The playground supports import assertions.

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKlFISk5RSCvKz1VQcshNydNPKsovL04t0k3Ozy1ILNFNSSxJVFJILAYKlShUl1QWpFopqGcV5%2Bep1wIA3Ku0iUAAAAA%3D&config=H4sIAAAAAAAAA2VPOw6DMAzdOQXy3KFi7NYD9BBRMCiIxJFtJBDi7g0B0lbd%2FD5%2Bz16ruoZBLDzqNY0JRMOCXHBiZAlq5sQAWm%2FEsosKt0sdZJc6MwoWzvlIrE9JQeooSDIoT5jl7XCBGu5Rc6o096Y5E2EkEvxNBO%2BC65bvmyz5yCjyV%2B1N6MeyfzRWZyt4aqcsnr%2FqEncEgVoMOCt8nFdjSQcnr2s9P7O9AZ2HeVY8AQAA

**Comment by queengooborg** [comment]
Thanks, it took me a bit to see what the difference was, but I see `jsc.parser.importAssertions` in the config is set to `true`.  That's probably an oversight due to the fact that I use SWC within `ts-node`.  (It's also possible that this is some swc and ts-node integration issue.)

**Comment by kdy1** [comment]
I think it's about `jsc.experimental.keepImportAttributes`. i.e. wrong config


https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKlFISk5RSCvKz1VQcshNydNPKsovL04t0k3Ozy1ILNFNSSxJVFJILAYKlShUl1QWpFopqGcV5%2Bep1wIA3Ku0iUAAAAA%3D&config=H4sIAAAAAAAAA2WQPQ6DMAyF954Cee5QMbJ17NBDpGBQaP5kGwmEuHtDgLSoW96z%2Ffk586UooOcaqmKOzyiCIkbKOjo8OVFjdABrq7gmHQSuR7XntdQqw5g9bYMnuXMEifaOY4PQgKm8bF0gijqUROXyVpY7EYz3jGciWO10O%2F1mqr0NhMx%2Fq61yncnzp404BiRtMV5joMqoN2J4bIFFSL8GwXPgy44A65shsfevkimsCpxv0OEo8O08AudwoPl5jCf08gHJrxnPewEAAA%3D%3D

**Comment by queengooborg** [comment]
If `keepImportAttributes` is on, then the resulting code is `import bcd from "@mdn/browser-compat-data";` which is an invalid import since `assert {type: 'json'}` is required for importing JSON files.  Additionally, I found out that `keepImportAttributes` was only introduced in v1.3.83, but the problem started occurring in v1.3.81 -- so `keepImportAttributes` couldn't be the culprit.

---

Turns out that the behavior of `keepImportAssertions` changed in v1.3.81, which is where the issue occurs.  In [v1.3.80](https://play.swc.rs/?version=1.3.80&code=H4sIAAAAAAAAA8vMLcgvKlFISk5RSCvKz1VQcshNydNPKsovL04t0k3Ozy1ILNFNSSxJVFJILAYKlShUl1QWpFopqGcV5%2Bep1wIA3Ku0iUAAAAA%3D&config=H4sIAAAAAAAAA32QPQ6DMAyFd06BPHeoGNk6dughIjAoNH%2ByjQRC3L0hhbSoUre8Z%2Fvzc5aiLGHgBupyic8ogiJGyjo6PDtRU3QAG6u4IR0ELkd14K3UKcOYPW2DJ7lxBIn2jmOD0IipvL67QBT1KInK1bWqdiIY7xnPRLDa6W7%2BztR4GwiZf1Zb5XqT508bcQpI2mK8xkCdUU%2FEcP8XuNgRYH07Jvb%2BVTKHTYHzLTqcBD6dR%2BAcDjQ%2FjvGEXl8itYNkewEAAA%3D%3D), the import assertions are retained and unchanged, but in [v1.3.81](https://play.swc.rs/?version=1.3.81&code=H4sIAAAAAAAAA8vMLcgvKlFISk5RSCvKz1VQcshNydNPKsovL04t0k3Ozy1ILNFNSSxJVFJILAYKlShUl1QWpFopqGcV5%2Bep1wIA3Ku0iUAAAAA%3D&config=H4sIAAAAAAAAA32QPQ6DMAyFd06BPHeoGNk6dughIjAoNH%2ByjQRC3L0hhbSoUre8Z%2Fvzc5aiLGHgBupyic8ogiJGyjo6PDtRU3QAG6u4IR0ELkd14K3UKcOYPW2DJ7lxBIn2jmOD0IipvL67QBT1KInK1bWqdiIY7xnPRLDa6W7%2BztR4GwiZf1Zb5XqT508bcQpI2mK8xkCdUU%2FEcP8XuNgRYH07Jvb%2BVTKHTYHzLTqcBD6dR%2BAcDjQ%2FjvGEXl8itYNkewEAAA%3D%3D), `assert` gets replaced with `with`, causing the syntax error.

**Comment by queengooborg** [comment]
I see...so, import assertions are converted to import attributes, but if `"emitAssertForImportAttributes": true` is specified, import attributes are converted back into import assertions.  Seems backwards to me, but eh, it works at least, and ts-node just got an update to support the new parameter.
