### ISSUE TITLE
Imported files are not included in the output when compiling from ESM to CommonJS

### ISSUE THREAD

**Issue by Arkellys** [swc-project/swc#8409]
### Describe the bug

To be honest, I don't know if it's really a bug, or if it's the expected behaviour.

I use [`swc-loader`](https://swc.rs/docs/usage/swc-loader) with `webpack`. For a project configured to use ESM, with in `package.json`:

```json
"type": "module"
```

When I try to compile for prod to `commonjs`, the imported files are just converted to `require` and not included in the output, which lead to "no module found" errors.

### Input code

```typescript
import { EXPORT_TEST } from "./constants.js";
console.log("Test export: ", EXPORT_TEST);
```

### Config

```json
{
  "jsc": {
    "parser": {
     "syntax": "ecmascript",
     "jsx": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "refresh": true,
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": true,
  "sourceMaps": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA8vMLcgvKlGoVnCNCPAPCokPcQ0OUahVSCvKz1VQ0tNPzs8rLknMKynWyypWsuYCcfNzUvVy8tM1lEJSi0sUUitA%2Bq0UlHSQTdC0BgABbYHOWAAAAA%3D%3D&config=H4sIAAAAAAAAA12OwQ2DMAxF70wR%2BdwJukEPHcIKRg3CSWQ7UhFi95IUKOolct6z%2Fb10zsGoHu5u2UoHGUVJjm8lOkfD90aAPKN6CdngdthRqzIpdKJ%2BjsjBPzgnsV02t35bwASjDkn4GiOE3i6goUFIX3%2F7qyjRAlO9CYslRgsedr12x9vigFNfJjoXg825DfrEnOKo8OsMMQzzJQ00FfH0xKwbHXBS6tYP4BdyIDIBAAA%3D

### SWC Info output

```shell 
Operating System:
    Platform: win32
    Arch: x64
    Machine Type: x86_64    
    Version: Windows 10 Home
    CPU: (8 cores)
    Models: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

Binaries:
    Node: 20.9.0
    npm: N/A
    Yarn: N/A
    pnpm: N/A

Relevant Packages:
    @swc/core: 1.3.93
    @swc/helpers: N/A
    @swc/types: 0.1.5

SWC Config:
    output: N/A
    .swcrc path: N/A

Next.js info:
    output: N/A
```

### Expected behavior

I expect imported files to be included into the output. This is what I get when I remove `"type": "module"` from `package.json`:

```js
(()=>{"use strict";var e={250:(e,r)=>{Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"EXPORT_TEST",{enumerable:!0,get:function(){return t}});var t="Successfully exported ✔️"}},r={};function t(o){var n=r[o];if(void 0!==n)return n.exports;var s=r[o]={exports:{}};return e[o](s,s.exports,t),s.exports}(()=>{var e=t(250);console.log("Test export: ",e.EXPORT_TEST)})()})();
```

`EXPORT_TEST` is correctly included as `"Successfully exported ✔️"`.

### Actual behavior

This is the output I get when `"type": "module"` is defined in `package.json`:

```js
(()=>{"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./constants.js");console.log("Test export: ",e.EXPORT_TEST)})();
```

The `import` from `"./constants.js"` is converted to `require("./constants.js")`, but this file don't exist in the bundled output.

### Version

swc-loader@0.2.3

### Additional context

When I compile to ES6 or doesn't specify `module.type`, the imported files are correctly included in the output.

**Comment by bozdoz** [comment]
I am also running into this issue, with no clear solution.

**Comment by kdy1** [comment]
You should not use `"module.type": "commonjs"` with "type": "module".
This is expected behavior
