### ISSUE TITLE
How to keep top iife warp?

### ISSUE THREAD

**Issue by noyobo** [swc-project/swc#8411]
### Describe the bug

There is a hidden danger here. The method name of the compressed _instanceof is `n`. If it is in a js context, there may be a problem that the function with the same name is overwritten. Is there any way to keep the format of iife?

### Input code

```typescript
!function() {
    function isObject(obj) {
      return obj !== null && typeof obj === 'object' && !(obj instanceof Array);
    };
    function isArray(obj) {
      return obj !== null && typeof obj === 'object' && (obj instanceof Array);
    };
    ;
    console.log(isObject({}));
    console.log(isArray([]));
}()
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "format": {
        "asciiOnly": true,
              "wrapIife": true 
      },
      "compress": {
        "inline": 0,
              "drop_debugger": false,
              "passes": 1,
      },
      "mangle": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA1NMK81LLsnMz9PQVKjmUgACmIBCZrF%2FUlZqcolGflIWTFJBoSi1pLQoTwEopqBoa6uQV5qTo6CmplBSWZCanwYWtgUKq%2BeDtaqDpBRBBihk5hWXJOYlgxQ5FhUlVmpagw2stUa3FCxLqZ1EWAkhk%2FPzivNzUvVy8tM14B6urtXUxCYNcVp0LEi2VkMTAKnvGlo8AQAA&config=H4sIAAAAAAAAA2VQu27DMAzc8xUGZw%2Fp0KV%2FkCHoJwSsTRs09AIpozUC%2F3skRXYdZCPvjncH3k9NA5N28NXc05iWgKIk%2B54QXVzEv4QAdRa1Ew4R2o2dNFNRZirI%2BiQgoowUy5F%2BVjUY75USNqBRqphlx8NyzBu8WIwHJGEplvnbmaVmtTtVBb%2BC4cIDVb6p%2FLr37LwNQqqvvuwMu3x0fnPsxYdbTz%2FzOJZ%2FHEofVAFVKZt%2BtG%2BRFt1o6OU7p8qD9f1cuPr2uIS85ZrWu0nhX7k9aC8ArNftvFivD%2BBk8ffHAQAA

### Expected behavior

keep top iife wrap.

### Version

1.3.100

**Comment by Austaras** [comment]
https://swc.rs/docs/configuration/minification#jscminifycompress
set `toplevel` to `false`
