### ISSUE TITLE
`import.meta.url` will be hard-coded when using `swc.bundle()` method

### ISSUE THREAD

**Issue by TonyL1u** [swc-project/swc#8418]
### Describe the bug

When I using `swc.bundle()` , I find that the code `import.meta.url` in my source code will be auto transformed into an absoulte path like "xxx/index.ts". But I don't want it, what can I do to avoid this behavior?

input:
![image](https://github.com/swc-project/swc/assets/31915069/aa328acb-27a2-4219-a253-879ffea3ed9f)

output:
![image](https://github.com/swc-project/swc/assets/31915069/e2912e16-014f-4700-9975-0c9f2fe009d1)
![image](https://github.com/swc-project/swc/assets/31915069/ff201e2b-04a1-4f92-aceb-91d6b7cf473d)

### Input code

```typescript
const templateDir = path.resolve(fileURLToPath(import.meta.url), '..', getTemplate(variant, jsxSupport));
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0vOzysuUShJzS3ISSxJdcksUrBVKEgsydArSi3OzylL1UjLzEkNDfIJyQ8Aimpk5hbkF5Xo5aaWJOqVFuVo6iio6%2Bmp6yikp5aEQM3QKEssykzMK9FRyCquCC4tAGnQ1LQGAIDArfRpAAAA&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D

### Expected behavior

Do not transform the code `import.meta.url` .

```js
templateDir = path.resolve(fileURLToPath(import.meta.url), "..", getTemplate(variant, jsxSupport));
```

### Actual behavior

```js
const importMeta = {
    url: "xxx/index.ts",
    main: false
};

templateDir = path.resolve(fileURLToPath(importMeta.url), "..", getTemplate(variant, jsxSupport));
```

### Version

1.3.100

**Comment by kdy1** [comment]
We are not actively maintaining the bundler. https://swc.rs/docs/usage/bundling
