### ISSUE TITLE
loose transform spread syntax with Iterator error

### ISSUE THREAD

**Issue by BaffinLee** [swc-project/swc#8425]
### Describe the bug

Loose transform spread symbol `...` with Iterator output the wrong code, for example：
input：
```javascript
const a = new Map();
const b = [...a.values()];
```

output:
```javascript
var a = new Map();
var b = [].concat(a.values());
```

`Map.values()` returns [Iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator), which is **NOT** a real Array, and use with Array.concat will get unexpected result.

### Input code

```typescript
const a = new Map();
const b = [...a.values()];
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0vOzysuUUhUsFXISy1X8E0s0NC05koGCyYBBaP19PQS9coSc0pTizU0Y60BbxzM2C8AAAA%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxGd06BPHdth94hh7CoExHxJ0ykoih3LyFA2w2%2Fz%2FYzu5ASVlbwlHt5liJgZIqjLoSzS%2FguBEhZZBV1SHDr6cpnNKNhqui4EkgYF0p1iu%2BtHYz3TIWluFFDVjs951%2Bf8jZEYu5rh8qiWwz920QzgvWvrYbtHykHuuwP%2BDZ12VgMmqc%2BeV4ljg%2F3WmjeEwEAAA%3D%3D

### Expected behavior

Expect swc consume Iterator object, and transform it to an real Array object, just like compile without loose option

```javascript
var a = new Map();
var b = _to_consumable_array(a.values());
```

[swc playground about the right case](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0vOzysuUUhUsFXISy1X8E0s0NC05koGCyYBBaP19PQS9coSc0pTizU0Y60BbxzM2C8AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D)

### Version

1.3.100

**Comment by Austaras** [comment]
This is expected when `loose` is set to true.

**Comment by BaffinLee** [comment]
> This is expected when `loose` is set to true.

Why you expect **WRONG** code that won't work ? You transform the code to a totally different result, I don't get it.

It's not about the code style, it's totally wrong, the code after swc handered will cause error.

Are you sure?

**Comment by BaffinLee** [comment]
> This is expected when `loose` is set to true.

The code swc generated is **totally wrong**.

```javascript
// ['value']
[...(new Map([['key', 'value']])).values()]

// [MapIterator]
[].concat(new Map([['key', 'value']]).values())
```

**Comment by magic-akari** [comment]
Yes, it is incorrect, and this is expected behavior. This is what the term "loose" implies, encompassing a range of assumptions, including [`iterableIsArray`](https://babeljs.io/docs/assumptions#iterableisarray). In this situation, you should set `loose` to false.

**Comment by BaffinLee** [comment]
> Yes, it is incorrect, and this is expected behavior. This is what the term "loose" implies, encompassing a range of assumptions, including [`iterableIsArray`](https://babeljs.io/docs/assumptions#iterableisarray). In this situation, you should set `loose` to false.

Thank you for your clarification, this is still confusing and will cause bug hard to locate. Is it possible to support options in `env.include` so that we can opt-out loose mode for spread syntax only, like this way:

https://swc.rs/docs/configuration/compilation#envinclude

```json
{
    "env": {
        "include": [
            "transform-async-to-generator",
            "transform-regenerator",
            ["transform-spread", {
                "loose": false,
            }],
        ],
    },
}
```

**Comment by kdy1** [comment]
Disabling loose mode only for specific syntax is already possible using `assumptions`

**Comment by BaffinLee** [comment]
> Disabling loose mode only for specific syntax is already possible using `assumptions`

That's good to hear! But I don't think I can find details about `assumptions` in document. Could you share a link about this? Thanks.
