### ISSUE TITLE
Why doesn't the method exported by @swc/helpers include es6 polyfill

### ISSUE THREAD

**Issue by LinsRock** [swc-project/swc#8445]
### Discussed in https://github.sheincorp.cn/swc-project/swc/discussions/8444

<div type='discussions-op-text'>

<sup>Originally posted by **LinsRock** December 21, 2023</sup>
When I set env. targets to "chrome>40, safari>10", the build will import core-js polyfill and @swc/helpers, However, the method exported by @swc/helpers also contains es6 syntax and does not have a polyfill, which will make it impossible to run on the target browser

For example：

```javascript
const add = () => {
  const list = new Set()

  list.add(1)
  list.add(2)

  return [...list].reduce((a, b) => a + b, 0)
}
```

swc post-construct：

```javascript
import { _ } from '@swc/helpers/_/_to_consumable_array';
import 'core-js/modules/es.set.js';
import 'core-js/modules/es.array.iterator.js';
import 'core-js/modules/web.dom-collections.iterator.js';
import 'core-js/modules/es.object.to-string.js';
import 'core-js/modules/es.array.reduce.js';

var add = function() {
    var list = new Set();
    list.add(1);
    list.add(2);
    return _(list).reduce(function(a, b) {
        return a + b;
    }, 0);
};
```

The @swc/helpers/_/_to_consumable_array implementation uses es6's Array.from without adding the corresponding polyfill
An error occurs when running an earlier version of the browser：**Array.from is not a function**

Same for **iterableToArray** implementation
@swc/helpers@0.5.3：
```javascript
"use strict";

exports._ = exports._iterable_to_array = _iterable_to_array;
function _iterable_to_array(iter) {
    if (typeof Symbol !== "undefined" && iter[Symbol.iterator] != null || iter["@@iterator"] != null) {
        return Array.from(iter);
    }
}
```

@babel/runtime-corejs3@7.23.6：
```javascript
var _Symbol = require("core-js-pure/features/symbol/index.js");
var _getIteratorMethod = require("core-js-pure/features/get-iterator-method.js");
var _Array$from = require("core-js-pure/features/array/from.js");
function _iterableToArray(iter) {
  if (typeof _Symbol !== "undefined" && _getIteratorMethod(iter) != null || iter["@@iterator"] != null) return _Array$from(iter);
}
module.exports = _iterableToArray, module.exports.__esModule = true, module.exports["default"] = module.exports;
```

**Comment by Austaras** [comment]
This behavior is copied from babel and it's intentional, see babel/babel#5682

**Comment by LinsRock** [comment]
> This behavior is copied from babel and it's intentional, see [babel/babel#5682](https://github.sheincorp.cn/babel/babel/issues/5682)

I don't quite understand why this is so, but right now babel is used to automatically handle Array.from in the helper. swc seems to be having problems at the moment. Is there any way swc can handle es6 syntax in the helper

This is my .swcrc
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "tsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "externalHelpers": true
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "chrome>40,safari>10",
    "mode": "usage",
    "coreJs": "3.33"
  }
}
```

**Comment by Austaras** [comment]
Yes, but that's @babel/runtime-corejs3, not @babel/runtime. The former has been passed through a polyfill pass while the latter doesn't. It could be beneficial for swc to also have multiple package, but the interest is diminishing as there're fewer and fewer people who still use es5. Anyway, @kdy1 what's your opinion?

**Comment by kdy1** [comment]
I also think it's a bit beneficial but the benefit is diminishing too fast to have another set of packages.
