### ISSUE TITLE
Lottie animation failed in 1.3.101

### ISSUE THREAD

**Issue by JiangWeixian** [swc-project/swc#8455]
### Describe the bug

Lottie animation failed in 1.3.101, but worked fine in 1.3.00 version

### Input code

```typescript
see playground link
```

### Config

```json
see playground link
```

### Playground link (or link to the minimal reproduction)

https://github.com/JiangWeixian/swc_lottie_repo

### SWC Info output

Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Max

    Binaries:
        Node: 18.18.0
        npm: 9.8.1
        Yarn: N/A
        pnpm: 7.23.0

    Relevant Packages:
        @swc/core: 1.3.101
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 4.6.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Animation should work

### Actual behavior

Empty display

### Version

1.3.101

### Additional context

https://github.com/JiangWeixian/swc_lottie_repo

**Comment by Austaras** [comment]
Can you try swc nightly? This is likely fixed by #8442

**Comment by JiangWeixian** [comment]
Looks like fixed in `v1.3.102`, one more question, did this bad case already add into unit test?
