### ISSUE TITLE
I am using cypress along with next.js, cypress/code-coverage and swc-plugin-coverage-instrument. But it is giving me error when running npm run dev and npx run cypress opem

### ISSUE THREAD

**Issue by Jyoti-Yadav1** [swc-project/swc#8457]
**Error when running npm run dev**:-
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

thread 'thread '<unnamed>' panicked at '<unnamed>' panicked at 'thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', called `Result::unwrap()` on an `Err` value: LayoutError', called `Result::unwrap()` on an `Err` value: LayoutError', /Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:/Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67/Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm` as js transform plugin at /Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm
    1: RuntimeError: unreachable
    2: unreachablefailed to invoke plugin: failed to invoke plugin on 'Some("/Users/jyotiyadav/Desktop/web-dubuy-express/pages/_app.tsx")'

Caused by:
    0: failed to invoke `/Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm` as js transform plugin at /Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/swc-plugin-coverage-inst', rument/target/wasm32-wasi/release/swc_plugin_coverage.wasm
    1: RuntimeError: unreachable
    2: unreachablethread '/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.226.26/src/plugin.rs:', 216:<unnamed>14' panicked at '
failed to invoke plugin: failed to invoke plugin on 'Some("/Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/next/dist/client/next-dev.js")'
<img width="1051" alt="Screenshot 2023-12-29 at 1 28 10 PM" src="https://github.com/swc-project/swc/assets/52700059/8b65d33b-bda6-4f5f-a6f7-4aa0cc9324b2">

**Error when running npx run cypress open:-**
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/jyotiyadav/Desktop/web-dubuy-express/public' directory
thread 'thread '<unnamed>' panicked at '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', called `Result::unwrap()` on an `Err` value: LayoutError/Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:', thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', 266:67/Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67/Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:
266:67

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/jyotiyadav/Desktop/web-dubuy-express/cypress/component/useGetOtp.cy.tsx")'

Caused by:
    0: failed to invoke `/Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm` as js transform plugin at /Users/jyotiyadav/Desktop/web-dubuy-express/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm
    1: RuntimeError: unreachable
    2: unreachable

Stack backtrace:
   0: _wasmer_vm_raise_trap
   1: _wasmer_vm_raise_trap
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.226.26/src/plugin.rs:216:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/jyotiyadav/Desktop/web-dubuy-express/cypress/component/useFetchArea.cy.tsx")'

<img width="1057" alt="Screenshot 2023-12-29 at 1 31 04 PM" src="https://github.com/swc-project/swc/assets/52700059/c5d83148-32d5-4c35-aae8-d47d940bd67c">

**Package.json file**

"dependencies": {
    "@dpw/ecomm-ui": "0.0.26",
    "@formkit/auto-animate": "1.0.0-beta.5",
    "@newrelic/next": "0.3.0",
    "@tailwindcss/line-clamp": "0.4.2",
    "@tanstack/react-query": "4.16.1",
    "@tanstack/react-query-devtools": "4.16.1",
    "@tanstack/react-table": "8.5.22",
    "@types/ua-parser-js": "0.7.36",
    "axios": "0.27.2",
    "clsx": "1.2.1",
    "embla-carousel-react": "7.0.2",
    "express": "4.18.2",
    "i18next": "21.8.14",
    "i18next-browser-languagedetector": "6.1.4",
    "next": "12.3.1",
    "node-cache": "5.1.2",
    "node-schedule": "2.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "7.39.5",
    "react-i18next": "11.18.1",
    "tailwind-merge": "1.5.1",
    "tailwindcss": "3.1.7",
    "ua-parser-js": "1.0.32"
  },
  "devDependencies": {
    "@bgotink/playwright-coverage": "0.1.3",
    "@cypress/code-coverage": "^3.12.15",
    "@next/bundle-analyzer": "12.2.5",
    "@percy/playwright": "1.0.4",
    "@playwright/test": "1.24.2",
    "@types/node": "17.0.35",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.5",
    "autoprefixer": "10.4.7",
    "cypress": "^13.6.1",
    "dotenv": "^8.2.0",
    "eslint": "^8.21.0",
    "eslint-config-next": "^12.2.4",
    "eslint-config-prettier": "^8.5.0",
    "husky": "^8.0.1",
    "lint-staged": "13.0.3",
    "postcss": "8.4.14",
    "prettier": "2.7.1",
    "swc-plugin-coverage-instrument": "^0.0.20",
    "tailwindcss": "3.2.7",
    "typescript": "4.7.2"
  },

**next.config.js configuration**
 experimental: {
    swcPlugins: [['swc-plugin-coverage-instrument', {}]]
  },
  reactStrictMode: true,
  assetPrefix: envConfig.ASSET_URL,

@kwonoj  , and everyone , Thanks a lot in advance in resolving this

**Comment by kwonoj** [comment]
This is not a @swc/core issue, it's plugin issue.

**Comment by Jyoti-Yadav1** [comment]
@kwonoj  Is there any suggested way to use "swc-plugin-coverage-instrument" for instrumentaion along with cypress code coverage?
