### ISSUE TITLE
Failed to transform CSS modules with :global in some cases:  .foo:global(.bar).baz {}

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/swc#8461]
### Describe the bug

Currently SWC CSS modules fail to transpile

```css
 .foo:global(.bar).baz {}
```

but do transpile follow ing successfully

```css
 .foo :global(.bar).baz {}
```

You can reproduce this in SWC repo by adding the following code:

![image](https://github.com/swc-project/swc/assets/57202839/6adbeec1-17a6-4473-ab71-2326c79914be)

notice the last item has been stripped

### Input code

```typescript
Input


.foo:global(.bar).baz {}


Output like:

```css
._local_foo.bar {
    color: white;
}
```
```


### Config

_No response_

### Playground link (or link to the minimal reproduction)

https://github.com/swc-project/swc/tree/main/crates/swc_css_modules/tests/fixture/modules/pure

### SWC Info output

_No response_

### Expected behavior

```css
 ._local_foo.bar._local_baz {}
```

### Version

latest

**Comment by zDaoYang** [comment]
@kdy1 
I have met the same issue
Is there any progress

**Comment by emosheeep** [comment]
same problem here, any progress?🙏
