### ISSUE TITLE
Option to preserve ?? operator

### ISSUE THREAD

**Issue by ryuhhnn** [swc-project/swc#847]
**Describe the bug**

When using the nullish coalescing operator, the swc compiler will transpile it down to be compatible with previous versions of ECMAScript even when the `"nullishCoalescing": true` option in the config file is set. This is problematic because if nullish coalescing is used on object properties where the parent object may not exist, you'll get a reference error: `ReferenceError: X is not defined` on the transpiled output.

**Input code**

```js
const foo = someObjectThatDoesntExist.prop ?? "";

// I expect the value of foo to be "" here
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "decorators": true,
      "decoratorsBeforeExport": true,
      "classProperty": true,
      "nullishCoalescing": true,
      "optionalChaining": true
    },
    "target": "es2019"
  }
}
```

**Expected behavior**
Nullish coalescing should be preserved in compiled output when the `"nullishCoalescing": true` config option is set.

**Version**
```
@swc/cli@^0.1.24
@swc/core@^1.2.2
```

**Comment by kdy1** [comment]
I'll fix this and #846 when my final exam is over. I guess I'll fix it this weekend.

**Comment by kdy1** [comment]
`nullishCoalescing: true` is an option to enable transcompiling, and swc is working as intended.

Why do.you want to preserve `??` in output? I may add support for printing it as-is if there's a use case.


Also, 

> This is problematic because if nullish coalescing is used on object properties where the parent object may not exist, you'll get a reference error: ReferenceError: X is not defined on the transpiled output.

ReferenceError is correct behavior for the code

**Comment by ryuhhnn** [comment]
Thank you so much!
