### ISSUE TITLE
 swc v1.3.102 minify broke antd theme

### ISSUE THREAD

**Issue by nuintun** [swc-project/swc#8475]
### Describe the bug

Minify code with swc.

https://github.com/ant-design/ant-design/issues/46719

![image](https://github.com/swc-project/swc/assets/1730277/19ce1607-fb2b-4711-8f81-79cee44aa91f)

### Playground link (or link to the minimal reproduction)

https://github.com/ant-design/ant-design/issues/46719

### Expected behavior

Fix code minify.

### Version

1.3.102

**Comment by kdy1** [comment]
@nuintun Is v1.3.102 the first version that breaks antd theme?

**Comment by nuintun** [comment]
@kdy1 I tested and found that it started from v1.3.99.

**Comment by MadCcc** [comment]
The main cause is swc bundle differs between es5 and es6.

@ctrl/tinycolor targets `es2021` in 4.x, which makes the artifacts differ:

```
// 4.x
const CSS_INTEGER = '[-\\+]?\\d+%?';
const CSS_NUMBER = '[-\\+]?\\d*\\.\\d+%?';
const CSS_UNIT = `(?:${CSS_NUMBER})\|(?:${CSS_INTEGER})`;

// 3.x
var CSS_INTEGER = '[-\\+]?\\d+%?';
var CSS_NUMBER = '[-\\+]?\\d*\\.\\d+%?';
var CSS_UNIT = "(?:".concat(CSS_NUMBER, ")\|(?:").concat(CSS_INTEGER, ")");
```

And when swc bundle template string, the result will be escaped one more time, `[-\\+]` will become `[-\\\\+]`, which is broken.

**Comment by nuintun** [comment]
https://play.swc.rs/?version=1.3.98&code=H4sIAAAAAAAAA0vOzysuUUhUsFVQj4lRt%2BZKBvOTgPwElerE2gRrLrBQfk6qXk5%2BukaSJgBb5y21MQAAAA%3D%3D&config=H4sIAAAAAAAAA32UO3LjMAxA%2B5zCozrFjostcoDtcgYOLYIyshShIUDHmozvvtDHXieG3El4%2BBG%2Fr5fdrvngtnnbfemn%2Fgy%2BMJTbv0p4zOLPKmlkHIDbgoM0r1cqPKHoE8MsuiykSUQMV7LKeswYx3vfLfVDAeY7mUp96WoPWfi7%2FcoKfU5ASr2XH4gS%2BPyEOM8Os0AHxXLcUkp%2BYHAnXwwvU6a%2BIJMVYoJVILih0GDyHFCQssZ8pAF8cC0FMBAWaAVPYJlpLDXLrM8z3jPjAIfadXM%2Ff1jDyafqxYgJ57klmq3h9UjI4mLNVgkXuFGDBa7F%2FWmJ0RWQWvKj3Qdh3ujJXwCtQPLM2fdg%2BZ01os7TlnV8aok56sjKaHCdb%2BuVGTotqkOMRmWnykARtLpZINQWpsq2Vjor3igfYwAHMeqsGK75E6U9WkGnhaZoAO2vj9ZULcDdtnCDTwvxBP%2FRV4o9YKtG7%2BW4TXnsD5SeBOhBjhSeKGgrhLZx0StxHrZ5zQF0NCCYKpVn8HgEdAGEXAKxZkPXQz26LtHh%2F5lYFS7fbqvoQM8%2BGuD9r%2F2%2BeVlZ01Oo8zVYr%2FnU4EXv953S9QzfMm%2BQ36%2BWc9TLP4kAIlsZBgAA
