### ISSUE TITLE
ios_saf as target in object notation causes panic

### ISSUE THREAD

**Issue by Themezv** [swc-project/swc#8492]
### Describe the bug

`ios_saf` is unsupported target in swc preset env and causes panic.

jfyi its supported by https://github.com/browserslist/browserslist-rs

```
$: cargo run --example inspect -- 'ios_saf 14'                                                         
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
    Running `target/debug/examples/inspect 'ios_saf 14'`
ios_saf 14.0-14.4
```

### Input code

```typescript
// Doesn't matter
console.log(Promise.resolve)
console.log(globalThis)
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": false
        },
        "loose": false,
        "minify": {
            "compress": false,
            "mangle": false
        }
    },
    "module": {
        "type": "es6"
    },
    "minify": false,
    "isModule": true,
    "env": {
        "targets": {
            "chrome": 109,
            "ios_saf": "14"
        },
        "coreJs": "3.21",
        "mode": "usage"
    }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.102&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1wgoys%2FNLE7VK0oFCpWlanIlI0mm5%2BQnJeaEZGQWawIAoy6w3DQAAAA%3D&config=H4sIAAAAAAAAA21QSw6CMBDdcwoya2NEjYkewcQzmKYMWEJb0ilGQri7tFotn%2B765n3mTZ%2Bk44OKOFzS3n880DBDaCaYx6lTlr1GHJBLRtyIxsJmyqnIEQpWE%2F4Gw58DtdaEgRHhUihRdMtMrmVjkGgp%2BciYKmtcJiZRLkidt54UdbRdg74JnWBKDotEcSDoFjysaQOK6jkzZaZESystHkZLp85251kDoelOrHC7ZEdYvRnXBq%2FOFQ7bfQbx1XTuW7TESvz2SIY3D3lA6dgBAAA%3D

### Expected behavior

`ios_saf` can be used as target

### Actual behavior

preset_env_base panicked because ios_saf not implemented 
`panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/preset_env_base-0.4.9/src/query.rs:124:13:
not implemented: Targets: {"ios_saf": Query(Single("14")), ....`

### Version

1.3.102

**Comment by Themezv** [comment]
Some other targets causes panic too. 
For example: `Samsung` but `samsung` is acceptable

**Comment by kdy1** [comment]
Config is wrong. 

https://play.swc.rs/?version=1.4.1-nightly-20240207.2&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1wgoys%2FNLE7VK0oFCpWlanIlI0mm5%2BQnJeaEZGQWawIAoy6w3DQAAAA%3D&config=H4sIAAAAAAAAA2VQyw6CMBC88xVkz8YENR78BBO%2FwWzqQkroI91CJIR%2Ft1SrRXrrzOzOzE5FGR60LOBSTvETAYuOya2wiPOoPT4DDiQUsnDSetitNS0vgho7pi8x%2FzTQGcOUFBmupJb1uPUURllHzNuR9xjqpqOtY5H5gjKPPoqyjn60FJvwGdbiFCSzA8m3tMO7PqGkh7%2Bl6BryS1aQhu%2BMdVmdsguFNo6ukT%2FuD1XOhIwxT8%2FY0CdRMb8AWX72gaIBAAA%3D
