### ISSUE TITLE
0xa0 should be treated as a valid space in js code

### ISSUE THREAD

**Issue by xc2** [swc-project/swc#8499]
### Describe the bug

compile failed due to `0xa0` spaces

### Input code

```typescript
// the spaces in the next line is `0xa0` but not `0x20`
if (true) console.log(1)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAAx3HwQ2AIAwAwL9T9AkfQScCSdUmpDW2JozDLExm9H4XAtiJoFcuqED8j7EZVGIEUkix5ZhgewxY7Osa00T76M7uB%2F3oRVil4lzlcIt%2FAeWmDMtSAAAA&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYygZyCxKLi1CI4HyhSXJlXklgBFFFKTc5NLE4uyiwoUdKByWYVg6TSEnOKU8FCtRAZpZLEovTUErCuYlOocqWc%2FPziVCTltVy1ACq%2FqW6CAAAA

### Expected behavior

as is or change `0xa0` to `0x20`

```js
if (true) console.log(1);
```

### Actual behavior

```
  x Expected ';', '}' or <eof>
   ,-[input.js:1:1]
 1 | // the spaces in the next line is `0xa0` but not `0x20`
 2 | if (true) console.log(1)
   : ^^^^^|^^^^  ^^^^^^^
   :      `-- This is the expression part of an expression statement
   `----


Caused by:
    0: failed to process js file
    1: Syntax Error
```

### Version

1.3.100

### Additional context

Babel works: [playground](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYMwBQFALgTgrgUwJRgMYHsB2BndAbBAOj3QHMIBGJIA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=&prettier=false&targets=&version=7.23.8&externalPlugins=&assumptions=%7B%7D)

tsc works: [playground](https://www.typescriptlang.org/play?#code/JYMwBQFALgTgrgUwJRgMYHsB2BndAbBAOj3QHMIBGJIA)

**Comment by magic-akari** [comment]
Fixed in #8483 , will be released in 1.3.103 .
