### ISSUE TITLE
Unable to create a working plugin based on https://swc.rs/docs/plugin/ecmascript/getting-started

### ISSUE THREAD

**Issue by Artur-** [swc-project/swc#8504]
### Describe the bug

```
cargo install swc_cli
swc plugin new --target-type wasm32-wasi my-first-plugin
rustup target add wasm32-wasi
cd my-first-plugin
cargo build-wasi --release
```

results in
```
   Compiling my-first-plugin v0.1.0 (/.../my-first-plugin)
error: no rules expected the token `r#"console.log("transform");"#`
   --> src/lib.rs:47:5
    |
47  |     r#"console.log("transform");"#
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
    |
note: while trying to match `ok_if_code_eq`
   --> /.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_testing-0.138.10/src/lib.rs:415:61
    |
415 |     ($syntax:expr, $tr:expr, $test_name:ident, $input:expr, ok_if_code_eq) => {
    |                                                             ^^^^^^^^^^^^^

error: could not compile `my-first-plugin` (lib) due to previous error
```

### Playground link (or link to the minimal reproduction)

-

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Max

    Binaries:
        Node: 20.9.0
        npm: 10.1.0
        Yarn: N/A
        pnpm: N/A

    Relevant Packages:
        @swc/core: N/A
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The plugin builds

### Version

?

**Comment by kdy1** [comment]
v1.3.104 should fix this.

https://github.com/swc-project/swc/blob/585c24fc72c11aa4f8673d6c4e8eb8c691603cda/CHANGELOG.md#13104---2024-01-17
