### ISSUE TITLE
Migrate neon to napi-rs

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#852]
Started at https://github.com/napi-rs/node-rs/pull/34

## Benefits

- Minimal overhead
- Stable native API, easy to release [Releases](https://github.com/napi-rs/node-rs/releases)

First benchmark in my local machine

```bash
swc (es3) x 695 ops/sec ±1.92% (82 runs sampled)
swc (es5) x 699 ops/sec ±1.14% (83 runs sampled)
swc (es2015) x 667 ops/sec ±1.70% (85 runs sampled)
swc (es2016) x 1,654 ops/sec ±1.62% (84 runs sampled)
swc (es2017) x 1,630 ops/sec ±2.06% (85 runs sampled)
swc (es2018) x 2,177 ops/sec ±1.63% (88 runs sampled)
@node-rs/swc (es2018) x 5,538 ops/sec ±1.04% (86 runs sampled)
swc-optimize (es3) x 1,555 ops/sec ±1.31% (85 runs sampled)
babel (es5) x 32.78 ops/sec ±4.99% (52 runs sampled)
```

**Comment by kdy1** [comment]
@Brooooooklyn Does it support invoking javascript function from rust (in a thread created by rayon) and awaiting promise from rust (again, within any thread)?

I was considering switching to node-bindegen, but I'm open with other options, if the features above are implemented in a easy-to-use manner.

**Comment by Brooooooklyn** [comment]
> Does it support invoking javascript function from rust 

`ThreadSafeFunction` has not been implemented yet, I'm planning to finish it in this month.

But you can spawn task to `libuv` thread via [napi_create_async_work](https://nodejs.org/api/n-api.html#n_api_napi_create_async_work), see https://github.com/napi-rs/node-rs/pull/34/files#diff-ec133f03d8eaec6d1f6e2e0bffee7e50R64

`node-bindegen` is a great library, but the overhead is still too large if you are considering about performance: https://github.com/jdsaund/rust-node-perf

**Comment by kdy1** [comment]
@Brooooooklyn I think the benchmark does not fit for swc. The benchmark is about adding two numbers, but swc does lots of things in the background task.

I didn't update the README.md because I'm too lazy to do it, swc is 20+ faster than babel even with neon. Clearly, ffi overhead is a bottleneck in swc, but I'm not sure if it worths migration.

**Comment by Brooooooklyn** [comment]
> I didn't update the README.md because I'm too lazy to do it

The benchmark I mentioned above is produced in my machine right now... and it's over two times faster `@node-rs/swc (es2018) x 5,538 ops/sec ±1.04% (86 runs sampled)` vs `swc (es2018) x 2,177 ops/sec ±1.63% (88 runs sampled)` if my implement is not wrong. I think this gain of performance is really worth to consider about. Especially `napi-rs` won't bring more effort in native side.

> The benchmark is about adding two numbers, but swc does lots of things in the background task

I agree with this point, and I'm planning to setup more benchmark suites in `napi-rs` project.

**Comment by kdy1** [comment]
@Brooooooklyn Wow, it's cool. I'll see how much performance differs in the case of almost all work being done on native.

**Comment by Brooooooklyn** [comment]
> Does it support invoking javascript function from rust

`napi@0.4` support it now

**Comment by kdy1** [comment]
@Brooooooklyn Is there any documentation?
I want to improve swc and spack.

**Comment by Brooooooklyn** [comment]
I will write a simple guide in this week, and you can also find the api use cases in this project: https://github.com/napi-rs/node-rs

**Comment by kdy1** [comment]
@Brooooooklyn Can you help migration?
How can I expose a class from rust code?

**Comment by kdy1** [comment]
@Brooooooklyn Also, do you have a plan to provide an alternative `neon_serde`? `swc` requires passing object from each side to the other side

**Comment by Brooooooklyn** [comment]
> How can I expose a class from rust code

I will write an example tonight.

BTW. I don't think we need define class in rust side. `OnceCell` is enough for `swc` like this: https://github.com/Brooooooklyn/swc-node/blob/master/src/lib.rs#L63

> Do you have a plan to provide an alternative neon_serde

Yes. I will implement it in next week.

**Comment by Brooooooklyn** [comment]
https://github.com/napi-rs/napi-rs/blob/master/test_module/src/class.rs
here is an minimal example that show how to implement `JsClass` in `Rust`. The API is verbose than `neon` now, but I will reduce the noise in `napi-derive` crate soon.

**Comment by kdy1** [comment]
> BTW. I don't think we need define class in rust side. OnceCell is enough for swc like this:

It's right, but I want to reduce semantic changes.

> Yes. I will implement it in next week.

Good to hear. Thanks!

**Comment by Brooooooklyn** [comment]
> Yes. I will implement it in next week.

I may not have time in this month. I'm busy to push `@swc-node/jest` landing in my company projects and community projects. There are a lot of codes could not work as `ts-jest` (test failed or syntax error), I will continue to fix them in next period of time.

**Comment by kdy1** [comment]
Thanks for the notice. And it's okay, I can do it. 

Currently I'm working on a jsdoc parser and jsx pragma support, and I'll implement css support quickly after it.
Then, I'll switch to napi. If I manage to start working on it before you do it, I'll implement `napi-serde`.


Btw, I'm really happy to see swc used in company projects :)
If migration is successful, may I list your company on the swc user list?

**Comment by Brooooooklyn** [comment]
> If migration is successful, may I list your company on the swc user list?

Sure, and you can do it now, we have tons of code repos, and some of it has migrated successfully yet.

Site: https://www.bytedance.com

**Comment by kdy1** [comment]
Thanks! I updated the site :)

**Comment by kdy1** [comment]
@Brooooooklyn How can I send JsFunction to another thread?
I want js function to return `Promise<string> | string` and rust thread to wait for it.

**Comment by Brooooooklyn** [comment]
There is `Task` trait: https://github.com/Brooooooklyn/swc-node/blob/master/src/lib.rs#L70
And the `Env.spawn` take a `Task` and return `Promise` object.
`napi-rs` spawn the task to `libuv thread pool` under the hood.

See https://github.com/Brooooooklyn/swc-node/blob/master/src/lib.rs#L124 for example

**Comment by kdy1** [comment]
Thanks but I want to call javascript functions from rust and wait for it if it returns a promise.
Can I do it?

**Comment by Brooooooklyn** [comment]
`TheadsafeFunction` can let you call javascript functions in any thread. But the exposed API is `callback` not `Promise` because you can call the javascript  function any times.

See [rust](https://github.com/napi-rs/napi-rs/blob/master/test_module/src/napi4/tsfn.rs#L18) and [javascript](https://github.com/napi-rs/napi-rs/blob/master/test_module/__test__/napi4/threadsafe_function.spec.ts#L16) for example

**Comment by kdy1** [comment]
@Brooooooklyn 
How can I cast `JsObject` / `JsUnknown` to other js types? I looked at the tests, but I failed to find one. I'm currently trying to write deserializer

**Comment by kdy1** [comment]
Nevermind, I'll go with JsBuffer + serde_json

**Comment by Brooooooklyn** [comment]
> Nevermind, I'll go with JsBuffer + serde_json

haha,accord to my test, the performance is close between (Buffer + serde) and (serde serialize)

**Comment by kdy1** [comment]
Sounds great! Thank you very much for a good library.

**Comment by Brooooooklyn** [comment]
Maybe you should rerun benchmark and update the result on README. I see great improvement after upgrading to `@swc/core@1.2.22`

**Comment by m1212e** [comment]
> `TheadsafeFunction` can let you call javascript functions in any thread. But the exposed API is `callback` not `Promise` because you can call the javascript function any times.
> 
> See [rust](https://github.com/napi-rs/napi-rs/blob/master/test_module/src/napi4/tsfn.rs#L18) and [javascript](https://github.com/napi-rs/napi-rs/blob/master/test_module/__test__/napi4/threadsafe_function.spec.ts#L16) for example

The links you posted are broken and it would be awesome for future people which come here if you could update them!

**Comment by Brooooooklyn** [comment]
@m1212e updated
