### ISSUE TITLE
plugin-emotion still does not work uniformly

### ISSUE THREAD

**Issue by DavideDaniel** [swc-project/swc#8529]
### Describe the bug

This isn't a new issue. It's still https://github.com/swc-project/swc/issues/5453
Best guess is fix was done assuming there's a node_modules folder and anytime there isn't one the plugin doesn't work.

```sh
failed to get the node_modules path
```

### Playground link (or link to the minimal reproduction)

https://github.com/pietrop/cra-swc-emotion-plugin-example

### SWC Info output

   Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031
        CPU: (16 cores)
            Models: Apple M3 Max

    Binaries:
        Node: 18.19.0
        npm: 10.2.3
        Yarn: 3.7.0
        pnpm: N/A

    Relevant Packages:
        @swc/core: N/A
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 4.4.4

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

plugin-emotion should work as documented

### Version

@swc/plugin-emotion@2.5.110

### Additional context

While I added the swc info output, it's not really accurate since we are using .swcrc from within scoped packages for the company I work at since there's an internal tool that needs to share configs across many repos. There are .swcrc but only 3 flavors at the moment, CJS, ES, and TS. This is all to work around the fact that to replace babel-cli I have to use swc-cli but unlike babel having babel.config.js we have to create multiple rc files (and set them json and use require.resolve on those).

Tested on:
node:
v14
v16
v18

yarn: 
3.2.0-rc.2
3.4.0
3.7.0

**Comment by DavideDaniel** [comment]
Ok I have more info to share as well as something I did to work around. I'll try to share as much as I can.

From what I can glean, the problems are related to how lifecycle scripts are being used in rust based projects like `swc` and `yarn` and `pnpm`. Because postinstall scripts allow downloading of binaries and those are being referenced plugins need to be listed in certain ways when we need to share references through other nodejs modules. This can also happen locally with different workspace setups but the gist of it is that there can't be a reliance on a reference just being `@swc/plugin-emotion` for example if it's not actually directly installed into that project.

To make things work properly I created a new package to house just the swc configs, added `preferUnplugged: true` in package.json for it to account for projects using newer versions of yarn along with a postinstall lifecycle script that creates a dynamic .swcrc per type of config that could be used.

The crux of the issue was that the plugin config needed to be generated as such:
```js
const swcEmotionPluginPath = require.resolve('@swc/plugin-emotion');

...
experimental: {
      plugins: [
        [
          swcEmotionPluginPath,
          {
            sourceMap: true,
            autoLabel: 'dev-only',
            labelFormat: '[local]',
          },
        ],
      ],
    },
...
```
to look like this (example is with yarn@3.7.0 and 2.5.110 of `@swc/plugin-emotion`)
```json
...
"experimental": {
      "plugins": [
        [
          "<ABSOLUTE_PATH_TO_PROJECT>/.yarn/unplugged/@swc-plugin-emotion-npm-2.5.110-e5df0b711b/node_modules/@swc/plugin-emotion/swc_plugin_emotion.wasm",
          {
            "sourceMap": true,
            "autoLabel": "dev-only",
            "labelFormat": "[local]"
          }
        ]
      ]
    }
...
```

Also a note that I could not verify this worked in other repos using linking either because lifecycle scripts don't work in linked projects for `yarn`. Here's the relevant output from running with `RUST_BACKTRACE=1`:

**Comment by kdy1** [comment]
You may need to update `@swc/plugin-emotion`. See https://github.com/swc-project/plugins/pull/254

**Comment by kdy1** [comment]
Oh ... You also need to update `@swc/core` because of AST-breaking changes

**Comment by kdy1** [comment]
Your config was wrong. See https://github.com/kdy1/repro-swc-8529
