### ISSUE TITLE
cannot install swc_cli

### ISSUE THREAD

**Issue by zhuguoxi** [swc-project/swc#8560]
### Describe the bug

running `cargo install swc_cli` 

--> /Users/xxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.178.19/src/path.rs:233:16
    |
233 |         if let FileName::Real(resolved) = &target {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^   ------- this expression has type `&Resolution`
    |                |
    |                expected `Resolution`, found `FileName`

error[E0308]: mismatched types
   --> /Users/xxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.178.19/src/path.rs:235:26
    |
222 |           let mut target = match target {
    |  __________________________-
223 | |             Ok(v) => v,
224 | |             Err(err) => {
225 | |                 warn!("import rewriter: failed to resolve: {}", err);
226 | |                 return Ok(module_specifier.into());
227 | |             }
228 | |         };
    | |_________- expected due to this value
...
235 |                   target = FileName::Real(orig);
    |                            ^^^^^^^^^^^^^^^^^^^^ expected `Resolution`, found `FileName`

### Input code

```typescript
No response
```

### Config

```json
No response
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKlFQSFRIK8rPVVCvqKhQBwCmyJxEFAAAAA%3D%3D&config=H4sIAAAAAAAAA3WSsW7DIBCGdz%2BFxVgloe2QIVNfoGOnqsMZnxMqMNbdWW0U%2Bd0LTnCI0kzG%2F%2F18d%2FxwqupafbNRu%2FoUl%2FGnAcYPclFQGhqjW%2B1HZ51mMmo1W6JpADnwsucivjVg21H%2FWMZ1gyJI6866%2BEnOz8I5u%2BU4IOtsKKpfq3%2BgPjg0o8PHpMXxEEXYt0ixm35SuzvKRpf1x%2FPwAQjbhLifZJNS0oujhFzW0xkWAyRGKhJUfOwFflPs83kM2UGugQunUgeOcdFaNIFAwpyv0LhUqrKTAO1REhf59fllq7JO0HMXyJdDLMh3FGhBIJPr7CAEIzc3H6WOkA9JnFaFPPZifboxBaMED2JNjmS6GdGFwHh7POVtb7tjOZsJfoh9%2BC4HD%2F3eLfurzJ%2Fpyof2%2FGwuzzuFew5jq66m3GwBK8vveWcKoJr%2BAMuk2uIqAwAA

### SWC Info output

No response

### Expected behavior

swc_cli can be installed with stable Rust without issue

### Actual behavior

swc_cli cannot be installed on stable Rust

### Version

swc_cli v0.91.141

### Additional context

No response

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/commit/039c1685c663cd138e4a0cf769b506d1fd419ba5
