### ISSUE TITLE
Panicked at plugin.rs: Failed to invoke plugin

### ISSUE THREAD

**Issue by dlabrecq** [swc-project/swc#8562]
### Describe the bug

While running Jest, @swc/core v1.3.106 generates the error below. Note that @swc/core v1.3.105 works as expected.

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.272.1/src/plugin.rs:162:14:
failed to invoke plugin: failed to invoke plugin on 'Some("/Users/dlabrecq/Work/insights/repos/frontend-starter-app/src/Components/SampleComponent/sample-component.test.tsx")'

Caused by:
    0: failed to invoke `jest_workaround` as js transform plugin at jest_workaround
 FAIL  src/Components/SampleComponent/sample-component.test.tsx
  ● Test suite failed to run

    failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/dlabrecq/Work/insights/repos/frontend-starter-app/src/Components/SampleComponent/sample-component.test.tsx")'

    Caused by:
        0: failed to invoke `jest_workaround` as js transform plugin at jest_workaround
        1: RuntimeError: unreachable

      at Compiler.transformSync (node_modules/@swc/core/index.js:244:29)
      at transformSync (node_modules/@swc/core/index.js:351:21)
      at Object.process (node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:726:19)

### Input code

```typescript
1. Install packages via `npm install`
2. Run `npm run test`

This will invoke `run jest`, which tests the sample-component.test.tsx file below.

https://github.com/dlabrecq/frontend-starter-app/blob/swc-core/src/Components/SampleComponent/sample-component.test.tsx
```

### Config

```json
/** jest.config.js */

const transformIgnorePatterns = ['node_modules/(?!(uuid)/)'];

/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  coverageDirectory: './coverage/',
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.js', '!src/**/stories/*'],
  roots: ['<rootDir>/src/'],
  moduleNameMapper: {
    '\\.(css|scss)$': 'identity-obj-proxy',
  },
  transformIgnorePatterns,
  setupFilesAfterEnv: ['<rootDir>/config/jest.setup.js'],
  transform: {
    '^.+\\.(ts|js)x?$': [
      '@swc/jest',
      {
        $schema: 'http://json.schemastore.org/swcrc',
        jsc: {
          experimental: {
            plugins: [['jest_workaround', {}]],
          },
          parser: {
            jsx: true,
            syntax: 'typescript',
            tsx: true,
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      },
    ],
  },
};
```

### Playground link (or link to the minimal reproduction)

https://github.com/dlabrecq/frontend-starter-app/tree/swc-core

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Pro

    Binaries:
        Node: 18.18.0
        npm: 10.2.5
        Yarn: 1.22.19
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.3.106
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 5.2.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Plugins should be invoked as expected

### Actual behavior

Jest tests fail because plugin failed be invoked; however, it works with @swc/core v1.3.105

### Version

1.3.106

**Comment by kwonoj** [comment]
`failed to invoke jest_workaround`

You should report the issue to the failing plugin.

**Comment by dlabrecq** [comment]
Closing in favor of https://github.com/magic-akari/swc_mut_cjs_exports/issues/99
