### ISSUE TITLE
Support the `using` keyword for functions

### ISSUE THREAD

**Issue by KyleJune** [swc-project/swc#8570]
### Describe the feature

The following check for the `using` keyword currently only allows it for objects. These lines will prevent the `using` keyword from being used on functions which is allowed in tsc.

https://github.com/swc-project/swc/blob/d6cd2146faed9155ae6f2c625daa173ddc7c0064/packages/helpers/esm/_using.js#L5-L7

A function can have the `Symbol.dispose` or `Symbol.asyncDispose` added to them to make them disposable just like how an object can. Here is the implementation in TypeScript, showing that it should allow the `using` keyword for functions.

https://github.com/microsoft/TypeScript/blob/36f9e9e037a8bf715d96c8270732d5830719d7c8/tests/baselines/reference/usingDeclarations.11.js#L57
```js
if (typeof value !== "object" && typeof value !== "function") throw new TypeError("Object expected.");
``` 

### Additional context

This is based on a discussion about making spies and stubs disposable so that the originals will automatically be restored after they are no longer needed. This is needed to implement the feature.

https://github.com/denoland/deno_std/issues/3966

**Comment by Austaras** [comment]
babel/babel#16150
