### ISSUE TITLE
Question: how to compare a AST with another one as tokens?

### ISSUE THREAD

**Issue by magurotuna** [swc-project/swc#858]
**Question**

Hi.
I'm using this library to port ESLint rules to deno_lint.
When I was working on the `no-dupe-else-if` rule, I found we need to compare an `Expr` with another one as tokens.
For example, given the following code:

```javascript
if (a > 1) {
  // some stuff
} else if (a > 1) {
  // other stuff
}
```

In this code, two `if` statements have the same conditions, `a > 1`.
I want to make sure that the two conditions are identical by comparing `swc_ecma_ast::Expr`.
But simple comparing like `expr1 == expr2` (in Rust) never works in this particular case, bacause this comparison always false if `expr1` and `expr2` have different spans.
So I wonder if there is any solution to check whether or not two expressions are the same as tokens regardless of their spans.

Any idea would be appreciated. Thank you.

**Comment by kdy1** [comment]
I think it can be done by capturing tokens and comparing the position of the token with the one from ast.

Other way is to remove span using `swc_ecma_visit`. Just create a folder which returns `DUMMY_SP` from `fold_span` and fold a cloned node with it. In my experience, it's fast enough.

**Comment by magurotuna** [comment]
@kdy1 
Thanks for the answer!
The second way looks simple and practical way to me, but if my understanding is not wrong, we should use nightly compiler to use `fold` features, right?
To be honest I hesitate to use nightly, so I think I have to take the first way.
Thank you again :)

**Comment by kdy1** [comment]
swc_ecma_visit is a stable-rust variant of fold

**Comment by magurotuna** [comment]
Oh I missed that. I'll check it.

**Comment by magurotuna** [comment]
By using `swc_ecma_visit::Fold` trait, I've succeeded in removing spans, and now comparing `expr1 == expr2` as tokens works as expected.
Thanks a lot!!!
