### ISSUE TITLE
Should swc parse paren expressions on the left hand side of an assignment?

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#861]
**Question**

Given the following code:

```ts
(x) = (6);
```

TS compiler does:

![image](https://user-images.githubusercontent.com/1609021/85750621-db330800-b6d7-11ea-9d1e-1f5139ecaf5e.png)

SWC however, does not have a parenthesized expression on the left hand side:

```
Node kind: Module
Text: "(x) = (6);"
Node kind: ExprStmt
Text: "(x) = (6);"
Node kind: AssignExpr
Text: "(x) = (6)"
Node kind: Ident
Text: "x"
Node kind: ParenExpr
Text: "(6)"
Node kind: Number
Text: "6"
```

Should it?

Note that once I access a property on the parentheses (ex. like `(x).test = (6);`), then swc parses it.

**Comment by kdy1** [comment]
I think it should on ts parser mode

**Comment by dsherret** [comment]
I was thinking about this more. Since swc parses paren expressions as their own ast node (I prefer this, by the way 😀) then I think it should do it regardless of whether its  on the left or right side of an expression and regardless of parsing ts or not.

I didn't try out what babel does when its configured to parse paren expressions, but I would be surprised if it didn't include a paren expression node on the left side when there exists one.

**Comment by kdy1** [comment]
> Since swc parses paren expressions as their own ast node 

Hmm... Good point. I'll go with it.

**Comment by kdy1** [comment]
Published a new version

**Comment by dsherret** [comment]
Thanks @kdy1! Also, thanks for your work on the TS 4.0 support :)
