### ISSUE TITLE
After `cargo update`, it throw `Plugin's AST schema version is not compatible with host's` this error

### ISSUE THREAD

**Issue by JiangWeixian** [swc-project/swc#8613]
After `cargo update`, it throw `Plugin's AST schema version is not compatible with host's` this error, I have no idea how to fix it...

anyone please help me...

Cargo.toml is

```
swc_core = { version = "0.87.3", features = ["ecma_quote", "ecma_plugin_transform"] }
swc_ecma_ast = "0.110.15"
swc_ecma_utils = "0.125.0"
swc_ecma_visit = "0.96.15"
swc_plugin_proxy = "0.39.15"
```

and `@swc/core@1.3.100`

_Originally posted by @JiangWeixian in https://github.com/swc-project/swc/discussions/8612_

**Comment by kdy1** [comment]
See https://swc.rs/docs/plugin/selecting-swc-core

**Comment by JiangWeixian** [comment]
I use `@swc/core@1.3.100` and `swc_core@0.87.3`,  looks like is match `@swc/core@1.3.81 ~ @swc/core@1.3.105`

**Comment by kdy1** [comment]
Can you try `swc_common = "=0.33.15"`

**Comment by JiangWeixian** [comment]
> Can you try `swc_common = "=0.33.15"`?

It works

**Comment by thekip** [comment]
@kdy1 Could you add more explanation on this? How this going to work in future? You going to provide correct version of `swc_common` together with `swc_core` for each entry in the https://swc.rs/docs/plugin/selecting-swc-core ?

**Comment by kdy1** [comment]
Nope, it was my mistake and I'll fix it soon

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/pull/8621
