### ISSUE TITLE
Regression: "this is undefined" when minifying @google/model-viewer with @swc/core 1.4.1 or newer

### ISSUE THREAD

**Issue by Frank3K** [swc-project/swc#8643]
### Describe the bug

There is a minification bug in @swc/core version 1.4.1 and 1.4.2-nightly-20240216.1. The bug does not appear in @swc/core version 1.4.0. The package used is @google/model-viewer (version 3.4.0).

When the minified code is being run, the following NPE can be observed on the console `this is undefined`.

I have created a repository showcasing the issue: https://github.com/Frank3K/swc-minification-bug-model-viewer.

### Input code

```typescript
@google/model-viewer 3.4.0: 

https://github.com/google/model-viewer/releases/tag/v3.4.0
https://www.npmjs.com/package/@google/model-viewer/v/3.4.0

(Included in minimal reproduction's package.json).
```

### Config

```json
No .swcrc, but these parameters are passed to the minify command:


const { code, map } = await minify(content, {
  module: true,
  ecma: 2015,
});
```

### Playground link (or link to the minimal reproduction)

https://github.com/Frank3K/swc-minification-bug-model-viewer

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
        CPU: (8 cores)
            Models: Apple M1

    Binaries:
        Node: 18.15.0
        npm: 9.5.0
        Yarn: 1.22.19
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.4.2-nightly-20240216.1
        @swc/helpers: N/A
        @swc/types: 0.1.5
        

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

No NPE occurs, like with version 1.4.0.

### Actual behavior

Code is generated which contains an NPE. Related lines (beautified):

```js
let aU = function(e, t) {
		!1 !== this.enabled && (this.files[e] = t)
	},
	aP = function(e) {
		if (!1 !== this.enabled) return this.files[e]
	},
	aN = function(e) {
		delete this.files[e]
	};
```

Corresponding input source:

```js
const Cache = {

	enabled: false,

	files: {},

	add: function ( key, file ) {

		if ( this.enabled === false ) return;

		// console.log( 'THREE.Cache', 'Adding key:', key );

		this.files[ key ] = file;

	},

	get: function ( key ) {

		if ( this.enabled === false ) return;

		// console.log( 'THREE.Cache', 'Checking key:', key );

		return this.files[ key ];

	},

	remove: function ( key ) {

		delete this.files[ key ];

	},

	clear: function () {

		this.files = {};

	}

};
```

### Version

1.4.2-nightly-20240216.1

**Comment by kdy1** [comment]
# Investigation:

https://github.com/kdy1/repro-swc-8643/commit/14c856b922fa8bce8d4a3d14027473970c9f116e

if the difference of `compress`, with mangler disabled.

**Comment by Frank3K** [comment]
I've confirmed the fix is working. Thanks for the quick response 👍.
