### ISSUE TITLE
Support for 32-bit Linux (x86/ia32)

### ISSUE THREAD

**Issue by edwillard** [swc-project/swc#8646]
### Describe the feature

I would like to use SWC in a 32-bit Linux environment for use in low-resource VMs. Is it possible to produce binaries for x86 Linux in addition to the current x64 (32-bit seems supported for Windows and ARM Linux but not x86)? I would love to take advantage of the improvements SWC offers.

**Comment by kwonoj** [comment]
There is no plan to expand support ia32 targets, as we'll gradually retire any existing ia32 targets.
