### ISSUE TITLE
esm-style export don't get lazy loaded - Same as https://github.com/swc-project/swc/issues/4799

### ISSUE THREAD

**Issue by Kahor** [swc-project/swc#8650]
### Describe the bug

I am having the exact same issue described in https://github.com/swc-project/swc/issues/4799

The exact same code still output the same result and the expected behavior listed in the issue is never reached.

Looking at the documentation for lazy loading (https://swc.rs/docs/configuration/modules) I am not 100% sure what is the expected behavior ? Can we force lazy loading for this code in some way if this is part of an exception ?

### Input code

```typescript
export {
    createP
} from './St';
```

### Config

```json
{
    "module": {
      // You can specify "commonjs", "es6", "amd", "umd"
      "type": "commonjs",
      "strict": false,
      "strictMode": true,
      "lazy": true,
      "noInterop": false,
      "ignoreDynamic": false
    }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0utKMgvKlGo5lIAguSi1MSS1ACuWoW0ovxcBXU9%2FeASdWsAVGIICyMAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DMAhE9z6FxbrbbnqHHsJySeTIPwGRakW5e%2B3UTpsdzAw82JTWsLCFh95qWZtsiJHOvipcoph3VUBKRrbkssBtuMLNmoxnPKT964AYmlHaFPK9x8GnxDjiXQsuuqn8A20KmZD5GmxRE2ePV5zqSAjptR5mf6Qd2%2FB1W0hxYfglB%2FHcDo6fY1xoRbV%2FALu7P%2BkZAQAA

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: x64
        Machine Type: x86_64
        Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
        CPU: (12 cores)
            Models: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

    Binaries:
        Node: 20.11.0
        npm: 10.2.4
        Yarn: N/A
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.4.2
        @swc/helpers: N/A
        @swc/types: 0.1.5
        

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Object.defineProperty(exports, "createP", ({
  enumerable: true,
  get: function get() {
    return _St().createP;
  }
}));

function _St() {
  var data = __webpack_require__("../path/to/St");

  _St = function _St() {
    return data;
  };

  return data;
}

### Actual behavior

Object.defineProperty(exports, "createP", ({
  enumerable: true,
  get: function get() {
    return _st.createP;
  }
}));

var st = __webpack_require__ ("./path/to/St");

### Version

1.4.2

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/4864#issuecomment-1172855122

**Comment by kdy1** [comment]
Also, see https://github.com/swc-project/swc/pull/5103/files#diff-fb5c3473351c5bd1ebf2ead2ddee9b8dabe8cd230a0905d3df32f14d01835c98
