### ISSUE TITLE
Unable to import AWS SDK DynamoDB DocumentClient type

### ISSUE THREAD

**Issue by rubnogueira** [swc-project/swc#8658]
### Describe the bug

After upgrading SWC to version `1.3.89`, I was unable to use AWS SDK DynamoDB code. I created a repo with the bug reproduction.

### Input code

```typescript
import { DocumentClient } from 'aws-sdk/lib/dynamodb/document_client';
import Key = DocumentClient.Key;
import PutItemInput = DocumentClient.PutItemInput;
```

### Playground link (or link to the minimal reproduction)

https://github.com/rubnogueira/swc_1.3.89_type_import

### Expected behavior

It works under 1.3.88 and using tsc.

### Version

1.3.89

**Comment by kdy1** [comment]
Try latest.

**Comment by rubnogueira** [comment]
@kdy1 It's not working on the latest version. 1.3.89 is where it breaks.

**Comment by kdy1** [comment]
It working as expected. You should add `type` keyword. `tsc` 

https://swc.rs/docs/migrating-from-tsc#isolatedmodules-true
