### ISSUE TITLE
TS 4.0: Support new assignment operators

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#866]
**Describe the feature**

```ts
a &&= b;
a ||= b;
a ??= b;
```

**Additional context**

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/

**Comment by dsherret** [comment]
By the way, I can help out with some of this work (we should probably wait for 4.0 to hit RC though).

**Comment by kdy1** [comment]
Oh... it requires a major version bump.
I'll just do it. I don't think they will withdraw something written in the announcing post.
