### ISSUE TITLE
Remove unused arguments when compressing function

### ISSUE THREAD

**Issue by alshdavid** [swc-project/swc#8671]
### Describe the feature

It's safe to drop tail args from a function call when they are unused
```javascript
function foo(a,b,c,d) {
   console.log(b)
}
```
Can become
```javascript
function foo(a,b) {
   console.log(b)
}
```
However it currently optimizes to:
```javascript
function foo(a, b, c, d) {
    console.log(b);
}
```

### Additional context

[Playground link](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9dI1EnSSdZJ0VSo5uVSUFBIzs8rzs9J1cvJT9dI1uTlquXl4uUqTi0JycxNzS8t0dDQVLC1A2s01DHSMdYx0THV1FEwAKoEABn9iL5WAAAA&config=H4sIAAAAAAAAA32UO3LjMAyG%2B5zCozrFjost9gDpcgYOTYIyvXxoCNCxJuO7L0RJtjeG3En48AMkAOL7bbfrTmi6P7tv%2FuSfQReEcvtnC46J9IUtHZio0RQ%2FUPe%2B0hNOyOmA0EzXmXSkSw%2FUVLj%2Ftd8vii7kjLAqFlv0ybvxMafJcSiA%2BGBjK4esERJNZioV3h9RyV%2BC%2FZBzAJ1eEKVR%2BUTQQ8H%2Fz7WcJAQ9IKizLkKU6aC6eMxSiglWAquGkgeRJ%2BvJ58Q5n6kFbZXJFgTkCxjyZ5BknItlCfl6wn0atnCofd%2Fa%2FEMNZx2qJiEnXFpH%2BLRC1GP2SMpVqQozW0sgK5fi%2FoTeqQJUS3qOeso%2BbfTkLwBXIGjEpCNIcZuH43HaUrtVKUGfHA8sjUJgnm6p0Ql6rqny3gmFnSoDhbyUr4CtBqbCmm0qVwG9BQXO8aBI9MuTOUopaRwgOwFwc7WTRmoG6vYEN%2Fj0Gl7gD74jydO1eERNx22KYzzk8CJBBDpm%2B8KBG0F5GxdeEZdhm9dkgQcDrOhSsYHnDcDTT1mFtiufJoPfBkdUfciH%2B45YHK63HRx16u%2BPfV7Db4tDF7OtDS4LfurvvJZ%2Fd3endQPfDt55%2FFyVLen1H3xJ9VcsBgAA)

**Comment by Austaras** [comment]
SWC already had this functionality but under the option of `keep_fargs`. It's enabled by default because user may need to read function length.
