### ISSUE TITLE
`jsc.baseUrl` is not resolving the require/import path

### ISSUE THREAD

**Issue by devjiwonchoi** [swc-project/swc#8674]
### Discussed in https://github.com/swc-project/swc/discussions/8665

x-ref: #8660

<div type='discussions-op-text'>

<sup>Originally posted by **devjiwonchoi** February 26, 2024</sup>
Hello, fellow engineers and appreciatable SWC maintainers,

I wish to understand if the following behavior is intended and if so, the reason for it:

### TL;DR

Why is `jsc.baseUrl` not resolving the require path as either relative or absolute?

### Context

Using `transform` or `transformSync` from `@swc/core`.

Based on this error message:

```sh
Error: failed to handle: base_dir(`.`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
```

I've understood that the `baseUrl` path must be absolute which differs from `tsconfig.json`, so I'm passing `process.cwd()`.

### Code

```ts
import { foo } from "src/foo"
console.log(foo)
```

```ts
await transform(code, { jsx: { baseUrl: process.cwd() } })
```

Expected:

```js
import { foo } from "./src/foo" // or a resolved absolute path?
console.log(foo)
```

Output:

```ts
import { foo } from "src/foo"
console.log(foo)
```

## Repro

https://github.com/devjiwonchoi/repro-swc-base-url-paths

```sh
pnpm i
pnpm tsx .
```

**Comment by ParadeTo** [comment]
Yes, I also try use this in rust and get the same issue, here is my demo https://github.com/ParadeTo/swc-bug-demo.git. Let me check if I can fix it and submit a PR.

**Comment by kdy1** [comment]
Closing as can't repro. Please provide a minimal reproduction. https://github.com/swc-project/swc/pull/8686

**Comment by kdy1** [comment]
The current output is https://github.com/swc-project/swc/pull/8686/files#diff-04466b8074b970c0631a0c7cdd95d34cdbfb62e59db2019c6ba1eee213264e20 , which is correct

**Comment by devjiwonchoi** [comment]
@kdy1 My bad, updated repro, thank you for reviewing!
