### ISSUE TITLE
plugin resolve logic incorrect

### ISSUE THREAD

**Issue by himself65** [swc-project/swc#8688]
### Describe the bug

Same as this issue: https://github.com/vercel/next.js/issues/37409

I spend a few minutes reading the source code, and reason is 

For example, with the following file structure:

```
node_modules
	next
		node_modules
			swc-plugin-a
		next-app.js
my-app.js
```

```js
// #file: my-app.js
require('next/next-app.js')

// #file: next/next-app.js
transform(source, {
  swcrc: false,
  jsc: {
    experimental: {
      plugins: [['swc-plugin-a', {}]],
    },
  },
})
```

it will go check `node_modules->swc-plugin-a`, but the expected behavior should be `node_modules->next->node_modules->swc-plugin-a`

Related code 

https://github.com/swc-project/swc/blob/71fb5c12a75bec27cc775069f83b576019d261f2/crates/swc_ecma_loader/src/resolvers/node.rs#L495-L503

The reason is the baseDir here should be caller's baseDir, not CWD's baseDir

https://github.com/swc-project/swc/blob/71fb5c12a75bec27cc775069f83b576019d261f2/crates/swc_ecma_loader/src/resolvers/node.rs#L427-L432a 

### Playground link (or link to the minimal reproduction)

N/A

### Expected behavior

Resolve correct

### Version

latest

**Comment by magic-akari** [comment]
rspack needs to address similar issues. 
rspack introduce the [oxc-resolver](https://github.com/oxc-project/oxc-resolver) to handle node resolution.
Perhaps we can try it.

**Comment by kdy1** [comment]
@magic-akari I think the problem is the base directory being `current_dir`

**Comment by kdy1** [comment]
I concluded that this is not a bug of swc. Use fully qualified path for `transform()`
