### ISSUE TITLE
docs.rs build is failing since 0.20.0

### ISSUE THREAD

**Issue by Cerber-Ursi** [swc-project/swc#8693]
I've just noticed that the last version of swc_core available on docs.rs is 0.19 - all later versions failed to build. At least the first of them, i.e. [0.20.0](https://docs.rs/crate/swc_core/0.20.0/builds/621914), and the (current) last, [0.90.16](https://docs.rs/crate/swc_core/0.90.16/builds/1147997), are broken for the same reason - `package.metadata.docs.rs` lists some features which are not present on the create itself. Not sure what should be changed (either the metadata or the features themselves) and in what way, so simply try to call for attention.

**Comment by kdy1** [comment]
Use swc rustdoc instead. https://rustdoc.swc.rs/swc_core
