### ISSUE TITLE
Unable to load schema from `https://json.schemastore.org/swcrc`

### ISSUE THREAD

**Issue by rostaingc** [swc-project/swc#8694]
### Describe the bug

The url is returning a 503 error
`https://json.schemastore.org/swcrc`

```
Unable to load schema from 'https://json.schemastore.org/swcrc': Service Unavailable. The server is currently unavailable (overloaded or down).
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=u.
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2021",
    "baseUrl": "./"
  },
  "minify": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAAwMAAAAAAAAAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D

### Expected behavior

The website should be available

### Version

0

**Comment by kdy1** [comment]
It's not managed by the SWC team. Closing as not actionable.
