### ISSUE TITLE
ReferenceError: cannot access 'class' before initialization 

### ISSUE THREAD

**Issue by milena-mognon** [swc-project/swc#8697]
### Describe the bug

I encountered a potential issue when executing my project compiled with SWC. I've been using version 1.3.96 for some time, and everything was working fine. However, upon updating the SWC version to compile the project, I encountered the following error during project execution:

``ReferenceError: Cannot access 'ActionPlan' before initialization``

This does not occur with the code generated with version 1.3.96, but with any other updated versions I get the same error

This is a snippet of my TypeScript code 

```ts
import Consensus from './Consensus';
import Goal from './Goal';

@Entity({ name: 'action_plan' })
export default class ActionPlan {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToOne(() => Consensus, consensus => consensus.actionPlan)
  @JoinColumn()
  consensus: Consensus;
}
```

While testing with the playground, I noticed only one difference between the code generated by version 1.3.96 and others.

The JavaScript code generated looks like this in version 1.3.96 (which works):

```js
var ActionPlan; // with this 'var' variable
ActionPlan = class ActionPlan {
    constructor(){
        _define_property._(this, "id", void 0);
        _define_property._(this, "consensus", void 0);
    }
};
```

In any other version, the JavaScript code generated looks like
```js
class ActionPlan { // without the variable
    constructor(){
        _define_property._(this, "id", void 0);
        _define_property._(this, "consensus", void 0);
    }
}
```

Using the `keepClassName` config yields the same error

```js
let ActionPlan = class ActionPlan { // with this 'let' variable
    constructor(){
        _define_property._(this, "id", void 0);
        _define_property._(this, "consensus", void 0);
    }
};
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true,     
    },
    "target": "es2020",
    "paths": {
      "@modules/*": ["modules/*"],
      "@config/*": ["config/*"],
      "@shared/*": ["shared/*"]
    },
    "baseUrl": "./src",
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.96&code=H4sIAAAAAAAAA0WPzQrCMBCE74W%2Bw96Sgui9olSKCF704F2WNspCsin5AUV8d9Mo8bKws9%2FMsGQm6wL0lr1iHz3cnDUglquiiHVd0Zc6WNQFmJf5VlfdngOFp3wBo1EtCBwCWb5OGlnAu6kr9cj%2BUd0w6gCDRu9hl6lzguBVVwDd2ZFB9zwoVg6DGnuro2EpYqRRNDNCYws%2BOOJ7Lk6eE6uLTUPKBjbb%2Fx8LGMpLSS%2FLEktrTuyOlvhXlIVCtv%2BwVPb%2BAAx5%2FXMpAQAA&config=H4sIAAAAAAAAA1VQuW7DMAzd8xWC0KkorCBjpgxdM3YqMrAyfcGSDJJGawT590qO4mOyH99F8X5Qyhil39g26ECflW5EBj4b03HwxXPMEgiLQLXhX0tWf0SX5jCSxSsMHF1CI87Tjm2E9%2FgbwQDESAtOpskL%2FKUamQZkS%2B0gc9zMlmgDQSzbRir1eH60EHiuArltYo812Onz5dwZt5FXFChB4CWY6X08UI2SdkM%2BHU%2FHvFd8hTS8rby4UI49snmP02%2B9ottSe7HBV22dFQvYCLgBwjILFnDbbfQDjF%2FUp5UKw%2FnwM5lL11OncyadDc4F37Fela1vqylyFfQcD%2FM4%2FAO7EHJz9QEAAA%3D%3D

### Expected behavior

I would like to use an updated version of SWC, such as 1.4.4, and don't get the error ``ReferenceError: Cannot access 'ActionPlan' before initialization``. 

Based on my tests till now, the code generated with the version 1.4.4 should be like this. 

```js
var ActionPlan; // with this 'var' variable
ActionPlan = class ActionPlan {
    constructor(){
        _define_property._(this, "id", void 0);
        _define_property._(this, "consensus", void 0);
    }
};
```

It looks like a hosting problem, but I'm not sure.

### Version

1.3.100 +

**Comment by kdy1** [comment]
Please provide a minimal repro that's exeutable.
