### ISSUE TITLE
Aliases (paths) are incorrectly resolved

### ISSUE THREAD

**Issue by dmitriy-kudelko** [swc-project/swc#8701]
### Describe the bug

The issue started happening after upgrading `@swc/core` from `1.4.2` to `1.4.4`.
The compilation now doesn't seem to take into account the relative part of an alias and simply insert the alias itself.

We're using NestJs.

### Input code

```typescript
import { AppController } from '@app/app.controller';
import { AppService } from '@app/app.service';
```

### Playground link (or link to the minimal reproduction)

https://github.com/dmitriy-kudelko/swc-paths

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Max

    Binaries:
        Node: 20.11.0
        npm: 10.2.4
        Yarn: 1.22.19
        pnpm: 8.15.4

    Relevant Packages:
        @swc/core: 1.4.4
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 5.3.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Previously the compiled code looked like this, and worked fine:

```ts
const _appcontroller = require("./app.controller");
const _appservice = require("./app.service");
```

### Actual behavior

The compiled output now looks like the following, and so module resolution fails:

```ts
const _appcontroller = require("src/app.controller");
const _appservice = require("src/app.service");
```

### Version

1.4.4

**Comment by kdy1** [comment]
# Investigation

 - cwd: `/Users/kdy1/projects/repro-swc-8701`

 - options: 
```
{
  target: 'es2021',
  parser: { syntax: 'typescript', decorators: true, dynamicImport: true },
  transform: {
    legacyDecorator: true,
    decoratorMetadata: true,
    useDefineForClassFields: false
  },
  keepClassNames: true,
  baseUrl: '/Users/kdy1/projects/repro-swc-8701',
  paths: { '@app/*': [ './src/*' ] }
}
```
