### ISSUE TITLE
[Crate bug] Yank swc_common 0.33.19 and publish under 0.34.0?

### ISSUE THREAD

**Issue by alshdavid** [swc-project/swc#8722]
### Describe the feature

Between `swc_common` version `0.33.18` and `0.33.19` there are breaking changes. 

In my project I use `swc_common` `=0.33.19` directly and am trying to integrate `deno_runtime` which depends on `=0.33.18`.

During a `cargo build`, Cargo cannot resolve the conflict and fails the install with:
```
all possible versions conflict with previously selected packages.
```
I believe Cargo will resolve this by duplicating the `swc_common` dependency if they are split by minor version (I think that will work for prerelease packages below version 1.0.0, otherwise it has to be major version bumps).

Could you please yank swc_common 0.33.19 and re-publish it under swc_common 0.34.0?

**Comment by kdy1** [comment]
Please provide more details. Repro, and compile error shown by the rustc

**Comment by alshdavid** [comment]
repro
```
$ cargo new my-project
$ cd my-project
$ cargo add swc_common
$ cargo add deno_runtime
```

Result
```
$ cargo new my-project
     Created binary (application) `my-project` package
$ cd my-project
$ cargo add swc_common
    Updating crates.io index
      Adding swc_common v0.33.19 to dependencies.
             Features:
                [...]
    Updating crates.io index
$ cargo add deno_runtime
    Updating crates.io index
      Adding deno_runtime v0.149.0 to dependencies.
             Features:
                [...]
    Updating crates.io index
error: failed to select a version for `swc_common`.
    ... required by package `deno_ast v0.34.1`
    ... which satisfies dependency `deno_ast = "^0.34.1"` of package `deno_runtime v0.149.0`
    ... which satisfies dependency `deno_runtime = "^0.149.0"` of package `my-project v0.1.0 (/home/dalsh/Development/scratch/my-project)`
versions that meet the requirements `=0.33.18` are: 0.33.18

all possible versions conflict with previously selected packages.

  previously selected package `swc_common v0.33.19`
    ... which satisfies dependency `swc_common = "^0.33.19"` of package `my-project v0.1.0 (/home/dalsh/Development/scratch/my-project)`

failed to select a version for `swc_common` which could resolve this conflict
➜  my-project git:(master) ✗
```

My current workaround is to have a fork of swc with adjusted versions and package names that I vendor into my project as a git submodule and use `swc_common = { path = "../vendor/swc/crates/swc_common" }` (for all swc imports I use). Will try to get that working today so I can be unblocked.

**Comment by kdy1** [comment]
It's not fault of swc

**Comment by kdy1** [comment]
I don't think it's buggy at this time

**Comment by kdy1** [comment]
Also, we are correctly following semver.

**Comment by alshdavid** [comment]
That's okay, thanks for the consideration. 

I just realized that I have `0.33.12` in my lockfile. There are breaking changes between `0.33.12` and `0.33.18` (looks like removal of `PatOrExpr` and inclusion of `AssignTarget`). 

But I can resolve the conflict with `deno_runtime` by updating my code to use the new API.
