### ISSUE TITLE
export default named function should report top  level name conflict

### ISSUE THREAD

**Issue by stormslowly** [swc-project/swc#8755]
### Describe the bug

```js
export default function x (){}
let x =1;
```

this code should report that x already defined,  but swc just compiles it as ok 

### Input code

```typescript
export default function x (){}
let x =1;
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.8&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUUgrzUsuyczPU6hQ0NBUqK615spJLQFybBUMrbkAmMVZhSwAAAA%3D&config=H4sIAAAAAAAAA22QOw6DMAyGd06BPLN26daxQw8RpQaFxklkGwmEuHtDCpRK3eL%2F8TnyXNU19GLhWs%2F5mQccE7IjDGr8oWb9hZjulCLrTQRZXQySfeUBS2RpPv1kONvnpkyZNWYF0JIRyy4pNLvby2q1xssvRw13qKUlly0O5IJrpzPcRkqMIjvj4JIJnce%2FaB%2BjnJ2iA8XnUArbIXRK67RuoBh6gW9y%2F8WxEZw89nq5yFK9Abnt2jdaAQAA

### Expected behavior

should report error like below
```
Identifier 'x' has already been declared. (2:4)

  1 | export default function x(){}
> 2 | let x =1 ;
```

this error is copied from https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnCABQCUA3gL4BQmw8IcAvAIxwDcQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.24.0&externalPlugins=&assumptions=%7B%7D

### Version

1.4.8

### Additional context

accord to the https://262.ecma-international.org/#prod-ExportDeclaration the `export  default function x() {}` it should be treated as a function declaration.  but in swc ast it's treated as function expression https://github.com/swc-project/swc/blob/82d1b8e49a242b677d6df259163469cfd1d360c7/crates/swc_ecma_ast/src/module_decl.rs#L197-L205

**Comment by stormslowly** [comment]
@kdy1 ，could share some ideas how to fix this，maybe i can make a PR

**Comment by stormslowly** [comment]
my first idea is  introducing a new struct like HoistedFnDecl to handle this case, but i will introduce breaking change.

next one's :  in resolve treat export default fn_expr 's  ident as top level variable; then it will be the `let a= 1; let a=1` case

**Comment by kdy1** [comment]
You can add `visit_export_default_decl` to 
https://github.com/swc-project/swc/blob/4c83dcc37058495ceeecd3ae225ed95df7cf0b6d/crates/swc_ecma_lints/src/rules/duplicate_bindings.rs#L121-L370 and add binding from there
