### ISSUE TITLE
Incorrection compilation for target es2017 when compiling swc

### ISSUE THREAD

**Issue by rycfung** [swc-project/swc#8761]
### Describe the bug

When compiling the file with swc and tsc, the program ouput is different.

The output is different than the file compiled by `tsx@4.9.5`  with the following tsconfig:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "lib": ["dom",  "es2017" ],
    "target": "es2017",
  },
}
```

### Input code

```typescript
class Test {
  a
}
const x = new Test()
Object.defineProperty(x, 'a', {
  get: function () {
    console.log('get a')
  },
  set: function () {
    console.log('set a')
  },
})

console.log(Object.values(x))
```

### Config

```json
{
  "module": { "type": "commonjs" },
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
    },
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.9-nightly-20240316.1&code=H4sIAAAAAAAAA42OQQrCMBBF93OKv0sCoQcQPIMuvECM01IJiXRSTZHc3RhcdOlm4M%2Bb9xkfnAguLBlvAhxV8im2VHBE5FdH2tDpemefhxuPc%2BTzkh685E0XC%2BWU7erE%2BYBxjT7PKUKbvgS%2BbSnwENKkVbuBU6aBatuQPxTZK9UQ7envq6cLK4suxtAHMkg6L9AAAAA%3D&config=H4sIAAAAAAAAA1VPSQ7DIAy88wrkcw9tL5X6hz4CUSciYhN2pKIofw%2BkkDY3exbPeBFSwkQannIpY1miSoTp2AtC2bP6FAQ4RySdTGS4dJapUoOyhDu0fhlglUbk6kK6X2%2BP5gAbAmF3NMwZb4b8n6mDiwmJzsIqVX60eE4ULRVceM872X6pfWuDcs0FPxH8lD3xuA6GXt3OaUaxbpEWNA8cAQAA

### Expected behavior

The expected output for this program should be 
```
[]
```

### Actual behavior

```
get a
[ undefined ]
```

### Version

1.4.8

### Additional context

Oddly enough, when running with the latest ts-node (10.9.2), the output is identical to when compiling with tsc, while `ts-node@10.9.1` has the wrong output

**Comment by kdy1** [comment]
https://swc.rs/docs/migrating-from-tsc#usedefineforclassfields
