### ISSUE TITLE
... spread operator not compiled correctly / does not return same result as Object.assign()

### ISSUE THREAD

**Issue by KoraySAP** [swc-project/swc#8766]
### Describe the bug

When using spread operator to merge two objects, the resulting object does not have the constructor of the target object.
In my below example
```
result = { ...some.prototype,
metadata: {
        aggregations: {
            _popover: {
                type: "x.Popover",
                multiple: false,
                visiblity: "hidden",
            },
        },
    },
}
```
After going through the SWC compiled code, the constructor of some.prototype is not present in result
Whereas if I use
```
result = Object.assign(
    some.prototype, 
    {
        metadata: {
            aggregations: {
                _popover: {
                    type: "x.Popover",
                    multiple: false,
                    visiblity: "hidden",
                },
            },
        }
    }
)
```
The code compiled by SWC does correctly give me the constructor in the result object

### Input code

```typescript
a.extend("b", {
    ...Object1,
    metadata: {
        aggregations: {
            _popover: {
                type: "x.Popover",
                multiple: false,
                visiblity: "hidden",
            },
        },
    },
});
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "transform": {
      "useDefineForClassFields": false
    },
  },
  "module": {
    "type": "commonjs",
    "strictMode": false,
    "lazy": true
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA2WMTQoCMQxG956idKVQCm7HQ%2BgNJLWxRvrHNA4OMne31QFl5m2S78sjoPHJGO1WGqnEayMqWuujueOF9%2BqTAzJYYOjmewOc69EBU4rlv2%2Bcc8ppwH7ZN3jM2AlZIOugT19PqpUWHp4p%2B6pewRdcCwMVMp54rM9uZC3GxZfpF%2Be1jml3eAPy81KA8QAAAA%3D%3D&config=H4sIAAAAAAAAA02OPQ7DMAhG954iYu4JurbK1kMgm0iObBMBkZpGuXvtNH8Lgu8JePOtaaBXB49mLm0ZBhQlOeaS6JQNPyUBmwZSJ2EwuO%2FUtCKTkY7Ik2NBY9GNrGD5czDBrB1Luv4YlV7UhUwtyzOiahso%2BrrfYdTLgbVAYj9GOqWrWBV0nBLnXjc9UJPg7M2e9ksbiPidTrnltvwAdlEA8wkBAAA%3D

### SWC Info output

npx -y swc-info@latest

    Operating System:
        Platform: darwin
        Arch: x64
        Machine Type: x86_64
        Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64
        CPU: (12 cores)
            Models: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

    Binaries:
        Node: 20.11.0
        npm: 10.2.4
        Yarn: N/A
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.4.2
        @swc/helpers: 0.5.6
        @swc/types: 0.1.5
        

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

I expect Object.assign(obj1, obj2) and { ...obj1, ...obj2) to behave exactly the same when compiled

### Actual behavior

When using spread operator, the constructor (from obj1) is not available in the resulting merged object.
When using Object.assign, it is

### Version

1.4.2

### Additional context

Using Babel/TSC (from which we are trying to migrate), the spread operator merge is compiled to this:
```
a.extend("b", (0, _tslib().__assign)((0, _tslib().__assign)({}, some.prototype), {
  metadata: {
    aggregations: {
      _popover: {
        type: "x.Popover",
        multiple: false,
        visiblity: "hidden"
      }
    }
  }
})) 
```
The __assign function:
```
var __assign = function() {
  __assign = Object.assign || function __assign(t) {
      for (var s, i = 1, n = arguments.length; i < n; i++) {
          s = arguments[i];
          for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p)) t[p] = s[p];
      }
      return t;
  }
  return __assign.apply(this, arguments);
}

```
This give us the expected result/behavior

**Comment by kdy1** [comment]
Babel output:

```js
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function ownKeys(e, r) { var t = Object.keys(e); if (Object.getOwnPropertySymbols) { var o = Object.getOwnPropertySymbols(e); r && (o = o.filter(function (r) { return Object.getOwnPropertyDescriptor(e, r).enumerable; })), t.push.apply(t, o); } return t; }
function _objectSpread(e) { for (var r = 1; r < arguments.length; r++) { var t = null != arguments[r] ? arguments[r] : {}; r % 2 ? ownKeys(Object(t), !0).forEach(function (r) { _defineProperty(e, r, t[r]); }) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(t)) : ownKeys(Object(t)).forEach(function (r) { Object.defineProperty(e, r, Object.getOwnPropertyDescriptor(t, r)); }); } return e; }
function _defineProperty(obj, key, value) { key = _toPropertyKey(key); if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
a.extend("b", _objectSpread(_objectSpread({}, Object1), {}, {
  metadata: {
    aggregations: {
      _popover: {
        type: "sap.m.Popover",
        multiple: false,
        visiblity: "hidden"
      }
    }
  }
}));

```

**Comment by kdy1** [comment]
Better repro:
```js
class Foo {

}


const NewObject = {
    ...Foo.prototype,
    metadata: {
        aggregations: {
            _popover: {
                type: "sap.m.Popover",
                multiple: false,
                visiblity: "hidden",
            },
        },
    },
}

console.log(new NewObject())
```


But this fails before transpilation

**Comment by kdy1** [comment]
Can you provide an executable repro case?
Otherwise this issue isn't actionable

**Comment by KoraySAP** [comment]
Tried to simplify as much as possible to show what I expect, hopefully this is helpful.

https://play.swc.rs/?version=1.4.2&code=H4sIAAAAAAAAA3WQwQrCMBBE7%2F2KJacWJKBHi2dP6sUfiHGpkZgtyRaU0n93rVYi1D3OzjyGsd6kBFui8zYiMkboC5AL5oZrSBxdaOqXMqptd%2FLOgqUgn84yxbL6BGBUyaP21JQqs6iq%2Fjj44pJ%2BkWED6oLek3q%2FhiLHJ%2BS9mMpEN5RIaKYiVT8D%2BrrmUC44ziqOuQmv2LCZyg2FBD0ydAnjERMvBd2D1jrbRreRmPjR4kJK3tegdsajgqH%2Bia4kejhd0bKWcV0Tyj%2BMPoMMVZEP%2BK0h%2Feb0lehP7gw%2Fa7wBAAA%3D&config=H4sIAAAAAAAAA21QsU7EMAzd7yuijKiiEwysoBMMsCPEYKUu6pHEke1KV079d5LqLrQ6slh%2B78X2e6edyc8exNkHc1qa3CpDlJ44rMAMj4JP2A8R98SPHkT2A%2FpOsqgHL3gWzk0dA%2FyFmmmLcmcrnIAFeTtapqhwLFKdEorjIWn9UUZJIZVHXIHdFCEM7iUkYv2HRkcMSixn7upATyR4Ob%2BieFTkCP4ZfUKu9pq2XS%2Bw34hpSeENAm5DOG%2BwgbrR48pp25p3Go2DaCShG%2FrJWEchUDyIbUpO96VA6EoZc6lZ5lhKPH%2FqCyPKg9NX6q6dePiZtjkn0GKunPtR0YW5vbEV%2BNwmNe%2FmXxLxurAoAgAA

Take the compiled code, run it in Chrome debbuger as a snippet, open both objects in the console, userTest1 does not have the constructor from GoodGreeter, whereas userTest2 does

<img width="1017" alt="Screenshot 2024-03-21 at 12 05 29" src="https://github.com/swc-project/swc/assets/162436347/a77fd200-1605-4a4d-bb3d-fd66d2b4c940">

**Comment by kdy1** [comment]
Thanks!

Executable form: https://play.swc.rs/?version=1.4.2&code=H4sIAAAAAAAAA3VQvQrCMBDe8xRHphYkYEeLs5O6%2BAKxHrWS5kpyBaX03T1rKxE0S3LfH1%2BucjZG2BFddgGRMcCgQI63LZav1zRV5COHvmIKWT4r3ig5NI7qTCcSnZezgq9NNK8o2IK%2BonOk39SopisiH4TNIrUoWl%2Fnww%2Fnh%2F3yNr7hpMxkWPI0W7ZLjVGJwyFDHzGcMPJaMgcwxiTfNl0gJn50uJJW9w3ovXWoYSy%2FrIVYj%2BcbVmxkb03tsz8ZQxIy5ipd1aeG9PuFF4KrJ%2FGtYCOYAQAA&config=H4sIAAAAAAAAA2VQPWsDMQzd8yuMx3D0pmTo2hC6NHsoHYRPF5z6C8mGXMP999omMXfEi9DT89N7um9EfvLKSr6Le21yGwkcj57sAsxwYjzgqB0ePX0YYD5qNANn0giG8UGcuyYDdMGYxxJ5JxscgBhpLc2Ti3CrVGWBFekQ249qsAwjpdctxnvGp4eG4i0iOTCfaAJS89j1fRFptF%2FEUKOcwOI6yWODtH5IBhd2%2B16cfRIKnOCASo%2BTkMpb692VZVfC7ksBO5SScmkHmUIRWrCfE46kVfzyw2sSA3%2FT%2BlgBYglX7H43tE7etrIBP%2BtLzZv5H9VuMprtAQAA

**Comment by kdy1** [comment]
@KoraySAP I checked detailed logs to see hidden values of two objects, and it seems like SWC is correct here
