### ISSUE TITLE
If a react key is used after a spread operation it is assigned as a prop

### ISSUE THREAD

**Issue by giggo1604** [swc-project/swc#8767]
### Describe the bug

If a react key is used after a spread operation it is assigned as a prop. I guess this issue is only relevant when using the automatic runtime. Furthermore the key is applied accordingly if there is no spread regardless of the property order.

### Input code

```typescript
function Component() {
  return null;
}

const register = {};

function Expected() {
  return <Component key="foo" {...register} />;
}

function Actual() {
  return <Component {...register} key="bar" />;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
      }
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.8&code=H4sIAAAAAAAAA3XMQQrCMBBG4f2c4qcr3cQD1AoiHkTiRIpxpqQTqITcXVFa6cLtg%2FeFLN56FZz0Maiw2GaLQkBiy0kgOcaWKpFXGe1db%2F1onNCh1JYozPt5GtgbX9f3flFx52fXBNUGxTk3OxW7w4dfoKO3fIl%2FmfX8Q7%2FMC27hvabOAAAA&config=H4sIAAAAAAAAA1WQMQ6DMAxF954Cee5QMXToHXoIKzUoiCTIdqQixN2bBEJhi%2F%2F%2Fed%2FycmsaGMTAq1nSMw0TshAfc1Jk9orfpAAZh2LYTgr36g6SLeVIRVk3A5TRSxfYnUlMaPQkZCl6tY4yHaMGh2rNAV%2BvSOSetOwh7aNt9xiMIUgGdDgK7Zqz3nbzudsENzGJXIM5ir4fj%2F%2B32ltawYVPLOZ%2BHZ0n2jZ4wj9Uyw4wWHnXn%2BU06w9sYduqaQEAAA%3D%3D

### Expected behavior

Key is passed as a third argument.

```
function Expected() {
    return _jsx(Component, {
        ...register
    }, "foo");
}
```

### Actual behavior

Key is passed as a prop.

```
function Expected() {
    return _createElement(Component, {
        ...register,
        key: "foo"
    });
}
```

### Version

1.4.8

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/f2c1da891b9263c560f6475b41b1d5d100144691/crates/swc_ecma_transforms_react/src/jsx/static_check.rs#L3-L7

**Comment by kdy1** [comment]
Related: https://github.com/swc-project/swc/issues/8230
