### ISSUE TITLE
Transforming classes while targeting Safari 5 in strict mode does not work

### ISSUE THREAD

**Issue by AlfonzAlfonz** [swc-project/swc#8781]
### Describe the feature

There is a bug on old Safari (version 5) where you can't in strict mode, declare a function expression with the same name as one of its parameters. This is an issue mainly for transpiling classes with the `_create_class` utility.

Input
```js
"use strict";

class Cache {
	ttl(value, ttl) {
		// ...
	}
}

const cache = new Cache();

cache.ttl();

```

Command
```sh
npx swc ./src/test.js -o test.js -C env.targets.safari=5
```

Error
```
SyntaxError: Cannot declare a parameter named 'ttl' as it shadows the name of a strict mode function.
```

Some safari versions also throws
```
Syntax Error: Cannot declare a parameter named 'ttl' in strict mode.
```

### Babel plugin or link to the feature description

https://github.com/babel/babel/issues/1456

**Comment by kdy1** [comment]
SWC already has bugfix transforms, which can be used in `preset-env` mode.
