### ISSUE TITLE
Directory import error on compiled output

### ISSUE THREAD

**Issue by stelescuraul** [swc-project/swc#8782]
### Describe the bug

Hi everyone,

I have created a small reproducible example of the error which you can find [here](https://github.com/stelescuraul/dep-cruiser-issue).

Using path aliases in `tsconfig` and `swcrc`, the index.js filename is stripped from the end of the import path when using ESM modules. 

```
> npx swc -d ./dist -D --delete-dir-on-start --only="**/*.js,**/*.ts,**/*.cjs,**/*.mjs" --ignore ./node_modules,./dist .
> node dist/projects/api/main.js

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'workspaces/dist/libs/math' is not supported resolving ES modules imported from workspaces/dist/projects/api/main.js
```

The output of in the `dist/projects/api/main.js` looks like this:
```js
import { sum } from "../../libs/math"; <<-- should be /math/index.js
```

Renaming the file "index.js" to anything else resolves the issue and the path is added correctly. EG renaming it to `main.js`:
```js
import { sum } from "../../libs/math/main.js"; <<-- main.js is correctly appended
```

This issue seems to have been introduced in `1.3.106`. last version that worked with this setup was `1.3.105`

### Input code

```typescript
// projects/api/main.ts

import { sum } from "@foo/math";

console.log(sum(1, 2));
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "isModule": true,
  "jsc": {
    "target": "es2022",
    "keepClassNames": true,
    "loose": false,
    "baseUrl": ".",
    "paths": {
      "@foo/math": ["libs/math/index.js"],
      "@foo/math/*": ["libs/math/*"],
      "@foo/common": ["libs/common/main.js"]
    },
    "parser": {
      "syntax": "typescript"
    }
  },
  "minify": false,
  "module": {
    "type": "es6",
    "resolveFully": true
  }
}
```

### Playground link (or link to the minimal reproduction)

https://github.com/stelescuraul/dep-cruiser-issue

### Expected behavior

Correctly append `/index.js` for path aliases.

### Version

>1.3.105

**Comment by kdy1** [comment]
I can't run `npm ci` from the repository you provided.
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://artifactory.workday.com/artifactory/api/npm/npm-virtual/source-map/-/source-map-0.6.1.tgz
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

**Comment by stelescuraul** [comment]
@kdy1 I removed package lock, you should be able to run `npm i` instead.
