### ISSUE TITLE
Difference between SWC and TSC, compilation of inheritance (class a extend b), the constructor is not enumerable in SWC

### ISSUE THREAD

**Issue by KoraySAP** [swc-project/swc#8783]
### Describe the bug

`class a extends b`
In SWC the extends is done through following _inherits method 
<pre>
function _inherits(subClass, superClass) {
    if (typeof superClass !== "function" && superClass !== null) {
        throw new TypeError("Super expression must either be null or a function");
    }
    subClass.prototype = Object.create(superClass && superClass.prototype, {
        <b>constructor: {
            value: subClass,
            writable: true,
            configurable: true
        }</b>
    });
    if (superClass) _set_prototype_of(subClass, superClass);
}
</pre>
The constructor is explicitly set as writable and configurable but not enumerable

In TSC, the extends is done through __extends method
<pre>
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { <b>this.constructor = d;</b> }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
</pre>
Since the constructor is done through simple (=) assignment, it is by default enumerable.

The constructor not being enumerable cause issues in our code when modifying inherited objects down the line. Adding 
`enumerable: true,`
in 
<pre>
subClass.prototype = Object.create(superClass && superClass.prototype, {
        <b>constructor: {
            value: subClass,
            writable: true,
            configurable: true
        }</b>
});
</pre>
solve our issues.

### Input code

```typescript
class MyButton {
    name:string;
}
class SelectionMenuButton extends MyButton {
    sex:string;
}
console.log(SelectionMenuButton.prototype.propertyIsEnumerable('constructor'));
```

### Config

```json
{
    "jsc": {
      "experimental": {
        "plugins": [["swc_mut_cjs_exports", {}]]
      },
      "transform": {
        "useDefineForClassFields": false
      },
      "target": "es5",
      "parser": {
        "syntax": "typescript",
        "tsx": true,
        "dynamicImport": true,
        "decorators": true
      },
      "loose": false,
      "externalHelpers": false,//true,
      "keepClassNames": false
    },
    "module": {
      // You can specify "commonjs", "es6", "amd", "umd"
      "type": "commonjs",
      "strictMode": false,
      "lazy": {
        "patterns": [
            ".*"
        ]
      },
    }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.2&code=H4sIAAAAAAAAA21Sy26DMBC88xVWLgEUhTuoh1Sq1BySVMoHVAa2DpXxInvJQxX%2FXhtIeCQ%2BWLZ3dnbGu5nkxrDd7b0mQsX%2BPGaX4iXEhnShROI1npe1oC%2Bs8Ay6x1RYHeztCEQWZmJMfyGjpI1lqGx2nRFqv5whgi7dLToVZj3jYW%2FskdGRNU5BFMK1Qk1hxDoxR5CWrEC1A1X34uFKoPKJm5aBC7F3jtjdknssueIC8kMrKmaHkXwDtBFCg%2BCugG9Gl%2F3wMyuGffJrY31Va2hOkEyBEyUWjmMtTbtHYdjlhGyrCmIl0Anz%2Finq%2BlGnsshYYcN%2BwAYtZ65dr1znckhrYQsouNyb6Q%2FA1vkJL5%2FAc9Ax%2B%2BHSwOopvNEaL0%2FRJph6mn3hhGXx3etZTNnHKh%2BBYBgCN1UoYS1R%2BC%2Fav640EtKtAneqQNNtaz5UXYLmqQR%2FOZrKZRAk%2F3gXxpD6AgAA&config=H4sIAAAAAAAAA21QsU7EMAzd7yuijKiiEwysoBMMsCPEYKUu6pHEke1KV079d5LqLrQ6slh%2B78X2e6edyc8exNkHc1qa3CpDlJ44rMAMj4JP2A8R98SPHkT2A%2FpOsqgHL3gWzk0dA%2FyFmmmLcmcrnIAFeTtapqhwLFKdEorjIWn9UUZJIZVHXIHdFCEM7iUkYv2HRkcMSixn7upATyR4Ob%2BieFTkCP4ZfUKu9pq2XS%2Bw34hpSeENAm5DOG%2BwgbrR48pp25p3Go2DaCShG%2FrJWEchUDyIbUpO96VA6EoZc6lZ5lhKPH%2FqCyPKg9NX6q6dePiZtjkn0GKunPtR0YW5vbEV%2BNwmNe%2FmXxLxurAoAgAA

_Edit - Simpler repro:_
https://play.swc.rs/?version=1.4.2&code=H4sIAAAAAAAAA22MMQrDMBAEe71Cne3GD4i7QIoUrvICRV6MQb4TdyewCPl7YpMikGw1xczGFFT9WM%2FFjMk%2FnH%2BPwoqTmiw0D%2B7p4uHckBBtYRpB5aNjM9D00yu275xJOaFPPLd%2FTvosbGw1Y6cMsXrVC5UVEu4JbbP3JiUaS9N1wwtaLJnXsgAAAA%3D%3D&config=H4sIAAAAAAAAA21QsU7EMAzd7yuijKiiEwysoBMMsCPEYKUu6pHEke1KV079d5LqLrQ6slh%2B78X2e6edyc8exNkHc1qa3CpDlJ44rMAMj4JP2A8R98SPHkT2A%2FpOsqgHL3gWzk0dA%2FyFmmmLcmcrnIAFeTtapqhwLFKdEorjIWn9UUZJIZVHXIHdFCEM7iUkYv2HRkcMSixn7upATyR4Ob%2BieFTkCP4ZfUKu9pq2XS%2Bw34hpSeENAm5DOG%2BwgbrR48pp25p3Go2DaCShG%2FrJWEchUDyIbUpO96VA6EoZc6lZ5lhKPH%2FqCyPKg9NX6q6dePiZtjkn0GKunPtR0YW5vbEV%2BNwmNe%2FmXxLxurAoAgAA

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: x64
        Machine Type: x86_64
        Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64
        CPU: (12 cores)
            Models: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

    Binaries:
        Node: 20.11.0
        npm: 10.2.4
        Yarn: N/A
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.4.2
        @swc/helpers: 0.5.6
        @swc/types: 0.1.5
        typescript: 5.4.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

I believe SWC and TSC should behave the same in this case, otherwise not sure how to fix this issue.

### Version

1.4.2

**Comment by kdy1** [comment]
Again, SWC is correct here, at least with your simplified reproduction.
SWC does not break ECMAScript specification

**Comment by kdy1** [comment]
You can try running the original source code via browser console and run the transpiled source code to check if the transpilation is corect

**Comment by KoraySAP** [comment]
Thank you for looking into it.

Does that mean that TSC is incorrect/TSC break ECMAScript specification in that case ?

If SWC is supposed to be a drop in replacement for TSC then this difference can be an issue, at least for us this means thousands of tests no longer passing that can't be easily fixed.

If this behavior breaks specifications then is there any chance a plugin similar to what was done for [mutable CJS exports](https://github.com/magic-akari/swc_mut_cjs_exports) could be developed ? So devs can move and then optimize their code step by step ?

If TSC behavior does not break specification, what would be the performance impact of this change ? Seems like it would be easier to have the same behavior.
Thanks.

**Comment by kdy1** [comment]
> Does that mean that TSC is incorrect/TSC break ECMAScript specification in that case ?

I think so.

> If SWC is supposed to be a drop in replacement for TSC then this difference can be an issue, at least for us this means thousands of tests no longer passing that can't be easily fixed.

Being drop-in replacement is about mimicking the behavior when the input code is correct. It's not the case here. If the input code depends on a bug, it's not something that should be mimicked.

> If this behavior breaks specifications then is there any chance a plugin similar to what was done for [mutable CJS exports](https://github.com/magic-akari/swc_mut_cjs_exports) could be developed ? So devs can move and then optimize their code step by step ?

Of course, you can do it.

> If TSC behavior does not break specification, what would be the performance impact of this change ? Seems like it would be easier to have the same behavior.

There will be almost no performance difference.
