### ISSUE TITLE
_define_property() is mistakenly used for !-properties of the class

### ISSUE THREAD

**Issue by dimikot** [swc-project/swc#8792]
### Describe the bug

Vanilla TypeScript compiler doesn't add class properties marked with `!` to the class instance (see example). [TypeScript Playground Link](https://www.typescriptlang.org/play?target=8#code/MYGwhgzhAECyCeBhcVoG8BQ1oG0BEwA9gHYQAuATgK7BmEV4C6AhAFzRnwAOApoQGZwkKCAG4s0QmQAWPCm2jEqAWwBGc8RPJgyAS2DRl8AMpkd+gBQBKdBOxFShEDwB0IQgHMLeI6fPA8KwkAXwwJI1geGUIAE2tbbGwZXQgXB3JqWnoXXzM9YGtxbFDgoA), try both es2021 and es2022.

As opposed to it, SWC (starting from 1.3.40 and till now on) does add them as `undefined` properties. In particular, it's most damaging for `constructor` property: in TS, defining `["constructor"]!: typeof MyClass` is a way to allow methods call static functions like `this.constructor.myStatic()`.

### Input code

```typescript
class MyClass {
  ["constructor"]!: typeof MyClass;
  other!: number;

  static myStatic() {
    console.log("myStatic")
  }

  myMethod() {
    this.constructor.myStatic();
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "target": "es2021",
    "minify": {
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.11&code=H4sIAAAAAAAAA0vOSSwuVvCtdAbT1VwKCtFKyfl5xSVFpckl%2BUVKsYpWCiWVBan5aTBF1kA1%2BSUZqUVAmbzS3KTUImsuoFBxSWJJZrJCbmUwmKGhCTZMQQFkWH5Oql5OfrqGEkxWSRMoVwvSllvpm1qSkZ8CV1%2BSkVmsh%2BQCPYSJ1mBNtQBzcM%2B%2BswAAAA%3D%3D&config=H4sIAAAAAAAAA01OOw6DMAzdc4rIc4eWsbexgkEg8pFtpEaIu9ehadXN7%2Bt3OO9hlQBPf9hpoCAL8Q8bIzUpvowBrYUk8FIUbl91pJAZNbOYQ3mnSzg%2FOijyTNqyJMN9ePQcxCUtU%2F3%2FEjHNGxkz4Sa9xPUiiHncL7GPbENaacgx5rQKNKc73xj6roLOAAAA

### SWC Info output

1.4.11 (see playground link)

### Expected behavior

```
class MyClass {
    static myStatic() {
        console.log("myStatic");
    }
    myMethod() {
        this.constructor.myStatic();
    }
    constructor(){
        // there should be NO _define_property() calls here!
    }
}
```

### Actual behavior

```
class MyClass {
    static myStatic() {
        console.log("myStatic");
    }
    myMethod() {
        this.constructor.myStatic();
    }
    constructor(){
        _define_property(this, "constructor", void 0); // <-- WRONG
        _define_property(this, "other", void 0); // <-- WRONG
    }
}
```

Also, try es2022: it generates the properties as well (directly, not with _define_property). Which is not what vanilla TypeScript does:

```
class MyClass {
    ["constructor"]; // <-- WRONG
    other; // <-- WRONG
    static myStatic() {
        console.log("myStatic");
    }
    myMethod() {
        this.constructor.myStatic();
    }
}
```

### Version

1.4.11

### Additional context

Reproducible starting from version 1.3.40

**Comment by magic-akari** [comment]
When you enable `useDefineForClassFields: true`[Playground 1](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoALrpLAFADGJZoAsgJ5FS0UAG82oUAG0ARB2xpozSB0Z4ZAXQCEDRvwAOsbEj6Du0ANwTQ2RgAtYuHaDSQAtgCNHV60uKMUDlA3fgBlRn9AgAoASjFrSXlFbEJYADpCbABzKJkQ8MiOGRjrAF82axDeWHtsalj4yUl7FGg0pKUWVTw0-IiAjlirSXLSoA) or set the `target: es2022`[Playground 2](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGLWAoAYwBtoMNQBZATwGEyLQBvA0UAbQCIiB7AOwyRYAVyKResLgF0AhGkg0ADol4AzavUYYA3G1C9IAC0Sx5ofiIC2AI1N79Q6JACWRUFZoBlGK6IAKAEoWfXY+QV4SRAA6El54fy5PH2c3LkD9AF8CfU8qZCNeABMgkPZ2YxcMaPChUXFJaOTfNyC9dmzMoA), TypeScript will behave consistently with SWC.

This is correct according to the ECMAScript specification.
To mimic the behavior of TypeScript, set useDefineForClassFields to false.

Alternatively, if you wish to express the code's intention more accurately, you can utilize `declare`.

```TypeScript
class MyClass {
    declare ["constructor"]: typeof MyClass;
    declare other: number;

    static myStatic() {
        console.log("myStatic")
    }

    myMethod() {
        this.constructor.myStatic();
    }
}
```
