### ISSUE TITLE
could not compile `swc_ecma_transforms_testing` (lib) due to 1 previous error

### ISSUE THREAD

**Issue by Zian502** [swc-project/swc#8798]
### Describe the bug

Compiling swc_ecma_transforms_testing v0.139.6
error[E0308]: mismatched types
--> /Users/zian/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/swc_ecma_transforms_testing-0.139.6/src/lib.rs:976:67
|
976 | println!("SourceMap: {}", visualizer_url(&actual_src, sourcemap));
| -------------- ^^^^^^^^^ expected sourcemap::SourceMap, found sourcemap::types::SourceMap
| |
| arguments to this function are incorrect
|
= note: sourcemap::types::SourceMap and sourcemap::SourceMap have similar names, but are actually distinct types
note: sourcemap::types::SourceMap is defined in crate sourcemap
--> /Users/zian/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/sourcemap-8.0.0/src/types.rs:481:1
|
481 | pub struct SourceMap {
| ^^^^^^^^^^^^^^^^^^^^
note: sourcemap::SourceMap is defined in crate sourcemap
--> /Users/zian/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/sourcemap-6.4.1/src/types.rs:459:1
|
459 | pub struct SourceMap {
| ^^^^^^^^^^^^^^^^^^^^
= note: perhaps two different versions of crate sourcemap are being used?
note: function defined here
--> /Users/zian/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/swc_ecma_transforms_testing-0.139.6/src/lib.rs:999:4
|
999 | fn visualizer_url(code: &str, map: &sourcemap::SourceMap) -> String {
| ^^^^^^^^^^^^^^ --------------------------

For more information about this error, try rustc --explain E0308.
error: could not compile swc_ecma_transforms_testing (lib) due to 1 previous error

### Input code

```typescript
-
```

### Config

```json
-
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/

### Expected behavior

cargo build does not report errors

### Version

0.88.3

### Additional context

[package]
name = "my-first-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
serde = "1"
swc_core = { version = "0.88.*", features = ["ecma_plugin_transform"] }

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.

**Comment by Zian502** [comment]
rustc 1.77.0 (aedd173a2 2024-03-17)

**Comment by Zian502** [comment]
rustup 1.27.0 (bbb9276d2 2024-03-08)

**Comment by Zian502** [comment]
SWC 0.8.23

**Comment by kdy1** [comment]
Add `sourcemap="6"` to the `Cargo.toml`

**Comment by Zian502** [comment]
> sourcemap="6"

swc common relies on the sourcemap 8.x release
![image](https://github.com/swc-project/swc/assets/26033663/27564481-f37e-460b-bf84-1ef4840515d1)

**Comment by Zian502** [comment]
![image](https://github.com/swc-project/swc/assets/26033663/91891c26-a7e4-45ca-acfb-5911a7238d30)

**Comment by kdy1** [comment]
https://crates.io/crates/swc_common/0.33.19/dependencies

You can do `swc_common = "=0.33.19"`.

I'll mark changes like this as a breaking change in the future

**Comment by Zian502** [comment]
> swc_common = "=0.33.19"

Is that right? Still report an error
![image](https://github.com/swc-project/swc/assets/26033663/a08812ce-adb3-4d91-a3c1-640207640db4)

**Comment by Zian502** [comment]
![image](https://github.com/swc-project/swc/assets/26033663/d45d1273-4bac-4351-887f-62ec53cae8c6)

**Comment by Zian502** [comment]
![image](https://github.com/swc-project/swc/assets/26033663/3f2a18c3-5f48-4350-b78e-3ae770afa4c1)

**Comment by kdy1** [comment]
You can look at the content of `Cargo.lock` and pin relevant crates
