### ISSUE TITLE
duplicated identifier with `mangle.safari10`

### ISSUE THREAD

**Issue by taozhou-glean** [swc-project/swc#8837]
### Describe the bug

with `safari10` enabled, the generated code is throwing `duplicated identifier` errors

https://github.com/swc-project/swc/discussions/3373#discussioncomment-9064386

### Input code

```typescript
// code taken from https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c9311d91794b7f4b3ae12b82754b1236746e1eb8/lib/msal-browser/src/broker/nativeBroker/NativeMessageHandler.ts#L106
export class NativeMessageHandler {
    static async createProvider(
        logger: Logger,
        handshakeTimeoutMs: number,
        performanceClient: IPerformanceClient
    ): Promise<NativeMessageHandler> {
        logger.trace("NativeMessageHandler - createProvider called.");
        try {
            const preferredProvider = new NativeMessageHandler(
                logger,
                handshakeTimeoutMs,
                performanceClient,
                NativeConstants.PREFERRED_EXTENSION_ID
            );
            await preferredProvider.sendHandshakeRequest();
            return preferredProvider;
        } catch (e) {
            // If preferred extension fails for whatever reason, fallback to using any installed extension
            const backupProvider = new NativeMessageHandler(
                logger,
                handshakeTimeoutMs,
                performanceClient
            );
            await backupProvider.sendHandshakeRequest();
            return backupProvider;
        }
    }
}
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "loose": true,
    "minify": {
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": true
      },
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      }
    }
  },
  "env": {
    "mode": "usage",
    "coreJs": "3.33.3",
    "shippedProposals": true,
    "targets": "last 2 version, >2%, not dead, not ie 11, not ie_mob 11",
    "bugfixes": true,
  },
  "module": {
    "type": "es6"
  },
  "isModule": true,
  "minify": false,
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.104&code=H4sIAAAAAAAAA8VTTY%2FaMBC98ytG2wtIBDdAYaEf0nahWqRdiugeelvZzoS4JDb1OLC02v9eB1q%2BEqnqqXNI%2FPHe5M17CmMgTYTg%2BBI1xNZkkDi3oiFjC%2BWSXLSkydjNj9zizYhlSlpDJnYBz12C2inJnTI6SJWw3G6D2NjgGzGRGsHkoBOG0SDsD7qiH3dFh2PYFtft%2FpuuCNudXr%2FbwxDFNfNklhFPA2HNhtAyspL59dIvte%2B%2Fxo%2F7zXS3eUAivsA7rqMUbcvRq%2Fvwda%2BGzytjHciUE0EVEn7WwBc5fyeB01ZLkBa5w5k1axWhre8ARaVmsUA7hPvdu3k4T3wrSrxXjypDk7sHGoLOM3GKWaH1NmRcS7xNlTdpCJPZ5dkO3RiC%2F3SmCN9VCf7wW%2FFRUMtZLrF%2BVTlecDENSJ6mGLWuGm8PbZzdnjQtShpNDlYWY7QWowP5PWjcVPpYP%2BMfxTVL52W3ypiSW2XIXsRtIZRrR63ZfPxpPJ%2BPR0%2Fjr4%2Fj6ZfJ5%2BnTZHRGOxm5KL7hqmLIFqGO7v6InOP3HMnVL7gWXW51mXxEvXinnUygjo0LcxmDSXykAj471OR%2FGIi5Sgn85LBJfGZr77gPj4xu%2Bqs0FVwuwRnISekFcL0FVUxf5HlsUpFjwctX%2Fz%2FEv4dxrvRfkjhnnsRQ2z9ffgH%2F94Mb1AQAAA%3D%3D&config=H4sIAAAAAAAAA41V22rcQAx9z1cYQ9%2BW0iRQSh%2F6VEopBPoHRuvReCcZj4aR7OwS8u%2BVb5u9jJfC4rV1NLoead7uiqJ85rr8Xrzpq37gXjAF8L%2FRR0ysgKQONxMYITGmo7JK%2BBAE9iop5RCR6%2BSilJsFFd7PBkbJ%2B2xGEgS2lNpTSx4bqA8%2FsaYEQunMscJmAZ5QwIBAzrAnYjwPuXXB2cOpoxZC4%2FFEMkRE0WOPXqUWPB%2FdKvSCGKvaA3OAFnlNw95EY3I9COo%2FxZySw28ZKYOF5O6%2FnKZ6TFbxmtqYkPk8F0hN12KQnB9IiV75orYq3xJ51KasIxVw5YJgM5Hi0nBN3kNkrHpIGStDpJoKU87FAHaC5lidKzwYJ46UlRnUIJiqJoMZyCWsxfWYO6a%2B9FhgGrlwmc8IG9x2TYOXXBympAffaUMzyH5siUabsbojx1LZLuRKOIErNZjAubhX7LFVQulSuD73TC6s9OR%2Fia18Wjt9m%2FQuWB0%2BOWRwHdRclkF3gE6JczZT2aEymMTlupnQdDUOla1z4czwSvnYGazQWuVKxjS%2FOql3OafDxiObAbS%2FYHOsmoDqOIUr%2BDAQN%2BBfmqXkCTZrtCC7dZQP7Zb8DQctyo7MDQVthdA6nHRL7OM63gWDSg00WZWOR%2BB6CegACFUeJccNHQ%2B1WDWeth9rYtmYd8tz3J0lhv7jwmun1VF2DA3OV5d6S%2FhnsFI%2Bfn7U3yLnnYsRzV%2BlIvHlOipFRwVHDpU6VlI8FL1uS%2B3Upvjx8GlTBJJiWFfTm8Pi%2Fn55rVra6ufiR%2FeOdfsz0k2ha7TdyeU1cnDwh%2Fy1PCo5flrUltMf9%2BBc8Pd%2F5hMUQPsHAAA%3D

### SWC Info output

repro from 1.3.104, its still there even on latest version

### Expected behavior

generated code should work

```
try {
} catch(name_here) {
   let should_not_use_same_name_as_in_catch
}
```

### Actual behavior
```
export class NativeMessageHandler {
    static async createProvider(e, a, t) {
        e.trace("NativeMessageHandler - createProvider called.");
        try {
            let s = new NativeMessageHandler(e, a, t, NativeConstants.PREFERRED_EXTENSION_ID);
            return await s.sendHandshakeRequest(), s;
        } catch (s) {
            // s is reused here ^ `catch(s)`
            let s = new NativeMessageHandler(e, a, t);
            return await s.sendHandshakeRequest(), s;
        }
    }
}
```

### Version

1.3.104

**Comment by Auspicus** [comment]
I'm also able to reproduce this. Great report @taozhou-glean. I'm going to dig in and see if I can find the cause here.

**Comment by Auspicus** [comment]
This [PR](https://github.com/swc-project/swc/pull/8857) introduces a test to reproduce this error. I've narrowed the issue down to this block so far: https://github.com/swc-project/swc/blob/main/crates/swc_ecma_transforms_base/src/rename/analyzer/mod.rs#L156-L177

**Comment by Auspicus** [comment]
I guess based on this thread https://github.com/swc-project/swc/discussions/3373 we no longer need the `mangle.safari10` option and it was only kept around to avoid an issue with existing configurations. We can probably remove all of the implementation and leave the option as deprecated.

**Comment by kdy1** [comment]
Yeah, I agree that it's better to remove related code. Will you do it?
