### ISSUE TITLE
Does spack support JSX

### ISSUE THREAD

**Issue by anshulrgoyal** [swc-project/swc#884]
**Question**
Does spack support JSX and React.

**Comment by kdy1** [comment]
Of course. You can enable it by using [.swcrc](https://swc-project.github.io/docs/configuring-swc.html)

**Comment by anshulrgoyal** [comment]
I tried it doesn't even import React stating conditional import not supported.

**Comment by anshulrgoyal** [comment]
So something wrong with my config or it's unsupported at this time.
