### ISSUE TITLE
How to retrieve parsing error ?

### ISSUE THREAD

**Issue by wongjiahau** [swc-project/swc#885]
**Question**
Based on the examples given at https://github.com/swc-project/swc/blob/master/examples/usage.rs, the parse error is directly piped into the stderr instead of being returned as a value, so are there any ways to return the error messages as value instead?

**Comment by kdy1** [comment]
You can create a custom Emitter to get diagnostics.

https://swc-project.github.io/rustdoc/swc_common/errors/emitter/trait.Emitter.html


Is this enough?

**Comment by bartlomieju** [comment]
Real world example:
https://github.com/denoland/deno_lint/blob/2701f07a51d86a3e158f9c3f0307eab08e4018e6/src/swc_util.rs#L72-L117
