### ISSUE TITLE
Does "Selecting the version" article is up to day for next-swc?

### ISSUE THREAD

**Issue by thekip** [swc-project/swc#8862]
### Describe the feature

The users of our swc plugin started to report that it doesn't work with Next 14.2, I see some PRs in next's repo which updates `swc_core` version to `0.90.*`. But "Selecting the version" for nextjs stuck on `v0.82.x ~ v0.87.x`.

**Comment by kdy1** [comment]
I'll check and update the doc today. I think rustc version upgrade of next.js might cause a problem

**Comment by kdy1** [comment]
Can you provide the error message or repro case?

**Comment by thekip** [comment]
https://github.com/lingui/swc-plugin/issues/88#issuecomment-2051531811
