### ISSUE TITLE
How to keep ascii string output

### ISSUE THREAD

**Issue by noyobo** [swc-project/swc#8863]
### Describe the bug

[swc repl](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0soSCwpSS3Ks1WKqTBNTlFKsAYAQ6376BIAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D)

`pattern="\x5cd"` output `pattern="\\d"`

[Rollup repl](https://rollupjs.org/repl/?version=4.14.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMnBhdHRlcm4lM0QlNUMlMjIlNUMlNUN4NWNkJTVDJTIyJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE)

`pattern="\x5cd"` output `pattern="\x5cd"`

Although their syntax is equivalent in js, my running program relies on the ascii code of `\x5c`

When I used swc to replace the rollup project, the program ran unexpectedly.

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0soSCwpSS3Ks1WKqTBNTlFKsAYAQ6376BIAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D

### Expected behavior

keep ascii code

### Version

14.14

**Comment by kdy1** [comment]
Did you read documentation in swc.rs?

**Comment by kdy1** [comment]
If you are using swc via rollup, there's `ascii_only`

https://rustdoc.swc.rs/swc_ecma_codegen/struct.Config.html
