### ISSUE TITLE
swc removes the backslash  "\" when target is "es5" even if "minify" option is not set

### ISSUE THREAD

**Issue by SoonIter** [swc-project/swc#8871]
### Describe the bug

The backslash was deleted when I was using swc, causing a syntax error in the js I inserted into the script tag of html.

```javascript
<html>
   <script>
      var x = "</script>“
   </script>
</html>
```

Babel or TypeScript doesn't seem to have this behavior, which caused string to be modified before minimizing.

[typescript-playground](https://www.typescriptlang.org/play?target=1#code/MYewdgzgLgBAHjAvDARAHgPQpgalRYAJwEsAHKAPhQChRJYBPJVNAHQwJPKtvGhgBezFO3YxxrVjSA)

[babel-playground](https://babeljs.io/repl#?browsers=IE%208&build=&builtIns=false&corejs=false&spec=true&loose=true&code_lz=MYewdgzgLgBAHjAvDARAHgPQpgalRYAJwEsAHKAPhQChRJYBPJVNAHQwJPKtvGhgBezFO3YxxrVjQCmcUiEKwA3nAA0MJqoEBfIA&debug=false&forceAllTransforms=true&modules=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.16.3&externalPlugins=&assumptions=%7B%7D)

Additionally, terser automatically avoids this error, and I am unaware whether it is a good behavior and whether it is worth for swc to follow.

```js
// terser
// input
var x = "</" + "script>";
var y = "<\/script>";
var z = "</script>"
var h = "\/\/"
console.log(x, y, z, h);
// output
console.log("<\/script>","<\/script>","<\/script>","//");
```

### Input code

```typescript
const x = "</" + "script>"
const y = "<\/script>"
const z = "\/\/   \\"

export { x, y ,z }
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "react": {
        "runtime": "classic",
        "development": false
      }
    },
    "target": "es5"
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.15-nightly-20240416.4&code=H4sIAAAAAAAAA0vOzysuUahQsFVQstFXUtBWUCpOLsosKLFT4koGS1WCpWL00YSrQMIx%2BjH6CgoKMTFKXFypFQX5RSUK1QoVOkA9OlUKtQB9gcrVWwAAAA%3D%3D&config=H4sIAAAAAAAAA21Qyw6DMAy78xUo5123w%2F5hH1GVgDr1pSRMQ4h%2FXwu0KtJuje3aideu7%2BHNGp79mp5piIoYqc4J4cWL%2BiYEZInImkwUuBVWOFOjsow7tB0M2BAYEyM04wk54824tNY6uEjIXByqq1N%2BsvjXWEh5HgO51ohQaWmADM1ejMseoK1iNroundgBP2hDdOjlkpJyrmmKJswSQL5DdxLgwjDv%2B52t5WYO0aMRlXvrbWD4VX7mYrrtB6t7kgaBAQAA

### Expected behavior

Same as babel, backslash will not be deleted.
```javascript
var x = "</" + "script>";
var y = "<\/script>";
var z = "\/\/   \\";
```

### Actual behavior

```javascript
var x = "</" + "script>";
var y = "</script>";
var z = "//   \\";
```

### Version

1.4.15-nightly-20240416.4

**Comment by SoonIter** [comment]
> Additionally, terser automatically avoids this error, and I am unaware whether it is a good behavior and whether it is worth for swc to follow.

related links, it has already been realized with `jsc.minify.format.inlineScript`
https://github.com/swc-project/swc/pull/8252
https://github.com/swc-project/swc/issues/7602

But it doesn't seem to work in swc-playground now🤔. I guess it only works in `swc_core` rust api?

[swc-playground](https://play.swc.rs/?version=1.4.15-nightly-20240416.4&code=H4sIAAAAAAAAA0vOzysuUchQsFVIsClOLsosKLGzidGHshK4ksHSiSjSCFmwdH5Oql5OfrpGoo5ChiYAIe6mNk8AAAA%3D&config=H4sIAAAAAAAAA41VS47bMAzdzykCr7toFx0UPUB3XfUAgmJRDqeyZIhUJsFg7l7Kn4wnpoPubD4%2BUvy%2FPR0OzQu1zc%2FDm3zKz2AzQb79i4Suke1FJA1fB6A248DNlwVlqpC3gWAUvU9IwzZ3wJUF9H1Wb0JKBCLjXGAW9RjRX9f%2BfMq95ZVEZBgDRvgz%2BV7zbw5FqU39kIFIo96RRC7vKz1EpuX5n7CcXmnLOaYUwMYHiLFkMDJ0kDXDbQrBDgTmbLNipUZgM1LSXFSwMDgz5DSoeHTImKL43KIOrDNtckomHGZoGc%2Bg0cSX0CJJeEo8I%2BzgWLpubJo7NpxtKJYVn3AZSyWvVayeEhIbX6KWwgncycEEzsm9Z6I3GbjkuOW9JIw7NfkLIBkIlijaHjS7o4aXftpj%2B4dMjF5mgK8KLvOiRRmhk6QaRK9ktmYGMqNWzQyutFAz22rPmeGd9BE6MOC99Ipiml6R25PmtG6N5BVA6mu91lUTYG5TuIPXgXgA%2F5IoWW%2BwWUPWzGkfpWt%2FTOGBgx74lNwDBSkFp304y5a4DPt4iQ6kNcCpKoVGYLsEZAA4mQD3i3LsDRkPsWi6kI4fa2KzSXsbu3HeV3uU0xDgDGGvjf9jRB6i8rZz7eplsjfTCz%2B0prQyePjt66cbJKF8vkVZNnM9K%2Bszk8G2d1cml8jY17ibMRpsm5UrV6NPQ70Zuren2WPTJ1dW6RsnYLqEz82H0nL4lho1SL8X4liV939UctMVngcAAA%3D%3D)

**Comment by noyobo** [comment]
It's really expected that the contents of the original string will be preserved. The developer knows what they are writing and why they are writing it, and does not want the content to be removed.   https://github.com/swc-project/swc/issues/8863  even if they are equivalent。

**Comment by kdy1** [comment]
It should work in playground, and I investigated:

# Investigation

The problem is that we drop `Str.raw` somewhere, and an invalid backslash is removed from `Str.value`.

**Comment by kdy1** [comment]
Lowering priority as the behavior of swc is not wrong.
