### ISSUE TITLE
Add a Dependency Analyzer in node-swc

### ISSUE THREAD

**Issue by littledivy** [swc-project/swc#888]
**Describe the feature**

```typescript
let deps = analyze(`import * from "./a.ts"`);
// [ "./a.ts" ]
```
Get local dependencies by reading the imports/dynamic import statements.

Example:
https://github.com/nestdotland/deno_swc/blob/master/swc_core/src/analyzer.rs

**Babel plugin or link to the feature description**
N/A

**Additional context**
Useful for hot reloading, dependencies analysis, tree shaking.
I'd be happy to open a PR!

**Comment by kdy1** [comment]
Oh... I never thought about those usecases.
I can do it soon. There exists a dependency analysi in spack.

**Comment by divy-work** [comment]
@kdy1 Will it be recursive? Analyzing sub dependencies would be very cool, just need to take care of circular deps!

**Comment by kdy1** [comment]
Of course. Bundlers should fetch all dependencies.

**Comment by kdy1** [comment]
Closing as wontfix. This is too opinionated.
