### ISSUE TITLE
Minify bug when `unused` set to false

### ISSUE THREAD

**Issue by wre232114** [swc-project/swc#8880]
### Describe the bug

when `compress.unused` set to `false`, running minified code throws `Uncaught ReferenceError: e is not defined`.

### Input code

```typescript
function a(module, exports, farmRequire, farmDynamicRequire) {
    "use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
const _interop_require_default = farmRequire("@swc/helpers/_/_interop_require_default");
const _typeof = _interop_require_default._(farmRequire("8178b9bd"));
const _dep734fea04 = farmRequire("92648bed");
const _dayjs = _interop_require_default._(farmRequire("d0dc4dad"));
farmRequire("15d5169f");
var zhCn = (0, _dep734fea04.c)(function(module, exports) {
    !function(e, _) {
        "object" == 'object' && "undefined" != 'object' ? module.exports = _(_dayjs.default) : "function" == typeof undefined && undefined.amd ? undefined([
            "dayjs"
        ], _) : (e = "undefined" != typeof globalThis ? globalThis : e || self).dayjs_locale_zh_cn = _(e.dayjs);
    }(_dep734fea04.a, function(e) {
        "use strict";
        function _(e) {
            return e && "object" == (0, _typeof.default)(e) && "default" in e ? e : {
                "default": e
            };
        }
        var t = _(e), d = {
            name: "zh-cn",
            weekdays: "星期日_星期一_星期二_星期三_星期四_星期五_星期六".split("_"),
            weekdaysShort: "周日_周一_周二_周三_周四_周五_周六".split("_"),
            weekdaysMin: "日_一_二_三_四_五_六".split("_"),
            months: "一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月".split("_"),
            monthsShort: "1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月".split("_"),
            ordinal: function ordinal(e, _) {
                return "W" === _ ? e + "周" : e + "日";
            },
            weekStart: 1,
            yearStart: 4,
            formats: {
                LT: "HH:mm",
                LTS: "HH:mm:ss",
                L: "YYYY/MM/DD",
                LL: "YYYY年M月D日",
                LLL: "YYYY年M月D日Ah点mm分",
                LLLL: "YYYY年M月D日ddddAh点mm分",
                l: "YYYY/M/D",
                ll: "YYYY年M月D日",
                lll: "YYYY年M月D日 HH:mm",
                llll: "YYYY年M月D日dddd HH:mm"
            },
            relativeTime: {
                future: "%s内",
                past: "%s前",
                s: "几秒",
                m: "1 分钟",
                mm: "%d 分钟",
                h: "1 小时",
                hh: "%d 小时",
                d: "1 天",
                dd: "%d 天",
                M: "1 个月",
                MM: "%d 个月",
                y: "1 年",
                yy: "%d 年"
            },
            meridiem: function meridiem(e, _) {
                var t = 100 * e + _;
                return t < 600 ? "凌晨" : t < 900 ? "早上" : t < 1100 ? "上午" : t < 1300 ? "中午" : t < 1800 ? "下午" : "晚上";
            }
        };
        return t["default"].locale(d, null, !0), d;
    });
});
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.17-nightly-20240421.1&code=H4sIAAAAAAAAA5VWbW8bRRD%2B7l%2BxOantmRrblziJ7RAFRD70AxaIREKoqk7nuzV35V7cu70Uh0biRSkJNEJUkUJpUfgAgoIi8aFCCb8ndsW%2FYGZ37%2Bxz1qacdPsyz8wzszO7e9dLQ5t5UUgsPYic1KcVQj%2FpRzFLKqRnxcH79F7qxVRMNgehFXi2lJXJpyUCj5YmlCQs9mymrZXe7d6lNqs6tOeF9L046tOYDfScUzNNmnS4J60iCXYsP6VtwuKUlvbKayU7ChNGTC9kFOzNWLgzgdJKfUbWJwPTtTeT%2B3bNpT44SmpmbZaZNiZmgz6NesAzS7dq6gUXTWO12W11Ha08JnFof3Wp0aNWvTEdUWtxpdHsUmfCpWMN7ib%2Fw6NTd%2ByGYwmPBcRYdpaNlVYPyXesmOy6b4dArNcrhZiqdlnvydpOVzYr3EKuAJiZSXlJI15FjayvkxtifINcvw6lDkVhHY0sTEAbRLioSg%2B4Ul0suipXWCZtomUOObEsQ06JDvJJ1QocoM3n%2Bu08OB4g59Zy2R2%2BgDbRKbieilL6%2BciPupa%2F7XoJ8E5M2oSSBw9IQv1eucppTT%2ByLZ%2Bau65ph3wpVACQcnS2pxcybcHhyBNZyGLhYGTSTBdpJ7XxiSlL4xACwlxP1IBXV6wjzydao1q2v4mHhhvwtqdYRcKkGiy3AO6NI9vLR7ixmFh5uUIcGBUZ4RqAA6vtuq%2FboVYpQPcp%2FRiSlQA8%2Bv509Ox0dPKLKUaX559lo78f5bJDORo%2BfZqjx5ls%2F0yrJn3fY7pmamW1py0Xthy4G373G%2FqCDh1hB1747BA75OfCYz57FeaOF%2BIygBQZkY5zARFnmUcRRCFzMQlgOXp2gMa8Oz%2FEDiiE8JjP9s8E9qWY%2FcFnFz%2Fy2dHnspNEOOJc%2F%2BU7S4uBVovYLGHTwGYZmxVsVrFpYtPCxqjzltsYi3O9RLHjhZbfHm9oKblym0ztbu0D3NOwufhmvckLp%2FFjeJMne%2BKs8F15tTZbzMKlGUVkQK1YIo0i0oviwGKJ6ly8sw0punWrHQRT%2B1iAWxnaThKVAsAfwlPrdGqbmyqFTGN48aID6dzE9anUFHpvuS%2B%2FuAiC4cFDtYXCxIFnrpmfB1xThev7rxSur9Ijs7LoK9UxVGkyr9wx9S3m7dBtD2%2Bcq%2FXrpbCn8C66lgwf7iu8962ECfjwSAHjER1%2B9dPLXx8rwACPD4FM%2FvP4VAUjfs2ZreAK%2Bz%2B%2FHZ38pYJdaT9LwRH2Pz9XYY40VqIdbnl5%2FjseYQXcEcYzFQbC88ULFTaQngGdV7qAxp7j0WDihshEM6%2BI7MNj1OvkNX4jmGtXlOQ9wsgbZAX0NrCCj0ZP%2BCWCwpYQjk6eX55%2FnQkNQ0hBNDw6yKVLmfRsUtrMpN9IqTZ68gOSTV1N40%2FnGMiiu51%2Fcu9UxQ%2BF7lRImPp%2BhSzU8bMq%2Fybgr4K%2FpX8BdPuecIwLAAA%3D&config=H4sIAAAAAAAAA42VzW7bMAyA732Kwuce2h22Yedh2GXPICgW5aiTRYOk0xhF3n30X5o0dLBL4PDjj0iR1PvD42P1ynX14%2FFdP%2FUPHAWo%2BPwbcgfECoR6eJph54mBzsoq4aGIP6qkkqEDril1Uj2tVHhE0WeGSXRa%2FAj5whGpvXSVofH18BNqJC9IV5HPhp4akDEc8Jfnl29LqCojMqyhFlmbSorDZYQa246A%2BUKmUnXZt1CEr%2B0XRvh2XYRJvkPMoDlsE%2BfZpSLQzEX87LjGnH3H4A6eDC%2FjST0lRivECHuB4DrCzuQlJEmot2jQAD64GgMYKBHUkg5gmWksNSus6Rn5TDjArm8aoFtrOPjcezFiwnG6Ej2t4XWPicXFvlglnOFGDWa4FPezZYqOQHoqt3avmMrGnfwF0Apkz1x8C5bfSSNqP21Zx7uWqURtWRkMrv1tZVl0ZARcStGo7FgZIEnWbRKEvoaxsrV1nAVvlI9TAAcxaq8YrvktSb23go4bAqMB9H59tLpqBu48hRt8HIg7%2BJdmKXaDLRqtl%2F025aHdYb4ToAXZY7ijoFchuI1Jt8Sx2%2BZ9CaCtAcFU6dkE46yKE3R5Wpg3zaHzoS5dk3H3sScWhdN5g7e%2BNNPAXyxMwS7DAfJWH%2F%2FHjNylerbD2NbraN%2BML3y3utLr5KWX56sHR1N5WH%2BnpKoWQ3%2BR0NSU83vytfpQWp%2BOc5Aq8Z%2FVcirU6R8XqlsDOwcAAA%3D%3D

### Expected behavior

work normally

### Version

1.4.16

**Comment by kdy1** [comment]
Can you share a repro that can be executed? I can't execute it because of `farmRequire` and etc

**Comment by kdy1** [comment]
I'll reopen this once you provide a reproduction case

**Comment by wre232114** [comment]
<img width="1503" alt="image" src="https://github.com/swc-project/swc/assets/8372439/33547d16-29ac-4835-bbcc-6712ac878af9">

`_dep734fea04.a` is transformed to `e = n.a`, which `e is not defined`
