### ISSUE TITLE
Why do you keep changing this version?

### ISSUE THREAD

**Issue by TryChai** [swc-project/swc#8885]
### Describe the bug

I made a mistake when I packaged the version, and from time to time, I made a mistake, why do I have to change this version often
![image](https://github.com/swc-project/swc/assets/30064871/0518cbb3-d78d-48c1-b58d-ff4730d78339)

### Playground link (or link to the minimal reproduction)

https://jenkins.localhome.cn/job/lky-ui/job/dev/455/console

### Expected behavior

Don't change it. Let this version go

### Version

1.4.7

**Comment by kdy1** [comment]
You should not depend directly on it.
