### ISSUE TITLE
swc/jest not support array.with

### ISSUE THREAD

**Issue by PeterChen1997** [swc-project/swc#8889]
### Describe the bug

It's a feature in es2023, I changed my swcrc file's target, but I still get the problem...
![image](https://github.com/swc-project/swc/assets/21072589/7be1b381-a29b-455a-a6f9-e7d3dc421a46)

### Config

```json
[
  {
    "test": ".*.tsx?$",
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "decorators": true,
        "dynamicImport": true,
        "tsx": true
      },
      "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true,
        "react": {
          "runtime": "automatic",
          "refresh": true
        }
      },
      "externalHelpers": true,
      "target": "es2023"
    }
  },
  {
    "test": ".*.js$",
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "decorators": true,
        "dynamicImport": true
      },
      "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true
      },
      "externalHelpers": true,
      "target": "es2023"
    }
  }
]
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0ssKkqs1CvPLMnQ0AQA0rYmxAwAAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D

### Expected behavior

support properly

### Version

0.2.26

**Comment by zloirock** [comment]
You missed
```js
  "env": {
    "mode": "usage",
    "coreJs": "3.37"
  }
```

**Comment by PeterChen1997** [comment]
Thx!
