### ISSUE TITLE
Keep `assert` and `with` keywords as is

### ISSUE THREAD

**Issue by petamoriken** [swc-project/swc#8893]
### Describe the bug

V8 will remove support for the `assert` keywords, so Node.js and Chrome will follow suit.

> Hey, quick update on this. Node.js is planning to remove support for assert in v22 (which will be released in April) and Chrome in v126 (which will be released in May).

https://github.com/denoland/deno/issues/17944#issuecomment-2027005952

I'm trying to implement this in Deno as well (https://github.com/denoland/deno/pull/23541), but it doesn't work because swc commonizes the `assert` and `with` keywords. Please add a new option to pass those keywords as is to V8.

### Input code

```typescript
import foo from "./foo.json" with { type: "json" };
import bar from "./bar.json" assert { type: "json" };
console.log(foo);
console.log(bar);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "experimental": {
      "keepImportAttributes": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.5.0&code=H4sIAAAAAAAAA8vMLcgvKlFIy89XSCvKz1VQ0tMHsvWyivPzlBTKM0syFKoVSioLUq0UlCBitdZcmRA9SYlFcD1ANlRPYnFxKlASU1dyfl5xfk6qXk5%2BugbQCk1UEaABmtYAe1o9F40AAAA%3D&config=H4sIAAAAAAAAA21QOw6DMAzdOQXy3KFi6NCtY4ceIqUGpU1IZBsJhLg7CSSUSt3i9%2FNzpqIs4c01XMspPMPgFTHSPgeEx07UEBCQ0SPXpL3AKbPCkWqUYVyheWNAFLUo0YVcnasqOcA4x5gdCbO608143Fk76wmZf4VRqrrW4N%2BNOHgkbTG0NcesD6K%2FW%2B9IbiKkn71gzBXqk79IGWDdq1%2FD01%2FEe7cLLvAV5bJ7MdD8yM41dV4AwZk7Q1cBAAA%3D

### Expected behavior

```js
import foo from "./foo.json" with {
    type: "json"
};
import bar from "./bar.json" assert {
    type: "json"
};
console.log(foo);
console.log(bar);
```

### Actual behavior

```js
import foo from "./foo.json" with {
    type: "json"
};
import bar from "./bar.json" with {
    type: "json"
};
console.log(foo);
console.log(bar);
```

### Version

1.5.0

### Additional context

related options:

https://github.com/swc-project/swc/blob/c76cd9eccf080da67d1c8d75063f8286dfc4acc1/packages/types/index.ts#L607-L616C9

**Comment by kdy1** [comment]
Closing as not planned. This require modification of AST, but it does not worth it.

**Comment by petamoriken** [comment]
@kdy1 Then, could you add `importAssertions: boolean` to `TsParserConfig` to disable the `assert` keywords in TypeScript?

**Comment by kdy1** [comment]
I'll accept a PR, but it should named differently so the default value can be false
