### ISSUE TITLE
`dynamicImport` option doesn't work with CJS export TypeScript

### ISSUE THREAD

**Issue by aramissennyeydd** [swc-project/swc#8914]
### Describe the bug

I'm working to allow Backstage to use ESM modules using dynamic imports as part of our migration path away from CJS, https://github.com/backstage/backstage/pull/22638. We're using Rollup for production builds and SWC locally. I'm unable to get SWC to keep dynamic imports in our output.

### Input code

```typescript
console.log(import('./test.mjs'));
```

### Config

```ts
{
    filename,
    sourceMaps: 'inline',
    module: { type: 'commonjs' },
    jsc: {
        target: 'es2022',
        parser: {
          syntax: 'typescript',
          dynamicImport: true,
        },
      },
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.13&code=H4sIAAAAAAAAA9NILK7MS1bQ0LS1q%2BZSUEjOzysuUShJBRK2ConliZklCpm5BflFJRrqmXnZ6prWKGqMMBTp6YPE9XKzikFqazUBQDmEwl8AAAA%3D&config=H4sIAAAAAAAAA2WPPQ7DMAiF954iYu5QZewNOvQQlkMiR8G2gEi1oty9dn7cVt3gffAeLJemgVEs3Jsll7mJhgW59lmR5NW8sgKaIoplFxWuJ1UpqDeTYNW65A05%2B6AYWDNVnnFj6z4CanjAQgClvbXtYQdTCIK%2FdkDOuz59H2QDRUaRv1wyfpjq%2Fp54OVKBQjdv8Hi0PFMuyG4U%2FCjwmTwTqzs4eZ7r2zPrG1secAA5AQAA

edit: updated to one with `dynamicImport` set - the behavior is the same.

### Expected behavior

The import statement is preserved

### Actual behavior

```
console.log(Promise.resolve().then(()=>/*#__PURE__*/ _interop_require_wildcard(require("./test.mjs"))));
```

### Version

@swc/core: 1.4.8

**Comment by kdy1** [comment]
@aramissennyeydd You can set `jsc.module.ignoreDynamic: true` to keep dynamic imports.

https://play.swc.rs/?version=1.4.13&code=H4sIAAAAAAAAA9NILK7MS1bQ0LS1q%2BZSUEjOzysuUShJBRK2ConliZklCpm5BflFJRrqmXnZ6prWKGqMMBTp6YPE9XKzikFqazUBQDmEwl8AAAA%3D&config=H4sIAAAAAAAAA2WPvQ7DIAyE9zxF5LlDlbFzlw59CEQcRBR%2BZBOpKMq7FxKgrbrh%2B8zdeev6HmaWcOu39EyDF8RIbU4KRxvEKykQokeWpH2AS6WBM5rEwti0MVphtHwY7ygkGmjFg%2B3nCgRBCjMB5OE6DMUOFucYf%2B3AaKun%2BF1IOuMJmf9yjbBqaf%2FPxK6kgnHjesByaD4mN0huxtmZawetrCO8nyd8yheTWqYFg%2BZndT5W9zezPjwdVAEAAA%3D%3D

I'll close this issue with a documentation commit

**Comment by kdy1** [comment]
Oh it was documented. https://swc.rs/docs/configuration/modules#ignoredynamic
