### ISSUE TITLE
SWC Core throws / prints (misleading) error

### ISSUE THREAD

**Issue by jd-carroll** [swc-project/swc#8944]
### Describe the bug

We are receiving hundreds of errors in our console using TSUP + @swc/core:
```
  ERROR  failed to read input source map: failed to parse inline source map url
index.js.map
Caused by:
    relative URL without a base
    at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.27/src/lib.rs:385
```

These errors seem to be thrown when the corresponding `.js.map` file is missing from the bundled sources. 

It would be nice if `@swc/core` printed a more meaningful error message.

Note: I have no idea how to produce a repro, but I've spent a fair bit of time debugging this with console.log and I am relatively confident that this is the case.

### Playground link (or link to the minimal reproduction)

https://github.com/egoist/tsup/blob/00188a0dc848c48fac45de245d1e021f370a84a3/src/esbuild/swc.ts#L31-L49

### Expected behavior

If an error is to be thrown / printed, print something more descriptive to the issue as well as a little more context.

### Version

1.5.5

### Additional context

Possibly related:
#8879
#8910
https://github.com/swc-project/swc/issues/8789#issuecomment-2105055772

Less likely related but will link anyways:
#8628

**Comment by jd-carroll** [comment]
@davidmurdoch I am seeing the same behavior related to sentry. The issue is (of course) `opentelemetry`. A number of the published modules list source maps, such as:
```
//# sourceMappingURL=internal-types.js.map
```

But inspecting the installed module, the source maps do not exist.

**Comment by kdy1** [comment]
Closing as duplicate

**Comment by jd-carroll** [comment]
@kdy1 duplicate to what?

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/8789
