### ISSUE TITLE
Module name shadowed with local variable

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#895]
See https://github.com/Brooooooklyn/swc-node/blob/master/packages/integrate/__tests__/name-shadowed/shadowed.ts

- `yarn`
- `cargo build --release && yarn build-release`
- `yarn test`

Input

```ts
import { queryString } from './url'

export function setup(url: string, obj: any) {
  const _queryString = queryString(obj)
  const _url = url + '?' + _queryString
  return _url
}
```

Output

```ts
var _url = require('./url');
function setup(url, obj) {
    const _queryString = _url.queryString(obj);
    const _url = url + '?' + _queryString;
    return _url;
}
```

Error

```
ReferenceError {
  message: 'Cannot access \'_url\' before initialization',
}
```

**Comment by kdy1** [comment]
I added some tests and I concluded swc is working properly.
You have to run resolver before applying module transforms. Also, you have to provide same global mark to each of them.

**Comment by Brooooooklyn** [comment]
Reproduce this issue with `disable_hygiene = true`

**Comment by kdy1** [comment]
@Brooooooklyn This behavior is expected if you disable hygiene.
