### ISSUE TITLE
Does not support type only import/export syntax

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#896]
**Describe the feature**

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Behavior in current version**

```
error: Expected LBrace, got Some(BinOp(Mul))
  --> packages/types/src/index.ts:13:13
   |
13 | export type * from '../typings'

```

**Comment by kdy1** [comment]
`export type * from '../typings'` seems like an invalid syntax.

Error message from tsc: `TS1383: Only named exports may use 'export type'.`

**Comment by Brooooooklyn** [comment]
Oh, interesting
But TypeScript can handle this case with:

```ts
// @ts-ignore
export type * from '../typings'
```
