### ISSUE TITLE
html codegen does not output closing tags for `html` and `body`

### ISSUE THREAD

**Issue by shulandmimi** [swc-project/swc#8962]
### Describe the bug

html codegen does not output closing tags for `html` and `body`

### Playground link (or link to the minimal reproduction)

https://github.com/shulandmimi/swc-html-codegen-error

### Expected behavior

```html
<!doctype html><html lang=en><head>
  <meta charset=UTF-8>
  <meta http-equiv=X-UA-Compatible content="IE=edge">
  <meta name=viewport content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id=root></div>
  <script src=./src/index.tsx></script>
</body>
</html>
```

### Actual behavior

```html
<!doctype html><html lang=en><head>
  <meta charset=UTF-8>
  <meta http-equiv=X-UA-Compatible content="IE=edge">
  <meta name=viewport content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id=root></div>
  <script src=./src/index.tsx></script>
```

### Version

latest

**Comment by kdy1** [comment]
cc @alexander-akait

**Comment by magic-akari** [comment]
This is a compression technique, and according to the spec at https://html.spec.whatwg.org/multipage/syntax.html#optional-tags, these end tags are optional.

[An html element's end tag may be omitted if the html element is not immediately followed by a comment. ](https://html.spec.whatwg.org/multipage/syntax.html#void-element:~:text=An%20html%20element%27s%20end%20tag%20may%20be%20omitted%20if%20the%20html%20element%20is%20not%20immediately%20followed%20by%20a%20comment.)
[A head element's end tag may be omitted if the head element is not immediately followed by ASCII whitespace or a comment.  ](https://html.spec.whatwg.org/multipage/syntax.html#void-element:~:text=A%20head%20element%27s%20end%20tag%20may%20be%20omitted%20if%20the%20head%20element%20is%20not%20immediately%20followed%20by%20ASCII%20whitespace%20or%20a%20comment.)
[A body element's end tag may be omitted if the body element is not immediately followed by a comment.  ](https://html.spec.whatwg.org/multipage/syntax.html#void-element:~:text=A%20body%20element%27s%20end%20tag%20may%20be%20omitted%20if%20the%20body%20element%20is%20not%20immediately%20followed%20by%20a%20comment.)

**Comment by shulandmimi** [comment]
> This is a compression technique, and according to the spec at [html.spec.whatwg.org/multipage/syntax.html#optional-tags](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags), these end tags are optional.这是一种压缩技术，根据 html.spec.whatwg.org/multipage/syntax.html#optical-tags 上的规范，这些结束标记是可选的。

thanks for the explanation.
