### ISSUE TITLE
Setting `importAttributes` in jsc.parser forcely outuput CommonJS

### ISSUE THREAD

**Issue by Armadillidiid** [swc-project/swc#8991]
### Describe the bug

When enabling import attributes/assertions in `swcrc` config, it forcefully transpiles my code from ESM to CJS despite `target` set to `es6`. If I remove the `importAttributes` option, it compiles fine to ESM.  Below is the output code:

```typescript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "countries", {
    enumerable: true,
    get: function() {
        return countries;
    }
});
const _countryjson = /*#__PURE__*/ _interop_require_default(require("./country.json"));
function _interop_require_default(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
const countries = _countryjson.default;

//# sourceMappingURL=country.js.map
```

### Input code

```typescript
import countryJSON from "./country.json" with { type: "json" };

export type Country = {
  name: string;
  dial_code: string;
  code: string;
};

export const countries: Country[] = countryJSON;
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "es6"
  },
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
      "importAttributes": true,
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./"
  },
  "minify": false
}
```

### Playground link (or link to the minimal reproduction)

[Playground Link](https://play.swc.rs/?version=1.5.7&code=H4sIAAAAAAAAA8vMLcgvKlFIzi%2FNKymq9Ar291NIK8rPVVDS04eK6WUV5%2BcpKZRnlmQoVCuUVBakWikoQcRqrbm4UivABoDEFZwhOhRsFaq5FBTyEnOBSotLijLz0q2B%2FJTMxJz45PwUFEFUPpKByfl5xTB3ZaYWW8EMj44FGo%2FkXGsA%2Fq48iMIAAAA%3D&config=H4sIAAAAAAAAA22RwU7DMAyG7zxFFXFELeqBw24TCIlDufEAXup2GUkT2a5YNe3dSdJ26hBH%2F%2F79xb9zeSgK9cj6iA7UrlBHkcC7qjqxH8pZZvGEpae%2B4h9NWj2lEfYjaWwgcJwSGjGrzrejxahcYhVrmUKqFPKLiso1m06sNw6gHmX21M91nelRD0CMdPOlF6dB4JycicqaTJDFnTicWh1YxixdF44QDNx5cluUxR709IbaE8RwmwS53a6NBgVaEFgMd%2BBvxPBqgfkTHPIdQh2A8Yts2rWs1kR4DkjGYUxhN8ssqA8XPMlehMxhlD%2FAed4Z2XM8irx7%2Bse%2ByX47tTOD6aa1mSXDzfpJOdP1F4i%2FCC4CAgAA)

### SWC Info output

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Feb 2024 19:08:51 +0000
        CPU: (12 cores)
            Models: AMD Ryzen 5 4600H with Radeon Graphics

    Binaries:
        Node: 22.0.0
        npm: 10.5.1
        Yarn: N/A
        pnpm: 9.1.1

    Relevant Packages:
        @swc/core: 1.5.7
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.4.5

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A
        
     Nest.js info:
        version: 10.3.8
     
     

### Expected behavior

Include the `with { type: "json" }` in transpiled code in ESM format

### Actual behavior

Transpiles code to CommonJS

### Version

    "@swc/cli": "^0.3.12",  "@swc/core": "^1.5.7"

### Additional context

Here is my `nest-cli.json` config:

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "assets": ["**/*.json"],
    "builder": {
      "type": "swc",
      "options": {
        "outDir": "dist",
        "extensions": [".ts", ".tsx", "d.ts"]
      }
    }
  }
}
```

**Comment by kdy1** [comment]
I read playground, and your repro is wrong.

**Comment by Armadillidiid** [comment]
The problem was a trailing comma causing Nestjs to use the fallback config. This wouldn't have been an issue if swc configs have a `.json` extension so your editor could easily highlight the error.

**Comment by kdy1** [comment]
SWC supports trailing commas in swcrc
