### ISSUE TITLE
connot find module '@swc/core/VIsitor.js'

### ISSUE THREAD

**Issue by longge0516** [swc-project/swc#8997]
### Describe the bug

Error wher install @swc/core@1.5.22
<img width="832" alt="0zm4y12000e8lmighD16B" src="https://github.com/swc-project/swc/assets/10055044/e6ccc58b-750b-49c6-9218-040aa44453ed">

### Input code

```typescript
npm install @swc/core/VIsitor.js
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/

### Expected behavior

No error

### Version

1.5.22

**Comment by sunmengm** [comment]
I also encountered this problem
