### ISSUE TITLE
Mangle function name duplicate with parameter names

### ISSUE THREAD

**Issue by chinalichen** [swc-project/swc#9015]
### Describe the bug

output code:

`runOnce(function e(e,c=0){});`

Run this in Safari (iOS 16.1.1) throw error:
![image](https://github.com/swc-project/swc/assets/2139908/a2339956-a72f-4e18-b21a-f4438980246e)

Works in chrome and latest safari.

### Input code

```typescript
runOnce(function dup_func(dup_param, offset = 0) {})
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.5.24&code=H4sIAAAAAAAAAytKTc8sLkkt0kgrzUsuyczPU0gpLcjJTE4sSY0HCWkguAWJRYm5Ogr5aWnFqSUKtgoGmgrVtZpcACgasG1CAAAA&config=H4sIAAAAAAAAA1WPSwrDMAxE9zmF0bqLttAueocewrhKcPAPS4GGkLvH33521sw8j7QNQsBMCh5iS880BBkJ42dOCq2O5TspgMpKUlEHhlN3Z8rWKA1hkfbqAMs4IReKrufLrRFgvCfsRNOsdnpcfzuVtyEi0X8wR6WbTOY5Lq1waKVg%2FWspXjuF14B1gTt8Q70rf1AUTc8O1jP2A%2BC7qlwWAQAA

### Expected behavior

runOnce(function n(e,c=0){});

### Actual behavior

runOnce(function n(n,c=0){});

### Version

1.5.24

**Comment by Austaras** [comment]
Note: this seems to be Safari only bug.

**Comment by Austaras** [comment]
But we should rename the function name anyway.
