### ISSUE TITLE
panic: not implemented: emit_private_prop

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#903]
Occurred when working on this PR: https://github.com/denoland/deno/pull/6895

Using `swc_ecma_codegen 0.28.0`

```
▶ target/debug/deno cache --reload --no-check std/examples/chat/server_test.ts
thread 'main' panicked at 'not implemented: emit_private_prop', /Users/biwanczuk/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_codegen-0.28.0/src/lib.rs:897:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File causing panic: https://github.com/denoland/deno/blob/c8fc679/std/examples/chat/server_test.ts

**Comment by kdy1** [comment]
Fixed it. I will merge it if check passes

**Comment by bartlomieju** [comment]
@kdy1 thanks! Just tried uploading AST dump, but it seems it's not needed

**Comment by kdy1** [comment]
@bartlomieju It's quite simple to implement.
It was unimplemented! just because no one used swc to print private properties as-is - swc transforms it to a special hidden variable.

**Comment by bartlomieju** [comment]
Thanks for explanation. Just to be clear, should something like this work without additional transforms?
```rust
let program = Program::Module(module);
let mut pass = typescript::strip();
let program = helpers::HELPERS.set(&Helpers::new(false), || {
  util::HANDLER.set(&self.handler, || {
    // Fold module
    program.fold_with(&mut pass)
  })
});

...emit program...
```

**Comment by kdy1** [comment]
I think it will work, even without `HELPERS` or `HANDLER`.

 - Helpers are not required for typescript stripper (permanently, as ts syntax is designed after js syntax)
 - Handler is **currently** not required (and I think it will not in the future, but it's not 100%)

**Comment by bartlomieju** [comment]
Sounds great, thanks for quick response on this issue!

**Comment by kdy1** [comment]
@bartlomieju Published a new version
