### ISSUE TITLE
No more standalone binaries upload in release assets since 1.5.8

### ISSUE THREAD

**Issue by Klaitos** [swc-project/swc#9035]
### Discussed in https://github.com/swc-project/swc/discussions/9034

<div type='discussions-op-text'>

<sup>Originally posted by **Klaitos** June 11, 2024</sup>
Hello,
We were downloading swc binaries from Github in our CI to generate source maps. 
Since v1.5.8, only .node files are uploaded and not executable on system anymore. Is this an expected behavior ?

Assets uploaded before : 
- swc-darwin-arm64

Assets now : 
- swc.darwin-arm64.node (little change in naming too after swc)

Thanks

</div>

**Comment by kdy1** [comment]
I triggered a nightly release with https://github.com/swc-project/swc/commit/dab7bfca536686f1c38dc569d16c756578f67053

I'll publish a normal version if the CI fix was correct and nightly publish action works as expected

**Comment by Klaitos** [comment]
Thanks
