### ISSUE TITLE
overwrite Symbol cause Symbol undefined when target to es5 

### ISSUE THREAD

**Issue by stormslowly** [swc-project/swc#9045]
### Describe the bug

the output code will be similar to below,  then get can't read iterator of undefined.

```js
for ( y[Symbol.iteraor]()  // due to hoist the Symbol is undefined
...
var Symbol = function Symbol(){ ... 
...
```

### Input code

```typescript
"use strict";
let y = [1];
function a(y) {
  for (let x of y) {
    console.log(x);
  }
}
a(y);
class Symbol {
  constructor() {}
}

console.log(new Symbol());
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.5.29&code=H4sIAAAAAAAAA03MsQoCMRAE0H6%2FYrhq0wjWwa%2BwFIsYEjmIWUg2eEHu303Uwm4Y3szSakDVsnpdLKWg6Djhcrxaii17XSXDscGLgCgFPMkGiejfEvCSq6RwSHLnzdjR7bST4z6yT65WnPvjJunDJ9bSvEqZr1PS%2F0EOzx9nM%2FZvAZXX6J8AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAxE95wCed1tN71DD2FRJwLxEyZSUZS7Fyikzc4z8%2ByRdyElGFbwkHsdq4iYmNKpq8PFZ3xXB0g5ZJV0zHCbqeEWLWiZunV8E8iYVsp9i%2B8DBxsC08SH57TXS%2FkvVMHFRMxXsKHoV0vXOjEqwYXX1sPxSC6xqXbNBW8YfuRsPK%2BD5udcz2kjcXwAmJf30BkBAAA%3D

### Expected behavior

`var Symbol = function Symbol (){ ...`

should change to 
`var _$Symbol = function _$Symbol (){ ...` to  avoid the overwrite

### Version

1.5.29

**Comment by stormslowly** [comment]
what workaround is to rename all the resolved `Symbol` to  `_Symbol` before preset_env

is there any better ways now ?

**Comment by kdy1** [comment]
You should not declare a variable named `Symbol`, if you want to access global `Symbol`. This is expected behavior.
Try running the original code and the transpiled code.

**Comment by stormslowly** [comment]
@kdy1 ,  I fully understand that overwrite `Symbol` is bad, but it happens in the npm package @svgdotjs/svg.js
https://www.unpkg.com/browse/@svgdotjs/svg.js@3.2.0/dist/svg.js
line 13-17 contains the for-of syntax in a function; line 6236-6242 is the class Symbol definition。
```js
function registerMethods(name, m) {
  if (Array.isArray(name)) {
    for (const _name of name) {
      registerMethods(_name, m);
    }

    return;
  }
```
 line 6236-6242 
```js
  class Symbol extends Container {
    // Initialize node
    constructor(node, attrs = node) {
      super(nodeOrNew('symbol', node), attrs);
    }

  }
```

and from SWC's view , the `Symbol` in inject helper , and the class ident `Symbol` should  have different  `Ident#sym` after some transform in Swc.

**Comment by stormslowly** [comment]
after changing the bug code
```js
let y = [1];
function a(y) {
  for (let x of y) {
    console.log(x);
  }
}
class Symbol {
  constructor() {}
}
```
to (remove func a declare just keep the for-of stmts)
```js
let y = [1];

  for (let x of y) {
    console.log(x);
  }

class Symbol {
  constructor() {}
}
```

the class Symbol ident changed to `_$Symbol`, the problem maybe relate to block_scoping

**Comment by kdy1** [comment]
Regardless, it exists in real-world code, SWC should not change the behavior of the code.

**Comment by stormslowly** [comment]
so i have to do a workaround : (
