### ISSUE TITLE
Recompilation randomly generates different output

### ISSUE THREAD

**Issue by sezanzeb** [swc-project/swc#9051]
### Describe the bug

When I run `swc src -d dist` repeatedly, different output is generated.

- Sometimes the output is broken (scroll down): https://github.com/sezanzeb/swc-test/blob/main/outputs/main_3.js
- Sometimes it's with require: https://github.com/sezanzeb/swc-test/blob/main/outputs/main_2.js
- And I'm tempted to think this is what it is supposed to be: https://github.com/sezanzeb/swc-test/blob/main/outputs/main_1.js, though at the same time app.module.js uses `require` so it still doesn't work.

### Input code

```typescript
See https://github.com/sezanzeb/swc-test
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "decoratorsBeforeExport": true,
    },
    "baseUrl": "./"
  },
  "module": {
    "type": "nodenext"
    "resolveFully": true
  },
  "minify": false
}
```

### Playground link (or link to the minimal reproduction)

https://github.com/sezanzeb/swc-test

### SWC Info output

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024
        CPU: (12 cores)
            Models: AMD Ryzen 5 5500U with Radeon Graphics

    Binaries:
        Node: 22.3.0
        npm: 10.8.1
        Yarn: 1.22.19
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.5.29
        @swc/helpers: N/A
        @swc/types: 0.1.8
        typescript: 5.3.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

To produce working output, that doesn't change randomly

### Actual behavior

See above

### Version

```
"@swc/cli": "^0.3.12",
"@swc/core": "^1.5.29"
```

**Comment by sezanzeb** [comment]
Furthermore, in the compiled app.module.js, there is outdated code. For example imports that have been removed already, that were present in older versions of the typescript code.

**Comment by sezanzeb** [comment]
ok, so webstorm gracefully hides that there are additional main.js and app.module.js files in src 👍👍👍👍👍👍

deleting those makes it work consistently

So it might be some sort of parallelization that writes to the same file, because the output-filename is the same?

**Comment by sezanzeb** [comment]
> So it might be some sort of parallelization that writes to the same file, because the output-filename is the same?

Should this throw an error instead?

**Comment by kdy1** [comment]
I think so, but I don't think `@swc/core` should throw an error for this, and it does not care about output file name, except for sourcemap support.

Also, `@swc/cli` does not look like a good place for exceptions in this case. It does not have the conflicting `output-filename`
