### ISSUE TITLE
ExportDecl.type_only

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#908]
This is required for deno linter

**Comment by bartlomieju** [comment]
I'll tackle that!

**Comment by kdy1** [comment]
@bartlomieju Thanks!

**Comment by bartlomieju** [comment]
@kdy1 I just took a look at it and does it make sense to add `type_only` to `ExportDecl`? 

I don't think it is valid to do:
```
export type const a = "a";
export type class B {};
etc.
```

It seems `type_only` is already handled on `NamedExport`.

**Comment by kdy1** [comment]
@bartlomieju You are correct. I added type_only to `NamedExport` because `export type` can be used only with named exports.
