### ISSUE TITLE
@swc/wasm + vite: Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by cha0s** [swc-project/swc#9098]
### Describe the bug

The library fails to load in the browser with:

```
Uncaught ReferenceError: process is not defined
    at node_modules/util/util.js (chunk-JVHG6XFR.js?v=645bda90:775:5)
    at __require (chunk-F2AEQYBP.js?v=645bda90:12:50)
    at node_modules/@swc/wasm/wasm.js (@swc_wasm.js?v=645bda90:41:40)
    at __require (chunk-F2AEQYBP.js?v=645bda90:12:50)
    at @swc_wasm.js?v=645bda90:705:16
```
If I work around this bug with e.g.:

```
  define: {
    'process.env.NODE_DEBUG': JSON.stringify(false),
  },
```

in my `vite.config.js`, another bug appears:

```
Uncaught TypeError: TextDecoder is not a constructor
    at node_modules/@swc/wasm/wasm.js (@swc_wasm.js?v=645bda90:59:29)
    at __require (chunk-F2AEQYBP.js?v=645bda90:12:50)
    at @swc_wasm.js?v=645bda90:705:16
```

`TextDecoder` does not require a library: https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.3&code=H4sIAAAAAAAAAwXBgQkAIAgEwFUet2mMIimRlNT2746C75MQW2iYjtqSOF05YY5kS8Z4BVf67mqBqCsAAAA%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxGd06BPHdth94hh7CoExHxJ0ykoih3LyFA2w2%2Fz%2FYzu5ASVlbwlHt5liJgZIqjLoSzS%2FguBEhZZBV1SHDr6cpnNKNhqui4EkgYF0p1iu%2BtHYz3TIWluFFDVjs951%2Bf8jZEYu5rh8qiWwz920QzgvWvrYbtHykHuuwP%2BDZ12VgMmqc%2BeV4ljg%2F3WmjeEwEAAA%3D%3D

### Expected behavior

There should be no assumption that `process` is defined.

### Version

1.6.5

**Comment by kwonoj** [comment]
`@swc/wasm` is specific to node.js.

https://www.npmjs.com/package/@swc/wasm-web
