### ISSUE TITLE
swc_ecma_codegen doesn't preserve quotes

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#910]
**Describe the feature**

Running type stripping and code generation on a super small example changes quotes.

```ts
// Input 
console.log("Hello World");

// Output
console.log('Hello World');
```

I'd expect that output would be identical to input, but it turns out SWC defaults to single quotes. I think this is caused by this method:

https://github.com/swc-project/swc/blob/de1f967d327dd20e47ad2efd78d28968800f1cb2/ecmascript/codegen/src/lib.rs#L385-L410

Ref https://github.com/denoland/deno/pull/6895#discussion_r461194267

**Comment by kdy1** [comment]
Published a new version
