### ISSUE TITLE
"This is the expression part of an expression statement" on "type alias"

### ISSUE THREAD

**Issue by v1d3rm3** [swc-project/swc#9103]
### Describe the bug

When i try to compile a file with "type alias", i get "This is the expression part of an expression statement" error.

### Input code

```typescript
type SpecialType = string;
const a: SpecialType = "asd";
```
```


### Config

```json
{
  "module": {
    "type": "common"
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.5&code=H4sIAAAAAAAAAyupLEhVCC5ITc5MzAkBsW0VikuKMvPSrXm5kvPziksUEq3Q5JUSi1OUrAHCJHMGOQAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

Compilation of file.

### Version

@swc/cli: 0.3.12 @swc/core: 1.6.3

**Comment by kdy1** [comment]
Try setting `jsc.parser.syntax` to `typescript`.

https://play.swc.rs/?version=1.6.5&code=H4sIAAAAAAAAAyupLEhVCC5ITc5MzAkBsW0VikuKMvPSrXm5kvPziksUEq3Q5JUSi1OUrAHCJHMGOQAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D
