### ISSUE TITLE
`export default function` parsed as FunctionExpression

### ISSUE THREAD

**Issue by todor-a** [swc-project/swc#9120]
### Describe the bug

This:
```ts
export default function three() {}
```

Is parsed as (some parts omitted for brevity):
```json
{
  "type": "Module",
  "body": [
    {
      "type": "ExportDefaultDeclaration",
      "decl": {
        "type": "FunctionExpression",
          "value": "three",
          "optional": false
        }
    }
  ],
  "interpreter": null
}
```

If you remove the `default` it becomes;

```json
{
  "type": "Module",
  "body": [
    {
      "type": "ExportDeclaration",
      "declaration": {
        "type": "FunctionDeclaration",
          "value": "three",
          "optional": false
        }
      }
  ],
  "interpreter": null
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.6&code=H4sIAAAAAAAAA0utKMgvKlFQSCvNSy7JzM9TKMkoSk3V0FSorgUA3N7FvhsAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

Should be reported as a `FunctionDeclaration`.

### Version

1.6.6

**Comment by dsherret** [comment]
It's parsed correctly. It's `export default <expression>`

**Comment by todor-a** [comment]
> It's parsed correctly. It's `export default <expression>`

All of [these](https://astexplorer.net/#/gist/9822eafce633aee90f6191c87c35eb8a/1008fa0d3505d768a4d799ceece2a0a6fa5c3417) parse it as a function declaration 🤔 (except swc)

**Comment by dsherret** [comment]
Yes, you're correct: https://262.ecma-international.org/14.0/#prod-ExportDeclaration

**Comment by kdy1** [comment]
See `ExportDefaultDeclaration`. `DefaultDecl` uses `FnExpr` to ease processing, but you can hook on `visit_default_decl`
