### ISSUE TITLE
Provide Wasm plugins TypeScript types and decorators (under a flag)

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9132]
### Describe the feature

It was intentional decision to make implementing Wasm plugins easier, but some users want it.

**Comment by slotDumpling** [comment]
When is this feature expected to be available? thx.

**Comment by amanteaux** [comment]
I am really looking for this feature, thank you so much!

**Comment by slotDumpling** [comment]
Real nice feature for implementing plugins that work the same as Typescript transformers. thx.
