### ISSUE TITLE
Coverage is not updated at CodeCov

### ISSUE THREAD

**Issue by trivikr** [swc-project/swc#917]
**Describe the bug**
Coverage is not updated at CodeCov https://codecov.io/gh/swc-project/swc
The latest commit for which coverage is updated is 291251e2dfa6480c86a32ae1d7fe0b3ec3fcffae from Jun 2, 2020.

<details>
<summary>Screenshot</summary>

![Screenshot from 2020-07-30 23-01-51](https://user-images.githubusercontent.com/16024985/89005251-d3f3b100-d2b8-11ea-9d67-569a3a0d6781.png)

</details>

**Expected behavior**
Coverage gets updated on codecov on every git push

**Version**
master

**Additional context**
Because of this issue, the CodeCov badge shows coverage at 15% which is old
<details>
<summary>Screenshot</summary>

![Screenshot from 2020-07-30 23-04-43](https://user-images.githubusercontent.com/16024985/89005426-449acd80-d2b9-11ea-817a-a901fbccc43f.png)

</details>

**Comment by kdy1** [comment]
It's killed due to OOM / timeout.
To run coverage, you need a device with 20+ GB ram.

Splitting `swc_ecma_transforms` can be a solution, but it will make tests much more complex.
