### ISSUE TITLE
Dynamic Imports flag not respected

### ISSUE THREAD

**Issue by Larsundso** [swc-project/swc#9174]
### Describe the bug

Dynamically importing files and modules in the code will lead swc to believe the module or file is unused and omit it during compilation. Even if `dynamicImport` is set to true in parser options.

### Input code

```typescript

// index.ts
(async () => {
 const r = await import("./lang.json");
 console.log(r);
})();

// lang.json
{
 "hi": "hi"
}

```

### Config

```json
{
 "$schema": "https://swc.rs/schema.json",
 "jsc": {
  "parser": {
   "syntax": "typescript",
   "tsx": false,
   "decorators": true,
   "dynamicImport": true,
   "preserveAllComments": false,
   "topLevelAwait": true,
   "resolveFully": true
  },
  "target": "esnext"
 },
 "module": {
  "type": "nodenext"
 },
 "minify": true,
 "sourceMaps": true,
 "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://github.com/Larsundso/swc-dynamic-import

### SWC Info output
-- OS 1

    Operating System:
        Platform: win32
        Arch: x64
        Machine Type: x86_64
        Version: Windows 11 Enterprise
        CPU: (24 cores)
            Models: AMD Ryzen 9 5900X 12-Core Processor

    Binaries:
        Node: 22.4.0
        npm: N/A
        Yarn: N/A
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.6.12-nightly-20240706.1
        @swc/helpers: N/A
        @swc/types: N/A

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

-- OS 2

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024
        CPU: (8 cores)
            Models: AMD EPYC 7282 16-Core Processor

    Binaries:
        Node: 22.3.0
        npm: 10.8.1
        Yarn: N/A
        pnpm: 9.4.0

    Relevant Packages:
        @swc/core: 1.6.12-nightly-20240706.1
        @swc/helpers: N/A
        @swc/types: N/A

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

lang.json should be compiled into /dist
the program should log its contents into the console

### Actual behavior

lang.json is missing from /dist
the program fails with the following error

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/swc-dynamic-import/dist/lang.json' imported from /swc-dynamic-import/dist/index.js

### Version

1.6.12-nightly-20240706.1

**Comment by kdy1** [comment]
`lang.json` should be copied by other means. e.g. --copy-files
swc does not have a project mode of `tsc`

**Comment by ab-geoff-plitt** [comment]
@kdy1 That works for JSON files, but is there any way to do dynamic import of code? Was hoping to use `await import()` with an ESM module

**Comment by kdy1** [comment]
You can compile directory instead of specifying only entry file
