### ISSUE TITLE
Changed type of the derived class property makes it undefined

### ISSUE THREAD

**Issue by vyshkov** [swc-project/swc#9179]
### Describe the bug

If I redefine property type to be more specific in the derived class, it makes it undefined.

```
    class A {
      prop: string;

      constructor(test: string) {
        this.prop = test;
      }
    }

    class B extends A {
      prop: 'str1' | 'str2';

      constructor(test: 'str1' | 'str2') {
        super(test);
      }
    }

    const test = new B('str2');

    console.log(test.prop);
```

I know, I didn't explicitly set it in the constructor of class B, however, when I compile the file with TSC it works differently: I can access the `prop` and it's not `undefined`.

### Config

```json
{
  jsc: {
    parser: {
      syntax: 'typescript',
      dynamicImport: true,
      decorators: true
    },
    target: 'es2021',
    transform: {
      decoratorMetadata: true,
      legacyDecorator: true
    },
    baseUrl: path.resolve(__dirname, '.')
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.7&code=H4sIAAAAAAAAA32PywrCMBBF94X%2Bw92l2RR0aXBh%2F0TiUAshCUmKQu2%2Fm4fBB%2BqshsmdMycAINXRexywtA1yWWfsDj64SY%2BibepYGh1nswzGdYF8qBH%2B3ATCefJ9AmCPFBL1aS3NWnnl6gC6BtKnL%2FdZpG8YbrnZsr8iH9k3Iz9bKjn%2BWyYRs2%2FU1nTB0D1I4jViFPXKjBmWP8nFHeglkztBAQAA&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KHN0KF36CEQdSIqfsKOVBTl7oUE0maz38fveRFSwps0PORSxrJElQjTsReEsmf1KQhwjkg6mchw6SxTpUZlCTdo3RlglSbk6kIarsOtOcCGQNgdDXPGmzH%2FZ%2BrgYkKis7BKlZ8snhNFSwUXXvNGtl9q373BHX6iHnYcBkPP7uQ0o1i%2FsnkCbBcBAAA%3D

### Expected behavior

this.prop should be defined

### Version

1.6.6

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/7435

**Comment by magic-akari** [comment]
You should set `useDefineForClassFields`.
