### ISSUE TITLE
TypeScript emitDecoratorMetadata support

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#919]
Relate issue: https://github.com/swc-project/swc/issues/666

I will try to implement this feature.

**Comment by kdy1** [comment]
Oh.. I missed your comment and I implemented it. Sorry.

**Comment by Brooooooklyn** [comment]
@kdy1 oh doesn't matter, I have not started this yet 🌚

**Comment by elliotaplant** [comment]
How does one use this feature? Do you need to do anything other than have `emitDecoratorMetadata: true` in your `tsconfig.json`?
