### ISSUE TITLE
Helper methods do not need to be export functions

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9203]
### Describe the feature

`_` export is enough, and we can rename them while exporting.

**Comment by kdy1** [comment]
cc @magic-akari Is there a reason we use `export function` while we can use `_`?

**Comment by magic-akari** [comment]
It is used only within helpers. We can retain only the `_` name.

**Comment by kdy1** [comment]
# Guide for GFI

You need to patch https://github.com/swc-project/swc/blob/260f806d3e2a8350864c6e751949566f6a9654ff/packages/helpers/scripts/build.js#L43-L78 to use `_` as the original name for re-export.

After then, you can patch files like https://github.com/swc-project/swc/blob/260f806d3e2a8350864c6e751949566f6a9654ff/packages/helpers/esm/_apply_decorated_descriptor.js to export only `_`
