### ISSUE TITLE
[key: string]: any is not stripped properly

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#921]
**Input code**

```ts
export abstract class Kernel {
  /**
   * Multiple variables that will be defined during runtime,
   * holding the values of the commands passed from the user
   */
  [key: string]: any
  ... snip ...
}
```

** Output code**
```ts
export class Kernel {
    /**
   * Multiple variables that will be defined during runtime,
   * holding the values of the commands passed from the user
   */
    [key]: ;
    ... snip ...
}
```

I guess it should be removed altogether.

<s>Also it seems that `abstract` is not emitted.</s> Nvm, obviously `abstract` is TS-only construct

**Comment by kdy1** [comment]
Published a new version. However it seems like a critical issue for deno.

I will add a test which uses typescript files from parser test to check that typescript::strip does not generate invalid es code.
