### ISSUE TITLE
Large numeric literals are emitted as `Infinity` / `-Infinity` instead of remaining as they are.

### ISSUE THREAD

**Issue by lucacasonato** [swc-project/swc#9223]
### Describe the bug

Roundtripping an AST containing the code below, the output contains `-Infinity` instead of `-1e999`. I think the output should remain as `-1e999`.

### Input code

```typescript
const x = -1e999;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "react": {
        "importSource": "npm:react",
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.7&code=H4sIAAAAAAAAA0vOzysuUahQsFXQNUy1tLS0BgAenTgBEQAAAA%3D%3D&config=H4sIAAAAAAAAA21QOw7CMAzde4rKMwPqwMAdmDiBFVwU1HxkOxJV1buTtA0tEksUv4%2Bf7alpW3iJgWs75W8uIrIQf%2BuMyOgV3xkBHSOJYRsVTpVVKVSPg9ACzSsDivwkLS6S7tx1mwOGEISqY8Oc9bYfj5kmuMgk8issUvTPgf4nMnrpA7tjIyY0egAyZF0MrPeQ2JRG4KO7rrLTLuLk1bqFx6TBoVoDGz039V2iwYVHWmbaTljOtC5%2BgV1Ud%2FzuA1Zu1amcqJk%2FtsEHsI4BAAA%3D

### Expected behavior

```js
const x = -1e999;
```

### Actual behavior

```js
const x = -Infinity;
```

### Version

1.6.7

**Comment by magic-akari** [comment]
Are you currently writing custom DTS codegen?
I believe you can extract data from the raw data of the Number.

[SWC AST Viewer](https://swc-ast.vercel.app/#code/MYewdgzgLgBAHjAvDAtARgKYE4cG4g)

<img width="351" alt="image" src="https://github.com/user-attachments/assets/f5375c5a-8e1f-4e86-b9ca-77b9e3e2d93a">

**Comment by kdy1** [comment]
# Guide for GFI

The problematic logic is https://github.com/swc-project/swc/blob/260f806d3e2a8350864c6e751949566f6a9654ff/crates/swc_ecma_codegen/src/lib.rs#L705-L713

We can move code for using `raw` before the code checking infinity

**Comment by imranbarbhuiya** [comment]
> # Guide for GFI
> The problematic logic is
> 
> https://github.com/swc-project/swc/blob/260f806d3e2a8350864c6e751949566f6a9654ff/crates/swc_ecma_codegen/src/lib.rs#L705-L713
> 
> We can move code for using `raw` before the code checking infinity

Hi, I was working on this, how can I test the changes?
