### ISSUE TITLE
minifier produces incorrect constant value on large floating-point value

### ISSUE THREAD

**Issue by levi-nz** [swc-project/swc#9256]
### Describe the bug

Running `1.7976931348623157e+308 << 1` in NodeJS v20.12.2 and in browser (Firefox) returns `0` but SWC minifier transforms this into `-2`.

For reference, `1.7976931348623157e+308` is `Number.MAX_VALUE` in JavaScript and `f64::MAX` in Rust.

### Input code

```typescript
1.7976931348623157e+308 << 1
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.7&code=H4sIAAAAAAAAA0vTMNQztzQ3szQ2NDaxMDMyNjQ1T9U2NrBQsLFRMNTkAgCxoDjzIAAAAA%3D%3D&config=H4sIAAAAAAAAA32UO3LjMAyG%2B5zCozrFjostcoDtcgYOTYIyvXxoCNCxJuO7L0TJj40hdRI%2B%2FAAJgPh%2B2%2B26E5ruY%2FfNn%2Fwz6IJQ7v9swTGRvrClAxM1muIH6t5v9IQTcjogNNN1Jh3p0gM1Fe5%2F7feLogs5I9wUiy365N34nNPkOBRAfLKxlUPWCInwf%2F3CSv6aAJX6bD%2FkHECnDaI0Kp8IeihSYJND0AOCOusiRJlOqovHLKWYYCWwaih5EHmynnxOnPOVWtBWmWxBQL6AIX8GSca5WJaQryfcp2ELh9r3rc8%2F1HDWoWoScsKltYRPK0Q9Zo%2BkXE1SCWe4UoMZLsX9qfROFaBa0qvulH1a6clfAK5A0IhJR5DiNg%2FH87SmdptKnxyPLI0C5%2FmWbpmg56Iq751Q2akyUMhL3Sxgq4GpskY6zoJXyofeggLneFaE0PjlyRylpDQOkJ0AuL%2FaSVM1A3V%2FhSt8ehAb%2BA%2FfkuQBWzyipuM6xTEecthIEIGO2W44cCsor%2BPCW%2BIyrPOaLPBogBVdKjbwugT4AVBWoe3Ll9ng58ERVR%2Fy4bEmFofrfQ9HnfrHe59X8dvi0MVsa4PLkp%2F6O6%2Fm393D6baF7wfvPH7elC3p9R%2BoYzQdMAYAAA%3D%3D

### Expected behavior

Should be transformed to `f(0)`

### Actual behavior

Transforms to `f(-2)`

### Version

1.6.7

**Comment by levi-nz** [comment]
I believe the problem is [js_convert_double_to_bits](https://github.com/swc-project/swc/blob/5cc64497341316b2bef4c48ee55732dd92207efb/crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs#L639) not returning 0 if the value exceeds 32-bit integer limit as defined in [ToInt32](https://262.ecma-international.org/5.1/#sec-9.5)

**Comment by levi-nz** [comment]
Not sure if we need to use `overflowing_*` here for shifting

**Comment by kdy1** [comment]
Related:

 - https://tc39.es/ecma262/#sec-numeric-types-number-leftShift
 - https://tc39.es/ecma262/#sec-numeric-types-number-signedRightShift
 - https://tc39.es/ecma262/#sec-numeric-types-number-unsignedRightShift
