### ISSUE TITLE
`@swc/wasm-typescript` is failing on some architectures

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9259]
@kdy1 it seems tests are failing on some architecture such as:
- s390x
- ppc64

```
19:22:06       code: 'ERR_ASSERTION'
19:22:06       name: 'AssertionError'
19:22:06       expected: ''
19:22:06       actual: |-
19:22:06         wasm://wasm/0072633a:1
19:22:06         
19:22:06         
19:22:06         RuntimeError: memory access out of bounds
19:22:06             at wasm://wasm/0072633a:wasm-function[1521]:0x1a6744
19:22:06             at wasm://wasm/0072633a:wasm-function[51]:0x60118
19:22:06             at wasm://wasm/0072633a:wasm-function[1264]:0x1a32e8
19:22:06             at module.exports.transformSync (node:internal/deps/swc/wasm:248:14)
19:22:06             at tsParse (node:internal/modules/helpers:310:18)
19:22:06             at node:internal/main/eval_string:27:3
```

_Originally posted by @marco-ippolito in https://github.com/nodejs/node/issues/53725#issuecomment-2229226306_

**Comment by magic-akari** [comment]
I suspect there might be an issue with wasm-bindgen.

> [!NOTE]  
> Note: WebAssembly memory is always in little-endian format, regardless of the platform it's run on. Therefore, for portability, you should read and write multi-byte values in JavaScript using [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView).

https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory

**Comment by miladfarca** [comment]
Regarding the failures on powerpc, is it only on AIX or it includes Linux on little endian as well?

If it's only a problem on big endian then could you tell me if emscripten was used to generated the wasm code and it's JavaScript glue code?

We have previously patched emscripten to handle big endian platforms here https://github.com/emscripten-core/emscripten/pull/13413 , you will need to add SUPPORT_BIG_ENDIAN=1 during compilation to apply BE patches.
We also maintain V8 as it's runtime to make sure BE platforms are supported.

**Comment by marco-ippolito** [comment]
This is the list of failures, windows and osx seems unrelated
![image](https://github.com/user-attachments/assets/a3efdaf0-3fd5-4c0d-9903-b4a7accc400a)

**Comment by miladfarca** [comment]
Thanks, so plinux (being little endian) seems green. How is the wasm file with is `js` glue code generated?

**Comment by magic-akari** [comment]
[swc-binding_typescript_wasm-1.6.13.tgz](https://github.com/user-attachments/files/16255794/swc-binding_typescript_wasm-1.6.13.tgz)

Could you try this package? @marco-ippolito 
I made some manual adjustments. If it works, we need to correct the output of wasm-bindgen.

**Comment by marco-ippolito** [comment]
> [swc-binding_typescript_wasm-1.6.13.tgz](https://github.com/user-attachments/files/16255794/swc-binding_typescript_wasm-1.6.13.tgz)
> 
> Could you try this package? @marco-ippolito I made some manual adjustments. If it works, we need to correct the output of wasm-bindgen.

can you please publish it as a nightly release?

**Comment by kdy1** [comment]
@marco-ippolito I published it as @swc/binding_typescript_wasm@1.7.0-rc.0

**Comment by miladfarca** [comment]
how is rust compiled to wasm? is emscripten used or rust has its own internal compiler and needs to use `wasm-bindgen` afterwards?

**Comment by kdy1** [comment]
We use `wasm-bindgen` and `wasm-pack`.

https://github.com/swc-project/swc/blob/02f77f6409b831b67859f0290e4484a4353e3351/bindings/binding_typescript_wasm/scripts/build.sh#L4-L7

**Comment by marco-ippolito** [comment]
It seems to be working on such architectures, but there is this failure when node is built without ICU
```
15:16:04       failureType: 'testCodeFailure'
15:16:04       error: |-
15:16:04         Expected values to be strictly equal:
15:16:04         + actual - expected
15:16:04         
15:16:04         + 'node:internal/encoding:487\n' +
15:16:04         +   `          throw new ERR_NO_ICU('"fatal" option');\n` +
15:16:04         +   '          ^\n' +
15:16:04         +   '\n' +
15:16:04         +   'TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU\n' +
15:16:04         +   '    at new TextDecoder (node:internal/encoding:487:17)\n' +
15:16:04         +   '    at node:internal/deps/swc/wasm:90:25\n' +
15:16:04         +   '    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)\n' +
15:16:04         +   '    at requireBuiltin (node:internal/bootstrap/realm:430:14)\n' +
15:16:04         +   '    at lazyLoadTSParser (node:internal/modules/helpers:304:15)\n' +
15:16:04         +   '    at tsParse (node:internal/modules/helpers:309:17)\n' +
15:16:04         +   '    at node:internal/main/eval_string:27:3 {\n' +
15:16:04         +   "  code: 'ERR_NO_ICU'\n" +
15:16:04         +   '}\n' +
15:16:04         +   '\n' +
15:16:04         +   'Node.js v23.0.0-pre\n'
```

**Comment by magic-akari** [comment]
> It seems the fix release in the nightly is working on such architectures, but there is this failure when node is built without ICU
> 
> ```
> 15:16:04       failureType: 'testCodeFailure'
> 15:16:04       error: |-
> 15:16:04         Expected values to be strictly equal:
> 15:16:04         + actual - expected
> 15:16:04         
> 15:16:04         + 'node:internal/encoding:487\n' +
> 15:16:04         +   `          throw new ERR_NO_ICU('"fatal" option');\n` +
> 15:16:04         +   '          ^\n' +
> 15:16:04         +   '\n' +
> 15:16:04         +   'TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU\n' +
> 15:16:04         +   '    at new TextDecoder (node:internal/encoding:487:17)\n' +
> 15:16:04         +   '    at node:internal/deps/swc/wasm:90:25\n' +
> 15:16:04         +   '    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)\n' +
> 15:16:04         +   '    at requireBuiltin (node:internal/bootstrap/realm:430:14)\n' +
> 15:16:04         +   '    at lazyLoadTSParser (node:internal/modules/helpers:304:15)\n' +
> 15:16:04         +   '    at tsParse (node:internal/modules/helpers:309:17)\n' +
> 15:16:04         +   '    at node:internal/main/eval_string:27:3 {\n' +
> 15:16:04         +   "  code: 'ERR_NO_ICU'\n" +
> 15:16:04         +   '}\n' +
> 15:16:04         +   '\n' +
> 15:16:04         +   'Node.js v23.0.0-pre\n'
> ```

```
// `ignoreBOM` is needed so that the BOM will be preserved when sending a string from Rust to JS
// `fatal` is needed to catch any weird encoding bugs when sending a string from Rust to JS
```

- rustwasm/wasm-bindgen#1730

**Comment by magic-akari** [comment]
TextDecoder is used for decoding strings from Rust.
Perhaps we could simply eliminate the fatal option. 
What do you think? @kdy1

**Comment by kdy1** [comment]
I agree and I left a question at https://github.com/rustwasm/wasm-bindgen/pull/1730#issuecomment-2233431213

For now, I think we can do some string replace in `patch.mjs`. We already do it.
https://github.com/swc-project/swc/blob/02f77f6409b831b67859f0290e4484a4353e3351/bindings/binding_typescript_wasm/scripts/patch.mjs#L9-L13

**Comment by kdy1** [comment]
I published `1.7.0-rc.1`, which includes manual fix of `fatal` option by @magic-akari.
@marco-ippolito Can you try this version?

**Comment by marco-ippolito** [comment]
It seems to be working! CI is green, (only windows on arm seems to be flaky but its probably unrelated) @kdy1 thank you sooo much 🙏🏼

**Comment by kdy1** [comment]
@marco-ippolito Can you try `@swc/wasm-typescript@1.7.0`? We applied necessary patches to the package.

**Comment by marco-ippolito** [comment]
Updating breaks it
```
    
    '\n' +
      '  #  /Users/marcoippolito/Documents/projects/forks/node/out/Release/node[63807]: void node::contextify::CompileFunctionForCJSLoader(const FunctionCallbackInfo<Value> &) at ../../src/node_contextify.cc:1648\n' +
      '  #  Assertion failed: args[0]->IsString()\n' +
      '\n' +
      '----- Native stack trace -----\n' +
      '\n' +
      ' 1: 0x1027ca020 node::Assert(node::AssertionInfo const&) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 2: 0x104561a7c node::contextify::CompileFunctionForCJSLoader(v8::FunctionCallbackInfo<v8::Value> const&) (.cold.6) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 3: 0x1027bab40 node::contextify::CompileFunctionForCJSLoader(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 4: 0x10354f118 Builtins_CallApiCallbackGeneric [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 5: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 6: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 7: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 8: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      ' 9: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '10: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '11: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '12: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '13: 0x10354cef0 Builtins_InterpreterEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '14: 0x10354ac0c Builtins_JSEntryTrampoline [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '15: 0x10354a8f4 Builtins_JSEntry [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '16: 0x102b4667c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '17: 0x102b45fd4 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '18: 0x1029f5370 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '19: 0x1027a69f4 node::builtins::BuiltinLoader::CompileAndCall(v8::Local<v8::Context>, char const*, node::Realm*) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '20: 0x102854d4c node::Realm::ExecuteBootstrapper(char const*) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '21: 0x102785c90 node::StartExecution(node::Environment*, char const*) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '22: 0x102785be4 node::StartExecution(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '23: 0x1026dd6f4 node::LoadEnvironment(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>, std::__1::function<void (node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Value>)>) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '24: 0x102810d00 node::NodeMainInstance::Run() [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '25: 0x102789070 node::Start(int, char**) [/Users/marcoippolito/Documents/projects/forks/node/out/Release/node]\n' +
      '26: 0x18819e0e0 start [/usr/lib/dyld]\n' +
      '\n' +
      '----- JavaScript stack trace -----\n' +
      '\n' +
      '1: wrapSafe (node:internal/modules/cjs/loader:1458:18)\n' +
      '2: Module._compile (node:internal/modules/cjs/loader:1480:20)\n' +
      '3: loadTS (node:internal/modules/cjs/loader:1667:10)\n' +
      '4: Module.load (node:internal/modules/cjs/loader:1313:32)\n' +
      '5: Module._load (node:internal/modules/cjs/loader:1123:12)\n' +
      '6: traceSync (node:diagnostics_channel:315:14)\n' +
      '7: wrapModuleLoad (node:internal/modules/cjs/loader:217:24)\n' +
      '8: executeUserEntryPoint (node:internal/modules/run_main:166:5)\n' +
      '9: node:internal/main/run_main_module:30:49\n' +
      '\n' +
      '\n'
```

it breaks this check https://github.com/nodejs/node/blob/014dad5953a632f44e668f9527f546c6e1bb8b86/src/node_contextify.cc#L1648 
The source is expected to be a string, while now the transformSync function returns something else

**Comment by kdy1** [comment]
Yeah, it was inevitable, as we now may have to emit a source map. Sorry, I forgot to tell you.

**Comment by kdy1** [comment]
Closing as `@swc/wasm-typescript@1.7.1` is published
