### ISSUE TITLE
1.7.0 nightly tagged on npm as "latest"?

### ISSUE THREAD

**Issue by dburles** [swc-project/swc#9269]
### Describe the feature

Is the 1.7.0 nightly build supposed to be tagged as the latest version? See: https://www.npmjs.com/package/@swc/core?activeTab=versions

### Additional context

Your issue templates are quite restrictive, but discussions doesn't seem like the right place for this.

**Comment by kdy1** [comment]
I did `npm dist-tag add @swc/core@1.6.13 latest`
I'll close this issue with a PR to prevent same problem
