### ISSUE TITLE
parse function does not add comments to ast

### ISSUE THREAD

**Issue by 3axap4eHko** [swc-project/swc#9273]
### Describe the bug

```typescript
const ast = await swc.parse(sourceCode, {
  comments: true,
  syntax: 'typescript',
});
```

### Input code

```typescript
/**
 * @internal
 */
class A {}
```

### Config

```json
N/A
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.7&code=H4sIAAAAAAAAA9PXVyhJLS4x5OVKzkksLlZwVKiu5eXS19Li5VLQAkspGIGY%2BjAFTkAFAJ7%2BSWA1AAAA&config=H4sIAAAAAAAAA02PPQ7DIAxG954Cec5QMXToHXIIRJ2IKBBkE6koyt2LofkZv2d%2FT%2Fb2UAr88llnhLfaSio55SgJkF9QyN7J0sT22oiGGOnMhXAOyXylJW225GKCOqx1sRoaMTWvfmoNf%2B5dcEO%2Bu%2BziIyFzYYOZGbtj4E0Y66EVN%2Ft5oOP%2B%2BCPRWkuXuxX2H6DweD7vAAAA

### SWC Info output

Node.js v22.4.1

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64
        Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
        CPU: (32 cores)
            Models: 13th Gen Intel(R) Core(TM) i9-13900K

    Binaries:
        Node: 22.4.1
        npm: 10.8.1
        Yarn: N/A
        pnpm: 9.4.0

    Relevant Packages:
        @swc/core: 1.6.13
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.4.5

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

I expect to see comments in AST

### Version

1.6.13

**Comment by kdy1** [comment]
It's not exposed to JS, and it's a duplicate
