### ISSUE TITLE
unknown variant `ESNext`

### ISSUE THREAD

**Issue by Enteleform** [swc-project/swc#9287]
### Describe the bug

I am experiencing the same bug described in https://github.com/swc-project/swc/issues/8516, which was supposed to be resolved by https://github.com/swc-project/swc/pull/8653.

> When set `compilerOptions.target: "ESNext"` (title case), I got error:
> ```log
> [vite] Internal server error: unknown variant `ESNext`, expected one of `es3`, `es5`, `es2015`, `es2016`, `es2017`, `es2018`, `es2019`, `es2020`, `es2021`, `es2022`, `esnext` at line 1 column 241 Plugin: swc
> ```

Relevant Dependencies, up to date as of today:
```yaml
"unplugin-swc": 1.5.1
"@swc/core":    1.7.0
```

### Playground link (or link to the minimal reproduction)

https://stackblitz.com/edit/vitejs-vite-pezqps?file=package.json

### Expected behavior

`swc` should accept `ESNext` and other PascalCase variants, as defined in https://json.schemastore.org/tsconfig.json

### Version

1.7.0

**Comment by Enteleform** [comment]
@kdy1

**Comment by kdy1** [comment]
Use `EsNext` instead

**Comment by Enteleform** [comment]
@kdy1

That does not match the [JSON schema specification](https://json.schemastore.org/tsconfig.json) for `package.json`, which is implemented in IntelliSense as well:
![image](https://github.com/user-attachments/assets/57d0bc07-13ed-4b6e-9a62-8f9925981cb6)
