### ISSUE TITLE
`swc_core::ecma::visit::visit_expr` is gone?

### ISSUE THREAD

**Issue by smoelius** [swc-project/swc#9288]
In version 0.96, the path existed. Same for `...::visit_stmt`.

But in the most recent version (0.99), the path is gone.

Does the function still exist, but at another path?

**Comment by kdy1** [comment]
It's removed, and you can use `expr.visit_children_with(self)` instead

**Comment by smoelius** [comment]
Thanks for your prompt reply. 🙏
