### ISSUE TITLE
Running smoke tests against npm packages

### ISSUE THREAD

**Issue by tom-sherman** [swc-project/swc#929]
In order to test correctness of changes and prevent regressions it can be good to run smoke tests on real life projects in the wild. 

## Prior art

- Node.js [citgm](https://github.com/nodejs/citgm)
- Typescript user tests. [Example](https://github.com/microsoft/TypeScript/pull/39336#issuecomment-652065275)
- Rust's [crater](https://github.com/rust-lang/crater)

**Comment by kwonoj** [comment]
This would be cool and open to accept contributions, but I don't think core team have a bandwitdh to look into this right now.
