### ISSUE TITLE
`@swc/wasm-typescript` handling `() => <T>{}`

### ISSUE THREAD

**Issue by acutmore** [swc-project/swc#9295]
### Describe the bug

TypeScript's (legacy) prefix style type assertions (`<Type>val` instead of `(val as Type)`) cannot always be safely removed in `"strip-only"` mode when they are at the start of the body of an arrow function.

### Input code

```typescript
import * as swc from "@swc/wasm-typescript";

const input = `(() => <any>{})`;
const output = swc.transformSync(input, { mode: "strip-only" });

console.log(output.code);
```

### Config

```json
{ "mode": "strip-only" }
```

### Playground link (or link to the minimal reproduction)

no playground support for wasm-typescript yet: https://github.com/swc-project/swc-playground/issues/42

### Expected behavior

Either error or (if possible) produce JS with matching semantics as the input i.e. the equivalent of: `() => ({})`;

### Actual behavior

Resulting code is: `(() =>      {})` which has different semantics to the input.

### Version

@swc/wasm-typescript@1.7.0

### Additional context

I _think_ it's not possible to solve this in all cases. So it might be best to error for arrow functions that start with `<Type>{`.

There are some cases that can work with `"strip-only"`:

```typescript
let f = () => <T>{};
```

can strip and keep the JS in place with:

```javascript
let f = () => 0||{};
```

But that approach does not work for:

```typescript
let f = () => <T>{p:null}.p ?? g();
```

which could not be changed to:

```javascript
let f = () => 0||{p:null}.p ?? g();
```

As it is invalid to have `||` and `??` at the same level.

I would be very interesting if there was a way to solve this, otherwise I think the solution is to error.

**Comment by kdy1** [comment]
> TypeScript's (legacy) prefix style type assertions (<Type>val instead of (val as Type)) cannot always be safely removed in "strip-only" mode when they are at the start of the body of an arrow function.


That's why we don't touch it.

**Comment by acutmore** [comment]
> That's why we don't touch it.

Hi @kdy1, thanks for taking a look. In my testing it looks like `"strip-types"` does remove it.

`(() => <any>{})()` becomes `(() =>      {})`. The first returns `{}` at runtime, the second returns `undefined`.

For the case where the arrow function body only contains the type-assertion and object literal I think there is a safe transform to:  `(() =>   0||{})`, which keeps the original JS in the same position with the same semantics. However there are niche inputs which I _think_ don't have safe position-preserving transforms such as: `(() => <T>{p:null}.p??g)`, though I admit the chances of someone writing that is low.
