### ISSUE TITLE
strip: Class fields should be assigned after parameter properties

### ISSUE THREAD

**Issue by nayeemrmn** [swc-project/swc#930]
**Input code**

TypeScript allows regular class fields to depend on parameter properties:
```ts
class A {
  b = this.a;
  constructor(public a: any) {}
}
```

**Output code (actual)**
The regular class field `b` is incorrectly initialised before the parameter property `a`:
```ts
class A {
    b = this.a;
    constructor(a){
        this.a = a;
    }
}
```

**Output code (expected)**
The correct ordering is, parameter property assignment -> class field initialisation -> rest of the constructor. So if there are parameter properties present (or always), the class field initialisation must be moved below their assignments in the constructor:
```ts
class A {
    constructor(a) {
        this.a = a;
        this.b = this.a;
    }
}
```
This is the official compiler's output.

---

Seen in https://github.com/denoland/deno/blob/v1.2.2/std/mime/multipart.ts#L263-L271

cc @bartlomieju

**Comment by kdy1** [comment]
This is handled by class properties pass.

**Comment by Brooooooklyn** [comment]
Seems like `TypeScript` default behavior is different between the ECMA class field proposal: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier.

So  I think:
>  I can modify typescript pass to do it

is a better way to handler this situation. And because `class properties` need to be handled with `parameter properties`

**Comment by kdy1** [comment]
I think modifying class_properties pass to accept mode is better than modifying typescript_strip pass because typescript also supports `useDefineForClassFields `. If I modify typescript_strip pass, I have to do same work twice

**Comment by kdy1** [comment]
Now there exists a `typescript_class_properties` pass for it.
