### ISSUE TITLE
No `collections.rs` file in the published swc_allocator v0.1.7 crate

### ISSUE THREAD

**Issue by anqurvanillapy** [swc-project/swc#9305]
### Describe the bug

```bash
$ curl -L 'https://crates.io/api/v1/crates/swc_allocator/0.1.7/download' | tar -zxf -
$ ll swc_allocator-0.1.7/src/
```

There's not `collections.rs` file there, anything wrong with the publishing?

### Playground link (or link to the minimal reproduction)

See the above Bash command.

### Expected behavior

There should be a `collections.rs` file and related `pub mod collections;` statement in the entry file `lib.rs`.

### Version

swc_allocator v0.1.7

**Comment by kdy1** [comment]
See https://github.com/swc-project/swc/issues/9304
