### ISSUE TITLE
missig main files for @swc/types 0.1.10

### ISSUE THREAD

**Issue by ClarkXia** [swc-project/swc#9306]
### Describe the bug

![image](https://github.com/user-attachments/assets/05a8e024-04fc-492b-a76b-7be627c5c13a)

index.js is missing in version 0.1.10

### Playground link (or link to the minimal reproduction)

none

### Expected behavior

compile @swc/types before publish

### Version

@swc/types@0.1.10

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/blob/47cb71057c984d1c04084ed8d25fa0a79650d5d3/packages/types/package.json#L7-L11 

I think it's a bug of npm

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/commit/7514d9b705e0aeb897afeff3a6baa81860cb3d2e
