### ISSUE TITLE
https://swc-project.github.io/ has a broken link in the footer

### ISSUE THREAD

**Issue by jasikpark** [swc-project/swc#932]
<img width="869" alt="Screen Shot 2020-08-03 at 4 03 43 PM" src="https://user-images.githubusercontent.com/10626596/89227255-f4668880-d5a2-11ea-9beb-f7ec293bf3b7.png">

the link "Usage" links to https://swc-project.github.io/docs/usage-cli.html

instead of https://swc-project.github.io/docs/usage-swc-cli

**Comment by kdy1** [comment]
Thanks!
