### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by Dagur** [swc-project/swc#9326]
### Describe the feature

I saw the old issue here https://github.com/swc-project/swc/issues/174 but I was wondering, since it's been five years, if you have considered adding Flow support. 
It's being actively developed and still used in big projects. Your claim to be a drop-in replacement for babel doesn't really hold water without it IMO.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/9114

**Comment by Dagur** [comment]
awesome!
