### ISSUE TITLE
`@swc/wasm-typescript` ASI risk 

### ISSUE THREAD

**Issue by acutmore** [swc-project/swc#9331]
### Describe the bug

In `@swc/wasm-typescript` "strip types only" mode it's possible to trigger a missing automatic semicolon insertion bug.

### Input code

```typescript
f
interface I {}
(1)
```

### Config

```js
import * as swc from "@swc/wasm-typescript";

const input = `...`;
const output = swc.transformSync(input, { mode: "strip-only" });

console.log(output.code);
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.1&code=H4sIAAAAAAAAA0vjyswrSS1KS0xOVfBUqK7l0jDUBACEKC2gFAAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D&strip-types=

### Expected behavior

```js
f
;             
(1)
```

### Actual behavior

```js
f
              
(1)
```

### Version

1.71

**Comment by kdy1** [comment]
Do you need a new stable version?
