### ISSUE TITLE
swc-loader appears to be in a deadlock since @swc/core@1.7.0

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#9335]
### Describe the bug

AFFiNE can not build since `@swc/core@1.7.0`, downgrade to `@swc/core@1.6.13` is fine

### Playground link (or link to the minimal reproduction)

See this branch: https://github.com/toeverything/AFFiNE/tree/swc-deadlock

- yarn install
- BUILD_TYPE=canary yarn workspace @affine/web build

### Expected behavior

Build successfully 

### Actual behavior

Build is freeze

### Version

1.7.2/1.7.1/1.7.0

**Comment by kdy1** [comment]
My guess is https://github.com/swc-project/swc/pull/9207
I'll try running the test suite with debug build. The optimization is about UB, so if related codes are encountered in the release build hang is one of _correct_ behavior (for rustc)

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://github.com/user-attachments/assets/0cbfdb74-8390-4c25-8606-66607ce3ff0b">

Okay it was the cause. Thank you for the report! I'll fix this within weekend.
