### ISSUE TITLE
VisitAll seems to work the same as Visit now

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#9337]
Just an FYI/heads up. I don't want to do a full report/reproduction because I switched away from it. It seems there's no longer a `visit_all_with` method for example and that's just `visit_with` with the same behaviour as `visit_with` on `VisitWith`.

https://github.com/search?q=repo%3Aswc-project%2Fswc%20visit_all_with&type=code

**Comment by kdy1** [comment]
I'll remove `VisitAll` then. SWC does not use it. It exists just for Deno
