### ISSUE TITLE
RFC: Simplify `SyntaxContext` and `Mark`

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9346]
We don't use complex features of `SyntaxContext` nor `Mark`. 

For `@swc/core` and `next-swc`, we only need

 - Parent-child relationship for `Mark`
 - `SyntaxContext.apply_mark()`

But I want to know if there's a project using more complex features.

**Comment by g-plane** [comment]
What're complex features?

**Comment by kdy1** [comment]
- `Mark#set_is_builtin` && `Mark#is_builtin` (https://rustdoc.swc.rs/swc_common/struct.Mark.html#method.is_builtin)
 - `SyntaxContext#*_adjust` (https://rustdoc.swc.rs/swc_common/struct.SyntaxContext.html)
