### ISSUE TITLE
How to set env values in .swcrc - @swc/jest

### ISSUE THREAD

**Issue by Aravin** [swc-project/swc#9357]
### Describe the feature

I wanted to set some values to env

**example:**
process.env.NODE_ENV = ABC
process.env.SOMETHING = SOMEDATA

this is my config file

```
jsc: {
		parser: {
			syntax: 'typescript',
			tsx: true,
			decorators: true,
			dynamicImport: true,
		},
		transform: {
			react: {
				runtime: 'automatic'
			},
		},
	},
````

I have tried setting props: `define`, `global` etc. it doesn't works

### Additional context

OS: Mac
transformer: @swc/jest
app: react/front-end

**Comment by kdy1** [comment]
Please use GitHub discussion or discord #questions for questions.

**Comment by Aravin** [comment]
btw @kdy1  do you have answer for this?
