### ISSUE TITLE
compilation doesn't omit import that is not used in runtime if typescript alias is created from imported type

### ISSUE THREAD

**Issue by layerok** [swc-project/swc#9368]
### Describe the bug

compilation doesn't omit import statement that is not used in runtime if typescript alias is created from imported type

### Input code

```typescript
import {Schemas} from './types.d';
import AddressResource = Schemas.AddressResource;
```

### Config

```json
{}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.4&code=H4sIAAAAAAAAA8vMLcgvKlGoDk7OSM1NLK5VSCvKz1VQ19MvqSxILdZLUbfm5cqEqHFMSSlKLS4OSi3OLy1KTlWwVYBq0kOTsQYAWJI5D1UAAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3CHK0KF36CEQdSIqfsKOVBTl7oUE0maz38fveRVSwps0PORaxrJElQjTuReEsmf1KQhwjkg6mchw6yxTpSZlCXdoOxhglWbk6kIah3FoDrAhEHZHw5zxZsr%2FmTq4mJDoKqxS5WeL10TRUsGF17KT7Zfa92hwh5%2Boh52HwdCzOzktKLYvIO%2B2AhcBAAA%3D

### SWC Info output
<details>
  <summary><code>npx -y swc-info@latest</code></summary>
  
```
    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
        CPU: (8 cores)
            Models: Apple M1

    Binaries:
        Node: 20.0.0
        npm: 9.6.4
        Yarn: 1.22.19
        pnpm: 9.4.0

    Relevant Packages:
        @swc/core: 1.3.89
        @swc/helpers: N/A
        @swc/types: 0.1.12
        

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A
        
```
</details>

### Expected behavior

import statement that is unsused in runtime is omitted 

### Actual behavior

import statement that is unsused in runtime is preserved

### Version

1.7.4

### Additional context

I'm using swc in my Vite project. After updating swc to version 1.3.89 I started seeing this error in the browser console.
```
SyntaxError: The requested module './types.d.ts' does not provide an export named 'Schemas'
```
swc prior to version 1.3.89 omitted import that was unused in runtime. That is why there was no such error in the browser console before.

Also I noticed if I use `import type` then swc of 1.3.89 version works as expected. 
```typescript
import type {Schemas} from './types.d';
import AddressResource = Schemas.AddressResource;
```

swc output is
```typescript
export {};
```

I guess this issue occured after issue #7177 was fixed.

**Comment by magic-akari** [comment]
As a workaround, use type import

```TypeScript
import { Schemas } from './types.d';
import type AddressResource = Schemas.AddressResource;
```
