### ISSUE TITLE
what is the JsWord mean? can I set a value of this type?

### ISSUE THREAD

**Issue by 756445638** [swc-project/swc#938]
**Question**

pub struct Ident {
    pub span: Span,
    #[serde(rename = "value")]
    #[cfg_attr(feature = "fold", fold(ignore))]
    pub sym: JsWord,
    #[serde(default, rename = "typeAnnotation")]
    pub type_ann: Option<TsTypeAnn>,
    /// TypeScript only. Used in case of an optional parameter.
    #[serde(default)]
    pub optional: bool,
}
I want to rewrite the Ident's field sym ,how can I do that?

**Comment by kdy1** [comment]
It's a read-only and reference-counted symbol. You have to treat it as `Box<str>`. I mean, you should do something like `i.sym = "foo".into();`. (JsWord implements From<&str>)

**Comment by 756445638** [comment]
ok thank you very much
