### ISSUE TITLE
Add LICENSE to @swc/wasm-typescript

### ISSUE THREAD

**Issue by marco-ippolito** [swc-project/swc#9408]
### Describe the feature

It would be very useful to add the SWC license to the npm package and in the `bindings/binding_typescript_wasm/scripts/patch.mjs` script.
https://www.npmjs.com/package/@swc/wasm-typescript?activeTab=code
So that Node could pull it directly

**Comment by kdy1** [comment]
I'll do this on the main branch directly once https://github.com/swc-project/swc/pull/9399 is merged, and I'll publish a new version after adding one.

**Comment by kdy1** [comment]
Closing as fixed by `v1.7.9`
