### ISSUE TITLE
TypeScript 4.0: Support type on catch clause bindings

### ISSUE THREAD

**Issue by dsherret** [swc-project/swc#941]
**Describe the feature**

TypeScript 4.0 allows an unknown type on catch clause bindings:

```ts
try {
}
catch (e: unknown) {
}
```

**Babel plugin or link to the feature description**

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-rc/#unknown-on-catch

**Comment by kdy1** [comment]
I think it's already supported by swc.

https://github.com/swc-project/swc/blob/0989e73a99d1fbd123c0da76e40f033963176ce9/ecmascript/parser/src/parser/stmt.rs#L576-L594

**Comment by kdy1** [comment]
Oh.. there was wrong error.

**Comment by dsherret** [comment]
Could the type be stored in the AST?

**Comment by kdy1** [comment]
I'll do so

**Comment by dsherret** [comment]
Awesome. Thanks a lot! 🙂
