### ISSUE TITLE
HTML is modified through swc_html-visit and the generated HTML string from swc_html-codegen is used to convert " to &quot

### ISSUE THREAD

**Issue by SKT1yang** [swc-project/swc#9410]
### Describe the bug

 want to use swc_html related tools to parse, modify, and regenerate HTML. One of the tasks is to wrap the Chinese characters displayed in HTML with a't 'function using swc_html-visit, such as the visit_mut_antent callback function. During the wrapping process, I need to use double quotation marks
`let new_text = format!(r#"t("{}")"#, value);`
inside the string, but in the final generated HTML string, the double quotation marks become
`&quot;`
, Just like the picture below, I don't know if this is normal:
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/890e67ee-d16d-4e41-a9d4-4c2c30cd3827">

### Playground link (or link to the minimal reproduction)

https://github.com/SKT1yang/loader

### SWC Info output

Operating System:
Platform: darwin
Arch: x64
Machine Type: x86_64
Version: Darwin Kernel Version 20.6.0: Thu Jul 6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64
CPU: (12 cores)
Models: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

```
Binaries:
    Node: 22.3.0
    npm: 10.8.1
    Yarn: N/A
    pnpm: 9.3.0

Relevant Packages:
    @swc/core: N/A
    @swc/helpers: N/A
    @swc/types: N/A
    

SWC Config:
    output: N/A
    .swcrc path: N/A

Next.js info:
    output: N/A
```

### Expected behavior

```
  <template>
    <div label="t("资产")" :title="t('标题')">
      我是中文
    </div>
  </template>
```

### Actual behavior

```
  <template>
    <div label="t(&quot;资产&quot;)" :title="t('标题')">
      我是中文
    </div>
  </template>
```

### Version

0.283.0

### Additional context

```
swc_html_ast = { version = "0.37.0", features = ["serde-impl"] } 
swc_html_parser = { version = "0.43.0" } 
swc_html_visit = { version = "0.37.1" } 
swc_html_codegen = { version = "0.46.0" } 
swc_common = { version = "0.37.0" } 
swc_core = { version = "0.100.2", features = ["common"] } 
swc_atoms = "0.6.7"
```

**Comment by magic-akari** [comment]
This is in compliance with the standard, please refer to the [HTML specification](https://html.spec.whatwg.org/#escapingString).

> Escaping a string (for the purposes of the algorithm above) consists of running the following steps:
>
> 1. Replace any occurrence of the "&" character by the string "&amp;".
> 2. Replace any occurrences of the U+00A0 NO-BREAK SPACE character by the string "&nbsp;".
> 3. If the algorithm was invoked in the attribute mode, replace any occurrences of the """ character by the string "&quot;".
> 4. If the algorithm was not invoked in the attribute mode, replace any occurrences of the "<" character by the string "&lt;", and any occurrences of the ">" character by the string "&gt;".

You can also use the following simple code to verify:

```JavaScript
let div = document.createElement("div")
div.setAttribute("label", `t("资产")`);
console.log(div.outerHTML)
```

You will get the following result:

```HTML
<div label="t(&quot;资产&quot;)"></div>
```

**Comment by LingyuCoder** [comment]
How to set `src` with `&` on `script` tag? It will always be escaped. I can use following code to set it in web

```js
let script = document.createElement("script")
script.src="file.js?a=1&b=2";
```

But I can not find a way to do this with `swc_html`

**Comment by LingyuCoder** [comment]
> > How to set `src` with `&` on `script` tag? It will always be escaped. I can use following code to set it in web
> > ```js
> > let script = document.createElement("script")
> > script.src="file.js?a=1&b=2";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I can not find a way to do this with `swc_html`. Need some help @magic-akari
> > Perhaps need a flag on `Attribute` to not [escape](https://github.com/swc-project/swc/blob/08b21a9588e9c49e95dc6003ffd134d722012277/crates/swc_html_codegen/src/lib.rs#L801) its `value`?
> 
> This is an interesting issue. We know that both `&` and `&amp;` work in this case. I suggest opening a new issue to talk about it.

Oh, seems I was wrong. `.setAttribute()` and `.src=` have the same behavior. The escaping occur in `script.outerHTML`:

```js
let script = document.createElement("script")
script.src="file.js?a=1&b=2"
// or
script.setAttribute("src", "file.js?a=1&b=2")
console.log(script.src.endsWith("file.js?a=1&b=2")) // true
console.log(script.outerHTML) // <script src="index.js?a=1&amp;b=2"></script>
```

So swc_html is same with web. I can just unescape the `outerHTML` to get the raw HTML code of script tag. Thanks
