### ISSUE TITLE
Make CDN ESM paths work

### ISSUE THREAD

**Issue by sdegutis** [swc-project/swc#9423]
### Describe the feature

I want to specify this config:

```json
{
  "jsc": {
    "paths": {
      "@swc/wasm-web": [
        "https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.7.10/+esm"
      ]
    },
    "parser": {
      "syntax": "typescript",
    },
  }
}
```

and have this input:

```ts
import foo from '@swc/wasm-web';
foo();
```

give this output:

```ts
import foo from "https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.7.10/+esm";
foo();
```

but instead I get this:

```ts
import foo from "./https:/cdn.jsdelivr.net/npm/@swc/wasm-web@1.7.10/+esm";
foo();
```

I can't tell if there's already a way to do this or not, but it looks like no, so I'm specifying it as a feature request at the very least.

**Comment by magic-akari** [comment]
I haven't tested it yet, but it appears to be exactly what you need.
See https://github.com/swc-project/swc/discussions/9016#discussioncomment-10308208

**Comment by sdegutis** [comment]
Thanks, but when I use jsc.experimental with an empty object, or include plugins with an empty array, or include this plugin with an empty object, etc, swc crashes with a weird error that I can't find anything about. I also can't find any docs for this plugin or for how to use the experimental-plugins feature. So I'm trying to create a plugin manually instead to use with the non-experimental plugin feature to accomplish this.

**Comment by kdy1** [comment]
@sdegutis JS plugin is deprecated, and I would recommend using wasm plugins if possible.
It's documented at https://github.com/swc-project/plugins/tree/34141644d2a9ac43ff8d853b4c938f2afd5fb610/packages/transform-imports, but `@swc/wasm-web` does not support it. But `@swc/wasm*` does not support JS plugin, too.
