### ISSUE TITLE
reflect-metadata does not work as expected in some scenarios

### ISSUE THREAD

**Issue by cjnoname** [swc-project/swc#9430]
### Describe the bug

Hi,

We are developing NodeJS applications using TypeORM and TypeGraphQL, both of which heavily rely on decorators and emitDecoratorMetadata.

We have encountered some unusual behaviors during the SWC compilation process. I have provided an example below:

https://github.com/cjnoname/example-esm

Please check out the repository, install the package, and run npm start. You will see the issues within seconds.

You can easily toggle the “swc” flag between true and false in tsconfig.json file to compare the output between tsc and swc.

Issue 1: A getter function within a class object does not return the correct type, as demonstrated in the example code.
It should return “String” as shown in tsc, but it is showing “Function” in swc.

Issue 2: The enum metadata is correct when the enum is in the same file as the class, but it is incorrect when loaded from another TypeScript file. enum1 and enum2 are incorrect, displaying the original file content in their metadata, while enum3 shows correctly in its prototype.

### Playground link (or link to the minimal reproduction)

https://github.com/cjnoname/example-esm

### Expected behavior

Both of these issues should be fixed to align the output with the compilation results of tsc.

### Actual behavior

As shown in the example on Git

### Version

"@swc/core": "1.7.11"

**Comment by kdy1** [comment]
`swc` works on a single-file basis so enum from another module cannot work.

**Comment by cjnoname** [comment]
> Issue 1: A getter function within a class object does not return the correct type, as demonstrated in the example code.
> It should return “String” as shown in tsc, but it is showing “Function” in swc.

How about this one mate? This happens in a single file.

**Comment by kdy1** [comment]
Please provide a minimal reproduction

**Comment by cjnoname** [comment]
> Please provide a minimal reproduction

It's in the same GitHub repo, mate. Could you take a quick look at both issues? It might take you less than five minutes. I love this library and hope it can be perfect. Many thanks mate.

**Comment by kdy1** [comment]
I meant that your reproduction is way too big

**Comment by kdy1** [comment]
Minimal reproduction is something like https://github.com/swc-project/swc/issues/9435

**Comment by cjnoname** [comment]
> Minimal reproduction is something like #9435

Thanks mate :) This is the first time I did it :)
