### ISSUE TITLE
swc.transform:  decorators - descriptor is undefined

### ISSUE THREAD

**Issue by dxhsmwqcwelllee** [swc-project/swc#9431]
### Describe the bug

descriptor is undefined

### Input code

```typescript
const swc = require('@swc/core');

const swcOptions = {
    'jsc': {
        'parser': {
            'syntax': 'ecmascript',
            decorators: true,
        },
        transform: {
            legacyDecorator: true,
            decoratorMetadata: true
        }
    },
};

swc.transform(content, swcOptions).then(
    (output) => {
        callback(
            null,
            output.code,
        );
    },
    () => {
        // some thing wrong
    },
);
```

### Config

```json
const swcOptions = {
    'jsc': {
        'parser': {
            'syntax': 'ecmascript',
            decorators: true,
        },
        transform: {
            legacyDecorator: true,
            decoratorMetadata: true
        }
    },
};
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.11&code=H4sIAAAAAAAAA0srzUsuyczPUyhKTUzJz8up1ChJLEpPLdFRyEvMTdVRSEktTi7KLCjJL9JUqOZSAAKEiF55UWZJYlJOqoKtQlpiTnGqNVhBUWpJaVEekjprrlouruScxOJihZDU4hKoOQ4wG8G84pLEksxkBV%2FHiPhgzyjX%2BNAAH39HF6DBhgZGJgpaCMrAWoGrFgBku2XMtgAAAA%3D%3D&config=H4sIAAAAAAAAA12NTQ6DUAiE957ihXVP0HW3PcQEsalRnwFMNMa7l%2FoX2xXMfAwzFylRbUz3NMcaooea6KnDsalzjOGQcAtjffdOt4PW9kUVGpPTK4WzwrNaINdhJ8s2yBWdVVnbS8sKGnmBp8eR%2Fgn%2Fv36Ko4RjP9oKirVk%2BQDOOCO%2F1gAAAA%3D%3D

### Expected behavior

descriptor is not undefined

### Version

1.7.11

### Additional context

Any version

**Comment by kdy1** [comment]
You are using legact decorator

**Comment by dxhsmwqcwelllee** [comment]
> You are using legact decorator

How can I solve this problem? thank

**Comment by dxhsmwqcwelllee** [comment]
['@babel/plugin-proposal-decorators', { legacy: true }] in babel.config.js ，swc not support it？

**Comment by dxhsmwqcwelllee** [comment]
@kdy1

**Comment by kdy1** [comment]
No it's supported

**Comment by kdy1** [comment]
swc is correct here. See https://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true#code/GYVwdgxgLglg9mABAJwKYEMAmCA2BPACinWQHNUoAaRMdAW1Ws1QGcJkYAHKOZASkQBvAFCIxiZmw7deAOgDuHYgCMcqRAF5EwdDhaoA3KPFooIZEknsuPZEYC+w4RBzoWLRABVWUIcbEAAmhYuHj+iCzEsBCIALIAggAaAPoAygCSAFoAoskAqgAKADIA8vEAIpqIAIwADABMACyIAFQ1Dc1tdbUGiML2QA

**Comment by kdy1** [comment]
And please do not ping me.
