### ISSUE TITLE
`design:returntype` is wrong for getter properties

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9435]
### Describe the bug

Extracted from https://github.com/swc-project/swc/issues/9430

### Input code

```typescript
import { Entity, Column } from "typeorm";
import { Field, ObjectType, registerEnumType } from "type-graphql";
import { Enum1, Enum2 } from "./enum.js";

export enum Enum3 {
  A = "A",
  B = "B",
  C = "C",
  D = "D"
}

registerEnumType(Enum3, { name: "Enum3" });

@Entity("user", { schema: "public" })
@ObjectType("User")
export class User {
  @Column({ name: "first_name" })
  @Field({ nullable: true })
  firstName?: string;

  @Column({ name: "last_name" })
  @Field({ nullable: true })
  lastName?: string;

  @Field()
  get fullName(): string {
    if (!this.firstName && !this.lastName) {
      return "";
    }
    return `${this.firstName} ${this.lastName}`.trim();
  }

  @Column()
  @Field(() => Enum1)
  enum1: Enum1;

  @Column()
  @Field(() => Enum2)
  enum2: Enum2;

  @Column()
  @Field(() => Enum3)
  enum3: Enum3;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "decoratorMetadata": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.11&code=H4sIAAAAAAAAA42STU%2FDMAyG7%2FkVJkJTKpWidbdNg31yhAucWVfSLlPTliSVmKb%2Bd%2BKEjg5NGqfazvO%2BttMIWVfKwBHWpRHmEMKyKhpZQguZqiRQc6h5pSSdENGRT4IXHyG8bPc8Na%2F2PATFc6ENV%2BuykVg5k9%2FlKql3n0XfA8Fh6D7xCY7uuc2jvbYk4V8OxYrDRnAkAHOYAp3T0IYLDBcuXGK4dOEKwxUlLSF%2Fh2LOJrTdy0TyMVCXU2gD227m92e00VxRhHS64zKxWN1sC5EiR2a%2FSzP6hmTQDZoWidaANTfozN8jOzXLhNLmHRPnZAl3jwg0RZFsCwsZ1XB%2F6OhnCz%2BOQRslytzOeMHVNv2%2FKcIXPL0EgZwbyKwQIRZ0lNsHQGTAbsxO6Og0HAwG4EuddfADg30SplElUPsvMW1Jr7i5PZ4btfBT6XzaTWR7Sxaguu2v3tuSBTB98E8Jq%2FhUhmOfT65K4k4Se0l8XTLqJCMvGU1I%2Bw1uayezQAMAAA%3D%3D&config=H4sIAAAAAAAAA2WQSw6DMAxE95wCed1FxbJ34BBWMCiIfGQbqQhx9yYUUlB38Uxm%2FOS1qmsYxcCrXtMzDRFZiMucFFm84jspoEskMWyjwuN0VbLV4yRUtI5MYNTAkizlmXZj%2B%2FqgyANp7iNpnk1zdMEUgtC9C5z1tl%2BuNCa4yCTyt9ShH6aSv29k9NIHdteiAtmSYoeKN9bqSIML3bzXHvfJN8jsicMFPwr8fp6shQustGd8r94%2BQ9POT3ABAAA%3D

### Expected behavior

It should be a property

### Version

1.7.11

**Comment by cjnoname** [comment]
Thank you for helping me with this reproduction. The enum issue is crucial as it affects all TypeORM users, a library widely used in the Node.js community.
