### ISSUE TITLE
Confusing warning message when using __wbg_init in @swc/wasm-web v1.7.x

### ISSUE THREAD

**Issue by catloversg** [swc-project/swc#9443]
### Describe the bug

Starting from `@swc/wasm-web` v1.7.x, I see this warning message: `using deprecated parameters for the initialization function; pass a single object instead` when calling `__wbg_init` without a parameter. Current documentation at <https://swc.rs/docs/usage/wasm> does not say anything about a required parameter.

When I check code in `node_modules\@swc\wasm-web\wasm.d.ts` and `node_modules\@swc\wasm-web\wasm.js`, I see that:
- `__wbg_init` allows `module_or_path` to be optional. It says `Passing InitInput directly is deprecated`. With this way of phrasing, I think it means: "If you want to pass `InitInput`, you need to pass `{module_or_path:InitInput}` instead of plain `InitInput`". It does not say anything about skipping `module_or_path`. This is how I interpret it.
- Implementation of `__wbg_init` shows that if `module_or_path` is undefined, it will print the warning message.

Can you confirm that skipping `module_or_path` is also deprecated? If that's the case, I suggest:
- Clearly state that in the TSDoc. 
- Update the documentation at <https://swc.rs/docs/usage/wasm>.

### Playground link (or link to the minimal reproduction)

https://swc.rs/docs/usage/wasm

### Expected behavior

- `__wbg_init` does not print the warning message or the TSDoc is updated.
- The documentation at <https://swc.rs/docs/usage/wasm> is up-to-date.

### Version

1.7.11

**Comment by kdy1** [comment]
Actually it's generated by wasm-pack and wasm-bindgen, and I don't have any idea about them at the moment.

**Comment by catloversg** [comment]
This issue was fixed in `wasm-bindgen`. Ref: https://github.com/rustwasm/wasm-bindgen/issues/4122#issuecomment-2380562394
