### ISSUE TITLE
Node bindings for swc_html_minifier

### ISSUE THREAD

**Issue by slorber** [swc-project/swc#9457]
### Describe the feature

As far as I understand, `swc_html_minifier` only exists as a Rust crate

It would be nice to expose it as an npm package as well so that the JS community can use it.

### Additional context

For static site generators like Docusaurus, minimizing html and inlined JS is an expensive task, for which we do no have a lot of very fast options currently.

Our current dependency is:

```js
import {minify} from 'html-minifier-terser';
```

It accounts for almost half the time it takes to generate static files. We could be happy to replace it with a faster option solving a similar problem.

**Comment by kdy1** [comment]
I triggered a publish action for [v1.7.15](https://github.com/swc-project/swc/actions/runs/10466071856)

**Comment by slorber** [comment]
Awesome 🤟😍 that was fast, can't wait to test it!

**Comment by kdy1** [comment]
Publish action failed. I'll publish the package once it's fixed.

**Comment by kdy1** [comment]
@Brooooooklyn Are you still working on the CI fix?

**Comment by kdy1** [comment]
I fixed CI and now `@swc/html` is published!

**Comment by slorber** [comment]
Thanks! ❤️ 

Now can you please opensource your lightningcss-loader? 😄
