### ISSUE TITLE
Duplicate variable declaration with compress and mangle

### ISSUE THREAD

**Issue by m-2k** [swc-project/swc#9468]
### Describe the bug

result contain dup code:
```
var arg2, arg2;
```

**config**: `compress` & `mangle` only with default configurations

### Input code

```typescript
function func1(arg1, arg2) {
  return getX(arg1)+arg2
}
function getX(x) {
  const v = document.getElementById('eid').getAttribute(x)
  return v
}
console.log(func1(7,getX('data-x')))
console.log(func1(7,getX('data-y')))
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.14&code=H4sIAAAAAAAAA4WOMQvCMBCF9%2FyK29JgLdTFyUHBwX%2FgGpNLCMQE0ktpEf%2B7SYo4uhyP%2B967dyYHRS4GMEWMnUx27KHMg4AXA0hIOQWwSPfGxK4y9mbmm2to2dwqholghhPoqPITAw0FXz1WeVlvuuPoNBd1eyZK7pEJS%2FhXNJfT9Ur0OPhou%2B2rY99auJYk9wsXQvwzrc3EPrpDYNTeAAAA&config=H4sIAAAAAAAAA42VS47bMAxA93OKwOsu2kWLogformcQFItylMqiIVKZBIPcvbRsZzJj2ugmiPn4ESmSens5HJoztc2vw5v8lY%2FBZoL8%2BBYJ3RLbq0gaaHtLbQ4DN18WeqYReRsJqug%2BkYZt7oCrFX2f1ZuISLCoz7I%2BpOBvzwFb7IcMRE8ykYq%2F0kNi%2Bmg%2Fs4yvI%2BBcnuVHxAg27RBjyYTE0EHWHLcYox0IzMVmxct4UpsDoRZihIXBmSHjoPLkAgdMEnNNHVhnWnSgoJCh5XABzUxiiVkiSU%2FJp2IHx9J19ZI%2FWcPFxmJZiQnXeiVyWsXrCQOx8SVpJZzgRg0mOBf3s2XwJgOXnNZ2Zwxp407%2BAkgFoiVKtgfNb9Xw0k9b1n7XMiQvLcs3hUt%2Fa1km6KSoJgSvVHasDGQO2m1mcKWFsbKtdpwZb5SPggMD3kuvKK7pNXB70oLybQD0CpD7tV7rqgmYxxRu8HEgdvBvyZL1Bps1esunbUq3%2FohxJ0APfEK3oyBXwbiNs2yJ67DNS3IgrQFOVSlUwXoJyAAwmliX5ao3ZDzEo%2BkiHt%2FXxKxwfyzh3qauzvvTvmQcIlwgbrXxf4zILpWzXcauXiZ7Nb3wU2tKK4MXvn398GZIKi%2FLb02q6dGVp4RqT05vyY%2FmXWl5OR5BmkB%2FFstaqPs%2F4HBnGOEGAAA%3D

### Expected behavior

maybe single declaration for every variables

### Actual behavior

```js
var arg2, arg2; /// <--- Dup code. Before mangling: var arg2, arg21;
function getX(t) {
    return document.getElementById('eid').getAttribute(t);
}
console.log((arg2 = getX('data-x'), getX(7) + arg2)), console.log((arg2 = getX('data-y'), getX(7) + arg2));
```

### Version

1.7.14

**Comment by kdy1** [comment]
Error log:


  DEBUG  ===== Start =====

```js
function func1(arg1, arg2) {
    return getX(arg1) + arg2;
}
function getX(x) {
    return document.getElementById('eid').getAttribute(x);
}
var arg1, arg2;
var arg11, arg21;
console.log((arg1 = 7, arg2 = getX('data-x'), getX(7) + arg2)), console.log((arg11 = 7, arg21 = getX('data-y'), getX(7) + arg21));
```

    at crates/swc_ecma_minifier/src/compress/mod.rs:179
    in optimize with pass: 2
    in compress ast
    in minify



  DEBUG  ===== Start =====

```js
var arg2, arg21;
function getX(x) {
    return document.getElementById('eid').getAttribute(x);
}
console.log((arg2 = getX('data-x'), getX(7) + arg2)), console.log((arg21 = getX('data-y'), getX(7) + arg21));
```

    at crates/swc_ecma_minifier/src/compress/mod.rs:179
    in optimize with pass: 3
    in compress ast
    in minify

**Comment by kdy1** [comment]
I found the cause.

`mangle.toplevel` is false by default, and the name mangler just preserves top level identifiers even if those are synthesized.
