### ISSUE TITLE
es(minify):  if_return plus sequence optimize make code run in wrong order 

### ISSUE THREAD

**Issue by stormslowly** [swc-project/swc#9485]
### Describe the bug

using swc_core: 0.101.4

just parse, resolve, optimize to the input code, then final generated code run in the wrong order.

in the input code, the `hook` will not be called, is async is `false`

after optimize 
```js
function bug(r, e) {
  var i;
  return e && isPromiseLike((i = r())) ? i : 0;
}
```

### Input code

```typescript
export function bug(hook, async) {
  var ret;
  ret = hook();
  if (!(async && isPromiseLike(ret))) {
    return 0;
  }
  return ret;
}
```

### Playground link (or link to the minimal reproduction)

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b61031e4d72c3952b521891a3b3f7955

### Expected behavior

no matter what value `async`  is,  function `hook` should always be called.

### Actual behavior

after optimize 
```js
function bug(r, e) {
  var i;
  return e && isPromiseLike((i = r())) ? i : 0;
}
```
if `e`( `async`) is `false`,  the `r`(`hook`) will never be called

### Version

0.101.4

### Additional context

config CompressOption with below, code works as expect
```
    sequences: 0,
    if_return: false,
    ..Default::default()
```

**Comment by stormslowly** [comment]
can not be reproduced in https://play.swc.rs  with swc 1.7.4 nor nightly

**Comment by stormslowly** [comment]
@kdy1  any hint for me?  maybe i can help to fix it

**Comment by kdy1** [comment]
It's not a bug of SWC minifier; it's wrong usage I guess

**Comment by kdy1** [comment]
You may need `paren_remover` and `fixer`

**Comment by kdy1** [comment]
See: https://github.com/swc-project/swc/blob/ede1a52cb8fb681ca08c54880c75c9b115c7a906/crates/swc_ecma_minifier/examples/minifier.rs

**Comment by kdy1** [comment]
Can you try the example minifier with your input?

**Comment by kdy1** [comment]
After applying the name mangler or the `hygiene` pass. `optimize` applies the name mangler (if mangle option is specified), so it's after `optimize` in this case.

**Comment by stormslowly** [comment]
thx a lot
