### ISSUE TITLE
Unused imports are removed only when language is TypeScript

### ISSUE THREAD

**Issue by madbence** [swc-project/swc#9491]
### Describe the bug

SWC removes `import` when it realizes that `unused` is not used, and the used language is TypeScript. In JS, the `import` statement is preserved.

### Input code

```typescript
import { unused } from './unused.js'
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.14&code=H4sIAAAAAAAAA8vMLcgvKlGoVijNKy1OTVGoVUgrys9VUNfThwjoZRWrAwAGPMf%2FJAAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KHN0KF36CEQdSIqfsKOVBTl7oUE0maz38fveRFSwps0PORSxrJElQjTsReEsmf1KQhwjkg6mchw6SxTpUZlCTdo3RlglSbk6kIarsOtOcCGQNgdDXPGmzH%2FZ%2BrgYkKis7BKlZ8snhNFSwUXXvNGtl9q373BHX6iHnYcBkPP7uQ0o1i%2FsnkCbBcBAAA%3D

### Expected behavior

The behavior should be the same for both JS and TS (I think the `import` statement should be preserved).

### Actual behavior

In JS, the output is the following:

```js
import { unused } from './unused.js';
```

In TS:

```ts
export { };
```

### Version

1.7.14

**Comment by kdy1** [comment]
It's expected

**Comment by kdy1** [comment]
JS has specification, while TS has only `tsc`. We follow behavior of `tsc` for TypeScript inputs.
