### ISSUE TITLE
emitIsolatedDts does not emit .d.ts when using --out-file

### ISSUE THREAD

**Issue by jbedard** [swc-project/swc#9512]
### Describe the bug

`emitIsolatedDts` does not output any dts when `--out-file` is used to specify the output location.

 This works for sourcemaps with `--out-file` and `--out-dir`. This works for dts when `--out-dir` is used but NOT `--out-file`.

### Input code

```typescript
export interface Foo {
  name: string;
}
export const AF: Foo = {
  name: "bar",
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "experimental": {
        "emitIsolatedDts": true
    }
  },
  "sourceMaps": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.6&code=H4sIAAAAAAAAA%2BNKrSjILypRyMwrSS1KS0xOVXDLz1eo5lJQyEvMTbVSKC4pysxLt%2Baq5YIqTM7PKy5RcHSzAiu0RVKqlJRYpKTDVWsNAEpEJOhUAAAA&config=H4sIAAAAAAAAA02Muw2AMAxEe6aIXDMBNQ0FQ0TBRRAByzYSUZTdMR8hOt%2B9ey6NczBLgM4VOy2QZ0H%2BsjWSV%2FWHNaCZUAJHUrhhbR8HD0KOCW23%2FMyLpKiDbItXnHoVg8o7PnLzPgDZdg44evp4PQGPl4lFmAAAAA%3D%3D

### Expected behavior

When `--out-file dist/foo.ts` is specified `foo.js.map` and `foo.d.ts` output behaviour should be equivalent. Today sourcemap files are outputted alongside `dist/foo.js`, dts files should do the same.

### Actual behavior

dts files are not outputted when using `--out-file`

### Version

v1.6.6

**Comment by kdy1** [comment]
Are you using Rust CLI?

**Comment by jbedard** [comment]
Yes, we're using the rust cli and invoking it per-file for the bazel [rules_swc](https://github.com/aspect-build/rules_swc/blob/v2.0.0/swc/private/swc.bzl#L313).
