### ISSUE TITLE
`strictMode` configuration does not work

### ISSUE THREAD

**Issue by Pyroglyph** [swc-project/swc#9514]
### Describe the bug

Disabling the `strictMode` option still causes strict mode related errors to occur.

### Input code

```typescript
const eval = '';
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6",
    "strictMode": false
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.21&code=H4sIAAAAAAAAA0vOzysuUUgtS8xRsFVQV7cGACUl70cQAAAA&config=H4sIAAAAAAAAA1WPSw6DMAxE9zlF5HW37aJ34BBRMCiIfGQbqRHi7g2QINjZM2M%2Fe1Vaw8QWvnotZWmSIUa6%2BqJwDmJ%2BRQG03rAllwRezZ14twYzMx7SdjoghkaUY4rfNQ5zjIwtXjXvghvyHWijT4TMz%2BAeNWGc8YlTFQk%2B9sth1kckJzzxn4ZnIWeli%2F19R51uV1xEcNy1lUILqu0PkwOtqC0BAAA%3D

### SWC Info output

    Operating System:
        Platform: win32
        Arch: x64
        Machine Type: x86_64
        Version: Windows 11 Pro
        CPU: (16 cores)
            Models: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics

    Binaries:
        Node: 20.17.0
        npm: N/A
        Yarn: N/A
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.7.21
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.5.4

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

I expect a similar output to the input (an empty string being assigned to a variable with the name "eval").

### Actual behavior

A strict-mode related error appears, despite strict mode supposedly being disabled.

```
  x 'eval' and 'arguments' cannot be used as a binding identifier in strict mode
   ,-[input.js:1:1]
 1 | const eval = '';
   :       ^^^^
   `----


Caused by:
    0: failed to process js file
    1: Syntax Error
```

### Version

1.7.21

**Comment by kdy1** [comment]
You used 

```json
"module": {
    "type": "es6",
    "strictMode": false
  },
  "isModule": true
```

Module codes are always in strict mode
