### ISSUE TITLE
can't add comments in right place after changing AST structure because can't get the right Bytepos

### ISSUE THREAD

**Issue by zhangmingyuan666** [swc-project/swc#9517]
### Describe the bug

In my swc plugin, I can't add comments after changing AST structure because I can't get the right bytePos of the target AST node.

### Input code

```typescript
const c = s1sAsyncImport("@/components/async-component.vue")
```

### Playground link (or link to the minimal reproduction)

https://github.com/zhangmingyuan666/async_import_plugin 

### Expected behavior

```js
const c = ()=>{
    return import(/* webpackChunkName: chunkIndex */"@/components/async-component.vue").then((res)=>res);
};
```

### Actual behavior

const c = ()=>{
    return import("@/components/async-component.vue").then((res)=>res);
};

### Version

swc_core: 0.91.0

### Additional context

Build shell: `cargo build` 

Test: `cargo test --package s1s_async_import_plugin --test fixture -- --show-output` 

Version: swc_core: `0.91.0`

Goal: Transform a function named `s1sAsyncImport` into a function structure with magic comments using a custom swc plugin. 

Core Issue: After changing the AST nodes in my swc plugin, I need to add magic comments to the left of the modified import path.

In Babel, my solution is as follows:

1. Create a node for the path string
2. Add comments to the node using `addComments`
3. Add the node to the new AST tree

```js
module.exports = function({ types: j }) {
  return {
    name: 'syntax-async-import',
    visitor: {
      CallExpression(path) {
        if (path.node.callee.name === 's1sAsyncImport') {
          // pathValue as a sample
          let pathValue = 'path'
          
          // add comment in import param node
          const importParamNode = j.stringLiteral(pathValue)
          j.addComments(importParamNode, 'leading', [{
            type: 'CommentBlock',
            value: ` webpackChunkName: '${path}'`
          }])
        
          path.replaceWith(
            j.arrowFunctionExpression([], j.blockStatement([
              j.returnStatement(j.callExpression(j.memberExpression(j.callExpression(
                j.identifier('import'),
                // add importParamNode here
                [importParamNode],
              ), j.identifier('then'), false), [j.arrowFunctionExpression(
                [j.identifier('res')],
                j.blockStatement([j.returnStatement(j.identifier('res'))])
              )]))
            ]))
          )    
    }
  }
}
```

However, in swc, the `add_leading` method used to add comments takes **BytePos** as the first argument, which seems to represent the **AST position** to insert the comment. This is different from the way comments are added in Babel plugins. Therefore, in swc plugins, I cannot insert comments as freely as in Babel plugins.

In swc-plugin, I can only write it like this, which leads to a failure to insert comments:

1. Create an importNode
2. Pass the Span of importNode and the corresponding comment in the `self.comments.add_leading` method. However, I can't get the Bytepos of the ImportNode

This is what I have tried:

```rust
let import_path = "path"

let importNode = ExprOrSpread {
    spread: None,
    expr: Box::new(Expr::Lit(Lit::Str((Str {
        span: DUMMY_SP,
        value: import_path.into(),
        raw: None
    }))))
};

let comment = Comment {
    span: DUMMY_SP,
    kind: CommentKind::Block,
    text: "comment".into()
};
self.comments.add_leading(importNode.span().lo, comment);
```

Questions:

1. In swc-plugin, how can I add comment blocks while modifying AST nodes?
2. Is it possible to bind comments to corresponding nodes like in Babel plugins (without considering Span and still being able to add comments)?
3. **How can I get the right BytePos to insert the comment?**

**Comment by kdy1** [comment]
Did you try adding a leading comment to the AST node? `BytePos` is a position in the input source code, and even if the codegen make it different, comments on AST nodes are preserved.

**Comment by zhangmingyuan666** [comment]
> Did you try adding a leading comment to the AST node? `BytePos` is a position in the input source code, and even if the codegen make it different, comments on AST nodes are preserved.

i know. But in my practise, I had successfully change the code from 
```js
const c = s1sAsyncImport("@/components/async-component.vue")
```
to
```js
const c = s1sAsyncImport(/* webpackChunkName: chunkIndex */ "@/components/async-component.vue")
```
because I can insert leading comments with the bytepos of the **AST nodes of `"@/components/async-component.vue"`**

***

However, if I changing the AST node of the `s1sAsyncImport("@/components/async-component.vue")` to 
```js
()=>{
    return import("@/components/async-component.vue").then((res)=>res);
};
```

with the same bytepos as before, I can't insert the comment, why?

**Comment by kdy1** [comment]
You used dummy span, which does means no bytepos.
See https://rustdoc.swc.rs/swc_common/struct.Span.html#method.dummy_with_cmt if you want to use a dummy span.

**Comment by zhangmingyuan666** [comment]
> You used dummy span, which does means no bytepos. See https://rustdoc.swc.rs/swc_common/struct.Span.html#method.dummy_with_cmt if you want to use a dummy span.

Thanks, I will try it.

**Comment by zhangmingyuan666** [comment]
> You used dummy span, which does means no bytepos. See https://rustdoc.swc.rs/swc_common/struct.Span.html#method.dummy_with_cmt if you want to use a dummy span.

My issue is fixed. Thanks!
