### ISSUE TITLE
Could not resolve "./node_modules/@swc/helpers/_/_call_super" (originally "@swc/helpers/_/_call_super")

### ISSUE THREAD

**Issue by noyobo** [swc-project/swc#9525]
### Describe the bug

version 1.7.23 enable externalHelpers

`_call_super` does not exist  https://www.npmjs.com/package/@swc/helpers?activeTab=code

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.23&code=H4sIAAAAAAAAA0vOSSwuVnAM8HQtKsovUkitKEnNSylWgPCquRSAIDk%2Fr7ikqDS5JL9II7c4XUchFSSpCZUFgeLSglSwnKY1XKwkI7NYD6zStzhdwRaiCS6ATZ1zfkoqqkKQCJrKzLy81CKI62BKkYRqamDaK0ogGmvBZEFRZl6JBrKTQZ7Kz0nVy8lP1wAbXFySmJytCdNUCwDnICgzGAEAAA%3D%3D&config=H4sIAAAAAAAAA22PSw7CMAxE95yi8potLDgBGw5hBRelyk%2B2K7WqeneStCkgsYtn3mTs5dR1MIiBW7fkZx4SshAfc1ZkDopTVoCMRzFsk8K5uYMUq0cnVKV1c0CRX6Q1JZcdBxejUMN3zdtg%2B%2Fm70ESfmER%2BwYJieDn6W0eTEgd0d3KJuESVx4JUAHx8jjW5X6lzom23K3ygtsnRClYeLVn%2FW98mTB8tMQEAAA%3D%3D

### Expected behavior

-

### Version

1.7.23

**Comment by noyobo** [comment]
Need to upgrade `@swc/helpers` maybe forgot it https://github.com/swc-project/swc/pull/9519

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/commit/6bdc4f7e5eb923a316744757c8bfdf2cfcf7a3ef
