### ISSUE TITLE
Spack doesn't use `.swcrc` file

### ISSUE THREAD

**Issue by anshulrgoyal** [swc-project/swc#953]
# Description
I tried using spack but it doesn't read `.swcrc` file

**Comment by anshulrgoyal** [comment]
Test is even not working 
![image](https://user-images.githubusercontent.com/32068075/89769074-31d69300-db1a-11ea-8c3c-82c29f0853a8.png)

**Comment by kdy1** [comment]
Nice catch. I never thought test was failing silently.
