### ISSUE TITLE
Number compression with minification creates invalid code

### ISSUE THREAD

**Issue by jiby-aurum** [swc-project/swc#9540]
### Describe the bug

`219994525426954..toString()` ends up bring transformed to `0xc815778a650a..toString();` which is invalid

### Input code

```typescript
219994525426954..toString()
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.24&code=H4sIAAAAAAAAAzMytLS0NDE1MjUxMrM0NdHTK8kPLinKzEvX0AQAWdlafxsAAAA%3D&config=H4sIAAAAAAAAA1WPMQ7DIAxFd06BPHeoGDr0Dj0Eok5EBQFhRyqKcvcCgbbZ8Pv%2F8%2B1NSAkvMnCXW3mWIepEmL5zIZQX1u9CgHNEMslGhstQmao0aUfY0H4owDrNyDWFpK5K9QS4EAhHojNvFzvl%2F04TfExIdDZWq15mh%2BdG0VvBh%2BfaxH5L3ffY4AY%2F0yjjtLZ%2FwdJjBCsT%2Bwd2MUYiFgEAAA%3D%3D

### Expected behavior

should not produce invalid code

### Actual behavior

produces invalid code

### Version

1.7.24

**Comment by jiby-aurum** [comment]
@kdy1 strangely still happens with 1.7.25, 

https://play.swc.rs/?version=1.7.24&code=H4sIAAAAAAAAAzMytLS0NDE1MjUxMrM0NdHTK8kPLinKzEvX0AQAWdlafxsAAAA%3D&config=H4sIAAAAAAAAA1WPMQ7DIAxFd06BPHeoGDr0Dj0Eok5EBQFhRyqKcvcCgbbZ8Pv%2F8%2B1NSAkvMnCXW3mWIepEmL5zIZQX1u9CgHNEMslGhstQmao0aUfY0H4owDrNyDWFpK5K9QS4EAhHojNvFzvl%2F04TfExIdDZWq15mh%2BdG0VvBh%2BfaxH5L3ffY4AY%2F0yjjtLZ%2FwdJjBCsT%2Bwd2MUYiFgEAAA%3D%3D

**Comment by kdy1** [comment]
@jiby-aurum It seems like `Publish crates` action in publish pipeline has a bug. 

1.7.26 fixes it.
https://play.swc.rs/?version=1.7.26-nightly-20240911.1&code=H4sIAAAAAAAAAzMytLS0NDE1MjUxMrM0NdHTK8kPLinKzEvX0AQAWdlafxsAAAA%3D&config=H4sIAAAAAAAAA1WPMQ7DIAxFd06BPHeoGDr0Dj0Eok5EBQFhRyqKcvcCgbbZ8Pv%2F8%2B1NSAkvMnCXW3mWIepEmL5zIZQX1u9CgHNEMslGhstQmao0aUfY0H4owDrNyDWFpK5K9QS4EAhHojNvFzvl%2F04TfExIdDZWq15mh%2BdG0VvBh%2BfaxH5L3ffY4AY%2F0yjjtLZ%2FwdJjBCsT%2Bwd2MUYiFgEAAA%3D%3D
