### ISSUE TITLE
Paths are not transformed in dts files

### ISSUE THREAD

**Issue by kishieel** [swc-project/swc#9548]
### Describe the bug

I am using the "paths" option in "jsc". The paths are correctly rewritten in the output *.js files, but remain untouched in the *.d.ts files. I would expect them to be rewritten the same way in both types of files.

### Input code

```typescript
export * from "@lib/example";
```

### Config

```json
{
    "$schema": "https://swc.rs/schema.json",
    "sourceMaps": true,
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "decorators": true,
        "dynamicImport": true,
        "dts": true
      },
      "target": "es5",
      "baseUrl": "./",
      "preserveAllComments": false,
      "experimental": {
        "emitIsolatedDts": true
      },
      "paths": {
        "@lib/*": ["src/*"],
        "@tests/*": ["tests/*"]
      }
    },
    "module": {
        "type": "commonjs",
        "strict": true,
        "strictMode": true,
        "lazy": false,
        "noInterop": false
    },
    "minify": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.24&code=H4sIAAAAAAAAA0utKMgvKlHQUkgrys9VUHfIyUzST61IzC3ISVW3BgCTcYWLHQAAAA%3D%3D&config=H4sIAAAAAAAAA21RsXLCMAzd%2BQrO16nXI1MXJnrtwsDYqcdgHNGYsy2fpLSkHP9eOwlpUuJJfk960pMui2V66oFNBV6r9VJVIpHXRcHfZkVcdMTqxBjUU5fMWJOBnY6c8oVq6PETmwRc2k%2F6Rk0MNEJyaRNEn3MbaSKwIRull235EgySFqSpdMc1QXtrtj4iyQwtMzXCudlRO4YevN5YJZo%2BIQsp4OdhCHXQDO%2FkMr4q%2FuBIkNx8wYtzr%2Bg9hLZdqzzkwDkC2cxpN%2FUN3sqW0WmB8m0Y9G6kqKXiaeXG2UPxmLAPxWRStB%2FZ2wiwcE%2Ff4v2drENkmOyh55THsnYw7Zgvk92bZBPDicf3YSFrZpbf4Tss4Z5z%2Bqf5v6oEB9wGAcI4P5gN9jiULa6%2Ft7hwB6gCAAA%3D&strip-types=

### SWC Info output

    Operating System:
        Platform: linux
        Arch: x64
        Machine Type: x86_64

    Binaries:
        Node: 18.17.0
        npm: 9.6.7
        Yarn: 1.22.22
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.7.26
        @swc/helpers: N/A
        @swc/types: 0.1.12
        typescript: 5.6.2

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

main.d.ts looks like:

```typescript
export * from "./src/example";
```

### Actual behavior

main.d.ts looks like:

```typescript
export * from "@lib/example";
```

### Version

@swc/cli: 0.4.0 @swc/core: 1.7.26

**Comment by robpalme** [comment]
TypeScript does not do specifier rewriting today, so this feature would be SWC-specific behavior.

**Comment by CPunisher** [comment]
swc emit type declarations before do transformation. https://github.com/swc-project/swc/blob/185d6f55b35f4f8323035c1199cddb9dd547f254/crates/swc/src/lib.rs#L975

@kdy1  So shoud we disable the rewriting (may be breaking change) or do an isolated rewriting ahead of time?

**Comment by kdy1** [comment]
I think we should apply `path_rewriter` (or similar name, but in `swc_ecma_transforms_module`) to the cloned dts module
