### ISSUE TITLE
`resolveFully` don't use `--out-file-extension` value

### ISSUE THREAD

**Issue by weslenng** [swc-project/swc#9549]
### Describe the bug

If you use `resolveFully: true` with e.g. `--out-file-extension mjs` CLI option, the compiled code will try to import relative files using a fixed `*.js` extension causing a `ERR_MODULE_NOT_FOUND` error

### Config

```json
{
  "$schema": "https://swc.rs/schema.json",
  "jsc": {
    "baseUrl": ".",
    "parser": {
      "dynamicImport": true,
      "syntax": "typescript"
    },
    "target": "es2022"
  },
  "module": {
    "noInterop": true,
    "resolveFully": true,
    "strictMode": true,
    "type": "es6"
  },
  "sourceMaps": true
}
```

### Playground link (or link to the minimal reproduction)

https://github.com/savi2w/swc-repro-1

### Expected behavior

I think the compiled code should use the provided value of `--out-file-extension` CLI option to import relative files

### Version

^0.4.0

**Comment by kdy1** [comment]
Yeah I think so but currently the value of `--out-file-extension` is not passed to `@swc/core`
