### ISSUE TITLE
bug: swc not allowing tsconfig paths with values containing >1 array element

### ISSUE THREAD

**Issue by fedenusy** [swc-project/swc#9554]
tsconfig paths values with >1 array element are valid, regardless of whether or not the key has a trailing *

the bug is that swc errors out when it sees this

### Discussed in https://github.com/swc-project/swc/discussions/8396

<div type='discussions-op-text'>

<sup>Originally posted by **obzva** December  7, 2023</sup>
# TLDR
What does "value of `paths.{}` should be an array with one element because the src path does not contains * (wildcard)" mean and why should it be?
***
Hi I'm working on old Next.js project and I recently upgraded it to v13.
I ran some jest test on my project and met some of this fail log like below.
```
  ● Test suite failed to run

    failed to process assertion failed: `(left == right)`
      left: `2`,
     right: `1`: value of `paths.@components` should be an array with one element because the src path does not contains * (wildcard)

      at Object.transformSync (node_modules/next/src/build/swc/index.ts:1000:25)
      at transformSync (node_modules/next/src/build/swc/index.ts:1181:19)
      at Object.process (node_modules/next/src/build/swc/jest-transformer.ts:117:25)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
```
This failure is not from the test code itself because my code looks like below.
```
describe('Test', () => {
  it('this should pass', () => {
    const a = 1;
    expect(a).toBe(1);
  });
});
```
So I checked the tsconfig.json file and amended some.
```
from
      "@components/*": ["components/*"],
      "@components": ["components"],

to
      "@components/*": ["src/components/*", "components/*"],
      "@components": ["src/components", "components"],
```
And it worked well!

I wanted to know the detail of this failure and rules of path aliasing, so I digged typescript docs but actually I found that it is on SWC.
I couldn't understand what is the message and by typescript docs, even if the first path is invalid, the second one will be the fallback so I thought it is OK.</div>

**Comment by kdy1** [comment]
Please use the issue template
