### ISSUE TITLE
Bug: new.target is not transpiled for ios

### ISSUE THREAD

**Issue by kholstinin** [swc-project/swc#9589]
### Describe the bug

When you specify iOS 10.3 `new.target` doesn't get properly transpiled: instead it stays the same `new.target`, which is not supported on that platform.

### Input code

```typescript
function a() {
  const b = new.target;
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.28&code=H4sIAAAAAAAAA0srzUsuyczPU0jU0FSo5lJQSM7PKy5RSFKwVchLLdcrSSxKTy2x5qrlAgBCMqA1KQAAAA%3D%3D&config=H4sIAAAAAAAAA22QTYrDMAyF9zmF0bqUGQa6KHRuMKs5gXCV4hL%2FIMmloeTu4zhxm8JsjPW9p2dLj84YuIqFo3mUaykSshA%2F60JkDIr3QoCsR7HsksKuqVeZpR4HoYqmRYEhRqGmrMy74Ppxm22jT0wi78bZiuEy0L%2FJyhikj%2By3QUxodQMKcj5F1t%2BY2c5BEJI%2FLrbdy8Q5qPNVx6zRozoLqzx17axPg4%2FnXP%2B0rkrHVBtJDvAytRmf84CTn9apnBdG4bYJQr6QzksAF8V8n8znx%2F6rZnbTH67cPM%2BjAQAA

### Expected behavior

`new.target` transpiled

### Actual behavior

`new.target` not transpiled

### Version

1.7.28

### Additional context

https://caniuse.com/?search=new.target

**Comment by Austaras** [comment]
SWC doesn't tranpile `new.target` because we copy compat data from [babel](https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugins.json#L719). I don't have the device to test if real iOS Safari behaviour matches that file.

**Comment by kdy1** [comment]
`babel` behaves identically.
https://babeljs.io/repl#?browsers=ios%20%3E%3D%2010.3&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAQwBQEpEG8BQjEQIDOUiARogLyJgCmA7gHRTIBOA5rVANw4C-OIA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=Node-8&version=7.25.8&externalPlugins=&assumptions=%7B%7D
