### ISSUE TITLE
Property decorator break class inherent behavior

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#960]
```ts
class Base {
  constructor() {
    this.action = new Subject()
  }
}

class Child extends Base {
  @DefineAction() action: Observable<void>
 
  callApi() {
    console.log(this.action) // undefined
  }
}
```

Seems caused by `defineProperty` in constructor in Child Class

**Comment by kdy1** [comment]
How should this be hsndled? 
Does babel works for the case?

**Comment by Brooooooklyn** [comment]
TypeScript works fine，action should be Subject here

**Comment by Brooooooklyn** [comment]
https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEQKbBmVBBa8wAUAlIgN6IBOqUIFSoksCBA+gIYA0iLARlxCXJUadRBEQBfSQChpEADZsAzksQAhZajLTEYhEqgUQ0OBWLbduqAAsYSgHRs8CRAF5EARh0yJshctUAYVt5ABNEVAAPKFQwUNUNJS1SbwABNAwsXCZCEiccgC5EMBAAWx5UCh1vCDZ5eWwABxhzFMs9MCU4eVR7eTgAcwIbO0dnMBIAeknEcFD0TFRQ719fOX0oMTdi1AB3RGCYMOI-e1r6ppaiIA

Click run and output **1** in Logs tab

**Comment by kdy1** [comment]
Thanks for the example!
