### ISSUE TITLE
`swc-linux-arm64-gnu` is not included in the GitHub releases after `v1.7.14`.

### ISSUE THREAD

**Issue by pan93412** [swc-project/swc#9609]
### Describe the bug

The filename is `swc-linux-arm64-gnu`. 

It was present not after version `v1.7.14`: https://github.com/swc-project/swc/releases/tag/v1.7.14. It has now disappeared. I suspect there was a change in the CI, but I cannot find the code that introduced this issue. 

Discord discussion: https://discord.com/channels/889779439272075314/889785438938726441/1290999698328649738.

### Playground link (or link to the minimal reproduction)

N/A

### Expected behavior

I can download `gnu` target for `linux-arm64` from GitHub Releases.

### Version

v1.7.30

**Comment by kdy1** [comment]
Diff: https://github.com/swc-project/swc/compare/v1.7.12...v1.7.14
