### ISSUE TITLE
Mixed commonjs and esm module code could not be transformed right

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#962]
Code from `lodash-es/isBuffer`

```js
import root from './_root.js';
import stubFalse from './stubFalse.js';
  
var freeExports = typeof exports == 'object' && exports && !exports.nodeType && exports;
var freeModule = freeExports && typeof module == 'object' && module && !module.nodeType && \
   module;
  
var moduleExports = freeModule && freeModule.exports === freeExports;
  
var Buffer = moduleExports ? root.Buffer : undefined;
  
var nativeIsBuffer = Buffer ? Buffer.isBuffer : undefined;
  
var isBuffer = nativeIsBuffer || stubFalse;
  
export default isBuffer
```

Output:

```js
Object.defineProperty(exports1, "__esModule", {
    value: true
});
exports1.default = void 0;
var _rootJs = _interopRequireDefault(require("./_root.js"));
var _stubFalseJs = _interopRequireDefault(require("./stubFalse.js"));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
var freeExports = typeof exports == 'object' && exports && !exports.nodeType && exports;
var freeModule = freeExports && typeof module == 'object' && module && !module.nodeType && module;
var moduleExports = freeModule && freeModule.exports === freeExports;
var Buffer = moduleExports ? _rootJs.default.Buffer : undefined;
var nativeIsBuffer = Buffer ? Buffer.isBuffer : undefined;
var isBuffer = nativeIsBuffer || _stubFalseJs.default;
var _default = isBuffer;
exports1.default = _default;
```

[Babel repl](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBFCF4DNEjgcgHQHoD6iy2AVgM6YDcAUKJLHGTAK4BGAYgIYA2ZApnDQQMOXEzZdefUhRrUAbpyiCofPgFEAHvRhk4AXjgwAnmD4QUcPtui6DhzBFYk-AYxiY4AMi9WbsPR84AEJrHTJsADsIABM-ABVTASCw2zIaRWU0NQBZWOZuAUNsjX87IJMzCzgQfML7LCcXd08g2piC5N9g9s6o2ISk719qODHewrlMmrrS8IMVXNnhxb48jsLsVID7YtU5tKmlOAAhZhQUPmVDCYOdgH4EJBhsM4uruAAuOGZIuJRgJE-DEjspIpwYMB5HwAJJkN6Xa6nc6IuCPBFXbDAeEoj7fX7_QHA0FwbEYpHgyHQuHkuAAHzpjBYHB4_Dk23g_04BXgZNxUGoQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-3%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.10.4)

[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBFCF4DNEjgcgHQHoD6iy2AVgM6YDcAUKJLHGTAK4BGAYgIYA2ZApnDQQMOXEzZdefUhRpw41AG6cogqHz4BRAB70YZOAF44MAJ5g+EFHD67o+o8cwRWJPgGMYmOADIfNu1gDPzgAQls9MmwAOwgAEz4AFXMBEIj7MhplVTQNAFl45m4BY1ytQIcQswsrOBBC4scsFzdPbxD6uKLU-1DO7pj4pJTffwAdank6hr45BWzpruKdSKM1fJnR9b4Cpel0oMdS9XLIuaUVOAAhZhQUPlVjfuWKgwB+BCQYbBu7h7gAFxwZjRBIoYDRPhxc4LaKcGDARR8ACSZF+90e11uGLgH3RD2wwDR2P+QJBYIhUJhlyJ+MxcIRSNRdLgAB9WYwWBwePxzgd4GDOEV4LSSVAgA)

**Comment by kdy1** [comment]
I'll modify code to allow using exports as a *reference*.
I mean, I'll rename function / var / class named `exports` while preserving reference.

**Comment by Brooooooklyn** [comment]
`Babel` only rename the `var` named `exports`, and report error when `class/function` named exports: `Identifier 'exports' has already been declared`

`TypeScript` does nothing with `var/function/class` named exports, just preserved it.
