### ISSUE TITLE
Legacy decorators with ESNext target breaks with `@swc/core@1.7.35`

### ISSUE THREAD

**Issue by thetutlage** [swc-project/swc#9640]
### Describe the bug

Up until `@swc/core@1.7.26` using target as `esnext` with `legacyDecorator` was working fine. However, now the compiled code results in `SyntaxError: Invalid or unexpected token`.

### Input code

```typescript
function computed() {
  return function (target) {
    console.log(target)
  }
}

class User {
  @computed()
  get fullName() {
    return 'foo'
  }
}
```

### Config

```json
{
  "$schema": "https://swc.rs/schema.json",
  "module": {
    "type": "es6"
  },
  "jsc": {
    "target": "esnext",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "importAssertions": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true,
      "useDefineForClassFields": true
    },
    "keepClassNames": true,
    "experimental": {
      "keepImportAttributes": true,
      "emitAssertForImportAttributes": false
    }
  },
  "minify": false
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.35&code=H4sIAAAAAAAAA0WNMQ6AIAxFd07RTVw8gydw8wAECzGp1ECZjHe3EYlj%2F3t5DTV52TmB5%2BOsgpsd4TIAGaXmBKFjKy5HlAZB7VSYcCKOneh%2Bm9sYT64UWAvm153%2FsF4qapNocQfaHvt%2BDYF5aJUHwlorwJYAAAA%3D&config=H4sIAAAAAAAAA22RzU7DQAyE7zxFtOKImhuH3hBVJQ70HczGabfsn2xHJKry7ji%2FCqVHe76d8WhvT0VhntleMIDZF%2BYiknlflvxjd8TlJOyunKJ5GdCQqsajkjeddJYuD5NBfjW66UfoynZDAJ1RJiZiK6OP7jMQI62cbriLAu1ADq5syeWFVrVCmwgkESsh1OCquJATyRurnbgUF32U%2BzlNCCLXicI20OMZbHdYjO9918RPFKhA4B5oGA9Yu4jHRO8emI8OffUw%2Fxsxj8gJAv5tYLDNSC6gtvfb84Y3H1M3EXJfjeC%2F7hjc3FxveADX4Hm%2BZP2e4KKru1XsfwH3myXFBAIAAA%3D%3D

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:31 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6030
        CPU: (11 cores)
            Models: Apple M3 Pro

    Binaries:
        Node: 22.5.1
        npm: 10.8.2
        Yarn: 4.5.0
        pnpm: 9.6.0

    Relevant Packages:
        @swc/core: 1.7.35
        @swc/helpers: N/A
        @swc/types: 0.1.13

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The compiled output should be valid and should not break. Same as version `1.7.26`.

### Actual behavior

Throws a runtime fatal error `SyntaxError: Invalid or unexpected token`

### Version

1.7.35

**Comment by kdy1** [comment]
It’s expected. Do not use esnext

**Comment by thetutlage** [comment]
How was it working with the last version of swc and how come there is no mention of it in the release notes?

**Comment by kdy1** [comment]
I'll match the behavior of tsc.

Reopening as tsc handles decorators on esnext target

**Comment by thetutlage** [comment]
Thanks for re-opening the issue. I expected it work because of `legacyDecorators` flag. Looking forward for the fix 🙂

**Comment by dlabrecq** [comment]
I'm not using `legacyDecorators`, but encountering multiple ` TypeError: Cannot set properties of undefined` errors with `@swc/core@v1.7.35`. Specifically related to `Enums` and `Interfaces`. Everything has been working with `@swc/core@1.7.26` and earlier.

The `transform` from my jest.config.js file:
![Screenshot 2024-10-14 at 10 19 02 PM](https://github.com/user-attachments/assets/d8cbf5b6-f39a-4937-b027-a02dd07fd21d)

Example of Enum type errors:
![Screenshot 2024-10-14 at 10 18 37 PM](https://github.com/user-attachments/assets/e60e12c2-ced2-4022-98a1-413e7e77a09f)

**Comment by thetutlage** [comment]
Thanks for the fix. I can confirm its working fine :)
