### ISSUE TITLE
@swc/jest TypeError with @swc/core@1.7.36

### ISSUE THREAD

**Issue by dlabrecq** [swc-project/swc#9651]
### Describe the bug

I'm encountering `TypeError: Cannot set properties of undefined` errors with `@swc/core@v1.7.36` and `@swc/core@v1.7.35`. My jest tests have been working with `@swc/core@1.7.26` and earlier.

### Input code

```typescript
export const enum TagType {
  tag = 'tag',
}
```

### Config

```json
// jest.config.js

const transformIgnorePatterns = [
  'node_modules/(?!(@patternfly/react-core/src|@patternfly/react-icons/dist/esm|uuid/dist/esm-browser))',
];

/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  clearMocks: true,
  collectCoverage: false,
  // collectCoverageFrom: ['src/**/*.js'],
  // coverageDirectory: './coverage/',
  fakeTimers: {
    enableGlobally: true,
  },
  moduleDirectories: ['node_modules', '<rootDir>/src'],
  moduleNameMapper: {
    '\\.(css|scss)$': 'identity-obj-proxy',
  },
  preset: 'ts-jest',
  roots: ['<rootDir>/src/'],
  setupFiles: ['<rootDir>/test/testEnv.ts'],
  setupFilesAfterEnv: ['<rootDir>/test/jest.setup.js'],
  testEnvironment: 'jsdom',
  // testEnvironment: 'jest-environment-jsdom',
  transformIgnorePatterns,
  transform: {
    '^.+\\.svg$': 'jest-transform-stub',
    '^.+\\.(ts|js)x?$': [
      '@swc/jest',
      {
        $schema: 'http://json.schemastore.org/swcrc',
        jsc: {
          experimental: {
            plugins: [['swc_mut_cjs_exports', {}]],
          },
          parser: {
            jsx: true,
            syntax: 'typescript',
            tsx: true,
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      },
    ],
  },
};
```

### Playground link (or link to the minimal reproduction)

https://github.com/dlabrecq/swc-test-case

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Pro

    Binaries:
        Node: 20.17.0
        npm: 10.9.0
        Yarn: 1.22.22
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.7.36
        @swc/helpers: N/A
        @swc/types: 0.1.13
        typescript: 5.6.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The jest tests should not break. Same as version 1.7.26.

### Actual behavior

Throws a runtime `TypeError: Cannot set properties of undefined` error

### Version

1.7.36

### Additional context

Example of breakage

![Screenshot 2024-10-16 at 9 08 20 AM](https://github.com/user-attachments/assets/70885622-4d26-4ecd-8b85-3053ddd77149)

**Comment by magic-akari** [comment]
Investigation:

[SWC Playground](https://play.swc.rs/?version=1.7.36&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIzSvNVQhJTA%2BpLEhVqOZSUChJTFewVVAHUuo6XLUAXiLZ9SwAAAA%3D&config=H4sIAAAAAAAAA1VPSQ7CMAy85xWRzxwACQ78gUdEwa2Csil2JaKqfydpk0Jv9iye8SykhDdpeMi5jGWJKhGmfS8IZc%2FqUxDgHJF0MpHh1FmmSg3KEq7QsjHAKo3I1YV0PV9uzQE2BMLuaJgz3gz5P1MHFxMSHYVVqvxo8ZgoWiq48JpWsv1S%2B24N7vAT9bD9MBh6dienCcXyBbnuEC8XAQAA)


```TypeScript
export const enum TagType {
  tag = 'tag',
}
```

The input code, after being processed by SWC's TypeScript pass, has become as follows:

```JavaScript
export var TagType = /*#__PURE__*/ function(TagType) {
    TagType["tag"] = "tag";
    return TagType;
}({});
```

No issue there, but after the `swc_mut_cjs_exports` pass, it transforms into:

```JavaScript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "TagType", {
    enumerable: true,
    get () {
        return TagType;
    },
    set (v) {
        TagType = v;
    },
    configurable: true
});
var TagType = /*#__PURE__*/ function(TagType) {
    exports.TagType["tag"] = "tag";
    return exports.TagType;
}({});
```

The problem is that `TagType` was misidentified. Within the `TagType` enum function, `TagType` is prefixed with `exports`.
It should be private.

**Comment by magic-akari** [comment]
@dlabrecq Please try swc_mut_cjs_exports@0.109.1
