### ISSUE TITLE
Typescript 'Namespace' not works

### ISSUE THREAD

**Issue by HealGaren** [swc-project/swc#966]
**Describe the bug**
If I write code using the `namespace` spec in typescript, it is removed after transpiling.

[handbook document link](https://www.typescriptlang.org/docs/handbook/namespaces.html)

Namespace should be able to have `export function` or `export const variable`, and etc..
And it can have runtime behavior.

**Input code**
```ts
namespace A {
    export function test() {
        console.log('test');
    }
}

A.test();
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    }
  }
}
```

**Expected behavior**

Output of the same code compiled with tsc: [typescript playground](https://www.typescriptlang.org/play?target=0#code/HYQwtgpgzgDiDGEAEBBJBvAUEnSIA8YB7AJwBckAzAV2HjIEsjgkzoyAKASg213-jMoRADYQAdCKIBzDgHI2UMgEI5XANx8cAX0y7MKcYs4agA)
```js
"use strict";
var A;
(function (A) {
    function test() {
        console.log('test!');
    }
    A.test = test;
})(A || (A = {}));
A.test();
```

and swc:
```js
A.test();
```

**Version**
The version of @swc/core: `1.2.19`

**Additional context**

**Comment by HealGaren** [comment]
Isn't this a bug? Or is this spec not going to be implemented soon?

I'm looking forward to applying this awesome library to my project.

**Comment by kdy1** [comment]
It a feature which can't be supported by swc, but can be by spack.
However, I'm not sure if I have to implement this, mainly because modules are preferred over namespaces.

Side note: Implementation will be easy

**Comment by HealGaren** [comment]
Thank you for your answer 👍 

May I ask why swc can't support this?

In my opinion, swc is a typescript compiler,
so I think it should support the syntax supported by typescript as much as possible...

Is it a design issue of swc? Or doesn't it fit the purpose of swc?

**Comment by kdy1** [comment]
swc (and babel) works by file-by-file manner and namespace support (and const enums) requires reading multiple files. 

Hmm... I noticed that it can supported if swc accepts a list of files or directory names.
But I'm not sure about it because namespace is not recommended.

There is a lint about it. https://palantir.github.io/tslint/rules/no-namespace/

**Comment by HealGaren** [comment]
I don't think all use of namespaces is discouraged.
Most namespaces used for module purposes can be replaced with es module.

But like Java's inner class,
When designing code using namespaces, it is good to specify the contextual meaning.
[example comment](https://github.com/babel/babel/issues/8244#issuecomment-483914539)


The namespace is not deprecated.

It's also because typescript doesn't want to remove the existing spec,
Looking at the related [babel](https://github.com/babel/babel/issues/8244) and [typescript](https://github.com/microsoft/TypeScript/issues/30994) discussions, I think there is a good reason that es module cannot replace.
it is necessary to apply selectively if possible.
