### ISSUE TITLE
_ts_dispose_resources is not correctly invoked for `using` keyword

### ISSUE THREAD

**Issue by jtbandes** [swc-project/swc#9673]
### Describe the bug

The `Symbol.dispose` function is not invoked when using the `using` keyword.

The output includes
```js
finally{
    _ts_dispose_resources(env);
}
```

However, this function is defined as
```js
function _ts_dispose_resources(SuppressedError1) {
    return function(env) {
        // ...
    };
}
```

So calling `_ts_dispose_resources(env);` does not actually invoke the dispose logic.

The function does seem to be invoked here, so something else must be going wrong: https://github.com/swc-project/swc/blob/8f45eaf837d023847c478e562265e141213ce231/crates/swc_ecma_transforms_base/src/helpers/_ts_dispose_resources.js#L32

### Input code

```typescript
using x = {
  [Symbol.dispose]() {
    console.log("disposed")
  }
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "explicitResourceManagement":true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.39&code=H4sIAAAAAAAAAystzsxLV6hQsFWo5lJQiA6uzE3Kz9FLySwuyC9OjdXQBAsrKCTn5xXn56Tq5eSnayhBZVOUNIFytVy11gBoxdWzRQAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw6DMAzdOQXyzFAx9g4svYGVGhSUn2IjgRB3bxIgbbe8f7w3bQszK3i2e3omEDAyxYoTw5sTXBMDpCyyijoIdLc6c5ZGNEwd0BqMVlpexH6JigZ0OJElJ%2FCUuFAJHWcWBONEUnq5f%2FT91QnGe6baeXJWOz1uv79S3oZIzP%2FGbEU3mZo%2FF5trFax%2FL0W8rpUtZJTbrHczw9d5L9Z20Dzc8XLM8QEIU%2BriPgEAAA%3D%3D

### Expected behavior

`console.log("disposed")` should run

### Actual behavior

No log message

### Version

1.7.39

### Additional context

See also https://github.com/swc-project/swc/issues/9576

**Comment by kdy1** [comment]
# Investigation:

`helpers/Marker` (`resolver` for injected inline helpers) seems to be the cause. https://github.com/swc-project/swc/blob/70fcbc4a76aac06ae90a1ebbf2daa6c7f6659e6e/crates/swc_ecma_transforms_base/src/helpers/mod.rs#L549-L630
