### ISSUE TITLE
Miscompilation of TypeScript classes with uninitialized member

### ISSUE THREAD

**Issue by magcius** [swc-project/swc#9679]
### Describe the bug

There's a mismatch of TypeScript compilation between tsc and swc involving uninitialized members that can be seen in the provided script.

### Input code

```typescript
class Foo {
    constructor() { this.setup(); }
    protected void setup(): void {}
}

class Bar extends Foo {
    public two: number;
    protected override setup(): void { this.two = 2; }
}

console.log(new Bar().two);
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "decorators": true,
        },
        "externalHelpers": true
    },
    "env": {
        "targets": "last 2 Chrome versions"
    }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.39&code=H4sIAAAAAAAAA12OsQ6DMBBDdyT%2BwWOyMHQEdenQ%2F4Dk1EZKcyi5QCXUf29oWMrpNtvPbhvjx5RwZ8bWNihnOCSJ2QhHpbFBni51iSTPSg%2F4VNMcWcgIWRxKj4WdxVb08u2BvY0R9BYK9q9izpN3BrJyj5BfE8XhjOWFYnSWzvw6pyRxxeU3p9aV0eyp8%2FxQgda9WOndpgv5CzudVfvlAAAA&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D

### Expected behavior

The equivalent code in tsc omits the variable declaration entirely.

https://www.typescriptlang.org/play/?#code/FAYwNghgzlAEBiB7RsDexadiRA7KALgE4CuIBiRAFAJRqwEAWAllAHRQCmBJADrQG5YAXwxZeRRAU7lOAE1hce-GgC5YAN0TMFqUaNCQYsAEIQisTgA9puOXCQp0WWLxIAjMMxAMA7onVcEgBbd04iATFMCSkZaQVEDXCiHU5Fbj5adS0deiZWNgJ-WABeWAAmIX1gUDwoRDBONjBEAHMqXE5fU3NaQv8aSKA

### Actual behavior

The issue is subtle, but the addition of the `two` here initializes the variable after setup's constructor has been called in Foo, causing it to not be properly set.

### Version

@swc/core@1.7.39

**Comment by magic-akari** [comment]
https://swc.rs/docs/migrating-from-tsc#usedefineforclassfields

Please declare `useDefineForClassFields` in both TypeScript and SWC, and you will see consistent results.

[SWC with useDefineForClassFields: true](https://play.swc.rs/?version=1.7.39&code=H4sIAAAAAAAAA12OsQ6DMBBDdyT%2BwWOyMHQEdenQ%2F4Dk1EZKcyi5QCXUf29oWMrpNtvPbhvjx5RwZ8bWNihnOCSJ2QhHpbFBni51iSTPSg%2F4VNMcWcgIWRxKj4WdxVb08u2BvY0R9BYK9q9izpN3BrJyj5BfE8XhjOWFYnSWzvw6pyRxxeU3p9aV0eyp8%2FxQgda9WOndpgv5CzudVfvlAAAA&config=H4sIAAAAAAAAA21QOw6DMAzdOQXy3KFi6NC1FVsPEYGDUuUnO0hFiLuTQEKp1M1%2BP3%2Fmqq7hzR3c6zmWsfGCGOnoI8KTDeITEQiTR%2B5I%2BQCXwgZOlBSacYOWnYEgaMCQXMjNtWmyA7RzjMWRMaOsktN5ZueMJ2T%2BFSapsIPG%2FxNJWJaOzDloZHyiVBZbRw8tmFuFuk%2B5gcbsr3IGGNePW3j%2BRbp3v%2BAGX1FZ9lgMFL%2BKc0tdVgsCQtpXAQAA)
[tsc with useDefineForClassFields: true](https://www.typescriptlang.org/play/?useDefineForClassFields=true#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoALrpLAFADGJZoO2oAbzagRoDtjTRmkDozwAKAJSCmACxTQAdHEaQADkoDcoAL7DRe3NkaxZsaqB36lDAG7YUDgWbOdu0UAAhYlxQWAAPGzRaXmx+IVFQPUgAI0IUDiYAd2wGNEgAWxTYXENzEUtrWxsHbFcS3E9YR1hdA0U3Dy81DU1GHNAAXlAAJmMfNk4JaGxCWE1CbABzeQwsoJClPpzFMqA)

[SWC with useDefineForClassFields: false](https://play.swc.rs/?version=1.7.39&code=H4sIAAAAAAAAA12OsQ6DMBBDdyT%2BwWOyMHQEdenQ%2F4Dk1EZKcyi5QCXUf29oWMrpNtvPbhvjx5RwZ8bWNihnOCSJ2QhHpbFBni51iSTPSg%2F4VNMcWcgIWRxKj4WdxVb08u2BvY0R9BYK9q9izpN3BrJyj5BfE8XhjOWFYnSWzvw6pyRxxeU3p9aV0eyp8%2FxQgda9WOndpgv5CzudVfvlAAAA&config=H4sIAAAAAAAAA21QOw6DMAzdOQXy3KFi6NC1FVsPEYGDUuUnO0hFiLs3gYSC1M1%2BP3%2Fmqq7hzR3c6zmWsfGCGGnvI8KTDeITEQiTR%2B5I%2BQCXwgZOlBSacYWWjYEgaMCQXMjNtWmyA7RzjMWRMaOsktNxZueMJ2Q%2BC5NU2EHj%2F4kkLEtH5hg0Mj5RKouto4cWzK1C3fM5oMohYFw%2Frun5Geng7YQb%2FERl230zUPwqzkAjVssXqld1UVgBAAA%3D)
[tsc with useDefineForClassFields: false](https://www.typescriptlang.org/play/?&useDefineForClassFields=true#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoSxhcAUAMYlmg7agDerUMNDtsaaABdckdpLwAKAJQDQkgBYpoAOjiTIAB2UBuUAF8hIg7myTYc2NVB7DyhgDdsKJ-wsWOXNCgAELEuKCwAB52aLQ82HyCIqAGkABGhCjsagDu2AxokAC2abC4xpbC1rb2dk7Y7mW43rDOsPpGSh5ePmqaOpJ5oAC8oABMpn6sHOLQ2ISw2oTYAOYKGDkhYcrag9hKFUA)
