### ISSUE TITLE
In tsx with generic, delete<T> or new<T> method makes "Unexpected token Some(JSXTagStart)" Error

### ISSUE THREAD

**Issue by HealGaren** [swc-project/swc#968]
**Describe the bug**
I have written code that uses generics, but swc seems to recognize it as a jsx tag.

**Input code**
```tsx
class A {
  delete<T>() {}
}
```
or
```tsx
class A {
  new<T>() {}
}
```

**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

**Expected behavior**
expected successful compilation like babel or ts-loader
[babel example](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1oBMCmIMBcMB4AVAPgAoBKRFVGgJ1wFdaA7aU_NASwDcB6Y8tQC-SIUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=)

But it makes that error:
```
error: Unexpected token Some(JSXTagStart)
 --> index.ts:2:9
  |
2 |   delete<T>() {}
  |         ^

[Error: failed to process js file

Caused by:
    failed to parse module]
```

**Version**
The version of @swc/core: `1.2.19`

**Additional context**

**Comment by Amareis** [comment]
Yep, really strange behavior - even in .ts files.

**Comment by daflyinbed** [comment]
this problem seems to have been fixed. 

ps: I failed to reproduce #2099 ,that may be another problem

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/swc-project/swc/pull/2076
