### ISSUE TITLE
Using JSX syntax in a namespace may incorrectly use the exported members of the current namespace as intrinsic elements

### ISSUE THREAD

**Issue by codehz** [swc-project/swc#9685]
### Describe the bug

use jsx syntax in namespace will incorrectly use exported members of the current namespace instead of intrinsic elements

### Input code

```typescript
export namespace form {
  export const input = null;
  export const test = <input />
}
```

### Config

```json
none
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.7.40&code=H4sIAAAAAAAAA0utKMgvKlHIS8xNLS5ITE5VSMsvylWo5lJQSIXIJOfnFZcoZOYVlJYo2CrklebkWKNLlqQWg%2BRsIIr07bhqAe8HVbtWAAAA&config=H4sIAAAAAAAAA1WPSw7CMAxE9z1F5DVbWHAHDhEFtwrKT7ErEVW9O%2FkDu%2FjNTMY%2BFiHgRQru4sjPPAQZCeOcM6HkWL4zAU4BSUUdGC5DZSoSxx0rOZsALOOGXEJI1%2B4G4z1hZqs0hJ1Z7fSafvuUtyEi0b%2BxWKXbzMy3uqVXgvXPvYr9jrJrq7%2FB1zTK5seg6TGS9YjzA2yuiPwTAQAA

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112
        CPU: (8 cores)
            Models: Apple M2

    Binaries:
        Node: 22.10.0
        npm: 10.9.0
        Yarn: 1.22.22
        pnpm: 9.12.2

    Relevant Packages:
        @swc/core: 1.7.40
        @swc/helpers: N/A
        @swc/types: 0.1.13
        typescript: 5.6.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

```js
(function(form) {
    form.input = null;
    form.test = /*#__PURE__*/ React.createElement("input", null);
})(form || (form = {}));
export var form;
```

### Actual behavior

generated code:
```js
(function(form) {
    form.input = null;
    form.test = /*#__PURE__*/ React.createElement(form.input, null);
})(form || (form = {}));
export var form;
```

### Version

\>=1.4 (tested in 1.4.0, 1.7.40)

### Additional context

it works in version 1.3.107 and below.

And this bug can be replicated in tsc with jsx: preserve mode (but not in react/react-jsx mode)
https://github.com/microsoft/TypeScript/issues/60365

**Comment by magic-akari** [comment]
[SWC AST Viewer](https://swc-ast.vercel.app/#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDgM2hTgG8AoOOUSWObCBdeASwTAFd4BeRdgGz4BuClXDR49RvBgZucADysO8APQA+MgF8gA)

The issue occurred in our TS resolver with the `input` reference labeled as context `#3`.
