### ISSUE TITLE
Question about emitter attribute

### ISSUE THREAD

**Issue by rowanoulton** [swc-project/swc#97]
Hi there,

This is a non-urgent question about the emitter attribute. I'm not too familiar with rust and I'm trying to understand what [this code block](https://github.com/swc-project/swc/blob/4ff6d4ed4abbdbebf92a75c64c2b0fc5b374de0f/ecmascript/codegen/macros/src/lib.rs#L83-L86) is doing, and why it's necessary:

```rust
#[allow(unreachable_code)]
{
    return Ok(());
}
```

Could you explain it to me?

Thank you for the interesting project. Very excited to see where it goes!

**Comment by kdy1** [comment]
`emit_*` methods returns `Result<(), !>`.
#[emiter] attribute injects 

```rust
#[allow(unreachable_code)]
{
    return Ok(());
}
```

to avoid writing `Ok(())` all the time (Actually once for each method)

**Comment by rowanoulton** [comment]
Got it. Thanks for the quick reply.
