### ISSUE TITLE
[Enhancement][dts]: align the tsc error format of `isolatedDeclaration` 

### ISSUE THREAD

**Issue by SoonIter** [swc-project/swc#9718]
## Summary

deno's implementation is earlier than tsc, so it has its own error format.

But presently, tsc has its standard error format, and users would use it with tsc `isolatedDeclaration: true` in `tsconfig.json` and wish they both have the same error diagnostic behavior

there is one case

### input

```typescript
import { useState } from 'react';
import './App.css';

function App() {
	return (
    	<div className="App"></div>
  	);
}

export default App;
```

### expected behavior

```
src/App.tsx(4,10): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
```

### actual behavior

output successfully

```typescript
import { useState } from 'react';
import './App.css';
declare function App(); // -> 'App' implicitly has an 'any' return type
export default App;
```

## Related links

https://github.com/swc-project/swc/issues/9715#issuecomment-2456761751_

https://github.com/web-infra-dev/rspack/pull/8097

**Comment by kdy1** [comment]
I think it may create too much maintenance burden. And I can't make the time to maintain isolated dts frequently, so please do what you want. I'll be able to help a bit or review PRs, though.
