### ISSUE TITLE
`@swc/wasm-typescript` allow alias path option

### ISSUE THREAD

**Issue by Ceres6** [swc-project/swc#9722]
### Describe the feature

It would be great to allow the paths parameter from regular `.swcrc` to be available in `@swc/wasm-typescript` so we could use it in Node.js

**Comment by kdy1** [comment]
@marco-ippolito Would it be useful for node.js?

**Comment by marco-ippolito** [comment]
Im not sure how this would be implemented without supporting a .swcrc (which we dont plan to support in node)

**Comment by Ceres6** [comment]
For some context, my idea is that people who have projects in typescript with path aliases don't have to migrate off them to be able to use them with `--experimental-transform-types`

**Comment by marco-ippolito** [comment]
But path aliases are defined in tsconfig, or .swcrc and we dont support either.

**Comment by Ceres6** [comment]
@marco-ippolito maybe we could use a flag or NODE_OPTIONS? I agree it might not make a lot of sense to accept all the .swcrc, but this is a feature widely used in TS that is unusable without it or an intermediate build step
