### ISSUE TITLE
_ts_add_disposable_resource seems to not be present in the latest @swc/helpers

### ISSUE THREAD

**Issue by onigoetz** [swc-project/swc#9728]
### Describe the bug

When using SWC I get `Can't resolve '@swc/helpers/_/_ts_add_disposable_resource'`

```
    "@swc/core": "1.9.1",
    "@swc/helpers": "0.5.13",
```

### Input code

```typescript
class TempFile implements Disposable {
  #path: string;
  constructor(path: string) {
    this.#path = path;
  }
  // other methods
  [Symbol.dispose]() {
    // Close the file and delete it.
    console.log("Disposing of", this.#path);
  }
}

export function usingDeclaration() {
  using file = new TempFile(".some_temp_file");

  console.log("Got file", file);
}
```

### Config

```json
{
  jsc: {
    parser: {
      syntax: 'typescript',
      tsx: true,
      decorators: true,
      usingDecl: true
    },
    experimental: { keepImportAssertions: true },
    externalHelpers: true
  },
  env: {
    targets: 'Edge >= 96, Safari >= 15, iOS >= 15, Chrome >= 96, and_chr >= 96, Firefox >= 94, > 1%, not dead, not op_mini all, chrome 71',
    mode: 'entry',
    coreJs: 3
  },
  sourceMaps: true,
  module: { type: 'es6' }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.9.1&code=H4sIAAAAAAAAA12QwWrDMAyG734KkV1SGO69o6eV7QHWWxnFdZTGYFvGVtjGyLtXdrZRdjBCv37p%2F7D1phQ4YkgvziO4kDwGjFzg4EqiYi6ifiuAh2R42kHh7OL1SQRLUZrZMuX%2BfrZpdgCeXNFtC%2FZQS11a5G23QDxhhoA80VBEOr19hQt5PbRMfO9%2Fj4j32Ysi1xDGSmjiAAN6ZIFl3UyVhDxqT9e%2BW7GFA2jsHu8oNmv%2BohR%2BJsoM4xwtO4owV%2FsBrTfZVOEnvclr6B4ifvz9Ut%2FpQgHPLP25zju5rf5xvBK3XWGoRRyLugFKsOizbQEAAA%3D%3D&config=H4sIAAAAAAAAA22PSw7CMAxE95wi8potLDgBGw4RBbcKyk%2B2K7WqeneSNCkgsYtn3mTs9aQUvNjATa35mYekiZGOOSu8BNFzVkCWhGzIJoFzd4WLNWjHWKVtd0A0jSglhXxpOLgYGTveNG%2BDHZbvQhN9ImT%2BBQuqw%2Bjwbx3OghS0u6NLSCUqNBWkAuDjc6rJdmW5ZN%2FtCh%2Bob3K0guVHT9b%2FtjeNDDPTMQEAAA%3D%3D

### Expected behavior

The generated output contains `import { _ as _ts_add_disposable_resource } from "@swc/helpers/_/_ts_add_disposable_resource";`
and that looks all good, but that file doesn't exist in the latest `@swc/helpers`

### Version

SWC 1.9.1, Helpers 0.5.13

**Comment by kdy1** [comment]
Should be fixed by https://github.com/swc-project/swc/commit/9dfa3f541d7452d07c0849918f599237d1489d32
