### ISSUE TITLE
Introduce ability to config `run_plugin_first` on plugin level

### ISSUE THREAD

**Issue by jzhan-canva** [swc-project/swc#9737]
### Describe the feature

Currently `run_plugin_first` is a global config that run all plugins before swc's internal transformation.
I'd like to have this feature on plugin level.
Currently, I'm building a plugin that transform typescript enum into something else, and it needs to inject some annotation comment.
Because it's taking the typescript enum as input, it must run before swc's ts transform.

However, the comment I injected are then stripped by swc.

**Comment by kwonoj** [comment]
Not sure if it's easily doable. First, swc runtime need to configure itself's plugin excution order before load plugin. When we load plugin / its config and half of the plugin already ran.. then what to do?

Also this means plugin can interfere other plugins. If other plugin want to those excution in specific order, what plugin wins? And if transformed results by prior plugin conflicts to others, what'll happen?

**Comment by kdy1** [comment]
Comments are not stripped if you apply plugin first, and your description does not match the title.
