### ISSUE TITLE
Array method toSorted was not transformed

### ISSUE THREAD

**Issue by Alan-Asl** [swc-project/swc#9750]
### Describe the bug

The toSorted method was supported by Chrome from 110. 
But I don't see swc  transform this method on playground.
![image](https://github.com/user-attachments/assets/af665ebb-ccf4-4490-8f20-b9a5c017b001)
![image](https://github.com/user-attachments/assets/84daf3d8-dbae-4126-bd84-98679a612da8)

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.9.2&code=H4sIAAAAAAAAA4uO1SvJD84vKklN0dAEABMqV1sNAAAA&config=H4sIAAAAAAAAA1WOSw6DMAxE9zlF5HUXXVVqF71BDxGlhgblJztURYi7EwKhsLNnxs8zCimhYw0POeYxL1ERI%2B17VnjwSf2yAqidYk0mJrhUt%2BPFapRlLNK0OmBDYKzOpjnjTTMc2Tq4SMh8Di5R5VuLZ7LY6ODCuy%2Fm1jkNEUs%2FvsE%2FVJ%2FtYDD8qpeJ%2BlVD%2Fz2AFLWYljagPxQcyqe8XwtTTDN6Rv7ELAEAAA%3D%3D

### Expected behavior

toSorted method being compiled.

### Version

1.9.2

**Comment by kdy1** [comment]
This is not what SWC is expected to do
